### ISSUE TITLE
Kubeadm init fails to pull images

### ISSUE THREAD

**Issue by kscarlett** [kubernetes/kubeadm#1001]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: Baremetal (4c/4t, 32GB RAM)
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04 LTS x86_64
- **Kernel** (e.g. `uname -a`): 4.15.0-23-generic
- **Others**:

## What happened?
When I was trying to install kubernetes on my newly installed server, `kubeadm init` returns the following:

```
[preflight/images] Pulling images required for setting up a Kubernetes cluster
[preflight/images] This might take a minute or two, depending on the speed of your internet connection
[preflight/images] You can also perform this action in beforehand using 'kubeadm config images pull'
[preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image [k8s.gcr.io/kube-apiserver-amd64:v1.11.1]: exit status 1
        [ERROR ImagePull]: failed to pull image [k8s.gcr.io/kube-controller-manager-amd64:v1.11.1]: exit status 1
        [ERROR ImagePull]: failed to pull image [k8s.gcr.io/kube-scheduler-amd64:v1.11.1]: exit status 1
        [ERROR ImagePull]: failed to pull image [k8s.gcr.io/kube-proxy-amd64:v1.11.1]: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

When attempting to visit the urls above, a 404 is returned.

## What you expected to happen?
A successful pull of the images.

## How to reproduce it (as minimally and precisely as possible)?
Run `kubeadm init` (on version 1.11.1 apparently)

## Anything else we need to know?

**Comment by easylei** [comment]
is there any way i can config it to pull from other docker repository.
i'm a poor guy in china. behind the GFW . no way to access k8s.gcr.io

**Comment by neolit123** [comment]
@easylei if you are using version 1.12 you can have a look at this example config:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1alpha3/doc.go#L117

imageRepository can be changed to something else.
you can pass the config using `--config=filename`

**Comment by dims** [comment]
@easylei there are some good helpful suggestions in https://github.com/kubernetes/kubernetes/issues/56038
