### ISSUE TITLE
HA and HA-etcd docs issues at `k/website`

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1007]
i browsed over the `k/website` repo in terms of kubeadm, HA and the `sig-cluster-lifecycle` labeled issues and closed some.

here are some items that need to be reviewed and fixed:
https://github.com/kubernetes/website/issues/9563
https://github.com/kubernetes/website/issues/9526
https://github.com/kubernetes/website/issues/9525
https://github.com/kubernetes/website/issues/9405

filtered list:
https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Asig%2Fcluster-lifecycle
ignore the last 3.

help-is-wanted by folks who have experience setting up HA.

@kubernetes/sig-cluster-lifecycle-bugs

**Comment by timothysc** [comment]
So long as the team has been @'d and assigned I don't think we need to double-track here.
