### ISSUE TITLE
Consider adding kubeadm util fetch-ci-image [commit]?

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#101]
I just threw together a small script for myself for testing against k8s head:
```bash
#!/bin/bash

CI_COMMIT=${CI_COMMIT:-latest}
ARCH=${ARCH:-amd64}

if [[ ${ARCH} == "amd64" ]]; then
	ARCH_EXT=""
else
	ARCH_EXT="-${ARCH}"
fi

OLD_REGISTRY=${OLD_REGISTRY:-gcr.io/google_containers}
NEW_REGISTRY=${NEW_REGISTRY:-${OLD_REGISTRY}}

if [[ ${CI_COMMIT} == "latest" ]]; then
	CI_COMMIT=$(curl -sSL https://storage.googleapis.com/kubernetes-release-dev/ci-cross/latest.txt)
fi

CI_COMMIT_TAG=$(echo ${CI_COMMIT} | sed "s/+/-/")

echo "Using commit: ${CI_COMMIT}"
echo "Tagging to registry: ${NEW_REGISTRY}"

images=(
	kube-apiserver
	kube-scheduler
	kube-controller-manager
	kube-proxy
)

for image in ${images[@]}; do
	curl -sSL https://storage.googleapis.com/kubernetes-release-dev/ci-cross/${CI_COMMIT}/bin/linux/${ARCH}/${image}.tar | docker load
	image_tag=$(curl -sSL https://storage.googleapis.com/kubernetes-release-dev/ci-cross/${CI_COMMIT}/bin/linux/${ARCH}/${image}.md5)
	docker tag ${OLD_REGISTRY}/${image}${ARCH_EXT}:${image_tag} ${NEW_REGISTRY}/${image}-${ARCH}:${CI_COMMIT_TAG}
	docker rmi ${OLD_REGISTRY}/${image}${ARCH_EXT}:${image_tag}
	echo "Image created: ${NEW_REGISTRY}/${image}-${ARCH}:${CI_COMMIT_TAG}"
done

cat <<EOF
Now you can run:
	kubeadm init --use-kubernetes-version ${CI_COMMIT_TAG}
EOF
```

Should we provide this functionality through a `kubeadm util` command or it is out of scope?
This is a discussion thread.

On the other hand, this could be fixed with making the CI automatically push the images it's building to `gcr.io/kubernetes-release-dev` or something and make kubeadm understand `--use-kubernetes-version ci/latest` for example. What are you in favor of?
Quite many users have asked for this, so bringing it up here

@jbeda @mikedanese @roberthbailey @errordeveloper @lukemarsden @dgoodwin

**Comment by kad** [comment]
I'd rather bring back support of ci/* from initial versions of --use-kubernetes-version, but that require pushing images to registry (and hopefully PR images too).

**Comment by mikedanese** [comment]
This would be very useful for e2e testing but I somewhat agree with @kad, tighter integration with --version would be nice. @pipejakob

**Comment by luxas** [comment]
Basically, we only have to start pushing CI images to the `gcr.io/kubernetes-release-dev` repository for example.

ref: https://github.com/kubernetes/test-infra/issues/1400

**Comment by luxas** [comment]
cc @ixdy @spxtr

**Comment by luxas** [comment]
(I do think the pushing the images automatically and having version support those images OOTB is a much better solution, just posted the alternative here)

**Comment by mikedanese** [comment]
That also works.

**Comment by jbeda** [comment]
See also https://github.com/kubernetes/kubeadm/issues/34.

**Comment by luxas** [comment]
Closing in favor for https://github.com/kubernetes/kubeadm/issues/238 which will be the real solution
