### ISSUE TITLE
kubeadm should warn about missing podSubnet/clusterCIDR

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#1011]
# BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04 LTS
- **Kernel** (e.g. `uname -a`):
Linux srv-jlhyq 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

Without a pod subnet specified, or a specific clusterCIDR specified you get: 

```
W0720 13:06:36.713799       1 proxier.go:311] clusterCIDR not specified, unable to distinguish between internal and external traffic
```

from kube-proxy and masquerade facilities will be affected

## What you expected to happen?

The clusterCIDR should be given to kube-proxy, or a warning issued during init

Given the number of CNI plugins that require a subnet specification there should be at least a warning from kubeadm about the impact of failing to tell the system what addresses the pods will be using. 

## How to reproduce it (as minimally and precisely as possible)?

kubeadm init without a podSubnet

## Anything else we need to know?

There appears to be a bit of a battle going on between the top down allocation of system's addresses and the bottom up discovery of the system's addresses, with bits of each leaking into the instructions. Perhaps a pre-flight check is required to ensure consistency.

**Comment by stealthybox** [comment]
I agree this check is necessary.
It's very easy to produce unworkable configurations.

**Comment by xlgao-zju** [comment]
/assign
I'd like to take this issue. We just print a warning when the podSubnet/serviceSubnet is missing?

**Comment by stealthybox** [comment]
bump @xlgao-zju -- are you still working on this? :)
cheers!

**Comment by xlgao-zju** [comment]
@stealthybox Sorry for the delay. I had some personal stuff... I will fix this issue ASAP.
And as I asked should we just print a warning or fail the init, when the podSubnet/serviceSubnet is missing? WDYT?
cc @neolit123

**Comment by neolit123** [comment]
@xlgao-zju 
i haven't looked at this. possibly @NeilW or @stealthybox can provide the right details required by the `good first issue` label.

**Comment by NeilW** [comment]
Given it produces unworkable configs, I would fail the init if it is not specified.

**Comment by stealthybox** [comment]
commented on PR:https://github.com/kubernetes/kubernetes/pull/68682#issuecomment-422102727

**Comment by NeilW** [comment]
I don't I'm afraid. I've only used this on the 1.11 cycle

**Comment by rosti** [comment]
I think, that this issue and the possible solutions to it should be discussed at some of the next kubeadm office hours meetings.

**Comment by ericsgagnon** [comment]
still an issue on v1.13. Upgrading from v1.12 to v1.13 using the kubeadm upgrade guide wiped my pod subnet and restarted all my pods in a cidr outside my weave subnet in an internal subnet with collisions.

**Comment by rajibmitra** [comment]
I would like to work on this if its still pending , please let me know.

**Comment by neolit123** [comment]
@rajibmitra this PR was already sent, but we didn't decide on how to handle this check properly:
https://github.com/kubernetes/kubernetes/pull/68682

**Comment by astrieanna** [comment]
/remove-help

because the way to handle the check still hasn't been decided (or hasn't been documented on this issue).

**Comment by timothysc** [comment]
@astrieanna - unless you are actively engaging with the subproject on helping to triage the backlog with that team I'm going to politely ask you to stop.  Contribex are guidelines, not policy.  `help wanted` is used to indicate to external contributors that we are not actively working on it, and if they are interested they may need to investigate to find an optimal path and work with the team.

**Comment by neolit123** [comment]
> The clusterCIDR should be given to kube-proxy, or a warning issued during init

> Given the number of CNI plugins that require a subnet specification there should be at least a warning from kubeadm about the impact of failing to tell the system what addresses the pods will be using.

we actually closed the only attempt to add a warning for this as the implementation was not very clean and there was no consensus.

overall an explicit podSubnet is not mandatory for CNI as a whole, but some plugins just require it.

if a plugin requires it, it is outlined both in ours and their docs, thus it becomes an operator mistake if the CIDR is not passed.

given the CNI plugin step is outside of kubeadm, a warning about not having a podSubnet value different from the default is not something we want to show.

i'm going to close this ticket as part of triage but also would like to note that i have not seen any recent `triage/support` reports where users miss passing the CNI required CIDR.
