### ISSUE TITLE
Authorization error with multiple masters

### ISSUE THREAD

**Issue by bladerunner512** [kubernetes/kubeadm#1013]
## What keywords did you search in kubeadm issues before filing this one?
x509: cannot validate certificate

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.10.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.10.0
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux master001 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
Authorization error between apiserver and proxy/dns/controller components

## What you expected to happen?
No auth errors

## How to reproduce it (as minimally and precisely as possible)?
1. use kubeadm init to create first master node
2. copy /etc/kubernetes/pki file to second master node
3. use kubeadm init to create second master node

## Anything else we need to know?
ETCD healthy and running on separate cluster with ngnix running on master nodes:
user001@master001:~$ sudo etcdctl --endpoints http://127.0.0.1:4242 cluster-health
member 7af39e5a6b14eba is healthy: got healthy result from http://xx.xxx.xxx.178:2379
member 2c25f5d70d54500f is healthy: got healthy result from http://xx.xxx.xxx177:2379
member 69cfa803a1aaaf9b is healthy: got healthy result from http://xx.xxx.xxx.176:2379
cluster is healthy

user001@master001:~$ kubectl -n kube-system get nodes
NAME        STATUS     ROLES     AGE       VERSION
master001   NotReady   master    9m        v1.10.0
master002   NotReady   master    9m        v1.10.0

user001@master001:~$ kubectl -n kube-system get pods
NAME                                READY     STATUS    RESTARTS   AGE
kube-apiserver-master001                   1/1       Running   0          9m
kube-apiserver-master002                   1/1       Running   0          9m
kube-controller-manager-master001   1/1       Running   0          9m
kube-controller-manager-master002   1/1       Running   0          9m
kube-dns-86f4d74b45-c7sld                0/3       Pending   0          8m
kube-proxy-8tdbc                                 1/1       Running   0          8m
kube-proxy-9nbrh                                 1/1       Running   0          8m
kube-scheduler-master001                   1/1       Running   0          9m
kube-scheduler-master002                   1/1       Running   0          9m

user001@master001:~$ kubectl -n kube-system logs kube-apiserver-master001
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
I0720 19:53:32.101778       1 server.go:135] Version: v1.10.0
I0720 19:53:32.101924       1 server.go:679] external host was not specified, using xx.xxx.xxx.171
I0720 19:53:32.934471       1 plugins.go:149] Loaded 9 admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota.
I0720 19:53:32.939333       1 master.go:228] Using reconciler: master-count
W0720 19:53:33.001210       1 genericapiserver.go:342] Skipping API batch/v2alpha1 because it has no resources.
W0720 19:53:33.011977       1 genericapiserver.go:342] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W0720 19:53:33.013233       1 genericapiserver.go:342] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
W0720 19:53:33.022927       1 genericapiserver.go:342] Skipping API admissionregistration.k8s.io/v1alpha1 because it has no resources.
[restful] 2018/07/20 19:53:33 log.go:33: [restful/swagger] listing is available at https://xx.xxx.xxx.171:6443/swaggerapi
[restful] 2018/07/20 19:53:33 log.go:33: [restful/swagger] https://xx.xxx.xxx.171:6443/swaggerui/ is mapped to folder /swagger-ui/
[restful] 2018/07/20 19:53:34 log.go:33: [restful/swagger] listing is available at https://xx.xxx.xxx.171:6443/swaggerapi
[restful] 2018/07/20 19:53:34 log.go:33: [restful/swagger] https://xx.xxx.xxx.171:6443/swaggerui/ is mapped to folder /swagger-ui/
I0720 19:53:37.974837       1 serve.go:96] Serving securely on [::]:6443
I0720 19:53:37.974903       1 available_controller.go:262] Starting AvailableConditionController
I0720 19:53:37.974912       1 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
I0720 19:53:37.974936       1 apiservice_controller.go:90] Starting APIServiceRegistrationController
I0720 19:53:37.974945       1 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I0720 19:53:37.974970       1 crdregistration_controller.go:110] Starting crd-autoregister controller
I0720 19:53:37.974981       1 controller.go:84] Starting OpenAPI AggregationController
I0720 19:53:37.974992       1 controller_utils.go:1019] Waiting for caches to sync for crd-autoregister controller
I0720 19:53:37.975154       1 customresource_discovery_controller.go:174] Starting DiscoveryController
I0720 19:53:37.975285       1 crd_finalizer.go:242] Starting CRDFinalizer
I0720 19:53:37.975357       1 naming_controller.go:276] Starting NamingConditionController
I0720 19:53:38.075060       1 cache.go:39] Caches are synced for AvailableConditionController controller
I0720 19:53:38.075061       1 controller_utils.go:1026] Caches are synced for crd-autoregister controller
I0720 19:53:38.075069       1 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I0720 19:53:38.075225       1 autoregister_controller.go:136] Starting autoregister controller
I0720 19:53:38.075239       1 cache.go:32] Waiting for caches to sync for autoregister controller
I0720 19:53:38.175343       1 cache.go:39] Caches are synced for autoregister controller
I0720 19:53:39.942303       1 controller.go:537] quota admission added evaluator for: {rbac.authorization.k8s.io roles}
I0720 19:53:39.948796       1 controller.go:537] quota admission added evaluator for: {rbac.authorization.k8s.io rolebindings}
I0720 19:53:39.955597       1 controller.go:537] quota admission added evaluator for: { serviceaccounts}
I0720 19:53:40.006298       1 controller.go:537] quota admission added evaluator for: {apps deployments}
I0720 19:53:40.297715       1 controller.go:537] quota admission added evaluator for: {apps daemonsets}
I0720 19:53:56.552985       1 controller.go:537] quota admission added evaluator for: { endpoints}
I0720 19:54:14.916615       1 controller.go:537] quota admission added evaluator for: {extensions replicasets}
I0720 19:54:15.216454       1 controller.go:537] quota admission added evaluator for: {apps controllerrevisions}
E0720 19:54:15.935606       1 authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, square/go-jose: error in cryptographic primitive]]

user001@master002:~$ kubectl -n kube-system logs kube-controller-manager-master001
I0720 19:53:32.097345       1 controllermanager.go:116] Version: v1.10.0
W0720 19:53:32.098167       1 authentication.go:55] Authentication is disabled
I0720 19:53:32.098183       1 insecure_serving.go:44] Serving insecurely on 127.0.0.1:10252
I0720 19:53:32.098598       1 leaderelection.go:175] attempting to acquire leader lease  kube-system/kube-controller-manager...
E0720 19:53:32.099047       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: Get https://xx.xxx.xxx.171:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager: dial tcp xx.xxx.xxx.171:6443: getsockopt: connection refused
E0720 19:53:38.002878       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system"
I0720 19:53:57.573452       1 leaderelection.go:184] successfully acquired lease kube-system/kube-controller-manager
I0720 19:53:57.573577       1 event.go:218] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"e37eea51-8b8d-11e8-88e0-00530c004695", APIVersion:"v1", ResourceVersion:"18566", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' master001_947b50c4-8c56-11e8-89da-00530c0067fa became leader
.
.
.
I0720 19:54:15.224599       1 event.go:218] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"kube-proxy", UID:"e3e89a1d-8b8d-11e8-943d-00530c0067fa", APIVersion:"apps", ResourceVersion:"18535", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: kube-proxy-w4292
E0720 19:54:15.238887       1 daemon_controller.go:266] kube-system/kube-proxy failed with : error storing status for daemon set &v1.DaemonSet{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-proxy", GenerateName:"", Namespace:"kube-system", SelfLink:"/apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy", UID:"e3e89a1d-8b8d-11e8-943d-00530c0067fa", ResourceVersion:"18535

user001@master002:~$ kubectl -n kube-system logs kube-controller-manager-master002
I0720 20:04:22.059251       1 controllermanager.go:116] Version: v1.10.0
W0720 20:04:22.060156       1 authentication.go:55] Authentication is disabled
I0720 20:04:22.060170       1 insecure_serving.go:44] Serving insecurely on 127.0.0.1:10252
I0720 20:04:22.060476       1 leaderelection.go:175] attempting to acquire leader lease  kube-system/kube-controller-manager...
E0720 20:04:27.822914       1 leaderelection.go:224] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get endpoints in the namespace "kube-system": [clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "system:kube-controller-manager" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found]

user001@master002:~$ kubectl -n kube-system logs kube-dns-86f4d74b45-fr8vs kubedns
I0720 21:10:07.563265       1 dns.go:48] version: 1.14.8
I0720 21:10:07.564022       1 server.go:71] Using configuration read from directory: /kube-dns-config with period 10s
I0720 21:10:07.564064       1 server.go:119] FLAG: --alsologtostderr="false"
I0720 21:10:07.564074       1 server.go:119] FLAG: --config-dir="/kube-dns-config"
I0720 21:10:07.564081       1 server.go:119] FLAG: --config-map=""
I0720 21:10:07.564084       1 server.go:119] FLAG: --config-map-namespace="kube-system"
I0720 21:10:07.564088       1 server.go:119] FLAG: --config-period="10s"
I0720 21:10:07.564094       1 server.go:119] FLAG: --dns-bind-address="0.0.0.0"
I0720 21:10:07.564097       1 server.go:119] FLAG: --dns-port="10053"
I0720 21:10:07.564102       1 server.go:119] FLAG: --domain="cluster.local."
I0720 21:10:07.564106       1 server.go:119] FLAG: --federations=""
I0720 21:10:07.564113       1 server.go:119] FLAG: --healthz-port="8081"
I0720 21:10:07.564116       1 server.go:119] FLAG: --initial-sync-timeout="1m0s"
I0720 21:10:07.564120       1 server.go:119] FLAG: --kube-master-url=""
I0720 21:10:07.564124       1 server.go:119] FLAG: --kubecfg-file=""
I0720 21:10:07.564137       1 server.go:119] FLAG: --log-backtrace-at=":0"
I0720 21:10:07.564143       1 server.go:119] FLAG: --log-dir=""
I0720 21:10:07.564147       1 server.go:119] FLAG: --log-flush-frequency="5s"
I0720 21:10:07.564150       1 server.go:119] FLAG: --logtostderr="true"
I0720 21:10:07.564155       1 server.go:119] FLAG: --nameservers=""
I0720 21:10:07.564158       1 server.go:119] FLAG: --stderrthreshold="2"
I0720 21:10:07.564161       1 server.go:119] FLAG: --v="2"
I0720 21:10:07.564164       1 server.go:119] FLAG: --version="false"
I0720 21:10:07.564172       1 server.go:119] FLAG: --vmodule=""
I0720 21:10:07.564244       1 server.go:201] Starting SkyDNS server (0.0.0.0:10053)
I0720 21:10:07.564469       1 server.go:220] Skydns metrics enabled (/metrics:10055)
I0720 21:10:07.564488       1 dns.go:146] Starting endpointsController
I0720 21:10:07.564492       1 dns.go:149] Starting serviceController
I0720 21:10:07.564583       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0720 21:10:07.564598       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
E0720 21:10:07.886138       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: x509: cannot validate certificate for 10.96.0.1 because it doesn't contain any IP SANs

user001@master002:~$ kubectl -n kube-system logs kube-scheduler-master001
W0720 19:53:32.096351       1 server.go:163] WARNING: all flags other than --config are deprecated. Please begin using a config file ASAP.
I0720 19:53:32.102210       1 server.go:555] Version: v1.10.0
I0720 19:53:32.102580       1 server.go:574] starting healthz server on 127.0.0.1:10251
E0720 19:53:38.005715       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:kube-scheduler" cannot list poddisruptionbudgets.policy at the cluster scope
E0720 19:53:38.005835       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Node: nodes is forbidden: User "system:kube-scheduler" cannot list nodes at the cluster scope

user001@master002:~$ kubectl -n kube-system logs kube-scheduler-master002
W0720 20:04:22.045114       1 server.go:163] WARNING: all flags other than --config are deprecated. Please begin using a config file ASAP.
I0720 20:04:22.051020       1 server.go:555] Version: v1.10.0
I0720 20:04:22.053647       1 server.go:574] starting healthz server on 127.0.0.1:10251
E0720 20:04:27.826200       1 reflector.go:205] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:594: Failed to list *v1.Pod: pods is forbidden: User "system:kube-scheduler" cannot list pods at the cluster scope: [clusterrole.rbac.authorization.k8s.io "system:volume-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:kube-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found, clusterrole.rbac.authorization.k8s.io "system:basic-user" not found]
E0720 20:04:27.826267       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.ReplicaSet: replicasets.extensions is forbidden: User "system:kube-scheduler" cannot list replicasets.extensions at the cluster scope: [clusterrole.rbac.authorization.k8s.io "system:kube-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found, clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "system:volume-scheduler" not found]
E0720 20:04:27.826318       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list storageclasses.storage.k8s.io at the cluster scope: [clusterrole.rbac.authorization.k8s.io "system:discovery" not found, clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "system:volume-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:kube-scheduler" not found]
E0720 20:04:27.826384       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.ReplicationController: replicationcontrollers is forbidden: User "system:kube-scheduler" cannot list replicationcontrollers at the cluster scope: [clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "system:volume-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:kube-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found]
E0720 20:04:27.827139       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.StatefulSet: statefulsets.apps is forbidden: User "system:kube-scheduler" cannot list statefulsets.apps at the cluster scope: [clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "system:volume-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:kube-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found]
E0720 20:04:27.827235       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Node: nodes is forbidden: User "system:kube-scheduler" cannot list nodes at the cluster scope: [clusterrole.rbac.authorization.k8s.io "system:basic-user" not found, clusterrole.rbac.authorization.k8s.io "system:volume-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:kube-scheduler" not found, clusterrole.rbac.authorization.k8s.io "system:discovery" not found]

**Comment by timothysc** [comment]
HA was never fully supported by the community and the instructions have been updated and validated for v1.11.  

We recommend exercising those instructions.
