### ISSUE TITLE
Allow overriding CoreDNS image tag in kubeadm configuration

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubeadm#1017]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## What happened?
Unable to override the CoreDNS image tag for a kubeadm installation in the kubeadm config file

## What you expected to happen?
Be able to override the CoreDNS image tag for a kubeadm installation in the kubeadm config file

## Anything else we need to know?
The CoreDNS image tag is hard-coded as a constant and referenced at https://github.com/kubernetes/kubernetes/blob/0ffee495ad173fc75c01031cd3e90798de7fb9c0/cmd/kubeadm/app/images/images.go#L85 when installing CoreDNS.

**Comment by timothysc** [comment]
@ncdc would an overall tag-suffix suffice(e.g. - .patch.0 ) for all images?  Or do we want to treat CoreDNS differently?

**Comment by ncdc** [comment]
We use a separate version for etcd. It's probably appropriate to keep CoreDNS separate as well - it's an independently versioned component. Right?

**Comment by luxas** [comment]
This is being discussed in the beta config KEP: https://docs.google.com/document/d/1Sk2VW7IKaLjrjf_4a1NEU0l7X0ysZoXq9lVBvH-ruYY/edit & #911

**Comment by chuckha** [comment]
I added some suggestions to that doc regarding a DNSPlugin type that we can use to customize the DNS plugin image.

**Comment by neolit123** [comment]
FYI this ticket is a subset of the following addon improvements tracking issue:
https://github.com/kubernetes/kubeadm/issues
(where also some discussion started happening)

please re-open if closing this seems out of order.
/close

**Comment by ncdc** [comment]
@neolit123 which issue are you referring to - #1091?

**Comment by neolit123** [comment]
@ncdc 
copy-paste error, sorry.
yes, that one.
