### ISSUE TITLE
Offline install with kubeadm v1.11 fails

### ISSUE THREAD

**Issue by bladerunner512** [kubernetes/kubeadm#1019]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions
v1.11.0

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
v1.11.0
- **OS** (e.g. from /etc/os-release): 
Ubuntu 16.04
- **Kernel** (e.g. `uname -a`):
Linux  4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
                        - No internet connection is available so the kubelet cannot pull or find the following control plane images:
                                - k8s.gcr.io/kube-apiserver-amd64:v1.11.0
                                - k8s.gcr.io/kube-controller-manager-amd64:v1.11.0
                                - k8s.gcr.io/kube-scheduler-amd64:v1.11.0
                                - k8s.gcr.io/etcd-amd64:3.2.18

## What you expected to happen?
All required images are local so init should succeed. 
Also added DNS images not listed in error msg:
                                - k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.10
                                - k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.10
                                - k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.10
                                - k8s.gcr.io/coredns:1.1.3
                                - k8s.gcr.io/pause:3.1

## How to reproduce it (as minimally and precisely as possible)?
$ kubeadm init --kubernetes-version v1.11.0 --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=xx.xxx.xxx.171

**Comment by neolit123** [comment]
can you show the list of images on your system?

**Comment by bladerunner512** [comment]
$ docker images
REPOSITORY                                         TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-apiserver-amd64                    v1.11.0             214c48e87f58        3 weeks ago         187 MB
k8s.gcr.io/kube-controller-manager-amd64           v1.11.0             55b70b420785        3 weeks ago         155 MB
k8s.gcr.io/kube-proxy-amd64                        v1.11.0             1d3d7afd77d1        3 weeks ago         97.8 MB
k8s.gcr.io/kube-scheduler-amd64                    v1.11.0             0e4a34a3b0e6        3 weeks ago         56.8 MB
k8s.gcr.io/coredns                                 1.1.3               b3b94275d97c        2 months ago        45.6 MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64             1.14.10             6816817d9dce        3 months ago        40.4 MB
k8s.gcr.io/k8s-dns-kube-dns-amd64                  1.14.10             55ffe31ac578        3 months ago        49.5 MB
k8s.gcr.io/k8s-dns-sidecar-amd64                   1.14.10             8a7739f672b4        3 months ago        41.6 MB
k8s.gcr.io/etcd-amd64                              3.2.18              b8df3b177be2        3 months ago        219 MB
k8s.gcr.io/kubernetes-dashboard-amd64              v1.8.3              0c60bcf89900        5 months ago        102 MB
k8s.gcr.io/pause                                   3.1                 da86e6ba6ca1        7 months ago        742 kB

**Comment by neolit123** [comment]
hm, the images seem valid.

/cc @chuckha 
/help

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by dixudx** [comment]
@bladerunner512 Can you help check your `kubelet`.

Since the whole error message should be,

```
This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
 	- No internet connection is available so the kubelet cannot pull or find the following control plane images:
            - k8s.gcr.io/kube-apiserver-amd64:v1.11.0
            - k8s.gcr.io/kube-controller-manager-amd64:v1.11.0
            - k8s.gcr.io/kube-scheduler-amd64:v1.11.0
            - k8s.gcr.io/etcd-amd64:3.2.18
```

Actually the images have already been cached locally already as we have pulled them using crictl in the preflight checks. Hence we can have a pretty short timeout for the kubelet to start creating Static Pods. The message here is a little bit misleading.

**Comment by bart0sh** [comment]
@bladerunner512 Can you show full error message starting from "Unfortunately, an error has occurred:" line?

**Comment by bart0sh** [comment]
@bladerunner512 following instructions given in the error message would help too:
```
If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
    'systemctl status kubelet'
    'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
     'docker ps -a | grep kube | grep -v pause'
Once you have found the failing container, you can inspect its logs with:
      'docker logs CONTAINERID'
```

**Comment by bladerunner512** [comment]
Didn't list the full error for brevity, but did check the kubelet which is not returning errors. Also got no images back from 'docker ps -a'. v1.10 installed ok on the same node, moved to v1.11 to get support for HA masters with kubeadm. Installation is the same as v1.10 with the exception of updating the local images listed previously.

$ docker ps -a
no images are found

user001@master001:~$ sudo systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-07-26 10:12:02 EDT; 4min 0s ago
     Docs: http://kubernetes.io/docs/
 Main PID: 32517 (kubelet)
    Tasks: 40
   Memory: 34.7M
      CPU: 4.379s
   CGroup: /system.slice/kubelet.service
           └─32517 /usr/bin/kubelet

Jul 26 10:14:23 master001 kubelet[32517]: I0726 10:14:23.609910   32517 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach



user001@master001:~$ sudo journalctl -xeu kubelet
--
-- Unit kubelet.service has finished starting up.
--
-- The start-up result is done.
Jul 26 10:12:02 master001 kubelet[32517]: I0726 10:12:02.946313   32517 feature_gate.go:230] feature gates: &{map[]}
Jul 26 10:12:02 master001 kubelet[32517]: I0726 10:12:02.946442   32517 feature_gate.go:230] feature gates: &{map[]}
Jul 26 10:12:02 master001 kubelet[32517]: I0726 10:12:02.967606   32517 server.go:408] Version: v1.11.0
Jul 26 10:12:02 master001 kubelet[32517]: I0726 10:12:02.967692   32517 feature_gate.go:230] feature gates: &{map[]}
Jul 26 10:12:02 master001 kubelet[32517]: I0726 10:12:02.967745   32517 feature_gate.go:230] feature gates: &{map[]}
Jul 26 10:12:02 master001 kubelet[32517]: I0726 10:12:02.967856   32517 plugins.go:97] No cloud provider specified.
Jul 26 10:12:02 master001 kubelet[32517]: W0726 10:12:02.967903   32517 server.go:549] standalone mode, no API client
Jul 26 10:12:03 master001 kubelet[32517]: W0726 10:12:03.003963   32517 server.go:465] No api server defined - no events will be sent to API server.
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.003984   32517 server.go:648] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.004243   32517 container_manager_linux.go:243] container manager verified user specified cgroup-root exists: []
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.004257   32517 container_manager_linux.go:248] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: K
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.004350   32517 container_manager_linux.go:267] Creating device plugin manager: true
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.004373   32517 state_mem.go:36] [cpumanager] initializing new in-memory state store
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.004414   32517 state_mem.go:84] [cpumanager] updated default cpuset: ""
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.004425   32517 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.007131   32517 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.007160   32517 client.go:104] Start docker client with request timeout=2m0s
Jul 26 10:12:03 master001 kubelet[32517]: W0726 10:12:03.008310   32517 docker_service.go:545] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.008552   32517 docker_service.go:238] Hairpin mode set to "hairpin-veth"
Jul 26 10:12:03 master001 kubelet[32517]: W0726 10:12:03.008911   32517 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Jul 26 10:12:03 master001 kubelet[32517]: W0726 10:12:03.010990   32517 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.012020   32517 docker_service.go:253] Docker cri networking managed by kubernetes.io/no-op
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.024696   32517 docker_service.go:258] Docker Info: &{ID:OT2U:XW5F:3ICP:42KH:YZWI:O7QS:H3SD:6S4H:2LFS:FCNR:BY2K:67ZT Containers:0 ContainersRunni
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.024781   32517 docker_service.go:271] Setting cgroupDriver to cgroupfs
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.042179   32517 kuberuntime_manager.go:186] Container runtime docker initialized, version: 17.03.2-ce, apiVersion: 1.27.0
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.042862   32517 csi_plugin.go:111] kubernetes.io/csi: plugin initializing...
Jul 26 10:12:03 master001 kubelet[32517]: W0726 10:12:03.044571   32517 kubelet.go:1361] No api server defined - no node status update will be sent.
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.044750   32517 server.go:129] Starting to listen on 0.0.0.0:10250
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.044771   32517 server.go:986] Started kubelet
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.045952   32517 fs_resource_analyzer.go:66] Starting FS ResourceAnalyzer
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.046007   32517 status_manager.go:148] Kubernetes client is nil, not starting status manager.
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.046023   32517 kubelet.go:1760] Starting kubelet main sync loop.
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.046044   32517 kubelet.go:1777] skipping pod synchronization - [container runtime is down PLEG is not healthy: pleg was last seen active 2562047
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.045962   32517 server.go:302] Adding debug handlers to kubelet server.
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.046557   32517 volume_manager.go:247] Starting Kubelet Volume Manager
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.046598   32517 desired_state_of_world_populator.go:130] Desired state populator starts to run
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.146149   32517 kubelet.go:1777] skipping pod synchronization - [container runtime is down]
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.146745   32517 reconciler.go:154] Reconciler: start to sync state
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.211252   32517 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.213221   32517 cpu_manager.go:155] [cpumanager] starting with none policy
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.213235   32517 cpu_manager.go:156] [cpumanager] reconciling every 10s
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.213245   32517 policy_none.go:42] [cpumanager] none policy: Start
Jul 26 10:12:03 master001 kubelet[32517]: Starting Device Plugin manager
Jul 26 10:12:03 master001 kubelet[32517]: W0726 10:12:03.213987   32517 manager.go:496] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
Jul 26 10:12:03 master001 kubelet[32517]: I0726 10:12:03.214166   32517 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach

**Comment by bladerunner512** [comment]
FYI, noticed warning in init output:
        [WARNING ImagePull]: failed to pull image [k8s.gcr.io/pause-amd64:3.1]: exit status 1
I believe in previous releases this image didn't include 'amd64', i.e. 'k8s.gcr.io/pause:3.1'
Including the image didn't have any effect on this issue though.

**Comment by bart0sh** [comment]
@bladerunner512 
> I believe in previous releases this image didn't include 'amd64', i.e. 'k8s.gcr.io/pause:3.1'

This is probably caused by [this issue](https://github.com/kubernetes/kubeadm/issues/962) and already fixed by [this PR](https://github.com/kubernetes/kubernetes/pull/65920) in master and [cherry picked](https://github.com/kubernetes/kubernetes/pull/65923) into 1.11 branch.

Can you try if the fix works for you?

**Comment by bart0sh** [comment]
@timothysc This issue can be closed I think.

**Comment by neolit123** [comment]
@bart0sh 
reference code changes / PR?

**Comment by neolit123** [comment]
edit, looks like it:
https://github.com/kubernetes/kubernetes/pull/66658

thanks for the reminder.
/close
