### ISSUE TITLE
Kubeadm not using etcd local extraArgs defined in config file

### ISSUE THREAD

**Issue by danbeaulieu** [kubernetes/kubeadm#1022]
## Is this a request for help?

No 

## What keywords did you search in kubeadm issues before filing this one?

etcd, extraArgs, initial-cluster

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

```# kubeadm version kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:50:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}```

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: EC2 instance
- **OS** (e.g. from /etc/os-release): VERSION="16.04.5 LTS (Xenial Xerus)"
- **Kernel** (e.g. `uname -a`): Linux ip-10-97-0-251 4.4.0-1063-aws #72-Ubuntu SMP Fri Jul 13 07:23:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
I am following this guide for stacked HA control plane nodes: https://kubernetes.io/docs/setup/independent/high-availability/#stacked-control-plane-nodes
Things are wrong after the first node is complete. Everything looks ok from the outside, ie etcd is running, it looks happy, nodes are listed via kubectl etc.
However if we look at the etcd.yaml static pod def we can see that it did not use any of the etcd.local.extraArgs values defined in the kubeadm.conf file. Adding the second node results in errors since they are now both only listening on 127.0.0.1 instead of the other interface defined in etcd local extraArgs as outlined in the guide.

## What you expected to happen?
Added multiple control plane nodes does not result in cluster failure

## How to reproduce it (as minimally and precisely as possible)?
Follow the guide

## Anything else we need to know?
I am pretty sure I had this working a few weeks ago.  I verified the kubeadm.conf file is being read properly because I can see other overrides for other components in the files kubeadm writes out ie /var/lib/kubelet/config.yaml.

It does appear kubeadm makes an attempt to use the overrides but something is failing either before or after I suppose: https://github.com/kubernetes/kubernetes/blob/32dc6cc08aa0349d44aa3109f0a718cbb51fb101/cmd/kubeadm/app/phases/etcd/local.go#L99

**Comment by neolit123** [comment]
can you share your kubeadm config, please?
make sure that you REMOVE any sensitive data.

**Comment by danbeaulieu** [comment]
@neolit123 thanks for the hint. My config file specified apiVersion kubeadm.k8s.io/v1alpha1 instead of apiVersion: kubeadm.k8s.io/v1alpha2. Nice reminder that those things mean something.
