### ISSUE TITLE
kubeadm manifests should use multi-arch images

### ISSUE THREAD

**Issue by dims** [kubernetes/kubeadm#1030]
Just like we started using the `pause` image with fat manifest, we should switch to using all the kubernetes components to use images without say the `-amd64` in their name. Starting with the items below:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/images/images.go#L70-L73

TODO(@neolit123): this page needs a bump, possibly others too:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

**Comment by neolit123** [comment]
these end up calling `GetGenericArchImage()` which was a recent addition and it uses `runtime.GOARCH`.
we do have manifest lists nowadays in the gcr bucket, but do we have them for everything?

@rosti WDYT?

**Comment by rosti** [comment]
I'll prepare a PR for this tomorrow.

**Comment by dims** [comment]
@neolit123 if we find something missing then we fix it :)

**Comment by neolit123** [comment]
/kind documentation

this needs an update:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

**Comment by luxas** [comment]
Closing this in favor for the oldest open issue we have atm: #51 _sigh_
Sooooon we're there :sunglasses: :tada:
