### ISSUE TITLE
unable to generate certificates offline

### ISSUE THREAD

**Issue by bladerunner512** [kubernetes/kubeadm#1032]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04
- **Kernel** (e.g. `uname -a`):
Linux 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
$ sudo kubeadm alpha phase certs etcd-ca
unable to get URL "https://dl.k8s.io/release/stable-1.11.txt": Get https://dl.k8s.io/release/stable-1.11.txt: dial tcp 23.236.58.218:443: connect: connection refused

## What you expected to happen?
Certificates should be created without the need to access Internet

## How to reproduce it (as minimally and precisely as possible)?
1. install kubeadm
2. generate certificate:
$ sudo kubeadm alpha phase certs etcd-ca

## Anything else we need to know?
Generating the initial certs is not an issue since it can be done anywhere, but after that the other certs generated appear to have DNS/IP of local machine not etcd node where certs are used:

$ kubeadm alpha phase certs etcd-peer --config=kubeadmcfg.yaml
I0801 18:00:17.873841    8047 feature_gate.go:230] feature gates: &{map[]}
[certificates] Generated etcd/peer certificate and key.
[certificates] etcd/peer serving cert is signed for DNS names [ubuntu localhost] and IPs [192.168.113.140 127.0.0.1 ::1]

Is "localhost/127.0.0.1 ::1" all that is required - kubeadmcfg.yaml has etcd node IP that is not included in cert?

**Comment by neolit123** [comment]
> $ sudo kubeadm alpha phase certs etcd-ca
unable to get URL "https://dl.k8s.io/release/stable-1.11.txt": Get https://dl.k8s.io/release/stable-1.11.txt: dial tcp 23.236.58.218:443: connect: connection refused

it goes for the latest 1.11.x release.
can you try bypassing that by using:
```
sudo kubeadm alpha phase certs etcd-ca --kubernetes-version=1.11.0
```

> but after that the other certs generated appear to have DNS/IP of local machine not etcd node where certs are used
> kubeadm alpha phase certs etcd-peer --config=kubeadmcfg.yaml

i think this is a problem, yes. the x509 SAN has to include public DNS and IP that works for this cert, unless i'm missing something in the etcd peer context here.
please share that yaml as well. hide sensitive data if you have any.

/cc @kubernetes/sig-cluster-lifecycle-bugs

**Comment by bladerunner512** [comment]
$ sudo kubeadm alpha phase certs etcd-ca --kubernetes-version=1.11.0
Error: unknown flag: --kubernetes-version

I was able to get this to work by creating a config file with the version number though:
apiVersion: kubeadm.k8s.io/v1alpha2
kubernetesVersion: v1.11.0

$ sudo kubeadm alpha phase certs etcd-ca --config=/etc/kubernetes/k8s_conf.yaml
I0802 18:34:29.504078  106312 feature_gate.go:230] feature gates: &{map[]}
[certificates] Generated etcd/ca certificate and key.

I then added "kubernetesVersion: v1.11.0" to kubeadmcfg.yaml file and was able to generate etcd-server certs with correct IP:
$ sudo kubeadm alpha phase certs etcd-server --config=kubeadmcfg.yaml
I0802 18:40:34.781649  107459 feature_gate.go:230] feature gates: &{map[]}
[certificates] Generated etcd/server certificate and key.
[certificates] etcd/server serving cert is signed for DNS names [k8s-master001 localhost] and IPs [127.0.0.1 ::1]

kubeadmcfg.yaml:
apiVersion: "kubeadm.k8s.io/v1alpha2"
kind: MasterConfiguration
kubernetesVersion: v1.11.0
etcd:
    localEtcd:
        serverCertSANs:
        - "xx.xxx.xxx.176"
        peerCertSANs:
        - "xx.xxx.xxx.176"
        extraArgs:
            initial-cluster: infra0=https://xx.xxx.xxx.176:2380,infra1=https://xx.xxx.xxx.177:2380,infra2=https://xx.xxx.xxx.178:2380
            initial-cluster-state: new
            name: infra0
            listen-peer-urls: https://xx.xxx.xxx.176:2380
            listen-client-urls: https://xx.xxx.xxx.176:2379
            advertise-client-urls: https://xx.xxx.xxx.176:2379
            initial-advertise-peer-urls: https://xx.xxx.xxx.176:2380

So there does seem to be an issue generating certs on a different host, i.e. not getting IP of etcd host from yaml config (xx.xxx.xxx.176), but using IP of local machine (xxx.xxx.xxx.140):

user001@ubuntu:~$ kubeadm alpha phase certs etcd-peer --config=kubeadmcfg.yaml
I0802 17:52:04.592401   16850 feature_gate.go:230] feature gates: &{map[]}
[certificates] Generated etcd/peer certificate and key.
[certificates] etcd/peer serving cert is signed for DNS names [ubuntu localhost] and IPs [xxx.xxx.xxx.140 127.0.0.1 ::1]

**Comment by neolit123** [comment]
a fix for ` kubeadm alpha phase` is in:
https://github.com/kubernetes/kubernetes/pull/62721

**Comment by chuckha** [comment]
Closing, the PR is merged.
