### ISSUE TITLE
kubeadm should describe the [tlsbootstrap] cycle better.

### ISSUE THREAD

**Issue by mauilion** [kubernetes/kubeadm#1034]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

Currently kubeadm join will output the following on success:
```
~~ snip ~~
[preflight] Activating the kubelet service
[tlsbootstrap] Waiting for the kubelet to perform the TLS Bootstrap...
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "worker-01.v.k8s.work" as an annotation

This node has joined the cluster:
* Certificate signing request was sent to master and a response
  was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the master to see this node join the cluster.
```
In the case where the `kube-controller-manager` will still happily start up if it can not access the 
`    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key`

When this happens we see this as the failure output of kubeadm join ...:

```
~~ snip ~~
[preflight] Activating the kubelet service
[tlsbootstrap] Waiting for the kubelet to perform the TLS Bootstrap...
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'
timed out waiting for the condition
```

This turned out to be a fault in the way the master was provisioned. The Operator had removed the `/etc/kubernetes/pki/ca.key` from the filesystem prior to running `kubeadm init` This clearly broke the TLS bootstrap process at the `kube-controller-manager` was unable to issue certificates.

It was pretty hard to chase down from the error described above. 

The feature enhancement I'd like to see is to have kubeadm be explicit about each step in the bootstrap tls process. i.e:
Successful result:
```
[tlsbootstrap] Waiting for the kubelet to perform the TLS Bootstrap...
[tlsbootstrap] Generated private key and csr for node [nodename]
[tlsbootstrap] Certificate Signing Request posted at node-csr-S-rrX8YXIHC6v1WjsR1ZyrtwBqBehpmdRtrTirvWU_Y
[tlsbootstrap] CSR approved.
[tlsbootstrap] Certificate issued.
[tlsbootstrap] Certificate retrieved and populated on disk at /etc/kubernetes/kubelet.conf
```
Unsuccessful result:
```
[tlsbootstrap] Waiting for the kubelet to perform the TLS Bootstrap...
[tlsbootstrap] Generated private key and csr for node [nodename]
[tlsbootstrap] Certificate Signing Request posted at node-csr-S-rrX8YXIHC6v1WjsR1ZyrtwBqBehpmdRtrTirvWU_Y
[tlsbootstrap] CSR approved.
[tlsbootstrap] Error: Certificate not issued. Is the cluster able to issue certificates?
```
## Versions

**kubeadm version** (use `kubeadm version`): 1.11.1

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
N/A
- **OS** (e.g. from /etc/os-release):
N/A
- **Kernel** (e.g. `uname -a`):
N/A
- **Others**:
N/A

**Comment by chuckha** [comment]
Regarding this issue being [discussed in slack](https://kubernetes.slack.com/archives/C13J86Z63/p1541173767169200)

One approach here might be to look at the kubelet and figure out the assumptions it makes and then do some preflight kubelet checks to make sure it can likely succeed. Unfortunately the way we've decoupled kubeadm and kubelet this style of logging is not going to be possible without some rearchitecting.

**Comment by rdodev** [comment]
@mauilion given this ^ at the moment we can't get the desired level of output requested. We could do some naive file system check, but once we pass the witness to the kubelet, it's blackbox-ish to kubeadm side. Would these naive file system checks be sufficient?

**Comment by rdodev** [comment]
Upon closer inspection, the file system checks would be in the control plane node(s), not in the would-be worker nodes and presently there's no good way to accomplish that from a remote machine.

**Comment by timothysc** [comment]
This particular issue is really thorny from a layer violation perspective.  Kubeadm can only check what it knows about and crossing those lines get's into a weird space that will force us to subsume a class of problems that I don't think we want to get into.  I think it may make more sense to have a set of control plane check that can be accessed via monitoring as part of initial bootstrap.  

If you disagree please feel free to reopen
