### ISSUE TITLE
kubeadm high-availability-Is Step to Set up master Load Balancer mandatory? 

### ISSUE THREAD

**Issue by smenon78** [kubernetes/kubeadm#1035]
Is this Step
Set up master Load Balancer Mandatory?
Following this documentation for HA cluster in k8s 1.9.5
https://v1-9.docs.kubernetes.io/docs/setup/independent/high-availability/

I am setting Kubenetes HA cluster on a baremetal setup. Could I skip the step to setup load balancer and would this still work?

**Comment by neolit123** [comment]
> I am setting Kubenetes HA cluster on a baremetal setup. Could I skip the step to setup load balancer and would this still work?

depends on your setup.
it can still work, but without load balancing, it's going to be hard to qualify this cluster as HA.

learn more here:
https://velotio.com/blog/2018/6/15/kubernetes-high-availability-kubeadm

/close
