### ISSUE TITLE
tracking issue for community work opportunities at the role-board

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1042]
WIP

Jorge Castro notified about the launch of a board, where SIGs can propose what areas they need help with community work (jobs). Maybe we can create a list of such areas.

The board would be under:
https://discuss.kubernetes.io/c/contributors/

TMK they went away from the naming "jobs" due to a controversy, so this is de facto about community work.

**google doc where SIG cluster lifecycle can add their ideas:**
https://docs.google.com/document/d/1iQ_Lola1s9_ilqbKLtZChDnbkqNt9uq1p6S1PbOkXCM/edit?usp=sharing

the role board is now open :tada: 
https://discuss.kubernetes.io/c/contributors/role-board

**Comment by chuckha** [comment]
Is that link right? I'm not sure how it's related to the previous sentence.

As a side note, last I heard we should be using the `good first issue` so folks can find easy-ish places to get started...I don't think that idea has taken off yet at all given there are 0 issues in k/k with that label.

**Comment by neolit123** [comment]
as @castrojo said on slack:
> I jumped the gun a bit (I need to give it 72 hours to get concensus in contribex) -- so I've made the subforum private for now, but if ya'll can still think about how you'd use it that'd be swell.

**Comment by neolit123** [comment]
the role board is now open :tada: 
https://discuss.kubernetes.io/c/contributors/role-board

@kubernetes/sig-cluster-lifecycle 

we only have one entry in our [gdoc](https://docs.google.com/document/d/1iQ_Lola1s9_ilqbKLtZChDnbkqNt9uq1p6S1PbOkXCM/edit?usp=sharing) for now, but hopefully in time we can add more and post them at the board.

**Comment by dixudx** [comment]
Wow, good news! We can have more volunteers to help us.

**Comment by neolit123** [comment]
we couldn't find any task that we can add and also some of the ideas did not get approved on the kubeadm side.
we can leave this issue with the current automated lifecycle, unless cluster-api or kops would like to add proposals.

**Comment by timothysc** [comment]
@neolit123 should we keep this open or close it?

**Comment by neolit123** [comment]
seems like we were unable to rally ideas for this.
i'm OK with closing.
