### ISSUE TITLE
HA documentation update

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1044]
The **Configure SSH** [section in this document](https://kubernetes.io/docs/setup/independent/high-availability/#first-steps-for-both-methods) has caused much confusion. I would love some help finding an easier way to approach this.

I think outlining *why* we are configuring SSH would be a good starting point, but maybe `ssh-agent` is not well known enough and we should stick to very basic, albeit verbose, commands.

**Comment by fabriziopandini** [comment]
Uhhmm 
I don't think we should outline a solution for doing SSH because there is already plenty of public doc for this (eventually we should link something instead)

**Comment by neolit123** [comment]
i agree with @fabriziopandini 
e.g. link to http://rabexc.org/posts/using-ssh-agent

**Comment by motek80** [comment]
Personally I would love to know *why* SSH is required. As a user, when I understanding reason for each step I can plan alternative solutions \ workarounds as needed.

**Comment by neolit123** [comment]
expending with a sentence on two on why ssh is needed here and what it does might help users.

**Comment by Bradamant3** [comment]
@cha do you have more details about where/how/why users are tripping over SSH? Would a small prerequisites section added to this section help?

**Comment by timothysc** [comment]
xref - https://github.com/kubernetes/kubeadm/issues/706

**Comment by timothysc** [comment]
kubernetes/website#10264  is merged, closing.
