### ISSUE TITLE
Kubernetes cluster upgrade to 1.11.2 from 1.10.0 can't communicate with etcd

### ISSUE THREAD

**Issue by merdincz** [kubernetes/kubeadm#1046]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** v1.11.2

**Environment**:
- **Kubernetes version** v1.10.0
- **OS** (e.g. from /etc/os-release): centos-release-7-4.1708.el7.centos.x86_64
- **Kernel** Linux RMPH014 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
I am trying to upgrade my kubernetes cluster 1.10.0 to 1.11.2. I've used kubeadm upgrade plan command and get the error;
```
[root]# kubeadm upgrade plan
 [preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.10.0
[upgrade/versions] kubeadm version: v1.11.2
[upgrade/versions] Latest stable version: v1.11.2
[upgrade/versions] FATAL: dial tcp [::1]:2379: connect: connection refused
```
I've checked etcd status;
```
kubectl get componentstatuses --all-namespaces
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-0               Healthy   {"health": "true"}
```

Also try to add manuel record to etcd without any error.

`curl -X PUT "http://127.0.0.1:22379/v2/keys/_test"`

## What you expected to happen?
Upgrade to 1.11.2

## Anything else we need to know?
I tried different versions of kubeadm for minor version upgrade like to 1.10.1 or 1.10.2 but got same error.

I've just tried on master;
```
telnet localhost 2379
Trying ::1...
telnet: connect to address ::1: Connection refused
```

but i can connect with
```
telnet 127.0.0.1 2379
Trying 127.0.0.1...
Connected to 127.0.0.1.
```

**Comment by rosti** [comment]
Hi @merdincz , thanks for filing this issue!

Is your etcd external or you used kubeadm to deploy it (local one)?

**Comment by merdincz** [comment]
Hi @rosti 

Thanks i've just found problem. 

In my `/etc/hosts` file has a entry like 
`::1       localhost localhost.localdomain localhost6 localhost6.localdomain6`

Because of this telnet localhost 2379 didn't work. I changed that line like;

```
127.0.0.1 localhost
::1       localhost.localdomain localhost6 localhost6.localdomain6
```

and it worked. I've just upgraded successfully.
