### ISSUE TITLE
training on kubernetes GPU cluster

### ISSUE THREAD

**Issue by EmnamoR** [kubernetes/kubeadm#1048]
i set up a gpu cluster with 1 cpu only master and 3 gpu nodes
is there a way to make machine learning using the three gpus at once ?
because now i can only use 1 node with only 1 gpu

**Comment by neolit123** [comment]
@EmnamoR 
> is there a way to make machine learning using the three gpus at once ? 

i'm pretty sure you can.

but this is more of a generic kubernetes question and not about kubeadm.
if you google `kubernetes machine learning` there are some interesting resources.

also k8s has a working group about machine learning that meets every other Thusrday:
https://github.com/kubernetes/community/tree/master/wg-machine-learning

they have a mailing list and they are on slack too. :+1: 


thanks
/close
