### ISSUE TITLE
dashboard login not working with basic-auth-file

### ISSUE THREAD

**Issue by nancykyo** [kubernetes/kubeadm#105]
I'm trying kubeadm to setup a simple k8s cluster, and wish to have basic auth while using the k8s dashboard:
ex: A login dialog should pop up.

Experiment Steps: using basic-auth-file to start apiserver
modify the code, rebuild, and reinit the cluster.
{code}
```
diff --git a/cmd/kubeadm/app/master/manifests.go b/cmd/kubeadm/app/master/manifests.go
index b54e2ee..ae061d7 100644
--- a/cmd/kubeadm/app/master/manifests.go
+++ b/cmd/kubeadm/app/master/manifests.go
@@ -292,6 +292,7 @@ func getAPIServerCommand(cfg *kubeadmapi.MasterConfiguration) []string {
 		"--tls-cert-file="+kubeadmapi.GlobalEnvParams.HostPKIPath+"/apiserver.pem",
 		"--tls-private-key-file="+kubeadmapi.GlobalEnvParams.HostPKIPath+"/apiserver-key.pem",
 		"--token-auth-file="+kubeadmapi.GlobalEnvParams.HostPKIPath+"/tokens.csv",
+		"--basic-auth-file="+kubeadmapi.GlobalEnvParams.BasicAuthFile,
 		fmt.Sprintf("--secure-port=%d", cfg.API.Port),
 		"--allow-privileged",
 	)


```
and checking /etc/kubernetes/manifests/kube-apiserver.json, the option is injected.
--basic-auth-file.

But the dashboard can still be visited without username/password. So I'm confused.. Anything wrong with my understanding of the auth file?

**Comment by kargakis** [comment]
Probably related to https://github.com/kubernetes/kubeadm/issues/23?

**Comment by luxas** [comment]
How are you trying to contact the dashboard? Via the nodePort?

**Comment by nancykyo** [comment]
@luxas  yes, with nodePort.
thanks @kargakis  seems it's duplicated.

**Comment by luxas** [comment]
Closing in favor for #23, let's continue there
