### ISSUE TITLE
kubeadm init --dry-run Attached object display format error 

### ISSUE THREAD

**Issue by chenyb4** [kubernetes/kubeadm#1050]
## Versions

**kubeadm version** (use `kubeadm version`):  v1.11.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.11.2
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core)
- **Kernel** (e.g. `uname -a`): 3.10.0-327.el7.x86_64
- **Others**:

## What happened?
execute "kubeadm init --kubernetes-version=v1.11.2 --apiserver-advertise-address 192.168.8.64 --pod-network-cidr=10.244.0.0/16 --dry-run" display error.

[dryrun] Resource name: "coredns"
[dryrun] Would perform action CREATE on resource "configmaps" in API group "core/v1"
[dryrun] Attached object:
apiVersion: v1
data:
Corefile: ".:53 {\n errors\n health\n kubernetes cluster.local in-addr.arpa
ip6.arpa {\n pods insecure\n upstream\n fallthrough in-addr.arpa
ip6.arpa\n }\n prometheus :9153\n proxy . \n cache 30\n reload\n}\n"
kind: ConfigMap
metadata:
creationTimestamp: null
name: coredns
namespace: kube-system

kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by chrisohaver** [comment]
Is this an error or just informational?  It's normal that the coredns configmap would be created during init, it's required by CoreDNS.

**Comment by neolit123** [comment]
@chenyb4 
this is not an error.
dry-run is just dumping this object:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L294
it does the same for other configs.

are you referring to the `\n` used instead of new lines for the Corefile contents?

**Comment by chenyb4** [comment]
Display format and "\n" looks not good.

**Comment by neolit123** [comment]
ok, go for it.

**Comment by timothysc** [comment]
For stuff like this, please just submit PRs and they will be routed and auto-assigned.
