### ISSUE TITLE
Remove (or deprecate) --feature-gates=HighAvailability, SelfHosting, CertsInSecrets

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1058]
In the context of [Checklist for kubeadm join --control-plane implementation](https://github.com/kubernetes/kubeadm/issues/751) we are going to remove following feature-gates flags HighAvailability, SelfHosting, CertsInSecrets (this [Tracking issue for "Config to v1beta1"](https://github.com/kubernetes/kubeadm/issues/963) will benefit from this simplification as well)

We should decide how to do this:
- remove feature-gates flags from v1.12 or deprecate  flags in v1.12 for kubeadm init
- how to manage in kubeadm updates (preserve flags or change flags/the cluster; how to inform users about this)
- when to cleanup code
- other implications

/kind feature
/kind cleanup
/priority important-soon

**Comment by neolit123** [comment]
> remove feature-gates flags from v1.12 or deprecate flags in v1.12 for kubeadm init

deprecated state:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/feature/feature_gate.go#L72

but a feature gate is also a CLI flag so i'm unsure about the policy:
https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli

given these FGs are ALPHA it says "0 releases", which means we can deprecate right away?

**Comment by neolit123** [comment]
as, confirmed by api-machinery folks, we can remove these without a deprecation policy.

**Comment by fabriziopandini** [comment]
Summing up comments above, what discussed the 14 of august in sig meeting  and the 15 in kubeadm office hours, and my deep dive on the topic I propose the following solution with the goal to:
- block usage of feature-gates flags `HighAvailability`, `SelfHosting`, `CertsInSecrets` for new clusters starting from v1.12
- give a warning to users during upgrades to v1.12 of clusters with `SelfHosting`, `CertsInSecrets`, but not block; instead upgrades to v1.13 of such clusters will be blocked

Implementation plan:

**v1.12 milestone (1 PR)**
- Mark feature-gates flags `HighAvailability`, `SelfHosting`, `CertsInSecrets` as Hidden (not visible in help)
- Add a new `DeprecationMode` attribute to [feature gates struct](https://github.com/kubernetes/kubernetes/blob/eeb3389f3ba3f4b23fedbac365e78e1e7173bf3b/cmd/kubeadm/app/features/features.go#L61) flags for defining how deprecation will happen during upgrades
- Set `DeprecationMode = SilentlyRemove` for feature gate `HighAvailability`, and make this happen during upgrades [here](https://github.com/kubernetes/kubernetes/blob/eeb3389f3ba3f4b23fedbac365e78e1e7173bf3b/cmd/kubeadm/app/cmd/upgrade/common.go#L53)
- Set `DeprecationMode = Warning` for feature gate `SelfHosting`, `CertsInSecrets`, and generate the warning during upgrade plan and upgrade apply [here](https://github.com/kubernetes/kubernetes/blob/eeb3389f3ba3f4b23fedbac365e78e1e7173bf3b/cmd/kubeadm/app/cmd/upgrade/common.go#L53)
- Block usage of feature gates flags with `DeprecationMode != None` in all CLI commands where feature gate is passed as import [here](https://github.com/kubernetes/kubernetes/blob/eeb3389f3ba3f4b23fedbac365e78e1e7173bf3b/cmd/kubeadm/app/features/features.go#L139)
- clean-up implementation code for `HighAvailability` (if any)

**v1.13  milestone (1 PR)**
- remove feature gate flag `HighAvailability` 
- Set `DeprecationMode = Block` for feature gate `SelfHosting`, `CertsInSecrets`, and make this happen during upgrades [here](https://github.com/kubernetes/kubernetes/blob/eeb3389f3ba3f4b23fedbac365e78e1e7173bf3b/cmd/kubeadm/app/cmd/upgrade/common.go#L53)
- clean-up implementation code for `SelfHosting`, `CertsInSecrets`

**v1.14 milestone (1 PR)**
- remove feature gate flags `SelfHosting`, `CertsInSecrets`

**Comment by neolit123** [comment]
@fabriziopandini 
there is already a deprecated state in the FeatureSpec as far as i can see:
https://github.com/kubernetes/kubernetes//blob/master/staging/src/k8s.io/apiserver/pkg/util/feature/feature_gate.go#L72

so i think we can do this:
`PreRelease: utilfeature.Deprecated`

and a warning _should_ be printed:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/feature/feature_gate.go#L180

but as outlined in my previous commend and the office hours discussion we understood that we don't need to have a deprecation period for alpha gates:
> as confirmed by api-machinery folks, we can remove these without a deprecation policy since these are alpha. a release note would suffice.

do you think that the new `DeprecationMode` and the deprecation policy here is only needed here only because we also have to handle upgrades?

i will reserve on voting now, because i don't understand the need for the deprecation yet.
this complicates things for us, but if you really think this is is needed we can go with it, i guess.

@chuckha @liztio @stealthybox

**Comment by fabriziopandini** [comment]
@neolit123 my only concern  is too mitigate impacts on users, and even if we can remove alpha features without advice I think that in case of self hosting we should give proper advice + grace period 
For the implementation, the proposed solution consider that kubeadm has its own implementation of feature gates :-( ...

**Comment by neolit123** [comment]
> my only concern is too mitigate impacts on users, and even if we can remove alpha features without advice I think that in case of self hosting we should give proper advice + grace period

yep, understood.
there is always someone that depends on an alpha feature and will complain if we remove it without notice. it's just that this is extra work for us and someone has to do it.

> For the implementation, the proposed solution consider that kubeadm has its own implementation of feature gates :-( ...

/grumble :\

**Comment by fabriziopandini** [comment]
As for SIG discussion (see meeting notes - August 21 - 2018) we are going to block usage of feature gates and block updates on existing clusters in V1.12

**Comment by timothysc** [comment]
Closing, the deprecation PR has merged.
