### ISSUE TITLE
[HA L7 LoadBalancer] kubeadm managed kubelets reject externally generated self-signed certificates

### ISSUE THREAD

**Issue by motek80** [kubernetes/kubeadm#1063]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
AWS, T2 Medium

- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04

- **Kernel** (e.g. `uname -a`):

Linux ip-172-31-13-197 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?

- I tried to setup HA deployment as described [here](https://kubernetes.io/docs/setup/independent/high-availability/). 

- I deployed my own Nginx on separated EC2 instance, and configured it to serve as a https load balancer. 
- I generated a self-signed certificate and used it inside Nginx ssl binding configuration
- I copied that certificate to "master" node and added it to "trusted list" (as described [here](https://unix.stackexchange.com/a/132163))
- I verified that certificate indeed trusted by doing cUrl to the Nginx machine

- When executing "kubeadm init --config kubeadm-config.yaml" the setup hangs on "[init] this might take a minute or longer if the control plane images have to be pulled" stage.

## What you expected to happen?
Setup will succeed

## How to reproduce it (as minimally and precisely as possible)?
Do the steps I described above (use load balancer with self-signed certificate)

## Anything else we need to know?

This is what i getting from Journal logs:

Aug 16 07:42:38 ip-172-31-13-197 kubelet[7367]: E0816 07:42:38.688683    7367 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Get https://ip-172-31-10-234.eu-central-1.compute.internal:6443/api/v1/nodes?fieldSelector=metadata.name%3Dip-172-31-13-197&limit=500&resourceVersion=0: x509: **certificate signed by unknown authority**

**Comment by yidane** [comment]
I got the same issue, and I rum the command with `sudo kubeadm init`,but got another issue: get https://storage.googleapis.com/kubernetes-release/release/stable-1.11.txt .... time out.

**Comment by yidane** [comment]
It works by using command `sudo kubeadm init --kubernetes-version=v1.11.2`. We are the same version.

**Comment by motek80** [comment]
@yidane: I not sure I follow you. Do you know how to resolve issue related to "certificate signed by unknown authority" ?

**Comment by stealthybox** [comment]
One way to address this would be to add your APIServer LB certificate to the trusted certificates store on all of your Nodes.

I believe we mount these directories into all kubernetes components, and the kubelet typically runs as a systemd unit, so it definitely will use the host's cert-store

**Comment by stealthybox** [comment]
@motek80, if you want NGINX to perform TLS termination at L7, you'll need to deploy `/etc/kubernetes/pki/apiserver.{crt,key}` to your NGINX machine so that the APIServer identity is consistent with how the kubelet and other kubernetes components are configured.

These certificates are generated by kubeadm for you and are self-signed by default.
You can also use kubeadm in external-ca mode if you wish to manage your certificates differently.

The current documentation recommends doing TCP forwarding instead of L7 loadbalancing:
https://kubernetes.io/docs/setup/independent/high-availability/#create-load-balancer-for-kube-apiserver
With this setup, the TLS handshakes happen with the APIServer Pods directly, meaning you would not need to manage your certificates on your loadbalancer.

**Comment by motek80** [comment]
@liztio : If you following an official guide for setting up a HA cluster (using KubeAdm), you have to configure Load Balancer _before_ setting up any of K8ss Masters. So, at that point you have no kubernetes generated certificate yet - it created later, during Master setup. Therefore, you have to use something else for Load Balancer...

**Comment by stealthybox** [comment]
@motek80 
> The current documentation recommends doing TCP forwarding instead of L7 loadbalancing:
https://kubernetes.io/docs/setup/independent/high-availability/#create-load-balancer-for-kube-apiserver
With this setup, the TLS handshakes happen with the APIServer Pods directly, meaning you would not need to manage your certificates on your loadbalancer.

If you insist on setting up an L7 LB with TLS termination, you will need to either use a kubeadm generated CA or manage your own.

**Comment by timothysc** [comment]
> I generated a self-signed certificate and used it inside Nginx ssl binding configuration 

The documentation states "In a cloud environment you should place your control plane nodes behind a TCP forwarding load balancer."  

SSL termination has to occur at the apiserver endpoints.
