### ISSUE TITLE
Allow configuring of coredns options

### ISSUE THREAD

**Issue by dionysius** [kubernetes/kubeadm#1064]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

[Kubeadm currently only allows definition of mainly crutial options](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L305), while [coredns has a good list of options to consider allowing to be set](https://github.com/coredns/coredns/tree/master/plugin/kubernetes#syntax). It is difficult to `kubectl patch` the wished changes to the configmap in afterwards, so requesting the implementation of these/some options. Personally, I'd like to define `ttl`, `resyncperiod`, `endpoint_pod_names`, `transfer` and `ignore empty_service`

## Versions

**kubeadm version** (use `kubeadm version`): current master branch (see link above)

**Environment**:
- **Kubernetes version** (use `kubectl version`): *unrelated*
- **Cloud provider or hardware configuration**: *unrelated*
- **OS** (e.g. from /etc/os-release): *unrelated*
- **Kernel** (e.g. `uname -a`): *unrelated*
- **Others**:

## What happened?

I have no options to configure the coredns.

## What you expected to happen?

I have at least some options to configure the coredns.

## How to reproduce it (as minimally and precisely as possible)?

Can't reproduce, options are missing

## Anything else we need to know?

Don't think so

**Comment by neolit123** [comment]
this is a know problem.
users want to set addon specifics, but don't support it yet.

it could happen after 1.12.

**Comment by neolit123** [comment]
/close

in favor of:
https://github.com/kubernetes/kubeadm/issues/1091
