### ISSUE TITLE
remove SHA from flannel CNI instructions once 0.11 is released

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1069]
we are using a fixed SHA in the flannel instructions:
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/independent/create-cluster-kubeadm.md

fix that to a version TAG once flannel 0.11 is released.

**Comment by neolit123** [comment]
/lifecycle frozen
0.11 is not out yet:
https://github.com/coreos/flannel/releases

**Comment by Adirio** [comment]
This issue acts as a reminder to remove something that was already modified by [kubernetes/website#10571](https://github.com/kubernetes/website/pull/10571)

The remainder now is to switch back to a version-based instead of SHA-based link.

**Comment by neolit123** [comment]
0.11 was released:
https://github.com/coreos/flannel/releases/tag/v0.11.0

TODO update docs (possibly tomorrow).
/lifecycle active

**Comment by neolit123** [comment]
looks like they forgot to update the manifest for 0.11.0 and it's still using 0.10.0 images :man_facepalming: 

sent PR to fix that:
https://github.com/coreos/flannel/pulls

**Comment by neolit123** [comment]
closing this ticked it seems that we have to maintain SHA's instead of tags until 0.12.
