### ISSUE TITLE
Improve UX for upgrade node experimental-control-plane 

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1071]
https://github.com/kubernetes/kubernetes/pull/66973 implemented upgrade for secondary instances of the control plane via the new command `kubeadm upgrade node experimental-control-plane`.

This approach isolates the alpha feature from the main kubeadm workflows, but gives extra works to the users.

Once `join --control-plane` became not experimental we should review the approach to upgrades as well, perhaps detecting and triggering automatically upgrade of secondary instances of the control plane as a step of a comprehensive `kubeadm upgrade node` action

See [this comments](https://github.com/kubernetes/kubernetes/pull/66973#pullrequestreview-147388093) on the PR for more background

**Comment by timothysc** [comment]
Thanks for filing @fabriziopandini

**Comment by timothysc** [comment]
@fabriziopandini can we close?

**Comment by fabriziopandini** [comment]
No. Users are still required to do two actions for upgrading control-plane nodes ATM

**Comment by MalloZup** [comment]
@fabriziopandini i can take a look at this.

**Comment by fabriziopandini** [comment]
kk
/lifecycle active

**Comment by yuexiao-wang** [comment]
I will take this issue this week after talking with @MalloZup

**Comment by fabriziopandini** [comment]
@yuexiao-wang when do you plan to send PR for this issue (I'm updating state for Tracking issue for Certificates copy for join --control-plane)

**Comment by fabriziopandini** [comment]
@yuexiao-wang as discussed in slack we are punting this to v1.15 because HA will not make beta in V1.14

**Comment by yuexiao-wang** [comment]
Got it

**Comment by fabriziopandini** [comment]
/lifecycle active
@timothysc @neolit123 @yago @ereslibre @rosti 

For upgrades on nodes now we have two commands now:
1. `kubeadm upgrade node config` to be run on all nodes
2. `kubeadm upgrade node experimental-control-plane` to be run on control-plane nodes only 

My proposal is to:
a. Merge the two commands into `kubeadm upgrade node`, implementing it as a command with two phases, `kubelet-config` and `control-plane`
c. Deprecate 1. (subject to GA constraints), pointing users to use a. (or a. phase)
b. Remove 2. (or deprecate as for 1.) (edited) 

CONS: for a transitory period we will have `kubeadm upgrade node` command with `phases` subcommand + the olds `config` / `experimental-control-plane` deprecated subcommands, that is kind of weird

**Comment by neolit123** [comment]
i was thinking that we should punt the upgrade phases work to 1.16.
but if you think otherwise, it's fine.

**Comment by neolit123** [comment]
this seems to be done. upgrade phases for "apply" has a separate ticket.
please reopen if needed.
