### ISSUE TITLE
kubeadm v1.11.2 does not set service dns domain

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubeadm#1074]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): ubuntu bionic
- **Kernel** (e.g. `uname -a`): `Linux ubuntu-bionic 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?
I initialised a single node cluster with
```
kubeadm init \
    --apiserver-advertise-address=192.168.1.142 \
    --pod-network-cidr=10.244.0.0/16 \
    --service-cidr=10.42.0.0/16 \
    --service-dns-domain=zerkms-vagrant-test.local
```

The dns domain is specified in the coredns config:
```
root@ubuntu-bionic:/var/lib/kubelet# kubectl describe configmap coredns -n kube-system
Name:         coredns
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
Corefile:
----
.:53 {
    errors
    health
    kubernetes zerkms-vagrant-test.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    reload
}

Events:  <none>
```

yet the `search` in the containers would be

```
# cat /etc/resolv.conf
nameserver 10.42.0.10
search default.svc.cluster.local svc.cluster.local cluster.local home
options ndots:5
```

so the short service names do not work

## What you expected to happen?
I expect the `search` to be
```
search default.svc.zerkms-vagrant-test.local svc.zerkms-vagrant-test.local zerkms-vagrant-test.local
```

## How to reproduce it (as minimally and precisely as possible)?
All is in `What happened`

**Comment by neolit123** [comment]
once you call `kubeadm init`, what are the contents of?
`/var/lib/kubelet/kubeadm-flags.env`

do you have `systemd-resolved` enabled on your system?
AFAIK, Bionic is using `systemd-resolved` by default and the `--resolv-conf` for the kubelet should be automatically set to `/run/systemd/resolve/resolv.conf` by kubeadm.

**Comment by zerkms** [comment]
```
root@ubuntu-bionic:/home/vagrant# cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS=--cgroup-driver=cgroupfs --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni --resolv-conf=/run/systemd/resolve/resolv.conf
```

> do you have systemd-resolved enabled on your system?

yes, it's a default ubuntu bionic installation

```
root@ubuntu-bionic:/home/vagrant# systemctl status systemd-resolved
● systemd-resolved.service - Network Name Resolution
   Loaded: loaded (/lib/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-08-24 21:26:20 UTC; 7min ago
     Docs: man:systemd-resolved.service(8)
           https://www.freedesktop.org/wiki/Software/systemd/resolved
           https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
           https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
 Main PID: 620 (systemd-resolve)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4704)
   CGroup: /system.slice/systemd-resolved.service
           └─620 /lib/systemd/systemd-resolved
```

```
root@ubuntu-bionic:/home/vagrant# cat /run/systemd/resolve/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 10.0.2.3
search home
```

**Comment by zerkms** [comment]
I can share the complete script for vagrant and the rest so that anybody could reproduce it on their machines:

```ruby
# Vagrantfile
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "public_network", ip: "192.168.1.142"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end
```

```bash
# install.sh
# docker

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
apt update
apt install docker-ce=17.03.2~ce-0~ubuntu-xenial

# @TODO disable docker routes?

# kubernetes packages

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
apt update
apt install -y kubelet kubeadm kubectl

# kubeadm

kubeadm init \
    --apiserver-advertise-address=192.168.1.142 \
    --pod-network-cidr=10.244.0.0/16 \
    --service-cidr=10.42.0.0/16 \
    --service-dns-domain=zerkms-vagrant-test.local
```

**Comment by neolit123** [comment]
> root@ubuntu-bionic:/home/vagrant# cat /run/systemd/resolve/resolv.conf
> ...
> search home

this is odd.

what happens if you temporary disable systemd-resolved (for testing only):
https://askubuntu.com/questions/907246/how-to-disable-systemd-resolved-in-ubuntu

and try `kubeadm init` again.
is `search` valid in `/etc/resolv.conf` and does `/var/lib/kubelet/kubeadm-flags.env` contain `--resolv-conf=/etc/resolv.conf`

sadly, i don't have experience with the vagrant-kubeadm setup yet.

**Comment by zerkms** [comment]
> this is odd.
what is odd? It's a default search domain on the host machine. It might be anything here.

> vagrant-kubeadm
there is no `vagrant-kubeadm` there: it's a vagrant that sets up naked ubuntu bionic (for convenience), then I install kubernetes inside as usually on any other machine.

Do you really think I need to disable systemd-resolver, given it's a problem with container dns/coredns, not with the dns on the host machine?

**Comment by zerkms** [comment]
Wait a second, did you mean that `kubeadm` should modify the host's `resolv.conf`?

**Comment by zerkms** [comment]
I disabled `systemd-resolved` and re-run `kubeadm` again (after a `reset`).

Results:

```
root@ubuntu-bionic:/home/vagrant# cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS=--cgroup-driver=cgroupfs --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni
```
```
root@ubuntu-bionic:/home/vagrant# kubectl describe configmap coredns -n kube-system
Name:         coredns
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
Corefile:
----
.:53 {
    errors
    health
    kubernetes zerkms-vagrant-test.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    reload
}

Events:  <none>
```

**Comment by neolit123** [comment]
> vagrant-kubeadm

i just meant that i have never tried kubeadm with vagrant.
we do have this playground though:
https://github.com/kubernetes/kubeadm/tree/master/vagrant

> Wait a second, did you mean that kubeadm should modify the host's resolv.conf?

going back to the first post:
```
Corefile:
----
.:53 {
    errors
    health
    kubernetes zerkms-vagrant-test.local in-addr.arpa ip6.arpa {
```
the dns you pass on the command line is written correctly in the coredns Corefile.

> I expect the search to be
> search default.svc.zerkms-vagrant-test.local svc.zerkms-vagrant-test.local zerkms-vagrant-test.local

kubeadm or the kubelet would not write resolv.conf files, managed by `systemd-resolved` or not.

perhaps i'm missing something in the report?

**Comment by zerkms** [comment]
> perhaps i'm missing something in the report?

kubeadm generates slightly invalid kubelet config:

```
root@ubuntu-bionic:/home/vagrant# grep -i "clusterdom" /var/lib/kubelet/config.yaml
clusterDomain: cluster.local
```
while it should be:
```
clusterDomain: zerkms-vagrant-test.local
```

**Comment by neolit123** [comment]
we should probably set `clusterDomain` automatically for the kubelet based on `--service-dns-domain` in 1.12?
what do others think @kubernetes/sig-cluster-lifecycle 

@zerkms as a workaround in 1.11.x you can pass a custom kubeadm config to `kubeadm init --config <kubeadm-config>` and in there include a `kubeletConfiguration` with `clusterDomain` field:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

the other workaround is to pass `--cluster-domain` per node in `/etc/default/kubelet`
https://kubernetes.io/docs/setup/independent/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

according to this thread passing both `--cluster-domain` and `--resolv-conf` to the kubelet has unclear behavior:
https://github.com/kubernetes/kubernetes/issues/30073

**Comment by timothysc** [comment]
@fabriziopandini - for 1.13 we should probably have a config param to cleanup the UX across components before we hit beta.

**Comment by timothysc** [comment]
Closing due to issue timeout and it doesn't appear to be kubeadm specifc vs. coredns config request.
