### ISSUE TITLE
Kubectl DeadlineExceeded/ NetworkPlugin cni failed  : Unable to access services(NodePort) via Master Node 

### ISSUE THREAD

**Issue by anupam4881** [kubernetes/kubeadm#1078]
[root@TPSERVER195 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
 [root@TPSERVER195 ~]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[root@TPSERVER195 ~]# uname  -a
Linux TPSERVER195 3.10.0-693.17.1.el7.bug14347.centos.plus.x86_64 #1 SMP Tue Feb 6 16:27:03 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@TPSERVER195 ~]#
Dear Team ,

We are facing this issue from last two month  as we are new so we reset and reconfigure system again and again and things start running again for next 20 days max.  now we want to fix same as re-installation is not a solution. 
We have one master & 2 node cluster having 20 container running, daily machines get down at night and come up at morning and all container come up later one by one ( slace up & down ) , during scale up process we start getting Fist error after few days on new setup again  

  Warning  FailedCreatePodSandBox  9m (x89 over 6h)  kubelet, tpserver195  Failed create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   SuccessfulMountVolume   6m                kubelet, tpserver195  MountVolume.SetUp succeeded for volume "kube-dns-config"
  
  Warning  FailedCreatePodSandBox  6m                kubelet, tpserver195  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-86f4d74b45-vzhj4_kube-system" network: unable to allocate IP address: Post http://127.0.0.1:6784/ip/81bbb6597c8dd94366883c5c36a3185192b3ded16c9e835572df489e34ed5a5b: dial tcp 127.0.0.1:6784: connect: connection refused

And same with kubedns 

Warning  FailedCreatePodSandBox  14m                 kubelet, tpserver195  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "kube-dns-86f4d74b45-vzhj4_kube-system" network: unable to allocate IP address: Post http://127.0.0.1:6784/ip/81bbb6597c8dd94366883c5c36a3185192b3ded16c9e835572df489e34ed5a5b: dial tcp 127.0.0.1:6784: connect: connection refused

So we run below command to release IP manually 

[root@TPSERVER195 ~]# kubectl exec -n kube-system weave-net-9snvj  -c weave -- /home/weave/weave --local rmpeer tpserver102
XXXXX IPs taken over from tpserver102
[root@TPSERVER195 ~]# kubectl exec -n kube-system weave-net-9snvj -c weave -- /home/weave/weave --local status ipam

And services are than come up but not accessible from master IP: NodePort only through NodeIp:NodePort. 

So we have two problem as our machines reboot everyday several time, and re-installation didnt help us. 
1.	How to  fix this IP issue ( pool full)  need your expert help.
2.	Not able to telnet once we run ipam commond from masterIP:NodePort 

root@TPSERVER195 ~]# telnet 10.225.241.159 30677
Trying 10.225.241.159...
telnet: connect to address 10.225.241.159: No route to host

looking for you kind help/suggestion  or any patch to fix same

Regards
Anupam Narayan

DNS related one observation not sure related to this issue or not 

[root@TPSERVER195 ~]# kubectl logs -n kube-system kube-dns-86f4d74b45-vzhj4    -c sidecar
I0826 02:41:40.729365       1 main.go:51] Version v1.14.8
I0826 02:41:40.732649       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0826 02:41:40.732835       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
I0826 02:41:40.733003       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
W0826 02:41:40.733896       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:39807->127.0.0.1:53: read: connection refused

**Comment by anupam4881** [comment]
This problem-2 solved 
Not able to telnet once we run ipam commond from masterIP:NodePort

cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl --system


But main case is still not fixed.

Kindly help

Regards
Anupam

**Comment by rosti** [comment]
Hi @anupam4881, thanks for filing this issue!

Can you check which of the required `kube-system` pods are running?

```
kubectl get pods --namespace=kube-system
```

**Comment by anupam4881** [comment]
Hi
Please find the current status.

[root@TPSERVER195 ~]# kubectl get pods --namespace=kube-system 
NAME                                    READY     STATUS      RESTARTS   AGE
backup-1535112600-2bct9                 0/1       Completed   0          4d
backup-1535371800-j9n6t                 0/1       Completed   0          1d
backup-1535458200-q8xwz                 0/1       Completed   0          16h
etcd-tpserver195                        1/1       Running     9          23d
kube-apiserver-tpserver195              1/1       Running     10         23d
kube-controller-manager-tpserver195     1/1       Running     9          23d
kube-dns-86f4d74b45-vzhj4               3/3       Running     0          3d
kube-proxy-h9kxh                        1/1       Running     27         23d
kube-proxy-nfnqt                        1/1       Running     3          3d
kube-proxy-rqntc                        1/1       Running     3          3d
kube-scheduler-tpserver195              1/1       Running     9          23d
kubernetes-dashboard-7d5dcdb6d9-ksj8n   1/1       Running     0          3d
weave-net-bc2lb                         2/2       Running     8          3d
weave-net-qv5l9                         2/2       Running     8          3d
weave-net-x2smj                         2/2       Running     8          3d
[root@TPSERVER195 ~]# 

Regards
Anupam

**Comment by anupam4881** [comment]
rub below command to release few ip
[root@TPSERVER195 ~]# kubectl exec -n kube-system  weave-net-bc2lb  -c weave -- /home/weave/weave --local rmpeer tpserver102
128 IPs taken over from tpserver102
[root@TPSERVER195 ~]# kubectl exec -n kube-system  weave-net-x2smj   -c weave -- /home/weave/weave --local rmpeer tpserver169
192 IPs taken over from tpserver169
[root@TPSERVER195 ~]#

**Comment by anupam4881** [comment]
Any update one same, today we again hit by same problem , now we run rmpeer every time and restart pod to fix this temp.

Regards
Anupam

**Comment by rosti** [comment]
Hi @anupam4881 seems that your cluster runs out of IPs. Can you use `weave ps` to check the status of allocated IPs?

**Comment by anupam4881** [comment]
Apologize for delay response.  Yes cluster  seems running out of ip. but how to fix it ? , we are releasing IP on daily basis. 
[root@TPSERVER195 ~]# weave  ps
weave:expose ca:04:64:81:b4:09 10.35.248.2/12
1087c2d2241e ea:35:5c:5a:88:68 10.32.4.1/12
fc0b7e76a233 ea:35:5c:5a:88:68 10.32.4.1/12
cb239d42514e ce:a2:63:be:8a:e5 10.32.4.0/12
1dc1853eb0c1 ea:35:5c:5a:88:68 10.32.4.1/12
72160a0f4afb ea:35:5c:5a:88:68 10.32.4.1/12
a6bf8123ac49 ce:a2:63:be:8a:e5 10.32.4.0/12

**Comment by timothysc** [comment]
Closing, this seems like a CIDR-range setup issue, not kubeadm.

**Comment by HolimaX** [comment]
> Closing, this seems like a CIDR-range setup issue, not kubeadm.

Hi, @timothysc , could you please share more details on how to fix it or diagnose it better? Thanks.
