### ISSUE TITLE
kubeadm join requires cri-socket parameter on Windows Server 2016

### ISSUE THREAD

**Issue by nguyenlamlll** [kubernetes/kubeadm#1079]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**: 

```
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Windows Server 2016 (run as a VM on Hyper-V)
- **Kernel** (e.g. `uname -a`): Windows NT
- **Others**: I have installed Docker EE on this machine with the information as
```
Client:
 Version:      17.06.2-ee-14
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   6345dd7
 Built:        Thu Jun 21 18:16:45 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-14
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   6345dd7
  Built:        Thu Jun 21 18:28:51 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

## What happened?

I have set up a cluster with one master on Linux (Ubuntu 16.04) using default settings. It's in ready state which can be seen from `kubectl get nodes` as

```
NAME          STATUS    ROLES     AGE       VERSION
kube-master   Ready     master    3d        v1.11.2
```

I want to connect a Windows Server 2016 node to this cluster. I used the command:
```
kubeadm join <ip>:<port>--token <my_token> --discovery-token-ca-cert-hash sha256:<my_hashed_token>
```
and got an error as following: `nodeRegistration.criSocket: Invalid value: "/var/run/dockershim.sock": path is not absolute`

As I looked around, it seems that Windows and Docker for Windows don't support such a thing for dockershim.sock or socket? ([Here](https://forums.docker.com/t/where-is-the-file-docker-sock/13061)). This is the confusing thing for me.

What should I pass within the parameter `--cri-socket`? If I pass something randomly to the param, and ignore the cri errors with `--ignore-preflight-errors=cri`, `kubeadm join` can connect and establish a connection to the server. However, there are some issues with `kubelete` isn't running. 

Example command `kubeadm join <ip>:<port> --token <token> --discovery-token-ca-cert-hash sha256:<hased_token> --cri-socket "C:\Program Files\docker" --ignore-preflight-errors=cri` (I tried to pass docker.exe location...). Full response log:

```
[preflight] running pre-flight checks
        [WARNING CRI]: unable to check if the container runtime at "C:\\Program Files\\docker" is running: exit status 1
I0827 01:44:42.719736    3144 kernel_validator.go:81] Validating kernel version
        [WARNING Service-Kubelet]: kubelet service does not exist
[discovery] Trying to connect to API Server "192.168.160.120:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://192.168.160.120:6443"
[discovery] Requesting info from "https://192.168.160.120:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "192
.168.160.120:6443"
[discovery] Successfully established connection with API Server "192.168.160.120:6443"
[preflight] couldn't detect a kubelet service, can't make sure the kubelet not running for a short period of time while setting up con
figuration for it.
[preflight] WARNING: unable to stop the kubelet service momentarily: [exit status 1]
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.11" ConfigMap in the kube-system namespace
[kubelet] Writing kubelet configuration to file "\\var\\lib\\kubelet\\config.yaml"
[kubelet] Writing kubelet environment file with flags to file "\\var\\lib\\kubelet\\kubeadm-flags.env"
[preflight] couldn't detect a kubelet service, can't make sure the kubelet is running properly.
[preflight] Activating the kubelet service
[preflight] WARNING: unable to start the kubelet service: [couldn't stop service: exit status 1]
[preflight] please ensure kubelet is reloaded and running manually.
[tlsbootstrap] Waiting for the kubelet to perform the TLS Bootstrap...
**[kubelet-check] It seems like the kubelet isn't running or healthy.**
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/health
z: dial tcp [::1]:10248: connectex: No connection could be made because the target machine actively refused it..
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/health
z: dial tcp [::1]:10248: connectex: No connection could be made because the target machine actively refused it..
```

## What you expected to happen?
The Windows Server 2016 node is connected to the cluster and can be seen with the command `kubectl get nodes`.

## How to reproduce it (as minimally and precisely as possible)?
1. Prepare a VM that runs Ubuntu 16.04 LTS. Set up the cluster with a master node using `kubeadm init`. Install weave-net as a CNI plugin (`kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"`).
2. Prepare a VM that runs Windows Server 2016. Try to join the cluster with the command as `kubeadm join <ip>:6443 --token <my_token> --discovery-token-ca-cert-hash sha256:<my_hashed_token>` (as instructed of the result of `kubeadm init`).

**Comment by bart0sh** [comment]
@nguyenlamlll 
In theory it can be fixed in master by [this PR](https://github.com/kubernetes/kubernetes/pull/65900)
However, nobody tested it on Windows I believe.

Did you build kubernetes for windows yourself? If so, can you build master binaries and verify they work for you?

**Comment by bart0sh** [comment]
you can also use pre-built windows binaries from here https://storage.googleapis.com/kubernetes-release/release/v1.12.0-beta.0/kubernetes-node-windows-amd64.tar.gz

**Comment by neolit123** [comment]
we also have this PR for the socket path on Windows:
https://github.com/kubernetes/kubernetes/pull/67447

it's not merged yet.

**Comment by neolit123** [comment]
> What should I pass within the parameter --cri-socket?

when you install docker on Windows you should open this socket/port:
`tcp://localhost:2375`

**Comment by timothysc** [comment]
closing b/c kubernetes/kubernetes#67447 has merged.

**Comment by wachuwach** [comment]
Hi,

When can I expect binaries with fixed this issue? Any other (which) versions doesn't have this issue?
https://github.com/kubernetes/kubernetes/releases/

**Comment by neolit123** [comment]
@wachuwach 
> When can I expect binaries with fixed this issue? Any other (which) versions doesn't have this issue?

1.12 - to be released late September.

**Comment by bangzhuzhu** [comment]
still get this problem from newest kubernetes-node-windows-amd64.tar.
![image](https://user-images.githubusercontent.com/111118214/189095072-506ed7ea-c593-4fed-998a-996933406472.png)
How to fix this?

**Comment by neolit123** [comment]
your screenshot has 1.11, which is an old version. try 1.25.
