### ISSUE TITLE
Make code OS-agnostic as much as possible

### ISSUE THREAD

**Issue by pires** [kubernetes/kubeadm#108]
Kubernetes just got [Windows Containers alpha support](http://blog.kubernetes.io/2016/12/windows-server-support-kubernetes.html), opening the opportunity for `kubeadm` to also be used to setup, at least, Windows Server 2016 or newer worker nodes. With that in mind, we should take the effort of writing OS-agnostic code whenever possible, e.g. when dealing with the filesystem.

**Comment by luxas** [comment]
Case in point is using `filepath.Join` instead of just `path.Join`. 
Anything else that differs between linux and windows?

**Comment by pires** [comment]
Not that I'm aware of.

**Comment by luxas** [comment]
@fabriziopandini Could you send a PR that changes all uses of `path.Join` to `filepath.Join`?

**Comment by luxas** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/46600 by @fabriziopandini :+1:
