### ISSUE TITLE
Add other log backend for audit policy

### ISSUE THREAD

**Issue by riverzhang** [kubernetes/kubeadm#1080]
## What happened?
kubeadm audit featuregates  not support log-maxbackup and audit-log-maxsize
## What you expected to happen?
auditPolicy:
  logDir: /var/log/audit/kube-apiserver-audit.log
  logMaxAge: 30
  logMaxBackup: 2
  logMaxSize: 100
  path: /etc/kubernetes/audit-policy/apiserver-audit-policy.yaml

and apiserver command args:
    - --audit-log-maxage=30
    - --audit-log-maxbackup=2
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/kubernetes/audit/audit.log
    - --audit-policy-file=/etc/kubernetes/audit/audit.yaml

and fix https://github.com/kubernetes/kubernetes/pull/67956

**Comment by timothysc** [comment]
The tentative plan from the community is to support the dynamic audit web-hooks.  We don't want to own the configuration for this feature other than to allow folks to pass it through via extra args.
