### ISSUE TITLE
GoDoc types and config 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#1085]
Ideally, we maintain our examples in GoDoc that is updated with the code.  

The init examples should then point to this GoDoc reference.

/assign @neolit123 @liztio

**Comment by timothysc** [comment]
@mauilion @hhoover do you have concrete examples for the config that you would like to see. 

I'll drop a link to the current example which we can port and cleanup.

**Comment by mauilion** [comment]
I've seen quite a few requests for examples of setting node name and cloud provider lately (for aws to work correctly etc)

**Comment by mauilion** [comment]
@timothysc ^^

**Comment by liztio** [comment]
@mauilion could you file a separate issue with exactly what examples you want?
