### ISSUE TITLE
CRI Installation Instructions

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#1086]
We need a canonical doc that sig-node maintains - https://github.com/kubernetes/website/issues/9692 

/assign @neolit123 @kad

**Comment by kad** [comment]
cc @bart0sh

**Comment by bart0sh** [comment]
I used information from http://cri-o.io and https://github.com/kubernetes-incubator/cri-o when configuring CRI-O.
For containerd this can help I guess: https://github.com/containerd/cri

**Comment by bart0sh** [comment]
Any other CRI implementations to cover in the doc?

**Comment by bart0sh** [comment]
I wasn't able to figure out which page to put this information in. I'd propose this one: https://kubernetes.io/docs/setup/independent/install-kubeadm/ We can rename "Installing Docker" to "Installing Runtime" and have 3 tabs there: Docker, CRI-O and Containerd.

**Comment by neolit123** [comment]
@timothysc 
> We need a canonical doc that sig-node maintains

not sure if that maps well with using https://kubernetes.io/docs/setup/independent/install-kubeadm/ though. we can potentially link to a new page from our page, except that i don't know where that new page should be.

possibly under https://kubernetes.io/docs/setup, but this should be coordinated with sig-node / sig-docs...

**Comment by bart0sh** [comment]
I consider [this PR](
https://github.com/kubernetes/website/pull/10186) as a partial fix for this. I'm going to add CRI-O instructions the same way. 

Any objections?

**Comment by timothysc** [comment]
Doc has merged, closing this issue.
