### ISSUE TITLE
error marking master: timed out waiting for the condition

### ISSUE THREAD

**Issue by sebt3** [kubernetes/kubeadm#1087]
## What keywords did you search in kubeadm issues before filing this one?
The exact same message as in title

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/arm64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/arm64"}

- **Cloud provider or hardware configuration**:
an aarch64 board (can specify if needed, but that doesnt seem revelant)

- **OS** (e.g. from /etc/os-release):
cat /etc/debian_version 
buster/sid

- **Kernel** (e.g. `uname -a`):
Linux nano14 4.4.138 #3 SMP Wed Aug 29 16:37:10 CEST 2018 aarch64 GNU/Linux
(I rebuilded this kernel to add the missing cgroup options today hence the build date)

- **Others**:
ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.9.214  netmask 255.255.255.0  broadcast 192.168.9.255
...
eth0.100: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.14  netmask 255.255.255.0  broadcast 192.168.10.255
...

## What happened?
[markmaster] Marking the node nano14 as master by adding the taints [node-role.kubernetes.io/master:NoSchedule]
nano14: error marking master: timed out waiting for the condition

## What you expected to happen?
kubeadm to succed obviously :P

## How to reproduce it (as minimally and precisely as possible)?
kubeadm init --config=/etc/kubernetes/init-config.yaml --ignore-preflight-errors=all
bellow the said init-config.yaml
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 192.168.10.14
etcd:
  endpoints:
  - https://127.0.0.1:2379
  caFile: /etc/kubernetes/pki/etcd/ca.crt
  certFile: /etc/kubernetes/pki/etcd/client.crt
  keyFile: /etc/kubernetes/pki/etcd/client.key
networking:
  podSubnet: 10.244.0.0/16
apiServerCertSANs:
- 192.168.10.200
apiServerExtraArgs:
  endpoint-reconciler-type: lease
```

## Anything else we need to know?
Nothing in the etcd log that would matter (that's why I didnt used the other oppened issue)
But this in the kubelet log :
Aug 29 23:36:41 nano14 kubelet[20661]: I0829 23:36:41.574519   20661 kubelet_node_status.go:79] Attempting to register node nano14
Aug 29 23:36:41 nano14 kubelet[20661]: E0829 23:36:41.575257   20661 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Aug 29 23:36:41 nano14 kubelet[20661]: E0829 23:36:41.586637   20661 kubelet_node_status.go:103] Unable to register node "nano14" with API server: Unauthorized
Aug 29 23:36:41 nano14 kubelet[20661]: E0829 23:36:41.593687   20661 event.go:203] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"nano14.154f7252c2669
Aug 29 23:36:42 nano14 kubelet[20661]: E0829 23:36:42.505253   20661 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
Aug 29 23:36:42 nano14 kubelet[20661]: E0829 23:36:42.610036   20661 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized

It clealy explain why the taint failed : you cannot taint an unregistered node. But I failed to see why kubelet fail to register the node. My google-fu pointed me to network issue, but everything is local. I tried to use the "public" IP of the board (192.168.9214, see the ifconfig extract) but it fail the exact same way.
I'm using a configuration file since I dont want to use the etcd in a container. This method used to work on an other board (slightly less performant) without that network configuration in 1.10.2, and the etcd version is exactly the same.

**Comment by sebt3** [comment]
Since I've seen i'm not the only one having the kubelet registration issue (see #1026), I've decided to dig at which versions the issue start apearing. I first tried 1.10.4, since it was the last 1.10 I used successfully. And kubeadm finish succesfully. That test excluded my network configuration changes and hardware changes. So I tried 1.10.7, and it worked like a charm too.
Then I tried 1.11.0. It also worked, but kubelet did not register the node, its log was full of the same errors I posted in my previous post and kubectl get nodes did not list the node (obviously). So kubeadm couldn't have successfully marked successfully the node and should have returned an error (just like it does now in 1.11.2).
Back at 1.10.7, I verified that "kubectl get nodes" does list the node and it does. I rebooted the node, to verify that #1026 is not an issue at that version. and reboot works like a charm. Then I upgraded kubelet to 1.11.0. But with control-plane at 1.10.7 and kubelet 1.11.0, kubelet fail to register itself (with the "Unauthorized" error in my previous post).
Then I tied the other way around by trying to rebuild a cluster, and I also got the error in my previous post.

All my tests was done with kubeadm 1.11.2 (only changing the kubelet and control-plane version), so the issues isnt in kubeadm code base. The issue lie in the kubelet registration code and the issue was introduced between 1.10.7 and 1.11.0. I hope my tests are helpfull to pin-point the code change.

Cheers, 
Sébastien

**Comment by sebt3** [comment]
I now fail to reproduce the issue...

**Comment by DevilMayCrySamsara** [comment]
How was the problem solved?

**Comment by DevilMayCrySamsara** [comment]
> 我现在无法重现这个问题......

How was the problem solved?
