### ISSUE TITLE
kubeadm should configure resource request for critical kube-system component

### ISSUE THREAD

**Issue by peterableda** [kubernetes/kubeadm#1095]
## Versions

**kubeadm version**:
```
&version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

## What happened?
Connections to etcd are timing out on my heavy loaded machines. My suspicion is that this happens due to not reserving a minimum amount of CPU time for the service. 

I checked the `kubectl describe node` output for the resource requests:
```
  Namespace                  Name                                                CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                                ------------  ----------  ---------------  -------------
  kube-system                coredns-78fcdf6894-bxv7k                            100m (5%)     0 (0%)      70Mi (0%)        170Mi (2%)
  kube-system                coredns-78fcdf6894-kr8jv                            100m (5%)     0 (0%)      70Mi (0%)        170Mi (2%)
  kube-system                etcd-myhost.com                                     0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-apiserver-myhost.com                           250m (12%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-controller-manager-myhost.com                  200m (10%)    0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-proxy-zvcpw                                    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-scheduler-myhost.com                           100m (5%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                weave-net-ccjj4                                     20m (1%)      0 (0%)      0 (0%)           0 (0%)
```

## What you expected to happen?
The request here is to configure some amount of CPU requests for the etcd and kube-proxy.

**Comment by neolit123** [comment]
i think this might be outside of the scope of the `kubernetes/kubeadm` tracker.
please file the issue in `kubernetes/kubernetes`

possibly tag `/sig node` and `/sig architecture` for feedback.

thank you
/close

**Comment by neolit123** [comment]
actually, i've missed the title.

@peterableda do you have a proposal for how should kubeadm do that?

**Comment by stealthybox** [comment]
Could you please tell us more about your control-plane node?
How much CPU and memory does it have?
Are you using an HDD or an SSD?
Are you scheduling other Pods to it?

We might look to dig up some docs about what a reasonable CPU request could be for etcd and kube-proxy, but these components should be stable with the current defaults, even without ResourceRequirements.

**Comment by peterableda** [comment]
Yes, we removed the NoSchedule taint from the control-plane node and run potentially CPU intensive pods on it. We are aware of the root cause and understand that this might not be a good practice but we need to do this for our use-case. Reserving a small amount of CPU time for the etcd component would solve the issue for us.

**Comment by neolit123** [comment]
> We are aware of the root cause and understand that this might not be a good practice but we need to do this for our use-case. Reserving a small amount of CPU time for the etcd component would solve the issue for us.

a question, how would you configure these parameters in case you are using another bootstrapping tool instead of kubeadm?

**Comment by peterableda** [comment]
I would do this on the kubernetes level, like adding resource requests for etcd (we are doing this for the apiserver or scheduler also):
```
    resources:
      requests:
        cpu: 250m
```

**Comment by neolit123** [comment]
understood, thanks.

as per the OP request:
> The request here is to configure some amount of CPU requests for the etcd and kube-proxy.

hardcoded values would have to be added, here for the kube-proxy daemon-set
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L54
.
and for the etcd static pod manifest:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/etcd/local.go#L54

we already do this for the control plane:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/controlplane/manifests.go#L81

@peterableda 
btw, contributions  are welcome as this seems to affect your use case, yet, we haven't seen reports from others.

also as per your comment:
> My suspicion is that this happens due to not reserving a minimum amount of CPU time for the service.

my assumption would be that we are not even sure that this is the actual cause?

/priority backlog
/help

**Comment by yagonobre** [comment]
Can we configure hpa to coredns deployment?

**Comment by timothysc** [comment]
I'm going to use this issue to adjust priority, but perhaps there should be a ImageMeta @fabriziopandini ?

**Comment by fabriziopandini** [comment]
closing in favor of https://github.com/kubernetes/kubeadm/issues/1291
/close
