### ISSUE TITLE
Cleanup - Rename the constant that refers to the `kubeadm-config` ConfigMap

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1096]
https://github.com/kubernetes/kubernetes/pull/67944 changed how kubeadm uses the `kubeadm-config`ConfigMap, that now stores only the `ClusterConfiguration` and the `ClusterStatus`.

We should now rename the constant that refers to the `kubeadm-config` from `InitConfigurationConfigMap` to something more generic like e.g. `KubeadmConfigConfigMap`

rif [code](
https://github.com/kubernetes/kubernetes/blob/e5f55dd9d0969af3a37e7880d9b88c9aef8c654d/cmd/kubeadm/app/constants/constants.go#L193)

**Comment by Klaven** [comment]
@fabriziopandini I can pick this up if you want.
