### ISSUE TITLE
Kubeadm HA documenation for 1.11 is completely different from 1.9.5/1.10.11

### ISSUE THREAD

**Issue by smenon78** [kubernetes/kubeadm#1099]
Kubeadm HA cluster documentation is completely different in 1.11 from the steps in 1.9/1.10. I want to reuse the automated steps which was already done for 1.9.5. Will it still work for 1.11? Or can I make it work with minimal changes? 
It becomes extremely difficult to automate when steps are significantly different from version to version. 

Documentation for k8s 1.9/1.10
https://v1-10.docs.kubernetes.io/docs/setup/independent/high-availability/
Documentation for 1.11
https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by neolit123** [comment]
@smenon78 
i wouldn't say the new documentation is completely different, it's similar.
the new documentation also separates the HA etcd into a separate page.
https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/

but also it's improved and adapted to 1.11 as 1.11 saw a number of changes.
it's **highly** recommended to use the new documentation if you want to create a 1.11 cluster.

please close if this answers your question.
thanks.
