### ISSUE TITLE
kubernetes cluster inited by kubeadm does not start automatically after rebooting os

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubeadm#110]
```
kubeadm: v1.6.0-alpha.0.2074+a092d8e0f95f52
# docker images
REPOSITORY                                               TAG             
gcr.io/google_containers/kube-apiserver-amd64            v1.5.0          
gcr.io/google_containers/kube-controller-manager-amd64   v1.5.0          
gcr.io/google_containers/kube-scheduler-amd64            v1.5.0          
gcr.io/google_containers/etcd-amd64                      3.0.14-kubeadm  
gcr.io/google_containers/kube-discovery-amd64            1.0             
gcr.io/google_containers/pause-amd64                     3.0       
```      

and i can not find a subcommand like `start` to restart the cluster i have initialized by kubeadm.

os : a customized flavor of CentOS 7, 64 bit, but believe me, it is almost the same with CentOS

**Comment by luxas** [comment]
What does `journalctl -xeu kubelet` say after you've rebooted?
It's the kubelet's task to automatically spin everything up again.
I assume you've run `systemctl enable kubelet`?

**Comment by bruceauyeung** [comment]
@luxas i tried again and found it worked as expected.
thanks.

**Comment by yx1989** [comment]
I use `sudo swapoff -a` when I init k8s with kubeadm, then when I robot k8s hasn't started up.

 journalctl -xeu kubelet shows some error when startup.

After `sudo swapoff -a` , I try `systemctl enable kubelet` again. 

Everything going well now.

**Comment by yagonobre** [comment]
Have you removed the swap entry from `/etc/fstab`?
