### ISSUE TITLE
/proc/sys/net/ipv6/conf/eth0/accept_dad: no such file or directory in Kubernetes 1.11.2 when ipv6 disabled on hosts

### ISSUE THREAD

**Issue by kcao3** [kubernetes/kubeadm#1100]
Hello,
I am using kubeadm v1.11.2, with CNI plugins version v0.6.0 as indicated from this 
link: https://github.com/kubernetes/kubernetes/blob/v1.11.2/build/rpms/kubernetes-cni.spec.

Currently I am having an issue when IPv6 is disabled on my hosts. For some reason, 
the pods failed to start on hosts and I see some error messages from kubelet 
indicating the file /proc/sys/net/ipv6/conf/eth0/accept_dad does NOT exist on my hosts. This is true since my hosts do not have eth0 NIC. 

After a few minutes google searching, I realize I am not the ONLY one who ran into this issue:
https://github.com/containernetworking/cni/issues/569

As someone comments in the link right above, this is due to the fact that I am using an older 
version of CNI plugin. 

Does anyone run into this issue? Which version of CNI plugins should be upgraded to? 
Could you please provide any documents about how to upgrade the CNI plugins?

**Comment by neolit123** [comment]
hi, this issue seems outside of scope of kubeadm even if you are using kubeadm for the deployment.
might be a better idea to file an issue in `kubernetes/kubernetes` instead and tag `sig-network` (example bellow).

/sig network
/priority awaiting-more-evidence
