### ISSUE TITLE
Dynamic Kubelet Config broken in v1.12.0-beta.1

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1102]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**

kubeadm v1.12.0-beta.1

## What happened?

When executing `kubeadm join` with `featureGates: DynamicKubeletConfig: true` the following error is returned:
```
nodes "kubeadm-playground-node" is forbidden: cannot update configSource to a new non-nil configSource
```

## What you expected to happen?
To join a node with `featureGates: DynamicKubeletConfig: true` without errors

## How to reproduce it (as minimally and precisely as possible)?
Create a cluster with kubeadm v1.12.0-beta.1 with `featureGates: DynamicKubeletConfig: true`, then join a node (with `featureGates: DynamicKubeletConfig: true` as well)

## Anything else we need to know?

The line generating the error is [here](https://github.com/kubernetes/kubernetes/blob/8d1127cb41c9394a437e09728a25a3dcf4a4cadf/plugin/pkg/admission/noderestriction/admission.go#L356) and it is part of the noderestriction plugin; however it is not clear why it is failing, because the new node's configSource is nil

```
$ kubectl get node kubeadm-playground-node -o yaml
apiVersion: v1
kind: Node
metadata:
  ...
  name: kubeadm-playground-node
  ...
spec:
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    timeAdded: 2018-09-09T09:04:56Z
status:
  ...
  config: {}
  ...
```

The error seems not related to kubeadm specific logic, because it can be reproduced with `kubectl` following the procedure described [here](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/#kubectl-patch-example) 
```
sudo kubectl patch node kubeadm-playground-node -p "{\"spec\":{\"configSource\":{\"configMap\":{\"name\":\"kubelet-config-1.12\",\"namespace\":\"kube-system\",\"kubeletConfigKey\":\"kubelet\"}}}}" --kubeconfig /etc/kubernetes/kubelet.conf
```

**Comment by fabriziopandini** [comment]
/cc @mtaufen 
Any suggestion about how this can be fixed?

**Comment by fabiand** [comment]
Could this be the same as https://github.com/kubernetes/kubernetes/issues/68620#issue-359867124 ?

**Comment by mtaufen** [comment]
Nodes are not allowed to set their own config source to non-nil values, as this could allow a node to escalate privilege (e.g. by reading ConfigMaps it was not originally configured to have access to).

Since this is about kubeadm join, is it safe to assume that kubeadm has the same identity as the node when it tries to set the config source?
Are you identified as the node you are trying to patch when you run that kubectl command?

**Comment by mtaufen** [comment]
@luxas wrt kubeadm implementation

**Comment by neolit123** [comment]
^ @fabriziopandini

**Comment by fabriziopandini** [comment]
@mtaufen 
yes, kubeadm join uses kubelet identity, and if I got your answer right, with this identity dynamic kubelet config can't be initialised. Is that right?

If yes:
1) The fact is kubeadm using kubelet identity was not changed in this release, so however I don't understand how former release of kubeadm could work.... @luxas suggestions here?
2) And moving forward, how this can be fixed? the only Identity I have at hand when executing the joind workflow is the bootstrap token, and I'm not sure extending bootstrat token rights is a wise move.. @timothysc thoughts?

**Comment by mtaufen** [comment]
Yes, that's correct. 

Is there a doc with the reason behind this workflow that I can read to understand more?

Typically a controller (e.g. machine controller in Cluster API) or admin (e.g. via a rollout script) would set the dynamic config after the node was registered.

**Comment by fabriziopandini** [comment]
@mtaufen thanks for your answer.
I'm not aware of documents with rationals behind this, but I will dig a little more.

We should discuss at sig level how to remove the dynamic config step from the `kubeadm join` workflow and how to bring back this action to the controller/the admin.

/cc @timothysc

**Comment by MrD2** [comment]
I'm trying to update dynamic kubelet configSource from a cURL command from each minion after initialization and this error happens.

`until curl -vvv\
  --request PATCH --cacert ${CERT_DIR}/ca.crt \
  --cert ${CERT_DIR}/kubelet.crt --key ${CERT_DIR}/kubelet.key \
  -H 'Content-Type: application/json-patch+json' \
  -H 'Accept: application/json' \
  --data '[ {
          "op": "add",
          "path": "/spec/configSource",
          "value": {
            "configMap": {
              "name": "test",
              "namespace": "kube-system",
              "kubeletConfigKey": "kubelet"
            }
          }
        }]' \
      ${PROTOCOL}://${KUBE_MASTER_IP}:${KUBE_API_PORT}/api/v1/nodes/{`hostname | sed 's/.novalocal//'`}
do
    echo "Waiting for kubernedes dynamic kubelet node patch..."
    sleep 5
done`


And output

`*   Trying 10.0.0.18...
* TCP_NODELAY set
* Connected to 10.0.0.18 (10.0.0.18) port 6443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: PROFILE=SYSTEM
* successfully set certificate verify locations:
*   CAfile: /etc/kubernetes/certs/ca.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=kubernetes
*  start date: Nov  8 17:19:41 2018 GMT
*  expire date: Nov  8 17:19:41 2023 GMT
*  subjectAltName: host "10.0.0.18" matched cert's IP address!
*  issuer: CN=kube1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x558c1fbbff80)
> PATCH /api/v1/nodes/kube1-2l6rerez733u-minion-0 HTTP/2
> Host: 10.0.0.18:6443
> User-Agent: curl/7.55.1
> Content-Type: application/json-patch+json
> Accept: application/json
> Content-Length: 267
> 
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 403 
< content-type: application/json
< content-length: 341
< date: Mon, 12 Nov 2018 15:02:23 GMT
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "nodes \"kube1-2l6rerez733u-minion-0\" is forbidden: cannot update configSource to a new non-nil configSource",
  "reason": "Forbidden",
  "details": {
    "name": "kube1-2l6rerez733u-minion-0",
    "kind": "nodes"
  },
  "code": 403
* Connection #0 to host 10.0.0.18 left intact
}`

**Comment by timothysc** [comment]
This is only accessible via alpha command in 1.13
