### ISSUE TITLE
kube-controller-manager broken on HA upgrades from v1.11 to v1.12

### ISSUE THREAD

**Issue by detiber** [kubernetes/kubeadm#1103]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

v1.12-beta.1

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.12-beta.1

## What happened?

After performing an upgrade from v1.11 to v1.12-beta.1 on an HA environment kube-controller-manager is crashlooping.

## What you expected to happen?

kube-controller-manager instances to be running normally

## How to reproduce it (as minimally and precisely as possible)?

https://gist.github.com/detiber/98742a1db1151aa9a8aaaa3c219e061d

## Anything else we need to know?

The issue appears to be related to the delegated auth changes for kube-controller-manager: https://github.com/kubernetes/kubernetes/pull/64149

**Comment by timothysc** [comment]
@detiber - can we close this now?
