### ISSUE TITLE
kube-dns can't  READY

### ISSUE THREAD

**Issue by liaoqiArno** [kubernetes/kubeadm#1111]
OS: centos7
docker: 17.03
k8s:1.10

[root@k8s-node1 manifests]#  kubectl get all --all-namespaces
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
kube-system   calico-etcd-2qwx9                          1/1       Running            0          1h
kube-system   calico-kube-controllers-5c949c46bf-v5r96   1/1       Running            0          1h
kube-system   calico-node-9m7z6                          2/2       Running            0          57m
kube-system   calico-node-g6l68                          2/2       Running            0          40m
kube-system   etcd-k8s-node1                             1/1       Running            0          1h
kube-system   kube-apiserver-k8s-node1                   1/1       Running            0          1h
kube-system   kube-controller-manager-k8s-node1          1/1       Running            0          1h
kube-system   kube-dns-86f4d74b45-s9n5s                  1/3       CrashLoopBackOff   20         21m
kube-system   kube-proxy-52m58                           1/1       Running            0          1h
kube-system   kube-proxy-rcxk4                           1/1       Running            0          57m
kube-system   kube-scheduler-k8s-node1                   1/1       Running            0          1h

NAMESPACE     NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP         1h
kube-system   calico-etcd   ClusterIP   10.96.232.136   <none>        6666/TCP        1h
kube-system   kube-dns      ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP   1h

NAMESPACE     NAME          DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
kube-system   calico-etcd   1         1         1         1            1           node-role.kubernetes.io/master=   1h
kube-system   calico-node   2         2         2         2            2           beta.kubernetes.io/os=linux       1h
kube-system   kube-proxy    2         2         2         2            2           <none>                            1h

NAMESPACE     NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   calico-kube-controllers   1         1         1            1           1h
kube-system   kube-dns                  1         1         1            0           1h

NAMESPACE     NAME                                 DESIRED   CURRENT   READY     AGE
kube-system   calico-kube-controllers-5c949c46bf   1         1         1         1h
kube-system   kube-dns-86f4d74b45                  1         1         0         1h
[root@k8s-node1 manifests]#
[root@k8s-node1 manifests]#  kubectl get all --all-namespaces
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
kube-system   calico-etcd-2qwx9                          1/1       Running            0          1h
kube-system   calico-kube-controllers-5c949c46bf-v5r96   1/1       Running            0          1h
kube-system   calico-node-9m7z6                          2/2       Running            0          1h
kube-system   calico-node-g6l68                          2/2       Running            0          46m
kube-system   etcd-k8s-node1                             1/1       Running            0          1h
kube-system   kube-apiserver-k8s-node1                   1/1       Running            0          1h
kube-system   kube-controller-manager-k8s-node1          1/1       Running            0          1h
kube-system   kube-dns-86f4d74b45-s9n5s                  1/3       CrashLoopBackOff   24         26m
kube-system   kube-proxy-52m58                           1/1       Running            0          1h
kube-system   kube-proxy-rcxk4                           1/1       Running            0          1h
kube-system   kube-scheduler-k8s-node1                   1/1       Running            0          1h

NAMESPACE     NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP         1h
kube-system   calico-etcd   ClusterIP   10.96.232.136   <none>        6666/TCP        1h
kube-system   kube-dns      ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP   1h

NAMESPACE     NAME          DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
kube-system   calico-etcd   1         1         1         1            1           node-role.kubernetes.io/master=   1h
kube-system   calico-node   2         2         2         2            2           beta.kubernetes.io/os=linux       1h
kube-system   kube-proxy    2         2         2         2            2           <none>                            1h

NAMESPACE     NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   calico-kube-controllers   1         1         1            1           1h
kube-system   kube-dns                  1         1         1            0           1h

NAMESPACE     NAME                                 DESIRED   CURRENT   READY     AGE
kube-system   calico-kube-controllers-5c949c46bf   1         1         1         1h
kube-system   kube-dns-86f4d74b45                  1         1         0         1h

describe pod:
Events:
  Type     Reason                 Age                 From                Message
  ----     ------                 ----                ----                -------
  Normal   Scheduled              28m                 default-scheduler   Successfully assigned kube-dns-86f4d74b45-s9n5s to k8s-node2
  Normal   SuccessfulMountVolume  28m                 kubelet, k8s-node2  MountVolume.SetUp succeeded for volume "kube-dns-config"
  Normal   SuccessfulMountVolume  28m                 kubelet, k8s-node2  MountVolume.SetUp succeeded for volume "kube-dns-token-zknzh"
  Normal   Pulled                 28m                 kubelet, k8s-node2  Container image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8" already present on machine
  Normal   Started                28m                 kubelet, k8s-node2  Started container
  Normal   Created                28m                 kubelet, k8s-node2  Created container
  Normal   Pulled                 28m                 kubelet, k8s-node2  Container image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.8" already presenton machine
  Normal   Created                28m                 kubelet, k8s-node2  Created container
  Normal   Started                28m                 kubelet, k8s-node2  Started container
  Normal   Started                27m (x2 over 28m)   kubelet, k8s-node2  Started container
  Normal   Created                27m (x2 over 28m)   kubelet, k8s-node2  Created container
  Normal   Pulled                 27m (x2 over 28m)   kubelet, k8s-node2  Container image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.8" already present on machine
  Warning  Unhealthy              26m (x3 over 27m)   kubelet, k8s-node2  Liveness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy              18m (x38 over 28m)  kubelet, k8s-node2  Readiness probe failed: Get http://192.168.169.198:8081/readiness: dial tcp 192.168.169.198:8081: getsockopt: connection refused
  Warning  BackOff                8m (x21 over 13m)   kubelet, k8s-node2  Back-off restarting failed container
  Warning  BackOff                3m (x81 over 24m)   kubelet, k8s-node2  Back-off restarting failed container

**Comment by neolit123** [comment]
@liaoqiArno hello, are you using kubeadm?

**Comment by liaoqiArno** [comment]
> @liaoqiArno hello, are you using kubeadm?

yes，I used kubeadm.

**Comment by liaoqiArno** [comment]
> @liaoqiArno hello, are you using kubeadm?

yes，I used kubeadm.

**Comment by chrisohaver** [comment]
@bart0sh, It's hard to read, because the output is not enclosed in backticks (```) ... but it looks to be a kube-dns deployment, not coredns `kube-system kube-dns-86f4d74b45-s9n5s 1/3 CrashLoopBackOff 20 21m`

**Comment by bart0sh** [comment]
@chrisohaver True, it's kube-dns deployment. Thanks for pointing this out to me.

@liaoqiArno can you show the log of crashlooping kube-dns pod please?
you can do it by running kubectl logs -n kube-system <kube-dns pod name>

**Comment by jimcm** [comment]
I am seeing the same problem. Details:

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:13:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:17:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.4", GitCommit:"bf9a868e8ea3d3a8fa53cbb22f566771b3f8068b", GitTreeState:"clean", BuildDate:"2018-10-25T19:06:30Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:

I'm installing k8s on an Ubuntu VM running on qemu-kvm

- **OS** (e.g. from /etc/os-release):

Ubuntu VM is running 16.04.5 LTS (Xenial Xerus)

- **Kernel** (e.g. `uname -a`):

Linux mtpnjvzonap001 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?

I followed instructions at https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/ to launch k8s using kubeadm

## What you expected to happen?

I expected all the pods to come up, but the two coredns pods went into CrashLoopBackOff and stayed there

## How to reproduce it (as minimally and precisely as possible)?

    # kubeadm init --pod-network-cidr=10.32.0.0/12 
    # kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" 
    # kubectl taint nodes --all node-role.kubernetes.io/master-

Additional info: I'm behind a corporate firewall, so I set my proxy variables as follows BEFORE running kubeadm:

    # echo $http_proxy
    http://135.28.13.11:8080
    # echo $https_proxy
    http://135.28.13.11:8080
    # echo $no_proxy
    127.0.0.1,135.21.27.139,135.0.0.0/8,10.96.0.0/12,10.32.0.0/12

## Anything else we need to know?

Both coredns pods stay in CrashLoopBackOff

    # kubectl get pods  --all-namespaces -o wide
    NAMESPACE     NAME                                     READY     STATUS             RESTARTS   AGE       IP              NODE             NOMINATED NODE
    default       hostnames-674b556c4-2b5h2                1/1       Running            0          5h        10.32.0.6       mtpnjvzonap001   <none>
    default       hostnames-674b556c4-4bzdj                1/1       Running            0          5h        10.32.0.5       mtpnjvzonap001   <none>
    default       hostnames-674b556c4-64gx5                1/1       Running            0          5h        10.32.0.4       mtpnjvzonap001   <none>
    kube-system   coredns-78fcdf6894-s7rvx                 0/1       CrashLoopBackOff   18         1h        10.32.0.7       mtpnjvzonap001   <none>
    kube-system   coredns-78fcdf6894-vxwgv                 0/1       CrashLoopBackOff   80         6h        10.32.0.2       mtpnjvzonap001   <none>
    kube-system   etcd-mtpnjvzonap001                      1/1       Running            0          6h        135.21.27.139   mtpnjvzonap001   <none>
    kube-system   kube-apiserver-mtpnjvzonap001            1/1       Running            0          1h        135.21.27.139   mtpnjvzonap001   <none>
    kube-system   kube-controller-manager-mtpnjvzonap001   1/1       Running            0          6h        135.21.27.139   mtpnjvzonap001   <none>
    kube-system   kube-proxy-2c4tx                         1/1       Running            0          6h        135.21.27.139   mtpnjvzonap001   <none>
    kube-system   kube-scheduler-mtpnjvzonap001            1/1       Running            0          1h        135.21.27.139   mtpnjvzonap001   <none>
    kube-system   weave-net-bpx22                          2/2       Running            0          6h        135.21.27.139   mtpnjvzonap001   <none>


coredns pods have this in their log

    # kubectl logs -n kube-system  coredns-78fcdf6894-s7rvx
    E1121 22:38:41.119752       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:313: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
    E1121 22:38:41.119781       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:320: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
    E1121 22:38:41.119864       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout


This suggests to me that coredns cannot access apiserver pod using its cluster IP:

    # kubectl describe svc/kubernetes
    Name:              kubernetes
    Namespace:         default
    Labels:            component=apiserver
                       provider=kubernetes
    Annotations:       <none>
    Selector:          <none>
    Type:              ClusterIP
    IP:                10.96.0.1
    Port:              https  443/TCP
    TargetPort:        6443/TCP
    Endpoints:         135.21.27.139:6443
    Session Affinity:  None
    Events:            <none>


I also went through the troubleshooting steps at https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/

 - I created a busybox pod for testing
 - I created the hostnames deployment successfully 
 - I exposed the hostnames deployment successfully
 - From the busybox pod, I accessed the hostnames service by its cluster IP successfully
 - from the node, I accessed the hostnames service by its cluster IP successfully

So in short, I created the hostnames service which had a cluster IP in 10.96.0.0/12 space (as expected), and it works, but for some reason, pods cannot access the apiserver's cluster IP of 10.96.0.1, though from the node I can access 10.96.0.1:

    # wget --no-check-certificate https://10.96.0.1/hello
    --2018-11-14 21:44:25--  https://10.96.0.1/hello
    Connecting to 10.96.0.1:443... connected.
    WARNING: cannot verify 10.96.0.1's certificate, issued by ‘CN=kubernetes’:
      Unable to locally verify the issuer's authority.
    HTTP request sent, awaiting response... 403 Forbidden
    2018-11-14 21:44:25 ERROR 403: Forbidden.

Some other things I checked, based on advice from others who reported a similar problem:

    # sysctl net.ipv4.conf.all.forwarding
    net.ipv4.conf.all.forwarding = 1
    # sysctl net.bridge.bridge-nf-call-iptables
    net.bridge.bridge-nf-call-iptables = 1
    # iptables-save | egrep ':INPUT|:OUTPUT|:POSTROUTING|:FORWARD'
    :INPUT ACCEPT [0:0]
    :OUTPUT ACCEPT [11:692]
    :POSTROUTING ACCEPT [11:692]
    :INPUT ACCEPT [1697:364811]
    :FORWARD ACCEPT [0:0]
    :OUTPUT ACCEPT [1652:363693]
    # ls -l /usr/sbin/conntrack
    -rwxr-xr-x 1 root root 65632 Jan 24  2016 /usr/sbin/conntrack
    # systemctl status firewalld
    ● firewalld.service
       Loaded: not-found (Reason: No such file or directory)
       Active: inactive (dead)


I checked the log for kube-proxy, did not see any errors. 
I also tried deleting coredns pods, apiserver pod; they are recreated (as expected), but the problem remains. 

Here's a copy of the log from the weave container

    # kubectl logs -n kube-system weave-net-bpx22 weave
    DEBU: 2018/11/14 15:56:10.909921 [kube-peers] Checking peer "aa:53:be:75:71:f7" against list &{[]}
    Peer not in list; removing persisted data
    INFO: 2018/11/14 15:56:11.041807 Command line options: map[name:aa:53:be:75:71:f7 nickname:mtpnjvzonap001 ipalloc-init:consensus=1 ipalloc-range:10.32.0.0/12 db-prefix:/weavedb/weave-net docker-api: expect-npc:true host-root:/host http-addr:127.0.0.1:6784 metrics-addr:0.0.0.0:6782 conn-limit:100 datapath:datapath no-dns:true port:6783]
    INFO: 2018/11/14 15:56:11.042230 weave  2.5.0
    INFO: 2018/11/14 15:56:11.198348 Bridge type is bridged_fastdp
    INFO: 2018/11/14 15:56:11.198372 Communication between peers is unencrypted.
    INFO: 2018/11/14 15:56:11.203206 Our name is aa:53:be:75:71:f7(mtpnjvzonap001)
    INFO: 2018/11/14 15:56:11.203249 Launch detected - using supplied peer list: [135.21.27.139]
    INFO: 2018/11/14 15:56:11.216398 Checking for pre-existing addresses on weave bridge
    INFO: 2018/11/14 15:56:11.229313 [allocator aa:53:be:75:71:f7] No valid persisted data
    INFO: 2018/11/14 15:56:11.233391 [allocator aa:53:be:75:71:f7] Initialising via deferred consensus
    INFO: 2018/11/14 15:56:11.233443 Sniffing traffic on datapath (via ODP)
    INFO: 2018/11/14 15:56:11.234120 ->[135.21.27.139:6783] attempting connection
    INFO: 2018/11/14 15:56:11.234302 ->[135.21.27.139:49182] connection accepted
    INFO: 2018/11/14 15:56:11.234818 ->[135.21.27.139:6783|aa:53:be:75:71:f7(mtpnjvzonap001)]: connection shutting down due to error: cannot connect to ourself
    INFO: 2018/11/14 15:56:11.234843 ->[135.21.27.139:49182|aa:53:be:75:71:f7(mtpnjvzonap001)]: connection shutting down due to error: cannot connect to ourself
    INFO: 2018/11/14 15:56:11.236010 Listening for HTTP control messages on 127.0.0.1:6784
    INFO: 2018/11/14 15:56:11.236424 Listening for metrics requests on 0.0.0.0:6782
    INFO: 2018/11/14 15:56:11.990529 [kube-peers] Added myself to peer list &{[{aa:53:be:75:71:f7 mtpnjvzonap001}]}
    DEBU: 2018/11/14 15:56:11.995901 [kube-peers] Nodes that have disappeared: map[]
    10.32.0.1
    135.21.27.139
    DEBU: 2018/11/14 15:56:12.075738 registering for updates for node delete events
    INFO: 2018/11/14 15:56:41.279799 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=ce66cb23-e825-11e8-abc3-525400314503&flag_kubernetes-version=v1.11.4&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 74.125.196.121:443: i/o timeout
    INFO: 2018/11/14 20:52:47.025412 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=ce66cb23-e825-11e8-abc3-525400314503&flag_kubernetes-version=v1.11.4&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 74.125.196.121:443: i/o timeout
    INFO: 2018/11/15 01:46:32.842792 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=ce66cb23-e825-11e8-abc3-525400314503&flag_kubernetes-version=v1.11.4&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 74.125.196.121:443: i/o timeout
    INFO: 2018/11/15 09:06:03.624359 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=ce66cb23-e825-11e8-abc3-525400314503&flag_kubernetes-version=v1.11.4&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 172.217.9.147:443: i/o timeout
    INFO: 2018/11/15 14:34:02.070893 Error checking version: Get https://checkpoint-api.weave.works/v1/check/weave-net?arch=amd64&flag_docker-version=none&flag_kernel-version=4.4.0-135-generic&flag_kubernetes-cluster-size=1&flag_kubernetes-cluster-uid=ce66cb23-e825-11e8-abc3-525400314503&flag_kubernetes-version=v1.11.4&os=linux&signature=EJdydeNysrC7LC5xAJAKyDvxXCvkeWUFzepdk3QDfr0%3D&version=2.5.0: dial tcp 172.217.9.147:443: i/o timeout

Here are the events for the 2 coredns pods

    # kubectl get events -n kube-system --field-selector involvedObject.name=coredns-78fcdf6894-6f9q6
    LAST SEEN   FIRST SEEN   COUNT     NAME                                        KIND      SUBOBJECT                  TYPE      REASON      SOURCE                    MESSAGE
    41m         20h          245       coredns-78fcdf6894-6f9q6.1568eab25f0acb02   Pod       spec.containers{coredns}   Normal    Killing     kubelet, mtpnjvzonap001   Killing container with id docker://coredns:Container failed liveness probe.. Container will be killed and recreated.
    26m         20h          248       coredns-78fcdf6894-6f9q6.1568ea920f72ddd4   Pod       spec.containers{coredns}   Normal    Pulled      kubelet, mtpnjvzonap001   Container image "k8s.gcr.io/coredns:1.1.3" already present on machine
    5m          20h          1256      coredns-78fcdf6894-6f9q6.1568eaa1fd9216d2   Pod       spec.containers{coredns}   Warning   Unhealthy   kubelet, mtpnjvzonap001   Liveness probe failed: HTTP probe failed with statuscode: 503
    1m          19h          2963      coredns-78fcdf6894-6f9q6.1568eb75f2b1af3e   Pod       spec.containers{coredns}   Warning   BackOff     kubelet, mtpnjvzonap001   Back-off restarting failed container
    # kubectl get events -n kube-system --field-selector involvedObject.name=coredns-78fcdf6894-skjwz
    LAST SEEN   FIRST SEEN   COUNT     NAME                                        KIND      SUBOBJECT                  TYPE      REASON      SOURCE                    MESSAGE
    6m          20h          1259      coredns-78fcdf6894-skjwz.1568eaa181fbeffe   Pod       spec.containers{coredns}   Warning   Unhealthy   kubelet, mtpnjvzonap001   Liveness probe failed: HTTP probe failed with statuscode: 503
    1m          19h          2969      coredns-78fcdf6894-skjwz.1568eb7578188f24   Pod       spec.containers{coredns}   Warning   BackOff     kubelet, mtpnjvzonap001   Back-off restarting failed container
    #1267 

I suspected this might be a problem with the pod network provider (weave). So I ran `kubeadm reset`, rebooted my VM for good measure, and ran `kubeadm init etc...` again, but this time using flannel as the pod network provider. I get exactly the same problem, codedns pods in CrashLookBackOff, with same error.

**Comment by liaoqiArno** [comment]
> @liaoqiArno hello, are you using kubeadm?

yes, I use kubeadm1.12.2

**Comment by timothysc** [comment]
closing, the original issue/open looked like it was stale but the recent update looks like a dupe of default fixes.
