### ISSUE TITLE
The kubeadm-config configmap which kubeadm uploaded is not raw.

### ISSUE THREAD

**Issue by youyongsong** [kubernetes/kubeadm#1116]
## Versions

**kubeadm version** (use `kubeadm version`): `v1.11.3`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `v1.11.3`
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **Kernel** (e.g. `uname -a`): `4.4.0-130-generic`
- **Others**:

## What happened?
The `kubeadm-config` configmap kubeadm uploaded is not the same as I passed to kubeadm, it expanded many default fields, but some fields are environment related like `api.advertiseAddress` field, it will cause problems when using kubeadm setup a second master.

## What you expected to happen?
kubeadm should upload the raw kubeadm-config file, should not upload the expanded one.

**Comment by rosti** [comment]
Hi @youyongsong and thanks for filing this issue!

Have you experienced any particular problems with this?

For the `api.advertiseAddress` this is actually fixed in the upcoming 1.12 release (as there is a map containing all available API server endpoints).
Also, expanding any unset fields to their defaulted values is preferred to be done before upload of the configuration. This is done in order to avoid having to expand it after download, which will be done per invocation and can produce different results, thus causing trouble.

**Comment by neolit123** [comment]
@rosti 
> Also, expanding any unset fields to their defaulted values is preferred to be done before upload of the configuration. This is done in order to avoid having to expand it after download, which will be done per invocation and can produce different results, thus causing trouble.

yes, absolutely.

@youyongsong 

> it will cause problems when using kubeadm setup a second master.

hm, i don't think so. we do have multi master setups guidelines in the docs and they work fine.
if you want to see config map improvements you should try 1.12 towards the end of the month.

until then i'm tempted to close this issue.
any objections?

/priority awaiting-more-evidence

**Comment by youyongsong** [comment]
Hello @rosti  , I experienced a problem caused by the expanded `api.advertiseAddress` field:
I use kubeadm to set up a ha k8s cluster, I create a kubeadm-config file on the first master and run `kubeadm init --config <kubeadm-config-file>`, then on other 2 masters I download the kubeadm-config file from configmap and use it to generate certs manifests and join current node as master.
The cluster looks good at the beginning, but when the first master is down the other 2 master's apiserver also crashed. 
Finally, I found that the apiserver manifests on the other masters have some problems, the `--advertise-address` argument and the address in the liveness probe are both set to the first master's private ip, because the `api.advertiseAddress` is generated on the first master.

**Comment by youyongsong** [comment]
@neolit123 thanks.
> hm, i don't think so. we do have multi master setups guidelines in the docs and they work fine.

It works fine with the official docs. I encountered this problem when I setup automation tools using the flow mentioned in [kep-0015(kubeadm join --control-plane workflow)](https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0015-kubeadm-join-control-plane.md).

**Comment by neolit123** [comment]
@youyongsong 

> Finally, I found that the apiserver manifests on the other masters have some problems, the --advertise-address argument and the address in the liveness probe are both set to the first master's private ip, because the api.advertiseAddress is generated on the first master.

it should update to the local bind address. you mention v1.11.3, so that could be an old bug.

>  I encountered this problem when I setup automation tools using the flow mentioned in kep-0015(kubeadm join --control-plane workflow).

hm, but this is something that is coming in 1.12 are you testing the current kubernetes master branch with `kubeadm join --control-plane` workflow?

/assign @fabriziopandini 
for feedback on `--join control-plane`.

**Comment by youyongsong** [comment]
@neolit123 
> hm, but this is something that is coming in 1.12 are you testing the current kubernetes master branch with kubeadm join --control-plane workflow?
No, I'm using kubernetes v1.11.3, I have an ansible project that wraps kubeadm, and I implemented the flow described in kep-0015 using ansible module.

**Comment by youyongsong** [comment]
@neolit123 I have tried kubeadm v1.12.2, the problem is resolved. I will close this issue.
