### ISSUE TITLE
write 1.12 themes and update the release notes

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1118]
the release notes doc is WIP for 1.12:
https://docs.google.com/document/d/1ZZkcIqDwUZiC77rhjA_XUGGsmAa9hyQ6nc5PXSX3LGI/edit

we need to add themes and verify / edit if the PR list is OK.

SIG WIP doc:
https://docs.google.com/document/d/1rbSO3_WpfcFoNqNvsuXl3y4Gkfhpdd2pOYC6YopVzBM/edit?usp=sharing

/kind documentation
/priority critical-urgent
/cc @kubernetes/sig-cluster-lifecycle

**Comment by dixudx** [comment]
An updated version has been moved to https://docs.google.com/document/d/1ZZkcIqDwUZiC77rhjA_XUGGsmAa9hyQ6nc5PXSX3LGI/edit.

**Comment by timothysc** [comment]
I'm going to run through this tonight or tomorrow.

**Comment by neolit123** [comment]
since the official doc does not allow direct edits (only suggestions) here is our own WIP doc:
https://docs.google.com/document/d/1rbSO3_WpfcFoNqNvsuXl3y4Gkfhpdd2pOYC6YopVzBM/edit?usp=sharing

**Comment by neolit123** [comment]
i have updated the list of PRs, removing duplicates.
also the WIP gdoc now has some ideas for the themes writeup.

**Comment by neolit123** [comment]
the PR list has been cleaned up, as much as we can.
the themes have been added in the form of a couple of sentences and a list of kubeadm features bellow.

**Comment by timothysc** [comment]
closing, this is done.
