### ISSUE TITLE
kubeadm blocks on "waiting for the kubelet to boot up the control plane..." resolved in this instance by symlinking /run/resolvconf to /run/systemd/resolve

### ISSUE THREAD

**Issue by poobalan-arumugam** [kubernetes/kubeadm#1124]
## What keywords did you search in kubeadm issues before filing this one?

- boot up the control plane
- kubeadm init timeout
- kubeadm resolve.conf
- kubeadm dns

I did find other similar sounding issues but none resolved my issue (excuse the pun).

BUG REPORT

## Versions

**kubeadm version**: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:59:42Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version**: Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: AWS instance

- **OS**

NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"

- **Kernel**:

Linux labt1 4.4.0-1067-aws #77-Ubuntu SMP Mon Aug 27 13:22:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

**kubeadm config images list**

k8s.gcr.io/kube-apiserver-amd64:v1.11.3
k8s.gcr.io/kube-controller-manager-amd64:v1.11.3
k8s.gcr.io/kube-scheduler-amd64:v1.11.3
k8s.gcr.io/kube-proxy-amd64:v1.11.3
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd-amd64:3.2.18
k8s.gcr.io/coredns:1.1.3

## What happened?

kubeadm init times out (failure) after "waiting for kubelet to boot up the control plane".

- docker ps -a -n 10 shows nothing happening
- waiting lines in log:

> [controlplane] wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
> [controlplane] wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
> [controlplane] wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
> [etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
> [init] waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests" 
> [init] this might take a minute or longer if the control plane images have to be pulled
> 

- /var/log/messages indicates:

dns.go:159] CheckLimitsForResolvConf: open /run/systemd/resolve/resolv.conf: no such file or directory

- and further on:

kuberuntime_sandbox.go:41] GeneratePodSandboxConfig for pod "etcd-labt.com_kube-system(f585365a38b8ec09ab532034050cdc30)" failed: open /run/systemd/resolve/resolv.conf: no such file or directory

## What you expected to happen?

docker to be creating instances and init to succeed and return token.

## How to reproduce it (as minimally and precisely as possible)?

On ubuntu 16.04 - I do not see a /run/systemd/resolve.

When I link (**ln -s /run/resolvconf/ /run/systemd/resolve**) before the timeout - then docker instances are created and init succeeds.
Otherwise I did a kubeadm reset followed again by 

kubeadm init --pod-network-cidr 10.240.0.0/16

which worked.

## Anything else we need to know?

The resolve link was it.

ln -s /run/resolvconf/ /run/systemd/resolve

/run/resolvconf/

/run/resolvconf/
├── enable-updates
├── interface
│   └── eth0.dhclient
└── resolv.conf

Kind Regards
murphy

**Comment by neolit123** [comment]
thanks for the report,

this is really outside of the scope of kubeadm.
the symlink is something distro specific and relates to systemd-resolved.

**Comment by neolit123** [comment]
^ @kubernetes/sig-cluster-lifecycle 
if anyone has objections.

**Comment by rcmelendez** [comment]
In case someone gets here and has CentOS 8/Rocky Linux, these are the commands I used to fix it:

`sudo mkdir -p /run/systemd/resolve`
`sudo ln -s /etc/resolv.conf /run/systemd/resolve/resolv.conf`

**Comment by minhhungit** [comment]
thanks @rcmelendez 
btw, in case file /etc/resolv.conf not exists or can not ping google, here is steps to fix: (https://stackoverflow.com/a/54460886/3007147)

Using Ubuntu 18.04, first disable systemd-resolved service.

> sudo systemctl disable systemd-resolved.service

Stop the service

> sudo systemctl stop systemd-resolved.service

Then, remove the link to /run/systemd/resolve/stub-resolv.conf in /etc/resolv.conf

> sudo rm /etc/resolv.conf

Add a manually created resolv.conf in /etc/

> sudo vim /etc/resolv.conf

Add your prefered DNS server there

> nameserver 8.8.8.8

Note: on stackoverflow nameserver is 208.67.222.222 but I used 8.8.8.8 and it works for me

**Comment by minhhungit** [comment]
there is a problem, everytime I reboot my server the file /run/systemd/resolve/resolv.conf is lost

> journalctl -xeu kubelet

```
/run/systemd/resolve/resolv.conf: no such file or directory
```

does anyone know how to fix it

**Comment by emvidi** [comment]
untested code from https://developers.redhat.com/blog/2016/09/20/managing-temporary-files-with-systemd-tmpfiles-on-rhel7

```
cat /usr/lib/tmpfiles.d/36-resolv.conf
d /run/systemd/resolve 0755 root root -
L /run/systemd/resolve/resolv.conf - - - - /etc/resolv.conf
```
