### ISSUE TITLE
Cleanup `util/config` packages; filenames and methods should be updated to use new names

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1125]
Package `k8s.io/kubernetes/cmd/kubeadm/app/util/config/` contains a set of function for dealing with kubeadm config files.

Filenames and methods name should be now updated to use new names of the kubeadm config types. e.g.:
MasterConfiguration --> InitConfiguration
NodeConfiguration --> JoinConfiguration

**Comment by RA489** [comment]
@fabriziopandini I want to take this.
