### ISSUE TITLE
Add support for `kubeadm config print-defaults --api-objects {componentConfig}` 

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1126]
`kubeadm config print-defaults` command lets user to get a defaulted config file.

The command supports a `--api-objects` flag that allows to filter the api objects that will be included in the output. Currently value supported by this flag are only `InitConfiguration`, `ClusterConfiguration` and `JoinConfiguration`.

Since in v1.12 component config were moved out from `ClusterConfiguration`, now the `--api-objects` flag should be modified in order to accept also component config api objects: `KubeletConfiguration` and `KubeProxyConfiguration`

**Comment by Klaven** [comment]
I will take this issue.

**Comment by Klaven** [comment]
@fabriziopandini Quick question, I saw some `TODO`'s in the code that is related to this ticket. do you all want me to include the todo's in the PR?

An example of this would be found here: https://github.com/kubernetes/kubernetes/blob/e9a3aaa44b0655e0ca67be6d460a4ef0774e0648/cmd/kubeadm/app/cmd/config.go#L175

Anyhow. I'm still working on this, just wanted to know if you all would like me to clean up the TODO's that are in the code I'm working with.
thanks

**Comment by fabriziopandini** [comment]
@Klaven 
The two changes are un-related, even if impacting the same source file, so IMO it will be better to make a separated PR

**Comment by Klaven** [comment]
This ticket looks to be working on current master. @fabriziopandini can confirm. ticket should be closed.

**Comment by fabriziopandini** [comment]
/close
many many thanks to @Klaven for help on investigating this ticket
