### ISSUE TITLE
Fix panic on "kubeadm alpha phase etcd" when invoked (improperly) with External Etcd

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1127]
`kubeadm alpha phase etcd` subcommand allows to invoke the generation of the static pod manifest for etcd.

This phase during the `kubeadm init` workflow is invoked only in clusters using a local etcd; however currently there is no such a filter in the `alpha phase etcd` subcommand, and when a user by mistake invokes this phase with a cluster configuration using external etcd instead, the command panics.

`kubeadm alpha phase etcd` should better handle this condition - `kubeadm alpha phase etcd` subcommand invoked with external etcd configuration - by printing "WARNING! etcd static pod manifest cannot be generated for cluster using external etcd"  and exit 1

**Comment by fabriziopandini** [comment]
Adding more context info for helping candidate first-time contributors:

kubeadm supports two types of etcd configurations, local etcd and external ectd.

Local etcd is the default configuration used by kubeadm, and consists on an etcd deployed as a static pod. The `kubeadm alpha phase etcd` allows to generate such static pod manifest (out of the kubeadm init workflow)

External etcd is an additional option, where kubeadm is instructed to connect to an existing etcd instance (and so kubeadm doesn't deploy any new etcd instance).
External etcd mode can be activated only using the kubeadm config file, as described here:
- https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file
- https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm#Etcd

This issue want to implement a better error handling for an inappropriate call to `kubeadm alpha phase etcd` with a configuration using an external etcd, that currently panics.

A possible solution for the fix (but feel free to propose better solutions 😉 ) should be implemented here
https://github.com/kubernetes/kubernetes/blob/a27adf1612d267b4460b420cec544ba4e3786cad/cmd/kubeadm/app/phases/etcd/local.go#L39
by returning an error in case an external etcd is used (the error will be then managed an returned to the user by the current `kubeadm alpha phase etcd` implementation)

The new behaviour should be tested here
https://github.com/kubernetes/kubernetes/blob/da5730e88346e028cc58130b01bf487da227f8bf/cmd/kubeadm/app/phases/etcd/local_test.go#L56

By modifying the test in order to validate more than one test cases (see f.i.  https://github.com/golang/go/wiki/TableDrivenTests or https://github.com/kubernetes/kubernetes/blob/da5730e88346e028cc58130b01bf487da227f8bf/cmd/kubeadm/app/phases/etcd/local_test.go#L87)

**Comment by ereslibre** [comment]
I'll take this one if nobody else is working on it :)

**Comment by neolit123** [comment]
@ereslibre
sure! please go ahead.
you can add questions in this issue if you have any.

also @ -ping us on the PR once submitted.

thanks.
