### ISSUE TITLE
kubeadm config print-default display incorrect version number

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#1134]
# BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:04:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:08:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
Brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04
- **Kernel** (e.g. `uname -a`):
Linux srv-xxic5 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:
$ docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.10.1
 Git commit:	7390fc6
 Built:	Wed Apr 18 01:23:11 2018
 OS/Arch:	linux/amd64

## What happened?
`kubeadm config print-default` outputs:

```
kubernetesVersion: v1.12.0
```

whereas `kubeadm init` states:

```
[init] using Kubernetes version: v1.11.3
```

followed by

```
[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.12.0-rc.1" Control plane version: "1.11.3"
```

## What you expected to happen?
The version output  in `print-default` should match the control plane version kubeadm intends to use (taking into account the various release-candidate activation flags etc) - so users can `grep` for it and use it to install the correct version of kubelet, etc.

## How to reproduce it (as minimally and precisely as possible)?
```
$ kubeadm config print-default
```
```
$ kubeadmin init --config my_config_file
```
The config file has no requested version number in it - expecting to default to `stable-1.11`

**Comment by PI-Victor** [comment]
i can confirm thi

```
[root@k8s-master-8dae0818-bdb0-11e8-9e4a-525400bceb07 manifests]# kubeadm init --pod-network-cidr=10.244.0.0/16
[init] using Kubernetes version: v1.11.3
[preflight] running pre-flight checks
[preflight] Some fatal errors occurred:
	[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.12.0-rc.1" Control plane version: "1.11.3"
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
[root@k8s-master-8dae0818-bdb0-11e8-9e4a-525400bceb07 manifests]# kubelet --version
Kubernetes v1.12.0-rc.1
[root@k8s-master-8dae0818-bdb0-11e8-9e4a-525400bceb07 manifests]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-rc.1", GitCommit:"3e4aee86dfaf933f03e052859c0a1f52704d4fef", GitTreeState:"clean", BuildDate:"2018-09-18T21:04:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
[root@k8s-master-8dae0818-bdb0-11e8-9e4a-525400bceb07 manifests]# kubeadm config print-default | grep -i kubernetesversion
kubernetesVersion: v1.12.0
```

**Comment by timothysc** [comment]
Until the release is cut you will need to pass `--kubernetes-version v1.12.0-rc.X` where `X=1,2`  

2 will be cut later this afternoon.
