### ISSUE TITLE
Kubeadm should support running master as unschedulable

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes/kubeadm#115]
When running kubelet with --register-schedulable=false, kubeadm hangs because it creates addons.

**Comment by luxas** [comment]
This will probably be possible when we've refactored the kubeadm API: https://github.com/kubernetes/kubeadm/pull/100

**Comment by pires** [comment]
I believe that at least the network add-ons should run on master too but would advise for DNS as well (the mandatory add-ons).

**Comment by luxas** [comment]
This is done via a master taint. Kubelet should not be run with `--register-schedulable`. Instead kubeadm automatically taints the master which makes it reject all pods except for kube-discovery, kube-proxy and kube-dns

**Comment by luxas** [comment]
I think this issue can be closed
