### ISSUE TITLE
kubeadm cannot use control plane images that are built locally

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1150]
steps to reproduce:
- build the control plane images locally and double check if they are tagged correctly - e.g. `v1.13.0-alpha.0.....`.
- start kubeadm and specify the same version.
- kubeadm fails because it wants to pull these images from the GCR bucket.

feature:
- make it possible for kubeadm to use images that are tagged locally.

i might be missing a trick on how this is possible without hacks, so if someone has ideas, please share?
AFAIK, currently the only reliable way to test a recent build is using `ci-cross/latest`, except that if you want to debug a control plane bug, your patch would not be available at GCR.

/cc @BenTheElder

**Comment by BenTheElder** [comment]
what I've done so far that works fine is:
- docker load the images
- don't use `kubeadm config images pull`, instead you can do `kubeadm config images list` then selectively pull images that are not `.*kube-.*`

**Comment by fabriziopandini** [comment]
Same here....

**Comment by timothysc** [comment]
There are multiple ways to get around this fwiw.  I have my own local registry.

**Comment by neolit123** [comment]
this falls into the land of debugging and i don't think we should add features for it, for now at least, unless there is user demand.
what we can do instead of adding features is document how to pre-load and to satisfy the kubeadm pre-pull not to fail.

**Comment by timothysc** [comment]
Can we close this or is there actual work or docs that folks want todo here.

**Comment by BenTheElder** [comment]
from my POV we're having no real issues with this in `kind`, not sure if @neolit123 wants to do anything further.
