### ISSUE TITLE
update kubernetes-anywhere to support only v1alpha3 post v1.12.0

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1151]
v1alpha2 was removed in master and this broke our k-a based tests, as expected.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-master/263

https://github.com/kubernetes/kubernetes/commit/bb8eec49345acc6084eab40b874e6263c4cd74c1

/assign @neolit123 
/cc @fabriziopandini 
/priority critical-urgent
/kind failing-test

**Comment by fabriziopandini** [comment]
Ideally we should consider v1beta1 as well

**Comment by neolit123** [comment]
the v1beta1 config can be pre-added this time in k-a so that we don't break CI in early 1.13.

**Comment by neolit123** [comment]
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-master
is back to green now, the rest of e2e should follow.

/close
