### ISSUE TITLE
Kubeadm does not provide meaniful error if config file did not even exist

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1158]
From  @seanhig  [comment](https://github.com/kubernetes/kubeadm/issues/1152#issuecomment-427017561) on #1152 

kubeadm returns 

```bash
[root@k8s-m1 admin]# kubeadm init --config kube-adm.yml
error converting YAML to JSON: yaml: line 4: found character that cannot start any token
```
 
When invoked with the kube-adm.yml file did not even exist.

**Comment by fabriziopandini** [comment]
@seanhig 
I tried to reproduce this use case, but when I pass a non existing file to kubeadm I got:

```bash
vagrant@kubeadm-playground-master:~$ sudo kubeadm init --config=/etc/kubernetes/kubeadm-configx.yml
unable to read config from "/etc/kubernetes/kubeadm-configx.yml" [open /etc/kubernetes/kubeadm-configx.yml: no such file or directory]
```

Could you kindly support me in reproducing your problem?

**Comment by timothysc** [comment]
@vincepri here is a good first issue.

**Comment by yagonobre** [comment]
Can't reproduce in `1.11`, `1.12` and master.

**Comment by seanhig** [comment]
I will see if I can re-produce it, but the versions have since been updated, and 1.12.1 is now the current version I’ve been working with, so I would have to spin up a new environment and revert to 1.12.0.  I’ll have a look this weekend.

**Comment by bart0sh** [comment]
@timothysc This can be closed, I believe. I hardly imaging that this kind of error would be possible with the file that doesn't exist.

**Comment by neolit123** [comment]
+1.
