### ISSUE TITLE
token changing when using v1alpha2 API

### ISSUE THREAD

**Issue by pmichali** [kubernetes/kubeadm#1164]
## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
Bare metal systems

- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"

- **Kernel** (e.g. `uname -a`):
Linux bxb-c2-78 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:
Using Lazyjack tool to provision K8s on bare-metal running IPv6. Essentially, is a wrapper for kubeadm. It sets up config files, routes, etc.

https://github.com/pmichali/lazyjack

## What happened?
When do `kubeadm init` and provide a pre-created token, the kubeadm output shows a different token and hash, than was pre-created. Minions cannot use the pre-computed values to join.

This is what I see, when using API version v1alpha2.

## What you expected to happen?
That the token and hash displayed will be the same as what was precomputed and therefore can be used on minion nodes.

This is what I see, when using API version v1alpha1.

## How to reproduce it (as minimally and precisely as possible)?
Use lazyjack tool to do `init` and `prepare` on master. After doing `up` command, you can see the output differs from the pre-generated token.

For example, after doing `init` and `prepare`, the config.yaml file I use with Lazyjack had:

```
general:
    token: "inidp0.97jita8a1qxw4vc9"
    token-cert-hash: "923b41d5a8e6e34d27dfb8b7119c6ac6c4a38f5206e70ff519eef686ecda7294"
```

The generated kubeadm.conf file has:
```
# Autogenerated file
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
api:
  advertiseAddress: "fd00:20::4"
networking:
  serviceSubnet: "fd00:30::/110"
nodeName: bxb-c2-79
token: "inidp0.97jita8a1qxw4vc9"
tokenTTL: 0s
apiServerExtraArgs:
  insecure-bind-address: "::"
  insecure-port: "8080"
  runtime-config: "admissionregistration.k8s.io/v1alpha1"
  feature-gates: AllAlpha=true
```

During the `up` command, I see this from the tool output (which has kubeadm output):

```
I1009 12:50:44.394986   16988 os_exec.go:16] Invoking: kubeadm init --config=/home/c2/bare-metal/work-area/kubeadm.conf
I1009 12:51:35.078812   16988 os_exec.go:22] Command "kubeadm" with args "init --config=/home/c2/bare-metal/work-area/kubeadm.conf" successful
I1009 12:51:35.078893   16988 up.go:189] Kubernetes init output: [init] using Kubernetes version: v1.11.3
[preflight] running pre-flight checks
[preflight/images] Pulling images required for setting up a Kubernetes cluster
[preflight/images] This might take a minute or two, depending on the speed of your internet connection
[preflight/images] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[preflight] Activating the kubelet service
[certificates] Using the existing ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [bxb-c2-79 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [fd00:30::1 fd00:20::4]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Generated etcd/ca certificate and key.
[certificates] Generated etcd/server certificate and key.
[certificates] etcd/server serving cert is signed for DNS names [bxb-c2-79 localhost] and IPs [127.0.0.1 ::1]
[certificates] Generated etcd/peer certificate and key.
[certificates] etcd/peer serving cert is signed for DNS names [bxb-c2-79 localhost] and IPs [fd00:20::4 127.0.0.1 ::1]
[certificates] Generated etcd/healthcheck-client certificate and key.
[certificates] Generated apiserver-etcd-client certificate and key.
[certificates] valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[controlplane] wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] this might take a minute or longer if the control plane images have to be pulled
[apiclient] All control plane components are healthy after 41.002342 seconds
[uploadconfig] storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.11" in namespace kube-system with the configuration for the kubelets in the cluster
[markmaster] Marking the node bxb-c2-79 as master by adding the label "node-role.kubernetes.io/master=''"
[markmaster] Marking the node bxb-c2-79 as master by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "bxb-c2-79" as an annotation
[bootstraptoken] using token: g03yow.wjgfrzb9tpdicpff
[bootstraptoken] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstraptoken] creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join [fd00:20::4]:6443 --token g03yow.wjgfrzb9tpdicpff --discovery-token-ca-cert-hash sha256:923b41d5a8e6e34d27dfb8b7119c6ac6c4a38f5206e70ff519eef686ecda7294
```

See how the token and hash are different? If I use API version v1alpha1, they are the same.

## Anything else we need to know?

The only change is the version in the kbueadm.conf file. Am I missing some other change?

I'll want to retry this all with v1alpha3 and Kubernetes 1.12 as well (with I guess a few more changes to kubeadm.conf - kind, apiEndpoint).

**Comment by neolit123** [comment]
> Autogenerated file

i don't think that's the autogenerated file from `print-default` in 1.11. i just verified that.
it looks like the v1alpha1 config.

alpha2 accepts a list of bootstrap tokens:
https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kubeadm/app/apis/kubeadm/v1alpha2/types.go#L39

so it should look like:

```
apiVersion: kubeadm.k8s.io/v1alpha2
...
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication

```

try running `kubeadm config migrate` on your file and using the output of that for your `kubeadm init`.

/priority needs-more-evidence

**Comment by pmichali** [comment]
Yes, this was an older 1.10 style config (with minimum info) that was used in 1.11 (as-is), and then I tried to modify to use v1alpha2 API.

I just tried the migrate script, and then used that and it seems to work, so this looks like an issue with the config file modifications.

Question: Is there a way to have the migration only the items that are specified and not provide all the default settings that are used for that version? Or will that potentially cause problems with   needed supporting settings (at defaults) to those that are specified?

The reason I ask is because the tool I'm using (and another tool), attempt to generate the kubeadm.conf file based on the K8s version being used, and the settings desired for the tool, and it would be nice to be able to specify the minimum file needed.

Any ideas?

**Comment by neolit123** [comment]
> Question: Is there a way to have the migration only the items that are specified and not provide all the default settings that are used for that version? Or will that potentially cause problems with needed supporting settings (at defaults) to those that are specified?

i think that's a side-effect of migrate and possibly we can have a separate feature request issue logged.
one problem here is that such a feature would be really low-priority for us as the migrate tool is really just a workaround until we get the config to GA (v1) - migrating from one pre-GA config to another.

after generating a default, you can technically omit any default settings manually and only keep the ones you need.

thanks.
