### ISSUE TITLE
kubeadm token create mix: --print-join-command and --config

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/kubeadm#1166]
## Versions
**kubeadm version** (use `kubeadm version`):
1.12.0 / 1.12.1
**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
```
kubeadm token create --print-join-command --config /etc/kubernetes/kubeadm-master.conf
```
Error:  **can not mix '--config' with arguments [print-join-command]**

complains that one cannot mix "--print-join-command" and "--config /etc/kubernetes/kubeadm-master.conf"

But:
- "--print-join-command" request cannot be put in the config file (afaik, please correct me)
- if we don't put the "--config /etc/kubernetes/kubeadm-master.conf" it complains that it cannot access the internet to get the version.

## What you expected to happen?
"--print-join-command" should be accepted even when the "--config" is configured.

## How to reproduce it (as minimally and precisely as possible)?
try the above command.

**Comment by neolit123** [comment]
> if we don't put the "--config /etc/kubernetes/kubeadm-master.conf" it complains that it cannot access the internet to get the version.

this should have been fixed before 1.12 was released.
checking...

**Comment by neolit123** [comment]
> if we don't put the "--config /etc/kubernetes/kubeadm-master.conf" it complains that it cannot access the internet to get the version.

yes so the above is not exactly true in 1.12.x.

```
lubo-it@luboitvbox:~/go/src/k8s.io/kubernetes$ kubeadm token create -v=4 --print-join-command
I1010 19:10:44.722484   15919 token.go:115] [token] validating mixed arguments
I1010 19:10:44.722530   15919 token.go:122] [token] getting Clientsets from KubeConfig file
I1010 19:10:44.726815   15919 token.go:219] [token] loading configurations
W1010 19:10:44.727148   15919 common.go:169] WARNING: could not obtain a bind address for the API Server: no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"; using: 0.0.0.0
I1010 19:10:44.727225   15919 version.go:156] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
I1010 19:10:44.728962   15919 version.go:89] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get https://dl.k8s.io/release/stable-1.txt: dial tcp: lookup dl.k8s.io on 127.0.0.53:53: server misbehaving
I1010 19:10:44.728991   15919 version.go:94] falling back to the local client version: v1.12.1
I1010 19:10:44.729181   15919 feature_gate.go:206] feature gates: &{map[]}
I1010 19:10:44.729203   15919 token.go:225] [token] creating token
```

note the:
`falling back to the local client version: v1.12.1` part...
so our fallback works.

@bart0sh
the PR is a workaround, but the original issue should not exists in the first place and we need to invetigate.

@ReSearchITEng 

could you add `-v=4` and show the output you get.

**Comment by bart0sh** [comment]
@neolit123 I'm not sure I understand why is it workaround. --print-join-command can't be put into the config, so ValidateMixedArguments will not allow to use it with --config. The PR fixes this the same way as it's fixed for similar cases: --ignore-preflight-errors --dry-run etc.

**Comment by neolit123** [comment]
@bart0sh 

i think the question here is why does one need to provide `--config` to the `kubeadm token create`?

i'm looking at the issue description and i'm a bit confused as well:
@ReSearchITEng please clarify on these points.

> --print-join-command" request cannot be put in the config file (afaik, please correct me)

no, do you need the config from anything else other than kuberentesVersion?

> if we don't put the "--config /etc/kubernetes/kubeadm-master.conf" it complains that it cannot access the internet to get the version.

i cannot reproduce that in 1.12, we had a patch that explicitly fixes that after a few dozen of reports by users with air-gapped use-cases.

**Comment by ReSearchITEng** [comment]
@neolit123 
The only reason I need --config is to specify the k8s version, because:
```
kubeadm token create --print-join-command --kubernetes-version v1.12.1
Error: unknown flag: --kubernetes-version
```
From https://github.com/kubernetes/kubeadm/issues/1152#issuecomment-428616112 I understand it won't be required in 1.13, when we'll be able to specify `--kubernetes-version` in more cases (**I guess** also when generating the token).

**Comment by neolit123** [comment]
understood, but why do you need to provide a version to `kubeadm token create`?

i'm assuming this gets us into this topic:
>> if we don't put the "--config /etc/kubernetes/kubeadm-master.conf" it complains that it cannot access the internet to get the version.

> i cannot reproduce that in 1.12, we had a patch that explicitly fixes that after a few dozen of reports by users with air-gapped use-cases.

**Comment by bart0sh** [comment]
@neolit123 
> i think the question here is why does one need to provide --config to the kubeadm token create.

I believe there are a lot of cases when it's much more convenient to put TTL, usages, groups and other token parameter into the config file than to specify them in the command line. Especially when kubeadm is called from other tools.

After all this was implemented for some reason, reviewed and merged, so people was able to see some value in it.

**Comment by neolit123** [comment]
yes, agreed. i was asking if there is a reason other than passing kubernetesVersion from the config as that was an air-gapped workaround.
