### ISSUE TITLE
kubeadm reset doesn't clean up custom etcd datadir

### ISSUE THREAD

**Issue by peterableda** [kubernetes/kubeadm#1169]
## Versions
**kubeadm version** (use `kubeadm version`):
[root@myk8s ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

## What happened?
Tried to init-reset-init which failed with the following preflight error:
```
[preflight] Some fatal errors occurred:
	[ERROR DirAvailable--path-to-etcd]: /path/to/etcd is not empty
```

## What you expected to happen?
The kubeadm reset should check whether the local etcd is using a custom dataDir and clean that directory instead of the default.
https://github.com/kubernetes/kubernetes/blob/488ac6825bacc766590adc9907b3cd5b327813f8/cmd/kubeadm/app/cmd/reset.go#L155

## How to reproduce it (as minimally and precisely as possible)?
```
$ cat kubeadmconfig.yaml
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
etcd:
  local:
    dataDir: "/path/to/etcd"
$ kubeadm init --config kubeadmconfig.yaml
...
$ kubeadm reset
...
$ kubeadm init --config kubeadmconfig.yaml
...
[preflight] Some fatal errors occurred:
	[ERROR DirAvailable--path-to-etcd]: /path/to/etcd is not empty
...
```

**Comment by neolit123** [comment]
thanks @yagonobre

**Comment by yagonobre** [comment]
@neolit123 is it better to get the etcd dataDir from a config flag or from the kubeadm-config configmap?

**Comment by neolit123** [comment]
@yagonobre 
i think for this case we should respect the local config.
