### ISSUE TITLE
Completely redesign the API configuration group

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#117]
Work in progress here: https://github.com/kubernetes/kubeadm/pull/100

**Comment by luxas** [comment]
There has been improvements in this area during the v1.8, but the beta push is deferred to v1.9

**Comment by jamiehannaford** [comment]
@luxas Should we focus on this for v1.10?

**Comment by luxas** [comment]
I might be able to do something related to this already in v1.9

**Comment by luxas** [comment]
This depends on ComponentConfig being ready for all components, which is gonna take quite some time.
We're tracking component-by-component progress in individual issues like #527 #528 and implementing ASAP in the meantime.

**Comment by timothysc** [comment]
@liztio I'm going to close this one in favor of your config issue, it's the same topic.
