### ISSUE TITLE
During Kubelet startup on node reboot, docker cri networking is used

### ISSUE THREAD

**Issue by ChiefAlexander** [kubernetes/kubeadm#1176]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): `v1.11.3`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `1.11.3`
- **Cloud provider or hardware configuration**: `Openstack`
- **OS** (e.g. from /etc/os-release): `OEL 7.5`
- **Kernel** (e.g. `uname -a`): `3.10.0-862.14.4.el7.x86_64 #1 SMP Tue Sep 25 17:20:38 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:
We utilize LVM for our filesystems and have a filesystem mounted to `/var/lib/kubelet`

## What happened?
After a node reboot the kubelet systemd service is started before our `/var/lib/kubelet` filesystem is ready. This ends up causing kubelet to use Docker CRI networking since systemd cannot read from the `/var/lib/kubelet/kubeadm-flags.env` file. The result is pods running on the Docker Bridge network even though everything within kubernetes appears to be correct (eg podcidr).

## What you expected to happen?
I would expect the systemd unit to wait until after it is able to read from its environment file.
For a work around we have added a dropin that Requires, and waits for After var-lib-kubelet.mount

## How to reproduce it (as minimally and precisely as possible)?
In order to test our dropin I removed the var-lib-kubelet filesystem from fstab and watched to see if the service would start. I am not sure how else this could be reproduced.

## Anything else we need to know?
Specifically our filesystem was in recovery.
```
Oct 18 13:35:55 systemd[1]: Mounting /var/lib/kubelet...

Oct 18 13:35:56 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Oct 18 13:35:56 systemd[1]: Starting kubelet: The Kubernetes Node Agent...

Oct 18 13:35:57 kernel: XFS (dm-9): Ending recovery (logdev: internal)
Oct 18 13:35:57 systemd[1]: Mounted /var/lib/kubelet.
Oct 18 13:35:57 systemd[1]: Reached target Remote File Systems.

Oct 18 13:35:58 systemd[1]: Started Kubernetes systemd probe.
Oct 18 13:35:58 systemd[1]: Starting Kubernetes systemd probe.
Oct 18 13:35:58 kubelet[1034]: I1018 13:35:58.546311    1034 server.go:408] Version: v1.11.3
```

Creating this issue so if anyone else has something similar happen they don't have to dig in. I am not sure if there is really anything that we should change with kubeadm's dropin since this might be isolated to how we are running our nodes filesystems.

**Comment by yagonobre** [comment]
I guess that it's not a kubeadm issue, so we can close it.

**Comment by MalloZup** [comment]
yop i think we could close since is a doc then a real-issue
