### ISSUE TITLE
Refactor directory fetching code

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1177]
FEATURE REQUEST
There are several places in the code where we need to get a directory to write files to. In some cases we use a dry-run env to indicate if we should create a temp directory or if we should return the real thing.

For example (not limited to these):

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/init.go#L329
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/postupgrade.go#L207

and here dry-run is ignored (maybe intentionally, but maybe not): https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/postupgrade.go#L227

As suggested by @neolit123 we should abstract this functionality to be shared across commands.

**Comment by padlar** [comment]
@chuckha i think i have a patch for this, can i create PR for this?

**Comment by joshuarubin** [comment]
Looks like this should probably be marked as active thanks to @padlar's work?

**Comment by neolit123** [comment]
so init.go saw a heavy refactor and such an utility is not longer needed there IMO.
for upgrades it seems that we still need it.

@padlar your PR was only against init.go, you can send a separate PR for upgrades if you want.

/remove-lifecycle active
