### ISSUE TITLE
Bad reference to controlManagerExtraArgs in v1alpha3 documentation

### ISSUE THREAD

**Issue by nkinkade** [kubernetes/kubeadm#1178]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

/kind documentation

## Versions

**kubeadm version** (use `kubeadm version`): N/A

**Environment**:
- **Kubernetes version** (use `kubectl version`): N/A
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Others**: N/A

## What happened?

The [documentation for v1alpha3](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1alpha3/doc.go#L213) seems to incorrectly reference `controlManangerExtraArgs`, which I believe should be `controllerManagerExtraArgs`  instead.

## What you expected to happen?

The documentation to represent the configuration terms correctly.

## How to reproduce it (as minimally and precisely as possible)?
N/A

## Anything else we need to know?
I don't know if it matters, but [v1beta1 seems to have the same issue](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta1/doc.go#L205).

**Comment by neolit123** [comment]
@nkinkade thanks good catch...
if anyone wants to fix this it would be a matter of modifying the mentioned locations:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta1/doc.go#L205
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1alpha3/doc.go#L213

but we also have the typo in the release-1.12 branch:
https://github.com/kubernetes/kubernetes/blob/release-1.12/cmd/kubeadm/app/apis/kubeadm/v1alpha3/doc.go#L86

**Comment by yuexiao-wang** [comment]
I would like to fix it.
/assign

**Comment by yuexiao-wang** [comment]
@neolit123  please assign it to me. thanks

**Comment by neolit123** [comment]
@yuexiao-wang 
sure, noted. just send the PRs when you are ready and reference this issue.
thanks.

/lifecycle active

**Comment by yuexiao-wang** [comment]
The typo of master is merged and the release-1.12 is updated.
