### ISSUE TITLE
Switch to github.com/pkg/errors

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1183]
Currently kubeadm code base uses `fmt.Errorf` both for wrapping errors and for creating new errors, but there is a general consensus on moving toward `github.com/pkg/errors`

e.g.
```golang
// wrapping errors
// from
fmt.Errorf("couldn't create a temporary directory: %v", err)
// to
errors.Wrap(err, "couldn't create a temporary directory")

// creating new errors
// from
fmt.Errorf("couldn't initialize a Kubernetes cluster")
// to
errors. New("couldn't initialize a Kubernetes cluster")
```

@timothysc @rosti @neolit123 @chuckha @detiber @liztio 
If there is consensus, this is a good issue for new contributors that can do this package by packages (or grouping packages)

**Comment by yuexiao-wang** [comment]
If there is consensus on this issue , I would like to work on it
I prefer to use errors.Wrap() and errors.New()

**Comment by neolit123** [comment]
@yuexiao-wang hi, we should use errors.Wrap() and errors.New().

thanks a lot for the help.
/lifecycle active

**Comment by yuexiao-wang** [comment]
@neolit123  thanks, i am ready to go

**Comment by joshuarubin** [comment]
I've started picking off a few packages for this (see kubernetes/kubernetes#70272).

**Comment by yuexiao-wang** [comment]
@joshuarubin You maybe do some repeated work？ I have modify almost packages for this issue.
Please check your PR.

**Comment by neolit123** [comment]
folks please observe if a help-wanted issue has a `/lifecycle active` label, which means that someone is already working on it. e.g. https://github.com/kubernetes/kubeadm/issues/1183#issuecomment-432219437

**Comment by joshuarubin** [comment]
Ah! Sorry about that! I'm new to the project and wasn't familiar with what `/lifecycle active` meant. Feel free to take any of my work if there's anything you haven't yet done. I'll stand down on this.

**Comment by qingsenLi** [comment]
@yuexiao-wang I add other packages in /kubeadm/app/ as follows:
cmd/kubeadm/app/constants
cmd/kubeadm/app/features
cmd/kubeadm/app/preflight

**Comment by yuexiao-wang** [comment]
ok. 
the rest of kubeadm packeages will be appended into my PR https://github.com/kubernetes/kubernetes/pull/70271
