### ISSUE TITLE
--cluster-dns do check invalid network

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/kubeadm#1184]
when i do below config:
```
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.53.0.10 --cluster-domain=cluster.local"
```
The kube-dns auto change to
```
kube-system    kube-dns                          ClusterIP   10.48.0.10
```
While i still use 10.53.0.* to config the clusterIP for my service.

Obviously, it can not intercommunicate.

The kube-dns can auto change to valid network is a great feather, but it do not make any warning which make me spend too much time debug why my service do not work.

Maybe check and add a waning here is better.

```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by timothysc** [comment]
@daixiang0 I'm confused by what you're requesting, this doesn't appear to be a kubeadm issue.

**Comment by daixiang0** [comment]
Sorry, since the config named as `10-kubeadm.conf`
