### ISSUE TITLE
cluster setup downloads pause image two times

### ISSUE THREAD

**Issue by Joerg-L** [kubernetes/kubeadm#1186]
## Versions
**kubeadm version**: v1.12.1

**Environment**:
- **Kubernetes version** : v1.12.1
- **Cloud provider or hardware configuration**: on-premis, vmware machine
- **OS** :  CentOS Linux release 7.5.1804 (Core) 
- **Kernel** : 3.10.0-862.14.4.el7.x86_64
- **Others**:

## What happened?
We are using Artifactory to proxy any external repository (Docker, RPM, etc) because normally our servers are not able to access internet directly.

Why trying to setup a kubernetes cluster, we are using kubeadm init with following config file

> apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
imageRepository: google-containers
apiserver-advertise-address: 172.28.16.82
pod-network-cidr: 10.244.0.0/16
kubernetes-version: v1.12.1

In addition to that, we have a daemon.json file which points docker to our Artifactory Instance
> {
"insecure-registries":["fqdn of artifactory"],
  "registry-mirrors": ["http://fqdn of artifactory"]
}

During the several first runs, the setup failed and the reason was almost unclear.
For testing, we have activated internet access for the server and after this, setup works fine.

We observer, while the setup is running that the required docker images are pulled fine from Artifactory
> [root@vmkubei02 ~]# docker images
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
google-containers/kube-proxy                v1.12.1             61afff57f010        2 weeks ago         96.6MB
google-containers/kube-scheduler            v1.12.1             d773ad20fd80        2 weeks ago         58.3MB
google-containers/kube-apiserver            v1.12.1             dcb029b5e3ad        2 weeks ago         194MB
google-containers/kube-controller-manager   v1.12.1             aa2dd57c7329        2 weeks ago         164MB
google-containers/etcd                      3.2.24              3cab8e1b9802        4 weeks ago         220MB
google-containers/coredns                   1.2.2               367cdc8433a4        8 weeks ago         39.2MB
google-containers/pause                     3.1                 da86e6ba6ca1        10 months ago       742kB
[root@vmkubei02 ~]#

how ever, during some later steps of the setup we observed that the pause images is requested a second time

> [root@vmkubei02 ~]# docker images
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
google-containers/kube-proxy                v1.12.1             61afff57f010        2 weeks ago         96.6MB
google-containers/kube-apiserver            v1.12.1             dcb029b5e3ad        2 weeks ago         194MB
google-containers/kube-controller-manager   v1.12.1             aa2dd57c7329        2 weeks ago         164MB
google-containers/kube-scheduler            v1.12.1             d773ad20fd80        2 weeks ago         58.3MB
google-containers/etcd                      3.2.24              3cab8e1b9802        4 weeks ago         220MB
google-containers/coredns                   1.2.2               367cdc8433a4        8 weeks ago         39.2MB
google-containers/pause                     3.1                 da86e6ba6ca1        10 months ago       742kB
**k8s.gcr.io/pause                            3.1                 da86e6ba6ca1        10 months ago       742kB**
[root@vmkubei02 ~]#

As the image k8s.gcr.io/pause was pulled from external, even if google-containers/pause  is identical, the setup fails if server has no access.

## What you expected to happen?
- Respect of setting imageRepository from config file for any download
-  not downloading pause image two times

**Comment by neolit123** [comment]
@Joerg-L thanks for the report.
first, please migrate to v1alpha3 if you are using 1.12.x  because the older config is no longer supported:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3

in the release-1.12 branch of k8s kubeadm is using the image repo from the config:
https://github.com/kubernetes/kubernetes/blob/release-1.12/cmd/kubeadm/app/images/images.go#L65

that output of the command `kubeadm config image list --kubernetes-version=v1.12.1` is what kubeadm will use in your case.

any other images you can delete.

/priority needs-more-evidence

**Comment by Joerg-L** [comment]
@neolit123 thanks for the first feedback.
I will change the setting in config right now and come back to you

In the meantime, hiere is the output of the command
> [root@vmkubei02 manifests]# kubeadm config images list --kubernetes-version=v1.12.1
k8s.gcr.io/kube-apiserver:v1.12.1
k8s.gcr.io/kube-controller-manager:v1.12.1
k8s.gcr.io/kube-scheduler:v1.12.1
k8s.gcr.io/kube-proxy:v1.12.1
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd:3.2.24
k8s.gcr.io/coredns:1.2.2

**Comment by Joerg-L** [comment]
@neolit123 
I have 
- reset cofniguration with kubeadm reset
- delete all images with docker rmi imagename
so I'm starting completely fresh.

I have change my config file as follow
> apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
imageRepository: google-containers
apiserver-advertise-address: 172.28.16.82
pod-network-cidr: 10.244.0.0/16
kubernetes-version: v1.12.1

And run kubeadmin init again
`[root@vmkubei02 ~]# kubeadm init --config /tmp/kube_config.yml 
[init] using Kubernetes version: v1.12.1
[preflight] running pre-flight checks
[preflight/images] Pulling images required for setting up a Kubernetes cluster
[preflight/images] This might take a minute or two, depending on the speed of your internet connection
[preflight/images] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[preflight] Activating the kubelet service`
images are fetched from Artifactory.

The later steps
`[controlplane] wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests" 
[init] this might take a minute or longer if the control plane images have to be pulled
[apiclient] All control plane components are healthy after 20.001943 seconds`
seams to pull from external

>[root@vmkubei02 ~]# docker images        
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
google-containers/kube-proxy                v1.12.1             61afff57f010        2 weeks ago         96.6MB
google-containers/kube-scheduler            v1.12.1             d773ad20fd80        2 weeks ago         58.3MB
google-containers/kube-apiserver            v1.12.1             dcb029b5e3ad        2 weeks ago         194MB
google-containers/kube-controller-manager   v1.12.1             aa2dd57c7329        2 weeks ago         164MB
google-containers/etcd                      3.2.24              3cab8e1b9802        4 weeks ago         220MB
google-containers/coredns                   1.2.2               367cdc8433a4        8 weeks ago         39.2MB
google-containers/pause                     3.1                 da86e6ba6ca1        10 months ago       742kB
**k8s.gcr.io/pause                            3.1                 da86e6ba6ca1        10 months ago       742kB**
[root@vmkubei02 ~]#

**Comment by neolit123** [comment]
> imageRepository: google-containers

try removing this line and report back.

**Comment by Joerg-L** [comment]
> > imageRepository: google-containers
> 
> try removing this line and report back.

I have done this now.
As we see now on docker images 
> [root@vmkubei02 ~]# docker images
> REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
> **k8s.gcr.io**/kube-proxy                v1.12.1             61afff57f010        2 weeks ago         96.6MB
> **k8s.gcr.io**/kube-apiserver            v1.12.1             dcb029b5e3ad        2 weeks ago         194MB
> **k8s.gcr.io**/kube-controller-manager   v1.12.1             aa2dd57c7329        2 weeks ago         164MB
> **k8s.gcr.io**/kube-scheduler            v1.12.1             d773ad20fd80        2 weeks ago         58.3MB
> **k8s.gcr.io**/etcd                      3.2.24              3cab8e1b9802        4 weeks ago         220MB
> **k8s.gcr.io**/coredns                   1.2.2               367cdc8433a4        8 weeks ago         39.2MB
> **k8s.gcr.io**/pause                     3.1                 da86e6ba6ca1        10 months ago       742kB
> [root@vmkubei02 ~]# 

are pulled from external.
As normally the servers will have no internet access, this will not work in future.

With the line
 > imageRepository: google-containers

in the config, we see that 6 from 7 images are correctly pulled from Artifactory.
Also as mentiond we see that pause image is also pulled from Artifactory but it's also pulled a second time from k8s.gcr.io

**Comment by dims** [comment]
@Joerg-L Do you have logs from kubelet around the time the of the second pull?

**Comment by Joerg-L** [comment]
@dims 
this is the log from the whole kubeadm init run
[kubelet_log.txt](https://github.com/kubernetes/kubeadm/files/2515519/kubelet_log.txt)

**Comment by neolit123** [comment]
its the kubelet that is pulling this image, not kubeadm.
you should be able to override this from the config. let me create you an example...

**Comment by neolit123** [comment]
set the value for pod-infra-container-image and see how that goes.

have a look here:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3

this example combines cluster and init configs:
```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
imageRepository: google-containers
apiserver-advertise-address: 172.28.16.82
pod-network-cidr: 10.244.0.0/16
kubernetes-version: v1.12.1
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: "google-containers/pause 3.1"
```

**Comment by Joerg-L** [comment]
@neolit123 greate stuff. thank you.

I have change the config file, reset kubeadm and delete all images and now every image in docker is from "google-containers", so no external pull anymore.

Currently my firewall admins are not available but I will retest the setup after the server was disconnected from internet to ensure that the setup can now run offline.

I'm still wondering why a second pull, from the external location was done.
Why does this happend?

**Comment by neolit123** [comment]
if the flag pod-infra-container-image is left empty, it defaults to k8s.gcr.io/pause:3.1 and the kubelet goes for pulling the image from that location as this  image is mandatory for the kubelet to work.

but you are asking a good question. ideally kubeadm should be pulling all the images that the cluster needs and the kubelet should not be pulling any. one problem is that this cannot be disabled. also pod-infra-container-image is really something that makes sense for docker and not for other CRIs.

this is more of kubelet issue. our only solution for now is to do this - previously logged issues and PRs:
https://github.com/kubernetes/kubeadm/issues/1003
https://github.com/kubernetes/kubernetes/pull/66798

thanks.
