### ISSUE TITLE
Change FetchConfigFromFileOrCluster parameters to improve cmd upgrade, join and reset tests

### ISSUE THREAD

**Issue by yagonobre** [kubernetes/kubeadm#1188]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST
## What happened?
`configutil.FetchConfigFromFileOrCluster` and `configutil.loadInitConfigurationFromFile`use the `constants.KubernetesDir`

## What you expected to happen?
Make `KubernetesDir` a parameter in both so we can mock this on upgrade, join ad reset command tests.

**Comment by yagonobre** [comment]
@timothysc I'll work on that

**Comment by MalloZup** [comment]
@neolit123  i think we can close this right?

**Comment by neolit123** [comment]
i don't think we can yet.

**Comment by rosti** [comment]
@yagonobre I am actually doing some experimental work in that field, trying to share more code between InitConfiguration funcs, optimize stuff a bit and reduce the unnecessary usage of InitConfiguration.
So, on my side, I reduced the calls to this func to a single one and largely got it replaced by a func, that has almost the same signature, but fetches config solely from the cluster.

**Comment by yagonobre** [comment]
Thanks @rosti, I was off in the last 2 week due to kubecon, I'll take a look at this in a bit.

**Comment by neolit123** [comment]
can we close this @rosti ,@yagonobre ?

**Comment by yagonobre** [comment]
@neolit123 unfortunately not, I'll have a pr this week.

**Comment by yagonobre** [comment]
Move to 1.15

**Comment by neolit123** [comment]
> Move to 1.15

done.
