### ISSUE TITLE
Make RBAC the default authorization mode for kubeadm and create RoleBindings

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#119]
@andrewrynhard has been kind enough to create a PR where we're implemeting this: https://github.com/kubernetes/kubernetes/pull/39846

More information about is in that thread

**Comment by pires** [comment]
The PR is merged but the requirements for this to work are not clear. What Kubernetes version and/or flags are needed?

**Comment by luxas** [comment]
I think this is fixed; RBAC is implemented and RoleBindings for a default cluster are created automatically by kubeadm.
