### ISSUE TITLE
write "Kubernetes" consistently in cmd/kubeadm

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1191]
the cmd/kubeadm package contains some spellings of Kubernetes which is either lowercase (kubernetes) or have a typo e.g. ([kuberenets](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/certlist.go#L239)) in messages written to the user.

we need to create a PR to clean these typos and spellings.

**Comment by yagonobre** [comment]
I'm working on that

**Comment by neolit123** [comment]
thanks
/lifecycle active

**Comment by yagonobre** [comment]
I'm also making `KubeConfig`consistently
