### ISSUE TITLE
`kubeadm reset` doesn't disable/remove `kubelet`

### ISSUE THREAD

**Issue by drigz** [kubernetes/kubeadm#1194]
## BUG REPORT

Originally reported at https://github.com/kubernetes/kubernetes/issues/65165 but closed due to inactivity.

## Versions

**kubeadm version**: v1.12.2

**Environment**:
- **Kubernetes version**:  v1.12.2
- **Hardware configuration**:  amd64
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04

## What happened?

`kubeadm reset` stops the `kubelet` service, but doesn't disable or remove it. Restarting the system causes systemd to start the old kubelet service, which doesn't work because the static pod manifests have been removed.

## What you expected to happen?

From the `kubeadm reset` docs:

> This command reverts any changes made by kubeadm init or kubeadm join.

So I would expect that the `kubelet` service is removed automatically, or at least disabled.

## How to reproduce it (as minimally and precisely as possible)?

```
kubeadm init
kubeadm reset --force
systemctl status kubelet
# this says it's enabled
```

## Anything else we need to know?

This may also cause problems with `kubeadm init` after a restart, since the preflight check for port 10250 might fail. I haven't tested this.

**Comment by drigz** [comment]
Hmm, on second thoughts I filed this too soon. I believe the `kubelet` service is created (and possibly enabled) by `apt install kubelet`.

**Comment by neolit123** [comment]
yes, thats true.
kubeadm reset will stop the server but will not uninstall it!

> Restarting the system causes systemd to start the old kubelet service, which doesn't work because the static pod manifests have been removed.

we have plans to make the kubelet to not fail without being started from kubeadm.
cc @chuckha

**Comment by drigz** [comment]
Thanks! The problem I was worried about (Port-10250 failing) doesn't occur because kubelet immediately fails with `failed to load Kubelet config file`, so this is not a problem for me. Sorry for the noise!
