### ISSUE TITLE
Can't get kubeadm-config -o jsonpath={.data.MasterConfiguration}

### ISSUE THREAD

**Issue by RockyFu267** [kubernetes/kubeadm#1199]
**What happened**:
when upgraded from 1.11.3 to 1.12.1, the order cannot show any result, and it's an empty file.

`kubectl get configmap -n kube-system kubeadm-config -o jsonpath={.data.MasterConfiguration} > kubeadm-config.yaml`

How can I fix it？
PS: when upgraded from 10.5 to 11.3, the order can be used normally.

**What you expected to happen**:
I am unable to export cluster info-{.data.MasterConfiguration} now， that means cluster cannot be upgraded in the future;

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure if I did any abnormal action;

**Anything else we need to know?**:
When I upgraded from version 1.11.3 to version 1.12.1, kubelet could not start.
I have tried to do some changes to the kueblet configuration file.
Finally kubelet is normal.
The etcd cluster is external.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.5-->1.11.3-->1.12.1(now)
- Cloud provider or hardware configuration: aliyun
- OS (e.g. from /etc/os-release): centos7.5
- Kernel (e.g. `uname -a`): 3.10.0-693.2.2.el7.x86_64
- Install tools: kubeadm
- Others:
I can see the configmap of kubeadm-config&kubelet-config-1.11&kubelet-config-1.12.

/kind bug

**Comment by neolit123** [comment]
hi, please try `.data.ClusterConfiguration` and report back.

**Comment by RockyFu267** [comment]
@neolit123 Does this mean that I will use this command to upgrade in the future?

**Comment by neolit123** [comment]
this is the ClusterConfiguration. we are no longer storing the whole "MasterConfiguration" in the config map.

details on the config changes:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3

> Is the configuration content here enough to upgrade?

i think you are doing some sort of a manual upgrade?
have you looked at ths `kubeadm upgrade` [link](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/)?

you normally don't have to fiddle with kubectl manually when doing upgrades.

**Comment by RockyFu267** [comment]
This order can display all the information before.
`kubeadm upgrade plan`
This order can see the version information of each node and component before the upgrade.
But now there is no information output.
I don't know if it will affect the upgrade.
I don't mind if it doesn't affect the upgrade.
Thanks so much.
