### ISSUE TITLE
Missing validation of kubeconfig files in case of external CA mode

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1203]
As per comment https://github.com/kubernetes/kubernetes/pull/70098#discussion_r229320061

## What you expected to happen?

External CA mode requires that the uses provides all the certs - except certificate authorithy keys - and all the kubeconfig files.

However, the check for External CA mode validates certs (existance and validity) but does not validates kubeconfig files (nether existance nor validity), and this can lead to errors.

Instead, external CA mode test should check for kubeconfig files (existance and validity) too.

## Anything else we need to know?

A possible solution is to trigger the check as part of the external CA mode test [here](https://github.com/kubernetes/kubernetes/blob/50dffba0f3f21580c0ce433096a5e54575341224/cmd/kubeadm/app/phases/certs/certs.go#L315) but the most of the implementation should be done into [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go) reusing the validation logic already implemented [here](https://github.com/kubernetes/kubernetes/blob/50dffba0f3f21580c0ce433096a5e54575341224/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L237-L255)

**Comment by yagonobre** [comment]
I can work on this tomorrow
