### ISSUE TITLE
Expose the kubeadm join workflow as phases

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1204]
as per comment https://github.com/kubernetes/kubernetes/pull/70333#discussion_r229811268

in v1.12 we are exposing the kubeadm init workflow as phases, and moving all the other commands formerly hoster under `kubeadm alpha phase` to `kubeadm alpha` (without phases).
This re-shuffle includes also subcommands that are part of the kubeadm join workflow (e.g. `preflight node`, `kubelet config download`).

if there is consensus, we should start from those pieces and expose also the kubeadm join workflow as phases 

----

### plan:

old KEP for phases:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/0029-20180918-kubeadm-phases-beta.md

(neolit123): here is document for discussing the phases for join:
https://docs.google.com/document/d/1nkTy7r1pBZvQT_YnuGHEQ5MrQZBaC2A7frXxzd6y7m0/edit?usp=sharing

we need to evict the Run method from [join.go](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/join.go#L382) and move the logic to join phases.
the phase runner mechanic that we use in [init.go](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/init.go#L382) should be used for that.

**NOTE: the merging of PRs should happen in the exact order bellow.**

### list of phases, action items, PRs, assignees :

---

item: move the fetching of init configuration to `joinData struct` + prepare for phases.
assigned: @neolit123
- [x] PR: https://github.com/kubernetes/kubernetes/pull/73029

notes: we need to move the init config from Run() to joinData as an (e.g.) initConfig field.

**this is is a preliminary step and has to happen before everything else**

---

item: get args working for leaf phases 
assigned: @ereslibre 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/73487

---

item: phase name `preflight`
assigned: @MalloZup 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/73163

note: includes the following logic:
- general checks
- optional checks based on initConfig
- check if ready for additional control plane
- control plane checks

---

item: phase name `control-plane-prepare`
assigned: @ereslibre 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/73145

notes: function name is `PrepareForHostingControlPlane`

has these sub phases:
- `certs` (create PKI assets)
- `kubeconfig`
- `manifests`

plus an additional hidden phase named etcdCheck
- etcd check (`if initConfiguration.Etcd.External == nil` from PrepareForHostingControlPlane)

---

item: phase name `kubelet-start`
assigned: @yagonobre 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/73732

notes: function name is `BootstrapKubelet`
no sub phases, all logic in a single runner callback function.

---

item: phase name `control-plane-join`
assigned: @RA489 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/73452

notes: main function name is `PostInstallControlPlane` but also code from `Run()`

has these sub phases:
- `etcd-local`
- `upload-config`
- `mark-control-plane`

---

item: make a final check on the UX, with focus on args (e.g. evaluate if args should be made phase specific)

See document Auditing Join Phases
https://docs.google.com/document/d/1tqgjB_KJMeYAXHYqOuBKKpCLSzxVgSl-MUfXf7d8C8U/edit?usp=sharing

Decide on how to handle the extra arg (see comment on the issue)
https://github.com/kubernetes/kubeadm/issues/1375
assigned: TBD
- [ ] PR: 

Fix labels and help messages
assigned: @fabriziopandini 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/74834

First pass on flags (add missing flags, optimize usage of discovery flags)
assigned: @fabriziopandini
- [x] PR: https://github.com/kubernetes/kubernetes/pull/74751
- [x] PR: https://github.com/kubernetes/kubernetes/pull/74831

Second pass on flags (check and remove flags marked as why?)
assigned: @neolit123 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/75013

Cleanup of join output (all the message should be prefixed by the phase name, where possible print messages should be made equal to init)
assigned: @neolit123 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/74870

Cleanup of preflight checks (join call preflight twice; make the second call skip checks already executed by the first one or make a new preflight check function for join control-plane)
assigned: @neolit123 
- [x] PR: https://github.com/kubernetes/kubernetes/pull/74873

**Comment by yagonobre** [comment]
I can work on it in the next cycle
/assign @yagonobre
/lifecycle active

**Comment by fabriziopandini** [comment]
@yagonobre great! 
Looking forward for the draft of the list of phases to be implemented!

**Comment by neolit123** [comment]
/assign

we are going to track the work in this issue and possibly have volunteers help us with that.

after this PR merged:
https://github.com/kubernetes/kubernetes/pull/72442
we need to solidify/define the list of phases for join.

**Comment by ereslibre** [comment]
I'm also willing to help with this effort, as of todays kubeadm office hours meeting.

**Comment by RA489** [comment]
I can also help with this effort.

**Comment by neolit123** [comment]
@RA489 thanks, assigned.

as a reminder, please note that the PRs have to come in order.
preflight -> control plane -> .....

**Comment by ereslibre** [comment]
I can take `control-plane-prepare` phase

**Comment by MalloZup** [comment]
@neolit123  i can take the `prefligh` one

**Comment by neolit123** [comment]
thanks @ereslibre and @MalloZup .
the only vacant item now is `kubelet-start`

**Comment by yagonobre** [comment]
I can take kubelet-start

**Comment by neolit123** [comment]
thanks you @yagonobre

**Comment by neolit123** [comment]
the base pr for phases in join has merged.
@MalloZup you can start with the PR for preflight.

**Comment by MalloZup** [comment]
@neolit123 thx for infos. yop i'm looking at it :rocket:

**Comment by ereslibre** [comment]
`control-plane-prepare` phase is ready for review in https://github.com/kubernetes/kubernetes/pull/73145/

**Comment by neolit123** [comment]
thanks for everyone who contributed. all the PRs for phases are added.
we now need to focus on auditing them.

it will be OK to push bugfixes even after code freeze.

**Comment by neolit123** [comment]
i will help next week or later this week to verify the join phases.

also this doc already has outlined some nits (thanks @fabriziopandini )
https://docs.google.com/document/d/1tqgjB_KJMeYAXHYqOuBKKpCLSzxVgSl-MUfXf7d8C8U/edit#
(if you don't see the comments on the right of the screen - make sure you zoom out)

**Comment by neolit123** [comment]
we are pretty much done here, minus:
> Decide on how to handle the extra arg (see comment on the issue)
> #1375

which is for 1.15.

and auditing.

**Comment by neolit123** [comment]
closing this ticket as the work here is done.
leaving https://github.com/kubernetes/kubeadm/issues/1375 as as standalone ticket.
