### ISSUE TITLE
Review kubeadm package layout

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1205]
as per comment https://github.com/kubernetes/kubernetes/pull/70346#issuecomment-433856703 and https://github.com/kubernetes/kubernetes/pull/70333#discussion_r228758810

If there is consensus, kubeadm package layout should be aligned with other Kubernetes commands.

- `cmd/kubeadm` should be used only for the UX
- `pkg/kubeadm` should be introduces and host `apis` and all the other kubeadm packages

Additionally IMO:

1. phases (an UX concept) should not be reflected in the `pkg/kubeadm` sub tree
2. existing weirdness should be fixed (e.g. update inside /phases and vice-versa preflight outside /phases)
3. Everything code for UX should be removed from `pkg/kubeadm` (e.g. printf/kubeadm output)
4. util is abused/too crowded. it should be simplified.
5. documentation about what is the scope of each package should be added
6. expose the kubeadm backend as vendorable API ([xref](https://github.com/kubernetes/kubeadm/issues/1215))

**Comment by yuexiao-wang** [comment]
It is a similar issue about test utilites.  https://github.com/kubernetes/kubeadm/issues/1257

**Comment by fabriziopandini** [comment]
Not yet. 
I think that this will be discussed in v1.14 planning (this week or the week after kubeconfig)

> It is a similar issue about test utilites. #1257
Similar, but not overlapping

**Comment by yuexiao-wang** [comment]
Got it.  https://github.com/kubernetes/kubernetes/pull/71702 will be hold and wait for v1.14 planning.

**Comment by MalloZup** [comment]
@fabriziopandini I would like to help on this. We might split this issue in small actionables issues. If you want we can talk about it in irc or here as you wish.

**Comment by fabriziopandini** [comment]
@luxas considering that this cycle seems there are people willing to help, it will be great to hear what do you think about this idea...

Cleaning up some tech debt and getting in better shape for enabling kubeadm vendoring in future are the main reason behind this.
What about trying to combine a meeting for a quick brainstorming on this topic?

**Comment by astrieanna** [comment]
/remove-help

because it isn't clear from the comments here if there is consensus or exactly what that consensus is.

**Comment by fabriziopandini** [comment]
/close 
in favor of https://github.com/kubernetes/kubeadm/issues/2316
