### ISSUE TITLE
Image prepull fails with PodSecurityPolicy present

### ISSUE THREAD

**Issue by praseodym** [kubernetes/kubeadm#1208]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.12.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.12.2
- **Cloud provider or hardware configuration**: VMware vSphere
- **OS** (e.g. from /etc/os-release): Debian 9 (Stretch)
- **Kernel** (e.g. `uname -a`): `Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08)`
- **Others**: PodSecurityPolicy is enabled and [configured](https://gist.github.com/praseodym/88ea84fef721f0da5ecf6b1f42ba77d7)

## What happened?
`kubeadm upgrade apply v1.12.2` hangs on the 'upgrade/prepull' stage:
```
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler etcd]
[upgrade/prepull] Prepulling image for component etcd.
[upgrade/prepull] Prepulling image for component kube-apiserver.
[upgrade/prepull] Prepulling image for component kube-controller-manager.
[upgrade/prepull] Prepulling image for component kube-scheduler.
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
```
It turns out this is because the prepull pod doesn't specify in its security context that it will be run as root, and thus gets assigned a restricted pod security policy that requires it to run as non-root. This gets rejected with an `Error: container has runAsNonRoot and image will run as root` and the pod will not start.

## What you expected to happen?
Pod starts and continues without problems, even with a restricted PodSecurityPolicy. This can be achieved by specifying `runAsNonRoot: false` in the pod's security context (which ensures it gets assigned a more privileged PodSecurityPolicy) or by specifying some non-root user that the pod should run as (which will allow it to run under the restricted PodSecurityPolicy).

## How to reproduce it (as minimally and precisely as possible)?
Enable restricted pod security policy and execute `kubeadm upgrade apply`.

## Anything else we need to know?
A workaround is to patch the prepull pods' specs after they get registered by kubeadm:
```bash
for ds in $(kubectl -n kube-system get ds -o name | grep prepull | cut -d/ -f2); kubectl -n kube-system patch ds $ds  -p'{"spec":{"template":{"spec":{"securityContext":{"runAsNonRoot":false}}}}}'; end
```

**Comment by timothysc** [comment]
I'm struggling to understand the user story specified in this issue, for example root is required for init/join/upgrade.   If you have more details please feel free to reopen.

**Comment by kfox1111** [comment]
Guessing based just on the original request, that they had setup a pod security policy and that is not allowing root by default. So its blocking kubeadm from launching stuff in kube-system namespace.

It could be argued that its a misconfiguration by the user.

It would be very handy though if kubeadm registered its own permissions that it needed for working when podsecuritypolicy is enabled though. In that case, this is a legitimate issue to keep open.

**Comment by neolit123** [comment]
i can try sending a fix for that for 1.15, but if anyone else wants it please go ahead.

**Comment by neolit123** [comment]
cannot be reproduced with the latest master and the given PSP:
> Others: PodSecurityPolicy is enabled and [configured](https://gist.github.com/praseodym/88ea84fef721f0da5ecf6b1f42ba77d7)

```
$ sudo kubeadm upgrade apply --force v1.15.0-alpha.3
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade/version] You have chosen to change the cluster version to "v1.15.0-alpha.3"
[upgrade/versions] Cluster version: v1.14.1
[upgrade/versions] kubeadm version: v1.15.0-alpha.3
[upgrade/version] Found 1 potential version compatibility errors but skipping since the --force flag is set: 

	- Specified version to upgrade to "v1.15.0-alpha.3" is an unstable version and such upgrades weren't allowed via setting the --allow-*-upgrades flags
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler etcd]
[upgrade/prepull] Prepulling image for component etcd.
[upgrade/prepull] Prepulling image for component kube-controller-manager.
[upgrade/prepull] Prepulling image for component kube-apiserver.
[upgrade/prepull] Prepulling image for component kube-scheduler.
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-etcd
[upgrade/prepull] Prepulled image for component etcd.
[upgrade/prepull] Prepulled image for component kube-apiserver.
[upgrade/prepull] Prepulled image for component kube-controller-manager.
[upgrade/prepull] Prepulled image for component kube-scheduler.
[upgrade/prepull] Successfully prepulled the images for all the control plane components
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.15.0-alpha.3"...
Static pod: kube-apiserver-luboitvbox hash: d26df524eb56353b9f182898d49c5540
Static pod: kube-controller-manager-luboitvbox hash: a1825adb865bb94fdbb55304aec7b36e
Static pod: kube-scheduler-luboitvbox hash: cec431cc95dc0ac9329d95795c76be1a
[upgrade/etcd] Upgrading to TLS for etcd
[upgrade/staticpods] Writing new Static Pod manifests to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests351632083"
[upgrade/staticpods] Preparing for "kube-apiserver" upgrade
[upgrade/staticpods] Renewing "apiserver-etcd-client" certificate
[upgrade/staticpods] Renewing "apiserver" certificate
[upgrade/staticpods] Renewing "apiserver-kubelet-client" certificate
[upgrade/staticpods] Renewing "front-proxy-client" certificate
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-apiserver.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-05-12-02-18-21/kube-apiserver.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
Static pod: kube-apiserver-luboitvbox hash: d26df524eb56353b9f182898d49c5540
Static pod: kube-apiserver-luboitvbox hash: 43e51d173ab032c067e676b050611333
[apiclient] Found 1 Pods for label selector component=kube-apiserver
[upgrade/staticpods] Component "kube-apiserver" upgraded successfully!
[upgrade/staticpods] Preparing for "kube-controller-manager" upgrade
[upgrade/staticpods] Renewing certificate embedded in "controller-manager.conf" 
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-controller-manager.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-05-12-02-18-21/kube-controller-manager.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
Static pod: kube-controller-manager-luboitvbox hash: a1825adb865bb94fdbb55304aec7b36e
Static pod: kube-controller-manager-luboitvbox hash: d9dd62363963abfcf77e29e25e9713c8
[apiclient] Found 1 Pods for label selector component=kube-controller-manager
[upgrade/staticpods] Component "kube-controller-manager" upgraded successfully!
[upgrade/staticpods] Preparing for "kube-scheduler" upgrade
[upgrade/staticpods] Renewing certificate embedded in "scheduler.conf" 
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-scheduler.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-05-12-02-18-21/kube-scheduler.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
Static pod: kube-scheduler-luboitvbox hash: cec431cc95dc0ac9329d95795c76be1a
Static pod: kube-scheduler-luboitvbox hash: cd121922482ca014c9daf4cf21d3a9c1
[apiclient] Found 1 Pods for label selector component=kube-scheduler
[upgrade/staticpods] Component "kube-scheduler" upgraded successfully!
[upgrade/staticpods] Renewing certificate embedded in "admin.conf" 
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.15" in namespace kube-system with the configuration for the kubelets in the cluster
[kubelet-start] Downloading configuration for the kubelet from the "kubelet-config-1.15" ConfigMap in the kube-system namespace
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

[upgrade/successful] SUCCESS! Your cluster was upgraded to "v1.15.0-alpha.3". Enjoy!

[upgrade/kubelet] Now that your control plane is upgraded, please proceed with upgrading your kubelets if you haven't already done so.

$ kubectl get psp
NAME           PRIV    CAPS   SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
a-restricted   false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
c-moderate     false          RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
f-privileged   true    *      RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
```

the provided PSP is in action but the image pre-pull is not blocked.
i don't think anything changed in the related kubeadm code since 1.12.x, so maybe something else changed elsewhere.

/close

**Comment by neolit123** [comment]
@kfox1111 

> It would be very handy though if kubeadm registered its own permissions that it needed for working when podsecuritypolicy is enabled though. In that case, this is a legitimate issue to keep open.

i'd prefer if this is tracked in a separate issue. we haven't seen any requests about this yet.

**Comment by praseodym** [comment]
@neolit123 Thanks for the reply! I'm not quite sure why you cannot reproduce the issue. Was the `PodSecurityPolicy` admission controller enabled in your cluster?

What happened in my case is that the pods got assigned the `a-restricted` PSP, which includes a `MustRunAsNonRoot` rule. The description for `RunAsNonRoot` is incorrect: having it unset is not the same as explicitly setting `false`. This can be seen in the following code, which specifically triggers on `sc.RunAsNonRoot() == nil` and sets its value to `true`:

https://github.com/kubernetes/kubernetes/blob/ace60e8acb2c62e006884a654936d7e30a67824b/pkg/security/podsecuritypolicy/provider.go#L167-L173

**Comment by neolit123** [comment]
i forgot enabling the admission controller.

i can reproduce the problem, except that patching with `'{"spec":{"template":{"spec":{"securityContext":{"runAsNonRoot":false}}}}}'` does not work on my side, because the pods don't get assigned the `a-restricted` PSP.

please provide detailed reproduction steps - e.g.
- when do you add the PodSecurityPolicy controller? kubeadm by default has NodeRestriction which can conflict with PodSecurityPolicy.
- do you `kubectl apply` the policies before or after enabling the controller?
- how / when do you authorize the PSP?

thanks

**Comment by praseodym** [comment]
> * when do you add the PodSecurityPolicy controller? kubeadm by default has NodeRestriction which can conflict with PodSecurityPolicy.

My kubeadm `ClusterConfiguration` has the following setting configured:
```yaml
apiServer:
  extraArgs:
    enable-admission-plugins: NodeRestriction,PodSecurityPolicy
```

> * do you `kubectl apply` the policies before or after enabling the controller?

[First add policies, then enable the admission controller.](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#enabling-pod-security-policies)

> * how / when do you authorize the PSP?

Through [cluster roles](https://gist.github.com/praseodym/88ea84fef721f0da5ecf6b1f42ba77d7#file-psp-clusterroles-yaml) that ensure only administrator users can use the `f-privileged` role that allows privilege escalation.

Kubeadm upgrades use the admin.conf kubeconfig, which uses a certificate with the `system:masters` group. This group has access to all resources (`'*'`) by default, so it is allowed to use all PSPs (including the `c-moderate` and `f-privileged` PSPs that allow root containers).

> * do you patch with `{"runAsNonRoot":false` after `kubeadm upgrade apply` gets stuck on waiting for the DS pods?

Yes. Once kubeadm is stuck, a `kubectl describe pod` on the image prepull pod will diagnose the issue:

```
$ kubectl -n kube-system describe pod upgrade-prepull-etcd-rv5r4
...
Annotations:        container.apparmor.security.beta.kubernetes.io/etcd: runtime/default                               
                    kubernetes.io/psp: a-restricted                                                                                 
                    seccomp.security.alpha.kubernetes.io/pod: docker/default
...
Events:
  Type     Reason          Age              From                 Message
  ----     ------          ----             ----                 -------
  Normal   Scheduled       16s              default-scheduler    Successfully assigned kube-system/upgrade-prepull-etcd-rv5r4 to k8s-master
  Normal   SandboxChanged  8s               kubelet, k8s-master  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          6s (x4 over 9s)  kubelet, k8s-master  Container image "k8s.gcr.io/etcd:3.2.24" already present on machine
  Warning  Failed          6s (x4 over 9s)  kubelet, k8s-master  Error: container has runAsNonRoot and image will run as root
```
After patching the DS the pod starts fine and kubeadm continues.

**Comment by neolit123** [comment]
thanks for the details.

> enable-admission-plugins: NodeRestriction,PodSecurityPolicy
> ...
> First add policies, then enable the admission controller.

the `PodSecurityPolicy` is already enabled if present in `enable-admission-plugins`, so this happens before the PSP + authorization is applied.

if these plugins are both enabled from `kubeadm init --config...` i'm not getting any pods to start in 1.12.x and 1.14.x (which is expected).

however if i start with:
> enable-admission-plugins: NodeRestriction

then apply `psp.yaml` and `psp-clusterroles.yaml` and then modify `kube-apiserver.yaml` to only include `PodSecurityPolicy` the api-server pod shows up. if both `NodeRestriction,PodSecurityPolicy` are added the api-server pod does not show in `kubectl get po` with no apparent errors in the logs; i read somewhere that these controllers can conflict.

at this point i see this problem:
```
$ kubectl -n kube-system describe ds upgrade-prepull-etcd
...
  Warning  FailedCreate  45s (x15 over 2m8s)  daemonset-controller  Error creating: pods "upgrade-prepull-etcd-" is forbidden: unable to validate against any pod security policy: []
```

and

```
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
```

so no upgrade pods are created. i was able to get the pods to start once, but cannot reproduce this consistently with both 1.12.2 and 1.14.1.

**Comment by neolit123** [comment]
ok, apparently it takes a while before the pods get created after being stuck at:
```
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
```

i guess your patch is viable. i will send a PR, but assign some reviewers to inspect your clusterole+psp setup to verify if this our best option.

**Comment by neolit123** [comment]
there is discussion in the PR in flight.
moving ticket to 1.16 milestone.

**Comment by astrieanna** [comment]
/remove-help

because there's a PR in flight.
