### ISSUE TITLE
1.12.1 advertise address not applied in config.yaml

### ISSUE THREAD

**Issue by davejrt** [kubernetes/kubeadm#1213]
## What keywords did you search in kubeadm issues before filing this one?
config.yaml
advertiseaddress

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
`kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:43:08Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**:
Vagrant
- **OS** (e.g. from /etc/os-release):
```{
  architecture => "amd64",
  distro => {
    codename => "xenial",
    description => "Ubuntu 16.04.5 LTS",
    id => "Ubuntu",
    release => {
      full => "16.04",
      major => "16.04"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
  },
  selinux => {
    enabled => false
  }
}
```
- **Kernel** (e.g. `uname -a`):
`Linux kube-master 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?
Running `kubeadm init --config config.yaml` does not produce a cluster listening on the correct ipaddress/interface when multiple network interfaces exist on the server. Snippet from config file below.

```
root@kube-master:~/.ssh# cat /etc/kubernetes/config.yaml
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
apiEndpoint:
  advertiseAddress: 172.17.10.101
  bindPort: 6443
```

```

## What you expected to happen?

The `advertiseAddress` configuration is read by the init command, and the api is listening on the address specified in the yaml file


## How to reproduce it (as minimally and precisely as possible)?

Specify an advertiseAddress address and port in the config.yaml file on a host with multiple interfaces and see if the correct IP is being advertised by the cluster


## Anything else we need to know?

Previously worked on 1.11.3

**Comment by fabriziopandini** [comment]
@davejrt if I got your problem right the advertise address should be set using InitConfiguration, not in ClusterConfiguration.
See https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3 for more detail

**Comment by neolit123** [comment]
/close
@davejrt please re-open if the above solution does not work for you.

**Comment by davejrt** [comment]
Just wanted to say thanks for pointing this out. Helped a lot @fabianofranz
