### ISSUE TITLE
kubeadm upgrade will still pre-pull etcd image when specified --etcd-upgrade=false

### ISSUE THREAD

**Issue by youyongsong** [kubernetes/kubeadm#1214]
## Versions

**kubeadm version** (use `kubeadm version`): v1.12.1

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.11.2
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
When I run `kubeadm upgrade apply v1.12.1 --config <config_path> --etcd-upgrade=false` command to upgrade my kubernetes cluster, it will still pre-pull etcd image on each master node.

## What you expected to happen?
etcd image should not be pre-pulled when I specified `--etcd-upgrade=false` option.

## How to reproduce it (as minimally and precisely as possible)?
use kubeadm to upgrade a kubernetes cluster with `--etcd-upgrade=false` option.

**Comment by fabriziopandini** [comment]
+ etcd image should not be pre-pulled when external etcd is used (should be already the case, but worth a double check)
