### ISSUE TITLE
Provide a basic API

### ISSUE THREAD

**Issue by inercia** [kubernetes/kubeadm#1215]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Description

The only API currently provided by `kubeadm` is a _command line_ API. So users interested in using `kubeadm` from higher-level tools have to shell out `kubeadm` calls, and the only option for customizing its behaviour is by using flags, writting a config file and/or using kubeadm's `phases`.

Developers could be interested in using the `kubeadm`'s functionalties in a programatic way. So it would be good if `kubeadm` could provide at least some basic _golang_ API, so other tools could `import` the `kubeadm` library and do some basic things like initiating the cluster or joining an existing one... 

Might be related to #1205

**Comment by neolit123** [comment]
hi, no i don't think anyone is.
we should first do some decision making on how to proceed about it.

currently not a critical priority for 1.13.

**Comment by luxas** [comment]
You can use the `app/phases/*` packages today, which are aimed to be more "vendorable" than other code in kubeadm. We don't provide any guarantees for code stability though.
Implementing this kind of issue requires a full code review and written proposal.

**Comment by neolit123** [comment]
there is also a minor problem at the moment where `kubeadm/app/phases` imports `kubeadm/test`, which holds integration tests and utils.
this has to be fixed once we claim a backend vendorable.

**Comment by neolit123** [comment]
the process of exposing the backend is going to take a while.
we should start of by reserving a kubeadm office hours meeting for this in 2019 and discussing the tasks at hand.

**Comment by MalloZup** [comment]
hi @luxas @neolit123  yop, i agree we can make a meeting on it. 

In the meanwhile i could have a look on some minor issue like this one `kubeadm/test,` import
thx :sunflower:

**Comment by MalloZup** [comment]
@neolit123  ah thx for feedback ! any issue get fixed really quick here :smile_cat:

**Comment by fabriziopandini** [comment]
IMO this is related to https://github.com/kubernetes/kubeadm/issues/1205, I'm not sure if it make sense to have two separated issues

**Comment by neolit123** [comment]
added an bullet point about adding API in the OP of https://github.com/kubernetes/kubeadm/issues/1205
