### ISSUE TITLE
kubeadm reset is not idempotent

### ISSUE THREAD

**Issue by inercia** [kubernetes/kubeadm#1217]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

1.13.alpha.3, at cfd53d6dae55d8663b082ba5ab2bd6a6dc01b24f

**Environment**:
- **Kubernetes version**: 1.12.2
- **OS**: openSUSE/Leap
- **Kernel**: Linux laxe 4.12.14-lp150.12.22-default #1 SMP Sat Oct 13 05:05:16 UTC 2018 (09415e8) x86_64 x86_64 x86_64 GNU/Linux

## What happened?

I did `kubeadm reset --cri-socket=...` for `crio` when I realized I did not create my cluster with `crio` but  with `docker`. However, a second `kubeadm reset` with the right parameters failed because `kubeconfig` was removed on the first run.

## What you expected to happen?

I expected `kubeadm reset` to be idempotent and to go ahead with any neccessary cleanups, ignoring errors because of things that have already been reset. In my case, I expected to be able to run `kubeadm reset` again and `kubeadm` to stop the docker containers.

## How to reproduce it (as minimally and precisely as possible)?

Invoke `kubeadm reset` twice.

**Comment by yagonobre** [comment]
I can work on it

**Comment by yagonobre** [comment]
I can't reproduce that, also looking to the code the bug not seems to exist.
The first `reset` remove the files and the second just remove the containers.

```
root@kubeadm-lab:~# kubeadm init

root@kubeadm-lab:~# kubeadm reset --cri-socket=/path
[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] are you sure you want to proceed? [y/N]: y
[preflight] running pre-flight checks
[reset] stopping the kubelet service
[reset] unmounting mounted directories in "/var/lib/kubelet"
E1109 04:38:51.332937   19937 reset.go:145] [reset] failed to remove containers: output: time="2018-11-09T04:38:51Z" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
, error: exit status 1
[reset] deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes /var/lib/etcd]
[reset] deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

root@kubeadm-lab:~# kubeadm reset
[reset] WARNING: changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
[reset] are you sure you want to proceed? [y/N]: y
[preflight] running pre-flight checks
[reset] stopping the kubelet service
[reset] unmounting mounted directories in "/var/lib/kubelet"
[reset] no etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml". Assuming external etcd
[reset] please manually reset etcd to prevent further issues
[reset] deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]
[reset] deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
```

**Comment by inercia** [comment]
Maybe it is finding a valid `kubeconfig` anyway. I'm getting:

```
$ kubeadm reset --cri-socket=/var/run/dockershim.sock --cert-dir=/etc/kubernetes/pki --force --ignore-preflight-errors=fileexisting-crictl,isprivilegeduser,port-10250,service-docker,swap,systemverification --v=3
failed to load admin kubeconfig: open /root/.kube/config: no such file or directory
```
So maybe `/etc/kubernetes/admin.conf ` is being deleted on the first run but next runs are happy because a `/root/.kube/config` exists...

**Comment by yagonobre** [comment]
Thanks for the report, I find the bug, I'll send a pr soon
