### ISSUE TITLE
kubeadm/HA - Joining a second master the cluster fails while trying to annotate-cri

### ISSUE THREAD

**Issue by andrelop** [kubernetes/kubeadm#1218]
Choose one: **BUG REPORT**

**kubeadm version** (use `kubeadm version`):

```
root@master01:~# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:51:33Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
root@master01:~#
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):

```
root@master01:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 186.202.83.66:6443 was refused - did you specify the right host or port?
root@master01:~#
```

- **Cloud provider or hardware configuration**:

```
Bare-metal (03 masters), 02 nodes, 01 load-balancer (haproxy) for kubeapi-server
```

- **OS** (e.g. from /etc/os-release):

```
root@master01:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@master01:~#
```

- **Kernel** (e.g. `uname -a`):

```
root@master01:~# uname -a
Linux master01 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
root@master01:~#
```

- **Others**:

```
root@master01:~# docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:23:18 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:22:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
root@master01:~#
```

## What happened?

I'm trying to use the instructions given at https://kubernetes.io/docs/setup/independent/high-availability/ to create a k8s HA master setup. I'm using the 'stacked masters' mode (control plane and etcd members co-located).

Already bootstrapped the first master, trying to add the second stacked control plane now, everything went well until I tried to execute step *6. Deploy the control plane components and mark the node as a master:*.

When executing "kubeadm alpha phase kubelet config annotate-cri --config kubeadm-config.yaml" I get the following as output :

```
root@master02:~# kubeadm alpha phase kubelet config annotate-cri --config kubeadm-config.yaml
[upgrade/versions] kubeadm version: v1.12.2
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "master02" as an annotation
                timed out waiting for the condition
root@master02:~#
```

No, there's no ```/var/run/dockershim.sock``` on this second master, while there is one on the first master. I tried restarting docker on the second master, but it wasn't created. I suspect somehting else should be creating it, but isn't.

## What you expected to happen?

I expected the command which failed worked and then I could procced to the next steps and finish the HA master setup as indicated at https://kubernetes.io/docs/setup/independent/high-availability/ .

## How to reproduce it (as minimally and precisely as possible)?

Try to follow step-by-step the instructions given at https://kubernetes.io/docs/setup/independent/high-availability/ and see the error show while trying the **6. Deploy the control plane components and mark the node as a master:** step, more specifically the step : 

```kubeadm alpha phase kubelet config annotate-cri --config kubeadm-config.yaml```

## Anything else we need to know?

I don't know if this could be related, but I noticed the following output for the step 

```kubeadm alpha phase kubelet write-env-file --config kubeadm-config.yaml```

in the step **4. Run the kubeadm phase commands to bootstrap the kubelet:**.

/kind bug
/sig cluster-lifecycle

**Comment by andrelop** [comment]
One more info :

```
root@master01:~# ps auxwwf | grep bootstrap-kubelet | grep -v grep
root     15107  4.2  0.6 2282328 99904 ?       Ssl  15:50   4:18 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni
root@master01:~#
```
```
root@master02:~# ps auxwwf | grep bootstrap-kubelet | grep -v grep
root     17899  4.2  0.5 2428412 97120 ?       Ssl  16:23   2:52 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml
root@master02:~#
```
```
root@master03:~# ps auxwwf | grep bootstrap-kubelet | grep -v grep
root     13931  3.9  0.5 2123176 93704 ?       Ssl  16:31   2:22 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml
root@master03:~#
```

Notice that only ```kubelet``` on ```master01``` is running with ```--cgroup-driver=systemd``` (despite having ```cgroupDriver``` set to ```cgroupsfs``` on ```/var/lib/kubelet/config.yaml``` ). The others masters (```master02``` and ```master03```) are all running **without** a ```--cgroup-driver=systemd``` config option set (probably now reading it from their respective ```/var/lib/kubelet/config.yaml``` files).

Docker is se to use ```systemd``` as the value for its ```native.cgroupdriver``` option, on **all the three masters** :

```
root@master01:~# cat /etc/docker/daemon.json 
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
root@master01:~#
```

The file above is identifcal on all the three masters.

**Comment by andrelop** [comment]
One more issue related to this issue :

When trying to schedule pods on master02 or master03 (ie: kubernetes-dashboard) I noticed that pods were using IPs from the docker daemon IP range (172.17.0.0/16) instead of IPs from the Pod's CIDR range.

I noticed that this was due to the fact that on master02 and master03 the ```/var/lib/kubelet/kubeadm-flags.env``` file was **NOT** being created (on master01 it was created). I then created it manually on master01 and master02 and restarted kubelet on both.

After that, pods scheduled on these masters were correctly created using IPs from the Pod's CIDR (10.244.0.0/16 in my case).

Just for the record, the content of the ```/var/lib/kubelet/kubeadm-flags.env``` file is the following :

``
KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --network-plugin=cni
``

Hope it helps.

**Comment by neolit123** [comment]
1) this step is no longer needed for upgrades in 1.13.
`kubeadm alpha phase kubelet config annotate-cri --config kubeadm-config.yaml`

2) kubeadm auto-detects your Docker cgroup driver and you don't have to pass it via config:
https://kubernetes.io/docs/setup/independent/kubelet-integration/#providing-instance-specific-configuration-details

> I noticed that this was due to the fact that on master02 and master03 the /var/lib/kubelet/kubeadm-flags.env file was NOT being created (on master01 it was created). I then created it manually on master02 and master03 and restarted kubelet on both.

this should not happen.

this ticket seems to accumulate multiple topics.
please use separate ones if you are still having troubles.

/close
