### ISSUE TITLE
RFE Feature Gate Enable DNS CACHE 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#1220]
Tracking Issue https://github.com/kubernetes/kubernetes/issues/70707

What would you like to be added:
Support to run nodelocaldns addon

Why is this needed:
The feature runs a local dns cache on all cluster nodes to help with dns latency. Initial PR adds support on e2e/gce scripts. We want to extend this to other cluster creation tools.
#70555

This is the KEP: https://github.com/kubernetes/community/blob/master/keps/sig-network/0030-nodelocal-dns-cache.md
Follow up to the KEP - kubernetes/community#2842

/kind feature

**Comment by srueg** [comment]
I'm taking a shot at this: https://github.com/kubernetes/kubernetes/pull/71642
Feedback appreciated.

**Comment by luxas** [comment]
Thanks @srueg!

**Comment by neolit123** [comment]
closed the existing PRs let's discuss again how we want to approach this in the 1.15 cycle.

**Comment by timothysc** [comment]
IMO we should make this the default for 1.16 and update the deployment.

**Comment by stealthybox** [comment]
We aspire to enable users to do this with an addon operator + the upcoming kubeadm addon-installer library/component-config integration.

See https://github.com/kubernetes-sigs/addon-operators/issues/34

Closing in favor of that approach.
( +3 from [kubeadm office hours - Nov13](https://docs.google.com/document/d/130_kiXjG7graFNSnIAgtMS1G8zPDwpkshgfRYS0nggo/edit#heading=h.xb857zog4kub) attendees )
