### ISSUE TITLE
Remove AuditPolicyConfiguration from config

### ISSUE THREAD

**Issue by Klaven** [kubernetes/kubeadm#1221]
Per kubeadm office hours on 11.07.2018 we need to remove AuditPolicyConfiguration from config and from the code.

## Is this a BUG REPORT or FEATURE REQUEST?
neither
/kind cleanup

## Versions
current master

## What happened?
It exists

## What you expected to happen?
It should not exist

**Comment by Klaven** [comment]
@chuckha per office hours.

**Comment by Klaven** [comment]
I will be doing this.

**Comment by chuckha** [comment]
@k8k

**Comment by chuckha** [comment]
My understanding from the office hours was that this also included setting the correct flags for the dynamic audit policy on the kube apiserver or is that a different ticket?

**Comment by Klaven** [comment]
I thought that was a different ticket. I will verify though.

**Comment by Klaven** [comment]
@chuckha I don't see mention of that, but it would make since too. @fabriziopandini.

**Comment by chuckha** [comment]
the user will be able to specify the flag in the kubeapiserver extra args configuration section

**Comment by chuckha** [comment]
so this is totally a removal ticket

**Comment by Klaven** [comment]
I will leave the ticket as is then.
