### ISSUE TITLE
CoreDNS 1.1.3 not resolving ExternalName services

### ISSUE THREAD

**Issue by krisdock** [kubernetes/kubeadm#1222]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.11.4

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.11.4
- **Others**: CoreDNS 1.1.3

## What happened?

ExternalName services fail to resolve. 

## What you expected to happen?

ExternalName services to resolve without the need to manually update the CoreDNS version.

## How to reproduce it (as minimally and precisely as possible)?

Bring up a 1.11.4 cluster with kubeadm and create a service with ExternalName type. DNS resolution will fail for this service.

## Anything else we need to know?

Updating CoreDNS to v1.2.6 immediately resolved the issue.

**Comment by yagonobre** [comment]
@krisdock please update the kubeadm

**Comment by chrisohaver** [comment]
@krisdock, Was the ExternalName you tested pointing to an in-cluster name? e.g. 
`myexternalservice.default.svc.cluster.local -> someotherservice.default.svc.cluster.local`

coredns/coredns#2040

**Comment by neolit123** [comment]
@krisdock 

>  please update the kubeadm

+1 to this.
kubeadm (and k8s) 1.12 will pull coredns 1.2.x for you.

this is not a bug for the kubeadm tracker.
and we cannot backport the change to kubeadm 1.11.

you can still respond to @chrisohaver 's question though.

/close
