### ISSUE TITLE
Give warning for deprecated featureGate flags

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1226]
As per Lucas comment https://github.com/kubernetes/kubernetes/pull/70024#pullrequestreview-173179342 and for discussion on https://github.com/kubernetes/kubernetes/pull/70849 we should provide proper handling for deprecate feature flags

The situation at the beginning of this cycle was not fully in line with the [official deprecation policy](https://github.com/kubernetes/website/blob/master/content/en/docs/reference/using-api/deprecation-policy.md#deprecating-a-feature-or-behavior), so some trade-off should be taken when transitioning toward the official deprecation policy.

Starting point:

```
SelfHosting:                  Deprecated
StoreCertsInSecrets:          Deprecated
HighAvailability:             Deprecated
CoreDNS:                      GA   (but not compliant because underlying feature is still beta)
DynamicKubeletConfig:         Beta (but not compliant because defaulted to false)
Auditing:                     Alpha
```

Now I think that we can safely get rid of feature gates `SelfHosting`, `StoreCertsInSecrets` and `HighAvailability` because already deprecated in v1.13 (and corresponding to alpha features in v1.11). Same goes for feature gates `Auditing` / Alpha

`DynamicKubeletConfig: Beta` should become Deprecated; and considering that:
- the feature gate was unproperly defaulted to false 
- the underlying feature is still operational (the user can achieve the same behavior using flags)

IMO a warning should suffice and should go away in v1.14 (as per policy)

`CoreDNS: GA` should become Deprecated; and considering that: 
- the feature gate was unproperly classified GA when the underlying feature is still beta 
- the feature is still operational (via addons config) 

IMO a warning should suffice and should go away in v1.14 (instead of v.1.15 as per policy when the underlying feature is effectively GA)

/cc @timothysc 
/cc @neolit123
/cc @luxas  
@yagonobre

**Comment by timothysc** [comment]
Per conversation today, I think it's totally fine to outright remove some of the deprecated feature gates.

**Comment by timothysc** [comment]
@fabriziopandini - close?

**Comment by fabriziopandini** [comment]
@timothysc, IMO yes, but I leave final word on @neolit123 and/or @luxas cos this issue is a follow up from their comments

**Comment by neolit123** [comment]
i will monitor the issue tracker for user complains.
