### ISSUE TITLE
kubeadm join unknown flag: --cloud-provider 

### ISSUE THREAD

**Issue by runningman84** [kubernetes/kubeadm#123]
The kubeadm join command does not support the cloud provider flag:

```
jon@ip-192-168-99-158:~$ kubeadm join --token=7c5312 --cloud-provider aws ip-192-168-99-160.eu-central-1.compute.internal
Error: unknown flag: --cloud-provider
Usage:
  kubeadm join <master address> [flags]

Flags:
      --api-port int32          (optional) API server port on the master (default 6443)
      --config string           Path to kubeadm config file
      --discovery-port int32    (optional) Discovery port on the master (default 9898)
      --skip-preflight-checks   skip preflight checks normally run before modifying the system
      --token string            (required) Shared secret used to secure bootstrap. Must match the output of 'kubeadm init'
```

This is a problem because the cloud provider config is also not configured here:
/etc/systemd/system/kubelet.service.d/10-kubeadm.conf

This means you have to manually change the config file to include the cloud provioder in order to use ELB, EBS and so on....

**Comment by luxas** [comment]
Yes, that's a known limitation we've documented in the kubeadm page as well.
We'd like to use Kubelet Dynamic Settings (#28) for this, and then it will work automatically.

**Comment by luxas** [comment]
Until that, you have to edit the systemd file unfortunately

**Comment by dmmcquay** [comment]
This flag has since been removed and will be added in as a kubeadm phase, is that correct @luxas?

Should we close this issue?

**Comment by luxas** [comment]
This is about adding to join, but since we're moving in the out-of-core-cloudproviders we are not gonna implement this. Not that kubeadm can do anything in this situation either.

@runningman84 You should just edit `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` and it will work
