### ISSUE TITLE
Fix the kubeadm upgrade test jobs

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1230]
The upgrade tests are facing a multitude of problems.
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all

1 ginkgo is not skipping 3 tests that we want skipped:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm-upgrade.yaml#L157

can't tell if this is a kube-test vs ginkgo vs e2e framework bug.

2 kubernetes-anywhere 's paths in the e2e framework for old branches is bogus after we switched to pulling branches instead of specific commits in prow jobs:
https://github.com/kubernetes/kubernetes/pull/70894
https://github.com/kubernetes/kubernetes/pull/70895

3 we have actual failures in the `[master-upgrade]` tests:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-upgrade-stable-master/2831#master-upgrade-sig-cluster-lifecycle-master-upgrade

this PR:
https://github.com/kubernetes/kubeadm/issues/1224

and the two cherry picks above might fix these.

cc @timothysc @fabriziopandini 
cc @kubernetes/sig-cluster-lifecycle 

/assign
/kind failing-test
/priority important-longterm
/area testing

**Comment by timothysc** [comment]
I want to push this onto cluster-api implementations TBH. 

/assign @detiber @chuckha

**Comment by neolit123** [comment]
we no longer have to fix these, but rather remove them completely and use kind based upgrades.
moving the work here so that we don't have multiple tracking issues:
https://github.com/kubernetes/kubeadm/issues/1290
