### ISSUE TITLE
KubeConfigPath get a wrong path when we are dry-running

### ISSUE THREAD

**Issue by yuexiao-wang** [kubernetes/kubeadm#1233]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-alpha.0.162+a40647a42ab30d-dirty", GitCommit:"a40647a42ab30d983e514f2cf2a2893613b841cd", GitTreeState:"dirty", BuildDate:"2018-11-13T11:02:56Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
`KubeConfigPath` get a wrong path when we are dry-running. I think it have a bug in `KubeConfigPath`
https://github.com/kubernetes/kubernetes/blob/94c5953904f4f365776eb2c61b6b28d95f005d4c/cmd/kubeadm/app/cmd/init.go#L399

## What you expected to happen?
`KubeConfigPath` get a dryRunDir when we are dry-running and get a correct kube config path.

**Comment by yuexiao-wang** [comment]
I have send a PR to fix it

**Comment by neolit123** [comment]
i'm going to close this now as the fix is in place
thanks!
