### ISSUE TITLE
Documentation must be updated for 1.13

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1237]
https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/

the phases have all changed and need to be validated. At the very least `kubeadm alpha phase certs etcd-ca` does not exist any more.

**Comment by chuckha** [comment]
ah, moved to `kubeadm init phase certs etcd-ca`

**Comment by neolit123** [comment]
@chuckha i have a PR planned for all cmd renames here:
https://github.com/kubernetes/website/pull/10960

i will start on that tomorrow. any remaining changes will go on top as separate PR.

docs / website tracking issue:
https://github.com/kubernetes/website/issues/10937

**Comment by neolit123** [comment]
added small PR with bugfixes related to v1beta1:
https://github.com/kubernetes/website/pull/10988
