### ISSUE TITLE
kubeadm v1.12.2 startup errors

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubeadm#1239]
## Is this a request for help?
Yes.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
1.12.2
**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.12.2
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): Ubuntu 18.10
- **Kernel** (e.g. `uname -a`): 4.18.0-10-generic
- **Others**:

## What happened?
sudo kubeadm init --config kubeadm_new.config --ignore-preflight-errors=all
This appears in /var/log/syslog:
`Nov 14 11:42:04 khteh-T580 kubelet[1008]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 14 11:42:04 khteh-T580 kubelet[1008]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 14 11:42:04 khteh-T580 kubelet[1008]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 14 11:42:04 khteh-T580 kubelet[1008]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 14 11:42:04 khteh-T580 kubelet[1008]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 14 11:42:04 khteh-T580 kubelet[1008]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.`

/var/lib/kubelet/ folder has kubeadm-flags.env which provides the flags.

Apparently, kubeadm still uses command line flags which is shooting itself in the foot!

## What you expected to happen?
No error. kubelet started successfully

## How to reproduce it (as minimally and precisely as possible)?
Install the latest kubernetes and run kubeadm init.

**Comment by neolit123** [comment]
this is a known problem as is already tracked in this repo.
also the flags are not going away soon.
