### ISSUE TITLE
Missing label kubeadm.alpha.kubernetes.io/role

### ISSUE THREAD

**Issue by runningman84** [kubernetes/kubeadm#124]
Right now the kubeadm command does not setup this label on the master:
kubeadm.alpha.kubernetes.io/role:master
But the kube-discovery pod does not run on the master without this label.

**Comment by luxas** [comment]
Hmm, I think that works for me though, can you give some more debug information?

**Comment by luxas** [comment]
The master label will be changed in v1.6 as well, reopen if this is can be reproducable again then.
ref: https://github.com/kubernetes/kubernetes/pull/41835
