### ISSUE TITLE
Documentation for `certs renew --use-api`

### ISSUE THREAD

**Issue by liztio** [kubernetes/kubeadm#1242]
The `--use-api` version of renewal works a little different than the standalone version. Documentation should be added that explains:

* certificates may need to be [manually approved][manual]
* the certificate signer is not available [by default][signer]

Possibly just linking to the above articles is sufficient

[manual]: https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#approving-certificate-signing-requests
[signer]: https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators

**Comment by luxas** [comment]
@neolit123 @liztio this can merge right after the v1.13 cut, right?

**Comment by Bradamant3** [comment]
currently the docs PR is in my hands for copyedit, will be merged this week (before 1.13 release).

**Comment by neolit123** [comment]
closed by:
https://github.com/kubernetes/website/pull/11093
