### ISSUE TITLE
Kubernetes Dashboard issue while login. #help wanted

### ISSUE THREAD

**Issue by reddysandeep** [kubernetes/kubeadm#1247]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by reddysandeep** [comment]
Versions
kubeadm version (use kubeadm version):

Environment:

Kubernetes version : v1.12.2
Cloud provider or hardware configuration: AWS
OS (e.g. from /etc/os-release):Ubuntu 16.04.5 LTS
Kernel (e.g. uname -a): 4.4.0-1067-aws
Others:

**Comment by timothysc** [comment]
Closing this is not a kubeadm issue.
