### ISSUE TITLE
Failing test: kubeadm-gce-master on master-blocking

### ISSUE THREAD

**Issue by mariantalla** [kubernetes/kubeadm#1248]
**Which jobs are failing**:
[sig-release-master-blocking#kubeadm-gce-master](https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-master)

**Since when has it been failing**:
2018-11-14. [843a67b21 in k/k](https://github.com/kubernetes/kubernetes/commit/843a67b215dcfa1781820a797c4c759e42e81d3a), [7d7a939a8 in k/test-infra](https://github.com/kubernetes/test-infra/commit/7d7a939a8).

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#kubeadm-gce-master

**Reason for failure**:
From [gubernator](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-master/835):
```
I1115 12:41:19.723] Call:  kubectl get -oyaml pods/a941dc4a-e8d3-11e8-8c3b-0a580a6c0007
W1115 12:41:19.818] The connection to the server localhost:8080 was refused - did you specify the right host or port?
E1115 12:41:19.822] Command failed
```
**Anything else we need to know**:
Here's the [diff](https://github.com/kubernetes/kubernetes/compare/e3ddaaad1...843a67b21?) from last successful run.

/kind failing-test

**Comment by AishSundar** [comment]
/assign @cjwagner @amwat 
/sig testing
/priority important-soon
/milestone v1.13

This job passes fine on 1.13 branch. Can we look into what could be causing this? Thanks

**Comment by AishSundar** [comment]
This seems to be related to https://github.com/kubernetes/kubectl/issues/562

**Comment by timothysc** [comment]
Closing!  

This is not out fault.

**Comment by mariantalla** [comment]
Sorry, my bad! I unintentionally abused my power.
