### ISSUE TITLE
Common utility functions do not belong in kubeadm

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#125]
There are fair number of utility function that wrap various behaviors in the system.  If those behaviors change this amounts to technical debt and code sprawl.  

Currently there are a number of wrapping functions against things that can be common.  e.g. api f(n)s, and it's clear these are even tested.  

The only reason I found this is I was cleaning up scheduler affinity then found the wrappers and decided to poke further.  

As api's shift from alpha-beta etc, please place all utility f(n)s into a common location to reduce the technical debt sprawl, and ensure they are testable.

**Comment by luxas** [comment]
Fully aware of this. I'm working on refactoring the entire kubeadm codebase into something cleaner, and as a part of that I'm removing most of the helper functions I think you're referring to.

See https://github.com/kubernetes/kubernetes/pull/40556 for example

**Comment by luxas** [comment]
@timothysc I think this is fixed now thanks to the refactoring work myself and others have made.
Reopen if you don't agree.
