### ISSUE TITLE
How to access the Dashboard?

### ISSUE THREAD

**Issue by venkatasykam** [kubernetes/kubeadm#1253]
## What keywords did you search in kubeadm issues before filing this one? : **Dashboard**

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?: May be Feature

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): 1.12.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.12.2
- **Cloud provider or hardware configuration**: AWS EC2 t2.midium instance - Ubuntu - region N.Virginia
- **OS** (e.g. from /etc/os-release): Ubuntu Server 18.04 LTS (HVM), SSD Volume Type - ami-0ac019f4fcb7cb7e6
- **Kernel** (e.g. `uname -a`): Linux ip-172-31-87-28 4.15.0-1021-aws #21-Ubuntu SMP Tue Aug 28 10:23:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

**Comment by neolit123** [comment]
hi, please try the support channels like stackoverflow:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example
