### ISSUE TITLE
Move test utilites out of /test

### ISSUE THREAD

**Issue by liztio** [kubernetes/kubeadm#1257]
Currently we have a set of harnesses and utilities placed in kubeadm/test:
https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/test/certs

This causes `workflow` to have a dependency on `test/`. Because we want the workflow portion of kubeadm to be vendorable, we should not be depending on the test/ package at all. These utilities should be moved somewhere else.

**Comment by liztio** [comment]
cc @neolit123

**Comment by yagonobre** [comment]
Thanks @yuexiao-wang 
/lifecycle active

**Comment by yagonobre** [comment]
Closed by https://github.com/kubernetes/kubernetes/pull/71702
/close
