### ISSUE TITLE
Flannel installed however coredns errros with check that the calico/node container is running and has mounted /var/lib/calico/

### ISSUE THREAD

**Issue by dannymk** [kubernetes/kubeadm#1259]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

```
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:51:33Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):

```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?

Following the instructions at:  https://kubernetes.io/docs/setup/independent/high-availability/
I was up to the point where I had to install the pod network and I chose flannel:
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml

The flannel pods continuously failed until I set the variables:

        - name: KUBERNETES_SERVICE_HOST
          value: "kube-apiserver.config-settings.com" #ip address of the host where kube-apiservice is running
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
Then it ran as expected.  However we are now getting the error:

 kubectl -n kube-system describe pod/coredns-576cbf47c7-6dd2v

```
...
  Warning  FailedCreatePodSandBox  31m                  kubelet, kube-apiserver-2  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "35f546fa814a0eba052a2ee6a0799ac47f13f8e1d3d0da7175e49e21c344dde9" network for pod "coredns-576cbf47c7-6dd2v": NetworkPlugin cni failed to set up pod "coredns-576cbf47c7-6dd2v_kube-system" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
  Normal   SandboxChanged          31m (x12 over 31m)   kubelet, kube-apiserver-2  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  92s (x568 over 31m)  kubelet, kube-apiserver-2  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "33c307b2ef2cffa4a4dd42a5773903b5fd3cd5ba8f82ef28bbf23e1c49914bc0" network for pod "coredns-576cbf47c7-6dd2v": NetworkPlugin cni failed to set up pod "coredns-576cbf47c7-6dd2v_kube-system" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
```

## What you expected to happen?

First, I did not expect Calico to be running or supported at all as I chose Flannel as the pod network plugin.

I also expected coredns to use Flannel and go into a ready state.

## How to reproduce it (as minimally and precisely as possible)?

Install Kubernetes using kubeadm
Setup an external etcd cluster
Create a control plane using the external etcd cluster section at:  
https://kubernetes.io/docs/setup/independent/high-availability/
Modify the kube-flannel.yml to include the host and port as stated above then apply to cluster.
Describe the coredns pods to see error

## Anything else we need to know?

The current status of the cluster is:

```
NAME                                       READY   STATUS              RESTARTS   AGE
coredns-576cbf47c7-6dd2v                   0/1     ContainerCreating   0          53m
coredns-576cbf47c7-7jtgv                   0/1     ContainerCreating   0          53m
kube-apiserver-kube-apiserver-1            1/1     Running             1          3h14m
kube-apiserver-kube-apiserver-2            1/1     Running             0          3h5m
kube-apiserver-kube-apiserver-3            1/1     Running             0          3h4m
kube-controller-manager-kube-apiserver-1   1/1     Running             6          7h4m
kube-controller-manager-kube-apiserver-2   1/1     Running             0          3h5m
kube-controller-manager-kube-apiserver-3   1/1     Running             0          3h4m
kube-flannel-ds-amd64-b8rxl                1/1     Running             0          43m
kube-flannel-ds-amd64-mrbhl                1/1     Running             1          43m
kube-flannel-ds-amd64-s5bkn                1/1     Running             0          43m
kube-proxy-f4csh                           1/1     Running             0          3h5m
kube-proxy-lh7mq                           1/1     Running             3          7h3m
kube-proxy-qzhgf                           1/1     Running             0          3h4m
kube-scheduler-kube-apiserver-1            1/1     Running             6          7h4m
kube-scheduler-kube-apiserver-2            1/1     Running             0          3h5m
kube-scheduler-kube-apiserver-3            1/1     Running             0          3h4m
```

I may have tried using Calico at some point by trying the instructions at:  https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

I do run a v1.10.3+coreos.0 cluster without issue but we now need to support Kubernetes on OpenStack instances.

There seems to be conflicting or missing information at:  https://kubernetes.io/docs/setup/independent/high-availability

Am I wrong?

**Comment by neolit123** [comment]
> First, I did not expect Calico to be running or supported at all as I chose Flannel as the pod network plugin.

**Comment by dannymk** [comment]
Well, weavnet produces the same error:

```
  Normal   SandboxChanged          3s (x5 over 19s)  kubelet, kube-apiserver-1  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  3s                kubelet, kube-apiserver-1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e397cae582b73e89c632ff28fe21754578ed0281af1bbd0b364c09b5dd6430dd" network for pod "coredns-576cbf47c7-czgll": NetworkPlugin cni failed to set up pod "coredns-576cbf47c7-czgll_kube-system" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
```

kubectl -n kube-system get pods
```
NAME                                       READY   STATUS              RESTARTS   AGE
coredns-576cbf47c7-czgll                   0/1     ContainerCreating   0          12s
coredns-576cbf47c7-dbhzj                   0/1     ContainerCreating   0          12s
kube-apiserver-kube-apiserver-1            1/1     Running             2          4h8m
kube-apiserver-kube-apiserver-2            1/1     Running             0          3h59m
kube-apiserver-kube-apiserver-3            1/1     Running             0          3h58m
kube-controller-manager-kube-apiserver-1   1/1     Running             7          7h58m
kube-controller-manager-kube-apiserver-2   1/1     Running             0          3h59m
kube-controller-manager-kube-apiserver-3   1/1     Running             0          3h58m
kube-proxy-f4csh                           1/1     Running             0          3h59m
kube-proxy-lh7mq                           1/1     Running             4          7h57m
kube-proxy-qzhgf                           1/1     Running             0          3h58m
kube-scheduler-kube-apiserver-1            1/1     Running             7          7h58m
kube-scheduler-kube-apiserver-2            1/1     Running             0          3h59m
kube-scheduler-kube-apiserver-3            1/1     Running             0          3h58m
weave-net-7xxlz                            2/2     Running             0          51s
weave-net-wrhr2                            2/2     Running             0          51s
weave-net-wshqd                            2/2     Running             0          51s
```

By the way, I had to add the same variables to the Weavenet yaml file:

```
...
        spec:
          containers:
            - name: weave
              command:
                - /home/weave/launch.sh
              env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: KUBERNETES_SERVICE_HOST
                  value: "kube-apiserver.config-settings.com"
                - name: KUBERNETES_SERVICE_PORT
                  value: "6443"
              image: 'docker.io/weaveworks/weave-kube:2.5.0'
              readinessProbe:
                httpGet:
                  host: 127.0.0.1
                  path: /status
                  port: 6784
              resources:
...

```

**Comment by neolit123** [comment]
i'm confused why this is happening.
`/var/lib/calico/nodename` is something that calico defines.

https://github.com/projectcalico/calico/search?q=%22%2Fvar%2Flib%2Fcalico%2F%22&unscoped_q=%22%2Fvar%2Flib%2Fcalico%2F%22

try removing any existing calico images / containers.

**Comment by dannymk** [comment]
Believe it or not I went into all three hosts and removed all docker images that had anything to do with Calico.  I also rebooted each system and I am still getting the same error.  I am confused myself.

```
  Warning  FailedCreatePodSandBox  4s                     kubelet, kube-apiserver-1  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b15e6a616058e078952b962f997c899581b5398c9568ef08d881ab164b4ce60f" network for pod "coredns-576cbf47c7-czgll": NetworkPlugin cni failed to set up pod "coredns-576cbf47c7-czgll_kube-system" network: stat /var/lib/calico/nodename: no such file or directory: check that the calico/node container is running and has mounted /var/lib/calico/
  Normal   SandboxChanged          3s (x8 over 33s)       kubelet, kube-apiserver-1  Pod sandbox changed, it will be killed and re-created.
```

**Comment by neolit123** [comment]
> By the way, I had to add the same variables to the Weavenet yaml file:

could you please file a separate issue.

> Do you think it may have anything to do with an etcd key/value?


callico by default does depend on etcd:
https://github.com/projectcalico/calico/blob/master/v2.6/getting-started/kubernetes/installation/integration.md

did you try callico on the exact same running cluster before installing the other CNI plugins?

if you are willing to bring the etcd cluster down you can do this:
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#replacing-a-failed-etcd-member

this is a calico error:
https://github.com/kubernetes/kubernetes/issues/62451

> kubectl -n kube-system get pods

are there any other pods running i.e. `--all-namespaces`?
also did you try `--include-uninitialized`?

**Comment by dannymk** [comment]
OK, this is what I did.  On a hunch I started from scratch and got it to work out of the box with one modification of the flannel pod network configuration before being applied to the cluster.  See issue #1264

**Comment by neolit123** [comment]
@dannymk thanks for logging the other issue. can we close this, assuming it's not kubeadm related?

**Comment by dannymk** [comment]
Can we augment the instructions on the HA cluster to include these two variables in some way?  It could definitely save someone else days of work.

**Comment by dannymk** [comment]
Rebuild of master cluster with external ha worked as expected once we started with a clean slate.  Make sure you start from scratch so there are no lingering pods/images/instances.

**Comment by neolit123** [comment]
> Can we augment the instructions on the HA cluster to include these two variables in some way? It could definitely save someone else days of work.

just want to ask for a second opinion.
but yes, i will be editing the HA docs the following days and we can add it.
