### ISSUE TITLE
Review components resource limits

### ISSUE THREAD

**Issue by pires** [kubernetes/kubeadm#126]
As per @luxas comments, we should review the resource limits we set for better kubeadm UX.

**Comment by luxas** [comment]
@jbeda @timothysc @mikedanese Do you think we're good as is or have to change something here?

**Comment by luxas** [comment]
ping @timothysc I think we're in a good position, can we close this?

**Comment by luxas** [comment]
Closing as I think we're in a good shape

**Comment by discordianfish** [comment]
I'm reviewing the resources limits and requests on my kubeadm based cluster and it seems that none of the core cluster components (kube-proxy, apiserver, scheduler, controller manager) have memory limits set.
At first I thought that probably makes sense, nobody wants k8s to kill them. But then people explained QoS classes to me and it looks like currently all these cluster components are in the best effort class and therefor should get OOM killed first under memory pressure. That's probably not what we want, no?
