### ISSUE TITLE
upgrade docs 1.12 => 1.13 (multi-control-plane and single control plane)

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1261]
We need to add a new document for upgrading from 1.12 to 1.13.

xref: https://github.com/kubernetes/website/issues/10937

- [x] single control plane (@chuckha)
- [x] multi control plane (@rdodev)

We will be pushing to https://github.com/kubernetes/website/pull/11094 PR

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/priority critical-urgent
@kubernetes/sig-cluster-lifecycle-pr-reviews 
/assign @tfogo @fabriziopandini 
/cc

**Comment by rdodev** [comment]
Splitting off HA section, so that doesn't block this PR or issue.

**Comment by rdodev** [comment]
External etcd upgrade docs PR here: https://github.com/kubernetes/website/pull/11364

**Comment by luxas** [comment]
@rdodev This all seems merged now, thanks!
