### ISSUE TITLE
Upgrade docs 1.12 => 1.13 (multi-control-plane)

### ISSUE THREAD

**Issue by rdodev** [kubernetes/kubeadm#1265]
Documenting upgrade for highly-available control planes.

 - [x] external HA etcd
 - [ ] 3 control planes (fronted by an LB)
 - [ ] 1 worker node

**Comment by luxas** [comment]
@rdodev status update? Is this now done given the recent merges?

**Comment by luxas** [comment]
Closing as fixed by https://github.com/kubernetes/website/pull/11364 :tada:
