### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1266]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

Kubeadm handles errors in a somewhat hard to use and error prone way.

We spend too much time wrapping errors unnecessarily. What we want to be doing is wrapping errors with stack traces that don't already have stack traces. So anytime we call an external library (standard library included) we should be wrapping the error with errors.Wrap. Otherwise, we should just be returning the error directly without modification *assuming no further context is required*. At the top level we should be logging the stack trace that all of our errors will now have in addition to the main error that caused the stack trace.

This will have several benefits:

1. Reduce the amount of error wrapping we are currently doing.
2. Provide a very easy to trace output when a user opens an issue and shows us the stack trace they have produced.
3. Creates a rule that we can easily reference during a code review. Wrap errors that need to be wrapped and don't wrap anything else unless additional context is necessary.

/kind feature
/priority important-longterm
/milestone v1.14
/good-first-issue

**Comment by chuckha** [comment]
True. This might also requires discussion of some kind as well. I'm out tomorrow but can bring it up the following week.

**Comment by timothysc** [comment]
Golang 2 semantics are ideal for this scenario.  I think we should hold until it's real, otherwise, we would implement something only to replace it again.

**Comment by chuckha** [comment]
I see this as two separate issues, 1) error handling strategy, 2) repetitive syntax. I understand your concern. This is no small ticket, which was also what @neolit123 was getting at.

As for Go2, assuming the proposal goes through unchanged, will have the ability to clean up repetitive error handling cases. The proposal in this issue is focused on issue 1. I believe there is a much more efficient method that will provide more context with less error wrapping allowing more people to understand bugs as they come through.

Go2's proposal will help with the second issue, repetitive syntax, but it will not help with changing our error handling strategy.

It's ok to defer this since it's a ton of work, but I am proposing revamping our error strategy in the interest of improving the errors that we see getting entered into issues. A complete stack trace would be a godsend in an issue.

**Comment by bart0sh** [comment]
@chuckha Please, correct me if I'm wrong here, but the idea of this issue sounds somehow contradictory to the main purpose of errors.Wrap - adding context to errors that come from low level API.  Without it error message on the upper level would confuse users. Getting "no such file or directory" message when running "kubeadm join" is not giving much help for user to understand what's going on. Getting traceback is good for programmer, but we shouldn't forget about users.

It could be that I completely missed the idea. If this is the case, please help me to get it right. Some examples from kubeadm code would be also appreciated.

**Comment by chuckha** [comment]
@bart0sh I totally agree with you, we should not forget about the users! A stack trace is too extreme to show the users and is really only necessary during an unexpected error. If the error is expected then we have the ability to handle it and print a user friendly error message. If it's not expected we can print a stack trace along with a link to kubeadm/issues and instructions to fill out an issue.

If you're looking for examples of how to handle various types of errors in go, I usually point to https://golang.org/pkg/os/#IsTimeout (and similar functions) as ways that the standard library handles custom errors. Kubeadm errors could even include what the error means and potentially how to fix it, or common mistakes that cause that error.

Overall I think this ticket would help make the user experience nicer if we handle errors in a nice way as well as improve the types of issues that get created.

**Comment by astrieanna** [comment]
/remove-help

I think that this does not fit the definition of [help-wanted](https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md). The task here seems to be for the community to discuss and agree on an error handling/printing strategy; the definition of help-wanted says that the task should not require further discussions in the community.

**Comment by neolit123** [comment]
@astrieanna 
yet the kubeadm repo does not exactly agree with the official help-wanted rules.
the overlap between help-wanted and good-first-issue is misleading.

for example, help may be wanted from experienced contributors to kubeadm, who can help confirming a bug or sending a PR to fix it. for those cases we don't have a label...

**Comment by cblecker** [comment]
@neolit123 We need these labels to be use consistently across the project, as they are entrypoints for new contributors. We have community-wide documentation that defines what they should mean.

Happy to discuss more how to help kubeadm/cluster-lifecycle call out work that needs a more experienced contributor to lead, but these specific labels tie into both project-wide and GitHub automation.
