### ISSUE TITLE
Fix some names of tests in phases/controlplane/manifests_test.go

### ISSUE THREAD

**Issue by atoato88** [kubernetes/kubeadm#1267]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
I found this in code reading on k/k master. So I don't use any kubeadm binary.

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
Following test name have "custom cloudprovider" in name, but it checks for "--cluster-cidr" in kube-controller-manager parameter.  

-   https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/controlplane/manifests_test.go#L600
-   https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/controlplane/manifests_test.go#L703

It should rename from "custom cloudprovider" to "custom cluster-cidr" or "custom pod-subnet", I think.

## What you expected to happen?

NONE

## How to reproduce it (as minimally and precisely as possible)?

NONE

## Anything else we need to know?

NONE

**Comment by neolit123** [comment]
i don't think this is that much of an error, because the CP can be using a custom CIDR too.
but if someone want's to fix please send a PR.

please mind that i can be merged only after the release of 1.13. thanks.

**Comment by yuexiao-wang** [comment]
I will work on it

**Comment by yagonobre** [comment]
Thanks again
/close

**Comment by yuexiao-wang** [comment]
Thanks
