### ISSUE TITLE
join --experimental-master fails on clusters created with v1.12

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1269]
## Is this a BUG REPORT or FEATURE REQUEST?
/kind bug

## Versions

**kubeadm version** (use `kubeadm version`):
v1.13.0-beta.1

## What happened?

`join --control-plane` failed with `` on a cluster created with v1.12 and then updated to v1.13.0-beta.1

## What you expected to happen?
`join --control-plane` pass

## How to reproduce it (as minimally and precisely as possible)?
create a cluster with v1.12
upgrade to  v1.13.0-beta.1
add a node and try `join --control-plane`  

## Anything else we need to know?
In v1.12 cluster etcd is listening on local host only
In v1.13 cluster etcd is listening on local host and advertise address, but during upgrade this change is not applied because etcd version remain the same between v1.12 and v1.13

**Comment by fabriziopandini** [comment]
This can be fixed by forcing etcd upgrade during v1.12 --> v1.13, but this brings some risks
So my proposal (already briefly discussed with @luxas) is to document this issue in release notes/ha upgrade document

@timothysc @neolit123  opinions?

**Comment by neolit123** [comment]
by documenting it would we provide a workaround in the HA-upgrade doc?
given the etcd version remained the same between 1.12 and 1.13 AFAIK, what risk do we have by forcing the upgrade?

**Comment by fabriziopandini** [comment]
> by documenting it would we provide a workaround in the HA-upgrade doc?
No, only tell the user that this alpha feature has a known problem in this scenario

> what risk do we have by forcing the upgrade?
Etcd "upgrade" imply some machinery to be executed, and that's implicitily brings some extra risk, that I'm not sure we want take at this stage of the cycle/for an alpha fefature/for a very specific use case

**Comment by neolit123** [comment]
> No workaround, but tell the user that this alpha feature has a known problem in this scenario

@rdodev  has promised to update the HA upgrade docs. we can discuss the exact phrasing here.
so isn't patching the etcd listening addresses in the manifest for this node before calling `join --experimental-control-plane` a workaround?

> Etcd "upgrade" imply some machinery to be executed, and that's implicitily brings some extra risk that I'm not sure we want take at this stage of the cycle/for an alpha fefature/for a very specific use case

ok, that's true.
we did patch last minute problems in the alpha config, but there was less risk, so i agree.

**Comment by fabriziopandini** [comment]
manual patching can be a workaround. you are right
probably also calling `kubeadm phase etcd` with the right config will do the trick ... 
I need to check this

**Comment by luxas** [comment]
Yeah, not worth it to do a potentially risky upgrade for no significant benefit for an alpha feature.
:+1: to do fix this as a "side-effect" of bumping etcd version in the next version, and documenting meanwhile.

**Comment by fabriziopandini** [comment]
@neolit123 @rdodev this workaround worked for me
```bash 
# NB1. this procedure will make local etcd restart
# NB2. kubeadm v1.13 should be used
# NB3. this procedure assumes you get the kubeadm-config file stored in /etc/kubernetes/kubeadm-config.yml

# before joining the secondary control plane node you should so on the existing master and run following commands:

# remove etcd certs where etcd listen and peer address should be changed
sudo rm /etc/kubernetes/pki/etcd/peer*
sudo rm /etc/kubernetes/pki/etcd/server*

# recreate etcd certs with the new etcd listen and peer address
sudo kubeadm init phase certs etcd-peer --config /etc/kubernetes/kubeadm-config.yml
sudo kubeadm init phase certs etcd-server --config /etc/kubernetes/kubeadm-config.yml

# recreate etcd manifest with the new etcd listen and peer address
sudo kubeadm init phase etcd local --config /etc/kubernetes/kubeadm-config.yml

# now your are ready for scaling up your control plane and etcd

```

**Comment by timothysc** [comment]
We can add a known issues section to the bottom of the doc and crosslink the issue.

**Comment by neolit123** [comment]
> this workaround worked for me

seems quite complicated to include in the main docs, also in which page?

**Comment by fabriziopandini** [comment]
@neolit123 this applies to upgrade v1.12 --> v1.13 doc (https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13/).

IMO the following note will be enough

Known Issue:
the commad `join --experimental-control-plane` is know to fail on single node clusters created with kubeadm v1.12 and then updated to v1.13.x; this will be fixed when graduating the `join --control-plane` workflow from alpha to beta.
Nevertheless a possible workaround is described [here](https://github.com/kubernetes/kubeadm/issues/1269#issuecomment-441116249)

**Comment by neolit123** [comment]
> IMO the following note will be enough

ok.
/assign
