### ISSUE TITLE
Error in join --control-plane

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1270]
Kubedam v1.13 raise an error joining a control plane node.

The error happens when connecting to etcd, and this problem is similar to what fixed by https://github.com/kubernetes/kubernetes/pull/70893 but gets triggered only during join control plane worflow

I have a fix in flight

**Comment by luxas** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/71360 :+1:
