### ISSUE TITLE
Merge flags and config correctly

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1271]
As discussed in e.g. https://github.com/kubernetes/kubernetes/pull/71323
related to #906 and a lot of other issues and pulls. e.g. @rosti had a PR that stalled.
The way we're gonna attack this issue is to solve it generically for k8s first with a `k8s.io/component` repo, and then start using the common code in kubeadm. Targeted for v1.14

KEP draft for `k8s.io/component` https://docs.google.com/document/d/1nZnzJD9dC0xrtEla2Xa-J6zobbC9oltdHIJ3KKSSIhk/edit#heading=h.tvd3ryz8p4b3

**Comment by luxas** [comment]
cc @neolit123 @bart0sh @fabriziopandini @timothysc

**Comment by RA489** [comment]
@luxas i can take a look.

**Comment by luxas** [comment]
@RA489 Join our workgroup that will discuss this: https://github.com/kubernetes/community/tree/master/wg-component-standard
In this WG, we'll come up with a k8s-wide solution to this problem, and we'll adopt this in kubeadm afterwards.

**Comment by neolit123** [comment]
closing in favor of: https://github.com/kubernetes/kubeadm/issues/1040
