### ISSUE TITLE
can`t set dns service clusterIP

### ISSUE THREAD

**Issue by l453595892** [kubernetes/kubeadm#1278]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
v1.12.2
**Environment**:
- **Kubernetes version** (use `kubectl version`):
v1.12.2
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- **Kernel** (e.g. `uname -a`):
Linux node1 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?

when I use `kubeadm --cluster-dns=xxxxx` there only set POD  `/etc/resolv.conf` ,but not set coreDNS  `clusterIP` from my config

## What you expected to happen?

the coreDNS service `clusterIP` will set by my config `cluster-dns=xxxxx`

**Comment by neolit123** [comment]
please provide your complete setup using the issue template:
https://raw.githubusercontent.com/kubernetes/kubeadm/master/.github/ISSUE_TEMPLATE.md

**Comment by l453595892** [comment]
@neolit123 i have edited it already

**Comment by foxyriver** [comment]
https://github.com/kubernetes/kubernetes/blob/152226c557e1b006d8aa0f2e1709192e84baad6e/cmd/kubeadm/app/util/config/initconfiguration.go#L57
your config will be reset by this method with default

**Comment by timothysc** [comment]
closing, issue is stale.  Please reopen if the issue still exits and you can repro.
