### ISSUE TITLE
Use pod anti-affinity in kube-dns

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubeadm#128]
Also we may want to scale kube-dns by default to 2.

See related discussion in https://github.com/kubernetes/kubernetes/issues/40063

**Comment by luxas** [comment]
@kargakis could I assign you this issue?

**Comment by kargakis** [comment]
Technically you can, I am not sure when I'll get to this though:)

**Comment by luxas** [comment]
@kargakis Haha I see. Assigned to us both, and whoever gets to it first may do it ;)

**Comment by luxas** [comment]
@kargakis Do you think we should revisit/do this before v1.8 code freeze? How important do you think it is?
Right now, we're trying to be in sync with the other manifests in `cluster/`
cc @kubernetes/dns-maintainers

**Comment by luxas** [comment]
Moving this out of v1.8 due to the lack of response.
This isn't that important now when we're using a single replica of DNS, but we probably want this once/if we start deploying the horizontal DNS autoscaler with kubeadm.

**Comment by jamiehannaford** [comment]
@luxas If we do add the horizontal DNS autoscaler, should it be behind a feature gate? I might have time for this in 1.9 if it's easy to implement

**Comment by luxas** [comment]
@jamiehannaford Alternatively, I'm wondering whether it would make sense to use the native `autoscaling/v1` or `autoscaling/v2beta1` HPAs instead...

**Comment by timothysc** [comment]
Where are we at with this now..?  
/cc @MrHohn

**Comment by bowei** [comment]
There is a PR out, but the author has to update with the feedback in the comments.

**Comment by timothysc** [comment]
@bowei link?

**Comment by bowei** [comment]
https://github.com/kubernetes/kubernetes/pull/57683

**Comment by webwurst** [comment]
but also https://github.com/kubernetes/kubernetes/pull/59357

**Comment by timothysc** [comment]
This looks like it was ripped back out for a reason, closing here.
