### ISSUE TITLE
Add an high level doc for docker/external components recommended versions

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1282]
As per slack discussion with @luxas 
https://kubernetes.slack.com/archives/C13J86Z63/p1543406930652200
https://kubernetes.slack.com/archives/C13J86Z63/p1543407324656100

"@zhangxiaoyu-zidif pointed out that we don't have the recommended/supported docker version in our kubeadm docs
We should definitely include that"

"We should aggregate a common doc that is higher-level and has all that dep info in one place
Can somebody open an issue for that that we can track?
Ideally we should do that for all of k8s, and merge to website right after v1.13.0"

IMO this should include also other CRIs, CoreDNS, ETCD

Marking this a v1.13 but it is acceptable to do this a the beginning of v1.14

**Comment by luxas** [comment]
any volunteer to aggregate the version dep information from the three latest releases :smile:
cc @neolit123 @rosti @rdodev ^?

**Comment by neolit123** [comment]
we do have the recommended version.

here:
https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-runtime
there is a link that leads to:
https://kubernetes.io/docs/setup/cri/

this was contributed by @bart0sh and @vincepri and approved by @timothysc .

**Comment by luxas** [comment]
@neolit123 I mean ALL the versions. etcd, CoreDNS, Docker, CRI/CNI/CSI API specifications, cri-tools
Like this: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#external-dependencies, but in the website for the three latest versions. Not all of those but the most important ones.

**Comment by luxas** [comment]
> ideally it should be for k8s as a whole.

I meant this doc would be maintained by us, based directly from the release notes.
So in other words "just" (very needed!) maintenance work

**Comment by rosti** [comment]
We used to maintain such a table here:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#running-kubeadm-without-an-internet-connection

However, we decided to simply tell the users to use `kubeadm config images list` to list the exact images and versions (tags). This looks way more accurate and less error prone, than having to maintain a table.
The table at the link is only maintained for kubeadm versions, that don't support `kubeadm config images` and should have been removed with the drop of 1.10 support.

**Comment by timothysc** [comment]
ok, we should chat on a sig call on this one.  

We need to be careful with this and actually provide test signal that is good for the (stream) of components.

**Comment by luxas** [comment]
@rosti this is not about the control plane images that is k8s, but everything else ;)

**Comment by fabriziopandini** [comment]
@timothysc @luxas @neolit123 
I think this should be closed in favour of https://github.com/kubernetes/website/issues/12328
Wdyt?

**Comment by neolit123** [comment]
+1 for close.

i definitely think this should not be a sig-cluster-lifecycle only task.
what we discussed in the latest WG-LTS meeting is the following:

- we need to create a YAML file in k/k that has a support matrix of the current release with regard external deps (this needs a sig-arch stamp). people were mostly +1 on this.
- after we have the YAML we need to educate contributors (i'm throwing :eyes: at the cluster folder folks, for this one) to bump the YAML with their PRs. this is the hardest task.
- release notes and website need to link to the YAML or use it as machine consumable. (this needs approval by sig-docs on the location and sig-release about writing a tool that consumes the YAML for the release notes).
