### ISSUE TITLE
Stop using API server's `--insecure-port`

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1283]
From startup logs:
```
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
```
@fabriziopandini @timothysc

**Comment by RA489** [comment]
@luxas I will work on this.

**Comment by neolit123** [comment]
thanks @RA489 
/lifecycle active

**Comment by luxas** [comment]
Thanks @RA489 :clap:!

**Comment by neolit123** [comment]
we had to revert the previous PR, see:
https://github.com/kubernetes/kubernetes/issues/75412

we can only remove once this changes:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/options/deprecated_insecure_serving.go#L76-L79

**Comment by smekkley** [comment]
I'm not convinced that it is a good idea. Kubeadm is free to remove from the default but saying it's deprecated gives a totally a wrong impression.
Listening to only localhost for http is one of the valid use case.

**Comment by mydockergit** [comment]
Why do you want to remove it? How developers will be able to debug Kubernetes network ?  I am a developer and I can't debug it because the network is encrypted.

**Comment by neolit123** [comment]
forgot that we had this ticket already.
logged https://github.com/kubernetes/kubeadm/issues/2156
which links to the new k/k tracking issue.

/close
