### ISSUE TITLE
Certify kubeadm v1.13 as a Conformant Kubernetes deployment

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1288]
We should do this ASAP after v1.13 is cut to kick off the v1.13 programme.

xref: https://github.com/kubernetes/kubeadm/issues/1061

/assign @stealthybox @timothysc @fabriziopandini 
@stealthybox (to certify kubeadm if you have time)
@timothysc (to make sure sonobuoy is able to handle v1.13)
@fabriziopandini (as backup if @stealthybox is unavailable)

**Comment by rdodev** [comment]
@luxas I'm on it. As soon as 1.13 is cut, I'll run conformance.

**Comment by luxas** [comment]
@rdodev Thanks :tada:!

**Comment by rdodev** [comment]
On it. Testing v1.13.0 conformance via sonobuoy scanner.

Results will be found here: https://scanner.heptio.com/3f1f5668066edb40a648f065de811acb/

**Comment by rdodev** [comment]
Conformance has passed: https://scanner.heptio.com/3f1f5668066edb40a648f065de811acb/diagnostics/

**Comment by luxas** [comment]
I'll submit a PR like: https://github.com/cncf/k8s-conformance/pull/353

**Comment by luxas** [comment]
Sonobuoy doesn't support v1.13 at the moment, and needs to be updated first: https://github.com/heptio/sonobuoy/issues/560

**Comment by luxas** [comment]
Now got around to submitting the PR, here we go: https://github.com/cncf/k8s-conformance/pull/403

**Comment by neolit123** [comment]
https://github.com/cncf/k8s-conformance/pull/403
seems to be merged.
