### ISSUE TITLE
Write a survey and sync it with the blog post for 1.13

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1289]
EDIT: link is private for now.

**Comment by neolit123** [comment]
i think we have time until Saturday because we want to release it in-sync with the blog - i.e. have a link in the blog.

**Comment by neolit123** [comment]
survey is pretty much done at this point. tomorrow is the end date for this.
we broke it down into sections after @fabriziopandini suggested an early exit and a couple of more questions.

**Comment by timothysc** [comment]
I've added some questions and rephrased others.

**Comment by neolit123** [comment]
this is done.
