### ISSUE TITLE
RFE: Audit default limits and priorities 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#1291]
We need to update limit defaults and make certain we are using sane values for priorities.  We have legacy cruft that also needs to be audited. 

xref: https://github.com/kubernetes/kubernetes/pull/69734

**Comment by fabriziopandini** [comment]
This is spreading:
https://github.com/kubernetes/kubernetes/pull/72424 (control plane components)
https://github.com/kubernetes/kubeadm/issues/1337 (core DNS)

**Comment by yagonobre** [comment]
I can work on this
/lifecycle active

**Comment by fabriziopandini** [comment]
@yagonobre fyi there is also https://github.com/kubernetes/kubernetes/pull/73649

**Comment by timothysc** [comment]
needs 
priorityClassName: system-cluster-critical 

and remove older field (TBD)

**Comment by ereslibre** [comment]
@yagonobre as per our discussion today, are you OK with me having a look at this?

**Comment by ereslibre** [comment]
Certainly, we were using `scheduler.alpha.kubernetes.io/critical-pod` annotation.

**Comment by yagonobre** [comment]
@ereslibre go ahead :)
/unassign

**Comment by yagonobre** [comment]
IMO we should add request/limit too.
