### ISSUE TITLE
Remove the v1alpha3 config API version in v1.15

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1296]
It has been deprecated in v1.13 in favor of v1beta1, and will be removed in v1.14

@rosti can you send a PR for this?
I & @fabriziopandini will review it.
/assign @luxas @fabriziopandini @rosti

**Comment by rosti** [comment]
I am on it.

/lifecycle active

**Comment by luxas** [comment]
Thanks!

**Comment by neolit123** [comment]
@luxas , @timothysc proposed that we keep this old version for a longer time - maybe one more cycle?
the idea would be to not allow clusters that use it and return an error, but keep it for the sake of having godocs for it.

**Comment by rosti** [comment]
Yes, this was discussed yesterday at the kubeadm office hours. I agree with that.
In the mean time I can put together a PR to disable creating/joining clusters with v1alpha3, but still allow it `kubeadm config migrate` to convert such configs into v1beta1.

**Comment by luxas** [comment]
Sounds good to me :+1:

**Comment by neolit123** [comment]
are we shifting the actual removal to 1.15?
if so, i can adjust the ticket description.

**Comment by luxas** [comment]
Yes, done
