### ISSUE TITLE
Bump minimum supported version to v1.13 at HEAD

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1297]
xref: https://github.com/kubernetes/kubeadm/issues/1260
this should be simpler than it is but meanwhile...

let's:
 - bump the minimum version to v1.13 at HEAD
 - remove v1.12-specific code
 - remove v1.10, v1.11, v1.12 records for matching etcd versions

@yagonobre or @ereslibre can you help with this?

**Comment by luxas** [comment]
cc @rosti @fabriziopandini @timothysc @neolit123

**Comment by neolit123** [comment]
ideally https://github.com/kubernetes/kubeadm/issues/1260
should probably done before this.

constants need cleanup first....

**Comment by luxas** [comment]
Can do it after as well, or at the same time :wink: whatever works for me as long as we do both

**Comment by fabriziopandini** [comment]
@yagonobre I guess this is done for v1.13 or I'm wrong?
