### ISSUE TITLE
Cleanup upgrade from no-TLS etcd to TLS etcd

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1298]
Kubeadm upgrade still implements support from no-TLS local etcd to TLS local etcd, that should not be necessary anymore

**Comment by yuexiao-wang** [comment]
I will work on it.
/assign

**Comment by yagonobre** [comment]
Thanks @yuexiao-wang
/lifecycle active

**Comment by yagonobre** [comment]
Closed by https://github.com/kubernetes/kubernetes/pull/71740
/close
