### ISSUE TITLE
Minor improvements on upgrade Docs

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1301]
In [Installing kubeadm](https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) we are suggesting to `apt-mark hold` packages.

On [upgrade instructions](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13/ ) for single node cluster we should suggest `apt-mark unhold` before and `apt-mark hold` again after, similar to what already implemented in [HA upgrade instructions](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha-1-13/)

If I'm not wrong, this should apply to v1.12 to v1.13 upgrade instructions only 

/cc @neolit123

**Comment by yuexiao-wang** [comment]
I will work on it

**Comment by yagonobre** [comment]
Thanks @yuexiao-wang
/lifecycle active
