### ISSUE TITLE
No cloud provider specified  &  No api server defined - no events will be sent to API server.

### ISSUE THREAD

**Issue by para27rsh** [kubernetes/kubeadm#1302]
I am getting this Error while running kubelet 
Following Steps mentioned 
http://kamalmarhubi.com/blog/2015/08/27/what-even-is-a-kubelet/

![screenshot from 2018-12-05 14-24-06](https://user-images.githubusercontent.com/27858047/49501972-1a053100-f89a-11e8-9a2e-4c9f16430257.png)

Inside **manifest** folder 

**nginx.yaml**

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  -name: nginx
   image: nginx
   ports:
   - containerPort: 80
   volumeMounts:
   - mountPath: /var/log/nginx
     name: nginx-logs
  -name: log-truncator
   image: busybox
   command:
   - /bin/sh
   args: [-c, 'while true; do cat /dev/null > /logdir/access.log; sleep 10; done']
   volumeMounts:
   - mountPath: /logdir
     name: nginx-logs
  volumes: 
  - name: nginx-logs
    emptyDir: {}

**Comment by neolit123** [comment]
please re-open if this is kubeadm related.
also provide your whole setup by following this template:
https://github.com/kubernetes/kubeadm/blob/master/.github/ISSUE_TEMPLATE.md

thanks!
