### ISSUE TITLE
kubeadm token create: kubeconfig flag should take higher precedence than kubeconfig in home dir

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubeadm#1304]
## What keywords did you search in kubeadm issues before filing this one?

kubeadm token create kubeconfig precedence

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 
```
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:54:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):  
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): RHEL 7.5 
- **Kernel** (e.g. `uname -a`): `3.10.0-862.14.4.el7.x86_64`
- **Others**:

## What happened?

`kubeadm token create` was using a stale kubeconfig file that was located in `~/.kube/config`, instead of using the kubeconfig file specified via the `--kubeconfig flag`. The stale kubeconfig file was pointing to an old cluster that no longer existed, and thus the token creation was failing.

## What you expected to happen?

`kubeadm token create` should use the kubeconfig file specified via the `--kubeconfig`  flag

## How to reproduce it (as minimally and precisely as possible)?
1. kubeadm init
2. Create a kubeconfig file in ~/.kube/config. Set the server to some non-existent location.
3. Attempt to create a token using `kubeadm token create --kubeconfig /etc/kubernetes/admin.conf`

## Anything else we need to know?
I looked at the source briefly and I am wondering if the issue is here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/util/cmdutil.go#L73

It seems like the DefaultClientConfigLoadingRules take precedence over the --kubeconfig flag? If so, this issue probably affects other kubeadm commands.

**Comment by neolit123** [comment]
> I looked at the source briefly and I am wondering if the issue is here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/util/cmdutil.go#L73
It seems like the DefaultClientConfigLoadingRules take precedence over the --kubeconfig flag? If so, this issue probably affects other kubeadm commands.

if the file that is being passed is different from the value from `kubeadmconstants.GetAdminKubeConfigPath()` (or `/etc/kubernetes/admin.conf`)
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/util/cmdutil.go#L67

then it should use the file, if not it will try to search for standard location and only then use the file.

i think we should amend this to prepend the default location, to avoid this scenario.
we had a talk about it when doing the 1.13 refactor, but this slipped trough.

for now the workaround for you is to just move the file somewhere.

/assign
/kind bug
/area UX
/priority important-soon

**Comment by alexbrand** [comment]
Yup, I ended up just removing the stale file. Thanks @neolit123

**Comment by neolit123** [comment]
it was agreed that this is not a bug and commands such as token should search in the KUBECONFIG env variable first.
`init` and `reset` on the other hand should search for the default kubeadm path first.

**Comment by alexbrand** [comment]
There is no `KUBECONFIG` environment variable here. 

The problem is that kubeadm uses the kubeconfig file in `~/.kube/config ` when the value of the `--kubeconfig` flag is `/etc/kubernetes/admin.conf`.

I have added some test cases below:

#### No ~/.kube/config file:
```
root@kind-1-control-plane:~# ls -l ~/.kube
total 16
-rw------- 1 root root 5450 Feb  3 18:31 bad.kubeconfig
drwxr-xr-x 3 root root 4096 Jan 28 19:56 cache
drwxr-xr-x 3 root root 4096 Feb  3 18:15 http-cache
root@kind-1-control-plane:~# KUBECONFIG='' kubeadm token create --kubeconfig /etc/kubernetes/admin.conf
I0203 18:33:34.032236    9677 version.go:236] remote version is much newer: v1.13.3; falling back to: stable-1.12
pcmm19.9s6kq8pxg2jviugo
```
Result: Successfully creates token.

#### ~/.kube/config with a bad `server` entry (i.e. points to a non-existent server)
```
root@kind-1-control-plane:~# cp ~/.kube/bad.kubeconfig ~/.kube/config
root@kind-1-control-plane:~# KUBECONFIG='' kubeadm token create --kubeconfig /etc/kubernetes/admin.conf
I0203 18:34:09.192782    9910 version.go:236] remote version is much newer: v1.13.3; falling back to: stable-1.12
timed out waiting for the condition
```
Result: Times out trying to talk to non-existent server defined in `~/.kube/config`. In this case, I would expect `/etc/kubernetes/admin.conf` to be used, instead of `~/.kube/bad.kubeconfig`.

I think the problem might lie in that the default value of `--kubeconfig` in kubeadm is `/etc/kubernetes/admin.conf`. This is different than kubectl, where the default value of `--kubeconfig` is the empty string.

**Comment by neolit123** [comment]
my mistake for not clarifying,
`~/.kube/config` should **also** take precedence over the `/etc/kubernetes/admin.conf`.

this comment outlines the precedence and for which commands it is activated:

https://github.com/kubernetes/kubernetes/pull/71874#issuecomment-460072241

**Comment by alexbrand** [comment]
That seems confusing as a user? 

As a user, when I specify the --kubeconfig flag, I would expect that to be the kubeconfig to be used, regardless of the value.

**Comment by alexbrand** [comment]
Yeah, exactly! Seems like we need a way to tell whether the user set the flag or not.

**Comment by neolit123** [comment]
> Yeah, exactly! Seems like we need a way to tell whether the user set the flag or not.

latest update of the PR should handle that:
https://github.com/kubernetes/kubernetes/pull/71874
