### ISSUE TITLE
Kubernetes cluster from 1.10.6 to 1.11.5, except master node, pods in other nodes are assigned with 172.17.x.x

### ISSUE THREAD

**Issue by alanh0vx** [kubernetes/kubeadm#1305]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

 BUG REPORT 

## Versions
v1.10.6 to v1.11.5

## What happened?
I have followed the guide to upgrade the cluster from v1.10.6 to 1.11.5
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/

upgrade was "successful" and pods are up and running.

however, the pods often throw errors of "no routes to host", then after some checking, we found that in master node, the pods are assigned correctly with 192.168.x.x

but other nodes, the pods are assigned with 172.17.0.x

## What you expected to happen?
expect pods are assigned with 192.168.x.x

**Comment by neolit123** [comment]
hi, for a certain host kubeadm tries to find the preferred outbound address from your default network interface. there seems to be something strange happening in your setup.

please provide outputs from the following commands:
`iptables --list`
`ifconfig`
`route`

cc @rosti @mauilion

**Comment by rosti** [comment]
Also, what is the network plugin you are using? Is it Calico?

**Comment by mauilion** [comment]
Can you also provide the output of
`kubectl get ippools -o yaml`

**Comment by alanh0vx** [comment]
Hi All,

probably some settings were being overwritten during the upgrade, after doing some investigation,

We try to add the following in each node:

```
vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf 
```
adding ` --network-plugin=cni` as the parameter

`systemctl daemon-reload` and `systemctl restart kubelet`

then the pods will be assigned correctly.

but we still can't confirm why the settings were change during upgrade
