### ISSUE TITLE
kubeadm v1.13 ignores --kubeconfig-dir on phases

### ISSUE THREAD

**Issue by tommyknows** [kubernetes/kubeadm#1306]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT (?)

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:02:01Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

## What happened?
I'm writing a script to automate kubernetes deployments with kubeadm. Up until now, I have used the following command to do all the steps regarding bootstrap-tokens on a remote server:
```
kubeadm init phase bootstrap-token all --config "$kubeadm_config_file" --kubeconfig "$kubeconfig_file"
```
With kubeadm v1.13, this does not work anymore - there's no `--kubeconfig` flag anymore. 
I'm now trying to use
```
kubeadm phase bootstrap-token all --config "$kubeadm_config_file" --kubeconfig-dir "$kubeconfig_dir
```
This does not work:
```
can not mix '--config' with arguments [kubeconfig-dir]
```
I have removed the `--config` flag (as this may not be relevant in my case), and set `$kubeconfig_dir` to a path that contains the `admin.conf` file or giving the path to a valid kubeconfig file directly into this variable.
However, I am always getting the following output:

```
error execution phase bootstrap-token: failed to load admin kubeconfig: open etc/kubernetes/admin.conf: no such file or directory
```

## What you expected to happen?
I expect kubeadm to either read from the kubeconfig-file (supplied by `--kubeconfig-dir`), or search the `--kubeconfig-dir` for a `admin.conf` file.

## How to reproduce it (as minimally and precisely as possible)?
- have a running kubernetes master
- copy the kubeconfig file (`admin.conf`) to some path
- run `kubeadm init phase bootstrap-token --kubeconfig-dir [KUBECONFIG-PATH]

**Comment by yagonobre** [comment]
Hi @tommyknows can you post the output of `echo $kubeconfig_file`

**Comment by yagonobre** [comment]
@tommyknows I'll send a pr with the fix sson
/remove-priority  awaiting-more-evidence
/priority important-soon
