### ISSUE TITLE
Identify a solution for godoc links versioning

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1307]
In the k8s website we are using links to the api to get

However, while the k8s website is versioned, godoc is always generated from master, so it might happen that the code linked by godoc changes or get deleted e.g. links to old v1alphaX<3 kubeadm config 

Ideally, godoc link should be defined pointing to specific branch/tags instead of master, but I don't know if it is possible...
See https://github.com/golang/gddo/issues/593

**Comment by yagonobre** [comment]
I tested with gopkg.in, as you said in the meeting, but the k8s branchs are named `release-1.12.0` and gopkg.in don't allow points in the branch name =/

**Comment by timothysc** [comment]
Closing because of the support window and change on versioning.
