### ISSUE TITLE
not able to pass properly specific configuration parameters to api server

### ISSUE THREAD

**Issue by mszumilak** [kubernetes/kubeadm#1309]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

The apiServerExtraArgs is dictionary:
```
apiServerExtraArgs:
  authorization-mode: Node,RBAC
  bind-address: 0.0.0.0
```

Passing additional arguments with special characters is not possible.

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
```
--oidc-username-prefix string
--
  | If provided, all usernames will be prefixed with this value. If not provided, username claims other than 'email' are prefixed by the issuer URL to avoid clashes. To skip any prefixing, provide the value '-'.
```

Providing "-" requires API server manifest to have the line enquoted:
```
$ grep -E "oidc.*prefix"  /etc/kubernetes/manifests/kube-apiserver.manifest
    - "--oidc-username-prefix="
    - "--oidc-groups-prefix=keycloak:"
$
```

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:54:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: baremetal
- **OS** (e.g. from /etc/os-release): CentOS Linux 7

## What happened?
```
/usr/local/bin/kubeadm  upgrade apply -y v1.12.3 --config=/etc/kubernetes/kubeadm-config.v1alpha3.yaml  --ignore-preflight-errors=all --allow-experimental-upgrades --allow-release-candidate-upgrades --etcd-upgrade=false --force
```
failed because of not properly enquoted configuration lines were causing API server not starting.

Due to dictionary nature of yaml manifest it's not possible to place double hyphen inside the quote.

## What you expected to happen?
I'd like to have possiblity to pass special parameters not as dictionary but taken "as is".

## How to reproduce it (as minimally and precisely as possible)?
Try to pass any argument to api server that accepts ":" in the argument or "-" as argument.

**Comment by mszumilak** [comment]
Maybe adding additional section called:
```
apiServerExtraArgsRaw 
```
as a yaml list containing only strings would be an option here?

**Comment by neolit123** [comment]
> Passing additional arguments with special characters is not possible.

what special characters are you passing?

```
apiServerExtraArgs:
  oidc-username-prefix: "somePrefix"
```

this should work.

**Comment by mszumilak** [comment]
This does not work.

```
apiServerExtraArgs:
  oidc-username-prefix: "-"
```

After setting it up there's an error in redeploying services and rollback to previous version.

**Comment by neolit123** [comment]
downgrade from 1.12.3 to 1.12.1 worked fine and after that i again see this in the apiserver manifest:
```
- --oidc-username-prefix=-
```

**Comment by neolit123** [comment]
> After setting it up there's an error in redeploying services and rollback to previous version.

what is the error you are seeing? i cannot confirm this.

**Comment by fabriziopandini** [comment]
I double checked @neolit123 solution and it works also for me, so IMO `kubeadm init` is able to pass properly specific configuration parameters to the API server.
@mszumilak is it possible to close this issue?
