### ISSUE TITLE
Adopt pod checkpointer

### ISSUE THREAD

**Issue by pires** [kubernetes/kubeadm#131]
Refs #127

**Comment by luxas** [comment]
This task includes:
 - moving the checkpointer from https://github.com/kubernetes-incubator/bootkube/blob/master/cmd/checkpoint/main.go (probably with commit history) to the kubeadm repo
 - adding a license header to the files
 - moving to client-go
 - renaming the annotation used 
 - creating a `Makefile` that can build and push the binary for multiple architectures to gcr.io

**Comment by errordeveloper** [comment]
I am somewhat reluctant to moving the moving the code without making any use of it, what is the follow up accomplishment? If we are not so sure, may be we shouldn't do it until we are sure.

**Comment by luxas** [comment]
First, move the code to kubernetes/kubeadm, and once we have the Makefile as well, @mikedanese will push the Docker image with that checkpointer inside and then we'll deploy it when using selfhosting and kuebadm.

**Comment by pires** [comment]
Also @aaronlevy mentioned that when this move is done, bootkube would be changed to use the _upstream_ (this!) solution.

**Comment by luxas** [comment]
Exactly! Both can take advantage of and experiment with it!

**Comment by aaronlevy** [comment]
What is the process for getting images built? That would be my only concern moving bootkube over (e.g. needing a fix but not being able to get an image built). But I don't want to have to manage changes between the code in two places - so ideally can move over to a single source of truth quickly.

**Comment by luxas** [comment]
That can be a bottleneck frankly, since Googlers only have push access to gcr.io
But maybe @mikedanese can promise to push images quickly if there have been changes committed  ;)

**Comment by luxas** [comment]
@timothysc is working on implementing this; it's tracked in a features issue as well: https://github.com/kubernetes/features/issues/378

**Comment by luxas** [comment]
@timothysc I'm moving this to v1.9

**Comment by luxas** [comment]
@timothysc we need to annotate the control plane manifests with the magic annotation if the feature gate is set now, right?

**Comment by timothysc** [comment]
yes, add `node.kubernetes.io/bootstrap-checkpoint=true`

**Comment by timothysc** [comment]
complete details are here - https://github.com/kubernetes/community/pull/1241/files

**Comment by jberkus** [comment]
This issue is listed as being in 1.9, can we have a status?  It appears that there hasn't been any work on it in a while.

**Comment by luxas** [comment]
Moved to v1.10 as discussed in the SIG

**Comment by timothysc** [comment]
@errordeveloper was going to re-look into the secrets issues and the multiple approaches.

**Comment by timothysc** [comment]
Closing, I have cleaner plans.
