### ISSUE TITLE
Kubeadm reset should cleanup control-plane nodes properly

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1312]
Kubeadm reset should take care of removing control-plane nodes from the ClusterStatus status ConfigMap

**Comment by Klaven** [comment]
I'll take this one.

**Comment by yagonobre** [comment]
Thanks @Klaven 
/lifecycle active

**Comment by fabriziopandini** [comment]
additional info as per @Klaven request:

`kubeadm-config` ConfigMap is in `kube-system` namespace

All the machinery for reading/writing the config map already exists in `cmd/kubeadm/app/phases/uploadconfig/uploadconfig.go` and `cmd/kubeadm/app/util/config/cluster.go`

The ConfigMap has two key values: one for the `ClusterConfiguration`object, one for the `ClusterStatus`

Whenever a control-plane node joins, a new entry is created in `ClusterStatus`; this PR should implement removal of entry from the `Clust erStatus`whenever a `kubeadm reset` operation is executed on a control-plane node.

**Comment by ereslibre** [comment]
Is it also desired to attempt a `kubectl delete node` aside from modifying the `kubeadm-config` configmap?
