### ISSUE TITLE
upgrade v1.10.7 -> v1.10.11

### ISSUE THREAD

**Issue by chenxushuo** [kubernetes/kubeadm#1314]
## Is this a BUG REPORT or FEATURE REQUEST?
 BUG REPORT 

## Versions
**kubeadm version** (use `kubeadm version`):
v1.10.11
**Environment**:
- **Kubernetes version** (use `kubectl version`):
v1.10.7
- **Cloud provider or hardware configuration**:
alicloud
- **OS** (e.g. from /etc/os-release):
centos 7
- **Kernel** (e.g. `uname -a`):
 3.10.0-693.2.2.el7.x86_64
- **Others**:

## What happened?
when i want to upgrade V1.10.7 to V1.10.11  used kubeadm , I run CMD 'kubeadm upgrade plan',
But I cann't get the version what i want  ，because the kubeadm  search a error stable URL !
```
[root@cn-shenzhen upgrade]# ./kubeadm version  
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
[root@cn-shenzhen upgrade]# ./kubeadm upgrade plan
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade/plan] computing upgrade possibilities
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.10.7
[upgrade/versions] kubeadm version: v1.10.11
[upgrade/versions] Latest stable version: v1.13.0
[upgrade/versions] WARNING: Couldn't fetch latest version in the v1.1 series from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.1.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.1.txt: net/http: TLS handshake timeout
[upgrade/versions] WARNING: No recommended etcd for requested kubernetes version (v1.13.0)

External components that should be upgraded manually before you upgrade the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT   AVAILABLE
Etcd        3.2.18    N/A

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT       AVAILABLE
Kubelet     8 x v1.10.7   v1.13.0

Upgrade to the latest stable version:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.10.7   v1.13.0
Controller Manager   v1.10.7   v1.13.0
Scheduler            v1.10.7   v1.13.0
Kube Proxy           v1.10.7   v1.13.0
Kube DNS             1.14.8    1.14.8

You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply v1.13.0

Note: Before you can perform this upgrade, you have to update kubeadm to v1.13.0.
```
`why  get URL "https://dl.k8s.io/release/stable-1.1.txt" ?`
## What you expected to happen?
 get URL "https://dl.k8s.io/release/stable-1.10.txt" 
```
[root@VM_0_12_centos ~]# curl -sSL https://dl.k8s.io/release/stable-1.10.txt
v1.10.11
```

**Comment by neolit123** [comment]
> [upgrade/versions] WARNING: Couldn't fetch latest version in the v1.1 series from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.1.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.1.txt: net/http: TLS handshake timeout

this seems like a bug to me. it should be `https://dl.k8s.io/release/stable-1.10.txt`

>  kubeadm upgrade apply v1.13.0

but we also have the question if we want to cap upgrades from minor X -> X+1 as the maximum version to check. currently the 1.10 client find 1.13 and this upgrade skew is not possible.

cc @rdodev @chuckha @timothysc 

/kind bug
/area upgrades
/priority important-longterm

**Comment by chenxushuo** [comment]
if you want to cap upgrades from minor X -> X+1 as the maximum version to check，you should check  "https://dl.k8s.io/release/stable-1.txt" not  "https://dl.k8s.io/release/stable-1.1.txt" ?!

**Comment by chenxushuo** [comment]
And then ,Can i  run the CMD  to update my kubernetes?
```
 kubeadm upgrade apply v.1.10.11
```

**Comment by fabriziopandini** [comment]
@chenxushuo yes, you can always specify a version on `kubeadm upgrade apply`

**Comment by chenxushuo** [comment]
OK thk！
