### ISSUE TITLE
change api server config

### ISSUE THREAD

**Issue by Lokicity** [kubernetes/kubeadm#132]
After deployment, I want to change some command line setting in the api server to accept different certificate authorities other than self signed one by kubernetes. 

Theoretically, I should be able to change /etc/kubernetes/manifests/kube-apiserver.json and restart the api server. However, my kubectl becomes unreponsive even though all I did was a open json and :wq
I didn't change any config, I just did a save and exit command. 
when I do docker ps, I no longer see my api-server as a running pod
And this is my kubelet log

```
Jan 23 23:40:05 photon-rAxxJw9jm kubelet[9030]: E0123 23:40:05.212028    9030 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://10.118.97.39:6443/api/v1/nodes?fieldSelector=metadata.name%3Dphoto...onnection refused
Jan 23 23:40:05 photon-rAxxJw9jm kubelet[9030]: E0123 23:40:05.212421    9030 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://10.118.97.39:6443/api/v1/pods?fieldSelector=spec.nodeName%3...onnection refused
Jan 23 23:40:05 photon-rAxxJw9jm kubelet[9030]: E0123 23:40:05.431676    9030 event.go:208] Unable to write event: 'Post https://10.118.97.39:6443/api/v1/namespaces/kube-system/events: dial tcp 10.118.97.39:6443: getsockopt: con...y after sleeping)
Jan 23 23:40:06 photon-rAxxJw9jm kubelet[9030]: E0123 23:40:06.212137    9030 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://10.118.97.39:6443/api/v1/services?resourceVersion=0: dial tcp 1...onnection refused
Jan 23 23:40:06 photon-rAxxJw9jm kubelet[9030]: E0123 23:40:06.212652    9030 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://10.118.97.39:6443/api/v1/nodes?fieldSelector=metadata.name%3Dphoto...onnection refused
Jan 23 23:40:06 photon-rAxxJw9jm kubelet[9030]: E0123 23:40:06.213010    9030 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://10.118.97.39:6443/api/v1/pods?fieldSelector=spec.nodeName%3...onnection refused
Jan 23 23:40:06 photon-rAxxJw9jm kubelet[9030]: E0123 23:40:06.251623    9030 mirror_client.go:87] Failed deleting a mirror pod "kube-apiserver-photon-raxxjw9jm_kube-system": dial tcp 10.118.97.39:6443: getsockopt: connection refused
Jan 23 23:40:07 photon-rAxxJw9jm kubelet[9030]: E0123 23:40:07.212785    9030 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://10.118.97.39:6443/api/v1/services?resourceVersion=0: dial tcp 1...onnection refused
```

I am using kubeadm 1.5.1, is this the expected behavior? How can I get around this. How I specify different set of parameters to api server other then the default ones using kubeadm?

**Comment by Lokicity** [comment]
To clarify, after I save the kube-apiserver.json, when I run docker ps -a
My apiserver container was not in it anymore. It got deleted by somethingl.
"kube-controller-mana" and   "kube-scheduler --v=2" get exited

**Comment by kargakis** [comment]
Restart kubelet on the machine your master components are running and you should see the apiserver back up. In 1.6 it should be easier to update the api server with the self-hosted deployment: https://github.com/kubernetes/kubernetes/pull/40075
