### ISSUE TITLE
kubelet.service: Service hold-off time over, scheduling restart. 

### ISSUE THREAD

**Issue by kshitijkarandikar** [kubernetes/kubeadm#1320]
### Context
We are currently using a few clusters with v1.8.7 (which was created by currently unavailable developers, months ago) and are trying to upgrade to a higher version.
However, we wanted to try the same on an cluster we use for experimental & POCs.

### What we tried
In doing the same, we tried to run a few kubeadm commands on one of the master nodes, but kubeadm was not found.

So, we tried installing the same with commands -
```
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl
```

### What happened
However, now that node has status Not Ready and kubelet service is failing

Any pointers on how to fix this and what we should've done ?

![image](https://user-images.githubusercontent.com/26628548/49947596-ee192980-fef1-11e8-96bd-40f257700619.png)

![image](https://user-images.githubusercontent.com/26628548/49947387-6af7d380-fef1-11e8-81f8-64b8575799d5.png)

**Comment by neolit123** [comment]
> We are currently using a few clusters with v1.8.7 

hi, i'm very sorry but 1.8.7 is outside of the support skew and the kubeadm maintainers don't have the bandwidth to support such versions.

your best bet for upgrading from such an old version is to ask on reddit/slack/stackoverflow.
also please mind that kubeadm only allows upgrading only one minor version at a time: 1.8 -> 1.9 -> 1.10.

thanks
