### ISSUE TITLE
Will not work on ubuntu 18.04

### ISSUE THREAD

**Issue by jbrandes** [kubernetes/kubeadm#1325]
## Is this a request for help? Yes. I tried to troubleshoot and it didn't work

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one? uninstall, purge, remove
If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST? bug report
Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): will not load 
 
**Environment*
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?

sudo snap install kubeadm
error: This revision of snap "kubeadm" was published using classic confinement
       and thus may perform arbitrary system changes outside of the security
       sandbox that snaps are usually confined to, which may put your system at
       risk.

       If you understand and want to proceed repeat the command including
       --classic.
jbrandes@k8s-master:~$ sudo snap install kubeadm--classic
error: snap "kubeadm--classic" not found

**Comment by rosti** [comment]
Hi @jbrandes and thank you for filing this issue!
Unfortunately the Kubernetes community does not produce snap packages for any of the components. I think, that those are done by Canonical themselves.
The community recommended way of installing kubeadm is through DEB or RPM packages as described here:
https://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by neolit123** [comment]
close as per @rosti 's comment +1

**Comment by BestBackwards** [comment]
I have to say, Kubernetes documentation for a non-existing user is utterly useless. How can you justify not providing functional installation instructions?

**Comment by mitchellmaler** [comment]
@BestBackwards
The install instructions for kubeadm is located here: https://kubernetes.io/docs/setup/independent/install-kubeadm/
It provides the steps, requirements and exact commands to run on the different supported distributions.
