### ISSUE TITLE
Use secure port for scheduler and controller-manager liveness probe

### ISSUE THREAD

**Issue by joshrosso** [kubernetes/kubeadm#1327]
## Feature request: 

Since 1.13, `kube-controller-manager` and `kube-scheduler` expose secure ports and marked insecure ports as deprecated.

scheduler: https://github.com/kubernetes/kubernetes/pull/69663

	change: 1.13
	enable secure port: 10259
	deprecate old port: 10251

controller-manager: https://github.com/kubernetes/kubernetes/pull/67069

	change: 1.12
	enable secure port: 10257
	deprecate old port: 10252

We should use the secure ports as the default the livenessProbes going forward. I have this fixed in a fork and will open a PR.

## Versions

**kubeadm version** 

```
kubeadm version: &version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-alpha.0.1048+21904a5f7d38b1", GitCommit:"21904a5f7d38b1054edad36f3b05b0d7bd556d08", GitTreeState:"clean", BuildDate:"2018-12-18T01:09:09Z", GoVersion:"go1.11.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by luxas** [comment]
Closing this as a duplicate of #1285

**Comment by rosti** [comment]
#1285 was about enabling secure serving, this is about redirecting the liveness probes to the secure ports. As of today, everything in #1285 is done, but the liveness probes are still working with HTTP.
/reopen

**Comment by neolit123** [comment]
@yastij i've sent a PR for this https://github.com/kubernetes/kubernetes/pull/85043
