### ISSUE TITLE
Refactor token.go flag names into const

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1333]
Flag names in [token.go](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/options/token.go) should be refactored into constants.

e.g. flag name `token` defined here
https://github.com/kubernetes/kubernetes/blob/7c112762b0df87f3a1772f3bbede7fe9185fa249/cmd/kubeadm/app/cmd/options/token.go#L48

Should be refactored into a constant defined into [constant.go](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/options/constant.go)

The same apply for `token-ttl`, `usages`, `groups`, `description` flags

**Comment by MalloZup** [comment]
@fabriziopandini, hi!  i can take this one but i will start looking at it after new year :fireworks: :dragon_face: :smile:

**Comment by Zyqsempai** [comment]
I can make it today;) Of course, If @MalloZup doesn't mind)

**Comment by fabriziopandini** [comment]
@Zyqsempai please sink with @MalloZup; this is not urgent

**Comment by Zyqsempai** [comment]
@fabriziopandini Sure.

**Comment by MalloZup** [comment]
@Zyqsempai i don't mind if you tackle this issue.

If you tackle this, reference your PR or PRs to this Issue so i know that you work on it.

From my part i will relook on this issue after the 3 January,  so if you wish to solve it before feel free! :)

For me is just for learning more the step by step internals of kubeadm, so is fine for me to pick another issuethe next time :sun_with_face: .

**Comment by Zyqsempai** [comment]
Done, merged, we can close the issue!!

**Comment by yagonobre** [comment]
Thanks @Zyqsempai 
/close
