### ISSUE TITLE
could not initialize etcdv3 client: open /calico-secrets/server.crt: no such file or directory

### ISSUE THREAD

**Issue by Jack-qing** [kubernetes/kubeadm#1334]
1. Environmental Science： ubuntu:16.04  docker:18.06  kubeadm:1.12.00  calico:v3.2.3

This problem is difficult to solve. I need help

To configure calico.yaml
[calico.txt](https://github.com/kubernetes/kubeadm/files/2717000/calico.txt)

guyi@guyi-KVM:~$ kubectl get pods -n kube-system -o wide
NAME                                       READY   STATUS             RESTARTS   AGE   IP               NODE       NOMINATED NODE
calico-kube-controllers-744cf7848f-qfwp5   1/1     Running            0          22h   192.168.10.120   guyi-kvm   <none>
calico-node-fvgpm                          1/2     CrashLoopBackOff   257        21h   192.168.10.106   node1      <none>
calico-node-wgghm                          2/2     Running            0          22h   192.168.10.120   guyi-kvm   <none>
coredns-576cbf47c7-46gsk                   1/1     Running            0          23h   172.16.58.65     guyi-kvm   <none>
coredns-576cbf47c7-qs6g6                   1/1     Running            0          23h   172.16.58.66     guyi-kvm   <none>
etcd-guyi-kvm                              1/1     Running            0          23h   192.168.10.120   guyi-kvm   <none>
kube-apiserver-guyi-kvm                    1/1     Running            0          23h   192.168.10.120   guyi-kvm   <none>
kube-controller-manager-guyi-kvm           1/1     Running            0          23h   192.168.10.120   guyi-kvm   <none>
kube-proxy-6d7f2                           1/1     Running            0          23h   192.168.10.120   guyi-kvm   <none>
kube-proxy-bpb68                           1/1     Running            0          21h   192.168.10.106   node1      <none>
kube-scheduler-guyi-kvm                    1/1     Running            0          23h   192.168.10.120   guyi-kvm   <none>

guyi@guyi-KVM:~$ kubectl logs -f calico-node-fvgpm -n kube-system

Error from server (BadRequest): a container name must be specified for pod calico-node-fvgpm, choose one of: [calico-node install-cni]

guyi@guyi-KVM:~$ kubectl -n kube-system logs -f -p calico-node-fvgpm -c calico-node

2018-12-30 07:33:28.411 [INFO][10] startup.go 252: Early log level set to info
2018-12-30 07:33:28.411 [INFO][10] startup.go 272: Using HOSTNAME environment (lowercase) for node name
2018-12-30 07:33:28.411 [INFO][10] startup.go 280: Determined node name: node1
Calico node failed to start
ERROR: Error accessing the Calico datastore: could not initialize etcdv3 client: open /calico-secrets/server.crt: no such file or directoryguyi@guyi

Installation and deployment：

1. sudo vim /etc/selinux/config
SELINUX=permissive

2. sudo vim /etc/sysctl.conf
net.ipv4.ip_forward = 1

3. sudo swapoff -a 

4. sudo vim /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1

5. sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

6. sudo vim /etc/docker/daemon.json
{                                                                                                                                            
 "registry-mirrors": ["http://hub-mirror.c.163.com"],                                                                                        
 "insecure-registries":["192.168.10.111:5000"],                                                                                              
 "iptables": false,                                                                                                                          
 "ip-masq": false,                                                                                                                           
 "storage-driver": "overlay2",                                                                                                               
 "graph": "/home/lk/docker"                                                                                                                  
}

7. sudo apt-get install -y kubelet=1.12.0-00 kubeadm=1.12.0-00 kubectl=1.12.0-00

sudo systemctl enable kubelet && sudo systemctl start kubelet

8. sudo kubeadm init --apiserver-advertise-address=192.168.10.120 --pod-network-cidr=172.16.0.0/16 --service-cidr=10.233.0.0/16 --kubernetes-version=v1.12.0

9. install calico
wget https://github.com/projectcalico/calico/releases/download/v3.2.3/release-v3.2.3.tgz

10.  kubectl apply -f release-v3.2.3/k8s-manifests/rbac.yaml

11.  sudo vim release-v3.2.3/k8s-manifests/hosted/calico.yaml
##############################
  #To configure etcd address
  etcd_endpoints: "https://localhost:2379"
############################## 
  #To configure etcd Related certificates and key 
  etcd_ca: "/calico-secrets/ca.crt"   # "/calico-secrets/etcd-ca"
  etcd_cert: "/calico-secrets/server.crt" # "/calico-secrets/etcd-cert"
  etcd_key: "/calico-secrets/server.key"  # "/calico-secrets/etcd-key"
##############################
          #To configure etcd  Related certificates and key Location on the host
          "etcd_key_file": "/etc/kubernetes/pki/etcd/server.key",
          "etcd_cert_file": "/etc/kubernetes/pki/etcd/server.crt",
          "etcd_ca_cert_file": "/etc/kubernetes/pki/etcd/ca.crt",
##############################
            #To configure cluster pod Address Scope  and kubeadm Consistency specified at startup
            - name: CALICO_IPV4POOL_CIDR
              value: "172.16.0.0/16"
##############################
        #To configure calico-node Use the host kubeadm Generated etcd Related certificates key
        - name: etcd-certs
          hostPath:
            path: /etc/kubernetes/pki/etcd
#          secret:
#            secretName: calico-etcd-secrets
#            defaultMode: 0400
##############################
        #To configure calico-kube-controllers Use the host kubeadm Generated etcd Related certificates key
        - name: etcd-certs
          hostPath:
            path: /etc/kubernetes/pki/etcd
#          secret:
#            secretName: calico-etcd-secrets
#            defaultMode: 0400

12. calico-node create clusterrolebinding
kubectl create clusterrolebinding kube-system-default-role-binding --clusterrole=cluster-admin --serviceaccount=kube-system:calico-node

13. run
kubectl apply -f release-v3.2.3/k8s-manifests/hosted/calico.yaml

**Comment by neolit123** [comment]
hi, please try with a dfferent CNI plugin like flannel or weave.
i don't see this as a kubeadm problem.

might be worth reporting here:
https://github.com/projectcalico/cni-plugin

/close
