### ISSUE TITLE
Refactor cloud-controller-manager options flags into constants

### ISSUE THREAD

**Issue by Zyqsempai** [kubernetes/kubeadm#1336]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

Flag names in https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/app/options/options.go can be refactored into constants

example: https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/app/options/options.go#L133

The refactoring inspired by https://github.com/kubernetes/kubeadm/issues/1333

**Comment by yagonobre** [comment]
Thanks @zyqsempai
/kind cleanup
/priority important-longterm
/help-wanted

**Comment by Zyqsempai** [comment]
@yagonobre I will take care of this one;) Thanks for your help!

**Comment by yagonobre** [comment]
Nice!
/lifecycle active

**Comment by fabriziopandini** [comment]
@Zyqsempai @yagonobre 
The cloud-controller code base is managed by other sigs, so IMO it is better to close this issue and reopen the original one in k/k

**Comment by timothysc** [comment]
Also agreed.
