### ISSUE TITLE
CoreDNS pods lack a positive priority value (no priority class specified)

### ISSUE THREAD

**Issue by seh** [kubernetes/kubeadm#1337]
## What keywords did you search in kubeadm issues before filing this one?

- _dns_
- _coredns_
- _priority_
- _class_
- _priorityclass_

## Is this a BUG REPORT or FEATURE REQUEST?

_BUG REPORT_

## Versions

**kubeadm version** (use `kubeadm version`):

```
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:36:44Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:  
  AWS EC2
- **OS** (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1911.5.0
VERSION_ID=1911.5.0
BUILD_ID=2018-12-15-2317
PRETTY_NAME="Container Linux by CoreOS 1911.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- **Kernel** (e.g. `uname -a`):  
  `Linux ip-10-105-50-28 4.14.84-coreos #1 SMP Sat Dec 15 22:39:45 UTC 2018 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`

## What happened?

After running _kubeadm init_ (allowing it to run [the "addon/coredns" phase](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/#cmd-phase-addon)), my cluster has a _Deployment_ called "coredns" in the "kube-system" namespace, and its pod spec template lacks a value for [the `PriorityClassName` field](https://github.com/kubernetes/api/blob/release-1.13/core/v1/types.go#L2886-L2893).

Without this field present, the CoreDNS pods receive the default pod priority, which is zero unless an administrator has created a `PriorityClass` object with a positive value and designated it as the global default. Normally, these CoreDNS pods will run on the master machines which will repel most tenant-submitted workload by virtue of the role taint, but still, it would be safer to run these CoreDNS pods at a boosted priority to make it clear that they must be scheduled and keep running at the expense of other, lesser pods—assuming that we agree that in-cluster DNS is a critical service.

## What you expected to happen?

The "coredns" _Deployment_'s pod spec template would have its "priorityClassName" populated with the value "system-cluster-critical," granting it a priority of 2,000,001,000.

## How to reproduce it (as minimally and precisely as possible)?

Run either _kubeadm init_ or _kubeadm init phase addon coredns_, confirm that it succeeds, then inspect the pods created by the resulting _Deployment_:
```
kubectl get pods \
  --namespace=kube-system \
  --selector=k8s-app=kube-dns \
  --output=custom-columns='NAME:{.metadata.name},CLASS:{.spec.priorityClassName},VALUE:{.spec.priority}'
NAME                       CLASS    VALUE
coredns-86c58d9df4-xfp9f   <none>   0
coredns-86c58d9df4-zn7rd   <none>   0
```

## Anything else we need to know?

If we can't agree that [the built-in priority class "system-cluster-critical"](https://sourcegraph.com/github.com/kubernetes/kubernetes@71050b6f2dfe67bb2fb6d0acf6a64bc1e3cc50b0/-/blob/pkg/apis/scheduling/helpers.go#L35-41) is appropriate here, we could define a weaker or lower priority class. At the level at which _kubeadm init_ operates, though, it's hard to say how we'd guess what a more appropriate priority value would be, and we may inadvertently make it more difficult for administrators to restrict use of high-priority classes by introducing more of them.

Some precedent for using the "system-cluster-critical" priority class in _kubeadm_: kubernetes/kubernetes#63684 (addressing #395).

**Comment by timothysc** [comment]
From slack : 
>  "TBH I was going to wait a while, given some of the issues we have witnessed with CoreDNS.  We want to keep update the controlplane components and once CoreDNS matures more than yes."

**Comment by fabriziopandini** [comment]
closing in favour of https://github.com/kubernetes/kubeadm/issues/1291

**Comment by ojmhetar** [comment]
@fabriziopandini I feel that #1291 does not point out the [lack of a pod priority](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/pod-priority-api.md#priority-and-qos-classes) for coredns. While kubeadm must set sane defaults for requests/limits, shouldn't coredns also have an appropriate `priorityClassName`?

**Comment by fabriziopandini** [comment]
@ojmhetar I think that priority should be set in a consistent way in all the components managed by kubeadm. This is why I grouped things in one issue - arbitrary choosen - and reported there the link to all the variations of the same issue (see [comment](https://github.com/kubernetes/kubeadm/issues/1291#issuecomment-452282756)), and then raised the topic at the planning meeting. 
If you don't agree with this approach feel free to re-open / open a new issue
