### ISSUE TITLE
How to create a cluster using kube-up.sh??

### ISSUE THREAD

**Issue by ariamore** [kubernetes/kubeadm#1339]
Hi!! I'm  new in programming with Kubernetes. I'm trying to create my first cluster, but I've had some trouble. I use Linux via Ubuntu. 
Following the online kubernetes's guide, first I installed kubectl, and I tried to configure it deploying Minikube (unsuccessful, because I find a bug with the kubeadm' initialization file). So, I decide to install cluster using "kube-up.sh", but I didn't find any instructions about it on internet.
Someone has any ideas to how can I find the instruction? Or, have you find a solution with minikube config problem?? 

Thank u in advance!!

**Comment by fabriziopandini** [comment]
@ariamore 
minikube gives you a single node cluster running in a VM. if you have trouble in using minikube you can file an issue on github kubernetes/minikube or join the #minikube channel on kubernetes slack
https://kubernetes.io/docs/setup/minikube/

kubeadm  is used internally by minikube, but this should be transparent to you. kubeadm can be used also as a standalone tool and it gives you a cluster running locally on your machine. If this is is what you want to do, this is the right place for filing an issue, or join the #kubeadm channel
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm 

some more info here:
https://kubernetes.io/docs/setup/pick-right-solution/

kubeup.sh is a legacy method for creating a cluster, and as far as I know, is going to be deprecated in favor of

**Comment by timothysc** [comment]
Closing, this is repo is for defect tracking and feature requests only.
