### ISSUE TITLE
Cannot change service IP range with flag service-cidr

### ISSUE THREAD

**Issue by shenshouer** [kubernetes/kubeadm#134]
Cannot change service IP range with flag service-cidr. I use commant `kubeadm init --service-cidr=10.100.0.0/12 `, actually init master with 10.96.0.0 .

**Comment by spdeshpande** [comment]
@shenshouer how did you resolve this? I am facing the same issue. kubeadm version is 1.6.1

**Comment by shenshouer** [comment]
@spdeshpande  The range of 10.100.0.0/12 is start at 10.96.0.1
