### ISSUE TITLE
Upgrade from 1.12.3 to 1.12.4 timeout

### ISSUE THREAD

**Issue by Mymetique** [kubernetes/kubeadm#1343]
Hello we tried to upgrade our staging and production clusters to kubernetes 1.12.4 from 1.12.3. We proceed with our staging without issue but when we tried on our production environment we encountered a timeout.

The process has been the same, upgrade of kubeadm, kubelet ect then upgrade with kubeadm. The kube-apiserver is stuck in container creating mode for 5 minutes before kubeadm upgrade timeouts and reverts back the changes. 

Is there any log I can provide or things to look for  ? 

Moreover now our cluster is running a 1.12.3 kubeapi but kubelet is in 1.12.4 can it be an issue ? 

Just to let you know that the image is already pulled, it's not a connectivity issue preventing to pull the image quickly enough. We tried 3 times before giving up for now.

Thank you very much for your help.

**Comment by timothysc** [comment]
> Moreover now our cluster is running a 1.12.3 kubeapi but kubelet is in 1.12.4 can it be an issue ? 

Yes, upgrade instructions clearly state to update control plane 1st.  

I'd recommend looking into the api-server logs, or if needed updating the default timeouts which can be found in the godoc documentation.

**Comment by antoinep92** [comment]
@timothysc thanks for the help, I assume you mean [this doc](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade). We indeed want to increase `UpgradeManifestTimeout`, but it doesn't appear to be in our config map (not referenced in`kubeadm config view` nor `kubeadm config print-default`) so from the doc it's not evident how this setting can be changed. Or do you mean temporarily patching `kubeadm` and shipping our modified version ?

**Comment by timothysc** [comment]
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1 

`timeoutForControlPlane`
