### ISSUE TITLE
/etc/sysconfig/kubelet config rpm

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubeadm#1346]
I just upgraded my rpm based system and it unexpectedly broke.

/etc/sysconfig/kubelet is reverting with each upgrade. The file should be marked as a config file in the rpm spec so it does not upgrade if there are changes.

**Comment by neolit123** [comment]
what is your OS?

TMK, the k8s project does not distribute config files other than the kubelet / kubeadm drop in file. the override has to come from elsewhere.

**Comment by kfox1111** [comment]
centos7

[root@p0 ~]# rpm -qf /etc/sysconfig/kubelet 
kubelet-1.12.2-0.x86_64

**Comment by kfox1111** [comment]
the /etc/sysconfig/kubelet file should have %config(noreplace) added to it.

I'm a bit confused though. the rpm came from the official rpm repository.

The only code I can find though for a spec file is in kubernetes/kubernetes/build/rpms/kubelet.spec

it does not reference the config file and the 'Summary' field is different then the one in the binary rpm:
The binary says:
Summary     : Container cluster management

the spec:
Summary: Container Cluster Manager - Kubernetes Node Agent

So that isn't the right spec file.

Where are the specs for the release rpms?

**Comment by kfox1111** [comment]
found it. https://github.com/kubernetes/release/blob/master/rpm/kubelet.spec

**Comment by kfox1111** [comment]
Here's a pr that should fix the issue: https://github.com/kubernetes/release/pull/658

**Comment by kfox1111** [comment]
See above for a pr that fixes the issue.

**Comment by neolit123** [comment]
@timothysc @Klaven 
we had this PR for this:
https://github.com/kubernetes/release/pull/658

**Comment by neolit123** [comment]
k/release PR merged.
