### ISSUE TITLE
Add preflight check for incorrect FQDN?

### ISSUE THREAD

**Issue by jberkus** [kubernetes/kubeadm#135]
There are a variety of system configuration errors (such as cloud-init bugs when deploying on AWS) which can cause hostname and uname -n to be wrong for a given host.  This will cause kubeadm setup to fail in interesting and hard-to-figure-out ways (it doesn't fail until you start trying to set up DNS on the master, for example).

Given this, would it be worth adding a preflight check for this?  Or would it be very hard to determine?

**Comment by luxas** [comment]
I think it's a good idea!

Feel free to contibute that! :smile:

**Comment by jberkus** [comment]
@luxas somehow I knew you would say that.  I've been trying to figure out how to test that the fqdn is wrong since I reported it.

**Comment by kad** [comment]
Do we have examples of "wrong" situations or github issues about that ?

**Comment by luxas** [comment]
@dmmcquay Can I assign you this?

@jberkus 

> @luxas somehow I knew you would say that.

Yeah, totally agree it wasn't an unexpected answer, I know that. Anyway, we're in need for more contributors so I had to check :smile:

But I think @dmmcquay could be a good assignee here

**Comment by dmmcquay** [comment]
@luxas Please do, I'll start working on this.

**Comment by mikedanese** [comment]
> Do we have examples of "wrong" situations or github issues about that ?

Agree, that we need an answer for this.

**Comment by jberkus** [comment]
I have a test case, I've just been on the road with Devconf/FOSDEM.  Sorry, will get it up next week.

**Comment by luxas** [comment]
@jberkus Any update on this? Do you want to improve something more in kubeadm regarding this?

**Comment by jberkus** [comment]
Oh, oops, forgot about this issue.  Will test as soon as I'm back from CoreOSFest.

**Comment by pipejakob** [comment]
@jberkus Friendly ping. Especially with https://github.com/kubernetes/kubernetes/pull/46772 merged, I'm curious if there are any more DNS-related issues left to fix. Are you able to test the newest 1.7 beta?

**Comment by jberkus** [comment]
It solves one case. I'll retest with the beta.

**Comment by jamiehannaford** [comment]
@jberkus Friendly ping :) Is there anything left that kubeadm can do here?

**Comment by jberkus** [comment]
I don't think so.  Declaring closed.
