### ISSUE TITLE
Deprecate and remove --cri-socket flag from kubeadm upgrade apply

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#1356]
For historical reasons `kubeadm upgrade apply` accepts a `--cri-socket` flag.
This is no longer needed, because the CRI socket of the node is stored in the NodeRegistrationOptions of the node at the cluster.
During `kubeadm upgrade apply` it is much safer and less error prone to fetch the CRI socket from the cluster, rather than rely on the user to supply the same value as upon `kubeadm init` or `kubeadm join`.

Timeline:
1. Mark the flag as deprecated (in 1.14).
- [X] kubernetes/kubernetes#69366
2. Remove the flag (+3 releases from deprecation - from 1.17 on wards)
- [ ] https://github.com/kubernetes/kubernetes/pull/85044

/kind cleanup
/lifecycle active
/assign
/priority important-longterm
/cc @fabriziopandini

**Comment by rosti** [comment]
@RA489 The first part of this is already done as part of the above mentioned PR. The second part (the actual removal) is going to be done after (at least) 3 minor releases due to deprecation policies.
Feel free to work on that when the time comes.

**Comment by neolit123** [comment]
should be removed in 1.17
added help-wanted please see OP for details:
https://github.com/kubernetes/kubeadm/issues/1356#issue-401399670

**Comment by yastij** [comment]
/assign
/priority important-soon

@neolit123 - I'll take a look

**Comment by neolit123** [comment]
@yastij thanks.

**Comment by neolit123** [comment]
sent PR here: https://github.com/kubernetes/kubernetes/pull/85044
