### ISSUE TITLE
CoreDNS Service - add "metrics" port - 9153

### ISSUE THREAD

**Issue by bitva77** [kubernetes/kubeadm#1360]
## Is this a BUG REPORT or FEATURE REQUEST?

Both? Either?

## Versions

**kubeadm version** (use `kubeadm version`):  1.13

**Environment**:
- **Kubernetes version** (use `kubectl version`):  1.13
- **Cloud provider or hardware configuration**:  bare-metal
- **OS** (e.g. from /etc/os-release):  Red Hat 7.6

## What happened?

The CoreDNS Pods have a metrics port (9153) defined but not the CoreDNS (kube-dns) service.

## What you expected to happen?

I expect to access port 9153 (via the name 'metrics') on the CoreDNS service (called kube-dns at the moment).

## Anything else we need to know?

This is close but appears to be about the label (which doesn't look like is used anymore): 
 https://github.com/kubernetes/kubeadm/issues/955

See this for details:  https://github.com/coreos/prometheus-operator/issues/2278#issuecomment-457144506

Thanks!

-Matt

**Comment by andrewsav-datacom** [comment]
Is it possible to find out which release version this is going to be in?

**Comment by neolit123** [comment]
@andrewrynhard 1.14

**Comment by andrewrynhard** [comment]
@andrewsav-datacom ^ :)

**Comment by andrewsav-datacom** [comment]
Thank you

**Comment by gurudattest** [comment]
Is this fix out  ? I have a cluster with Kubernetes version 1.14.1. The version of the coredns is 1.3.1 which is documented to have 9153 as metrics port exposed for the coredns service. But I don't see it.

**Comment by rajansandeep** [comment]
@gurudattest Yes, the fix was done in https://github.com/kubernetes/kubernetes/pull/73302

**Comment by gurudattest** [comment]
Thanks :) How can we check which exact version of kubernetes , this fix goes in.
I'm using "orchestratorVersion":"1.14.1", and I don't see it yet.

**Comment by rajansandeep** [comment]
If I'm not mistaken, this should have gone out in k8s 1.14.

**Comment by gurudattest** [comment]
I have 1.14.1, I don't understand why I don't see the metrics port on the coredns service. I use aks-engine to deploy my cluster. Any idea what might be going on ?

**Comment by gurudattest** [comment]
Here is what kubectl get svc kube-dns shows 


Name:              kube-dns
Namespace:         kube-system
Labels:            addonmanager.kubernetes.io/mode=Reconcile
                   k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=CoreDNS
Annotations:       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9153","prometheus.io/scrape":"true"},"labels":{"addonmanager.kuber...
                   prometheus.io/port=9153
                   prometheus.io/scrape=true
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP:                10.0.0.10
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:         10.240.0.15:53,10.240.0.16:53
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:         10.240.0.15:53,10.240.0.16:53
Session Affinity:  None
Events:            <none>

**Comment by gurudattest** [comment]
https://github.com/kubernetes/kubernetes/commit/d54716338af0b7a1c874c1898fa3e4c29160cabb

Here, it says
 master (#73302)  v1.16.0-alpha.0 … v1.14.0-alpha.2

Does that mean it goes to kuberenetes v.1.16 ? I cannot find it in kuberentes v1.14 changelogs as well https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md

**Comment by gurudattest** [comment]
@rajansandeep  Any idea what might be going on?

Kubectl version command on the master node shows
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
