### ISSUE TITLE
Improve contributor experience with a developer getting started guide

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1369]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Getting started developing kubeadm is a fairly painless process but there are a few gotchas that could make people's lives a lot easier.

I recently encountered trouble running the kubeadm tests and discovered these four gotchas that I had to untangle myself.

1. The tests must be run as root
2. The tests must be run through hack/make-rules/test-kubeadm-cmd.sh and not using the standard go testing tools
3. The tests will only pass on linux systems. We do not even mention in the test name that the failure is expected on non-linux systems.
4. The tests must be run on a system with a validated docker version. I don't really understand why we're testing the system that is running the test. A little explanation of this test would also be nice

## What you expected to happen?
I expected the tests to pass on my non linux system using the standard go tools since there was no documentation to the contrary.

## How to reproduce it (as minimally and precisely as possible)?
Run `KUBE_ROOT=$(pwd) go test ./cmd/kubeadm/...` from a fresh checkout.

**Comment by alejandrox1** [comment]
can I help out with this?

**Comment by chuckha** [comment]
@alejandrox1 yes! that would be great!

**Comment by neolit123** [comment]
> The tests must be run as root

i don't seem to need to run these tests are root on my Ubuntu 17.10.

> The tests must be run through hack/make-rules/test-kubeadm-cmd.sh and not using the standard go testing tools

this command only runs the integration tests in `cmd/kubeadm/test`
i still run our per-package unit tests using:
`go test ./cmd/kubeadm/app/...`

> The tests will only pass on linux systems. We do not even mention in the test name that the failure is expected on non-linux systems.

this is k8s wide problem, though.
i don't have OSX or i haven't tried windows, but maybe users already expect Linux only?

> The tests must be run on a system with a validated docker version. I don't really understand why we're testing the system that is running the test. A little explanation of this test would also be nice

we need to refactor the docker tests in:
k8s.io/kubernetes/cmd/kubeadm/app/util/system

such system checks are not unit tests!

**Comment by chuckha** [comment]
Even if it's a k8s-wide problem we can fix it for kubeadm and potentially propose a solution for the broader community.

I might have jumped the gun on needing root...but someone in chat was saying the tests tried to write to `/etc/`

**Comment by timothysc** [comment]
@fabriziopandini is currently working on the kinder guide.
