### ISSUE TITLE
kubeadm package for s390x

### ISSUE THREAD

**Issue by XiLongZheng** [kubernetes/kubeadm#137]
From 1.6.0 alpha 1, s390x binaries are included into kubernetes build, but kubeadm repository is not update to have s390x packages?

N: Skipping acquire of configured file 'main/binary-s390x/Packages' as repository 'http://apt.kubernetes.io kubernetes-xenial InRelease' doesn't support architecture 's390x'

**Comment by luxas** [comment]
Yes, I know s390x nor ppc64le isn't in the kubeadm repository, but it's in the works.
Binaries for it were released yesterday, right?

It will be provided with the next kubeadm release though, (and probably before that as well)

**Comment by XiLongZheng** [comment]
Thanks for your quick response! Looking forward to have kubeadm repo ready for s390x!
The tar ball for s390x and ppc64le were released yesterday. And kubeadm is already included into kubernetes-server-linux-s390x.tar.gz
