### ISSUE TITLE
Unable to create storage backend?

### ISSUE THREAD

**Issue by jianzzz** [kubernetes/kubeadm#1371]
**What happened**:
I am using kubeadm 1.13.0 to build my kubernetes service.
On my single master machine, kube-controller-manager、kube-scheduler is running by container way.
By kube-apiserver is failed:
Unable to create storage backend: config
...
err (asn1: structure error: tags don't match
 
**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.0

**Comment by chuckha** [comment]
@jianzzz Would you be able to provide a bit more information please? kubeadm config and more logs would help us know what else we need to assist in debugging.

/triage needs-information

**Comment by fabriziopandini** [comment]
/close 
Due to delay on answer/inactivity
Feel free to reopen if the problem persists & required info are available
