### ISSUE TITLE
Update CRI docs for Docker 18.09

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1372]
we had recent PRs to bump Docker in the kubeadm validation to 18.09:
https://github.com/kubernetes/kubernetes/pull/72823
https://github.com/kubernetes/kubernetes/pull/73457

this page needs updated instructions:
https://kubernetes.io/docs/setup/cri/

- in the sentence "On each of your machines, install Docker. Version 18.06 is recommended...". at the end of the sentence we need to add 18.09 to the known supported list.

we are still keeping 18.06 as the default.

good-first-issue

you need to clone the website repo and send a PR for this file against the master branch:
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/cri.md

**Comment by RA489** [comment]
@neolit123 I can have a look.
