### ISSUE TITLE
Decide on how to handle the extra arg we use in `kubeadm join`

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1375]
we treat the extra arg for `kubaedm join` as an endpoint of the API server (or LB) this node want's to join.

```
[lubomir] the extra unnamed arg in `kubeadm join <some-endpoint>` has opened a can of worms for us and the `join phases`:
[lubomir] [here is how it’s handled](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/join.go#L345-L352)
```

i known phase that needs this arg is "boostrap".

cc @ereslibre @fabriziopandini

**Comment by rosti** [comment]
Another phase is the pre-flight join phase. An API server endpoint is required to validate the `JoinConfiguration` if bootstrap tokens are used for discovery.
I do become more and more convinced, that we need to go down the `--api-endpoint=` road.

**Comment by neolit123** [comment]
> I do become more and more convinced, that we need to go down the --api-endpoint= road.

:100:

**Comment by chuckha** [comment]
I think making `kubeadm init phase` and `kubeadm join phase` could be improved by flipping the commands around. I think about it like `kubeadm init` is a command that runs a set of phases. If I want to see which phases `kubeadm init` runs, I would do something like `kubeadm phases init` or some other method of filtering ALL phases by which command(s) they are associated with. Same logic applies to `kubeadm join`.

I see this problem coming from breaking the single responsibility principle. Since both init and join are now responsible for *two* things, running their command *and* listing/running subphases, the UX is breaking down. There are many workarounds like @fabriziopandini has pointed out, but I think we could consider moving the phase subcommand out from init and join and into its own command, `kubeadm phases` with some mechanism for showing phases by how they are used. Tagging phases might make sense here since phases can be reused across various kubeadm sub commands. I could see some UX like `kubeadm phases` lists all phases while `kubeadm phases init` lists just phases tagged as phases that run during the init command.

**Comment by fabriziopandini** [comment]
@chuckha Even i see your point about the single responsibility principle, but such change is not easy to achieve

In the short term, what I'm trying to do is to ensure that 
- From a user perspective, `kubeadm init --help` will continue to show the init workflow/set of phases, while `kubeadm join --help` will show the join workflow/set of phases
- Even if technically possible, we are not considering to use the same phase in both workflows (e.g `certs` phase in init is different from `certs` phase in join; eventually we can choose to use a different name, but this has backside as well)
- #73725 introduced a cleaner separation in the codebase between init and join actions

This doesn't solve the arg problem, but hopefully avoids new problems

**Comment by neolit123** [comment]
@ereslibre @fabriziopandini 
i got this command line from a user today in a k/k issue thread:
```
kubeadm join 10.109.0.80:6443 --ignore-preflight-errors --token 3i2jzo.gicrm3jjbz0y64zg --discovery-token-ca-cert-hash sha256:5b20e87a257ea5551d8f5b3e1d502de099b485011d6b0e6062ad571fa97f5acb
```

this results in the following error:
```
Error: accepts at most 1 arg(s), received 2
```

the cause for the error is "interesting".

**Comment by ereslibre** [comment]
> Error: accepts at most 1 arg(s), received 2

Colour me confused, :question:

**Comment by bart0sh** [comment]
@ereslibre It's caused by missing parameter for --ignore-preflight-errors I guess.

**Comment by ereslibre** [comment]
Summing up that case (with current master):

1. `kubeadm join 172.28.128.5:6443 --ignore-preflight-errors --token <token> --discovery-token-ca-cert-hash <hash>`

    ```
    Error: accepts at most 1 arg(s), received 2
    ```

2. `kubeadm join 172.28.128.5:6443 --ignore-preflight-errorss --token <token> --discovery-token-ca-cert-hash <hash>`

    ```
    error: unknown flag: --ignore-preflight-errorss
    ```

3. `kubeadm join 172.28.128.5:6443 --ignore-preflight-errors= --token <token> --discovery-token-ca-cert-hash <hash>`
    * No error, when we should probably raise one asking for specific errors to be ignored or to provide `all`.

Case 1 seems like a bug on cobra? It's accepting a `StringSliceVar` with an empty list, and afterwards considering it as a second unnamed argument, whereas a completely unknown flag like case 2 is rejected properly. I am not a cobra expert but I could dig a bit into this.

**Comment by ereslibre** [comment]
In `kubeadm join 172.28.128.5:6443 --ignore-preflight-errors --token <token> --discovery-token-ca-cert-hash <hash>` (case 1) this is parsed as:

* Unnamed arg 1: `172.28.128.5:6443`
* `--ignore-preflight-errors` with argument `--token`
* Unnamed arg 2: `<token>`
* `--discovery-token-ca-cert-hash` with argument `<hash>`

:cry:

**Comment by neolit123** [comment]
had a chat with @ereslibre on slack. the above is a cobra issue and we can improve it upstream, but probably only if we get a lot of user reports.

**Comment by fabriziopandini** [comment]
I agree that cobra issue should be addressed upstream.

However, I think that it would be nice to have the possibility to set the Args validation function for leaf phases (if not set this should top-level command). 

More specifically, we would like to have leaf phases without discovery flags using `Args: cobra.NoArgs` (while the top-level command/all the other leaf phases will use `Args: cobra.MaximumNArgs(1)`)

@ereslibre, if I'm not wrong you already prototyped this. Would you like to take charge of this?

**Comment by ereslibre** [comment]
> @ereslibre, if I'm not wrong you already prototyped this. Would you like to take charge of this?

Yes, I can investigate during the next cycle on this.

/assign

**Comment by fabriziopandini** [comment]
/close
With https://github.com/kubernetes/kubernetes/pull/77400 we already did what is possible within the scope of kubeadm.
Potential conflict between args and subcommands are intrinsic in cobra design, but in our specific use case, one probability of conflict between <API server address> arg and the "phase" subcommand are low; in case of conflict, as a workaround, the user can add https:// prefix and/or :6443 suffix to disambiguate.

This can be eventually reconsidered when wg Component Standard has a proposal for handling flags Vs Config
