### ISSUE TITLE
cleanup: master -> control-plane

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1376]
we still have a lot of places in user visible output and in the code base where "master" is used.
we should be using "control-plane/Control Plane/controlPlane" in all possible locations.

guide:
- clone the kubernetes/kubernetes repository
- `cd` the folder `./cmd/kubeadm` and use `grep` to search for the word `master` / `Master` etc...
- replace occurrences of "master" with "control plane" and send PR.
- if there are way too many changes, send multiple PRs.

thanks.

**Comment by vanduc95** [comment]
@neolit123 I will work on it

**Comment by yagonobre** [comment]
Thanks @vanduc95 
/lifecycle active

**Comment by atoato88** [comment]
@vanduc95 It's OK for me.
Sorry for unclear action to this issue.
I should have said "I do this" at here.
If you create PR, can I review it, OK?

**Comment by vanduc95** [comment]
@atoato88 yes, thanks.

**Comment by RA489** [comment]
@vanduc95 are you working on this?

**Comment by vanduc95** [comment]
@RA489, I am on Lunar new year holiday, I will working on this after the end of holiday.

**Comment by yagonobre** [comment]
Hey @vanduc95 and @SataQiu I saw that all of yours are working in the same issue, can you coordinating to avoid duplicated work? In general a issue with the label `lifecycle/active` means that someone is currently working on it.

**Comment by SataQiu** [comment]
@yagonobre Thank you for your reminding. I'm sorry that I didn't notice the `lifecycle/active` label.
@vanduc95 As the task has been assigned to you, I will not work in this issue more. Please go on with your work. Good luck!

**Comment by neolit123** [comment]
this can be closed for now after the help and a number of PRs from @vanduc95 and @SataQiu 
thank you! :tada:
