### ISSUE TITLE
Kubeadm should install a default storage class

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubeadm#138]
This is part of proposal kubernetes/community#285.

We need kubeadm init --cloud-provider=XXX to look at addon manager files (shipped as kubernetes.tar.gz) and if cluster/addons/storage-class/XXX/default.yaml exists, then kubeadm should make sure this file is injected into Kubernetes (but it should not overwrite any existing objects, see #39561). Using addon manager would be the best.

**Comment by luxas** [comment]
Currently kubeadm is never really using a cloud provider so this isn't an issue we have to fix.
kubeadm will only support out-of-core cloud providers: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloud-provider-refactoring.md
