### ISSUE TITLE
Allow kubeadm to join by validating a provided CA certificate file instead of the CA hash

### ISSUE THREAD

**Issue by frittentheke** [kubernetes/kubeadm#1384]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm join
ca certificate
discovery-token-ca-cert-hash

## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

Currently ```kubeadm join``` only accept either the hash of the CA certificate using the ```discovery-token-ca-cert-hash``` parameter or one can simply skip this validation and simply trust the next best control plane that introduces itself.
There are environments (pre-generated PKI) where it is just as easy to transfer the whole CA certificate from the control plane also to the worker nodes as it is to create the required hash and have the nodes use that on their kubeadm join.

I propose to enable certificate pinning of kubeadm join not just by hash, but also by referencing the whole certificate.

## Versions

**kubeadm version** (use `kubeadm version`):
1.13.3

**Environment**:
- **Kubernetes version** (use `kubectl version`):
1.13.3

**Comment by timothysc** [comment]
I believe you can already do this today, but I need to verify. 

/assign @timothysc

**Comment by frittentheke** [comment]
@timothysc  am I reading your added "Next" tag correctly by assuming this does not yet work, but you consider adding this functionality?

**Comment by bart0sh** [comment]
This doesn't work yet as far as I can see from the code.
I'll take this.

/assign

**Comment by linxcat** [comment]
Updates? This seems nice to have and would remove the need to do ```sed -i "s/CACERTHASHHERE/sha256:$(openssl x509 -pubkey -in k8s-int.crt openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex)/g" kubeadm-config.yaml```

**Comment by rojkov** [comment]
Isn't the `--discovery-file` option of `kubeadm join` command supposed to do just that?

**Comment by arianvp** [comment]
Yes this is possible today.

You can do:

```
$ kubectl -n kube-public get cm cluster-info -o json | jq -r '.data.kubeconfig' > discovery-config.yaml
```

Then either:

1. copy over `discovery-config.yaml` to your worker nodes and `kubedm join --discovery-file ./discovery-config.yaml`
2. Or  put `discovery-config.yaml` on some webserver with HTTPs  and do `kubeadm join --discovery-file https://my-web-server.example/.well-known/k8s/discovery-config.yaml`

**Comment by linxcat** [comment]
The problem is when you're automating and creating your own CA (which good security dictates) and importing it. You aren't going to boot up servers on by one and export the CA from the master, they all need to know the hash at the same time. There's currently no alternative to sed'ing in the hash when you start your automation workflow.

**Comment by arianvp** [comment]
The `discovery-file` is just a CA cert wrapped in a YAML. One could generate it  out of band beforehand with just knowledge about the CA cert and the master IP. But I agree that feels a bit redundant as the master IP itself is already in the cert.

So it is possible. Just a bit cumbersome.   Would be nice if the discovery-file flag just took a cert as argument instead

**Comment by fabriziopandini** [comment]
/priority backlog
Considering there are at least two viable workaround (generate the CA hash, generate the kubeconfig file)

Some random thoughts about this:
I'm not sure that from an UX perspective it makes sense to allow the same flag to accept both a Kubeconfig file or a certificate file with the same flag; additionally, the Kubeconfig file carries two info (the server address and the CA file), while a certificate file only one, and this will force us to consider the kubeadm join "server-address" argument, that afaik today is not considered for the file discovery mechanism.

That's can lead to implement a third, separated discovery mechanism, with new additional knobs required both in kubeadm join and in the kubeadm config file. 

If this is the case, before proceeding, it is probably better to make a small showcase of how this will work and how the kubeadm join UX/documentation can be improved in order to help users to deal with different options

**Comment by frittentheke** [comment]
@arianvp kubeadm does expect a join token via the CLI ... still.

**Comment by arianvp** [comment]
@frittentheke Yes. there are two tokens at play here.  One is the `--tls-bootstrap-token` which we still need.    `--discovery-file` replaces just the `--discovery-token + --discovery-token-ca-cert-hash`

By default if you specify `--token` it sets `--tls-bootstrap-token` and `--discovery-token` to the same value.


As far as I understand `--tls-bootstrap-token` can be hardcoded apriori on both the master node and the worker nodes without any downsides to security.  So, to do a secure bootstrap without any intervention the following steps you should do:

0. apriori, generate your certs
1. Apriori, generate the `bootstrap-kubeconfig` and put it in the **worker** image
```bash
masterAddress="https://10.138.0.2:6443"
cacert=$(base64 < ca.crt)
cat > bootstrap-config.cfg << EOF
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: "$cacert"
    server: "$masterAddress"
  name: ""
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
EOF
```

2. Apriori generate a token (doesn't need any cluster to run)
```bash
$ kubeadm token generate
ckanuw.e1nh5mexdg8zu25s
```
3. In your master image start kubeadm as follows:
```
kubeadm init --token=ckanuw.e1nh5mexdg8zu25s
```

4. In your worker image, start kubeadm as follows:
```
kubeadm join --tls-bootstrap-token=ckanuw.e1nh5mexdg8zu25s --discovery-file=./bootstrap-config.cfg
```

**Comment by frittentheke** [comment]
@arianvp sorry I lost track of this issue and just not got to reply to you.
You are indeed correct, there are two mechanisms here at play - the bootrapping and the config-discovery.
It's currently documented that one can simply use "token" for both - see https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#options
And when doing so, it's possible to give kubeadm the hash via "--discovery-token-ca-cert-hash stringSlice" but not to simply point it to the CA file which is already on the machine. I still have to "create" the hash.
I get that I can use a discovery file and place the CA certificate in there ... but then I again have some command line parameters and some things in a to be created file. Just as complex as doing the hash on the CA file.

And then apart from referencing the discovery config with a CA file ... there is also the JoinConfiguration - which supposedly is another approach to providing a token + CA file to kubeadm? (see https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm#JoinConfiguration)

**Comment by astrieanna** [comment]
/remove-help
I believe that this issue does not fit the [definition of `help wanted`](https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md) because it does not have a clearly defined, agreed upon task.

**Comment by neolit123** [comment]
this has become a duplicate of https://github.com/kubernetes/kubeadm/issues/1687

for 1.16 you will be able to feed client cert/key and the --tls-boostrap-token flag is no longer needed.
e.g. `--file-discovery=somefile.conf` without extra flags works.
 
this PR also fixed related bugs:
https://github.com/kubernetes/kubernetes/pull/80675

a side note is that we added e2e tests for that.
