### ISSUE TITLE
kubeadm upgrade apply from 1.9.0 to 1.10.x hangs

### ISSUE THREAD

**Issue by Klmanjaro** [kubernetes/kubeadm#1387]
## Is this a request for help?
Yes.
I looked into various channels mentioned here and tried some of the workarounds.
But none have worked.

## Versions

**kubeadm version** (use `kubeadm version`):1.9.0
**Environment**:
- **Kubernetes version** (use `kubectl version`):1.9.0
- **Cloud provider or hardware configuration**:Linux OVM node
- **OS** (e.g. from /etc/os-release):OEL 7.5
- **Kernel** (e.g. `uname -a`):4.1.12-124.24.3.el7uek.x86_64 #
- **Others**:

## What happened?
kubeadm upgrade plan output:

[root@test-kubem01-den3 ~]# chmod a+rx /bin/kubeadm
[root@test-kubem01-den3 ~]# kubeadm upgrade plan
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade/plan] computing upgrade possibilities
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.9.0
[upgrade/versions] kubeadm version: v1.10.12
[upgrade/versions] Latest stable version: v1.13.3
[upgrade/versions] Latest version in the v1.9 series: v1.9.11
[upgrade/versions] WARNING: No recommended etcd for requested kubernetes version (v1.13.3)

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT      AVAILABLE
Kubelet     4 x v1.9.0   v1.9.11

Upgrade to the latest version in the v1.9 series:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.9.0    v1.9.11
Controller Manager   v1.9.0    v1.9.11
Scheduler            v1.9.0    v1.9.11
Kube Proxy           v1.9.0    v1.9.11
Kube DNS             1.14.8    1.14.8

You can now apply the upgrade by executing the following command:

	kubeadm upgrade apply v1.9.11

_____________________________________________________________________

External components that should be upgraded manually before you upgrade the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT   AVAILABLE
Etcd        3.1.12    N/A

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT      AVAILABLE
Kubelet     4 x v1.9.0   v1.13.3

Upgrade to the latest stable version:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.9.0    v1.13.3
Controller Manager   v1.9.0    v1.13.3
Scheduler            v1.9.0    v1.13.3
Kube Proxy           v1.9.0    v1.13.3
Kube DNS             1.14.8    1.14.8

You can now apply the upgrade by executing the following command:

	kubeadm upgrade apply v1.13.3

Note: Before you can perform this upgrade, you have to update kubeadm to v1.13.3.

---------------------------------------------------------------------------------------------
/tmp/kubeadm upgrade apply v1.10.4 shows:
......
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler]
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version “v1.10.4”...
Static pod: kube-apiserver-test-kubem02-den3 hash: 5f37c591f08f9d80f8024547afcdbcf6
Static pod: kube-controller-manager-test-kubem02-den3 hash: d04ee3a37266580c485b5587d420b020
Static pod: kube-scheduler-test-kubem02-den3 hash: 3b65954ad15570c54bda11f161993009
[upgrade/staticpods] Writing new Static Pod manifests to “/etc/kubernetes/tmp/kubeadm-upgraded-manifests619273361"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to “/etc/kubernetes/tmp/kubeadm-upgraded-manifests619273361/kube-apiserver.yaml”
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to “/etc/kubernetes/tmp/kubeadm-upgraded-manifests619273361/kube-controller-manager.yaml”
[controlplane] Wrote Static Pod manifest for component kube-scheduler to “/etc/kubernetes/tmp/kubeadm-upgraded-manifests619273361/kube-scheduler.yaml”
[certificates] Generated etcd/ca certificate and key.
[certificates] Generated apiserver-etcd-client certificate and key.
[upgrade/staticpods] Moved new manifest to “/etc/kubernetes/manifests/kube-apiserver.yaml” and backed up old manifest to “/etc/kubernetes/tmp/kubeadm-backup-manifests228116668/kube-apiserver.yaml”
[upgrade/staticpods] Waiting for the kubelet to restart the component
Static pod: kube-apiserver-test-kubem02-den3 hash: 5f37c591f08f9d80f8024547afcdbcf6
[upgrade/apply] FATAL: couldn’t upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: [timed out waiting for the condition]
## What you expected to happen?
Kubeadm upgrade apply should be successfully done and it should prompt me to upgrade kubectl  kubelet etc to 1.10.4 and restart cluster.

--------------------------------------------------------------------------------------------
## How to reproduce it (as minimally and precisely as possible)?
kubeadm upgrade from 1.9.0 on a k8s cluster.
If you are on GCP or AWS this should be v easy to reproduce.

## Anything else we need to know?
Please suggest any workarounds and I saw issues reported and no solution provided.
I could install kubeadm/kubectl/kubelet to 1.10.4 and restart kubelet directly: but that won't make kubeadm cluster to up to 1.10.4. right?
thank you.

**Comment by timothysc** [comment]
1.9.0 is no longer a supported version.
