### ISSUE TITLE
kubeadm join atomically cordon new node

### ISSUE THREAD

**Issue by michaelfig** [kubernetes/kubeadm#1392]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Please add a command-line option, say `--cordon` for `kubeadm join`, so that when the new node resource is created by kubeadm, the following is added:

```yaml
spec:
  taints:
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
  unschedulable: true
```

This would be desirable for adding a node to a cluster but guaranteeing nothing (except for daemonsets) is scheduled on the new node.  Then, later, when say change control approves using the new cluster, operations can run `kubectl uncordon NODE` to allow scheduling.

We can do something like this today, but there is a race condition between when we `kubeadm join` and when the new node can be cordoned.

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:33:30Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
On-premises cluster.

- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"


CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- **Kernel** (e.g. `uname -a`):
```
Linux Kube-LXC 4.15.18-10-pve 1 SMP PVE 4.15.18-32 (Sat, 19 Jan 2019 10:09:37 +0100) x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## Anything else we need to know?

I am willing to work on a PR, if this feature is desirable.

**Comment by fabriziopandini** [comment]
@michaelfig kubeadm already allows to set taints for the joining node using the configuration file
see `JoinConfiguration.NodeRegistrationOptions.Taints` https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#NodeRegistrationOptions

**Comment by michaelfig** [comment]
@fabriziopandini, Most of the options in the config file can be specified with command-line flags, too.  The disadvantage I have in using the config file is that I have to also add all the options that I formerly used as command-line options to the config file.  This would be a lot less onerous if the command-line overrode the config file.

Also, the node's `spec.unschedulable` attribute isn't modified with just the taints.  I'm not sure what that affects, but `kubectl cordon` seems to set it to `true`.

Thanks,
Michael.

**Comment by fabriziopandini** [comment]
@michaelfig flag config override is work in progress ATM. 

With regards to the unschedulable flag I'm not aware of a kubelet flag that kubeadm can use to make this happen (but kubelet has tons of flags and knobs, so might be I'm wrong here)

I'm also hesitant in embedding in kubeadm assumptions about an external process/organisation that doesn't apply to all the use cases (rif change control team approves)

@neolit123 @timothysc opinions?

**Comment by neolit123** [comment]
it might take a while before we support such a flag from the CLI, so better to move to the config if you need it in the near future @michaelfig .

but that won't solve the lack of `unschedulable: true`

> Also, the node's `spec.unschedulable` attribute isn't modified with just the taints. I'm not sure what that affects, but `kubectl cordon` seems to set it to `true`.

the kubectl command modifies the value in the Node object.
we don't have a knob for that from kubeadm and also i can't find a way to do it from the kubelet.

> This would be desirable for adding a node to a cluster but guaranteeing nothing (except for daemonsets) is scheduled on the new node. Then, later, when say change control approves using the new cluster, operations can run `kubectl uncordon NODE` to allow scheduling.

i can see uses cases for this. then again we have to decide if kubectl is the tool to use for this if this is out of scope for kubeadm.

**Comment by michaelfig** [comment]
Has there been any work on flag config overrides?  After some evaluation, it appears that would solve my use case (and that `unschedulable: true` can easily be added with `kubectl cordon NODE` soon after joining the cluster).

**Comment by neolit123** [comment]
there is a kubernetes working group called "component standard" that has the flag -> config overrides as a working item, but there are higher priorities for them ATM.

> The disadvantage I have in using the config file is that I have to also add all the options that I formerly used as command-line options to the config file

flags definitely have their benefits.
in case you re-consider, here is the kubeadm v1beta1 config documentation:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1

**Comment by timothysc** [comment]
Closing, b/c we are not going to modify for this specific behavior when there are ways to work around this problem
