### ISSUE TITLE
`kubeadm join` aborts during CA key rotation

### ISSUE THREAD

**Issue by anguslees** [kubernetes/kubeadm#1399]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.10.x apiserver
- **Cloud provider or hardware configuration**: baremetal
- **OS** (e.g. from /etc/os-release): CoreOS
- **Kernel** (e.g. `uname -a`): 4.19.18-coreos
- **Others**:

## What happened?

I am part-way through rotating my CA key.  This involves appending a second key to just about everywhere that needs it (in particular: `/etc/kubernetes/pki/ca.crt` now contains two keys).  I updated the cluster-info configmap similarly, but now `kubeadm join` loops continuously with:

[discovery] Trying to connect to API Server "kube.lan:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://kube.lan:6443"
[discovery] Failed to connect to API Server "kube.lan:6443": failed to parse cluster CA from the cluster-info configmap: trailing data after first PEM block
(repeat)

## What you expected to happen?

As with everywhere else in k8s, I expect `kubeadm` to use all the CA keys for TLS validation (ie: each connection must be validated against at least one key in this set).  In particular, the presence of a second key should not be an error.

## How to reproduce it (as minimally and precisely as possible)?

Append a second CA key to cluster-info configmap

**Comment by vaamarnath** [comment]
I am willing to fix this bug. Can I pick this one?

**Comment by yagonobre** [comment]
Yes @vaamarnath, but I suggest that you send a pr in the next cycle, to avoid a lot of rebase.
Thanks!
/lifecycle active

**Comment by vaamarnath** [comment]
I have a high level question about the fix. When several CA are part of the `certificate-authority-data`, doesn't it mean that `--discovery-token-ca-cert-hash` can accept any of the certificates'  SPKI?

@yagonobre Sure, I will start working on it and send the PR in the next cycle.

**Comment by anguslees** [comment]
> doesn't it mean that --discovery-token-ca-cert-hash can accept any of the certificates' SPKI?

Yes, I believe that is the desired behaviour.  The apiservers may present any of the listed CAs, and any one of them should be considered valid.

**Comment by rojkov** [comment]
@vaamarnath are you still working on this issue? I have a preliminary fix and wonder if I could submit it as a PR.
