### ISSUE TITLE
Implement easy upgrades with one command: `kubeadm upgrade`

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#14]
_From @danielschonfeld on October 28, 2016 10:49_

Wanted to make a wish.  Being a long time kubernetes user and having stitched clusters by hand, I am convinced `kubeadm` is the best thing that happened to kubernetes in terms of mass adoption. I think it would be nice if we could do version upgrades with `kubeadm`.  I imagine it wouldn't be too hard needing only to update the versions in the manifests and download a new version of kubelet?

Is there something else I'm missing? Could this become a reality?

_Copied from original issue: kubernetes/kubernetes#35779_

**Comment by ekozan** [comment]
any news of this one ? ✌️

**Comment by luxas** [comment]
@ekozan Yes, see: https://github.com/kubernetes/features/issues/296

**Comment by jamiehannaford** [comment]
I imagine when self-hosting becomes more stable (hopefully completed by v1.8), this will just be a matter of documentation. I'll add it to our v1.8 goals.

**Comment by luxas** [comment]
Yes, this is definitely a v1.8 goal

**Comment by luxas** [comment]
This is happening for v1.8, if you're interested, take a look at this google doc that I just updated with new info:
https://docs.google.com/document/d/1PRrC2tvB-p7sotIA5rnHy5WAOGdJJOIXPPv23hUFGrY/edit

**Comment by luxas** [comment]
The implementation PR is here: https://github.com/kubernetes/kubernetes/pull/48899

**Comment by luxas** [comment]
Not quite yet fixed, one of two PRs for this has merged
