### ISSUE TITLE
Alllow user to provide the certificate key on upload-certs

### ISSUE THREAD

**Issue by yagonobre** [kubernetes/kubeadm#1408]
- Add the `--certificate-key` flag to upload-certs phase, so user can provide the certificate
- Add the `--skip-certificate-key-print` flag to avoid printing the key

/area ha
/area ux
/kind feature
/priority important-soon
/lifecycle active

**Comment by RA489** [comment]
@yagonobre Can i help on this?

**Comment by yagonobre** [comment]
Hey @RA489, sorry but I already have a pr for it, I'm just waiting the base pr get merged.

**Comment by RA489** [comment]
@yagonobre Thanks for the info.

**Comment by rosti** [comment]
@yagonobre should we close this one?

**Comment by yagonobre** [comment]
@rosti not yet, I'll send the pr tomorrow.
