### ISSUE TITLE
kubeadm init fails with error marking master: timed out waiting for the condition

### ISSUE THREAD

**Issue by abhijeetab07** [kubernetes/kubeadm#1410]
## Is this a request for help?
yes

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
CentOS Linux release 7.4.1708 (Core)
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.13", GitCommit:"954ff68d59e9dc62fa8252ffa9023a90ff8a358c", GitTreeState:"clean", BuildDate:"2019-02-13T11:03:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
Bare-metal
- **OS** (e.g. from /etc/os-release):
CentOS Linux release 7.4.1708 (Core)
- **Kernel** (e.g. `uname -a`):
Linux vm4-xxx 3.10.0-693.21.1.el7.x86_64
- **Others**:

## What happened?
Kubeadm fails with error:
[markmaster] Will mark node vm4-xxx as master by adding a label and a taint
error marking master: timed out waiting for the condition

## What you expected to happen?
Kubernetes master initialized successfully!

## How to reproduce it (as minimally and precisely as possible)?
Kubeadm init --conifg=config.yaml

## Anything else we need to know?

Working on HA setup, there are 3 masters and etcd resides on the masters, where 1 of my master is initialized successfully, other 2 masters fail with the above error.
Below is my config.yaml file

apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 192.168.4.175
  controlPlaneEndpoint: 192.168.4.175
  nodeName: 192.168.4.175
etcd:
  endpoints:
  - https://192.168.4.173:2379
  - https://192.168.4.174:2379
  - https://192.168.4.175:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: 172.0.0.0/16
apiServerCertSANs:
- 192.168.4.173
- 192.168.4.174
- 192.168.4.175
apiServerExtraArgs:
  apiserver-count: "3"

Have tried the --node-name option, ip_forward, but still the same issue.
Although the first master was failing too, but it got successful once, rest it had been failing with the same error.

I am following the below link for High Availability:
https://v1-10.docs.kubernetes.io/docs/setup/independent/high-availability/

**Comment by yagonobre** [comment]
Hi @abhijeetab07, thanks for you report, but  1.10 version is no longer supported.
/close
