### ISSUE TITLE
List Contiv-VPP as a Pod Network Provider

### ISSUE THREAD

**Issue by rastislavszabo** [kubernetes/kubeadm#1411]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

If possible, please list [Contiv-VPP](https://github.com/contiv/vpp) network plugin as a Pod Network Provider option in:

https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

Contiv-VPP is a Kubernetes CNI plugin for Kubernetes that employs a programmable CNF vSwitch based on FD.io VPP offering feature-rich, high-performance cloud-native networking and services.

Link to setup instructions:
https://github.com/contiv/vpp/blob/master/docs/setup/MANUAL_INSTALL.md

**Comment by neolit123** [comment]
hello @rastislavszabo 

we don't have strict rules of what goes on the create-cluster-kubeadm page, but it was discussed at some point that verifying that the clusters which uses a CNI plugin is conformant is a nice-to-have:
https://github.com/cncf/k8s-conformance/blob/master/instructions.md#running

so providing sonobuoy logs is a good start.
also, are you a maintainer of VPP? we need someone to ping about user facing problems.

**Comment by rastislavszabo** [comment]
Hi @neolit123,

yes, I am the maintainer of Contiv-VPP. You can also note @lukasmacko and @jmedved as maintainers.

Will run the conformance tests and get back to you here soon.

**Comment by rastislavszabo** [comment]
Hi @neolit123,

the results of a conformance tests run on a k8s 1.12 cluster with Contiv-VPP:

```
Ran 187 of 1814 Specs in 5698.450 seconds
SUCCESS! -- 187 Passed | 0 Failed | 0 Pending | 1627 Skipped PASS

Ginkgo ran 1 suite in 1h34m59.187590493s
Test Suite Passed
```

Logs: [e2e.txt](https://github.com/kubernetes/kubeadm/files/2893657/e2e.txt)

[201902220919_sonobuoy_3551ab08-17d8-436e-b726-b697f59dba5a.tar.gz](https://github.com/kubernetes/kubeadm/files/2893658/201902220919_sonobuoy_3551ab08-17d8-436e-b726-b697f59dba5a.tar.gz)

**Comment by neolit123** [comment]
hello, the logs seem good.
thank you for running the conformance test on a Contiv-VPP based cluster.

are you willing to send a PR to kubernetes/website for this file, so that the CNI plugin is added?
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/independent/create-cluster-kubeadm.md

@kubernetes/sig-cluster-lifecycle

**Comment by rastislavszabo** [comment]
Hi @neolit123, I opened this PR: https://github.com/kubernetes/website/pull/12822

**Comment by yagonobre** [comment]
closed by https://github.com/kubernetes/website/pull/12822
/close
