### ISSUE TITLE
etcd-servers is not set correctly in static Pod manifest for kube-apiserver   

### ISSUE THREAD

**Issue by wubigo** [kubernetes/kubeadm#1414]
## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.3-dirty", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"dirty", BuildDate:"2019-02-16T11:21:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.3-dirty", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"dirty", BuildDate:"2019-02-16T11:21:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:

- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- **Kernel** (e.g. `uname -a`):
Linux bigo-vm1 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?

sudo cat kube-apiserver.yaml 
apiVersion: v1
kind: Pod
spec:
  containers:
  - command:
    - kube-apiserver
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379

## What you expected to happen?
sudo cat kube-apiserver.yaml 
apiVersion: v1
kind: Pod
spec:
  containers:
  - command:
    - kube-apiserver
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
***# etcd-servers should be https://192.168.1.9:2379***
    - --etcd-servers=https://192.168.1.9:2379

## How to reproduce it (as minimally and precisely as possible)?

git diff kubernetes/hack/lib/etcd.sh
-ETCD_HOST=${ETCD_HOST:-127.0.0.1}
+ETCD_HOST=${ETCD_HOST:-192.168.1.9}
./build/run.sh make
sudo cp  ./_output/dockerized/bin/linux/amd64/kubeadm  /usr/local/bin/
sudo kubeadm init phase control-plane apiserver
sudo kubeadm init phase etcd local

cat /etc/kubernetes/manifests/etcd.yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://192.168.1.9:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://192.168.1.9:2380
    - --initial-cluster=bigo-vm1=https://192.168.1.9:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://192.168.1.9:2379
    - --listen-peer-urls=https://192.168.1.9:2380

**Comment by neolit123** [comment]
hi,

> * etcd-servers should be https://192.168.1.9:2379

that's not exactly true. for a control plane node (using the default kubeadm etcd setup). etcd and the api-server will be on the same host.

why are you considering this a bug ?
> * --etcd-servers=https://127.0.0.1:2379

also this file is for testing purposes and kubeadm does not depend on it:
> /hack/lib/etcd.sh

**Comment by wubigo** [comment]
both  https://127.0.0.1:2379 and  https://192.168.1.9:2379 are valid etcd endpoint.
