### ISSUE TITLE
Add node affinity and tolerations  for coredns

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubeadm#1416]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

```sh
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:02:01Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):

```sh
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):

```sh
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- **Kernel** (e.g. `uname -a`):

```sh
Linux k8s-lixin-211 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- **Others**:

## What happened?

Use `kubeadm` create 3 master and 2 node cluster, when i kill coredns pod, coredns will running on the node.

## What you expected to happen?

I wants coredns only running on the master. 

## How to reproduce it (as minimally and precisely as possible)?

- use `kubeadm` create 3 master and 2 node cluster
- `kubectl delete pod coredns-xxx`

## Anything else we need to know?

In my case, i hope the coredns only running on the master. 

I see some issue, but i don't find the `tolerations` and `nodeAffinity` configuration, now i patch the coredns deployment when the cluster created. 

If someone know, hope can tell me. Thanks.

Could `kubeadm` add `tolerations` and `nodeAffinity` configuration in config file?

Ref:
https://github.com/kubernetes/kubeadm/issues/1091
https://github.com/kubernetes/kubeadm/issues/995

**Comment by xichengliudui** [comment]
do you need to submit pr? Or can you assign it to me?

**Comment by pytimer** [comment]
@xichengliudui I don't know whether `kubeadm` needs to add  this feature, so i wants confirm is it correct that this feature add in kubeadm?

**Comment by xichengliudui** [comment]
ok，thanks. @neolit123  @fabianofranz

**Comment by neolit123** [comment]
hello,

> I don't know whether `kubeadm` needs to add this feature, so i wants confirm is it correct that this feature add in kubeadm?

we don't support customizing addons such as DNS in such a way.
this is what is only supported currently:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L241-L245

you can modify that using kubectl, but please mind that we don't guarantee a clean upgrade path after such modifications.

https://github.com/kubernetes/kubeadm/issues/1091
was closed due to the problem with upgrades and allowing custom manifests.

thank you.

**Comment by pytimer** [comment]
@neolit123  Thanks. I know.
