### ISSUE TITLE
Tracking issue for reduce the number of calls that fetch configuration when reset

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubeadm#1417]
This is the tracking issue for the implementation of reduce the number of calls that fetch configuration from cluster when reset node.

Now `kubeadm reset` fetch the cluster configuration invoke the `FetchInitConfigurationFromCluster` function three times in reset.go, we hope it only fetch the configuration from the Kubernetes cluster once.

The origin issue: https://github.com/kubernetes/kubernetes/pull/74112#discussion_r257860113 .

**Comment by neolit123** [comment]
@pytimer if want to work on this issue please type the `/lifecycle active` command.
thanks!

**Comment by pytimer** [comment]
@neolit123 Thanks, i know.
