### ISSUE TITLE
Upgrading v1.10 to v1.11 omits kubeadm-flags.env, causing pods to end up in Docker bridge subnet

### ISSUE THREAD

**Issue by svenvanheugten** [kubernetes/kubeadm#1418]
## Versions

**kubeadm version** (use `kubeadm version`): v1.10.13 -> v1.11.7

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.10.13 -> v1.11.7
- **Cloud provider or hardware configuration**: Bare-metal
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Kernel** (e.g. `uname -a`): 4.15.0-45-generic
- **Others**:

## What happened?
When updating a Kubernetes cluster bootstrapped with `kubeadm` from v1.10.13 to v1.11.7 according to [the official instructions](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/), the new file `/var/lib/kubelet/kubeadm-flags.env` is only written on the control plane node, while setting up a new cluster causes it to be written on _all_ nodes (by the `init` and `join` commands).

Since a number of required `kubelet` options [have been moved to that file in v1.11](https://github.com/kubernetes/kubernetes/commit/b930d7f9153f1c74a8927de3f061a448c2a5a98c#diff-c8f893dbb92a4f1b64f87ec2f118a543), this causes `kubelet` to start with the wrong options on the worker nodes.

As some of the options (`--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"`) are required for the CNI plugin to function, this causes all pods on the worker nodes to be assigned to the Docker bridge subnet (172.17.2.0/24), rather than, in my particular case, the Weave subnet (10.32.0.0/12). As a direct consequence, you can not connect to these pods from pods running on a different node.

## What you expected to happen?
When following the official upgrade instructions, the file `/var/lib/kubelet/kubeadm-flags.env` should also be written on the worker nodes, such that, amongst other things, the CNI plugin works and pods can connect with eachother across different nodes.

## How to reproduce it (as minimally and precisely as possible)?
Spin up two fresh Ubuntu 18.04 machines.

### Installing Kubernetes v1.10.13
Follow https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/.

On the master:

```bash
# Install docker-ce
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
apt-get install install docker-ce=$(apt-cache madison docker-ce | grep 18.03 | head -1 | awk '{print $3}')

# Install kubelet, kubeadm and kubectl
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt install -y kubelet=1.10.13-00 kubeadm=1.10.13-00 kubectl=1.10.13-00

# Initialize the cluster and install the Weave network add-on
kubeadm init
export KUBECONFIG=/etc/kubernetes/admin.conf
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

On the secondary:

```bash
kubeadm join ... --token ... --discovery-token-ca-cert-hash ...
```

### Upgrading to Kubernetes v1.11.7
Follow https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/.

On the master:

```bash
export VERSION=1.11.7
export ARCH=amd64 # or: arm, arm64, ppc64le, s390x
curl -sSL https://dl.k8s.io/release/${VERSION}/bin/linux/${ARCH}/kubeadm > /usr/bin/kubeadm
chmod a+rx /usr/bin/kubeadm
kubeadm upgrade apply v1.11.7
apt-get install -y kubelet=1.11.7-00 kubectl=1.11.7-00 kubeadm=1.11.7-00
systemctl restart kubelet
```

On the secondary:

```bash
apt-get install -y kubelet=1.11.7-00 kubectl=1.11.7-00 kubeadm=1.11.7-00
kubeadm upgrade node config --kubelet-version $(kubelet --version | cut -d ' ' -f 2)
systemctl restart kubelet
```

### Verifying the problem
On the secondary, check that `/var/lib/kubelet/kubeadm-flags.env` does not exist.

Furthermore, you can spin up a deployment and see that is assigned to the Docker bridge network:

```bash
> kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node
> kubectl get pods -o wide
NAME                          READY     STATUS    RESTARTS   AGE       IP           NODE                         NOMINATED NODE
hello-node-7f5b6bd6b8-nqzhh   1/1       Running   1          1h        172.17.0.4   ubuntu-seconary              <none>
````

## Anything else we need to know?
By copying `/var/lib/kubelet/kubeadm-flags.env` from the master to the worker nodes and restarting `kubelet`, the problem is resolved.

When setting up a new cluster, rather than upgrading, this problem does not occur, since [running the `join` command on the worker nodes creates the file](https://github.com/kubernetes/kubeadm/issues/1015#issuecomment-425733688).

This issue is also mentioned in https://github.com/kubernetes/kubeadm/issues/1015#issuecomment-425732365, https://github.com/kubernetes/kubeadm/issues/1347#issuecomment-456739287 and in [this StackOverflow question](https://stackoverflow.com/questions/51183276/kubernetes-upgrade-failed-to-keep-pod-subnet).

**Comment by neolit123** [comment]
thank you for the report but 1.10 is outside of the support skew with 1.11 going out with the release of 1.14 late march.

> By copying `/var/lib/kubelet/kubeadm-flags.env` from the master to the worker nodes and restarting `kubelet`, the problem is resolved.

this is something that we've introduced by not handling the introduction of kubeadm-flags.env in 1.11.
the workaround is valid.

> When setting up a new cluster, rather than upgrading, this problem does not occur, since [running the `join` command on the worker nodes creates the file]

yes, this is true.

thanks.
/close

**Comment by svenvanheugten** [comment]
@neolit123 Fair enough. Are changes to the documentation still accepted (to add a workaround)? It might make it easier to upgrade past 1.11 to a supported version.

**Comment by neolit123** [comment]
most likely no, the docs website has branches for the old documentation, but these old branches are unmaintained at this point.
