### ISSUE TITLE
1.14: docs updates

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1422]
placeholder docs PRs for k/website should be sent until March 1st.
deadline for reviews is March 18th.

PRs should be sent against the k/website `dev-1.14` branch.

marking this as `help-wanted`.

---------

task: update kubeadm command line reference docs
assigned: @neolit123 
- [x] PR: https://github.com/kubernetes/website/pull/12911

info:
https://github.com/kubernetes/website/tree/master/content/en/docs/reference/setup-tools/kubeadm
- we have new join phase commands.
- need to look at what we kept or removed in other commands and flags.

---------

task: add 1.13 -> 1.14 upgrade docs (single control-plane + HA)
assigned: @neolit123
- [x] PR: https://github.com/kubernetes/website/pull/13189

info:
https://github.com/kubernetes/website/tree/master/content/en/docs/tasks/administer-cluster/kubeadm

add new page for 1.13->1.14 upgrade.
remove 1.10 -> 1.11 docs as well.

---------

task: updates to HA docs in 1.14
assigned: @neolit123 
- [x] PR: https://github.com/kubernetes/website/pull/13191

info:
https://github.com/kubernetes/website/tree/master/content/en/docs/setup/independent
`high-availability.md` etc..

we are adding `copy-certs` support.

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle 

i've added some tasks that need to be performed for updating the kubeadm 1.14 docs.

**Comment by RA489** [comment]
@neolit123 I can help with this effort.

**Comment by neolit123** [comment]
@RA489 @Klaven 
i've assigned you to a couple of items. see above and thank you very much.

let's post any questions in this thread instead of pining on private, so that we can give the change of more people to respond.
thank you !

**Comment by yagonobre** [comment]
I can take `task: add 1.13 -> 1.14 upgrade docs (HA)`

**Comment by neolit123** [comment]
thanks @yagonobre !

**Comment by Klaven** [comment]
@neolit123 HA placeholder PR https://github.com/kubernetes/website/pull/12892

**Comment by neolit123** [comment]
to modify existing branch of PR try this:
https://help.github.com/en/articles/changing-the-base-branch-of-a-pull-request

has to be `dev-1.14`.

**Comment by neolit123** [comment]
^ or if this asks you to merge 100 commits just create a new PR.

**Comment by yagonobre** [comment]
@neolit123 I created a new pr https://github.com/kubernetes/website/pull/12913

**Comment by RA489** [comment]
@neolit123 I created PR https://github.com/kubernetes/website/pull/12919

**Comment by neolit123** [comment]
thanks!

**Comment by Klaven** [comment]
@neolit123 I created a new PR! :D 
https://github.com/kubernetes/website/pull/12923

**Comment by jimangel** [comment]
@neolit123 I think this is ok to close.
