### ISSUE TITLE
Coredns failed to list *v1.namespace!!!!

### ISSUE THREAD

**Issue by yy55yyo** [kubernetes/kubeadm#1424]
## Versions

kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

## What happened?

All the domain <svc_name>.<namespace> like kubernetes.default can't be used.The logs in the Pod coredns display failed to list *v1.namespace.
This problem has been bothering me for two days. 

kubectl -n kube-system get pods

`NAME                                    READY   STATUS    RESTARTS   AGE
coredns-86c58d9df4-8js7n                1/1     Running   8          4d
coredns-86c58d9df4-wnhbd                1/1     Running   6          4d
etcd-longedev                           1/1     Running   8          4d
heapster-6d5b765c99-s4jx4               1/1     Running   2          2d23h
kube-apiserver-longedev                 1/1     Running   0          35m
kube-controller-manager-longedev        1/1     Running   9          4d
kube-flannel-ds-amd64-mztcj             1/1     Running   10         3d23h
kube-flannel-ds-amd64-qxmzf             1/1     Running   1          3d23h
kube-proxy-dbg9q                        1/1     Running   2          3d23h
kube-proxy-tdckg                        1/1     Running   7          4d
kube-scheduler-longedev                 1/1     Running   10         4d
kubernetes-dashboard-7f477fdfdb-fwtw6   1/1     Running   1          2d22h
monitoring-grafana-57cbc5c659-mfhbf     1/1     Running   1          2d23h
monitoring-influxdb-7f897d5cc8-4l98l    1/1     Running   1          2d23h`

kubectl exec -ti busybox -- nslookup kubernetes.default

`;; connection timed out; no servers could be reached

command terminated with exit code 1`

coredns logs

`E0226 02:56:22.830398       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:318: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0226 02:56:22.838831       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:313: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0226 02:56:22.842605       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
.............`

kubectl get nodes

`server02   Ready    <none>   3d23h   v1.13.3
server01      Ready    master   4d      v1.13.3`

kubectl get svc

`NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   4d`

kubectl -n kube-system describe pod/coredns-86c58d9df4-wnhbd

`Name:               coredns-86c58d9df4-wnhbd
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               server01/172.18.73.148
Start Time:         Fri, 22 Feb 2019 11:43:11 +0800
Labels:             k8s-app=kube-dns
                    pod-template-hash=86c58d9df4
Annotations:        <none>
Status:             Running
IP:                 10.244.0.26
Controlled By:      ReplicaSet/coredns-86c58d9df4
Containers:
  coredns:
    Container ID:  docker://9f370c0f048d013fce7adc367a853f1327225ccfe52b66f80f71d4b5ee11ca47
    Image:         k8s.gcr.io/coredns:1.2.6
    Image ID:      docker://sha256:f59dcacceff45b5474d1385cd5f500d0c019ed9ca50ed5b814ac0c5fcec8699e
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Running
      Started:      Tue, 26 Feb 2019 10:47:47 +0800
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 25 Feb 2019 18:09:27 +0800
      Finished:     Tue, 26 Feb 2019 10:47:22 +0800
    Ready:          True
    Restart Count:  6
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-rsls5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-rsls5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-rsls5
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>`

**Comment by neolit123** [comment]
please test with kube-dns
instructions here:
https://github.com/kubernetes/kubeadm/issues/1420#issuecomment-466784038

**Comment by chrisohaver** [comment]
The error says that the Kubernetes API is refusing connections from CoreDNS.  CoreDNS needs to connect to the Kubernetes API to get lists of namespaces, services, endpoints.

**Comment by yy55yyo** [comment]
> @yy55yyo, The error says that the Kubernetes API is refusing connections from CoreDNS. CoreDNS needs to connect to the Kubernetes API to get lists of namespaces, services, endpoints.

yes, I know that the Kubernetes API is refusing connections from CoreDNS.But I don't know why CoreDNS can't connect.

I saw that both the IP and port accessed by CoreDNS should be okay. All pods are working.

Is this the question of Kubernetes1.13.3?

**Comment by yy55yyo** [comment]
> please test with kube-dns
> instructions here:
> [#1420 (comment)](https://github.com/kubernetes/kubeadm/issues/1420#issuecomment-466784038)

I want to use CoreDNS to do this, and I want to know why this problem occurs when the configuration is known to be correct.

**Comment by chrisohaver** [comment]
Do the kubernetes api logs reveal anything?
Can you connect to the api from anther pod?
A connection refused error suggests that that the API isn't listening on that port. Or that the connection is being blocked by something in between (e.g. firewall).

A problem with RBAC or keys would result in a different error.

@neolit123 is suggesting trying kube-dns as a troubleshooting measure, not as a permanent replacement.

**Comment by yy55yyo** [comment]
@chrisohaver @neolit123 Thank you for your help.

I erased kubernetes and run it with Rancher is working now.

I will close it, although the reason was not found in the end.

**Comment by thomastvedt** [comment]
Just as a reference for the future me;
In my case it helped to just delete the two dns pods. When Kubernetes re-created them, dns was working again.

The error occurred when removing an app from "namespaceA", and then reinstalling it in "namespaceB".
