### ISSUE TITLE
kubeadm CoreDNS Restart

### ISSUE THREAD

**Issue by Apokleos** [kubernetes/kubeadm#1426]
asd

**Comment by Apokleos** [comment]
I installed a new k8s cluster with kubeadm-1.13.3, but CoreDNS will restart frequently and CrashBackOff. I have tried with some tips or sugguests, but none helps me. 
Problem Describe As below:
[root@localhost ~]# kubectl get po --all-namespaces
NAMESPACE     NAME                                            READY   STATUS                   RESTARTS       AGE
kube-system   coredns-7655b945bc-9h9m5                        0/1     CrashLoopBackOff   61          13m
kube-system   coredns-7655b945bc-jjvnw                        0/1     CrashLoopBackOff      61          13m
kube-system   etcd-localhost.localdomain                      1/1     Running            0          91m
kube-system   kube-apiserver-localhost.localdomain            1/1     Running            0          91m
kube-system   kube-controller-manager-localhost.localdomain   1/1     Running            0          91m
kube-system   kube-flannel-ds-amd64-rgvs4                     1/1     Running            0          89m
kube-system   kube-proxy-ftscw                                1/1     Running            0          92m
kube-system   kube-scheduler-localhost.localdomain            1/1     Running            0          91m
===========================
My VM Environment as below:
--------------------------------------------
1. SELINUX: disabled
2. [root@localhost ~]# uname -msr
Linux 3.10.0-862.11.6.el7.x86_64 x86_64
--------------------------
[root@localhost ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
----------------------------
[root@localhost ~]# runc -v
runc version 1.0.0-rc6
spec: 1.0.1-dev
[root@localhost ~]# crictl -v
crictl version v1.12.0
--------------------------------
[root@localhost ~]# cat /etc/crictl.yaml
runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
timeout: 10
debug: true
======================================
Some Logs and description of one CoreDNS pod as below:
[root@localhost ~]# kubectl logs coredns-7655b945bc-9h9m5 -n kube-system
.:53
2019-02-27T08:58:02.525Z [INFO] CoreDNS-1.2.6
2019-02-27T08:58:02.525Z [INFO] linux/amd64, go1.11.2, 756749c
CoreDNS-1.2.6
linux/amd64, go1.11.2, 756749c
 [INFO] plugin/reload: Running configuration MD5 = f65c4821c8a9b7b5eb30fa4fbc167769
[INFO] SIGTERM: Shutting down servers then terminating
-------------------------
[root@localhost ~]# kubectl describe po coredns-7655b945bc-9h9m5 -n kube-system
Name:               coredns-7655b945bc-9h9m5
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               localhost.localdomain/10.83.99.107
Start Time:         Wed, 27 Feb 2019 16:46:48 +0800
Labels:             k8s-app=kube-dns
                    pod-template-hash=7655b945bc
Annotations:        <none>
Status:             Running
IP:                 10.244.0.4
Controlled By:      ReplicaSet/coredns-7655b945bc
Containers:
  coredns:
    Container ID:  containerd://50e707317b1d6fc79f1bff17ccb79d5e48ed3a9dcce88c1062eb21587fff08c2
    Image:         k8s.gcr.io/coredns:1.2.6
    Image ID:      k8s.gcr.io/coredns@sha256:81936728011c0df9404cb70b95c17bbc8af922ec9a70d0561a5d01fefa6ffa51
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 27 Feb 2019 16:58:02 +0800
      Finished:     Wed, 27 Feb 2019 16:59:51 +0800
    Ready:          False
    Restart Count:  6
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-9pmq8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-9pmq8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-9pmq8
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                            Message
  ----     ------     ----                  ----                            -------
  Normal   Scheduled  15m                   default-scheduler               Successfully assigned kube-system/coredns-7655b945bc-9h9m5 to localhost.localdomain
  Normal   Pulled     11m (x3 over 15m)     kubelet, localhost.localdomain  Container image "k8s.gcr.io/coredns:1.2.6" already present on machine
  Normal   Killing    11m (x2 over 13m)     kubelet, localhost.localdomain  Killing container with id containerd://coredns:Container failed liveness probe.. Container will be killed and recreated.
  Normal   Created    11m (x3 over 15m)     kubelet, localhost.localdomain  Created container
  Normal   Started    11m (x3 over 15m)     kubelet, localhost.localdomain  Started container
  Warning  Unhealthy  4m53s (x26 over 14m)  kubelet, localhost.localdomain  Liveness probe failed: Get http://10.244.0.4:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    7s (x12 over 2m23s)   kubelet, localhost.localdomain  Back-off restarting failed container
================================================
Always, journalctl -xeu kubelet some error info will come up, infos as below:
[root@localhost ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─0-containerd.conf, 10-kubeadm.conf, proxy.conf
   Active: active (running) since Wed 2019-02-27 15:27:23 CST; 1h 44min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 21899 (kubelet)
    Tasks: 21
   Memory: 42.7M
   CGroup: /system.slice/kubelet.service
           └─21899 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kub...

Feb 27 17:08:22 localhost.localdomain kubelet[21899]: E0227 17:08:22.931371   21899 pod_workers.go:190] Error syncing pod 3836dc03...
Feb 27 17:08:29 localhost.localdomain kubelet[21899]: E0227 17:08:29.931373   21899 pod_workers.go:190] Error syncing pod 38428b59...
Feb 27 17:08:36 localhost.localdomain kubelet[21899]: E0227 17:08:36.931366   21899 pod_workers.go:190] Error syncing pod 3836dc03...
Feb 27 17:08:40 localhost.localdomain kubelet[21899]: E0227 17:08:40.931431   21899 pod_workers.go:190] Error syncing pod 38428b59...
Feb 27 17:08:51 localhost.localdomain kubelet[21899]: E0227 17:08:51.932443   21899 pod_workers.go:190] Error syncing pod 3836dc03...
Feb 27 17:08:51 localhost.localdomain kubelet[21899]: E0227 17:08:51.932654   21899 pod_workers.go:190] Error syncing pod 38428b59...
Feb 27 17:09:02 localhost.localdomain kubelet[21899]: E0227 17:09:02.931476   21899 pod_workers.go:190] Error syncing pod 3836dc03...
Feb 27 17:09:04 localhost.localdomain kubelet[21899]: E0227 17:09:04.931375   21899 pod_workers.go:190] Error syncing pod 38428b59...
Feb 27 17:09:16 localhost.localdomain kubelet[21899]: E0227 17:09:16.931386   21899 pod_workers.go:190] Error syncing pod 3836dc03...
Feb 27 17:09:17 localhost.localdomain kubelet[21899]: E0227 17:09:17.931731   21899 pod_workers.go:190] Error syncing pod 38428b59...
Hint: Some lines were ellipsized, use -l to show in full.
.....
Feb 27 17:09:02 localhost.localdomain kubelet[21899]: E0227 17:09:02.931476   21899 pod_workers.go:190] 
Error syncing pod 3836dc03-3a6c-11e9-af2a-fa163ed765a9 ("coredns-7655b945bc-9h9m5_kube-system(3836dc03-3a6c-11e9-af2a-fa163ed765a9)"), 
skipping: failed to "StartContainer" for "coredns" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=coredns pod=coredns-7655b945bc-9h9m5_kube-system(3836dc03-3a6c-11e9-af2a-fa163ed765a9)"
...
===================================================
I don't know  if it's a bug. I want to know why it produce,and how to resolve it.
Thank you!

**Comment by neolit123** [comment]
please note that we don't have strong e2e test signal from critctl.
so ideally you should try with docker as well.

**Comment by pytimer** [comment]
Need to check if kubelet configures http proxy. If the kubelet is configurated with http proxy, it needs to be removed. Because this will cause `coredns`  pod `livenessProbe`  check fail.

**Comment by Apokleos** [comment]
The root reason is kubelet proxy.  I have remove the /etc/systemd/system/kubelet.service.d/proxy.conf. after that, It will not restart and crash back off again and again.
I will close it.
THX.
