### ISSUE TITLE
unable to reset kubernet

### ISSUE THREAD

**Issue by Niladri579** [kubernetes/kubeadm#1427]
## Is this a request for help?
Yes, i am unable to reset kubernet by this command - sudo kubeadm reset
If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## Versions

**kubeadm version** (use `kubeadm version`):
v1. 13.3
**Environment**:
Amazon Linux
- **Cloud provider or hardware configuration**:
AWS

## What happened?

----The reset process does not reset or clean up iptables rules or IPVS tables.
If you wish to reset iptables, you must do so manually.
For example:
iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
to reset your system's IPVS tables.

**Comment by neolit123** [comment]
could you elaborate on the problem?
> Yes, i am unable to reset kubernet by this command - sudo kubeadm reset

**Comment by timothysc** [comment]
Closing due to timeout.
