### ISSUE TITLE
kubeadm init cannot be achieved via config.ymal in version 1.13.3

### ISSUE THREAD

**Issue by kASUNSithira** [kubernetes/kubeadm#1428]
I am tring to configure highly available cluster with 3 master nodes.I follow 
https://kazuhisya.netlify.com/2018/02/08/how-to-install-k8s-on-el7/
tutorial.

kubeadm version.

    kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

config file

    apiVersion: kubeadm.k8s.io/v1alpha3
    kind: MasterConfiguration
    api:
      advertiseAddress: 10.1.1.20
    etcd:
      endpoints:
      - https://${PEER_HOST1IP}:2379
      - https://${PEER_HOST2IP}:2379
      - https://${PEER_HOST3IP}:2379
      caFile: /etc/kubernetes/pki/etcd/ca.pem
      certFile: /etc/kubernetes/pki/etcd/client.pem
      keyFile: /etc/kubernetes/pki/etcd/client-key.pem
    networking:
      podSubnet: 10.244.0.0/16
    apiServerCertSANs:
    - 10.1.1.20
    apiServerExtraArgs:
      apiserver-count: "3"

when I try to run below command,kubeadm init fail with error.

command.

    kubeadm init --config=config.yaml

error.

    W0227 18:22:25.467977    6564 strict.go:47] unknown configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1alpha3", Kind:"MasterConfiguration"} for scheme definitions in "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:31" and "k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs/scheme.go:28"

I just need to init kubedeam by config.ymal file. I don't know what goes wron. Could not found proper answer.

Your help will be highly appreciated.

**Comment by pytimer** [comment]
@kASUNSithira You can reference this article [Creating Highly Available Clusters with kubeadm](https://kubernetes.io/docs/setup/independent/high-availability/).

**Comment by rosti** [comment]
Hi @kASUNSithira , please follow the official guide for setting up HA clusters with kubeadm.
Also, the config format you are using looks more like v1alpha2. It's not supported with kubeadm 1.13. The current one is v1beta1.

**Comment by dennohyegon** [comment]
Experiencing the same issue
