### ISSUE TITLE
Reduce number of parameters in init.go

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#1429]
Following the init phases work in 1.13, we are left with a couple of functions in `init.go`, that take an awful lot of parameters, but should only take a single struct pointer and use that.

1. `AddInitOtherFlags`:
- [Definition](https://github.com/kubernetes/kubernetes/blob/36787041cbb7a83531ffea765b045117f2fb301c/cmd/kubeadm/app/cmd/init.go#L228) from latest master:
```
func AddInitOtherFlags(
	flagSet *flag.FlagSet,
	cfgPath *string,
	skipTokenPrint, dryRun, uploadCerts *bool,
	ignorePreflightErrors *[]string,
) {
```

- The only [invocation](https://github.com/kubernetes/kubernetes/blob/36787041cbb7a83531ffea765b045117f2fb301c/cmd/kubeadm/app/cmd/init.go#L143):
```
AddInitOtherFlags(cmd.Flags(), &initOptions.cfgPath, &initOptions.skipTokenPrint, &initOptions.dryRun, &initOptions.uploadCerts, &initOptions.ignorePreflightErrors)
```

- New definition:
```
func AddInitOtherFlags(flagSet *flag.FlagSet, initOptions *initOptions)
```

- How it should be invoked:
```
AddInitOtherFlags(cmd.Flags(), initOptions)
```

2. `printJoinCommand`:
- [Definition](https://github.com/kubernetes/kubernetes/blob/36787041cbb7a83531ffea765b045117f2fb301c/cmd/kubeadm/app/cmd/init.go#L479) from latest master:
```
func printJoinCommand(out io.Writer, adminKubeConfigPath, token, key string, skipTokenPrint, uploadCerts bool) error
```

- The only [invocation](https://github.com/kubernetes/kubernetes/blob/36787041cbb7a83531ffea765b045117f2fb301c/cmd/kubeadm/app/cmd/init.go#L499):
```
printJoinCommand(out, adminKubeConfigPath, token, i.certificateKey, i.skipTokenPrint, i.uploadCerts)
```

- New definition:
```
func printJoinCommand(out io.Writer, adminKubeConfigPath, token string, i *initData) error
```

- How it should be invoked:
```
printJoinCommand(out, adminKubeConfigPath, token, i)
```

In both cases the structs are already put in place. What needs to be done is a simple refactor, that replaces the parameters in those structs with the structs themselves (as shown in the examples above).

Don't hesitate to ping me, I'll be happy to give you guidance and reviews.

/kind cleanup
/priority important-longterm
/good-first-issue

**Comment by pytimer** [comment]
@rosti  I wants to take it if no one works on it.

**Comment by neolit123** [comment]
/lifecycle active
thanks @pytimer

**Comment by fabriziopandini** [comment]
Thanks @rosti 
I'm pretty sure that changes similar to what you suggested could be applied to join as well (but in a separated PR)
