### ISSUE TITLE
remove TestInitConfigurationMarshallingFromFile commented test

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1431]
after enabling go 1.12, go-vet started complaining about our `inline` of ClusterConfiguration inside InitConfiguration. a quick fix was to do `ClusterConfiguration json:"-"` in our internal type and disable our marshall unit tests (TestInitConfigurationMarshallingFromFile).

https://github.com/kubernetes/kubernetes/pull/74797

we can remove this commented code now.

https://github.com/kubernetes/kubernetes/blob/ddc4ed03657d6c8c009a5d915265d00cadcb634c/cmd/kubeadm/app/util/config/initconfiguration_test.go#L127

**Comment by rosti** [comment]
We need to evaluate if all cases, that are tested by this test can be covered by the fuzzer. If that's the case we can kill it.

As an additional item, if we decide to re-enable and keep the test, it may be best to move the test data closer to code as this has caused some inconsistencies in the past (such as cases that claim to test v1beta1, but were really using v1alpha3).

**Comment by timothysc** [comment]
As of today we should probably just remove the commented test.

**Comment by nzoueidi** [comment]
I am interested to help with this issue! If anyone have any hints from that would be much appreciated.

**Comment by astrieanna** [comment]
@nzoueidi My interpretation of this issue is that [this commented out code](https://github.com/fabriziopandini/kubernetes/blob/9577cbfb9fd607d3698e1f2440f5875c85eca384/cmd/kubeadm/app/util/config/initconfiguration_test.go#L127-L200) needs to be removed.

**Comment by rosti** [comment]
This is no longer kind API Change
/remove-kind api-change

**Comment by neolit123** [comment]
good first issue guide:

- open a PR for kubernetes/kubernetes and remove this commented out test code:
https://github.com/kubernetes/kubernetes/blob/ddc4ed03657d6c8c009a5d915265d00cadcb634c/cmd/kubeadm/app/util/config/initconfiguration_test.go#L127
