### ISSUE TITLE
Cloud provider argument to k8s component

### ISSUE THREAD

**Issue by stgleb** [kubernetes/kubeadm#1434]
Is there any way to pass cloud-provider string to kubernetes components that requires it: api-server, controller-manager, kubelet?
Currently I see only the way how to pass it to kubelet using drop-in file.

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:35:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
- ubuntu 18.04 LTS
- Linux instance-1 4.15.0-1027-gcp #28-Ubuntu SMP Tue Jan 15 12:29:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yagonobre** [comment]
Hi @stgleb you can use the kubeadm config.
https://kubernetes.io/docs/setup/independent/control-plane-flags/

**Comment by neolit123** [comment]
also a k8s.io docs search for "kubeadm cloud provider" reveals this page:
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#kubeadm
