### ISSUE TITLE
 Regression: No longer able to generate custom kubeconfig

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubeadm#1435]
What happened:
After https://github.com/kubernetes/kubernetes/pull/74628, users lost the functionality to do the following that was present in v1.13.x:
kubeadm alpha kubeconfig user --client-name kubernetes-admin --org system:masters --apiserver-advertise-address 192.168.0.1 --apiserver-bind-port 6443

The ClusterRole was configurable and the output for the file was stdout (not hardcoded to admin.conf).

Kubespray currently leverages this functionality to create a separate kubeconfig that points to an external k8s api loadbalancer.

In the latest master, kubeadm now offers the ability to create only kubeconfigs for admin, controller-manager, kubelet, and scheduler.
What's missing are the following options:
--client-name
--org
ability to output to stdout (or to a custom file name)

**Comment by seh** [comment]
We also rely on this capability as part of our cluster administration. I know that it's possible to create and sign CSRs using other tools like _openssl_, with scripting on top to create corresponding kubeconfig files, but _kubecfg_ eliminates—or used to eliminate—the need to write such custom programs.

**Comment by neolit123** [comment]
@mattymo @seh what prevents you from using kubectl as a replacement for the removed `user` command.

**Comment by seh** [comment]
Are you assuming that we'd create the private key and certificate ourselves using something like _openssl_? As I mentioned above, I know that that's possible, and I've done it in the past, but it's much easier to do using _kubeadm_.

**Comment by fabriziopandini** [comment]
@seh @mattymo I'm really sorry this change impacted negatively on you

The change was discussed during kubeadm office hours, and I don't think there is room for discussing/reverting before code freeze (unless @neolit123 @timothysc have different opinions)

Ps. Technically this isn't a regression because Alfa feature can be removed at any time. Nevertheless I ttake the point that it is necessary to improve communication around deprecation, and I will raise the point the next office hours meeting

**Comment by neolit123** [comment]
@fabriziopandini 

> Technically this isn't a regression because Alfa feature can be removed at any time.

it's definitely not a regression.
anything under alpha can go at any point in time.

> the change was discussed during kubeadm office hours, and I don't think there is room for discussing/reverting before code freeze (unless @neolit123 @timothysc have different opinions)

true, i don't have strong opinions here. so 50/50 on my side.

@seh

> Are you assuming that we'd create the private key and certificate ourselves using something like openssl? As I mentioned above, I know that that's possible, and I've done it in the past, but it's much easier to do using kubeadm.

it's definitely easier to use kubeadm for this, i agree. but if we are completely removing this we should at least document the alternative.

**Comment by timothysc** [comment]
What is missing from `kubeadm init phase kubeconfig` ,  that you need?

**Comment by neolit123** [comment]
> What is missing from kubeadm init phase kubeconfig , that you need?

the `kubeconfig user` functionality was removed with `kubeadm alpha kubeconfig`

https://github.com/kubernetes/kubernetes/pull/74628/files#diff-12fe845fa0bf1f4f9d1a12c7aef7ba22L74
"Outputs a kubeconfig file for an additional user"

**Comment by timothysc** [comment]
Let me look at that code and see if we should port of if there is another way.

**Comment by timothysc** [comment]
So it's a little weird to add that back into init, because it's a utility vs a part of the phase.  

However, I'm not opposed to a revert for the utility if it's being used in the wild.

**Comment by timothysc** [comment]
OK, it looks like we pruned too deep and didn't provide the actual ask - https://github.com/kubernetes/kubeadm/issues/1381#issuecomment-461054337 .  

In other words, we did 1/2 the work needed.  I'll PR a revert and reopen the issue for next cycle.

**Comment by mattymo** [comment]
I'm not asking for a full revert, but the "user" functionality was really stellar for issuing certs. It was an easy button that's not critical for the project, but losing it hurts. Yes, it's entirely possible to issue new certs manually and construct them into a kubeconfig, but that effort seems overwhelming for an average user.

**Comment by timothysc** [comment]
We can address the final form in 1.15.
