### ISSUE TITLE
v1beta2 config

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#1439]
A proposal issue for the next kubeadm API version (currently proposed as v1beta2).

The actual details are in [this doc](https://docs.google.com/document/d/1XnP67oO1i9VcDIpw42IzptnJsc5OQM-HTf8cVcjCR2w/edit).

If you are a member of the Kubernetes SIG Cluster Lifecycle Google Group you should already have edit rights for it. Ping me if you have any problems accessing the doc.

----

track PRs here:
- [x] https://github.com/kubernetes/kubernetes/pull/76710
- [x] https://github.com/kubernetes/kubernetes/pull/77012
- [x] https://github.com/kubernetes/kubernetes/pull/77345
- [x] https://github.com/kubernetes/kubernetes/pull/77739

---

- k/enhancements issue: https://github.com/kubernetes/enhancements/issues/970
- KEP: https://github.com/kubernetes/enhancements/pull/969

/kind api-change
/assign

**Comment by yagonobre** [comment]
https://github.com/kubernetes/kubernetes/pull/74216

**Comment by fabriziopandini** [comment]
@rosti there are issues asking for allowing kube-apiserver customizations at node level 
https://github.com/kubernetes/kubeadm/issues/1348

**Comment by fabriziopandini** [comment]
There is also the Kube Router use case (skip kube-proxy in join/upgrade vs config)

**Comment by neolit123** [comment]
DNS local cache, but we didn't talk if we want it in the config yet.

**Comment by rosti** [comment]
@fabriziopandini we can make this more generic. We can probably add `skipPhases []string` to `InitConfiguration` and `JoinConfiguration`.
Seems like a nice generic solution to what you are describing here.

**Comment by fabriziopandini** [comment]
@rosti skipping phase from config can be an idea but I'm not sure it is the right solution for the problem above.
I think that "with/without kube-proxy" should be treated as a supported cluster variant, like CoreDNS/KubeDNS or internal/external etcd. That implies that the list of action should automatically adapt to this variant (instead of relying on the user picking up the right steps)

**Comment by fabriziopandini** [comment]
a request we have time to time: Improve support for Kubernetes on ARM (timeouts)

**Comment by neolit123** [comment]
> a request we have time to time: Improve support for Kubernetes on ARM (timeouts)

there is a workaround by using phases and patching the api-server manifest, but also the idea to make liveness probes configurable was not accepted by Robert and Tim, when we first started seeing the problem happening. ARM is OK in general, but the problem only happens on Raspberry PI. unless someone debugs the actual problems there i don't think we should take action.

**Comment by neolit123** [comment]
local etcd volumes were just requested here:
https://github.com/kubernetes/kubeadm/issues/1455

**Comment by fabriziopandini** [comment]
https://github.com/kubernetes/kubeadm/issues/1468

Etcd, controller-manager and scheduler configuration per node

**Comment by neolit123** [comment]
for reference the v1beta1 kep was here: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/0023-kubeadm-config-v1beta1.md

**Comment by ghouscht** [comment]
Are there any plans to change the hanling of `extraArgs` in the `ControlPlaneComponent` with v1beta2? The current implementation is backed by a `map[string]string` type and this leads to some problems we're currently facing. For example the api-server allows some arguments multiple times (`--service-account-key-file` and `--tls-sni-cert-key`). We can't handle this with the `extraArgs` type as it is a map which of course does not allow the same key twice and thus overrides previous declarations.

Example:

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: 1.14.2
apiServer:
  extraArgs:
    "tls-sni-cert-key": "/etc/kubernetes/pki/apiserver.crt,/etc/kubernetes/pki/apiserver.key"
    "tls-sni-cert-key": "/etc/kubernetes/pki/mycert.crt,/etc/kubernetes/pki/mykey.key" # overrides the previous declaration
```

(This is probably also a problem for other control plane components but I haven't checked it.)
Or is there another way to do this which I'm currently not aware of?

**Comment by neolit123** [comment]
@ghouscht 
unfortunately yes, using `map[string]string` does introduce this problem. we'd need something like Java's `MultiValuedHashMap` as a backend here.
kubeadm allows the component extra args from the CLI too, where this problem also minifests.

the workaround for now is to patch the e.g kube-apiserver.yaml manifest and the kubelet will restart it.

**Comment by neolit123** [comment]
@rosti i'm closing this as v1beta2 was added successfully.
@ghouscht please file a separate ticket that outlines the problem in https://github.com/kubernetes/kubeadm/issues/1439#issuecomment-495502283
if you wish.
