### ISSUE TITLE
Create e2e tests for HA secret transfer

### ISSUE THREAD

**Issue by ereslibre** [kubernetes/kubeadm#1440]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## What happened?

In order to get HA to GA we need e2e tests that test the secret transfer.

Part of the https://github.com/kubernetes/kubeadm/issues/1373 umbrella issue.

**Comment by neolit123** [comment]
we have too many "test tickets".
this is already tracked with these two items here https://github.com/kubernetes/kubeadm/issues/1373

>     - [ ] Periodic job for multi control-plane without upload certs (@neolit123)
>     - [ ] Periodic job for multi control-plane with upload certs (on hold/@neolit123)
