### ISSUE TITLE
Kubeadm init --config=file.yaml is failing with Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady

### ISSUE THREAD

**Issue by Ashraf-Hassan** [kubernetes/kubeadm#1444]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm HA 
kubeadm Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
v1.13.4

**Environment**:
- **Kubernetes version** (use `kubectl version`):
v1.13.4

- **Cloud provider or hardware configuration**:
Virtual Machines

- **OS** (e.g. from /etc/os-release):
CentOS 7

- **Kernel** (e.g. `uname -a`):
Linux master01 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:
HA Proxy on Centos
haproxy-1.5.18-8.el7.x86_64

## What happened?
I am trying to deploy the HA K8c clutser using 3 masters (master01, master02, and master03) and one LB (lb01).
The steps I used to create each of the masters are as follow:
    1-   Update packages
           yum update -y
    2- Create Kubernetes repo:
         /etc/yum.repos.d/kubernetes.repo
    3-  Disable selinux in: /etc/selinux/config
    4- Add the following in  /etc/sysctl.d/k8s.conf:
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
   5-  Install docker
   6- Disable and mask firewalld
   7- Install kubelet, kubeadm, and kubectl using the command:
       `  yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes`
    8- Adjust the docker storage
    9- Adding internet proxy in the following, then enabling docker, then rebooting:
       /etc/systemd/system/docker.service.d/http-proxy.conf
    I start following the following link:
          https://kubernetes.io/docs/setup/independent/high-availability/
     so:
     10: I created the following kubeadm-config.yaml:
           apiVersion: kubeadm.k8s.io/v1beta1

```
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
    certSANs:
    - "lb01.example.com"
controlPlaneEndpoint: "lb01.example.com:6443"
networking:
   dnsDomain: cluster.local
   podSubnet: "192.168.0.0/16"
   serviceSubnet: 10.96.0.0/12
```

  11- Then I executed the command:
           kubedam init --config=kubeadm-config.yaml
    

## What you expected to happen?
I was expecting that the command will execute successfully, and I will get:
You can now join any number of machines by running the following on each node
as root:

  kubeadm join lb01.example.com:6443 --token   xxxxx--discovery-token-ca-cert-hash xxxxx

But instead I got the following:
```
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster


```
Although I can see the kubelet daemon is running and the ha-proxy is reporting it green, and the master journal I am getting these errors:
```
Mar 10 01:59:27 master01.example.com kubelet[18378]: I0310 01:59:27.808536   18378 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Mar 10 01:59:27 master01.example.com kubelet[18378]: I0310 01:59:27.811455   18378 kubelet_node_status.go:72] Attempting to register node master01.example.com
Mar 10 01:59:27 master01.example.com kubelet[18378]: E0310 01:59:27.881355   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:27 master01.example.com kubelet[18378]: E0310 01:59:27.981649   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.081843   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.182140   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.282327   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.382537   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.482785   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.582988   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.683163   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.783347   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: E0310 01:59:28.883541   18378 kubelet.go:2266] node "master01.example.com" not found
Mar 10 01:59:28 master01.example.com kubelet[18378]: I0310 01:59:28.975535   18378 kubelet_node_status.go:75] Successfully registered node master01.example.com
Mar 10 01:59:28 master01.example.com kubelet[18378]: I0310 01:59:28.981759   18378 reconciler.go:154] Reconciler: start to sync state
Mar 10 01:59:31 master01.example.com kubelet[18378]: W0310 01:59:31.323437   18378 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 10 01:59:31 master01.example.com kubelet[18378]: E0310 01:59:31.323670   18378 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not
Mar 10 01:59:31 master01.example.com kubelet[18378]: E0310 01:59:31.334851   18378 summary_sys_containers.go:47] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/sy
Mar 10 01:59:36 master01.example.com kubelet[18378]: W0310 01:59:36.324903   18378 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 10 01:59:36 master01.example.com kubelet[18378]: E0310 01:59:36.325111   18378 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not
Mar 10 01:59:41 master01.example.com kubelet[18378]: W0310 01:59:41.326263   18378 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 10 01:59:41 master01.example.com kubelet[18378]: E0310 01:59:41.326472   18378 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not
Mar 10 01:59:41 master01.example.com kubelet[18378]: E0310 01:59:41.348257   18378 summary_sys_containers.go:47] Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/sy
Mar 10 01:59:46 master01.example.com kubelet[18378]: W0310 01:59:46.327867   18378 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d


```
My understanding that these errors will only appear if you are missing the networking snippet in the kubeadm config yaml whhich is not my case.

## How to reproduce it (as minimally and precisely as possible)?

By following all the previous steps

## Anything else we need to know?
No

**Comment by pytimer** [comment]
I see an issue about this, but i don't know is it work for you? 
You can see it https://github.com/kubernetes/kubernetes/issues/56850#issuecomment-372933448.

**Comment by Ashraf-Hassan** [comment]
No it did not fix the issue, I tested all the previous versions for kubeadm up to 13.1.1 and they are all having this issue!

**Comment by rosti** [comment]
@Ashraf-Hassan looks like the cgroup driver is not setup properly. Did you took a note of [this](https://kubernetes.io/docs/setup/cri/#cgroup-drivers)?
Also, make sure you checkout the Docker installation instructions for CentOS/RHEL in the paragraph below.

**Comment by neolit123** [comment]
> looks like the cgroup driver is not setup properly

it should be set automatically, regardless.
this is the first report of the cgroup driver detection failing in a while.

**Comment by Ashraf-Hassan** [comment]
> > looks like the cgroup driver is not setup properly
> 
> it should be set automatically, regardless.
> this is the first report of the cgroup driver detection failing in a while.

I have reinstalled the docker as per the https://kubernetes.io/docs/setup/cri/#cgroup-drivers, but if the cgroup should be set automatically, how can I solve my my problem when I user kubeadm?
By the way when I use kubeadm init --pod-network-cidr=192,168.0.0/16 it works perfectly, but it installs it on a single master, when I use kubadm init --config=kubeadm-config.yaml it fails with this error with the following error and I do not know the reason for that although I have added networking snippet in the config file:
```
Mar 10 01:59:36 master01.example.com kubelet[18378]: W0310 01:59:36.324903   18378 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 10 01:59:36 master01.example.com kubelet[18378]: E0310 01:59:36.325111   18378 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not 
```

**Comment by timothysc** [comment]
Your CNI is not installed and configured properly.

**Comment by pytimer** [comment]
@timothysc I think this problem not related to CNI, because it occur at the `kubeadm init`.

I think maybe this cause by `Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats` , but i am not sure. 

Somebody setting kubelet systemd service, like below:
```sh
[Service]
CPUAccounting=true
MemoryAccounting=true
```
I'm not sure if it is works well and fix this issue.

**Comment by neolit123** [comment]
@Ashraf-Hassan 

you might see his once or twice, but i don't think you can consider it a fatal error, right away..

> Mar 10 01:59:36 master01.example.com kubelet[18378]: W0310 01:59:36.324903   18378 cni.go:203] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 10 01:59:36 master01.example.com kubelet[18378]: E0310 01:59:36.325111   18378 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not 

this is a fatal error:

> Mar 10 22:37:05 master01.example.com kubelet[15719]: F0310 22:37:05.991673   15719 server.go:261] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker

> I have reinstalled the docker as per the https://kubernetes.io/docs/setup/cri/#cgroup-drivers, but if the cgroup should be set automatically, how can I solve my my problem when I user kubeadm?

^ do you still see the above message `"cgroupfs" is different from docker` message?

1) what is the output of `docker info` in terms of `Cgroup Driver: ....`?
2) after you start `kubeadm init` what do you see in this file `/var/lib/kubelet/kubeadm-flags.env`?

> By the way when I use kubeadm init --pod-network-cidr=192,168.0.0/16 it works perfectly, but it installs it on a single master

>    dnsDomain: cluster.local
   podSubnet: "192.168.0.0/16"
   serviceSubnet: 10.96.0.0/12

this indicates problems with your DNS.
is `10.96.0.0/12` a valid CIDR?

**Comment by Ashraf-Hassan** [comment]
The problem is solved by:
1- Using the docker-ce release!
2- And adding:
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
And then adding  $KUBELET_CGROUP_ARGS in ExecStart
in The file  /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
and make systemd daemon-reload.
However as I understood that this will be depricated is that correct?

**Comment by pytimer** [comment]
@Ashraf-Hassan I think you can setting kubelet configurations when init using `kubeadm-config.yaml`, like below:

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
```

Or you can see https://kubernetes.io/docs/setup/independent/kubelet-integration/#kubelet-configuration-patterns this article.

Hope it can help you.

**Comment by Ashraf-Hassan** [comment]
Yes thank you that helped.
