### ISSUE TITLE
edit release notes draft for 1.14

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1449]
release notes draft for 1.14 is here
https://docs.google.com/document/d/1PAbK3D6-GorRf_Fi1U_q-Vvt9wM4MMh-qQfiq-dtOTE/edit

tasks:
- edit/move PR release notes where/if needed.
- add SIG theme; kubeadm mostly, as other projects are k8s release unbound.

/assign @timothysc @fabriziopandini @neolit123 
/kind documentation
/priority important-soon

**Comment by neolit123** [comment]
@fabriziopandini @timothysc 
@kubernetes/sig-cluster-lifecycle-pr-reviews 

WIP theme doc is here:
https://docs.google.com/document/d/1kGHktVfjMFoZCzou--L26-zXrfk8moE9nFlKgzKdZJE/edit?usp=sharing

please help edit the most notable items.

**Comment by neolit123** [comment]
@timothysc i did a first pass on release notes and our notes seem good. some are under "new features", some are under SIG CL.

i cannot find a section with SIG themes?
either way our themes are done here (from my POV):
https://docs.google.com/document/d/1kGHktVfjMFoZCzou--L26-zXrfk8moE9nFlKgzKdZJE/edit?usp=sharing

**Comment by neolit123** [comment]
> Dave Strebel
> Sig Major Themes has been removed for this release. We are using "What's New" "Action Required" and "Known Issues" categories for notable changes.

SIG themes have been removed.
i guess we need to format our new features in "what's new".

**Comment by neolit123** [comment]
updated:
https://docs.google.com/document/d/1kGHktVfjMFoZCzou--L26-zXrfk8moE9nFlKgzKdZJE/edit

**Comment by timothysc** [comment]
reviewed and gave feedback.  
Thx for doing this @neolit123 . 

lgtm

**Comment by neolit123** [comment]
we have finished this task.
