### ISSUE TITLE
Integrate kubeadm and kubefed

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubeadm#145]
has this been implemented yet? or have any plan to do this?

**Comment by luxas** [comment]
Just use kubefed on the kubeadm-bootstrapped cluster I think :)

**Comment by bruceauyeung** [comment]
@luxas  a kubeadm-bootstrapped cluster doesn't have current context on the master, is this a bug or not implemented yet ?

> -bash-4.2# kubectl get nodes
NAME                        STATUS         AGE
vmwarecgsl5-2.localdomain   Ready          22d
vmwarecgsl5.localdomain     Ready,master   22d
-bash-4.2# kubectl config get-contexts
CURRENT   NAME      CLUSTER   AUTHINFO   NAMESPACE
-bash-4.2#

**Comment by luxas** [comment]
@bruceauyeung You should use `--kubeconfig /etc/kubernetes/admin.conf`, that's the kubeconfig file kubeadm generated. Of course you can copy it the default kubeconfig in `~/.kube` if you want as well

**Comment by luxas** [comment]
@kubernetes/sig-federation-feature-requests Is it possible to run kubefed on bare metal yet?
Can we do something to make sure it works with kubeadm clusters easily?

**Comment by pipejakob** [comment]
@bruceauyeung Can you describe what breaks when you try to use kubefed on a kubeadm-initialized cluster (other than the context issue, which I believe should be solved by @luxas's suggestion to use the correct kubeconfig file)? Or were you hoping that kubeadm's CLI would provide additional options to automatically set up Federation?

**Comment by luxas** [comment]
@kubernetes/sig-federation-feature-requests PTAL
Do we have a story for easy federation on bare metal yet?
In that case, can we have tests so kubeadm clusters are easily kubefed-able afterwards?

**Comment by madhusudancs** [comment]
@luxas

> Do we have a story for easy federation on bare metal yet?

There is. `kubefed` should work on bare-metal clusters.

> In that case, can we have tests so kubeadm clusters are easily kubefed-able afterwards?

Please file an issue for it. I will be happy to help/mentor anyone who is willing to set this up.

**Comment by jamiehannaford** [comment]
@luxas Should we keep this open?

**Comment by luxas** [comment]
Ok, I think we can close this. BTW, @shashidharatd is working on spinning up federated clusters on top of kubeadm clusters.
