### ISSUE TITLE
move the self-hosting documentation from the kubeadm init authored page

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1451]
move references of self-hosting away from the kubeadm init authored page:
https://github.com/kubernetes/website/blob/master/content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md#self-hosting-the-kubernetes-control-plane-self-hosting

destination is possibly a new page.

**Comment by neolit123** [comment]
/assign @Klaven 
/lifecycle active
@Klaven said that he can help with this page.

**Comment by Klaven** [comment]
@neolit123 this was merged and can be closed
