### ISSUE TITLE
Node can't join to cluster

### ISSUE THREAD

**Issue by ssoor** [kubernetes/kubeadm#1452]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

 BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- **OS** (e.g. from /etc/os-release):
CentOS Linux release 7.5.1804 (Core)
- **Kernel** (e.g. `uname -a`):
Linux 3.10.0-862.14.4.el7.x86_64

## What happened?
[discovery] Failed to connect to API Server "172.13.0.52:6443": token id "bs0nxj" is invalid for this cluster or it has expired. Use "kubeadm token create" on the master node to creating a new valid token

## What you expected to happen?
A node joins to a cluster.

## How to reproduce it (as minimally and precisely as possible)?
master1:
kubeadm init --apiserver-advertise-address=<master1_addr> --pod-network-cidr=<pod_sub>

master2:
kubeadm token create 
kubeadm join <master1_addr>:6443 --token 75le87.v8jmvyeegi4nm8hd --discovery-token-unsafe-skip-ca-verification --experimental-control-plane

master3:
kubeadm token create 
kubeadm join <master1_addr>:6443 --token 75le87.v8jmvyeegi4nm8hd --discovery-token-unsafe-skip-ca-verification --experimental-control-plane

kubectl delete node master1
kubeadm token create 

master1:
hostnamectl set-hostname master4
kubeadm reset
kubeadm join <master2_addr>:6443 -token bs0nxj.wf0dh0jp1cms40e0 --discovery-token-unsafe-skip-ca-verification --experimental-control-plane

## Anything else we need to know?

master2:
[root@master2 ~]# kubeadm token list
TOKEN                     TTL         EXPIRES                     USAGES                   DESCRIPTION   EXTRA GROUPS
75le87.v8jmvyeegi4nm8hd   invalid   2019-03-15T11:32:33+08:00   authentication,signing   <none>        system:bootstrappers:kubeadm:default-node-token
bs0nxj.wf0dh0jp1cms40e0   23h         2019-03-17T15:13:42+08:00   authentication,signing   <none>        system:bootstrappers:kubeadm:default-node-token

**Comment by neolit123** [comment]
you need to `kubeadm init` on the first control-plane node.
then you `kubeadm join` the rest of your control-plane nodes with the same token that `kubeadm init` printed for you.

but you also need to copy certificates from the first node.
please follow this guide: https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by timothysc** [comment]
Closing due to workaround and lack of response.
