### ISSUE TITLE
Init help suggests there are feature gates but lists none

### ISSUE THREAD

**Issue by carlpett** [kubernetes/kubeadm#1456]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version**: `kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:35:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

## What happened?
`kubeadm init --help` has this section:
```
[...]
      --feature-gates string                 A set of key=value pairs that describe feature gates for various features. Options are:

  -h, --help                                 help for init
[...]
```
That is, it suggests there are feature gates, but then presents an empty list.

## What you expected to happen?
Looking at [the source](https://github.com/kubernetes/kubernetes/blob/8142ab59046e4535684188968dd135db443ce430/cmd/kubeadm/app/features/features.go#L41), it appears there actually aren't any in the current version. 

The flag should either be omitted completely, or (probably better) explain that there aren't any valid values. I should not have to check the source to understand why there are no options presented.

## How to reproduce it (as minimally and precisely as possible)?
`kubeadm init --help`

**Comment by neolit123** [comment]
i don't think it's a big problem to have the flag, but possibly add a note it's description that currently no feature gates are supported.  i don't think we want to remove it, because at some point we might want to add gates, even though this is not one of my preferred feature/toggle mechanics.

@kubernetes/sig-cluster-lifecycle

**Comment by Bubblemelon** [comment]
Hello :smile: I would like to attempt this fix. It would be a good chance to try out [kind](https://github.com/kubernetes-sigs/kind) at the same time.

**Comment by carlpett** [comment]
@neolit123 Completely agree that it shouldn't be removed, what I meant was it could potentially be omitted from the help output. But that also seems confusing UX-wise.
So just putting some text there about "no gates are available in this release" would be good enough.

**Comment by fabriziopandini** [comment]
@Bubblemelon thanks for volunteering!
Ideally, what we need is that the machinery that generates the help for `feature-gates`handle the case  "no gates are available in this release" 

/lifecycle active
