### ISSUE TITLE
Generate a separate cert/key pair for the ServiceAccount signing

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#146]
Right now, we're using the apiserver's cert/key pair, but as pointed out in https://github.com/kubernetes/kubernetes/pull/41098#issuecomment-278312089, this won't work in a multi-master scenario where different apiservers have different certs and there is no consensus how to encode/decode the serviceaccount secrets cluster-wide.

This should be fixed by generating `sa.{crt,key}` in `/etc/kubernetes/pki` and passing those files to the apiserver and controller-manager.

cc @andrewrynhard @pires @dmmcquay @mikedanese @roberthbailey @errordeveloper @alexbrand

**Comment by andrewrynhard** [comment]
@luxas is this something you are working on? I can take a shot at it if you'd like.

**Comment by luxas** [comment]
@andrewrynhard That would be awesome :smile:! That was why I mentioned you; you said you wanted to help with something, and I think this is a perfect task at the moment ;)!

**Comment by andrewrynhard** [comment]
@luxas great. I will get to work then ;)

**Comment by pires** [comment]
For as long as the CA is the same for all TLS stuff in the cluster, I see no reason why not to do this.

**Comment by andrewrynhard** [comment]
@pires I like the idea. From an operations point of view this would simplify things. If any master could seed required information masters joining the cluster, then I wouldn't have to worry about getting that data to the new node manually.

**Comment by andrewrynhard** [comment]
In combination with putting all the master nodes behind a load balancer, as long as at least one master is up any future nodes could join as a master as well.

**Comment by pires** [comment]
Exactly my point! @timothysc wdyt?

**Comment by luxas** [comment]
IIUC, we're starting to talk about cert rotation/HA here now?
That's totally fine and super-interesting, but it's a different topic ;)

This is just about splitting out the serviceaccount thing, and generate a dedicated cert/key pair for it

**Comment by andrewrynhard** [comment]
@luxas yes the discussion has deviated from the scope of this ticket. @pires and I were talking about HA briefly before in slack. Can we move this conversation there or have it at one of the meetings?

**Comment by timothysc** [comment]
I would grok the other installers to validate their process.  kargo, openshift-ansible, etc.  I typically offload cert-magic on them.

**Comment by luxas** [comment]
Fixed with: https://github.com/kubernetes/kubernetes/issues/41295
