### ISSUE TITLE
Add way to specify kubeadm's --ignore-preflight-errors in InitConfiguration and JoinConfiguration

### ISSUE THREAD

**Issue by marccarre** [kubernetes/kubeadm#1460]
**What would you like to be added**:

A single way to configure all of `kubeadm`'s behaviour.
In particular, given `ignorePreflightErrors` and `externalcfg` are currently disjoint:

- https://github.com/kubernetes/kubernetes/blob/a887ae8344adf9739c1d156a718c05fdf95b73ab/cmd/kubeadm/app/cmd/init.go#L104-L106
- https://github.com/kubernetes/kubernetes/blob/a887ae8344adf9739c1d156a718c05fdf95b73ab/cmd/kubeadm/app/cmd/join.go#L132-L133

I would like a way to specify the set of strings corresponding to `--ignore-preflight-errors`'s value as an "array" in (at least) `InitConfiguration` and `JoinConfiguration`.

**Why is this needed**:

This would simplify programmatic usage of `kubeadm`: one configuration file to generate, and then pass to `kubeadm`.

**Potential way forward**:

1. Keep `--ignore-preflight-errors` for backward-compatibility (for now).
2. Add the following field to both `InitConfiguration` and `JoinConfiguration`:

    ```go
    IgnorePreflightErrors []string `json:"ignorePreflightErrors,omitempty"`
    ```

3. Take the union of both sets, validate it (as currently done), and use this going in the rest of the program.

**Misc.**:

Happy to make the change myself, once I get a "go" (or at least, no "no-go") from someone more knowledgeable. (Maybe @luxas? 🙂 )

/kind feature
/sig cluster-lifecycle

**Comment by fabriziopandini** [comment]
@marccarre fyi yesterday in the kubeadm office hours planning for v1.15 was discussed
There is a batch of changes for the config (including this), and there will be a deep dive hopefully next week. If you want to join the discussion you are more than welcome!

**Comment by fabriziopandini** [comment]
Fyi https://github.com/kubernetes/kubeadm/issues/1439#issuecomment-474728529
