### ISSUE TITLE
Update Contributing Guidelines for "Building" Section

### ISSUE THREAD

**Issue by Bubblemelon** [kubernetes/kubeadm#1466]
Under the [Building](https://github.com/kubernetes/kubeadm/blob/master/CONTRIBUTING.md#building) section of `CONTRIBUTING.md` :

There should be a new link to replace "_See ./vagrant/README.md for a quick workflow to build and test your own kubeadm binaries_"

Since all the `/vagrant` files have been removed in commit: https://github.com/kubernetes/kubeadm/commit/90a02d77e117645cd233fec3a6dcb837628ac9fe 

As far as I can tell, based on [the statement](https://github.com/kubernetes/kubeadm/commit/90a02d77e117645cd233fec3a6dcb837628ac9fe#diff-a33810049da88ccb0b4c6fb4d2b3c757) in `/vagrant/README.md` 
and and PR #1446  , I suggest pointing to https://github.com/kubernetes/kubeadm/tree/master/kinder in the Building section of `CONTRIBUTING.md`.

**Comment by yagonobre** [comment]
Thanks @bubblemelon for reporting this, would you want to send a pr with the fix?

**Comment by Bubblemelon** [comment]
:smile:  Checkout my pr :arrow_up:

**Comment by yagonobre** [comment]
Closed by https://github.com/kubernetes/kubeadm/pull/1467
/close
