### ISSUE TITLE
Make /etc/kubernetes/ a constant

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#147]
The `/etc/kubernetes/` path should be a constant in kubeadm and _not changeable_. We have to draw the line between configurability and standardization, and if you do want to use an other path (although there's no reason to), a lot of other things will break.

So myself and @mikedanese made the decision in https://github.com/kubernetes/kubeadm/pull/100 that this path should not be configurable, it's a standardized path for k8s deployments.

In the same manner, `/etc/kubernetes/manifests` is the standardized path for Static Pods.

Right now, `/etc/kubernetes` is configurable via an env param in kubeadm, which leads to extra complexity.
Instead, a constant should be made in `cmd/kubeadm/app/constants` and consumed everywhere.

**Comment by luxas** [comment]
I think this could be a good first contribution for @wilkers-steve and @larryrensing :+1:

**Comment by wilkers-steve** [comment]
@luxas Sounds good!  We'll start on this today

**Comment by fabriziopandini** [comment]
This topic is related also to kubeadm #45008 https://github.com/kubernetes/kubernetes/pull/45008 addresses "Fix behaviour of parameters insensible to KUBE_KUBERNETES_DIR env var"

**Comment by pipejakob** [comment]
It looks like the const exists now, but is it still desirable to completely kill the ability to override it? https://github.com/kubernetes/kubeadm/issues/232 seems to be a valid usecase for wanting to write files elsewhere, if the user really knows what they're doing.

**Comment by luxas** [comment]
@pipejakob @errordeveloper How common is it to have `/etc` ro-mounted? Is it possible to `ln -s` in some way to workaround that while keeping `/etc/kubernetes` a constant in kubeadm.
I want to minimize complexity inside of the tool and I think having the manifests in different places may mostly lead to confusion... as noted in the design proposal

**Comment by luxas** [comment]
Now fixed
