### ISSUE TITLE
New experimental-upload-certs flag handling of external etcd certs

### ISSUE THREAD

**Issue by krisdock** [kubernetes/kubeadm#1472]
## What keywords did you search in kubeadm issues before filing this one?
experimental
external etcd

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.14

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.14
- **Cloud provider or hardware configuration**: GCE nodes
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.6.1810 (Core)
- **Kernel** (e.g. `uname -a`): 3.10.0-957.5.1.el7.x86_64
- **Others**:

## What happened?
I have a cluster utilizing an external etcd cluster. I attempted to add a second control plane node with the `--certificate-key` flag. The join fails with:
```
[preflight] Running pre-flight checks before initializing the new control plane instance
	[WARNING ExternalEtcdClientCertificates]: /etc/kubernetes/pki/etcd/ca.crt doesn't exist
	[WARNING ExternalEtcdClientCertificates]: /etc/kubernetes/pki/apiserver-etcd-client.crt doesn't exist
	[WARNING ExternalEtcdClientCertificates]: /etc/kubernetes/pki/apiserver-etcd-client.key doesn't exist
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ExternalEtcdVersion]: couldn't load external etcd's server certificate /etc/kubernetes/pki/etcd/ca.crt: open /etc/kubernetes/pki/etcd/ca.crt: no such file or directory
```

If I skip the `ExternalEtcdClientCertificates` and `ExternalEtcdVersion` preflight checks, the join works and the external etcd certs/keys are properly copied over.

## What you expected to happen?
I shouldn't have to skip those checks if using the new experimental-upload-certs and cert-key flags/features.

## How to reproduce it (as minimally and precisely as possible)?
Init a cluster with the `--experimental-upload-certs` flag that is using an external etcd cluster then use the control plane join command from the output to try to join another control plane node.

**Comment by fabriziopandini** [comment]
/close
fixed on master; cherry pick for v1.14 https://github.com/kubernetes/kubernetes/pull/75851
