### ISSUE TITLE
Invalid kube-dns to CoreDNS translation

### ISSUE THREAD

**Issue by rajansandeep** [kubernetes/kubeadm#1473]
Kube-dns now [accepts service name for stubdomain and nameserver](https://github.com/kubernetes/dns/pull/279), while CoreDNS does not support this feature.

As a result, a user having service name in stubdomains/nameserver in their kube-dns ConfigMap while migrating to CoreDNS will result in an invalid CoreDNS Config, resulting in a broken k8s cluster.

/kind bug
/area upgrades
/priority important-soon
/assign

**Comment by neolit123** [comment]
@rajansandeep 

thanks for logging this!

could you please clarify what has to be done on the kubeadm side?
do you plan on detecting such a service name under the stubs or nameserver (e.g. "google.local") in the ConfigMap during upgrade and omitting / ignoring it until CoreDNS supports the feature.

we seem to need some CoreDNS version detection too.

@kubernetes/sig-cluster-lifecycle

**Comment by rajansandeep** [comment]
>do you plan on detecting such a service name under the stubs or nameserver (e.g. "google.local") in the ConfigMap during upgrade and omitting / ignoring it until CoreDNS supports the feature.

Yes, I will detect a service name and omit it while translating to the equivalent CoreDNS config.
And additionally warn the user that it has been omitted during translation since it's not supported.
