### ISSUE TITLE
Make a `kubeadm phase` command that invokes the individual phases

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#148]
In last sig meeting, we voted that the command that can invoke individual phases should be named `kubeadm phase`.

Example commands might then be:
 - `kubeadm phase certs --altnames=mydomain --dns-domain=cluster.external --cert-dir=/var/lib/kubecerts --service-subnet=10.97.0.1/13`
 - `kubeadm phase certs --config cert-config.yaml`
 - `kubeadm phase controlplane --type self-hosted`
 - `kubeadm phase addons --dns-domain=cluster.external --extra-manifests https://somesite.com/manifest.yaml`

(Those examples are just examples of what if _might_ look like, not binding)

**Comment by luxas** [comment]
Basic implementation in v1.6, more advanced implementation will exist in v1.8

**Comment by fabriziopandini** [comment]
Duplicate of #267; I suggest to merge and keep only one as soon as we review proposal document for 1.8

**Comment by luxas** [comment]
Closing as a duplicate of #267 then, anyway we're really soon done with this one.
