### ISSUE TITLE
We need delete kubeconfig

### ISSUE THREAD

**Issue by MengZn** [kubernetes/kubeadm#1480]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
```bash
$kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:35:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```bash
$cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
``` 
- **Kernel** (e.g. `uname -a`):
```bash
$uname -a
Linux vagrant 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?

Everyone knows that when we enter kubeadm reset -f, the program will not delete it($HOME/. kube /config) automatically.

## What you expected to happen?

We need a way to delete the cluster and delete $HOME/. kube /config

## How to reproduce it (as minimally and precisely as possible)?
Can try to delete the cluster by ```kubeadm reset -f ``` and use ls ```$ HOME /. Kube / config```
## Anything else we need to know?
I am working hard to add this feature.
If you can assign this task to me please.

**Comment by neolit123** [comment]
> We need a way to delete the cluster and delete $HOME/. kube /config

multiple other tools don't delete the kubeconfig and leave it to the user to clean manually.
why are you considering this being a problem?

> I am working hard to add this feature.
If you can assign this task to me please.

please hold before sending PRs so that we can have discussion.
@kubernetes/sig-cluster-lifecycle

**Comment by yagonobre** [comment]
We don't create this file, so IMO we shouldn't delete it.

**Comment by detiber** [comment]
I agree that this seems outside the scope of `kubeadm`, since we only instruct the user how to copy the file to the default kubeconfig path and do not actually perform the copying.

**Comment by yagonobre** [comment]
We can add a warning on`kubeadm reset`

**Comment by rosti** [comment]
I like @yagonobre 's idea. Hinting the user that "Note: You may want to revisit your $HOME/.kube/config file in order to remove the resetted cluster from there" can do the trick.

Blindly removing that file is not an option for a couple of reasons:
1. We did not create that file.
2. It can contain the info on how to connect to a multitude of clusters.

**Comment by MengZn** [comment]
I also agree with @yagonobre your idea and let the user decide if the file should be deleted.

Can the work of prompting user information be assigned to me please?

**Comment by rosti** [comment]
@MengZn feel free to work on that. Ping me for a review when you have something.
