### ISSUE TITLE
kubeadm 1.13.5 from official yum repo installs kubelet 1.14.0 as a dependency

### ISSUE THREAD

**Issue by MarkDeckert** [kubernetes/kubeadm#1481]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
1.13.5

## What happened?
I was updating cluster from 1.13.3 to 1.13.5.  When I do a yum install kubeadm-1.13.5 from official yum repository it wants to install kubelet 1.14.0 as a dependency.

```
Updating:
 kubeadm                         x86_64                  1.13.5-0
Updating for dependencies:
 kubelet                         x86_64                  1.14.0-0
 kubernetes-cni                  x86_64                  0.7.5-0
```

## What you expected to happen?
kubelet dependency should match kubeadm version at 1.13.5

## How to reproduce it (as minimally and precisely as possible)?
yum install kubeadm-1.13.5

**Comment by MarkDeckert** [comment]
Just as an extra datapoint:
```
# yum deplist kubeadm-1.13.5
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: mirror.layeronline.com
package: kubeadm.x86_64 1.13.5-0
  dependency: cri-tools >= 1.11.0
   provider: cri-tools.x86_64 1.12.0-0
  dependency: kubectl >= 1.6.0
   provider: kubectl.x86_64 1.14.0-0
  dependency: kubelet >= 1.6.0
   provider: kubelet.x86_64 1.14.0-0
  dependency: kubernetes-cni >= 0.7.5
   provider: kubernetes-cni.x86_64 0.7.5-0
```

**Comment by neolit123** [comment]
/sig release
the kubeadm, kubelet, etc packages are a best effort and need a complete rewrite.

with:
```
dependency: kubelet >= 1.6.0
```
it just pulls the latest kubelet.

you are going to have to use pinning and hold.

**Comment by fabriziopandini** [comment]
:scream:

**Comment by timothysc** [comment]
Closing b/c @kubernetes/sig-release has sent out messaging on this issue.
