### ISSUE TITLE
kubeadm init did not install '/root/.kube/plugins/verify/verify.sh', after kubeadm reset.

### ISSUE THREAD

**Issue by zhang-shengping** [kubernetes/kubeadm#1484]
Hello, I met a problem with `kubeadm init` after `kubeadm reset`, the CLI `kubectl get pods` return error: `-bash: /root/.kube/plugins/verify/verify.sh: No such file or directory`

Reproduce the error:
1. Use kubeadm `(Major:"1", Minor:"13", GitVersion:"v1.13.4")` to setup a kubernetes env.
3. Delete all deployments, and run `kubeadm reset`.
4. Follow the log of `kubeadm reset` and clean the `iptables`.
5. Restart vm
6. after the vm booted, Ran `kubeadm init` again
7. Follow the log of `kubeadm init` and mkdir `.kube` and cp the config to the dir
8. Run CLI `kubectl get pods`
9. `-bash: /root/.kube/plugins/verify/verify.sh: No such file or directory`

I checked the .kube directory, there is no verify.sh. the log only tells to cp `config`, so why the CLI complains about `verify.sh`? what is `verify.sh`? or did I do something wrong?

**Comment by yagonobre** [comment]
Hi @zhang-shengping it's not seems to be a kubeadm problem, but what os are you using?

/priority awaiting-more-evidence

**Comment by zhang-shengping** [comment]
@yagonobre 
 
The Linux distribution:
```
root@robota:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

The Keneral:
```
root@robota:~# uname -a
Linux robota 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fabriziopandini** [comment]
@zhang-shengping writing anything in `root/.kube/plugins/` is out of scope of kubeadm tasks, so  I agree with @yagonobre this doesn't seems a kubeadm problem 

This is probably something related to kubectl plugin feature, so my suggestion is to close this PR here and reopen it in the main Kubernetes repo adding the Sig CLI label
