### ISSUE TITLE
Automatically add roles to non-controlplane nodes

### ISSUE THREAD

**Issue by tahsinrahman** [kubernetes/kubeadm#1487]
## FEATURE REQUEST
Automatically add `node-labels: "node-role.kubernetes.io/node="` to `kubeletExtraArgs `for non-controlplane nodes. So it would show role `node` instead of `<none>`

## What happened?
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/681
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/170

cc @detiber

**Comment by detiber** [comment]
Unless there are valid use cases for keeping the default joined nodes showing with a role of <none>, I think this is a worthwhile change.

/cc @neolit123 @fabriziopandini

**Comment by neolit123** [comment]
i will bring this in the agenda for kubeadm office hours today.

**Comment by mitchellmaler** [comment]
Would it make more sense to label non control plane nodes as worker and not just node? I know worker is used even in the kubeadm docs when joining.

**Comment by neolit123** [comment]
>  I know worker is used even in the kubeadm docs when joining.

can you link to this docs page?

**Comment by mitchellmaler** [comment]
This page mentions the worker on the first line. "Initializes a kubernetes worker node"
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

**Comment by neolit123** [comment]
ok, i though we had instances of `node-role.kubernetes.io/worker` in the documentation.

**Comment by justaugustus** [comment]
Canonical naming (`node`) for reference: https://kubernetes.io/docs/concepts/architecture/nodes/

**Comment by rosti** [comment]
I know, that kops, for instance, uses `node` and not `worker`. Not aware of other setup tools.

**Comment by endzyme** [comment]
Should this be closed due to the decision referenced in the above-mentioned PR? https://github.com/kubernetes/kubernetes/pull/77923#pullrequestreview-237992447

**Comment by neolit123** [comment]
as a PSA, we decided to not do that due to:
- the change will break existing kubeadm users
- the kubelet rejects `node-role` self-assigned labels (security concerns)
- in general, we do not want to auto-assign `node-roles` - it's up to the cluster operators to do that.
possibly the Cluster API implementations, should not auto-assign either.

/close
