### ISSUE TITLE
kube-controller-manager doesn't work properly in ha mode after update to v1.14

### ISSUE THREAD

**Issue by username1366** [kubernetes/kubeadm#1494]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:51:21Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu 18.10
- **Kernel** (e.g. `uname -a`): Linux k8s-master1 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Others**: containerd 1.26

## What happened?
After upgrade to 1.14 via kubeadm, kube-controller-manager showed following error:
```
E0403 09:08:30.986462       1 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "endpoints" in API group "" in the namespace "kube-system": RBAC: [role.rbac.authorization.k8s.io "extension-apiserver-authentication-reader" not found, role.rbac.authorization.k8s.io "system::leader-locking-kube-controller-manager" not found]
```
And some of daemonset pods can't schedule

kubectl describe ds -n kube-system calico-node
```
Desired Number of Nodes Scheduled: 196
Current Number of Nodes Scheduled: 195
Number of Nodes Scheduled with Up-to-date Pods: 195
Number of Nodes Scheduled with Available Pods: 195
Number of Nodes Misscheduled: 0
Pods Status:  195 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

## What you expected to happen?
I expect that daemonset's pods will schedule properly

## How to reproduce it (as minimally and precisely as possible)?
Kubernetes HA topology:
https://kubernetes.io/docs/setup/independent/ha-topology/#stacked-etcd-topology

## Anything else we need to know?
Related to the issue https://github.com/kubernetes/kubernetes/issues/75937

**Comment by neolit123** [comment]
> E0403 09:08:30.986462       1 leaderelection.go:306] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "endpoints" in API group "" in the namespace "kube-system": RBAC: [role.rbac.authorization.k8s.io "extension-apiserver-authentication-reader" not found, role.rbac.authorization.k8s.io "system::leader-locking-kube-controller-manager" not found]

it doesn't seem like a kubeadm problem, directly.

are you waiting a few minutes before adding your secondary control plane nodes?

**Comment by timothysc** [comment]
@fabriziopandini we should eval on our current HA upgrade scenario. 

/assign @yagonobre @fabriziopandini

**Comment by Gangadharkandula** [comment]
hi,
i am doing master node.i given below command
## kubeadm init --config=kubeadm-config.yaml --experimental-upload-certs
i am getting error:

[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'docker logs CONTAINERID'

**Comment by RA489** [comment]
@username1366 can you please restart the kubelet if not running.

**Comment by Gangadharkandula** [comment]
> @username1366 can you please restart the kubelet if not running.

hi,

kublete is already running.....still we are getting same errror.

**Comment by neolit123** [comment]
> kube-controller-manager doesn't work properly in ha mode after update to v1.14

we have upgrade CI test signal where 1.13->1.14 HA upgrades work:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1.13-1.14

to me this seems related to https://github.com/kubernetes/kubernetes/issues/78633 and possibly a kubeernetes bug (not kubeadm). please re-open if needed.

> i am doing master node.i given below command
> kubeadm init --config=kubeadm-config.yaml --experimental-upload-certs

this seems like a separate issue.
