### ISSUE TITLE
Documentation about kubeadm systemd dropin out of date

### ISSUE THREAD

**Issue by arianvp** [kubernetes/kubeadm#1496]
FEATURE REQUEST

The description of the kubeadm drop-in file is out of sync with
What the drop-in file actually contains.

See https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#kubelet-drop-in

 Vs 

https://github.com/kubernetes/kubernetes/blob/master/build/debs/10-kubeadm.conf

However this part of the documentation _does_ describe the drop-in correctly. Perhaps 
The docs for `kubeadm init` should just copy over this part : https://kubernetes.io/docs/setup/independent/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

**Comment by neolit123** [comment]
thanks for the report.
we should probably just remove this reference there and link to this one:
https://kubernetes.io/docs/setup/independent/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

/sig cluster-lifecycle
/assign
