### ISSUE TITLE
Kubeadm upgrade 1.14.0 postupgrade addon coredns failed cause by label

### ISSUE THREAD

**Issue by ypsilik** [kubernetes/kubeadm#1499]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.14.0
- **Kubernetes version** (use `kubectl version`): 1.13.4
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Others**: kubernetes is deployed with kubespray and kubeadm

## What happened?

Currently postupgrade failed if dns haven't `k8s-app: kube-dns` label.
 
```
[upgrade/postupgrade] FATAL post-upgrade error: unable to update deployment:
Deployment.apps "coredns" is invalid: spec.selector: Invalid value:
v1.LabelSelector{MatchLabels:map[string]string{"k8s-app":"kube-dns"}, MatchExpressions:
[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

It's because kubespray coredns deployment have `k8s-app: coredns` label instead of `k8s-app: kube-dns`. 
If I modify label, all works fine but I think is a good practice to set k8s-app with app name. 

## What you expected to happen?

```
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy
[upgrade/successful] SUCCESS! Your cluster was upgraded to "v1.14.0". Enjoy!
```

## How to reproduce it (as minimally and precisely as possible)?

Run an upgrade from k8s 1.13 to 1.14 with core-dns deploy instead of kube-dns.
```
kubeadm upgrade apply v1.14.0 --config=/etc/kubernetes/kubeadm-config.yaml \
--ignore-preflight-errors=all --allow-experimental-upgrades \
--allow-release-candidate-upgrades --etcd-upgrade=false --force -y
```

**Comment by neolit123** [comment]
> If I modify label, all works fine but I think is a good practice to set k8s-app with app name.

that is true, but kubeadm decided to keep the app name kube-dns until the service name is also core-dns, in which case we can rename both the deploylment and service.

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go

> []v1.LabelSelectorRequirement(nil)}: field is immutable

this is expected to fail under such conditions and we also have other immutable fields.

> kubernetes is deployed with kubespray and kubeadm

as far as i know kubespray uses kubeadm under the hood, but it's unclear to me why it's coredns deployment differs. i'd say that we should close this issue and report the problem to the kubespray repository. kubespray has to use the kubeadm coredns manifests (or something very close to it) if it wants to cleanly support kubeadm upgrades.

@kubernetes/sig-cluster-lifecycle 
/close
