### ISSUE TITLE
How to set extra args for kube-proxy

### ISSUE THREAD

**Issue by wnxn** [kubernetes/kubeadm#1500]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
v1.13.5

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.13.5

## What happened?

I want to create a Kubernetes v1.13 cluster by kubeadm phase and kubeadm config file.
I can set all parameters for [kube-apiserver, kube-controller-manager, kube-scheduler](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#ControlPlaneComponent) and [kubelet](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#NodeRegistrationOptions) by "ExtraArgs". But I can not set ExtraArgs, such as log level (-v), for kube proxy in kubeadm config file.

## What you expected to happen?

Add kube-proxy's ExtraArgs parameter in kubeadm config file

**Comment by wnxn** [comment]
PTAL /assign @neolit123

**Comment by neolit123** [comment]
/triage support
/sig network

hi, kube-proxy has a KubeProxyConfiguration component config that kubeadm supports:
https://github.com/kubernetes/kube-proxy/blob/master/config/v1alpha1/types.go#L98

you can add it at the bottom of your kubeadm configuration file that you pass to kubeadm init, like so:
```
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
# kube-proxy specific options here
```
see here:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1

for more details.

**Comment by neolit123** [comment]
please reopen if you question is not answered.

**Comment by rulai-jianfang** [comment]
I found another way to do it, planning to use ipvs instead of iptables:

1. Change the configMap of kube-proxy,  modify "mode" from "" to "ipvs"
```
 kubectl -n kube-system edit cm kube-proxy
```

2. Delete all the active proxy pods
```
kubectl get pods -n kube-system

kubectl delete pod --namespace=kube-system kube-proxy-<random name>
```

3. Check the logs of new kube-proxy pods
```
kubectl -n kube-system logs kube-proxy-c6sqb
```
Result: change to ipvs Proxier
```
I1014 22:58:53.309128       1 node.go:135] Successfully retrieved node IP: 10.238.244.92
I1014 22:58:53.309225       1 server_others.go:176] Using ipvs Proxier.
W1014 22:58:53.309904       1 proxier.go:420] IPVS scheduler not specified, use rr by default
I1014 22:58:53.310228       1 server.go:529] Version: v1.16.1
I1014 22:58:53.311527       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I1014 22:58:53.314803       1 config.go:131] Starting endpoints config controller
I1014 22:58:53.314891       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
I1014 22:58:53.314929       1 config.go:313] Starting service config controller
I1014 22:58:53.314946       1 shared_informer.go:197] Waiting for caches to sync for service config
I1014 22:58:53.415272       1 shared_informer.go:204] Caches are synced for endpoints config
I1014 22:58:53.415272       1 shared_informer.go:204] Caches are synced for service config
```

**Comment by Joseph94m** [comment]
Hi @neolit123. Sorry to restart this ticket but it's the closest to my question. I would like to be able to specify the interface (eth0 (private) for instance) on which i would like the kube-proxy to communicate. By default, it exposes itself on both the private and the public interfaces. For us, this is a security issue and I need to stop all public ports and force all of the communications on the internal network. I understand that there are configuration parameters that can be used in kubeadm to set kube-proxy configurations:

> apiVersion: kubeproxy.config.k8s.io/v1alpha1  
> kind: KubeProxyConfiguration. 
> mode: iptables

I found some references for these configs:
[kube-proxy-github](https://github.com/kubernetes/kube-proxy/blob/master/config/v1alpha1/types.go#L98)
[kube-proxy-doc](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/#options)

But they only allow me to set a specific address,  globally and once only. Given that i want to apply this option on all of my k8s nodes, this isn't possible. Any suggestions?

**Comment by Joseph94m** [comment]
Do you think that setting the bind to 192.168.0.0 could work?

**Comment by neolit123** [comment]
hi, @Joseph94m this is a common problem for other components too like kubelet - there is no way to specify the interface.
you could log a ticket in the kubernetes/kubernetes repository and tag it with `/sig network`; this is the group the maintains kube-proxy.

**Comment by Joseph94m** [comment]
Ok but in kubelet we specifiy the IP for each node by modifying the `/usr/lib/systemd/system/kubelet.service.d/20-cri.conf` and adding something like `Environment="KUBELET_EXTRA_ARGS=--node-ip=${PRIVATE_IP} `

I'll go post in kubernetes/kubernetes thanks for the advice

**Comment by neolit123** [comment]
kubeproxy has a "bind address" (i.e. where to bind to for serving):
https://godoc.org/k8s.io/kube-proxy/config/v1alpha1#KubeProxyConfiguration

**Comment by Joseph94m** [comment]
Yeah but's a cluster wide Config map

**Comment by neolit123** [comment]
> Yeah but's a cluster wide Config map. Not something that is node specific. 

for instance specific configuration see this WIP proposal:
https://github.com/kubernetes/enhancements/pull/1439

**Comment by Joseph94m** [comment]
Great. I see this is WIP so there is no need for me to propose it.
Thank you for your return.
