### ISSUE TITLE
Chicken and egg problem changing cgroup driver

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#1501]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
Brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04
- **Kernel** (e.g. `uname -a`):
Linux srv-fwu87 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?

There doesn't appear to be a way of getting a kubeadm installation installed on the 'cgroupfs' Cgroup across to the 'systemd' cgroup when you receive the preflight error https://github.com/kubernetes/kubeadm/issues/1394

If you alter the docker config in 'daemon.json' to enable the systemd cgroup, then kubelet crashes with the error

```
kubelet[7257]: F0411 14:31:02.244445    7257 server.go:261] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"
```

and kubeadm upgrade won't run

```
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/health] FATAL: [preflight] Some fatal errors occurred:
	[ERROR ControlPlaneNodesReady]: there are NotReady control-planes in the cluster: [srv-fwu87]
```

## What you expected to happen?

There should be a way to move from cgroupfs to systemd gracefully, or at least in a documented manner. 

## How to reproduce it (as minimally and precisely as possible)?

- Install 1.13.5 cluster using standard docker.io package. 
- Add the daemon.json to set the cgroup,  as shown here: https://kubernetes.io/docs/setup/cri/
- restart docker. 
- Try to run a kubeadm upgrade to 1.14.1

**Comment by neolit123** [comment]
> cgroup when you receive the preflight error #1394

it's a non-fatal preflight warning.
running with either cgroupfs or systemd on the docker side will work, but as https://kubernetes.io/docs/setup/cri/ explains it's advisable to use systemd as the manager.

having said that, we might have a bug in here, such as the kubeadm-flags.env file does not receive the `--cgroup-driver=systemd` properly after the kubeadm auto-detection of the manager:
https://kubernetes.io/docs/setup/independent/kubelet-integration/#the-kubelet-drop-in-file-for-systemd

will try to reproduce the steps in a minute.

**Comment by neolit123** [comment]
@NeilW i think i might need more details from you because i could not reproduce your steps locally.

- had docker with cgroupfs as the cgroup manager
- created cluster with 1.13.5
- modified daemon.json to systemd as the cgroup manager
- restarted docker
- the cluster came back up fine
- installed kubeadm 1.14.1
- ran kubeadm upgrade plan / apply
- the cluster came back up fine
- upgraded kubelet to 1.14.1
- the cluster came back up fine

which docker version are you running?
also if you try to create a single node CP node cluster with systemd in daemon.json does `kubeadm init` pass? this question is related to /var/lib/kubelet/kubeadm-flags.env and the cgroup-driver flag detection, which works on my side.

**Comment by NeilW** [comment]
:/

I'm using the docker.io package from the Ubuntu archives, which is 18.09.2 I think. I'll find out why kubelet is falling over and failing to restart.

**Comment by utdrmac** [comment]
From the dockerd systemctl script:

```
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
```

If docker does not recommend using systemd, why is kubernetes suggesting it is preferred?

**Comment by neolit123** [comment]
please read here: https://kubernetes.io/docs/setup/cri/

**Comment by utdrmac** [comment]
> please read here: https://kubernetes.io/docs/setup/cri/

It should be noted that those instructions do not work on CentOS 7.5. Even with daemon.conf contents as exactly on those docs, dockerd does not parse it and continues to start up with cgroupfs

**Comment by neolit123** [comment]
> Even with daemon.conf contents as exactly on those docs, dockerd does not parse it and continues to start up with cgroupfs

are you naming the file /etc/docker/daemon.json ?
if it ignores that file i would consider this a bug in the daemon.

**Comment by utdrmac** [comment]
Son of a .... sorry. I named it daemon.conf for some reason.

**Comment by NeilW** [comment]
Ok, I think I have it. 

The process that fails is as follows

- Install a 1.13.5 cluster using the k8s Debian packages at version 1.13.5, and using the docker.io package from the Ubuntu archives
- Add in a daemon.json and restart docker - which kills all the containers in the cluster. Kubelet then starts issuing errors like this:
```
kubelet[18651]: E0412 07:09:02.576609   18651 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "etcd-srv-4864d": Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"
```
- Upgrade the kubeadm package to 1.14.1 *which restarts kubelet*. And then you're stuck with errors like this:

```
Apr 12 07:09:03 srv-4864d kubelet[11064]: I0412 07:09:03.933877   11064 docker_service.go:256] Docker Info: &{ID:O7XZ:WDL7:OFVM:E6ZS:RMWH:32H6:EHQW:BMAJ:QRZZ:WFKJ:ZLMJ:KMJH Containers:19 ContainersRunning:0 ContainersPaused:0 ContainersStopped:19 Images:10 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true]] SystemStatus:[] Plugins:{Volume:[local] Network:[bridge host macvlan null overlay] Authorization:[] Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:false KernelMemory:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:23 OomKillDisable:true NGoroutines:45 SystemTime:2019-04-12T07:09:03.915864887Z LoggingDriver:json-file CgroupDriver:systemd NEventsListener:0 KernelVersion:4.15.0-47-generic OperatingSystem:Ubuntu 18.04.2 LTS OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc0003b8b60 NCPU:2 MemTotal:2090029056 GenericResources:[] DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:srv-4864d Labels:[] ExperimentalBuild:false ServerVersion:18.09.2 ClusterStore: ClusterAdvertise: Runtimes:map[runc:{Path:docker-runc Args:[]}] DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:9754871865f7fe2f4e74d43e2fc7ccd237edcbce Expected:9754871865f7fe2f4e74d43e2fc7ccd237edcbce} RuncCommit:{ID:09c8266bf2fcf9519a651b04ae54c967b9ab86ec Expected:09c8266bf2fcf9519a651b04ae54c967b9ab86ec} InitCommit:{ID:v0.18.0 Expected:fec3683b971d9c3ef73f284f176672c44b448662} SecurityOptions:[name=apparmor name=seccomp,profile=default]}
Apr 12 07:09:03 srv-4864d kubelet[11064]: F0412 07:09:03.934006   11064 server.go:261] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"
```
- then the upgrade doesn't work
```
$ sudo kubeadm upgrade plan --config $HOME/install/kubeadm.conf
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/health] FATAL: [preflight] Some fatal errors occurred:
	[ERROR APIServerHealth]: the API Server is unhealthy; /healthz didn't return "ok"
```

So it looks like you have to upgrade kubeadm before switching docker over, and that might work around it.

**Comment by neolit123** [comment]
i can no longer reproduce my steps from yesterday:
```
had docker with cgroupfs as the cgroup manager
created cluster with 1.13.5
modified daemon.json to systemd as the cgroup manager
restarted docker
the cluster came back up fine
```

> Add in a daemon.json and restart docker - which kills all the containers in the cluster. Kubelet then starts issuing errors like this:

in my testing, given the default docker manager was cgroupfs and the introduction of a daemon.json changes the manager to systemd the containers are killed and not recreated. the error i'm seeing is also similar to:

> kubelet[18651]: E0412 07:09:02.576609   18651 remote_runtime.go:96] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "etcd-srv-4864d": Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"

the slices are an artifact of the systemd manager.

my thinking here is the following:
- a cluster is running using cgroupfs as the driver in docker and the same for the kubelet (the `--cgroup-driver` flag is configured by kubeadm)
- the cgroup driver in docker changes to systemd and docker is restarted
- the docker daemon will start throwing errors via `(Run|Create)PodSandbox` because the existing cgroup parents are not systemd slices.
- kubelet is in a healthy state but the containers are not coming back up.
- restarting the kubelet will not work properly without:
  - modify `/var/lib/kubelet/kubeadm-flags.env` to have `--cgroup-driver=systemd`
  - systemctl restart kubelet

the same does not happen if the reverse is done: have a running cluster using systemd -> switch docker to cgroupfs -> works -> switch to systemd -> works (repeat)

this works for some reason, i do not know why. but either way not restarting the kubelet while swapping the manager seems like a really bad practice and probably leaks resources too.

regardless, this suggests that changing the cgroup manager on a running cluster is really *not recommended*. i should add a note about that in the docs. the proper recommended way of doing this is to `kubeadm reset` the node and rejoin it to the cluster and also always use https://kubernetes.io/docs/setup/cri/ to install a kubeadm compatible docker.

**Comment by NeilW** [comment]
I'd agree with that. I've been fighting this for a couple of days. 

Similarly if you have live restore running in the docker daemon to avoid the problem with the system being shut down when docker has a security fix upgrade, then all the containers can end up in a different cgroup and chaos ensues. 

Looks like it is a rather harder problem to solve than it first appears, without a clean restart of the server.

**Comment by anguslees** [comment]
> regardless, this suggests that changing the cgroup manager on a running cluster is really not recommended. i should add a note about that in the docs. the proper recommended way of doing this is to kubeadm reset the node and rejoin it to the cluster 

@neolit123 (or others?) There was a question on #kubernetes-dev today regarding the note you added to the docs, and I was unable to answer it :)   Can you describe further why a node *re-join* is necessary here?

My rudimentary understanding suggests a node **reboot** would be sufficient to trigger systemd/dockerd/kubelet to recreate the podsandboxes correctly under the new regime.  (Specifically: node drain, change dockerd/kubelet flags, reboot, uncordon)

I agree that re-join is one way to get kubeadm to update the `--cgroup-driver` flag in `/var/lib/kubelet/kubeadm-flags.env`.  Is there more to it than this however?

Thanks for any additional experience that we can add to the communal memory...

**Comment by neolit123** [comment]
join is the easier option for users.

> My rudimentary understanding suggests a node reboot would be sufficient to trigger systemd/dockerd/kubelet to recreate the podsandboxes correctly under the new regime. (Specifically: node drain, change dockerd/kubelet flags, reboot, uncordon)

on theory yes, if there are no pods to sandbox, then switching the cgroup driver might just work. i have not tried. if you have the time, please try this and if it works, feel free to PR the note for k/website.

probably someone at #sig-node is more competent on such topics.
in any case i doubt they recommend switching drivers too.

**Comment by b10s** [comment]
@neolit123 
> it's a non-fatal preflight warning.

But I think should be a fatal: https://systemd.io/CGROUP_DELEGATION/
and probably related issue: https://github.com/kubernetes/kubernetes/issues/95488
