### ISSUE TITLE
Allow multiple config files

### ISSUE THREAD

**Issue by arianvp** [kubernetes/kubeadm#1502]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

The current kubeadm config file passed by `--config`
is multiple yaml documents one "file" separated by `---`.

I currently have a piece of tooling that generates kubeadm configs, but as `json` because
`json` is easier to target with our code generator.  However,  `json` has no concept of multiple
documents per file.

I was wondering if we could fix this by allowing multiple invocations of `--config` ala:

```
---config init-config.json --config cluster-config.json --config kubelet-config.json
```

Just like `kubectl` supports providing multiple json files as an argument.

Another option would be to support the `kind: List` api type just like `kubectl` does, such that
you can have multiple api objects without requiring multiple 'documents'

```
{ 
  "kind": "List",
  "items" : [
    {kind:"InitConfiguration", ...}, 
    {kind:"KubeletConfiguration", ...}
  ] 
}
```

**Comment by neolit123** [comment]
i think we had a ticket for this already, but i cannot find it.
there is currently a working group called "component-standard" that is working on standardizing how a component configuration is treated and i think this falls under their scope.

the model of using `---` still has to be supported, but eventually other options can be considered such as passing a folder with files, the same way kubectl supports that.

**Comment by fabriziopandini** [comment]
I agree with @neolit123 that this is something that should be standard across different components

Fyi, another option discussed in the past was to allow users to pass a folder to --config instead of files, but I'm not aware of any analysis of Pro and cons of the various approaches

**Comment by josdotso** [comment]
I am in a situation which is similar to @arianvp's. `kubectl` accepts multiple `-f` statements, so there is precedent. `kind: List` is a kind of multi-"file" format that is compatible with JSON. Kubeadm should accept both the `---` YAML stream as well as the `kind:LIst`.

https://github.com/kubernetes/kubernetes/blob/master/hack/testdata/list.yaml

> To specify resources with one or more files: `-f file1 -f file2 -f file<#>`

https://kubernetes.io/docs/reference/kubectl/overview/

**Comment by rosti** [comment]
There are numerous workarounds for this one ATM. It's better to wait for WG component standard's solution on this for now.

**Comment by neolit123** [comment]
@arianvp 
>  However, json has no concept of multiple documents per file.

try:
```
{
    "apiVersion": "kubeadm.k8s.io/v1beta2",
    "kind": "InitConfiguration",
    "bootstrapTokens": [
        {
            "token": "9a08jv.c0izixklcxtmnze7",
            "description": "kubeadm bootstrap token",
            "ttl": "24h"
        }
    ]
}
---
{
    "apiVersion": "kubeadm.k8s.io/v1beta2",
    "kind": "ClusterConfiguration",
    "kubernetesVersion": "v1.15.1"
}
```

while the document is not valid JSON, the k8s YAML/JSON parsing machinery does support the `---` separator.

but supporting List or a folder seems still viable.

**Comment by neolit123** [comment]
/close
our single config file already supports multiple yaml and json documents.
