### ISSUE TITLE
how to specify etcd prefix

### ISSUE THREAD

**Issue by fkpwolf** [kubernetes/kubeadm#1503]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one:  FEATURE REQUEST

If this is a FEATURE REQUEST, please:
  - when deploy HA k8s cluster with external etcd, I want to specify etcd prefix so different clusters can share one etcd cluster. Currently kubeadm has no this kind of configuration. And api server has supported to accept prefix as a [parameter](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/): `--etcd-prefix string     Default: "/registry"`. 

Is this reasonable to add this feature?

**Comment by neolit123** [comment]
> Is this reasonable to add this feature?

kubeadm already supports this using:
```
kind: ClusterConfiguration
...
apiServer:
  extraArgs:
    etcd-prefix: .....
...
```

see here:
https://kubernetes.io/docs/setup/independent/control-plane-flags/

pass such a file to `kubeadm init` using `--config`.

please re-open if your question is not answered.
thanks.
