### ISSUE TITLE
Change the certificates expired time in config.yml when kubeadm init

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubeadm#1505]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
```sh
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```sh
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```sh
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```sh
Linux kubeadm-231 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?

Use `kubeadm init` to create the Kubernetes cluster, it works well. I found certificates expired time only one year, If time is more than one year, the cluster will not be work. I should renew the certificates manually.

## What you expected to happen?

I hope `kubeadm init` can add a parameter that change the default certificate expired time, we can change the certificate expired time when we create the Kubernetes cluster, such as five years or other time.

**Comment by neolit123** [comment]
having the certificates be valid for more than one year is considered a security issue.
i believe it was agreed that we should not make this configurable.

but you can always try to renew your certificates.

these are our official docs for certs renewal:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

the document is currently missing some detailed steps that can be seen here:
https://github.com/kubernetes/kubeadm/issues/581#issuecomment-471575078

**Comment by pytimer** [comment]
@neolit123  Thanks for you reply.

I know this security issue, and renew these certificates according to your links.

But if the certificate expired, in my case, i need to renew certificates, and  notify other system that out of cluster change the Kubernetes certificates. And some Kubernetes is not control by me, how to do it better?

**Comment by neolit123** [comment]
> and notify other system that out of cluster change the Kubernetes certificates. And some Kubernetes is not control by me, how to do it better?

it really depends on what communication channels you have with the other systems. if you automate the renewal of your cluster certs then you can possibly automate the notifications for the certs change too.

either way communicating the certs update should be secure too - e.g. sending client certificates over secure channels.

**Comment by fabriziopandini** [comment]
@pytimer I would like to better understand your use case: which Kubernetes certificates are you moving around? The only certificate that should be moved IMO is the one in admin.conf (and with limited audience) while everything else is self-contained in the cluster...
Said that, I agree that the UX around certificates renewal can be improved

**Comment by timothysc** [comment]
We discussed the option, but the defaults are picked according to upstream support policy and you can always renew via command line. 

/assign @kad

**Comment by pytimer** [comment]
Sorry, i have something during these days, reply late.

> it really depends on what communication channels you have with the other systems.

@neolit123 Thanks, i understand. But now we have no good channel to notify other systems, so if i renew these certificates, i need to work with other systems together.

@fabriziopandini I renew all certificates and move `admin.conf` to other nodes, but `sa.key` and `sa.pub` still using old.

> the defaults are picked according to upstream support policy

@timothysc What's mean `picked according to upstream support policy`, i don't quite understand it. Did you mean i can setting default certificate expired time?

**Comment by fabriziopandini** [comment]
@kad @pytimer 

considering that you can already provide your own certificates, if necessary, and that as discussed in the kubeadm office hours ATM we are not extending/making configurable the certificate expire time for certificates created by kubeadm, IMO this issue can be closed

I'm also starting some work trying to simplify the certificate renewal UX in v1.15; I hope this will help as well

**Comment by pytimer** [comment]
@fabriziopandini Thanks. I think this issue can be closed.  And i will learn how to use my own certificates for Kubernetes cluster.
