### ISSUE TITLE
indicate which certificate or key is missing during DownloadCerts

### ISSUE THREAD

**Issue by mdaniel** [kubernetes/kubeadm#1507]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

_Although that kind of depends on one's perspective, as we will soon see_

## Versions

**kubeadm version** (use `kubeadm version`):

`kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: `AWS`
- **OS** (e.g. from /etc/os-release): `NAME="Ubuntu" VERSION="18.04.2 LTS (Bionic Beaver)"`
- **Kernel** (e.g. `uname -a`): `Linux ip-10-0-2-238.us-west-2.compute.internal 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?

While attempting to join a new master, `kubeadm` emitted this error message and halted the join:

`error execution phase control-plane-prepare/download-certs: error downloading certs: couldn't find required certificate or key in Secret`

## What you expected to happen?

`error execution phase control-plane-prepare/download-certs: error downloading certs: couldn't find required certificate or key in Secret[name=external-etcd.crt][path=/etc/kubernetes/pki/apiserver-etcd-client.crt]`

(I patched `kubeadm` and rebuilt a local version to include that information, which is why I was able to finally get the new master to join):

```diff
diff --git a/cmd/kubeadm/app/phases/copycerts/copycerts.go b/cmd/kubeadm/app/phases/copycerts/copycerts.go
index 438a152dae..5c612c6ed8 100644
--- a/cmd/kubeadm/app/phases/copycerts/copycerts.go
+++ b/cmd/kubeadm/app/phases/copycerts/copycerts.go
@@ -231,7 +231,7 @@ func DownloadCerts(client clientset.Interface, cfg *kubeadmapi.InitConfiguration
        for certOrKeyName, certOrKeyPath := range certsToTransfer(cfg) {
                certOrKeyData, found := secretData[certOrKeyNameToSecretName(certOrKeyName)]
                if !found {
-                       return errors.New("couldn't find required certificate or key in Secret")
+                       return fmt.Errorf("couldn't find required certificate or key in Secret[name=%s][path=%s]", certOrKeyName, certOrKeyPath)
                }
                if len(certOrKeyData) == 0 {
                        klog.V(1).Infof("[download-certs] Not saving %q to disk, since it is empty in the %q Secret\n", certOrKeyName, kubeadmconstants.KubeadmCertsSecret)
```

This section of the issue is why this could be a "bug report" or "feature request," or even "close: wontfix" depending on one's perspective.

If it is not a security risk to emit the the `certOrKeyName` in the error message, then I think it's a bug for `kubeadm` to withhold the specifics from the user. Even if it _is_ a security risk, then perhaps something like `--insecure-copycerts-error-message` would allow truly stuck users to opt in to this reduction in security.

## How to reproduce it (as minimally and precisely as possible)?

On an existing master node:

```sh
# /usr/local/bin/kubeadm-v1.14.1 init phase upload-certs --experimental-upload-certs
```

Then on a new master node:

```sh
# /usr/local/bin/kubeadm-v1.14.1 join ${apiserver_name}:443 --token "$KUBEADM_JOIN_TOKEN"  --discovery-token-ca-cert-hash sha256:dfc4b5ada07a6b6a1ee29838eff86a89e36d20ad4521713cb029895bfff70c8e --experimental-control-plane --certificate-key "$KUBEADM_CERT_KEY"
```
and observe the opaque error message because `kubeadm` was looking for the external ETCD certs and not finding them.

Had `kubeadm` chosen to say _which_ key it failed to find, it would have focused my debugging efforts around the missing `--config` to the `upload-certs` phase, rather than trying to guess why `kubeadm` couldn't decrypt the certs.

**Comment by fabriziopandini** [comment]
@mdaniel thanks for the detailed report.
If you would like to send a PR with the patch above let me know that I will mark this issue as assigned to you (only use errors.Errorf instead of fmt.Errorf)

**Comment by fabriziopandini** [comment]
Thanks!
/lifecycle active
