### ISSUE TITLE
Replace the old master label kubeadm.alpha.kubernetes.io/role=master

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#151]
As part of moving to beta, we should replace the label used to mark the master (currently `kubeadm.alpha.kubernetes.io/role=master`) to something official that we can stand behind and say we actually support from now on.

This is being proposed in: https://github.com/kubernetes/kubernetes/pull/39112#issuecomment-278337996

cc @philips @jbeda @deads2k @roberthbailey @justinsb @mikedanese @smarterclayton

**Comment by deads2k** [comment]
I'd suggest choosing something consistent with https://github.com/kubernetes/community/issues/300

**Comment by luxas** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/41835
