### ISSUE TITLE
Kublet config upgrade with immutable infrastructure

### ISSUE THREAD

**Issue by yvespp** [kubernetes/kubeadm#1511]
## What keywords did you search in kubeadm issues before filing this one?
config upgrade, immutable, kubelet-config

## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.13.5 and v1.14.1

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.13.5 and v1.14.1
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.2

## What happened?
We use immutable infrastructure with kubeadm. This means that nodes have a fixed version of kubeadm and kubelet installed and packages can't be updated. To update a VM or Kubernetes the VM is replaced with a new one that has a newer versions of the packages installed.

I built a Kubernetes cluster in version v1.13.5 with 3 immutable CP (control plane) nodes, I joined the CP nodes using `--experimental-control-plane`.
I then build a new VM with the v1.14.1 packages installed. Trying to join this CP node to the existing CP fails because the ConfigMap "kubelet-config-1.14" doesn't exist. I found no clear way to create this ConfigMap and also update the kubeadm ConfigMap.
What I tried:
* `kubeadm upgrade apply --config /etc/kubernetes/kubeadm-conf.yaml --ignore-preflight-errors=StaticPodManifest` on the new node: doesn't work because there are no manifests on the new node. Running on an old node is not possible as it doesn’t have the new kubeadm version. Also updating the CP on that node makes no sense as it will be deleted anyway.
* `kubeadm init phase upload-config kubelet --config kubeadm.conf -v2` with a new kubeadm config: uploads a new config but then fails on this step because the node doesn't exist:  `I0416 21:13:11.692960    3654 patchnode.go:30] [patchnode] Uploading
the CRI Socket information "/var/run/dockershim.sock" to the Node API object "kind-control-plane2" as an annotation`. I could probably add an Init config so it would update an existing Node but this feels hacky and no update validation is run(?).
Is there another way to do this?

## What you expected to happen?
Ideally `kubeadm update` had away to skip the node specific parts (updating manifests etc.) and would only updated the config/ConfigMaps in the cluster. This way update validation, updating the existing kubeadm config and other stuff could also run. I also think cli ux wise it would be better fit than `kubeadm init phase upload-config`.
New Nodes joining the cluster would automatically get the new config, the existing ones stay on the old version. 

## How to reproduce it (as minimally and precisely as possible)?
In kinder (cool tool btw) create a cluster with two CP Node in version v1.4.0. On the first Node change the Kubernetes version in the kubeadm file to v1.13.5 and then run `kubeadm init` and ignore all preflight errors. On the second CP Node run the join CP command: `kubeadm join --experimental-control-plane …`

**Comment by timothysc** [comment]
By policy you have to upgrade the control plane 1st.

**Comment by yvespp** [comment]
@timothysc I'm trying to update the control plane first but in an immutable way.

Currently I would have to do this: 
- Copy new/updated kubeadm and kubeadm config to old control plane node
- Run `kubeadm upgrade` on old node
  - Kubeadm will upgrade the kubeadm and kubelet config in cluster and the old control plane components on the node
- Delete the old node (delete the vm)
- Join the new control plane node in the new version

What I would like:
- Copy admin kubeconfig to new control plane node (kubeadm and kubeadm config is already part of the vm image)
- Update the kubeadm and kubelet config in the cluster from the new control plane node
- Delete the old control plane node
- Join the new control plane node

For that I would be nice to have phases in `kubeadm upgrade` that only updates the in cluster config, certs etc. without modifying the node it is run on.

**Comment by mitchellmaler** [comment]
@timothysc I ran into this issue and have the same problem without a good solution. We try to limit the amount of SSH access that nodes have after they are provisioned and added to the cluster using cloud-init. What I am looking for is a way to upgrade the cluster and proxy configmap and create/upgrade the kubelet configmap without needing to ssh into a master node since it will be replaced anyways. Would be nice if there was a way to upgrade remotely using kubeapi since the nodes would be rebuilt and don't need directly upgraded.

**Comment by neolit123** [comment]
kubeadm doesn't have a clear story around immutable node upgrades in docs and best practices.

> For that I would be nice to have phases in kubeadm upgrade that only updates the in cluster config, certs etc. without modifying the node it is run on.

upgrade phases might solve that.

currently we have phases for `kubeadm upgrade node`, but not for `kubeadm upgrade apply`
its tracked here:
https://github.com/kubernetes/kubeadm/issues/1318
