### ISSUE TITLE
Join command error message suggests the use of a flag that does not exist

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubeadm#1513]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm join command error unsafeSkipCAVerification

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`): `v1.14.1`
- **Cloud provider or hardware configuration**: AWS EC2
- **OS** (e.g. from /etc/os-release): RHEL 7.6
- **Kernel** (e.g. `uname -a`):

## What happened?
I attempted to join a node without caCertHashes. The join command returned an error that suggested using an unknown flag: `--unsafeSkipCAVerification`

```
ec2-user@ip-172-31-46-205 ~]$ kubeadm join 172.31.46.19:6443 --token m2f82u.k0qdvkv2qtln898s
discovery.bootstrapToken: Invalid value: "": using token-based discovery without caCertHashes can be unsafe. Set unsafeSkipCAVerification to continue
[ec2-user@ip-172-31-46-205 ~]$ kubeadm join 172.31.46.19:6443 --token m2f82u.k0qdvkv2qtln898s --unsafeSkipCAVerification
Error: unknown flag: --unsafeSkipCAVerification
```

## What you expected to happen?
The join command should suggest the correct flag: `--discovery-token-unsafe-skip-ca-verification`

## How to reproduce it (as minimally and precisely as possible)?
Attempt to join a node using a token without providing the CA cert hashes.

**Comment by alexbrand** [comment]
I think what is happening here is that the suggestion printed by the join command is saying to set the `unsafeSkipCAVerification` option in the config file.

Perhaps the error message should be more specific about this. The message could also inform the user about the `--discovery-token-unsafe-skip-ca-verification` flag.

**Comment by yagonobre** [comment]
Thanks for reporting it @alexbrand 
/area ux
/lifecycle active

**Comment by SataQiu** [comment]
This issue has been waiting for a long time. 
Are you working on it @yagonobre ?
If you are busy, I think I can have a try.

**Comment by yagonobre** [comment]
Thanks @SataQiu, I was not working on it.
