### ISSUE TITLE
On node join, validate that the minimum server version is v1.6.0-alpha.1

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#152]
Since the Certificates API graduated to beta and k8s v1.5.x has the Certificates API at alpha, we can only support v1.6.0-alpha.1 as the server version for kubeadm at HEAD currently.

A constant `MinimumAPIServerJoinVersion` or similar should be made in `cmd/kubeadm/app/constants` and `checkAPIEndpoint` in `cmd/kubeadm/app/node/bootstrap.go` should be updated to only allow that minimum version.

Can @larryrensing and/or @wilkers-steve work on this?

**Comment by larryrensing** [comment]
I'll take care of this one

**Comment by luxas** [comment]
This is basically fixed in https://github.com/kubernetes/kubernetes/pull/38816; it makes sure the API Server supports v1beta1 of the Certificates API, which essentially is the same thing as the issue outlined above
