### ISSUE TITLE
dial tcp 172.28.62.68:10250: connect: no route to host

### ISSUE THREAD

**Issue by zhangxingdeppon** [kubernetes/kubeadm#1520]
## Versions
<pre><code>[root@D21117U04-62-64 ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:36:44Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
**kubeadm version** (use `kubeadm version`):
</code><pre>

<pre><code>[root@D21117U04-62-64 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
</code></pre>
## What happened?
dial tcp 172.28.62.68:10250: connect: no route to host
I have a problem about netwok.when I did  a command "kubectl  exec -it  pod_name sh "
it will heppened "dial tcp 172.28.62.68:10250: connect: no route to host"
for example:
<pre><code>[root@D21117U04-62-64 yaml]# kubectl run -it curl-test2 --image=radial/busyboxplus:curl  --overrides='{ "apiVersion": "apps/v1beta1", "spec": { "template": { "spec": { "nodeSelector": { "ip": "
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: error dialing backend: dial tcp 172.28.62.68:10250: connect: no route to host
Error from server: Get https://172.28.62.68:10250/containerLogs/default/curl-test2-57959969cc-vmzpw/curl-test2: dial tcp 172.28.62.68:10250: connect: no route to host
</code></pre>
I did try to resolve this problem,I kown my host have two network card，
one card configure ip network 172.28.*.*,other card is 172.29.*.*;
network 172.28.*.* ,and we have configured the stratege that 172.28.*.* can't connect to network  172.29.*.*  ;
so I have changed the kubelet‘s  listen address to 172.29.*.*
but kubectl  still connected  the  network  172.28.*.*

for example:
<pre><code>[root@D21117U04-62-64 yaml]# kubectl run -it curl-test  --image=radial/busyboxplus:curl  --overrides='{ "nodeSelector": { "ip": "test" } }' 
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: error dialing backend: dial tcp 172.28.62.68:10250: connect: no route to host'''
</code></pre>

## What you expected to happen?

I have no idea about it , i want to known why, could you help me resolve it ? 
 it's very important to me ,Tks

**Comment by neolit123** [comment]
hi, thank for the report, but this doesn't seem like a kubeadm problem.

> I have no idea about it , i want to known why, could you help me resolve it ?

the kubeadm team is relatively small and might not be able to respond to your question.
you might have better results if you post the question on stackoverflow or the #kubeadm slack channel.

**Comment by zhangxingdeppon** [comment]
> hi, thanks for the report, but this doesn't seem like a kubeadm problem.
> 
> > I have no idea about it , i want to known why, could you help me resolve it ?
> 
> the kubeadm team is relatively small and might not be able to respond to your question.
> you might have better results if you post the question on stackoverflow or the #kubeadm slack channel.

ok，thanks for you ,LuckyI have resloved it,Lol,it must be appointed “--node-ip=”

**Comment by neolit123** [comment]
than you for the response and confirming that it now works for you.

**Comment by harshita-chaudhary** [comment]
@zhangxingdeppon I'm facing the same issue. Could you please tell me how you resolved this?
Thanks in advance.

**Comment by liurd** [comment]
if firewalld enabled, it will also bring the issue.
