### ISSUE TITLE
Store the Static Pods as YAML files instead of JSON

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#153]
Right now, the Static Pods are stored as `.json` files in `/etc/kubernetes/manifests`.
I think we should store them instead as YAML as it's easier to read, more common etc.
Also when I mentioned that they are json files in the sig meeting I was asked why they aren't yaml files currently, which I think is a agreement with this issue.

And this is a thing we should do before going to beta.

**Comment by luxas** [comment]
@dmmcquay Is this something you can pick up?

**Comment by dmmcquay** [comment]
@luxas yes, you can assign it to me.
