### ISSUE TITLE
Switch to generating ECDSA keys

### ISSUE THREAD

**Issue by rojkov** [kubernetes/kubeadm#1535]
edit(neolit123)

#### v1beta4 tasks

- [x] add a field to ClusterConfiguration:
https://github.com/kubernetes/kubernetes/pull/120417

- [x] allow various ECDSA/RSA variations:
https://github.com/kubernetes/kubernetes/pull/123054

- [ ] add kinder e2e test (for latest only)?:
TO-BE-DECIDED, maybe we are OK with just unit tests?

~- [ ] remove the feature gate PublicKeysECDSA (same release as v1beta4 or one later max):~
should be done with the removal of v1beta3 !

-----

FEATURE REQUEST

To unify the type of certificates used across Kubernetes make kubeadm generate ECDSA keys and certificates instead of RSA ones during cluster initialization and key renewal.

## Motivation

As explained in [OpenSSL wiki][] the primary advantage of using Elliptic Curve based cryptography is reduced key size and hence speed.

In addition to that kubelet already generates self-signed server certificates of the ECDSA type and uses ECDSA client certificates when communicating with API servers. It would reduce complexity if the same defaults were used across Kubernetes components.

[OpenSSL wiki]: https://wiki.openssl.org/index.php/Elliptic_Curve_Cryptography

### Goals

- unconditionally generate ECDSA keys upon cluster initialization.

## Proposal

Since people feel more comfortable when there is a transition period it makes sense to introduce a configuration option first for the type of keys used in new clusters or the clusters undergoing upgrades.

The selected key type should be defined in `InitConfiguration` or optionally overridden with a command line option applicable to the `init` command and to the `certs` related subcommands.

The function `pkiutil.NewPrivateKey()` should accept `keyType` parameter of two possible values `ECDSA` and `RSA`. The actual value is passed from `InitConfiguration` by callers. Currently the function unconditionally generates RSA keys only.

The default value for the option is `RSA`.

It is OK to have certificates of mixed types in the same certificate chain thus after two or three releases the default value can be switched to `ECDSA`.

After the transition period is over the option can be removed completely and all new keys are going to be of the ECDSA type.

**Comment by fabriziopandini** [comment]
@rojkov is it possible to merge this issue with https://github.com/kubernetes/kubeadm/issues/984?

**Comment by rojkov** [comment]
@fabriziopandini I don't think it's needed as they are different issues: #984 is about kubeadm accepting pre-generated ECDSA certs (without kubeadm) and this issue is about kubeadm generating ECDSA certs itself.

**Comment by timothysc** [comment]
@rojkov - could you please attach your PRs to this issue and what else needs to get done here? 

/cc @kad

**Comment by neolit123** [comment]
xref https://github.com/kubernetes/kubernetes/pull/76390

**Comment by neolit123** [comment]
moving to melestone Next.

https://github.com/kubernetes/kubernetes/pull/76390
added support for user generated ECDSA.

this ticket tracks the generation of ECDSA by kubeadm.

> After the transition period is over the option can be removed completely and all new keys are going to be of the ECDSA type.

we probably should define when this transition is going to happen.

**Comment by anguslees** [comment]
ECDSA keys are *significantly* faster fwiw, particularly on arm32.  I could not enable TLS peering certs on my rPi2 cluster and have the health checks (TLS handshakes) complete in less than the etcd hard-coded connect timeout with RSA keys - ECDSA keys work fine.

**Comment by fabriziopandini** [comment]
@rojkov thanks for the feedback.
@neolit123 @timothysc we should start to consider if/how to make ECDSA became the kubeadm default

**Comment by neolit123** [comment]
@anguslees 
> ECDSA keys are significantly faster fwiw, particularly on arm32. I could not enable TLS peering certs on my rPi2 cluster and have the health checks (TLS handshakes) complete in less than the etcd hard-coded connect timeout with RSA keys - ECDSA keys work fine.

i think i've seen related issues before.
the workaround until now was patching the timeouts to be longer.

but isn't 15 seconds a bit too much even for rpi?

people were considering race conditions at some point on ARM...
also the kubeadm kubeconfig logic randomly panic-ed for a rpi2 certain user and that did not make any sense (possible compiler bugs).

rpi in general is not supported until we have e2e tests for it.

@fabriziopandini 

> we should start to consider if/how to make ECDSA became the kubeadm default

+1 if @rojkov can get back to this work.

**Comment by rojkov** [comment]
I might get back to this. Will update tomorrow or on this Wednesday.

**Comment by rojkov** [comment]
I need to finalize one my PR to Envoy's main repo and one more PR to the OpenSSL extension to Envoy first. They take all my time budget allowed for open source contributions. Then I can continue with ECDSA keys.

**Comment by neolit123** [comment]
thanks @rojkov

**Comment by rojkov** [comment]
Submitted https://github.com/kubernetes/kubernetes/pull/86953

**Comment by neolit123** [comment]
@rojkov 
during the kubeadm meeting today we discussed the alternative option to use feature gates instead of adding this as part of the API, but we didn't make a clear decision.

i'm personally in favor of adding this as part of the API, but it means it has to wait until we have enough new features for v1beta3. we might not be able to release v1beta3 because kubeadm is moving out of k/k and that's where most of the effort will be.

if you want to add this as part of kubeadm ASAP, then it has to be a future gate and only work on `init`. my problem with that is that the new cluster certs will be stuck to ECDSA.

ideally i wish we support renew paths that support transitioning old certs to ECDSA from RSA, or the other way around for people to opt-out of the feature gate.

**Comment by fabriziopandini** [comment]
I'm +1 for a feature gate now with some documentation about the scope of the current implementation (e.g only new clusters, no opt out, yes renewal)

In parallel, a KEP will help in figuring out all the user-stories (e.g opt-in/opt-out, mixed old/new certs)

**Comment by rojkov** [comment]
@neolit123 @fabriziopandini Thanks for your fast reply!

I'll rework the PR to have an `init` only feature gate for ECDSA and write a KEP for the rest of possible scenarios (or better the ones I can come up with).

**Comment by neolit123** [comment]
@rojkov thank you!

**Comment by stealthybox** [comment]
Thanks for working on this.

What's the rough order of operations to manually move a cluster from RSA to ECDSA.

I can guess that there are dependencies on certain flags in components and the communication between those components.  (kube-apiserver / kubelet / etcd / ....)

Is downtime required in some or all upgrade techniques? (multiple controlplane nodes?)

If we can document this with the gated feature, it will serve users and maybe point us toward a more automated behavior.

**Comment by rojkov** [comment]
@stealthybox It's safe to have keys of different types in a single certificate bundle or chain. I don't expect problems if to add the ECDSA feature gate to `ClusterConfiguration` of an existing cluster and then renew the keys. But it makes sense to test first :)

**Comment by neolit123** [comment]
we decided to not add this as a field in v1beta3, due to some uncertainties around the feature.
we should discuss this more.

**Comment by maximmasiutin** [comment]
I have generated keys and certificates with the secp256k1, run `rke`  version v1.2.8 today and got the following error:

```
FATA[0000] Failed to read certificates from dir [/home/max/cluster_certs]: failed to read certificate [kube-apiserver-requestheader-ca.pem]: x509: unsupported elliptic curve
```

`kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

Which of the curves are actually supported today?

**Comment by neolit123** [comment]
AFAIK, RKE does not use kubeadm.

**Comment by chendave** [comment]
This feature is still alpha, the original plan for this is making the ECDSA as the defaults, and deprecated the RSA which I think is breaking change as well.

> we decided to not add this as a field in v1beta3, due to some uncertainties around the feature.

not sure if we can add this to v1beta4, since I haven't done enough test around this, something we can do for v1beta4 is graduate this feature to beta with RSA still supported, properly, we need to create some e2e testcases for this to be beta.

@neolit123 @fabriziopandini @SataQiu @pacoxu and others, WDTY about this?

**Comment by neolit123** [comment]
my take:
i think we need to remove it from being a feature gate. FG implies ECDSA will be the default without opt out. instead it seems it can be a cluster level field. preferably without a CLI flag for kubeadm init/upgrade.

**Comment by chendave** [comment]
thanks @neolit123 !

I am +1 for the idea of cluster level filed instead of FG, so that this won't be a breaking change.

**Comment by neolit123** [comment]
> thanks @neolit123 !
> 
> I am +1 for the idea of cluster level field instead of a FG, so that this won't be a breaking change.

technically, it will be a breaking change as we will drop the alpha FG.

**Comment by neolit123** [comment]
PR that adds add v1beta4.ClusterConfiguration.EncryptionAlgorithm is up:
https://github.com/kubernetes/kubernetes/pull/120417

**Comment by neolit123** [comment]
> add kinder e2e test (for latest only)?:
TO-BE-DECIDED, maybe we are OK with just unit tests?

maybe so
