### ISSUE TITLE
Certificate renewal vs config changes

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1540]
As of today `kubeadm alpha certs renew` has an inconsistent behavior wrt to the usage of the kubeadm config

1. `kubeadm alpha certs renew` reads the current certificates as the authoritative source for certificates attributes
2. `kubeadm alpha certs renew --csr-only` uses the kubeadm config as the authoritative source for certificates attributes

Please note that 1. is used also during upgrades, and this creates another inconsistent behavior when executing upgrades with a modified config file, because e.g. all the changes affecting static pod manifests will be applied, while changes affecting certificates won't be applied.

As a consequence, in the short term it is necessary to document 
a) what is the recommended way to apply changes to the cluster (e.g. using phases)
b) what are the backsides of trying to execute config changes during upgrades

In the long term, inconsistent behaviors should be fixed, and way forward for upgrade vs change the cluster should be defined

NB. please note that changing authoritative sources for certificate renewal have pro and cons (e.g. override manual changes to the certificates) and there are also scenarios like external CA that requires special considerations.

/area security
/priority important-soon
/assing @fabriziopandini 
/assign @timothysc 
/kind bug
/kind documentation
/milestone v1.15

**Comment by neolit123** [comment]
moving to 1.16.

**Comment by fabriziopandini** [comment]
@neolit123 the part about certificate renewal is now consistent and documented, even if it still uses certificates as authoritative source for renewal. 

The part relative to change the cluster is now tracked in https://github.com/kubernetes/kubeadm/issues/1581

So I'm ok in closing this (eventually in future we should reconsider the part relative to the authoritative source in a separated PR)
