### ISSUE TITLE
Replace kubernetes-anywhere tests with kinder tests

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1543]
Kinder test is there, so finally it is possible to get rid of tests using kubernetes-anywhere (which is not maintained anymore)

Currently there are following tests using kubernetes-anywhere:

- [ ] ci-kubernetes-e2e-kubeadm-gce-1-11
- [ ] ci-kubernetes-e2e-kubeadm-gce-1-12
- [ ] ci-kubernetes-e2e-kubeadm-gce-1-13
- [ ] ci-kubernetes-e2e-kubeadm-gce-1-14
- [ ] ci-kubernetes-e2e-kubeadm-gce-master 
- [ ] ci-kubernetes-e2e-kubeadm-gce-upgrade-1-11-1-12
- [ ] ci-kubernetes-e2e-kubeadm-gce-upgrade-1-12-1-13 
- [ ] ci-kubernetes-e2e-kubeadm-gce-upgrade-1-13-1-14
- [ ] ci-kubernetes-e2e-kubeadm-gce-upgrade-stable-master
- [ ] ci-kubernetes-e2e-kubeadm-gce-1-11-on-1-12 
- [ ] ci-kubernetes-e2e-kubeadm-gce-1-12-on-1-13 
- [ ] ci-kubernetes-e2e-kubeadm-gce-1-13-on-1-14
- [ ] ci-kubernetes-e2e-kubeadm-gce-stable-on-master

The action plan is to implement a test replacement with kinder first, run both tests in parallel for some time, and then dismiss kubernetes-anywhere test as soon as we consider stable/reliable the new one

/priority important-soon
/area kubeadm
/area testing
/milestone v1.15
/assign
/lifecycle active

**Comment by fabriziopandini** [comment]
@neolit123 on slack
re: kubernetes-anywhere jobs. while we are soon to have replacements for everything, we can't remove all of them yet. only the upgrade ones.
the rest are present in the release-informing dashboard, so this requires sig-release/sig-testing discussion.

**Comment by fabriziopandini** [comment]
Current status about release informing is:
- gce-master is in sig-release-master-informing
- gce-1-14 is in sig-release-1.14-all
- gce-1-13 is in sig-release-1.13-all
- gce-1-12 is in sig-release-1.12-all
- gce-1-11 is missing from sig-release-1.11-all, this seems an error
- gce-upgrade-stable-master is in sig-release-master-informing
- gce-upgrade-1-13-1-14 is in sig-release-1.14-all
- gce-upgrade-1-12-1-13 is in sig-release-1.13-all
- gce-upgrade-1-11-1-12 is in sig-release-1.12-all
- gce-stable-on-master is in sig-release-master-informing
- gce-1-13-on-1-14 is in sig-release-1.14-all
- gce-1-12-on-1-13 is in sig-release-1.13-all
- gce-1-11-on-1-12  is missing from sig-release-1.12-all, this seems an error

**Comment by fabriziopandini** [comment]
About run frequency:
- gce jobs every 2h for master, every 12h for an older release
- gce-upgrade jobs every 6h for master, every 12h for an older release
- gce-x-on-y jobs every 4h for master, every 12h for an older release
- [kind jobs every 1h for master, every 4h for an older release]

**Comment by fabriziopandini** [comment]
About notifications:
- gce jobs (with the exception of 1.11) send notifications after failing for 24h
- gce-upgrade jobs do not send notification
- gce-x-on-y jobs, only for stable-on-master, send notifications after failing for 24h
-[kind jobs send notifications after failing for 24h]

**Comment by fabriziopandini** [comment]
wrap up: the proposal to be discussed next kubeadm office hours is:
- gce jobs are going to be deleted in favor of kubeadm-kind* jobs
- gce-upgrade jobs are going to be deleted in favor of kubeadm-kinder-upgrade* jobs
- gce-x-on-y jobs are going to be deleted in favor of kubeadm-kinder-x-on-y* jobs
- sig release dashboard will be updated accordingly, and misconfiguration fixed
- run frequency will be harmonized on every 2h for master, every 12h for an older releases
- notification will be harmonized and everything will send notifications after failing for 24h

cc @neolit123 @rosti @timothysc

**Comment by neolit123** [comment]
i think i went ahead of the office hours meeting and i've sent this PR that already merged:
https://github.com/kubernetes/test-infra/pull/12493

kubeadm-gce* is no longer present in release -informing and -all dashboards.
kinder jobs are now in place of skew and upgrade jobs.

the remaining tasks here are:
- remove kubeadm-gce* from both job definitions and testgrid dashboards.
- restructure our SIG dashboards as see fit.

**Comment by fabriziopandini** [comment]
After merging
https://github.com/kubernetes/test-infra/pull/12591
https://github.com/kubernetes/test-infra/pull/12592

/close
