### ISSUE TITLE
kubeadm init --dry-run attempts to create folders

### ISSUE THREAD

**Issue by hh** [kubernetes/kubeadm#1549]
## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.2.12+b5d9aa58e373b4", GitCommit:"b5d9aa58e373b4170f3218d561c5800a5ccd74a7", GitTreeState:"clean", BuildDate:"2019-04-30T18:02:08Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
Packet
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04 LTS
- **Kernel** (e.g. `uname -a`):
Linux ii.cncf.ci 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

```kubeadm init --dry-run``` tried to create a folder

## What you expected to happen?

To just print out what it would do.

## How to reproduce it (as minimally and precisely as possible)?

```kubeadm --dry-run```

```
couldn't create a temporary directory: failed to create directory "/etc/kubernetes/tmp": mkdir /etc/kubernetes: permission denied
```

**Comment by timothysc** [comment]
@hh I don't see a tempdir as a problem to assemble the details..

**Comment by chenzhiwei** [comment]
I can work on this.

**Comment by chenzhiwei** [comment]
@timothysc I changed the tmp dir from `/etc/kubernetes/tmp` to `/tmp/etc/kubernetes`, and run as non-root permission with following parameters:

```
kubeadm init --dry-run --kubernetes-version=v1.14.1 -v 10 --ignore-preflight-errors=IsPrivilegedUser,IsDockerSystemdCheck,SystemVerification,DirAvailable--var-lib-etcd,CRI
```

Output:

```
I0506 01:34:30.187317    7043 loader.go:359] Config loaded from file:  /tmp/etc/kubernetes/tmp/kubeadm-init-dryrun108133306/admin.conf
I0506 01:34:30.187938    7043 loader.go:359] Config loaded from file:  /tmp/etc/kubernetes/tmp/kubeadm-init-dryrun108133306/admin.conf

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /tmp/etc/kubernetes/tmp/kubeadm-init-dryrun108133306/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 10.0.2.15:6443 --token oswkaa.d6kxo5py1k9t2um7 \
    --discovery-token-ca-cert-hash sha256:9905019c1f6496b304ae8086773429f37bc5998ed30961cade8785a2438b57f7

vagrant@ubuntu:~$ ls /tmp/etc/kubernetes/tmp/kubeadm-init-dryrun108133306/
admin.conf                    apiserver-kubelet-client.key  ca.key                        etcd.yaml                     front-proxy-client.key        kubeadm-flags.env             scheduler.conf
apiserver-etcd-client.crt     apiserver.crt                 config.yaml                   front-proxy-ca.crt            kube-apiserver.yaml           kubelet.conf
apiserver-etcd-client.key     apiserver.key                 controller-manager.conf       front-proxy-ca.key            kube-controller-manager.yaml  sa.key
apiserver-kubelet-client.crt  ca.crt                        etcd/                         front-proxy-client.crt        kube-scheduler.yaml           sa.pub
```

**Comment by timothysc** [comment]
Closing this issue, b/c it's a security problem and doesn't affect 99% of folks.
