### ISSUE TITLE
Using --skip-phases=addon/coredns still creates kube-dns service

### ISSUE THREAD

**Issue by woopstar** [kubernetes/kubeadm#1557]
## Is this a BUG REPORT or FEATURE REQUEST?
**BUG REPORT**

If you skip the `addons/coredns` phase upon install, the `kube-dns` service is still added.

```
$ kubectl get svc -n kube-system
NAME                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
kube-dns               ClusterIP   10.233.0.10    <none>        53/UDP,53/TCP,9153/TCP   8m30s
kubernetes-dashboard   ClusterIP   10.233.60.15   <none>        443/TCP                  6m46s
```

## Versions

**kubeadm version** (use `kubeadm version`):
````
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yagonobre** [comment]
I can't reproduce it.
```
sudo kubeadm init --skip-phases addon/coredns

kubectl -n kube-system get svc
No resources found.
```

**Comment by SataQiu** [comment]
I agree with @yagonobre . I also can't reproduce this probelm.
No DNS pod running.
```
root@shida-VirtualBox:/tmp# kubectl get pod -n kube-system
NAME                                       READY   STATUS    RESTARTS   AGE
etcd-shida-virtualbox                      1/1     Running   0          3m19s
kube-apiserver-shida-virtualbox            1/1     Running   0          3m39s
kube-controller-manager-shida-virtualbox   1/1     Running   0          3m23s
kube-proxy-k7cmz                           1/1     Running   0          4m27s
kube-scheduler-shida-virtualbox            1/1     Running   0          3m40s
```

**Comment by RA489** [comment]
@woopstar Do you mind specifying os version you are using?

**Comment by woopstar** [comment]
> I agree with @yagonobre . I also can't reproduce this probelm.
> No DNS pod running.
> 
> ```
> root@shida-VirtualBox:/tmp# kubectl get pod -n kube-system
> NAME                                       READY   STATUS    RESTARTS   AGE
> etcd-shida-virtualbox                      1/1     Running   0          3m19s
> kube-apiserver-shida-virtualbox            1/1     Running   0          3m39s
> kube-controller-manager-shida-virtualbox   1/1     Running   0          3m23s
> kube-proxy-k7cmz                           1/1     Running   0          4m27s
> kube-scheduler-shida-virtualbox            1/1     Running   0          3m40s
> ```

It's not a pod, but an svc.

**Comment by woopstar** [comment]
> @woopstar Do you mind specifying os version you are using?

I tried on latest stable coreos. We have the issue at Kubespray and I seached our base code for a kube-dns svc but we don't have any. And we appli the skip phase when we init the master, yet we end up with the kube-dns svc.

**Comment by SataQiu** [comment]
@woopstar svc does not exist. :man_shrugging:

**Comment by woopstar** [comment]
> @woopstar svc does not exist. 🤷‍♂

I'll try investigate this further then. Thanks for checking with me

**Comment by RA489** [comment]
@woopstar  didnot got any service running
```
[root@localhost ~]# kubectl get svc -n kube-system
No resources found.

```

**Comment by yagonobre** [comment]
@woopstar did you have time to confirm if it not a bug?

**Comment by RA489** [comment]
@woopstar did your issue got resolved?

**Comment by woopstar** [comment]
Sorry for the delay. Was unable to look into it, but I will have time now.

I think the error might be a logic result in Kubernetes. I waiting for https://github.com/kubernetes-sigs/kubespray/pull/4867/files to get merged and see if that actually fixes the problem.

**Comment by woopstar** [comment]
Looks like this fixed the error. Doing a vagrant up after this PR got merged results in:

```
k8s-1 core # /opt/bin/kubectl get svc --all-namespaces
NAMESPACE     NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes             ClusterIP   10.233.0.1      <none>        443/TCP                  14m
kube-system   coredns                ClusterIP   10.233.0.3      <none>        53/UDP,53/TCP,9153/TCP   11m
```
