### ISSUE TITLE
Component Pack installation - Kubernetes failure nslookup: can't resolve 'kubernetes.default'

### ISSUE THREAD

**Issue by vtobias** [kubernetes/kubeadm#1558]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

 -> Checked but no case fit the scenario:
No results matched your search.
You could search all of GitHub or try an advanced search.

## What keywords did you search in kubeadm issues before filing this one?

Connections, Pink, Component pack

## Versions

kubeadm version

kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:36:44Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

cat /etc/os-release

NAME="Red Hat Enterprise Linux Server"

VERSION="7.6 (Maipo)"

ID="rhel"

ID_LIKE="fedora"

VARIANT="Server"

VARIANT_ID="server"

VERSION_ID="7.6"

PRETTY_NAME="Red Hat Enterprise Linux"

ANSI_COLOR="0;31"

CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"

HOME_URL="https://www.redhat.com/"

BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"

REDHAT_BUGZILLA_PRODUCT_VERSION=7.6

REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"

REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

uname -a

Linux vrt0874.bndes.net 3.10.0-957.5.1.el7.x86_64 #‌1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

kubeadm version

kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:36:44Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

cat /etc/os-release

NAME="Red Hat Enterprise Linux Server"

VERSION="7.6 (Maipo)"

ID="rhel"

ID_LIKE="fedora"

VARIANT="Server"

VARIANT_ID="server"

VERSION_ID="7.6"

PRETTY_NAME="Red Hat Enterprise Linux"

ANSI_COLOR="0;31"

CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"

HOME_URL="https://www.redhat.com/"

BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"

REDHAT_BUGZILLA_PRODUCT_VERSION=7.6

REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"

REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

uname -a

Linux vrt0878.bndes.net 3.10.0-957.5.1.el7.x86_64 #‌1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
**kubeadm version** (use `kubeadm version`):

## What happened?

Customer is trying to install IBM Connections Component PACK.
However Kubernet installation is failing with thiserror:

kubectl exec -ti busybox -- nslookup kubernetes.default

Server: 10.96.0.10

Address: 10.96.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer

root@vrt0874 ~]# for p in $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name); do kubectl logs --namespace=kube-system $p; done
.:53
CoreDNS-1.1.3
2019/03/17 00:17:15 [INFO] CoreDNS-1.1.3
linux/amd64, go1.10.1, b0fd575c
2019/03/17 00:17:15 [INFO] linux/amd64, go1.10.1, b0fd575c
2019/03/17 00:17:15 [INFO] plugin/reload: Running configuration MD5 = 2a066f12ec80aeb2b92740dd74c17138
2019/04/04 18:01:36 [ERROR] 2 kubernetes.default. AAAA: unreachable backend: read udp 172.20.0.90:33430->10.1.2.77:53: i/o timeout
2019/04/04 18:01:51 [ERROR] 2 kubernetes.default. AAAA: unreachable backend: read udp 172.20.0.90:57629->10.96.0.10:53: i/o timeout
2019/04/04 18:01:51 [ERROR] 2 kubernetes.default. AAAA: unreachable backend: read udp 172.20.0.90:59388->10.1.2.77:53: i/o timeout
2019/04/04 18:01:51 [ERROR] 2 kubernetes.default. AAAA: unreachable backend: read udp 172.20.0.90:37713->10.96.0.10:53: i/o timeout
2019/04/04 18:01:56 [ERROR] 2 kubernetes.default. A: unreachable backend: read udp 172.20.0.90:55567->10.96.0.10:53: i/o timeout
2019/04/04 18:02:01 [ERROR] 2 kubernetes.default. AAAA: unreachable backend: read udp 172.20.0.90:46157->10.96.0.10:53: i/o timeout
2019/04/04 18:02:01 [ERROR] 2 kubernetes.default. A: unreachable backend: read udp 172.20.0.90:57026->10.96.0.10:53: i/o timeout
2019/04/04 18:02:06 [ERROR] 2 kubernetes.default. AAAA: unreachable backend: read udp 172.20.0.90:43304->10.1.2.77:53: i/o timeout
2019/04/04 18:02:06 [ERROR] 2 kub

## What you expected to happen?

Desired output: Installed CONNECTIONS component pack  6.0.0.7

## How to reproduce it (as minimally and precisely as possible)?

There is no condensed steps, You must follow these steps:

https://www.ibm.com/support/knowledgecenter/en/SSYGQH_6.0.0/admin/install/cp_install_services_intro.html

## Anything else we need to know?

We applied the requested pre-install tasks:

https://www.ibm.com/support/knowledgecenter/SSYGQH_6.0.0/admin/install/cp_prereq_kubernetes_dns.html

We also applied this troubleshooting:

If you encounter a DNS problem, you must correct it.If the nslookup command fails, execute the following command on all Kubernetes nodes in your cluster (including all masters and worker nodes):

 

iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

 

Then repeat step 3 to verify that the DNS is now working correctly. If DNS problems persist, recreate the core-dns pods on the Kubernetes master by running the following command (in an HA deployment, execute this command on the primary Kubernetes master):

 

kubectl delete pod -n kube-system -l k8s-app=kube-dns

 

Remember that you must repeat step 3 to verify that the DNS is now working correctly.

https://www.ibm.com/support/knowledgecenter/en/SSYGQH_6.0.0/admin/install/cp_prereq_kubernetes_dns.html

 -> Output was:

root@vrt0874 ~]#‌ iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

[root@vrt0874 ~]#‌ kubectl delete pod -n kube-system -l k8s-app=kube-dns

pod "coredns-78fcdf6894-n7zzz" deleted

pod "coredns-78fcdf6894-s8sg7" deleted

[root@vrt0874 ~]#‌ iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

[root@vrt0874 ~]#‌ kubectl exec -ti busybox -- nslookup kubernetes.default

Server:  10.96.0.10

Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'kubernetes.default'

command terminated with exit code 1
------------------

 - However after this we still could not solve the problem.

**Comment by neolit123** [comment]
> kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", 

hi 1.11 is no longer supported.
if you are able to reproduce the problem with 1.12 or later please re-open the issue.
thanks!
