### ISSUE TITLE
Fail to create token when multi CRI sockets exist

### ISSUE THREAD

**Issue by jwang11** [kubernetes/kubeadm#1559]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.2.323+b3a73f761f5b67", GitCommit:"b3a73f761f5b67f783d40a8b89dce47c5a015909", GitTreeState:"clean", BuildDate:"2019-05-07T06:02:57Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"archive", BuildDate:"2019-04-15T07:32:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29250
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

- **Kernel** (e.g. `uname -a`):
Linux 5.0.13-751.native #1 SMP Sun May 5 14:14:30 UTC 2019 x86_64 GNU/Linux
- **Others**:

## What happened?
When I run "kubeadm token create --print-join-command", it show error as below
```
Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock
```
Actually, I have executed "kubeadm init --cri-socket=/var/run/crio/crio.sock" when setup cluster.

If I pass --cri-socket with "kubeadm token create --cri-socket=/var/run/crio/crio.sock", it show
```Error: unknown flag: --cri-socket```

## What you expected to happen?
show token created, maybe complete join command

## How to reproduce it (as minimally and precisely as possible)?
1) install crio plugin
2) kubeadm init --cri-socket=/var/run/crio/crio.sock
3) kubeadm token create --print-join-command

**Comment by SataQiu** [comment]
Thanks for reporting it @jwang11 
/kind bug
/assign

**Comment by SataQiu** [comment]
/lifecycle active
I will try to solve this problem.

**Comment by rosti** [comment]
Hi @jwang11 and thanks for filing this issue!
One possible work around for now is to use a dummy config file just for `kubeadm token create`:

```
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
```

then your command would look something like:
```
kubeadm token create --print-join-command --config=dummy-config.yaml
```

Haven't tested that myself, but it should work for now, until we get the actual fix in.
