### ISSUE TITLE
Passing --encryption-provider-config to kubeadm for the API server

### ISSUE THREAD

**Issue by danapoklepovich** [kubernetes/kubeadm#1562]
## Versions
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

K8s version: Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud provider or hardware configuration: Centos7 on premise cluster

## What happened?

I've successfully enabled secret encryption for Kubernetes https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/ 

As I'm leveraging kubeadm I have added a command flag to /etc/kubernetes/manifests/kube-apiserver.yaml like so 

```
spec:
  containers:
  - command:
    - kube-apiserver
    - --encryption-provider-config=/etc/kubernetes/enc.yaml
```

and I have also added the required volume mounts for the kube-apiserver container to access the config file. 

This all works. 

However I would like to be able to supply the encryption-provider flag to the kubeadm init cli command rather than manually editing the kube-apiserver yaml file as I can write that into a script. 

I would have thought this would be similar to the --apiserver-advertise-address flag for the kubeadm init command (which I am also using) but adding the flag fails the init.

Manually editing the file isn't really an option for me as my deployment needs to be automated and I can only use bash for my scripts. 

Is this a possible feature request? I'm happy to try and write a PR but I'm not a Go programmer.  If anyone else has found a way to avoid manually editing the apiserver config file I'd be delighted to know.

**Comment by fabriziopandini** [comment]
@danapoklepovich 
For advanced customizations (like setting API servers extra args or defining volume mounts) you can use the kubeadm config file. See https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file

**Comment by timothysc** [comment]
Until component config or --kustomize overrides exist we are stuck with the current work-around. 

closing.
