### ISSUE TITLE
Check certificate expiration

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1563]
A discussed in the kubeadm office hours April 24th, we are going to create a new command `kubeadm alpha certs check-expiration`

The proposed output for this command is 
```bash
CERTIFICATE                EXPIRES                  RESIDUAL VALIDITY   SET FOR AUTOMATIC RENEWAL
admin.conf                 May 13, 2020 10:00 UTC   364d, 23h59m27s     false
apiserver                  May 13, 2020 09:59 UTC   364d, 23h59m5s      false
apiserver-etcd-client      May 13, 2020 09:59 UTC   364d, 23h59m4s      false
apiserver-kubelet-client   May 13, 2020 09:59 UTC   364d, 23h59m5s      false
controller-manager.conf    May 13, 2020 10:00 UTC   364d, 23h59m27s     false
etcd-healthcheck-client    May 13, 2020 09:59 UTC   364d, 23h59m4s      false
etcd-peer                  May 13, 2020 09:59 UTC   364d, 23h59m4s      false
etcd-server                May 13, 2020 09:59 UTC   364d, 23h59m4s      false
front-proxy-client         May 13, 2020 09:59 UTC   364d, 23h59m5s      false
scheduler.conf             May 13, 2020 10:00 UTC   364d, 23h59m27s     false
```

As initial proposal `SET FOR AUTOMATIC RENEWAL` will be computed considering a renewal window of 180d before expiration.

This info will be used by `kubeadm upgrade apply` in order to decide if to automatically upgrade certs or not

opinions?
/assign @mauilion 
/assign @timothysc   
/assign @rosti 
/assign @neolit123

**Comment by neolit123** [comment]
i've commented on the PR. operators usually wait for cert expiration until the last moment, thus i proposed a threshold of 1 month.

**Comment by fabriziopandini** [comment]
ok, lets continue the discussion on the PR

**Comment by pytimer** [comment]
I am implement a service that every 6 hours it will check the certificates expire time in Kubernetes cluster, if `kubeadm` support the check, it good for me and i can use this command instead of my logic.

**Comment by ierwind** [comment]
would `kubeadm alpha certs check-expiration` work in kubernetes v1.11.3?

**Comment by pytimer** [comment]
AFAIK, this command not work in 1.11.3.

**Comment by neolit123** [comment]
the command was added in 1.15.
you might be able to use by downloading a new kubeadm binary and call it `kubeadm-1.15` then try running it. i have not guarantees it is going to work.

your best option is to keep up with kubernetes and upgrade more frequently.
