### ISSUE TITLE
kinder upgrade and ci/latest label

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1565]
recent kinder stable->master upgrade tests are red, because the 
https://storage.googleapis.com/kubernetes-release-dev/ci/latest.txt (ci/latest label)
now resolves to `v1.16.0-alpha.0.xxxx`.

https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-stable-master
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-stable-master/1128360807457886209/artifacts/task-06-upgrade-log.txt

```
kubeadm upgrade apply -f v1.16.0-alpha.0.3+23fb942ed7272b
...
[upgrade/apply] FATAL: failed to retrieve an etcd version for the target Kubernetes version: Unsupported or unknown Kubernetes version(1.16.0-alpha.0.3+23fb942ed7272b)
```

this causes `upgrade apply` to do a +2 version jump and it fails.

the reason for the 1.16.0 resolve is that the release-1.15 branch was just created, and master now has the v1.16 tag:
https://groups.google.com/forum/#!topic/kubernetes-dev/5OIjMo7Dz3o

this is a tricky moment...

the old upgrade tests did this which i don't think worked correctly:
https://github.com/kubernetes/test-infra/commit/f1092e8ff46bdfa52b4372459ac6d7a491d66d03#diff-89271433d25b3bbde631bcfdd4087d6eL126

`stable->master` in such situations is difficult to define and it does not make sense WRT to our upgrade support.

possible solutions:

A) continue defining the labels as `release/stable -> ci/latest`
however if `ci/latest` points to a +2 version fallback to `ci/latest-1.{stabelMinor + 1)`

this solution however has missing upgrade singnal for 1.15 -> 1.16 until 1.15 is stable.

B) have two jobs:
- `ci/latest-1.{stabelMinor + 1)` -> `ci/latest-1.{stabelMinor + 2)`
skip this job if `ci/latest-1.{stabelMinor + 2)` does not resolve.
- `release/stable -> ci/latest-1.{stabelMinor + 1)` 

this is an OK solution except that we have a job that is skipped and this is odd WRT to release-informing dashboards.

C) don't use "stable" for naming.
- instead of calling the current "latest upgrade job" stable->master job, call it "1.14->master".
- when the new release branch is created rename this job to 1.14->1.15.
- add a new job that does 1.15->master testing.

my vote goes for C.
@fabriziopandini WDYT?

**Comment by fabriziopandini** [comment]
@neolit123  test job upgrade-stable on master is back on track after https://github.com/kubernetes/kubernetes/pull/77931 was merged

However I propose to keep this open and rename jobs as suggested in C because it is simpler and clean (no matter if 1.14-1.15/1.15-master should be created after release cut, not after release branch created)

I propose also those changes 
- `1.14->master` to be changed in order to use `ci/latest-1.14  > ci/latest` instead of  `release/stable > ci/latest`
- to rename also `master-on-current` into `master-on-1.14` (and use `ci/latest-1.14` instead of `release/stable`)

**Comment by fabriziopandini** [comment]
Some notes:
- this is a cleanup that should land on after v1.15 is cut
- we want to replace stable with a proper release number
- old v1.11 jobs should be deleted and new v1.15 jobs should be created (new point)
- the version we are testing should be made consistent (see TODOs in  https://github.com/kubernetes/kubeadm/blob/master/kinder/ci/kubeadm-periodic.tests.md)
- https://github.com/kubernetes/kubeadm/blob/master/kinder/ci/kubeadm-periodic.tests.md page should be updated accordingly

**Comment by neolit123** [comment]
ack, changed priority and moved to 1.16 milestone.
