### ISSUE TITLE
Set kube-proxy bindaddress through kubeadm config file failed.

### ISSUE THREAD

**Issue by mzyfree** [kubernetes/kubeadm#1569]
[https://github.com/kubernetes/kubernetes/issues/77876](url)
k8s version: 1.14.0
Set kube-proxy bindaddress through kubeadm kubeproxyconfiguration parameters failed.Must Set the LocalAPIEndpoint to make the kubeproxy bindAddress set to [::].
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by SataQiu** [comment]
Thanks for reporting it @mzyfree 
Can you provide more detailed information? 
Such as the configuration files and commands you used.
So we can locate the problem faster!

**Comment by mzyfree** [comment]
@SataQiu 
**kubeadm config file:**

> apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: "v1.14.0"
controlPlaneEndpoint: "2000:1691:1111:2222:aaaa:bbbb:cccc:2000"
imageRepository: "matrix"
etcd:
external:
endpoints:
\- "http://[2000:1691:1111:2222:aaaa:bbbb:cccc:1180]:2379"
\- "http://[2000:1691:1111:2222:aaaa:bbbb:cccc:1181]:2379"
\- "http://[2000:1691:1111:2222:aaaa:bbbb:cccc:1182]:2379"
apiServer:
certSANs:
\- 2000:1691:1111:2222:aaaa:bbbb:cccc:2000
\- ::1
\- 2000:1691:1111:2222:aaaa:bbbb:cccc:1180
\- 2000:1691:1111:2222:aaaa:bbbb:cccc:1181
\- 2000:1691:1111:2222:aaaa:bbbb:cccc:1182
\- kubernetes
\- kubernetes.default
\- kubernetes.default.svc
\- kubernetes.default.svc.cluster
\- kubernetes.default.svc.cluster.local
extraArgs:
advertise-address: "2000:1691:1111:2222:aaaa:bbbb:cccc:2000"
token-auth-file: /etc/kubernetes/pki/token.csv
service-node-port-range: 1-65535
networking:
podSubnet: fd00:177:177::/112
serviceSubnet: fd00:10:96::/112
\-\-\-
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: "::"

**test command:**
kubeadm init --config=./kubeadm_config.yml --ignore-preflight-errors all
OR
 kubeadm init phase addon kube-proxy --config=./kubeadm_config.yml

**test command info:**
> [root@180 k8s]# kubeadm init phase addon kube-proxy --config=./kubeadm_config.yml -v 6
I0515 03:50:54.291684 59421 initconfiguration.go:186] loading configuration from "./kubeadm_config.yml"
I0515 03:50:54.295023 59421 initconfiguration.go:105] detected and using CRI socket: /var/run/dockershim.sock
I0515 03:50:54.295647 59421 interface.go:384] Looking for default routes with IPv4 addresses
I0515 03:50:54.295662 59421 interface.go:389] Default route transits interface "eth0"
I0515 03:50:54.296598 59421 interface.go:196] Interface eth0 is up
I0515 03:50:54.296733 59421 interface.go:244] Interface "eth0" has 5 addresses :[10.99.212.140/24 2000:1691:1111:2222:aaaa:bbbb:cccc:3000/128 2000:1691:1111:2222:aaaa:bbbb:cccc:2000/128 2000:1691:1111:2222:aaaa:bbbb:cccc:1180/64 fe80::4448:9f73:479f:af7a/64].
I0515 03:50:54.296769 59421 interface.go:211] Checking addr 10.99.212.140/24.
I0515 03:50:54.296781 59421 interface.go:218] IP found 10.99.212.140
I0515 03:50:54.296796 59421 interface.go:250] Found valid IPv4 address 10.99.212.140 for interface "eth0".
I0515 03:50:54.296806 59421 interface.go:395] Found active IP 10.99.212.140
I0515 03:50:54.297045 59421 feature_gate.go:226] feature gates: &{map[]}
I0515 03:50:54.299206 59421 loader.go:359] Config loaded from file /etc/kubernetes/admin.conf
I0515 03:50:54.320455 59421 round_trippers.go:438] POST https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/api/v1/namespaces/kube-system/serviceaccounts 409 Conflict in 19 milliseconds
I0515 03:50:54.326518 59421 round_trippers.go:438] POST https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/api/v1/namespaces/kube-system/configmaps 409 Conflict in 3 milliseconds
I0515 03:50:54.337540 59421 round_trippers.go:438] PUT https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy 200 OK in 10 milliseconds
I0515 03:50:54.357913 59421 round_trippers.go:438] POST https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/apis/apps/v1/namespaces/kube-system/daemonsets 409 Conflict in 4 milliseconds
I0515 03:50:54.362305 59421 round_trippers.go:438] PUT https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy 200 OK in 4 milliseconds
I0515 03:50:54.367381 59421 round_trippers.go:438] POST https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings 409 Conflict in 4 milliseconds
I0515 03:50:54.369524 59421 round_trippers.go:438] PUT https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/kubeadm:node-proxier 200 OK in 1 milliseconds
I0515 03:50:54.377739 59421 round_trippers.go:438] POST https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles 409 Conflict in 6 milliseconds
I0515 03:50:54.381402 59421 round_trippers.go:438] PUT https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/roles/kube-proxy 200 OK in 3 milliseconds
I0515 03:50:54.387662 59421 round_trippers.go:438] POST https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings 409 Conflict in 4 milliseconds
I0515 03:50:54.391570 59421 round_trippers.go:438] PUT https://[2000:1691:1111:2222:aaaa:bbbb:cccc:2000]:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings/kube-proxy 200 OK in 3 milliseconds
[addons] Applied essential addon: kube-proxy

**the code below leads this problem:**

> func SetInitDynamicDefaults(cfg *kubeadmapi.InitConfiguration) error {
> if err := SetBootstrapTokensDynamicDefaults(&cfg.BootstrapTokens); err != nil {
> return err
> }
> if err := SetNodeRegistrationDynamicDefaults(&cfg.NodeRegistration, true); err != nil {
> return err
> }
> if err := SetAPIEndpointDynamicDefaults(&cfg.LocalAPIEndpoint); err != nil {
> return err
> }
> return SetClusterDynamicDefaults(&cfg.ClusterConfiguration, cfg.LocalAPIEndpoint.AdvertiseAddress, cfg.LocalAPIEndpoint.BindPort)
> }

**the function caller:**

> func SetInitDynamicDefaults(cfg *kubeadmapi.InitConfiguration) error {
> if err := SetBootstrapTokensDynamicDefaults(&cfg.BootstrapTokens); err != nil {
> return err
> }
> if err := SetNodeRegistrationDynamicDefaults(&cfg.NodeRegistration, true); err != nil {
> return err
> }
> if err := SetAPIEndpointDynamicDefaults(&cfg.LocalAPIEndpoint); err != nil {
> return err
> }
> return SetClusterDynamicDefaults(&cfg.ClusterConfiguration, cfg.LocalAPIEndpoint.AdvertiseAddress, cfg.LocalAPIEndpoint.BindPort)
> }

**Comment by chenzhiwei** [comment]
I just confirmed with following configuration, the kube-proxy configmap still has bindAddress `0.0.0.0`:

```
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: "::"
```

**Comment by SataQiu** [comment]
Thank you for your detailed description. @mzyfree 
And thanks for your verification. @chenzhiwei 

This could be a bug, and I'll look into it.
/kind bug
/assign

**Comment by rosti** [comment]
@mzyfree @chenzhiwei can you fetch the config map of the provisioned kube-proxy?
This can be done with the following command:
```
kubectl get cm kube-proxy -n kube-system -o yaml
```

**Comment by chenzhiwei** [comment]
@rosti My environment was destroyed, but I checked the configmap before, the bindAddress is always `0.0.0.0`.

It is easy to reproduce this issue:

1. export the default config

    ```
    kubeadm config print init-defaults > kubeadm-init.conf
    ```

2. add kube-proxy config to default config file

    ```
    ---
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    bindAddress: "::"
    ```

3. remove kube-proxy ds and cm

3. re-add kube-proxy

**Comment by SataQiu** [comment]
Yes, I agree with @chenzhiwei .
I feel that the generation logic of kube-proxy ConfigMap is problematic.

**Comment by mzyfree** [comment]
@SataQiu 
Here is my cm of kube-proxy:

> [root@180 ~]# kubectl get cm kube-proxy -n kube-system -o yaml
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: '::'
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 5
    clusterCIDR: fd00:177:177::/112
    configSyncPeriod: 15m0s
    conntrack:
      max: null
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    healthzBindAddress: 0.0.0.0:10256
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      syncPeriod: 30s
    kind: KubeProxyConfiguration
    metricsBindAddress: 127.0.0.1:10249
    mode: ""
    nodePortAddresses: null
    oomScoreAdj: -999
    portRange: ""
    resourceContainer: /kube-proxy
    udpIdleTimeout: 250ms
    winkernel:
      enableDSR: false
      networkName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://[2000:1691:1111:2222:aaaa:bbbb:cccc:1188]:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  creationTimestamp: "2019-05-24T02:37:14Z"
  labels:
    app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "222"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-proxy
  uid: d6e670f5-7dcc-11e9-852b-0cda411d4a65

And here is my kubeadm config file,not use bindAddress in KubePorxyConfiguration but use localAPIEndpoint in InitConfiguration.Because after read code, i found kubeproxy bindaddress is hardly bound with localAPIEndpoint.
> apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: "v1.14.0"
controlPlaneEndpoint: "2000:1691:1111:2222:aaaa:bbbb:cccc:1188"
imageRepository: "matrix"
etcd:
 external:
  endpoints:
  \- "http://[2000:1691:1111:2222:aaaa:bbbb:cccc:1181]:2379"
  \- "http://[2000:1691:1111:2222:aaaa:bbbb:cccc:1182]:2379"
  \- "http://[2000:1691:1111:2222:aaaa:bbbb:cccc:1180]:2379"
apiServer:
  certSANs:
  \- 2000:1691:1111:2222:aaaa:bbbb:cccc:1188
  \- ::1
  \- 2000:1691:1111:2222:aaaa:bbbb:cccc:1181
  \- 2000:1691:1111:2222:aaaa:bbbb:cccc:1182
  \- 2000:1691:1111:2222:aaaa:bbbb:cccc:1180
  \- kubernetes
  \- kubernetes.default
  \- kubernetes.default.svc
  \- kubernetes.default.svc.cluster
  \- kubernetes.default.svc.cluster.local
  extraArgs:
    advertise-address: "2000:1691:1111:2222:aaaa:bbbb:cccc:1188"
    token-auth-file: /etc/kubernetes/pki/token.csv
    service-node-port-range: 1-65535
networking:
  podSubnet: fd00:177:177::/112
  serviceSubnet: fd00:10:96::/112
\-\-\-
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "2000:1691:1111:2222:aaaa:bbbb:cccc:1180"

**Comment by rosti** [comment]
@mzyfree That is how things are supposed to work. You should not be setting the kube-proxy bind address yourself. kubeadm is goind to default it for you, based on the local API endpoint advertise address.

**Comment by rosti** [comment]
> I just confirmed with following configuration, the kube-proxy configmap still has bindAddress `0.0.0.0`:
> 
> ```
> ---
> apiVersion: kubeproxy.config.k8s.io/v1alpha1
> kind: KubeProxyConfiguration
> bindAddress: "::"
> ```

That may as well happen due to your local API endpoint being and IPv4 address. This could easily happen if you have an IPv4 enabled on the machine and you don't fill in the setting in InitConfiguration or JoinConfiguration.

**Comment by mzyfree** [comment]
@rosti 
Yes, that's right.
I have both ipv4 and ipv6 address in my k8s enviroment and I prefer to use ipv6 address.
what makes me confused is the bindAddress in KubeProxyConfiguration not working and I must use local API endpoint in initConfiguration to make proxy bind to [::].
So what is the meaning of existence to the bindAddress config parameter in KubeProxyConfiguration for kubeadm if it strongly dependents on local API endpoint.
I think the configuration behavior in kubeadm should be the same as binary kube-proxy command start with config parameters.
For example, If I set bindAddress to [::] with KubeProxyConfiguration using kubeadm, after kubeadm init, the kube-proxy command in manifest should be like this:
kube-proxy --bind-address :: ...(other start parameter).

**Comment by mzyfree** [comment]
In the enviroment mixed with ipv4 and ipv6 address, if I doesn't set localAPIAddress in apiserver,then it 
 prefer to use ipv4 address as local API address.Then I cann't bind the kube-proxy to [::] anymore.
In this scenes, I think these two parameters should be decoupling.Beacuse kube-proxy command like iptables in ipv4 and ip6tables in ipv6 are highly dependenting on this bindAddress parameters.
But if you think current k8s does not support ip address mixed running,then making the parameters dependence is ok.

**Comment by rosti** [comment]
@mzyfree kubeadm deploys kube-proxy as a daemon set. This makes using any other value, than `0.0.0.0` or `::` for bind address useless (unless in the single node cluster case). That happens, because the same value is going to be propagated to all kube-proxy instances (one for each node) on the cluster.
Thus, it's best to just leave kubeadm decide whether to choose between `0.0.0.0` or `::` based on your local API bind address.

**Comment by mzyfree** [comment]
@rosti 
Of course the kube-proxy address must be 0.0.0.0 or [::] in cluster deployment env.
That's your choice to sacrifice user's config bindAddress ability to make sure the local apiserver and kube-proxy daemonset use same ip address protocol in kubeadm.
It's all right if you think kubeadm has the responsibility to make sure that kube-proxy bindaddress and the local API address must use the same ip address protocol.
