### ISSUE TITLE
Setting kubelet client certificate file path through kubeadm config file failed

### ISSUE THREAD

**Issue by prakashpc** [kubernetes/kubeadm#1572]
## What keywords did you search in kubeadm issues before filing this one?

kubelet client certificate , kubeadm config

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

Kubernetes version: 1.14

## What happened?

I want to set kubelet clientCA file path through command:
"kubeadm init --config=./kubeadm.yml --ignore-preflight-errors all"

Genereated kubelet config file(/var/lib/kubelet/config.yaml) always point to /etc/kubernetes/pki/ca.crt for clientCAFile option.
Kubelet process will fail unless i overide with --clientCAFile option through systemd for kubelet.

## What you expected to happen?

Kube config certificate file path should be same as user option.

## How to reproduce it (as minimally and precisely as possible)?

kubeadm init --config=./kubeadm.yml --ignore-preflight-errors all

My kubeadm config file:

apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
advertiseAddress: 192.168.64.57
bindPort: 8443
bootstrapTokens:

groups:
system:bootstrappers:kubeadm:default-node-token
ttl: 24h0m0s
usages:
signing
authentication
nodeRegistration:
criSocket: /var/run/dockershim.sock
name: knative
taints: []
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
certificatesDir: /var/lib/minikube/certs/
clusterName: kubernetes
controlPlaneEndpoint: 192.168.64.57:8443
dns:
type: CoreDNS
etcd:
local:
dataDir: /data/minikube
kubernetesVersion: v1.14.1
networking:
dnsDomain: cluster.local
podSubnet: ""
serviceSubnet: 10.96.0.0/12

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
anonymous:
enabled: false
webhook:
cacheTTL: 2m2s
enabled: true
x509:
clientCAFile: /var/lib/minikube/certs/ca.crt

**Comment by prakashpc** [comment]
This issues is moved from https://github.com/kubernetes/kubernetes/issues/78075

**Comment by neolit123** [comment]
the PR in flight needs discussion: https://github.com/kubernetes/kubernetes/pull/78079
i will try to bring it as a discussion topic for the next meeting.

**Comment by neolit123** [comment]
moving to 1.16 as we were not able to get a definitive answer to the questions in https://github.com/kubernetes/kubernetes/issues/78075

**Comment by neolit123** [comment]
> /etc/kubernetes/pki/ca.crt 

this is the cluster CA, not the kubelet client cert.
currently it's hardcoded in kubeadm and it's not supported to change the location.

**Comment by neolit123** [comment]
why are you not using the default place for ca.crt?

**Comment by neolit123** [comment]
closing due to no response and based on:
https://github.com/kubernetes/kubeadm/issues/1572#issuecomment-515090482

> certificatesDir: /var/lib/minikube/certs/

please log a ticket for minikube if needed
