### ISSUE TITLE
Can I specify a specific pod-network CIDR for flannel besides 10.244.0.0/16

### ISSUE THREAD

**Issue by dbwest** [kubernetes/kubeadm#1579]
## What keywords did you search in kubeadm issues before filing this one?

cidr, flannel

## Is this a BUG REPORT or FEATURE REQUEST?

I  am talking with a networking expert and we want to specify a CIDR. Should we use a different pod network besides flannel? can I do this with flannel? Am I tied to certain CIDRs? Is this a kubeadm thing? How can I plan out the networking space we're using and have more flexibility?

Thanks.

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by yagonobre** [comment]
Hi @dbwest, you can use `--pod-network-cidr` or kubeadm config. Take a look on https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

/close
