### ISSUE TITLE
token flag shouldn't had been removed

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubeadm#158]
We should provide a backwards compatible `--token` flag.

Also help text for the new `--discovery` flag is is not clear at all.

For `kubeadm init` I see this:
```
--discovery discovery    The discovery method kubeadm will use for connecting nodes to the master (default token://:@)
```
and it doesn't make sense to me, how am I supposed to interpret `token://:@`.

And for `kubeadm join` text help is even more obscure:
```
--discovery discovery    The discovery method kubeadm will use for connecting nodes to the master (default unknown)
```

**Comment by jbeda** [comment]
I agree -- this is super confusing.  Was there a design proposal that went through this?

**Comment by jbeda** [comment]
Also -- what is `token://`.  Is this a new URL scheme?  Does it talk about how to name and get a resource?  The `@` symbol is generally not used in URL schemes.

This is the type of thing that should go through wide design review at the SIG meetings, IMO.  (If it did and I missed it, I apologize -- but the criticisms still stand)

**Comment by jbeda** [comment]
See https://github.com/kubernetes/community/pull/381 for discussion around the UX for kubeadm around this area.

**Comment by luxas** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/38816
