### ISSUE TITLE
RFE: change cluster config as day 2 operation 

### ISSUE THREAD

**Issue by DanyC97** [kubernetes/kubeadm#1581]
### "change the cluster" is now tracked in:
https://github.com/kubernetes/kubeadm/issues/970

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

## Feature description

Following a deployment a K8s cluster using `kubeadm` on a cloud and/or on-prem environement, i'd like to be able to change the default values for K8s core components (scheduler, api, kube-prox, controller, kubelet) as well as addons like coreDNS without having to scale up/ add a new control plane node.

On slack we had a very [useful conversation](https://kubernetes.slack.com/archives/C2P1JHS2E/p1559074749049200) and with help from @fabriziopandini we found out that there is already a discussion going on - see [here](https://docs.google.com/presentation/d/15wuKEReLDP9JSLubVn96c4TNja-OkLeaQVDA13N_kQo/edit#slide=id.g4b71772736_0_1).

While i understand that maybe day 2 operation might be covered by cluster-api i think we should definitely have the option on kubeadm (as standalone) just because a lot of folks already started using kubeadm while cluster-api is not ready for consumption and missing this feature does cause a bad experience for operators

**Comment by DanyC97** [comment]
so here are some use cases i do see

@anguslees maybe you want to chime in and add your thoughts / use cases ?

* User wants to modify K8s core components flags and perform a "reload" w/o having to "replace" (scale up) the control plane node
* User wants to modify the cluster addon installed by kubeadm and perform a "reload" 

@neolit123 i've deliberately avoided providing specific _flags_  as is very hard to know what folks wants to change in a prod env. As such my view is that all flags should be allowed to be changed.

**Comment by neolit123** [comment]
@fabriziopandini 
this issue can be reused for the 1.16 "change the cluster" / reconf ideas.

**Comment by neolit123** [comment]
@fabriziopandini i've changed the title and we can use this ticket as the tracking issue for "change the cluster". we can update the OP with user stories, pending PRs and KEP links.

in terms of KEPs the deadline passed, so this would need an exception (deadline for exceptions is the 19th of Aug).

please move the milestone to 1.17 if see fit.

**Comment by fabriziopandini** [comment]
@neolit123 
IMO there are several tickets tracking slightly different variations of the same topic, which is changing the configuration of a running cluster. My proposal is to close this and conflate everything under https://github.com/kubernetes/kubeadm/issues/1698

**Comment by neolit123** [comment]
@fabriziopandini 
i think before we do that the operator idea needs a quick discussion in terms of it's architecture.
with the original "change the cluster" we planned calling kubeadm commands on each node which is safe, while the operator is something that will be topology aware and have super powers.

**Comment by neolit123** [comment]
closing in favor of:
https://github.com/kubernetes/kubeadm/issues/970

(it links to this issue for example user story)
