### ISSUE TITLE
kubelet-config-x.y ConfigMap logic improvements

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1582]
tracking issue in k/e + KEP: https://github.com/kubernetes/enhancements/issues/2915

1.23 Alpha:
- [x] deprecate the old format and introduce the new one controlled by UnversionedKubeletConfigMap:
https://github.com/kubernetes/kubernetes/pull/105741
- [x] add e2e tests in k/kubeadm:
https://github.com/kubernetes/kubeadm/pull/2601

1.24 Beta:
- [x] update KEP:
https://github.com/kubernetes/enhancements/pull/3120
- [x] flip the FG to enabled and graduate it to Beta, update the appropriate Beta TODOs introduced in the [original PR](https://github.com/kubernetes/kubernetes/pull/105741):
https://github.com/kubernetes/kubernetes/pull/108027
- [x] other k/k fixes:
https://github.com/kubernetes/kubernetes/pull/108336
https://github.com/kubernetes/kubernetes/pull/108128
https://github.com/kubernetes/kubernetes/pull/108127
- [x] cleanup k/kubeadm / update e2e tests:
https://github.com/kubernetes/kubeadm/pull/2654
- [x] docs: cleanup any kubelet-config-x.yy instances in at k/website
https://github.com/kubernetes/website/pull/31687

1.25 GA:
- [x] update KEP to GA:
https://github.com/kubernetes/enhancements/pull/3316
- [x] remove logic related to the feature gate and lock it to true. update the appropriate GA TODOs introduced in the [original PR](https://github.com/kubernetes/kubernetes/pull/105741):
https://github.com/kubernetes/kubernetes/pull/110327
https://github.com/kubernetes/kubernetes/pull/111146
- [x] remove e2e tests in k/kubeadm as the default e2e tests will exercise this
https://github.com/kubernetes/test-infra/pull/26461
https://github.com/kubernetes/kubeadm/pull/2702
- [x] k/website docs (update kubeadm-init page FG section)
https://github.com/kubernetes/website/pull/34159

1.26 post-GA:
- [x] remove the feature gate
https://github.com/kubernetes/kubernetes/pull/113448

-------------
EDIT: original issue description below

when a control-plane node is created by `init` using `kubernetesVersion: X.Y`, kubeadm will create a "versioned" ConfigMap called `kubelet-config-X.Y`.

when a worker node joins the cluster, it uses the version of the local kubelet to fetch this ConfigMap, but if the version of the local kubelet differs from the control-plane version (X.Y) used to originally create the CM, the join process will just fail.

both `init` and `upgrade` use the version of the control-plane to manage this ConfigMap,
so it makes *some* sense for the `join` process to use the version of the control-plane as well.
but this raises the question whether this internal config stored in the CM will be compatible with the local kubelet.

however we have a version skew topic to discuss here as well.
Kubernetes itself supports X-1 nodes joining a X cluster, but kubeadm does not.

in our documentation we have no official mentions if e.g a kubeadm 1.13 and a kubelet 1.13 worker node can join a cluster with a CP that is 1.14:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#version-skew-policy

**Comment by SataQiu** [comment]
Maybe we can get the cluster version through `kubeadm-config` ConfigMap when joining new work node.

```sh
# kubectl describe cm kubeadm-config -n kube-system
Name:         kubeadm-config
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
ClusterConfiguration:
----
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta1
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: ""
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12
scheduler: {}

ClusterStatus:
----
apiEndpoints:
  test-01:
    advertiseAddress: 192.168.137.139
    bindPort: 6443
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterStatus

Events:  <none>
```

The `ClusterConfiguration` contains `kubernetesVersion: v1.13.0`.

**Comment by neolit123** [comment]
@SataQiu 
the PR you sent is something we've discussed yesterday - use `kubernetesVersion`.
so maybe we can merge that as a start in 1.16.

but the issue has deeper roots and we possibly need to discuss all the implications here.
e.g. versioning the kubelet-config CM, the usage of internal types and the component skew as a whole.

**Comment by rosti** [comment]
kubelet's component config is a versioned API. It is at beta level now and I don't expect catastrophic incompatibility issues between a couple of consecutive kubelet versions, especially on join.
So I am all in for having equivalent behavior between the different kubeadm sub-commands.

**Comment by xlgao-zju** [comment]
@neolit123  I am think about after user change the config in cm kubelet-config-X.Y, is there anyway to keep the change and put the change into cm kubelet-config-X.Y+1, when he to upgrade his cluster.

**Comment by neolit123** [comment]
^ cc @rosti 

if the user creates `kubelet-config-X.Y+1` in advance before upgrade, kubeadm will just fail, AFAIK.
if they create `kubelet-config-X.Y+1` after upgrade it will not be used.

also, as far as i know about the latest state of component config, kubeadm would not be able to automatically preserve upgrades if kubeletconfiguration changes to e.g. v1beta2, so the users will have to up-convert manually.

**Comment by rosti** [comment]
@xlgao-zju 
> @neolit123 I am think about after user change the config in cm kubelet-config-X.Y, is there anyway to keep the change and put the change into cm kubelet-config-X.Y+1, when he to upgrade his cluster.

As long as there is no kubelet config API version change involved (e.g. `v1beta1` to say `v1beta2`), this should be done automatically by kubeadm. There's no need to manually change the kubelet-config-X.Y+1 CM. Your changes should be there.

If a version change is required, you should create kubelet config in the new format and pass it to `kubeadm upgrade apply` with the `--config` option in a file.

**Comment by xlgao-zju** [comment]
thanks @neolit123 @rosti 

> if kubeletconfiguration changes to e.g. v1beta2, so the users will have to up-convert manually.

will we support this convert in kubeadm (and maybe keep the changes user made)? so that `kubeadm upgrade` can work more smoothly with the pipelines.

**Comment by neolit123** [comment]
only if the kubelet exposes a way to upconvert from it's CLI e.g. `kubelet --convert`

**Comment by xlgao-zju** [comment]
@neolit123 I see... kubelet config convert is out of kubeadm scope. we will not have command like `kubeadm config migration` to migrate the kubelet config.

**Comment by neolit123** [comment]
considering writing a short KEP for this for 1.23, if there is enough time.
looks like enhancements freeze for 1.23 is 9th of Sept.

rough plan:
- deprecate the kubelet-config-x.y CM naming in 1.23.
- introduce a kubelet-config CM in 1.23.
- maintain both during the deprecation period.
- remove usage of the kubelet-config-x.y CM naming after a GA deprecation period (3 releases / 1 year).
-

**Comment by pacoxu** [comment]
A question is frequently asked by our customers if their custom configs can be saved after upgrading the cluster.
/cc 
The new solution seems to improve the experience.

**Comment by pacoxu** [comment]
For beta in 1.24, is ` cleanup any kubelet-config-x.yy instances in kubeadm` too aggressive?
In my mind, the cleanup should happen when the feature is GA. Or users cannot roll back easily.

**Comment by neolit123** [comment]
> For beta in 1.24, is cleanup any kubelet-config-x.yy instances in kubeadm too aggressive?
In my mind, the cleanup should happen when the feature is GA. Or users cannot roll back easily.

i think i mean clearing docs / code comments.
the code path for supporting the x.yy variant will still be supported.

**Comment by neolit123** [comment]
looks like https://github.com/kubernetes/kubernetes/pull/108027 broke https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest-on-1-23

that is a skew test.
maybe we need to one day make the k/k -> /test/e2e_kubeadm suite match the kubeadm version and not the k8s version.
if it matches the k8s version it also means it must support the kubeadm skew of k8s N and N-1.

the fix here is to make [test/e2e_kubeadm/kubelet_config_test.go](https://github.com/kubernetes/kubernetes/pull/108027/files#diff-2c2f807aa2fa4e8532b93c64fdbd537bc80b85d0fc0547103b3a5e25a0532070) tollerate both the old and new object names in the 1.23 branch of k/k.

i will send a PR later.

**Comment by pacoxu** [comment]
The CI is green again.

v1.24 tasks are finished and the milestone can move to 1.25.

**Comment by neolit123** [comment]
the feature gate was removed for 1.26. this is complete.
