### ISSUE TITLE
Create a kubeadm logo

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1588]
@dankohn offered CNCF help (in https://github.com/cncf/k8s-conformance/pull/592) with creating a kubeadm logo. That's awesome!

@alexcontini will create and post the logos here for the community to vote on.
Many thanks in beforehand :clap: :rocket: :smile:!

cc @timothysc @justinsb

**Comment by dankohn** [comment]
This group first needs to suggest several bullet points of ideas for a logo. I presume you'll want it to look different from the other installers in the project: https://landscape.cncf.io/category=certified-kubernetes-installer&format=card-mode&grouping=category&organization=cloud-native-computing-foundation-cncf

**Comment by luxas** [comment]
Ok, we'll discuss that during next week's SIG meeting on Tuesday.
FWIW we're not in a rush.

**Comment by neolit123** [comment]
created a google doc with some ideas:
https://docs.google.com/document/d/1oAzGFaUPdZSDwsFsSzK1WMy8rfUoj6GE2JlN3Yv02G0/edit

quite empty ATM.

**Comment by neolit123** [comment]
the google doc for ideas collected 5, thus far.

**Comment by alexcontini** [comment]
Hi! I have attached a board of some rough logo concepts. I tried to incorporate all the suggestions but let me know if this isn't what you were thinking.

I am not sure if I should email instead of posting here but I thought I would attach here first -

[kubeadm_logo_v1.pdf](https://github.com/kubernetes/kubeadm/files/3283170/kubeadm_logo_v1.pdf)

**Comment by neolit123** [comment]
awesome, thanks a lot @alexcontini !

i'm going to create a poll so that people can vote on their favorite design and we can possibly bikeshed on the best votes during the next kubeadm office hours meeting (wednesday - 20th).

these look great! :tada: :tada: :tada:

**Comment by neolit123** [comment]
poll link
https://forms.gle/HqL4FJU2SbC8yUmb7

**Comment by luxas** [comment]
Hi all, the community has voted, and the winner is option 2 :tada: :rocket: 
The three top votes:
 - Option 2: 17.4% (67 votes)
 - Option 17: 12.4%
 - Option 9: 10.6%

![kubeadm-logos](https://user-images.githubusercontent.com/5442475/59677283-2451a180-91d2-11e9-958d-5a9fc4ab3ff5.png)

The total amount of votes during this week was 386, so I'd argue that we have critical mass.

**Comment by luxas** [comment]
@alexcontini Can you please send a PR to this repo with Option 2 files in a new folder called simply `logo`? Thank you again :clap:

**Comment by tovbinm** [comment]
Nice looking logos! I would go with 17 or some modification of 18.

We also need one for TransmogrifAI library - https://github.com/salesforce/TransmogrifAI

@dankohn interested? :wink:

**Comment by luxas** [comment]
> Nice looking logos! I would go with 17 or some modification of 18.

As reported above, this poll is now closed. It had been up for a week, got 380+ votes, and the announced result is Option 2.

Also see: https://kubernetes.io/blog/2019/06/19/kubernetes-1-15-release-announcement/

> @dankohn interested?

This does not belong to this thread.
Please handle this discussion (if applicable) in some other thread.

**Comment by dankohn** [comment]
Please review https://github.com/cncf/landscape/pull/1283

**Comment by neolit123** [comment]
this is complete now, thanks everyone.
