### ISSUE TITLE
reset command does not make a node quitting from a cluster

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubeadm#159]
i have a kubeadm bootstrapped cluster having one master and one node.
when i run `kubeadm reset` on the node, the reset command finished successfully. but after then, i run `kubectl get nodes` on the master, i can see this node still there with status `NotReady`

i expect that node not listed in `kubectl get nodes`'s output

kubeadm : v1.6.0-alpha.0.2074+a092d8e0f95f52
kubernetes:
>Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by GheRivero** [comment]
I can confirm this issue. Although the `kubeadm reset` command finished successfully, the log indicated that something went wrong:

root@node:/home/stack# ./kubeadm reset
[preflight] Running pre-flight checks
[reset] Draining node: "node"
[reset] Failed to cleanup node: [failed to drain node "node": exit status 1]

Which match exactly the problem described here. Will look into it..

**Comment by GheRivero** [comment]
Fixed in:kubernetes/kubernetes#41345

**Comment by luxas** [comment]
@GheRivero Yes, it is, thanks for the ping. I just forgot to close this issue :)

**Comment by GheRivero** [comment]
This issue is not completely solved...

**Comment by liggitt** [comment]
I would expect a cluster admin to drain a node. I don't think nodes should be able to go inspect all the resources that result in pods
