### ISSUE TITLE
have e2e jobs that use docker once we move kinder to latest kind

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1592]
upstream kind has moved to crictl and containerd on the k8s nodes it creates.
given we are using kind/kinder for all tests we need to be able to test docker on k8s nodes too.

currently kinder is not using the latest kind, but once it does we need to think of having docker jobs.

**Comment by neolit123** [comment]
@fabriziopandini BTW, currently the kubeadm-kind jobs are pinned to kind 0.2.0 which uses docker, due to HA problems. the bump to e.g. 0.4.0 might happen post 1.16.

**Comment by fabriziopandini** [comment]
@neolit123 agree; the change in kinder will be invasive, so I'm 💯 ok with waiting post release

**Comment by fabriziopandini** [comment]
This was implemented with https://github.com/kubernetes/kubeadm/pull/1660
/close
