### ISSUE TITLE
kinder jobs as PR and release blocking

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1599]
Tracking issue for a couple items moved from:
https://github.com/kubernetes/kubeadm/issues/1290

- [ ] currently kinder jobs are not release blocking
  - we have kinder jobs in `master-informing` and `x.yy-all` dashboards, but not in the `*-blocking` dashboards
https://k8s-testgrid.appspot.com/sig-release-master-informing
https://k8s-testgrid.appspot.com/sig-release-1.14-all

  - promoting kind(er) jobs to release blocking needs by-in by sig-release. but also our signal should be more stable and well maintained.

- [x] promote kind(er) jobs to PR blocking (pre-submits)
  - RESOLVED: kind jobs are already PR blocking for k/k. kinder jobs will be PR blocking for k/kubeadm once kubeadm moves here.
  - currently there is only a  kind based pre-submit job that can be called with `/test pull-kubernetes-e2e-kind` on k/k PRs. see `presubmits` in this file https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm-kind.yaml
  - needs by-in by sig-testing

**Comment by tpepper** [comment]
Is there anything remaining to be done on this?  I see release-master-blocking on testgrid has KinD, there's config/jobs/kubernetes-sigs/kind/kind-presubmits.yaml presubmits.

**Comment by neolit123** [comment]
there are no e.g. kinder upgrade jobs in release blocking.
i think both points need some work still.

**Comment by neolit123** [comment]
> promote kind(er) jobs to PR blocking (pre-submits)

kind is already PR blocking, but this is unlikely to happen for kinder jobs for k/k.
once kubeadm moves k/kubeadm will have them here though.

i will mark this item as resolved with a comment.

> currently kind(er) jobs are not release blocking

kinder jobs are not release blocking yet.
they are pretty stable and well maintained at this point. we are resolving issues as fast as we can.

**Comment by tpepper** [comment]
Discussed today in SIG Release meeting and consensus was reached to continue with these jobs as release informing until the underlying docker copy flake is understood (and hopefully fixed).

Rational for this includes:
 * while the test meets criteria to move to blocking, SIG Cluster Lifecycle resources are limited when it comes to truly root cause and fix the issue, so most likely outcomes of CI Signal folks reporting flakes will just be minimal triage to recognize the basic flake pattern and accept it as a flake.  Ie: not block a release until flake is fixed.
 * CI Signal folks do treat informing the same as blocking from a triage perspective (ie: they do not ignore issues there), we're not loosing any signal to the release decision process.

**Comment by fabriziopandini** [comment]
@tpepper @neolit123 I can help in getting rid of flakes (most of the work should be completed now)

**Comment by neolit123** [comment]
ack, i should be able to find more time for debugging this too.

**Comment by neolit123** [comment]
/remove-lifecycle stale

the jobs are currenetly quite flaky due to GCE / prow infra problems, so if we decide to move them to release-blocking we definitely have to increase the priority of the jobs so that they get more resources.

**Comment by hasheddan** [comment]
@neolit123 is this issue being wrapped up blocked by the move to k/kubeadm? If so, should we re-scope or consider it resolved for the time-being?

**Comment by neolit123** [comment]
the kubeadm/kinder jobs can flake due to resource limits, which has prevented us to promoting them to release blocking.

if SIG testing give their approval for moving the current "kinder" release informing jobs to the a designated cluster with guaranteed resources.
cc @spiffxp @BenTheElder
(also please specify what `cluster: ...` value we should set?)

then perhaps SIG release would agree to graduate them to release-blocking:
cc @justaugustus @saschagrunert 

current jobs are here - kubeadm-kinder*
https://k8s-testgrid.appspot.com/sig-release-1.20-informing

**Comment by xmudrii** [comment]
As discussed at the SIG Release meeting today (4/6), there's still some work needed to define the criteria and policy for promoting jobs to the release-blocking.

**Comment by neolit123** [comment]
closing for the time being.

the jobs are less flaky nowadays:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm

but there has not been clear benefits for us to maintain these as release-blocking vs release-informing. we might promote them out of band in the future.
