### ISSUE TITLE
upgrade the default etcd version for kubeadm to 3.0.13

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#16]
_From @luxas on October 27, 2016 20:16_

We want to default to etcd3 in etcd2 mode for kubeadm now I think, and eventually default to etcd3 in etcd3 mode as well (I suppose that will be the default for v1.5?)

I don't think we have to deal with migration and upgrades from etcd2 to etcd3, as we're in alpha.
We can just say: create a new cluster.

Of course, when we're in beta, etc. we can't do that, but I think it's best to "fully support" etcd3 and higher when we're that far.

WDYT?
@kubernetes/sig-cluster-lifecycle @wojtek-t @lavalamp 

_Copied from original issue: kubernetes/kubernetes#35723_

**Comment by mikedanese** [comment]
_From @errordeveloper on October 28, 2016 8:6_

I don't know enough about the level of support for v3. I wouldn't rush this
just yet.

**Comment by mikedanese** [comment]
_From @dgoodwin on October 28, 2016 11:5_

This is our plan with OpenShift, I would say lets go for it.

**Comment by mikedanese** [comment]
_From @roberthbailey on October 28, 2016 15:6_

I think that @mml is hoping to switch GCE/GKE over to etcd3 in the 1.5 timeframe as well.

**Comment by mikedanese** [comment]
_From @wojtek-t on October 28, 2016 17:46_

We are still targetting 1.4.x release to switch to etcd3 (unless we find some problems during final testing).
So yes, switching kubeadm should be ok.

**Comment by mikedanese** [comment]
_From @xiang90 on October 28, 2016 18:1_

@errordeveloper 

etcd3 is well supported. We (etcd team + k8s team) are working hard on both correctness testing for migration and scalability testing for our 1.5 goals.

**Comment by mikedanese** [comment]
_From @timothysc on October 31, 2016 16:26_

> I don't think we have to deal with migration and upgrades from etcd2 to etcd3, as we're in alpha. 

do we support any upgrade strategy yet in kubeadm?

**Comment by mikedanese** [comment]
_From @luxas on October 31, 2016 17:22_

Nope @timothysc, but I talked to @errordeveloper and @lukemarsden about it; not sure if a doc has been written about that...

Anyway, my motivation is that we should use etcd3 by default for all kubeadm clusters now to avoid having to upgrade when turning to beta at some point

@wojtek-t When you've pushed 3.0.13, ping me so I can make the change in kubeadm

**Comment by luxas** [comment]
PR here: https://github.com/kubernetes/kubernetes/pull/35921

**Comment by luxas** [comment]
This is now fixed, given that the PR is merged.
