### ISSUE TITLE
There should be a way to avoid printing bootstrap token

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubeadm#160]
When `kubeadm init` is used in an automated context, it still prints the token to standard out. When standard output ends up in a log file, it can be cosidered that token is leaked there and can be compromised. We could simply avoid this by either detecting a non-interactive terminal and thereby not printing the join command to the standard output, or have a flag to explicitly disable this behaviour.

**Comment by luxas** [comment]
Fixed with https://github.com/kubernetes/kubernetes/issues/44588
