### ISSUE TITLE
certificate-key could have better messaging

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1607]
## Is this a BUG REPORT or FEATURE REQUEST?

 FEATURE REQUEST
## Versions

**kubeadm version** (use `kubeadm version`): 1.14.2

## What happened?
I tried to use the `--experimental-cert-upload` flag with `--certificate-key` but passed in a key that was an invalid size. It told me the size was 2 but did not tell me what a valid size is. I also did not see how to generate a key in documentation.

/kind documentation

**Comment by yagonobre** [comment]
on 1.15 you can use `kubeadm alpha certs certificate-key` to generate a key

**Comment by neolit123** [comment]
> It told me the size was 2 but did not tell me what a valid size is

hm, where is the size 2 coming from?
the size is 32 bytes.

in 1.14 one can only generate a new key when you call `kubeadm init phase upload-certs --experimental-upload-certs`.
