### ISSUE TITLE
don't retry indefinitely to fetch cluster-info if a domain is not in the certs SANs

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1613]
a user reported [here](https://github.com/kubernetes/kubeadm/issues/1611#issuecomment-502117234) that if they pass a domain to `kubeadm join` and this domain is not in the known certs SANs for the api server, our token discovery re-tries indefinitely.

> I0613 23:09:11.949959 22036 token.go:147] [discovery] Failed to request cluster info, will try again: [Get https://weinformatics.vicp.io:36791/api/v1/namespaces/kube-public/configmaps/cluster-info: x509: certificate is valid for k8smaster1, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not weinformatics.vicp.io]

ideally we need a timeout that makes sense - e.g. 60 seconds.

@astrieanna has been cleaning a lot of our `help-wanted` labels recently :), so i'm not going add the label here. but if anyone has the time please go ahead and send a fix.

`/help-is-wanted`

thanks.

**Comment by astrieanna** [comment]
🤦‍♀ This sounds like a really specific fix and a good fit for `help wanted` (as long as a constant 60 seconds is agreed on as the appropriate timeout). If you included where the timeout needs to be changed or referenced a similar code change to model this one on, it could even be a `good first issue`.

**Comment by SataQiu** [comment]
The default discovery timeout is 5 minutes. 
See:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/discovery/token/token.go#L214
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta2/defaults.go#L55

**Comment by neolit123** [comment]
@cailiangliang765

can you please confirm again that it runs longer than 5 minutes?
you've mentioned "one hour" in this comment:

> Many thanks for your reply ! It stop at [preflight] Running pre-flight checks for one hour so i have to terminate it. I add --v=3 to kubeadm join as you say.

https://github.com/kubernetes/kubeadm/issues/1611#issuecomment-502117234

**Comment by cailiangliang765** [comment]
> @cailiangliang765
> 
> can you please confirm again that it runs longer than 5 minutes?
> you've mentioned "one hour" in this comment:
> 
> > Many thanks for your reply ! It stop at [preflight] Running pre-flight checks for one hour so i have to terminate it. I add --v=3 to kubeadm join as you say.
> 
> [#1611 (comment)](https://github.com/kubernetes/kubeadm/issues/1611#issuecomment-502117234)

@neolit123 Thanks for your further investigation. I try again and this time it runs less in 5 minutes. I use vscode tool to connect the master node and perhaps it was hunging up. Thanks.
```
[root@k8snode1 kubernetes]# kubeadm join weinformatics.uicp.io:50437 --token egvr79.joo388bcbmou0rxn --discovery-token-ca-cert-hash sha256:d7406a6794d4844a21dfc746ca22c92520d70f829374542ea9bccc5cdb78eba6
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: failed to get config map: Get https://192.168.220.132:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config: dial tcp 192.168.220.132:6443: i/o timeout
[root@k8snode1 kubernetes]# 
```

**Comment by neolit123** [comment]
>  I try again and this time it runs less in 5 minutes.  I use vscode tool to connect the master node and perhaps it was hunging up. 


the 5 minute timeout in general should always work.
thank you for checking.
