### ISSUE TITLE
host a kubeadm meeting in a Chinese friendly time

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1622]
during the kubeadm 1.16 planning meeting of June 19th we discussed the potential of having a separate kubeadm office hours meeting in a Chinese friendly time. the idea is to host this meeting bi-weekly.

before we begin we need to discuss a couple of topics:
- who can sign up to host the meeting?
we have a couple of regular contributors from China at the moment: @dixudx @SataQiu 
given @dixudx has been with kubeadm for years, ideally he should host this meeting, but newer contributors like @SataQiu can step up?
- where can the agenda for this meeting be hosted. it seems that it should be in a separate google doc, except that google docs are blocked in China, so perhaps another more available platform should be used?
- another important question is - are we going to get enough attendance? possibly we can give this a test for a while and see if more contributors join,

**Comment by SataQiu** [comment]
That's Great! 
@dixudx In view of your experience, I propose that you chair the meeting! WDYT?

**Comment by SataQiu** [comment]
Google Docs alternative in China:
- https://shimo.im
- https://www.yuque.com

**Comment by dixudx** [comment]
Thanks for all your supports.

> another important question is - are we going to get enough attendance? possibly we can give this a test for a while and see if more contributors join,

@kad  We could do a test in KubeCon China next week.

**Comment by neolit123** [comment]
ok, guys. please go ahead and organize the meeting + sending the time and invites.
let us know of the outcome.

if this is a success we can continue doing it.
thank you!

**Comment by dixudx** [comment]
@neolit123 I will collect some feedbacks from Kubecon next week. And later send out a time and invitations.

@SataQiu Would you please have a try on the google doc alternatives and select a better one?

Thanks all.

**Comment by SataQiu** [comment]
@dixudx Yes, I'm glad to do this.

**Comment by timothysc** [comment]
/assign @timothysc 

Just let me know the time folks want and I can update the community deets.

**Comment by dixudx** [comment]
Sure. @timothysc

**Comment by riverzhang** [comment]
+1  
That's Great! I also look forward to attending.

**Comment by pytimer** [comment]
+1
Awesome! Looking forward to attending.

**Comment by RainbowMango** [comment]
Great!

**Comment by fabriziopandini** [comment]
+1 if we can setup a time that works also for EU, I will be happy to attend and help communication across meetings/timezones

**Comment by SataQiu** [comment]
For Google Docs alternative in China, I personally prefer to https://shimo.im.
An example document (editable): https://shimo.im/docs/YcoaYlvRmIYcrwnd/
More Suggestions are welcome!

**Comment by dixudx** [comment]
The feedbacks that I've collected are that quite a few people show their interests in this bi-weekly meeting. The preferred time slot is 8pm-8:30pm in China Standard Time.

Well, it is still open for any suggestions. Don't be hesitate to get involved in.

**Comment by neolit123** [comment]
@dixudx if you have you have found a good time and week day for the meeting just poke the sig-chairs to get hosting credentials.

**Comment by dixudx** [comment]
Sure. Will do that.

**Comment by neolit123** [comment]
i'm going to close this as to my understanding the meeting already happened.
please re-open the ticket if needed.
