### ISSUE TITLE
kubeadm should allow specifying `--control-plane-endpoint`

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1625]
For the options that make sense, we should provide CLI flags. I argue that it makes sense to add a flag for `controlPlaneEndpoint` ASAP, to not have to force the user to create a config file just for running the automated HA flow. This will reduce the burden on first-time users significantly IMO.

I think we should consider backporting such a change to v1.15.1.
(I realized this when writing the v1.15 blog post, FWIW)

@timothysc @fabriziopandini @neolit123

**Comment by luxas** [comment]
@neolit123 I think we could maybe backport this to v1.15
cc @timothysc @fabriziopandini @SataQiu

**Comment by neolit123** [comment]
we started to vote on backports as everybody has a different opinion most of the time.
e.g. Tim is mostly -1 on most things that are non-blocking.
