### ISSUE TITLE
`kubeadm init phase upload-certs --upload-certs` is redundant

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1626]
The flag should not be required, but automatically set. After all, that's why the user runs the command ;)

@neolit123 @fabriziopandini

**Comment by neolit123** [comment]
there is a complication between  running individual phases and the whole
init
The is an issue for this already. Cant find it on the phone.

**Comment by neolit123** [comment]
already logged as:
https://github.com/kubernetes/kubeadm/issues/1442
