### ISSUE TITLE
`kubeadm init` output refers to `--experimental-control-plane`

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#1627]
See: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/util/join.go#L35

We should fix this in a follow-up, in v1.15.1 or similar

/kind bug

@neolit123 @fabriziopandini

**Comment by pytimer** [comment]
If no one works it, i can take.

**Comment by luxas** [comment]
This is not fixed yet, in v1.15. That change should be purely changing the line https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/cmd/util/join.go#L35, and nothing else. @SataQiu can you please fix that too, for the `release-1.15` branch?

**Comment by SataQiu** [comment]
@luxas Thank you for reminding me. I'm glad to fix it!

**Comment by dixudx** [comment]
Got fixed in kubernetes/kubernetes#79369.

/close
