### ISSUE TITLE
Kubelet service wont start

### ISSUE THREAD

**Issue by afagund** [kubernetes/kubeadm#1629]
## Is this a BUG REPORT or FEATURE REQUEST?

Bug report

## Versions
**kubeadm version** (use `kubeadm version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

- **Kernel** (e.g. `uname -a`):
Linux etcd1.andrefagundes.org 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
I am following the official documentation below to set up a new Kubernetes cluster using kubeadm, however, I am not able to start kubelet on mu etcd nodes.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

## What you expected to happen?
I expect to start kubelet as per steps in the official documentation.

## How to reproduce it (as minimally and precisely as possible)?
Just follow exactly the steps from the documentation.

## Anything else we need to know?
Jun 20 19:38:14 etcd1 systemd: Started kubelet: The Kubernetes Node Agent.
Jun 20 19:38:14 etcd1 kubelet: Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 20 19:38:14 etcd1 kubelet: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.

After creating a kubelet config file, I see a different error.

Config File:

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
staticPodPath: /etc/kubernetes/manifests
address: 127.0.0.1

Error:

Jun 20 19:26:22 etcd1 systemd: Started kubelet: The Kubernetes Node Agent.
Jun 20 19:26:23 etcd1 systemd: Started Kubernetes systemd probe.
Jun 20 19:26:23 etcd1 kubelet: I0620 19:26:23.038340 15772 server.go:425] Version: v1.15.0
Jun 20 19:26:23 etcd1 kubelet: I0620 19:26:23.038558 15772 plugins.go:103] No cloud provider specified.
Jun 20 19:26:23 etcd1 kubelet: W0620 19:26:23.038574 15772 server.go:564] standalone mode, no API client
Jun 20 19:26:23 etcd1 kubelet: F0620 19:26:23.038588 15772 server.go:273] failed to run Kubelet: no client provided, cannot use webhook authentication
Jun 20 19:26:23 etcd1 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Jun 20 19:26:23 etcd1 systemd: Unit kubelet.service entered failed state.
Jun 20 19:26:23 etcd1 systemd: kubelet.service failed.
Jun 20 19:43:12 etcd1 kubelet: F0620 19:43:12.031754 16803 server.go:156] unknown flag: --allow-privileged

**Comment by pytimer** [comment]
@afagund You can try to remove the `--allow-privileged` in /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf, because the Kubernetes v1.15.0 remove this flag. I remove this flag, kubelet is running.

**Comment by afagund** [comment]
I removed the flag and placed all parameters in a config file, however, I am seeing the following:

Jun 20 19:26:22 etcd1 systemd: Started kubelet: The Kubernetes Node Agent.
Jun 20 19:26:23 etcd1 systemd: Started Kubernetes systemd probe.
Jun 20 19:26:23 etcd1 kubelet: I0620 19:26:23.038340 15772 server.go:425] Version: v1.15.0
Jun 20 19:26:23 etcd1 kubelet: I0620 19:26:23.038558 15772 plugins.go:103] No cloud provider specified.
Jun 20 19:26:23 etcd1 kubelet: W0620 19:26:23.038574 15772 server.go:564] standalone mode, no API client
Jun 20 19:26:23 etcd1 kubelet: F0620 19:26:23.038588 15772 server.go:273] failed to run Kubelet: no client provided, cannot use webhook authentication
Jun 20 19:26:23 etcd1 systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Jun 20 19:26:23 etcd1 systemd: Unit kubelet.service entered failed state.
Jun 20 19:26:23 etcd1 systemd: kubelet.service failed.
Jun 20 19:43:12 etcd1 kubelet: F0620 19:43:12.031754 16803 server.go:156] unknown flag: --allow-privileged

**Comment by pytimer** [comment]
You execute `systemctl daemon-reload` and restart kubelet, this problem still exists?

**Comment by afagund** [comment]
Yes, same issue.

**Comment by pytimer** [comment]
This is my kubelet systemd file:

```sh
systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf, 20-etcd-service-manager.conf
   Active: active (running) since Fri 2019-06-21 19:40:23 CST; 987ms ago
     Docs: https://kubernetes.io/docs/
 Main PID: 12065 (kubelet)
    Tasks: 14
   Memory: 19.3M
   CGroup: /system.slice/kubelet.service
           └─12065 /usr/bin/kubelet --address=127.0.0.1 --pod-manifest-path=/etc/kubernetes/manifests
```

```sh
$ cat /usr/lib/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
[Service]
ExecStart=
ExecStart=/usr/bin/kubelet --address=127.0.0.1 --pod-manifest-path=/etc/kubernetes/manifests
Restart=always
```

You can compare your kubelet file.

**Comment by afagund** [comment]
Are you sure you are running kubernetes 1.15? Because its does not support the parameters you have specified for kubelet, they have been deprecated.

**Comment by pytimer** [comment]
Yes, i'm sure. 

```sh
$ kubelet --version
Kubernetes v1.15.0
```

this paramters have been deprecated, but the `--allow-privileged` flag is removed, so kubelet can not started. You should remove this flag in your kubelet service.

I think maybe you not remove `--allow-privileged` flag, because your log also show this flag error.

**Comment by neolit123** [comment]
closing due to no response.

we have running e2e tests against 1.15 clusters created with kubeadm;
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm
