### ISSUE TITLE
kubelet remove --allow-privileged flag in setup etcd cluster document

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubeadm#1630]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

```sh
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
`Kubernetes v1.15.0`
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?

[Set up a High Availability etcd cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster) document create etcd cluster, but the first steps `Configure the kubelet to be a service manager for etcd` is wrong, follow this step, kubelet can't started, because kubelet remove the `--allow-privileged` flag when Kubernetes v1.15.0.

## Related issues

issue https://github.com/kubernetes/kubeadm/issues/1629

## What you expected to happen?

The document change this step according to the latest Kubernetes version.

## How to reproduce it (as minimally and precisely as possible)?

Follow the first step.

## Anything else we need to know?

The Kubernetes 1.15 changelog about this flag: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#node

I can fix it, but i don't know where document i should update. If someone know, please tell me. Thanks.

**Comment by SataQiu** [comment]
Thanks for reporting this  @pytimer 
Please change it at : https://github.com/kubernetes/website/edit/master/content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md

**Comment by pytimer** [comment]
@SataQiu Thanks for your reply. 

I submit a PR to fix it. If you have time, you can review it.

**Comment by pytimer** [comment]
Now the PR merged, so i close this issue.
If something i missing, i will reopen it.
