### ISSUE TITLE
Add a new property to the API Server 'ClusterConfiguration' to define the dns policy

### ISSUE THREAD

**Issue by hectorj2f** [kubernetes/kubeadm#1637]
Choose one:  FEATURE REQUEST

In the past kubeadm set the dns policy to a specific type for the control plane pods. However that might not fit to all the scenarios or environments, so that change got reverted. In order to be able to still define that property value, we consider there should be a new flag and configuration property for `kubeadm` `ClusterConfiguration` to set the DNS policy for the API Server. As mentioned, it isn't possible to set a specific DNS policy for that pod with v1beta1 and v1beta2. 

Based on the environment or the infrastructure, it could become a requirement to set the DNS policy to `ClusterFirstWithHostNet` to resolve cluster internal addresses. For instance, this could be use to resolve internal auth webhooks or calling component such as dex k8s-auth.

Consequently, we believe it'd be good to expose that option to be configured on demand.

I started a PR with a proposal change https://github.com/kubernetes/kubernetes/pull/79379 but I was asked to create an issue for discussion.

## Versions

**kubeadm version** (use `kubeadm version`): v1.15.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.15.0

**Comment by neolit123** [comment]
thanks for logging the issue, if you want this discussed live, please add it as an agenda item for the zoom  meeting.

we can technically expose a v1.Pod-like object per component and merge some of those settings that end up in the actual v1.Pod that we write in the manifests for static pods. this however also needs discussion.

**Comment by timothysc** [comment]
It's a little unusual to setup DNS policy as ClusterFirst, so I'm not crazy about plumbing this through the main types, however this would definitely fit under the kustomize umbrella for a given provider. 

/assign @fabriziopandini

**Comment by hectorj2f** [comment]
@timothysc The intention is to be able to set the dns policy to the API Server to `ClusterFirstWithHostNet` instead of `ClusterFirst`. Also, I remember reading that ClusterFirst is the default dns policy set to pods, if none was defined, as far as I know :).

I started a PR https://github.com/kubernetes/kubernetes/pull/79379 but @neolit123 told me that `v1beta1` and `v1beta2` types are locked. 

I won't have problem to contribute or adapt my PR according to your suggestions.

**Comment by neolit123** [comment]
punting to the "kustomization" support in kubeadm 1.16
https://github.com/kubernetes/kubeadm/issues/1379

please read the design proposal and follow up on that ticket if needed.
