### ISSUE TITLE
service-account-token rotation on upgrade

### ISSUE THREAD

**Issue by qw1mb0** [kubernetes/kubeadm#1641]
## Is this a request for help?
yes

## What keywords did you search in kubeadm issues before filing this one?
service-account-token, certificate, tls, expire, upgrade

## Versions

**kubeadm version** (use `kubeadm version`): 1.15.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.15.0
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): `Linux kube-a-1 4.18.0-20-generic #21~18.04.1 SMP Thu May 16 11:54:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

## What happened?
During the cluster upgrade, kubeadm re-issues the control plane certificates using the old CA.

From the parameters of the API server, I see:
```--service-account-key-file A file containing a PEM encoded key for signing bearer tokens. If unspecified, the TLS server’s private key will be used.```

What service-account-token is generated using Api server TLS (by default). 

## What you expected to happen?
Then it turns out that when updating certificates. All operators that use the old service-account-token should stop going to the API server. However, everything continues to work correctly for me. Could you explain this moment?

**Comment by neolit123** [comment]
hi, i'm going to attempt to respond to your questions, but will ping some folks who have more knowledge than me to provide extra feedback if needed.

cc @alexbrand @mauilion 

> --service-account-key-file A file containing a PEM encoded key for signing bearer tokens. If unspecified, the TLS server’s private key will be used.
> What service-account-token is generated using Api server TLS (by default).

i'm not sure i understand this question exactly, but bearer tokens are signed by the service-account-controller with a `service-account-token` named service-account-controller-token-xxxxx.

if you don't pass the service account public key that kubeadm generates to `--service-account-key-file` it will use the server's private key for this same purpose. please, also mind that this flag works in combination with passing `--service-account-private-key-file` to the controller-manager.

see https://github.com/kubernetes/kubernetes/issues/22351#issuecomment-270710416

> Then it turns out that when updating certificates. All operators that use the old service-account-token should stop going to the API server. However, everything continues to work correctly for me. Could you explain this moment?

the service account private and public keys do not change for the cluster after upgrade (same goes for the cluster CA). they are generated during `kubeadm init` as `/etc/kubernetes/pki/sa.{key|pub}`.

this also means that post-ugrade the token in e.g. the `service-account-controller-token-xxxxx` Secret remains the same.

**Comment by qw1mb0** [comment]
I found a function that generates sa files: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/certs.go#L67-L96
https://github.com/kubernetes/kubernetes/blob/master//cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L548:6

Apparently this is the usual RSA keys. Not related to rootCa, right?

It turns out that when a request from ServiceAccount goes to the API server, rootCa validation (which is located in the secret) and the rsa key occurs. Right? Therefore, updating the certificates themselves does not affect the change in RSA keys.

**Comment by neolit123** [comment]
> Apparently this is the usual RSA keys. Not related to rootCa, right?

yes, it's a private / public RSA key pair generated using the golang standard library -> sa.pub, sa.key.

> Therefore, updating the certificates themselves does not affect the change in RSA keys.

we do not re-generate sa.pub, sa.key on upgrade. we also don't re-generate the CA.

**Comment by qw1mb0** [comment]
thanks!
