### ISSUE TITLE
Recover a Self-hosted Kubeadm Kubernetes Cluster After Reboot -V1.15

### ISSUE THREAD

**Issue by RotemEmergi** [kubernetes/kubeadm#1645]
Hi ,

I am using - 

>  kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

I created a  self-hosted cluster that all the servers was shutdown after power outage and the cluster doesn't recover from that .

There is a way to use the -

>  kubeadm init --pod-network-cidr=192.168.0.0/16 --feature-gates=SelfHosting=true

And use this solution/workaround for this case ? 
[https://github.com/xetys/k8s-self-hosted-recovery](url)

Best Regards

**Comment by neolit123** [comment]
hello, i personally have not tried self-hosting at all.
self-hosting in kubeadm is deprecated and unsupported.

this it the only remaining docs we have on this subject:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/self-hosting/

> --feature-gates=SelfHosting=true

this feature gate no longer exists.

the feature can be enabled by "pivoting" an existing cluster using the `kubeadm alpha selfhosting` command.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/#cmd-selfhosting

**Comment by timothysc** [comment]
> I created a self-hosted cluster that all the servers was shutdown after power outage and the cluster doesn't recover from that . 

This has been a known deficiency of self hosting for a long time and part of the reason this path was abandoned.  

Closing due to support policy.
