### ISSUE TITLE
Update CIS Benchmark tests for Kubelet ComponentConfig

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/kubeadm#1648]
/kind feature

Part of #683

CIS Benchmark for Kubernetes currently has tests for kubelet checking environment variables and command line flags. These report false positives in test suites that apply the tests from the documentation as kubeadm uses ComponentConfig.

We need to supply to the next version of the documentation tests that satisfactorily pass on kubelet component configuration.

This can be done at https://workbench.cisecurity.org/communities/43#

cc @liztio @neolit123  

## Versions

**kubeadm version** (use `kubeadm version`): 1.16

**Comment by neolit123** [comment]
@randomvariable i'm going to close this issue as it seems more appropriate to me to track this as an issue on the CIS benchmark side.

please reopen if you disagree
/close
