### ISSUE TITLE
Produce documentation for running a CIS compliant cluster with kubeadm

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/kubeadm#1649]
/kind feature
/assign randomvariable
/priority critical-urgent
/milestone v1.16

Part of #683

Produce documentation on k8s.io for how to achieve CIS compliance with kubeadm

cc @liztio @neolit123  

## Versions

**kubeadm version** (use `kubeadm version`): 1.16

**Comment by neolit123** [comment]
moving to "Next" milestone and adding "help-wanted". if contributors want to help in this area please make a comment and we can instruct you how to send a PR to kubernetes/website.

instructions on running kube-bench are here:
https://github.com/aquasecurity/kube-bench
