### ISSUE TITLE
Unable to override service subnet for DNS

### ISSUE THREAD

**Issue by pmichali** [kubernetes/kubeadm#165]
Wanted to use a different (and smaller) subnet for service IPs. I changed /etc/systemd/system/kubelet.service.d/10-kubeadm.conf to set the cluster-dns environment argument to 10.20.30.10. On init, I used:
kubeadm init --api-advertise-addresses=10.86.7.206 --service-cidr=10.20.30.0/24

The kubectl get svc shows that DNS is using 10.20.30.10:
kubectl get svc --all-namespaces -o wide
NAMESPACE     NAME         CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE       SELECTOR
default       kubernetes   10.20.30.1    <none>        443/TCP         1h        <none>
kube-system   kube-dns     **10.20.30.10**   <none>        53/UDP,53/TCP   1h        name=kube-dns

But the kubelet process that was started, has the default IP:

root     32515     1 13 16:39 ?        00:11:39 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=**10.96.0.10** --cluster-domain=cluster.local

I did verify that kubelet process did not exist after "kubeadm reset", and that it was there after init.

Not sure if I'm missing some additional configuration setting, or if there is a bug here and kubelet is being started with a hard-coded value.

**Comment by GheRivero** [comment]
Did you try to reload systemd daemon after modifying the config? ( `systemctl daemon-reload`)

**Comment by pmichali** [comment]
No, I didn't and later, when rebooting the system, I did see that the IP address was correct. Looks like that is the issue. Thanks!
