### ISSUE TITLE
remove kinder and potentially move it's features in kind

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1652]
investigate if we can one day remove kinder and have it's features under kind.

**Comment by fabriziopandini** [comment]
https://github.com/kubernetes/kubeadm/pull/1684 documents kind/kinder differences

**Comment by neolit123** [comment]
kinder at this point only mimics the kind CI and uses the DIND model, but is a mostly different implementation.
closing as our testing setup is quite complex and out of scope for upstream kind.
