### ISSUE TITLE
How to update expired certificates in version 1.6.2 of kubeadm

### ISSUE THREAD

**Issue by songchuangyuan** [kubernetes/kubeadm#1653]
There are no commands to regenerate certificates, such as "kubeadm alpha phase certs".only this：
![image](https://user-images.githubusercontent.com/46445562/60641287-c40f6080-9e5d-11e9-8cd3-8b709656082d.png)
But make a mistake，like this：
[certificates] Generated CA certificate and key.
failure while creating API server key and certificate [unable to sign certificate [x509: cannot parse IP address of length 0]]
How should I solve it?

**Comment by neolit123** [comment]
hi. i'm sorry but 1.6 is not supported for a long time.
you can try stackoverflow or reddit for support on this problem.

/close
