### ISSUE TITLE
kubeadm join fails configuring taints with empty value

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/kubeadm#1655]
## Versions

**kubeadm version** (use `kubeadm version`): `v1.15.0`

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.14.3
- **Cloud provider or hardware configuration**: Openstack
- **OS** (e.g. from /etc/os-release): `Container Linux by CoreOS 2023.5.0 (Rhyolite)`
- **Kernel** (e.g. `uname -a`): `Linux os1pi014-kube-master01 4.19.25-coreos #1 SMP Sat Mar 9 01:05:06 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz GenuineIntel GNU/Linux
`
- **Others**:
  - kubelet version: `1.14.3`

## What happened?
When trying to join a new worker node with taints using kubeadm join the kubelet is stuck restarting because of a wrong `register-with-taints` parameter:
From `/var/lib/kubelet/kubeadm-flags.env`
```
--register-with-taints=node.kubernetes.io/not-ready:NoExecute
```
From kubeadm.yaml (long version below):
```
apiVersion: kubeadm.k8s.io/v1beta2
discovery:
  ...
kind: JoinConfiguration
nodeRegistration:
  ...
  taints:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
...
```

## What you expected to happen?
The kubelet started and kubeadm to succeed including the taints being applied.

## How to reproduce it (as minimally and precisely as possible)?
Example kubeadm config:
```
apiVersion: kubeadm.k8s.io/v1beta2
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.6.0.16:6443
    caCertHashes:
    - sha256:<replaced>
    token: <replaced>
  timeout: 5m0s
  tlsBootstrapToken: <replaced>
kind: JoinConfiguration
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  kubeletExtraArgs:
    cloud-provider: external
  name: os1pi014-kube-node01
  taints:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
```
start kubeadm
```
os1pi014-kube-node01 core # /opt/bin/kubeadm join --ignore-preflight-errors FileAvailable--etc-kubernetes-kubelet.conf,FileAvailable--etc-kubernetes-pki-ca.crt --config kubeadm_config.yaml 
[preflight] Running pre-flight checks
        [WARNING FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileAvailable--etc-kubernetes-pki-ca.crt]: /etc/kubernetes/pki/ca.crt already exists
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Downloading configuration for the kubelet from the "kubelet-config-1.14" ConfigMap in the kube-system namespace
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Activating the kubelet service
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
```
See failing kubelet:
```
os1pi014-kube-node01 core # journalctl -u kubelet --since "5 minutes ago" | grep -e "invalid argument"
Jul 04 12:56:56 os1pi014-kube-node01 kubelet[6189]: F0704 12:56:56.359371    6189 server.go:152] invalid argument "node.kubernetes.io/not-ready:NoExecute" for "--register-with-taints" flag: invalid taint spec: node.kubernetes.io/not-ready:NoExecute
```
See line:
```
cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--cgroup-driver=cgroupfs --cloud-provider=external --network-plugin=cni --pod-infra-container-image=reg-dhc.app.corpintra.net/caas/pause:3.1 --register-with-taints=node.kubernetes.io/not-ready:NoExecute --resolv-conf=/run/systemd/resolve/resolv.conf"
```

And this is how it **should** look like to make it work:
```
KUBELET_KUBEADM_ARGS="--cgroup-driver=cgroupfs --cloud-provider=external --network-plugin=cni --pod-infra-container-image=reg-dhc.app.corpintra.net/caas/pause:3.1 --register-with-taints=node.kubernetes.io/not-ready=:NoExecute --resolv-conf=/run/systemd/resolve/resolv.conf"
```

## Anything else we need to know?

Feature was introduced in https://github.com/kubernetes/kubernetes/pull/79107
I think the problem is that the normal `ToString` function for taints get used [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubelet/flags.go#L96) and [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/taint.go#L31).
Which looks forward to not add the `=` on empty valued taints

**Comment by neolit123** [comment]
@chrischdi 
what is your kubelet version?

the parsing on the kubelet 1.15 side:
https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/util/taints/taints.go#L38-L81
(cc @dlipovetsky )

for the 1.14 kubelet:
https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/util/taints/taints.go#L39-L63

if you pass this:
`--register-with-taint=node.kubernetes.io/not-ready:NoExecute` 

it should be accepted. but it doesn't seem to work.

@chrischdi 
is it a workaround for you if you pass `node.kubernetes.io/not-ready=:NoExecute` in the kubeadm config. in your current setup?

/sig node
/priority awaiting-more-evidence

**Comment by chrischdi** [comment]
> @chrischdi
> what is your kubelet version?
> 
> the parsing on the kubelet 1.15 side:
> https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/util/taints/taints.go#L38-L81
> (cc @dlipovetsky )
> 
> for the 1.14 kubelet:
> https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/util/taints/taints.go#L39-L63
> 
> if you pass this:
> `--register-with-taint=node.kubernetes.io/not-ready:NoExecute`
> 
> it should be accepted. but it doesn't seem to work.
> 
> @chrischdi
> is it a workaround for you if you pass `node.kubernetes.io/not-ready=:NoExecute` in the kubeadm config. in your current setup?
> 
> /sig node
> /priority awaiting-more-evidence

Hi neolit123: right, I'm using v1.14.3 kubelet. So it's just not backward compatible I guess?
:+1:

**Comment by chrischdi** [comment]
I think I could workaround by passing `register-with-taint` as `kubeletExtraArgs`

**Comment by neolit123** [comment]
> Hi neolit123: right, I'm using v1.14.3 kubelet. So it's just not backward compatible I guess?

yes, the `key:effect` parsing support was introduced in kubelet 1.15.
but your kubelet version has to be equal or older compared to the control-plane components.

> I think I could workaround by passing register-with-taint as kubeletExtraArgs

yes.

**Comment by chrischdi** [comment]
> > Hi neolit123: right, I'm using v1.14.3 kubelet. So it's just not backward compatible I guess?
> 
> yes, the `key:effect` parsing support was introduced in kubelet 1.15.
Ok, I got it :-)

> but your kubelet version has to be equal or older compared to the control-plane components.

Sure, I'm setting up a whole v1.14.3 cluster but am using v1.15 kubeadm, because we've got clusters we want first lift (from `v1.13`) to `v1.14`.

So regarding this bug: should I close this issue or is it maybe wanted to check this in preflight that there are no taints set via `nodeRegistration.taints` when using kubelets < `v1.15` (If I'm right the kubelet version get's also checked)

> 
> > I think I could workaround by passing register-with-taint as kubeletExtraArgs
> 
> yes.

**Comment by neolit123** [comment]
let's keep this issue open for visibility and take action if there are more reports.

**Comment by neolit123** [comment]
closing as this also saw a change for 1.16 (thanks @SataQiu )

see: https://github.com/kubernetes/kubernetes/pull/79834/files#diff-09819a55e7cc3686c70b31b14ae7803dR30

for older versions of the kubelet, not mapping there isn't much we can do as we don't want to special case this with - e.g. preflight checks.
