### ISSUE TITLE
run kubeadm join phase control-plane-prepare all  No response

### ISSUE THREAD

**Issue by odeng888** [kubernetes/kubeadm#1656]
[root@dev-node2 data]# kubeadm join phase control-plane-prepare all 192.168.1.51:6443 --discovery-token abcdef.0123456789abcdef --token 6cd86e.621e41898f4050da --discovery-token-ca-cert-hash sha256:ab2224355ec9bcee4aa7400b912bf0ffe8c09c095bb3e562d4df9b92ff21e0f1  --node-name dev-node2
[root@dev-node2 data]# 

what happen?
No output

**Comment by stgleb** [comment]
What output do you expect from this step? AFAIK this step creates yaml files for control plane components.

**Comment by odeng888** [comment]
I want to add a new control node
 apiserver  etcd...

**Comment by stgleb** [comment]
In that case you don't have to run single phase, to add new node you just run

```
kubeadm join --control-plane all 192.168.1.51:6443 --discovery-token abcdef.0123456789abcdef --token 6cd86e.621e41898f4050da --discovery-token-ca-cert-hash sha256:ab2224355ec9bcee4aa7400b912bf0ffe8c09c095bb3e562d4df9b92ff21e0f1 --node-name dev-node2
```

**Comment by odeng888** [comment]
Error: accepts at most 1 arg(s), received 2
Usage:
  kubeadm join [api-server-endpoint] [flags]
  kubeadm join [command]

Available Commands:
  phase       Use this command to invoke single phase of the join workflow

Flags:
      --apiserver-advertise-address string            If the node should host a new control plane instance, the IP address the API Server will advertise it's listening on. If not set the default network interface will be used.
      --apiserver-bind-port int32                     If the node should host a new control plane instance, the port for the API Server to bind to. (default 6443)
      --certificate-key string                        Use this key to decrypt the certificate secrets uploaded by init.
      --config string                                 Path to kubeadm config file.
      --control-plane                                 Create a new control plane instance on this node
      --cri-socket string                             Path to the CRI socket to connect. If empty kubeadm will try to auto-detect this value; use this option only if you have more than one CRI installed or if you have non-standard CRI socket.
      --discovery-file string                         For file-based discovery, a file or URL from which to load cluster information.
      --discovery-token string                        For token-based discovery, the token used to validate cluster information fetched from the API server.
      --discovery-token-ca-cert-hash strings          For token-based discovery, validate that the root CA public key matches this hash (format: "<type>:<value>").
      --discovery-token-unsafe-skip-ca-verification   For token-based discovery, allow joining without --discovery-token-ca-cert-hash pinning.
  -h, --help                                          help for join
      --ignore-preflight-errors strings               A list of checks whose errors will be shown as warnings. Example: 'IsPrivilegedUser,Swap'. Value 'all' ignores errors from all checks.
      --node-name string                              Specify the node name.
      --skip-phases strings                           List of phases to be skipped
      --tls-bootstrap-token string                    Specify the token used to temporarily authenticate with the Kubernetes Control Plane while joining the node.
      --token string                                  Use this token for both discovery-token and tls-bootstrap-token when those values are not provided.

Global Flags:
      --log-file string          If non-empty, use this log file
      --log-file-max-size uint   Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --rootfs string            [EXPERIMENTAL] The path to the 'real' host root filesystem.
      --skip-headers             If true, avoid header prefixes in the log messages
      --skip-log-headers         If true, avoid headers when opening log files
  -v, --v Level                  number for the log level verbosity

Use "kubeadm join [command] --help" for more information about a command.

error: accepts at most 1 arg(s), received 2

**Comment by odeng888** [comment]
One more all parameter
I'll try again.

**Comment by stgleb** [comment]
Sorry, I did not remove `all` subcommand
that must work for kubeadm 1.15

```
kubeadm join --control-plane 192.168.1.51:6443 --discovery-token abcdef.0123456789abcdef --token 6cd86e.621e41898f4050da --discovery-token-ca-cert-hash sha256:ab2224355ec9bcee4aa7400b912bf0ffe8c09c095bb3e562d4df9b92ff21e0f1 --node-name dev-node2
```

**Comment by stgleb** [comment]
@odeng888 don't hesitate to ping me if it doesn't work for you

**Comment by odeng888** [comment]
[root@dev-node5 data]# kubeadm join --control-plane 192.168.1.51:6443 --token 6cd86e.621e41898f4050da --discovery-token-ca-cert-hash sha256:ab2224355ec9bcee4aa7400b912bf0ffe8c09c095bb3e562d4df9b92ff21e0f1 --node-name dev-node5
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
error execution phase preflight: 
One or more conditions for hosting a new control plane instance is not satisfied.

unable to add a new control plane instance a cluster that doesn't have a stable controlPlaneEndpoint address

Please ensure that:
* The cluster has a stable controlPlaneEndpoint address.
* The certificates that must be shared among control plane instances are provided.

**Comment by RA489** [comment]
@odeng888 could you please provide the environment on which you executed these commands.

**Comment by neolit123** [comment]
close due to no response.
