### ISSUE TITLE
kubeadm doesn't fallback to client version when there is 502 Bad Gateway

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes/kubeadm#1662]
**What happened**:
I was using kubeadm to generate cluster ca:

```
kubeadm init phase certs ca --cert-dir /etc/kubernetes/pki/
```

The CA generation failed because of 502 bad gateway returned and the response body isn't empty when it's trying to fetch stable version from internet. In this case, the `KubernetesReleaseVersion` function returns error instead of falling back to local client version:

```
unable to fetch file. URL: "https://dl.k8s.io/release/stable-1.txt", status: 502 Bad Gateway
failed to run commands: exit status 1
```

[here](https://github.com/kubernetes/kubernetes/blob/v1.13.7/cmd/kubeadm/app/util/version.go#L176) is how kubeadm fetches stable version and [here](https://github.com/kubernetes/kubernetes/blob/v1.13.7/cmd/kubeadm/app/util/version.go#L90) is how the error is handled for `fetchFromURL`.

Should kubeadm always fall back to client version when there is any internet issue? Otherwise, this sounds defeat the purpose of fallback.

/sig cluster-lifecycle

**What you expected to happen**:
kubeadm falls back to local client version when there is any internet issue.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.7
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by hyahm** [comment]
how to solve this issue

**Comment by RainbowMango** [comment]
@hyahm 
These two issues sound very similar, and yet, they are not the same. There is a subtle difference.

Your problem is the connection cannot be set up then fall back to the client version, it is the expected behavior I think.

**Comment by hyahm** [comment]
in china ,  i can't open this url

**Comment by RainbowMango** [comment]
I can't figure out how serious for a user who can only use the local version.

Just a guess, your problem seems certificate file missing from "/etc/kubernetes/pki/apiserver.crt".
How about trying this command.  
`kubeadm init phase certs ca --cert-dir /etc/kubernetes/pki/apiserver.crt`

**Comment by neolit123** [comment]
thanks for moving the issue @leakingtapan
