### ISSUE TITLE
Not all api types have a json struct tag

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1663]
All api types should have a json struct tag, but BootstrapTokenString does not define any for the fields `ID` and `Secret`.

## Versions
All versions with BootstrapTokenString

I would like to embed the InitConfiguration type into a CRD and use controller-gen v0.2 on that CRD. However, there is a new hard requirement (the requirement has always existed, but it is now an error) that every struct field MUST have a json tag.

**Comment by neolit123** [comment]
we need to fix this in beta3, possibly by also moving BTS to cluster-bootstrap. :(
