### ISSUE TITLE
how to get all config like kubectl explain

### ISSUE THREAD

**Issue by zgfh** [kubernetes/kubeadm#1666]
how to get all config of kubeadm like kubectl explain xxx?
becase `kubeadm config print init-defaults` not print all config any more

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
1.15.0
**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.15.0
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): centos 7.5
- **Kernel** (e.g. `uname -a`): Linux 192-168-101-55 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
`kubeadm config print init-defaults ` or some command print all config of kubeadm

**Comment by neolit123** [comment]
this command just prints the defaults.
to see all possible options you need to visit godocs:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

/triage support
cc @rosti

**Comment by zgfh** [comment]
thanks to reply, I think add a `kubeadm config print init-defaults -a` or `kubeadm explain InitConfiguration` will more easy to use and  edit

**Comment by neolit123** [comment]
> kubeadm explain InitConfiguration

the kubeadm binary does not compile information on the API types.
i think we just need to link from our command line flag descriptions to godocs in some places and users will be just able to open the URL.

**Comment by zgfh** [comment]
thanks to reply
should I make a PR to add a link in the long message of `kubeadm config print`, make it easy find out ?

**Comment by neolit123** [comment]
i'm a tentative +1 but let's get more votes.
@fabriziopandini @rosti ?

**Comment by fabriziopandini** [comment]
I'm +1. thanks @zgfh

**Comment by zgfh** [comment]
PR: https://github.com/kubernetes/kubernetes/pull/80433
