### ISSUE TITLE
Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container 

### ISSUE THREAD

**Issue by kadalarasan** [kubernetes/kubeadm#1667]
I have configured k8s Cluster one master and two Worker Nodes. 
My Master and Nodes are in ready state. But when i try to create new Pod, its unable to complete and getting below error. 

[root@master01 ~]# kubectl get no
NAME       STATUS     ROLES    AGE     VERSION
master01   Ready      master   3h13m   v1.15.0
node01     Ready      <none>   3h3m    v1.15.0
node02     NotReady   <none>   178m    v1.15.0
[root@master01 ~]#

[root@master01 ~]# kubectl get po -o wide
NAME                     READY   STATUS              RESTARTS   AGE    IP       NODE     NOMINATED NODE   READINESS GATES
nginx-7bb7cd8db5-5qjrb   0/1     Terminating         0          177m   <none>   node02   <none>           <none>
nginx-7bb7cd8db5-qxhpl   0/1     ContainerCreating   0          120m   <none>   node01   <none>           <none>
[root@master01 ~]#

[root@master01 ~]# kubectl get pods --all-namespaces
NAMESPACE     NAME                               READY   STATUS              RESTARTS   AGE
default       nginx-7bb7cd8db5-5qjrb             0/1     Terminating         0          179m
default       nginx-7bb7cd8db5-qxhpl             0/1     ContainerCreating   0          123m
kube-system   coredns-5c98db65d4-ctl74           1/1     Running             3          3h15m
kube-system   coredns-5c98db65d4-plhfv           1/1     Running             3          3h15m
kube-system   etcd-master01                      1/1     Running             3          3h14m
kube-system   kube-apiserver-master01            1/1     Running             3          3h14m
kube-system   kube-controller-manager-master01   1/1     Running             3          3h14m
kube-system   kube-proxy-ccdgj                   1/1     Running             3          3h6m
kube-system   kube-proxy-gfjpx                   1/1     Running             3          3h15m
kube-system   kube-proxy-lqlbk                   1/1     Running             0          3h1m
kube-system   kube-scheduler-master01            1/1     Running             3          3h14m
kube-system   weave-net-7c58s                    2/2     Running             1          3h1m
kube-system   weave-net-mt5xz                    2/2     Running             8          3h6m
kube-system   weave-net-w2dml                    2/2     Running             8          3h13m
[root@master01 ~]#

[root@master01 ~]# kubectl describe pods nginx-7bb7cd8db5-qxhpl
Name:           nginx-7bb7cd8db5-qxhpl
Namespace:      default
Priority:       0
Node:           node01/192.168.13.129
Start Time:     Sat, 13 Jul 2019 12:30:10 +0530
Labels:         pod-template-hash=7bb7cd8db5
                run=nginx
Annotations:    <none>
Status:         Pending
IP:
Controlled By:  ReplicaSet/nginx-7bb7cd8db5
Containers:
  nginx:
    Container ID:
    Image:          nginx
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wc9pg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-wc9pg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wc9pg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Warning  FailedScheduling        20m (x4 over 23m)    default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling        13m (x5 over 14m)    default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.
  Normal   Scheduled               13m                  default-scheduler  Successfully assigned default/nginx-7bb7cd8db5-qxhpl to node01
  Warning  FailedCreatePodSandBox  13m                  kubelet, node01    Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "a5bffb9a3b279d66d0b1dce910ef6a0eb22481106f7e920acfa009dde6a67a21" network for pod "nginx-7bb7cd8db5-qxhpl": NetworkPlugin cni failed to set up pod "nginx-7bb7cd8db5-qxhpl_default" network: unable to allocate IP address: Post http://127.0.0.1:6784/ip/a5bffb9a3b279d66d0b1dce910ef6a0eb22481106f7e920acfa009dde6a67a21: dial tcp 127.0.0.1:6784: connect: connection refused, failed to clean up sandbox container "a5bffb9a3b279d66d0b1dce910ef6a0eb22481106f7e920acfa009dde6a67a21" network for pod "nginx-7bb7cd8db5-qxhpl": NetworkPlugin cni failed to teardown pod "nginx-7bb7cd8db5-qxhpl_default" network: Delete http://127.0.0.1:6784/ip/a5bffb9a3b279d66d0b1dce910ef6a0eb22481106f7e920acfa009dde6a67a21: dial tcp 127.0.0.1:6784: connect: connection refused]
  Normal   SandboxChanged          13m (x2 over 13m)    kubelet, node01    Pod sandbox changed, it will be killed and re-created.
  Normal   SandboxChanged          11m (x2 over 11m)    kubelet, node01    Pod sandbox changed, it will be killed and re-created.
  Normal   SandboxChanged          20s (x7 over 9m1s)   kubelet, node01    Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  20s (x2 over 4m21s)  kubelet, node01    Failed create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
[root@master01 ~]#

[root@master01 ~]# kubectl version --short
Client Version: v1.15.0
Server Version: v1.15.0
[root@master01 ~]#
[root@master01 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@master01 ~]#
[root@master01 ~]#

**Comment by neolit123** [comment]
best to log a ticket in kubernetes/kubernetes and tag it with `/triage support`, `/sig node`, `/area kubelet`. also please provide information about your container runtime there.
