### ISSUE TITLE
combine the "kubeadm upgrade apply/node" commands

### ISSUE THREAD

**Issue by ereslibre** [kubernetes/kubeadm#1668]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## What happened?

`kubeadm upgrade` UX got simplified in the `1.15` release after https://github.com/kubernetes/kubernetes/pull/78408 merged. Right now, the upgrade UX looks like:

* Run `kubeadm upgrade apply` on the first control plane of the cluster
  * Either pass the new version as a positional argument (e.g. `v1.15.0`)
  * Pass a fully fledged configuration file to it using the `--config` argument
* Run `kubeadm upgrade node` on the rest of control plane nodes and worker nodes

This is a much better situation than the previous one before https://github.com/kubernetes/kubernetes/pull/78408 merged, [described here](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-14/), for example.

This feature request is to have a single upgrade command for all nodes, regardless of what role the machine has in the cluster.

## Proposal

* `kubeadm upgrade apply` is the only command that exists, used both in control planes (first and secondary) and worker nodes
* `kubeadm upgrade node` is kept for compatibility with previous versions, deprecated

### `kubeadm upgrade apply` with version or `--config` provided

In this case, we'll check that the current node is a control plane node and that the provided version either in the positional argument or in the configuration file is more recent than the previous version in the cluster configuration in the `kubeadm-config` ConfigMap.

Optionally, we could enforce that no minor versions are skipped (e.g. the current kubernetes version in the `kubeadm-config` ConfigMap is `1.13.x` and we are trying to upgrade to `1.15.y`).

### `kubeadm upgrade apply` without version nor `--config` provided

In this case, we'll check if there's a newer version present in the cluster configuration in the `kubeadm-config` ConfigMap. If there is, we will update this node to that version. Depending on the role of this node, we'll perform the control plane upgrade or the worker upgrade.

## Non-goals

Further checks could be performed assuming we have a `kubeconfig` we can use to connect to the cluster, but this would mean that `kubeadm` will perform smarter checks that go beyond the current node. Some of this examples are:

* Do not allow to upgrade control plane versions if some worker nodes are outdated
  * The [current skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/) does not support a kubelet version `< x.(y - 2)` when the control planes are at `x.y`. Abort the upgrade of the control plane.

* Do not allow to upgrade worker nodes before all control planes are updated
  * No `kubelet` should be newer than any `apiserver`. Abort the upgrade of the worker node.

These checks would ensure that versioning between the different nodes of a cluster created with `kubeadm` are consistent and comply with the skew policy. Also, this would imply that for example, what worker nodes should we consider (e.g. when doing the consistency check, does it make sense to check cordoned nodes? -- maybe they are under investigation and the user does not plan to upgrade those right now, but still, they want to move the cluster forward).

**Comment by ereslibre** [comment]
As an aside, I think it's worth noting that the way we are upgrading HA clusters is not safe according to the skew policy. Please, point out if I'm missing something, but in an HA cluster, assuming 3 control plane nodes, after one control plane upgraded:

- CP0: control plane components: `1.15.0`, kubelet: `1.15.0`
- CP1: control plane components: `1.14.1`, kubelet: `1.14.1`
- CP2: control plane components: `1.14.1`, kubelet: `1.14.1`
- W0: kubelet: `1.14.1`

In this scenario, `CP0`'s kubelet could reach `CP1` or `CP2` apiservers running an older version, what is not supported. Same situation after upgrading `CP1` afterwards:

- CP0: control plane components: `1.15.0`, kubelet: `1.15.0`
- CP1: control plane components: `1.15.0`, kubelet: `1.15.0`
- CP2: control plane components: `1.14.1`, kubelet: `1.14.1`
- W0: kubelet: `1.14.1`

`CP0` or `CP1`'s kubelet could reach `CP2` apiserver running an older version. When `CP2` is upgraded we reach a supported skew:

- CP0: control plane components: `1.15.0`, kubelet: `1.15.0`
- CP1: control plane components: `1.15.0`, kubelet: `1.15.0`
- CP2: control plane components: `1.15.0`, kubelet: `1.15.0`
- W0: kubelet: `1.14.1`

If we follow the current approach of upgrading all components node by node we will have this situation, unless we start upgrading control plane components on control planes first, then kubelets in all nodes.

Just wanted to drop this here, before we go the path of simplifying the upgrade process even more when we are going through unsupported temporary situations.

**Comment by fabriziopandini** [comment]
@ereslibre 

> kubeadm upgrade apply _with or without_ version or --config provided

If I got this right, this change introduces only a different semantic for upgrading all the nodes after the first, but the difference between the first and the following still remain.
Is that right? in this case, what are the expected benefits

>  the way we are documenting the upgrade of HA clusters is not safe according to the skew policy... unless we start upgrading control plane components on control planes first, then kubelets in all nodes

Originally kubelet on control plane-nodes was talking only on the local api server, and in this case we are safe. I should check if it is still the case; otherwise, this point should be addressed

**Comment by neolit123** [comment]
discussed this with @fabriziopandini and i will send PR to update the HA upgrade docs.
/kind documentation
/priority important-longterm
/assign

**Comment by neolit123** [comment]
1.15 doc updated with this PR:
https://github.com/kubernetes/website/pull/15452

**Comment by neolit123** [comment]
@ereslibre 
thank you for bringing the upgrade order problem up!

> As an aside, I think it's worth noting that the way we are documenting the upgrade of HA clusters is not safe according to the skew policy. Please, point out if I'm missing something, but in an HA cluster, assuming 3 control plane nodes, after one control plane upgraded:

with the current upgrade docs (without my PR above), a newer kubelet in the cluster can technically reach an api-server that is older, but i do not believe this will cause a catastrophic failure unless they are on the same node(?).

> If we follow the current approach of upgrading all components node by node we will have this situation, unless we start upgrading control plane components on control planes first, then kubelets in all nodes.

i read a recent discussion somewhere that while this is the case, in theory a kubelet can be X+1 compared to an apiserver. i don't have the link for this discussion, so maybe this is changing in the future.

but i confirm myself that i was able to break a cluster with a kubelet that is newer than the server around the 1.14 cycle. yet more recently i've been doing this by mistake all the time and it seems that the system is happy not following the version skew - possibly a lucky set of commits that don't break.

in any case, the change in docs is quite viable.

**Comment by fabriziopandini** [comment]
focusing back on UX, after fix for the upgrade workflow

> kubeadm upgrade apply with or without version or --config provided

If I got this right, this change introduces only a different semantic for upgrading all the nodes after the first, but the difference between the first and the following still remain.
Is that right? in this case, what are the expected benefits @ereslibre?

**Comment by ereslibre** [comment]
> Is that right? in this case, what are the expected benefits @ereslibre?

The idea is to improve user upgrade UX by reducing the upgrade to the same command on every node. The flow would look like:

1. User runs `kubeadm upgrade apply vX.Y` on the first control plane
2. User runs `kubeadm upgrade apply (v.X.Y) [optional]` on the rest of control planes and on workers

The idea is that if we want to go down that route, on the first step we could perform several extra checks:

* List all nodes (control planes and workers) using the API, if there's any schedulable kubelet with `version < X.(Y - 2)`, reject the upgrade. Ignore unschedulable kubelets for the purpose of having "under investigation" machines while allowing the rest of the cluster to move forward.

* List all control planes using the API, if there's any control plane with `version < ClusterConfiguration.KubernetesVersion`, reject the upgrade. This ensures that all control planes first move to `X.Y` before attempting a second bump to `X.(Y+d)`.

How the current version of a node is defined depends on the role of the node, but one way would be to get the current version of the `apiserver` in control planes, and the `kubelet` version in worker nodes. This could be retrieved using the API, so cluster-wide checks can be performed while keeping actions local as usual in kubeadm.

The UX is improved because `kubeadm upgrade apply` is the only command required to upgrade all nodes. `kubeadm upgrade apply` would behave as follows:

* `kubeadm upgrade apply vX.Y`
  * If `ClusterConfiguration.KubernetesVersion == X.(Y - 1)`, and all nodes are in `X.(Y - 1)`, perform the upgrade, this is the "first control plane" to be upgraded
  * If `ClusterConfiguration.KubernetesVersion == X.Y`, all control planes are at least in `X.(Y - 1)`, and all worker nodes are at least in `X.(Y - 1)` perform the upgrade, this is a "secondary control plane" to be upgraded or a worker node (we can find out locally as it's currently done)

* `kubeadm upgrade apply`
  * This will by default bump the current node to `ClusterConfiguration.KubernetesVersion` if it's newer
  * If it's a control plane it will have to check that all control planes are at least in `X.(Y - 1)` where `X.Y` is `ClusterConfiguration.KubernetesVersion`
  * If it's a worker node it will have to check that all control palnes are in `X.Y` where `X.Y` is `ClusterConfiguration.KubernetesVersion`.

**Comment by neolit123** [comment]
@ereslibre 

having a quick comment to continue the discussion here.
in any case the complexity of this proposal seems KEP worthy.

> If ClusterConfiguration.KubernetesVersion == X.(Y - 1), and all nodes are in X.(Y - 1), perform the upgrade, this is the "first control plane" to be upgraded

for the "and all nodes are in X.(Y - 1)" part are you suggesting kubelet version?

> If ClusterConfiguration.KubernetesVersion == X.Y, all control planes are at least in X.(Y - 1), and all worker nodes are at least in X.(Y - 1)

currently the kubeadm commands operate on the cluster (to some limited extend) and on the local node. what mechanic are you suggesting for determining the control-plane versions?

my concern is that we might end up with a single command that has complicated logic that is hard to explain and may confuse the users.
also, currently users need to follow a strict guide for upgrading in any case. this UX improvement will not simplify the same guide much.

what the kubeadm upgrading users really need is the kubeadm operator that @fabriziopandini is working on. passing a single request to the operator in the lines of "upgrade the cluster to X.Y" is the true simplification.

**Comment by ereslibre** [comment]
> in any case the complexity of this proposal seems KEP worthy.

Yes, I agree.

> for the "and all nodes are in X.(Y - 1)" part are you suggesting kubelet version?

Yes. On control plane nodes we could also check the Kubernetes control plane components as well.

> what mechanic are you suggesting for determining the control-plane versions of all nodes?

Listing the Kubernetes control plane pods, and reading the tag.

> my concern is that we might end up with a single command that has complicated logic that is hard to explain and may confuse the users.

In the end of the day, either a similar kind of logic would have to be implemented either on kubeadm or on the operator.

> also, currently users need to follow a strict guide for upgrading in any case. this UX improvement will not simplify the same guide much.

Hm, I tend to disagree. I think having a single upgrade command makes thing slightly more convenient. It's not life changing, on that I agree.

> what the kubeadm upgrading users really need is the kubeadm operator that @fabriziopandini is working on. passing a single request to the operator in the lines of "upgrade the cluster to X.Y" is the true simplification.

I agree to some extent. As said before, some logic needs to be place somewhere. Let's not forget that in principle `kubeadm` will be perfectly usable without the operator. In that spirit, I think that if we implement this logic on `kubeadm` we'll make the manual case slightly better, and at the same time the operator will also be slightly simplified than if this logic was not there.

**Comment by neolit123** [comment]
closing this until we get more user requests for combining the commands.
it seems doable and a nice to have, but also someone has to own the implementation / writing the KEP, tracking the GA command deprecation, updating docs etc.
