### ISSUE TITLE
Kubeadm bazel build does not respect hack/print-workspace-status.sh anymore

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1669]
## Is this a BUG REPORT or FEATURE REQUEST?
/kind bug

## Versions
onmaster

## What happened?
I'm trying to compile kubeadm on master, and the kubeadm binary does not get the version as usual but instead gots a wrong GitVersion:"v0.0.0-master+$Format:%h$"
```
kubeadm version: &version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
```

## What you expected to happen?
kubeadm get the expected version, consistent with hack/print-workspace-status.sh

## How to reproduce it (as minimally and precisely as possible)?
create a buildversion file with the following content
```
export KUBE_GIT_MAJOR=1
export KUBE_GIT_MINOR=15
export KUBE_GIT_VERSION=v1.15.0
export KUBE_GIT_TREE_STATE=clean
export KUBE_GIT_COMMIT=d34db33
```
Set the build version
```
export KUBE_GIT_VERSION_FILE=$working_dir/buildversion
```
then check the version is properly set
```
hack/print-workspace-status.sh
```
then build kubeadm
```
bazel build //cmd/kubeadm
```
and finally check kubeadm got the right version with `kubeadm version`

## Anything else we need to know?
probably this is a regression introduced by https://github.com/kubernetes/kubernetes/pull/78929

/cc @SataQiu 
/cc @rosti 
/cc @yastij 
/priority critical-urgent
/milestone v1.16

**Comment by SataQiu** [comment]
Thanks @fabriziopandini 
`make all WHAT=cmd/kubeadm` can work well.
I'll see if `bazel build //cmd/kubeadm` can work.
