### ISSUE TITLE
Failure to find certificate authority in kubectl generated config due to relative path

### ISSUE THREAD

**Issue by hickeng** [kubernetes/kubeadm#1670]
## What keywords did you search in kubeadm issues before filing this one?
relative path
pki/ca.crt no such file or directory
kubeconfig

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version**: 
```
kubeadm version: &version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.1-117+36b0f83ddceb53", GitCommit:"36b0f83ddceb537ac24a71c7deb9a618d838a402", GitTreeState:"clean", BuildDate:"2019-06-11T07:49:02Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}`
```

**Environment**:
- **Kubernetes version**: 
```Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.1-117+36b0f83ddceb53", GitCommit:"36b0f83ddceb537ac24a71c7deb9a618d838a402", GitTreeState:"clean", BuildDate:"2019-06-11T07:50:07Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.1-117+36b0f83ddceb53", GitCommit:"36b0f83ddceb537ac24a71c7deb9a618d838a402", GitTreeState:"clean", BuildDate:"2019-06-11T07:45:39Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: `n/a`
- **OS**: `VMware Photon OS 3.0`
- **Kernel**: `4.19.52-2.ph3-esx #1-photon SMP Tue Jun 25 16:53:25 UTC 2019 x86_64 GNU/Linux`
- **Others**:

## What happened?
Running kubeadm phase below from `/tmp` reported no such file or directory:
```
/usr/bin/kubeadm init phase mark-control-plane --config=/etc/vmware/wcp/kubeadm.yaml
error execution phase mark-control-plane: failed to create API client configuration from kubeconfig: invalid configuration: unable to read certificate-authority pki/ca.crt for kubernetes due to open pki/ca.crt: no such file or directory
```

## What you expected to happen?
Success

## How to reproduce it (as minimally and precisely as possible)?
```
# KUBECONFIG=/etc/kubernetes/admin.conf /usr/bin/kubectl config set-cluster kubernetes --certificate-authority="/etc/kubernetes/pki/ca.crt"
Cluster "kubernetes" set.
# /usr/bin/kubeadm init phase mark-control-plane
I0715 17:06:35.943443   23775 version.go:237] remote version is much newer: v1.15.0; falling back to: stable-1.13
error execution phase mark-control-plane: failed to create API client configuration from kubeconfig: invalid configuration: unable to read certificate-authority pki/ca.crt for kubernetes due to open pki/ca.crt: no such file or directory
```

## Anything else we need to know?
https://github.com/kubernetes/kubernetes/issues/75552 notes that the relative path is a deliberate choice, implying that all consumers of the config files need to honor that semantic.

It looks like a documentation note should be added to https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/staging/src/k8s.io/client-go/tools/clientcmd/api/types.go in order to inform users of the config that relative paths require special handling (or update whatever wrapper logic is normally used to consume configs to transform the relative paths appropriately given location of config file).

**Comment by neolit123** [comment]
hi,

the cert authority resulting in a relative path such as:
> certificate-authority: pki/ca.crt

is not a kubeadm problem and a problem in client-go/kubectl:

one option is to re-open https://github.com/kubernetes/kubernetes/issues/75552 using `/reopen` and request documentation using `/kind documentation`. i'm not sure of the best location for this.

on the kubeadm side:
- could you briefly explain the use case of modifying `certificate-authority`?
- you have a couple of workarounds:
  - `sed` an absolute path in there
  - invoke kubectl with a KUBECONFIG that is owned by the regular user - e.g. the one that kubeadm recommends copying to $HOME `sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config`

**Comment by SataQiu** [comment]
```sh
# sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
# kubectl config set-cluster kubernetes --certificate-authority="/etc/kubernetes/pki/ca.crt"
# kubeadm init phase mark-control-plane
```
It works well!

```sh
[root@node-ttnm-bocloud /]# cat ~/.kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://192.168.137.71:6443
  name: kubernetes
...
```

**Comment by neolit123** [comment]
@hickeng i'm going to close this issue as it's not a kubeadm bug.
but we can continue the discussion.
