### ISSUE TITLE
Create a PodDisruptionBudget for CoreDNS

### ISSUE THREAD

**Issue by rmb938** [kubernetes/kubeadm#1672]
## What keywords did you search in kubeadm issues before filing this one?

coredns disruption budget

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Currently when a kubeadm cluster is created there is no PodDisruptionBudget created for CoreDNS. If multiple nodes are drained at the same time this may cause a DNS outage before the CoreDNS pods are restarted. 

A PodDisruptionBudget could prevent this by blocking a node from draining and keeping at least 1 CoreDNS pod alive.

## Versions

**kubeadm version** (use `kubeadm version`):

`
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
`

**Environment**:
- **Kubernetes version** (use `kubectl version`):

`
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
`

- **Cloud provider or hardware configuration**: `bare metal hardware and VMs`
- **OS** (e.g. from /etc/os-release): `CentOS 7`
- **Kernel** (e.g. `uname -a`): `Linux apslp1559 5.1.2-1.el7.elrepo.x86_64 #1 SMP Tue May 14 18:19:37 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
`

## What happened?

No PodDisruptionBudget created for CoreDNS

## What you expected to happen?

A PodDisruptionBudget created for CoreDNS

## How to reproduce it (as minimally and precisely as possible)?

`kubeadm init`

**Comment by neolit123** [comment]
> If multiple nodes are drained at the same time this may cause a DNS outage before the CoreDNS pods are restarted.

with the current tollerations, the coredns pods will prefer the worker nodes, but can still schedule on a control-plane node if no other nodes are available.

were you able to see a case were the above does not work and coredns pods do not schedule at all after worker drain?

to me PDB and PSP fall under the same bucket of higher level customization that i'm really hesitant about enabling by default and i'd prefer if we leave that to the operator.

but let's see what others think too.
@kubernetes/sig-cluster-lifecycle 

/priority awaiting-more-evidence
/kind feature
/area ecosystem

**Comment by rmb938** [comment]
So it's more along the lines of if I have a CoreDNS deployment of 2 pods and I drain the 2 nodes they are on at the same time. Without a PDB they might be killed at the same time and cluster dns may be broken in the half second or so it will take to start on another node.

If we want this to be under the bucket of higher level customization I am perfectly fine with that as well.

**Comment by neolit123** [comment]
so i investigated this a little i think i found that PDB can be buggy in 1.15.1, or at least i cannot explain what is going on.

say, if you drain a couple of nodes that each host a coredns pod, one of the coredns pod will get evicted and restarted, but then the second pod can get stuck in Pending with this loop:
> error when evicting pod "coredns-5c98db65d4-cclp7" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.

the PDB status also gets stuck with:
```
  currentHealthy: 1
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 2
  observedGeneration: 1
```

at this point the `  disruptionsAllowed: 0` rule, prevents you from even restarting the Pending coredns pod.

deleting the PDB does not fix that!

deleting all coredns objects and the pod network, re applying the coredns objects and the pod network still gets the coredns pods stuck at Pending!

the Pods event logs show:
>   Warning  FailedScheduling  32s (x3 over 34s)  default-scheduler  0/1 nodes are available: 1 node(s) were unschedulable.

playing with node-selections, taints and tolerations in the coredns Deployment does not fix the problem and it feels as if the PDB left some sort of a "state" blocking the coredns Deployment from ever rescheduling.

my solution at that point was to restart the cluster.
there might be something else to hack and fix it, but this is quite "disruptive" (pun intended).

after this investigation it seems that we actually shouldn't enable PDB and that there are critical bugs at play here.

**Comment by neolit123** [comment]
something to add is that this breakage only happens when using `kubectl drain`.

for `kubectl delete` on the coredns Pods, the PDB still attempts to manage the Pods of the Deployment it's attach to, but it fails to, and there are cases of:

```
  currentHealthy: 0
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 2
```

then after a while both Pods restart:
```
  currentHealthy: 2
  desiredHealthy: 1
  disruptionsAllowed: 1
  expectedPods: 2
```

this particular case also invalidates the usage of PDB, as `currentHealthy: 0` defeats it's purpose.

**Comment by neolit123** [comment]
xref
https://github.com/kubernetes/kubernetes/issues/72320
https://github.com/kubernetes/kops/issues/2537

**Comment by neolit123** [comment]
moving to Next milestone.

**Comment by neolit123** [comment]
i'm going to close this issue. with CoreDNS moving outside of kubeadm in the future as an addon for an addon installer maybe it can be added there. from my tests above it seemed that PDB can be a bit problematic.

**Comment by rdxmb** [comment]
> with the current tollerations, the coredns pods will prefer the worker nodes

Really? Is this still the case? I cannot find the definition for that with kubernetes 1.21

**Comment by neolit123** [comment]
Having both pods on the first cp node is expected. If that is not the
desired behavior in your use case you can skip the kubeadm coredns or apply
the desired (anti)affinity and pdb extensions over the stock kubeadm one.

**Comment by rdxmb** [comment]
Ok I will try to do that. Thanks
