### ISSUE TITLE
Recreate the cluster after reseting it

### ISSUE THREAD

**Issue by smaillns** [kubernetes/kubeadm#1674]
I have executed `kubeadm reset` on the master node, I've got this error while trying to recreate the cluster 

> 	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

I tried to delete the config file in `$HOME/.kube/config` but still having the same error

NB: I don't want to use `--ignore-preflight-errors=All` in order to avoid possible problems

Thanks

**Comment by SataQiu** [comment]
Thanks @smaillns 
It is a bug! And it has been fixed by kubernetes/kubernetes#79331
Ref: #1642

**Comment by smaillns** [comment]
How can I remove all kubeadm configuration files including token list ?

**Comment by SataQiu** [comment]
Remove the etcd folder (`/var/lib/etcd`) before run `kubeadm init`

**Comment by neolit123** [comment]
closing as fixed for 1.15.x in kubernetes/kubernetes#79331
please feel free to continue the discussion.

> Remove the etcd folder (/var/lib/etcd) before run kubeadm init

+1.
