### ISSUE TITLE
Improve customisation of kubeadm pause container

### ISSUE THREAD

**Issue by sysrich** [kubernetes/kubeadm#1675]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-23T12:00:00Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-23T12:00:00Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
KVM Virtual Machine 2 cores 8GB RAM

- **OS** (e.g. from /etc/os-release):
NAME="openSUSE MicroOS"
VERSION="20190713"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20190713"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20190713"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"

- **Kernel** (e.g. `uname -a`):
Linux g177 5.1.16-1-default #1 SMP Wed Jul 3 12:37:47 UTC 2019 (2af8a22) x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
In openSUSE Kubic we are moving towards using our own built and hosted k8s containers with kubeadm instead of those hosted on k8s.gcr.io

This means we are starting to run `kubeadm` with `--image-repository` defined, or the with our own config file with `imageRepository` defined

However, it appears that the version of the Pause container is hard coded:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L264

Therefore kubeadm tries to download the container from our.registry.com/pause:3.1 instead of the version we actually have in our registry.

In our case we use CRI-O as our container runtime, or podman when we're not using k8s. In both cases, both runtimes can configure the pause container to use for their pods (see: https://github.com/cri-o/cri-o/blob/master/docs/crio.conf.5.md)

Therefore the current kubeadm behaviour leads to a very weird and buggy situation, where `kubeadm config images pull --image-repository our.registry.com` tries to pull `our.registry.com/pause:3.1`. This obviously fails because our pause container isn't at version 3.1

But even if we make it work, any subsequent pods, including the pods for etcd and coredns created by kubeadm, use the `pause_container` defined in our container runtime.
This secondary behaviour also seems very wrong and buggy to me.

Therefore I'd like to propose a number of possible solutions

1. Our Ideal - Provide a capability in kubeadm to stop using a hardcoded pause container version and instead defer to consistently use the pause container defined in the container runtime.
2. Less ideal - Provide a runtime & config parameter to be able to define the pause container version used in kubeadm so we could at least craft a config that `kubeadm init` would pull the same pause container we're going to use after the init

Without either 1. or 2. we're going to need to resort to injecting a fake "3.1" version tag to our pause container, which would be a lie given our pause container isn't at version 3.1 ;)

Or we'll need to distro-patch constants.go, which we'd also like to avoid given there will be times we'd prefer to use the kubeadm defaults.

Thanks in advance

**Comment by neolit123** [comment]
> This obviously fails because our pause container isn't at version 3.1

hm, what version does it have? is it a custom build or possibly based on https://github.com/kubernetes/kubernetes/tree/master/build/pause but with modifications?
why not use the k8s pause:3.1?

kubeadm expects the pause container that the Kubernetes project maintains, you just have the alternative to host it in a repository of your choice.

> Without either 1. or 2. we're going to need to resort to injecting a fake "3.1" version tag to our pause container, which would be a lie given our pause container isn't at version 3.1 ;)

that's actually a very viable solution, because as mentioned above, kubeadm is essentially looking for the latest Kubernetes "approved" pause container.

> But even if we make it work, any subsequent pods, including the pods for etcd and coredns created by kubeadm, use the pause_container defined in our container runtime.

the pre-pull of the pause image that kubeadm does is just to conform the kubelet in air-gaped scenarios.
it's up to the kubelet to manage the sandbox and a pause container next to a component container.

> Our Ideal - Provide a capability in kubeadm to stop using a hardcoded pause container version and instead defer to consistently use the pause container defined in the container runtime.

we discussed custom tags/version for images like coredns, pause, etc at some point but this idea was rejected because it can create a difficult to maintain situation with upgrades.

cc @rosti @bart0sh 
who contributed to the most recent logic there.

**Comment by sysrich** [comment]
@neolit123 thanks for the explanations and clarifications :) based on what we've now learned, we're actually going to be producing 'not fake' version 3.1'd versioned pause containers

Somewhere along the line we'd introduced our own versioning thinking we were using different sources than the pause.c from gh/k8s/k8s..but on analysis we're more aligned with upstream than we thought..and that's just how we like it.

We don't need kubeadm to change anything, thanks again for being so helpful :)

**Comment by neolit123** [comment]
> We don't need kubeadm to change anything, thanks again for being so helpful :)

no problem. thanks for confirming!
