### ISSUE TITLE
kubeadm on Fedora 30 with containerd and flannel is (surprisingly badly) broken

### ISSUE THREAD

**Issue by vorburger** [kubernetes/kubeadm#1677]
kubeadm on Fedora 30 with containerd and Flannel doesn't work, and is (surprisingly badly) broken.

I've done some investigation, and found at least two separate major issues:

1. Pointing to https://bugzilla.redhat.com/show_bug.cgi?id=1731597 re. /opt/cni/bin VS /usr/libexec/cni/bridge disprecancy in Fedora's containerd and containernetworking-plugins packages.

2. Pointing to https://github.com/coreos/flannel/issues/1164 re. Services not working on Flannel just in case this kind of things gets more attention here than there (Flannel's Issues and PRs don't seem to be attended to?). Or is there a better place to raise that kind of thing?

More out of curiosity than really have time to contribute to something like this (or would I perhaps...), I was wondering if the project (`kubeadm`), or some other place in the Kubernetes community, doesn't run automated tests which exercise `kubeadm` and then runs some sanity test suite (does that exist?) where both of these problems should have been discovered?

**Comment by fabriziopandini** [comment]
@vorburger thanks for this issue.
Are you installing official kubernetes-cni package? as far as I understand the root of your problems is the CNI stuffs are not getting installed in the right place...

**Comment by jackadam1981** [comment]
[ERROR SystemVerification]: unsupported kernel release: 5.0.9-301.fc30.x86_64


[root@localhost ~]# kubeadm init
I0722 22:30:54.123100    1286 version.go:94] could not fetch a Kubernetes versio                                                                                                                                                             n from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt":                                                                                                                                                              Get https://dl.k8s.io/release/stable-1.txt: net/http: request canceled while wa                                                                                                                                                             iting for connection (Client.Timeout exceeded while awaiting headers)
I0722 22:30:54.123414    1286 version.go:95] falling back to the local client ve                                                                                                                                                             rsion: v1.13.5
[init] Using Kubernetes version: v1.13.5
[preflight] Running pre-flight checks
        [WARNING Firewalld]: firewalld is active, please ensure ports [6443 1025                                                                                                                                                             0] are open or your cluster may not function correctly
[preflight] The system verification failed. Printing the output from the verific                                                                                                                                                             ation:
KERNEL_VERSION: 5.1.18-300.fc30.x86_64
CONFIG_NAMESPACES: enabled
CONFIG_NET_NS: enabled
CONFIG_PID_NS: enabled
CONFIG_IPC_NS: enabled
CONFIG_UTS_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_CPUSETS: enabled
CONFIG_MEMCG: enabled
CONFIG_INET: enabled
CONFIG_EXT4_FS: enabled
CONFIG_PROC_FS: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_AUFS_FS: not set - Required for aufs.
CONFIG_BLK_DEV_DM: enabled
DOCKER_VERSION: 1.13.1
DOCKER_GRAPH_DRIVER: overlay2
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR SystemVerification]: unsupported kernel release: 5.1.18-300.fc30.                                                                                                                                                             x86_64
[preflight] If you know what you are doing, you can make a check non-fatal with                                                                                                                                                              `--ignore-preflight-errors=...`

use  --ignore-preflight-errors?

**Comment by neolit123** [comment]
> [ERROR SystemVerification]: unsupported kernel release: 5.0.9-301.fc30.x86_64

this was fixed in 1.14:
https://github.com/kubernetes/kubernetes/commit/148b222d97e1ef8b1cc45bc2dbcb04014c0783c0

for 1.13 you need `--ignore-preflight-errors=` for this error.

**Comment by neolit123** [comment]
> Pointing to https://bugzilla.redhat.com/show_bug.cgi?id=1731597 re. /opt/cni/bin VS /usr/libexec/cni/bridge disprecancy in Fedora's containerd and containernetworking-plugins packages.

seems like something Fedora package maintainers should fix.

the official k8s Fedora/CentOS packages:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
use /opt/cni/bin.

if you think the official k8s package have a problem please file an issue in the kubernetes/release repository.

here is the spec:
https://github.com/kubernetes/release/blob/master/rpm/kubelet.spec#L132

> Pointing to coreos/flannel#1164 re. Services not working on Flannel just in case this kind of things gets more attention here than there (Flannel's Issues and PRs don't seem to be attended to?). Or is there a better place to raise that kind of thing?

flannel is not maintained actively.
kubeadm supports a number of CNI plugins:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

the easiest to install is WeaveNet.

**Comment by neolit123** [comment]
closing as not a kubeadm bug.

if there is something we can do for our packages, please log a ticket for kubernetes/release as that is the repository that hosts the specs:
https://github.com/kubernetes/release/blob/master/rpm/kubelet.spec
