### ISSUE TITLE
Self-hosting should use a file lock

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#168]
See: https://github.com/kubernetes-incubator/bootkube/pull/264 and https://github.com/kubernetes-incubator/bootkube/issues/262

Currently kubeadm does not use a flock when deploying in self-hosted mode.
And we can't rely on the `flock` binary being in the container: https://github.com/kubernetes/kubeadm/issues/167

cc @pires @errordeveloper @aaronlevy

**Comment by luxas** [comment]
Related PR where I discovered this: https://github.com/kubernetes/kubernetes/pull/41400

**Comment by pires** [comment]
You can rely on your fix of the flock usage for now and until we have a better solution in place, which I believe won't be in the form of a file-lock, given we won't have access to any other binaries other than the apiserver, for instance, and I'm not seeing such code getting in.

**Comment by jamiehannaford** [comment]
Bootkube are considering [removing this](https://github.com/kubernetes-incubator/bootkube/pull/616) because the self-hosted apiserver will eventually come up after the pivot, even without a flock

**Comment by luxas** [comment]
@jamiehannaford Thanks for pointing that out; would be awesome if we waited that thing out.
I had a lot of issues with trying to implement it; different flock binaries for different base images for the control plane for example... adding the right mounts and making sure things race well is quite hard.

Anyway, I can also confirm that selfhosting seems to work well without the flock...

**Comment by luxas** [comment]
cc @aaronlevy Can we close this?

**Comment by aaronlevy** [comment]
We're likely going to remove the flock (but hasn't merged quite yet). Can close, or if you want to wait till it's merged, fine too. 

flock was mostly an optimization during bootstrap: the pivot could take as long as the exponential backoff retry period to retry starting the apiserver -- which was annoying in some cases (and shows a high restart count at the end of bootstrap). But as long as kubelet doesn't go down, it will start the apiserver eventually. It also sort of helps with checkpointing, but isn't actually necessary with current behavior.

**Comment by luxas** [comment]
Ok, then I'm closing... Thanks!
