### ISSUE TITLE
Single-node kubeadm lost after machine shutdown (bare-metal)

### ISSUE THREAD

**Issue by staticdev** [kubernetes/kubeadm#1683]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: Bare-metal
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
- **Kernel** (e.g. `uname -a`): 4.15.0-54-generic
- **Others**: -

## What happened?
I configured a single-node kubeadm with the instructions [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/). Everything was working until my machine shutdown. When it restated kubectl wasn't working anymore:

> The connection to the server MYIP:6443 was refused - did you specify the right host or port?

Also I couldn't `sudo kubeadm init` anymore:
```
[init] Using Kubernetes version: v1.15.1
[preflight] Running pre-flight checks
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[ERROR Swap]: running with swap on is not supported. Please disable swap
	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

## What you expected to happen?
Having a wait to restore node state before restart.

## How to reproduce it (as minimally and precisely as possible)?
```sh
   sudo kubeadm init --pod-network-cidr=192.168.0.0/16
   mkdir -p $HOME/.kube
   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
   sudo chown $(id -u):$(id -g) $HOME/.kube/config
   kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
   kubectl taint nodes --all node-role.kubernetes.io/master-
   reboot #wait
   kubectl get all
```
## Anything else we need to know?
-

**Comment by rosti** [comment]
Hi @staticdev and thank you for filing this issue!

Can you check that kubelet is running on your system and if it has error messages in its log?
Also, can you verify, that you have a `k8s_` prefixed containers running?
Last, but not least, are you sure, that your machine did not have its IP changed?

/priority awaiting-more-evidence

**Comment by timothysc** [comment]
Please run: 
`sudo systemctl enable kubelet` 

I suspect you have no enabled all your system services needed.

**Comment by timothysc** [comment]
Also in order for you to be able to run init again you need to run 

`kubeadm reset`

**Comment by pytimer** [comment]
Did you enabled the swap?

**Comment by SataQiu** [comment]
@staticdev 
In my view, you should turn the swap off :
```sh
$ sudo swapoff -a  
$ sudo sed -i '/ swap / s/^/#/' /etc/fstab
```
Ref: https://www.tecmint.com/disable-swap-partition-in-centos-ubuntu/

**Comment by staticdev** [comment]
@rosti my containers from k8s weren't running.

@timothysc  systemctl kubelet service wasn't indeed enabled, the [documentation](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/) didn't tell I had to enable that, it would be a nice note addition.

@SataQiu after I enabled kubelet I realized there were an error in the service related to this pre-flight-check. I also had to comment swap partitions on fstab.

Now everything works, but I think documentation needs to be improved to have these instructions.

**Comment by neolit123** [comment]
>  systemctl kubelet service wasn't indeed enabled, the documentation didn't tell I had to enable that, it would be a nice note addition.

kubelet setup is part of installing kubeadm:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

>after I enabled kubelet I realized there were an error in the service related to this pre-flight-check. I also had to comment swap partitions on fstab.

swap can be distro specific.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
has:
> Swap disabled. You MUST disable swap in order for the kubelet to work properly.

thanks.
/close
