### ISSUE TITLE
[kubeadm] Network Config E2E Tests

### ISSUE THREAD

**Issue by Arvinderpal** [kubernetes/kubeadm#1686]
FEATURE REQUEST

Kubeadm e2e tests currently do not test that network configuration values specified by the user are correctly configured in the cluster. 

This is a tracker issue for the tests that check the following config parameters in kubeadm:

- [x] `pod-network-cidr` PR: https://github.com/kubernetes/kubernetes/pull/80259
- [x] `service-cluster-ip-range` PR: https://github.com/kubernetes/kubernetes/pull/80259
- [ ] `allocate-node-cidrs`
- [ ]  `node-cidr-mask-size`

CC:
@fabriziopandini @neolit123 @yastij

**Comment by neolit123** [comment]
Dual stack is going ga in 1.23 - this release. Dual stack is already covered in a number of e2e tests. Closing this as it feels like higher level setups can test / or sig network.

Please reopen if you think something else can be done here.
