### ISSUE TITLE
Utilize client credentials from discovery file if present during join

### ISSUE THREAD

**Issue by hickeng** [kubernetes/kubeadm#1687]
## What keywords did you search in kubeadm issues before filing this one?
file-discovery
anonymous
bootstrap

## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

During file-discovery based join workflow, allow use of client credentials from the discovery file in place of the bootstrap token.

This is in support of environments where a secure means of providing client certificate to candidate nodes exists and anonymous auth is undesirable.

For example, have a dedicated phase `kubeadm join phase control-plane-prepare client-cert` that uses the bootstrap token to acquire a client cert for use during the remainder of the bootstrap workflow.

Then in the case of an environment where the discovery file contains client credentials we can use the following:
```
kubeadm join --skip-phases client-cert
```

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:39:35Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:39:35Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: `kind 0.4.0`
- **OS** (e.g. from /etc/os-release): `"Ubuntu 18.04.2 LTS"`
- **Kernel** (e.g. `uname -a`): `Linux dev 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

## What happened?
Attempted to use file-discovery with a valid client cert as credentials instead of using a bootstrap token. Client credentials are ignored:
```
root@a337d802c79e:/kind# kubeadm --config=/kind/kubeadm.conf join help --ignore-preflight-errors=all
[preflight] Running pre-flight checks
        [WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
        [WARNING Swap]: running with swap on is not supported. Please disable swap
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 4.15.0-50-generic
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
        [WARNING SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/4.15.0-50-generic\n", err: exit status 1
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: failed to get config map: configmaps "kubeadm-config" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

## What you expected to happen?
Successful join, or at least not failing to to RBAC issues given client cert credentials are for a user with sufficient access to perform the bootstrap workflows. 

## How to reproduce it (as minimally and precisely as possible)?
Run join workflow using file-discovery with client cert present, without providing valid bootstrap token.

## Anything else we need to know?
Somewhat related: kubernetes/kubeadm#1384

**Comment by neolit123** [comment]
thanks for logging this ticket.
(i was going back and forth with the labels, but now i have a clearer picture).

there are a couple of items here:

1) we have a bug in our file discovery; i know what is going on here and i can send a fix, but it's a bit tricky.

> error execution phase preflight: unable to fetch the kubeadm-config ConfigMap

/kind bug
/remove-priority awaiting-more-evidence
/priority important-soon
/lifecycle active

2) a feature request to fetch the client credentials on join.

> For example, have a dedicated phase` kubeadm join phase control-plane-prepare client-cert` that uses the bootstrap token to acquire a client cert for use during the remainder of the bootstrap workflow.

> Then in the case of an environment where the discovery file contains client credentials we can use the following:

to clarify the ask, we can use a boostrap token and a new phase to fetch the client cert/key that later can be used in a discovery file instead of the TLS bootstrap tokens to avoid RBAC?

i think this would be equivalent to transferring a kubeconfig that has client-cert/key and the CA to all the nodes. instead of using the phase, the operator should just perform this and turn off the CSR auto-approver for client certs and delete the kubeadm cluster-info config map.

one side effect of this is that the kubelet bootstrap kubeconfig will contain that client cert/key and this information will persist on the node. token bootstrap on the other hand is *much* more secure 
because tokens expire.

> anonymous auth is undesirable.

we are seeing this request recur, but we are yet to understand the motivation; could you please explain yours? 

currently `--anonymous-auth=false` will also fail the static pod probe checks and there are a few issues in k/k that talk about that, such as:
https://github.com/kubernetes/kubernetes/issues/51076#issuecomment-413137267

it was discussed a number of times that `--anonymous-auth=false` is not really solving any security problems and that RBAC is the preferred auth method for k8s.

**Comment by fabriziopandini** [comment]
@hickeng @neolit123 
it seems that the implementation already deviated from the original design (without updating any doc :neutral_face:). See https://github.com/kubernetes/kubernetes/pull/66482
However, looking at the code, this works only if the user credentials are provided via Client Certificates....

**Comment by hickeng** [comment]
@neolit123 

> i think this would be equivalent to transferring a kubeconfig that has client-cert/key and the CA to all the nodes.

Yes - but currently you cannot use that kubeconfig with client-cert/key for `join control-plane`. Re-phrasing the ask for clarity - I want to be able to use a client-cert/key with kubeadm to perform a control-plane prepare/join, including /download-certs. I don't care about worker nodes at this time.

Getting a client cert into place via a CSR workflow is much less fraught than copying the full set of certs&keys around out-of-band given kubeadm already provides a means to do just that.

> currently --anonymous-auth=false will also fail the static pod probe checks and there are a few issues in k/k that talk about that

Correct, but already resolved in this environment using a node local bearer token. We _should_ open a kubeadm PR with the switch to a secure liveliness probe, however for now it's not directly integrated into kubeadm code.

> it was discussed a number of times that --anonymous-auth=false is not really solving any security problems and that RBAC is the preferred auth method for k8s.

From a technical standpoint I think it's debatable. Personally I am inclined towards defense in depth and not assuming that k8 admins will do, or even know to do, the right thing with RBAC in the cluster. This likely keeps coming up not only because the technical point is debatable, but also because of existing policy and process constraints which are often harder to change than implementation.

**Comment by fabriziopandini** [comment]
@hickeng a fix is merging that address the problem without changes to the UX

**Comment by neolit123** [comment]
closing as the PR merged in k/k.
