### ISSUE TITLE
Delete bootstrap-kubelet.conf after TLS bootstrap

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1689]
when doing `kubeadm join`, kubeadm creates the `bootstrap-kubelet.conf` for kubelet start the TLS bootstrap process.
After completing the TLS bootstrap process kubelet switches to use the `kubelet.conf`, but the `bootstrap-kubelet.conf` remains on disk even if not necessary anymore.

Considering that `bootstrap-kubelet.conf` contains authorization credentials that kubeadm generates (tokens) or the users pass via the discovery file, it will be nice to delete this file avoiding to let authorization credential on the disk when not necessary

**Comment by neolit123** [comment]
@akekorrakot you reacted with a :confused: emoji on the ticket description.
do you have feedback for us?

**Comment by neolit123** [comment]
closing as the main PR for this merged.
there is a followup to use `defer` https://github.com/kubernetes/kubeadm/issues/1699
