### ISSUE TITLE
kubeadm should warn about invalid api-server extra args

### ISSUE THREAD

**Issue by olivierlemasle** [kubernetes/kubeadm#1690]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

    kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:15:32Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

      Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Vagrant / virtualbox
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- **Kernel** (e.g. `uname -a`): `Linux stretch 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux`

## What happened?

When an invalid extra flag is passed to api-server, the api-server pod fails and loops in error. `kubeadm` does not detect the error in preflight, and fails only after 4-minutes timeout.

<details><summary>Kubadm logs</summary>

    [kubeconfig] Using kubeconfig folder "/etc/kubernetes"
    [kubeconfig] Writing "admin.conf" kubeconfig file
    [kubeconfig] Writing "kubelet.conf" kubeconfig file
    [kubeconfig] Writing "controller-manager.conf" kubeconfig file
    [kubeconfig] Writing "scheduler.conf" kubeconfig file
    [control-plane] Using manifest folder "/etc/kubernetes/manifests"
    [control-plane] Creating static Pod manifest for "kube-apiserver"
    [control-plane] Creating static Pod manifest for "kube-controller-manager"
    [control-plane] Creating static Pod manifest for "kube-scheduler"
    [etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
    [wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
    [kubelet-check] Initial timeout of 40s passed.

    Unfortunately, an error has occurred:
    	timed out waiting for the condition

    This error is likely caused by:
    	- The kubelet is not running
    	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

    If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
    	- 'systemctl status kubelet'
    	- 'journalctl -xeu kubelet'

    Additionally, a control plane component may have crashed or exited when started by the container runtime.
    To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
    Here is one example how you may list all Kubernetes containers running in docker:
    	- 'docker ps -a | grep kube | grep -v pause'
    	Once you have found the failing container, you can inspect its logs with:
    	- 'docker logs CONTAINERID'
    error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster

</details>

<details><summary>API Server logs</summary>

      Error: unknown flag: --foo
      Usage:
        kube-apiserver [flags]

      Generic flags:
      ...

</details>

## What you expected to happen?

1) I expected `kubeadm` to report a warning in preflight checks, because it is what's documented in https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#preflight-checks

        [warning] if extra arg flags for API server, controller manager, scheduler contains some invalid options

    I don't know if the documentation is obsolete, or if this preflight check was designed and not implemented... Anyway, documentation is not aligned with current behavior.

2) Independently from preflight checks, I'd expect `kubeadm` to fail fast and not waiting for the timeout.

## How to reproduce it (as minimally and precisely as possible)?

`kubeadm init --config config.yaml`, with this config file:

    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        foo: bar

**Comment by neolit123** [comment]
hello and thanks for logging the ticket.

> When an invalid extra flag is passed to api-server, the api-server pod fails and loops in error. kubeadm does not detect the error in preflight, and fails only after 4-minutes timeout.

unfortunately this is currently not possible.

there is a working group in kubernetes called "WG Component Standard" that this issue falls under.
once the API server supports a configuration file with validation this will become possible.

until then there is no good way to validate the unversioned apiserver CLI flags/arguments on the kubeadm side. one possible hack is to have the apiserver binary locally and see if it exits with an error if the same flags are passed before running the apiserver as a Pod with kubeadm.

/close
cc @rosti
