### ISSUE TITLE
Make discovery wait for a finite time

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1693]
Follow up of https://github.com/kubernetes/kubernetes/pull/80675#discussion_r308016782

Currently the discovery logic runs indefinitely and we should change this to fail after a while.
I'd say 10 retries * 5 seconds (DiscoveryRetryInterval) should be enough.

**Comment by fabriziopandini** [comment]
We should be aware that this wait cycle is fundamental for worker nodes waiting for control-plane nodes in case of parallel provisioning, so I think that in this case, we should wait for some minutes (5 minutes might be)

**Comment by olivierlemasle** [comment]
I'd like to work on this.

/assign
