### ISSUE TITLE
include more details about the kubeadm upgrade backup process

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1694]
during upgrade if the process fails on static pods, kubeadm writes a folder called `/etc/kubernetes/backup`.

currently we do not:
- document how this folder works. **WIP**
- have test coverage when kubeadm falls back to a manifest in the backup folder. **EDIT: we have some unit tests for this.**

xref: https://github.com/kubernetes/kubeadm/issues/1617#issuecomment-515967794

**Comment by Klaven** [comment]
I will document this and start working on the test coverage.

**Comment by neolit123** [comment]
adding help-wanted to see if someone wants to take this one.
/help

**Comment by neolit123** [comment]
a PR for this is here:
https://github.com/kubernetes/website/pull/18424/files
