### ISSUE TITLE
E2E Testing Documentation has been invalidated by Testgrid Updates

### ISSUE THREAD

**Issue by chases2** [kubernetes/kubeadm#1695]
The documentation on [managing end-to-end tests](https://github.com/kubernetes/kubeadm/blob/master/docs/managing-e2e-tests.md) in this repository has grown stale as Testgrid has been enhanced.

Specifically:
- "config.yaml" no longer exists; testgrid configurations live in their [own directory](https://github.com/kubernetes/test-infra/tree/master/config/testgrids). Those links are broken.
- Many of the jobs referenced, such as the example file [kubeadm.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm-kind.yaml), now use prow annotations instead of only a YAML Testgrid configuration
- The Testgrid configs pertinent to this doc and repository [should](https://github.com/kubernetes/test-infra/issues/13541) be separated into their own file. If this is done, then the document could be simplified since grepping through a large YAML file isn't needed anymore.

**Comment by neolit123** [comment]
thanks for the reminder @chases2
