### ISSUE TITLE
investigate a problem with the deletion of the upgrade prepull DaemonSet

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1700]
during upgrade multiple people have encountered the following error:
```
[upgrade/prepull] Failed prepulled the images for the control plane components error: unable to cleanup the DaemonSet used for prepulling kube-scheduler: daemonsets.apps "upgrade-prepull-kube-scheduler" not found
```

https://github.com/kubernetes/kubernetes/pull/80798
https://github.com/kubernetes/kubeadm/issues/1603
https://github.com/kubernetes/kubeadm/issues/1546

this is a weird problem because it seems the deamon set was deleted previously and we are trying to delete it twice.

help-wanted:
- investigate why this can happen. @fabriziopandini mentioned that this might be cause if the user aborted the upgrade previously.
- the place to look for this is this file that creates the daemonset "prepuller":
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/prepull.go

**Comment by xlgao-zju** [comment]
> investigate why this can happen. @fabriziopandini mentioned that this might be cause if the user aborted the upgrade previously.

@neolit123 I upgrade my master from 1.12 to 1.13, and then I upgrade it from 1.13 to 1.14. And when I upgrade cluster from 1.13 to 1.14, I get this error. So, cloud this be the reason?

**Comment by xlgao-zju** [comment]
maybe I should `sleep 60`, between the two `kubeadm upgrade apply`?

**Comment by fabriziopandini** [comment]
@neolit123 @xlgao-zju if the use case is upgrades executed in a quick sequence, I'm not sure the fix already merged is correct.

Pre pull DaemonSet were implemented to ensure image in place before upgrades, and thus improve speed/reduce risk of errors/timeout during the most critical part of the update procedure.

If the long tail of the first upgrade deletes pre pull DaemonSet of the second update, we will lose ^^^ and ignoring the error hides the problem without actually fixing it.

Instead, if I got the problem right, my proposal is to add a version suffix to the name of Pre pull DaemonSet so there is no risk of a clash between upgrades executed in a quick sequence

**Comment by xlgao-zju** [comment]
> If the long tail of the first upgrade deletes pre pull DaemonSet of the second update, we will lose ^^^ and ignoring the error hides the problem without actually fixing it.

As you said `thus improve speed/reduce risk of errors/timeout`, I think we should not break the process of upgrading because of the failure of deleting pre pull DaemonSet . Since it is just a method to  ensure image in place before upgrades.

>Instead, if I got the problem right, my proposal is to add a version suffix to the name of Pre pull DaemonSet so there is no risk of a clash between upgrades executed in a quick sequence

Agree, I think we'd better add a suffix to the name of ds. But in a HA cluster, we have more than one master, and we will upgrade them one by one. So, I think just version suffix may be not enough, we can add node name as a part of version suffix too.

**Comment by neolit123** [comment]
> maybe I should sleep 60, between the two kubeadm upgrade apply?

i think the only way to give a definitive answer is to debug the upgrade process.
i remember doing pretty fast upgrades between MINOR versions without delay and i did not encounter this problem.

> If the long tail of the first upgrade deletes pre pull DaemonSet of the second update, we will lose ^^^ and ignoring the error hides the problem without actually fixing it.

the second upgrade process should always ensure it has a DS at disposal even if deleting a stray DS from a previous upgrade.

> Instead, if I got the problem right, my proposal is to add a version suffix to the name of Pre pull DaemonSet so there is no risk of a clash between upgrades executed in a quick sequence

from what i've seen thus far in k8s, version suffixes over resources names can't lead to more problems. before taking further action i really wish us to debug the actual cause.

**Comment by neolit123** [comment]
i've tried reproducing the problem in 1.15 by:
- aborting the upgrade process using ctrl+c and restarting
- disabling the internet during image pre-pull
- reducing the prepull timeout to a very small duration

looking at the source, the only way this could happen is if 
- the user starts the upgrade
- a DS is created for each component to be prepulled
https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/phases/upgrade/prepull.go#L102
- something deletes the DS for a component while the prepull is still active for that component
- the DS for a component is then attempted to be deleted:
https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/phases/upgrade/prepull.go#L120
but it's missing.

so quite frankly, i think the fix we applied is quite sane.
@fabriziopandini i'm reducing the priority of this and tempted to close.

**Comment by fabriziopandini** [comment]
> something deletes the DS for a component while the prepull is still active for that component

If something external interferes with kubeadm probably we should block and report an error instead of recovering, but considering your comment above and the result of your tests I'm ok with closing this and letting the final delete run at best effort

**Comment by neolit123** [comment]
>  I'm ok with closing this and letting the final delete run at best effort

+1
