### ISSUE TITLE
Single node failing ControlPlaneNodesReady upgrading to 1.15.2

### ISSUE THREAD

**Issue by jaredledvina** [kubernetes/kubeadm#1710]
## What keywords did you search in kubeadm issues before filing this one?
ControlPlaneNodesReady
[WARNING ControlPlaneNodesReady]: failed to find any nodes with a control-plane role

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version**: `&version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:20:51Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`  

**Environment**:
- **Kubernetes version**: 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: bare metal
- **OS**: Debian 10 Buster 
- **Kernel**: `Linux foo.bar 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux`

## What happened?
Attempting to upgrade a single node installed on 1.15.1 via https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ to 1.15.3 fails with:
```
root@foo:~# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/health] FATAL: [preflight] Some fatal errors occurred:
        [ERROR ControlPlaneNodesReady]: failed to find any nodes with a control-plane role
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

## What you expected to happen?
`kubeadm upgrade plan` would succeed without errors.

## How to reproduce it (as minimally and precisely as possible)?
I believe this is because of this step during the single node install docs: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation

because (per the docs) I'm supposed to remove the `node-role.kubernetes.io/master-` taint, now `kubeadm upgrade plan` is upset with me. 

## Anything else we need to know?

For folks who discover this issue, simply run:
```
kubeadm upgrade plan --ignore-preflight-errors=ControlPlaneNodesReady
```

That appears to do the trick for me. 

I'd be great if someone from the k8s side could confirm that I do not need this taint on my single master/control-plane node.

**Comment by neolit123** [comment]
hi, is your control-plane node healthy?
what is the output of `kubectl get po -A`?

`kubeadm upgrade` can only work if the node is in a Ready state and the Pods are Running.

**Comment by neolit123** [comment]
> I'd be great if someone from the k8s side could confirm that I do not need this taint on my single master/control-plane node.

removing the taint is required if you want to be able to schedule workloads on this node.

> because (per the docs) I'm supposed to remove the node-role.kubernetes.io/master- taint, now kubeadm upgrade plan is upset with me.

please answer the above kubectl questions and if the node is healthy, i will try to test this myself.

**Comment by neolit123** [comment]
> I'd be great if someone from the k8s side could confirm that I do not need this taint on my single master/control-plane node.

in the single control-plane scenario you have to remove the taint to be able to schedule workloads on this node.

**Comment by jaredledvina** [comment]
Hi @neolit123 - Okay cool, that's what I figured but, figured I should make sure. 

Would it be fair to say that `kubeadm` should skip the `node-role.kubernetes.io/master` taint check if this is a single control-plane configuration?

**Comment by neolit123** [comment]
> Would it be fair to say that kubeadm should skip the node-role.kubernetes.io/master taint check if this is a single control-plane configuration?

possibly.

**Comment by neolit123** [comment]
@ereslibre i'm going to try to send a fix for this today, because i was looking at the same area of the code for something else.

**Comment by ereslibre** [comment]
Thank you @neolit123

**Comment by neolit123** [comment]
@jaredledvina 
it seems the only case where the error:
```
[ERROR ControlPlaneNodesReady]: failed to find any nodes with a control-plane role
```

can be returned is if you next to untainting the node using, e.g.:
```
kubectl taint node <node-name> node-role.kubernetes.io/master-
```
(our official guide recommends `kubectl taint nodes --all node-role.kubernetes.io/master-`)

you also must have unlabeled the node using:
```
kubectl label node <node-name> node-role.kubernetes.io/master-
```

this will leave the control-plane node without a "role" label and the upgrade preflight check indeed has the right to fail.

your workarounds are:
- make sure the node is labeled with a node role
`kubectl label node <node-name> node-role.kubernetes.io/master=`
- or skip the preflight check as already discussed.

thanks.
/close
