### ISSUE TITLE
reject a node joining the cluster if a node with the same name already exists

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1711]
the discussion in https://github.com/kubernetes/kubernetes/issues/79779
revealed that adding multiple nodes with the same name as a control-plane node name can bring the cluster down.

while this can be considered an operator mistake, given k8s does not support nodes with the same name, kubeadm should take action on preventing the bootstrap of such nodes on `kubeadm join` time.

**Comment by RA489** [comment]
@neolit123 can i work on this?

**Comment by neolit123** [comment]
@RA489 
i've just sent a PR for it. please have a look at some of the help-wanted items if you can.

**Comment by RA489** [comment]
@neolit123 Thanks!
