### ISSUE TITLE
Remove dependency on pkg/kubeapiserver/authorizer/modes

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1713]
Same as https://github.com/kubernetes/kubernetes/pull/80307, but on `manifests_test.go`
Might be worth a check if something else is missing...

**Comment by bart0sh** [comment]
sorry, my bad. I forgot about _test.go files in my previous PR. I hope #81084 fixes this.

**Comment by neolit123** [comment]
commented here:
https://github.com/kubernetes/kubernetes/pull/81084#discussion_r311632092

i wonder why this import is not in the import-restrictions file.

**Comment by neolit123** [comment]
related PR merged.
