### ISSUE TITLE
Kubeadm upload component configuration from file to configmap

### ISSUE THREAD

**Issue by jfbai** [kubernetes/kubeadm#1718]
**What would you like to be added**:

Upload kubelet configs from file to configmap, something like,

`kubeadm config upload from-file --component-configs KubeletConfiguration --config kubeadm-kubelet.yaml`

```kubeadm-kubelet.yaml
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
systemReserved:
  cpu: "500m"
    memory: "200M"
systemReservedCgroup: "/system.slice"
cgroupDriver: "systemd"
```

**Why is this needed**:

In order to maintain kubelet config in a consistent way by kubeadm, from upload to download.

**Comment by neolit123** [comment]
thanks for moving the ticket here @jfbai

**Comment by neolit123** [comment]
@jfbai hi, would this ticket also cover KubeProxyConfiguration?

**Comment by jfbai** [comment]
> @jfbai hi, would this feature request also cover KubeProxyConfiguration?

@neolit123 IMO, it would be better to cover KubeProxyConfiguration, so that user can update the `kube-proxy` configMap via kubeadm as well. :)

**Comment by Klaven** [comment]
@jfbai Thanks for this info!

I believe that `kubeadm config upload from-file` has been deprecated as you can see here https://github.com/kubernetes/kubeadm/issues/988 

That being said this command does exist:
`kubeadm init phase upload-config kubelet --config kubeadm.yaml ` and I think it does what you where asking.

I could add a `kube-proxy` command to the `init phase upload-config` to enable the uploading of kube-proxy config files. @neolit123 and @jfbai what do you think?

**Comment by jfbai** [comment]
> @jfbai Thanks for this info!
> 
> I believe that `kubeadm config upload from-file` has been deprecated as you can see here #988
> 
> That being said this command does exist:
> `kubeadm init phase upload-config kubelet --config kubeadm.yaml ` and I think it does what you where asking.
> 
> I could add a `kube-proxy` command to the `init phase upload-config` to enable the uploading of kube-proxy config files. @neolit123 and @jfbai what do you think?

@Klaven Thanks for this info as well. I missed the previous issue.

`kubeadm init phase upload-config kubelet --config kubeadm.yaml` is actually what I need.

BTW, Could I try to add `kube-proxy` command to the codebase, I'm trying to make contributions in kubernetes project.

**Comment by Klaven** [comment]
@jfbai Sure! Have fun! and feel free to reach out if you need any help!

**Comment by neolit123** [comment]
> BTW, Could I try to add kube-proxy command to the codebase, I'm trying to make contributions in kubernetes project.

kube-proxy and addon management might be moving outside of the responsibility of kubeadm into a "addon manager" of sorts, so we rather not add this command until the picture related to addons is more clear.

**Comment by neolit123** [comment]
i'm going to close the ticket as your can easily achieve ConfigMap update today with kubectl commands too. :)

thanks.
/close

**Comment by jfbai** [comment]
@Klaven and @neolit123 thanks a lot. Then this issue can be closed.

**Comment by KevinTHU** [comment]
@neolit123 Although ConfigMap could be updated by kubectl, but the consistency between ConfigMap and kubeadm.yaml is maintained by human, and this is not reliable. If we want to create a new cluster, the kubeadm.yaml maybe outdated, some additional manual work need to be done.

**Comment by neolit123** [comment]
the future of kubeadm managing component config for kube-proxy is unclear. kube-proxy might be becoming the responsibility of an addon manager, while `kubeadm init phase upload-config kubelet` is an already existing solution for the kubelet.

**Comment by KevinTHU** [comment]
@neolit123 thanks, I see. but if kube-proxy is installed by kubeadm,  I think it should be updated by kubeadm also, after all kube-proxy is not like a pure add-ons, the initialization of cluster need it. But anyway, just an advise, hope for the final decision.
