### ISSUE TITLE
fix static check failures for cmd/kubeadm

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1719]
this PR will add static checking of the kubernetes/kubernetes repository:
https://github.com/kubernetes/kubernetes/pull/81189

mini-guide:
- wait for https://github.com/kubernetes/kubernetes/pull/81189 to merge.
- clone kubernetes/kubernetes or fetch the latest master.
- modify the file `./hack/.staticcheck_failures` to exclude all `cmd/kubeadm/*` entries.
- run `./hack/verify-staticcheck.sh`.
- look at the problems the check returns a send a PR to kubernetes/kubernetes to fix them.

/kind bug
/priority backlog
/help
/milestone v1.16

**Comment by RA489** [comment]
@SataQiu Are you working on this?

**Comment by SataQiu** [comment]
@RA489 Yes, I am waitting for kubernetes/kubernetes#81189 to merged, then I will fix this.

**Comment by RA489** [comment]
@SataQiu Thanks For the update.

**Comment by neolit123** [comment]
@SataQiu 
the linked PR merged.

**Comment by SataQiu** [comment]
OK ! thanks @neolit123 I will do this.
