### ISSUE TITLE
v1beta3: make kubeadm types better support CRDs

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1727]
EDIT: neolit123

issue repurposed to track the addition of +optional tags.
ObjectMeta is now out of scope for the time being.

PR:
https://github.com/kubernetes/kubernetes/pull/101925

---

users such as `kind` or those that apply kustomize patches over the kubeadm config types need to manually add:
```
metadata:
  name: config
```
to your types in serialized form as kustomize requires them.

however this later results in strict unmarshal errors (warnings) when the same types are fed into kubeadm because "metadata" is not a known field.

this can be resolved if we start embedding ObjectMeta in the types.

this seems to be a quirk of the ecosystem (kustomize) and while our types are not really "API" types (more of a component-config), it seems reasonable to make the change.

also i think @fabriziopandini already said that this seems OK to him.
(please correct me if needed)

alternatively a subset of ObjectMeta via a custom type can work too, but i will prefer the full type even if we don't need most of the fields.

---

ComponentConfig ObjectMeta KEP:
https://github.com/kubernetes/enhancements/pull/1816

**Comment by rosti** [comment]
The only field we can make use of is the `name` field. Everything else is targeted into, either supporting the object type by the API server, or supporting multiple instances of that object.
In particular, the `name` field is meant to distinguish multiple instances of the object type (described in `TypeMeta`).
For some of the types (notably, `InitConfiguration` and `JoinConfiguration`) it may be appropriate to distinguish multiple different objects, based not on `metadata.name`, but on `nodeRegistration.name` (after all, that value will be used for the Node object's `metadata.name` value).
`ClusterConfiguration` is a completely different thing. You don't expect more than one of these in a cluster. Hence, it's a "singleton" and having a separate `metadata.name` field is a bit senseless.

If the only user of `metadata.name` is kustomize, then I do believe, that there is a workaround that. Kustomize supports redirecting that field to something else, hence users can redirect it to `nodeRegistration.name` for `InitConfiguration` and `JoinConfiguration`, and to `kind` for `ClusterConfiguration`.

Hence, I don't like the idea of adding a full blown ObjectMeta to types, that are opaque to the API server and usually stored in files and config maps.

**Comment by neolit123** [comment]
> Hence, I don't like the idea of adding a full blown ObjectMeta to types, that are opaque to the API server and usually stored in files and config maps.

CAPI did something similar because of bugs in unmarshaling related to kubebuilder.
they created a custom ObjectMeta with only the fields they need.

no strong opinions on my side, so i think a custom ObjectMeta is fine.

> ClusterConfiguration is a completely different thing. You don't expect more than one of these in a cluster. Hence, it's a "singleton" and having a separate metadata.name field is a bit senseless.

unless someone creates multi-cluster topologies using kubeadm?

**Comment by rosti** [comment]
> > ClusterConfiguration is a completely different thing. You don't expect more than one of these in a cluster. Hence, it's a "singleton" and having a separate metadata.name field is a bit senseless.
> 
> unless someone creates multi-cluster topologies using kubeadm?

Yep, I forgot about that. In that case `clusterName` is the field to be used in place of `metadata.name`.

**Comment by neolit123** [comment]
it really seems that metada.name for our types is to only satisfy kustomize.

**Comment by neolit123** [comment]
it seems patches can use a few more fields like `namespace` and `annotations`:
https://github.com/kubernetes/kubeadm/pull/1724/files#diff-d937f45ffd1a04bea321ca4d15977b0cR65

**Comment by fabriziopandini** [comment]
I'm +1 making our config API objects more similar to other K8s objects, with this regard, I expect support at least for name, labels, and annotations

**Comment by neolit123** [comment]
note, we decided to not add ObjectMeta in kubeadm types for the time being (in v1beta3)
we are only adding +option.

the open PR will close this issue as it is now reporposed:
https://github.com/kubernetes/kubernetes/pull/101925

in the future we can revisit the topic, but currently there is no evidence of demand outside of kustomize.
