### ISSUE TITLE
Need preflight check for etcd version

### ISSUE THREAD

**Issue by sgmiller** [kubernetes/kubeadm#174]
Spent a very long time debugging what I thought were permissions issues or a bug in RBAC.  It turns out to be failure to read and/or write values to my external Etcd 2.3 cluster while kubeadm was expecting v3.   Upgrading my cluster fixed the issue.

If possible, kubeadm should validate that an external etcd cluster is the right version before proceeding.

**Comment by luxas** [comment]
That would be a very good preflight check indeed?
Up for contributing that :smile:?

**Comment by bruceauyeung** [comment]
@luxas i wanna try, but i have some questions.
1. with the master branch, there is no flags for using external etcd in `kubeadm init` and `kubeadm reset` commands. how do we specify external etcd now ?
2. add preflight checks when `kubeadm init` ?

**Comment by dgoodwin** [comment]
@bruceauyeung I believe the etcd option was moved to the master config file which you can specify with kubeadm init --config, I'm not 100% sure these docs are totally up to date but there's a master config file example here: https://kubernetes.io/docs/admin/kubeadm/

For reference the API definition can be seen here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go#L23

For (2) I would say it's fine to skip the check if we're using the etcd pod configured by kubeadm, but also fine to check it, whatever is cleanest in the code.

For (3) yes should just be a check for kubeadm init.
