### ISSUE TITLE
Kubeadm join to and existing master fails.

### ISSUE THREAD

**Issue by paragkha** [kubernetes/kubeadm#175]
Hi,

We have an existing kubeadm master and slave setup where 10.180.86.228 is master and 10.180.86.229 is slave.

Both machines have similar OS and Kernel
OS  :- Oracle Linux Server 7.1
Kernel :- 4.1.12-61.1.23.el7uek.x86_64

Now when we are trying to add a new slave(10.180.86.3) to existing master(10.180.86.228) we get the following error :- 
'<node/discovery> failed to parse response as JWS object [square/go-jose: compact JWS format must have three parts]'

When we try to connect to master using curl (http://10.180.86.228:9898/cluster-info/v1/?token-id=$token) we get output as 'Forbidden'
The port 9898 is open on master node and has been verified using netstat.

Also on observing the logs in master while joining new slave we get:- 
{"log":"2017/02/21 14:30:16 Got token ID: bb4639\n","stream":"stderr","time":"2017-02-21T14:30:16.535843294Z"}
{"log":"2017/02/21 14:30:16 open /tmp/secret/token-map.json: no such file or directory\n","stream":"stderr","time":"2017-02-21T14:30:16.535879356Z"}

The logs are observed using :- 
tail -f /var/log/containers/kube-discovery-1769846148-7qldz_kube-system_kube-discovery-bb41775a7636ba6a20db95ff05533a117ad0900ca6a07072ac48582a9f985007.log

From the code it seems to be trying to open /tmp/secret/token-map.json file which it is not finding. 
Can somebody please guide with this issue.

**Comment by simt2** [comment]
This happens for me when using a token generated via `kubeadm token generate` and not the initially generated token from `kubeadm init` on the master.

**Comment by simt2** [comment]
So at least for me its pebkac, see #109

**Comment by luxas** [comment]
Please use kubeadm v1.6, that will probably solve this issue
