### ISSUE TITLE
Kubelet configuration should not be set defaults on kubeadm side.

### ISSUE THREAD

**Issue by jfbai** [kubernetes/kubeadm#1751]
## What keywords did you search in kubeadm issues before filing this one?

kubelet, configuration, default

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.14

**Environment**: 
- **Kubernetes version** (use `kubectl version`): v1.14
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?

It is unable to customize `readOnlyPort` via `kubeadm init phase upload-config kubelet --config kubeadm.yaml`.

## What you expected to happen?

`readOnlyPort` should be customizable via `kubeadm init phase upload-config`.

## How to reproduce it (as minimally and precisely as possible)?

`kubeadm init phase upload-config kubelet --config kubeadm.yaml`

```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
readOnlyPort: 10255
```

## Anything else we need to know?
This is caused by kubeadm's default behaviour. But I think it would be better not to default the configurations on kubeadm side (even if it will be deprecated in the future), otherwise, it will break users' expectation.

**Comment by neolit123** [comment]
closing in favor of: https://github.com/kubernetes/kubeadm/issues/1378
which already tracks this problem.
