### ISSUE TITLE
Define how to handle kinder base image

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1759]
For kinder e2e test we want to use base images with docker because docker is still the most used CRI runtime.

With kinder rebase to kind 0.5.0 landing (https://github.com/kubernetes/kubeadm/pull/1750) old kind image with docker will not work anymore so
- it should be implemented in kinder support for build state of the art docker images
- it should be defined where those images should be stored

---

EDIT (neolit123)

current images in use:
```
baseImage: kindest/base:v20190403-1ebf15f # has docker
baseImage: kindest/base:v20191105-ee880e9b # has containerd
```

**Comment by neolit123** [comment]
Nope. The Docker support in kinder for base images is still there. Current
set of e2e jobs use a containerd base image without Docker. If cri-dockerd
becomes better maintained we might re add one Docker job that uses a base
image with Docker.

Docker on the host is still required.

**Comment by neolit123** [comment]
looks like we don't have to do anything here.
newer kinder just works with the latest kind base images, after a small change in:
https://github.com/kubernetes/kubeadm/pull/2778
