### ISSUE TITLE
The same hostname failed to join the node

### ISSUE THREAD

**Issue by hwdef** [kubernetes/kubeadm#1764]
## What keywords did you search in kubeadm issues before filing this one?

hostname

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## What happened?

If the hostname is same,master node can not distinguish them.
I know the document says ,I should use unique hostname,but it is not conspicuous enough, most people won't notice it. 
And if I use the same hostname,I won't get a warning or a error. It's not friendly for novices.

## What you expected to happen?

1.use uuid for each node.
2.Improve the documentation to make the tips more visible
3.Report an error or warning when I use the same hostname。

## How to reproduce it (as minimally and precisely as possible)?

Use the same hostname and kubeadm to join the node.

**Comment by neolit123** [comment]
> 3.Report an error or warning when I use the same hostname。

hi, this is already tracked here:
https://github.com/kubernetes/kubeadm/issues/1711

thanks
/close
