### ISSUE TITLE
update release-cycle.md

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1766]
https://github.com/kubernetes/kubeadm/blob/master/docs/release-cycle.md
is out of date and overlaps with the new https://github.com/kubernetes/kubeadm/blob/master/docs/managing-e2e-tests.md document.

we need to update the doc and make it cross link to managing-e2e-tests instead.

also, might be a good idea to create a github issue template for a type of issue where we want to track a checklist of items for each cycle - e.g. update tests, update docs etc.
cc @fabriziopandini

**Comment by neolit123** [comment]
xref https://github.com/kubernetes/kubeadm/issues/1807

**Comment by fabriziopandini** [comment]
> also, might be a good idea to create a github issue template for a type of issue where we want to track a checklist of items for each cycle - e.g. update tests, update docs etc.

https://github.com/kubernetes/kubeadm/issues/1807
