### ISSUE TITLE
IPv6 addresses are broken due to buggy HTTP proxy check

### ISSUE THREAD

**Issue by ismacasti** [kubernetes/kubeadm#1769]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:44:48Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:40:58Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
OpenStack
- **OS** (e.g. from /etc/os-release):
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
- **Kernel** (e.g. `uname -a`):
Linux master-0-n25-eccd-ci-02-jenkins 4.12.14-197.15-default #1 SMP Thu Aug 1 12:18:13 UTC 2019 (8a1385f) x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
kubeadm init fails on IPv6 clusters when the machine IPv6 address ends on an address that contains letters.
2001:db8::1 --> OK
2001:db8::f --> FAIL
The error message is:
[ERROR HTTPProxy]: parse https://2001:db8::f: invalid port ":f" 

## What you expected to happen?
kubeadm to come up and configure the control plane.

## How to reproduce it (as minimally and precisely as possible)?
kubeadm init on a machine with an IPv6 address that ends in letters

## Anything else we need to know?
This seems to be a parse error in Golang, reproducible here:
https://play.golang.org/p/T9lvfcRBW1c

**Comment by neolit123** [comment]
> This seems to be a parse error in Golang, reproducible here:
> https://play.golang.org/p/T9lvfcRBW1c


hi, as you pointed out this is something in golang and not kubeadm.
to distinguish ipv6 port from address please use `[ ... ]:..`
and let me know if it works.

example:
https://play.golang.org/p/PbPud__MTFU

/triage support

**Comment by ismacasti** [comment]
Hi, that's not possible. Setting the node IP addresses in kubeadm.conf with brackets does not work, kubeadm complaints that it expects an IPv4 or IPv6 address.

**Comment by ismacasti** [comment]
Workaround: add `--ignore-preflight-errors=HTTPProxy` to kubeadm

**Comment by kad** [comment]
I'll have a look at this. I think it is trivial to fix.
/assign

**Comment by rosti** [comment]
Everywhere else we seem to be using `net.JoinHostPort` which does the proper bracket wrapping for IPv6 addresses. However, in this check in particular, `net.JoinHostPort` is not used (because we don't take the port number into account, the check does not require that).
Hence, we need to check if the address is IPv6 and bracket wrap it if it is.

**Comment by ismacasti** [comment]
Thanks a lot!!
