### ISSUE TITLE
unclear usage of external CA

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1770]
in our docs we have a couple of sentences what "external CA" means, but no details and guide:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#external-ca-mode

this page does not have information on how to setup external CA:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

i had to look at the source code to determine what validation kubeadm performs:
https://github.com/kubernetes/kubernetes/blob/34db8e08c194d8bd35fbed7778c6cb8f8bb47273/cmd/kubeadm/app/phases/certs/certs.go#L314-L318

xref https://github.com/kubernetes/kubernetes/issues/82178
cc @WeAreHadock
cc @fabriziopandini 

/kind documentation
/priority important-longterm

**Comment by WeAreHadock** [comment]
Hello,
thanks for your time trying to solve our problem.

We follow your instruction : kubeadm reset -> provide ca.crt, apiserver.crt/key and apiserver-kubelet-client.crt/key -> kubeadm init

We have now this error:
 I0904 08:51:11.338174   25452 initconfiguration.go:189] loading configuration from "kubeadm-config.yaml"
I0904 08:51:11.349082   25452 feature_gate.go:216] feature gates: &{map[]}
the admin.conf file does not exists or it is not valid: stat /etc/kubernetes/admin.conf: no such file or directory


Our pki folder : 
├── pki
│   ├── apiserver.crt
│   ├── apiserver.key
│   ├── apiserver-kubelet-client.crt
│   ├── apiserver-kubelet-client.key
│   └── ca.crt


According to the documentation here : 
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/


We have to provide four kubeconfig file  : 
kubelet.conf, controller-manager.conf,  scheduler.conf, admin.conf

but we don't know how to fill it : 

the section certificate-authority-data correspond to the ca.crt in the pki folder.

but with which value we have to fill the field client-certificate-data and client-key-data ??

**Comment by fabriziopandini** [comment]
afaik this document is the reference for certificate management https://kubernetes.io/docs/setup/best-practices/certificates/

but I agree we can improve the external CA documentation and do more xref between documents

**Comment by neolit123** [comment]
i'm going to create a PR for k/website to cross link:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/
to:
https://kubernetes.io/docs/setup/best-practices/certificates/

also link this page:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

from here:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#external-ca-mode

**Comment by neolit123** [comment]
@WeAreHadock 
> but we don't know how to fill it :
> the section certificate-authority-data correspond to the ca.crt in the pki folder.
> but with which value we have to fill the field client-certificate-data and client-key-data ??

this is outlined here:
https://kubernetes.io/docs/setup/best-practices/certificates/#configure-certificates-for-user-accounts

it gives you kubectl commands on how to fill the kubeconfig fields for client-cert/key and CA.

**Comment by neolit123** [comment]
@fabriziopandini 
PTAL for LGTM on this docs PR:
https://github.com/kubernetes/website/pull/18397

**Comment by fabriziopandini** [comment]
Done. It looks great!

**Comment by PrashantGSIN** [comment]
Hi, Is this channel still responding to the questions ? I am also trying to use the External CA mode of kubeadm. But getting negative results. I have placed the ca.crt into /etc/kubernetes/pki directory without the ca.key along with apuserver.crt and apiserver.key. These files were placed at /etc/kubernetes/pki directory after running the sudo kubeadm init command. The complete command is sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket=unix:///var/run/cri-dockerd.sock. Can any guide me over this, How should I proceed with this ?

**Comment by PrashantGSIN** [comment]
I have been getting the below error and this error is not listed on that page:
E0201 05:22:21.979920  678667 memcache.go:265] couldn't get current server API group list: Get "https://IPAddress:6443/api?timeout=32s": tls: failed to verify certificate: x509: cannot validate certificate for IPAddress because it doesn't contain any IP SANs
