### ISSUE TITLE
default kubeadm install exposes kubelet API to unauthenticated users

### ISSUE THREAD

**Issue by raesene** [kubernetes/kubeadm#178]
**Kubeadm version**
kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Kubernetes Version**
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

By default after using kubeadm to install a cluster following the procedure [here](https://kubernetes.io/docs/getting-started-guides/kubeadm/) the kubelet API is exposed on port 10250/TCP on each of the nodes.

It's possible for anyone who can reach that port at a network level to execute code in containers which are part of the cluster without authentication.  Details to reproduce included [here](https://raesene.github.io/blog/2016/10/08/Kubernetes-From-Container-To-Cluster/)

**Comment by jbeda** [comment]
This is being fixed in 1.6.  As kubeadm is alpha for 1.5 we aren't in a position to patch.

See https://github.com/kubernetes/release/pull/264.  /cc @luxas

**Comment by luxas** [comment]
Fixed already in v1.6 :tada:
