### ISSUE TITLE
certs check-expiration should report on CA/kubelet lifetimes

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#1784]
FEATURE REQUEST

The current check-expiration command reports on the certificates that kubeadm can upgrade dynamically. 

However there is no report on the other certificates in the system that kubeadm cannot upgrade - particularly the CAs and, I think, kubelet. 

If any of the CAs end up within a year of expiration, then renewal will (or at least should) fail. 

If we can't change these things automatically, then we should at least flag them up.

**Comment by SataQiu** [comment]
Emm... I wonder if we also need to check the expiration of `kubelet.conf`, since it is not managed by kubeadm but kubelet. If there is no need to manage kubelet certificates, I think this issue can be closed now. @neolit123 @NeilW

**Comment by neolit123** [comment]
I will defer to @fabriziopandini. My take is that users probably want all
expirations of certs created using the the kubeadm ca.

**Comment by fabriziopandini** [comment]
TBH I don't see much value in showing expiration for certificates that can't be renewed.

But I won't block on @neolit123 idea that the user might find useful a unique summary about all the certificates. 

My only concern is that, also in this case the certificate should be kept separated from the others and it should be made clear to the users that this canìt be renewed by kubeadm.
Instead, it should be useful to show when this certificate will be automatically renewed by kubelet or not (using the same discovery method introduced by https://github.com/kubernetes/kubernetes/pull/84118)

**Comment by neolit123** [comment]
> Instead, it should be useful to show when this certificate will be automatically renewed by kubelet or not (using the same discovery method introduced by kubernetes/kubernetes#84118)

i'm not sure how would it be possible (or easy) to find when the kubelet is going to rotate the certificate.
i think the kubelet cert manager used a constant from client-go for that, so it was roughly 2-3 months before expiration, but this requires us to hardcode the expiration assumption to 1 year.

**Comment by fabriziopandini** [comment]
This was fixed upstream by https://github.com/kubernetes/kubernetes/pull/83932
/close

feel free to reopen if I'm missing something from this thread
