### ISSUE TITLE
Can't init kubeadm

### ISSUE THREAD

**Issue by richyguo** [kubernetes/kubeadm#1788]
Hi,

OS version: RedHat 7.7

I am trying to run 'kubeadm init', but got this error:

[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Can someone please help?

**Comment by neolit123** [comment]
did you call `kubeadm reset` before `kubeadm init`?
>  It seems like the kubelet isn't running or healthy.

what do the kubelet logs say?

> - 'systemctl status kubelet'
> - 'journalctl -xeu kubelet'

**Comment by richyguo** [comment]
Yes, I have doe 'kubeadm reset'. Here is the output for systemctl:

[ec2-user@ip-10-247-239-16 ~]$ systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-09-11 09:03:17 EDT; 8s ago
     Docs: https://kubernetes.io/docs/
  Process: 29842 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=255)
 Main PID: 29842 (code=exited, status=255)
   Memory: 0B
   CGroup: /system.slice/kubelet.service

Sep 11 09:03:17 ip-10-247-239-16.awscloud.cms.local systemd[1]: Unit kubelet....
Sep 11 09:03:17 ip-10-247-239-16.awscloud.cms.local systemd[1]: kubelet.servi...
Hint: Some lines were ellipsized, use -l to show in full.



journalctl -xeu kubelet:
Sep 11 09:05:00 ip-10-247-239-16.awscloud.cms.local kubelet[30216]: I0911 09:05:00.160053   30216 certificate_store.go:129] Loading cert/key pair fr
Sep 11 09:05:00 ip-10-247-239-16.awscloud.cms.local kubelet[30216]: F0911 09:05:00.167322   30216 server.go:273] failed to run Kubelet: failed to ge
Sep 11 09:05:00 ip-10-247-239-16.awscloud.cms.local systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Sep 11 09:05:00 ip-10-247-239-16.awscloud.cms.local systemd[1]: Unit kubelet.service entered failed state.
Sep 11 09:05:00 ip-10-247-239-16.awscloud.cms.local systemd[1]: kubelet.service failed.
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local systemd[1]: kubelet.service holdoff time over, scheduling restart.
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished shutting down.
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished starting up.
--
-- The start-up result is done.
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local kubelet[30370]: Flag --cgroup-driver has been deprecated, This parameter should be set via the c
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local kubelet[30370]: Flag --cgroup-driver has been deprecated, This parameter should be set via the c
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local kubelet[30370]: I0911 09:05:10.421511   30370 server.go:425] Version: v1.15.3
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local kubelet[30370]: I0911 09:05:10.421697   30370 plugins.go:103] No cloud provider specified.
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local kubelet[30370]: I0911 09:05:10.421719   30370 server.go:791] Client rotation is on, will bootstr
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local kubelet[30370]: I0911 09:05:10.424025   30370 certificate_store.go:129] Loading cert/key pair fr
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local kubelet[30370]: F0911 09:05:10.431249   30370 server.go:273] failed to run Kubelet: failed to ge
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local systemd[1]: Unit kubelet.service entered failed state.
Sep 11 09:05:10 ip-10-247-239-16.awscloud.cms.local systemd[1]: kubelet.service failed.

**Comment by neolit123** [comment]
this line is cut `failed to run Kubelet: failed to ge....`
what does it say?

**Comment by richyguo** [comment]
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local kubelet[4756]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/task
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local kubelet[4756]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/task
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local kubelet[4756]: I0911 09:29:15.655661    4756 server.go:425] Version: v1.15.3
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local kubelet[4756]: I0911 09:29:15.655846    4756 plugins.go:103] No cloud provider specified.
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local kubelet[4756]: I0911 09:29:15.655869    4756 server.go:791] Client rotation is on, will bootstrap in background
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local kubelet[4756]: I0911 09:29:15.658147    4756 certificate_store.go:129] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local kubelet[4756]: F0911 09:29:15.666275    4756 server.go:273] failed to run Kubelet: failed to get the kubelet's cgroup: cpu and memory cgroup hierarchy not unified.  cpu: /, memory: /s
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Sep 11 09:29:15 ip-10-247-239-16.awscloud.cms.local systemd[1]: Unit kubelet.service entered failed state.

**Comment by richyguo** [comment]
sounds like something to do with 'cgroup'? What is 'cgroup'? And how to fix it?

Thanks so much!

**Comment by neolit123** [comment]
the logic in the kubelet is here:
https://github.com/kubernetes/kubernetes/blob/5823cfce76780efe5897429ea59ca55f268a3123/test/e2e_node/resource_collector.go#L513-L530

what it does, is it makes sure that for a certain PID the mounts for cpu and memory are the same.
on this host machine you seem to have a problem where the mounts end up being different.

more information here:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-cpu_and_memory-use_case

if you have not made such changes, then something could be wrong with the OS image you are using.
instead of digging into this your best option might be to try a different distribution - e.g. Ubuntu.

this is not a kubeadm problem.
/close
