### ISSUE TITLE
Provided minimal Resource requirement to install kube cluster via kubeadm

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubeadm#179]
The current document does not describe the minimal system resource requirement for install kube cluster.

I try to install kube cluster at a $5 vps. but the install progress very slow. and memory /cpu usage very high. 

uptime almost 80.0 79.0 79.0

I wonder to know . if we want to install kube cluster (per node) , how much resource we need.

CPU: 2 core or 4 core?
RAM: 4GB / 8GB?
Disk: 50GB / 100GB? 
Network: 10MB/100MB ?

**Comment by pipejakob** [comment]
What's difficult about this request is that unless you completely run out of memory, or the kubelet starts evicting critical pods, I don't know if it makes sense to claim "minimum requirements" without your specific SLOs. Having some or all operations run slowly could be perfectly fine for some cluster owners, if they're deliberately running on low-cost platforms.

That said, I think the Scalability SIG has been defining generic SLOs and might be able to weigh in on the hardware expectations to meet them. `kubeadm` helps you install a Kubernetes cluster, but the performance of everything afterward is a core issue, not a `kubeadm` one. I think it makes sense to move this issue to the `kubernetes/kubernetes` repo for sig-scalability to handle.

@kubernetes/sig-scalability-feature-requests

**Comment by jamiehannaford** [comment]
@netroby We already specify 1GB RAM as a requirement. 1 core for the masters should also be fine. Disk space really depends on what you're deploying, so I'm not sure how much value an arbitrary figure would be in a requirements list. 

Would you mind taking a look at our [requirements list](https://kubernetes.io/docs/setup/independent/install-kubeadm/#before-you-begin) and seeing if there's anything missing?

**Comment by luxas** [comment]
I think this is fine as is right now

**Comment by brendandburns** [comment]
I think providing minimal request values for CPU and Memory would be a good idea, in my raspberry pi cluster, the master is marked as schedulable, and the kube-dns pod lands on the master, but there really isn't enough memory for it to operate, and it gets evicted.
