### ISSUE TITLE
create an integration test for the DualStack feature-gate

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1803]
we found a panic when DualStack is passed as a feature-gate:
https://github.com/kubernetes/kubernetes/pull/83025

we need an integration test under /cmd/kubeadm/test, just to test if the gate is accepted and does not error out.

/kind feature
/area test
/priority important-longterm
/assign @ereslibre 
cc @Arvinderpal

**Comment by neolit123** [comment]
hi, @Arvinderpal

@ereslibre said that he can do this, but it probably should be tracked in here:
https://github.com/kubernetes/kubeadm/issues/1612

also please comment if you want to take this item.
should be fairly low complexity.

**Comment by Arvinderpal** [comment]
@neolit123 It would be great if @ereslibre can take a stab at this one. 
At the moment I'm overloaded but should have spare time coming up and if necessary I will take this task.

**Comment by neolit123** [comment]
ack @Arvinderpal

**Comment by ereslibre** [comment]
PR open: https://github.com/kubernetes/kubernetes/pull/83369
