### ISSUE TITLE
kubeadm reset hangs

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1805]
## Is this a BUG REPORT or FEATURE REQUEST?

/kind bug

**kubeadm version** (use `kubeadm version`):  v1.16.0

## What happened?
I ran a `kubeadm init --control-plane-endpoint testing-1565291768.us-west-2.elb.amazonaws.com:80 --upload-certs` but this failed because I didn't specify the aws cloud provider. So I wanted to reset my system and ran `kubeadm reset` and got this:

```
kubeadm reset
[reset] Reading configuration from the cluster...
[reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
```

## How to reproduce it (as minimally and precisely as possible)?
Create a classic ELB and an instance and run the provided command with your load balancer DNS. Make sure security groups allow access between load balancer and security groups.

**Comment by neolit123** [comment]
are you able to provide more output using e.g --v=5?
i think i know what it is and it hangs for 5 minutes, but just wanting to make sure.

**Comment by chuckha** [comment]
```
root@ip-172-31-32-167:~# kubeadm reset --v=5
I0927 12:56:39.657793   18471 reset.go:93] [reset] Loaded client set from kubeconfig file: /etc/kubernetes/admin.conf
[reset] Reading configuration from the cluster...
[reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
W0927 12:58:39.976726   18471 reset.go:96] [reset] Unable to fetch the kubeadm-config ConfigMap from cluster: failed to get config map: Get https://testing-1565291768.us-west-2.elb.amazonaws.com:80/api/v1/namespaces/kube-system/configmaps/kubeadm-config: dial tcp 35.166.206.86:80: i/o timeout
I0927 12:58:39.977089   18471 reset.go:118] [reset] Detected and using CRI socket: /run/containerd/containerd.sock
[reset] WARNING: Changes made to this host by 'kubeadm init' or 'kubeadm join' will be reverted.
```

it did indeed work after about five minutes

**Comment by neolit123** [comment]
@chuckha thanks for confirming.

@RainbowMango after our discussion on slack today do you want to try to send a PR for this?
the problem here is that `kubeadm reset` tries to fetch a ConfigMap for 5 minutes. we should shorten this timeout, because it can seem as if the program is crashed/hanging.

**Comment by RainbowMango** [comment]
@neolit123 
Sure,  let me try.

/assign

**Comment by RainbowMango** [comment]
@neolit123 
I guess you want shorten the backoff here.
https://github.com/kubernetes/kubernetes/blob/39286f396259494b54c9459ea8a2a0b42a1497b5/cmd/kubeadm/app/util/apiclient/idempotency.go#L304

If yes. Can you propose a suitable backoff?

By the way, it is the same issue with https://github.com/kubernetes/kubeadm/issues/1606, right?

**Comment by neolit123** [comment]
> By the way, it is the same issue with #1606, right?

it's related, but for reset we have a slightly different use case.
while during init we want the cluster to try to succeed for longer, reset is a best effort command and it should give up earlier and not continue for 5 minutes.

this means that we have to be able to specify how much time the different commands need.
we don't want to change the value of clientsetretry.DefaultBackoff for init.

**Comment by RainbowMango** [comment]
Got it.

> this means that we have to be able to specify how much time the different commands need.

It is the point.  That's interesting and make sense. 

> we don't want to change the value of clientsetretry.DefaultBackoff for init.

Sure, we can't change the default one from client-go.

**Comment by neolit123** [comment]
let me assign myself.
i did some experiments here and i'm not exactly sure why this would wait for 5 minutes.

the default backoff is much shorter so it must be something else causing such a big delay.

**Comment by neolit123** [comment]
ok, i remember seeing this problem at one point but cannot reproduce it anymore by trying a number of things.


the important part is:

> dial tcp 35.166.206.86:80: i/o timeout

my understanding here is that the `i/o timeout` error is something we cannot control the timeout of:
https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/configmap.go#L65-L76

[1] 
one way is to modify client-go to support Timeout for `GetOptions`.
the same way `ListOptions` supports it already:
https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/configmap.go#L79-L93

this means propagating the the change to all k8s API types and it's not clear whether api-machinery will approve of the change.

[2]
another option is to handle our config map "get" calls:
https://github.com/kubernetes/kubernetes/blob/2e6b073a3f800654ec217e763fcb97412308a9db/cmd/kubeadm/app/util/apiclient/idempotency.go#L306

inside a go routine that exists after a custom timeout.

[3] another option is to use a rest client with credentials directly.

my personal proposal is to not take action on [2] and [3], but if someone wants to push for this, they should create a kuberenetes/kubernetes ticket for option [1] and tag with `/sig api-machinery`.

/sig api-machinery
/priority backlog
/remote-priority awaiting-more-evidence
/help
/unassign

**Comment by RainbowMango** [comment]
> this means propagating the change to all k8s API types and it's not clear whether api-machinery will approve of the change.

@sttts Can you share your comments about this?

**Comment by neolit123** [comment]
i brought a laptop to another network and was able to reproduce the problem again.
the local node IP changed.

i think what we can do is instead of going for the API Get call for the ConfigMap is we can try generic connectivity to the endpoint first.

**Comment by neolit123** [comment]
sent experimental PR here https://github.com/kubernetes/kubernetes/pull/84648
