### ISSUE TITLE
kubectl get cs shows only 1 ready etcd service with an ha setup

### ISSUE THREAD

**Issue by sfxworks** [kubernetes/kubeadm#1806]
/kind bug 

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:11:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
Openstack
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- **Kernel** (e.g. `uname -a`):
Linux controller-1 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
`kubectl get cs` only reports 1 etcd service named etcd-0 instead of all three within the kube-system namespace. 

```
C:\Users\samuelwa>kubectl get pods -n kube-system
NAME                                 READY   STATUS    RESTARTS   AGE
coredns-5c98db65d4-99vlc             1/1     Running   7          3d2h
coredns-5c98db65d4-tq9sq             1/1     Running   5          5m48s
etcd-w-master-1                      1/1     Running   4          3d2h
etcd-w-master-2                      1/1     Running   1          3d1h
etcd-w-master-3                      1/1     Running   4          3d1h
...
C:\Users\samuelwa>kubectl get cs
NAME                 STATUS    MESSAGE             ERROR
scheduler            Healthy   ok
controller-manager   Healthy   ok
etcd-0               Healthy   {"health":"true"}
```
## What you expected to happen?
It to show all 3 etcd nodes. 

## How to reproduce it (as minimally and precisely as possible)?
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
Follow the steps in kubeadm's ha cluster guide using the "Stacked control plane and etcd nodes" method.  

## Anything else we need to know?
etcd reports just fine and is online otherwise. Discussion started in slack at https://kubernetes.slack.com/archives/C2P1JHS2E/p1569010344115600

**Comment by neolit123** [comment]
`kubectl get cs`
to my knowledge cluster status is a command that is planned for being deprecated and you should not rely on it.

i have seen the same with this command in an HA setup and this is not a kubeadm bug.
if you wish to report your finding try asking in the #sig-cli channel on slack or log a kubernetes/kubernetes ticket.

thanks.
