### ISSUE TITLE
Kubernetes cluster fails to initialize with API endpoint as ALB

### ISSUE THREAD

**Issue by grk-kulkarni** [kubernetes/kubeadm#1815]
## What keywords did you search in kubeadm issues before filing this one?
x509: certificate signed by unknown authority

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT
## Versions

**kubeadm version** (use `kubeadm version`): v1.15.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.15.3
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CentOS
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
Kubernetes cluster using Kubeadm fails to initialize when the control plane end point is pointing to AWS application load balancer. It works perfectly if the control plane end point is given as master IP address. 
during initialization, Kubelet is trying to reach api-server but fails with this error:
Failed to list *v1beta1.CSIDriver: Get https://gateway-dev.gateway-imd.boozallencsn.com:443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: x509: certificate signed by unknown authority
I tried regenerating the Kubelet certificates in /var/lib/Kubelet/pki as suggested in other issues but have no luck yet.

## What you expected to happen?
Kubernetes cluster should be initialized and cluster should be managed using AWS ALB endpoint.

## How to reproduce it (as minimally and precisely as possible)?
sudo kubeadm init --upload-certs --config config.yaml --v=10

config.yaml:
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.3
clusterName: gw-kubeadm-test
controlPlaneEndpoint: my-aws-alb-address:443
networking:
  podSubnet: 192.168.0.0/16
apiServer:
  extraArgs:
    cloud-provider: aws
  certSANs:
  - my-aws-alb-address
  - 127.0.0.1
  - kubernetes.default

**Comment by neolit123** [comment]
hello, unfortunately this is not a kubeadm bug, but rather a problem with your setup with the cloud provider LB.

the kubeadm team does not have e2e tests to help verify your setup or debug potential issues.

this topic might interest you:
https://github.com/kubernetes/kubeadm/issues/1685

you can also ask in the #cluster-api channel on k8s slack as the Cluster API project has a AWS provider and they know how to setup AWS load balancers.

thanks
/triage support
/close
