### ISSUE TITLE
unknown flag: --experimental-control-plane.

### ISSUE THREAD

**Issue by Inv0k-er** [kubernetes/kubeadm#1816]
Hello. I try to add in my cluster a two new master node. 
I am using 

kubeadm join ip:6443 --token key --discovery-token-ca-cert-hash sha256:key --experimental-control-plane.
And I have error: unknown flag: --experimental-control-plane

**Comment by neolit123** [comment]
/triage support
this means your are using an old version of kubeadm - check `kubeadm version`.
for this feature you need 1.14, but better use 1.16 (latest).

**Comment by Inv0k-er** [comment]
> 
> 
> /triage support
> this means your are using an old version of kubeadm - check `kubeadm version`.
> for this feature you need 1.14, but better use 1.16 (latest).

sorry but this is my 
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:34:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Inv0k-er** [comment]
Ok how to upgrade kubeadm ?

**Comment by neolit123** [comment]
i checked and the flag `--experimental-control-plane` is still there for 1.16 `kubeadm join`.
it should work for you, so not sure what's causing the error for you.

try `kubeadm join --help`.

**Comment by Inv0k-er** [comment]
I tryed use without experimental; it is kubeadm join --control-plane
And will be work I am not sure. Because I have another error it is 

error execution phase check-etcd: error syncing endpoints with etc: context deadline exceeded

**Comment by neolit123** [comment]
something is not right on your side, maybe you are mixing versions, because 1.16 should still have the --expermental-control-plane flag.
