### ISSUE TITLE
kube-flannel dial tcp 10.96.0.1:443: i/o timeout

### ISSUE THREAD

**Issue by dannymk** [kubernetes/kubeadm#1817]
## Is this a BUG REPORT or FEATURE REQUEST?
Choose one: BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):  Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:34:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"

**Environment**:
- **Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:  OpenStack Instances
- **OS** (e.g. from /etc/os-release):  18.04.3 LTS (Bionic Beaver)
- **Kernel** (e.g. `uname -a`):
Linux kube-node-5 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

Installed a new 1.16.0 node on an existing 1.15.0 cluster per the instructions at: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

Flannel fails to initialize and work on this single node. I have tried many solutions including making sure I passed the correct network during init to --pod-network-cidr, firewall issues, ip forwarding issues and the like and nothing. Can't get past this error. Not my first time installing a node or a cluster but this has me baffled.

## What you expected to happen?

The flannel pod should remain in service
```
kube-flannel-ds-amd64-2qnvz                1/1     Running            0          36m   192.168.5.31   kube-node-3           <none>           <none>
kube-flannel-ds-amd64-4btvh                1/1     Running            0          36m   192.168.5.48   kube-node-2           <none>           <none>
kube-flannel-ds-amd64-j9f9h                0/1     CrashLoopBackOff   8          26m   192.168.5.46   kube-node-5           <none>           <none>
kube-flannel-ds-amd64-jhv59                1/1     Running            0          36m   192.168.5.23   kube-node-1           <none>           <none>
kube-flannel-ds-amd64-kh46h                1/1     Running            0          36m   192.168.5.30   kube-node-4           <none>           <none>
```

## How to reproduce it (as minimally and precisely as possible)?

Follow the instructions to create a new node at:  https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

## Anything else we need to know?

Flannel pod for new node is in CrashLoopBackOff state because of:

```
I1002 17:50:45.287131       1 main.go:514] Determining IP address of default interface
I1002 17:50:45.287344       1 main.go:527] Using interface with name ens3 and address 192.168.5.46
I1002 17:50:45.287359       1 main.go:544] Defaulting external address to interface address (192.168.5.46)
E1002 17:51:15.288450       1 main.go:241] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-amd64-j9f9h': Get https://10.96.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-amd64-j9f9h: dial tcp 10.96.0.1:443: i/o timeout
```

**Comment by dannymk** [comment]
Could this have anything to do with this issue:

```
$ kubectl -n kube-system describe ds kube-proxy
Name:           kube-proxy
Selector:       k8s-app=kube-proxy
Node-Selector:  beta.kubernetes.io/os=linux
Labels:         k8s-app=kube-proxy
Annotations:    deprecated.daemonset.template.generation: 2
Desired Number of Nodes Scheduled: 8
Current Number of Nodes Scheduled: 8
Number of Nodes Scheduled with Up-to-date Pods: 8
Number of Nodes Scheduled with Available Pods: 8
Number of Nodes Misscheduled: 0
Pods Status:  8 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           k8s-app=kube-proxy
  Service Account:  kube-proxy
  Containers:
   kube-proxy:
    Image:      k8s.gcr.io/kube-proxy:v1.15.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
      --hostname-override=$(NODE_NAME)
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
  Volumes:
   kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
   xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
   lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
Events:
  Type     Reason        Age   From                  Message
  ----     ------        ----  ----                  -------
  Warning  FailedCreate  47m   daemonset-controller  Error creating: Pod "kube-proxy-mpvjq" is invalid: spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
  Warning  FailedCreate  30m   daemonset-controller  Error creating: Pod "kube-proxy-qhqtv" is invalid: spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
  Warning  FailedCreate  14m   daemonset-controller  Error creating: Pod "kube-proxy-k4dv9" is invalid: spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```

**Comment by neolit123** [comment]
please try another CNI plugin like calico or weavenet
we had so many problem reports about flannel recently that's really hard for us to respond to users and maintain support for this problem.

**Comment by dannymk** [comment]
Using Calico with these instructions:  https://docs.projectcalico.org/v3.9/getting-started/kubernetes/installation/migration-from-flannel
