### ISSUE TITLE
kubeadm init should provide a HTTP_PROXY configure

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubeadm#182]
We are living in china. our network can not reach gcr.io. so while try to using kubeadm init to create kubernetes cluster. we will failed to create containers. 
Because Greate firewall blocked gcr.io and the all google service domain.

So please let kubeadm support a configure argument (which support HTTP_PROXY)

Download image through proxy seems a only one solution for us. or we can not using kubernetes

**Comment by bruceauyeung** [comment]
kubeadm will try to download kubenetes components and etcd images if they don't exist.These images by default will be pulled from `gcr.io/google_containers`, but you can pull them from any repository by setting environment variables `KUBE_REPO_PREFIX`, `KUBE_DISCOVERY_IMAGE`, `KUBE_ETCD_IMAGE`, please refer to https://kubernetes.io/docs/admin/kubeadm/

**Comment by netroby** [comment]
I know that section. but this is not about my issue. 
set up that ENV Vars not as quick as configure a proxy for kubernetes.

Just one command can save much time

```bash
kubeadm init --with-proxy=http://10.0.19.28:8080 
```
If with these flag.  kubeadm will configure proxy global for the master/join node. and exclude the node master ip for us automatic.

Should make things easier

**Comment by xilabao** [comment]
@netroby  In fact, kubeadm support http proxy.  see https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/master/manifests.go#L426
set http_proxy as environment variable, it could work.

**Comment by netroby** [comment]
Ok. I guess we can update the document for more details

**Comment by yuvipanda** [comment]
Should this issue be closed now?

**Comment by netroby** [comment]
closed

**Comment by lastboy1228** [comment]
If you set http_proxy as environment variable when execute "kubeadm init", the env variable will be recorded in the files in /etc/kubernetes/manifests/.

**Comment by TodayyadoT** [comment]
@xilabao  [the link you attached above didn't exist now](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/master/manifests.go#L426)

@lastboy1228 I have set http_proxy and then execute 'kubeadm init', but it didn't record in  /etc/kubernetes/manifests/

**Comment by hiobama** [comment]
sudo http_proxy=192.168.99.1:1080 kubeadm init

**Comment by mhrsalehi** [comment]
setting env. from terminal did not work for me. I used /etc/environment

**Comment by mhrsalehi** [comment]
ok, but how to set a socks proxy?

**Comment by alicommit-malp** [comment]
by using socks5h it will contact 127.0.0.1:53 for DNS lookup so I say you need to configure 127.0.0.1 as a DNS server if you want to make it work.
but regarding the socks5 if you are running : 
```bash 
sudo systemctl set-environment https_proxy=socks5://127.0.0.1:9050
```
you need to restart the target service (ex: docker or containerd) to reload the env again otherwise it won't work. if you are using the kubeadm you need to know what is your CRI and accordingly restart the proper service (ex: docker or containerd ... )

**Comment by gotomypc** [comment]
> by setting HTTP_PROXY &/ HTTPS_PROXY in /etc./environment or exporting it directly you are setting the proxy for the processes that you will run under your shell process. kubeadm is using containerd service to download the images therefore you need to set the systemctl env
> 
> ```shell
> sudo systemctl set-environment HTTP_PROXY=127.0.0.1:1080
> sudo systemctl set-environment HTTPS_PROXY=127.0.0.1:1080
> sudo systemctl restart containerd.service
> ```
> 
> then you can pull the packages with
> 
> ```shell
> sudo kubeadm config images pull
> ```



> by setting HTTP_PROXY &/ HTTPS_PROXY in /etc./environment or exporting it directly you are setting the proxy for the processes that you will run under your shell process. kubeadm is using containerd service to download the images therefore you need to set the systemctl env
> 
> ```shell
> sudo systemctl set-environment HTTP_PROXY=127.0.0.1:1080
> sudo systemctl set-environment HTTPS_PROXY=127.0.0.1:1080
> sudo systemctl restart containerd.service
> ```
> 
> then you can pull the packages with
> 
> ```shell
> sudo kubeadm config images pull
> ```

correct, thanks!
