### ISSUE TITLE
kubeadm config images pull support for Amazon ECR with containerd

### ISSUE THREAD

**Issue by aaroniscode** [kubernetes/kubeadm#1820]
FEATURE REQUEST

Would like to be able to pre pull container images when using Amazon ECR container registry and `containerd` as the CRI.

`containerd` does not have native support for authenticating to Amazon ECR. This is an open ticket: https://github.com/containerd/cri/issues/1131.

This capability might best be a feature of `containerd`. However, this authentication is already built into `kubelet`, maybe it could be easily reused (as a library) for kubeadm?

## Versions
v1.15.4

**Comment by timothysc** [comment]
This really doesn't seem like a kubeadm issue.

**Comment by aaroniscode** [comment]
@timothysc That may be the case.  However, it appears from the comment https://github.com/containerd/cri/issues/1131#issuecomment-500075502 that the `containerd` team is considering not adding the logic to authenticate with ECR.

If that's the case, where should the logic live to authenticate with ECR?

**Comment by neolit123** [comment]
@aaroniscode 

> If that's the case, where should the logic live to authenticate with ECR?

ideally we should not include registry authorizations mechanisms as part of kubeadm.

as per:
https://github.com/containerd/cri/issues/1131#issuecomment-500075502

> crictl pull --creds aaa:bbb gcr.io/google-containers/busybox:latest

does crictl support the `--creds` as part of it's config or is this only supported from a CLI flag?

**Comment by neolit123** [comment]
cc @bart0sh

**Comment by neolit123** [comment]
@aaroniscode 

for the kubeadm side to work, crictl needs to support authorization files in a default location, instead of only accepting `--creds` on the CLI.

this way any `crictl pull` call would read credentials from a config and not require the explicit `--creads` flag which kubeadm lacks. we have the option to expose the `USER:PASSWORD` using environment variables, but it feels like this would be a hack / workaround for the lack of a feature in critctl.

related:
https://github.com/kubernetes-sigs/cri-tools/issues/482

/close

**Comment by aaroniscode** [comment]
@neolit123 Is it at all possible that the `kubeadm` could leverage the credential provider inside Kubernetes?

https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/aws/aws_credentials.go

**Comment by neolit123** [comment]
> @neolit123 Is it at all possible that the kubeadm could leverage the credential provider inside Kubernetes?

kubeadm should be cloud provider agnostic.

> Or maybe I misunderstood that the Kubernetes ECR credential support is limited only to Docker and doesn't work with containerd?

> The Kubernetes docs around ECR Support don't mention a limitation of only supporting Docker: https://kubernetes.io/docs/concepts/containers/images/#using-amazon-elastic-container-registry

i think this only works for docker currently, even if the docs don't mention it.

>  https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/aws/aws_credentials.go

this comment gives some explanations about the above package:

https://github.com/containerd/cri/issues/1131#issuecomment-481706725

> Finally, the future roadmap for Kubernetes has the ECR credential fetch moving from the Kubelet (--cloud=provider=aws) into the control plane (--cloud-provider=external), so a standalone Kubelet would need to fully rely on containerd for ECR pull credentials.

i have not information for what is the future of `pkg/credentialprovider/aws` and credential providers.
most likely moving outside of k/k and decoupling from the kubelet.

> The Kubernetes level provides credentials for pulling Pod images, but these credentials are not used by containerd when it pulls the sandbox image.

this is true. credentials for pulling the sandbox image still have to be provided outside of Kubernetes and into raw `crictl pull` calls.

**Comment by aaroniscode** [comment]
thanks @neolit123 . This is really helpful and makes sense. So once `containerd` has native support for ECR pull credentials, `kubeadm` will "just work".

**Comment by roshankakad** [comment]
Hello Team,

Getting crictl pul image error ""401 Unauthorized "
root@ip-X-X-X-X:~# crictl pull X.dkr.ecr.us-east-2.amazonaws.com/netq-app-air:4.7.0-SNAPSHOT 

E0703 04:20:12.150068 4026085 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \".dkr.ecr.us-east-2.amazonaws.com/netq-app-air:4.7.0-SNAPSHOT\": failed to resolve reference \".dkr.ecr.us-east-2.amazonaws.com/netq-app-air:4.7.0-SNAPSHOT\": pulling from host .dkr.ecr.us-east-2.amazonaws.com failed with status code [manifests 4.7.0-SNAPSHOT]: 401 Unauthorized" image=".dkr.ecr.us-east-2.amazonaws.com/netq-app-air:4.7.0-SNAPSHOT"
FATA[0000] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image ".dkr.ecr.us-east-2.amazonaws.com/netq-app-air:4.7.0-SNAPSHOT": failed to resolve reference "498186410471.dkr.ecr.us-east-2.amazonaws.com/netq-app-air:4.7.0-SNAPSHOT": pulling from host X.dkr.ecr.us-east-2.amazonaws.com failed with status code [manifests 4.7.0-SNAPSHOT]: 401 Unauthorized.


Please share your comments
