### ISSUE TITLE
Update min Docker-CE Version more recent version 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#1821]
Testing locally - 

[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.2. Latest validated version: 18.09

**Comment by neolit123** [comment]
please prescribe a more recent docker version.
/assign @timothysc @mauilion 
cc @kubernetes/sig-cluster-lifecycle 

we should mind that test-infra / kubekins is still at `18.09`:
https://github.com/kubernetes/test-infra/blob/master/images/bootstrap/Dockerfile#L101
so the test-infra images do not provide signal for 19* yet, project wide.

for docker-in-docker / kinder / kubeadm-e2e on the other hand we have the option to include a custom version:
https://github.com/kubernetes/kubeadm/blob/master/kinder/images/base/docker/Dockerfile#L65-L67

cc @fabriziopandini 

@timothysc @yastij 
https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L27-L33
if we bump only the kubeadm validators we are going to detach from test-infra, which i'm not in favor of. so sig-testing needs to be in sync.

**Comment by timothysc** [comment]
In walking their repo data (https://download.docker.com/linux) is looks like only 19+ exists on fedora channels while CentOS is still at 18.  We should leave this open to track as things shift.

**Comment by yastij** [comment]
+1 on not diverging. let's wait until we have a consistent version across the distros

**Comment by fabriziopandini** [comment]
+1 on not diverging

**Comment by yagonobre** [comment]
+1 on not diverging

**Comment by neolit123** [comment]
PSA (recent change): kubekins / test-infra is using 19* now:
https://github.com/kubernetes/test-infra/blob/29b34a06d716841dc1f4f2eb7ab0a80cc598be27/images/bootstrap/Dockerfile#L101
