### ISSUE TITLE
K8S: convert “kubeadm init” command-line arguments to “–config” YAML-file equivalent

### ISSUE THREAD

**Issue by hunternins** [kubernetes/kubeadm#1825]
## Is this a request for help?

**YES**

## What keywords did you search in kubeadm issues before filing this one?

- API.
- Config.
- YAML.
- Command line argument equivalents.

## Is this a BUG REPORT or FEATURE REQUEST?

**BUG REPORT** (i.e. undocumented feature for mapping two APIs against each other).

## Versions

**kubeadm version** (use `kubeadm version`):

- 1.15.4-00

**Environment**:
- 1.15.4-00
- Kubeadm on Intel bare metal
- Ubuntu 18.04.3 LTS x86_64
- 4.15.65-00-generic

## What happened?

---

# Background

I'm attempting to configure a cluster via `kubeadm`. I normally create the (test) cluster via:

    sudo kubeadm init --pod-network-cidr 10.244.0.0/16

This parameter appears to eventually find its way into the static pod definition for the controllerManager (`/etc/kubernetes/manifests/kube-controller-manager.yaml`):

    - --cluster-cidr=10.244.0.0/16

Larger portions of `sudo vim /etc/kubernetes/manifests/kube-controller-manager.yaml`:

    apiVersion: v1
    kind: Pod
    metadata:
      creationTimestamp: null
      labels:
        component: kube-controller-manager
        tier: control-plane
      name: kube-controller-manager
      namespace: kube-system
    spec:
      containers:
      - command:
        - kube-controller-manager
        - --allocate-node-cidrs=true
        - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
        - ...
        - --cluster-cidr=10.244.0.0/16

---

# Question 1:

How can I pass this setting, `--pod-network-cidr=10.244.0.0/16` via a config file, i.e. `kubeadm init --config my_config.yaml`? I found a [sample config file template on an unofficial K8S documentation wiki][1], but I can't seem to find any documentation at all that maps these command-line arguments to `kubeadm` to their `kubeadm_config.yaml` equivalents.

[There's also a document showing how I can create a baseline static pod definition/`yaml`][2] via `kubeadm config print init-defaults > kubeadm_config.yaml`, but again, no documentation that shows how to set `pod-network-cidr` by modifying and applying this `yaml` file (i.e. `kubeadm upgrade -f kubeadm_config.yaml`).

**Sample output of `kubeadm config view`:**

    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta2
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controllerManager: {}
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.15.4
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    scheduler: {}

---

# Question 2:

How can I do the above, but pass something like `--experimental-cluster-signing-duration=0h30m0s`? I'd like to experiment with tests involving manually/automatically renewing all `kubeadm`-related certs.

---

  [1]: https://unofficial-kubernetes.readthedocs.io/en/latest/admin/kubeadm/
  [2]: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/

**Comment by neolit123** [comment]
/triage support
/area UX

Q1

> How can I pass this setting, --pod-network-cidr=10.244.0.0/16 via a config file, i.e. kubeadm init --config my_config.yaml? I found a sample config file template on an unofficial K8S documentation wiki, but I can't seem to find any documentation at all that maps these command-line arguments to kubeadm to their kubeadm_config.yaml equivalents.

we have a long running problem of not having a good mapping between flags and config, there are some proposals in progress at the moment and long term we would like to simplify this.

the minimal config you are looking for is:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.4
networking:
  podSubnet: 10.244.0.0/16
```

Q2

`experimental-cluster-signing-duration` is a flag for the controller manager and can be passed using "extra args", the tutorial is here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/

your full config will look like:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.4
networking:
  podSubnet: 10.244.0.0/16
controllerManager:
  extraArgs:
    experimental-cluster-signing-duration: <YOUR_VALUE>
```

let me know if you have further questions.
/close

**Comment by hunternins** [comment]
@neolit123 Thank you for your help. It is appreciated.

**Comment by neolit123** [comment]
@Dev0Null 

please see:
https://github.com/kubernetes/kubeadm/issues/1040

and

https://docs.google.com/document/d/1Dvct469xfjkgy3tjWMAKvRAJo4CmGH4cgSVGTDpay6A/edit

ideally we would want this to apply to all components, however the proposal may see some opposition, thus we might end up doing only for kubeadm.

**Comment by shellwhale** [comment]
Hello @neolit123, any updates on this?
