### ISSUE TITLE
provide way to upload kubeadm and kubelet configurations to cluster

### ISSUE THREAD

**Issue by gdoctor** [kubernetes/kubeadm#1827]
FEATURE REQUEST:

There should be a way to upload a kubeadm configuration to a cluster, independent of `kubeadm init` and `kubeadm upgrade` commands (ie update `kubadm-config` in `kube-system` namespace as well create `kubelet-config-1.xx` configmap). 

Updating/creating these two configmaps is important to both cluster initialization, as well as cluster upgrades via kubeadm. Imagine a scenario where the kubelet and kubeadm configurations are controlled by a third party entity (such as a controller). Giving that controller the ability to update the kubelet and kubeadm configurations would be very valuable. We could then update these configmaps prior to a cluster upgrade, then bring up new nodes, on the new kubernetes version, without having to mutate any of the currently running nodes.

One way to achieve this is to remove the patch node phase `AnnotateCRISocket` from the `kubeadm init phase upload-config all` command. This command assumes that we are initializing a cluster, rightfully so, but by removing it, we can achieve the desired outcome.

Alternatively, and probably a better long term solution anyway, is to add a new command `kubeadm config upload` that takes a kubernetes version, kubeadm config, and kubeconfig as inputs. The ideal behavior would be to take the config, update the config's `kubernetesVersion` to the inputted kubernetes version, and upload it to the cluster defined in the kubeconfig file. 

/kind feature

Side Note:
As infrastructure and kubernetes move towards more immutability, kubeadm should also take these use cases into account. It seems like a lot of the feature set provided by kubeadm focuses on mutable infrastructure.

**Comment by neolit123** [comment]
> It would appear that this functionality previously existed, but was deprecated. I do not think it is appropriate to deprecate this functionality in favor of kubeadm init phase upload-config without removing the patch node phase from the kubeadm init phase upload-config command. That part of the command is kubeadm initialization specific, and makes the command not very useful for other scenarios.

your observation is true.

the patch node part being part of the phase is not a good replacement for `kubeadm config upload from-flags`. but maybe we should just deprecate it without replacement on the kubeadm side.
/assign @rosti 

> As infrastructure and kubernetes move towards more immutability, kubeadm should also take these use cases into account. It seems like a lot of the feature set provided by kubeadm focuses on mutable infrastructure.

uploading configuration can be done with kubectl which is a pretty viable option.

/priority awaiting-more-evidence.

**Comment by gdoctor** [comment]
> uploading configuration can be done with kubectl which is a pretty viable option.
While your comment is definitely true, the challenging part of this whole thing is marshalling/unmarshalling the different kubeadm schemes as they evolve. In order to stay up to date with the latest configurations, it is far easier to use kubeadm directly to manage your configurations versus trying to manipulate these configurations on a case by case basis, either via kubectl, or via a third party controller.

**Comment by gdoctor** [comment]
> > It would appear that this functionality previously existed, but was deprecated. I do not think it is appropriate to deprecate this functionality in favor of kubeadm init phase upload-config without removing the patch node phase from the kubeadm init phase upload-config command. That part of the command is kubeadm initialization specific, and makes the command not very useful for other scenarios.
> 
> your observation is true.
> 
> the patch node part being part of the phase is not a good replacement for `kubeadm config upload from-flags`. but maybe we should just deprecate it without replacement on the kubeadm side.
> /assign @rosti
> 
> > As infrastructure and kubernetes move towards more immutability, kubeadm should also take these use cases into account. It seems like a lot of the feature set provided by kubeadm focuses on mutable infrastructure.
> 
> uploading configuration can be done with kubectl which is a pretty viable option.
> 
> /priority awaiting-more-evidence.

**Comment by neolit123** [comment]
> While your comment is definitely true, the challenging part of this whole thing is marshalling/unmarshalling the different kubeadm schemes as they evolve. In order to stay up to date with the latest configurations, it is far easier to use kubeadm directly to manage your configurations versus trying to manipulate these configurations on a case by case basis, either via kubectl, or via a third party controller.

technically, both the kubeadm config that is on disk and the ConfigMap that is in the cluster are versioned. `kubeadm config migrate` allows you to manage conversion if needed and `kubectl` can be the tool used for the upload itself.

**Comment by fabriziopandini** [comment]
My mayor concerns is what are the expectations when uploading a new kubeadm-config / kubelet-config object before upgrades.

Kubeadm upgrade (for in place upgrades) was not designed with configuration changes scenario in mind, and there are several reports about problems when going for this path

If instead you are going for node replacement (using kubeadm join instead of upgrades), my suggestion is to join forces with the cluster API folks, because they're solving the same problems upstream ATM.

With regards to kubeadm, have you considered to use `kubeadm config upload from-file` ?

**Comment by neolit123** [comment]
`kubeadm config upload from-file` has been deprecated, but @gdoctor is correct that
`kubeadm init phase upload-config` is not a good replacement for it (see first post).
https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/cmd/kubeadm/app/cmd/config.go#L283

i'm in favor of removing these command completely:
- `kubeadm config upload`
- `kubeadm config view`

because with these commands we are duplicating `kubectl` functionality which is pretty easy to use.

**Comment by neolit123** [comment]
merging this with the older ticket:
https://github.com/kubernetes/kubeadm/issues/1827
