### ISSUE TITLE
Failed to parse subnet when creating IPv4/IPv6 dual stack

### ISSUE THREAD

**Issue by qiangtang** [kubernetes/kubeadm#1828]
## Versions
**kubeadm version** (use `kubeadm version`):
```
root@v6-master:~# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:58:27Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```
**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
root@v6-master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

```
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04

- **Kernel** (e.g. `uname -a`):
Linux v6-master 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
```
root@v6-master:~# kubeadm init --feature-gates=IPv6DualStack=true --pod-network-cidr=fc00:20::/64,172.20.0.0/16 --service-cidr=fc00:30::/64,172.30.0.0/16 -v=5

I1009 06:08:23.858223   26165 initconfiguration.go:102] detected and using CRI socket: /var/run/dockershim.sock
I1009 06:08:23.859006   26165 interface.go:384] Looking for default routes with IPv4 addresses
I1009 06:08:23.859053   26165 interface.go:389] Default route transits interface "ens160"
I1009 06:08:23.860004   26165 interface.go:196] Interface ens160 is up
I1009 06:08:23.860380   26165 interface.go:244] Interface "ens160" has 3 addresses :[192.168.111.69/24 2019:10::111:69/64 fe80::250:56ff:fe9a:b27d/64].
I1009 06:08:23.860474   26165 interface.go:211] Checking addr  192.168.111.69/24.
I1009 06:08:23.860486   26165 interface.go:218] IP found 192.168.111.69
I1009 06:08:23.860545   26165 interface.go:250] Found valid IPv4 address 192.168.111.69 for interface "ens160".
I1009 06:08:23.860552   26165 interface.go:395] Found active IP 192.168.111.69 
I1009 06:08:23.861051   26165 version.go:182] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
I1009 06:08:25.598188   26165 feature_gate.go:216] feature gates: &{map[]}
serviceSubnet: Invalid value: "fc00:30::/64,172.30.0.0/16": couldn't parse subnet

```
## What you expected to happen?
kube cluster create succeed with the correct cidr setting.

## How to reproduce it (as minimally and precisely as possible)?
Just run the cli above based on kube 1.16

**Comment by neolit123** [comment]
/sig network
/priority awaiting-more-evidence
/assing @Arvinderpal 

please take a look if you can.
thanks.

**Comment by qiangtang** [comment]
The dual stack option seems take effect when input single ip type cidr as below:
root@v6-master:~# kubeadm init --feature-gates=IPv6DualStack=true --pod-network-cidr=10.244.10.0/24 --service-cidr=10.244.20.0/24  -v=5
I1010 03:20:59.797672   22989 initconfiguration.go:102] detected and using CRI socket: /var/run/dockershim.sock
I1010 03:20:59.799780   22989 interface.go:384] Looking for default routes with IPv4 addresses
I1010 03:20:59.799827   22989 interface.go:389] Default route transits interface "ens160"
I1010 03:20:59.801995   22989 interface.go:196] Interface ens160 is up
I1010 03:20:59.802539   22989 interface.go:244] Interface "ens160" has 3 addresses :[192.168.111.69/24 2019:10::111:69/64 fe80::250:56ff:fe9a:b27d/64].
I1010 03:20:59.802729   22989 interface.go:211] Checking addr  192.168.111.69/24.
I1010 03:20:59.802758   22989 interface.go:218] IP found 192.168.111.69
I1010 03:20:59.802807   22989 interface.go:250] Found valid IPv4 address 192.168.111.69 for interface "ens160".
I1010 03:20:59.802813   22989 interface.go:395] Found active IP 192.168.111.69 
I1010 03:20:59.803218   22989 version.go:182] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
I1010 03:21:01.544354   22989 feature_gate.go:216] feature gates: &{map[]}
podSubnet: Invalid value: "10.244.10.0/24": expected at least one IP from each family (v4 or v6) for dual-stack networking

But as I check the code:
func ValidateIPNetFromString(subnetStr string, minAddrs int64, isDualStack bool, fldPath *field.Path) field.ErrorList {
	allErrs := field.ErrorList{}
	if isDualStack {
		subnets, err := utilnet.ParseCIDRs(strings.Split(subnetStr, ","))
		if err != nil {
			allErrs = append(allErrs, field.Invalid(fldPath, subnetStr, err.Error()))
		} else {
			areDualStackCIDRs, err := utilnet.IsDualStackCIDRs(subnets)
			if err != nil {
				allErrs = append(allErrs, field.Invalid(fldPath, subnets, err.Error()))
			} else if !areDualStackCIDRs {
				allErrs = append(allErrs, field.Invalid(fldPath, subnetStr, "expected at least one IP from each family (v4 or v6) for dual-stack networking"))
			}
			for _, s := range subnets {
				numAddresses := ipallocator.RangeSize(s)
				if numAddresses < minAddrs {
					allErrs = append(allErrs, field.Invalid(fldPath, s, "subnet is too small"))
				}
			}
		}
	} else {
		_, svcSubnet, err := net.ParseCIDR(subnetStr)
		if err != nil {
			allErrs = append(allErrs, field.Invalid(fldPath, subnetStr, "couldn't parse subnet"))
			return allErrs
		}
		numAddresses := ipallocator.RangeSize(svcSubnet)
		if numAddresses < minAddrs {
			allErrs = append(allErrs, field.Invalid(fldPath, subnetStr, "subnet is too small"))
		}
	}
	return allErrs
}

The error is thrown from the else part, which means the kube site try to create cluster with single stack setting when I adding both the v4/v6 cidrs

**Comment by qiangtang** [comment]
Same issue when I created cluster with the config yaml by kubeadm:
```
root@v6-master:~# kubeadm init --config config.yaml 
W1010 04:21:52.106026   23014 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta2", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "config"
[serviceSubnet: Invalid value: "172.30.0.0/24,2019:30::/24": couldn't parse subnet, podSubnet: Invalid value: "172.20.0.0/24,2019:20::/24": couldn't parse subnet, KubeProxyConfiguration.ClusterCIDR: Invalid value: "172.20.0.0/24,2019:20::/24": must be a valid CIDR block (e.g. 10.100.0.0/16 or FD02::0:0:0/96)]
To see the stack trace of this error execute with --v=5 or higher
```
```
root@v6-master:~# cat config.yaml 
apiServer:
  certSANs:
    - 192.168.111.69
    - 2019:10::111:69
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager:
  config:
    featureGates:
      IPv6DualStack: true
kubeProxy:
  config:
    featureGates:
      SupportIPVSProxyMode: true
    mode: ipvs
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.16.1
networking:
  dnsDomain: cluster.local
  podSubnet: 172.20.0.0/24,2019:20::/24
  serviceSubnet: 172.30.0.0/24,2019:30::/24
scheduler: {}
```

**Comment by qiangtang** [comment]
Also is this related with https://github.com/kubernetes/kubeadm/issues/1612 ?

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubeadm/issues/1612
is our tracking issue for dual-stack support in kubeadm.
ideally @Arvinderpal should have a look at your report if/once he has the time.

**Comment by Arvinderpal** [comment]
@qiangtang looks like you're not using the latest kubernetes version. The following PR merged last week for handling a list of service subnets https://github.com/kubernetes/kubernetes/pull/82473
I would recommend building from the master branch directly. Also, refer to the `k8s-dual-stack` channel on slack for help.

**Comment by neolit123** [comment]
thanks @Arvinderpal 

closing as per the fact that this is bleeding edge, unsupported functionality in a stable k8s release.
/close
