### ISSUE TITLE
Make the host-scoped configuration observable

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes/kubeadm#1829]
As a user, I would like to be able to observe the _actual_ (i.e. with the default values kubeadm applies at runtime) host-scoped configuration used by kubeadm `init` or `join`.

Being able to observe this configuration would be especially helpful to debug clusters deployed with Cluster API. I filed https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/265.

Today, I can already observe the _actual_ cluster-scoped configuration because kubeadm stores the `ClusterConfiguration` as a ConfigMap. I can also observe the `InitConfiguration` and `JoinConfiguration`_defaults_ used with `config print init-defaults` and `config print join-defaults`, respectively. But, I cannot observe the _actual_ `InitConfiguration` and `JoinConfiguration`, i.e., the values I supply, merged with the defaults kubeadm applies.

## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.16.x

/kind feature-request

**Comment by neolit123** [comment]
@dlipovetsky @rosti 
i think what we can do here without changing too much is to dump the dynamically defaulted configurations as yaml in key locations on higher verbosity levels?

**Comment by fabriziopandini** [comment]
As far as I remember all the node specific settings are already stored in the cluster (and kubeadm use them for upgrades). On top of my head:
- The cri socket and taints are stored with an annotation at node level
- The local API server address is stored in the kubeadm config config map

The only thing that is not stored in the cluster are the kubelet extra args, which are stored locally. however might be this is going to change with the ongoing work around component config management. @rosti ^^^

**Comment by dlipovetsky** [comment]
> As far as I remember all the node specific settings are already stored in the cluster (and kubeadm use them for upgrades). On top of my head:

Thanks for looking at this issue! I hope you aren't objecting to making it easy to get the actual configuration; I think it's a lot easier for kubeadm to generate it than it is for the user to query multiple sources.

**Comment by neolit123** [comment]
unassigned folks until we get an agreement about the direction here.
maybe this is worth of kubeadm office hours discussion (e.g. next week - 29th Jan)

**Comment by fabriziopandini** [comment]
@neolit123 this is converging to the instance-specific component config. As soon as we figure out how kubeadm handles those values, we should also take care of make them discoverable.
Ideally, the components itself should start exposing some endpoints to get the current config, but this can potentially introduce a certificate nighmare as well if we should provide serving certs for all components... however, if this goes through the API server...

**Comment by neolit123** [comment]
core k8s components currently also lack this (e.g. scheduler), so it seems to me a new KEP will be needed at some point.

but kubeadm is not a daemon, so it cannot serve it's configuration. potentially it needs to start storing the instance specific config in ConfigMaps too.

**Comment by BenTheElder** [comment]
seems like you could get _pretty far_ without a lot of effort by {de,}serializing somewhere on each instance's disk.
