### ISSUE TITLE
Kubeadm init forces me to open public port

### ISSUE THREAD

**Issue by SamMorrowDrums** [kubernetes/kubeadm#183]
I initialise my master, add Weave plugin and then join the nodes (precisely as instruction sugggest), but with the default setup it forces me to open the public port to let nodes join, and if I specify a local IP to advertise, it breaks the installation. Installation is bare metal: Ubuntu 16.04 on Profit Bricks host.

It could be related to: https://github.com/kubernetes/kubeadm/issues/37 https://github.com/kubernetes/kubernetes/issues/33618

When I use kubeadm init `--api-advertise-addresses=<eth1 IP Address>`. The init works, and the nodes join, but then networking fails to work, here are logs from the Weave Net container:

```
<probe> ERRO: 2017/02/26 17:07:53.038948 Error fetching app details: Get http://10.99.38.109:80/api: dial tcp 10.99.38.109:80: getsockopt: connection refused
<probe> ERRO: 2017/02/26 17:07:56.151746 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:165: Failed to list *api.Pod: Get https://10.96.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
<probe> ERRO: 2017/02/26 17:07:56.206349 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:165: Failed to list *api.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
<probe> ERRO: 2017/02/26 17:07:56.207533 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:165: Failed to list *api.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
<probe> ERRO: 2017/02/26 17:07:56.215526 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:165: Failed to list *api.ReplicationController: Get https://10.96.0.1:443/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
<probe> ERRO: 2017/02/26 17:08:03.038891 Error fetching app details: Get http://10.99.38.109:80/api: dial tcp 10.99.38.109:80: getsockopt: connection refused
```

I've tried to follow some suggested fixes, but I am really not sure how to get a working setup, with the local network only.

**Comment by SamMorrowDrums** [comment]
Is it normal to open the secure service port `<server-ext-ip>:6443` to the public internet? If this is normal perhaps it should be documented?

**Comment by SamMorrowDrums** [comment]
Turns out this does work:

http://stackoverflow.com/questions/39872332/how-to-fix-weave-net-crashloopbackoff-for-the-second-node#40338365

But over my local network I need to take additional undocumented steps... So really we still might need to look at why some setups require this clusterCIDR setting, and why others don't.

**Comment by SamMorrowDrums** [comment]
FWIW setting the POD Network CIDR on kubeadm init doesn't seem to resolve this either.

**Comment by shavo007** [comment]
this caught me out when following the tutorial on aws using ubuntu. what security group entries do I need for the master node?

**Comment by luxas** [comment]
cc @jbeda @justinsb @chrislovecnm ^

**Comment by jbeda** [comment]
For any kubernetes configuration it is assumed that there is some level of communication allowed between nodes for the control plane to communicate.  I don't think we document exactly what ports are needed, exactly.  The networking solution you use may have other requirements also.  Generally people run with full connectivity between all nodes in the cluster on a private subnet.

**Comment by luxas** [comment]
@jbeda Do you see any action items from this issue?

**Comment by SamMorrowDrums** [comment]
One thing that should probably be documented (albeit obvious to many) is that it's ok to expose the secure kubernetes api to the public Internet.

Also there were problems with kubeadm adaptor selection at the time of writing this report. If the workflow for that has been improved, I'd be very pleased. 

Still a few rookie issues that can bite novice users trying bare metal for the first time. I just think there are still some assumptions left out of the docs.

**Comment by luxas** [comment]
Totally reasonable

I'd happily take PRs for improving the docs! Indeed gaps there are hard to notice for the people that have written it... I appreciate the perspective!

If you think the gaps are severe enough, open a new, more focused issue for that with action items.

Thanks!
