### ISSUE TITLE
Multiple automated master nodes (e.g. in autoscaling group)

### ISSUE THREAD

**Issue by lewismarshall** [kubernetes/kubeadm#184]
I would like to be able to use kubeadm to bootstrap a cluster (if it didn't exist) and to join a cluster if it does.

I'm having trouble working out how to use kubeadm in an automated fashion if the master resources are all created on a single node only.

Can anyone help as the direction seems to pertain to a manual only tool for single master nodes.

**Comment by luxas** [comment]
Provisioning physical or virtual nodes is out of scope for kubeadm.
Have you taken a look at kops? It's in scope for kops though...
