### ISSUE TITLE
coredns CrashLoopBackOff

### ISSUE THREAD

**Issue by ranjithssipl** [kubernetes/kubeadm#1841]
kubectl logs -f coredns-bdffbc666-fvz76 -n kube-system
E1018 06:39:54.604839       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: no route to host
E1018 06:39:54.604839       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:315: Failed to list *v1.Service: Get https://10.43.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: no route to host
log: exiting because of error: log: cannot create log: open /tmp/coredns.coredns-bdffbc666-fvz76.unknownuser.log.ERROR.20191018-063954.1: no such file or directory

Cluster created using Rancher

**Comment by neolit123** [comment]
hi, there are a variety of reasons of why this can happen.
please have a look at :
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#coredns-pods-have-crashloopbackoff-or-error-state

if you can't solve that try asking in #kubeadm on slack.

also best to specify your k8s version in your reports.
if you have the option please try 1.16.

> Cluster created using Rancher

i have no information if this uses kubeadm even.

thanks
/close
