### ISSUE TITLE
"kubeadm config images pull" should not pull etcd image if external etcd configured

### ISSUE THREAD

**Issue by bartwensley** [kubernetes/kubeadm#1842]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.16.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.16.0
- **Cloud provider or hardware configuration**: hardware
- **OS** (e.g. from /etc/os-release): CentOS Linux 7
- **Kernel** (e.g. `uname -a`): 3.10.0-957.21.3
- **Others**:

## What happened?

A v1.16.0 HA cluster was configured with kubeadm, using external etcd nodes. Later, in preparation for upgrading to v1.16.1, the following command was run to download the images:
kubeadm config images pull --kubernetes-version v1.16.1

## What you expected to happen?

Since the cluster was configured with external etcd nodes, the etcd image should not be pulled. When the initial installation was done, the following command is smart enough to not pull the etcd image if the kubeadm.yaml file specifies external etcd configuration:
kubeadm config images pull --config /etc/kubernetes/kubeadm.yaml

When the "kubeadm config images pull --kubernetes-version <version>" is done on an already installed cluster, it should look at the kubeadm-config config map and see that it specifies external etcd configuration and avoid pulling the etcd image.

## How to reproduce it (as minimally and precisely as possible)?

Install a v1.16.0 cluster using kubeadm and external etcd nodes. Then run the following command:
kubeadm config images pull --kubernetes-version v1.16.1

## Anything else we need to know?

This is a problem in the case where the kubernetes images are being pulled from a private docker registry (not k8s.gcr.io). In that case, the private registry may not have the etcd image, since it isn't required if external etcd is configured.

**Comment by neolit123** [comment]
> This is a problem in the case where the kubernetes images are being pulled from a private docker registry (not k8s.gcr.io). In that case, the private registry may not have the etcd image, since it isn't required if external etcd is configured.

i think etcd should not be pulled during `init`, `join` and `upgrade` commands if external etcd is used?
isn't kubeadm already skipping it in that case?

> kubeadm config images pull ...

i personally think this command is a best effort to prepull *all* required images.
if you wish to pull only the ones you need, that would be a job for:
```
kubeadm config images list ...
docker pull ...
```

kubeadm 1.17 will also have JSON/YAML format for `list`.

**Comment by bartwensley** [comment]
> i think etcd should not be pulled during `init`, `join` and `upgrade` commands if external etcd is used?
> isn't kubeadm already skipping it in that case?

Yes - kubeadm init/join/upgrade skip the etcd image in that case.
 
> > kubeadm config images pull ...
> 
> i personally think this command is a best effort to prepull _all_ required images.
>

My complaint is that this command will skip the etcd image if the --config option is used, but will not skip the image if the --config option is not used. That is inconsistent. If the kubeadm-config config map exists, this command should be able to use it to determine whether external etcd is configured.

**Comment by neolit123** [comment]
> Yes - kubeadm init/join/upgrade skip the etcd image in that case.

ok, so if --config is used kubeadm behaves correctly on prepull.

> My complaint is that this command will skip the etcd image if the --config option is used, but will not skip the image if the --config option is not used. That is inconsistent. If the kubeadm-config config map exists, this command should be able to use it to determine whether external etcd is configured.

using the config map would be a bit odd, because we currently assume from the operator that they prepulled required images before the cluster was already. i.e. the workflow is: prepull images once, distribute images to nodes, create cluster. instead of, create primary control-plane pull images again and distribute images.

if this config map fetch is added to `images pull` it also has to be added to `images list` because without that we are creating another inconsistency. however currently `images list --kubernetes-version` is used in a lot of places (including k8s CI) to acquire the list of images even without accessing the network and ideally we would like to keep it that way.

**Comment by bartwensley** [comment]
> using the config map would be a bit odd, because we currently assume from the operator that they prepulled required images before the cluster was already up. i.e. the workflow is: prepull images once, distribute images to nodes, create cluster. instead of, create primary control-plane, pull images again and distribute images.

I'm doing this as part of a kubeadm upgrade. The reason here is that (to my knowledge) the "kubeadm upgrade apply" command does not support pulling images from an authenticated registry. So before doing the "kubeadm upgrade apply", I'd like to use "kubeadm config images pull --version" to pull the images from an authenticated registry (after doing a "docker login" of course). That workflow doesn't work today if the etcd image is not in the registry.

> if this config map fetch is added to `images pull` it also has to be added to `images list` because without that we are creating another inconsistency. however, currently `images list --kubernetes-version` is used in a lot of places (including k8s CI) to acquire the list of images even without accessing the network and ideally we would like to keep it that way.

To me it seems more important that "images pull" is internally consistent (when --config is used or not used) than being consistent with "images list", but that's just an opinion and I understand your point.

**Comment by neolit123** [comment]
> The reason here is that (to my knowledge) the "kubeadm upgrade apply" command does not support pulling images from an authenticated registry

in all cases kubeadm just calls `docker pull` (or crictl), yet you can login into a private registry using `docker login` beforehand or use `~/.docker/config.json` to store the credentials.

the custom registry can be specified in the ClusterConfiguration of kubeadm.

once you are authenticated, `kubeadm upgrade` should pull from the private registry.

if you find a bug related to this workflow please log a separate issue.

> I'd like to use "kubeadm config images pull --version" to pull the images from an authenticated registry (after doing a "docker login" of course). That workflow doesn't work today if the etcd image is not in the registry.

but this is already possible if one passes `--config` to `pull`.

> To me it seems more important that "images pull" is internally consistent (when --config is used or not used) than being consistent with "images list", but that's just an opinion and I understand your point.

if your cluster is configured with a `--config`  during `init` i would expect the same `--config` to be passed to `kubeadm config images *` if you want the prepull to respect the external etcd aspect.

adding CM fetch for `pull` and/or `list` seems like adding guessing logic whether the cluster is up or not for the different workflows - 1) is the user prepulling before init? 2) is the user prepulling during upgrade?

i will add other developers who helped in this area to the discussion:
@rosti @bart0sh @chuckha

**Comment by bartwensley** [comment]
> > The reason here is that (to my knowledge) the "kubeadm upgrade apply" command does not support pulling images from an authenticated registry
> 
> in all cases kubeadm just calls `docker pull` (or crictl) or [leverages the kubelet pull](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/), yet you can login into a private registry using `docker login` beforehand or use `~/.docker/config.json` to store the credentials.
> 
> the custom registry can be specified in the ClusterConfiguration of kubeadm.
> 
> once you are authenticated, `kubeadm upgrade` should pull from the private registry.
> 
> if you find a bug related to this workflow please log a separate issue.
> 

I just re-tested this and confirmed that the "kubeadm upgrade apply" does NOT support pulling images from an authenticated registry. Doing the "docker login" before running "kubeadm upgrade apply" makes no difference - I suspect this is because a set of pods (e.g. upgrade-prepull-kube-apiserver-xxxxx) are being created to do the pulls and these pods will not have the docker credentials.

I have not seen any indication in the documentation that "kubeadm upgrade apply" supports docker registries with authentication, so I'm hesitant to raise a bug for this.

> > I'd like to use "kubeadm config images pull --version" to pull the images from an authenticated registry (after doing a "docker login" of course). That workflow doesn't work today if the etcd image is not in the registry.
> 
> but this is already possible if one passes `--config` to `pull`.
> 

My understanding was that after the initial "kubeadm upgrade init" was done, the kubeadm-config config map was supposed to be the one source of truth for kubeadm. The user shouldn't be supplying config files to kubeadm after the initial "kubeadm upgrade init" is done.

> > To me it seems more important that "images pull" is internally consistent (when --config is used or not used) than being consistent with "images list", but that's just an opinion and I understand your point.
> 
> if your cluster is configured with a `--config` during `init` i would expect the same `--config` to be passed to `kubeadm config images *` if you want the prepull to respect the external etcd aspect.
> 
> adding CM fetch for `pull` and/or `list` seems like adding guessing logic whether the cluster is up or not for the different workflows - 1) is the user prepulling before init? 2) is the user prepulling during upgrade?
> 

I understand your point so I guess I will just live with the current limitation and use a combination of "kubeadm config images list" and "docker pull".

**Comment by bartwensley** [comment]
Forgot to mention one thing. I believe there is a bug in "kubeadm upgrade apply". In the case where the  control plane images cannot be pulled due to authentication failure. The apply incorrectly says the image pull was successful and then fails to upgrade the control plane pods:

```
# kubeadm upgrade apply v1.16.1
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/version] You have chosen to change the cluster version to "v1.16.1"
[upgrade/versions] Cluster version: v1.16.2
[upgrade/versions] kubeadm version: v1.16.2
[upgrade/confirm] Are you sure you want to proceed with the upgrade? [y/N]: y
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler]
[upgrade/prepull] Prepulling image for component kube-scheduler.
[upgrade/prepull] Prepulling image for component kube-apiserver.
[upgrade/prepull] Prepulling image for component kube-controller-manager.
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[apiclient] Found 2 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 2 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 2 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[upgrade/prepull] Prepulled image for component kube-controller-manager.
[upgrade/prepull] Prepulled image for component kube-apiserver.
[upgrade/prepull] Prepulled image for component kube-scheduler.
[upgrade/prepull] Successfully prepulled the images for all the control plane components
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.16.1"...
Static pod: kube-apiserver-controller-0 hash: b8f262c11cb9416aab304978a5d26929
Static pod: kube-controller-manager-controller-0 hash: 832740cd954ab0a68bbc591b578341cf
Static pod: kube-scheduler-controller-0 hash: a01478acdc49404c8f4dffa14b34b63d
[upgrade/staticpods] Writing new Static Pod manifests to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests164703542"
[upgrade/staticpods] Preparing for "kube-apiserver" upgrade
[upgrade/staticpods] Renewing apiserver certificate
[upgrade/staticpods] Renewing apiserver-kubelet-client certificate
[upgrade/staticpods] Renewing front-proxy-client certificate
[upgrade/staticpods] Moved new manifest to "/etc/kubernetes/manifests/kube-apiserver.yaml" and backed up old manifest to "/etc/kubernetes/tmp/kubeadm-backup-manifests-2019-10-23-13-30-58/kube-apiserver.yaml"
[upgrade/staticpods] Waiting for the kubelet to restart the component
[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s)
Static pod: kube-apiserver-controller-0 hash: b8f262c11cb9416aab304978a5d26929
Static pod: kube-apiserver-controller-0 hash: 44973c1a837dba6e4b6c573a0b46e330
[apiclient] Found 2 Pods for label selector component=kube-apiserver
[upgrade/apply] FATAL: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher
```
Here is what kubelet reports:
`2019-10-23T13:26:04.606 controller-0 kubelet[90588]: info E1023 13:26:04.606003   90588 pod_workers.go:191] Error syncing pod 374a487d-d835-4cb0-8ac0-e58248af48c6 ("upgrade-prepull-kube-apiserver-8pkm9_kube-system(374a487d-d835-4cb0-8ac0-e58248af48c6)"), skipping: failed to "StartContainer" for "kube-apiserver" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: Get https://registry.local:9001/v2/k8s.gcr.io/kube-apiserver/manifests/v1.16.1: unauthorized: authentication required"
`

Should I raise a bug for this?

**Comment by neolit123** [comment]
@bartwensley 

> I just re-tested this and confirmed that the "kubeadm upgrade apply" does NOT support pulling images from an authenticated registry. Doing the "docker login" before running "kubeadm upgrade apply" makes no difference - I suspect this is because a set of pods (e.g. upgrade-prepull-kube-apiserver-xxxxx) are being created to do the pulls and these pods will not have the docker credentials.

> I have not seen any indication in the documentation that "kubeadm upgrade apply" supports docker registries with authentication, so I'm hesitant to raise a bug for this.

for upgrade kubeadm does use a DaemonSet for the prepull and not a `docker pull`.

the kubelet on that node needs to have the credentials stored in the docker config file.
did you follow the steps here?
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

> My understanding was that after the initial "kubeadm upgrade init" was done, the kubeadm-config config map was supposed to be the one source of truth for kubeadm. The user shouldn't be supplying config files to kubeadm after the initial "kubeadm upgrade init" is done.

true, but in case `kubeadm config images *` is used without a cluster is running, kubeadm has to take a guess trying to get a CM using the admin.conf and not fail if no cluster or admin.conf exists.

this is my main objection to this proposed extension. passing --config solves that.

> https://registry.local:9001/v2/k8s.gcr.io/kube-apiserver/manifests/v1.16.1: unauthorized: authentication required"
> Should I raise a bug for this?

we have users using private registries and upgrade.
my suspicions is that your docker/kubelet are not setup correctly.
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by fabriziopandini** [comment]
If we are going to implement this, we should carefully design it in order to not prevent the users to run image pull before a cluster exists.
Also, we should make sure to be consistent with the UX of other commands

**Comment by bartwensley** [comment]
@neolit123 - I appreciate your help.

> for upgrade kubeadm does use a DaemonSet for the prepull and not a `docker pull`.
> 
> the kubelet on that node needs to have the credentials stored in the docker config file.
> did you follow the steps here?
> https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

I don't think that is the page you meant to reference. That page refers to creating a secret and referencing that in the imagePullSecrets in the pod spec. That approach works for me with "regular" pods, but doesn't work for control plane pods because they use static manifests created by kubeadm and do not contain imagePullSecrets.

Were you meaning to refer to this page instead?
https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry

I hadn't seen those instructions before. I just did a quick test following those instructions where I copied my ~/.docker/config.json (with correct auths info) to /var/lib/kubernetes/config.json and restarted kubelet. That didn't work - the "kubeadm upgrade apply" still fails to download the images. I may have done something wrong though so I will continue to play around with this.

> > Should I raise a bug for this?
> 
> we have users using private registries and upgrade.
> my suspicions is that your docker/kubelet are not setup correctly.
> https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

Even if I did cause this by incorrect setup (which is entirely possible), isn't it still a bug that "kubeadm upgrade init" is saying that it "Successfully prepulled the images for all the control plane components" when it clearly didn't?

**Comment by neolit123** [comment]
> Were you meaning to refer to this page instead?
https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry

yes, that is the page i was referring to.

> I will continue to play around with this.

thanks.

> Even if I did cause this by incorrect setup (which is entirely possible), isn't it still a bug that "kubeadm upgrade init" is saying that it "Successfully prepulled the images for all the control plane components" when it clearly didn't?

that part does sound like a bug.

**Comment by neolit123** [comment]
@bartwensley 
did you manage to get the private registry setup working?

**Comment by bartwensley** [comment]
@neolit123 
The instructions at https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry don't work for me at all. I followed the instructions to create the docker config file with the credentials for my private registry and copied the file to the search path(s) that kubelet is supposed to use to find this file. I also restarted kubelet in the hope that it would use the credentials. No luck. It appears that kubelet is not using the credentials. When I attempt to create a pod using a private image I see errors like this in syslog:

2019-11-18T20:10:11.685 controller-0 kubelet[330459]: info E1118 20:10:11.684556  330459 remote_image.go:113] PullImage "registry.local:9001/testimage:latest" from image service failed: rpc error: code = Unknown desc = Error response from daemon: Get https://registry.local:9001/v2/testimage/manifests/latest: unauthorized: authentication required

Doing a docker login from the shell allows me to pull the image (with "docker pull") with no issue.

**Comment by neolit123** [comment]
ok, i see. please log the above comment as an issue in the kubernetes/kubernetes repository.
and tag it with `/sig node`.

this issue is tracking your feature request for `config images`.
i'm personally -1 on adding cluster checks for `config images` because most of it's use cases are before the cluster is created. but deferring to @fabriziopandini as per his comment here:
https://github.com/kubernetes/kubeadm/issues/1842#issuecomment-545573952

close if needed.

**Comment by fabriziopandini** [comment]
I'm +1 in making kubeadm config images to try to get the kubeadm-config ConfigMap (if no config was explicitly passed with `--config`), and failback to the current behavior in case of error.
FYI, a similar change was recently implemented for kubeadm alpha certs.

@bartwensley I think that it will be really valuable for the community to document how to get kubeadm working with a private registry. Have you considered to write a getting start guide? I will be more than happy to help in reviewing it....

**Comment by neolit123** [comment]
> I'm +1 in making kubeadm config images to try to get the kubeadm-config ConfigMap (if no config was explicitly passed with --config), and failback to the current behavior in case of error.
FYI, a similar change was recently implemented for kubeadm alpha certs.

@fabriziopandini given there is a user request for this and we have similar for alpha certs.
let's proceed with the change.

adding help-wanted.

> @bartwensley I think that it will be really valuable for the community to document how to get kubeadm working with a private registry. Have you considered to write a getting start guide? I will be more than happy to help in reviewing it....

a kubeadm specific guide would be nice, indeed.

**Comment by LucaLanziani** [comment]
Hello, reading the conversation and assuming this is the PR you are talking about in alpha certs: https://github.com/kubernetes/kubernetes/pull/85091 
I would like to give this issue a try if it's not a problem.

**Comment by neolit123** [comment]
> I would like to give this issue a try if it's not a problem.

@LucaLanziani  hi, please go ahead.

> https://github.com/kubernetes/kubernetes/pull/85091

yes, it seems related to the conversation.

**Comment by LucaLanziani** [comment]
Proposal:

Move this function into `configutils` or similar: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/alpha/certs.go#L265

Use the same logic here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/config.go#L474

Problems:
I cannot find tests for the `images pull` command

**Comment by neolit123** [comment]
we had a discussion about this and the TL;DR is that we have some concerns and users should use a local config file that is passed via --config instead.

full rationale from from slack:
- "config images" is a GA command.
- while the same "fetch from the cluster" functionality was added to
the "cert renew" command (that is alpha), this is suggesting a change to GA
behavior. so it can be considered disruptive.
- the primary purpose of the "config images" command is to solve the air-gapped
use case.
- "certs renew" and "config images" are executed in different times of the
cluster lifecycle. "renew" is supposedly always run on an existing cluster,
while "config images" can be also be used before the cluster is up.
- getting the configuration from the cluster assumes that there is a
kubeconfig on disk on the node where the command is called. the kubelet.conf
has enough priviliges to get the kubeadm-config ConfigMap.
- [as per rosti's comment] if the command finds a stray kubeconfig for an old
cluster and creates a client-set it will download and use invalid configuration
for image list and pre-pull. this suggests pontential "action-required".
- having the new suggested feature only to "images pull", but not for "image
list" will make the commands inconsistent.
- the workaround today is the following:
```
$ kubectl get configmap --kubeconfig=/etc/kubernetes/kubelet.conf \
  -n kube-system kubeadm-config -o jsonpath={.data.ClusterConfiguration} > \
  myconfig.yaml
$ kubeadm images pull --config myconfig.yaml
```
