### ISSUE TITLE
Retries for init images

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#1844]
/kind bug

I believe it is a bug that kubeadm init does not retry image pulling on a failed connection. Recently we ran a test, specifically @vivgoyal did that created 200 cluster-api clusters bootstrapped with kubeadm. 1% (2) of the clusters failed to `kubeadm init` during the image pull stage. A retry would likely have eliminated this failure case.

## Versions

I believe this affects all versions of kubeadm

**Comment by neolit123** [comment]
there is also the option that for stability the images can be pre-pulled and distributed to all nodes?

/help
/priority backlog
/remove-kind bug
/kind feature

if we consider this as a viable feature request, these functions have to be extended to support a retry mechanic:
https://github.com/kubernetes/kubernetes/blob/a5e3d7469149c704e32a9fd858be2a25c4ca9a2c/cmd/kubeadm/app/util/runtime/runtime.go#L152-L168

**Comment by Klaven** [comment]
I'll take this and bring a plan for it to Wednesday's meeting. I think that some sane amount of retries would be good from a user experience.

**Comment by neolit123** [comment]
hi, @Klaven 
@rajibmitra wanted to take a shot at this problem and get more familiar with the kubeadm development.

**Comment by neolit123** [comment]
@rajibmitra did you make any progress on this issue?

**Comment by SataQiu** [comment]
Hi @rajibmitra  If you don't have time, I am willing to have a try!
/assign
