### ISSUE TITLE
"kubeadm init" fails: kubelet reports "connect: connection refused"

### ISSUE THREAD

**Issue by LSmyrnaios** [kubernetes/kubeadm#1849]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm init fails

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:15:39Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Running on my pc directly (no cloud services).
- **OS** (e.g. from /etc/os-release): "Ubuntu 18.04.3 LTS (Bionic Beaver)"
- **Kernel** (e.g. `uname -a`): 4.15.0-66-generic
- **Other**: nothing

## What happened?
Tried to run `kubeadm init` and got the following error:
reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.RuntimeClass: Get https://195.134.66.28:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 195.134.66.28:6443: connect: connection refused

It seems that the dependency "client-go" tries to load an older API-vesrion: **v1beta1**, instead of **v1**.

## What you expected to happen?
Kubernetes to get initialized.

## How to reproduce it (as minimally and precisely as possible)?
Run `sudo kubeadm init --kubernetes-version=stable --pod-network-cidr=10.244.0.0/16`

## Anything else we need to know?
I discovered the error using `systemctl status kubelet`

**Comment by neolit123** [comment]
> sudo kubeadm init --kubernetes-version=stable --pod-network-cidr=10.244.0.0/16

after running the above command what did you see?
did you see an error that the kubelet is unhealthy?

> It seems that the dependency "client-go" tries to load an older API-vesrion: v1beta1, instead of v1.

v1beta1 is the latest version of runtimeclass:
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/kubernetes/typed/node/v1beta1

so this request seems fine.

> dial tcp 195.134.66.28:6443: connect: connection refused

this seems like the api server is not running.
you can try inspecting the Pod / container logs for it.

**Comment by LSmyrnaios** [comment]
> > sudo kubeadm init --kubernetes-version=stable --pod-network-cidr=10.244.0.0/16
> 
> after running the above command what did you see?
> did you see an error that the kubelet is unhealthy?

I saw the following output:
```
Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
```


> v1beta1 is the latest version of runtimeclass:
> https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/kubernetes/typed/node/v1beta1
> 
> so this request seems fine.

Oh ok, I had read that kubernetes v.1.16 was moving to the stable API-version  **v1**



> > dial tcp 195.134.66.28:6443: connect: connection refused
> 
> this seems like the api server is not running.
> you can try inspecting the Pod / container logs for it.

Where can I find those logs?

**Comment by neolit123** [comment]
> Where can I find those logs?

try starting `kubeadm init...` again and once it fails check:
see `journal -xeu kublet` and share the results.

also look at the containers running:
`docker ps -a`, look for `kube-apiserver....` and share the output of `docker logs kube-apiserver...` if present.

**Comment by LSmyrnaios** [comment]
> try starting `kubeadm init...` again and once it fails check `journalctl -xeu kubelet` and share the results (e.g. in a gist or pastebin).
> make sure you call `kubeadm reset...` always before `init` or `join`.

I do call `kubeadm reset...` before `init`. (In this case I don't use `join`)
You can find the results produced by `journalctl -xeu kubelet`, here:
https://gist.github.com/LSmyrnaios/482ce7831092a50d5d3df7124cf6b779

> also look at the containers running:
> `docker ps -a`, look for `kube-apiserver....` and share the output of `docker logs kube-apiserver...` if present.

I find a kube-aipserver with `docker ps -a` but there is no output produced by `docker logs <kube-apiserver-NAME>`.

**Comment by ereslibre** [comment]
@LSmyrnaios the output you provided contains lines like `Get https://<IP>:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0`, here you didn't replace `<IP>`, hence the failures.

Please, provide a new log that can help us understand the problem you are facing. Thank you!

**Comment by LSmyrnaios** [comment]
@ereslibre I anonymized the logs for privacy.
The original ones do include valid <IP>-addresses as well as valid <hostName> and <userName>.
The <IP> is a Static IP.

**Comment by ereslibre** [comment]
Thank you @LSmyrnaios.

When you confirm that if you run a simple http server with python on 6443 port, that you can curl it from the machine where you are running kubeadm using <IP>:6443?

**Comment by LSmyrnaios** [comment]
I do confirm it.

**Comment by ereslibre** [comment]
Please, provide all `journalctl -u kubelet` during the join process. Can you also increase the kubelet verbosity to 5, and attach a `watch docker ps -a` during the init process, and in case the apiserver cannot start, its logs as well. Also, please, run `kubeadm` with a verbosity level of 9 and attach that output as well. In general, the more information you can provide, the better. Thanks.

**Comment by LSmyrnaios** [comment]
> Please, provide all `journalctl -u kubelet` during the join process.

You mean `init`-process, not `join`, right? I am only trying ti initialize kubernetes.
The logs from `journalctl -u kubelet` are huge and it's difficult the retrieve manually only the ones produced by the last `kubeadm init`.

> Can you also increase the kubelet verbosity to 5, and attach a `watch docker ps -a` during the init process, and in case the apiserver cannot start, its logs as well.

I am not sure how to do those.

> Also, please, run `kubeadm` with a verbosity level of 9 and attach that output as well.

https://gist.github.com/LSmyrnaios/a98828d9569efdbb1de905d0c653ffe6

**Comment by ereslibre** [comment]
> You mean init-process, not join, right? I am only trying ti initialize kubernetes.

Yes, sorry.

> The logs from journalctl -u kubelet are huge and it's difficult the retrieve manually only the ones produced by the last kubeadm init.

You could filter them by knowing when you started the `kubeadm init` process with `journalctl`: `journalctl -u kubelet --since "5 minutes ago"`, or using a timestamp. It would be great if you could also increase the default verbosity of the `kubelet` to have more information before you provide the logs as well.

Based on the logs you provided, and to make sure, can you please stop the `firewalld` service and retry?

**Comment by buccella** [comment]
Possible that this was previously reported as kubernetes/kubernetes#70334

**Comment by neolit123** [comment]
did you try a different CNI plugin, like weavenet?

**Comment by neolit123** [comment]
please re-open if needed.
