### ISSUE TITLE
Track + incorporate any updated 1.6 deployment add-ons.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#185]
Just found out today that the @kubernetes/sig-node-feature-requests is planning to deploy the NodeProblemDetector as part of their 1.6 install.  

This issue is to track to see what other add-ons we may be missing.  
/cc @Random-Liu @luxas

**Comment by luxas** [comment]
@Random-Liu @vishh 
In what way should the NodeProblemDetector be deployed? kubectl apply?
And how mandatory is it? Is it as essential as kube-dns for instance or should it be optional?

**Comment by luxas** [comment]
Something we need to do for v1.7/v1.8 re this?

**Comment by luxas** [comment]
Closing this as it didn't get any traction, and also I think that kube-dns/kube-proxy is the only thing we should install by default; as that is where the Conformance bar is today.
If something like the Node Problem Detector becomes required for passing Conformance tests, we'll revisit and add it probably.

A proper addon-manager is the long-term solution here...
