### ISSUE TITLE
Unwanted console output in the versiongetter API 

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubeadm#1853]
API to get version information(ClusterVersion, KubeadmVersion and VersionFromCILabel) contain unwanted calls of fmt.*Print* functions:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/versiongetter.go#L66
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/versiongetter.go#L78
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/versiongetter.go#L95

They should be moved outside of the API.  It should be done carefully in order to not degrade user experience, i.e. kubeadm console output should stay the same.

**Comment by neolit123** [comment]
@bart0sh please link to code examples for such fmt.Print* calls.

**Comment by jfbai** [comment]
I can help fix this.

@bart0sh @neolit123 Move them to caller side?

/assign

**Comment by bart0sh** [comment]
@jfbai Yes, that's pretty much what needs to be done. However, it should be done carefully to make sure user visible output doesn't change.

**Comment by jfbai** [comment]
> @jfbai Yes, that's pretty much what needs to be done. However, it should be done carefully to make sure user visible output doesn't change.

I have an idea about move them to caller side, something like this:
```
// ClusterVersion gets API server version
func (g *KubeVersionGetter) ClusterVersion() (string, *versionutil.Version, error) {
	clusterVersionInfo, err := g.client.Discovery().ServerVersion()
	if err != nil {
		return "", nil, errors.Wrap(err, "Couldn't fetch cluster version from the API Server")
	}
	fmt.Fprintf(g.w, "[upgrade/versions] Cluster version: %s\n", clusterVersionInfo.String())

	clusterVersion, err := versionutil.ParseSemantic(clusterVersionInfo.String())
	if err != nil {
-               return "", nil, errors.Wrap(err, "Couldn't parse cluster version")
+		return clusterVersionInfo.String(), nil, errors.Wrap(err, "Couldn't parse cluster version")
	}
	return clusterVersionInfo.String(), clusterVersion, nil
}

// caller side
	kubeadmVersionStr, kubeadmVersion, err := versionGetterImpl.KubeadmVersion()
	if err != nil {
+		if len(kubeadmVersionStr) > 0 {
+			fmt.Printf("[upgrade/versions] kubeadm version: %s\n", kubeadmVersionStr)
+		}
		return upgrades, err
	}
```

Could this be fine?

**Comment by jfbai** [comment]
> @jfbai Not sure why do you use ClusterVersion() API and KubeadmVersion() on the caller side in your example, but I think I've got your idea. It's a bit implicit to my taste, but could work. 

@bart0sh My mistake.

> You can also consider splitting ClusterVersion API to 2 APIs: ClusterVersionInfo() and ClusterVersion() It'd result in a bit more code duplication on the caller side, but it's more readable in my opinion.

IMO, your idea makes sense and I will implement in this way.
