### ISSUE TITLE
Node becomes unstable and needs reboot

### ISSUE THREAD

**Issue by dannymk** [kubernetes/kubeadm#1855]
## What keywords did you search in kubeadm issues before filing this one?
node delete pod stuck deleted

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):  version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:15:39Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:  OpenStack
- **OS** (e.g. from /etc/os-release):  
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- **Kernel** (e.g. `uname -a`):  Linux kube-node-2 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
Deleting a pod gets stuck and the only thing that fixes this issue is rebooting the node which affects every pod running or in a "invalid/hung" state on that node.

## What you expected to happen?
The pod gets deleted from the node and rescheduled to run again.

## How to reproduce it (as minimally and precisely as possible)?
Not really sure as the cluster seems to be pretty stable but this is happening often enough to cause concern in our production cluster.

## Anything else we need to know?

Delete command gets stuck at:

```
$ kubectl -n production delete pod wordpress-cc998cccd-f9bf2 
pod "wordpress-cc998cccd-f9bf2" deleted
====== NEVER returns to a prompt from this command
```

kubectl -n production logs wordpress-cc998cccd-f9bf2 
```
10.41.0.0 - - [23/Oct/2019:19:06:48 +0000] "GET / HTTP/1.1" 200 854 "-" "kube-probe/1.16" "-"
10.41.0.0 - - [23/Oct/2019:19:06:58 +0000] "GET / HTTP/1.1" 200 854 "-" "kube-probe/1.16" "-"
10.41.0.0 - - [23/Oct/2019:19:07:08 +0000] "GET / HTTP/1.1" 200 854 "-" "kube-probe/1.16" "-"
10.41.0.0 - - [23/Oct/2019:19:07:18 +0000] "GET / HTTP/1.1" 200 854 "-" "kube-probe/1.16" "-"
2019/10/23 19:07:53 [alert] 1#1: worker process 8 exited on signal 9
```

journalctl -xe on kube-node-2 shows:

```
...
Oct 23 20:02:55 kube-node-2 kubelet[1021]: W1023 20:02:55.515658    1021 watcher.go:87] Error while processing event ("/sys/fs/cgroup/devices/libcontainer_17981_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDI
Oct 23 20:02:55 kube-node-2 kubelet[1021]: W1023 20:02:55.515724    1021 watcher.go:87] Error while processing event ("/sys/fs/cgroup/pids/libcontainer_17981_systemd_test_default.slice": 0x40000100 == IN_CREATE|IN_ISDIR):
Oct 23 20:02:55 kube-node-2 dockerd[1078]: time="2019-10-23T20:02:55.521155697Z" level=error msg="Error running exec 9e2a82c84b2a89d312efac807aa55cf8c759dc206ff204f07957630e655f4a88 in container: OCI runtime exec failed: 
...

```

**Comment by neolit123** [comment]
@dannymk thanks for the report. this is concerning, but not a kubeadm issue.

> OCI runtime exec failed: 

i think after the `:` it should include more details for the reason.

please copy the contents of you report and log a kubernetes/kubernetes issue, instead.

also add the following as a comment:
```
/kind bug
/sig node
@kubernetes/sig-node-bugs 
```
thanks.
/close
