### ISSUE TITLE
CoreDNS KubeAdm v1.15.4 Linux 16.04 

### ISSUE THREAD

**Issue by patsadow2** [kubernetes/kubeadm#1859]
Pods cannot access coreDNS ;(
![image](https://user-images.githubusercontent.com/19226186/67705425-41d01c80-f9b7-11e9-8ec5-c61a5294e35d.png)

## Anything else we need to know?

Access to coreDNS ? I am wondering if it can be problem with namespaces ?

**Comment by neolit123** [comment]
hi, this is not a kubeadm bug.
kubeadm is just a user of coredns.

also please note that busy-box is known to be problematic with respect to DNS.
try using another image for nslookup, such as `debian:...`.

/triage support
/close
