### ISSUE TITLE
How does kubeadm recognize master node

### ISSUE THREAD

**Issue by Lokicity** [kubernetes/kubeadm#186]
When I run kubectl get nodes
Under status, it shows READY.MASTER
However, when I just look at the output from localhost:8081/api/v1/nodes. Under status, it only shows ready but nothing really indicating that this node is a master node.

{
            "type": "Ready",
            "status": "True",
            "lastHeartbeatTime": "2017-02-28T19:57:02Z",
            "lastTransitionTime": "2017-02-28T19:40:01Z",
            "reason": "KubeletReady",
            "message": "kubelet is posting ready status. AppArmor enabled"
}

Where to specify the master tag so that it recognize the node as a master node from kubectl get nodes? Thanks!

**Comment by Lokicity** [comment]
Solved

**Comment by sheerun** [comment]
It's good to post a solution when something is solved

In this case it's probably node label `kubeadm.alpha.kubernetes.io/role=master`

**Comment by luxas** [comment]
This will change in v1.6 to `node-role.kubernetes.io/master=""`, ref: #151
