### ISSUE TITLE
stop calling /bin/sleep during upgrade prepull

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1862]
with all control-plane images going for distroless, see:
https://github.com/kubernetes/kubernetes/issues/70249

we need to stop executing arbitrary commands on the containers we create during prepull.
such a command is "sleep":
https://github.com/kubernetes/kubernetes/blob/3758426884e3c82cbd99c72e8015f4396f21fde2/cmd/kubeadm/app/phases/upgrade/prepull.go#L182

ideally the prepull DaemonSets should be replaced with Jobs.
EDIT: or keep them as a DaemonSets but delete them after a while. from a go routine.

**Comment by rosti** [comment]
My bet here is that we should probably stop using a DaemonSet for the job. We should probably reuse the ImagePullCheck on each node.

**Comment by neolit123** [comment]
my PR that replaces /bin/sleep is here:
https://github.com/kubernetes/kubernetes/pull/90320

@rosti 

> My bet here is that we should probably stop using a DaemonSet for the job. We should probably reuse the ImagePullCheck on each node.

i tend to agree. pre-pulling control-plane images for all control-plane nodes using a daemon set seems convenient in terms of performing one action for multiple targets, but other than that it's inconsistent with ImagePullCheck.

@fabriziopandini 

> we should ensure images are pre-pulled on all nodes (this is mandatory e.g. when using locally built images and we are relying on this for our test grid)

for upgrade e2e, kinder node images should contain both old and target upgrade version of images; is that not the case? which makes the pre-pull during "apply" not really needed.

we should discuss @rosti proposal for replacing the DS prepull and potentially refactor kinder if needed, but in the meantime we should proceed with https://github.com/kubernetes/kubernetes/pull/90320
and potentially log a new issue. maybe close https://github.com/kubernetes/kubeadm/issues/2109 too.
