### ISSUE TITLE
Kinder: cleanup support for v1.11 and v1.12 Kubernetes releases

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1866]
kinder is a tools used for kubeadm E2E tests and can be run locally. see https://github.com/kubernetes/kubeadm/tree/master/kinder

Considering that in kubeadm E2E we are not testing anymore v1.11 and v1.12 Kubernetes releases, it is now possible to clean up the kinder codebase from support for those releases:

**remove V1_11 and v1_12 constants here:**

https://github.com/kubernetes/kubeadm/blob/004aff411a9fe0ba1fce9c8990680ef6f5251325/kinder/pkg/constants/constants.go#L103-L106

**remove support for v1alpha2 API here**

https://github.com/kubernetes/kubeadm/blob/004aff411a9fe0ba1fce9c8990680ef6f5251325/kinder/pkg/kubeadm/config.go#L56
https://github.com/kubernetes/kubeadm/blob/004aff411a9fe0ba1fce9c8990680ef6f5251325/kinder/pkg/kubeadm/config.go#L86
https://github.com/kubernetes/kubeadm/blob/004aff411a9fe0ba1fce9c8990680ef6f5251325/kinder/third_party/kind/kubeadm/config.go#L72-L147

**Comment by hypnoglow** [comment]
Hi,

I noticed there are other places where older versions of kubeadm config are supported in one way or another, for example:

Patches, e.g. for Calico:

https://github.com/kubernetes/kubeadm/blob/fe0d2ce5a6701c2559969c363a909fdad18b761b/kinder/pkg/kubeadm/calicopatch.go#L44-L46

References to **MasterConfiguration** which was renamed to **InitConfiguration** in v1alpha3:

https://github.com/kubernetes/kubeadm/blob/fe0d2ce5a6701c2559969c363a909fdad18b761b/kinder/pkg/cluster/manager/actions/kubeadm-config.go#L327-L330

And so on.

Doesn't this also relate to the issue? Or those should be kept for some reason? I'm new to the project, so I'm trying to understand possible caveats.

Thanks.

**Comment by fabriziopandini** [comment]
@hypnoglow thanks for noticing this! really appreciated!
reference to "v1alpha2" should go away; same for references to "MasterConfiguration"

**Comment by fabriziopandini** [comment]
/close
via https://github.com/kubernetes/kubeadm/pull/1870
