### ISSUE TITLE
kubeadm failed to start

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubeadm#187]
The admisssion control `DefaultTolerationSeconds` cause the problem.

kubeadm version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.445+36a5c0091bcaff", GitCommit:"36a5c0091bcafffd0fb2025b9501e6223a46f169", GitTreeState:"clean", BuildDate:"2017-02-28T04:58:02Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

see  https://github.com/kubernetes/kubernetes/issues/42228

**Comment by luxas** [comment]
As I wrote there, this will be fixed once `v1.6.0-beta.1` is released and kubeadm is updated to use that version by default.
