### ISSUE TITLE
Export join command for new master

### ISSUE THREAD

**Issue by TheLastProject** [kubernetes/kubeadm#1872]
*This is meant to be discussed on the upcoming kubeadm office hours meeting on 2019-11-6*

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Currently, kubeadm has the `token create --print-join-command` command, to show the command to let a new worker node to join your cluster. There is however no way to directly export the join command for letting a new master node join your cluster.

There are multiple ideas on how to solve this:
### Add a new command under the token namespace
This is the idea currently implemented in kubernetes/kubernetes#84591. However, @ereslibre and @neolit123 expressed the concern that the token command dealing with certificates breaks the separation of concerns. I agree there.

### Move --print-join-command out of the token command
This seems the cleanest way to me. It would deprecate `token create --print-join-command` in favour of new commands such as:
`print-join-command worker --token=[optional]`
`print-join-command master --token=[optional] --certificate=[optional]`
These commands will create a new token and/or certificate if not given and otherwise simply print the join commands with the given information. The exact command names still needs to be decided.

### Something else altogether
There may be other good ways too, feel free to add to this issue.

**Comment by neolit123** [comment]
thanks for logging the issue.

**Comment by SataQiu** [comment]
I'm also very supportive of adding this feature！

**Comment by neolit123** [comment]
i have added this as an agenda item for the meeting on wednesday.
https://docs.google.com/document/d/130_kiXjG7graFNSnIAgtMS1G8zPDwpkshgfRYS0nggo/edit

**Comment by neolit123** [comment]
@TheLastProject 
we had a discussion about this during the office hours and @fabriziopandini proposed that instead we add a `--certificate-key` as a flag to `kubeadm create token` command next to the `--print-join-command` flag. this will allow users see:
```
$ kubeadm create token --print-join-command --certificate-key=my-key
kubeadm join ..... --control-plane --certificate-key=my-key
```

i'm not a big fan of this solution, but probably we can go for it.
if you want to update your PR, the deadline for non-bug fixes in 1.17 is 15th of November.

**Comment by TheLastProject** [comment]
Not a huge fan of that solution either (sadly wasn't able to join in because Zoom bugged out and insisted I waited for the host to start the meeting even though that apparently already happened...) but it's better than nothing, I'll implement that.

**Comment by neolit123** [comment]
ok, sounds good.

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/pull/84591 is merging.
thanks @TheLastProject 

LMK if you want to help with other areas of kubeasm. we have a number of help-wanted ticktes,
