### ISSUE TITLE
Cluster creation failed with unsupported docker version

### ISSUE THREAD

**Issue by muemich** [kubernetes/kubeadm#189]
Due to the new versioning of Docker the preflight check is failing
`DOCKER_VERSION: 17.03.0-ce
[preflight] Some fatal errors occurred:
    unsupported docker version: 17.03.0-ce
[preflight]`

You can get it working when forcing to skip the preflight check

**Comment by dmmcquay** [comment]
I'll grab this one.

**Comment by cooligc** [comment]
+1 

Same issue in RHEL7

**Comment by dmmcquay** [comment]
@luxas this got solved in https://github.com/kubernetes/kubernetes/issues/42425
