### ISSUE TITLE
kubeadm init times out with custom config file

### ISSUE THREAD

**Issue by tokiwinter** [kubernetes/kubeadm#1890]
## Versions

**kubeadm version** (use `kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:15:39Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}`):

**Environment**:
- **Kubernetes version** ```Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}```
- **Cloud provider or hardware configuration**: Running in an LXD container
- **OS** Ubuntu 16.04
- **Kernel** (e.g. `Linux k8s-master-0 4.4.0-1087-aws #98-Ubuntu SMP Wed Jun 26 05:50:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`):
- **Others**:

## What happened?

I created an initial config file with:

```
kubeadm config print init-defaults > kubeadm.conf
```
I added
```
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
conntrack:
  maxPerCore: 0
```

To the bottom of the config file and ran:
```
kubeadm init --config kubeadm.conf
```

The API server failed to come online and the `kubeadm init` run exited with:
```
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
```
If I check the docker logs of the API server container, I see `panic: context deadline exceeded` followed by a Go stack trace.

## What you expected to happen?

A control plane to come online. This works without passing `--config`.

## How to reproduce it (as minimally and precisely as possible)?

As described above.

## Anything else we need to know?

Please let me know if you need further information.

**Comment by tokiwinter** [comment]
It seems to be an issue connecting to etcd
```
W1106 22:17:15.165577       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting..
```
Which is binding to an invalid address 
```
2019-11-06 22:17:14.562014 C | etcdmain: listen tcp 1.2.3.4:2380: bind: cannot assign requested address
```

**Comment by luxas** [comment]
Does it work if you _only_ specify the kubeproxy YAML document, omitting all other kubeadm-specific YAML? Then everything kubeadm-related will use the defaults, which are dynamically detected.
`kubeadm config print init-defaults` should only be used for advisory cases, not programmatically.

**Comment by tokiwinter** [comment]
If I do that, I receive:

```
no InitConfiguration or ClusterConfiguration kind was found in the YAML file
To see the stack trace of this error execute with --v=5 or higher
```

**Comment by tokiwinter** [comment]
I can get things to work by modifying the generated YAML config and setting:
```
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
```
To the correct master IP of the node, though I'm sure this is not the correct way of doing things.

**Comment by neolit123** [comment]
> kubeadm config print init-defaults should only be used for advisory cases, not programmatically.

+1

it defaults an address to `1.2.3.4` which should not be used:
```
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
```

i think the minimal configuration you want to use is:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
conntrack:
  maxPerCore: 0
```

**Comment by tokiwinter** [comment]
This works, thank you

**Comment by neolit123** [comment]
thanks for confirming.
