### ISSUE TITLE
 The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.

### ISSUE THREAD

**Issue by veera2019** [kubernetes/kubeadm#1893]
i have installed kubernetes on rhel7.4 
when i run kubeadm init i am getting error like
 **The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.**

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

can some one guide me to resolve this error

**Comment by neolit123** [comment]
try calling kubeadm reset, then kubeadm init again and look at the kubelet log right after this happens using `journalctl -xeu kubelet` and share them here.

/triage support

**Comment by veera2019** [comment]
Thanks i have done kubectl reset and i have increased the memory size and it's running fine.
can you tell me how to make single master node cluster i want to set up in one instance only master and node how can we do this

**Comment by neolit123** [comment]
> Thanks i have done kubectl reset and i have increased the memory size and it's running fine.

thanks for confirming that it works.

> can you tell me how to make single master node cluster i want to set up in one instance only master and node how can we do this

calling `kubeadm init` on one machine will give you a single control-plane instance (one master). then you can join workers to it. if you don't join any new control-planes using `kubeadm join control-plane...` you will remain with a single control-plane.

**Comment by venkatakrishna-biarca** [comment]
> Thanks i have done kubectl reset and i have increased the memory size and it's running fine.
  That must be kubeadm reset not kubectl reset
> can you tell me how to make single master node cluster i want to set up in one instance only master and node how can we do this

**Comment by venkatakrishna-biarca** [comment]
> Thanks i have done kubectl reset and i have increased the memory size and it's running fine.
**That must be kubeadm reset  but not kubectl reset**
> can you tell me how to make single master node cluster i want to set up in one instance only master and node how can we do this

**Comment by CentUser** [comment]
> Thanks i have done kubectl reset and i have increased the memory size and it's running fine.
> can you tell me how to make single master node cluster i want to set up in one instance only master and node how can we do this

Encountered this problem, minikube 1.12.1 docker 18.0.1 centos 8.1 kubernets version 1.18.3.

Tried your way, failed.

**Comment by cheeseyeah** [comment]
i have installed kubernetes on arm
and I have the same problem as you
**The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.**

but after i reset kubeadm , the problem remains
can you tell me the detailed solution process, thanks

**Comment by rendler-denis** [comment]
@cheeseyeah and anyone else stumbling upon this thread: in my case the containers where not created, or at least they weren't there after the kubeadm command finished. I managed to make it work only after disabling swap. This is crazy, from my point of view, because swap is a normal OS function and shouldn't create this bizarre behavior. But, hey, it works.

**Comment by babyalpha-icentric** [comment]
It's been a while but posting for any others who might stumble on a similar issue.
I have stumbled up a similar issue. I have found the problem with 'journalctl -xeu kubelet'. My problem was cgroup driver. Kubernetes cgroup driver was set to systems but docker was set to systemd.
I added docker config file '/etc/docker/daemon.json' and added below to the file.
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}

**Comment by glitterlip** [comment]
might be a docker version mismatch issue.I have a master docker 19.03 and node docker 18.03, after update node docker to 20.10, this issue resolved

**Comment by bikrampaul** [comment]
"swapoff -a" try to run this command it will fix the issue sure .

**Comment by Mallikarjuna1985** [comment]
Above all im trying but issue not solved

**Comment by vmacarrein** [comment]
I got the same issue during the installation. The kubelet was not running. in the procedure of kubelete installation you must to configure the docker container (I think they have remove this part in the procedure):

sudo mkdir /etc/docker
cat <<EOF | sudo tee /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF

sudo systemctl enable docker
sudo systemctl daemon-reload
sudo systemctl restart docker

Check if the kubelet became running:
sudo systemctl status kubelet

The procedure is in: 

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

**Comment by alainhenryt** [comment]
> I got the same issue during the installation. The kubelet was not running. in the procedure of kubelete installation you must to configure the docker container (I think they have remove this part in the procedure):
> 
> sudo mkdir /etc/docker
> cat <<EOF | sudo tee /etc/docker/daemon.json
> {
> "exec-opts": ["native.cgroupdriver=systemd"],
> "log-driver": "json-file",
> "log-opts": {
> "max-size": "100m"
> },
> "storage-driver": "overlay2"
> }
> EOF
> 
> sudo systemctl enable docker
> sudo systemctl daemon-reload
> sudo systemctl restart docker
> 
> Check if the kubelet became running:
> sudo systemctl status kubelet
> 
> The procedure is in:
> 
> https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

Thank you  @vmacarrein. The above slution was very helpful. Used it to resolve kubeadm init.

**Comment by 842Mono** [comment]
> It's been a while but posting for any others who might stumble on a similar issue.
> I have stumbled up a similar issue. I have found the problem with 'journalctl -xeu kubelet'. My problem was cgroup driver. Kubernetes cgroup driver was set to systems but docker was set to systemd.
> I added docker config file '/etc/docker/daemon.json' and added below to the file.
> {
> "exec-opts": ["native.cgroupdriver=systemd"]
> }

This worked for me. We just need to execute some commands after creating the file. Below are the commands one after the other:

```
cat <<EOF | sudo tee /etc/docker/daemon.json\n{\n"exec-opts": ["native.cgroupdriver=systemd"]\n}\nEOF\n
sudo systemctl enable docker && sudo systemctl daemon-reload && sudo systemctl restart docker
```

**Comment by rangercyh** [comment]
> It's been a while but posting for any others who might stumble on a similar issue.
> I have stumbled up a similar issue. I have found the problem with 'journalctl -xeu kubelet'. My problem was cgroup driver. Kubernetes cgroup driver was set to systems but docker was set to systemd.
> I added docker config file '/etc/docker/daemon.json' and added below to the file.
> {
> "exec-opts": ["native.cgroupdriver=systemd"]
> }

I do the same to docker and solve the problem,thx

**Comment by Sunnatillo** [comment]
> sudo systemctl enable docker && sudo systemctl daemon-reload && sudo systemctl restart docker

the same worked for me. Thanks

**Comment by youguanxinqing** [comment]
> I got the same issue during the installation. The kubelet was not running. in the procedure of kubelete installation you must to configure the docker container (I think they have remove this part in the procedure):
> 
> sudo mkdir /etc/docker cat <<EOF | sudo tee /etc/docker/daemon.json { "exec-opts": ["native.cgroupdriver=systemd"], "log-driver": "json-file", "log-opts": { "max-size": "100m" }, "storage-driver": "overlay2" } EOF
> 
> sudo systemctl enable docker sudo systemctl daemon-reload sudo systemctl restart docker
> 
> Check if the kubelet became running: sudo systemctl status kubelet
> 
> The procedure is in:
> 
> https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

work for me, thanks!

**Comment by m-karakus** [comment]
> I got the same issue during the installation. The kubelet was not running. in the procedure of kubelete installation you must to configure the docker container (I think they have remove this part in the procedure):
> 
> sudo mkdir /etc/docker cat <<EOF | sudo tee /etc/docker/daemon.json { "exec-opts": ["native.cgroupdriver=systemd"], "log-driver": "json-file", "log-opts": { "max-size": "100m" }, "storage-driver": "overlay2" } EOF
> 
> sudo systemctl enable docker sudo systemctl daemon-reload sudo systemctl restart docker
> 
> Check if the kubelet became running: sudo systemctl status kubelet
> 
> The procedure is in:
> 
> https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

this one is worked for me too. Thanks

do these steps;

```sudo kubeadm reset```
```sudo apt-get install -qy kubelet kubectl kubeadm```
```sudo apt-mark hold kubelet kubeadm kubectl```
```sudo mkdir /etc/docker```
```cat <<EOF | sudo tee /etc/docker/daemon.json
{
"exec-opts": ["native.cgroupdriver=systemd"],
"log-driver": "json-file",
"log-opts": {
"max-size": "100m"
},
"storage-driver": "overlay2"
}
EOF
```
```sudo systemctl enable docker```
```sudo systemctl daemon-reload```
```sudo systemctl restart docker```
```sudo kubeadm init --control-plane-endpoint kube-master:6443 --pod-network-cidr=192.168.0.0/16```

**Comment by sreedhark1243** [comment]
Thanks so much this was clueless for me since two days. This worked fantastically !
