### ISSUE TITLE
kinder: stop calling etcdctl from within the etcd containers

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1898]
with all control-plane images and etcd going for distroless, see:
kubernetes/kubernetes#70249

we need to stop executing `etcdctl` from within the etcd containers in kinder.

potential solution is to get the etcdctl version that we want from the etcd tarballs and execute it from a temporary directory:
https://github.com/etcd-io/etcd/releases

cc @fabriziopandini

**Comment by fabriziopandini** [comment]
Another option is described here https://mauilion.dev/posts/etcdclient/

**Comment by neolit123** [comment]
> Another option is described here https://mauilion.dev/posts/etcdclient/

this would require us to build our own image that has etcdctl, 
the `k8s.gcr.io/etcd:VERSION` image will not have it at some point.

**Comment by fabriziopandini** [comment]
pro and cons. 
considering the latest breaking changes in etcd, I would prefer to not rely on etcd tarballs...

**Comment by neolit123** [comment]
the breaking changes manifested without relying on tarballs.

if we start pulling tarbals to execute etcdctl we still need the different CA flags for etcdctl.
same goes if we start maintaining an etcdctl image - it still needs different CA flags.

i'd prefer the tarballs, but ideally the etcd and etcdctl binaries should be hosted in a separate tarballs.

**Comment by neolit123** [comment]
/remove-lifecycle stale
looking at the WIP PR for distorless etcd image, it seems that the etcdctl is preserved and etcd is not the only binary. will continue tracking this issue until the work there is complete.

**Comment by neolit123** [comment]
It seem etcdctl is going to stay in the image, since others depend on it
too. but we can keep this open for longer if they change their mind.

**Comment by neolit123** [comment]
/lifecycle frozen
etcdctl is still in the etcd image. unclear if we every have to do this.

**Comment by neolit123** [comment]
> /lifecycle frozen etcdctl is still in the etcd image. unclear if we every have to do this.

close for now
