### ISSUE TITLE
How to pass --pod-network-cidr via config

### ISSUE THREAD

**Issue by tokiwinter** [kubernetes/kubeadm#1899]
I am stuck trying to initialise a `kubeadm`-based master.

I am currently mixing command line params as well as a config file, which it would appear is not allowed, although the guide shows the passing of the `--pod-network-cidr` flag when installing a particular network overlay such as flannel. I have a config file for `kube-proxy` to work properly.

```
kubeadm init --pod-network-cidr=10.244.0.0/16 --config /etc/kubeadm.conf --ignore-preflight-errors=all
```
Would appreciate assistance on how to get `--pod-network-cidr` into my config file which currently looks like this:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
conntrack:
  maxPerCore: 0
```
Sorry for the simple question, but I have a hard deadline of the 19th to get this up and running, and figure there is a pool of knowledge here.

**Comment by neolit123** [comment]
/triage support

> I am currently mixing command line params as well as a config file,

flag and config mixtures are problematic in k8s components and we are working on creating a standard policy. until then please use config only for options present in both locations.

> Would appreciate assistance on how to get --pod-network-cidr into my config file which currently looks like this:

see
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

Would appreciate assistance on how to get --pod-network-cidr into my config file which currently looks like this:
```
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: "v1.12.0" # your version
kind: ClusterConfiguration
networking:
  podSubnet: "10.100.0.1/24" # --pod-network-cidr
```

**Comment by tokiwinter** [comment]
Thanks much

**Comment by alexcpn** [comment]
Thanks ;
If you want to pass some other config
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: containerd
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  podSubnet: "10.244.0.0/16" # --pod-network-cidr
```
