### ISSUE TITLE
[kubeadm] Only supports configuration from one source at a time, flags or file

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#19]
_From @pires on October 27, 2016 17:54_

Currently, one `kubeadm {init,join}` can only be configured through flags _or_ configuration file. So:

```
kubeadm init --config master.yaml
```

or

```
kubeadm init <flags>
```

Both configuration options don't coexist as users may expect it to (#35424).

_Copied from original issue: kubernetes/kubernetes#35710_

**Comment by jamiehannaford** [comment]
Since https://github.com/kubernetes/kubernetes.github.io/pull/4112 has been merged, we can go ahead and close this 🎆

**Comment by luxas** [comment]
Thanks for helping out on this one :+1:
