### ISSUE TITLE
kinder: remove few kind dependencies

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1902]
As part of a broader effort for simplifying the upgrade of kind dependency inside kinder, we should remove following dependencies with calls to kinder methods that provide similar features.

https://github.com/kubernetes/kubeadm/blob/1d66b0bda0976526ec169988a9d5d6109e6ca120/kinder/cmd/kinder/get/get.go#L23-L25

I'm going to update details as soon as https://github.com/kubernetes/kubeadm/pull/1901 will merge

**Comment by frederiko** [comment]
@fabriziopandini If no one is working on it yet, I'm happy to help. Let me know.

**Comment by fabriziopandini** [comment]
@frederiko thanks for volunteering for this task!
/lifecycle active

**Comment by neolit123** [comment]
the two linked PRs seem to cover the list in the OP.
please re-open if needed.
/close
