### ISSUE TITLE
create new survey for KubeCon EU 2020

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1915]
old survey was here:
https://docs.google.com/forms/d/1A855D054FZfdvNbx6mAa54tcZ204GmPCIhxe1UrXKd8/edit#responses

we can recycle some of the old questions but think of what else we can add.

WIP doc:
https://docs.google.com/document/d/1OokYTBOk61yWIoDzNnTDNvDfuoUswgyO8P2wzfCY4WY/edit#heading=h.4rulgguq5155

form:
https://forms.gle/WVBH3J2sTt4zvt2e9

**Comment by fabriziopandini** [comment]
Thanks @neolit123 for driving this effort!

**Comment by neolit123** [comment]
this work is pretty much done.
see updates in the google doc mentioned above.
we will be closing this ticket and opening the survey before kubecon 2020 eu.

**Comment by neolit123** [comment]
survey results will be avail on the 8th of Sept.
we can close this ticket after that.
