### ISSUE TITLE
MVP: kubeadm-dind-cluster version suitable for inclusion in kubeadm

### ISSUE THREAD

**Issue by ivan4th** [kubernetes/kubeadm#192]
Followup on discussion in #17.

This issue concerns the plans of inclusion of [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) in kubeadm repo and describes the requirements for kubeadm-dind-cluster that must be satisfied to make this possible.

[kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) provides the means of starting DIND (Docker-in-Docker) k8s cluster easily. Currently it builds k8s from source (including kubeadm), but support for prebuilt images that include the binaries is coming soon.

I'll start with points raised [here](https://github.com/kubernetes/kubeadm/issues/17#issuecomment-283143386) by @luxas:

> It should ideally be written in Go -- I generally think we are trying to move away from Bash, so Go is the way to Go for a new project I think :)

I agree here. Indeed it got complex enough to justify Go rewrite. I suggest that I complete the current update I'm working on and then start rewriting the scripts in Go. 

> The debian base should be based on gcr.io/google-containers/debian-base-$(ARCH):0.1

Ok, I'll check whether there any difficulties with switching from Ubuntu Xenial to this image. I suspect there should be no serious problems, but not 100% sure about at the moment.

> The base image for dind should ideally be published to gcr.io

No problem here.

> It should work on multiple arches like kubeadm

Didn't try kubeadm on ARM etc yet, but I don't think that's much of a problem. Will do this. BTW recent dockers support running images built for different arch - natively on Mac/Win, likely also easily doable on Ubuntu 16.04.2 that has newer kernel with support for `F` flag in [binfmt_misc](https://github.com/torvalds/linux/blob/e7aa8c2eb11ba69b1b69099c3c7bd6be3087b0ba/Documentation/admin-guide/binfmt-misc.rst) (fix binary - so e.g. `qemu-arm` can run outside container) -- this may help, too.

> You should be able to provide your own binaries, but most often it should download from the CI that publishes binaries for all arches every hour

After the update I'm currently working on there will be possibility to use both locally-built binaries and binaries downloaded from specific URL.

> It should use CNI -- with network providers swappable

kubeadm-dind-cluster uses CNI bridge plus some hacks currently, but Flannel, Calico etc. are going to be supported very soon

> It should expose its configuration options via a config file like kubeadm can take a config file as input for options

Config is supported currently but it's just a file with some env vars, will perhaps switch to yaml after Go rewrite.

> It should only support kubeadm v1.6+

No problem here.

**Some existing features that I think are useful to keep:**

1. An ability to use remote docker engine without transferring too much data to local machine, this can be quite convenient for hacking on k8s
2. Building k8s and consuming the binaries from the build data container directly
3. Running e2e tests against the cluster (may add node e2e tests later, too)
4. Support for Mac Docker
5. Enabling feature gates for apiserver/kubelet, this may be handy in a number of situations (e.g. `StreamingProxyRedirects` for working with CRI in k8s 1.5 or `DynamicKubeletConfiguration` that's needed for some tests etc.)

In addition to this there are some useful things to be added in the coming update:
1. Support for k8s master - there's some minor incompatibility with kube-proxy DS
2. Support prebuilt complete DIND images to make it easier to use the test cluster in CI setting for k8s-related projects such as [AppController](https://github.com/Mirantis/k8s-AppController) and [Virtlet](https://github.com/Mirantis/virtlet)
3. Fast cluster restarts via caching of docker data and changes made by kubeadm (via `docker diff` + `tar`)
4. It should be possible to start the cluster after downloading a single file (either a script or a binary).

One of the issues that need to be discussed is how the test cluster app should be distributed. There are a couple of possible approaches:

- there can be a binary that lives inside DIND containers and does necessary housekeeping there and another one that lives outside and is invoked by the user (it can be the same one actually but we will have to provide versions for Mac and ARM at least). The latter must be downloaded separately, or
- everything runs inside containers, including the binary responsible for all the magic, the user only needs to download a tiny wrapper script that starts some kind of 'bootstrap' container and points it at docker socket.

Another (perhaps simpler) issue is how to name it. Should we keep `kubeadm-dind-cluster` name or invent another?

I'd suggest the following plan:
1. I complete the current update to kubeadm-dind-cluster project (ETA: ~Mar 6)
2. I can then show a demo of its current state & features (e.g. on sig-cluster-lifecycle meeting)
3. We discuss what else needs to be done here
4. If it all goes well I commence the Go rewrite
5. Go version of kubeadm-dind-cluster is included in kubeadm repo (maybe under some other name)

cc @luxas  @jbeda @lukemarsden @errordeveloper @mikedanese @timothysc @sttts @pigmej @idvoretskyi @zen

**Comment by timothysc** [comment]
@ivan4th did you have a PR planned or in flight?

**Comment by ivan4th** [comment]
@timothysc as of the Go rewrite, not yet. Original [kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster) project has already gained the features described in "coming update" section here though. For the rewrite there's now community proposal: kubernetes/community#629

I'd love to move quicker but unfortunately that's not the only project I'm working on.

Closing this PR in favor of the community proposal above.
