### ISSUE TITLE
RFE: Help implementing unit tests for the operator

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#1920]
The skelethon for the kubeadm operator is there, but it is now necessary to write a bunch of unit test to ensure it works and avoid regressions 

https://github.com/kubernetes/kubeadm/pull/1919 adds the first set of unit tests; some of them have to be repeated for other controllers, and this issue is seeking for volunteers to pick up this work (as a whole or in small parts)

- [x] implement `operation_controller_test.go`

   - [x] implement `TestOperatorReconciler_reconcilePhase`, copy paste of https://github.com/kubernetes/kubeadm/blob/bb74d367f72093a4c731028998b4a30f2842cafd/operator/controllers/runtimetask_controller_test.go#L15

   - [x] implement `TestOperatorReconciler_reconcilePause`, copy paste of https://github.com/kubernetes/kubeadm/blob/bb74d367f72093a4c731028998b4a30f2842cafd/operator/controllers/runtimetask_controller_test.go#L155

- [x] implement `runtimetaskgroup_controller_test.go`

   - [x] implement `TestRuntimeTaskGorupReconciler_reconcilePhase`, copy paste of https://github.com/kubernetes/kubeadm/blob/bb74d367f72093a4c731028998b4a30f2842cafd/operator/controllers/runtimetask_controller_test.go#L15

   - [x] implement `TestRuntimeTaskGroupReconciler_reconcilePauseOverride `, copy paste of https://github.com/kubernetes/kubeadm/blob/bb74d367f72093a4c731028998b4a30f2842cafd/operator/controllers/runtimetask_controller_test.go#L155

- [x] implement `runtimetaskgroup_reconcile_test.go`
   
   this should be a copy/paste of https://github.com/kubernetes/kubeadm/blob/bb74d367f72093a4c731028998b4a30f2842cafd/operator/controllers/runtimetask_reconcile_test.go and include two unit tests `Test_newTaskGroupReconcileItem` and `Test_reconcileTaskGroups`

Also, many other unit tests are required, reach out if interested!

**Comment by RA489** [comment]
@fabriziopandini Anything remaining for help in this effort?

**Comment by fabriziopandini** [comment]
/close
I will reconsider this as soon as the work on the operator takes new strength
