### ISSUE TITLE
Kubeadm possible uses wrong image for kube-controller-manager

### ISSUE THREAD

**Issue by valumar** [kubernetes/kubeadm#1926]
The page related to [Storage classes](https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner) tells us that RBD Plugin realized as an Internal provisioner but it's not true since kubeadm uses `image: k8s.gcr.io/kube-controller-manager` which doesn't have rbd on board. If you try to create PVC with kubeadm provisioned cluster you get the message:
```
Events:
  Type     Reason              Age                  From                         Message
  ----     ------              ----                 ----                         -------
  Warning  ProvisioningFailed  2m5s (x20 over 30m)  persistentvolume-controller  Failed to provision volume with StorageClass "rbd-data": failed to create rbd image: executable file not found in $PATH, command output:
```
But changing the image for Controller Manager to hyperkube solves the [issue](https://github.com/kubernetes/kubernetes/issues/85454#issuecomment-555639080).

**Comment by neolit123** [comment]
hello, hyperkube is being deprecated in kubeadm and the support will be removed in the next releases.
this is tracked here:
https://github.com/kubernetes/kubeadm/issues/1889

in terms of the problems related to RBD, this is not a kubeadm issue. i see you logged https://github.com/kubernetes/kubernetes/issues/85454 but i think an issue about that existed already and it had many comments in kubernetes/kubernetes.

on the side of kubeadm, you have the option of rebuilding all control-plane components (with KCM having RDB) and pushing them to a custom registry. then using kubeadm's imageRepository option you can use your custom build.

this is really something that should be discussed with sig-release and sig-storage. try joining their slack channels and/or meetings.

thanks
/sig release storage
/triage support
/close
