### ISSUE TITLE
/var/lib/kubelet/kubeadm-flags.env not updated during kubeadm upgrade

### ISSUE THREAD

**Issue by pickledrick** [kubernetes/kubeadm#1927]
#1247  What keywords did you search in kubeadm issues before filing this one?

- kubeadm-flags.env
- upgrade

FEATURE REQUEST

If this is a FEATURE REQUEST, please:
  - The request is for /var/lib/kubelet/kubeadm-flags.env to be updated during `kubeadm upgrade`. An example of how we found this was during an upgrade. We were renaming an image repository, for example, `vmware/pause:3.1` to `vmware.io/pause:3.1. The kubelet flag `--pod-infra-container-image=` makes use of this image and during an upgrade, this was not upgraded. 

## Versions

**kubeadm version** (use `kubeadm version`):

`v1.16.2`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `v1.16.2`
- **Cloud provider or hardware configuration**: `baremetal`
- **OS** (e.g. from /etc/os-release): `ubuntu 18.04`
- **Kernel** (e.g. `uname -a`): `Linux host 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

## What happened?

We did see that kubeadm-flags.env are stated not to be updated during an upgrade
https://github.com/kubernetes/kubernetes/blob/2e6b073a3f800654ec217e763fcb97412308a9db/cmd/kubeadm/app/util/config/cluster.go#L133

and that the preferred method is to update the NodeRegistration.KubeletExtraArgs in the kubeadm config
https://github.com/kubernetes/kubernetes/blob/d5fbc1126bdb7462cca43f39cb15b336e28fdc00/build/rpms/10-kubeadm.conf

A `kubeadm upgrade` setting the NodeRegistration.KubeletExtraArgs in the kubeadm config was unsuccessful and the `/var/lib/kubelet/kubeadm-flags.env` remained unchanged. However, when performing `kubeadm init phase kubelet-start` the configuration applied the changes to the file.

We would like to understand the reasoning behind `kubeadm upgrade` not modifying the `/var/lib/kubelet/kubeadm-flags.env`file. And, if feasible allow it to

## What you expected to happen?

`/var/lib/kubelet/kubeadm-flags.env` not updated during `kubeadm upgrade`

## How to reproduce it (as minimally and precisely as possible)?

- update the kubeadm config file to reference a new imageRepository (for example)
- run kubeadm upgrade referencing the kubeadm config

**Comment by pickledrick** [comment]
duplicates https://github.com/kubernetes/kubeadm/issues/1916

**Comment by fabriziopandini** [comment]
> What you expected to happen?
> /var/lib/kubelet/kubeadm-flags.env NOT updated during kubeadm upgrade

https://github.com/kubernetes/kubernetes/pull/85412 fixed the issue; see https://github.com/kubernetes/kubeadm/issues/1916#issuecomment-559495330 (and following thread)  for the detailed explanation
