### ISSUE TITLE
Different crictl and cni versions for different OS in kubeadm documentation.

### ISSUE THREAD

**Issue by Baykonur** [kubernetes/kubeadm#1935]
## What keywords did you search in kubeadm issues before filing this one?
crictl version, cni version
## Is this a BUG REPORT or FEATURE REQUEST?
It is a request for documentation update and clarification of pre-requisite package versioning. 
Choose one: BUG REPORT or FEATURE REQUEST

## Versions
```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
`bare-metal`
- **OS** (e.g. from /etc/os-release):
```
# cat /etc/os-release
NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"
```
- **Kernel** (e.g. `uname -a`):
`Linux luu2008p 4.12.14-95.24-default #1 SMP Thu Jul 11 13:05:06 UTC 2019 (7b265b8) x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?
Please see version discrepancy for crictl and cni in [filelist.xml](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml) (which is taken from [installing-kubeadm-kubelet-and-kubectl](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) see _CentOS, RHEL and Fedora_ Tab) and same [kubeadm link](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl), _Container Linux_ tab this time: **For kubernetes-cni, it is 0.8.2 against 0.7.5 and for cri-tools, it is 1.16.0 against 1.13.0**.

## What you expected to happen?
I would have expected to see same kubernetes-cni and cri-tools versions for all OS.
I can understand [filelists.xml](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml) might be wrong but could you please explicitly set the required versions of kubernetes-cni and cri-tools in [that section](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) of documentation?

## How to reproduce it (as minimally and precisely as possible)?
N/A

## Anything else we need to know?
N/A

**Comment by neolit123** [comment]
> I can understand filelists.xml might be wrong 

can you please explain what is wrong in filelists.xml?

> CentOS, RHEL and Fedora Tab) and same kubeadm link, Container Linux tab this time: For kubernetes-cni, it is 0.8.2 against 0.7.5 and for cri-tools, it is 1.16.0 against 1.13.0.

if you are trying to install kubeadm/kubelet 1.16.0 on Fedora it gives you cri-tools 1.13.0 this seems like a bug. are you sure that is the case?

the versions in the container linux tab are correct.

what versions are you getting on Ubuntu/Debian?

**Comment by Baykonur** [comment]
@neolit123, thank you, then we will explicitly get the versions stated in Container Linux tab.

In [filelists.xml](https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/filelists.xml) I would have expected to see cri-tools version 1.16.0 and cni-plugin 0.8.2 but those versions are not there.

We have SLES12SP4 and once we do `zypper in kubeadm kubelet kubectl`, we get cri-tools 1.13.0 and cni plugins 0.7.5. I believe that it is the same case for CentOS, RHEL and Fedora.

**Comment by neolit123** [comment]
> In filelists.xml I would have expected to see cri-tools version 1.16.0 and cni-plugin 0.8.2 but those versions are not there.

if i'm not mistaken, in 1.17 the contents of kubernetes-cni will become part of the kubelet package, while crit-tools will be a manual download for non-docker users.
cc @justaugustus is still still the plan?

> We have SLES12SP4 and once we do zypper in kubeadm kubelet kubectl, we get cri-tools 1.13.0 and cni plugins 0.7.5. I believe that it is the same case for CentOS, RHEL and Fedora.

we have some SUSE developers contributing to kubeadm. perhaps they can give a better advice here:
@ereslibre @Klaven @aojea

**Comment by neolit123** [comment]
just tried a debian install, based on the steps here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

it gave me:
```
master $ sudo apt list --installed | grep kubernetes

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

cri-tools/kubernetes-xenial,now 1.13.0-00 amd64 [installed,automatic]
kubeadm/kubernetes-xenial,now 1.16.3-00 amd64 [installed]
kubectl/kubernetes-xenial,now 1.16.3-00 amd64 [installed]
kubelet/kubernetes-xenial,now 1.16.3-00 amd64 [installed]
kubernetes-cni/kubernetes-xenial,now 0.7.5-00 amd64 [installed]
```

so there are a couple of small problems here:
- the container linux kubernetes-cni version is ahead of the kubernetes recommended version - it should be 0.7.5 instead of 0.8.2. so our guide is wrong for container linux, but this is not a big issue because the newer CNI version is better.
- cir-tools is installed automatically as 1.13, but the version to use is ideally 1.16.0.

please see again my comment above as the potential future of these packages.

**Comment by Baykonur** [comment]
OK, so for latest k8s binaries as today, v1.16.3, the recommended kubernetes-cni version is 0.7.5, for cri-tools it is 1.16.0 and on top of that if the container runtime is docker then cri-tools are not needed?

**Comment by neolit123** [comment]
> on top of that if the container runtime is docker then cri-tools are not needed

it shouldn't be, yes.

>  v1.16.3, the recommended kubernetes-cni version is 0.7.5

yes

> for cri-tools it is 1.16.0

or the latest one from here:
https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.16.1

**Comment by Baykonur** [comment]
Thanks for your help. 
Ultimately it would be beneficial if there is a matrix of versions of all those components in the kubeadm documentation page for different kubernetes versions.

**Comment by neolit123** [comment]
we should try to avoid the matrix ideally.

- the kubelet, kubeadm, kubectl versions should match
- kubernetes-cni will be removed and become part of the kubelet package (already discussed and approved)
- in the kubeadm install guide we should add a note that cri-tools is an optional download (i.e. "please pick the latest version that matches your k8s version").

**Comment by aojea** [comment]
> * kubernetes-cni will be removed and become part of the kubelet package (already discussed and approved)

kubernetes-cni is optional too depending on which CNI plugin do you want to use, I mean, there are CNI plugins that don't require it

**Comment by Baykonur** [comment]
>we should try to avoid the matrix ideally

OK.

>please pick the latest version that matches your k8s version.

I think we users need to know which version of k8s requires which version of cri-tools and kubernetes-cni. For example, we are in need of a v1.15 k8s cluster so I need to know the exact versions of cri-tools and kubernetes-cni that are required.

If you tell me the version in [_Container Linux_ tab](https://v1-15.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl) is to be used at all times, then for me this issue can be closed.

**Comment by neolit123** [comment]
> I think we users need to know which version of k8s requires which version of cri-tools and kubernetes-cni. 

the cri-tools is an obvious one - it's MINOR version matches the MINOR version of k8s.
kubernetes-cni as a package is going away. so for newer versions of k8s you need the kubelet package. for older versions of k8s you need to look at the release notes.

> If you tell me the version in Container Linux tab is to be used at all times, then for me this issue can be closed.

i think we need to rework the container linux tab to be a "generic" tab about downloading the binaries directly without a package manager.

in any case this is not recommended and for advanced users. regular users need `apt` and `yum`.

/close

**Comment by neolit123** [comment]
@aojea 

> kubernetes-cni is optional too depending on which CNI plugin do you want to use, I mean, there are CNI plugins that don't require it

IIRC, the top 3 popular pod network plugins need the package.

**Comment by aojea** [comment]
I had the impression that they were shipping their binaries, a quick look into some of them:

* Calico: https://github.com/projectcalico/calico/blob/67cb745533b7539a00cb7fc03210fb0d689775f3/_includes/master/charts/calico/templates/calico-node.yaml#L77-L79

* Weave ships it's won cni binary and only depends on the portmap plugin
> Weave net depends on the portmap standard CNI plugin to support hostport functionality.

* Flannel: well, this is part of the CNi repository :)
https://github.com/containernetworking/plugins

**Comment by aojea** [comment]
now I remember something related to the loopback plugin, 🤔 maybe I am totally wrong and all of them requires it 😅
