### ISSUE TITLE
Support etcd server overrides in ClusterConfiguration

### ISSUE THREAD

**Issue by jfbai** [kubernetes/kubeadm#1936]
## Is this a BUG REPORT or FEATURE REQUEST?

/kind feature

## What you expected to happen?

Extracting events object to another etcd cluster seems to be common practice via setting `--etcd-server-overrides` flag in a large scale cluster in order to avoid overloading main etcd cluster.

Is it possible to add an option, something like `EtcdOverrides`, in `ClusterConfiguration` to support setting `--etcd-server-overrides`?

**Comment by jfbai** [comment]
I got to know how to achieve this.

**Comment by patrickshan** [comment]
It would be great if we can reopen this issue as this kind of becomes a requirement for big/busy clusters. It can work with `--etcd-servers-overrides` flag from kube-apiserver to achieve this.

**Comment by neolit123** [comment]
> It would be great if we can reopen this issue as this kind of becomes a requirement for big/busy clusters. It can work with `--etcd-servers-overrides` flag from kube-apiserver to achieve this.

under ClusterConfiguration there is already an etcd structure where using extraArgs this can be added.
also there is etcd patch target support for individual instances.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#apiserver-flags
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches
