### ISSUE TITLE
Nothing can talk to kube-apiserver: http: TLS handshake error from 192.168.1.235:38198: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by cjbottaro** [kubernetes/kubeadm#1938]
I had a nice working cluster for a few months, then the power went out and my cluster just stopped working. There are lots of issues for "cluster doesn't work after rebooting", but nothing worked for me. So I started over.

```
# On all
kubeadm reset
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X

# On master
kubeadm init --pod-network-cidr=100.64.0.0/16

# On workers
kubeadm join 192.168.1.192:6443 ...
```

And that _still_ doesn't fix it. Basically nothing can talk to kube-apiserver because of cert issues.

```
$kubectl -n kube-system logs kube-apiserver-clawhammer
...
I1124 22:25:02.245299       1 log.go:172] http: TLS handshake error from 192.168.1.235:38198: remote error: tls: bad certificate
I1124 22:25:02.445470       1 log.go:172] http: TLS handshake error from 192.168.1.235:38200: remote error: tls: bad certificate
I1124 22:25:02.649907       1 log.go:172] http: TLS handshake error from 192.168.1.235:38202: remote error: tls: bad certificate
I1124 22:25:02.900436       1 log.go:172] http: TLS handshake error from 192.168.1.235:38204: remote error: tls: bad certificate
I1124 22:25:03.044673       1 log.go:172] http: TLS handshake error from 192.168.1.235:38206: remote error: tls: bad certificate
I1124 22:25:03.248008       1 log.go:172] http: TLS handshake error from 192.168.1.235:38210: remote error: tls: bad certificate
I1124 22:25:03.445424       1 log.go:172] http: TLS handshake error from 192.168.1.235:38212: remote error: tls: bad certificate
I1124 22:25:03.703650       1 log.go:172] http: TLS handshake error from 192.168.1.235:38214: remote error: tls: bad certificate
I1124 22:25:03.844900       1 log.go:172] http: TLS handshake error from 192.168.1.235:38216: remote error: tls: bad certificate
I1124 22:25:04.044792       1 log.go:172] http: TLS handshake error from 192.168.1.235:38220: remote error: tls: bad certificate
...
```

```
$ kubectl -n kube-system logs kube-router-arm-m6nzr
I1124 23:03:49.045988       1 kube-router.go:207] Running /usr/local/bin/kube-router version v0.3.2, built on 2019-07-25T09:01:43-0300, go1.12.7
E1124 23:04:19.052539       1 reflector.go:205] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1124 23:04:19.053137       1 reflector.go:205] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1124 23:04:19.053301       1 reflector.go:205] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.NetworkPolicy: Get https://10.96.0.1:443/apis/networking.k8s.io/v1/networkpolicies?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1124 23:04:19.053624       1 reflector.go:205] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1124 23:04:19.053981       1 reflector.go:205] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
E1124 23:04:19.053995       1 reflector.go:205] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Pod: Get https://10.96.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout
Failed to run kube-router: Failed to synchronize cache: 1m0s timeout
```

What do?

I thought kubeadm was supposed to generate all the certs via `init` and distribute them to the workers via `join`.

Thanks for the help.

**Comment by neolit123** [comment]
/triage support

> I thought kubeadm was supposed to generate all the certs via init and distribute them to the workers via join.

workers will only get the following:
- /etc/kubernetes/*-kubelet.conf - kubelet client certificate and key for contacting the kube-apiserver.
this can be either embedded or
- /etc/kubernetes/pki/ca.crt - the CA certificate of the cluster

if your cluster does not work after resetting all nodes, then something else is at play here.

> I1124 22:25:02.245299       1 log.go:172] http: TLS handshake error from 192.168.1.235:38198: remote error: tls: bad certificate

it's not clear what is trying to connect to the kube-apiserver.

> E1124 23:04:19.052539       1 reflector.go:205] github.com/cloudnativelabs/kube-router/vendor/k8s.io/client-go/informers/factory.go:73: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.96.0.1:443: i/o timeout

this is not a certificate issue but rather the `10.96.0.1:443` URL cannot be reached.
please double check what this address means in your setup.

> # On master
kubeadm init --pod-network-cidr=100.64.0.0/16

i'm sure you are also installing the kube-router manifests right after that?

> kubectl -n kube-system logs kube-router-arm-m6nzr

kubeadm doesn't have e2e test signal for ARM and we've seen weird bugs (suspecting compiler bugs), so ARM is not really something that we can claim full support for yet.

my speculation is that there are multiple issues in your case;
- api-server or kubelet certificates expired - after one year.
- you tried to recreate the cluster, but now there are networking issues.

please double check your network setup and verify that all the workers have connectivity to the api-server and that there are no firewall rules blocking the api-server ports.

**Comment by cjbottaro** [comment]
Hi, thanks for the reply. I think you pointed me in the right direction, but need a little bit more...

> this is not a certificate issue but rather the 10.96.0.1:443 URL cannot be reached.
please double check what this address means in your setup.

It seems to be the pod ip of the api server...
```
$ kubectl -n kube-system exec kube-router-arm-m6nzr env | grep KUBER
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
```

> api-server or kubelet certificates expired - after one year (yet you are saying only a few months).

But doesn't `kubeadm init` create new ones that should last another full year?

> you tried to recreate the cluster, but now there are networking issues.

So before I did `kubeadm reset` on all the nodes, I did this...
```
$ iptables -P INPUT ACCEPT
$ iptables -P FORWARD ACCEPT
$ iptables -P OUTPUT ACCEPT
$ iptables -t nat -F
$ iptables -t mangle -F
$ iptables -F
$ iptables -X

$ iptables -nvL
Chain INPUT (policy ACCEPT 16 packets, 11120 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 21 packets, 1487 bytes)
 pkts bytes target     prot opt in     out     source               destination
```

And now after creating the cluster, running `iptables -nvL` shows like:
```
iptables -nvL
Chain INPUT (policy ACCEPT 12986 packets, 5721K bytes)
 pkts bytes target     prot opt in     out     source               destination
12986 5721K KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 11993 packets, 1213K bytes)
 pkts bytes target     prot opt in     out     source               destination
11993 1213K KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain KUBE-FIREWALL (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000
```

Does that seem right? It seems that some Docker rules are missing, no?

Thanks again.

**Comment by neolit123** [comment]
> But doesn't kubeadm init create new ones that should last another full year?

kubeadm reset, then kubeadm init will re-create them.
i was talking about the reboot problem. perhaps one of the certificates was expired and rebooting cause an error.

> It seems to be the pod ip of the api server...

kube-router is not really something i have no experience with.
any reason to use it instead of say Calico or WeaveNet as the Pod Network?

did you change the version of kube-router after you ran "kubeadm init", compared to the version that was used in the old cluster?

> And now after creating the cluster, running iptables -nvL shows like:

this doesn't seem right. 
it's missing at least the Docker and CNI rules.
you can check the same command here:
https://www.katacoda.com/courses/kubernetes/playground

please note that kubeadm does not manage iptables and it's rules.
this is up to the kubelet and kube-proxy.

so if something is wrong related to iptables it's not a kubeadm bug.

**Comment by cjbottaro** [comment]
Yeah, rebooting the machines put all the Docker iptables rules back.

Still having issues with the kube-router pods not being able talk to the api server though.

Closing the issue, but still not sure where to go from here other than reinstalling the OSes on all the machines and starting from absolute scratch.

**Comment by neolit123** [comment]
> Still having issues with the kube-router pods not being able talk to the api server though.

this might as well be a kube-router problem. sadly the kubeadm team does not have the reasources to monitor if all networking solutions out there work at any given point in time with version X of k8s or kubeadm.

our e2e test signal is Calico based.

> Closing the issue, but still not sure where to go from here other than reinstalling the OSes on all the machines and starting from absolute scratch.

often times this can save time, compared to debugging the problem.
