### ISSUE TITLE
New kubeadm component config scheme

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#1940]
- Use only public component config types (remove internal types)
	- Remove defaulting and validation
	- PR: kubernetes/kubernetes#79223
- Group based code in place of kind based one
	- Errors on version mismatch
	- PR: kubernetes/kubernetes#85639
- User supplied configs vs generated ones
	- Stop storing generated core component configs into config maps
	- PR: TBD
- Tolerate newer config versions (treat them as blobs of YAML)
	- PR: TBD
- Better UX when error happens (special error type)
	- PR: TBD
- `kubeadm upgrade plan` component config table
	- PR: TBD
- Deprecate the "Kind" based `--component-configs` of `kubeadm config print *-defaults` and introduce a replacement
	- PR: TBD

Enhancements tracking issue: kubernetes/enhancements#1381
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/20190925-component-configs.md

/assign
/lifecycle active
/area ecosystem
/kind tracking-issue

**Comment by neolit123** [comment]
archiving the ticket, but soon we may need to handle additional kube-proxy v1alpha1, v1alpha2 migration logic.
we should have a plan how to handle user migrating from an old config version to a new one.
cc @SataQiu
