### ISSUE TITLE
The multinode kube cluster does not seem to run controller kubelet

### ISSUE THREAD

**Issue by naveenbn** [kubernetes/kubeadm#195]
After installing the vagrant setup on the windows host machine, the VMs are commissioned and up and running. But on the controller machine c1 the api service does not run. The systemctl status for kubelet gives below error info. The service is also not accessible locally using curl - curl http://127.0.0.1:8080

ar 06 17:19:28 c1 kubelet-wrapper[8744]: E0306 17:19:28.680982    8744 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D172.17.4.101&resourceVersion=0: dial tcp 127.0.0.1:8
Mar 06 17:19:28 c1 kubelet-wrapper[8744]: E0306 17:19:28.745188    8744 event.go:208] Unable to write event: 'Post http://127.0.0.1:8080/api/v1/namespaces/default/events: dial tcp 127.0.0.1:8080: getsockopt: connection refused' (may retry after sleeping)
Mar 06 17:19:29 c1 kubelet-wrapper[8744]: E0306 17:19:29.097608    8744 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3D172.17.4.101&resourceVersion=0: dial tcp 127.0.0.1:8080: g
Mar 06 17:19:29 c1 kubelet-wrapper[8744]: E0306 17:19:29.230738    8744 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Mar 06 17:19:29 c1 kubelet-wrapper[8744]: E0306 17:19:29.682467    8744 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D172.17.4.101&resourceVersion=0: dial tcp 127.0.0.1:8
Mar 06 17:19:30 c1 kubelet-wrapper[8744]: E0306 17:19:30.098841    8744 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3D172.17.4.101&resourceVersion=0: dial tcp 127.0.0.1:8080: g
Mar 06 17:19:30 c1 kubelet-wrapper[8744]: E0306 17:19:30.232430    8744 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Mar 06 17:19:30 c1 kubelet-wrapper[8744]: E0306 17:19:30.686898    8744 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get http://127.0.0.1:8080/api/v1/pods?fieldSelector=spec.nodeName%3D172.17.4.101&resourceVersion=0: dial tcp 127.0.0.1:8
Mar 06 17:19:31 c1 kubelet-wrapper[8744]: E0306 17:19:31.100264    8744 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get http://127.0.0.1:8080/api/v1/nodes?fieldSelector=metadata.name%3D172.17.4.101&resourceVersion=0: dial tcp 127.0.0.1:8080: g
Mar 06 17:19:31 c1 kubelet-wrapper[8744]: E0306 17:19:31.233720    8744 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
~
~

**Comment by luxas** [comment]
Not enough information provided, closing...

**Comment by luxas** [comment]
Try to reproduce with v1.6.4
