### ISSUE TITLE
clusterName is not being propagated to kube-controller-manager

### ISSUE THREAD

**Issue by angelbarrera92** [kubernetes/kubeadm#1951]
Hiii!

We have encountered an error related to the cloud provider part in `kube-controller-manager`. 

In an AWS kubernetes cluster deployed with `kubeadm`, we found that the kubeadm `clusterName` attribute is not being propagated to the `kube-controller-manager` static pod definition.

We found it in the `1.15.5` version.

This makes impossible to deploy an ELB using a service of type `LoadBalancer` because the kube controller manager can not find the correct subnets.
All the vpc, subnets and nodes (asg) contains all required tags: https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html

We are using it here: https://github.com/sighupio/fury-kubernetes-aws/blob/master/roles/kube-control-plane/templates/kubeadm.yml.j2#L21

An we expect to have the `clusterName` attribute as a `kube-controller-manager` argument without adding it as an extra-argument.

**Comment by ereslibre** [comment]
Thank you for your report @angelbarrera92.

/kind bug
/priority important-longterm
/assign
/lifecycle active

I'm not sure if we should change priority in order to backport, or if backporting is desired here since as far as I know this is the only report about this we had.
