### ISSUE TITLE
`kubeadm reset` does not delete the apiserver 

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes/kubeadm#1958]
## What keywords did you search in kubeadm issues before filing this one?

reset, 6443, (looked at issues #1145 and #339)

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.16.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.16.3
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```
Linux prd-kb-gpu02.dc2.lan 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?

Ran `kubeadm init`
Ran `kubectl drain <node name> --delete-local-data --force --ignore-daemonsets`
Ran `kubectl delete node <node name>`
Ran `kubeadm reset`

apiserver process was left over, had to manually kill it

![Screen Shot 2019-12-06 at 10 06 29 AM](https://user-images.githubusercontent.com/5788514/70333166-ff4cfb80-1810-11ea-8381-04fead85b0a2.png)

## What you expected to happen?

`kubeadm reset` deletes all the processes

**Comment by neolit123** [comment]
/triage support

@yashbhutwala resets the node, it does not delete the node Pods or the Node object itself.

**Comment by yashbhutwala** [comment]
I see, so you're saying `kubectl delete node <node name>` should have deleted all the master components, including the `apiserver`.  That makes sense to me.  But apparently, that didn't happen 🙃.  I also did `kubectl get nodes` afterwards, and the Node Object was gone.  

Maybe this is a delete node bug, or maybe I didn't wait enough after the delete node command to run kubeadm reset.  Issue relevant to this repo is I guess should `kubeadm reset` wait for all node resources to be deleted?

**Comment by neolit123** [comment]
> But apparently, that didn't happen

maybe you had another control-plane node with the control-plane components?

in any case kubeadm is not responsible for deleting nodes.
it only resets them to a NotReady state and the administrator has to use kubectl delete.
try logging the issue in kubernetes/kubernetes.

thanks.

**Comment by cuongrep** [comment]
I had `kubeadm init ...` and join 1 worker node. k8s cluster running is OK
After that, I shutdown my Master Node to move it to a new location, the Master Node IP address change. I try to run `kubeadm reset` on both Master Node and Worker Node, rerun `kubeadm init` and join Worker Node again... Then I try to run `kubectl get pods` but terminal show `Unable to connect to the server: dial tcp <last IP addess>:6443: i/o timeout`. I think that any table relevant to k8s API Server is not cleaned. How can I do in this case?

**Comment by neolit123** [comment]
try search for help on the `iptables` linux command.

**Comment by cuongrep** [comment]
> try search for help on the `iptables` linux command.

I have solved the changing master IP address problem. My k8s cluster is running OK
