### ISSUE TITLE
Full reference for kubeadm config file

### ISSUE THREAD

**Issue by TomaszKlosinski** [kubernetes/kubeadm#1960]
Where can I find full reference for the kubeadm config file?

**Comment by neolit123** [comment]
it's sufficient to google "godoc kubeadm"
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm

make sure you pick the v1beta2 or v1beta1 package for the versioned APIs

/triage support
/close

**Comment by TomaszKlosinski** [comment]
But for example here:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1

the documentation for the part that I'm interested in is missing:
```
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# kubelet specific options here
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
# kube-proxy specific options here
```
What are those specific options? Where can I find them?

**Comment by mitchellmaler** [comment]
I think it should be easier for users to find the spec of that doc without having to google godoc and figure out how to navigate it. Not all kubernetes/kubeadm operators know golang and the documentation for it. If anything these specs (godocs) for each supported version should be linked or even pulled into the kubeadm documentation even if it’s not kubeadm (kubelet, proxy, etc. spec).

**Comment by neolit123** [comment]
well, if you go to the k8s.io website and navigate to kubeadm commands such as `init` and `join` you will find references to the kubeadm API.

> What are those specific options? Where can I find them?

if one does not know about the kubelet or kubeproxy configurations then they probably don't need these specific options.

they are also linked from the kubeadm guides or can be found using google / godoc.

**Comment by TomaszKlosinski** [comment]
I know about kubelet and kubeproxy configuration. I just wasn't sure how to pass it to the kubeadm config to overwrite one of the parameters (metrics are bound to localhost by default and my Prometheus can't reach kubeproxy). Documentation either doesn't exist or is hidden in some go packages docs and the support/developers tell me that I don't know what I'm doing because I ask for clearer documentation or clarification. Is it because kubeadm --config feature is still in beta?

**Comment by neolit123** [comment]
it's documented:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#kube-proxy

**Comment by TomaszKlosinski** [comment]
Thank you, this part I was looking for:
```
    // metricsBindAddress is the IP address and port for the metrics server to serve on,
    // defaulting to 127.0.0.1:10249 (set to 0.0.0.0 for all interfaces)
    MetricsBindAddress string
```
