### ISSUE TITLE
join Master in parallel

### ISSUE THREAD

**Issue by ponypaver** [kubernetes/kubeadm#1961]
This is actually a question
My question is: 
after init the first master, is it possible to join remain masters in parallel when using an external etcd cluster?

My Kubernetes version: 1.16.3

**Comment by fabriziopandini** [comment]
@ponypaver it should be possible
It will be great if you report backs results of your test (there is no currents test for parellel join 😢 )

**Comment by neolit123** [comment]
i saw occasional failures when joining control planes in parallel.
our discussions led to https://github.com/kubernetes/kubeadm/issues/1793

**Comment by ponypaver** [comment]
> @ponypaver it should be possible
> It will be great if you report backs results of your test (there is no E2E signal for parellel join ATM , hopefully, we will get this sorted soon)

Sure will report back

**Comment by ponypaver** [comment]
I've tested parallel join master, it works

**Comment by neolit123** [comment]
From my tests it can sometimes fail. In any case we would like to support
this in the future properly. There is already an issue tracking this.

Thanks.
/close
