### ISSUE TITLE
how to edit etcd options?

### ISSUE THREAD

**Issue by Hokwang** [kubernetes/kubeadm#1973]
Hello.

Sorry for beginer's question.

**kubeadm version** 1.15.7

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.15.7
- **Cloud provider or hardware configuration**: bare-metal
- **OS** (e.g. from /etc/os-release): ubuntu

## What happened?
installed using kubeadm

I want to add `--listen-metrics-urls=http://<ip>:2379` option for etcd.

How can I do this?

I did edit /etc/kubernetes/manifests/etcd.yaml file
and then `kubectl apply -f /etc/kubernetes/manifests/etcd.yaml`
but this does not work.

Is this right way?

Many thanks,

**Comment by neolit123** [comment]
> I did edit /etc/kubernetes/manifests/etcd.yaml file
and then kubectl apply -f /etc/kubernetes/manifests/etcd.yaml
but this does not work.

once your node is deployed you only have to go to the etcd.yaml file, edit and save it.
the kubelet should pick the changes and restart the etcd instance.

> I want to add --listen-metrics-urls=http://<ip>:2379 option for etcd.

1.16 has this enabled by default, but not 1.15.
i don't think you should use port 2379 though. try a custom port.

closing as not a kubeadm bug.
/triage support
/close

**Comment by Hokwang** [comment]
I think I need to use http for easy way for prometheus.

**Comment by Hokwang** [comment]
I upgrade k8s to 1.16, it has `--listen-metric-urls` option as you said.

But it only has http://127.0.0.1:2381, so I added http:<master IP>:2381.
