### ISSUE TITLE
Services not recognized when installed via snap

### ISSUE THREAD

**Issue by adiastra** [kubernetes/kubeadm#1979]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-10T03:03:11Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-10T03:03:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
Data Center (VMWare)
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
attempted to init kubeadm to bootstrap a controller 

## What you expected to happen?
Expected that kubeadm r=would be able to recognize services installed via snap

## How to reproduce it (as minimally and precisely as possible)?
Install via snap 

core     16-2.42.5  8268   stable    canonical✓    core
core18   20191126   1279   stable    canonical✓    base
docker   18.09.9    423    stable    canonical✓    -
helm     3.0.1      156    stable    snapcrafters  classic
kubeadm  1.17.0     1397   stable    canonical✓    classic
kubectl  1.17.0     1373   stable    canonical✓    classic
kubelet  1.17.0     1355   stable    canonical✓    classic
lxd      3.18       12631  stable    canonical✓    -

Attempt to kubeadm init

## Anything else we need to know?

result 

root@sbt-linux20191~# kubeadm init --node-name master
W1218 18:34:27.030440   30483 validation.go:28] Cannot validate kubelet config - no validator is available
W1218 18:34:27.030666   30483 validation.go:28] Cannot validate kube-proxy config - no validator is available
[init] Using Kubernetes version: v1.17.0
[preflight] Running pre-flight checks
        [WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "master" could not be reached
        [WARNING Hostname]: hostname "master": lookup master on 127.0.0.53:53: server misbehaving
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Service-Docker]: docker service is not active, please run 'systemctl start docker.service'
        [ERROR Swap]: running with swap on is not supported. Please disable swap
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
root@sbt-linux20191:~#

**Comment by neolit123** [comment]
hi, the kubeadm team or official k8s as whole, do not maintain a snap package installation.
please direct your question towards the owners of the snap packages.

thank you.
/close
