### ISSUE TITLE
`kubeadm init` fails on master: node "..." not found

### ISSUE THREAD

**Issue by liupeng0518** [kubernetes/kubeadm#1983]
## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm 1.14.6
**Environment**:
- **Kubernetes version** (use `kubectl version`):
1.14.6

- **OS** (e.g. from /etc/os-release):
centos7.3

## What happened?
```
 node "..." not found
```

## Anything else we need to know?
kubespray add master or node.

**Comment by neolit123** [comment]
try opening this issue in the kubespray repository and please provide more details.
