### ISSUE TITLE
unable to run 'kubeadm init' with config file,  kubeadm version v1.17

### ISSUE THREAD

**Issue by xxinran** [kubernetes/kubeadm#1984]
## What keywords did you search in kubeadm issues before filing this one?
MasterConfiguration, kubeadm 

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:17:50Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
One VM in OpenStack cloud 
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04
- **Kernel** (e.g. `uname -a`):
Linux xinran-dev 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:
None

## What happened?
I tried to init kubeadm with my own config file as below, it seems like a version mismatch error. I am not sure which api version should I use to define a MasterConfiguration.

apiVersion: kubeadm.k8s.io/v1alpha3
kind: MasterConfiguration
controllerManagerExtraArgs:
  horizontal-pod-autoscaler-use-rest-clients: "true"
  horizontal-pod-autoscaler-sync-period: "10s"
  node-monitor-grace-period: "10s"
apiServerExtraArgs:
  runtime-config: "api/all=true"
kubernetesVersion: "stable-1.17"

## What you expected to happen?
Init kubeadm successfully.

## How to reproduce it (as minimally and precisely as possible)?
You can install the latest kubeadm and try with the config file above...

## Anything else we need to know?
No.

**Comment by neolit123** [comment]
For 1.17 use v1beta2.
This information is present in the 'kubeadm init' page of the k8s.io
website.
/triage support
/close
