### ISSUE TITLE
discovery: Invalid value: null: exactly one discovery strategy can be provided

### ISSUE THREAD

**Issue by myonlyzzy** [kubernetes/kubeadm#199]
when I apt-get install kubeadm kubectl kubelet .use kubeadm init . I get a error.

[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
[preflight] Running pre-flight checks
[init] Using Kubernetes version: v1.5.4
discovery: Invalid value: null: exactly one discovery strategy can be provided

what that mean . 
if I use kubeadm  init --discovery discovery method  .what discovery method I can use!

**Comment by luxas** [comment]
This was fixed with v1.6

**Comment by luxas** [comment]
You can simply use `--token` as the examples show
