### ISSUE TITLE
Only 1 etcd with 3 master nodes

### ISSUE THREAD

**Issue by eilmrein** [kubernetes/kubeadm#1990]
## What keywords did you search in kubeadm issues before filing this one?
join master etcd missing

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

If this is a FEATURE REQUEST, please:
  - Describe *in detail* the feature/behavior/change you'd like to see.

docker version returns
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:17:50Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
2 Debian 10 hosts with 3 Debian 10 vboxes as master nodes with 2GB, 2CPU. 2 worker nodes with 4GB and 4CPUs

- **OS** (e.g. from /etc/os-release):
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- **Kernel** (e.g. `uname -a`):
Linux n00 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
- **Others**:

## What happened?
I followed instruction on https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/ going for the stacked control plane node model. 

kubeadm init --control-plane-endpoint kubernetes01.x.y:6443 --pod-network-cidr=172.18.0.0/16 --upload-certs | tee ~/kubejoincommands.txt

I had a haproxy already set up and working when I did this

I chose the kube-router pod network add-on in in the "kube-router providing service proxy, firewall and pod networking." variant and followed the instructions on https://github.com/cloudnativelabs/kube-router/blob/master/docs/kubeadm.md to get it installed.
This brought up my first master node and everything looked good.

then I joined the second master node with the command provided by the init on another node. It seemed to work, however kubectl get cs returns
NAME                 STATUS    MESSAGE             ERROR
scheduler            Healthy   ok
controller-manager   Healthy   ok
etcd-0               Healthy   {"health":"true"}

It seems there is an etcd instance missing. How come? What are potential reasons?

## What you expected to happen?
I expected to see a new instance of etcd: etcd-1 after adding the second master node

## How to reproduce it (as minimally and precisely as possible)?
As described above

## Anything else we need to know?
all *tables alternatives set to their -legacy versions

**Comment by neolit123** [comment]
> kubectl get cs

the `get cs` command does not show all etcd members. this is not a bug in kubeadm.
as long as your etcd pods are running (`kubectl get po -A`) your etcd cluster might as well be healthy.

if you really want to make sure it works, you need to learn how to use the etcdctl command.

on the first control-plane node:

```
# find the running etcd container
$ docker ps -a | grep etcd
# execute etcdctl from the etcd container
$ docker exec -it <ETCD_CONTAINER_NAME> etcdctl --cert /etc/kubernetes/pki/etcd/peer.crt --key /etc/kubernetes/pki/etcd/peer.key --cacert /etc/kubernetes/pki/etcd/ca.crt --endpoints https://127.0.0.1:2379 member list
# should return 3 members
```

alternatively you can download etcdctl 3.4.3 (used in k8s 1.17) on your host:
https://github.com/etcd-io/etcd/releases

hope this helps.
/triage support
/close
