### ISSUE TITLE
kube flanell crashloopbackoff and kube coredns containercreating status until now 

### ISSUE THREAD

**Issue by angkoso** [kubernetes/kubeadm#1994]
please help me , when  i installation flanell plugins and coredns, i have problem 

 kubectl get pods --all-namespaces
NAMESPACE     NAME                                        READY   STATUS              RESTARTS   AGE
kube-system   coredns-6955765f44-hsp28                    0/1     ContainerCreating   0          67m
kube-system   coredns-6955765f44-shvwc                    0/1     ContainerCreating   0          67m
kube-system   etcd-kubemaster-biznet                      1/1     Running             1          67m
kube-system   kube-apiserver-kubemaster-biznet            1/1     Running             1          67m
kube-system   kube-controller-manager-kubemaster-biznet   1/1     Running             1          67m
kube-system   kube-flannel-ds-amd64-r72pn                 0/1     CrashLoopBackOff    8          21m
kube-system   kube-flannel-ds-amd64-xn6rv                 0/1     CrashLoopBackOff    8          20m
kube-system   kube-proxy-gt9gw                            1/1     Running             1          31m
kube-system   kube-proxy-zvdxr                            1/1     Running             1          67m
kube-system   kube-scheduler-kubemaster-biznet            1/1     Running             1          67m

coredns pods never stop to containercreating status 
and flanell plugins always crashloopbackoff

many thank's

**Comment by neolit123** [comment]
please try another CNI plugin like Calico or WeaveNet instead of flannel.

thanks
/close

**Comment by cheeye** [comment]
I have the same issue with kubernetes v1.17.  

Also, I see tons of messages like below in kube-proxy.. Not sure if it's "normal" when there is no working network cni in the cluster. 

```
W0108 13:17:22.902894       1 iptables.go:508] Could not set up iptables canary mangle/KUBE-PROXY-CANARY: error creating chain "KUBE-PROXY-CANARY": exit status 2: update-alternatives: error: alternative /usr/sbin/iptables-legacy for iptables not registered; not setting
E0108 13:17:23.078173       1 proxier.go:787] Failed to ensure that filter chain KUBE-EXTERNAL-SERVICES exists: error creating chain "KUBE-EXTERNAL-SERVICES": exit status 2: update-alternatives: error: alternative /usr/sbin/iptables-legacy for iptables not registered; not setting
I0108 13:17:23.078192       1 proxier.go:779] Sync failed; retrying in 30s
```

**Comment by neolit123** [comment]
i'm pretty sure Calico 3.x+ also supports s390x.

flannel is not in a good state with latest k8s.
this is something to talk about in the flannel issue tracker.

**Comment by cheeye** [comment]
@neolit123 There is no official calico docker images for s390x available although I can manually build them. 

One thing I want to confirm that the messages I saw in the kube-proxy pod are expected when there is no cni installed?  Thanks!

**Comment by neolit123** [comment]
@cheeye 

> One thing I want to confirm that the messages I saw in the kube-proxy pod are expected when there is no cni installed? Thanks!

you can try asking in the #sig-network channel of k8s slack. they are the owners of kube-proxy.

**Comment by cheeye** [comment]
@neolit123 Thank you!
