### ISSUE TITLE
Add network plugin deploy to phase addons

### ISSUE THREAD

**Issue by jenningsloy318** [kubernetes/kubeadm#1995]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

if kubeadm install network plguin as well, then a working kubernetes cluster is there, consider to  integrated with kustomize to achieve this

**Comment by neolit123** [comment]
hi, applying a network plugin is not something that kubeadm has interest to do in a phase.
however, there are plans to support an "addon installer", which users can customize to deploy any plugin they wish.

https://github.com/kubernetes-sigs/addon-operators
https://github.com/kubernetes-sigs/addon-operators/issues/10

/close
