### ISSUE TITLE
upgrades: make etcd backup consistent for single CP and HA

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#1998]
in our discussion with @fabriziopandini here:
https://github.com/kubernetes/website/pull/18424#pullrequestreview-337991999

we discussed how etcd backup differs depending if the cluster has a single or multiple stacked control-plane nodes.

ideally we want to unify the logic to always backup etcd independent of the number of CP nodes.

guide:

modify https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/staticpods.go (and _test.go if needed), so that NewKubeStaticPodPathManagerUsingTempDirs() receives `saveEtcdDir == false` only in the case of "external etcd", but not on multiple CP nodes.

/kind cleanup
/priority important-longterm

**Comment by SataQiu** [comment]
Hi @fabriziopandini @neolit123 
I found a comment about this, but it was ambiguous. https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/upgrade/apply.go#L223

**Comment by neolit123** [comment]
here are the etcd docs for this:
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md

here is the openshift guide:
https://docs.openshift.com/container-platform/3.11/admin_guide/assembly_restoring-cluster.html#restoring-etcd-v2-v3-data

it is not exactly clear to me what happens if one rolls back the local data of a single active member in a multi-node active etcd, but it makes sense to not do that reading between the lines of the above docs.

i'm not convinced that etcd will end up in a corrupted state, but it has to be tested.

for a multi node etcd the suggestion is to that:
- all etcd processes should be stopped
- all etcd members should receive the same snapshot
- all etcd processes should be restarted

**Comment by rosti** [comment]
Provided that the etcd cluster is still operational (not too many instances have died) then I do think it's relatively safe to just restore the data dir, rejoin the same cluster with its old metadata and resync its logs.

If the etcd cluster is not operational, then things become a little more complicated. That means we have to have a backup of the last leader data dir, clear the metadata and rebuild the cluster using it.

Also, bear in mind that a non-operational cluster may have more than one instance running. For example, if the etcd cluster had 10 instances, then the maximum number of instances that can be lost is (10-1)/2 = 4 (rounded down). This means that such a cluster cannot operate with 5 members running.

**Comment by neolit123** [comment]
i unblocked https://github.com/kubernetes/kubernetes/pull/86861
