### ISSUE TITLE
Whether kubeadm init supports ipv6

### ISSUE THREAD

**Issue by Forest-L** [kubernetes/kubeadm#2002]
Versions:
kubeadm verison: v1.17.0
kubectl version: v1.17.0
OS: Centos 7.7
Kernel: 3.10.0-1062.el7.x86_64

what happened?
kubeadm init --advertiseAddress 2402:e7c0:0:a00:ffff:ffff:***:***

strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta2", Kind:"InitConfiguration"}: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field APIEndpoint.localAPIEndpoint.advertiseAddress of type string
v1beta2.InitConfiguration.LocalAPIEndpoint: v1beta2.APIEndpoint.AdvertiseAddress: ReadString: expects " or n, but found [, error found in #10 byte of ...|Address":["2402:e7c0|..., bigger context ...|guration","localAPIEndpoint":{"advertiseAddress":["2402:e7c0:0:a00:ffff:ffff:***:***"],"bindPort":|...

**Comment by neolit123** [comment]
```
kubeadm init --apiserver-advertise-address 2402:e7c0:0:a00:ffff:ffff::
```

and

```
$ kubeadm init --config=config.yaml

# config.yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "2402:e7c0:0:a00:ffff:ffff::"
```

work fine.

/triage support
/close

**Comment by Forest-L** [comment]
Thanks!

**Comment by Forest-L** [comment]
K8s:v1.17.0 is ok ; Howerver,not support K8s-v1.15.3?
Version: 
kubectl: v1.15.3
kubeadm: v1.15.3

```
kubeadm init --config=kubeadm.yaml
[init] Using Kubernetes version: v1.15.3
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.3. Latest validated version: 18.09
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR HTTPProxy]: parse https://2402:e7c0:0:a00:ffff:***:***:fffb: invalid port ":fffb" after host
```
