### ISSUE TITLE
kubeadm 1.16.5 reports as v1.16.6-beta.0

### ISSUE THREAD

**Issue by k0da** [kubernetes/kubeadm#2006]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
1.16.5

**Environment**:
- **Kubernetes version** (use `kubectl version`):
1.16.5
- **Cloud provider or hardware configuration**:
OpenStack
- **OS** (e.g. from /etc/os-release):
CentOS 7.7
- **Kernel** (e.g. `uname -a`):
4.19.75-1.el7.gdc.x86_64
- **Others**:

## What happened?
kubelet, kubectl, kubeadm and API reports 1.16.6-beta.0 version installed
```
node1 Ready    master   149m    v1.16.6-beta.0
```
```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:24:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
```
kubelet --version
Kubernetes v1.16.6-beta.0
```
```
rpm -q kubelet kubeadm kubectl
kubelet-1.16.5-0.x86_64
kubeadm-1.16.5-0.x86_64
kubectl-1.16.5-0.x86_64
```

## What you expected to happen?
kubeadm 1.16.5 installs 1.16.5 master

## How to reproduce it (as minimally and precisely as possible)?
install kubeadm 1.16.5 from https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/
and run kubeadm init

**Comment by neolit123** [comment]
this is a k8s wide issue and is tracked here:
https://github.com/kubernetes/release/issues/1020

/close
