### ISSUE TITLE
Custom API server port breaks health check

### ISSUE THREAD

**Issue by sgmiller** [kubernetes/kubeadm#201]
If I specify a custom API server port (which I'm doing to work around the next issue), the health check in /etc/kuberenetes/manifests/kube-apiserver.yml doesn't respect it.  It continues to be 6443 and the apiserver flaps.

**Comment by luxas** [comment]
This is fixed at HEAD by @pipejakob: https://github.com/kubernetes/kubernetes/pull/42613#event-990098350

Thanks for reporting though, keep it up :+1:!
