### ISSUE TITLE
Clarification on version sync between installed cluster and kubeadm

### ISSUE THREAD

**Issue by nisc-acooper** [kubernetes/kubeadm#2010]
I attempted to find answers to this in the documentation and other issues but felt it was unclear.

Is the recommended practice to keep kubeadm up to date even though a cluster it maintains is older?  Example:  cluster installed at 1.13.10,  is it safe to install kubeadm 1.17 and use it to stair step through the upgrade path, or should we maintain kubeadm 1.13, upgrade to kubeadm 1.14, and then upgrade the cluster to 1.14, rinse, repeat?

Essentially, has kubeadm been designed as a tool that is backwards compatible for upgrades?

Thanks! and I apologize if this is answered somewhere already, I did attempt to find answers before reaching out

**Comment by neolit123** [comment]
> Is the recommended practice to keep kubeadm up to date even though a cluster it maintains is older? Example: cluster installed at 1.13.10, is it safe to install kubeadm 1.17 and use it to stair step through the upgrade path, or should we maintain kubeadm 1.13, upgrade to kubeadm 1.14, and then upgrade the cluster to 1.14, rinse, repeat?

this is covered in the kubeadm documentation for upgrades. here:

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

> This page explains how to upgrade a Kubernetes cluster created with kubeadm from version 1.16.x to version 1.17.x, and from version 1.17.x to 1.17.y (where y > x).

> You only can upgrade from one MINOR version to the next MINOR version, or between PATCH versions of the same MINOR. That is, you cannot skip MINOR versions when you upgrade. For example, you can upgrade from 1.y to 1.y+1, but not from 1.y to 1.y+2.

> Essentially, has kubeadm been designed as a tool that is backwards compatible for upgrades?

kubeadm version 1.y can deploy kubernetes version 1.y.* and 1.y-1.* but not older than y-1 or newer than y. if you force some preflight checks you might get it to deploy or upgrade older or newer versions, but if you see failures please note that anything outside of the version skew is not supported.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#version-skew-policy

thanks for logging the ticket. i'm going to close this, but let me know if you have more questions.
/triage support
/close
