### ISSUE TITLE
kubeadm,kubelet service fails Docker in Docker

### ISSUE THREAD

**Issue by manishalankala** [kubernetes/kubeadm#2014]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:2
7:49Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:
10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

- **Cloud provider or hardware configuration**: No
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

Docker | Details
----- | --------
docker infoContainers: 3
Running: 3
Paused: 0
Stopped: 0
Images: 10
Server Version: 18.06.3-ce
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Security Options:
 apparmor
Kernel Version: 5.0.0-37-generic
Operating System: Ubuntu 14.04.6 LTS (containerized)
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 251.5GiB
Name: sample01
ID: ABLX:TFYC:G5GH:EYGU:NB5F:NV2N:LOCQ:NHBW:DEPS:626Y:AIZZ:LLL6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false
WARNING: No swap limit support

Docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:27:13 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:25:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false

docker ps

![image](https://user-images.githubusercontent.com/33985509/73736128-93b7d980-4740-11ea-9d8c-b384c5c253d4.png)

## Anything else we need to know?

docker run -itd --privileged --name sample01 -h sample01 jpetazzo/dind:latest

sudo apt-get update

sudo apt-get install apt-transport-https ca-certificates curl software-properties-common

sudo apt-get install nano net-tools iputils-ping ssh openssh-server

sudo swapoff -a

sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

sudo echo "vm.swappiness=0" | sudo tee --append /etc/sysctl.conf

sudo sysctl -p

echo 1 > /proc/sys/vm/drop_caches

cat /etc/lsb-release

cat /etc/os-release

lsb_release -r

Kube-proxy places its iptables chains first, and then inserts two iptables rules. These rules are KUBE-EXTERNAL-SERVICES and KUBE-FIREWALL

**Docker** | **Details**
------- | -------
Client  | 18.05.0-ce
api version | 1.37
Server | 18.05.0-ce
Storage Driver | overlay2
Backing Filesystem | extfs
Cgroup Driver | cgroupfs
Operating System | Ubuntu 14.04.5 LTS (containerized)
Kernel Version | 5.0.0-37-generic
VERSION | 14.04.5 LTS, Trusty Tahr

Workernode1
|----------|

docker run -itd --privileged --name sample01 -h sample01 -v /var/run/docker.sock:/var/run/docker.sock ubuntu:14.04.5 

apt install sudo wget apt-transport-https ca-certificates curl software-properties-common

https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

sudo dpkg -i https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

sudo apt-get install -f

sudo dpkg -i https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

Docker | Details
------- | -------
Docker client | 18.05.0-ce
Docker server Engine | 18.05.0-ce
api version | 1.37

Workernode2
|----------|

docker run -itd --privileged --name sample02 -h sample02 -v /var/run/docker.sock:/var/run/docker.sock ubuntu:14.04.5 

apt install sudo wget apt-transport-https ca-certificates curl software-properties-common

https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

sudo dpkg -i https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

sudo apt-get install -f

sudo dpkg -i https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

Docker | Details
------- | -------
Docker client | 18.05.0-ce
Docker server Engine | 18.05.0-ce
api version | 1.37

docker run -itd --privileged --name sample02 -h sample02 -v /var/run/docker.sock:/var/run/docker.sock ubuntu:14.04 

apt install sudo wget apt-transport-https ca-certificates curl software-properties-common

https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

sudo dpkg -i https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

sudo apt-get install -f

sudo dpkg -i https://download.docker.com/linux/ubuntu/dists/trusty/pool/test/amd64/docker-ce_18.05.0~ce~3-0~ubuntu_amd64.deb

Docker | Details
------- | -------
Docker client | 18.05.0-ce
Docker server Engine | 18.05.0-ce
api version | 1.37

![image](https://user-images.githubusercontent.com/33985509/73734122-6ddd0580-473d-11ea-95d0-ec95fbf2a480.png)

kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:2
7:49Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
root@sample01:~# kubeadm init
W0204 09:57:21.117360    1083 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0204 09:57:21.117420    1083 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.2
[preflight] Running pre-flight checks
[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
 [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 5.0.0-37-generic
DOCKER_VERSION: 18.06.3-ce
DOCKER_GRAPH_DRIVER: overlay2
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
 [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
 [ERROR Service-Docker]: docker service is not active, please run 'systemctl start docker.service'
 [ERROR FileExisting-nsenter]: nsenter not found in system path
 [ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep(
) could not open moddep file '/lib/modules/5.0.0-37-generic/modules.dep.bin'\n", err: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

Solution : for [ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: ERROR: ../libkmod/libkmod.c:556 kmod_search_moddep(
) could not open moddep file '/lib/modules/5.0.0-37-generic/modules.dep.bin'\n", err: exit status 1

sudo apt-get update # This will update the repositories list
sudo apt-get upgrade # This will update all the necessary packages on your system
sudo apt-get dist-upgrade # This will add/remove any needed packages
sudo apt-get install linux-headers-$(uname -r)
sudo apt-get install linux-generic
apt-cache search linux-headers
reboot # You may need this since sometimes after a upgrade/dist-upgrade, there are some left over entries that get fixed after a reboot
sudo apt-get install linux-headers-4.15.0-76-generic
sudo dockerd
Error starting daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid
rm -rf /var/run/docker.pid
service docker stop/start
hence we can able to locate under /lib/modules/
if specific linux-header required as below
https://ubuntu.pkgs.org/18.04/ubuntu-updates-main-amd64/linux-headers-5.0.0-37-generic_5.0.0-37.40~18.04.1_amd64.deb.html
wget http://archive.ubuntu.com/ubuntu/pool/main/l/linux-hwe/linux-headers-5.0.0-37-generic_5.0.0-37.40~18.04.1_amd64.deb
apt install debconf cdebconf libc6
sudo apt install linux-headers-5.0.0-37
depends on below
libc6	>= 2.14
libelf1	>= 0.142
libssl1.1	>= 1.1.0 (https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libssl1.1_1.1.0g-2ubuntu4_amd64.deb.html)
apt-get -f install (if it throws any error)

service docker status is running but still
if i run kubeadm init  it fails

**Comment by neolit123** [comment]
/close
/triage support

hello, this is not a kubeadm bug, per se.
also i doubt the kubeadm maintainers  will have the time to experiment and help you with the debug.

> kubeadm,kubelet service fails Docker in Docker

kubeadm and kublet do work in DinD setups and the tool "kind" is a proof for that.
in fact i think you should use it:

https://github.com/kubernetes-sigs/kind

if you don't want to use the full tool, you can use the images it creates!
