### ISSUE TITLE
Certify kubeadm v1.17 and v1.18 as a Conformant Kubernetes deployment

### ISSUE THREAD

**Issue by stealthybox** [kubernetes/kubeadm#2017]
I attempted to do this when v1.17.0 released -- I recall I ran into ~3 test failures which surprised me.
I forgot about chasing these conformance failures through the holidays.

Last night, I ran the sonobuoy 0.17.2 suite on a v1.17.0-00 ubuntu vagrant cluster as normal and ran into 12 test failures.
I joined our [Feb5 kubeadm call](https://docs.google.com/document/d/130_kiXjG7graFNSnIAgtMS1G8zPDwpkshgfRYS0nggo/edit#heading=h.pad8pkakz5ak) and @neolit123 mentioned that many of these may be flakes.

The sentiment is that our current e2e/kube-conformance suite may be too flakey to worry about submitting conformance results at this immediate moment.

We want to resolve this by v1.18.0.
At that point, we can submit results for both v1.18 and v1.17.

Some discussion of using kinder to produce the `kubeadm` conformance results	instead of the `vagrant up` method from previous versions was mentioned to reduce memory and CPU footprint for the multi-node test.

We should still submit `kind` results separately.
@BenTheElder did you try to run v1.17.0 conformance for kind? Did you run into flakes or other issues that kept you from submitting?

_________________________________
[Vagrant reproduction example from v1.16](https://github.com/cncf/k8s-conformance/pull/723)

Failing vagrant version variables for v1.17:
```ruby
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus   = "4"
    vb.memory = "4096"
  end

  folder     = "v1.17"
  apt_docker = "18.09.7-0ubuntu1~18.04.4"
  apt_k8s    = "1.17.0-00"
  v_k8s      = "1.17.0"
  v_sonobuoy = "0.17.2"

  num_controlplane = 1 # at the moment, scripts only support 1
  num_workers      = 2
```
Failed tests:
```
Summarizing 12 Failures:

[Fail] [sig-cli] Kubectl client Guestbook application [It] should create and stop a working application  [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2315

[Fail] [sig-network] DNS [It] should provide DNS for pods for Hostname [LinuxOnly] [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:526

[Fail] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: http [LinuxOnly] [NodeConformance] [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/network/utils.go:269

[Fail] [sig-apps] ReplicationController [It] should serve a basic image on each replica with a public image  [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/rc.go:170

[Fail] [sig-cli] Kubectl client Update Demo [It] should do a rolling update of a replication controller  [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2573

[Fail] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/network/utils.go:269

[Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] listing validating webhooks should work [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:608

[Fail] [sig-network] Services [It] should be able to create a functioning NodePort service [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:599

[Fail] [sig-cli] Kubectl client Update Demo [It] should create and stop a replication controller  [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2573

[Fail] [k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook [It] should execute prestop exec hook properly [NodeConformance] [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/lifecycle_hook.go:91

[Fail] [sig-network] Networking Granular Checks: Pods [It] should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/network/utils.go:381

[Fail] [sig-network] Proxy version v1 [It] should proxy through a service and a pod  [Conformance] 
/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/proxy.go:258

Ran 278 of 4814 Specs in 8328.647 seconds
FAIL! -- 266 Passed | 12 Failed | 0 Pending | 4536 Skipped
--- FAIL: TestE2E (8328.72s)
FAIL

Ginkgo ran 1 suite in 2h18m50.670871324s
Test Suite Failed
```

**Comment by BenTheElder** [comment]
I've actually neglected submitting for a bit, but we have continuous CI results you can inspect.

**Comment by neolit123** [comment]
and the same happens for kubeadm using kinder, we have periodics jobs that test conformance, but not using sonobuoy.
maybe we can submit for 1.18.

in terms of the errors above, i don't see us even running some of these. wondering why that may be.

e.g.

> Kubectl client Guestbook application [It] should create and stop a working application  [Conformance] 

some of those are green in kinder runs though - e.g. "[sig-network] DNS should provide DNS for pods for Hostname":
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-master

**Comment by stealthybox** [comment]
I'm going to run another two tests concurrently and see if they fail on v1.17.0

**Comment by stealthybox** [comment]
[sonobuoy v0.18.0](https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.18.0) now includes `--kubernetes-version`[sonobuoy#1085](https://github.com/vmware-tanzu/sonobuoy/pull/1085) for listing dependent images.

I was able to use this to build a version of the Vagrantfile that provisions a shared base-image.
This increases the reliability of the test suite.
I was able to get 2 successful runs in 3 attempts.
My first attempt only had 1 failure.

Here are the test submissions:
https://github.com/cncf/k8s-conformance/pull/932
https://github.com/cncf/k8s-conformance/pull/933

**Comment by neolit123** [comment]
thank you @stealthybox for running the tests and send the conformance results!
i was hoping that the tests will not be very flaky.

**Comment by BenTheElder** [comment]
something to raise to the #k8s-conformance channel, they definitely have
intermittently, but it's tricky to separate from the tests vs the platform
w/o more diverse signal.

we've tried to get more results on testgrid, but little of them are real
continuous integration.

**Comment by neolit123** [comment]
looks like the cncf PRs merged.
awesome.

/close
