### ISSUE TITLE
remove bash examples/comments from the v1beta1 and v1beta2 APIs

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2018]
similar to this PR:
https://github.com/kubernetes/kubernetes/pull/84406/files

except we want to remove the example lines instead of modifying the bash.

/help
/good-first-issue
/kind documentation
/kind api-change

**Comment by SataQiu** [comment]
Now that kubernetes/kubernetes#87886 has merged, close this issue.
/close
