### ISSUE TITLE
"upgrade node": deprecate and delete --kubelet-version command line option

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#2021]
The `--kubelet-version` parameter exists in `kubeadm upgrade node` for primarily historic reasons. However, supporting it becomes more and more cumbersome. In addition to that, it bypasses the kubeadm component configs machinery, thus it may produce unexpected results (such as patching with kubeadm defaults, validation, etc.)

This option is part of a GA command line interface. Hence, the [GA command line interface deprecation policies](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli) should be used.

Marked as deprecated: kubernetes/kubernetes#87942 (Kubernetes 1.18)
Deleted: TBD (1.18 release date + 12 months or 1.20 release, whichever takes longer)

/cc @timothysc @neolit123 @fabriziopandini @ereslibre

/kind cleanup
/area UX

**Comment by neolit123** [comment]
+1

**Comment by SataQiu** [comment]
+1 Maybe I can help with this.

**Comment by rosti** [comment]
Thanks @SataQiu ! At the moment we need a PR about marking the command line option as deprecated.

**Comment by SataQiu** [comment]
> Thanks @SataQiu ! At the moment we need a PR about marking the command line option as deprecated.

OK! I'll send a PR for this soon.

**Comment by fabriziopandini** [comment]
+1 to any change that helps to have a clean separation between the upgrade story and the change the cluster story

**Comment by ereslibre** [comment]
+1 to the removal as well.

**Comment by neolit123** [comment]
removal PR:
https://github.com/kubernetes/kubernetes/pull/94869
