### ISSUE TITLE
Remove kubeadm alpha kubelet config download

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#2022]
The ```kubeadm alpha kubelet config download``` is an old alpha grade command line interface. I don't think, that it's in use by somebody, but even if it is ```kubeadm upgrade node phase kubelet-config``` is in GA and does the same thing.
Moreover these commands share only a tiny amount of code between them. Hence, ```kubeadm alpha kubelet config download``` is an ideal candidate for cleanup. It's in alpha state, so we can remove it immediately.

/cc @timothysc @neolit123 @fabriziopandini @ereslibre 
/kind cleanup
/area UX

**Comment by neolit123** [comment]
+1

**Comment by SataQiu** [comment]
+1 Maybe I can help with this.

**Comment by rosti** [comment]
Thanks @SataQiu ! That would be great!

**Comment by SataQiu** [comment]
Hi @rosti @neolit123 
I wonder if [the code](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/upgrade/node.go#L199-L202) below needs to be cleaned up, too.
If yes, I'm willing to send a PR for this.
```
// NewCmdUpgradeNodeConfig returns the cobra.Command for downloading the new/upgrading the kubelet configuration from the kubelet-config-1.X
// ConfigMap in the cluster
// TODO: to remove when 1.18 is released
func NewCmdUpgradeNodeConfig() *cobra.Command {
	nodeOptions := newNodeOptions()
	nodeRunner := workflow.NewRunner()

	cmd := &cobra.Command{
		Use:        "config",
		Short:      "Download the kubelet configuration from the cluster ConfigMap kubelet-config-1.X, where X is the minor version of the kubelet",
		Deprecated: "use \"kubeadm upgrade node\" instead",
		RunE: func(cmd *cobra.Command, args []string) error {
			// This is required for preserving the old behavior of `kubeadm upgrade node config`.
			// The new implementation exposed as a phase under `kubeadm upgrade node` infers the target
			// kubelet config version from the kubeadm-config ConfigMap
			if len(nodeOptions.kubeletVersion) == 0 {
				return errors.New("the --kubelet-version argument is required")
			}

			return nodeRunner.Run(args)
		},
	}

	// adds flags to the node command
	addUpgradeNodeFlags(cmd.Flags(), nodeOptions)

	// initialize the workflow runner with the list of phases
	nodeRunner.AppendPhase(phases.NewKubeletConfigPhase())

	// sets the data builder function, that will be used by the runner
	// both when running the entire workflow or single phases
	nodeRunner.SetDataInitializer(func(cmd *cobra.Command, args []string) (workflow.RunData, error) {
		return newNodeData(cmd, args, nodeOptions)
	})

	return cmd
}
```

**Comment by neolit123** [comment]
@SataQiu seems valid to remove the command.
the PR needs a release note explaining why - i.e. it was deprecated in 1.15.

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/upgrade/node.go#L96-L98
