### ISSUE TITLE
add workarounds for Fedora Coreos's R/O /usr/libexec/

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2031]
the flex volume flag passed to the KCM points by default to a path that is R/O on Fedora-like distros.
add a note in the troubleshooting guide about that.

`--flex-volume-plugin-dir string Default: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"`
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

https://github.com/kubernetes/kubernetes/issues/88210

> **What happened**:
> I have create a cluster on fedora coreos with kubeadm,
> but failed to join in the cluster，
> systemctl status kubelet shows:mkdir /usr/libexec/kubernetes: read-only file system
> I then tried to add KUBELET_VOLUME_PLUGIN="--volume-plugin-dir=/var/lib/kubelet/volumeplugins" to /var/lib/kubelet/kubeadm-flags.env,but still failed the same.
> 
> **What you expected to happen**:
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> always
> **Anything else we need to know?**:
> [root@localhost bin]# kubectl get nodes
> NAME STATUS ROLES AGE VERSION
> localhost Ready master 3h57m v1.17.3
> [root@localhost bin]# kubectl describe nodes localhost
> Name: localhost
> Roles: master
> Labels: beta.kubernetes.io/arch=amd64
> beta.kubernetes.io/os=linux
> kubernetes.io/arch=amd64
> kubernetes.io/hostname=localhost
> kubernetes.io/os=linux
> node-role.kubernetes.io/master=
> Annotations: kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
> volumes.kubernetes.io/controller-managed-attach-detach: true
> CreationTimestamp: Sun, 16 Feb 2020 08:21:52 +0000
> Taints: node-role.kubernetes.io/master:NoSchedule
> node.kubernetes.io/not-ready:NoSchedule
> Unschedulable: false
> Lease:
> HolderIdentity: localhost
> AcquireTime:
> RenewTime: Sun, 16 Feb 2020 12:19:12 +0000
> Conditions:
> Type Status LastHeartbeatTime LastTransitionTime Reason Message
> 
> MemoryPressure False Sun, 16 Feb 2020 12:15:13 +0000 Sun, 16 Feb 2020 08:21:48 +0000 KubeletHasSufficientMemory kubelet has sufficient memory available
> DiskPressure False Sun, 16 Feb 2020 12:15:13 +0000 Sun, 16 Feb 2020 08:21:48 +0000 KubeletHasNoDiskPressure kubelet has no disk pressure
> PIDPressure False Sun, 16 Feb 2020 12:15:13 +0000 Sun, 16 Feb 2020 08:21:48 +0000 KubeletHasSufficientPID kubelet has sufficient PID available
> Ready True Sun, 16 Feb 2020 12:15:13 +0000 Sun, 16 Feb 2020 08:22:16 +0000 KubeletReady kubelet is posting ready status
> Addresses:
> InternalIP: 192.168.122.118
> Hostname: localhost
> Capacity:
> cpu: 2
> ephemeral-storage: 15193068Ki
> hugepages-1Gi: 0
> hugepages-2Mi: 0
> memory: 2029164Ki
> pods: 110
> Allocatable:
> cpu: 2
> ephemeral-storage: 14001931446
> hugepages-1Gi: 0
> hugepages-2Mi: 0
> memory: 1926764Ki
> pods: 110
> System Info:
> Machine ID: a4c8736868564d22ae726990c239b27d
> System UUID: a4c87368-6856-4d22-ae72-6990c239b27d
> Boot ID: 15c78d5d-9f25-45c8-8d64-7b23722bd7a1
> Kernel Version: 5.4.13-201.fc31.x86_64
> OS Image: Fedora CoreOS 31.20200127.3.0
> Operating System: linux
> Architecture: amd64
> Container Runtime Version: docker://18.9.8
> Kubelet Version: v1.17.3
> Kube-Proxy Version: v1.17.3
> Non-terminated Pods: (4 in total)
> Namespace Name CPU Requests CPU Limits Memory Requests Memory Limits AGE
> 
> kube-system etcd-localhost 0 (0%) 0 (0%) 0 (0%) 0 (0%) 3h57m
> kube-system kube-apiserver-localhost 250m (12%) 0 (0%) 0 (0%) 0 (0%) 3h57m
> kube-system kube-controller-manager-localhost 200m (10%) 0 (0%) 0 (0%) 0 (0%) 3h57m
> kube-system kube-scheduler-localhost 100m (5%) 0 (0%) 0 (0%) 0 (0%) 3h57m
> Allocated resources:
> (Total limits may be over 100 percent, i.e., overcommitted.)
> Resource Requests Limits
> 
> cpu 550m (27%) 0 (0%)
> memory 0 (0%) 0 (0%)
> ephemeral-storage 0 (0%) 0 (0%)
> Events:
> 
> **Environment**:
> 
> * Kubernetes version (use `kubectl version`):
>   Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
> * Cloud provider or hardware configuration:
>   virtual machine
> * OS (e.g: `cat /etc/os-release`):
>   [root@localhost bin]# cat /etc/os-release
>   NAME=Fedora
>   VERSION="31.20200127.3.0 (CoreOS)"
>   ID=fedora
>   VERSION_ID=31
>   VERSION_CODENAME=""
>   PLATFORM_ID="platform:f31"
>   PRETTY_NAME="Fedora CoreOS 31.20200127.3.0"
>   ANSI_COLOR="0;34"
>   LOGO=fedora-logo-icon
>   CPE_NAME="cpe:/o:fedoraproject:fedora:31"
>   HOME_URL="https://getfedora.org/coreos/"
>   DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
>   SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
>   BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
>   REDHAT_BUGZILLA_PRODUCT="Fedora"
>   REDHAT_BUGZILLA_PRODUCT_VERSION=31
>   REDHAT_SUPPORT_PRODUCT="Fedora"
>   REDHAT_SUPPORT_PRODUCT_VERSION=31
>   PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
>   VARIANT="CoreOS"
>   VARIANT_ID=coreos
>   OSTREE_VERSION='31.20200127.3.0'
> * Kernel (e.g. `uname -a`):
>   5.4.13-201.fc31.x86_64
> * Install tools:kubeadm init
> * Network plugin and version (if this is a network-related bug):flannel
> * Others:
>   ● kubelet.service - kubelet: The Kubernetes Node Agent
>   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
>   Drop-In: /etc/systemd/system/kubelet.service.d
>   └─10-kubeadm.conf
>   Active: active (running) since Sun 2020-02-16 10:24:45 UTC; 1h 58min ago
>   Docs: http://kubernetes.io/docs/
>   Main PID: 66419 (kubelet)
>   Tasks: 16 (limit: 2297)
>   Memory: 32.3M
>   CGroup: /system.slice/kubelet.service
>   └─66419 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1
> 
> Feb 16 12:18:10 localhost kubelet[66419]: E0216 12:18:10.938430 66419 pod_workers.go:191] Error syncing pod 2ec8c951d5bec8c6f385c0a277bf90b1 ("kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)"), skipping: unmounted volumes=[flexvolume-dir], unattached volumes=[k8s-certs kubeconfig ca-certs etc-pki flexvolume-dir]: timed out waiting for the condition
> Feb 16 12:19:06 localhost kubelet[66419]: E0216 12:19:06.873082 66419 nestedpendingoperations.go:270] Operation for ""kubernetes.io/host-path/2ec8c951d5bec8c6f385c0a277bf90b1-flexvolume-dir" ("2ec8c951d5bec8c6f385c0a277bf90b1")" failed. No retries permitted until 2020-02-16 12:21:08.87300065 +0000 UTC m=+6983.437108662 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume "flexvolume-dir" (UniqueName: "kubernetes.io/host-path/2ec8c951d5bec8c6f385c0a277bf90b1-flexvolume-dir") pod "kube-controller-manager-localhost" (UID: "2ec8c951d5bec8c6f385c0a277bf90b1") : mkdir /usr/libexec/kubernetes: read-only file system"
> Feb 16 12:20:06 localhost kubelet[66419]: E0216 12:20:06.041189 66419 container_manager_linux.go:466] cpu and memory cgroup hierarchy not unified. cpu: /system.slice, memory: /system.slice/docker.service
> Feb 16 12:20:06 localhost kubelet[66419]: E0216 12:20:06.041352 66419 container_manager_linux.go:511] failed to find cgroups of kubelet - cpu and memory cgroup hierarchy not unified. cpu: /system.slice, memory: /system.slice/kubelet.service
> Feb 16 12:20:26 localhost kubelet[66419]: E0216 12:20:26.935662 66419 kubelet.go:1680] Unable to attach or mount volumes for pod "kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)": unmounted volumes=[flexvolume-dir], unattached volumes=[etc-pki flexvolume-dir k8s-certs kubeconfig ca-certs]: timed out waiting for the condition; skipping pod
> Feb 16 12:20:26 localhost kubelet[66419]: E0216 12:20:26.937434 66419 pod_workers.go:191] Error syncing pod 2ec8c951d5bec8c6f385c0a277bf90b1 ("kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)"), skipping: unmounted volumes=[flexvolume-dir], unattached volumes=[etc-pki flexvolume-dir k8s-certs kubeconfig ca-certs]: timed out waiting for the condition
> Feb 16 12:21:08 localhost kubelet[66419]: E0216 12:21:08.880187 66419 nestedpendingoperations.go:270] Operation for ""kubernetes.io/host-path/2ec8c951d5bec8c6f385c0a277bf90b1-flexvolume-dir" ("2ec8c951d5bec8c6f385c0a277bf90b1")" failed. No retries permitted until 2020-02-16 12:23:10.880040391 +0000 UTC m=+7105.444148405 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume "flexvolume-dir" (UniqueName: "kubernetes.io/host-path/2ec8c951d5bec8c6f385c0a277bf90b1-flexvolume-dir") pod "kube-controller-manager-localhost" (UID: "2ec8c951d5bec8c6f385c0a277bf90b1") : mkdir /usr/libexec/kubernetes: read-only file system"
> Feb 16 12:22:43 localhost kubelet[66419]: E0216 12:22:43.935055 66419 kubelet.go:1680] Unable to attach or mount volumes for pod "kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)": unmounted volumes=[flexvolume-dir], unattached volumes=[kubeconfig ca-certs etc-pki flexvolume-dir k8s-certs]: timed out waiting for the condition; skipping pod
> Feb 16 12:22:43 localhost kubelet[66419]: E0216 12:22:43.935210 66419 pod_workers.go:191] Error syncing pod 2ec8c951d5bec8c6f385c0a277bf90b1 ("kube-controller-manager-localhost_kube-system(2ec8c951d5bec8c6f385c0a277bf90b1)"), skipping: unmounted volumes=[flexvolume-dir], unattached volumes=[kubeconfig ca-certs etc-pki flexvolume-dir k8s-certs]: timed out waiting for the condition

also see;
https://kubernetes.slack.com/archives/C2P1JHS2E/p1581437670219100

/kind documentation
/priority important-longterm
/assign

**Comment by neolit123** [comment]
@skycastlelily2 a known workaround is to do the following.

pass the following configuration file as a `--config` to `kubeadm init`:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
```

and the following file as `--config` to `kubeadm join`:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
```

let me know if this works for you.

mind that if you cannot mix `--config` and some other flags.
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

**Comment by skycastlelily2** [comment]
Hi,
Really thanks for your reply and help.
How could I set --token  and --discovery-token-ca-cert-hash in the join  config file?
I try the following:
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
bootstrapTokens:
- token: "bv2lok.bld9lvp7300dbjtn"
  description: "kubeadm bootstrap token"
  ttl: "24h"
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"

but failed:
[root@localhost ~]# kubeadm join --config join.yaml 
W0217 04:48:49.254349   16508 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
W0217 04:48:49.255021   16508 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta2", Kind:"JoinConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "bootstrapTokens"
discovery: Invalid value: "": bootstrapToken or file must be set
To see the stack trace of this error execute with --v=5 or higher

then I try to put bootstrapTokens under InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- token: "bv2lok.bld9lvp7300dbjtn"
  description: "kubeadm bootstrap token"
  ttl: "24h"

still failed:
[root@localhost ~]# kubeadm join --config join.yaml 
W0217 04:52:09.446651   17735 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
discovery: Invalid value: "": bootstrapToken or file must be set
To see the stack trace of this error execute with --v=5 or higher

Btw,I must missed something,there is no kubeadm.k8s.io/v1beta2 apiVersion

[root@dell-pem905-01 lnie]# kubectl api-versions
admissionregistration.k8s.io/v1
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
discovery.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1

**Comment by neolit123** [comment]
try:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- token: "<some-token>"
  description: "kubeadm bootstrap token"
  ttl: "24h"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: "<ip>:<port>"
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
```

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "<some-token>"
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
```

**Comment by skycastlelily2** [comment]
Hi,  I get  the following error with your demo
`error unmarshaling JSON: while decoding JSON: json: unknown field "nodeRegistration"` 
 I created the cluster successfully after moved the following to kind: InitConfiguration 
`nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"`

The created cluster can be joined  with 
`kubeadm join 192.168.122.118:6443 --token bv2lok.bld9lvp7300dbjtn --discovery-token-ca-cert-hash sha256:3ec93f29321c1b339c7f5836e32b5959af888e91e448321ccc037e54224ac28e `

with your joinconfiguration demo,I still get
`discovery: Invalid value: "": bootstrapToken or file must be set`
Is it a  bug?

**Comment by skycastlelily2** [comment]
Hi, this is a bug only affects Fedora Coreos ,Fedora Server and  Fedora Workstation are fine, I tried to modified your comment at the head of this page,but deleted my comments by mistake,sigh...
With your demo I get "json: unknown field "nodeRegistration"" error,
I create the cluster successfully after moved the following bellow kind:InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"

The created cluster can be joined successfully with 
kubeadm join 192.168.122.118:6443 --token bv2lok.bld9lvp7300dbjtn --discovery-token-ca-cert-hash sha256:3ec93f29321c1b339c7f5836e32b5959af888e91e448321ccc037e54224ac28e

with your demo,I still get "discovery: Invalid value: "": bootstrapToken or file must be set"
Is it a bug?

**Comment by skycastlelily2** [comment]
Hi, this is a bug only affects Fedora Coreos ,Fedora Server and Fedora Workstation are fine:)

**Comment by neolit123** [comment]
> Hi, I get the following error with your demo
error unmarshaling JSON: while decoding JSON: json: unknown field "nodeRegistration"

updated my response here:
https://github.com/kubernetes/kubeadm/issues/2031#issuecomment-586823530

> with your joinconfiguration demo,I still get
discovery: Invalid value: "": bootstrapToken or file must be set
Is it a bug?

i don't think so. try again using the above config:

also the join command should look like:
```
kubeadm join 192.168.122.118:6443 --config <the-JoinConfiguration-file>
```

**Comment by neolit123** [comment]
you can also share your config files here, for me to check them.

**Comment by neolit123** [comment]
> Hi, this is a bug only affects Fedora Coreos ,Fedora Server and Fedora Workstation are fine:)

it's not a bug, per se. only a problem if the distro decided to lock /usr.

you have to configure the flex volume path to a path that is writeable. kubeadm allows you to do that using the configuration.

**Comment by skycastlelily2** [comment]
Hi,below is init config I use,and I  joined the cluster without config file yesterday:
kubeadm join 192.168.122.118:6443 --token bv2lok.bld9lvp7300dbjtn --discovery-token-ca-cert-hash sha256:3ec93f29321c1b339c7f5836e32b5959af888e91e448321ccc037e54224ac28e 
now I know this way is not suggested.

apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"
    cgroup-driver: systemd
bootstrapTokens:
- token: "bv2lok.bld9lvp7300dbjtn"
  description: "kubeadm bootstrap token"
  ttl: "24h"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: "192.168.122.118:6443"
controllerManager:
  extraArgs:
    flex-volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"

here is the join config I use to join the cluster successfully, we need add the apiServerEndpoint line,
or an error will be printed:
"APIServerEndpoint is not set, discovery.bootstrapToken.apiServerEndpoint: Invalid value: "": missing port in address"

apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "bv2lok.bld9lvp7300dbjtn"
    caCertHashes:
    - "sha256:9d10ddb58734ec22d4082ed094a21d0881ec3a040ab0534170ab7a0250a7955c"
    apiServerEndpoint: "192.168.122.118:6443"
nodeRegistration:
  kubeletExtraArgs:
    volume-plugin-dir: "/opt/libexec/kubernetes/kubelet-plugins/volume/exec/"

sorry for having not put an exact word,the word I wanted to say is issue.

**Comment by neolit123** [comment]
if you have the above JoinConfiguration, you should just use:
```
kubeadm join 192.168.122.118:6443 --config=<join-config-file>
```

what errors are you getting?

**Comment by skycastlelily2** [comment]
I can join the cluster successfully with the join config above,there are no errors.
I failed to join the cluster with yesterday's join config, so I joined the cluster without specified a config file yesterday. Sorry for have not said it clearly.

**Comment by neolit123** [comment]
thank you for clarifying. i will add notes to our Troubleshooting guide about this.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

**Comment by rosti** [comment]
@skycastlelily2 just to clarify, is this Fedora CoreOS or Fedora Server?
It's important, because these two are distinctively different.

**Comment by neolit123** [comment]
> Hi, this is a bug only affects Fedora Coreos ,Fedora Server and Fedora Workstation are fine:)

**Comment by neolit123** [comment]
/close 
website pr merged.
