### ISSUE TITLE
fallback to a known etcd version if an unknown k8s version is passed

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2034]
during etcd upgrade kubeadm can fail with:
> unsupported or unknown Kubernetes version(1.19.0-alpha.0)

this can happen if a k8s version is passed that kubeadm still does not know about.
the errors originates for a map check, where a k8s version is mapped to an etcd version.

a desired fix here is convert this into a warning and fallback to the last known etcd version.
e.g. if k8s version is 1.19, but there is no etcd mapping for this version use the etcd version for 1.18.

example of the failure:
https://github.com/kubernetes/kubernetes/issues/88336

**Comment by SataQiu** [comment]
/assign
I'd like to have a try :)
