### ISSUE TITLE
Kubelet is not running or not healthy

### ISSUE THREAD

**Issue by gunalanbalakrishnan** [kubernetes/kubeadm#2040]
## What keywords did you search in kubeadm issues before filing this one?
Kubelet
If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?
Kind of bug
Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:17:50Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Virtual Machines from VMware
- **OS** (e.g. from /etc/os-release):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- **Kernel** (e.g. `uname -a`): 
Linux XXYYZZ.com 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
Kubelet is not running or not healthy unable to init the master node

## What you expected to happen?

sudo kubeadm init --config=config.yaml

Above command should work with out any issue

## How to reproduce it (as minimally and precisely as possible)?

sudo kubeadm init --config=config.yaml should initiate the master services.

## Anything else we need to know?
# journalctl -xeu kubelet
 F0226 08:28:55.868536   19203 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml,
Feb 26 08:28:55 XXYYZZ systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Feb 26 08:28:55 XXYYZZ  systemd[1]: Unit kubelet.service entered failed state.
Feb 26 08:28:55 XXYYZZ  systemd[1]: kubelet.service failed.

**Comment by neolit123** [comment]
hi,

> F0226 08:28:55.868536 19203 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml,

please note that once you install the kubelet and kubeadm packages on a node, the kubelet will fail (crash-loop), until you start `kubeadm init`.

this issue tracker is for logging bugs and feature requests.
try asking in the #kubeadm channel on k8s slack or our forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by gunalanbalakrishnan** [comment]
This issue came after i started the  # kubeadm init using the below command.

sudo kubeadm init --config=config.yaml

Please advice me for further troubleshooting.

**Comment by gunalanbalakrishnan** [comment]
> @neolit123: Closing this issue.

This issue came after i started the kubeadm using below command,

sudo kubeadm init --config=config.yaml

Please help me for further troubleshooting...

**Comment by neolit123** [comment]
the only reason for this to happen is if `kubeadm init` exited with an error.

> F0226 08:28:55.868536 19203 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml,
