### ISSUE TITLE
Applying a daemonset to thousands of controllers

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubeadm#2042]
Request for info:

**Goal:** To manage 50K to 100K nodes using kubernetes for applying daemonsets

A possibility:
- To manage this scale, we need around 5K to 10K of controllers/masters.

- Nodes can add labels that describe self as static & dynamic data
  Static data: e.g. clustername, platform, HWSKU, ...
  Dynamic Data: e.g. Status, ...

- Apply daemonset with appropriate node-selectors at a central place - May be a cloud file storage

-  The master nodes, are configured with cloud storage path & credentials required to access daemonset manifests

- Master nodes watch storage for updates, apply updated manifests locally.

**Questions:**

1. Is the above feasible today ?
2. Is there a better way to handle this ?

**Related questions**:
a. When a master nodes encounter failure in applying a manifest, does it provide any hook for registering a custom script ?
   For example, the custom script can take some action, like log a message, raise an alert, ...

b. When managing thousands of controllers & nodes, is there any inherent support or suggestion for a dash-board feasibility to reflect the current status of nodes w.r.t deployments/daemonsets/...

Thank you!

**Comment by neolit123** [comment]
hi, please re-open this in the core kubernetes repository (kubernetes/kubernetes) for a more detailed answer. you can also ask in the #sig-scalability channel on slack.

this is the kubeadm issue tracker which is specific for kubeadm bugs and features as a deployer of k8s.

my short answer to your questions is "maybe". newer versions of etcd scale pretty well with big clusters, but you might see performance issues, as 50k nodes is a lot.

you are better of creating separate small-scoped clusters.

**Comment by renukamanavalan** [comment]
Thank you!
