### ISSUE TITLE
Coredns crashes with api timeout on 443 

### ISSUE THREAD

**Issue by Venkatsai** [kubernetes/kubeadm#2049]
## Versions

**kubeadm version** (use `kubeadm version`): v1.17.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.17.3
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Linux
- **Kernel** (e.g. `uname -a`): Linux k8master 4.14.165-131.185.amzn2.x86_64
- **Others**: Considered Kubeadm to initialize Master. Applied Flannel networking once the cluster is Up.

## What happened?

The existing ticket 1463 addressed the about the coredns crash due to the API timeout is resolved in 1.15 version. It isn't the case with 1.17 version. The issue still exists which causes the PODS associated with coredns are stuck in CrashLoopBackOff state. The state would be in Running after a while.

## What you expected to happen?

The state of the PODS associated with CoreDNS should in running rather than in CrashLoopBackOff

## How to reproduce it (as minimally and precisely as possible)?

Unfortunately, the state swaps to CrashLoopBackOff. Unable to reproduce the error.

**Comment by neolit123** [comment]
hi, i'm not convinced this is a kubeadm bug, but rather either a CoreDNS issue or an issue with your networking setup.

please provide:
- all the flags or --config you use to configure kubeadm
- provide logs from the kubelet and the crashing coredns pods

> Applied Flannel networking once the cluster is Up.

please try Calico as your CNI plugin, Flannel is not in a good shape and is trailing behind k8s in some regards.

cc @rajansandeep 
/triage support

**Comment by neolit123** [comment]
make sure you clean the relevant existing configuration from `/etc/cni/net.d` before trying new CNI plugins.

**Comment by neolit123** [comment]
/close 

if this is coredns related try logging an issue in the coredns repository.
if core kubernetes related you can log an issue in kubernetes/kubernetes.

for general support questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by Venkatsai** [comment]
Thank you Neo
