### ISSUE TITLE
Latest kubeadm package in yum.kubernetes.io is not signed

### ISSUE THREAD

**Issue by rmohr** [kubernetes/kubeadm#205]
## Versions

- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core) 

## What happened?

Kubeadm in `yum.kubernetes.io` seems to be not signed. Since last week we see

```
Package ed1cdb328f2ee2cd2c9a200f3a3ae549801cd51216ef82e37d2b92acdbd72cf5-kubectl-1.5.4-0.x86_64.rpm is not signed
```

## How to reproduce it (as minimally and precisely as possible)?

First add the repo:

```bash
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
```

Then try to install the packages:

```bash
yum install -y docker kubelet kubeadm kubectl kubernetes-cni
```
You will get

```
Package ed1cdb328f2ee2cd2c9a200f3a3ae549801cd51216ef82e37d2b92acdbd72cf5-kubectl-1.5.4-0.x86_64.rpm is not signed
```

With `--nogpgcheck` it works.

**Comment by mikedanese** [comment]
Hi, sorry about this. I just pushed new rpms. Can you confirm the fix?

**Comment by rmohr** [comment]
Works perfect. Thanks for fixing this so fast :+1:
