### ISSUE TITLE
Ability to run kubeadm init in container

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubeadm#2057]
**Request for help:**

Per site on [installing kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/), of the required list, a container is a possibility.
<copy/paste>: "_Container Linux (tested with 1800.6.0)_"

As I am not sure, how to get container image, for the stated version, I tried 'ubuntu:latest'.

It  fails with spew below

```
root@remanava-kube-1:/system# kubeadm init --pod-network-cidr=192.168.0.0/16 
W0308 19:14:41.202999    4831 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0308 19:14:41.203044    4831 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.3
[preflight] Running pre-flight checks
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH
        [WARNING Firewalld]: no supported init system detected, skipping checking for services
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 5.0.0-1028-azure
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
        [WARNING Service-Kubelet]: no supported init system detected, skipping checking for services
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/5.0.0-1028-azure/modules.dep.bin'\nmodprobe: FATAL: Module configs not found in directory /lib/modules/5.0.0-1028-azure\n", err: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```

**Questions:**

1. Can you please tell me, which container image I could use to be able to run kubernetes control plane inside the container ?
2. Is there any special options do I pass to kubernetes, as there will not be any docker installed inside the container ?

This would be of a ***big*** help as this lets me run the master in any host, irrespective of the host OS, as long as it can run a linux container.

THANK YOU in advance!
--Renuka

**Comment by neolit123** [comment]
> Per site on installing kubeadm, of the required list, a container is a possibility.
<copy/paste>: "Container Linux (tested with 1800.6.0)"

the documentation stating that Container Linux is supported, does not necessarily mean that running `kubeadm init` from within a container is supported by the kubeadm team. it requires a number of changes to any base image that is used. i suggest you look at the [kind](https://github.com/kubernetes-sigs/kind) project which does exactly that - creates a local k8s cluster using kubeadm where the k8s nodes are containers.

it's support channel is #kind on the k8s slack.

> Can you please tell me, which container image I could use to be able to run kubernetes control plane inside the container ?
> Is there any special options do I pass to kubernetes, as there will not be any docker installed inside the container ?

the container image must have a Container Runtime (e.g. docker) and systemd installed as the bare minimum. from there the host <-> container networking has to be setup properly.

/close
/triage support
