### ISSUE TITLE
revist support for custom image tags (e.g. for etcd)

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2058]
currently we are facing some issues around custom image tags.

problems to solve:
- [ ] the GCR image for etcd will now always include a revision - e.g. `-0`, `-1`. we need to support upgrades between revisions, currently kubeadm fetches a version from the running etcd cluster and it aborts upgrade even if the revision of the original version was older.

- [ ] handle upgrade of arbitrary image tags. `myimage:tag-0-company-name` how?

- [ ] respect the etcd image tag that the user provides in --config (ClusterConfiguration) during upgrade. PR by @ereslibre is [here](https://github.com/kubernetes/kubernetes/pull/88845).

/assign @rosti @ereslibre 
cc @fabriziopandini

**Comment by fabriziopandini** [comment]
> handle upgrade of arbitrary image tags. myimage:tag-0-company-name how?

I'm leaning toward extending our ImageMeta struct with a new ImageSuffix field.
The main difference between ImageTag and ImageSuffix is that the first is replacing the kubeadm generated tag, and this has side effects like e.g. blocking for upgrades.
Images, suffix instead is going to simply amend kubeadm generated tags, and so upgrades will just works.
The tricky part here is to implement a library for handling the image string and all the relate operation (parse, apply imageTags, comparison etc.)

**Comment by neolit123** [comment]
for the time being, my idea is in the lines of the following:
- apply some non-strict requirements of how the user tags for (e.g) etcd are formatted. allowed formats:
  - `semver` (default, no metadata)
  - `semver-revision` (with metadata revision maintained by k8s)
  - `semver-vendor.revision` (with vendor metadata, revisions maintained by vendor)
- if the user feeds a tag that does not comply with the above, show a warning
- during upgrades if the new version coming from the kubeadm binary is newer `semver` compared to the user `semver` consider an etcd upgrade.
  - if there is vendor metadata preserve it, reset vendor revision to 0.
  - if there is no vendor reset the k8s revision to 0.
  - expect the image to exist.
- if the `semvers` are equal:
  - if using k8s revisions apply upgrade (e.g. `-0` -> `-1`)
  - if there is vendor metadata do nothing (e.g. do not auto increment vendor revisions)
- if the new `semver` is older don't upgrade

**Comment by fabriziopandini** [comment]
it seems a little bit tangled to me. 
what about considering what is after - a prerelease version and simply use alphabetical order when doing comparison as per https://semver.org/#spec-item-9

**Comment by neolit123** [comment]
we can do alpha-numeric comparison for k8s revisions:
`etcd:v3.4.4-0` -> `etcd:v3.4.4-1` would be a valid upgrade. as the string comparison passes `"-1" >"-0"`

how about if the current image is `etcd:v3.4.4-vendor.3` and kubeadm wants to upgrade to `etcd:v3.4.5-0` which is hardcoded in the binary? i think the right thing to do is to upgrade to `etcd:v3.4.5-vendor.0`
