### ISSUE TITLE
FR: creation of virtual IP, load balancing for kube-apiserver

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2059]
@mbert has created a google document with a proposal of handling VIP / LB from kubeadm:
https://docs.google.com/document/d/153G2DoZiIPyPInc6tgayBEnVti3KW3X75GXWi-9COeo/edit?usp=sharing

this issue is to track the progress and potential KEP transition if we agree on the initial proposal.

**Comment by fabriziopandini** [comment]
xposting here from google doc comments:
I think it is important to scope down this work of this work WRT to the kubeadm design principles:
1. kubeadm should remain agnostic to LB solutions
2. kubeadm should remain focuses on doing node bootstrap

This work is about exploring another alternative for HA deployments without the need for additional machines external LB, and to identify required changes in kubeadm/kubeadm documentation to make this option available to kubeadm users

**Comment by neolit123** [comment]
/kind documentation
related to:
https://github.com/kubernetes/kubeadm/issues/1685
(^ but this is mostly about cloud provider LBs)

**Comment by fabriziopandini** [comment]
Key points to be addressed are:
- how to make the VIP solution works well on the init/join workflow
- to define the lifecycle of the VIP solution (upgrades, but also changes to control plane)
- how to make ^^ generic enough to be LB agnostic
- how to implement in kubeadm extension points/hooks to trigger ^^

Given the fact those points are complex and require more design, I'm +1 to adopt an incremental approach by first documenting @mbert solution as an alpha solution, being transparent on known limitations and iterate on it according to user feedbacks

**Comment by neolit123** [comment]
the doc PR has merged.
let's gather feedback in dedicated issues / topics.
/close
