### ISSUE TITLE
Cann't curl service using clusterIP of nodeIP

### ISSUE THREAD

**Issue by deshui123** [kubernetes/kubeadm#2064]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):
[root@henry-dual-cs-01 ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:12:12Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
```
[root@henry-dual-cs-01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
## What happened?
Using kubeadm to setup cluster on openstack for IPv4,
kube-proxy mode is **ipvs**
CNI is **calico**.

Pods and service are running, but when what to curl service in one pod, get **Connection refused**
I tried using clusterIP or nodeIP, both failed with the same error
## What you expected to happen?
can access service within pod
## How to reproduce it (as minimally and precisely as possible)?

I refer to guide https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ and https://kubernetes.io/docs/concepts/services-networking/dual-stack/
The CNI is calico.

## Anything else we need to know?
```
[root@henry-dual-cs-01 ~]# kubectl get po -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP               NODE               NOMINATED NODE   READINESS GATES
cinfo-744f4547f-9gjsr   1/1     Running   0          99m   192.168.212.68   henry-dual-cs-02   <none>           <none>
cinfo-744f4547f-k6mvf   1/1     Running   0          99m   192.168.212.69   henry-dual-cs-02   <none>           <none>
curl-69c656fd45-p9brb   1/1     Running   0          78m   192.168.212.70   henry-dual-cs-02   <none>           <none>

[root@henry-dual-cs-01 ~]# kubectl get svc -o wide
NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE    SELECTOR
kubernetes           ClusterIP   10.253.0.1     <none>        443/TCP        166m   <none>
my-service-default   NodePort    10.253.10.64   <none>        80:30008/TCP   16m    app=cinfo

[root@henry-dual-cs-01 ~]#
[root@henry-dual-cs-01 ~]# kubectl get ep -o wide
NAME                 ENDPOINTS                                 AGE
kubernetes           192.16.1.10:6443                          166m
my-service-default   192.168.212.68:9376,192.168.212.69:9376   16m
```

```
[ root@curl-69c656fd45-p9brb:/ ]$ curl -vvv 192.16.1.10:30008
* Failed to connect to 192.16.1.10 port 30008: Connection refused
curl: (7) Failed to connect to 192.16.1.10 port 30008: Connection refused

[ root@curl-69c656fd45-p9brb:/ ]$ curl 192.168.212.68:9376
curl: (7) Failed to connect to 192.168.212.68 port 9376: Connection refused
[ root@curl-69c656fd45-p9brb:/ ]$ curl 10.253.71.121:80
curl: (7) Failed to connect to 10.253.71.121 port 80: Connection refused
```

```
[root@henry-dual-cs-01 ~]# kubectl logs -f -n kube-system   coredns-6955765f44-dwbs6
.:53
[INFO] plugin/reload: Running configuration MD5 = 4e235fcc3696966e76816bcd9034ebc7
CoreDNS-1.6.5
linux/amd64, go1.13.4, c2fd1b2
E0318 08:58:44.651506       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to watch *v1.Endpoints: Get https://10.253.0.1:443/api/v1/endpoints?resourceVersion=23348&timeout=9m15s&timeoutSeconds=555&watch=true: dial tcp 10.253.0.1:443: connect: connection refused
E0318 08:58:44.651506       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to watch *v1.Endpoints: Get https://10.253.0.1:443/api/v1/endpoints?resourceVersion=23348&timeout=9m15s&timeoutSeconds=555&watch=true: dial tcp 10.253.0.1:443: connect: connection refused
```

**Comment by neolit123** [comment]
hi, please use the support channels for questions like this:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

> kube-proxy mode is ipvs

if you find a bug with kube-proxy / IPVS, please log a ticket in kubernetes/kubernetes and tag it with `/sig network`

> CNI is calico.

if you find a bug with Calico log an issue in their repository.

thanks

**Comment by deshui123** [comment]
I don't think this is kubernetes issue.
all kubernetes parameters are from kubeadm.yaml
If there is wrong configuration, need to modify kubeadm.yaml. That's why I  open this ticket.

**Comment by neolit123** [comment]
that is why we have the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

also #kubeadm on k8s slack.

if there is clear evidence for a kubeadm bug we can log a ticket here.
