### ISSUE TITLE
kubelet cgroup driver: "systemd" is different from docker cgroup driver error

### ISSUE THREAD

**Issue by artisticcheese** [kubernetes/kubeadm#2066]
## What keywords did you search in kubeadm issues before filing this one?

 failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker 

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):
1.17.3
**Environment**:
- **Kubernetes version** (use `kubectl version`):
1.17.3
- **Cloud provider or hardware configuration**:
On prem Hyper-V
- **OS** (e.g. from /etc/os-release):
VERSION="18.04.4 LTS (Bionic Beaver)"
- **Kernel** (e.g. `uname -a`):
Linux master1 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?

Installed cluster via kubeadm and everything worked after untill reboot. Now kubelet will not start with relevant error below. Docker config file showing driver set as systemd yet docker info shows as "cgroups"

Mar 19 00:49:31 master1 kubelet[6599]: F0319 00:49:31.254570    6599 server.go:273] failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver

```
root@master1:~# cat /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}

```
## How to reproduce it (as minimally and precisely as possible)?
Not 100% sure. All I did install cluster via kubeadm and rebooted

**Comment by neolit123** [comment]
hi, this is something we get often.
but until now we have not confirmed a kubeadm bug.

- the kubelet has a default cgroup driver of `cgroupfs` if your docker driver is different and if you are not passing `--cgroup-driver=<yourdockerdriver>` to the kubelet it will fail.
- that is why, when `kubeadm join` or `init` are called they run `docker info` and look at your docker cgroup driver. then write the result as a flag in the dynamic file `/var/lib/kubelet/kubeadm-flags.env`.

please answer the following Qs:
- did you re-install docker or modify the file `/etc/docker/daemon.json` between restarts?
- what are the contents of  `/var/lib/kubelet/kubeadm-flags.env`?
- what is the output of `docker info -f "{{.CgroupDriver}}`?

/triage needs-information

**Comment by artisticcheese** [comment]
When I reboot machine docker starts with `Cgroup Driver: cgroupfs`, once I issue restart `service docker restart` it actually switches to systemd. I did not modify `daemon.json` between restarts.
Contents of kubelet config is `KUBELET_KUBEADM_ARGS="--cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --resolv-conf=/run/systemd/resolve/resolv.conf"
`

**Comment by neolit123** [comment]
> When I reboot machine docker starts with Cgroup Driver: cgroupfs, once I issue restart service docker restart it actually switches to systemd

this seems like an issue with the docker service? i have no explanation of why this happens, but this is not a kubeadm or kubernetes bug. try searching online for a solution.

in any case, the [recommend cgroup driver](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers) from the kubeadm maintainers is `systemd`, that is if you running the kubelet using the systemd init system.

i'd suggest attempting to resolve the docker service issue and letting the driver always be `systemd`.

thanks
/close

**Comment by abobakrahmed** [comment]
I've same issue with ubuntu 20.04
