### ISSUE TITLE
kubeadm upgrade plan failed with kubeadm-config not found  v1.17.3 to v1.17.4

### ISSUE THREAD

**Issue by sarath4** [kubernetes/kubeadm#2067]
[root@master ~]# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade/config] FATAL: failed to get config map: configmaps "kubeadm-config" not found
To see the stack trace of this error execute with --v=5 or higher
[root@master ~]#

**Comment by SataQiu** [comment]
I tested it on CentOS and it looks fine.
```sh
[root@CentOS ~]# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.17.3
[upgrade/versions] kubeadm version: v1.17.3
[upgrade/versions] Latest stable version: v1.17.4
[upgrade/versions] Latest version in the v1.17 series: v1.17.4

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT       AVAILABLE
Kubelet     1 x v1.17.3   v1.17.4

Upgrade to the latest version in the v1.17 series:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.17.3   v1.17.4
Controller Manager   v1.17.3   v1.17.4
Scheduler            v1.17.3   v1.17.4
Kube Proxy           v1.17.3   v1.17.4
CoreDNS              1.6.5     1.6.5
Etcd                 3.4.3     3.4.3-0

You can now apply the upgrade by executing the following command:

	kubeadm upgrade apply v1.17.4

Note: Before you can perform this upgrade, you have to update kubeadm to v1.17.4.

_____________________________________________________________________
```

**Comment by neolit123** [comment]
/triage needs-information

> [upgrade/config] FATAL: failed to get config map: configmaps "kubeadm-config" not found

if `kubectl -n kube-system get cm kubeadm-config -oyaml` also returns that the ConfigMap is missing it must be a problem with your cluster. there is no process in kubeadm that deletes this ConfigMap and it is managed for the lifespan of the cluster; something must have deleted it.

**Comment by neolit123** [comment]
please provide more detail if needed.
