### ISSUE TITLE
CreateServiceAccounts: Should not exit on first error

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubeadm#207]
CreateServiceAccounts tries to create 2 service accounts, but exits on the first error.  If we fail to create the second service account due to a transient error, or if the first service account already exists, then retries will always fail.

**Comment by luxas** [comment]
Same as https://github.com/kubernetes/kubeadm/issues/208#issuecomment-304671012

**Comment by pipejakob** [comment]
I believe this was fixed as part of https://github.com/kubernetes/kubernetes/pull/46875, as the code now ignores AlreadyExists errors. Are there other errors you would expect to either be ignored or automatically retried, or is it enough to redrive from the caller now that we ignore AlreadyExists?

**Comment by luxas** [comment]
I think what @justinsb meant was that the function should be idempotent, and now it is.
Closing, and we can open more targeted issues later if needed...
