### ISSUE TITLE
[root@kubemaster system]# ETCDCTL_API=3 etcdctl member list   --endpoints=https://127.0.0.1:2379   --cacert=/etc/etcd/ca.crt   --cert=/etc/etcd/etcd-server.crt   --key=/etc/etcd/etcd-server.key {"level":"warn","ts":"2020-03-23T12:47:38.622-0400","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-99894cc2-a3c5-4ecf-b869-52c4d121fc1b/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""} Error: context deadline exceeded [root@kubemaster system]#

### ISSUE THREAD

**Issue by sarath4** [kubernetes/kubeadm#2070]
Am trying to configure kubernetes hardway while setup the etcd cluster.
My configuration:
[root@kubemaster system]# cat etcd.service
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
ExecStart=/usr/local/bin/etcd
  --advertise-client-urls=https://192.168.86.128:2379
  --cert-file=/etc/etcd/etcd-server.crt
  --client-cert-auth=true
  --data-dir=/var/lib/etcd
  --initial-advertise-peer-urls=https://192.168.86.128:2380
  --initial-cluster=master=https://192.168.86.128:2380
  --key-file=/etc/etcd/etcd-server.key
  --listen-client-urls=https://127.0.0.1:2379,https://192.168.86.128:2379
  --listen-metrics-urls=http://127.0.0.1:2381
  --listen-peer-urls=https://192.168.86.128:2380
  --name=kubemaster
  --peer-cert-file=/etc/etcd/etcd-server.crt
  --peer-client-cert-auth=true
  --peer-key-file=/etc/etcd/etcd-server.key
  --peer-trusted-ca-file=/etc/etcd/ca.crt
  --snapshot-count=10000
  --trusted-ca-file=/etc/etcd/ca.crt

Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
[root@kubemaster system

**Comment by neolit123** [comment]
> Am trying to configure kubernetes hardway while setup the etcd cluster.

hi, this is the kubeadm repository.
we do not support the "kubernetes the hard way" guide. for related questions, please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
/close
