### ISSUE TITLE
CreateServiceAccounts: Should use kubernetes.Interface instead of *clientset.Clientset

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubeadm#208]
I believe we generally prefer using the interface rather than the concrete class, this would make kubeadm much easier to reuse as a library.  It would also make testing easier.

**Comment by luxas** [comment]
@justinsb I'm gonna work on cleaning this mess up ;)
Also I can take on rebasing kops on those changes as well if you want me to

**Comment by pipejakob** [comment]
This was fixed as part of https://github.com/kubernetes/kubernetes/pull/46875. The new signature is:

    func CreateServiceAccounts(clientset "k8s.io/client-go/kubernetes".Interface) error

https://github.com/kubernetes/kubernetes/blob/e554dd6d3d334fdd8054c8e9df39fa4b35b283f6/cmd/kubeadm/app/phases/apiconfig/clusterroles.go#L53
