### ISSUE TITLE
Multiple nodes in cluster have kubelet certificate that is not signed by kubernetes ca

### ISSUE THREAD

**Issue by brokenjacobs** [kubernetes/kubeadm#2080]
## What keywords did you search in kubeadm issues before filing this one?
kubelet certificates

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:01:11Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
Vmware vsphere 6.7u3
- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
``` 3.10.0-1062.18.1.el7.x86_64```
- **Others**:

## What happened?
I set up a 6 node cluster, restarted kubelet on the first node and it wouldn't start again. When I check apiserver logs it is complaining that the certificate being presented is not signed by the kubernetes CA. I ran a check from /var/lib/kubelet: 
On Failing nodes:
```
# openssl verify -verbose -CAfile /etc/kubernetes/pki/ca.crt kubelet-client-current.pem
kubelet-client-current.pem: O = system:nodes, CN = system:node:den-k8smaster2-1.ci.neoninternal.org
error 7 at 0 depth lookup:certificate signature failure
140035813529488:error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding:rsa_pk1.c:116:
140035813529488:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:rsa_eay.c:761:
140035813529488:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:249:
```
On my other nodes:
```
# openssl verify -verbose -CAfile /etc/kubernetes/pki/ca.crt kubelet-client-current.pem
kubelet-client-current.pem: OK
```

2 of my 3 master nodes have ca signed kubelet certificates. 1 master does not (the first one I built). All 3 of my workers do not. They all have the same ca certificate file at /etc/kubernetes/pki/ca.crt.

## What you expected to happen?
kubelet should have a CA signed certificate on all nodes.

## How to reproduce it (as minimally and precisely as possible)?
I built this cluster, installed flannel and the vmware csi, and this seems to happen. I will try a clean rebuild without flannel or any other components being added to see if the problem reproduces again. So far this has happened twice in a row on rebuilds. 

## Anything else we need to know?
time is synced on all these boxes.

**Comment by neolit123** [comment]
> When I check apiserver logs it is complaining that the certificate being presented is not signed by the kubernetes CA. I ran a check from /var/lib/kubelet:

can you please show the exact message?

> # openssl verify -verbose -CAfile /etc/kubernetes/pki/ca.crt kubelet-client-current.pem
kubelet-client-current.pem: O = system:nodes, CN = system:node:den-k8smaster2-1.ci.neoninternal.org
error 7 at 0 depth lookup:certificate signature failure

kubeadm does not manage these files. they are managed by the kubelet. all kubeadm is doing is enable client certificate rotation for the kubelet -> api-server communication.

Qs:
- is kubelet-client-current.pem even used on the problem nodes?

see the note here:
> Warning:
> On nodes created with kubeadm init, prior to kubeadm version 1.17, ....

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#check-certificate-expiration

- is client-certificate rotation disabled on the nodes (kubeadm enables it by default)?
- what happens if you do the following:
  - stop the kubelet
  - backup /var/lib/kubelet/pki
  - delete the contents of /var/lib/kubelet/pki
  - restart the kubelet
do you see the certificates being recreated?

**Comment by brokenjacobs** [comment]
I am rebuilding these vm's from scratch right now. I did a kubeadm reset between rebuilds and I'm wondering if something stuck around.

I'm going to check the certs after bootstrap on each node and see what happens. If the error happens again I'll bring the apiserver error messages back and report here.

**Comment by brokenjacobs** [comment]
After a rebuild and letting things sit for a bit I can't reproduce. I'm calling this an artifact of improper cleanup and moving on. Closing.
