### ISSUE TITLE
tracking issue for HA to GA

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2081]
long term we need to enumerate what tasks remain for HA support to be considered GA by the kubeadm project.

some ideas:
- more robustness for etcd e.g. using learner mode:
https://github.com/kubernetes/kubeadm/issues/1793
- instance specific component config?
https://github.com/kubernetes/kubeadm/issues/1682
- ?

--------

tracking issue at k/e:
https://github.com/kubernetes/enhancements/issues/357

tracking issue for HA to Beta:
https://github.com/kubernetes/kubeadm/issues/1567

Beta KEPS:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/0015-kubeadm-join-control-plane.md

https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/20190122-Certificates-copy-for-kubeadm-join--control-plane.md

**Comment by fabriziopandini** [comment]
IMO kubeadm HA
- should be agnostic to lb solutions (integrated lb should not be a GA criteria)
- should not be linked to the node specific/component config discussions (this should not be a graduation criteria)

Instead I think that GA criteria should be related to robustness and flexibility. WRT to this on top of my mind the etcd learner feature can be used both for improving robustness and as a sync mechanism for improving reliable parallel joins

**Comment by fabriziopandini** [comment]
@neolit123 wdyt about graduating this feature?

As far as I'm concerned we have two point still on the table
- Use etcd learner mode
- Parallel join for control plane nodes

Both of them are nice to have, but at the same time they requires investigation and I don't see use getting on them in the near future. So I'm starting to wonder if we have to go GA with the current implementation, which is now stable since a couple of versions, and reconsider the points above eventually in future

**Comment by neolit123** [comment]
> Parallel join for control plane nodes

i guess this is already supported within the limits of our hardcoded timeouts / retries on join.

> Both of them are nice to have, but at the same time they requires investigation and I don't see use getting on them in the near future. So I'm starting to wonder if we have to go GA with the current implementation, which is now stable since a couple of versions, and reconsider the points above eventually in future

i see what you mean, but maybe we can ask contributors to investigate learners mode and someone could create a prototype before going GA without it:
https://github.com/kubernetes/kubeadm/issues/1793

another item in the OP here is instance specific config:
https://github.com/kubernetes/kubeadm/issues/1682
i don't remember why we added it and it has a "?". current workaround for configuring a CP node differently is with patches.
your operator proposal had some ideas about instance specific config per CP node.
