### ISSUE TITLE
New HA setup - kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach

### ISSUE THREAD

**Issue by tedbrunelle** [kubernetes/kubeadm#2082]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm "Setting node annotation to enable volume controller attach/detach" HA, etcd

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
When attempting to kubeadm init --config=./config.yaml
my log file fills up with:
<pre>kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach</pre>

<pre>
Mar 29 01:27:52 kube-etcd1 kubelet[9450]: E0329 01:27:52.914386    9450 pod_workers.go:191] Error syncing pod 5dfd66fc8f0aa1926b6d66e181127def ("etcd-kube-etcd1.lan.ipsllc.us_kube-system(5dfd66fc8f0aa1926b6d66e181127def)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "back-off 5m0s restarting failed container=etcd pod=etcd-kube-etcd1.lan.ipsllc.us_kube-system(5dfd66fc8f0aa1926b6d66e181127def)"
Mar 29 01:27:58 kube-etcd1 kubelet[9450]: I0329 01:27:58.809450    9450 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Mar 29 01:28:06 kube-etcd1 kubelet[9450]: I0329 01:28:06.883916    9450 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Mar 29 01:28:06 kube-etcd1 kubelet[9450]: I0329 01:28:06.912744    9450 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 8a7cdc6a9b1f932630902ca92923dc3e3500a4cf46d78922d5596cd5b7302eab
Mar 29 01:28:06 kube-etcd1 kubelet[9450]: E0329 01:28:06.913158    9450 pod_workers.go:191] Error syncing pod 5dfd66fc8f0aa1926b6d66e181127def ("etcd-kube-etcd1.lan.ipsllc.us_kube-system(5dfd66fc8f0aa1926b6d66e181127def)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "back-off 5m0s restarting failed container=etcd pod=etcd-kube-etcd1.lan.ipsllc.us_kube-system(5dfd66fc8f0aa1926b6d66e181127def)"
Mar 29 01:28:08 kube-etcd1 kubelet[9450]: I0329 01:28:08.856612    9450 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Mar 29 01:28:17 kube-etcd1 kubelet[9450]: I0329 01:28:17.883916    9450 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Mar 29 01:28:17 kube-etcd1 kubelet[9450]: I0329 01:28:17.911635    9450 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 8a7cdc6a9b1f932630902ca92923dc3e3500a4cf46d78922d5596cd5b7302eab
Mar 29 01:28:17 kube-etcd1 kubelet[9450]: E0329 01:28:17.912044    9450 pod_workers.go:191] Error syncing pod 5dfd66fc8f0aa1926b6d66e181127def ("etcd-kube-etcd1.lan.ipsllc.us_kube-system(5dfd66fc8f0aa1926b6d66e181127def)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "back-off 5m0s restarting failed container=etcd pod=etcd-kube-etcd1.lan.ipsllc.us_kube-system(5dfd66fc8f0aa1926b6d66e181127def)"
Mar 29 01:28:18 kube-etcd1 kubelet[9450]: I0329 01:28:18.900573    9450 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
</pre>

And the health check fails.

## How to reproduce it (as minimally and precisely as possible)?
I followed the guide on setting up the HAProxy and hearbeat server.
This worked.
https://medium.com/faun/configuring-ha-kubernetes-cluster-on-bare-metal-servers-with-kubeadm-1-2-1e79f0f7857b

Starting Part 5, I switched to the more current document below:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

the EXACT setup commands were:
<pre>
cat << EOF > /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
[Service]
ExecStart=
#  Replace "systemd" with the cgroup driver of your container runtime. The default value in the kubelet is "cgroupfs".
ExecStart=/usr/bin/kubelet --address=127.0.0.1 --pod-manifest-path=/etc/kubernetes/manifests --cgroup-driver=systemd
Restart=always
EOF

systemctl daemon-reload
systemctl restart kubelet

# Update HOST0, HOST1, and HOST2 with the IPs or resolvable names of your hosts
export HOST0=10.64.0.101
export HOST1=10.64.0.102
export HOST2=10.64.0.103

# Create temp directories to store files that will end up on other hosts.
mkdir -p /tmp/${HOST0}/ /tmp/${HOST1}/ /tmp/${HOST2}/

ETCDHOSTS=(${HOST0} ${HOST1} ${HOST2})
NAMES=("infra0" "infra1" "infra2")

for i in "${!ETCDHOSTS[@]}"; do
HOST=${ETCDHOSTS[$i]}
NAME=${NAMES[$i]}
cat << EOF > /tmp/${HOST}/kubeadmcfg.yaml
apiVersion: "kubeadm.k8s.io/v1beta2"
kind: ClusterConfiguration
etcd:
    local:
        serverCertSANs:
        - "${HOST}"
        peerCertSANs:
        - "${HOST}"
        extraArgs:
            initial-cluster: ${NAMES[0]}=https://${ETCDHOSTS[0]}:2380,${NAMES[1]}=https://${ETCDHOSTS[1]}:2380,${NAMES[2]}=https://${ETCDHOSTS[2]}:2380
            initial-cluster-state: new
            name: ${NAME}
            listen-peer-urls: https://${HOST}:2380
            listen-client-urls: https://${HOST}:2379
            advertise-client-urls: https://${HOST}:2379
            initial-advertise-peer-urls: https://${HOST}:2380
EOF
done

kubeadm init phase certs etcd-ca
ls /etc/kubernetes/pki/etcd/ 

kubeadm init phase certs etcd-server --config=/tmp/${HOST2}/kubeadmcfg.yaml
kubeadm init phase certs etcd-peer --config=/tmp/${HOST2}/kubeadmcfg.yaml
kubeadm init phase certs etcd-healthcheck-client --config=/tmp/${HOST2}/kubeadmcfg.yaml
kubeadm init phase certs apiserver-etcd-client --config=/tmp/${HOST2}/kubeadmcfg.yaml
cp -R /etc/kubernetes/pki /tmp/${HOST2}/

find /etc/kubernetes/pki -not -name ca.crt -not -name ca.key -type f -delete

### Create certificates for the etcd2 node
kubeadm init phase certs etcd-server --config=/tmp/${HOST1}/kubeadmcfg.yaml
kubeadm init phase certs etcd-peer --config=/tmp/${HOST1}/kubeadmcfg.yaml
kubeadm init phase certs etcd-healthcheck-client --config=/tmp/${HOST1}/kubeadmcfg.yaml
kubeadm init phase certs apiserver-etcd-client --config=/tmp/${HOST1}/kubeadmcfg.yaml
cp -R /etc/kubernetes/pki /tmp/${HOST1}/

find /etc/kubernetes/pki -not -name ca.crt -not -name ca.key -type f -delete

### Create certificates for the this local node
kubeadm init phase certs etcd-server --config=/tmp/${HOST0}/kubeadmcfg.yaml
kubeadm init phase certs etcd-peer --config=/tmp/${HOST0}/kubeadmcfg.yaml
kubeadm init phase certs etcd-healthcheck-client --config=/tmp/${HOST0}/kubeadmcfg.yaml
kubeadm init phase certs apiserver-etcd-client --config=/tmp/${HOST0}/kubeadmcfg.yaml

find /tmp/${HOST2} -name ca.key -type f -delete
find /tmp/${HOST1} -name ca.key -type f -delete

cat << EOF > /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}
EOF
sed -i "s/cgroup-driver=systemd/cgroup-driver=cgroupfs/g" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
/etc/init.d/docker restart
systemctl daemon-reload
systemctl restart kubelet

chown root.root pki/ kubeadmcfg.yaml  -R
rm -rf /etc/kubernetes/pki; mv pki/ /etc/kubernetes/
kubeadm init phase etcd local --config=/root/kubeadmcfg.yaml
</pre>

Everything seemed to work.
netstat -tulpn gives:
<pre>
root@kube-etcd1:~# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      465/sshd            
tcp        0      0 127.0.0.1:33927         0.0.0.0:*               LISTEN      9450/kubelet        
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      9450/kubelet        
tcp        0      0 127.0.0.1:10250         0.0.0.0:*               LISTEN      9450/kubelet        
tcp        0      0 10.64.0.100:6443        0.0.0.0:*               LISTEN      472/haproxy         
tcp        0      0 127.0.0.1:10255         0.0.0.0:*               LISTEN      9450/kubelet        
tcp6       0      0 :::22                   :::*                    LISTEN      465/sshd            
udp        0      0 0.0.0.0:42910           0.0.0.0:*                           490/heartbeat: writ 
udp        0      0 0.0.0.0:47162           0.0.0.0:*                           494/heartbeat: writ 
udp        0      0 127.0.0.1:5404          0.0.0.0:*                           432/corosync        
udp        0      0 239.192.24.204:5405     0.0.0.0:*                           432/corosync        
udp        0      0 127.0.0.1:5405          0.0.0.0:*                           432/corosync        
udp        0      0 0.0.0.0:58708           0.0.0.0:*                           492/heartbeat: writ 
udp        0      0 0.0.0.0:37241           0.0.0.0:*                           488/heartbeat: writ 
udp        0      0 0.0.0.0:694             0.0.0.0:*                           494/heartbeat: writ 
udp        0      0 0.0.0.0:694             0.0.0.0:*                           492/heartbeat: writ 
udp        0      0 225.0.0.1:694           0.0.0.0:*                           490/heartbeat: writ 
udp        0      0 0.0.0.0:694             0.0.0.0:*                           488/heartbeat: writ 
</pre>

except - this times out:
<pre>
docker run --rm -it \
--net host \
-v /etc/kubernetes:/etc/kubernetes quay.io/coreos/etcd:v3.2.24 etcdctl \
--cert-file /etc/kubernetes/pki/etcd/peer.crt \
--key-file /etc/kubernetes/pki/etcd/peer.key \
--ca-file /etc/kubernetes/pki/etcd/ca.crt \
--endpoints https://10.64.0.101:2379 cluster-health
</pre>

I also attempted to switch from cgroupfs to systemd:
<pre>
cat << EOF > /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"]
}
EOF
sed -i "s/cgroup-driver=systemd/cgroup-driver=cgroupfs/g" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
/etc/init.d/docker restart
systemctl daemon-reload
systemctl restart kubelet
</pre>
and docker info DOES reflect that I am using systemd.v

**Comment by tedbrunelle** [comment]
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:56:30Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

root@kube-etcd1:/# docker -v
Docker version 19.03.8, build afacb8b7f0

**Comment by neolit123** [comment]
> I also attempted to switch from cgroupfs to systemd:

did you switch your cgroup driver after creating the cluster? this is a bad idea.
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers

> Caution: Changing the cgroup driver of a Node that has joined a cluster is highly unrecommended. 

[*] it's difficult to recover from this, so this cluster should be recreated at this point...

> kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach

this is not something that kubeadm manages.

> Mar 29 01:28:17 kube-etcd1 kubelet[9450]: E0329 01:28:17.912044    9450 pod_workers.go:191] Error syncing pod 5dfd66fc8f0aa1926b6d66e181127def ("etcd-kube-etcd1.lan.ipsllc.us_kube-system(5dfd66fc8f0aa1926b6d66e181127def)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "back-off 5m0s restarting failed container=etcd pod=etcd-kube-etcd1.lan.ipsllc.us_kube-system(5dfd66fc8f0aa1926b6d66e181127def)"

there seem to be errors starting the etcd pod. can be caused by [*].
what is the output of `kubectl get po -A`?

i've just tried the following and it worked for me on a running cluster:
```
docker run --rm -it --net host -v /etc/kubernetes:/etc/kubernetes quay.io/coreos/etcd:v3.2.24 etcdctl --cert-file /etc/kubernetes/pki/etcd/peer.crt --key-file /etc/kubernetes/pki/etcd/peer.key --ca-file /etc/kubernetes/pki/etcd/ca.crt --endpoints https://172.17.0.54:2379 cluster-health
```

> except - this times out:

if your etcd pod is running are you sure you are passing the right IP?

/triage support

**Comment by tedbrunelle** [comment]
Hi,
I did a "kubeadm reset", then switched from the cgroup driver to systemd, then performed the mentioned initialization and attempted join.
When I ran:
kube-etcd1:~$ kubectl get po -A
I get:
<pre>
error: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
</pre>

RE: _if your etcd pod is running are you sure you are passing the right IP?_
I'm passing the IP address of the LAN/management interface, which is pingable from the network, and is the IP that I'm ssh'ed into:
<pre>
tb@kube-etcd1:~$ ip a
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 4e:28:80:1d:d0:94 brd ff:ff:ff:ff:ff:ff
**(This is the machine management IP (the one I'm using))**
    inet 10.64.0.101/22 brd 10.64.3.255 scope global eth0
       valid_lft forever preferred_lft forever
**(This is the HA Proxy IP)**
    inet 10.64.0.100/22 brd 10.64.3.255 scope global secondary eth0:0   
       valid_lft forever preferred_lft forever
    inet6 fe80::4c28:80ff:fe1d:d094/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
</pre>

Am I joining the machine wrong? Is there a better tutorial to set this up than the one from Kubernetes site directly?

**Comment by neolit123** [comment]
hi,

> kube-etcd1:~$ kubectl get po -A

you need to run this on the control-plane node where you have the /etc/kubernetes/admin.conf

> Am I joining the machine wrong?

not clear. i suggest you clear the machines and start from scratch with a systemd cgroup driver.

> Is there a better tutorial to set this up than the one from Kubernetes site directly?

we don't get many user reports about that guide so it seems to be working fine for people.

this seems like a support ticket. let's re-open a ticket if we find a bug in kubeadm or an issue with our docs.

also the #kubeadm channel on k8s slack is a good place to ask for help. support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
