### ISSUE TITLE
Specify node taint on node join

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes/kubeadm#209]
Similar to #202, we should have an option to taint a node on join. One use case is when a cluster would have a set of nodes dedicated for ingress-controllers. A DaemonSet could be deployed that can use the label option in #202, and the taint option here. Otherwise this is a manual process.

**Comment by fabriziopandini** [comment]
I'm working on a PR on this and #202

**Comment by luxas** [comment]
See my comment: https://github.com/kubernetes/kubeadm/issues/202#issuecomment-302929790

**Comment by timothysc** [comment]
/assign @fabriziopandini @timothysc 

@fabriziopandini Is there anything left todo.

**Comment by fabriziopandini** [comment]
@timothysc this is still not addressed.

Following options where considered and then discarded:
1) generate systemd drop-ins and restart kubelet 
2) use dynamic kubelet config

The only option left on the table is to wait for the node to join and then send labels to the apiserver, but it is kind of risky for worker nodes nodes - where the only identity you get is the token or the kubelet itself - (see https://github.com/kubernetes/kubeadm/issues/202#issuecomment-335209964 from JBeda).

IMO we can create all the necessary facilities and the let the user explicitly opt-in for this:
- with a new phase (or by default during init) create a new RBAC role that allows to taint/label and nodes (but not assign tokens to this rule)
- let the user to use `kubeadm create token` to create additional tokens assigned to the above role
- modify `kubeadm join` for applying labels/taint or fail gracefully if the token doesn't have necessary grants.

WDYT?

**Comment by timothysc** [comment]
So the auth folks have ki-bashed this idea as a sec-hole.  

https://github.com/kubernetes/kubernetes/pull/63167  

I think we're going to have to admin control.
