### ISSUE TITLE
container linux docs include invalid URLs

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2097]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
container linux tab includes invalid links for the dropin/unit files.

these are now in https://github.com/kubernetes/release/tree/master/cmd/kubepkg/templates/latest

/kind documentation
/priority backlog
/assign

**Comment by RA489** [comment]
I can take a look.

**Comment by neolit123** [comment]
i've sent a PR here as i had to also clean something else on the same page.

/lifecycle active

**Comment by RA489** [comment]
Thanks for filing the PR.
