### ISSUE TITLE
Failed to create load balancer  for service default/nginx: No node tags supplied and also failed to parse the given lists of hosts for tags. Abort creating firewall rule.

### ISSUE THREAD

**Issue by edenxia** [kubernetes/kubeadm#210]
## What keywords did you search in kubeadm issues before filing this one?
Failed to create load balancer
 for service default/nginx: No node tags supplied and also failed to parse the given lists of hosts for tags. Abort creating firewall rule.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):v1.6.0-alpha.0.2074+a092d8e0f95f52

**Environment**:
- **Kubernetes version** (use `kubectl version`):GitVersion:"v1.5.5
- **Cloud provider or hardware configuration**:GCE
- **OS** (e.g. from /etc/os-release):Ubuntu 16.04.2 LTS
- **Kernel** (e.g. `uname -a`):4.4.0-66-generic
- **Others**:

## What happened?
when run "kubcelt expose deployment nginx --port=80 --type=LoadBalancer", can not get external IP. instead, it showed "pending ". the detail error is "Error creating load balancer (will retry): Failed to create load balancer
 for service default/nginx: No node tags supplied and also failed to parse the given lists of hosts for tags. Abort creating firewall rule."

## What you expected to happen?
get external IP when expose service type=LoadBalancer

## How to reproduce it (as minimally and precisely as possible)?
1. create 2 instances on GCE(one master and one node).
2. tag node as kube-test
3. follow https://kubernetes.io/docs/getting-started-guides/kubeadm/ to install kubeadm and init a cluster
4. install weave-net "kubectl apply -f https://git.io/weave-kube"
5. join node to cluster
6. run one nginx pod: " kubectl run nginx --image=nginx"
7. expose service: "kubectl expose deployment nginx --port=80 --type=LoadBalancer"
8. after 30 secs, run : "kubectl get events". it will showed the error

## Anything else we need to know?
we can expose service type as LoadBalancer successfully if we use GKE or if we setup cluster using kube-up.sh following https://kubernetes.io/docs/getting-started-guides/gce/

**Comment by edenxia** [comment]
I know what was wrong. we have to set the one tag(must be same) for both master and nodes. then it works fine. should add it to document?

**Comment by timothysc** [comment]
@edenxia 

> should add it to document? 

Yes please, but I don't know exactly where to add it under https://github.com/kubernetes/kubernetes.github.io

**Comment by jamiehannaford** [comment]
@edenxia What tag are you referring to? Can you explain how you resolved this issue?

**Comment by luxas** [comment]
And at the same time, please document it in the https://github.com/kubernetes/kubernetes.github.io repo

**Comment by jamiehannaford** [comment]
TBH I don't think this is a kubeadm failure, but rather some kind of cloud provider/node issue. Due to the lack of details saying otherwise, can we go ahead and close this? We can reopen if the OP provides more info.

**Comment by luxas** [comment]
@edenxia Please give us more information; are you running on GCE for example?
Until that, we'll have this issue closed.

**Comment by gangadhars** [comment]
Hi!
I'm facing the same issue. I'm running my cluster on GCE.  Here are my  controller logs:

```
I0920 14:16:59.135121    2177 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"instance-2", UID:"8f954b67-9e08-11e7-a800-42010a800002", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node instance-2 event: Registered Node instance-2 in NodeController
I0920 14:16:59.135405    2177 servicecontroller.go:663] Detected change in list of current cluster nodes. New node set: [instance-2]
I0920 14:16:59.135455    2177 servicecontroller.go:671] Successfully updated 0 out of 0 load balancers to direct traffic to the updated set of nodes
I0920 14:16:59.615459    2177 gce.go:596] Forwarding rule a8586c5d39e0911e7a80042010a80000 for Service default/nginx doesn't exist
I0920 14:17:03.406581    2177 gce.go:724] EnsureLoadBalancer(a8586c5d39e0911e7a80042010a80000(default/nginx)): creating firewall
E0920 14:17:07.089403    2177 servicecontroller.go:779] Failed to process service. Retrying in 5s: Failed to create load balancer for service default/nginx: No node tags supplied and also failed to parse the given lists of hosts for tags. Abort creating firewall rule.
I0920 14:17:12.312178    2177 gce.go:596] Forwarding rule a8586c5d39e0911e7a80042010a80000 for Service default/nginx doesn't exist
I0920 14:17:16.043793    2177 gce.go:724] EnsureLoadBalancer(a8586c5d39e0911e7a80042010a80000(default/nginx)): creating firewall
E0920 14:17:19.580197    2177 servicecontroller.go:779] Failed to process service. Retrying in 10s: Failed to create load balancer for service default/nginx: No node tags supplied and also failed to parse the given lists of hosts for tags. Abort creating firewall rule.
```
I have deployed cluster manually.  Please let me know if more information needed.

**Comment by kigawas** [comment]
> I know what was wrong. we have to set the one tag(must be same) for both master and nodes. then it works fine. should add it to document?

Excuse me, how can I set tag? Is it this?

https://cloud.google.com/vpc/docs/add-remove-network-tags

**Comment by ShilpaMerinMathew** [comment]
Is there any update on how to give a tag for the nodes so that the load balancer is allocated properly. I am having this issue. Can somebody help me ?

**Comment by AleksZimin** [comment]
> Is there any update on how to give a tag for the nodes so that the load balancer is allocated properly. I am having this issue. Can somebody help me ?

You can see this issue:
https://github.com/kubernetes/ingress-nginx/issues/462

Or this doc:
https://github.com/brightzheng100/kubernetes-the-kubeadm-way/blob/master/docs/10-faq.md#error-failed-to-ensure-load-balancer-in-kubernetes-on-gce
