### ISSUE TITLE
If possible, commands like 'kubeadm init phase' prefer to use the configuration stored in kube-system/kubeadm-config ConfigMap first

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubeadm#2103]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

I created a cluster using `kubeadm init --image-repository=registry.aliyuncs.com/google_containers`.
For some reason, I mistakenly deleted `kube-proxy` DaemonSet.
So I redeployed the `kube-proxy` DaemonSet using `kubeadm init phase addon kube-proxy`.
However, the new `kube-proxy` DaemonSet does not use the previous image repository(`registry.aliyuncs.com/google_containers`), but the default value `k8s.gcr.io`.
I know we can run `kubeadm init phase addon kube-proxy --image-repository=registry.aliyuncs.com/google_containers` to explicitly specify the image repository.
But it would be better/smarter if kubeadm can fetch `kubeadm-config` automatically.

The `image-repository` already stored in cluster:
```
# kubectl get cm kubeadm-config -n kube-system -o yaml | grep imageRepository
    imageRepository: registry.aliyuncs.com/google_containers
```

## Versions

**kubeadm version** (use `kubeadm version`): v1.18.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.18.0
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
kubeadm lacks the ability to intelligently retrieve configuration from cluster.

## What you expected to happen?
If possible, commands like 'kubeadm init phase' prefer to use the configuration stored in `kube-system/kubeadm-config` ConfigMap first.

**Comment by neolit123** [comment]
we had a similar request for `kubeadm config image list`.
https://github.com/kubernetes/kubeadm/issues/1842

- on the CLI we have flags, we in the long-term we should maybe deprecate (at least the kubelet is doing that).
- users should execute `--config` with a config file on disk for all use cases.
- a kubeadm "config" file for "init" can contain multiple config types initconfiguration, clusterconfiguration, etc.
- clusterconfiguration is a partial "init" configuration. adding the assumption that can be fetched from the cluster if the user does not pass a `--config` means that we have a gap about the rest of the kubeadm config kinds.

my personal vote would be to not add assumptions in kubeadm commands that the cluster is already up and clusterconfiguration can be fetched from there, as this creates maintenance complications for us. `--config` on disk should be the source of truth for all commands and it's easier for us to know this is the case when helping with user bug reports.

/kind design
/priority awaiting-more-evidence
cc @rosti @fabriziopandini

**Comment by SataQiu** [comment]
Admittedly, this will add to the complexity of maintenance for us :(
To keep things simple, we do need to sacrifice something.

**Comment by fabriziopandini** [comment]
I totally agree with @neolit123 point 
Adding --config to all your calls is a reasonable price also considering that explicit should be always preferred to implicit

**Comment by neolit123** [comment]
closing due to consensus. thanks.
/close
