### ISSUE TITLE
Consultation request: kubeadm join fails with conntract not found when run as cron job

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubeadm#2112]
This is *not* kubeadm bug.

I run a wrapper script that calls 'kubeadm join ...".
As master may not be available at that point (say, network issues), I write a cron job that invokes this script periodically until it succeeds.

When  I run the script manually, "kubeadm join ..." succeeds.
But when run as cron job, it fails with

```
pr 22 04:31:18.891528 str-s6000-acs-13 NOTICE kube_join_stdout: #011[WARNING FileExisting-ebtables]: ebtables not found in system path
Apr 22 04:31:18.894494 str-s6000-acs-13 NOTICE kube_join_stdout: #011[WARNING FileExisting-ethtool]: ethtool not found in system path
Apr 22 04:31:18.896623 str-s6000-acs-13 NOTICE kube_join_stdout: #011[WARNING FileExisting-tc]: tc not found in system path
Apr 22 04:31:19.857096 str-s6000-acs-13 NOTICE kube_join_stdout: error execution phase preflight: [preflight] Some fatal errors occurred:
Apr 22 04:31:19.861932 str-s6000-acs-13 NOTICE kube_join_stdout: #011[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
Apr 22 04:31:19.865987 str-s6000-acs-13 NOTICE kube_join_stdout: #011[ERROR FileExisting-conntrack]: conntrack not found in system path
Apr 22 04:31:19.867642 str-s6000-acs-13 NOTICE kube_join_stdout: #011[ERROR FileExisting-iptables]: iptables not found in system path
Apr 22 04:31:19.869441 str-s6000-acs-13 NOTICE kube_join_stdout: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
Apr 22 04:31:19.870841 str-s6000-acs-13 NOTICE kube_join_stdout: To see the stack trace of this error execute with --v=5 or higher

```

Any tips can be extremely helpful.

**Comment by neolit123** [comment]
/triage support
you can try skipping the relevant preflight with `kubeadm join ... --ignore-preflight-errors=FileExisting-ebtables,FileExisting-conntrack,...` but it would be better if you add these utils to the OS where you run kubeadm.

**Comment by renukamanavalan** [comment]
Thank you for the response. But these modules must be there, as I have *no* issue running it manually. The same command when executed via cron job, has the failure stated above.

```
Apr 22 04:46:34.685750 str-s6000-acs-13 NOTICE kube_join_stdout: [preflight] Running pre-flight checks
Apr 22 04:46:35.905822 str-s6000-acs-13 NOTICE kube_join_stdout: #011[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
Apr 22 04:46:42.086874 str-s6000-acs-13 NOTICE kube_join_stdout: [preflight] Reading configuration from the cluster...
Apr 22 04:46:42.089679 str-s6000-acs-13 NOTICE kube_join_stdout: [preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
Apr 22 04:46:42.289633 str-s6000-acs-13 NOTICE kube_join_stdout: [kubelet-start] Downloading configuration for the kubelet from the "kubelet-config-1.18" ConfigMap 

```

This implies that the system has all the required modules installed. Just when run as CRON job, it has some issues.

Anyone has any tips ?

**Comment by neolit123** [comment]
> Thank you for the response. But these modules must be there, as I have no issue running it manually. The same command when executed via cron job, has the failure stated above.

how are you setting the cron jobs; can you show the configuration?

> This implies that the system has all the required modules installed. Just when run as CRON job, it has some issues.

could be an issue with paths.

**Comment by renukamanavalan** [comment]
Yep. That fixed it. I should have tried, before creating noise. Sorry.

For others, who may encounter, "run sudo env" to get info and run it under cron, to see the diff. Look at the diff, make changes as needed.

For me,  I added "`export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`" in my script, that fixed it.

**Comment by neolit123** [comment]
thank you for confirming it was a PATH issue.
