### ISSUE TITLE
Bad default value for `--image` on `kinder create cluster` cmd

### ISSUE THREAD

**Issue by prasadkatti** [kubernetes/kubeadm#2116]
## What keywords did you search in kubeadm issues before filing this one?
image, latest

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST
The `kinder create cluster` command uses `kindest/node:latest` as the default image. But it looks like there is no `kindest/node` with `latest` tag on Docker hub. 
Maybe `--image` should be a required flag.

## Versions

**kubeadm version** (use `kubeadm version`): 
master

## What happened?
Error saying "manifest for kindest/node:latest not found"

## What you expected to happen?
cluster is created

## How to reproduce it (as minimally and precisely as possible)?
- `kinder create cluster`
Fails with the error `ERRO[15:50:35] docker: Error response from daemon: manifest for kindest/node:latest not found: manifest unknown: manifest unknown.` There does not seem to be a `latest` tag for that repo on [Docker Hub](https://hub.docker.com/r/kindest/node/tags?page=1&name=latest)

**Comment by SataQiu** [comment]
Thank you for reporting this @prasadkatti . 
/cc @neolit123 

In fact, You can build the image locally.  

- ensure that Kubernetes is cloned in `$(go env GOPATH)/src/k8s.io/kubernetes`
- build a node image and create a cluster with:
```console
kind build node-image
kinder create cluster 
```

But it is really a bad user experience that the deault image can not be pulled. 😟

**Comment by fabriziopandini** [comment]
I don't have strong preference here.
We can either remove the default or default to a specific version; the latter introduce a little maintenance burden

**Comment by neolit123** [comment]
> Maybe --image should be a required flag.

+1 on making the flag required and making the default "".

**Comment by fabriziopandini** [comment]
@prasadkatti do you want to give a try to this one?

**Comment by prasadkatti** [comment]
Sure. I will try to create to a PR for this.
