### ISSUE TITLE
`kinder do smoke-test` fails

### ISSUE THREAD

**Issue by prasadkatti** [kubernetes/kubeadm#2117]
## What keywords did you search in kubeadm issues before filing this one?
smoke

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
`kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T20:54:24Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

## What happened?
I was following the kinder [getting started](https://github.com/kubernetes/kubeadm/blob/master/kinder/doc/getting-started.md) guide.  I was able to create a cluster, but the `kinder do smoke-test` fails.

## What you expected to happen?
Expected the smoke test to pass.

## How to reproduce it (as minimally and precisely as possible)?
Follow along the kinder [getting started](https://github.com/kubernetes/kubeadm/blob/master/kinder/doc/getting-started.md) guide.

## Anything else we need to know?
The smoke test runs -

- `kubectl --kubeconfig=/etc/kubernetes/admin.conf run nginx ...` which creates an nginx pod.
- `kubectl --kubeconfig=/etc/kubernetes/admin.conf expose deployment nginx --port=80 --type=NodePort` which fails with "deployments.apps "nginx" not found"

**Comment by prasadkatti** [comment]
Looks like it is related to this - https://github.com/kubernetes/kubernetes/pull/87077 - (Remove kubectl run generators)

**Comment by prasadkatti** [comment]
I can work on a PR for fixing this.
/assign

**Comment by fabriziopandini** [comment]
thanks @prasadkatti
