### ISSUE TITLE
Use deploy(with node selector) to prepull the images

### ISSUE THREAD

**Issue by xlgao-zju** [kubernetes/kubeadm#2122]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

If this is a FEATURE REQUEST, please:

When I upgrade a cluster with 3 masters, we will create 3 pre-puller daemonsets to pull the master images.  And when I upgrade master 1, we will get 9 pre-puller pods. The 9 pre-puller pods will run on all masters, and pull the images. But when I grade master 2, there will be another 9 pre-puller pods. And the master images are already pulled, when we upgrade master 1.

So how about using a deploy(with node selector) to prepull the images? So that we will not have extra pre-pull pods. This is good for the performance of upgrading and saving resources.

If we are all agree with this FEATURE REQUEST, I'd like file a PR to implement it.
## Versions

**kubeadm version** (use `kubeadm version`): 1.16.6

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.16.6
- **Cloud provider or hardware configuration**: alibaba cloud
- **OS** (e.g. from /etc/os-release): CentOS 7.7
- **Kernel** (e.g. `uname -a`): 3.10.0-1062.9.1.el7.x86_64
- **Others**:

**Comment by neolit123** [comment]
hi @xlgao-zju 

> When I upgrade a cluster with 3 masters, we will create 3 pre-puller daemonsets to pull the master images. And when I upgrade master 1, we will get 9 pre-puller pods. The 9 pre-puller pods will run on all masters, and pull the images. But when I grade master 2, there will be another 9 pre-puller pods. And the master images are already pulled, when we upgrade master 1.

`kubeadm upgrade apply ...` pulls images using a daemonset, but you are supposed to call this only on a single node. for the rest of the nodes you should call `kubeadm upgrade node ...`.

> So how about using a deploy(with node selector) to prepull the images? So that we will not have extra pre-pull pods. This is good for the performance of upgrading and saving resources.

we have plans to not use kubernetes constructs (DaemonSet, Deployment...etc) and instead use per-node prepull during preflight:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L835-L848

this is out of scope for 1.19, or at least we haven't planned it.

**Comment by xlgao-zju** [comment]
>we have plans to not use kubernetes constructs (DaemonSet, Deployment...etc) and instead use per-node prepull during preflight:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L835-L848
this is out of scope for 1.19, or at least we haven't planned it for this cycle.

@neolit123 thank you for information. this plan is cool! and feel free to ping me, if there is anything I can help 😆

**Comment by neolit123** [comment]
ok, i'm going to close this ticket.
please follow https://github.com/kubernetes/kubeadm/issues/2123
