### ISSUE TITLE
investigate if we should stop using a DaemonSet for upgrade prepull

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2123]
investigate if we should stop using a DaemonSet for upgrade prepull.

@rosti brought the idea that we might want to maintain a single peace of code for doing prepull during init/join/upgrade.

upgrade currently uses a separate method - a DS.

see the discussion here:
https://github.com/kubernetes/kubeadm/issues/1862#issuecomment-616899539

/kind feature
/kind design
/priority backlog

**Comment by xlgao-zju** [comment]
I'd like to hear the opinion of everyone. And I'd like to help, if there is anything help wanted.

**Comment by fabriziopandini** [comment]
If we mange to remove pre-pull DS this will be a nice clean up for the upgrade logic.
 +1 for me

**Comment by xlgao-zju** [comment]
@fabianofranz @neolit123 Since we have already pulled images in the preflight:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L835-L848

I'd like to file a RP to remove pre-pull DS, WDYT?

**Comment by neolit123** [comment]
on paper it's simple enough, but i'm hesitant about doing that for 1.19 as it was not discussed in our planning session as a feature change / redesign.
@rosti @fabriziopandini thoughts?

**Comment by fabriziopandini** [comment]
Let's wait for @xlgao-zju providing some feedback on how complex this change is; If the implementation is straight forward, IMO we can consider this as a running task.

**Comment by xlgao-zju** [comment]
@neolit123 @fabriziopandini PR is filed, PTAL

https://github.com/kubernetes/kubernetes/pull/90788
