### ISSUE TITLE
kubeadm 1.5.6 package depends on kubelet 1.6.0

### ISSUE THREAD

**Issue by mausch** [kubernetes/kubeadm#213]
## What happened?

https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages currently has this definition for kubeadm 1.5.6:

```
Package: kubeadm
Version: 1.5.6-00
Installed-Size: 97696
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: amd64
Depends: kubelet (>= 1.6.0), kubectl (>= 1.6.0)
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.
Homepage: https://kubernetes.io
Filename: pool/kubeadm_1.5.6-00_amd64_badd4eb6b4ab3283f2f7be8b37e47a3a35c3252dd09903c103e1c2855134bab9.deb
Priority: optional
SHA256: badd4eb6b4ab3283f2f7be8b37e47a3a35c3252dd09903c103e1c2855134bab9
Section: misc
Size: 12865444
```

So I can't install kubeadm with kubernetes 1.5.x

## How to reproduce it (as minimally and precisely as possible)?

`$ sudo apt-get install -y kubelet=1.5.6-00 kubeadm=1.5.6-00 kubectl=1.5.6-00 kubernetes-cni`

output:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 kubeadm : Depends: kubelet (>= 1.6.0) but 1.5.6-00 is to be installed
           Depends: kubectl (>= 1.6.0) but 1.5.6-00 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mikedanese** [comment]
Probably a bug in https://github.com/kubernetes/release/blob/master/debian/build.go, looking...

**Comment by mikedanese** [comment]
I can't add the last stable version of kubeadm to the kubernetes repo because it's sort higher then 1.6.0 (it was 1.6.0-alpha). I think the right thing to do here is just remove old kubeadm versions. cc @luxas 
Going forward this should be possible now that kubeadm is on the opensource release.

**Comment by mausch** [comment]
:-1: to removing old versions. 
I already had 1.5.x working, seems there are breaking changes in 1.6.x because I still can't get it to work.

**Comment by mikedanese** [comment]
Kubeadm is alpha in 1.5. My concern is that we have absolutely no idea whether kubeadm 1.5.6 works with the rest of 1.5.6 because we haven't tested this configuration ever.

**Comment by mausch** [comment]
I see. It seems the problem I have now with kubeadm 1.6 is  https://github.com/kubernetes/kubernetes/issues/43815 . But because I can't even install any other kubeadm version it means I can't use kubeadm at all.

**Comment by mikedanese** [comment]
If you want, you can use kubernetes-xenial-unstable which has the fixed kubeadm packages. I'm very hesitant to tag an untested alpha release as stable when a beta exists.

https://packages.cloud.google.com/apt/dists/kubernetes-xenial-unstable/main/binary-amd64/Packages

**Comment by mikedanese** [comment]
I will let @luxas weigh in.

**Comment by mikedanese** [comment]
I'm leaving 1.5.6 in stable until 1.6 isn't broken. I'm going to remove it after since it's alpha with known vulnerabilities and not tested. After 1.6, we will leave the debs in the repo forever.

**Comment by mausch** [comment]
Thanks!
