### ISSUE TITLE
document the usage of --service-cidr and improve validation

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#2132]
BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:54:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04.4 LTS
- **Kernel** (e.g. `uname -a`):
Linux srv-u28wb 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## What happened?

Recurrence of #695 which I can't reopen

There doesn't appear to be a preflight validation of the **service CIDR** net mask so that it is of a size that is acceptable to the API server.

Therefore when you put `serviceSubnet: fd00::/64` into the config you get

```
ubuntu@srv-3316t:~$ sudo more /var/log/containers/kube-apiserver-srv-3316t_kube-system_kube-apiserver-33f4880590bb8d57aa832dfb54e6b8cd6c58b67eab00e6073dbd1fed8e31b135.log 
2020-05-07T13:10:14.562713334Z stderr F Flag --insecure-port has been deprecated, This flag will be removed in a future version.
2020-05-07T13:10:14.563080628Z stderr F I0507 13:10:14.562942       1 server.go:656] external host was not specified, using 2a02:1348:17c:72b9:24:19ff:fef1:cae6
2020-05-07T13:10:14.563355454Z stderr F Error: specified --service-cluster-ip-range is too large
2020-05-07T13:10:14.564709083Z stderr F Usage:
2020-05-07T13:10:14.564723613Z stderr F   kube-apiserver [flags]

```

from the API server

**Comment by neolit123** [comment]
hello,

@NeilW 
i'm personally against adding a preflight check for this in kubeadm for now, because i'm seeing the underlying cidr / ipam space of k8s in being partially in flux and not really well documented for ipv6 (e.g. "what ranges we support for ipv6 and why is that the case")

cc @Arvinderpal @aojea 
WDYT?

related to:
https://github.com/kubernetes/kubernetes/pull/90184#issuecomment-616229838
https://github.com/kubernetes/kubernetes/pull/90288

**Comment by NeilW** [comment]
Ideally we should be calling a "Is this a valid service CIDR" from a utility package somewhere we can pull in. 

As you say, no point doing it in two places. But it'd be nice to know at some point before the api-server goes over with no warning.

**Comment by aojea** [comment]
It seems that current validations of the apiserver CIDRs are not being exported.

Validating at this point is not ideal for the reasons @neolit123 is pointing out, just check this PR trying to change the service CIDR size for the context

xref https://github.com/kubernetes/kubernetes/pull/90115

... I'm afraid that we should go with documentation until this settles :smile:

**Comment by Arvinderpal** [comment]
We also came across this problem. 
In the api-server, there is a 20-bit limit on the block size and given the way the allocator stores records in etcd, having larger blocks seems problematic: 
https://github.com/kubernetes/kubernetes/blob/04deee94a8b70a214dd52e02b6ddf5b0f505c646/cmd/kube-apiserver/app/options/validation.go#L86

I don't think this will be "fixed" anytime soon. IMO, we should document this restriction in kubeadm under `--service-cidr` and in api-server under `--service-cluster-ip-range`.

**Comment by neolit123** [comment]
> I don't think this will be "fixed" anytime soon. IMO, we should document this restriction in kubeadm under --service-cidr and in api-server under --service-cluster-ip-range.

agreed, on the flag docs update. i guess for kubeadm we also need to validate the config (`serviceSubnet`)

PRs welcome.

**Comment by agowa338** [comment]
Is there already an issue for this on the api server side? Could somebody please link the tickets?

I don't think it's good to "just add it to the docs for now" without addressing the underlaying issue (or at least creating the GitHub issue for that).

**Comment by neolit123** [comment]
> Is there already an issue for this on the api server side? Could somebody please link the tickets?
> I don't think it's good to "just add it to the docs for now" without addressing the underlaying issue (or at least creating the GitHub issue for that).

i leave this to sig-network / sig-api-machinery maintainers.

/retitle document the usage of --service-cidr and improve validation

**Comment by neolit123** [comment]
1.20 has the validation.
in terms of documentation usage we have plans to add them as part of the dual-stack efforts.

**Comment by neolit123** [comment]
this PR is for core components and needs to be amended:
https://github.com/kubernetes/kubernetes/pull/91875

the kubeadm part is done.
