### ISSUE TITLE
Probes should be configurable

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubeadm#2139]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

During the discussions in https://github.com/kubernetes/kubernetes/pull/90970 I noticed that the values for the probes currently hardcoded (e.g. timeouts, failures etc.). I believe that it's impossible to set these values to "one size fits hem all". One solution would be to set these values to some sane values like defined in https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/manifests and if these values doesn't fit a specific use-case/environment the end user could configure these values.

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by fabriziopandini** [comment]
@johscheuer in kubeadm we are using flags and config options to address the most common use cases, while the experimental kustomize patches for static pod manifests can be used for the remaining use cases.

So far, the need for changing probes values was reported only for old models of raspberry PI, so IMO, this fits under the less frequent use case category that is already covered by kustomize patches.
@neolit123 opinions?

/triage support

**Comment by neolit123** [comment]
a proposal to expose probe or other static Pod configuration in the kubeadm API was discussed multiple times in the past, with an outcome that we don't want to do that.

kubeadm already allows you do to the following:
- `--experimental-kusomize` to patch your probes.
- use kubeadm init / join phases (does not work for upgrades though).

thanks
/close
