### ISSUE TITLE
Add more information when missing config element

### ISSUE THREAD

**Issue by Seb0042** [kubernetes/kubeadm#2140]
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.18.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.18.2
- **Cloud provider or hardware configuration**: VM (Vmware)
- **OS** (e.g. from /etc/os-release): CentOS
- **Kernel** (e.g. `uname -a`): 5.6.10-1.el7.elrepo.x86_64 
- **Others**:

## What happened?
"kubeadm upgrade plan" gives an error message like this one:
invalid configuration: kind and apiVersion is mandatory information that needs to be specified
Even with --v=5 (or more) not enough information to debug which is the config in error.

## What you expected to happen?

More information. I did something like this to see that it was the kubelet-config that was missing stuff.
file: cmd/kubeadm/app/componentconfigs/configset.go
function: FetchFromCluster
Around line 164:
 if err != nil {
                    klog.Warningf("WARNING: config group misses something: %v", handler.GroupVersion.Group)
                    return err
            }

## How to reproduce it (as minimally and precisely as possible)?
Delete "kind" line for ClusterConfiguration in kubelet-config-vxxx configmap

**Comment by fabriziopandini** [comment]
/help
/kind bug
/area upgrade
/priority backlog

given that this error is due to a user misconfiguration and that AFAIL this is the first report of this type
