### ISSUE TITLE
1.19: kinder: fix failing e2e tests

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2142]
this change broke e2e tests:
https://github.com/kubernetes/kubeadm/pull/2133

https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-master
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-master/1260480951998222336/artifacts/task-01-add-kubernetes-versions-log.txt

it says that it detected containerd in the base image.
so this might be a case where we were running docker in the PR pre-submit job that verifies PRs for kinder and it did not catch the problem.

/priority critical-urgent
/kind bug
/area kinder
/assign

**Comment by neolit123** [comment]
yes so the jobs are using different base images:
https://github.com/kubernetes/kubeadm/blob/master/kinder/ci/workflows/regular-tasks.yaml#L12
https://github.com/kubernetes/kubeadm/blob/master/kinder/ci/workflows/presubmit-upgrade-master.yaml#L11

i assume `kindest/base:v20190403-1ebf15f` has docker too and that's why we didn't catch the problem.

**Comment by fabriziopandini** [comment]
So, if I got this right, regular test is failing, and this is the only test using an image based on containerd
I think that is important for us to get this working with containerd, because the adoption is growing (e.g. Cluster API)
However from the logs I can't spot the problem, because the runtime detection works well but at a certain point it fails to create a folder... Any clue on what is going on?

**Comment by neolit123** [comment]
i could not reproduce the problem locally, but will try again because i think i was testing with the image that also has docker. in that image docker is detected as the CR, but i overwrote that to containerd (as it also has containerd) to be able to test my change.

something to note is that e2e test on k/k (via kind) and k/cluster-api-* are all containerd, so kuibeadm e2e and maybe some sig-node tests are the only tests for dockershim.

**Comment by neolit123** [comment]
hi, @hasheddan and @kubernetes/ci-signal https://github.com/kubernetes/kubeadm/pull/2143 is a potential fix for an actual bug in our e2e test tools that was introduced recently.

but me and @fabriziopandini had a discussion today and we are seeing a lot more flakes for certain tasks in our jobs. something that normally takes 2 minutes, would sometimes take 10minutes+, which implies network+CPU restrictions in the Prow cluster.

we don't have much control over that, so our only immediate option is to increase the timeouts everywhere, which given a potential 5x factor can be quite tricky..

**Comment by hasheddan** [comment]
@neolit123 understood, thanks for letting us know! This might be something we need to address with test-infra and see if the infra these tests are running on needs to be adjusted

@spiffxp do you have any initial thoughts here?
