### ISSUE TITLE
Ich habe ein Problem mit dem Port. Kann mir einer von Ihnen sagen, was ich tun soll, um den Port zu ändern?

### ISSUE THREAD

**Issue by Asem-AK** [kubernetes/kubeadm#2146]
W0518 16:29:26.022649  126934 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.18.2
[preflight] Running pre-flight checks
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10259]: Port 10259 is in use
	[ERROR Port-10257]: Port 10257 is in use
	[ERROR Port-10250]: Port 10250 is in use
	[ERROR Port-2380]: Port 2380 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by neolit123** [comment]
hi, this tells me that maybe kubeadm was already run on this node before:
> [ERROR Port-10259]: Port 10259 is in use
> [ERROR Port-10257]: Port 10257 is in use
> [ERROR Port-10250]: Port 10250 is in use
> [ERROR Port-2380]: Port 2380 is in use

always run `kubeadm reset` before running `kubeadm init/join`.

given this is a support ticket i'm going to close it.
please use the support channels or #kubeadm on k8s slack:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/triage support
/close

**Comment by Asem-AK** [comment]
Jedes Mal gibt es eine neue Nachricht ?
W0519 10:33:21.113583 1286779 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock
To see the stack trace of this error execute with --v=5 or higher
