### ISSUE TITLE
Documentation: kubeadm install manual converts two dashes to one

### ISSUE THREAD

**Issue by erhan-** [kubernetes/kubeadm#2149]
In the official documentation [1] for the installation of kubeadm, there is the part where you install kubeadm on CentOS. The repo configuration excludes kubeadm and during install `--disableexcludes=kubernetes` argument is used. 

The problem is that markdown converts two dashes to one or one is missing in the command. It should be two.

You will get errors like:
```
No match for argument: kubelet                                                                                
No match for argument: kubeadm                                                                                
No match for argument: kubectl 
```

Same problem with the command `systemctl enable –now kubelet`. It should be two dashes again.

[1]: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by neolit123** [comment]
hi, this is a problem in the website markdown processor and is quite unfortunate, as i think we already got near 10 reports in various repositories.

in any case, this is now tracked here:
https://github.com/kubernetes/website/issues/20915

thanks
/close
