### ISSUE TITLE
`serve_stale` option for coredns' cache

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubeadm#2152]
## What keywords did you search in kubeadm issues before filing this one?
cache, coredns, serve_stale

## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

Choose one: BUG REPORT or FEATURE REQUEST

Can we please add `serve_stale` so that if there is intermittent kubernetes api unavailable coredns at least served the latest known ip.

Details: https://github.com/coredns/coredns/tree/master/plugin/cache#syntax

## Versions

**kubeadm version** (use `kubeadm version`): n/a

**Environment**:
- **Kubernetes version** (use `kubectl version`): n/a
- **Cloud provider or hardware configuration**: n/a
- **OS** (e.g. from /etc/os-release): n/a
- **Kernel** (e.g. `uname -a`): n/a
- **Others**: n/a

## What happened?
If you have kubernetes masters in a HA-mode, and the currently nominated master (the one that serves API requests) goes away for whatever reason - then for the duration of IP failover coredns would serve NXDOMAINs, while it would be much better that for those several seconds the stale response was served instead.

## What you expected to happen?
I expect coredns to tolerate master failovers.

**Comment by neolit123** [comment]
hello,

thank you for logging this feature request @zerkms 

> If you have kubernetes masters in a HA-mode, and the currently nominated master (the one that serves API requests) goes away for whatever reason - then for the duration of IP failover coredns would serve NXDOMAINs, while it would be much better that for those several seconds the stale response was served instead.

@chrisohaver @rajansandeep do you think this addition makes sense?

/kind feature
/priority awaiting-more-evidence

**Comment by chrisohaver** [comment]
Serving stale cache was added as an option in coredns 1.6.6. There was a bug fix affective the serve_stale option in 1.6.9.

**Comment by chrisohaver** [comment]
Ah I see. This is a request to add it to the default kubeadm coredns corefile...

**Comment by chrisohaver** [comment]
serve_stale does have a performance-optimized behavior that some might find confusing. It always responds with a stale (possibly wrong) answer if it exists in cache. After responding to the client, it refreshes the cache entry.

**Comment by zerkms** [comment]
> It always responds with a stale (possibly wrong) answer if it exists in cache

It's the case with any cache - the current config already enables the `cache` plugin and it already may serve possible wrong answers.

But indeed, having `serve_stale` would increase the window of opportunity for rarely requested dns RRs (the frequently requested ones would stay the same though).

**Comment by chrisohaver** [comment]
@zerkms, IIUC, during a failover, `serve_stale` will serve a stale response to the first client that requests it, but then immediately refresh the cache and start serving that new answer (which is NXDOMAIN according to your description).  So, I think you'd need disable negative caching for it to work the way you intend.

CoreDNS should probably be replying with SERVFAIL (or some other uncache-able response) when cache has expired and the API connection is lost - not NXDOMAIN. I'll look into that.

Another thing to consider is that adding `serve_stale` to the existing cache stanza would enable serving stale records from upstream sources as well as k8s service records.  Don't know if that might cause unforseen issues/confusion.

**Comment by zerkms** [comment]
> will serve a stale response to the first client that requests it, but then immediately refresh the cache and start serving that new answer

that would be not helpful (and to be honest - if it's the case, then `serve_stale` looks like a useless feature overall).

In any case - it was just a suggestion, would we close it now?

**Comment by chrisohaver** [comment]
> In any case - it was just a suggestion, would we close it now?

I just got done verifying that forcefully interrupting the API connection (in a non-HA system), does not cause NXDOMAIN responses.  It actually continues to reply with the last known values in the API client's informer store.  Perhaps in an HA setup this behaves differently - maybe when the API shuts down gracefully it causes the api clients to flush their stores?  In the case where you saw NXDOMAINs, was the HA failover manual/graceful, or forceful (e.g. network cut)? IMO, CoreDNS should not be returning NXDOMAINs in an HA failover scenario, so I want to see if I can fix that if it's the case.

> (and to be honest - if it's the case, then serve_stale looks like a useless feature overall)

For kubernetes, it seems redundant with the API informer store.  But overall, it's useful for serving stale records from upstream dns servers that are temporarily not reachable.

**Comment by zerkms** [comment]
You're absolutely right.

After more thorough research I have found that it's actually `kube-router` that creates problems when API is not available for "too long", not coredns.

My apologies.
