### ISSUE TITLE
Request for doc on how to setup "stacked etcd topology"

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubeadm#2155]
**Request for info:**

The link for "[stacked etcd topology](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/)" does not say how ?

It says 

> _This is the default topology in kubeadm. A local etcd member is created automatically on control plane nodes when using kubeadm init and kubeadm join --control-plane_

But I don't know how to configure the etcd with direct IP addresses of the other masters in the cluster.

Please NOTE: My Load balancer does not allow the backend members to talk to each other using VIP. The VIP is only for external clients / worker nodes. So the default "kubeadm join" for other control-plane nodes using VIP would not work.

Any help/doc/tips is very much appreciated.

**Comment by fabriziopandini** [comment]
@renukamanavalan 
Etcd automatically gets the IP of the machine where the controlplane node is created.
Howeve, as already discussed in another issue, you need a VIP acting as a controlplane endpoint that can be reached by all the nodes

**Comment by fabriziopandini** [comment]
/reopen
Sorry I messed up answering from mobile

**Comment by renukamanavalan** [comment]
THANK YOU! This is a great point and pretty helpful. Let me try.

**Comment by renukamanavalan** [comment]
Thanks Fabrizio!

Martin has provided some invaluable tips in the [other issue](https://github.com/kubernetes/kubeadm/issues/2153). So  I re-opened it.

Can you please help  review the following comments ?
[comment 1](https://github.com/kubernetes/kubeadm/issues/2153#issuecomment-635496555)
[comment 2](https://github.com/kubernetes/kubeadm/issues/2153#issuecomment-635526196)

**Comment by fabriziopandini** [comment]
@renukamanavalan if the two issues are tackling the same problem, please de-dup

**Comment by renukamanavalan** [comment]
This is the dup of https://github.com/kubernetes/kubeadm/issues/2153
