### ISSUE TITLE
remove kube-apiserver --insecure-port usage

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2156]
the flag is being removed after a long deprecation period:
https://github.com/kubernetes/kubernetes/issues/91506

in kubeadm we are passing:
`--insecure-port=0` in the api server static pod.

**the flag became a no-op in 1.20**:
https://github.com/kubernetes/kubernetes/pull/95856

it will be removed in 1.24:
https://github.com/kubernetes/kubernetes/pull/95856/files#diff-3149c6ede53e3a658bbcf11f1456f2ac955ae49db5ab66ee9e13f883488349d3R151

kubeadm can remove it earleir

related to:
https://github.com/kubernetes/kubeadm/issues/2207

NOTE

this PR might do the change in kubeadm as well:
https://github.com/kubernetes/kubernetes/pull/95522

**Comment by liggitt** [comment]
critically, kubeadm should not stop setting this flag until a kubernetes version that removes insecure serving ability... in all currently released versions, not specifying the flag accepts the default behavior of *enabling* the insecure port

**Comment by pacoxu** [comment]
/assign

```
Flag --insecure-port has been deprecated, **This flag has no effect now and will be removed in v1.24.**
Error: invalid port value 28080: only zero is allowed
```
As this flag has no effect, we can just remove it in kubeadm side in 1.22 now.

**Comment by neolit123** [comment]
@pacoxu 

i see that for the kube-apiserver the change was made in 1.20:
https://github.com/kubernetes/kubernetes/commit/cfc2b330a7027e109ac26fc6a86b68898883099e

kubeadm can deploy N and N-1 control-plane. so kubeadm 1.22  can deploy 1.22 and 1.21 kube-apiserver.
given the flag no longer has effect in 1.21, we can remove it for the kube-apiserver that kubeadm 1.22 manages.

for the KCM and KS i see the insecure flags are becoming no-op in 1.22:
https://github.com/kubernetes/kubernetes/pull/96216
https://github.com/kubernetes/kubernetes/pull/96345

thus we can delay the kubeadm change for KCM and KS to 1.23, to avoid branching:
https://github.com/kubernetes/kubeadm/issues/2207
