### ISSUE TITLE
adding control-plane master node failed discovery.bootstrapToken.token: Invalid value

### ISSUE THREAD

**Issue by SergeyMuha** [kubernetes/kubeadm#2158]
## What keywords did you search in kubeadm issues before filing this one?

discovery.bootstrapToken.token: Invalid value

## Versions

**kubeadm version** (use `kubeadm version`):
 kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:54:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):ubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
vsphere
- **OS** (e.g. from /etc/os-release):
CentOS Linux release 7.8.2003 (Core)

- **Kernel** (e.g. `uname -a`):
Linux k8s-master 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
I am trying to connect second master to already initialized master
sudo kubeadm join  /etc/kubernetes/kubeadminitmaster.yaml --control-plane --discovery-token-unsafe-skip-ca-verification
[discovery.bootstrapToken.token: Invalid value: "": the bootstrap token is invalid, discovery.bootstrapToken.apiServerEndpoint: Invalid value: "/etc/kubernetes/kubeadminitmaster.yaml": address /etc/kubernetes/kubeadminitmaster.yaml: missing port in address, discovery.tlsBootstrapToken: Invalid value: "": the bootstrap token is invalid]
To see the stack trace of this error execute with --v=5 or higher

cat /etc/kubernetes/kubeadminitmaster.yaml 
apiVersion: kubeadm.k8s.io/v1beta2
discoveryFile: discovery.yaml
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.100.3.100:6443
    token: bootstrap-token-xxxx
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: bootstrap-token-xxx
kind: JoinConfiguration
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s-master
  taints: null
  kubeletExtraArgs:
    cloud-provider: vsphere
UnsafeSkipCAVerification: true

cat discovery.yaml 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: cert=
    server: https://ip:6443
  name: ""
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null

## What you expected to happen?
Second master should join the cluster

**Comment by neolit123** [comment]
hello, your JoinConfiguration is not correct.

try this:
```yaml
# myconfig.yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
controlPlane: {}
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.100.3.100:6443
    token: bootstrap-token-xxxx
    unsafeSkipCAVerification: true
  timeout: 5m0s
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s-master
  taints: null
  kubeletExtraArgs:
    cloud-provider: vsphere
```

with just `sudo kubeadm join --config myconfig.yaml`

notes:
- the documentation is here:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#JoinConfiguration
- passing both a discovery file and a bootstrap token in `JoinConfiguration` doesn't make sense
- you seem to be passing `unsafeSkipCAVerification` in a couple of places in the config and also as a flag.
- adding `tlsBootstrapToken` is not needed if you have `bootstrapToken.token` this is already explained in the godocs.
- `unsafeSkipCAVerification: true` is obviously less secure than passing
```
...
  bootstrapToken:
    caCertHashes:
    - somehash
```
docs are here:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#token-based-discovery-with-ca-pinning
- `controlPlane: {}` should act like a replacement for the `--control-plane` flag.
- `name: k8s-master` <- make sure a node with that name doesn't exist already.
- `  taints: null` this will allow workloads to schedule on this node, so remove this if you don't want it.

let me know if you have more questions.
/triage support

**Comment by SergeyMuha** [comment]
I regenerated certs with #sudo kubeadm init phase upload-certs --upload-certs
on first master vm
then
[sergey@k8s-master istio-1.6.0]$ kubectl describe secrets -n kube-system kubeadm-certs
Name:         kubeadm-certs
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
front-proxy-ca.crt:  1066 bytes
front-proxy-ca.key:  1703 bytes
sa.key:              1707 bytes
sa.pub:              479 bytes
ca.crt:              1053 bytes
ca.key:              1707 bytes
etcd-ca.crt:         1045 bytes
etcd-ca.key:         1703 bytes
 
Here is config.file . token is the same as I used for --token flag. It is correct.
[sergey@k8s-masters-0 ~]$ cat /etc/kubernetes/kubeadminitmaster.yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
controlPlane: {}
discovery:
  bootstrapToken:
    apiServerEndpoint: 10.100.3.100:6443
    token: y7yxxxxxx
    unsafeSkipCAVerification: true
  timeout: 5m0s
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  kubeletExtraArgs:
    cloud-config: /etc/kubernetes/vsphere.conf
    cloud-provider: vsphere
[sergey@k8s-masters-0 ~]$ sudo kubeadm join --config /etc/kubernetes/kubeadminitmaster.yaml 
W0601 07:55:38.907539    9797 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
error execution phase preflight: 
One or more conditions for hosting a new control plane instance is not satisfied.

failure loading certificate for CA: couldn't load the certificate file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory

Please ensure that:
* The cluster has a stable controlPlaneEndpoint address.
* The certificates that must be shared among control plane instances are provided.


To see the stack trace of this error execute with --v=5 or higher
.
So why it can't download certs from first master.
When I used 
sudo kubeadm join 10.100.3.100:6443 --token y7yxxxxxx   --control-plane --certificate-key $(cat certificate.key) --discovery-token-unsafe-skip-ca-verification 
Master joined successfully.

**Comment by neolit123** [comment]
i'm going to close this ticket until we config there is a kubeadm bug.
we rarely provide support in this issue tracker.
/close

> So why it can't download certs from first master.
> When I used sudo kubeadm join 10.100.3.100:6443 --token y7yxxxxxx --control-plane --certificate-key $(cat certificate.key) --discovery-token-unsafe-skip-ca-verification
> Master joined successfully.

the idea of `--certificate-key` is to provide a certificate key that is used to copy certificates from the primary control-plane.

so you do `kubeadm init ... --upload-certs` on the first control-plane and then `kubeadm join .... --control-plane --certificate-key <key>` on the secondary CP nodes.

please read the kubeadm HA docs + godocs:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#stacked-control-plane-and-etcd-nodes

https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#JoinConfiguration
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#JoinControlPlane

your config file needs to be changed to have the cert key:
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
...
controlPlane:
  certificateKey: <key-here>
...
```

**Comment by SergeyMuha** [comment]
Thanks. Now it is working.

**Comment by RyadMara** [comment]
> Thanks. Now it is working.

i know it's been 4 years, but do you remember how you solve it ? i have the same issue in my cluster can't add a new master node
