### ISSUE TITLE
update kubeadm-kubelet documentation to reflect CNI package change

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2160]
the kubernetes-cni contents (plugins) will now be bundled as part of the kubelet package:
https://github.com/kubernetes/release/pull/1330
the kubernetes-cni package will be removed.

the action item here is to remove:
> kubernetes-cni

from this list:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#kubernetes-binaries-and-package-contents

and update the item:
> kubelet

to have the description:
> Installs the kubelet binary in /usr/bin and CNI binaries in /opt/cni/bin.

file location:
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md

/priority important-longterm
/kind documentation
/help
/good-first-issue

**Comment by justaugustus** [comment]
FYI, changes should only be staged, and not merged until after the next set of patch releases goes out: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md
