### ISSUE TITLE
Adding KubeVirt as an addon

### ISSUE THREAD

**Issue by ashleyschuett** [kubernetes/kubeadm#2161]
## FEATURE REQUEST

Allow users to easily provision a cluster with KubeVirt enabled. This would allow users provisioning there clusters with kubeadm who need to run VMs in containers and easy way to set up their cluster and be able to run their applications from day 1. 

example: 
```
Kind: InitConfiguration
.....
addons:
   KubeVirt: true
```

The default value would be `false`. 

If the user sets the value to true, the plugin would then deploy the manifest for the kubevirt operator, and then kubevirt CR to deploy the kubevirt components. This would be similar to how CoreDNS is being deployed when enabled.

**Comment by fabriziopandini** [comment]
IMO this falls in the scope of https://github.com/kubernetes/enhancements/pull/1308 (and hopefully it can give additional support to this activity)

**Comment by ashleyschuett** [comment]
@fabiand this seems like the direction we where thinking?

@fabriziopandini is there anyway I can help assist with the KEP or getting this feature in?

**Comment by fabiand** [comment]
@ashleyschuett Yup, I think that's really everything that is needed.

**Comment by neolit123** [comment]
hello, yes we have plans to support more configurable addons, but this is in scope of the cluster-addons  sub-project of sig-cluster-lifecycle. our general idea is that the existing addons such as kube-proxy, coredns should move outside of kubeadm and kubeadm should not hardcode more addons, instead they will be maintained by another tool/library.

if you'd like please log this ticket in:
https://github.com/kubernetes-sigs/cluster-addons

which implies that a potential kubevirt addon should create an operator that maintains its installation lifecycle - install / upgrade.

thank you.

**Comment by neolit123** [comment]
also as @fabriziopandini mentioned the cluster-addon sub-project needs more participants / folks to help with the work.
