### ISSUE TITLE
Cannot create cluster networking: Flannel. ------------  Flannel pod --- Status: CrashLoopBackOff 

### ISSUE THREAD

**Issue by pmbibe** [kubernetes/kubeadm#2164]
Hi all, I am trying to create multiple master node by using external etcd cluster (not manage by k8s). But when I apply Flannel network on my cluster, it failed.

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:49:29Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- **Kernel** (e.g. `uname -a`):
Linux node-master-1 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Log files:

1. kubectl logs kube-proxy-mlb7j -n kube-system

![image](https://user-images.githubusercontent.com/53257014/83847381-5424ec80-a736-11ea-8c34-9b179c274373.png)

2.  kubectl logs kube-apiserver-node-master-1 -n kube-system

![image](https://user-images.githubusercontent.com/53257014/83847490-8c2c2f80-a736-11ea-9833-e627d4761dca.png)

3. kubectl logs kube-controller-manager-node-master-1 -n kube-system

![image](https://user-images.githubusercontent.com/53257014/83847573-b382fc80-a736-11ea-8ffc-257235c0034c.png)

4 .kubectl logs kube-flannel-ds-amd64-vdnjr -n kube-system
![image](https://user-images.githubusercontent.com/53257014/83847679-d9a89c80-a736-11ea-821d-d96a1ff8f8e6.png)

**Comment by neolit123** [comment]
the kubeadm team no longer endorses flannel as a CNI plugin because it has too many bugs, but you might be able to get it to work. instead you can try Calico, Cilium, WeaveNet.

also please use the support channels instead of this issue tracker for help and support questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

also use the k8s slack #kubeadm channel.

thank you
/triage support
/close
