### ISSUE TITLE
can't get the controlPlaneEndPoint info

### ISSUE THREAD

**Issue by lovexiongmao** [kubernetes/kubeadm#2167]
BUG REPORT

## Versions
kubeadm 1.18

**Environment**:
- **Kubernetes version** (use `kubectl version`):
kubernetes  1.18
- **Cloud provider or hardware configuration**:
3U4G 
- **OS** (e.g. from /etc/os-release):
centos 7
- **Kernel** (e.g. `uname -a`):
3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:
my cluster is  setup on bare metal.

## What happened?
I config the kubeadm-config.yaml to setup a HA cluster.   so I add controlPlaneEndPoint: master01ip:6443 to the kubeadm-config.yaml.  And execute "kubeadm init --config=kubeadm-config.yaml --upload-certs |tee kubeadm-init.log"  command. 
But when the command is done, I can't find the controlPlaneEndPoint info in the configmap of kubeadm by execute "kubectl describe cm kubeadm-config -n kube-system"
Also i can't add a new master to the cluster by the command `kubeadm join 172.16.5.181:6443 --token abcdef.0123456789abcdef --discovery-token-ca-cert-hash sha256:4e8b505b63bb06a474e226ced59f762442dbd5a454904974eb8ecc5ed8e52466 --control-plane --certificate-key 357624cba92341cb5350e299dd97f2b379488c9ed352a5249d45cd481a73b0b6 --v=9
`  I get the error like this "unable to add a new control plane instance a cluster that doesn't have a stable controoint address"
## What you expected to happen?
I expected I can see the controlPlaneEndPoint info in the configmap of kubeadm. And I hope I can add new master to the cluster successly.

## How to reproduce it (as minimally and precisely as possible)?
just follow the official documentation

## Anything else we need to know?
I installed it offline
in the Attached  the kubeadm-config.txt is my kubeadm init file. and the kubeadm-configMap.txt is 
 obtained by command "kubectl describe cm kubeadm-config -n kube-system"
[kubeadm-config.txt](https://github.com/kubernetes/kubeadm/files/4741606/kubeadm-config.txt)
[kubeadm-configMap.txt](https://github.com/kubernetes/kubeadm/files/4741607/kubeadm-configMap.txt)

**Comment by neolit123** [comment]
hi, are you sure you didn't delete the field `controlPlaneEndPoint` from the configmap?
as you can see in the kubeadm source code it takes the ClusterConfiguration as YAML and writes to in the config map:
https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/cmd/kubeadm/app/phases/uploadconfig/uploadconfig.go#L105

/priority awaiting-more-evidence

**Comment by lovexiongmao** [comment]
yes，i'm pretty sure. does somewhere has log the see what going on when it write configuration to the configmap. Maybe is there some reason to make it skip the field

**Comment by neolit123** [comment]
no, kubeadm just writes the whole ClusterConfiguration.
are you sure you are using a --config file that has the field?

**Comment by lovexiongmao** [comment]
@neolit123  yes, you can see that by the attached file.  by the way, at the firstly, when I use the command "kubeadm config print init-defaults > kubeadm-config.yaml"  to generate the kubeadm-config.yaml. there is no `controlPlaneEndPoint` in the file. I added this field manually later.

**Comment by neolit123** [comment]
@lovexiongmao 

>  when I use the command "kubeadm config print init-defaults > kubeadm-config.yaml" to generate the kubeadm-config.yaml. there is no controlPlaneEndPoint in the file. I added this field manually later.

that is because the `print init-defaults` commands prints default values and the default value for the control plane endpoint is `""`.

i tried reproducing the bug:

config:
```
# config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.18.2
controlPlaneEndpoint: localhost:6443
```

command:
```
kubeadm init ... --config=config.yaml
```

```
kubectl get cm kubeadm-config -n kube-system -o yaml | grep controlPlaneEndpoint -C 2
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: localhost:6443
    controllerManager: {}
    dns:
```

as you can see `controlPlaneEndpoint: localhost:6443` is present and i don't see a reason why it should not be there.

please verify your setup and let me know if  you have more questions.

thanks.
/close

**Comment by lovexiongmao** [comment]
@neolit123  I uploaded an operate [video ](https://www.youtube.com/watch?v=4GGpf9Tfacs)to YouTube, and in this video you can see that there is really  no controlPlaneEndpoint field.

**Comment by neolit123** [comment]
@lovexiongmao thanks for the video. i noticed that you are using `controlPlaneEndPoint` and not `controlPlaneEndpoint`, this should fix the problem for you.,

we used to have warnings printed to the user if one of the YAML fields is unknown / malformed but it seems we have a bug that these warnings are no longer printed.

i will log a separate ticket for that.

**Comment by neolit123** [comment]
so the issue is already logged and it's in the yaml library that we use:
https://github.com/kubernetes-sigs/yaml/issues/15

**Comment by lovexiongmao** [comment]
@neolit123 thank you very much, it work now!
