### ISSUE TITLE
kinder: support testing of custom image repositories

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#2171]
As of today when kinder loads images uses `ctr --namespace=k8s.io images import ...`.
We should investigate if `--namespace=k8s.io` can be safely removed so we can then move forward in using kinder for testing kubeadm image repository flags

fabriziopandini :
> In the long term I would like to support testing kubeadm with a custom image repository, but this is not a priority and I'm not sure this can be easily achieved with the current test infrastructure, so feel free to close

**Comment by neolit123** [comment]
@fabriziopandini 

> We should investigate if --namespace=k8s.io can be safely removed so we can then move forward in using kinder for testing kubeadm image repository flags

could you elaborate on what do you mean on testing kubeadm image repository flags?
it seems to be recommended to namespace the contrainerd images.

**Comment by fabriziopandini** [comment]
In the long term I would like to support testing kubeadm with a custom image repository, but this is not a priority and I'm not sure this can be easily achieved with the current test infrastructure, so feel free to close

**Comment by neolit123** [comment]
ok understood, i will update the title to scope more.

**Comment by neolit123** [comment]
> We should investigate if --namespace=k8s.io can be safely removed

kind is also importing images with containerd in the k8s.io namespace.
it seems like standard naming at this point.

as far as testing custom image repositories, i think kubeadm unit tests + higher level tools provide sufficient testing.
the usage of k8s.gcr.io in kubeadm ensures that feeding *a repository* URL works.

please re-open if needed.
