### ISSUE TITLE
kinder: containerd nodes prepull etcd and extra images

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2179]
@fabriziopandini 
https://github.com/kubernetes/kubeadm/pull/2168

it seems the above PR was a regression in terms of the the image prepull as etcd, coredns, pause are now again pulned N times for N nodes + N times for upgrade.

overall i did not understood the benefit of the PR, other than reducing the complexity on runtime for containerd.

https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-master
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-master/1270862973149122560/build-log.txt

```
I0610 23:44:53.489844     187 checks.go:845] pulling k8s.gcr.io/pause:3.2
I0610 23:44:53.781365     187 checks.go:845] pulling k8s.gcr.io/etcd:3.4.7-0
I0610 23:45:00.507048     187 checks.go:845] pulling k8s.gcr.io/coredns:1.6.7
```

i think we should fix this and not pull this extra Gigabyte+ of data in the kubeadm jobs...

/kind bug
/area kinder
/priority important-longterm
/assign @fabriziopandini

**Comment by fabriziopandini** [comment]
I will check why this is happening. 
But the code for fetching extra image was not changed by this PR...

However, I see several benefits in having preloaded images in the node variant, increasing the node startup speed for each node we are spinning up as first, maintaining a minimal consistency with kind as the second.

**Comment by neolit123** [comment]
> But the code for fetching extra image was not changed by this PR...

i remember the etcd prepull worked after my changes for both docker and containerd, but i could have messed something up.

> However, I see several benefits in having preloaded images in the node variant, increasing the node startup speed for each node we are spinning up as first, maintaining a minimal consistency with kind as the second.

this is good for local testing too...the Prow / GCP internet is very fast, but i get timeouts most of the time if i have to test a full workflow locally due to the etcd pull N times.

> And, as you probably remember, the decision of drifting away from the same behavior was due to a lack of understanding of the underlying issue, not by a design problem in the behavior itself.

true.
