### ISSUE TITLE
Kubernetes Apiserver status repeatedly faling error

### ISSUE THREAD

**Issue by vasanthakumars98** [kubernetes/kubeadm#2180]
vasanthakumar@vasanth:~/Desktop/kubernetes/smef$ minikube status
E0611 15:28:09.877660    6252 status.go:256] Error apiserver status: https://192.168.99.102:8443/healthz returned error 403:
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"forbidden: User \"system:anonymous\" cannot get path \"/healthz\"","reason":"Forbidden","details":{},"code":403}

minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Error
kubeconfig: Configured

vasanthakumar@vasanth:~/Desktop/kubernetes/smef$ minikube status
E0611 15:28:29.149931    6304 status.go:256] Error apiserver status: https://192.168.99.102:8443/healthz returned error 500:
[+]ping ok
[+]log ok
[-]etcd failed: reason withheld
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok
[-]poststarthook/bootstrap-controller failed: reason withheld
[-]poststarthook/rbac/bootstrap-roles failed: reason withheld
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: reason withheld
[+]poststarthook/start-cluster-authentication-info-controller ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[+]autoregister-completion ok
[+]poststarthook/apiservice-openapi-controller ok
healthz check failed

minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Error
kubeconfig: Configured

vasanthakumar@vasanth:~/Desktop/kubernetes/smef$ minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Stopped
kubeconfig: Configured

**Comment by neolit123** [comment]
>  minikube status

please use the minikube issue tracker
https://github.com/kubernetes/minikube

or the k8s support channels for this.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
