### ISSUE TITLE
Kubeadm HA control plane guide - missing keepalived health check script file

### ISSUE THREAD

**Issue by mstoetzer** [kubernetes/kubeadm#2189]
## What keywords did you search in kubeadm issues before filing this one?

- `kubeadm check_apiserver.sh missing` 
- `kubeadm check_apiserver.sh`
- `kubeadm keepalived healthcheck` 

## (not really a) BUG REPORT

Please see: [kubeadm docs - ha-considerations.md](https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md#keepalived-configuration)

The code snipped for the keepalived configuration contains a path of the health check script `/etc/keepalived/check_apiserver.sh`.

```sh
// ...
vrrp_script check_apiserver {
  script "/etc/keepalived/check_apiserver.sh"
// ...
```

Should the code of this file be in this documentation?

Thank you

**Comment by neolit123** [comment]
@mbert hello, do you think this is something we should include in the guide?

**Comment by mbert** [comment]
> @mbert hello, do you think this is something we should include in the guide?

Yes, I think so. So it looks like I forgot including this? I'll prepare another PR.

**Comment by mbert** [comment]
https://github.com/kubernetes/kubeadm/pull/2192

**Comment by mstoetzer** [comment]
Thank you for the fast fix!
