### ISSUE TITLE
kubeadm e2e kubectl bug

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#219]
While trying to fix our CI kubeadm e2e test, I found an odd, subtle bug I wanted to document (and track the correct fix for).

The symptoms we were seeing in the e2e runs were:

    W0331 07:07:19.147] +(./phase3/do:17): deploy(): kubectl apply -f ./.tmp/
    I0331 07:07:19.247] .tmp/weave-net-cluster-role-binding.json
    I0331 07:07:19.248] .tmp/weave-net-cluster-role.json
    I0331 07:07:19.248] .tmp/weave-net-daemon-set.json
    I0331 07:07:19.248] .tmp/weave-net-service-account.json
    W0331 07:07:19.412] error validating ".tmp/weave-net-cluster-role-binding.json": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
    W0331 07:07:19.412] error validating ".tmp/weave-net-cluster-role.json": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
    W0331 07:07:19.412] error validating ".tmp/weave-net-daemon-set.json": error validating data: found invalid field tolerations for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
    W0331 07:07:19.413] the namespace from the provided object "kube-system" does not match the namespace "default". You must pass '--namespace=kube-system' to perform this operation.

Originally, I suspected that the version of kubectl used was too old to support the new RBAC API, but I verified that the image was using kubectl 1.6.0-beta.4. What's more, I wasn't able to replicate the issue locally, even when using the same Docker container. The root cause actually turned out to be the service account that prow uses, coupled with other behavior:

- The current kubeadm e2e test uses kubernetes-anywhere to provision GCE instances running Ubuntu to approximate the environment we expect users to run in.
- In order for our Conformance tests to run, they need a kubeconfig file to be able to connect to the cluster. Kubeadm generates this file on the master, so it needs to be pulled back to the client running the e2e tests after initialization is complete.
- The file (`/etc/kubernetes/admin.conf`) is owned by root and only readable by root, by design. The Ubuntu VM image enforces that you cannot ssh in using the root account.
- To overcome this, we execute `gcloud compute ssh <master> --command "sudo cat /etc/kubernetes/admin.conf"`. This lets us log in as a generic user who has passwordless sudo permissions and output the target file. Another possible solution is to first chmod the file to be world-readable so that we can use `gcloud compute copy-files <master>:/etc/kubernetes/admin.conf .`, but that would compromise security.
- We don't specify a username during the ssh command because kubernetes-anywhere allows you to specify the VM image you want to use, and they likely have different default accounts setup for you to use.
- gcloud has undocumented behavior during ssh when you don't specify a username. The documentation claims that it will use $USER, but looking at the source code, if you're using a service account, it will actually try to look up the correct username to use from the service account information. In all of my local testing, even though my Docker container was running as root, gcloud was using a non-root username when sshing into the master, and the Ubuntu image was translating the unknown user into "ubuntu."
- In prow, the service account used causes `gcloud compute ssh` to use root@ when sshing into a remote instance, which is a recognized user. When Ubuntu detects that the root user is trying to log in, it simply prints an error message that logging in as root is forbidden, and that you should log in as "ubuntu" instead, and exits with a return value of 0.
  - This means that our `gcloud compute ssh` command was exiting cleanly, without error, but actually writing this error message to our kubeconfig file instead of the real file contents.
- During phase3, kubernetes-anywhere uses this kubeconfig file to try to install addons. Without any error, kubectl decides to ignore this invalid kubeconfig file and instead fall back to in-cluster configuration (which is the GKE cluster that prow itself is running on).
  - This means that phase3 actually ends up trying to install addons on prow's cluster instead of the newly provisioned e2e cluster, which explains the errors that we see because the version of Kubernetes is a bit old (1.4, I believe).

Right now, we have a [quick fix](https://github.com/kubernetes/test-infra/commit/df83f5462598fc6246f9b533ac54a4820fc6a298) that should be replaced.

Since our e2es always use an Ubuntu-based image for testing, the quick fix forces the gcloud ssh command to specify `ubuntu@<master>` to resolve the issue of logging in as root.

**Comment by pipejakob** [comment]
One suggestion from @mikedanese  was to always force logging in as `kubernetes@<master>` instead of leaving the username blank or forcing `ubuntu@<master>`. The Ubuntu image seems to detect when you're logging in as any unrecognized user and decides to log you in as `ubuntu` instead. Since the kubeadm implementation of phase2 in kubernetes-anywhere only supports `.deb`s, it's currently only expected to work on Debian/Ubuntu images. If I can verify that logging in as `kubernetes@<master>` works for a recent Debian image as well, that seems like a decent fix.

Otherwise, we may have to bloat the kubernetes-anywhere `.config` file with yet another value to specify what the login user should be, or maintain a map of known images => usernames.

**Comment by luxas** [comment]
@pipejakob Can you provide the current status of this issue?
I guess it's fixed but...

**Comment by luxas** [comment]
ping @pipejakob

**Comment by luxas** [comment]
friendly ping @pipejakob ;)
Can I close this?

**Comment by pipejakob** [comment]
Yes. It's patched in my fork (which is used by the e2e tests now), but not upstream. I'll still reference this issue when patching upstream, but this isn't actively affecting our e2es now. Closing.
