### ISSUE TITLE
kubeadm:need a way to config the memory of coredns

### ISSUE THREAD

**Issue by zgfh** [kubernetes/kubeadm#2191]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): 1.15.4

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**: k8s: 1.15.4
- **OS** (e.g. from /etc/os-release): centos
- **Kernel** (e.g. `uname -a`): 3.10
- **Others**: k8s: 1.15.4

## What happened?
in my cluster ,coredns have be oomkilled many times
k8s: 1.15.4
pod: 1000
node: 10

for now, I change the memory limit by `kubectl -n kube-system edit deployments coredns`
but if there is a way to change coredns memory, it will be good for me to install a new cluseter

## Anything else we need to know?

I find there is a env dns_memory_limit :https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/coredns/coredns.yaml.in#L125
but kubeadm hard code to 170Mi
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L59

**Comment by neolit123** [comment]
hello,
we have no plans to make the coredns Deployment object patchable / customizable on that level for the time being. also there are plans to move the coredns logic outside of kubeadm so that it's managed by an operator.

for now you have to use `kubectl edit/patch`.

thanks
/close

**Comment by zgfh** [comment]
thanks
