### ISSUE TITLE
A broken when  kubadm config 

### ISSUE THREAD

**Issue by xuxiaowei0512** [kubernetes/kubeadm#2194]
root@ubuntu20:/home/ubuntu# kubeadm config --v=5
missing subcommand; "config" is not meant to be run on its own
k8s.io/kubernetes/cmd/kubeadm/app/cmd/util.SubCmdRunE.func1
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/util/cmdutil.go:38
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
root@ubuntu20:/home/ubuntu#

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:11Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:
root@ubuntu20:/home/ubuntu# kubelet --version
Kubernetes v1.18.4
root@ubuntu20:/home/ubuntu#
root@ubuntu20:/home/ubuntu# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@ubuntu20:/home/ubuntu# uname -a
Linux ubuntu20 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu20:/home/ubuntu#

## What happened?
root@ubuntu20:/home/ubuntu# kubeadm config
missing subcommand; "config" is not meant to be run on its own
To see the stack trace of this error execute with --v=5 or higher
root@ubuntu20:/home/ubuntu#

## What you expected to happen?

I

**Comment by neolit123** [comment]
> kubeadm config
> missing subcommand; "config" is not meant to be run on its own

when you add `--v=5` it prints a backtrace.

you should use `kubeadm config` subcommands like `kubeadm config images list`.
`kubeadm config` alone would give you the error.

/triage support
/close
