### ISSUE TITLE
Create own token using command line

### ISSUE THREAD

**Issue by gudipudipradeep** [kubernetes/kubeadm#2196]
is it possible to configure our own token using kubeadm token create:
           kubeadm token create --token xxxx.zzzzzzzz --print-join-command
           or 
            any other way to create inside the "etcd document database" with token
            etcdctl put token xxxx.zzzzzzzze

Where this token will be saved inside the cluster..?

**Comment by neolit123** [comment]
/triage support

you can use something like:
`kubeadm token create 8ey2cb.nrqrw0t7t7qmd43k`

which will create the token `8ey2cb.nrqrw0t7t7qmd43k` for you.
the token format must match `\\A([a-z0-9]{6})\\.([a-z0-9]{16})\\z`

you can also generate a token with:
`kubeadm token generate`

> any other way to create inside the "etcd document database" with token
etcdctl put token xxxx.zzzzzzzze

kubeadm tokens are not the same as etcd tokens.
the kubeadm tokens are used for bootstrapping nodes.

hope this helps.
/close
