### ISSUE TITLE
etcd metrics endpoint should listen on advertise address

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubeadm#2199]
## What keywords did you search in kubeadm issues before filing this one?

`etcd`, `etcd metrics`

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

I would propose to change the current default for the etcd `--listen-metrics-urls` parameter to use the advertise address instead of the local address. The local address is not really useful if you want to monitor etcd with Prometheus since Prometheus is not able to pull the metrics from the endpoint. 

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):

```bash
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:

`libvirt`
- **OS** (e.g. from /etc/os-release):

`20.04 LTS (Focal Fossa)`

- **Kernel** (e.g. `uname -a`):

`Linux master 5.4.0-1011-kvm #11-Ubuntu SMP Mon May 11 14:03:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- **Others**:

## What happened?

The metrics endpoint of etcd was not reachable via the node IP address.

## What you expected to happen?

I would expect that the metrics endpoint is available over the node IP address so that Prometheus is able to collect the metrics.

## How to reproduce it (as minimally and precisely as possible)?

Just use kubeadm and spwan a minimal cluster.

**Comment by neolit123** [comment]
hello, @johscheuer 

> etcd metrics endpoint should listen on advertise address

i disagree with this assessment, at least not by default.
by doing that your are exposing an unsecure (HTTP) etcd metrics endpoint on a public IP address.

we closed a similar PR recently:
https://github.com/kubernetes/kubernetes/pull/90954
please have a look at the comments there.

instead of doing that by default in kubeadm, you should edit/patch your etcd.yaml.

**Comment by neolit123** [comment]
in particular this comment: https://github.com/kubernetes/kubernetes/pull/90954#discussion_r422998704
explains that the metrics are already exposed publicly, but require HTTPS.

**Comment by johscheuer** [comment]
Thanks for the pointe somehow I didn't find this pr in my search. Sorry for the inconvenience.

**Comment by neolit123** [comment]
no worries.
