### ISSUE TITLE
rename "node-role.kubernetes.io/master"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2200]
KEP: http://git.k8s.io/enhancements/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
https://github.com/kubernetes/enhancements/issues/2067

```
## Design Details

The process will be broken into multiple stages:
- First - 1.20
- Second - Minimum deprecation period for GA features is 1 year.
Estimated 1.24, but may depend on user feedback.
- Third - one release after Second
- Fourth - one release after Third

### Renaming the "node-role.kubernetes.io/master" Node label

First stage:
- Introduce the "node-role.kubernetes.io/control-plane" label in parallel to
the "master" label.
- Announce to users that they should adapt to use the new label.

Second stage:
- Remove the "master" label and announce it to the users.

### Renaming the "node-role.kubernetes.io/master" Node taint

First stage:
- Introduce the "node-role.kubernetes.io/control-plane:NoSchedule" toleration
in the CoreDNS Deployment of kubeadm.
- Announce to users that they should do that same for their workloads.

Second stage:
- Add the "node-role.kubernetes.io/control-plane:NoSchedule" taint to Nodes.

Third stage:
- Remove the "node-role.kubernetes.io/master:NoSchedule" taint from Nodes.

Fourth stage:
- Remove the "node-role.kubernetes.io/master:NoSchedule" toleration in the CoreDNS
Deployment of kubeadm
- Announce to users that they should remove tolerations for the "master" taint in
their workloads.
```

---------

1.20

- [x] KEP draft:
https://docs.google.com/document/d/1kPs_zFconMU83LCOfBr_xKXfghn3y9VLLrTUSlCAf4s/edit#
- [x] write KEP / create issue in k/enhancements
http://git.k8s.io/enhancements/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
https://github.com/kubernetes/enhancements/issues/2067
- [x] implement changes for 1.20 (deprecate the master label / taint):
https://github.com/kubernetes/kubernetes/pull/95382
- [x] docs update:
https://github.com/kubernetes/website/pull/24907
- [x] ADR for "master"->"control-plane":
https://github.com/kubernetes/community/pull/5243
------

1.24

- [x] Update KEP
https://github.com/kubernetes/enhancements/pull/3119
- [x] kind / kinder PRs:
https://github.com/kubernetes/kubeadm/pull/2638
https://github.com/kubernetes-sigs/kind/pull/2595
- [x] k/k PRs
https://github.com/kubernetes/kubernetes/pull/107533
https://github.com/kubernetes/kubernetes/pull/108170
https://github.com/kubernetes/kubernetes/pull/108336
- [x] k/website PRs
https://github.com/kubernetes/website/pull/31391
- [x] fix retaint bug:
https://github.com/kubernetes/kubernetes/pull/109841
------

1.25
- [x] fix retaint bug:
https://github.com/kubernetes/kubernetes/pull/109840
- [x] update KEP:
https://github.com/kubernetes/enhancements/pull/3313
- [x] k/k cleanup PRs:
https://github.com/kubernetes/kubernetes/pull/110095
https://github.com/kubernetes/kubernetes/pull/110111
https://github.com/kubernetes/kubernetes/pull/110137
- [x] patch k-sigs/kind:
https://github.com/kubernetes-sigs/kind/pull/2777
- [x] patch k/website (e.g. [this](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation) and other places?)
https://github.com/kubernetes/website/pull/33834
https://github.com/kubernetes/website/issues/33835

1.26
- [x] KEP update:
https://github.com/kubernetes/enhancements/pull/3477
- [x] cleanup k/k
https://github.com/kubernetes/kubernetes/pull/112008
TODO

old issue description text:
------

in the kubeadm meeting of 24.06.2020 we discussed the rename of the kubeadm "master" taint/label:
https://docs.google.com/document/d/1ONcoy8bOw8SWPUwXxnKeRZST3lnUxYpUv4Y6466h9Ek/edit#
https://youtu.be/tycqyzrkUr8

a new k8s working group is being created to oversee the removal of offensive language in k8s. kubeadm as part of the ecosystem must comply:
https://github.com/kubernetes/community/pull/4884

remaining usage of "master" and other offensive language in kubeadm:
- only usage of "master" can be found in a few places
- there is no other offensive language, such as "slave", "white/black list", or at least we are not aware of any (depends what we end up disallowing too)
- in the past, we did a big purge of "master" from code and k8s.io website docs, and replaced it with "control-plane", but a few usages remain in the code.
- kubeadm labels a control-plane Node with "node-role.kubernetes.io/master".
- kubeadm taints a control-plane Node with key "node-role.kubernetes.io/master" and effect "NoSchedule".
- kubeadm adds a toleration for its CoreDNS Deployment for the "node-role.kubernetes.io/master" taint.
- kubeadm code comments still call the label/taint as "the master label/taint".

timeline (TO BE DEFINED):
- likely no actions for 1.19.
- likely a GA deprecation policy will take action, which means that the removal will be executed over 1 year (or 3 releases).
- the exact order of tasks and how the replacement will happen is TBD, but we have ideas of how to minimize the breakage.
- a kubeadm level KEP will be required that will likely merge as "implementable" for 1.20.
- once the KEP is in place we will start executing on the tasks and notifying consumers on all possible channels.

replacement name (TO BE DEFINED):
- we have at least a couple of proposals, but we are leaning towards "Control Plane" naming.

action items before the work starts:
- [x] ACTION ITEM(@neolit123): join the SIG Cluster Lifecycle meeting and discuss:
  - usage of offensive language in SIG projects - all sub-projects have been notified.
  - discuss naming (control-plane vs ???) - no objections to `control-plane`.
  - discuss timeline for kubeadm and other projects - will vary between projects. still depends on the WG Naming demands, but we are hoping for a GA deprecation policy.
- [x] ACTION ITEM(@neolit123): discuss the following with WG naming:
  - usages of offensive language in kubeadm (+other SIG projects?)
  - preferred timeline?
  - naming?
  - communication channels for user complains?

-----

please subscribe to this ticket for updates.

**Comment by sftim** [comment]
How about adding the _new_ label to https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/ ?

**Comment by neolit123** [comment]
not long ago these labels were made deployer specific and we cannot add them as part of the core API docs:
https://github.com/kubernetes/enhancements/blob/143c03f0af52c47eab48ec54144dab6bcc86c98d/keps/sig-architecture/2019-07-16-node-role-label-use.md#use-of-node-rolekubernetesio-labels

**Comment by sftim** [comment]
The website documents more than the core API, and the point of the language seems like a good point to reconsider what's documented.

As I understand it, that KEP strongly advocated for writing sample manifests and other documentation that relies on these labels being used. I'd that documenting the existence of that label, with caveats, could be OK. Anyway, I'm happy to revisit this after this issue at hand gets fixed.

**Comment by BenTheElder** [comment]
Concrete proposal here? https://groups.google.com/d/msgid/kubernetes-sig-cluster-lifecycle/CAGDbWi9_2m3GPE3GTkbwU-qsaeV7XvzhUaHP%3DC0Guvk3zM5OFg%40mail.gmail.com

What's next for this?

**Comment by neolit123** [comment]
after the recent discussions at wg-naming i saw no objections around allowing maintainers to follow the established k8s deprecation policies for similar changes. thus, i think we can proceed with the KEP for 1.20 as outlined in the OP here.

**Comment by sftim** [comment]
In the KEP that follows from this, I would emphasize when explaining the motivation Kubernetes uses the term “control plane” (note: no dash when used in running text) to have pretty much the same meaning. Plus of course the word “master” in this context implies “slave” is linked directly to human rights abuses.

`node-role.kubernetes.io/control-plane` feels like the obvious replacement.

**Comment by neolit123** [comment]
NOTE: KEP draft is here:
https://docs.google.com/document/d/1kPs_zFconMU83LCOfBr_xKXfghn3y9VLLrTUSlCAf4s/edit#

**Comment by BenTheElder** [comment]
Thank you for writing this up! +1
This looks plenty detailed enough to move to a KEP PR when you're ready.

**Comment by neolit123** [comment]
> In the KEP that follows from this, I would emphasize when explaining the motivation Kubernetes uses the term “control plane” (note: no dash when used in running text) to have pretty much the same meaning. Plus of course the word “master” in this context implies “slave” is linked directly to human rights abuses.

@sftim "master" actually is not the same as "control plane". historically "master" in the k8s project meant:
- a Node that hosts control plane components
- an instance of the kube-apiserver

in kubeadm, we have usage of the former and a rename to `control-plane` has a clear intent.

i don't think we should include details around that or topics like "human rights" in the kubeadm KEP, so i'm defering this to the WG Naming group.

**Comment by qnetter** [comment]
Is there prior art in any distributor tooling? I know Rancher's RKE uses etcd, control-plane, and worker node naming.

**Comment by neolit123** [comment]
> Is there prior art in any distributor tooling?

usage of the key `node-role.kubernetes.io/master` can be found in both commercial and open-source projects.

**Comment by neolit123** [comment]
"enhancement" tracking issue:
https://github.com/kubernetes/enhancements/issues/2067
KEP PR:
https://github.com/kubernetes/enhancements/pull/2068

the plan for 1.20 is clear. for the later stages the feedback on the draft is now part of the KEP PR, but we can amend the proposal if needed.

**Comment by neolit123** [comment]
the proposal merged:
http://git.k8s.io/enhancements/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md
1.20 is the first stage of the rename. the plan for the later stages may change depending on feedback.

tracking issue at k/e:
https://github.com/kubernetes/enhancements/issues/2067

**Comment by neolit123** [comment]
PR for the 1.20 changes in kubeadm source code:
https://github.com/kubernetes/kubernetes/pull/95382

**Comment by neolit123** [comment]
> PR for the 1.20 changes in kubeadm source code:
> kubernetes/kubernetes#95382

this is merging.

**Comment by celestehorgan** [comment]
@neolit123 I believe all your sub-items on this task are done. Is this issue ready to be closed? :)

**Comment by neolit123** [comment]
@celestehorgan hi, we should keep this open until the transition from master -> control-plane has fully completed in future releases.
if you'd like we can be removed the WG Naming label via `/remove-wg naming` or just remove it from the WG Naming GitHub project tracking?

**Comment by sftim** [comment]
Would it be OK to mark this one as frozen?

**Comment by neolit123** [comment]
There are action items for 1.24.

/remove-lifecycle stale

**Comment by calvin0327** [comment]
1.23 will be released soon, can we delete the corresponding logic in 1.24?

**Comment by neolit123** [comment]
I will assign myself to work on this in 1.24. Thanks.

**Comment by neolit123** [comment]
WIP PR for 1.24 (stage 2) is here:
https://github.com/kubernetes/kubernetes/pull/107533

**Comment by neolit123** [comment]
we need to send a fix for the e2e_kubeadm suite in the release-1.23 branch of k/k:
https://github.com/kubernetes/kubernetes/pull/108128#issuecomment-1041822415
as [this](https://github.com/kubernetes/kubeadm/pull/2638) broke the kubeadm CP skew tests.

i will do that later today, probably.

**Comment by perosb** [comment]
just upgraded to 1.24.
shouldn't the control-plane taint only be added to nodes that have a master taint if this is a "rename"?
I had removed master from nodes which suddenly became unschedulable.

**Comment by perosb** [comment]
> that's a good point.. unfortunately that ended as an oversight on our side in [this code](https://github.com/kubernetes/kubernetes/blob/7477e1c91a141f33e1895427f4710f13cf7daaf8/cmd/kubeadm/app/phases/upgrade/postupgrade.go#L241-L275)
> 
> you are going to have to remove the new taint again.

do I read it correct that this will get added for all future upgrades too? as long as the code is there, at least for all 1.24.x?
the `master` taint wasn't previously added during every upgrade.

**Comment by neolit123** [comment]
No, we can backport a fix for the .1

**Comment by neolit123** [comment]
1.25 PR https://github.com/kubernetes/kubernetes/pull/109840
1.24 backport https://github.com/kubernetes/kubernetes/pull/109841

**Comment by devnewton** [comment]
"Kubernetes" also means "master". The whole project should be renamed to avoid this offensive word.

**Comment by tvsaru** [comment]
I did some googling and see that the inspiration for Kubernetes naming is from the meaning "helmsman", "pilot", "governor" , given that "[docker] containers were portrayed as  shipping containers on a whale like ship" and Kubernetes then becomes an awesome name for a "container orchestration system"

- https://news.ycombinator.com/item?id=9653797
- https://www.geekwire.com/2016/ever-come-kooky-kubernetes-name-heptio/

@devnewton where did you get the "master" meaning for Kubernetes from.

**Comment by sftim** [comment]
The home to discuss naming issues was WG Naming (see, for example, its [Google Group](https://groups.google.com/g/kubernetes-wg-naming)).
That WG has now dissolved as the discussions it dealt with are settled.

We're replacing the _English_ term “master” in some contexts due to its cultural links with oppression. WG Naming has not made any proposal to replace Greek terms. Please use this issue to discuss the [topic](https://github.com/kubernetes/kubeadm/issues/2200): replacing a specific label. If folks want to start any new discussion on a different topic, this is not the right place.

**Comment by neolit123** [comment]
i think we are done here. thanks to everyone who helped.

i don't see anything remaining in k/website or k/k but please LMK if you find anything. PRs around stage 4 in various repos are welcome too.

**Comment by sftim** [comment]
@neolit123 We should document the old label (and taint) in https://kubernetes.io/docs/reference/labels-annotations-taints/, but mark it as deprecated.

**Comment by sftim** [comment]
In fact, I thought that https://github.com/kubernetes/website/pull/36173 put it back. Hmm.

**Comment by neolit123** [comment]
> @neolit123 We should document the old label (and taint) in https://kubernetes.io/docs/reference/labels-annotations-taints/, but mark it as deprecated.

could you please log an k/website ticket about with help wanted? seems simple enough to be completed by a new contributor.

**Comment by neolit123** [comment]
> In fact, I thought that [kubernetes/website#36173](https://github.com/kubernetes/website/pull/36173) put it back. Hmm.

i don't know when was your change removed
