### ISSUE TITLE
update the kubeadm "create" docs with the right steps for node deletion

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2201]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#remove-the-node

^this section should have `kubectl delete node` as the last step after `kubeadm reset`
otherwise the following happens:

```
W0625 13:42:21.858309    5607 reset.go:99] [reset] Unable to fetch the kubeadm-config ConfigMap from cluster: failed to get node registration: failed to get corresponding node: nodes "master-etcd-test" not found
```

a PR for this file is required:
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md

**Comment by vinu2003** [comment]
Hey @neolit123, this can be a good first issue right ? I can pick this up.

**Comment by neolit123** [comment]
sure, go ahead @vinu2003
