### ISSUE TITLE
kubeadm config view replacement

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#2203]
`kubeadm config view` (as @neolit123 pointed out) is an unnecessary command because of the following:

- It is a shorthand for `kubectl get cm -o yaml -n kube-system kubeadm-config` that displays just the `ClusterConfiguration` portion of the config map.
- Users (including me) tend to use `kubectl` much more often as it can be executed from outside the cluster as well (provided that you have a proper kubeconfig).
- It does not display any component configs or any information specific to the current node (like name, taints, kubelet command line, etc.). Hence, it's not sufficient to debug config problems or to clone a cluster.

With that in mind it's best to deprecate and later remove this command. It's a GA command though and according to the GA deprecation policy, it must be functional, but deprecated, for 3 releases or 1 year (whichever is the longer).

the deprecation PR merged in 1.19:
https://github.com/kubernetes/kubernetes/pull/92740

1.22:
- [x] remove the command:
https://github.com/kubernetes/kubernetes/pull/102071
- [x] update the k8s.io page for "kubeadm config"
https://github.com/kubernetes/website/pull/28010

As a replacement, we should point out to `kubectl get cm -o yaml -n kube-system kubeadm-config` (or `kubectl get cm -o yaml -n kube-system kubeadm-config --kubeconfig=/etc/kubernetes/kubelet.conf` when executed from within the cluster).

to get the ClusterConfiguration yaml use:
```
kubectl get cm -n kube-system kubeadm-config -o=jsonpath="{.data.ClusterConfiguration}"
```

A new command, that can display the entire configuration should be considered in the future. At a bare minimum it should be able to display the `ClusterConfiguration` along with the component configs. It may be placed somewhere under `kubeadm config print`.

/cc @neolit123 @fabriziopandini 
/priority backlog
/kind deprecation
/kind cleanup
/area UX

**Comment by neolit123** [comment]
my vote goes for pointing users towards `kubectl get cm` in our documentation.

**Comment by leo-baltus** [comment]
I just stumbled over this deprecation warning. Would it not make sense to first provide an alternative command before deprecating `view`. E.g. the `config migrate` and `upgrade` take a `ClusterConfiguration` not a `ConfigMap`.

**Comment by neolit123** [comment]
the exact command is `kubectl get cm -n kube-system kubeadm-config -o=jsonpath="{.data.ClusterConfiguration}"` it will return the ClusterConfiguration as yaml.
i will add it to the issue description here.

given kubectl supports this, there is no need for the `view` command.
