### ISSUE TITLE
kubernetes kube-proxy mode ipvs, nodeport missed

### ISSUE THREAD

**Issue by timyl** [kubernetes/kubeadm#2205]
## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version**  v1.18.3
- **Cloud provider or hardware configuration**: local
- **OS** (e.g. from /etc/os-release):  centos7 1908 
- **Kernel** (e.g. `uname -a`): 4.4.228-2.el7.elrepo.x86_64
- **Others**: calico version: v3.13.3

## What happened?
I am testing dual stack kubernetes, and found that the node port will miss right after change kube-proxy mode to "ipvs", while it works by mode iptables

## What you expected to happen?
ipvs mode should be like with iptables mode, and node port should be worked fine

## How to reproduce it (as minimally and precisely as possible)?
use below kubeadm init command to set up, and change kube-proxy mode to ipvs
kubeadm init \
  --apiserver-advertise-address=192.168.9.101 \
  --pod-network-cidr=10.244.0.0/16,fc00::/48 \
  --service-cidr=10.96.0.0/12,fd00::/108 \
  --kubernetes-version=v1.18.3 \
  --image-repository registry.aliyuncs.com/google_containers \
  --feature-gates=IPv6DualStack=true

### some outputs when k8s environment is inited done
[root@k8s-master-01 ~]# kubectl get nodes k8s-master-01 -o go-template --template='{{range .spec.podCIDRs}}{{printf "%s\n" .}}{{end}}'
10.244.0.0/24
fc00::/64

there's just ipv4 address which is not exactly the same with below 
https://kubernetes.io/docs/tasks/network/validate-dual-stack/
[root@k8s-master-01 ~]# kubectl get nodes k8s-master-01 -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'
InternalIP: 192.168.9.101 
Hostname: k8s-master-01 

### calico outputs:  and i tried egress traffic from pod, is ok to ping to outside of cluster
[root@k8s-master-01 ~]# calicoctl get ipp -owide
NAME                  CIDR            NAT    IPIPMODE   VXLANMODE   DISABLED   SELECTOR   
default-ipv4-ippool   10.244.0.0/16   true   Never      Never       false      all()      
default-ipv6-ippool   fc00::/48       true   Never      Never       false      all()      

[root@k8s-master-01 ~]# calicoctl node status
Calico process is running.

IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
| PEER ADDRESS  |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+---------------+-------------------+-------+----------+-------------+
| 192.168.9.102 | node-to-node mesh | up    | 07:57:29 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
+------------------+-------------------+-------+----------+-------------+
|   PEER ADDRESS   |     PEER TYPE     | STATE |  SINCE   |    INFO     |
+------------------+-------------------+-------+----------+-------------+
| fd00:0:3:86::102 | node-to-node mesh | up    | 07:57:30 | Established |
+------------------+-------------------+-------+----------+-------------+

### set up an deployment and svc to test ingress traffic
[root@k8s-master-01 ~]# kubectl get pod -owide
NAME                                READY   STATUS    RESTARTS   AGE   IP              NODE            NOMINATED NODE   READINESS GATES
nginx-deployment-5c67dbcbc9-44xq5   1/1     Running   0          52m   10.244.36.197   k8s-worker-01   <none>           <none>
nginx-deployment-5c67dbcbc9-7sx7t   1/1     Running   0          52m   10.244.36.198   k8s-worker-01   <none>           <none>
[root@k8s-master-01 ~]# kubectl get pods nginx-deployment-5c67dbcbc9-44xq5 -o go-template --template='{{range .status.podIPs}}{{printf "%s \n" .ip}}{{end}}'
10.244.36.197 
fc00::24fe:200:8fa7:f4c7:af05 
[root@k8s-master-01 ~]# 
[root@k8s-master-01 ~]# kubectl get svc
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
kubernetes      ClusterIP   10.96.0.1       <none>        443/TCP           98m
my-service      NodePort    10.103.89.136   <none>        18080:30449/TCP   90m
my-service-v6   NodePort    fd00::69ed      <none>        18081:31608/TCP   14m
[root@k8s-master-01 ~]#
[root@k8s-master-01 ~]# cat nginx-svc-v6.yaml 
kind: Service
apiVersion: v1
metadata:
  name: my-service-v6
spec:
  type: NodePort
  ipFamily: IPv6
  selector:
    app: pod-nginx
  ports:
  - protocol: TCP
    port: 18081
    targetPort: 80

**_[root@k8s-master-01 ~]# netstat -an |grep 31608_**
[root@k8s-master-01 ~]# 
**_looks like 31608 is not bring up_** 

### outpus with ipvsadm, it's normal !!!!
[root@k8s-master-01 ~]# ipvsadm -ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.96.0.1:443 rr
  -> 192.168.9.101:6443           Masq    1      0          0         
TCP  10.96.0.10:53 rr
  -> 10.244.151.128:53            Masq    1      0          0         
  -> 10.244.151.129:53            Masq    1      0          0         
TCP  10.103.89.136:18080 rr
  -> 10.244.36.197:80             Masq    1      0          0         
  -> 10.244.36.198:80             Masq    1      0          0         
TCP  127.0.0.1:30449 rr
  -> 10.244.36.197:80             Masq    1      0          0         
  -> 10.244.36.198:80             Masq    1      0          0         
TCP  172.17.0.1:30449 rr
  -> 10.244.36.197:80             Masq    1      0          0         
  -> 10.244.36.198:80             Masq    1      0          0         
TCP  192.168.9.101:30449 rr
  -> 10.244.36.197:80             Masq    1      0          0         
  -> 10.244.36.198:80             Masq    1      0          0         
TCP  10.0.2.4:30449 rr
  -> 10.244.36.197:80             Masq    1      0          0         
  -> 10.244.36.198:80             Masq    1      0          0         
TCP  10.96.0.10:9153 rr
  -> 10.244.151.128:9153          Masq    1      0          0         
  -> 10.244.151.129:9153          Masq    1      0          0         
UDP  10.96.0.10:53 rr
  -> 10.244.151.128:53            Masq    1      0          0         
  -> 10.244.151.129:53            Masq    1      0          0         
TCP  [fd00::69ed]:18081 rr
  -> [fc00::24fe:200:8fa7:f4c7:af05]:80 Masq    1      0          0         
  -> [fc00::24fe:200:8fa7:f4c7:af06]:80 Masq    1      0          0 

logs from kube-proxy, no any outpus...
[root@k8s-master-01 ~]# kubectl -n kube-system logs -f kube-proxy-hnx5w
I0630 09:09:33.297641       1 node.go:136] Successfully retrieved node IP: 192.168.9.102
I0630 09:09:33.297669       1 server_others.go:259] Using ipvs Proxier.
I0630 09:09:33.297675       1 server_others.go:261] creating dualStackProxier for ipvs.
W0630 09:09:33.298631       1 proxier.go:429] IPVS scheduler not specified, use rr by default
W0630 09:09:33.298843       1 proxier.go:429] IPVS scheduler not specified, use rr by default
W0630 09:09:33.298854       1 ipset.go:110] ipset name truncated; [KUBE-6-LOAD-BALANCER-SOURCE-CIDR] -> [KUBE-6-LOAD-BALANCER-SOURCE-CID]
W0630 09:09:33.298860       1 ipset.go:110] ipset name truncated; [KUBE-6-NODE-PORT-LOCAL-SCTP-HASH] -> [KUBE-6-NODE-PORT-LOCAL-SCTP-HAS]
I0630 09:09:33.298927       1 server.go:583] Version: v1.18.3
I0630 09:09:33.299141       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I0630 09:09:33.299342       1 config.go:133] Starting endpoints config controller
I0630 09:09:33.299355       1 shared_informer.go:223] Waiting for caches to sync for endpoints config
I0630 09:09:33.299468       1 config.go:315] Starting service config controller
I0630 09:09:33.299472       1 shared_informer.go:223] Waiting for caches to sync for service config
I0630 09:09:33.400108       1 shared_informer.go:230] Caches are synced for service config 
I0630 09:09:33.400210       1 shared_informer.go:230] Caches are synced for endpoints config 

### change back to iptables, then node port is came back
[root@k8s-master-01 ~]# kubectl get svc
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
kubernetes      ClusterIP   10.96.0.1       <none>        443/TCP           130m
my-service      NodePort    10.103.89.136   <none>        18080:30449/TCP   122m
my-service-v6   NodePort    fd00::69ed      <none>        18081:31608/TCP   46m
[root@k8s-master-01 ~]# netstat -an |grep 31608
tcp6       0      0 :::31608                :::*                    LISTEN  

..
so what else did i missed by kubeadm set up ? or any others configurations ?

**Comment by rosti** [comment]
Thanks for filing this issue @timyl !
What steps do you use to change to and from IPVS mode on the fly? Can you supply the kube-proxy config map contents (via `kubectl get cm -o yaml -n kube-system kube-proxy`)?
If this is a kube-proxy issue we may not be able to help directly here.

**Comment by neolit123** [comment]
this doesn't seem like a kubeadm problem. NodePort is a feature maintained by SIG Node/SIG Network, kube-proxy is maintained by SIG Network. the ticket should be logged in the kubernetes/kubernetes repo.

**Comment by timyl** [comment]
@rosti  I change the mode by updating kube-proxy config-map as you mentioned, and then restart all kube-proxy pod, below is the  kube-proxy cm configuration 
------------------
[root@k8s-master-01 ~]# kubectl -n kube-system get cm kube-proxy -oyaml
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 0
      contentType: ""
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 0
    clusterCIDR: 10.244.0.0/16,fc00::/48
    configSyncPeriod: 0s
    conntrack:
      maxPerCore: null
      min: null
      tcpCloseWaitTimeout: null
      tcpEstablishedTimeout: null
    detectLocalMode: ""
    enableProfiling: false
    featureGates:
      IPv6DualStack: true
    healthzBindAddress: ""
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: null
      minSyncPeriod: 0s
      syncPeriod: 0s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: false
      syncPeriod: 0s
      tcpFinTimeout: 0s
      tcpTimeout: 0s
      udpTimeout: 0s
    kind: KubeProxyConfiguration
    metricsBindAddress: ""
    mode: ""
    nodePortAddresses: null
    oomScoreAdj: null
    portRange: ""
    showHiddenMetricsForVersion: ""
    udpIdleTimeout: 0s
    winkernel:
      enableDSR: false
      networkName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://192.168.9.101:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-30T13:19:18Z"
  labels:
    app: kube-proxy
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:config.conf: {}
        f:kubeconfig.conf: {}
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
    manager: kubeadm
    operation: Update
    time: "2020-06-30T13:19:18Z"
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "196"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-proxy
  uid: 741922ee-7799-4702-8cbe-2de9ca8328e8

**Comment by maxisam** [comment]
is this the reason  k8s_nginx-proxy_nginx-proxy pod is missing?

https://kubespray.io/#/docs/nodes?id=_3-restart-kube-systemnginx-proxy

**Comment by ranasheel2000** [comment]
@timyl Kindly share your "ip -6 r" output as well on master and worker node.

**Comment by timyl** [comment]
> @timyl Kindly share following outputs as well on master and worker node:
> 
> ip -6 r
> ip a s caliXYZ... (XYZ: number assigned to different calico interfaces)
> ip a s ipvs..(ipvs interfaces which keeps on adding all service IPs)

@ranasheel2000 
**show from worker-node where pod is running**
[root@k8s-worker-01 ~]# ip -6 r
unreachable ::/96 dev lo metric 1024 error -113 pref medium
unreachable ::ffff:0.0.0.0/96 dev lo metric 1024 error -113 pref medium
unreachable 2002:a00::/24 dev lo metric 1024 error -113 pref medium
unreachable 2002:7f00::/24 dev lo metric 1024 error -113 pref medium
unreachable 2002:a9fe::/32 dev lo metric 1024 error -113 pref medium
unreachable 2002:ac10::/28 dev lo metric 1024 error -113 pref medium
unreachable 2002:c0a8::/32 dev lo metric 1024 error -113 pref medium
unreachable 2002:e000::/19 dev lo metric 1024 error -113 pref medium
unreachable 3ffe:ffff::/32 dev lo metric 1024 error -113 pref medium
**fc00::24fe:200:8fa7:f4c7:af07 dev caliad11071a3dc metric 1024 pref medium
fc00::24fe:200:8fa7:f4c7:af08 dev cali8d7fe0525c2 metric 1024 pref medium**
blackhole fc00::24fe:200:8fa7:f4c7:af00/122 dev lo proto bird metric 1024 error -22 pref medium
fc00::6b4c:ae1b:e01b:1b30:9780/122 via fd00:0:3:86::101 dev enp0s8 proto bird metric 1024 pref medium
fd00::5d27 dev kube-ipvs0 proto kernel metric 256 pref medium
fd00:0:3:86::/64 dev enp0s8 proto kernel metric 256 pref medium
fe80::/64 dev enp0s3 proto kernel metric 256 pref medium
fe80::/64 dev enp0s8 proto kernel metric 256 pref medium
fe80::/64 dev caliad11071a3dc proto kernel metric 256 pref medium
fe80::/64 dev cali8d7fe0525c2 proto kernel metric 256 pref medium
default via fd00:0:3:86::1 dev enp0s8 metric 1 pref medium

**ip a s calixxx**
[root@k8s-worker-01 ~]# ip a s cali8d7fe0525c2
9: cali8d7fe0525c2@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
[root@k8s-worker-01 ~]# ip a s caliad11071a3dc
8: caliad11071a3dc@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever

**ipv-devxxx dummi interface**
**[root@k8s-worker-01 ~]# ip -4 addr**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 10.0.2.5/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 480sec preferred_lft 480sec
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    inet 192.168.9.102/24 brd 192.168.9.255 scope global enp0s8
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
5: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1
    inet 10.244.36.192/32 brd 10.244.36.192 scope global tunl0
       valid_lft forever preferred_lft forever
**7: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default** 
    inet 10.96.0.10/32 brd 10.96.0.10 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.96.0.1/32 brd 10.96.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.104.118.219/32 brd 10.104.118.219 scope global kube-ipvs0
       valid_lft forever preferred_lft forever

**looks like ipv6 ipvs dummy interface is DOWN automatically...**
**[root@k8s-worker-01 ~]# ip -6 addr** 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::a00:27ff:fef8:666f/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fd00:0:3:86::102/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe1b:97ae/64 scope link 
       valid_lft forever preferred_lft forever
**7: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 state DOWN** 
    inet6 fd00::5d27/128 scope global 
       valid_lft forever preferred_lft forever
8: caliad11071a3dc@docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 state UP 
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
9: cali8d7fe0525c2@docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 state UP 
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever

ipvs rule outputs
[root@k8s-master-01 ~]# kubectl get svc
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP           32h
my-service      NodePort    10.104.118.219   <none>        18080:30637/TCP   32h
my-service-v6   NodePort    fd00::5d27       <none>        18081:32113/TCP   28m

-------
**[root@k8s-worker-01 ~]# ipvsadm -ln**
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  192.168.9.102:30637 rr
  -> 10.244.36.200:80             Masq    1      0          0         
  -> 10.244.36.201:80             Masq    1      0          0         
TCP  10.0.2.5:30637 rr
  -> 10.244.36.200:80             Masq    1      0          0         
  -> 10.244.36.201:80             Masq    1      0          0         
TCP  10.96.0.1:443 rr
  -> 192.168.9.101:6443           Masq    1      0          0         
TCP  10.96.0.10:53 rr
  -> 10.244.151.131:53            Masq    1      0          0         
  -> 10.244.151.132:53            Masq    1      0          0         
TCP  10.96.0.10:9153 rr
  -> 10.244.151.131:9153          Masq    1      0          0         
  -> 10.244.151.132:9153          Masq    1      0          0         
TCP  10.104.118.219:18080 rr
  -> 10.244.36.200:80             Masq    1      0          0         
  -> 10.244.36.201:80             Masq    1      0          0         
TCP  10.244.36.192:30637 rr
  -> 10.244.36.200:80             Masq    1      0          0         
  -> 10.244.36.201:80             Masq    1      0          0         
TCP  127.0.0.1:30637 rr
  -> 10.244.36.200:80             Masq    1      0          0         
  -> 10.244.36.201:80             Masq    1      0          0         
TCP  172.17.0.1:30637 rr
  -> 10.244.36.200:80             Masq    1      0          0         
  -> 10.244.36.201:80             Masq    1      0          0         
UDP  10.96.0.10:53 rr
  -> 10.244.151.131:53            Masq    1      0          0         
  -> 10.244.151.132:53            Masq    1      0          0         
TCP  [fd00::5d27]:18081 rr
  -> [fc00::24fe:200:8fa7:f4c7:af07]:80 Masq    1      0          0         
  -> [fc00::24fe:200:8fa7:f4c7:af08]:80 Masq    1      0          0

**Comment by neolit123** [comment]
hi, this doesn't feel like a kubeadm issue, so i'm going to close it but please continue the discussion or open a new one in the kubernetes/kubernetes repository and tag it with `/sig network`

/sig network
/close

**Comment by ranasheel2000** [comment]
> @timyl

Thank you for sharing details.
>blackhole fc00::24fe:200:8fa7:f4c7:af00/122 dev lo proto bird metric 1024 error -22 pref medium

I am a bit curious about blackhole route with "error -22" in "ip -6 r s". 

[IPVS/dualStack follow up issue](https://github.com/kubernetes/kubernetes/issues/92412).

**Comment by ranasheel2000** [comment]
I know this bug is closed but still sharing information in case someone else face this issue and search in kubeadm for it.

Dear @timyl, 
Please update kernel version, it will work fine.
Checked on our end, its good to go with IPV6 dual stack with IPVS after updating kernel version.
All thanks to [uablrek](https://github.com/uablrek).

**Comment by kkendzia** [comment]
@timyl is this issue discussed anywhere else? I have similar issues.

**Comment by ranasheel2000** [comment]
> @timyl is this issue discussed anywhere else? I have similar issues.
@kkendzia 
upgrade linux kernel version, if you are running on older kernel version.
In our case it fixed the issue (centos).
