### ISSUE TITLE
remove --port from kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2207]
the flag is deprecated, but it prevents the components to serve insecurely.
remove the flag from kubeadm manifests once it's removed.

files:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/controlplane/manifests.go
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/controlplane/manifests_test.go

PR that added the flag in 1.19:
https://github.com/kubernetes/kubernetes/pull/92720

related to:
https://github.com/kubernetes/kubeadm/issues/2156

-------

1.22 PRs
- KCM:  https://github.com/kubernetes/kubernetes/pull/96216
- KS: https://github.com/kubernetes/kubernetes/pull/96345

1.23 PRs:
remove the flags from both components.
- KCM: https://github.com/kubernetes/kubernetes/pull/104157
- KS: TODO

**Comment by neolit123** [comment]
@RA489 
let's leave this unassigned for now, we don't know when the work is going to happen.

**Comment by RA489** [comment]
> @RA489
> let's leave this unassigned for now, we don't know when the work is going to happen.

+1. Thanks.

**Comment by karstland** [comment]
environment: kubernetes v1.16.13 with docker-ce v18.09.9, os: centos 7.7 kernel version: 3.10.0-1127.el7.x86_x64
bootstrap with kubeadm: kubeadm init
results: controller manager and scheduler keep crashloopbackoff
solutions: remove or comment the flag ```--port=0``` flag in /etc/kubernetes/manifests/kube-controler-manager.yaml and kube-scheduler.yaml
questions: what's the problem. after removing the flag, means that  _the components to serve insecurely_?

**Comment by neolit123** [comment]
1.16.13 has the problem, so you need to update to 1.16.14 or 1.17.x
removing --port=0 is not recommended, because it means the components would expose metrics and health checks publicly.

**Comment by pacoxu** [comment]
- [ ] - scheduler part will wait for https://github.com/kubernetes/kubernetes/pull/96345
- [x] - controller manager port is already deprecated: https://github.com/kubernetes/kubernetes/pull/96216/

**Comment by pacoxu** [comment]
- [ ] - scheduler part will wait for https://github.com/kubernetes/kubernetes/pull/96345
- [x] - controller manager port is already deprecated: https://github.com/kubernetes/kubernetes/pull/96216/

**Comment by neolit123** [comment]
yes, updated the issue description here to have an action item for kubeadm 1.23

**Comment by ingvagabund** [comment]
Any chance to resolved this issue in 1.22? I would like to remove the --port flag from KS in 1.22 given the flag has been deprecated for quite long.

**Comment by neolit123** [comment]
The KCM PR merged. If the KS PR merges soon we can have one kubeadm PR that
removes the flags from both components for 1.22.

**Comment by ingvagabund** [comment]
I see. So the KS PR needs to merge first. Then you can remove the port flag. And then KS can remove the port flag from its flags. Is that correct?

**Comment by neolit123** [comment]
Yes. Sound correct to me.
