### ISSUE TITLE
taints [node-role.kubernetes.io/master:NoSchedule] is lost after kubeadm init

### ISSUE THREAD

**Issue by andy-wolf168** [kubernetes/kubeadm#2209]
BUG REPORT
## Versions
[root@node1 k8s]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"archive", BuildDate:"2019-12-14T16:09:15Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
[root@node1 k8s]# kubectl get node
NAME    STATUS   ROLES    AGE    VERSION
node1   Ready    master   12d    v1.15.6
node2   Ready    master   12d    v1.15.6
node3   Ready    master   104s   v1.15.6

[root@node1 k8s]# uname -a
Linux node1 3.10.0-957.21.3.el7.x86_64 #1 SMP Wed Jul 17 06:57:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
We create the cluster by following the command：
kubeadm init  --config=./kubeadm_config.yml --ignore-preflight-errors all
```

[init] Using Kubernetes version: v1.15.6
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] External etcd mode: Skipping etcd/ca certificate authority generation
[certs] External etcd mode: Skipping etcd/peer certificate authority generation
[certs] External etcd mode: Skipping apiserver-etcd-client certificate authority generation
[certs] External etcd mode: Skipping etcd/server certificate authority generation
[certs] External etcd mode: Skipping etcd/healthcheck-client certificate authority generation
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[controlplane] Adding extra host path mount "kube-apiserver-log" to "kube-apiserver"
[controlplane] Adding extra host path mount "kube-controller-manager-log" to "kube-controller-manager"
[controlplane] Adding extra host path mount "kube-scheduler-log" to "kube-scheduler"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[controlplane] Adding extra host path mount "kube-apiserver-log" to "kube-apiserver"
[controlplane] Adding extra host path mount "kube-controller-manager-log" to "kube-controller-manager"
[controlplane] Adding extra host path mount "kube-scheduler-log" to "kube-scheduler"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[controlplane] Adding extra host path mount "kube-apiserver-log" to "kube-apiserver"
[controlplane] Adding extra host path mount "kube-controller-manager-log" to "kube-controller-manager"
[controlplane] Adding extra host path mount "kube-scheduler-log" to "kube-scheduler"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 0.014530 seconds
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.15" in namespace kube-system with the configuration for the kubelets in the cluster
[mark-control-plane] Marking the node node3 as control-plane by adding the label "node-role.kubernetes.io/master=''"
[mark-control-plane] Marking the node node3 as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[bootstrap-token] Using token: xs25g7.79pik74t75yqlulx
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!
```

Sometimes, taints [node-role.kubernetes.io/master:NoSchedule] is lost after kubeadm init.
I add debugging information to the following code, 
```
func PatchNodeOnce(client clientset.Interface, nodeName string, patchFn func(*v1.Node)) func() (bool, error) {
	return func() (bool, error) {
		....
		// Execute the mutating function
		patchFn(n)

		fmt.Println("###ANDY###Get node object after patchFn, %v\n", n)

		newData, err := json.Marshal(n)
		if err != nil {
			return false, errors.Wrapf(err, "failed to marshal modified node %q into JSON", n.Name)
		}

		patchBytes, err := strategicpatch.CreateTwoWayMergePatch(oldData, newData, v1.Node{})
		if err != nil {
			return false, errors.Wrap(err, "failed to create two way merge patch")
		}

		if _, err := client.CoreV1().Nodes().Patch(n.Name, types.StrategicMergePatchType, patchBytes); err != nil {
			// TODO also check for timeouts
			if apierrors.IsConflict(err) {
				fmt.Println("Temporarily unable to update node metadata due to conflict (will retry)")
				return false, nil
			}
			return false, errors.Wrapf(err, "error patching node %q through apiserver", n.Name)
		}

		// get the node object
		n2, err := client.CoreV1().Nodes().Get(nodeName, metav1.GetOptions{})
		if err != nil {
			// TODO this should only be for timeouts
			fmt.Println("###ANDY###this should only be for timeouts")
			return false, nil
		}
		fmt.Println("###ANDY###Get node object after client Patch, %v", n2)

		return true, nil
	}
}
```
and the output is as follows
```
[mark-control-plane] Marking the node node3 as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]
###ANDY###Get node object after patchFn,
...
Taints:[{node-role.kubernetes.io/master  NoSchedule <nil>} {node.kubernetes.io/not-ready  NoSchedule <nil>}],ConfigSource:nil,},...
###ANDY###Get node object after client Patch, ...
Taints:[{node.kubernetes.io/not-ready  NoSchedule <nil>} {node.kubernetes.io/not-ready  NoExecute 2020-06-30 21:21:50 +0800 CST}],ConfigSource:nil,},...
[bootstrap-token] Using token: zii14j.carxwvq04sw6ye0e
```

> taints [node-role.kubernetes.io/master:NoSchedule] is lost after kubeadm init
I wonder if the taint operation of NodeLifecycleController covers kubeadm's,
When the node registration and in not-Ready status, NodeLifecycleController  will add “node.kubernetes.io/not-ready  NoExecute”to it
```
controller/controller_utils.go#AddOrUpdateTaintOnNode#L919:
（1）oldNode, err = c.CoreV1().Nodes().Get(nodeName, metav1.GetOptions{})   
-->Maybe get the oldNode information before "[mark-control-plane] Marking the node node3 as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule]"
（2）c.CoreV1().Nodes().Patch(nodeName, types.StrategicMergePatchType, patchBytes)
```

NodeSpec.Taints  has no patchstrategy key value, and use the default replace patch policy.
```
type NodeSpec struct {
      ...
	// If specified, the node's taints.
	// +optional
	Taints []Taint `json:"taints,omitempty" protobuf:"bytes,5,opt,name=taints"`  
}
```

## What you expected to happen?
taints [node-role.kubernetes.io/master:NoSchedule] still exists after kubeadm init

## How to reproduce it (as minimally and precisely as possible)?
kubeadm init  --config=./kubeadm_config.yml --ignore-preflight-errors all

## Anything else we need to know?
Probability appearance

/kind bug
/help 
@neolit123

**Comment by neolit123** [comment]
thank you for debugging this problem.

this is odd...we have kubeadm specific e2e tests that ensure that the node is always tainted:
https://github.com/kubernetes/kubernetes/blob/dde6e8e7465468c32642659cb708a5cc922add64/test/e2e_kubeadm/controlplane_nodes_test.go#L57

we run the same e2e test at least every two hours:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-master

you can search for "node should be labelled and tainted" to see that this particular test is always green.

i cannot confirm this in my local testing too.

> I wonder if the taint operation of NodeLifecycleController covers kubeadm's,
When the node registration and in not-Ready status, NodeLifecycleController will add “node.kubernetes.io/not-ready NoExecute”to it

i'd assume that the NLC always finished patching, with NotReady _before_ kubeadm patches the Node object.
we could make kubeadm use Upgrade instead of Patch, but if the NLC is stomping the value with Patch, unclear it will help much.

> How to reproduce it (as minimally and precisely as possible)?

this is not reproducible, so we need to better understand why / when it happens.
at this point it seems specific to your setup as this is the first report i've seen about it.

/priority awaiting-more-evidence

**Comment by andy-wolf168** [comment]
I went to see  APIServer's log，it shows kube-controller-manager get node object before kubeadm's PATCH
```
apiserver.log
I0630 13:21:49.847052       1 wrap.go:47] GET /api/v1/nodes/node3: (300.171061ms) 200 [kubeadm/v1.15.6 (linux/amd64) kubernetes/7015f71 100.4.0.203:56440]

I0630 13:21:50.008768       1 wrap.go:47] GET /api/v1/nodes/node3?resourceVersion=0: (528.67碌s) 200 [kube-controller-manager/v1.15.6 (linux/amd64) kubernetes/7015f71/system:serviceaccount:kube-system:node-controller 100.4.0.202:46404]

I0630 13:21:50.464460       1 wrap.go:47] PATCH /api/v1/nodes/node3: (615.468732ms) 200 [kubeadm/v1.15.6 (linux/amd64) kubernetes/7015f71 100.4.0.203:56440]

I0630 13:21:51.219027       1 wrap.go:47] PATCH /api/v1/nodes/node3: (1.208663144s) 200 [kube-controller-manager/v1.15.6 (linux/amd64) kubernetes/7015f71/system:serviceaccount:kube-system:node-controller 100.4.0.202:46404]

I0630 13:21:51.220017       1 wrap.go:47] GET /api/v1/nodes/node3: (753.686819ms) 200 [kubeadm/v1.15.6 (linux/amd64) kubernetes/7015f71 100.4.0.203:56440]
```
controller_manager log
```
I0630 13:21:49.955457       1 node_lifecycle_controller.go:674] Controller observed a new Node: "node3"
I0630 13:21:49.955470       1 controller_utils.go:168] Recording Registered Node node3 in Controller event message for node node3
I0630 13:21:49.955534       1 node_lifecycle_controller.go:889] ReadyCondition for Node node3 transitioned from &NodeCondition{Type:Ready,Status:True,LastHeartbeatTime:2020-06-30 13:17:57 +0000 UTC,LastTransitionTime:2020-06-30 13:12:57 +0000 UTC,Reason:KubeletReady,Message:kubelet is posting ready status,} to &NodeCondition{Type:Ready,Status:False,LastHeartbeatTime:2020-06-30 13:21:46 +0000 UTC,LastTransitionTime:2020-06-30 13:21:45 +0000 UTC,Reason:KubeletNotReady,Message:runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized,}
I0630 13:21:49.955576       1 node_lifecycle_controller.go:897] Node node3 ReadyCondition updated. Updating timestamp.
I0630 13:21:49.955618       1 node_lifecycle_controller.go:732] Node node3 is NotReady as of 2020-06-30 13:21:49.955588193 +0000 UTC m=+44302.959301057. Adding it to the Taint queue.
I0630 13:21:49.956012       1 event.go:258] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node3", UID:"f48a17cc-546f-4ea3-bbf7-d679061c79f0", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node node3 event: Registered Node node3 in Controller
```

**Comment by neolit123** [comment]
> kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6",

> kube-controller-manager/v1.15.6

i realized this is an unsupported version of k8s / kubeadm.

can you reproduce the same problem with 1.16? if not we may have to close this ticket as we follow a support skew policy.
also 1.16 will be out-of-support with the release of 1.19 in August, so you have to upgrade to 1.17 soon.

**Comment by neolit123** [comment]
any updates on this @andy-wolf168 ?

also what are the contents of your `--config=./kubeadm_config.yml`?

> kubeadm init --config=./kubeadm_config.yml --ignore-preflight-errors all

**Comment by andy-wolf168** [comment]
thanks for taking the time to respond @neolit123 
I compared the master code of kubeadm with the code of version 1.15.6. There is no difference between the two for the add taint process. In my opinion, the problem described above will also occur in the latest version, that is, concurrent addition of tainted operations causes taint coverage.

[root@node40]# cat kubeadm_config.yml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: "v1.15.6"
controlPlaneEndpoint: "10.99.212.140"
imageRepository: "xxx.com:8088/xxx"
etcd:
 external:
  endpoints:
  \- "http://10.99.212.40:2379"
  \- "http://10.99.212.41:2379"
  \- "http://10.99.212.42:2379"
apiServer:
  certSANs:
  \- 10.99.212.140
  \- 127.0.0.1
  \- kubernetes
  \- kubernetes.default
  \- kubernetes.default.svc
  \- kubernetes.default.svc.cluster
  \- kubernetes.default.svc.cluster.local
  extraArgs:
    advertise-address: "10.99.212.140"
    token-auth-file: /etc/kubernetes/pki/token.csv
    service-node-port-range: 1-65535
    log-dir: /var/log/xxxx
    v: "2"
    logtostderr: "false"
    tls-cipher-suites: xxxx
  extraVolumes:
  \- name: kube-apiserver-log
    hostPath: /var/log/xxxx
    mountPath: /var/log/xxxx
    pathType: DirectoryOrCreate
    readOnly: false
networking:
  podSubnet: 177.177.0.0/16
  serviceSubnet: 10.96.0.0/16
controllerManager:
  extraArgs:
    log-dir: /var/log/xxxx
    v: "2"
    logtostderr: "false"
  extraVolumes:
  \- name: kube-controller-manager-log
    hostPath: /var/log/xxxx
    mountPath: /var/log/xxxx
    pathType: DirectoryOrCreate
    readOnly: false
scheduler:
  extraArgs:
    log-dir: /var/log/xxxx
    v: "2"
    logtostderr: "false"
  extraVolumes:
  \- name: kube-scheduler-log
    hostPath: /var/log/xxxx
    mountPath: /var/log/xxxx
    pathType: DirectoryOrCreate
    readOnly: false

\---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.99.212.140"

\---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 1000

**Comment by neolit123** [comment]
thank you for the kubeadm config, it looks fine.

> I compared the master code of kubeadm with the code of version 1.15.6. There is no difference between the two for the add taint process. In my opinion, the problem described above will also occur in the latest version, that is, concurrent addition of tainted operations causes taint coverage.

kubeadm source code is not the only code that can affect this. so please try a newer version of k8s + kubeadm.
as i mentioned, we are not seeing this in CI and **all of our e2e test jobs** run a test for the existence of the master taint:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm

i have not seen other user reports about this and have not seen the problem locally.

please answer these questions:
- is there anything else specific to your setup?
- is this a single node setup?
- are you sure something else in your setup is not racing to remove the taint?
- how often does it happen?

**Comment by neolit123** [comment]
/close
please re-open once you have more updates on this issue.
thanks
