### ISSUE TITLE
Not able to upgrade from 1.16.3 to 1.17.7 on CoreOS/FedoraCoreOS

### ISSUE THREAD

**Issue by msadofschi** [kubernetes/kubeadm#2212]
## What keywords did you search in kubeadm issues before filing this one?

upgrade 1.17 coreos FedoraCoreOS

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

`kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`):
`kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**:
Hardware configuration
- **OS** (e.g. from /etc/os-release):
`NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2303.3.0
VERSION_ID=2303.3.0
BUILD_ID=2019-12-02-2049
PRETTY_NAME="Container Linux by CoreOS 2303.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"`
- **Kernel** (e.g. `uname -a`):
`Linux master01 4.19.86-coreos #1 SMP Mon Dec 2 20:13:38 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz GenuineIntel GNU/Linux`
- **Others**:

## What happened?

after running:
`kubeadm upgrade apply v1.17.7`
it ends with:
`[apiclient] Found 3 Pods for label selector component=kube-controller-manager`

`[upgrade/apply] FATAL: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher`

Run with --v=5:

`[apiclient] Found 3 Pods for label selector component=kube-controller-manager
timed out waiting for the condition
couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced
k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade.rollbackOldManifests
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade/staticpods.go:515
k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade.upgradeComponent
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade/staticpods.go:255
k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade.StaticPodControlPlane
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade/staticpods.go:472
k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade.PerformStaticPodUpgrade
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade/staticpods.go:606
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.PerformControlPlaneUpgrade
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:224
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.runApply
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:164
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.NewCmdApply.func1
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:79
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
[upgrade/apply] FATAL
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.runApply
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:165
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.NewCmdApply.func1
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:79
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.17.7-rc.0.50+e4efcc9eb3807d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357`

## What you expected to happen?

`[upgrade/successful] SUCCESS! Your cluster was upgraded to "v1.17.7". Enjoy!`

`[upgrade/kubelet] Now that your control plane is upgraded, please proceed with upgrading your kubelets if you haven't already done so.`

## How to reproduce it (as minimally and precisely as possible)?

Having a v1.16.3 HA cluster running in CoreOS attempt to upgrade to v1.17.7

`kubeadm upgrade apply v1.17.7`

## Anything else we need to know?

This is probably related with:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#usr-mounted-read-only

As a workarround we were able to upgrade by editing the `kubeadm-config` configMap by adding:
`flex-volume-plugin-dir: /opt/libexec/kubernetes/kubelet-plugins/volume/exec`
as an `extraArgs`  to the  `controllerManager`  before making the upgrade.

Example:

    controllerManager:
      extraArgs:
        cloud-config: /etc/kubernetes/vsphere.conf
        cloud-provider: vsphere
        flex-volume-plugin-dir: /opt/libexec/kubernetes/kubelet-plugins/volume/exec
      extraVolumes:
      - hostPath: /etc/kubernetes/vsphere.conf
        mountPath: etc/kubernetes/vsphere.conf
        name: vsphere
        pathType: File
        readOnly: true

I would expect that `controllerManager` doesn't need to make use of a read-only FileSystem `/usr/` in CoreOS or FedoraCoreOS so that upgrades or fresh new installations don't need to have this kind of workarrounds.
If this can be corrected in future releases would be nice.
Also a note in the [Upgrading kubeadm clusters](https://v1-17.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/) and in [Troubleshooting kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#usr-mounted-read-only) would also be nice to have.

**Comment by neolit123** [comment]
hello,

> I would expect that controllerManager doesn't need to make use of a read-only FileSystem /usr/ in CoreOS or FedoraCoreOS so that upgrades or fresh new installations don't need to have this kind of workarrounds.

i recall issues in this issue tracker were users report the same problem.

> If this can be corrected in future releases would be nice.

we decided that kubeadm should not be in the business of tracking the underlying OS. /usr is the default value in the controller-manager too as can be seen here:
`--flex-volume-plugin-dir string     Default: "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"`

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

> Also a note in the Upgrading kubeadm clusters and in Troubleshooting kubeadm would also be nice to have.

as you pointed out there is already a note about this here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#usr-mounted-read-only

but i don't think we should add a note about this in the upgrade page.
also flex volume support is being removed, so hopefully this will be a non-issue in the future.
https://github.com/kubernetes/kubeadm/issues/2135

thanks
