### ISSUE TITLE
Kubelet Join blocked by Port 10250

### ISSUE THREAD

**Issue by vinhdiesal** [kubernetes/kubeadm#2218]
When I perform the `kubeadm join` on the worker node, I get the following error: 
```
W0712 10:16:01.596870 1909863 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10250]: Port 10250 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```
I performed a `netstat -ltnp | grep -w ":10250"` i see kubelet. 

I tried to stop the kubelet  by `systemctl stop kubelet`, but it kept running. 

What should I do in order to join my `worker` nodes into the kubeadm cluster?

**Comment by vinhdiesal** [comment]
i then killed the `kubelet` process by using `sudo kill -9 <process>` gotten further with the following failures
```
W0712 12:16:09.376069 2568305 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Downloading configuration for the kubelet from the "kubelet-config-1.18" ConfigMap in the kube-system namespace
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
[kubelet-check] Initial timeout of 40s passed.
error execution phase kubelet-start: error uploading crisocket: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher
```

**Comment by neolit123** [comment]
always call `kubeadm reset` before `kubeadm init/join`

> I tried to stop the kubelet by systemctl stop kubelet, but it kept running.

unclear why this doesn't stop the kubelet.

> [kubelet-check] Initial timeout of 40s passed.
> error execution phase kubelet-start: error uploading crisocket: timed out waiting for the condition

this usually means the kubelet is not healthy.

please use the support channels for support questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
also the #kubeadm channel on k8s slack.

/triage support
/close

**Comment by hushi2222** [comment]
![46ee81a463e245a83d208b05f21b4aa](https://github.com/kubernetes/kubeadm/assets/59379984/dbfac882-4926-4df9-b2c3-e21c957a7348)
 i tried a lot of ways to kill kubelet but it still ocupied port 10250

**Comment by engineerit99999** [comment]
isof -i :10250
kill pid number

**Comment by wilkis3** [comment]
> ![46ee81a463e245a83d208b05f21b4aa](https://github.com/kubernetes/kubeadm/assets/59379984/dbfac882-4926-4df9-b2c3-e21c957a7348) i tried a lot of ways to kill kubelet but it still ocupied port 10250

The screenshot says `Failed to kill`. Have you tried `sudo kill -9 <PID>`?
