### ISSUE TITLE
k8s-ha  how to join worker node to master node ,when master and worker node are in one machine

### ISSUE THREAD

**Issue by John402-cloud** [kubernetes/kubeadm#2219]
## Is this a request for help?
yes
If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): kubeadm-1.17.4

**Environment**:  
- **Kubernetes version** (use `kubectl version`): v1.17.4
- **Cloud provider or hardware configuration**: Dell PC
- **OS** (e.g. from /etc/os-release): CentOS 7.8
- **Kernel** (e.g. `uname -a`): Linux k8s-master-01 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

deploy k8s-ha ,when join worker node to master,which master and worker node are in one machine ，return this error:
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR DirAvailable--etc-kubernetes-manifests]: /etc/kubernetes/manifests is not empty
        [ERROR FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists
        [ERROR Port-10250]: Port 10250 is in use
        [ERROR FileAvailable--etc-kubernetes-pki-ca.crt]: /etc/kubernetes/pki/ca.crt already exists

## What you expected to happen?

I want master and worker node in one machine

**Comment by fabriziopandini** [comment]
NOTE: K8s is committed to be inclusive and to avoid potentially offensive words. so please replace master with control-plane

Might be I got this right, but kubeadm join can't be used to promote a worker node to control-plane node.
IF you want to reuse the same machine, please run kubeadm reset before kubeadm join
/triage support

**Comment by rosti** [comment]
@John402-cloud what do you mean by "when control-plane and worker node are in one machine"?
Do you have these nodes in separate VMs or containers running on the same physical machine? Or is it something else?

**Comment by John402-cloud** [comment]
@rosti 
in the same physical machine, deploy control-plane and worker node  ，not VMs

**Comment by John402-cloud** [comment]
@fabriziopandini 
if i use what you suggestion to kubeadm reset the node which i have deployed control-plane，is the node still  control-plane?

Due to resource constraints,what i want is to deploy control-plane and worker node in the same physical machine.

**Comment by SataQiu** [comment]
@John402-cloud I think you want to schedule the workloads to the control-plane node, you can do it by:
```sh
kubectl taint nodes <node-name> node-role.kubernetes.io/master-
```

**Comment by John402-cloud** [comment]
@SataQiu 
ths，i haved done according your suggestion。

**Comment by fabriziopandini** [comment]
> Due to resource constraints,what i want is to deploy control-plane and worker node in the same physical machine.

That's not possible (there should be only one kubelet running on a machine).
Want you can do, after creating a control-plane machine, is to remove the master label from the node so also the application workload can run on the same machine. See https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation for additional info

**Comment by rosti** [comment]
@John402-cloud I believe that @SataQiu and @fabriziopandini's answers should be the correct ones. Does that resolve your issue and can we close this one?

**Comment by John402-cloud** [comment]
it's ok, Thanks very much.

 

发件人: bounces+848413-2181-pzh1224=126.com@sgmail.github.com [mailto:bounces+848413-2181-pzh1224=126.com@sgmail.github.com] 代表 Rostislav M. Georgiev
发送时间: 2020年7月15日 17:27
收件人: kubernetes/kubeadm <kubeadm@noreply.github.com>
抄送: John402-cloud <pzh1224@126.com>; Mention <mention@noreply.github.com>
主题: Re: [kubernetes/kubeadm] k8s-ha how to join worker node to master node ,when master and worker node are in one machine (#2219)

 

@John402-cloud <https://github.com/John402-cloud>  I believe that @SataQiu <https://github.com/SataQiu>  and @fabriziopandini <https://github.com/fabriziopandini> 's answers should be the correct ones. Does that resolve your issue and can we close this one?
