### ISSUE TITLE
kubectl get componentstatus error with default init

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes/kubeadm#2222]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.
```
component status
cs
http://127.0.0.1:10252/healthz
```

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:56:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
AWS
- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- **Kernel** (e.g. `uname -a`):
```
Linux ip-10-0-193-187.us-west-2.compute.internal 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?
Ran `kubeadm init` with no other options

```
$ kubectl get componentstatus
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
etcd-0               Healthy     {"health":"true"}
```

`kube-scheduler` and `kube-controller-manager` are using the insecure port.
After https://github.com/kubernetes/kubernetes/pull/92720 the default `--port=0`.
I checked the pods themselves are using the correct secure ports for `liveness` checks.

## What you expected to happen?

Im not sure where the `componentstatus` configs are coming from so might not be really a `kubeadm` issue, but starting here.

## How to reproduce it (as minimally and precisely as possible)?
Installed with docker https://docs.docker.com/engine/install/centos/
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

## Anything else we need to know?
This also happens with `v1.17.9`.

**Comment by dkoshkin** [comment]
Found https://github.com/kubernetes/enhancements/issues/553#issue-297940643 so I understand if this is something that's not going to be addressed in kubeadm.

**Comment by neolit123** [comment]
we should start printing a warning in `kubect get componentstatus` that this API object is no longer supported and there are plans to remove it.

also this is not a kubeadm issue. if you'd like you can log a ticket in the kubernetes/kubernetes repository.

/close

**Comment by anu4love** [comment]
Please go through the cd /etc/kubernetes/manifests/ and change the port numbers in kube-scheduler.yaml and kube-controllermanager.yaml to the default specified in the document.
