### ISSUE TITLE
kinder: the latest etcd image cannot be pulled in the containerd base image

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2223]
the kinder base image (see [1]) we use with containerd for the kinder-regular-* jobs fails to pull the etcd image that was recently updated in https://github.com/kubernetes/kubernetes/pull/92349.

this a appears to be a ctr / containerd problem that i don't understand. possibly related to:
https://github.com/containerd/containerd/issues/3762

> In case anyone else reads this, I faced same issue with containerd 1.3.3 running in kata pod, turned out it was to do with `/var/lib` being on a 9p filesystem, which doesn't support `mknod`. For my use-case It was sufficient for to set `root = /run/containerd/root` and `state = /run/containerd/state` in the containerd config file, as `/run` is a `tmpfs` and I also got some performance improvements on image pulls that way (I do have plenty of memory to spare, at least at the moment).

more details in https://github.com/kubernetes/kubernetes/issues/93223

> ok, looks like there is a ctr / image layer problem:
> 
> ```
> DEBU[21:45:35] Running: [docker exec kind-build-8811a175-3bfe-4b62-80c7-c2c9ce5dd58d bash -c ctr image pull k8s.gcr.io/pause:3.2 > /dev/null] 
> DEBU[21:45:38] Running: [docker exec kind-build-8811a175-3bfe-4b62-80c7-c2c9ce5dd58d ctr image export /kind/images/pause.tar k8s.gcr.io/pause:3.2] 
> DEBU[21:45:38] Running: [docker exec kind-build-8811a175-3bfe-4b62-80c7-c2c9ce5dd58d ctr --namespace=k8s.io image import /kind/images/pause.tar --no-unpack] 
> DEBU[21:45:38] Running: [docker exec kind-build-8811a175-3bfe-4b62-80c7-c2c9ce5dd58d rm /kind/images/pause.tar] 
> DEBU[21:45:39] Running: [docker exec kind-build-8811a175-3bfe-4b62-80c7-c2c9ce5dd58d bash -c ctr image pull k8s.gcr.io/etcd:3.4.9-1 > /dev/null] 
> time="2020-07-19T18:46:20Z" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:ec3830e15d9c2ed4a38d301e352da36b792c3edf4d35d1fe9239c685dd15c1d7: failed to convert whiteout file \"usr/local/.wh..wh..opq\": operation not supported: unknown" key="extract-403197577-aEy0 sha256:bf2f2fdc8d35f212d09c046d50cbafc3fd0a1001455883c6b191b1169a15d389"
> ctr: failed to extract layer sha256:ec3830e15d9c2ed4a38d301e352da36b792c3edf4d35d1fe9239c685dd15c1d7: failed to convert whiteout file "usr/local/.wh..wh..opq": operation not supported: unknown
> ```
> 
> the pause image is pulled fine using `ctr image pull`, but the same command fails for the etcd image:
> 
> ```
> root@929c3b234f5b:/# ctr image pull k8s.gcr.io/pause:3.2
> k8s.gcr.io/pause:3.2:                                                             resolved       |++++++++++++++++++++++++++++++++++++++| 
> index-sha256:927d98197ec1141a368550822d18fa1c60bdae27b78b0c004f705f548c07814f:    done           |++++++++++++++++++++++++++++++++++++++| 
> manifest-sha256:4a1c4b21597c1b4415bdbecb28a3296c6b5e23ca4f9feeb599860a1dac6a0108: done           |++++++++++++++++++++++++++++++++++++++| 
> layer-sha256:c74f8866df097496217c9f15efe8f8d3db05d19d678a02d01cc7eaed520bb136:    done           |++++++++++++++++++++++++++++++++++++++| 
> config-sha256:80d28bedfe5dec59da9ebf8e6260224ac9008ab5c11dbbe16ee3ba3e4439ac2c:   done           |++++++++++++++++++++++++++++++++++++++| 
> elapsed: 1.7 s                                                                    total:  169.7  (99.7 KiB/s)                                      
> unpacking linux/amd64 sha256:927d98197ec1141a368550822d18fa1c60bdae27b78b0c004f705f548c07814f...
> done
> 
> root@929c3b234f5b:/# ctr image pull k8s.gcr.io/etcd:3.4.9-1
> k8s.gcr.io/etcd:3.4.9-1:                                                          resolved       |++++++++++++++++++++++++++++++++++++++| 
> index-sha256:735f090b15d5efc576da1602d8c678bf39a7605c0718ed915daec8f2297db2ff:    done           |++++++++++++++++++++++++++++++++++++++| 
> manifest-sha256:822af1b11c8ec54d5f861d0238b8376623cb4802bb7c983218d909a3814de3ef: done           |++++++++++++++++++++++++++++++++++++++| 
> layer-sha256:f46036bfc7b8d75b958bba04cc4854eba61344ce50d363ab942793deb02a307f:    done           |++++++++++++++++++++++++++++++++++++++| 
> layer-sha256:02a3f9ace3e1d9dd4caeb1c0f404da30214f97dad4766296dbb8593f5e4358a1:    done           |++++++++++++++++++++++++++++++++++++++| 
> layer-sha256:9fcd8c152ebf03542ecd7fc690c6ac6e25f4aed8033b805220df5bcf7a67d607:    done           |++++++++++++++++++++++++++++++++++++++| 
> config-sha256:d4ca8726196cb38bf43b87ccf73e19ed142799a30510f8d238d35cd4e00edf7e:   done           |++++++++++++++++++++++++++++++++++++++| 
> layer-sha256:38f4372b14d6d29dc7a9cf556122636e7b6181650185fc0152bc8c6ec421a8c5:    done           |++++++++++++++++++++++++++++++++++++++| 
> layer-sha256:9ff2acc3204b4093126adab3fed72de8f7bbfe332255b199c30b8b185fcf6923:    done           |++++++++++++++++++++++++++++++++++++++| 
> elapsed: 38.6s                                                                    total:  82.6 M (2.1 MiB/s)                                       
> unpacking linux/amd64 sha256:735f090b15d5efc576da1602d8c678bf39a7605c0718ed915daec8f2297db2ff...
> INFO[0039] apply failure, attempting cleanup             error="failed to extract layer sha256:ec3830e15d9c2ed4a38d301e352da36b792c3edf4d35d1fe9239c685dd15c1d7: failed to convert whiteout file \"usr/local/.wh..wh..opq\": operation not supported: unknown" key="extract-106035415-_MXS sha256:bf2f2fdc8d35f212d09c046d50cbafc3fd0a1001455883c6b191b1169a15d389"
> ctr: failed to extract layer sha256:ec3830e15d9c2ed4a38d301e352da36b792c3edf4d35d1fe9239c685dd15c1d7: failed to convert whiteout file "usr/local/.wh..wh..opq": operation not supported: unknown
> 
> root@929c3b234f5b:/# ctr version
> Client:
>   Version:  v1.3.0-20-g7af311b4
>   Revision: 7af311b4200b464a79c340b4e3a2799f8906ee8d
> 
> Server:
>   Version:  v1.3.0-20-g7af311b4
>   Revision: 7af311b4200b464a79c340b4e3a2799f8906ee8d
>   UUID: 1a60de6d-cd6b-4779-a1ae-d1114bc9d943
> 
> root@929c3b234f5b:/# echo $CONTAINERD_SNAPSHOTTER
> 
> root@929c3b234f5b:/# 
> ```
> 
> i don't understand if this is a problem with containerd or with the image contents (updated in #92349).
> but it appears k8s / containerd users will face the same problem.
> 
> maybe a ctr bug:
> [containerd/containerd#4086](https://github.com/containerd/containerd/issues/4086)
> [containerd/containerd#4099](https://github.com/containerd/containerd/pull/4099)

[1]
```
# task-00-pull-base-image
docker pull kindest/base:v20191105-ee880e9b

# task-01-add-kubernetes-versions
kinder build node-image-variant --base-image=kindest/base:v20191105-ee880e9b --image=kindest/node:test --with-init-artifacts=v1.20.0-alpha.0.245+363c3b89f57014 --loglevel=debug
```

**Comment by neolit123** [comment]
cc @fabriziopandini @BenTheElder

**Comment by BenTheElder** [comment]
kind side loads this image rather than pulling
We're also running much newer containerd and the data dir is a volume.

**Comment by neolit123** [comment]
i tried a number of things to try to resolve the "failed to convert whiteout file" problem, including:
- the suggestion here: https://github.com/containerd/containerd/issues/3762#issuecomment-608502595
- mounting /var/lib/containerd as volume
- the latest containerd beta

i think the right thing to do might be to not pull with the CR in the container, but rather pull the additional images (...config images list) on the host.

**Comment by BenTheElder** [comment]
this is what kind does in order to build the hermetic node image, though
I'd expect pulling to the node work on a running node.

**Comment by BenTheElder** [comment]
FWIW on `kind` (not kinder) at ~HEAD just now locally:
```console
$ docker exec -t kind-control-plane ctr image pull k8s.gcr.io/etcd:3.4.9-1
k8s.gcr.io/etcd:3.4.9-1:                                                          resolved       |++++++++++++++++++++++++++++++++++++++| 
index-sha256:735f090b15d5efc576da1602d8c678bf39a7605c0718ed915daec8f2297db2ff:    done           |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:822af1b11c8ec54d5f861d0238b8376623cb4802bb7c983218d909a3814de3ef: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:f46036bfc7b8d75b958bba04cc4854eba61344ce50d363ab942793deb02a307f:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:02a3f9ace3e1d9dd4caeb1c0f404da30214f97dad4766296dbb8593f5e4358a1:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:9fcd8c152ebf03542ecd7fc690c6ac6e25f4aed8033b805220df5bcf7a67d607:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:d4ca8726196cb38bf43b87ccf73e19ed142799a30510f8d238d35cd4e00edf7e:   done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:38f4372b14d6d29dc7a9cf556122636e7b6181650185fc0152bc8c6ec421a8c5:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:9ff2acc3204b4093126adab3fed72de8f7bbfe332255b199c30b8b185fcf6923:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 10.3s                                                                    total:  82.7 M (8.0 MiB/s)                                       
unpacking linux/amd64 sha256:735f090b15d5efc576da1602d8c678bf39a7605c0718ed915daec8f2297db2ff...
done
```
(the node image has `-1` pre-pulled, and also in k8s.io namespace)
