### ISSUE TITLE
kubeadm 1.16.13 from yum repo installs kubelet 1.18.6 as a dependency

### ISSUE THREAD

**Issue by MarkDeckert** [kubernetes/kubeadm#2226]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
1.16.13

## What happened?
I was updating cluster from 1.16.11 to 1.16.13.  Current version of kubelet was 1.16.11.  When I do a yum install kubeadm-1.16.13 from yum repository it wants to install kubelet 1.18.6 as a dependency.

```
Updating:
 kubeadm                                                      x86_64                                               1.16.13-0
 kubelet                                                      x86_64                                               1.18.6-0
Installing for dependencies:
 kubernetes-cni                                               x86_64                                               0.8.6-0
```

yum deplist kubeadm-1.16.13 shows the dependency as any kubelet higher than 1.13.0:
```
package: kubeadm.x86_64 1.16.13-0
  dependency: cri-tools >= 1.13.0
   provider: cri-tools.x86_64 1.13.0-0
  dependency: kubectl >= 1.13.0
   provider: kubectl.x86_64 1.18.6-0
  dependency: kubelet >= 1.13.0
   provider: kubelet.x86_64 1.18.6-0
  dependency: kubernetes-cni >= 0.8.6
   provider: kubernetes-cni.x86_64 0.8.6-0
```

But if I first install kubelet-1.16.13 then the kubeadm-1.16.13 install does not try to update it to 1.18.6.  Stumped as to why 1.16.11 doesn't seem to satisfy the >= 1.13.0 requirement.

Regardless, there should be an upper bound on dependency version since running a higher version of kubelet than apiserver is not a [supported configuration](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubelet).

## What you expected to happen?
kubelet dependency should not be allowed to be greater than kubeadm version at 1.16.13

## How to reproduce it (as minimally and precisely as possible)?
Without previously having kubelet-1.16.13 installed:
yum install kubeadm-1.16.13

**Comment by neolit123** [comment]
this is an issue with the k8s release packages.
please log the same issue in the kubernetes/release repository.

this related issue is still open here:
https://github.com/kubernetes/kubernetes/issues/92586

thanks
/close
