### ISSUE TITLE
remove "WARNING: kubeadm cannot validate component configs for API groups"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2230]
there were a number of cases in the #kubeadm slack channel where users are asking why they are getting this warning for commands that do not accept `--config` - e.g. `kubeadm token ...`

ideally the warning should be printed only if the user has provided a `--config`, but i'm pretty sure this logic is difficult to untangle, so we should instead just remove this warning or hide it behind a higher verbosity (e.g. `klog.V(1).Infof(....)`).

cc @rosti
/help
/kind cleanup
/priority backlog
/milestone v1.20

**Comment by neolit123** [comment]
the warning line is located here:
https://github.com/kubernetes/kubernetes/blob/af29f81af6f5afc0ad48cd2d3d5472a9ca4d4cc8/cmd/kubeadm/app/componentconfigs/configset.go#L348

**Comment by ZhiFeng1993** [comment]
Just for records, several slack discussions are: 
https://kubernetes.slack.com/archives/C2P1JHS2E/p1578407862006800
https://kubernetes.slack.com/archives/C2P1JHS2E/p1595445960138200

**Comment by pramodsharma62** [comment]
Is there any fix for this yet? I am having the same issues.

**Comment by ZhiFeng1993** [comment]
> Is there any fix for this yet? I am having the same issues.

We've made the fix in v1.19. In the meantime, you can find the troubleshooting item here: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubeadm-upgrade-plan-prints-out-context-deadline-exceeded-error-message

**Comment by neolit123** [comment]
> Is there any fix for this yet? I am having the same issues.

the warning itself is not an issue, it's just warning that kubeadm no longer validates the KubeletConfiguration, KubeProxyConfiguration that it feeds to the kubelet, kube-proxy components.

> context deadline exceeded

this is a separate problem around `kubeadm plan` not fetching the etcd versions properly for external etcd clusters.
