### ISSUE TITLE
After upgrade from 1.16.2 to 1.17.4 default KubeletConfiguration values changed.

### ISSUE THREAD

**Issue by jvanz** [kubernetes/kubeadm#2233]
## Versions

**kubeadm version** (use `kubeadm version`):

```
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-17T12:00:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-12-16T12:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`):

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-12-16T12:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-12-16T12:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- **OS** (e.g. from /etc/os-release):
```
cat /etc/os-release
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"
```

- **Kernel** (e.g. `uname -a`):
`Linux 010084072091 4.12.14-197.34-default #1 SMP Tue Feb 25 13:00:08 UTC 2020 (3701ec1) x86_64 x86_64 x86_64 GNU/Linux`

## What happened?

When the user upgrade a  cluster running  k8s/kubeadm from 1.16.2 to 1.17.4, the default value for the volumeStatAggPeriod changed from '1m' to '0s'.  I believe this happen due a change in the component config.  But I do not know if this is the expected behavior or not. I could not find any documentation which indicates this is a real problem or not.  This is more like a question about what we should expect than a bug report. ;)

This is a change that I think is related:
```
commit 994df0d6318759a6de6e3ae18a4ef6cd98fb102b
Author: Rostislav M. Georgiev <rostislavg@vmware.com>
Date:   Wed Jun 19 16:12:26 2019 +0300

    kubeadm: use versioned component configs
    
    This change removes dependencies on the internal types of the kubelet and
    kube-proxy component configs. Along with that defaulting and validation is
    removed as well. kubeadm will display a warning, that it did not verify the
    component config upon load.
    
    Signed-off-by: Rostislav M. Georgiev <rostislavg@vmware.com>
```

## What you expected to happen?

I would expect that after an upgrade the value keep the same.

## How to reproduce it (as minimally and precisely as possible)?

From a cluster running k8s 1.16.2 upgrade it to 1.17.4 using kubeadm

**Comment by neolit123** [comment]
thank you for logging the ticket.
what happened there is that kubeadm has to move out of kubernetes / kubernetes at some point and for that reason it had to stop importing the `pkg` folder of k/k where the "internal" types for kubelet and kube-proxy reside. without "internal" types kubeadm can no longer apply the defaults for these components, that you can see here:

https://godoc.org/k8s.io/kubelet/config/v1beta1
```
    // How frequently to calculate and cache volume disk usage for all pods
    // Dynamic Kubelet Config (beta): If dynamically updating this field, consider that
    // shortening the period may carry a performance impact.
    // Default: "1m"
    // +optional
    VolumeStatsAggPeriod metav1.Duration `json:"volumeStatsAggPeriod,omitempty"`
```

so the field just ends up defaulting to 0s on the side of kubeadm (where the golang struct is constructed).
but then once you pass this config to the component (e.g. kubelet), it sees some of these values are not user modified (on a best effort, when fields are not pointers) and then defaults them. so technically once your componentconfig reaches the component that value should end up being 1s.

are you not observing this behavior?

/triage support
/assign @rosti
PTAL, to double check my understanding.

**Comment by rosti** [comment]
Actually all fields that contain Go Lang default values (nil, 0, "", etc.) are now defaulted by the components themselves.
As @neolit123 mentioned, previously kubeadm imported defaulting code from the target components (in this case - the kubelet). However, this is no longer possible, nor is it required. Hence, it's best to leave defaulting to the components themselves (again, in this case - the kubelet).

Unfortunately, currently the kubelet config is lacking some `omitempty` tags to its defaulted fields. Hence, these would always appear as "noise" in the config.

@jvanz does this cause any issue on your side? It shouldn't in theory. If there is one, then it's a bug.

@mtaufen We should possibly add more `omitempty`s to the kubelet config and/or come up with some sort of a generic policy for component configs.

**Comment by neolit123** [comment]
there is nothing actionable on the side of kubeadm for the time being.
closing, but we can continue the discussion.

**Comment by mtaufen** [comment]
@rosti which fields?

I know we don't put it on non-pointer substructures, but IIRC that's because omitempty is meaningless for non-pointer substructures (only applies to "false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string" per https://golang.org/pkg/encoding/json/). Maybe we need to make some of the substructures pointers?

**Comment by jvanz** [comment]
This cause an issue in a cluster. Because the kubelet was using the `--c
onfig=/var/lib/kubelet/config.yaml` flag. But as the file has the `0` value in the configuration, which means that the feature was disabled,  it was not possible to get the kubelet volume metrics.

**Comment by mtaufen** [comment]
Kubelet still defaults volumeStatsAggPeriod to 1 minute, so not sure why you're getting 0:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults.go#L141-L143

**Comment by jvanz** [comment]
> Kubelet still defaults volumeStatsAggPeriod to 1 minute, so not sure why you're getting 0:
> https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults.go#L141-L143

Has not kubeadm move away from the kubelet config from `pkg` package? See https://github.com/kubernetes/kubeadm/issues/2233#issuecomment-663169016

**Comment by neolit123** [comment]
@jvanz do you have proof that the kubelet did not default the field to 1m, when the --config file that is passed to it contained 0?

**Comment by jvanz** [comment]
> @jvanz do you have proof that the kubelet did not default the field to 1m, when the --config file that is passed to it contained 0?

I'll run an update again and try to write a reproduce steps. What I can share now is something more simple. In one node of the cluster I can see this:

```
$kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-12-16T12:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

$kubeadm config print init-defaults --component-configs KubeletConfiguration
[...]
serializeImagePulls: true
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
topologyManagerPolicy: none
volumeStatsAggPeriod: 1m0s
```

After that, I've updated the kubeadm package and ran the same command again:

```
$kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-17T12:00:00Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

$kubeadm config print init-defaults --component-configs KubeletConfiguration
[...]
nodeStatusUpdateFrequency: 0s
rotateCertificates: true
runtimeRequestTimeout: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

I do not know if this means something. But at least is possible to see a change in the configuration value.

**Comment by neolit123** [comment]
> But at least is possible to see a change in the configuration value.

hi, this shows that kubeadm can no longer default KubeletConfiguration using its internal mechanism. as discussed above, if a value is not set (e.g. `0s` or `nil`) then once you pass this file to the kubelet binary it should default it.

> do you have proof that the kubelet did not default the field to 1m, when the --config file that is passed to it contained 0?

if you happen to pass a file that is not defaulted (e.g. generated by newer kubeadm), but confirm that a certain value is not defaulted (e.g. 0s -> 1m) then we have a kubelet compomentconfig defaulting bug (i doubt this is the case).
