### ISSUE TITLE
kubeadm init fails when I use --apiserver-advertise-address

### ISSUE THREAD

**Issue by SAshish19** [kubernetes/kubeadm#2241]
## Is this a request for help?

YES
If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?
--apiserver-advertise-address
If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):1.14

**Environment**:Bare Metal
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Bare Metal RHEL 7.7
- **OS** (e.g. from /etc/os-release):RHEL 7.7
- **Kernel** (e.g. `uname -a`):
Linux 3.10.0-1062.e17.x86_64

- **Others**:

## What happened?
kubeadm init --apiserver-advertise-address=<Load balancer IP> failed
I am Installing a standalone kubernetes cluster (kubeadm version is 1.14) on RHEL 7.7 Operating System. I have got a Load Balancer (Private LB with a private IP address) configured for my Kubernetes master node. When I issued the command

kubeadm init --apiserver-advertise-address= I got the below error:

Unable to register node "master node name" with API Server. write tcp "IP address of masternode":<52444>--"IP address of LB":6443. Connection reset by peer.

If I issue only kubeadm init, the command successfully initiates the cluster.

Also, If I use the DNS of the LB and try to create a multi-plane cluster (using controlPlaneEndpoint as DNS of the LB), that also works. Any idea on why only with the --apiserver-advertise-address it fails?

Also, what if I use the method of creating a multi-plane cluster (controlPlaneEndpoint) but use the cluster that is built as a standalone cluster? (i.e., not adding any further master nodes). Will it cause any issues?
## What you expected to happen?
Expected to kubeadm init to complete

## How to reproduce it (as minimally and precisely as possible)?
a single master node with a Load Balancer

**Comment by neolit123** [comment]
hello,

>  (kubeadm version is 1.14) 

this is not a kubernetes/kubeadm supported version. please upgrade to 1.17. 1.16 is going out of support too in August.

> Also, If I use the DNS of the LB and try to create a multi-plane cluster (using controlPlaneEndpoint as DNS of the LB), that also works. Any idea on why only with the --apiserver-advertise-address it fails?

this seems like a general network setup issue. for general feedback on these you could try discussing with other users at #kubeadm on k8s slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

> Also, what if I use the method of creating a multi-plane cluster (controlPlaneEndpoint) but use the cluster that is built as a standalone cluster? (i.e., not adding any further master nodes). Will it cause any issues?

using controlPlaneEndpoint for a single control-plane node is fine.
you can find more details here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#considerations-about-apiserver-advertise-address-and-controlplaneendpoint

/close
/triage support
