### ISSUE TITLE
Kinder: add flag for forcing the kubeadm config version

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#2249]
As discussed in https://github.com/kubernetes/kubeadm/pull/2248#discussion_r466457798, due to external reasons, we are removing "v1beta1" from the kubeadm test grid is kind of worrying because it is still used in CAPI.

We should consider adding a new flag to kinder for forcing the config version to use and add dedicated tests for this (v1.16 with v1beta1, v1.17 with v1beta1 etc)

**Comment by neolit123** [comment]
overall i'm -1 for this.

i really wish for us to stay on schedule for removal of deprecated v1beta1 API in 1.20.
wouldn't CAPI e2e provide signal for it if CAPI still wishes to use it?

**Comment by neolit123** [comment]
ok, maybe we can just shift the 1.16 and 1.17 kinder jobs to use this flag, but leave 1.18 and newer use v1beta2?

**Comment by fabriziopandini** [comment]
Yep. this should not affect out schedule for v1beta1 deprecation
My intention is only to have test coverage about the fact that the older version are actually capable to start a cluster given a v1beta1 config (and there are no regressions on this capability)
