### ISSUE TITLE
Apt packages < 1.6 removed from repo

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kubeadm#225]
We relied on 1.5.x release packages as part of our internal machine provisioning process. It seems these packages where removed from `apt.kubernetes.io`. Only 1.6 is available now. Were they removed for a reason and should we plan for such things going forward?

**Comment by overip** [comment]
is it possible to get the packages back please?
Thank you.

**Comment by luxas** [comment]
https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages shows that packages for different v1.5 flavors are available.

kubeadm v1.5 was removed due to the alpha status and the known issues with it.

No more packages will be removed; kubeadm v1.5 (v1.6.0-alpha.0-2074 for real but) was a special case and removed, but kubeadm v1.6 won't be

**Comment by ahawkins** [comment]
@luxas Yes the 1.5 flavors are available, but not for `kubeadm`. The repo includes `kubectl` and `kubelet`, but not `kubeadm`.

**Comment by v1k0d3n** [comment]
@luxas i have a lot of concern over this. our project (a large effort with Openstack) is based on 1.5 and 1.6, being extremely fresh, requires a lot of planning for this effort.

**Comment by luxas** [comment]
@ahawkins @v1k0d3n You should really be aware of the security concerns then if you insist to use kubeadm for v1.5. Are you?

BTW; I have no access to these repos. @mikedanese has and might add the kubeadm v1.5 stable version back if you have a lot of concerns if you talk kindly to him. However, please please be aware of that kubeadm v1.5 is marked alpha for a reason. We're constantly improving it, and for example the security side got _a lot_ better in v1.6. Also we promise CLI backwardscompat with v1.6.

We're aiming to have the implementation beta, graduate more of the stuff we're depending on and add upgrades in v1.7

**Comment by intlabs** [comment]
@luxas I'm aware of many of the concerns, though quite possibly not all. Kubeadm is important for us, not for use anywhere near production, but just because it helps us get a development k8s cluster up and running easily - the perfect use case for an alpha insecure tool :)

**Comment by v1k0d3n** [comment]
@luxas "You should really be aware of the security concerns then if you insist to use kubeadm for v1.5. Are you?"

definitely aware of it. it makes me hurt a little on the inside to accept this "as is" right now, but our current CI...and even our instructions for demonstrations are drafted for 1.5.x deb-based kubeadm installs *for now*. it will take a little bit to bring everything in line with 1.6, but it's on our near term roadmap. the reality is that we need a little bit of time between kubeadm releases...or at least a declared roadmap we can follow for removal of previous versions.

**Comment by buddy-yao** [comment]
I need kubeadm v1.5 !!! because i need use helm.

**Comment by pichouk** [comment]
One use case where it is useful to still have access to `kubeadm` version `1.5.6` : test upgrade to `1.6.0`.
I currently have a `1.5.6` Kubernetes cluster in production and I want to test the upgrade an upgrade from `1.5` to `1.6` before upgrading production environment. So I need the `1.5.6` version of `kubeadm` to easily reproduce my actual environnement.

**Comment by ahawkins** [comment]
> No more packages will be removed; kubeadm v1.5 (v1.6.0-alpha.0-2074 for real but) was a special case and removed, but kubeadm v1.6 won't be

@luxas Thanks for clarifying this. This is a good news going forward.

**Comment by timothysc** [comment]
@mikedanese how are you guys managing your repos?  Sounds like we need a repo per version similar to how OS's distribute.  1.5.x, 1.6.x, -testing

**Comment by mikedanese** [comment]
This is already done:
https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages
