### ISSUE TITLE
Allow to configure cluster name in the kubeconfig generated using kubeadm command

### ISSUE THREAD

**Issue by prabhu43** [kubernetes/kubeadm#2258]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.18.8

## What happened?
Creation of kubeconfig using `kubeadm alpha kubeconfig user` command generated a kubeconfig. But it always has `kubernetes` as cluster name. But the cluster name of my cluster is different, configured via kubeadm config `ClusterConfiguration`. 

## What you expected to happen?

Make the cluster name configurable from `kubeadm alpha kubeconfig user` command 

## Anything else we need to know?
When we use this command to generate kubeconfig for multiple clusters with different cluster names, this kubeconfig has same cluster name `kubernetes`. This causes the confusion when merging all those kubeconfig files together.

**Comment by fabriziopandini** [comment]
AFAIK this alpha command currently does not access the cluster for retrieving info, but it relies on command line flags only, and therefore I would like to better understand from @prabhu43 how he is expected we should to bring into the picture "ClusterConfiguration", especially in a "multiple cluster" scenario, and how we should manage flag/ClusterConfiguration conflicts.

TBH, personally I'm not really concerned about the name of the config used inside the kubeconfig (it is not exposed to the user), given that we are generating separated kubeconfig files for each user/cluster. 
But I will be more than happy to understand why there is a specific concern for having different cluster names, and to consider this change if this is something that could be useful to other users as well.

**Comment by neolit123** [comment]
users wish to combine multiple clusters in the same kubeconfig files for context switching, in which case all clusters created by kubeadm can end up being called "kubernetes". ClusterConfiguration can be used to change the cluster name, but if users wish to generate additional users for those clusters, the "kubernetes" cluster name is pinned.

see here and discussion bellow:
https://github.com/kubernetes/kubeadm/issues/1381#issuecomment-505635063

**Comment by prabhu43** [comment]
+1 to @neolit123
