### ISSUE TITLE
kubeadm init fails with node * not found when used with containerd, works perfect with Docker

### ISSUE THREAD

**Issue by alexcpn** [kubernetes/kubeadm#2262]
## What keywords did you search in kubeadm issues before filing this one?

Similar to
https://github.com/kubernetes/kubeadm/issues/1153

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:10:16Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

- **Kubernetes version** (use `kubectl version`):

root@k8s-storage-1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
VM  -Openstack

- **OS** (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"

- **Kernel** (e.g. `uname -a`):

4.15.0-96-generic
- **Others**:

## What happened?

Installed Containerd. Set Config properly 

Printed the default config 'kubeadm config print init-defaults >config.yam' and updated sections for containerd

```
 criSocket: /run/containerd/containerd.sock
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
```

Did 'kubeadm intit --config=config.yaml'

Kubeadm failed waiting for kubelet service to start.(Checked kubelet configuration yaml - it has systemd properly set)

Error in Logs, repeating forever
```
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.271977    4306 kubelet.go:2268] node "k8s-storage-1" not found
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: I0827 04:51:20.281185    4306 kubelet_node_status.go:70] Attempting to register node k8s-storage-1
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.281471    4306 kubelet_node_status.go:92] Unable to register node "k8s-storage-1" with API s
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.372328    4306 kubelet.go:2268] node "k8s-storage-1" not found
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.375398    4306 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:526: Failed to lis
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.472500    4306 kubelet.go:2268] node "k8s-storage-1" not found
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.572708    4306 kubelet.go:2268] node "k8s-storage-1" not found

```

## What you expected to happen?

Kubeadm to be successful

## How to reproduce it (as minimally and precisely as possible)?
Install Contianerd
Use kubeadm init with config file

## Anything else we need to know?

Did kubeadm reset, and installed with `kubeadm init --pod-network-cidr=10.244.0.0/16`

Everything worked. Note using config.yaml I could not give pod-nw-cidr in command line nor could find a place in configspec to add that. Thats the only difference.

```
Output with Docker used

kubeadm join 192.168.0.6:6443 --token u1u3s2.mcj5xcso4jy7kyy8 \
    --discovery-token-ca-cert-hash sha256:994e6a....
```

[config_containerd.zip](https://github.com/kubernetes/kubeadm/files/5134235/config_containerd.zip)
[config_docker.zip](https://github.com/kubernetes/kubeadm/files/5134236/config_docker.zip)

**Comment by neolit123** [comment]
Hi what is the full log of kubeadm init ( add --v=4 to the command)? Also
share the full kubelet log with: journalctl -xeu kubelet.

**Comment by alexcpn** [comment]
Sorry , I had reset kubeadm and reinstalled with docker. I don't have other logs now

**Comment by neolit123** [comment]
this seems the same issue as:
https://github.com/kubernetes/kubeadm/issues/2259
where containerd is failing, it does not seem like a kubeadm problem but a problem where the kubelet / containerd combination cannot create a Node object.

/close

**Comment by alexcpn** [comment]
@neolit123  the logs for #2259  ->https://pastebin.com/AFLYSXKT does not look anyway like the kubelet logs.

```
ug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.271977    4306 kubelet.go:2268] node "k8s-storage-1" not found
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: I0827 04:51:20.281185    4306 kubelet_node_status.go:70] Attempting to register node k8s-storage-1
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.281471    4306 kubelet_node_status.go:92] Unable to register node "k8s-storage-1" with API s
Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.372328    4306 kubelet.go:2268] node "k8s-storage-1" not found
`````

 You are right this may not be a kubeadm problem, but of kubelet and contained, I rather thought I could log the issue here

**Comment by neolit123** [comment]
> Aug 27 04:51:20 k8s-storage-1 kubelet[4306]: E0827 04:51:20.281471    4306 kubelet_node_status.go:92] Unable to register node "k8s-storage-1" with API s

what is the full error line here?

> You are right this may not be a kubeadm problem, but of kubelet and contained, I rather thought I could log the issue here

true, it usually ends up being some sort of a kubelet / CR bug or just the host node being incompatible with the kubelet in some way but the kubelet not reporting it properly.
