### ISSUE TITLE
kubeadm release-1.6 branch e2e failing a Conformance test

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#227]
Our CI job for kubeadm e2e against the release-1.6 branch went from green to red on 2017/04/04.

Last green run:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-6/5

Ignoring the timeout on run 6, the first run with a failing Conformance test is:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-6/7

The same Conformance test ([k8s.io] Downward API should provide pod and host IP as an env var [Conformance]) has now failed three times in a row with different commits to the branch.

All runs:
https://k8s-testgrid.appspot.com/google-gce#gce-kubeadm-1.6

**Comment by krousey** [comment]
It appears that this PR is needed for that test to work: https://github.com/kubernetes/kubernetes/pull/42717

**Comment by pipejakob** [comment]
So far, it looks like this isn't an actual regression, but a problem with our `release-1.6` e2e job, which might be using e2e tests from the master branch instead of the release-1.6 branch.

**Comment by pipejakob** [comment]
We've been able to confirm that prow pulls the correct branch when triggering this job, but then kubetest extracts the latest CI artifacts when running the job, which is why it's picking up a Conformance test from master. We'll need to adjust the job to either pass a different extraction strategy to kubetest, or a JENKINS_USE_* flag to e2e-runner.sh to do it for us.

Since we're only seeing this single Conformance test failure for kubeadm, I don't think this should block new patch releases (although we should verify that the e2e run against the candidate commit only fails this specific Conformance test).

**Comment by pipejakob** [comment]
The linked PR to fix this is merged. I'm not sure if there's a good way to forcibly trigger postsubmit jobs on prow to rerun the e2e against the same commit again, but I'll keep this issue open until the next run proves green.

**Comment by pipejakob** [comment]
We have a completely green run of the release-1.6 e2e now. Closing.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-6/10
