### ISSUE TITLE
kubeadm tries to call "docker info" even if the CRI socket was for another CR

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2270]
this warning can be seen even if the user specified the containerd socket or if they let kubeadm detect the socket:

> W0831 17:19:34.759405     352 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH

we should try not showing the warning, for CRI != docker.

**Comment by neolit123** [comment]
did some quick investigation:
this gets called by the kubelet.go, so it must be this blob:
https://github.com/kubernetes/kubernetes/blob/f2e3154a140dc192760a5cf8c01f8044e1aa867b/cmd/kubeadm/app/componentconfigs/kubelet.go#L196-L209

so this can happen only if `nodeRegOpts.CRISocket` ends up being `constants.DefaultDockerCRISocket`. the Cluster API test runs that were were looking at were letting kubeadm autodetect the socket on kubeadm join, and the logs did include a containerd socket being detected, but this `docker info` message was present, which suggests that nodeRegOpts.CRISocket is set to a docker socket somehow.

kubeadm's cri socket detection code is here:
https://github.com/kubernetes/kubernetes/blob/6aa4c7eca83b74076ae24afde5edff7d932b854e/cmd/kubeadm/app/util/runtime/runtime.go#L190-L229

cc @rosti

**Comment by sumitKash** [comment]
I am interested in knowing whether we can create Kubernetes cluster on production environment using Kubeadm alone on bare metal server.
Nobody on internet seems to give the clear answer(not even kubernetes docs) whether one can spin-up a Kubernetes Cluster on production using Kubeadm alone. Yes we have Kubespray that used kubeadm in the backgroud,but it do too much generic configuration, not to mention that you need to go through so many playbooks in order to understand it.

Do people really use Kubeadm for Kubernetes cluster deployment on production?

**Comment by neolit123** [comment]
@SataQiu thanks for the PR updates, @rosti should be back next week and i can take a look at it again myself then.

**Comment by neolit123** [comment]
@sumitKash 

kubeadm has existed for quite some time now and it is being used in production, on bare metal or any infrastructure out there.
some users might consider it too complex, but that is because it is low-level and has a lot of settings. higher level demanding users might prefer to use something like kube-spray or the Cluster API. so there is a trade off.

to get more feedback you can open this discussion in the #kubeadm slack channel.

**Comment by sumitKash** [comment]
Thanks for replying @neolit123. Unfortunatly, I got no answer there. 
So using kubeadm alone on production server is considered as a good practice ? Going throught Kubernetes docs it says that Kubeadm for quick setup and more confusing is, a two year blog on kubenetes.io hints that it is a good tool for system administrator to spin up the cluster.

**Comment by neolit123** [comment]
i can give you a biased response, so i recommend you use the support channels to get feedback from other people:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
we have slack, mailing lists, forums, etc.
