### ISSUE TITLE
could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt

### ISSUE THREAD

**Issue by Bugs-Resolver** [kubernetes/kubeadm#2285]
Bug report:
could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get https://dl.k8s.io/release/stable-1.txt: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Versions 
**kubeadm version** (use `kubeadm version`):v1.7.3

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): centos7
- **Kernel** (e.g. `uname -a`): 4.4
- **Others**:
cannot successfully pull from dl.k8s.io

**Comment by neolit123** [comment]
opening this link works for me:
https://dl.k8s.io/release/stable-1.txt
works from kubeadm too.

you should check if your node has access to the above link.

> kubeadm version (use kubeadm version):v1.7.3

if that is truly 1.7 (not 1.17) this has been out of support for a while. please upgrade to 1.17.x at minimum.

/triage support
/close
