### ISSUE TITLE
remove the v1beta1 configuration API

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2286]
the v1beta1 configuration API was deprecated in 1.17:
https://github.com/kubernetes/kubernetes/commit/3a050344d0e6475ec7ead775f3f1db32bc837c83

and is scheduled for removal in 1.20 (N+3 after the deprecation):
https://kubernetes.io/docs/reference/using-api/deprecation-policy/

suggested PR release note:
> action required: kubeadm: remove the v1beta1 component configuration. Please use "kubeadm config migrate" to migrate your configuration files on disk to v1beta2.

**Comment by neolit123** [comment]
note: still to be confirmed during the kubeadm office hours / planning session for 1.20.

**Comment by neolit123** [comment]
after the discussion this was punted to 1.21.

**Comment by fabriziopandini** [comment]
We should check again this at the SCL level, especially WRT to CAPI v1alpha4 progress

**Comment by pacoxu** [comment]
@neolit123  will this happen in 1.21?

If so, I will work on it this week.

**Comment by fabriziopandini** [comment]
Work I CAPI is happening right now, but we should check how the release schedule fits together in order to avoid problems to the users. Let's discuss this in the CAPI meeting again before green lighting removal

**Comment by pacoxu** [comment]
@fabriziopandini OK.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/101129 seems to have fixed this.

**Comment by fabriziopandini** [comment]
As per comment above
/close
