### ISSUE TITLE
kubeadm join fail,messge: couldn't validate the identity of the API Server: unknown hash format " sha256"

### ISSUE THREAD

**Issue by daiguanglin** [kubernetes/kubeadm#2288]
docker version:18.09.6
kubunate version:47.93.226.77
fail message:
 [preflight] found NodeName empty; using OS hostname as NodeName
[preflight] Running pre-flight checks
I0914 17:51:00.439015   11786 preflight.go:91] [preflight] Running general checks
I0914 17:51:00.439061   11786 checks.go:254] validating the existence and emptiness of directory /etc/kubernetes/manifests
I0914 17:51:00.439098   11786 checks.go:292] validating the existence of file /etc/kubernetes/kubelet.conf
I0914 17:51:00.439114   11786 checks.go:292] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0914 17:51:00.439124   11786 checks.go:105] validating the container runtime
        [WARNING CRI]: container runtime is not running: output: time="2020-09-14T17:51:00+08:00" level=fatal msg="getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
, error: exit status 1
I0914 17:51:00.443919   11786 checks.go:382] validating the presence of executable crictl
I0914 17:51:00.443947   11786 checks.go:341] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0914 17:51:00.443976   11786 checks.go:341] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0914 17:51:00.443998   11786 checks.go:653] validating whether swap is enabled or not
I0914 17:51:00.444022   11786 checks.go:382] validating the presence of executable ip
I0914 17:51:00.444038   11786 checks.go:382] validating the presence of executable iptables
I0914 17:51:00.444053   11786 checks.go:382] validating the presence of executable mount
I0914 17:51:00.444069   11786 checks.go:382] validating the presence of executable nsenter
I0914 17:51:00.444084   11786 checks.go:382] validating the presence of executable ebtables
I0914 17:51:00.444098   11786 checks.go:382] validating the presence of executable ethtool
I0914 17:51:00.444112   11786 checks.go:382] validating the presence of executable socat
I0914 17:51:00.444128   11786 checks.go:382] validating the presence of executable tc
I0914 17:51:00.444141   11786 checks.go:382] validating the presence of executable touch
I0914 17:51:00.444161   11786 checks.go:524] running all checks
I0914 17:51:00.447664   11786 checks.go:412] checking whether the given node name is reachable using net.LookupHost
I0914 17:51:00.448016   11786 checks.go:622] validating kubelet version
I0914 17:51:00.488600   11786 checks.go:131] validating if the service is enabled and active
I0914 17:51:00.493983   11786 checks.go:209] validating availability of port 10250
I0914 17:51:00.494092   11786 checks.go:292] validating the existence of file /etc/kubernetes/pki/ca.crt
I0914 17:51:00.494105   11786 checks.go:439] validating if the connectivity type is via proxy or direct
I0914 17:51:00.494136   11786 join.go:433] [preflight] Discovering cluster-info
error execution phase preflight: couldn't validate the identity of the API Server: unknown hash format " sha256"

**Comment by neolit123** [comment]
your join command line should look like:
```
kubeadm join --discovery-token abcdef.1234567890abcdef --discovery-token-ca-cert-hash sha256:1234..cdef 1.2.3.4:6443
```

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

/close
/triage support
