### ISSUE TITLE
multi network iface install with kubeadm custom advertise-address problem

### ISSUE THREAD

**Issue by oldthreefeng** [kubernetes/kubeadm#2289]
## Versions

**kubeadm version** (use `kubeadm version`):  
```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:56:30Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```
uname  -a
Linux dev-k8s-master 4.4.228-2.el7.elrepo.x86_64 #1 SMP Sun Jun 21 15:00:19 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

i have tow network iface. `192.168.160.243` is pubilc network route.  `192.168.253.129` is a internal IP. 

```
 $ ip a |grep inet 
    inet 127.0.0.1/8 scope host lo
    inet 192.168.253.129/24 brd 192.168.253.255 scope global noprefixroute dynamic ens32
    inet 192.168.160.243/23 brd 192.168.161.255 scope global noprefixroute ens33
```

default route  is 

```
$ ip route show | grep default
default via 192.168.160.1 dev ens33
```

## What happened?

use a exsit `kubeadm-config.yaml` to start a kubernetes cluster. 

```
$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.253.129 apiserver.cluster.local
$ cat kubeadm-config.yaml 
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.18.0
controlPlaneEndpoint: apiserver.cluster.local:6443
imageRepository: k8s.gcr.io
networking:
  # dnsDomain: cluster.local
  podSubnet: 100.64.0.0/10
  serviceSubnet: 10.96.0.0/12
apiServer:
  certSANs:
  - 127.0.0.1
  - apiserver.cluster.local
  - 192.168.253.129
  - 10.103.97.2
  extraArgs:
    advertise-address: 192.168.253.129
    feature-gates: TTLAfterFinished=true
  extraVolumes:
  - name: localtime
    hostPath: /etc/localtime
    mountPath: /etc/localtime
    readOnly: true
    pathType: File
controllerManager:
  extraArgs:
    feature-gates: TTLAfterFinished=true
    experimental-cluster-signing-duration: 876000h
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    readOnly: true
    pathType: File
scheduler:
  extraArgs:
    feature-gates: TTLAfterFinished=true
  extraVolumes:
  - hostPath: /etc/localtime
    mountPath: /etc/localtime
    name: localtime
    readOnly: true
    pathType: File
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
ipvs:
  excludeCIDRs: 
  - 10.103.97.2/32
```

init cmd

```
$ kubeadm  init --config kubeadm-config.yaml
...

```
## What you expected to happen?

 **then i found `kube-apiserver.yaml `  the annotations endpoints get my default route ip address `192.168.160.243` .  how to solve this problem**

```
cat /etc/kubernetes/manifests/kube-apiserver.yaml 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 192.168.160.243:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.253.129
....
```

## How to reproduce it (as minimally and precisely as possible)?

like i said. 

## Anything else we need to know?

when i have two network iface. install a kubernetes HA-cluster like a huge challenge.

**Comment by neolit123** [comment]
/triage support

> when i have two network iface. install a kubernetes HA-cluster like a huge challenge.

kubeadm and the kubelet both default to use the public interface and there is no way to change that.
we have no plans allow the users to pick an interface for the time being.

to make kubeadm use the advertise-address everywhere you should remove the flag `advertise-address: 192.168.253.129` under `extraArgs` and add:

```
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.253.129"
  bindPort: 6443
---
kind: ClusterConfiguration
....
---
...
...

you need to do the same for joining CP nodes.

```
kind: JoinConfiguration
controlPlane:
  localAPIEndpoint:
    advertiseAddress: "some-address"
    bindPort: 6443
```

please reopen the ticket if this does not work for you or if you have more questions.

**Comment by oldthreefeng** [comment]
thanks so much. 
another question is about etcd-ha.  like kube-apiserver. 
`localAPIEndpoint` do solve the annotations problem.  great !!

**Comment by neolit123** [comment]
> another question is about etcd-ha

can you please clarify?

**Comment by oldthreefeng** [comment]
the kubeconfig file like this. 

```
$ cat  kubeadm-config.yaml
...
etcd:
  local:
    serverCertSANs:
    - 192.168.253.129
    - 192.168.253.128
    peerCertSANs:
    - 192.168.253.129
    - 192.168.253.128
    extraArgs:
      initial-cluster: dev-k8s-master=https://192.168.253.129:2380
      initial-cluster-state: new
      name: dev-k8s-master
      listen-peer-urls: https://192.168.253.129:2380
      listen-client-urls: https://192.168.253.129:2379
      advertise-client-urls: https://192.168.253.129:2379
      initial-advertise-peer-urls: https://192.168.253.129:2380
...
```
then init  `kubeadm init --config  kubeadm-config.yaml`

the manifest file will be shown like this..

```
[root@dev-k8s-master ~]# cat /etc/kubernetes/manifests/etcd.yaml 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://192.168.160.243:6443
```

with the `localAPIEndpoint` set . the annotations turns to `https://192.168.253.129:2379`.

**Comment by neolit123** [comment]
> with the localAPIEndpoint set . the annotations turns to https://192.168.253.129:2379.

yes, the etcd manifest should also change based on  localAPIEndpoint.
so there is no problem here?

**Comment by oldthreefeng** [comment]
thanks.  no more problem~~

**Comment by oldthreefeng** [comment]
Does any  `localAPIEndpoint`  like define  in a work nodes?   
a work node  have tow network iface. `192.168.160.244` is pubilc network route.`192.168.253.128 `is a internal IP.
```
 $ ip a |grep inet 
    inet 127.0.0.1/8 scope host lo
    inet 192.168.253.128/24 brd 192.168.253.255 scope global noprefixroute dynamic ens32
    inet 192.168.160.244/23 brd 192.168.161.255 scope global noprefixroute ens33
```
default route is
```
$ ip route show | grep default
default via 192.168.160.1 dev ens33
```
join this nodes to a exsit kubernetes cluster as a work node.  how to set my defautl ip to` 192.168.253.128` instead of `192.168.160.244`

> kubeadm and the kubelet both default to use the public interface and there is no way to change that.
we have no plans allow the users to pick an interface for the time being.

in this sitution, master and CP nodes can use `localAPIEndpoint` to define my  `advertise-address`  everywhere.  include calico node ip.

**Comment by neolit123** [comment]
> Does any localAPIEndpoint like define in a work nodes

For workers you can pass --node-ip to the kubelet. This is possible via kubeadm joinconfiguration -noderegistrationoptions - kubeletextraargs

See the docs for v1beta2 JoinConfiguration.

**Comment by oldthreefeng** [comment]
> See the docs for v1beta2 JoinConfiguration.

ok,  Thanks for your patience.
