### ISSUE TITLE
graduate "alpha certs" to a parent "certs" command

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2291]
during the 1.20 planning session we agreed that we should graduate this.

proposal:

---

1.20:

- [x] mark "alpha certs" as deprecated in 1.20 and tell the users to move to "certs".
we can bring it back in the future if we need more certs related experimental commands. add a parent "certs" command in 1.20 that uses the same commands from the "alpha" backend
https://github.com/kubernetes/kubernetes/pull/94938
- [x] send k/website PR to include a new page for "certs" here:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/
link from that page to kubeadm's [certificate management](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/):
https://github.com/kubernetes/website/pull/24410
---

1.21:

- [x] in 1.21 copy the logic to reside under the "certs" command, remove the "alpha certs" command.
https://github.com/kubernetes/kubernetes/pull/97706
- [x] send k/website PR to remove the "alpha certs" commands from the reference docs.
https://github.com/kubernetes/website/pull/24410
---

xref https://kubernetes.io/docs/reference/setup-tools/kubeadm/

**Comment by neolit123** [comment]
@yagonobre you've mentioned that you could help with this work. would you be able to?

**Comment by yagonobre** [comment]
@neolit123 Yes, I'll send a pr later this week

**Comment by neolit123** [comment]
this is done
