### ISSUE TITLE
prepare "alpha kubeconfig user" for graduation

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2292]
during the 1.20 planning session we decided that we should first refactor the command and then graduate it to a root command.
the "init" phase should remain a separate workflow.

related topic about the overlap between the "init phase kubeconfig admin" and "alpha kubeconfig user":
https://github.com/kubernetes/kubeadm/issues/1381

proposal plan:

------

1.20:

- [x] refactor the command to only accept flags that are not present in the kubeadm config, make the command accept the kubeadm config.
https://github.com/kubernetes/kubernetes/pull/94879

------

1.21:

- [x] create a parent "kubeconfig user" command
deprecate the "alpha" command, tell users to use the new root "kubeconfig.." command.
make the root command use the "alpha" command temporary.
https://github.com/kubernetes/kubernetes/pull/97583
- [x] send a PR to update k/website with the new command.
https://github.com/kubernetes/website/pull/25935
------

1.22:

- [ ] copy the alpha command logic in the root "kubeconfig" command. remove the alpha command.

-----

xref https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/

**Comment by knight42** [comment]
I would like to help.
/assign

**Comment by knight42** [comment]
@neolit123 I have filed kubernetes/kubernetes#97583 to graduate the command.
