### ISSUE TITLE
CA.Key required for joining the another node to cluster with External CA and Kubeadm

### ISSUE THREAD

**Issue by Venkatvenstvm** [kubernetes/kubeadm#2296]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 

## Versions

**kubeadm version** : kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:24:31Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:  EC2 instances in aws ( not using ELK stack)
- **Kubernetes version** : Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
- **OS** : 18.04.5 LTS (Bionic Beaver)
- **Kernel** (e.g. `uname -a`): 5.3.0-1035-aws
- **Others**:

## What happened?
creating cluster using kubeadm tool with external CA and without ca.key, cluster is up with one controller , but it requires CA.key when  joining 2 nd controller node through load balancer ( software LB envoy proxy) with 1st controller. however worker-nodes are added to the clusters.

## What you expected to happen?
Controller 2 to be joined with cluster without ca.key file.

## How to reproduce it (as minimally and precisely as possible)?
  create cluster with external CA without ca.key file using kubeadm, after controller-1 is up join the controller-2 node with kubeadm join ( output of kubeadm init)

configuration used for kubeadm init

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- token: "9a08jv.c0izixklcxtmnze7"
  description: "kubeadm bootstrap token"
  ttl: "24h"
- token: "783bde.3f89s0fje9f38fhf"
  description: "another bootstrap token"
  usages:
  - authentication
  - signing
  groups:
  - system:bootstrappers:kubeadm:default-node-token
nodeRegistration:
  name: "controllerA"
  criSocket: "/var/run/dockershim.sock"
  taints:
  - key: "kubeadmNode"
    value: "master"
    effect: "NoSchedule"
  kubeletExtraArgs:
    cgroup-driver: "cgroupfs"
  ignorePreflightErrors:
  - IsPrivilegedUser
localAPIEndpoint:
  advertiseAddress: "172.31.39.244"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
etcd:
  # one of local or external
  external:
    endpoints:
    - "https://172.31.39.244:2379"
    - "https://172.31.38.173:2379"
    - "https://172.31.37.156:2379"
    caFile: "/etc/kubernetes/pki/etcd/ca.crt"
    certFile: "/etc/kubernetes/pki/etcd/server.crt"
    keyFile: "/etc/kubernetes/pki/etcd/server.key"
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.100.0.1/24"
  dnsDomain: "default-cluster"
apiServer:
  extraArgs:
    authorization-mode: "Node,RBAC"
    #cloud-provider: aws
  certSANs:
   - "172.31.20.115"
  timeoutForControlPlane: 4m0s
certificatesDir: "/etc/kubernetes/pki"
clusterName: "default-cluster"
kubernetesVersion: "v1.18.8"
controlPlaneEndpoint: "172.31.20.115:6443"
controllerManager:  
  extraArgs:
    #cloud-provider: aws
    configure-cloud-routes: "false"
    cluster-signing-cert-file: ""
    cluster-signing-key-file: ""
```

## Anything else we need to know?
Discussion happened with in issue  https://github.com/kubernetes/kubeadm/issues/1391 by neolit123 and me..

logs while joining controller b with cluster with log level --v=5

```
I0922 06:05:02.675785 20058 join.go:388] [preflight] found /etc/kubernetes/admin.conf. Use it for skipping discovery
I0922 06:05:02.676589 20058 join.go:398] [preflight] found NodeName empty; using OS hostname as NodeName
I0922 06:05:02.676604 20058 join.go:402] [preflight] found advertiseAddress empty; using default interface's IP address as advertiseAddress
I0922 06:05:02.676638 20058 initconfiguration.go:103] detected and using CRI socket: /var/run/dockershim.sock
I0922 06:05:02.676741 20058 interface.go:400] Looking for default routes with IPv4 addresses
I0922 06:05:02.676748 20058 interface.go:405] Default route transits interface "ens5"
I0922 06:05:02.676822 20058 interface.go:208] Interface ens5 is up
I0922 06:05:02.676863 20058 interface.go:256] Interface "ens5" has 2 addresses :[172.31.38.173/20 fe80::8c5:acff:fe43:ed16/64].
I0922 06:05:02.676882 20058 interface.go:223] Checking addr 172.31.38.173/20.
I0922 06:05:02.676892 20058 interface.go:230] IP found 172.31.38.173
I0922 06:05:02.676900 20058 interface.go:262] Found valid IPv4 address 172.31.38.173 for interface "ens5".
I0922 06:05:02.676907 20058 interface.go:411] Found active IP 172.31.38.173
[preflight] Running pre-flight checks
I0922 06:05:02.676962 20058 preflight.go:90] [preflight] Running general checks
I0922 06:05:02.676995 20058 checks.go:249] validating the existence and emptiness of directory /etc/kubernetes/manifests
I0922 06:05:02.677020 20058 checks.go:286] validating the existence of file /etc/kubernetes/kubelet.conf
[WARNING FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists
I0922 06:05:02.677050 20058 checks.go:286] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0922 06:05:02.677059 20058 checks.go:102] validating the container runtime
I0922 06:05:02.767314 20058 checks.go:128] validating if the "docker" service is enabled and active
[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
I0922 06:05:02.854410 20058 checks.go:335] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0922 06:05:02.854464 20058 checks.go:335] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0922 06:05:02.854492 20058 checks.go:649] validating whether swap is enabled or not
I0922 06:05:02.854526 20058 checks.go:376] validating the presence of executable conntrack
I0922 06:05:02.854547 20058 checks.go:376] validating the presence of executable ip
I0922 06:05:02.854567 20058 checks.go:376] validating the presence of executable iptables
I0922 06:05:02.854586 20058 checks.go:376] validating the presence of executable mount
I0922 06:05:02.854604 20058 checks.go:376] validating the presence of executable nsenter
I0922 06:05:02.854620 20058 checks.go:376] validating the presence of executable ebtables
I0922 06:05:02.854636 20058 checks.go:376] validating the presence of executable ethtool
I0922 06:05:02.854659 20058 checks.go:376] validating the presence of executable socat
I0922 06:05:02.854675 20058 checks.go:376] validating the presence of executable tc
I0922 06:05:02.854691 20058 checks.go:376] validating the presence of executable touch
I0922 06:05:02.854712 20058 checks.go:520] running all checks
I0922 06:05:02.932009 20058 checks.go:406] checking whether the given node name is reachable using net.LookupHost
I0922 06:05:02.932153 20058 checks.go:618] validating kubelet version
I0922 06:05:02.983585 20058 checks.go:128] validating if the "kubelet" service is enabled and active
I0922 06:05:02.992144 20058 checks.go:201] validating availability of port 10250
I0922 06:05:02.992322 20058 checks.go:432] validating if the connectivity type is via proxy or direct
I0922 06:05:02.992372 20058 join.go:483] [preflight] Fetching init configuration
I0922 06:05:02.992380 20058 join.go:526] [preflight] Retrieving KubeConfig objects
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
I0922 06:05:03.003394 20058 request.go:933] Got a Retry-After 1s response for attempt 1 to https://172.31.20.115:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s
I0922 06:05:04.027026 20058 interface.go:400] Looking for default routes with IPv4 addresses
I0922 06:05:04.027041 20058 interface.go:405] Default route transits interface "ens5"
I0922 06:05:04.027141 20058 interface.go:208] Interface ens5 is up
I0922 06:05:04.027190 20058 interface.go:256] Interface "ens5" has 2 addresses :[172.31.38.173/20 fe80::8c5:acff:fe43:ed16/64].
I0922 06:05:04.027206 20058 interface.go:223] Checking addr 172.31.38.173/20.
I0922 06:05:04.027212 20058 interface.go:230] IP found 172.31.38.173
I0922 06:05:04.027226 20058 interface.go:262] Found valid IPv4 address 172.31.38.173 for interface "ens5".
I0922 06:05:04.027236 20058 interface.go:411] Found active IP 172.31.38.173
I0922 06:05:04.120689 20058 preflight.go:101] [preflight] Running configuration dependant checks

One or more conditions for hosting a new control plane instance is not satisfied.

failure loading key for CA: couldn't load the private key file /etc/kubernetes/pki/ca.key: open /etc/kubernetes/pki/ca.key: no such file or directory

Please ensure that:

    The cluster has a stable controlPlaneEndpoint address.
    The certificates that must be shared among control plane instances are provided.

k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runPreflight
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/preflight.go:114
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:174
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:842
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
k8s.io/kubernetes/cmd/kubeadm/app.Run
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
/usr/local/go/src/runtime/proc.go:204
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1374
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:174
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:842
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
k8s.io/kubernetes/cmd/kubeadm/app.Run
/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
/usr/local/go/src/runtime/proc.go:204
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1374
```

**Comment by neolit123** [comment]
please share you full `kubeadm init` and `kubeadm join` command lines.

i'm curious if you are using the --upload-certs / --certificate-key feature.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

if not, how are you copying the CP certificates to the second CP node?

> [WARNING FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists

can you clarify why this file already exists on the second CP node?
unless it includes client cert/key for the kubelet that you signed you should remove it.

**Comment by Venkatvenstvm** [comment]
> please share you full `kubeadm init` and `kubeadm join` command lines.
> 
> i'm curious if you are using the --upload-certs / --certificate-key feature.
> https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
> 
> if not, how are you copying the CP certificates to the second CP node and which files?
> 
> > [WARNING FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists
> 
> can you clarify why this file already exists on the second CP node?
> unless it includes client cert/key for the kubelet that you signed you should remove it.

No i am not doing -- upload-certs

Manually copied files to node 2. following are the files available in /etc/kubernetes/pki
         apiserver-etcd-client.crt    
         apiserver-kubelet-client.key  
         ca.crt              
         front-proxy-client.crt  
         front-proxy.key
         apiserver-etcd-client.key    
         apiserver.crt                 
         etcd /
            ca.crt  , healthcheck-client.crt,  healthcheck-client.key,  peer.crt,  peer.key,  server.crt  and server.key
        front-proxy-client.key  
        sa.key
       apiserver-kubelet-client.crt 
       apiserver.key                
        front-proxy.crt         
        sa.pub

Earlier i created the kubelet.conf file manually singed by me, for verification purpose
     copied that into node b,  i have removed and  run the kubeadm join below is the logs 

I0922 16:37:32.117874    5219 join.go:388] [preflight] found /etc/kubernetes/admin.conf. Use it for skipping discovery
I0922 16:37:32.118633    5219 join.go:398] [preflight] found NodeName empty; using OS hostname as NodeName
I0922 16:37:32.118648    5219 join.go:402] [preflight] found advertiseAddress empty; using default interface's IP address as advertiseAddress
I0922 16:37:32.118681    5219 initconfiguration.go:103] detected and using CRI socket: /var/run/dockershim.sock
I0922 16:37:32.118785    5219 interface.go:400] Looking for default routes with IPv4 addresses
I0922 16:37:32.118794    5219 interface.go:405] Default route transits interface "ens5"
I0922 16:37:32.118868    5219 interface.go:208] Interface ens5 is up
I0922 16:37:32.118902    5219 interface.go:256] Interface "ens5" has 2 addresses :[172.31.38.173/20 fe80::8c5:acff:fe43:ed16/64].
I0922 16:37:32.118915    5219 interface.go:223] Checking addr  172.31.38.173/20.
I0922 16:37:32.118925    5219 interface.go:230] IP found 172.31.38.173
I0922 16:37:32.118936    5219 interface.go:262] Found valid IPv4 address 172.31.38.173 for interface "ens5".
I0922 16:37:32.118945    5219 interface.go:411] Found active IP 172.31.38.173 
[preflight] Running pre-flight checks
I0922 16:37:32.118993    5219 preflight.go:90] [preflight] Running general checks
I0922 16:37:32.119022    5219 checks.go:249] validating the existence and emptiness of directory /etc/kubernetes/manifests
I0922 16:37:32.119047    5219 checks.go:286] validating the existence of file /etc/kubernetes/kubelet.conf
I0922 16:37:32.119055    5219 checks.go:286] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0922 16:37:32.119066    5219 checks.go:102] validating the container runtime
I0922 16:37:32.218917    5219 checks.go:128] validating if the "docker" service is enabled and active
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
I0922 16:37:32.300193    5219 checks.go:335] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0922 16:37:32.300235    5219 checks.go:335] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0922 16:37:32.300261    5219 checks.go:649] validating whether swap is enabled or not
I0922 16:37:32.300299    5219 checks.go:376] validating the presence of executable conntrack
I0922 16:37:32.300319    5219 checks.go:376] validating the presence of executable ip
I0922 16:37:32.300338    5219 checks.go:376] validating the presence of executable iptables
I0922 16:37:32.300355    5219 checks.go:376] validating the presence of executable mount
I0922 16:37:32.300378    5219 checks.go:376] validating the presence of executable nsenter
I0922 16:37:32.300393    5219 checks.go:376] validating the presence of executable ebtables
I0922 16:37:32.300410    5219 checks.go:376] validating the presence of executable ethtool
I0922 16:37:32.300428    5219 checks.go:376] validating the presence of executable socat
I0922 16:37:32.300443    5219 checks.go:376] validating the presence of executable tc
I0922 16:37:32.300459    5219 checks.go:376] validating the presence of executable touch
I0922 16:37:32.300481    5219 checks.go:520] running all checks
I0922 16:37:32.376489    5219 checks.go:406] checking whether the given node name is reachable using net.LookupHost
I0922 16:37:32.376622    5219 checks.go:618] validating kubelet version
I0922 16:37:32.430292    5219 checks.go:128] validating if the "kubelet" service is enabled and active
I0922 16:37:32.439135    5219 checks.go:201] validating availability of port 10250
I0922 16:37:32.439340    5219 checks.go:432] validating if the connectivity type is via proxy or direct
I0922 16:37:32.439378    5219 join.go:483] [preflight] Fetching init configuration
I0922 16:37:32.439387    5219 join.go:526] [preflight] Retrieving KubeConfig objects
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
I0922 16:37:32.457578    5219 interface.go:400] Looking for default routes with IPv4 addresses
I0922 16:37:32.457589    5219 interface.go:405] Default route transits interface "ens5"
I0922 16:37:32.457685    5219 interface.go:208] Interface ens5 is up
I0922 16:37:32.457730    5219 interface.go:256] Interface "ens5" has 2 addresses :[172.31.38.173/20 fe80::8c5:acff:fe43:ed16/64].
I0922 16:37:32.457744    5219 interface.go:223] Checking addr  172.31.38.173/20.
I0922 16:37:32.457755    5219 interface.go:230] IP found 172.31.38.173
I0922 16:37:32.457766    5219 interface.go:262] Found valid IPv4 address 172.31.38.173 for interface "ens5".
I0922 16:37:32.457771    5219 interface.go:411] Found active IP 172.31.38.173 
I0922 16:37:32.529964    5219 preflight.go:101] [preflight] Running configuration dependant checks

One or more conditions for hosting a new control plane instance is not satisfied.

failure loading key for CA: couldn't load the private key file /etc/kubernetes/pki/ca.key: open /etc/kubernetes/pki/ca.key: no such file or directory

Please ensure that:
* The cluster has a stable controlPlaneEndpoint address.
* The certificates that must be shared among control plane instances are provided.


k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runPreflight
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/preflight.go:114
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:174
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:842
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdJoin.func1
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:174
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:842
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by neolit123** [comment]
on the primary CP node, is the kube-controller-manager tolerating the lack of ca.key - i.e. is it crashlooping?
or did you remove `--cluster-signing-key-file=/etc/kubernetes/pki/ca.key`?

> please share you full kubeadm init and kubeadm join command lines.

^ what are the command lines for init/join?

because if you are not passing the ca.key to the KCM then you cannot use bootstrap-tokens to join more kubelets to the cluster and you have to bootstrap using client certificates:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
without a ca.key the KCM cannot sign the certificates for new kubelets.

**Comment by Venkatvenstvm** [comment]
on primary node I dont not keep ca.key explicitly... and created manually all certificate with ca.crt and ca.key as per below instructions, and primary node running in ready mode able join worker node to that master node.

https://kubernetes.io/docs/setup/best-practices/certificates/

ref : "If you don't wish to copy the CA private keys to your cluster, you can generate all certificates yourself."


sudo kubeadm init --config=k8_Kubeadm_init_config.yaml --v=5

**k8_Kubeadm_init_config.yaml**
--- 
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- token: "9a08jv.c0izixklcxtmnze7"
  description: "kubeadm bootstrap token"
  ttl: "24h"
- token: "783bde.3f89s0fje9f38fhf"
  description: "another bootstrap token"
  usages:
  - authentication
  - signing
  groups:
  - system:bootstrappers:kubeadm:default-node-token
nodeRegistration:
  name: "controllerA"
  criSocket: "/var/run/dockershim.sock"
  taints:
  - key: "kubeadmNode"
    value: "master"
    effect: "NoSchedule"
  kubeletExtraArgs:
    cgroup-driver: "cgroupfs"
  ignorePreflightErrors:
  - IsPrivilegedUser
localAPIEndpoint:
  advertiseAddress: "172.31.39.244"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
etcd:
  # one of local or external
  external:
    endpoints:
    - "https://172.31.39.244:2379"
    - "https://172.31.38.173:2379"
    - "https://172.31.37.156:2379"
    caFile: "/etc/kubernetes/pki/etcd/ca.crt"
    certFile: "/etc/kubernetes/pki/etcd/server.crt"
    keyFile: "/etc/kubernetes/pki/etcd/server.key"
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.100.0.1/24"
  dnsDomain: "default-cluster"
apiServer:
  extraArgs:
    authorization-mode: "Node,RBAC"
    #cloud-provider: aws
  certSANs:
   - "172.31.20.115"
  timeoutForControlPlane: 4m0s
certificatesDir: "/etc/kubernetes/pki"
clusterName: "default-cluster"
kubernetesVersion: "v1.18.8"
controlPlaneEndpoint: "172.31.20.115:6443"
controllerManager:  
  extraArgs:
    #cloud-provider: aws
    configure-cloud-routes: "false"
    cluster-signing-cert-file: ""
    cluster-signing-key-file: ""

Kubeadm join

sudo kubeadm join 172.31.20.115:6443 --token <tokenvalue>    --discovery-token-ca-cert-hash sha256:<key>     --control-plane   --ignore-preflight-errors=all  --v=5

**Comment by neolit123** [comment]
> on primary node I dont not keep ca.key explicitly... and created manually all certificate with ca.crt and ca.key as per below instructions, and primary node running in ready mode able join worker node to that master node.

so, if you don't have the file ca.key on the primary CP node, you should remove these flags:
```
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
```

optionally this line too:
```
    - --controllers=*,bootstrapsigner,tokencleaner
```

from the KCM manifest.

> sudo kubeadm join 172.31.20.115:6443 --token --discovery-token-ca-cert-hash sha256: --control-plane --ignore-preflight-errors=all --v=5

as already mentioned, you can no longer use bootstrap tokens to join new nodes and you need to use discovery files:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#file-or-https-based-discovery

> failure loading key for CA: couldn't load the private key file /etc/kubernetes/pki/ca.key: open /etc/kubernetes/pki/ca.key: no such file or directory

this this seems like a bug in kubeadm, but even if we fix it `join` will fail due to the reasons explained above.

**Comment by Venkatvenstvm** [comment]
which means with CA.key could we not create the kubernetes cluster using kubeadm

**Comment by Venkatvenstvm** [comment]
which means without CA.key, could we not create Kubernetes cluster ?

**Comment by neolit123** [comment]
kubeadm should not prevent you from creating a cluster without ca.key, so bugs around that should be fixed...
but by removing ca.key you are entering an advanced use case that is complicated to manage.

the simplest solution is to write an intermediate ca.key.

**Comment by neolit123** [comment]
i was able to reproduce the problem and have a PR as a WIP:
https://github.com/kubernetes/kubernetes/pull/94988

/lifecycle active
/assign

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/pull/94988 merged, the fix is cherry picked to older versions down to 1.17.

thanks for reporting.
/close
