### ISSUE TITLE
deprecate and remove "kubeadm alpha selfhosting pivot"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2299]
see summary at the mailing list:
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/xdpnn7yJHvM

> historically the self-hosting support was more integral in kubeadm via
a FeatureGate that later got "demoted" to the alpha command, due to
complexities around the maintenance and no evidence of high demand.
kubeadm focused on static Pods and decided to move away from the
self-hosting support.

> we have not seen recent evidence of usage of the alpha command, thus
after a long stay under "alpha" instead of promoting it, we'd prefer
to deprecate / remove it.

proposed timeline:

----

1.20

- [x] mark the "selfhosting" and child "pivot" commands as deprecated, using Cobra's "Deprecated" field
https://github.com/kubernetes/kubernetes/pull/95125

---

1.21

- [x] remove the command
https://github.com/kubernetes/kubernetes/pull/97627
- [x] updated k/website to reflect the change
https://github.com/kubernetes/website/pull/25935

**Comment by neolit123** [comment]
waiting for replies on the [mailing list thread](https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/xdpnn7yJHvM)

**Comment by knight42** [comment]
@neolit123 Is it okay to remove this command now? If yes, I would like to submit a PR to do that.

**Comment by neolit123** [comment]
yes, this is scheduled for removal in 1.21.

**Comment by knight42** [comment]
@neolit123 Hi! I have filed kubernetes/kubernetes#97627 to remove this deprecated command.

**Comment by neolit123** [comment]
this is done!
/close
