### ISSUE TITLE
Remove offensive words from CI jobs configuration

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#2302]
In our CI tests we are still using master to refer to the tip of the main branch.
We should replace this with "latest" (or "main").

The change should apply to:
- file names under k/kubeadm/kinder/ci/workflows
- corresponding test configuration under k/test-infra/config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm*.yaml
- docs under k/kubeadm/kinder/ci

**Comment by BenTheElder** [comment]
Note that the kubernetes project at large plans to switch the branches themselves in github repos later this year when github finishes landing their features to support a smooth transition natively. the github admin team is in touch about this and wg-naming is tracking it.

**Comment by fabriziopandini** [comment]
Thanks for the context @BenTheElder!
This issue focuses on cleanup activities mostly on our(kubeadm) side, mostly on job names/dashboard names, but the branch switch is definitely another piece of the puzzle

**Comment by neolit123** [comment]
this is done, minus the `master` branches in the test-infra jobs, which i assume may be done in a bulk for * jobs in the repo.

**Comment by fabriziopandini** [comment]
/close
kudos to @SataQiu & @neolit123
