### ISSUE TITLE
port-forward not working in kubernetes cluster where as direct connection to pod on port 80 works fine

### ISSUE THREAD

**Issue by NitHas89** [kubernetes/kubeadm#2303]
ubuntu@k8master:~$ kubectl port-forward pods/fortunepod 8080:80
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80

ubuntu@node1:~$ curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused

if I curl directly to pod IP and port 80 . Everything works fine
ubuntu@node1:~$ curl 10.244.1.223:80
Today is the first day of the rest of your life.

Below is the description of POD with 2 conainers.  

Name:         fortunepod
Namespace:    default
Priority:     0
Node:         node1/10.108.147.192
Start Time:   Fri, 25 Sep 2020 13:49:27 +0530
Labels:       <none>
Annotations:  <none>
Status:       Running
IP:           10.244.1.223
IPs:
  IP:  10.244.1.223
Containers:
  content-generator:
    Container ID:   docker://ba81808efaf4375b164062880a8047fd4da89dbd6cd878b2c2bc77efb137f76a
    Image:          nithas/fortune
    Image ID:       docker-pullable://nithas/fortune@sha256:1e44d073f4147047a62e7f095087b78406b5bfd7efabab02e73a0ed79b120728
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 25 Sep 2020 17:04:46 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Fri, 25 Sep 2020 14:03:43 +0530
      Finished:     Fri, 25 Sep 2020 16:46:26 +0530
    Ready:          True
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /var/htdocs from html (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lwvhb (ro)
  web-server:
    Container ID:   docker://793411c6227229f1747e774d07627c0cffe95bd1e7d16995e0504ecb6a3bc3e2
    Image:          nginx:alpine
    Image ID:       docker-pullable://nginx@sha256:a97eb9ecc708c8aa715ccfb5e9338f5456e4b65575daf304f108301f3b497314
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 25 Sep 2020 17:04:46 +0530
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 25 Sep 2020 14:03:44 +0530
      Finished:     Fri, 25 Sep 2020 16:46:26 +0530
    Ready:          True
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /usr/share/nginx/html from html (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lwvhb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  html:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-lwvhb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lwvhb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                From     Message
  ----     ------                  ----               ----     -------
  Warning  FailedCreatePodSandBox  20m                kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "dade9c8d8f257194057b9122b25babc98d77f8c327c4f73b90088735a52f4794" network for pod "fortunepod": networkPlugin cni failed to set up pod "fortunepod_default" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  20m                kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "2ada97ab8d18e4159a5339f259123a3c28899c11b7324c82ba91c70c5868b907" network for pod "fortunepod": networkPlugin cni failed to set up pod "fortunepod_default" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  20m                kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ccb111efdce59fcc4e6163c1e35ceaf478e3d4cf900ff60f72c813a4a149314e" network for pod "fortunepod": networkPlugin cni failed to set up pod "fortunepod_default" network: open /run/flannel/subnet.env: no such file or directory
  Normal   SandboxChanged          20m (x4 over 20m)  kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling                 20m                kubelet  Pulling image "nithas/fortune"
  Normal   Pulled                  20m                kubelet  Successfully pulled image "nithas/fortune" in 6.293019293s
  Normal   Created                 20m                kubelet  Created container content-generator
  Normal   Started                 20m                kubelet  Started container content-generator
  Normal   Pulled                  20m                kubelet  Container image "nginx:alpine" already present on machine
  Normal   Created                 20m                kubelet  Created container web-server
  Normal   Started                 20m                kubelet  Started container web-server

ubuntu@k8master:~$ kubectl logs fortunepod web-server
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
10.244.1.1 - - [25/Sep/2020:12:01:30 +0000] "GET / HTTP/1.1" 200 49 "-" "curl/7.68.0" "-"

**kubeadm version** (use `kubeadm version`):1.19.2

**Environment**:
- **Kubernetes version** (use `kubectl version`):.1.19.2
:
- **OS** ubuntu lts 20.04

**Comment by neolit123** [comment]
hi,

> kubectl port-forward pods/fortunepod 8080:80
> ...
> curl: (7) Failed to connect to localhost port 8080: Connection refused

this can be caused by a number of factors, but i don't think it is caused by a kubeadm bug, per se.

please try asking for help in the #kubernetes-users slack channel or on our other support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
/triage support
