### ISSUE TITLE
kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

### ISSUE THREAD

**Issue by ShahidAttari26** [kubernetes/kubeadm#2304]
I am facing below problem once I am running "sudo minikube start" on Linux 18.04.05 LTS and details are given below. (Same issue if "sudo minikube start --vm-driver=none")

minikube v1.13.1 on Ubuntu 18.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running none "minikube" bare metal machine ...
ℹ️  OS release is Ubuntu 18.04.5 LTS
🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.13 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
❗  This bare metal machine is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
❌  Problems detected in kubelet:
    سبتمبر 26 11:41:03 a-Inspiron-15-3567 kubelet[2172]: E0926 11:41:03.242401    2172 pod_workers.go:191] Error syncing pod 49bba9517e3db662ab700d8c8c0c22d4 ("kube-apiserver-a-inspiron-15-3567_kube-system(49bba9517e3db662ab700d8c8c0c22d4)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "back-off 40s restarting failed container=kube-apiserver pod=kube-apiserver-a-inspiron-15-3567_kube-system(49bba9517e3db662ab700d8c8c0c22d4)"
    سبتمبر 26 11:41:06 a-Inspiron-15-3567 kubelet[2172]: E0926 11:41:06.872142    2172 pod_workers.go:191] Error syncing pod 83e4cc47ad91c5e2843506a7a03e05cd ("etcd-a-inspiron-15-3567_kube-system(83e4cc47ad91c5e2843506a7a03e05cd)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "back-off 1m20s restarting failed container=etcd pod=etcd-a-inspiron-15-3567_kube-system(83e4cc47ad91c5e2843506a7a03e05cd)"
    سبتمبر 26 11:41:11 a-Inspiron-15-3567 kubelet[2172]: E0926 11:41:11.387820    2172 pod_workers.go:191] Error syncing pod 49bba9517e3db662ab700d8c8c0c22d4 ("kube-apiserver-a-inspiron-15-3567_kube-system(49bba9517e3db662ab700d8c8c0c22d4)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "back-off 40s restarting failed container=kube-apiserver pod=kube-apiserver-a-inspiron-15-3567_kube-system(49bba9517e3db662ab700d8c8c0c22d4)"
    سبتمبر 26 11:41:12 a-Inspiron-15-3567 kubelet[2172]: E0926 11:41:12.300874    2172 pod_workers.go:191] Error syncing pod 2dc81bc22d586cfdb354aab23a76e650 ("kube-controller-manager-a-inspiron-15-3567_kube-system(2dc81bc22d586cfdb354aab23a76e650)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 10s restarting failed container=kube-controller-manager pod=kube-controller-manager-a-inspiron-15-3567_kube-system(2dc81bc22d586cfdb354aab23a76e650)"
    سبتمبر 26 11:41:19 a-Inspiron-15-3567 kubelet[2172]: E0926 11:41:19.237721    2172 pod_workers.go:191] Error syncing pod 2dc81bc22d586cfdb354aab23a76e650 ("kube-controller-manager-a-inspiron-15-3567_kube-system(2dc81bc22d586cfdb354aab23a76e650)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 10s restarting failed container=kube-controller-manager pod=kube-controller-manager-a-inspiron-15-3567_kube-system(2dc81bc22d586cfdb354aab23a76e650)"
🤦  Unable to restart cluster, will reset it: apiserver health: apiserver healthz never reported healthy: cluster wait timed out during healthz check

**Comment by neolit123** [comment]
Hi pleaese log the issue in the minikube repository.
