### ISSUE TITLE
kubeadm upgrade plan allows invalid versions

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubeadm#2311]
#BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:38:53Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
Brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 20.04.1 LTS
- **Kernel** (e.g. `uname -a`):
Linux srv-krwu8 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
`kubeadm upgrade plan` with an invalid version describes the upgrade as though it exists. 

## What you expected to happen?
kubeadm upgrade plan should detect that a version isn't available and explain the error. 

## How to reproduce it (as minimally and precisely as possible)?
kubeadm upgrade plan 1.20.1

## Anything else we need to know?
```
$ sudo kubeadm upgrade plan 1.20.1
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.19.2
[upgrade/versions] kubeadm version: v1.19.2
[upgrade/versions] Latest stable version: 1.20.1
[upgrade/versions] Latest version in the v1.19 series: 1.20.1

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT       AVAILABLE
kubelet     1 x v1.19.2   1.20.1

Upgrade to the latest version in the v1.19 series:

COMPONENT                 CURRENT    AVAILABLE
kube-apiserver            v1.19.2    1.20.1
kube-controller-manager   v1.19.2    1.20.1
kube-scheduler            v1.19.2    1.20.1
kube-proxy                v1.19.2    1.20.1
CoreDNS                   1.7.0      1.7.0
etcd                      3.4.13-0   3.4.13-0

You can now apply the upgrade by executing the following command:

	kubeadm upgrade apply 1.20.1

Note: Before you can perform this upgrade, you have to update kubeadm to 1.20.1.

_____________________________________________________________________


The table below shows the current state of component configs as understood by this version of kubeadm.
Configs that have a "yes" mark in the "MANUAL UPGRADE REQUIRED" column require manual config upgrade or
resetting to kubeadm defaults before a successful upgrade can be performed. The version to manually
upgrade to is denoted in the "PREFERRED VERSION" column.

API GROUP                 CURRENT VERSION   PREFERRED VERSION   MANUAL UPGRADE REQUIRED
kubeproxy.config.k8s.io   v1alpha1          v1alpha1            no
kubelet.config.k8s.io     v1beta1           v1beta1             no
_____________________________________________________________________
```

**Comment by neolit123** [comment]
thanks for the report,

it's important to note that `plan` is:
- supposed to work in air-gapped setups when the latest k8s version cannot be fetched from the web
- it supports upgrading to any pre-release / CI version

so `plan` should still allow "planning" for any version, even if fictional.

i think some of the messaging can be adjusted here...

> [upgrade/versions] Latest stable version: 1.20.1

this should just say "Target version: ..."

> [upgrade/versions] Latest version in the v1.19 series: 1.20.1

this should just say "Target version: ..."

> Upgrade to the latest version in the v1.19 series:

"Component upgrade:"

/help
/kind bug
/priority backlog

**Comment by prabhu43** [comment]
@neolit123 I can work on this. 
This should be the expected output, right?
```
[upgrade/versions] Cluster version: v1.19.2
[upgrade/versions] kubeadm version: v1.19.2
[upgrade/versions] Target version: 1.20.1

Components that must be upgraded manually....
COMPONENT   CURRENT       AVAILABLE
kubelet     1 x v1.19.2   1.20.1

Component upgrade:

COMPONENT                 CURRENT    AVAILABLE
...
```

**Comment by neolit123** [comment]
@prabhu43 this is my proposal, at least. not sure what others think.

**Comment by NeilW** [comment]
Sounds like a reasonable solution to me. The wording is misleading, so make the wording more neutral. 

I would switch "AVAILABLE" for "REQUIRED" (assuming we can work out what the lowest required version of the component is). We don't know if it is available as we haven't checked and in the case of gapped installations we can't check.

**Comment by neolit123** [comment]
Yes. REQUIRED is fine in the tables, or just TARGET again.

**Comment by prabhu43** [comment]
@NeilW @neolit123 "TARGET" is more suitable there

```
COMPONENT   CURRENT      TARGET
```

In additon, Shall we provide what is the latest stable version just as an info?
```
[upgrade/versions] Cluster version: v1.19.2
[upgrade/versions] kubeadm version: v1.19.2
[upgrade/versions] Target version: 1.20.1
[upgrade/versions] Latest stable version: 1.19.2
```

**Comment by NeilW** [comment]
How are you finding out what the latest stable version is? With air gapped installations there will be no way of finding out.

**Comment by neolit123** [comment]
I agree that plan is not very useful for air gapped, but it is still a
supported scenario.

**Comment by prabhu43** [comment]
okay, let me fix this without ""Latest Stable Version" for now. We can take this up as a different issue. 
is that okay @neolit123 ?

**Comment by neolit123** [comment]
Lets keep the discussion to this tocket for now.

**Comment by stmcginnis** [comment]
Still working on this @prabhu43 ? Otherwise I could pick this up.

**Comment by prabhu43** [comment]
@stmcginnis Feel free to pick this up
