### ISSUE TITLE
Specify lifetime of certs in "/etc/kubernetes/pki/" (rather than 1 year default).

### ISSUE THREAD

**Issue by IAXES** [kubernetes/kubeadm#2321]
## What keywords did you search in kubeadm issues before filing this one?

- Certificates.
- Renewal.
- Security.
- Lifetime.

## Is this a BUG REPORT or FEATURE REQUEST?

**FEATURE REQUEST**

- **Background**
  - This relates to [a previous post of mine](https://github.com/kubernetes/kubeadm/issues/1826) (which was addressed, and successfully resolved/closed).
  - The various certs in `/etc/kubernetes/pki` appear to have a 1 year lifetime. These can be [re-created manually](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal) via `kubeadm alpha certs renew`, though it appears to require taking down the static manifests/pods, waiting for the associated components to go down, and then re-enabling the static manifests/pods. While I've been able to create a script that executes this operation successfully thousands of times, there doesn't appear to be a vetted/canonical/official/recommended means of executing this operation (to my knowledge). **It would be preferable to go with something "known to work" (according to the maintainers), if available.**
  - I have a use case where K8S is deployed to a set of labs (i.e. offline, no internet access, air-gapped, etc.), and is expected to "just work" for 5+ years (barring routine maintenance or unexpected outages, which we've planned for). I have a requirement to remove an "un-needed moving part" from the overall system, by making these certs (i.e. every cert and config file in `/etc/kubernetes/pki/`) have a lifetime of 5 years or more.
  - I could manually re-create these files via my own scripts plus the `openssl` CLI tool, **but I'm not aware of what K8S-related impact this could have** (i.e. does `kubeadm` tolerate such an operation, or will it break other components/expectation/pre-conditions that would impact the cluster? Does `kubeadm alpha certs renew` execute additional operations or update other settings/hashes/timestamps/etc. in addition to creating new certs? etc.).
- **Request:** one (or more, if needed), of the following.
  - A way to specify the lifetime of these certs/files when the cluster is provisioned via `kubeadm` (i.e. 5/10/20 year lifetime; the use case is for offline isolated lab environments; adding a "warning: don't use unless you know what you're doing" notice to the option seems reasonable).
  - An API option for `kubeadm alpha certs renew` that allows the lifetime of the certs to be specified (similar to the point immediately above).
  - An officially recommended sequence for renewing certs (i.e. via `kubeadm alpha certs renew`, or via command-line tools in Linux) and re-starting the cluster (with the new certs loaded; the `.pem` file for `kubelet` under `/var/` seems to auto-update on masters/nodes, but not what is reported via `sudo kubeadm alpha certs check-expiration`). Previous documentation on the topic that I've found (not necessarily here in this project) advises either:
    - Rebooting the master (unacceptable in our use case; a sysadmin needs to authorize the reboot, and this would terminate any pods running on the master).
    - "Upgrade to a new K8S version to upgrade certs" (also unacceptable, as all that is needed for these offline clusters is the same S/W loadout and new certs; no changes to running versions of K8S, Docker, etc. are permitted).
  - **Question:** is there a recommended approach to revoking old certs? There appears to only be one set of certs in `/etc/kubernetes/pki`, whereas `.pem` files seem to proliferate in `/var/lib/kubelet/pki`. Should we be manually purging these (i.e. in `/var/lib/kubelet/pki`) after a cert renewal (and all `kubelet` instances across all nodes are up-to-date)?

**Notes:** ultimately, I'd like to increase the lifetime of these certs when a cluster is initially provisioned, and make sure "rolling my own" isn't breaking any additional operations that `kubeadm alpha certs renew` may execute (but that I'm not aware of). I'd also like to confirm the "right way" (i.e. recommended method) to restart one-or-more K8S masters without taking out already-running pods on the cluster (or the master, besides the static manifests/pods), and ensure static manifest/pods (and control of the cluster itself) will come back up after previously taking it down to rotate certs, so all pods (minus static manifests/pods) keep running running during a cert renewal operation.

Thank you for your time and assistance.

## Versions

**kubeadm version** (use `kubeadm version`): `v1.17.4`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `1.17.4`
- **Cloud provider or hardware configuration**: Local `kubeadm`-based deployments to physical servers.
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04 x86_64 LTS.
- **Kernel** (e.g. `uname -a`): `4.15.0-112-generic-smp`
- **Others**:

**Comment by neolit123** [comment]
hi,

> I have a use case where K8S is deployed to a set of labs (i.e. offline, no internet access, air-gapped, etc.), and is expected to "just work" for 5+ years (barring routine maintenance or unexpected outages, which we've planned for). I have a requirement to remove an "un-needed moving part" from the overall system, by making these certs (i.e. every cert and config file in /etc/kubernetes/pki/) have a lifetime of 5 years or more.

we have seen many requests about this, but the TL;DR is that we don't want to enable this functionality out-of-the box because everyone will sign their certificates for a long period of time and that is a bad security practice. 1 year is what we recommend as the default to all users.

> I could manually re-create these files via my own scripts plus the openssl CLI tool, but I'm not aware of what K8S-related impact this could have (i.e. does kubeadm tolerate such an operation, or will it break other components/expectation/pre-conditions that would impact the cluster? Does kubeadm alpha certs renew execute additional operations or update other settings/hashes/timestamps/etc. in addition to creating new certs? etc.).

if you are generating your certificates it will work fine as long as you match the data inside the certs kubeadm generates.

alternatively, you have the option to fork kubeadm and maintain a modified value for:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L49

> An officially recommended sequence for renewing certs (i.e. via kubeadm alpha certs renew, or via command-line tools in Linux) and re-starting the cluster (with the new certs loaded; the .pem file for kubelet under /var/ seems to auto-update on masters/nodes, but not what is reported via sudo kubeadm alpha certs check-expiration). Previous documentation on the topic that I've found (not necessarily here in this project) advises either:

in newer versions `certs renew` will print a message that you just have to restart the control-plane components.
one way of doing that is to temporary move the contents of /etc/kubernetes/manifests somewhere and after e.g. ~20 seconds bring them back.

> Question: is there a recommended approach to revoking old certs? There appears to only be one set of certs in /etc/kubernetes/pki, whereas .pem files seem to proliferate in /var/lib/kubelet/pki. Should we be manually purging these (i.e. in /var/lib/kubelet/pki) after a cert renewal (and all kubelet instances across all nodes are up-to-date)?

certificate revocation is a feature that k8s and kubeadm does not support, so if a certificate key leaked, you may have to take the appropriate actions to mitigate - e.g. even tearing a cluster down.
the /var/lib/kubelet/pki certificates are managed by the kubelet ('s built-in cert manager) and are out of scope of kubeadm.

given adjustable cert expiration, has seen multiple requests in the past, but the kubeadm maintainers have voted against it, i'm going to have to close this ticket. but feel free to ask more questions if you have any.

thanks.

**Comment by neolit123** [comment]
> if you are generating your certificates

i forgot to mention that we have a new command - `kubeadm alpha certs generate-csr` command that can be used to generate CSRs for the kubeadm certs. then when you sign them using a CA (and an external tool) you could specify custom expiration.
this is undocumented for the time being but there are generic guides on the web, such as:
https://stackoverflow.com/questions/21297139/how-do-you-sign-a-certificate-signing-request-with-your-certification-authority

**Comment by IAXES** [comment]
Good day @neolit123 , and thank you for the help.

> we have seen many requests about this, but the TL;DR is that we don't want to enable this functionality out-of-the box because everyone will sign their certificates for a long period of time and that is a bad security practice. 1 year is what we recommend as the default to all users.

That's reasonable. Would there be a case for me sharing my script here (i.e. put it in some `tools` folder) so it can be shared/scrutinized/etc.; or would that just run contrary to your point above (i.e. "don't sign 20 years certs, but here's a script to help automate it in our official repo"  ).
&nbsp;
  

> if you are generating your certificates it will work fine as long as you match the data inside the certs kubeadm generates.

I think I need to re-create the contents of `admin.conf` too, based on the certs created. Is this assumption correct? If so, are there any other files that need to be modified/re-generated, besides the `crt` files?
&nbsp;

> alternatively, you have the option to fork kubeadm and maintain a modified value for:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L49

Thanks: that's good to know. However, I'll avoid forking at all costs (esp. a project this big).
&nbsp;

> in newer versions certs renew will print a message that you just have to restart the control-plane components.
one way of doing that is to temporary move the contents of /etc/kubernetes/manifests somewhere and after e.g. ~20 seconds bring them back.

I have a script to execute this (could also likely share it; polls via `kubectl` to see when cluster is no longer responsive or a 30 second wait; whichever is longer). I was curious as to whether there is a more deterministic "tried and true" (i.e. vetted) approach.
&nbsp;

> given adjustable cert expiration, has seen multiple requests in the past, but the kubeadm maintainers have voted against it, i'm going to have to close this ticket. but feel free to ask more questions if you have any.

Would there be a case for me poking away at this feature long-term (i.e. on a dev branch), or is it something that is not desired/intended as mainline functionality (i.e. does it complicate `kubeadm` excessively, or should cert management by handled externally in the general sense with respect to the project's vision/goal)? I have cases where I'd like to remove nodes from the cluster and make sure it can't re-use the cert it has, i.e. per-node certs that can be revoked individually).

**Comment by neolit123** [comment]
> That's reasonable. Would there be a case for me sharing my script here (i.e. put it in some tools folder) so it can be shared/scrutinized/etc.; or would that just run contrary to your point above (i.e. "don't sign 20 years certs, but here's a script to help automate it in our official repo" ).

i think we should eventually write a small guide on how to use `alpha certs generate-csr` instead for this.

> I think I need to re-create the contents of admin.conf too, based on the certs created. Is this assumption correct? If so, are there any other files that need to be modified/re-generated, besides the crt files?

you should be able to generate the certs for kubeconfig files with `alpha certs generate-csr` too.

> I have a script to execute this (could also likely share it; polls via kubectl to see when cluster is no longer responsive or a 30 second wait; whichever is longer). I was curious as to whether there is a more deterministic "tried and true" (i.e. vetted) approach.

you could iterate the certificates and do `openssl x509 -enddate -noout -in file` which would give a date, but this has to be parsed.

> Would there be a case for me poking away at this feature long-term (i.e. on a dev branch), or is it something that is not desired/intended as mainline functionality (i.e. does it complicate kubeadm excessively, or should cert management by handled externally in the general sense with respect to the project's vision/goal)? I have cases where I'd like to remove nodes from the cluster and make sure it can't re-use the cert it has, i.e. per-node certs that can be revoked individually).

i'd say it's not desired at this point as a mainlined functioanlity. we delegated the customization of expiration time to `generate-csr` (i.e. generating CSRs and letting the users sign with the expiration time they want).

**Comment by IAXES** [comment]
@neolit123 As usual, thank you for the prompt, helpful, and detailed replies. Cheers!
