### ISSUE TITLE
kubectl join --control-plane failed due to read etcd endpoint timeout

### ISSUE THREAD

**Issue by Shuanglu** [kubernetes/kubeadm#2325]
## What keywords did you search in kubeadm issues before filing this one?

join
etcd timeout

## Is this a BUG REPORT or FEATURE REQUEST?
Bug report

## Versions

**kubeadm version** (use `kubeadm version`):
_kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:24:31Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}_

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
azure
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- **Kernel** (e.g. `uname -a`):
Linux k8s-master00000B 4.15.0-1098-azure #109~16.04.1-Ubuntu SMP Wed Sep 30 18:53:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
1. I used openssl to generate etcd CA and distribute to two nodes.  
2. I used kubeadm to provision a master  
3. I used 'kubeadm join <fqdn>:443 --token <token> --discovery-token-ca-cert-hash sha256:<hash> --v=9 --control-plane --cri-socket /var/run/containerd/containerd.sock' however the join process got stuck at 'I1015 07:50:47.378908    4319 etcd.go:101] etcd endpoints read from pods: https://172.15.0.4:2379'.

## What you expected to happen?
The kubeadm join works

## How to reproduce it (as minimally and precisely as possible)?
1. kubeadm init to provision a master
2. kubeadm join to join the master 

## Anything else we need to know?
I used 'curl' to check the connectivity and got below. 
root@k8s-master00000B:~# curl https://172.15.0.4:2379 -v --cacert /etc/kubernetes/pki/etcd/ca.crt 
* Rebuilt URL to: https://172.15.0.4:2379/
*   Trying 172.15.0.4...
* Connected to 172.15.0.4 (172.15.0.4) port 2379 (#0)
* found 1 certificates in /etc/kubernetes/pki/etcd/ca.crt
* found 508 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: Certificate is bad
* Closing connection 0
curl: (35) gnutls_handshake() failed: Certificate is bad

**Comment by neolit123** [comment]
Hi, you don't have to copy server certs to new nodes. Those must be
generated. Please have a look at the HA guide again.

This seems like a request for support. Please try #kubeadm on k8s slack for
discussion.

/kind support
/close
