### ISSUE TITLE
Kubeadm init proxy and dns

### ISSUE THREAD

**Issue by Geronium** [kubernetes/kubeadm#2336]
Hello, 

i have a bug with kubeadm, i'm trying to make the init and kubeadm doesn't use the proxy, 
he directly tries to solve by going through the dns server, which replies to him that he does not know the host.

and with a curl the repository is easily reachable

-(mar. oct. 27 19:56:58)--(kubernetes-master:~)-
[root] # curl https://k8s.gcr.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"Unauthorized access."}]}-

-(mar. oct. 27 19:56:45)--(kubernetes-master:~)-
[root] # kubeadm init --pod-network-cidr=192.168.0.0/16   --control-plane-endpoint=kubernetes-maitre
W1027 19:56:54.833327    1442 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.19.3
[preflight] Running pre-flight checks
    [WARNING HTTPProxy]: Connection to "https://172.20.0.1" uses proxy "http://10.----". If that is not intended, adjust your proxy settings
    [WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://10.----" This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
    [WARNING HTTPProxyCIDR]: connection to "192.168.0.0/16" uses proxy "http://10.----". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
    [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.19.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 10.----: **no such host**
, error: exit status 1

thanks

**Comment by fabriziopandini** [comment]
/kind support
kubeadm relies on the CRI engine (docker or containerd), so, if you are behind proxy, you should make sure to configure proxy in your CRI engine too.

**Comment by neolit123** [comment]
> "http://10.----"

is that the actual value, or did you hide it down with `----`? the HTTP*_PROXY values should be for an actual working proxy.

> curl https://k8s.gcr.io/v2/
> {"errors":[{"code":"UNAUTHORIZED","message":"Unauthorized access."}]}-

that is expected, because you cannot access the parent /v2 folder.

> [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.19.3: output: Error response from daemon: Get


as @fabriziopandini mentioned you must configure the CR (e.g. docker) to use the proxy too.
https://docs.docker.com/network/proxy/

once you have that working you can do:
`kubeadm config images list`

and pull the images one by one, or do `kubeadm config images pull`

hope that helps.
for more questions please use the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
