### ISSUE TITLE
kubeadm init fails on It seems like the kubelet isn't running or healthy.

### ISSUE THREAD

**Issue by orlakwahr** [kubernetes/kubeadm#2338]
BUG REPORT

## Versions

kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:47:53Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

Debian GNU/Linux 10 (buster)

Linux lhost 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
setup as per https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#before-you-begin

[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.

## What you expected to happen?

just run kubeadm init --pod-network-cidr=10.244.0.0/16  on fresh linux install and get this.

 systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-10-29 14:40:47 MSK; 1h 57min ago
     Docs: https://docs.docker.com
 Main PID: 1075 (dockerd)
    Tasks: 49
   Memory: 192.6M
   CGroup: /system.slice/docker.service
           └─1075 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Oct 29 14:40:46 lhost dockerd[1075]: time="2020-10-29T14:40:46.759691920+03:00" level=warning msg="Your kernel does not support swap memory limit"
Oct 29 14:40:46 lhost dockerd[1075]: time="2020-10-29T14:40:46.759749159+03:00" level=warning msg="Your kernel does not support cgroup rt period"
Oct 29 14:40:46 lhost dockerd[1075]: time="2020-10-29T14:40:46.759768753+03:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Oct 29 14:40:46 lhost dockerd[1075]: time="2020-10-29T14:40:46.760116755+03:00" level=info msg="Loading containers: start."
Oct 29 14:40:47 lhost dockerd[1075]: time="2020-10-29T14:40:47.357978292+03:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Oct 29 14:40:47 lhost dockerd[1075]: time="2020-10-29T14:40:47.465670701+03:00" level=info msg="Loading containers: done."
Oct 29 14:40:47 lhost dockerd[1075]: time="2020-10-29T14:40:47.558630225+03:00" level=info msg="Docker daemon" commit=4484c46d9d graphdriver(s)=overlay2 version=19.03.13
Oct 29 14:40:47 lhost dockerd[1075]: time="2020-10-29T14:40:47.558740109+03:00" level=info msg="Daemon has completed initialization"
Oct 29 14:40:47 lhost dockerd[1075]: time="2020-10-29T14:40:47.598985978+03:00" level=info msg="API listen on /var/run/docker.sock"
Oct 29 14:40:47 lhost systemd[1]: Started Docker Application Container Engine.

**Comment by neolit123** [comment]
hi, this usually indicates problems with the container runtime and kubeadm cannot do much about it.
you could try getting help at #kubeadm on k8s slack and our support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

you should also check the kubelet logs to see what is happening there.

thanks
/close
/kind support

**Comment by orlakwahr** [comment]
well actually this one is a bug. I have done  mount --bind /var/lib/kubelet /var/lib/kubelet and all started to work.

**Comment by neolit123** [comment]
i don't think this is a bug from kubeadm's perspective, at least. kubeadm just creates the folder /var/lib/kubelet if it doesn't exist before it starts the kubelet.
however, if the kubelet is not happy with the underlying filesystem or something similar then this could be a kubelet bug.

you could try logging a ticket in kubernetes/kubernetes and tagging it with `/sig node`.

**Comment by orlakwahr** [comment]
well I have checked it does not happen on ext4 and does happen on btrfs so it is connected to btrfs somehow.

**Comment by neolit123** [comment]
this search reveals a number of logged issues:
https://github.com/kubernetes/kubernetes/search?q=btrfs+kubelet&type=issues
