### ISSUE TITLE
Drop kustomize dependency in kinder

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#2344]
Kustomize dependency in kinder is difficult to upgrade given the indirect dependency with Kubernetes libraries that are reference directly by kinder or indirectly by kind.

Given that kustomize is used only in a single point in the kinder codebase (pkg/kubeadm), I'm proposing to replace it with standard json patches to greatly simplify our dependency tree.

/cc @neolit123

**Comment by neolit123** [comment]
we could replace with the "patches" package from k/k/cmd/kubeadm if that is moved to a the kubeadm library.

/area kinder
/kind design cleanup
/priority backlog
