### ISSUE TITLE
kubeadm init         How do I choose a container engine??

### ISSUE THREAD

**Issue by misteruly** [kubernetes/kubeadm#2348]
I want to use the ISula container engine

执行shell

kubeadm init --kubernetes-version=v1.17.9 --pod-network-cidr=10.244.0.0/16 --service-cidr=10.1.0.0/16  --apiserver-advertise-address=172.169.102.249
W1110 14:39:59.773789  334131 validation.go:28] Cannot validate kube-proxy config - no validator is available
W1110 14:39:59.773831  334131 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.9
[preflight] Running pre-flight checks
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH
        [WARNING Hostname]: hostname "master" could not be reached
        [WARNING Hostname]: hostname "master": lookup master on 114.114.114.114:53: no such host
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: docker is required for container runtime: exec: "docker": executable file not found in $PATH
To see the stack trace of this error execute with --v=5 or higher

**Comment by fabriziopandini** [comment]
/kind support
You can use the --cri-socket flag or the corresponding field in the kubeadm configuration file

**Comment by neolit123** [comment]
You can also ask for help on the k8s slack channel #kubeadm
/close
