### ISSUE TITLE
Kubeadm does not seem to allow --resolv-conf to be set although it is referenced in the docs.

### ISSUE THREAD

**Issue by a-hodgson** [kubernetes/kubeadm#2349]
Kubeadm version: 1.19
OS: Ubuntu 20.04.1
Kernel: Linux 5.4.0-53-generic 

I am trying to set the kubelet resolv-conf to /run/systemd/resolve/resolv.conf as stated on [this Kubernetes documentation page](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues) as I am using Ubuntu. 

The page states this can be done using kubelet's --resolv-conf flag. This does not work as it has been depreciated. 

My understanding is that it is possible to configuring each kubelet in your cluster using kubeadm. However, there seems to be no way to configure the resolv-conf flag. [This document which details configuring kubelet using kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#kubelet-configuration-patterns) clearly references the --resolv-conf flag in the first bullet point.

None of the man pages for kubeadm seem to reference this flag either.

This can be reproduced by the command kubeadm init --resolv-conf (or using any other kubeadm command).

**Comment by neolit123** [comment]
Passing a KubeletConfiguration next in 'kubeadm init --config ...' will allow you to do that. Ig has a ResolverConf field.

Please see:
https://godoc.org/k8s.io/kubelet/config/v1beta1#KubeletConfiguration
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

These documents are linked from the kubeadm pages at k8s.io

/kind support
/close
