### ISSUE TITLE
Kubeadm idempotency for creating a kubernetes cluster

### ISSUE THREAD

**Issue by cveld** [kubernetes/kubeadm#2353]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

Kubeadm should provide an idempotent way of initializing a kubernetes cluster.

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:38:53Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

## What happened?
We have scripted the creation of a kubernetes cluster by using kubeadm init. We don't see a way to make the script idempotent. A second run always fails with which kubeadm is complaining the ports are already in use.

```
[root@mybox ~]# kubeadm init
W1116 13:06:43.108836   14886 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
[init] Using Kubernetes version: v1.19.4
[preflight] Running pre-flight checks
        [WARNING Firewalld]: firewalld is active, please ensure ports [6443 10250] are open or your cluster may not function correctly
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Port-6443]: Port 6443 is in use
        [ERROR Port-10259]: Port 10259 is in use
        [ERROR Port-10257]: Port 10257 is in use
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
        [ERROR Port-10250]: Port 10250 is in use
        [ERROR Port-2379]: Port 2379 is in use
        [ERROR Port-2380]: Port 2380 is in use
        [ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```

## What you expected to happen?
Kubeadm should just report with something like "Everything set. Nothing to do."

## How to reproduce it (as minimally and precisely as possible)?
1. Run `kubeadm init` on a fresh box. This will create a kubernetes cluster.
2. Run `kubeadm init` a second time. This will throw the errors mentioned upwards.

**Comment by neolit123** [comment]
hello, i believe this is a topic that we discussed before.
if you skip preflight checks `kubeadm init` is an idempotent command.

but i think we should still exit with error if the ports / files are present, because they could be residual from a previous cluster setup. with the old files present you could overlap configuration between new / old cluster and this is not desired.

to skip you can call either --ignore-preflight-errors or --skip-phases=preflight
cc @fabriziopandini 

/kind support

**Comment by neolit123** [comment]
closing. skipping preflight makes the command idempotent, but instead `reset` should be used.

/close
