### ISSUE TITLE
kubeadm: change the default imageRepository value for CI images

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2356]
see https://github.com/kubernetes/test-infra/issues/19483#issuecomment-733258839
and https://github.com/kubernetes/test-infra/issues/19483#issuecomment-735899029

TL;DR if the kubeadm user passes a version that starts with `ci*` the image repository is defaulted to `gcr.io/kubernetes-ci-images`

this repository is being phased out in favor of `gcr.io/k8-staging-ci-images`

instead of making this an v1beta3 only change, i'm proposing that we default to the new URL in both old and new API versions.

**Comment by fabriziopandini** [comment]
I think it is ok to change the default, given that we are just adapting to a change of URL in test infra

**Comment by neolit123** [comment]
@SataQiu 
i can see you sent the PR for k/k master already.
the change must be backported to all versions in the support skew (back to release-1.17) and release-1.20 as well.

@spiffxp should we execute on this now?

**Comment by neolit123** [comment]
so given the change will become global in 1.21 we might want to backport this to the support skew:
https://github.com/kubernetes/kubernetes/pull/97087

will send backports in a bit.
