### ISSUE TITLE
Support two-tier CA configuration

### ISSUE THREAD

**Issue by robbiemcmichael** [kubernetes/kubeadm#2360]
### Context

We're trying to use kubeadm in external CA mode with a two-tier CA configuration. This is done to improve security through shorter expiries while giving us an easy way to rotate the signing CA. We have this setup for each of the required CAs:

- Root CA
- Intermediate CA (issued by Root CA)

We use the `kubeadm certs generate-csr` command to generate CSRs and issue all of the certificates under the appropriate intermediate CA. With this setup, certificates such as `apiserver.crt` must be a bundle with the leaf certificate followed by the intermediate CA certificate. The root CA can also be included at the end of the bundle, but it's not required to construct a valid chain as the verifier must already know of the root CA.

### What went wrong

Unfortunately, this approach doesn't seem to work with kubeadm as it performs some steps to verify that certificates were issued by the root CA. Our certificates are intentionally **not** issued by the root CA though, they're issued by the intermediate CA. What kubeadm should be doing is verifying that the certificate bundle contains a valid chain back to the root CA.

This verification step seems to cause all of the kubeadm init phases I've tested to fail with the following error:

```
W1203 04:04:10.101002    4228 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
crypto/rsa: verification error
certificate API server is not signed by corresponding CA
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.validateSignedCertWithCA
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:412
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.validateSignedCert
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/certs.go:399
```

### Simple fix

I've recompiled kubeadm with a quick change to comment out [this line of code](https://github.com/kubernetes/kubernetes/blob/e1c617a88ec286f5f6cb2589d6ac562d095e1068/cmd/kubeadm/app/phases/certs/certs.go#L431) which seems to be sufficient to allow all of the init phases to run to completion. I also haven't observed any issues with my single node test cluster; the control plane components are all running and the kubeconfig files can be used to connect to the API. This suggests to me that the two-tier CA configuration is supported by the rest of the Kubernetes components, it's just this verification step in kubeadm that's failing.

Commenting out an error obviously isn't a real fix though. Fixing this properly would involve updating this verification step to check that there is a valid chain back to the root CA.

**Comment by robbiemcmichael** [comment]
The above could be considered a bug so I'm most interested in addressing that first as it prevents a two-tier CA from being used even in external CA mode. There are however two further areas where the project lacks the proper support for intermediate CAs.

### The `csrsigning` controller

This controller currently doesn't support intermediate CAs: https://github.com/kubernetes/kubernetes/pull/88741

@neolit123 already noted two months ago that the PR to address this was closed without explanation.

This means that currently any certificates issued from this controller will be missing the intermediate CA certificate, forcing users to append it to the bundle if they want it to work.

This isn't a problem for my use case because we disable the `csrsigning` controller as we're not comfortable with those private keys sitting around on our nodes, but it seems worth flagging as many other users may want to use it and will expect it to work.

### Custom CA mode

[kubeadm supports users loading their own `ca.crt` and `ca.key` files](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#custom-certificates) (and their equivalents for etcd and front-proxy) onto the node and then allowing kubeadm to generate all of the required certificates. It would be great if it were possible to provide `ca.crt`, `intermediate-ca.crt` and `intermediate-ca.key` and then have kubeadm issue certificates with the intermediate CA. It would also need to append the intermediate CA certificate to the bundle for all of the `.crt` files as well as the embedded certificates in the kubeconfig files.

This is a much larger feature request, but this is what I imagine full support for a two-tier CA hierarchy would look like. This would give users an easy way to rotate their signing CA without resorting to generating CSRs and signing all certificates and kubeconfig files externally. Supporting this properly would make it much more accessible to use best practices such as shorter expiry dates on signing CAs.

**Comment by neolit123** [comment]
hi,

please post your comments to this existing issue about supporting CA bundles:
https://github.com/kubernetes/kubeadm/issues/1723

>  It would be great if it were possible to provide ca.crt, intermediate-ca.crt and intermediate-ca.key and then have kubeadm issue certificates with the intermediate CA. 

i'm personally not in favor of having separate files WRT intermediate / root CA. instead kubeadm can verify that a certificate is singed by one of the CAs in the bundle.

the rest of kubernetes supports bundles with a few minor exceptions.

>  I also haven't observed any issues with my single node test cluster; the control plane components are all running and the kubeconfig files can be used to connect to the API. 

are you sure? kubeadm passes the same CA file to KCM flags that do not support more than one object in the PEM:

https://github.com/kubernetes/kubeadm/issues/1723#issuecomment-521780910
https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

>> The files specified by the kube-controller-manager flags --client-ca-file and --cluster-signing-cert-file cannot be CA bundles

> I've recompiled kubeadm with a quick change to comment out this line of code which seems to be sufficient to allow all of the init phases to run to completion.

you might have to carry the local fork / patch for the time being until https://github.com/kubernetes/kubeadm/issues/1723 is resolved.

**Comment by robbiemcmichael** [comment]
Hi @neolit123, I did come across issue #1723 while searching to see if this issue had been discussed before, but I believe we are talking about two separate things. #1723 appears to be talking about CA bundles (i.e. more than one CA certificate in a bundle of trusted CAs, any of which can be used to verify a certificate) whereas I'm talking about support for certificate chains (i.e. a leaf certificate followed by the chain of intermediate CA certificates). Right now kubeadm only appears to support a certificate chain with a path length of 2 (root CA -> leaf certificate) whereas there are a lot of good reasons to support a path length of at least 3 (root CA -> intermediate CA -> leaf certificate).

> > I also haven't observed any issues with my single node test cluster; the control plane components are all running and the kubeconfig files can be used to connect to the API.
> 
> are you sure? kubeadm passes the same CA file to KCM flags that do not support more than one object in the PEM:
> 
> [#1723 (comment)](https://github.com/kubernetes/kubeadm/issues/1723#issuecomment-521780910)
> https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

I'm pretty sure it does work. Since the certificate bundles I'm talking about (the server and client `.crt` files) are still verified by a single CA (the root CA certificate `ca.crt`), the Kubernetes components most likely just rely on the standard Golang library for TLS which means everything just works. It appears to just be kubeadm that is trying to do a helpful verification step outside of the context of a TLS handshake, but unfortunately it only loads the first certificate.

Would it be possible to re-open this issue? I think these are two separate problems just with quite a bit of shared terminology.

**Comment by neolit123** [comment]
> I believe we are talking about two separate things

>> Root CA
>> Intermediate CA (issued by Root CA)

this still falls under https://github.com/kubernetes/kubeadm/issues/1723 as a supported scenario of a bundle.

> I'm pretty sure it does work. 

we may have missed a patch for that in the KCM, since if one's `ca.crt` contains (as noted) more than one PEM object it used to just fail.

> Would it be possible to re-open this issue? I think these are two separate problems just with quite a bit of shared terminology.

chains and bundles are semantically different, yes, but from kubeadm's POV it does not matter and we just called it a bundle in #1723. what we need to support is certificate validation based on a ca.crt that contains more than one CA object.

**Comment by robbiemcmichael** [comment]
> chains and bundles are semantically different, yes, but from kubeadm's POV it does not matter and we just called it a bundle in #1723. what we need to support is certificate validation based on a `ca.crt` that contains more than one CA object.

I think this is where the confusion lies, I'm not talking about a `ca.crt` file that contains more than one CA object in this issue. I'll be more explicit about the files to try to highlight the difference.

#### CA bundles

#1723 talks about CA bundles, which means these files would need to contain multiple CA certificates:

```
ca.crt
etcd/ca.crt
front-proxy-ca.crt
```

All of the other certificates files would contain a single leaf certificate.

#### Certificate chains

In this issue I am talking about certificate chains. This means the CA files listed above would each contain a single certificate, therefore they are not CA bundles.

These files on the other hand would need to contain a certificate chain:

```
apiserver.crt
apiserver-etcd-client.crt
apiserver-kubelet-client.crt
etcd/healthcheck-client.crt
etcd/peer.crt
etcd/server.crt
front-proxy-client.crt
```

The embedded certificates in the kubeconfig files would also need a certificate chain:

```
admin.conf
controller-manager.conf
kubelet.conf
scheduler.conf
```

**Comment by neolit123** [comment]
looks like i'm guilty of not reading the OP thoroughly.

> With this setup, certificates such as apiserver.crt must be a bundle with the leaf certificate followed by the intermediate CA certificate. The root CA can also be included at the end of the bundle, but it's not required to construct a valid chain as the verifier must already know of the root CA.

#1723 is indeed different.

what you are proposing is to have files such as `apiserver.crt` contain the following ordered contents:

- apiserver serving certificate
- intermediate CA
- (optionally root CA)

is that true?

currently, when kubeadm loads a certificate file it uses only the first PEM object, it then validates it against the first CA in the "ca.crt" file. if "ca.crt" contains the same intermediate CA that signed the "apiserver serving certificate" then it should work.

based on this error:

> certificate API server is not signed by corresponding CA

does your "ca.crt" contain the intermediate CA or root CA? if you signed the leaf certificate with the intermediate CA and ca.crt contains the intermediate CA, we have a bug.

> What kubeadm should be doing is verifying that the certificate bundle contains a valid chain back to the root CA.

not necessarily. one of the goal of "external CA" mode is to hide the root CA completely from kubeadm. most users of external CA just feed an intermediate CA under "ca.crt/key", without kubeadm knowing about the root CA or validating back to it.

> ca.crt, intermediate-ca.crt and intermediate-ca.key and then have kubeadm issue certificates with the intermediate CA. It would also need to append the intermediate CA certificate to the bundle for all of the .crt files as well as the embedded certificates in the kubeconfig files.

this tells me that ca.crt contains the root CA, instead ca.crt and ca.key should be the intermediate CA certificate and key.

> This isn't a problem for my use case because we disable the csrsigning controller as we're not comfortable with those private keys sitting around on our nodes, but it seems worth flagging as many other users may want to use it and will expect it to work.

similarly, most external CA users disable controller signing completely and don't pass the ca.key.

> It would be great if it were possible to provide ca.crt, intermediate-ca.crt and intermediate-ca.key and then have kubeadm issue certificates with the intermediate CA. It would also need to append the intermediate CA certificate to the bundle for all of the .crt files as well as the embedded certificates in the kubeconfig files.

i'm inclined to say that this is out of scope for kubeadm, for the time being, with the rationally that it's an advanced use case that we haven't  seen other requests about.

> This is a much larger feature request, but this is what I imagine full support for a two-tier CA hierarchy would look like. This would give users an easy way to rotate their signing CA without resorting to generating CSRs and signing all certificates and kubeconfig files externally

i don't understand how that would work. when the signing CA is rotated all certificates must be signed again.

**Comment by robbiemcmichael** [comment]
> what you are proposing is to have files such as `apiserver.crt` contain the following ordered contents:
> 
>     * apiserver serving certificate
> 
>     * intermediate CA
> 
>     * (optionally root CA)
> 
> 
> is that true?

Yep, that's exactly what I'm doing.

> does your "ca.crt" contain the intermediate CA or root CA? if you signed the leaf certificate with the intermediate CA and ca.crt contains the intermediate CA, we have a bug.

I would argue that `ca.crt` should only contain the root CA certificate. If this file contains the intermediate CA certificate then, taking the API server verifying client connections as an example, the API server will only accept connects from client certificates issued by this exact intermediate CA. The goal is to be able to sign certificates from a new intermediate CA without invalidating the ones issued by the old intermediate CA, otherwise it's impossible to do a graceful rotation of the intermediate CA.

It needs to be possible for both of these chains to be valid for an overlapping period of one month in the example below:

- Chain 1:
  - User client certificate 1
  - Intermediate CA 1 (valid for 1 year and 1 month, from 1st Jan 2019 to 30th Jan 2020)
  - Root CA (valid for 20 years)
- Chain 2:
  - User client certificate 2
  - Intermediate CA 2 (valid for 1 year and 1 month, from 1st Jan 2020 to 30th Jan 2021)
  - Root CA (the same one as above)

These chains can only be simultaneously valid if `ca.crt` contains the root CA.

Intermediate CA certificates should only ever be bundled with the leaf certificate. This is the same way that certificates work for websites, with the OS or browser having access to only the root CA for verification and the server presenting a leaf certificate along with one or more intermediate CA certificates that can be used to construct the chain back to the root CA.

> > What kubeadm should be doing is verifying that the certificate bundle contains a valid chain back to the root CA.
> 
> not necessarily. one of the goal of "external CA" mode is to hide the root CA completely from kubeadm. most users of external CA just feed an intermediate CA under "ca.crt/key", without kubeadm knowing about the root CA or validating back to it.

If `ca.crt` contains only an intermediate CA certificate, then the only difference between that and a root CA certificate is whether it is self-signed or not (root CA certificates are self-signed by definition). I have seen this pattern mentioned in the Kubernetes docs but I'm not entirely sure what functional benefit it provides over just generating separate root CAs. It doesn't solve the signing CA rotation problem so it's not an approach I can use.

> > It would be great if it were possible to provide ca.crt, intermediate-ca.crt and intermediate-ca.key and then have kubeadm issue certificates with the intermediate CA. It would also need to append the intermediate CA certificate to the bundle for all of the .crt files as well as the embedded certificates in the kubeconfig files.
> 
> i'm inclined to say that this is out of scope for kubeadm, for the time being, with the rationale that it's an advanced use case that we haven't seen other requests about.

That's fair enough, I'd be happy to settle for just fixing the verification logic for now. I'll start working on a patch for just that part.

> > This is a much larger feature request, but this is what I imagine full support for a two-tier CA hierarchy would look like. This would give users an easy way to rotate their signing CA without resorting to generating CSRs and signing all certificates and kubeconfig files externally
> 
> i don't understand how that would work. when the signing CA is rotated all certificates must be signed again.

I probably could have worded this more clearly. I was referring to it being possible for users to do graceful rotation without resorting to a full external CA mode where they need to use `kubeadm alpha certs generate-csr`, copy the CSR files off of the node to get them to whichever external tool they use to issue certificates, then copy those certificates back onto the node and embed some of them in kubeconfig files. It's quite an involved process so I doubt many people would ever do this.

Proper support in kubeadm for intermediate CA certificates could allow people to get the same benefits for signing CA rotation that I talked about above but without all of this extra work. In theory they would only need to feed in the intermediate CA `.crt` and `.key` and kubeadm could handle creating the chains. I think this would be a good thing to have, but if other users aren't having problems with the CA rotation workflow then it might not be worth spending time on.

**Comment by neolit123** [comment]
> I would argue that ca.crt should only contain the root CA certificate. If this file contains the intermediate CA certificate then, taking the API server verifying client connections as an example, the API server will only accept connections from client certificates issued by this exact intermediate CA. The goal is to be able to sign certificates from a new intermediate CA without invalidating the ones issued by the old intermediate CA, otherwise it's impossible to do a graceful rotation of the intermediate CA.

i think your comments here are worthy of opening a wider discussion with SIG Auth which is the group the approved our current manual CA rotation documentation:
https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/
and essentially the process which you are trying to improve.

their contact details slack / mailing are here:
https://github.com/kubernetes/community/tree/master/sig-auth

you could ask them if they agree to your proposal.

> Intermediate CA certificates should only ever be bundled with the leaf certificate. This is the same way that certificates work for websites, with the OS or browser having access to only the root CA for verification and the server presenting the leaf certificate along with any intermediate CA certificates required to construct the chain back to the root CA.

for kubernetes at least, i have not seen anyone bundling an intermediate CA with a leaf certificate, including some vendors out there.
cc @randomvariable have you seen this?

> That's fair enough, I'd be happy to settle for just fixing the verification logic for now. I'll start working on a patch for just that part.

SGTM, we can review your patch after the 1.20 release.

> I probably could have worded this more clearly. I was referring to it being possible for users to do graceful rotation without resorting to a full external CA mode where they need to use kubeadm alpha certs generate-csr, copy the CSR files off of the node to get them to whichever external tool they use to issue certificates, then copy those certificates back onto the node and embed some of them in kubeconfig files. It's quite an involved process so I doubt many people would ever do this.

i don't have statistics for that, but from what i've seen users just maintain a bash script that can do these actions.
i can ping the author of the `generate-csr` command, for their take on your proposal - cc @wallrj

> Proper support in kubeadm for intermediate CA certificates could allow people to get the same benefits for signing CA rotation that I talked about above but without all of this extra work. In theory they would only need to feed in the intermediate CA .crt and .key and kubeadm could handle creating the chains. I think this would be a good thing to have, but if other users aren't having problems with the CA rotation workflow then it might not be worth spending time on.

this is what i'd like to know too. kubeadm users have been fine with the current external CA mode and mostly fine with the CA rotation documentation, so from the maintainer perspective this feels like an improvement that needs further evidence whether we should proceed on it.

**Comment by robbiemcmichael** [comment]
Thanks for the suggestion @neolit123, I'll try to bring this up with SIG Auth at some point to get some feedback from them.

**Comment by neolit123** [comment]
let's re-open this until more people comment and since i closed it without understanding the OP.

/kind feature
/reopen
/area security

**Comment by randomvariable** [comment]
The use case makes sense, as long as the caveats are understood about not using enterprise root CAs, but you could and maybe would want to do this using Vault for example.

I belive the verification issue is valid, kubeadm should be checking the chain. I'll check the PR.

**Comment by neolit123** [comment]
@robbiemcmichael given https://github.com/kubernetes/kubernetes/pull/97266 merged, please break down the exact details of what else do you want changed in a new issue and cross-reference to this discussion.

**Comment by gwaines** [comment]
@robbiemcmichael and @neolit123 

Any further work on @robbiemcmichael 's suggestion of Custom CA mode that he describes above ?

Just wanted to indicate that we (OpenStack StarlingX) have users / usecases where this exact behaviour is being asked for. 
I.e. users effectively want to have K8S use an ICA (cert+key) to auto-generate & sign all the K8S server/client certificates, where that ICA has been signed by an external RCA (whose ca.crt would only be provided for trust validation).
I.e. our users like the simple approach of K8S generating all the certificates, JUST WANT K8S to use an ICA (generated by users's own RCA), so that all the K8S certificates are part of that trusted certificate chain as well.

Because this is not available, we will likely have to use external ca mode and write scripts to have an ICA generate and sign the K8S server and client certificates correctly ... instead of using kubeadm to do that certificate generation.

Actually I think this is a common use case.
I.e. OpenStack StarlingX solution has many certificates, not just the K8S certificates.  Their our StarlingX infrastructure certificates for restapis and registries ... as well as hosted applications' certificates.  For simplicity, most users want all those certificates under the same certificate trust chain / RCA ... i.e. remote clients only need to trust one RCA to talk to any API on StarlingX.

Any updated views on this ?
Greg.




> Custom CA mode
> kubeadm supports users loading their own ca.crt and ca.key files (and their equivalents for etcd and front-proxy) onto the node and then allowing kubeadm to generate all of the required certificates. It would be great if it were possible to provide ca.crt, intermediate-ca.crt and intermediate-ca.key and then have kubeadm issue certificates with the intermediate CA. It would also need to append the intermediate CA certificate to the bundle for all of the .crt files as well as the embedded certificates in the kubeconfig files.
> 
> This is a much larger feature request, but this is what I imagine full support for a two-tier CA hierarchy would look like. This would give users an easy way to rotate their signing CA without resorting to generating CSRs and signing all certificates and kubeconfig files externally. Supporting this properly would make it much more accessible to use best practices such as shorter expiry dates on signing CAs.

**Comment by neolit123** [comment]
With the related PR that merged kubeadm accepts two tier CA as valid. External CA would still be the way to go for enterprise deployments since this allows to not inlclude a CA key on CP nodes.

Two tier CA is a really advanced use case that a majority of kubeadm users do not need, so I can help with a proposal review (KEP), but I think consensus from the maintainers will lean towards - use external CA and have kubeadm with single tier CA by default.

**Comment by arcreigh** [comment]
@neolit123 can this be revisited? two-tier PKI is a VERY common practice in enterprise work. And is HEAVILY utilized in federal / public sector. @gwaines is correct in his statements. 

Most if not all public sector / government entities utilize multi-tier PKI solutions with CRLs / OCSP for revocation. 

From a security standpoint it is faster to rotate an intermediate then it is to rotate a root CA and everything underneath that root. 

A large majority of entities utilizing PKI will use Microsoft ADCS offline root CAs that issue intermediates to anything that needs to issue certificates as this eases the deployment of said certs to the trust stores of the organizations servers / workstations. 

For large organizations this 100% makes sense and should be re-considered.

While it is possible to do this via External CA modes (while generating CSRs) this adds administrative burden to those in these larger environments when instead said organization could apply for an intermediate and call it a day.

**Comment by neolit123** [comment]
you can feed an org's intermediate CA as the "root" ca.crt for the cluster and let kubeadm generate, no?
i may have forgotten the technically of this issue from 5 years ago. if you have a simple PR in mind send it out and let's review.

anything that is done must NOT break existing users that use the default self-signed CA mode.
complex changes need a KEP https://github.com/kubernetes/enhancements/blob/master/keps/README.md that i don't think anyone from the kubeadm maintainers has the bandwidth to write.
