### ISSUE TITLE
kubeadm init phase upload-certs --experimental-upload-certs can't be uesd

### ISSUE THREAD

**Issue by wuchenyanghaoshuai** [kubernetes/kubeadm#2366]
error: unknown flag: --experimental-upload-certs
my kubeadm version was v1.13.0 
i want my new two nodes join in my cluster as master 
but this cmmand can't be used

**Comment by fabriziopandini** [comment]
Upload cert was added in v1.14, and according to Kubernetes policy new features are not backported.
Also, v1.13 is out of the support window as defined in https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions, so I'm leaning toward closing this issue

@neolit123 opinions?

**Comment by neolit123** [comment]
yes, you should use 1.14 for --experimental-upload-certs.
the flag is --upload-certs in newer versions.

instead of creating a 1.14 cluster use 1.18 or newer, which is supported.

/close
/kind support
