### ISSUE TITLE
I use kubeadm to build k8s,but I found this problem the Scheduler and controllerManager is unhealthy

### ISSUE THREAD

**Issue by sunshone** [kubernetes/kubeadm#2368]
I want to add --port=10251 and --port=10252 to overide the --port=0,but kubeadm cannot to build it .
I try to add --secure-port=10259 and --secure-port=10257 but kubeadm cannot to build it too.
![image](https://user-images.githubusercontent.com/69560953/102622307-c9f52080-417b-11eb-8219-666736dac4fa.png)

**Comment by neolit123** [comment]
Hi, please try posting on the support channels like #kubeadm or
discuss.k8s.io first.

/close
/kind support
