### ISSUE TITLE
Release branches e2e's should use k8s from release branches

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#237]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT (of e2e test)

Our kubeadm e2e test that runs against the release-1.6 branch currently specifies `--kubernetes-version latest` when initializing the cluster. This is probably the correct behavior for our tests against the `master` branch, but this should really be `latest-1.6` for the release-1.6 job, which will require new plumbing to kubetest.

Relevant part of kubetest: https://github.com/kubernetes/test-infra/blob/ab9c9911b771807f179e4cbab80b883042f27ba4/kubetest/anywhere.go#L53

The 1.6 job on testgrid: https://k8s-testgrid.appspot.com/release-1.6-blocking#kubeadm-gce-1.6

**Comment by luxas** [comment]
@pipejakob This is fixed, right?

**Comment by timothysc** [comment]
@pipejakob ping.

**Comment by luxas** [comment]
@pipejakob ping

**Comment by pipejakob** [comment]
This will be fixed by https://github.com/kubernetes/test-infra/pull/2761. The reviewer requested some changes that I haven't had time to address yet. It's definitely in my queue.

**Comment by luxas** [comment]
@pipejakob I updated the issue description to count both for v1.6 and v1.7

**Comment by pipejakob** [comment]
https://github.com/kubernetes/test-infra/pull/2761 has been merged, and our `release-1.6` and `release-1.7` jobs are back to green:

https://k8s-testgrid.appspot.com/google-gce#gce-kubeadm-1.6
https://k8s-testgrid.appspot.com/google-gce#gce-kubeadm-1.7

**Comment by luxas** [comment]
Thank you a lot @pipejakob for fixing that!
