### ISSUE TITLE
kubeadm init fails with node not found

### ISSUE THREAD

**Issue by bbellrose1** [kubernetes/kubeadm#2370]
I am trying to initialize the cluster for the first time. Seems to go fine until it tries to boot kubelet. Then it gets a node not found... 

$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:07:13Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

From init:

$ sudo kubeadm init --config=kubeadm_config.yaml --upload-certs -v=6
I1223 17:40:03.468687   91734 initconfiguration.go:201] loading configuration from "kubeadm_config.yaml"
I1223 17:40:03.469726   91734 initconfiguration.go:104] detected and using CRI socket: /run/containerd/containerd.sock
I1223 17:40:03.469838   91734 interface.go:400] Looking for default routes with IPv4 addresses
I1223 17:40:03.469844   91734 interface.go:405] Default route transits interface "ens192"
I1223 17:40:03.469991   91734 interface.go:208] Interface ens192 is up
I1223 17:40:03.470019   91734 interface.go:256] Interface "ens192" has 2 addresses :[10.220.12.145/24 fe80::e411:63f8:561d:1e17/64].
I1223 17:40:03.470033   91734 interface.go:223] Checking addr  10.220.12.145/24.
I1223 17:40:03.470039   91734 interface.go:230] IP found 10.220.12.145
I1223 17:40:03.470045   91734 interface.go:262] Found valid IPv4 address 10.220.12.145 for interface "ens192".
I1223 17:40:03.470050   91734 interface.go:411] Found active IP 10.220.12.145
I1223 17:40:03.479509   91734 version.go:182] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable.txt
[init] Using Kubernetes version: v1.20.1
[preflight] Running pre-flight checks
I1223 17:40:03.699015   91734 checks.go:577] validating Kubernetes and kubeadm version
I1223 17:40:03.699033   91734 checks.go:166] validating if the firewall is enabled and active
I1223 17:40:03.719375   91734 checks.go:201] validating availability of port 6443
I1223 17:40:03.719507   91734 checks.go:201] validating availability of port 10259
I1223 17:40:03.719523   91734 checks.go:201] validating availability of port 10257
I1223 17:40:03.719539   91734 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I1223 17:40:03.719553   91734 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I1223 17:40:03.719560   91734 checks.go:286] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I1223 17:40:03.719567   91734 checks.go:286] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I1223 17:40:03.719575   91734 checks.go:432] validating if the connectivity type is via proxy or direct
I1223 17:40:03.719594   91734 checks.go:471] validating http connectivity to first IP address in the CIDR
I1223 17:40:03.719616   91734 checks.go:471] validating http connectivity to first IP address in the CIDR
I1223 17:40:03.719624   91734 checks.go:102] validating the container runtime
I1223 17:40:03.730798   91734 checks.go:376] validating the presence of executable crictl
I1223 17:40:03.730835   91734 checks.go:335] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I1223 17:40:03.730871   91734 checks.go:335] validating the contents of file /proc/sys/net/ipv4/ip_forward
I1223 17:40:03.730889   91734 checks.go:649] validating whether swap is enabled or not
I1223 17:40:03.730906   91734 checks.go:376] validating the presence of executable conntrack
I1223 17:40:03.730935   91734 checks.go:376] validating the presence of executable ip
I1223 17:40:03.730948   91734 checks.go:376] validating the presence of executable iptables
I1223 17:40:03.730966   91734 checks.go:376] validating the presence of executable mount
I1223 17:40:03.730985   91734 checks.go:376] validating the presence of executable nsenter
I1223 17:40:03.731001   91734 checks.go:376] validating the presence of executable ebtables
I1223 17:40:03.731010   91734 checks.go:376] validating the presence of executable ethtool
I1223 17:40:03.731019   91734 checks.go:376] validating the presence of executable socat
I1223 17:40:03.731032   91734 checks.go:376] validating the presence of executable tc
I1223 17:40:03.731053   91734 checks.go:376] validating the presence of executable touch
I1223 17:40:03.731067   91734 checks.go:520] running all checks
I1223 17:40:03.741754   91734 checks.go:406] checking whether the given node name is reachable using net.LookupHost
I1223 17:40:03.742557   91734 checks.go:618] validating kubelet version
I1223 17:40:03.815761   91734 checks.go:128] validating if the "kubelet" service is enabled and active
I1223 17:40:03.830576   91734 checks.go:201] validating availability of port 10250
I1223 17:40:03.830645   91734 checks.go:201] validating availability of port 2379
I1223 17:40:03.830670   91734 checks.go:201] validating availability of port 2380
I1223 17:40:03.830697   91734 checks.go:249] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I1223 17:40:03.838710   91734 checks.go:845] pulling k8s.gcr.io/kube-apiserver:v1.20.1
I1223 17:40:06.289721   91734 checks.go:845] pulling k8s.gcr.io/kube-controller-manager:v1.20.1
I1223 17:40:08.511022   91734 checks.go:845] pulling k8s.gcr.io/kube-scheduler:v1.20.1
I1223 17:40:09.955515   91734 checks.go:845] pulling k8s.gcr.io/kube-proxy:v1.20.1
I1223 17:40:12.814572   91734 checks.go:845] pulling k8s.gcr.io/pause:3.2
I1223 17:40:13.497729   91734 checks.go:845] pulling k8s.gcr.io/etcd:3.4.13-0
I1223 17:40:18.550367   91734 checks.go:845] pulling k8s.gcr.io/coredns:1.7.0
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I1223 17:40:19.970967   91734 certs.go:110] creating a new certificate authority for ca
[certs] Generating "ca" certificate and key
I1223 17:40:20.142968   91734 certs.go:474] validating certificate period for ca certificate
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.nalk8s.railcarmgt.com nalshsvrk8ss01.railcarmgt.com] and IPs [10.96.0.1 10.220.12.145]
[certs] Generating "apiserver-kubelet-client" certificate and key
I1223 17:40:20.936427   91734 certs.go:110] creating a new certificate authority for front-proxy-ca
[certs] Generating "front-proxy-ca" certificate and key
I1223 17:40:21.064115   91734 certs.go:474] validating certificate period for front-proxy-ca certificate
[certs] Generating "front-proxy-client" certificate and key
I1223 17:40:21.214855   91734 certs.go:110] creating a new certificate authority for etcd-ca
[certs] Generating "etcd/ca" certificate and key
I1223 17:40:21.293940   91734 certs.go:474] validating certificate period for etcd/ca certificate
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost nalshsvrk8ss01.railcarmgt.com] and IPs [10.220.12.145 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [localhost nalshsvrk8ss01.railcarmgt.com] and IPs [10.220.12.145 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
I1223 17:40:22.313697   91734 certs.go:76] creating new public/private key files for signing service account users
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
I1223 17:40:22.407630   91734 kubeconfig.go:101] creating kubeconfig file for admin.conf
[kubeconfig] Writing "admin.conf" kubeconfig file
I1223 17:40:22.658168   91734 kubeconfig.go:101] creating kubeconfig file for kubelet.conf
[kubeconfig] Writing "kubelet.conf" kubeconfig file
I1223 17:40:22.791828   91734 kubeconfig.go:101] creating kubeconfig file for controller-manager.conf
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
I1223 17:40:23.012512   91734 kubeconfig.go:101] creating kubeconfig file for scheduler.conf
[kubeconfig] Writing "scheduler.conf" kubeconfig file
I1223 17:40:23.098365   91734 kubelet.go:63] Stopping the kubelet
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
I1223 17:40:23.372452   91734 manifests.go:96] [control-plane] getting StaticPodSpecs
I1223 17:40:23.372821   91734 certs.go:474] validating certificate period for CA certificate
I1223 17:40:23.372892   91734 manifests.go:109] [control-plane] adding volume "ca-certs" for component "kube-apiserver"
I1223 17:40:23.372898   91734 manifests.go:109] [control-plane] adding volume "etc-pki" for component "kube-apiserver"
I1223 17:40:23.372902   91734 manifests.go:109] [control-plane] adding volume "k8s-certs" for component "kube-apiserver"
I1223 17:40:23.388156   91734 manifests.go:126] [control-plane] wrote static Pod manifest for component "kube-apiserver" to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
I1223 17:40:23.388193   91734 manifests.go:96] [control-plane] getting StaticPodSpecs
I1223 17:40:23.388573   91734 manifests.go:109] [control-plane] adding volume "ca-certs" for component "kube-controller-manager"
I1223 17:40:23.388580   91734 manifests.go:109] [control-plane] adding volume "etc-pki" for component "kube-controller-manager"
I1223 17:40:23.388585   91734 manifests.go:109] [control-plane] adding volume "flexvolume-dir" for component "kube-controller-manager"
I1223 17:40:23.388590   91734 manifests.go:109] [control-plane] adding volume "k8s-certs" for component "kube-controller-manager"
I1223 17:40:23.388594   91734 manifests.go:109] [control-plane] adding volume "kubeconfig" for component "kube-controller-manager"
I1223 17:40:23.389535   91734 manifests.go:126] [control-plane] wrote static Pod manifest for component "kube-controller-manager" to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[control-plane] Creating static Pod manifest for "kube-scheduler"
I1223 17:40:23.389549   91734 manifests.go:96] [control-plane] getting StaticPodSpecs
I1223 17:40:23.389872   91734 manifests.go:109] [control-plane] adding volume "kubeconfig" for component "kube-scheduler"
I1223 17:40:23.390482   91734 manifests.go:126] [control-plane] wrote static Pod manifest for component "kube-scheduler" to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
I1223 17:40:23.391376   91734 local.go:74] [etcd] wrote Static Pod manifest for a local etcd member to "/etc/kubernetes/manifests/etcd.yaml"
I1223 17:40:23.391388   91734 waitcontrolplane.go:87] [wait-control-plane] Waiting for the API server to be healthy
I1223 17:40:23.393182   91734 loader.go:379] Config loaded from file:  /etc/kubernetes/admin.conf
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
I1223 17:40:23.396469   91734 round_trippers.go:445] GET https://nalshsvrk8ss01.railcarmgt.com:6443/healthz?timeout=10s  in 1 milliseconds
I1223 17:40:23.904958   91734 round_trippers.go:445] GET https://nalshsvrk8ss01.railcarmgt.com:6443/healthz?timeout=10s  in 6 milliseconds
I1223 17:41:02.897664   91734 round_trippers.go:445] GET https://nalshsvrk8ss01.railcarmgt.com:6443/healthz?timeout=10s  in 
0 milliseconds
...
[kubelet-check] Initial timeout of 40s passed.
I1223 17:41:03.397504   91734 round_trippers.go:445] GET https://nalshsvrk8ss01.railcarmgt.com:6443/healthz?timeout=10s  in 0 milliseconds
...
^C

From /var/log/messages
Dec 23 17:42:36 nalshsvrk8ss01 kubelet[92039]: E1223 17:42:36.551307   92039 kubelet.go:2240] node "nalshsvrk8ss01.railcarmgt.com" not found
Dec 23 17:42:36 nalshsvrk8ss01 kubelet[92039]: E1223 17:42:36.651514   92039 kubelet.go:2240] node "nalshsvrk8ss01.railcarmgt.com" not found

**Comment by neolit123** [comment]
> node "nalshsvrk8ss01.railcarmgt.com" not found

node not found is a misleading error by the kubelet. at this point it means that the kubelet was unable to register a Node object with the api server.

> https://nalshsvrk8ss01.railcarmgt.com:6443/healthz?timeout=10s in 0 milliseconds

this means that the api server is cannot be connected. could be caused by a number of things.

please try the support channels before logging a ticket in kubernetes/kubeadm:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close

**Comment by bbellrose1** [comment]
So how do you know this is not an issue? Firewall is disabled so the first assumption that it could be firewall is incorrect. I added a post to support forum. So far nothing has come of that.

**Comment by neolit123** [comment]
from what i see kubeadm init passes, but the api server cannot be reached. there are a number things that can cause this.
you need to closely inspect the kubelet logs.

"node x not found" is usually not relevant:
https://github.com/kubernetes/kubernetes/issues/90637
https://github.com/kubernetes/kubeadm/issues/1153
https://github.com/cri-o/cri-o/issues/2357

you can also try getting help from the #kubeadm channel on k8s slack, but it's the holidays.

**Comment by bbellrose1** [comment]
It was related to a parameter I had in my config file… I was passing anonymous-auth and that was the cause. Not sure why that would result in a node not found. Seems like Kubernetes has a lot to be desired in regards to error logging. This can be closed as I found the resolution.

Brian

**Comment by SahilSheikh1** [comment]
> control-plane-endpoint

This really helped , thank you

**Comment by atulram** [comment]
> I was setting up --control-plane-endpoint of a DNS name which was not resolved. Once I registered the domain name, it initialized successfully. The "real" error message is written somewhere in between the node not found errors.

It really helped

**Comment by mcy567** [comment]
我也遇到了同样的问题，我配置了：
http_proxy=socks5://127.0.0.1:23033
https_proxy=socks5://127.0.0.1:23033

我发现/var/log/messages有一个错误：

> Jul 14 02:01:26 cluster2-172-21-48-17 kubelet: E0714 02:01:26.738729  200430 kubelet.go:2424] "Error getting node" err="node \"cluster2-172-21-48-17\" not found"

> Jul 14 02:01:26 cluster2-172-21-48-17 kubelet: E0714 02:01:26.839151  200430 kubelet.go:2424] "Error getting node" err="node \"cluster2-172-21-48-17\" not found"

> Jul 14 02:01:26 cluster2-172-21-48-17 kubelet: E0714 02:01:26.845401  200430 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://172.21.48.17:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/cluster2-172-21-48-17?timeout=10s": **socks connect tcp 127.0.0.1:23033->172.21.48.17:6443:** read tcp 127.0.0.1:57814->127.0.0.1:23033: i/o timeout

> Jul 14 02:01:26 cluster2-172-21-48-17 kubelet: E0714 02:01:26.939811  200430 kubelet.go:2424] "Error getting node" err="node \"cluster2-172-21-48-17\" not found"

> Jul 14 02:01:27 cluster2-172-21-48-17 kubelet: E0714 02:01:27.040567  200430 kubelet.go:2424] "Error getting node" err="node \"cluster2-172-21-48-17\" not found"

172.21.48.17是我的本机IP(local ip)，访问这个IP地址竟然走了我的代理(proxy)！

then：
```
[root@cluster2-172-21-48-17 pods]# systemctl show-environment
HOSTNAME=cluster2-172-21-48-17
HTTPS_PROXY=socks5://127.0.0.1:23033
HTTP_PROXY=socks5://127.0.0.1:23033
LANG=en_US.utf8
NO_PROXY=127.0.0.1,localhost,cluster2-172-21-48-17
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

[root@cluster2-172-21-48-17 pods]# systemctl set-environment NO_PROXY=127.0.0.1,localhost,cluster2-172-21-48-17,172.21.48.17   # add a 172.21.48.17

[root@cluster2-172-21-48-17 pods]# systemctl show-environment
HOSTNAME=cluster2-172-21-48-17
HTTPS_PROXY=socks5://127.0.0.1:23033
HTTP_PROXY=socks5://127.0.0.1:23033
LANG=en_US.utf8
NO_PROXY=127.0.0.1,localhost,cluster2-172-21-48-17,172.21.48.17
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

[root@cluster2-172-21-48-17 pods]# systemctl restart  containerd
[root@cluster2-172-21-48-17 pods]# kubeadm init --ignore-preflight-errors=all
```
NO_PROXY add a 172.21.48.17
it works!

**Comment by durga61** [comment]
NO_PROXY was missing, worked after adding hostname

**Comment by mattjhammond** [comment]
I am running into a very similar issue to the original post.  I am in an air gapped install on an AWS EC2 with RedHat and have all of the dependencies and kubernetes images loaded from offline sources.  When I initialize the cluster, it uses the existing images loaded in podman and gets to the control plane boot.  It's referencing the AWS assigned host.compute.internal address.  I am able to ping that address and all other private addresses assigned by AWS.  If I attempt the initialization while the system has internet access the control plane starts with no issue.  I am inclined to think that there is an external service being called at this point in the process and it's not being reported in the logs as failing.  I am getting a node not found in the kubelet service logs.  Running v1.25.0 on CRI-O.

**Comment by yonyossef** [comment]
> Once I registered the domain name

What do you mean by that? I'm facing the same issue and can't resolve
