### ISSUE TITLE
deploy redis-cluster(6.0.0) with statefulset in K8s-3master results an error /var/lib/redis/nodes.conf is already used

### ISSUE THREAD

**Issue by John402-cloud** [kubernetes/kubeadm#2372]
## Is this a request for help?
yes

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## Versions

**kubeadm version** (use `kubeadm version`):
v1.17.4
**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.17.4
- **Cloud provider or hardware configuration**: X86_64 PC
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.4
- **Kernel** (e.g. `uname -a`): 5.4.0-56-generic
- **Others**: three physical machine. k8s has three master nodes and three workload nodes , and master nodes and workload nodes in one  machine 

## What happened?
when deploy redis-cluster(6.0.0) with statefulset (replicas: 6) only one pod running normal, other two pods results an error.

# kubectl logs redis-app-1
1:C 30 Dec 2020 08:24:30.008 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 30 Dec 2020 08:24:30.008 # Redis version=6.0.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 30 Dec 2020 08:24:30.008 # Configuration loaded
1:M 30 Dec 2020 08:24:30.018 # Sorry, the cluster configuration file /var/lib/redis/nodes.conf is already used by a different Redis Cluster node. Please make sure that different nodes use different cluster configuration files.

## What you expected to happen?
redis-cluster running normal in three master nodes

## Anything else we need to know?
# kubectl describe cm redis-conf
Name:         redis-conf
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
redis.conf:
----
appendonly yes
cluster-enabled yes
cluster-config-file /var/lib/redis/nodes.conf
cluster-node-timeout 5000
dir /var/lib/redis
port 6379

Events:  <none>

**Comment by neolit123** [comment]
> 1:M 30 Dec 2020 08:24:30.018 # Sorry, the cluster configuration file /var/lib/redis/nodes.conf is already used by a different Redis Cluster node. Please make sure that different nodes use different cluster configuration files.

hello, this seems to originate from Redis and doesn't seem like a kubeadm problem.
try logging the issue in the redis issue tracker.

/close
