### ISSUE TITLE
deleting the built-in cluster admin clusterrole does not seem to have any impact on authentication and authorization

### ISSUE THREAD

**Issue by liyongxin** [kubernetes/kubeadm#2373]
## Versions

**kubeadm version** (use `kubeadm version`):
v1.19.0

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
CentOS-7
- **Kernel** (e.g. `uname -a`):
3.10.0-1127.10.1.el7.x86_64
- **Others**:

## What happened?
I installed the kubernetes cluster with kubedm, and then deleted the default cluster admin cluster role, but the kubectl command still works

## What you expected to happen?
After deleting the cluster admin clusterrole, kubectl should report an error and the authentication failed

## How to reproduce it (as minimally and precisely as possible)?
 mkdir -p $HOME/.kube
 sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
 sudo chown $(id -u):$(id -g) $HOME/.kube/config
 kubectl delete clusterrole cluster-admin

## Anything else we need to know?
config file uses kubernetes admin user and system:masters Group k8s authentication and authorization, but deleting the built-in cluster admin clusterrole does not seem to have any impact on authentication and authorization

**Comment by neolit123** [comment]
i can confirm what you are seeing, but that's not a kubeadm problem.

kubeadm signs the following admin certificate:
```
        Issuer: CN = kubernetes
        Subject: O = system:masters, CN = kubernetes-admin
```

`system:masters` is bound in the `cluster-admin` ClusterRoleBinding.
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:masters
```

please log this ticket in the kubernetes/kubernetes repository and:
- ping me on it.
- add this command on a new line `/sig auth`
- link to this issue.

**Comment by neolit123** [comment]
@liyongxin 

to clarify the response here a little:
https://github.com/kubernetes/kubernetes/issues/97758#issuecomment-755295241

kubeadm creates a kubeconfig with a super user admin account.
you cannot remove the admin access to this account even if RBAC is disabled.

if you want to create separate administrator users check `kubeadm kubeconfig user`.
- don't share the super user admin account.
- create RBAC for a new Group - e.g. `my-admins`
- add ClusterRole and Binding for this group.
