### ISSUE TITLE
add the node.kubernetes.io/exclude-from-external-load-balancers label to kubeadm CP nodes

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2375]
this PR made it so that nodes labeled with `master` will no longer be excluded from Cluster scoped LoadBalancers:
https://github.com/kubernetes/kubernetes/pull/97543

to preserve backwards compatibility we way want to add a new label on CP nodes `node.kubernetes.io/exclude-from-external-load-balancers` that now handles the exclusion.

1.21:
- [x] add the label for init, join, upgrade
https://github.com/kubernetes/kubernetes/pull/98269

1.22:
- [x] the labeling on upgrade can be removed, assuming 1.21 CP nodes already have the label.
https://github.com/kubernetes/kubernetes/pull/100942

**Comment by neolit123** [comment]
please don't send a PR for this yet. we are tracking this for 1.21 but need some more discussion with SIG Network.

**Comment by pacoxu** [comment]
need we add it to upgrade check or add the label during cluster upgrade?

**Comment by neolit123** [comment]
yes, during upgrade we'd need to have `upgrade apply` applying the label to all CP nodes if it's not present.

**Comment by neolit123** [comment]
/assign
will draft a PR today.

**Comment by neolit123** [comment]
this is done for 1.22.
