### ISSUE TITLE
kubeadm: fix broken e2e tests for 1.21

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2380]
we have a couple of failing jobs, which i think happened after the version bumps for 1.21:
https://github.com/kubernetes/kubernetes/commit/7791bbe978d4dbcbb5694565c4a1c856bca48223

- skew latest on 1.20

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest-on-1-20

this i failing in kubeadm init under kinder when the `kubeadm config images list` is called. i tried the isolated command and it works, so it seems to be failing only under kinder for some reason.

- upgrade 1.20 -> latest

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-20-latest

upgrade is failing with:
> this version of kubeadm only supports deploying clusters with the control plane version >= 1.20.0. Current version: v1.20.0-beta.2.96+98bc258bf5516b

then reset timeouts (runs more than 5 min)

**Comment by neolit123** [comment]
looks like the problem here is that https://console.cloud.google.com/storage/browser/_details/k8s-release-dev/ci/latest-1.20.txt which kinder uses to resolve e.g. `ci/latest-1.20` to `v1.20.0-beta.2.96+98bc258bf5516b`

the new bucket we switched to [here](https://github.com/kubernetes/kubeadm/pull/2379) does not have the latest versions:

the latest version reported by https://dl.k8s.io/ci/latest-1.20.txt points to the latest valid version:
`https://dl.k8s.io/ci/latest-1.20.txt`

**Comment by neolit123** [comment]
> looks like the problem is the new bucket we switched to [here](https://github.com/kubernetes/kubeadm/pull/2379).
> 
> https://console.cloud.google.com/storage/browser/_details/k8s-release-dev/ci/latest-1.20.txt resolves to `v1.20.0-beta.2.96+98bc258bf5516b`
> 
> the latest version reported by https://dl.k8s.io/ci/latest-1.20.txt is the valid one:
> `v1.20.3-rc.0.15+18194169ac684f`
> but this version and the artifacts are missing in the new bucket.

**Comment by neolit123** [comment]
lets keep this open until the tests become green:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-20-latest

checking https://console.cloud.google.com/storage/browser/_details/k8s-release-dev/ci/latest-1.20.txt still points to an old tag.

**Comment by SataQiu** [comment]
It seems that the job did not execute successfully.
https://testgrid.k8s.io/sig-release-1.20-blocking#build-1.20

**Comment by neolit123** [comment]
looking at the logs i don't understand why it's failing. i see this:
> W0128 15:18:14.861] subprocess.CalledProcessError: Command '('../release/push-build.sh', '--nomock', '--verbose', '--ci', '--bucket=k8s-release-dev', '--docker-registry=gcr.io/k8s-staging-ci-images', '--extra-version-markers=k8s-beta', '--allow-dup')' returned non-zero exit status 1

**Comment by spiffxp** [comment]
I opened a fix for this yesterday but test-infra is having merging issues (ref: https://github.com/kubernetes/test-infra/pull/20586#issuecomment-769248541)

**Comment by neolit123** [comment]
thanks @spiffxp

**Comment by neolit123** [comment]
https://github.com/kubernetes/test-infra/pull/20624 indeed fixed the 2 failing tests :tada: 
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm

/close
