### ISSUE TITLE
how to add more controlPlaneEndpoint using kubeadm ?

### ISSUE THREAD

**Issue by denghuancong** [kubernetes/kubeadm#2384]
## Versions

**kubeadm version** (use `kubeadm version`):  
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:25:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):v1.20.2
- **Cloud provider or hardware configuration**: local deploy
- **OS** (e.g. from /etc/os-release): centos 7.6
- **Kernel** (e.g. `uname -a`): 4.1.0-25
- **Others**:

## how to add more controlPlaneEndpoint using kebeadm? 
```
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc mq state UP qlen 1000
    link/ether 52:54:00:6f:18:c2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.13/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe6f:18c2/64 scope link
       valid_lft forever preferred_lft forever
4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 52:54:00:b0:0c:e4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.179.24/24 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:feb0:ce4/64 scope link
       valid_lft forever preferred_lft forever
```
kubeadm init controlplane using  10.0.0.13, but. we want to use 192.168.179.24 too, how can I do that?

**Comment by neolit123** [comment]
> kubeadm init controlplane using 10.0.0.13, but. we want to use 192.168.179.24 too, how can I do that?

hi, kubeadm has no plans to enable multiple control-plane endpoints.

you can achieve what you want with iptables routing:
https://unix.stackexchange.com/questions/156151/iptables-routing-incoming-ip-to-another-destination-ip-question

for other tricks you can ask in #kubeadm on k8s slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
