### ISSUE TITLE
Create extra new containers after every reboot

### ISSUE THREAD

**Issue by summerisc** [kubernetes/kubeadm#2385]
BUG REPORT

## Versions

**kubeadm version**:
{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:25:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- {Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- **OS** (e.g. from /etc/os-release):
- Ubuntu 18.04.5 LTS
- **Kernel** (e.g. `uname -a`):
- Linux 5.4.0-64-generic 

## What happened?
After rebooting the machine, kubeadm will create new containers and leave the old containers exited and stay there.
![Screen Shot 2021-02-01 at 2 44 58 PM](https://user-images.githubusercontent.com/21230663/106509802-11214180-649c-11eb-8f92-a2f571c36e44.png)

## What you expected to happen?
Is there a way we could reuse the old containers otherwise every reboot requires a manual clean up of the old containers.

## How to reproduce it (as minimally and precisely as possible)?
Reboot the machine and check docker containers.

**Comment by neolit123** [comment]
hi, please log this ticket in the kubernetes/kubernetes repository.
kubeadm does not manage the containers and it's the kubelet that's doing that.

tag the ticket with these commands: `/sig node` and `/area kubelet` and ping me @neolit123 on it.

thanks.

/close
/sig node

**Comment by neolit123** [comment]
though looking at your logs....

the pause container is duplicated by design. it acts like a sandbox - [read more here](https://www.ianlewis.org/en/almighty-pause-container).

the old containers i see exited.
is something else duplicated that you worry about?

**Comment by summerisc** [comment]
Hi, Thanks for the prompt reply. I will add this to k8s repo. To fill in a little bit more info here though, totally understand pause container duplication. While as you can see old containers all exited and after every reboot, it will create all new containers again, so if a server reboot a few times, it will have lots of exited unused containers for k8s, is this also by design?

**Comment by neolit123** [comment]
its the responsibility of the kubelet to GC old containers:
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#container-collection
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#user-configuration

you can experiment with the flags, but if you are seeing these containers stay "exited" indefinitely you can file the bug in kubernetes/kubernetes.
