### ISSUE TITLE
Master HA in IPV6 environment

### ISSUE THREAD

**Issue by chenysr** [kubernetes/kubeadm#2392]
Does Kubeadm support Kubernetes Master High availability on IPV6 environment ?
If it is supported, Could you please share me the inputs on the sample kubeadm configuration to bring up the cluster on IPV6?
Any support document is also helpful.

Thanks in advance.

**Comment by neolit123** [comment]
hi, it does.
but please note that the general ipv6 support in k8s is not GA yet.

for more questions you can ask in #kubeadm on k8s slack.

/close
/kind support

**Comment by fabriziopandini** [comment]
@chenysr this would be a great opportunity to contribute such a doc either in the K8s WebSite or in the kubeadm repo docs, such document could be really useful for other users as well 😉

**Comment by neolit123** [comment]
as one of the items here https://github.com/kubernetes/kubeadm/issues/1612 we have writing docs for dual stack usage with kubeadm.
