### ISSUE TITLE
remove ClusterConfiguration.DNS.Type

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2398]
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#DNS

with the removal of kube-dns:
https://github.com/kubernetes/kubernetes/pull/99646

kubeadm no longer supports multiple DNS types:
this is scheduled for v1beta3.

**Comment by pacoxu** [comment]
Is there a plan to install node-local-dns in `kubeadm init`. It was GAed in kubernetes for monthes.

**Comment by neolit123** [comment]
we had an issue for this is k/kubeadm:
https://github.com/kubernetes/kubeadm/issues/1220

we voted to have this as an addon / operator and not be part of kubeadm.

see:
https://github.com/kubernetes/kubeadm/issues/1220#issuecomment-553530193
https://github.com/kubernetes-sigs/cluster-addons/issues/34
