### ISSUE TITLE
kubeadm could store a configmap with some of it's flags

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#24]
_From @errordeveloper on October 4, 2016 17:14_

Things like service CIDR and pod network CIDR, cluster DNS domain are useful for network and other similar type of add-ons, also there has been some ideas around general accessibility of key parameters. Other example may include cloud provider name, CNI config path and other bits of information that are scatered in kubelet, kube-apiserver and kube-controller-manager flags. Let's discussed this more specifically.

_Copied from original issue: kubernetes/kubernetes#34025_

**Comment by mikedanese** [comment]
_From @pires on October 5, 2016 9:58_

1. What would be the use for the ConfigMap after it's stored?
2. Store it where, disk or API?

**Comment by mikedanese** [comment]
_From @pires on October 5, 2016 11:35_

Also, I just realized #33728 got merged so I believe we'll already have this info stored in the API as soon as we get assigned an apigroup?

**Comment by mikedanese** [comment]
_From @luxas on October 15, 2016 7:54_

I don't understand why this should be done.
Please clarify this now when we already have the api group and the possibility of specifying flags via a file

**Comment by luxas** [comment]
We won't do this per se, but https://github.com/kubernetes/community/pull/662 is highly relevant
