### ISSUE TITLE
Service DNS broken due to wrong CoreDNS IP addresses

### ISSUE THREAD

**Issue by ingobecker** [kubernetes/kubeadm#2400]
# Bugreport

## Versions

**kubeadm version**:
`kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:09:38Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version**: `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: libvirt 2GB RAM/ 2 vcpu
- **OS** (e.g. from /etc/os-release): `Fedora CoreOS 33.20210217.3.0`
- **Kernel**: `Linux master 5.10.12-200.fc33.x86_64 #1 SMP Mon Feb 1 02:40:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

## What happened?
Running `kubeadm init` creates CoreDNS pods with an IP address outside of the supplied `podSubnet: 10.244.0.0/16`. Somehow those pods end up having an IP from the subnet `10.88.0.0/24`. If i skip the `addon/coredns` phase, deploy the pod network addon first and, once the cni is up, run the `addon/coredns`, the coredns pods have an IP address from the correct subnet. Restarting the CoreDNS deployment also fixes this issue. This problem breaks the service dns name resolution for any pod because the CoreDNS server is unreachable due to its wrong IP.

## What you expected to happen?
CoreDNS pods should receive IP addresses from the specified `podSubnet`.

## How to reproduce it (as minimally and precisely as possible)?
`$ kubeadm init`

## Anything else we need to know?
- CNI: `flannel`

**Comment by neolit123** [comment]
you must pass `--pod-network-cidr=10.244.0.0/16` to kubeadm init, for flannel to work?
in general the kubeadm team does not support flannel since it has way too many problems in other areas too...
we recommend other CNIs like Calico. newer Calico versions doesn't to be explicit about the POD CIDR since it has it's own IPAM.

for more questions please use #kubeadm on k8s slack.

/close
/kind support

**Comment by ingobecker** [comment]
Thanks for the reply. I supplied a pod cidr using a `ClusterConfiguration`s `podSubnet` set to subnet mentioned. I think using a different CNI won't change the problem. If i don't skip the `addon coredns` phase and defer it until a CNI is in place, the CoreDNS pods will be started with the wrong IP range nonetheless. So is skipping the CoreDNS phase recommended to avoid this?

**Comment by neolit123** [comment]
i don't see this problem in my setup or in the kubeadm e2e tests.
