### ISSUE TITLE
Is there really a need to restart the control plane components after kubeadm cert renew?

### ISSUE THREAD

**Issue by geotransformer** [kubernetes/kubeadm#2409]
## What keywords did you search in kubeadm issues before filing this one?
certs renew

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):  v1.20.0
**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.20.0
- **Cloud provider or hardware configuration**: vsphere
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
- **Kernel** (e.g. `uname -a`): 5.4.0-49-generic
- **Others**:
~$ kubectl get pods -A -l tier=control-plane
NAMESPACE     NAME                                         READY   STATUS    RESTARTS   AGE
kube-system   etcd-xxxx                                        1/1     Running   0          33h
kube-system   kube-apiserver-xxxx                      1/1     Running   0          33h
kube-system   kube-controller-manager-xxxx    1/1     Running   1          33h
kube-system   kube-scheduler-xxxx                    1/1     Running   1          33h

## What happened?
 $ sudo kubeadm alpha certs renew all
Done renewing certificates. You must restart the kube-apiserver, kube-controller-manager, kube-scheduler and etcd, so that they can use the new certificates.

I did NOT restart control plane pods/containers. But when I tried the api-server or etcd api. I found the server cert were already new certs.

If the certs will be reloaded automatically, why there is a need to restart those control plane components after kubeadm certs renew

## What you expected to happen?
After kubeadm certs renew, if no control plane component restart, the server cert should be the same.

## How to reproduce it (as minimally and precisely as possible)?
1>  curl -k -v https://localhost:6443
2> Check the following output
* Server certificate:
*  subject: CN=kube-apiserver
*  start date: Mar  4 01:06:56 2021 GMT
*  **expire date: Mar 13 04:10:04 2022 GMT**
*  issuer: CN=kubernetes

## Anything else we need to know?

Is there really a need to restart the control plane components after kubeadm cert renew?

**Comment by neolit123** [comment]
> I did NOT restart control plane pods/containers. But when I tried the api-server or etcd api. I found the server cert were already new certs.

you need to check if all components are now using the new certs.

> If the certs will be reloaded automatically, why there is a need to restart those control plane components after kubeadm certs renew

AFAIK, the automatic reload of certificates from disk for the control-plane components is something that is work in progress, but i can't find the tracking issue.

until we get confirmation that restart is no longer needed, we are going to keep this message and recommend it to users.

/kind support
/close

**Comment by geotransformer** [comment]
> > I did NOT restart control plane pods/containers. But when I tried the api-server or etcd api. I found the server cert were already new certs.
> 
> you need to check if all components are now using the new certs.
> 
> > If the certs will be reloaded automatically, why there is a need to restart those control plane components after kubeadm certs renew
> 
> AFAIK, the automatic reload of certificates from disk for the control-plane components is something that is work in progress, but i can't find the tracking issue.
> 
> until we get confirmation that restart is no longer needed, we are going to keep this message and recommend it to users.
> 
> /kind support
> /close



> > I did NOT restart control plane pods/containers. But when I tried the api-server or etcd api. I found the server cert were already new certs.
> 
> you need to check if all components are now using the new certs.
> 
> > If the certs will be reloaded automatically, why there is a need to restart those control plane components after kubeadm certs renew
> 
> AFAIK, the automatic reload of certificates from disk for the control-plane components is something that is work in progress, but i can't find the tracking issue.
> 
> until we get confirmation that restart is no longer needed, we are going to keep this message and recommend it to users.
> 
> /kind support
> /close

Thanks for the prompt reply. Would you please follow up this issue so that we can get it confirmed? This is a critical issue in production env.

**Comment by neolit123** [comment]
> Thanks for the prompt reply. Would you please follow up this issue so that we can get it confirmed? This is a critical issue in production env.

this might take years.

dynamic reload of certificates from disk is added for one flag at a time and there is no parent tracking issue, that i can find...

therefore, you must restart the components.

if you look at our guide for rotating cluster CA, component restart is required after almost every change for a certificate on disk:
https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

if you wish to avoid downtime of the control-plane, you should introduce high-availability:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

**Comment by geotransformer** [comment]
> kubernetes/kubernetes#83579

Thanks
Also found these two issue relevant 
https://github.com/kubernetes/kubernetes/pull/84200
https://github.com/kubernetes/kubernetes/pull/84303

**Comment by geotransformer** [comment]
Seems no need to to restart etcd
Found this in security guide
https://etcd.io/docs/v3.4.0/op-guide/security/

Notes for TLS authentication
Since v3.2.0, TLS certificates get reloaded on every client connection. This is useful when replacing expiry certs without stopping etcd servers; it can be done by overwriting old certs with new ones. Refreshing certs for every connection should not have too much overhead, but can be improved in the future, with caching layer. Example tests can be found here.
