### ISSUE TITLE
docker-ce

### ISSUE THREAD

**Issue by blackstar257** [kubernetes/kubeadm#241]
[preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.03.1-ce. Max validated version: 1.12
[preflight] Some fatal errors occurred:
	missing cgroups: memory
	Port 10250 is in use
	/etc/kubernetes/manifests is not empty
	/var/lib/kubelet is not empty
[preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`

**Comment by errordeveloper** [comment]
I've been using it with `--skip-preflight-checks` and haven't encountered any issues so far.

**Comment by P4z** [comment]
From a user point of view the error message clearly states that this is a serious (fatal) problem resulting in cluster initialization failure. This is my very first attempt to try the kubernetes and I have no idea about the impact of ```missing cgroups: memory``` on the setup. I will risk switching ```--skip-preflight-checks``` on this Jessie box equipped with Xenial repository for kubernetes but I'm afraid that I may hit other missing dependencies without being aware of.

@errordeveloper, is this an already known issue scheduled for fixation? Clear and accurate log messages are invaluable specifically for newcomers.
