### ISSUE TITLE
Add global CA_BUNDLE to a cluster

### ISSUE THREAD

**Issue by velcrine** [kubernetes/kubeadm#2415]
Kind: FEATURE REQUEST

This is a feature in OpenShift: https://docs.openshift.com/container-platform/4.3/networking/configuring-a-custom-pki.html#configuring-a-custom-pki
It gives functionality to add cluster-wide trust bundle

I am using admissionControllers, which are restricted to only allow TLS. 
In case of providing the "request endpoint", for kubernetes service resource there is a field to provide CABUNDLE. But in case i set the "request endpoint" to an extenal url, that CABUNDLE is of no use.

Please provide a way to allow to add CABUNDLE throught the cluster for every purpose during non-prod use. Specifically, it will also enable to specify external url for admissionControllers, but use-cases are not limited till here.

**Comment by neolit123** [comment]
Hi. This is not a kubeadm feature request. If you want to add a CA bundle
to admission controllers / webhooks this is not something kubeadm can do
for you.

For questions on how to set this up properly try asking in #sig-auth on k8s
slack.

/close
/kind support

**Comment by velcrine** [comment]
@neolit123 this is not about admission controller, but admission controller is just an application of it. I want to add CA_bundle globally in kuberntes. Kubernetes must be using a list of Known CAs. I want to add my CA's root certificate to that as we can do in operating systems.
Pls reopen.

**Comment by neolit123** [comment]
>  I want to add CA_bundle globally in kuberntes. Kubernetes must be using a list of Known CAs. I want to add my CA's root certificate to that as we can do in operating systems.

again, this is not a kubeadm issue. if something is missing in core kubernetes, log a ticket in the kubernetes/kubernetes repository and/or ask in #sig-auth.

kubeadm allows you to configure the core k8s components.

> I want to add my CA's root certificate to that as we can do in operating systems.

the kube-apiserver and kube-controller manager mount and use the following folders:
/usr/local/share/ca-certificates
/etc/ssl/certs
/etc/ca-certificates

/sig auth

**Comment by velcrine** [comment]
Thanks neolit123 for this information

**Comment by velcrine** [comment]
so If I add a ca.pem in /etc/ssl/certs . Would it be honoured and accepted by kubernetes too?
