### ISSUE TITLE
windows: absolute paths do not work properly in config files

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2419]
on Windows there is a problem with the go standard library where the filepath.Abs() function
https://golang.org/pkg/path/filepath/#IsAbs

would return false for a path `/foo/bar`. this is by-design and is in a way correct, since absolute paths on Windows would normally need a drive letter - e.g. `c:/foo/bar`. (note: \ vs / are interchangeable)
yet, a path without a drive letter can still be considered absolute to the current drive.

this is hardcoded in client-go, kubelet and the rest of k8s where if you pass a path to a certificate in a kubeconfig file without a drive letter on windows it would assume a relative path and covert something like `/foo/bar/ca.crt` to `/localpath/foo/bar/ca.crt`, causing errors.

the problem was observed in KubeletConfiguration that kubeadm generates and shares between nodes, and the fix was in the lines of this:
https://gist.github.com/neolit123/1b7375c8a956155a2ca1cdd901336bce
but this has to be double checked.

a couple of more problems where this can happen are:
- the kubeadm API validation of absolute path for socket.
- the kubelet.conf file which kubeadm mutates after init to point to rotatable client cert/key.

what kubeadm must do to properly support Windows paths without too much user interaction is to convert them by determining the local drive  `/foo/bar/ca.crt` ->  `c:/foo/bar/ca.crt` (example in the above gist)

**Comment by neolit123** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/105992
thanks to @hwdef

**Comment by hwdef** [comment]
> fixed in [kubernetes/kubernetes#105992](https://github.com/kubernetes/kubernetes/pull/105992) thanks to @hwdef

Thanks for your help!
