### ISSUE TITLE
Needs to renew cluster K8 certificates for multiple years

### ISSUE THREAD

**Issue by chittu11** [kubernetes/kubeadm#2433]
I need to renew Kubernetes certs in our environment. Now I want to renew the certs for multiple year instead default one year. Can someone point me how can I achieve it?

I renewed certs to 1 year by using the below command. is there anyway I can include the expiry time in this command?

`#kubeadm alpha certs renew all `

We are using 1.18.1 version

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Thank you
CS

**Comment by neolit123** [comment]
hi, the 1 year expiration is hardcoded in kubeadm intentionally.
cluster certificates with expiration more than 1 year are insecure and it is not likely that this will change anytime soon.

kubeadm allows you to pass external CA and certificates which can be for any period.
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#external-ca-mode

alternatively you can create a CronJob that rotates certificates every year.

for more questions please use:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/c;lose
