### ISSUE TITLE
kubeadm upgrade apply fails 

### ISSUE THREAD

**Issue by challapradyumna** [kubernetes/kubeadm#2437]
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.17.17 / 1.17.9

**Environment**:
- **Kubernetes version** (use `kubectl version`):1.17.9
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
Upgrading from 1.17.9 to 1.17.17 . There is an already existing kube-dns service with a cluster IP which is not "10.9.0.10". Since ClusterIP cannot be updated in a Service object. The upgrade fails. 

## What you expected to happen?
Option 1: Have an option to skip DNS upgrade
Option 2: Verify if kube-dns has CoreDNS pods with required version and skip kube-dns upgrade.

## How to reproduce it (as minimally and precisely as possible)?
Create kube-dns service which is not having a clusterIP of '10.9.0.10' and use kubeadm upgrade apply. 

## Anything else we need to know?
Error Message - unable to create/update the DNS service: Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.9.0.10": field is immutable
Here is the location of code where it fails - https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/cmd/kubeadm/app/phases/addons/dns/dns.go#L251

**Comment by neolit123** [comment]
> Upgrading from 1.17.9 to 1.17.17 

1.17 is no longer in support.
you might have patch kubeadm locally and use a modified binary to be able to upgrade.

> Option 1: Have an option to skip DNS upgrade

this is not possible currently in kubeadm. we want to be able to support phases for `kubeadm upgrade apply` which will allow --skip-phases.

> Option 2: Verify if kube-dns has CoreDNS pods with required version and skip kube-dns upgrade.

i don't understand this option. are you suggesting that upgrade should be skipped if the user already did it manually?

in newer versions of kubeadm upgrade can be skipped if you:
- rename the coredns configmap
- pass --ingnore-preflight-errors to kubeadm

> Error Message - unable to create/update the DNS service: Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.9.0.10": field is immutable

well the field is immutable, so it cannot updated like that.

to avoid the error (instead of patching kubeadm) you can try:
- removing the service object.
- let kubeadm upgrade re-create it.
- create it again with your desired values.

cc @rajansandeep 

/kind support

**Comment by challapradyumna** [comment]
> i don't understand this option. are you suggesting that upgrade should be skipped if the user already did it manually?

Yes, if there service already exists with a version of Compatible CoreDNS. Update could be skipped.

A possible solution that I've arrived at for upgrading production clusters with 0 downtime (Little long but works) : 

* Create a new service with a different name and with ClusterIP address other than `10.9.0.10`
* Update the ClusterIP for the above-created service into kubelet-1.x ConfigMap in kube-system namespace
* Propagate this change across the cluster by decommissioning all current nodes and joining new nodes which will talk to ClusterIP of the new service for DNS
* Delete `kube-dns` service 
* Upgrade the Cluster
* (Optional) Clean up the above mess
  *  Update kubelet-1.x ConfigMap to 10.9.0.10 which should be the ClusterIP of kube-dns service created by Kubeadm
  * Decomm all current nodes and join new nodes
  * Delete the service created for upgrade purpose. 

Hope it helps someone !!

**Comment by neolit123** [comment]
hi, your solution does seems like something that would work.

you can also try this, which is simpler:
> - rename the coredns configmap
> - pass --ingnore-preflight-errors to kubeadm

> this is not possible currently in kubeadm. we want to be able to support phases for kubeadm upgrade apply which will allow --skip-phases for the dns addon.

^ i'm going to close this ticket given we are already planning to support skipping upgrade via phases.
https://github.com/kubernetes/kubeadm/issues/1318

this effort is unstaffed ATM, though - i.e. help is wanted.

**Comment by rajansandeep** [comment]
@neolit123 if there is no one taking on this effort, I can help in completing the task.

**Comment by neolit123** [comment]
@rajansandeep sure! note that it requires some refactoring before it can be done.
https://github.com/kubernetes/kubeadm/issues/1318 has the details.
