### ISSUE TITLE
kubeadm kubeconfig user raises error for 1.20 and higher

### ISSUE THREAD

**Issue by JukkaKeisala** [kubernetes/kubeadm#2438]
## Is this a request for help?

Yes,

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**: v1.21.0 and v1.20.0

**Environment**:
- **Kubernetes version**: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: on-Premise, 6 virtual machines, 3 master + 3 worker node (all having v1.21.0 kubectl, kubeadm, kubelet and same os/kernel/others)
- **OS** (e.g. from /etc/os-release): CentOS 8
- **Kernel** (e.g. `uname -a`): 4.18.0-240.22.1.el8_3.x86_64

## What happened?
After succesful multinode cluster installation (3 master, 3 worker) and succesful client-name creation by
```bash
kubectl create clusterrolebinding myusername --clusterrole=cluster-admin --user=myusername
```

I tried to generate kubeconfig file for this user `myusername`. The command I used was

```bash
sudo kubeadm kubeconfig user --client-name myusername --config /etc/kubernetes/admin.conf
```

the result was

```text
invalid configuration for GroupVersionKind /v1, Kind=Config: kind and apiVersion is mandatory information that must be specified
To see the stack trace of this error execute with --v=5 or higher
```

## What you expected to happen?

I expected a kubeconfig result.

## How to reproduce it (as minimally and precisely as possible)?

```bash
kubectl create clusterrolebinding myusername --clusterrole=cluster-admin --user=myusername
sudo kubeadm kubeconfig user --client-name myusername --config /etc/kubernetes/admin.conf
```

## Anything else we need to know?

I downgraded `kubeadm` to `v1.20.0` but the same result occured. After downgrading to `v1.19.0` the I got the result I wanted. At this point I'd like to remind that flag `--config` wasn't necessary in `v1.19.0` and also the command is not in alpha stage anymore.

**Comment by neolit123** [comment]
> sudo kubeadm kubeconfig user --client-name myusername --config /etc/kubernetes/admin.conf

for --config you should be passing kubeadm configuration:

i think the minimal config that works is:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
```

you might want to set `controlPlaneEndpoint` and `clusterName` in there:
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

/kind support

**Comment by JukkaKeisala** [comment]
Thanks, didn't really understand what was a kubeadm config file but of course that can be exported from configmap.
