### ISSUE TITLE
kubeadm fails preflight check with customized /etc/containerd/config.toml

### ISSUE THREAD

**Issue by dmitry-irtegov** [kubernetes/kubeadm#2449]
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): `kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:30:03Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): Bug hits before the kubernetes is installed.
- **Cloud provider or hardware configuration**: VirtualBox VM, 4 CPU, 8GB RAM
- **OS** (e.g. from /etc/os-release):  `CentOS Linux release 7.9.2009 (Core)`
- **Kernel** (e.g. `uname -a`): `Linux osboxes.org 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

- **Others**: 
- **Containerd**:  installed from repo docker-ce-stable 
```
sudo ctr version
Client:
  Version:  1.4.4
  Revision: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
  Go version: go1.13.15

Server:
  Version:  1.4.4
  Revision: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
  UUID: 887d41ff-262b-4c82-9943-aafc562c0f1e
```

## What happened?

I was trying to customize containerd to use systemd cgroup.  To do this, I edited the yum-supplied `/etc/containerd/config.toml` (commented lines are skipped):
```
disabled_plugins = []

imports = ["/etc/containerd/my.toml"]
```
The content of `/etc/containerd/my.toml`:
```
version = 2

  [plugins."io.containerd.grpc.v1.cri"]
    systemd_cgroup = true
```

`containerd config dump` displayed that the parameter changed, containerd service restarted without error and I could operate it using ctr.

Other preparation steps like modprobes, sysctl, etc were performed according to https://kubernetes.io/docs/setup/production-environment/container-runtimes/

Then I run `kubeadm init phase preflight` and get the following output:

```
$ sudo kubeadm init phase preflight
W0415 10:14:52.842753   15962 version.go:102] could not fetch a Kubernetes version from the internet: unable to get URL "https://dl.k8s.io/release/stable-1.txt": Get "https://storage.googleapis.com/kubernetes-release/release/stable-1.txt": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
W0415 10:14:52.842895   15962 version.go:103] falling back to the local client version: v1.21.0
[preflight] Running pre-flight checks
	[WARNING Firewalld]: firewalld is active, please ensure ports [6443 10250] are open or your cluster may not function correctly
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR CRI]: container runtime is not running: output: time="2021-04-15T10:14:52-04:00" level=fatal msg="getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
, error: exit status 1
```
 Without `imports = ["/etc/containerd/my.toml"]` the preflight check passes.

This closely resembles https://github.com/containerd/containerd/issues/4581 , but that issue is closed and this seems to be kubeadm, not containerd issue.

## What you expected to happen?

Preflight check passes with customized containerd conf.toml.  Or, at least, emits more meaningful message.

**Comment by wangyysde** [comment]
@dmitry-irtegov Maybe you should disable firewall,enable kubelet service and disalbe selinux.

**Comment by neolit123** [comment]
for containerd kubeadm runs this check
```
crictl -r <socket> info
```
and if the command fails kubeadm will show whatever the command error output is.
you should debug why this fails.

crictl is automatically installed for you if you use deb/rpms and you must install it manually if you are not using packages.

> This closely resembles containerd/containerd#4581 , but that issue is closed and this seems to be kubeadm, not containerd issue.

it is outside of the scope of kubeadm to setup the container runtime for the user.
you must do this following the guide at https://kubernetes.io/docs/setup/production-environment/container-runtimes/
if the guide there is incomplete please send a PR for that docs page at k/website.

/kind support
/close

**Comment by neolit123** [comment]
> The content of /etc/containerd/my.toml:

> Without imports = ["/etc/containerd/my.toml"] the preflight check passes.

i suspect that containerd is simply not happy with this import.
you can try instead adding the cgroup driver change inside the main config.toml.

**Comment by dmitry-irtegov** [comment]
```
$ sudo crictl --debug -r /run/containerd/containerd.sock info
DEBU[0000] StatusRequest: &StatusRequest{Verbose:true,} 
DEBU[0000] StatusResponse: nil                          
FATA[0000] getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
```
Similar error occurs with other commands, like stats, pull...

It seems to really be a containerd configuration issue.  I've found this in containerd logs:

`апр 15 09:47:24 osboxes.org containerd[15482]: time="2021-04-15T09:47:24.760703175-04:00" level=warning msg="failed to load plugin io.containerd.grpc.v1.cri" error="invalid plugin config: `systemd_cgroup` only works for runtime io.containerd.runtime.v1.linux"`

**Comment by dmitry-irtegov** [comment]
The output of systemd_cgroup parameter in 1.3+ is a known bug in containerd, see https://github.com/containerd/containerd/issues/4574

The snippet in https://github.com/containerd/containerd/issues/4203#issuecomment-651532765 at least allows cri plugin to start.  However I've yet to test if cgroups are working properly.
