### ISSUE TITLE
Create a mailing list for kubeadm CI error

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#2451]
As per [comment](https://github.com/kubernetes/kubeadm/pull/2434/files#r613873058), we should move emails for kubeadm CI jobs to a dedicate mailing list

> You can create a PR for a new group at https://github.com/kubernetes/k8s.io/tree/main/groups/sig-cluster-lifecycle, though don't do what I did and add yourselves as owners, adding as members is sufficient (going to add a PR to downgrade all of us).
> 
> Tag ameukam who can get the group set up after it's merged.
> 
> You're both in the OWNERS file as SIG leads, so can get yourself set up.

- [x] add new mailing list:
https://github.com/kubernetes/k8s.io/pull/1947
- [ ] Update e2e test config to use the new `sig-cluster-lifecycle-kubeadm-alerts@kubernetes.io` mailing list.
this should be done after https://github.com/kubernetes/kubeadm/pull/2434 merges
https://github.com/kubernetes/kubeadm/pull/2477
https://github.com/kubernetes/test-infra/pull/22206

**Comment by neolit123** [comment]
reopening to track the change in test config.

**Comment by neolit123** [comment]
https://groups.google.com/a/kubernetes.io/g/sig-cluster-lifecycle-kubeadm-alerts
is not active yet it seems. will recheck again in a few days.
