### ISSUE TITLE
Use kubeadmapiv1.SchemeGroupVersion.String() instead of "kubeadm.k8s.io/v1beta3"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2453]
In this PR we are adding kubeadm API v1beta3.
https://github.com/kubernetes/kubernetes/pull/101129

in a number of places in the code base, mostly around unit tests we are hardcoding the string `kubeadm.k8s.io/v1beta3`.
Instead we should have this import:

```
kubeadmapiv1 "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta3"
```

and replace `kubeadm.k8s.io/v1beta3` with `kubeadmapiv1.SchemeGroupVersion.String()`.

this will allow for smaller DIFFs when sending big API update PRs to change the latest API version.

NOTE: this needs https://github.com/kubernetes/kubernetes/pull/101129 to merge first.

**Comment by wangyysde** [comment]
/asign 
I am try to this.
