### ISSUE TITLE
imageTag should exist for everything

### ISSUE THREAD

**Issue by SebTardif** [kubernetes/kubeadm#2458]
I try to match what I have on a DOD approved images repository, and I cannot configure kubeadm enough to make this work.

For example:

apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.20
imageRepository: iron-bank-docker.nexus.boozallencsn.com/ironbank/opensource/kubernetes-1.20

Should work but say:
sudo kubeadm config images pull --config kubeadmConfig.yaml  
version "v1.20" doesn't match patterns for neither semantic version nor labels (stable, latest, ...)
To see the stack trace of this error execute with --v=5 or higher

What I have in my repo (that I don't control) is: docker pull registry1.dso.mil/ironbank/opensource/kubernetes-1.20/kube-apiserver-1.20:v1.20.6

Then if I change to kubernetesVersion: v1.20.0 it execute but doesn't match it.

we have imageTag for etcd but not the others, why don't we generalize flexibility of configuration for everything, everything with own repo, own tag, own version?

**Comment by neolit123** [comment]
Hi. Kubeadm and k8s use semantic versioning. 'v1.20.0' is correct, not
having the trailing '.0' is not compatible.

If you pin the k8s version to 'v1.20.0' in the config then you must upload
images with the same tag in you repository.

Making all images individually configurable is not something easy to
maintain. There was recently a related request for an API change.

/close
/kind support

**Comment by neolit123** [comment]
The correct naming is:

'kube-apiserver:v1.20.6'
