### ISSUE TITLE
add API support for controlling various timeouts

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubeadm#2463]
edit: neolit123

ticket repurposed for a general / broader timeout support.

design draft :
https://docs.google.com/document/d/1q0OLHSD6M0JPjN8PxgvpJX1726omQh_Qd3os4LQqrtI/edit

---------

## What keywords did you search in kubeadm issues before filing this one?

["etcd timeout"](https://github.com/kubernetes/kubeadm/issues?q=is%3Aissue+etcd+timeout+) (5 open, 173 closed)

Similar questions, but not formal asks:

[#1712 (comment)](https://github.com/kubernetes/kubeadm/issues/1712#issuecomment-549893600)
[#2092 (comment by @neolit123)](https://github.com/kubernetes/kubeadm/issues/2092#issuecomment-607994592)

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST
/kind feature
/kind api-change
/area etcd

Detailed motivation is covered in #2457,  but the short version is AWS would like to add support to CAPI for [Bottlerocket](https://github.com/bottlerocket-os/bottlerocket), and we have constraints that prevent us from just running `kubeadm join` without stopping part way along, running OS-specific configuration, and then resuming with `kubeadm join --skip-phases ...`. 

When bringing up etcd on additional control plane nodes, the subphase `control-plane-join/etcd`, kubeadm waits up to [40 seconds](https://github.com/kubernetes/kubernetes/blob/dd6ee9/cmd/kubeadm/app/phases/etcd/local.go#L208) for etcd to be available before exiting. In our case, we expect kubeadm to fail, and want to perform our own configuration when it does. We'd like to make this timeout configurable so that we can exit as soon as configuration and certificates are ready. Other users have asked [to increase this timeout](https://github.com/kubernetes/kubeadm/issues/1712#issuecomment-549893600)

I think a new `joinTimeout` option under `ClusterConfiguration.etcd.local` makes the most sense, but feel free to point me to a better location. (Similar to the existing `ClusterConfiguration.apiServer.timeoutForControlPlane` option)

## Versions

**kubeadm version** (use `kubeadm version`): All

**Environment**:
- **Kubernetes version** (use `kubectl version`): All
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Bottlerocket
- **Kernel** (e.g. `uname -a`):
- **Others**:

cc @bcressey @jaxesn @vignesh-goutham

**Comment by neolit123** [comment]
@micahhausler you've mentioned that the kubelet bootstrap timeout is also something that you'd like to be configurable:
https://github.com/kubernetes/kubeadm/issues/2457#issuecomment-828595025
https://github.com/kubernetes/kubernetes/blob/4f36038c0bc575cd33bc53017ed1e20184efae73/cmd/kubeadm/app/constants/constants.go#L184-L185
is that still true?

> ClusterConfiguration.etcd.local

scoping this to local only seems correct, because this is waiting for local etcd members to join.

`memberJoinTimeout` seems like a better name to me.

one problem here is that this function is based on retries * period:
https://github.com/kubernetes/kubernetes/blob/dd6ee99f62ebd91cf22c03a7f2c2594c1f5807e6/cmd/kubeadm/app/util/etcd/etcd.go#L482
https://github.com/kubernetes/kubernetes/blob/dd6ee9/cmd/kubeadm/app/phases/etcd/local.go#L46-L47

so a single timeout value `joinTimeout` requires internal assumptions and possibly deviating from the exact user specified value.

@micahhausler do you have someone that can take the action item to work on this for v1.22 and kubeadm v1beta3?

cc @fabriziopandini 
are you in favor of a controllable timeout for etcd join and controllable timeout for tls bootstrap for kubelet?

**Comment by micahhausler** [comment]
> you've mentioned that the kubelet bootstrap timeout is also something that you'd like to be configurable 

Yep, I'll open a separate issue for that.

> `memberJoinTimeout` seems like a better name to me

SGTM

> one problem here is that this function is based on retries * period:
https://github.com/kubernetes/kubernetes/blob/dd6ee99f62ebd91cf22c03a7f2c2594c1f5807e6/cmd/kubeadm/app/util/etcd/etcd.go#L482
https://github.com/kubernetes/kubernetes/blob/dd6ee9/cmd/kubeadm/app/phases/etcd/local.go#L46-L47

> so a single timeout field requires internal assumptions and possibly deviating from the exact user specified value.
exposing both retries & period in the API seems too granular.

I agree on not making the API too granular. Can we keep the existing retries/period values as defaults, but increase/decrease the retry count based on the supplied timeout? It also seems like [`getClusterStatus()`](https://github.com/kubernetes/kubernetes/blob/dd6ee99/cmd/kubeadm/app/util/etcd/etcd.go#L441-L479) could benefit from adding `context.Context` that includes the max timeout. 

> @micahhausler do you have someone that can take the action item to work on this for v1.22 and kubeadm v1beta3?

Yes, I'm good to take this one

**Comment by neolit123** [comment]
> I agree on not making the API too granular. Can we keep the existing retries/period values as defaults, but increase/decrease the retry count based on the supplied timeout?

we could drop the max retires approach and just execute getClusterStatus() in a loop delay between calls, counting the retires, until memberJoinTimeout passes or until getClusterStatus() returns success.

>  It also seems like getClusterStatus() could benefit from adding context.Context that includes the max timeout.

etcd.go needs cleanup / refactors., but getClusterStatus() is called in a few places so i think we might want to avoid touching it for the time being and leave the changes to the side of the caller around this API change - in this case WaitForClusterAvailable().

**Comment by neolit123** [comment]
@micahhausler 

we had a discussion with @fabriziopandini on the topic of timeouts in the kubeadm API today.
we concluded that perhaps we should have not added `timeoutForControlPlane` to be under ClusterConfiguration.apiServer.
the problem with that is that this is really a node specific setting (e.g. bound to node hardware) and ClusterConfiguration makes it  cluster wide. so a slower node joining will be bound to a setting that may not be suitable.

instead what we should have "timeouts" sub-structure under InitConfiguration and JoinConfiguration, that holds a number of different timeouts.

so if we are going to make timeout related changes in v1beta3 we should make a more broader change:
- drop ClusterConfiguration.apiServer.timeoutForControlPlane, replace it with something like {Init|JoinConfiguration{.timeouts.apiServerHealthCheck
- add JoinConfiguration.timeouts.kubeletTLSBootstrap
- add JoinConfiguration.timeouts.etcdMemberJoin

naming / field locations are just ideas at this point.

**Comment by wangyysde** [comment]
@micahhausler Are you start working on this? If not, I will to this.

**Comment by micahhausler** [comment]
@wangyysde Feel free to take this one!

**Comment by wangyysde** [comment]
@neolit123 Then, can I try to add timeouts.etcdMemberJoin to JoinConfiguration first?

**Comment by neolit123** [comment]
I think a single PR with multiple commits that covers all the changes is
preferred.

**Comment by wangyysde** [comment]
Hi @neolit123   @fabriziopandini   I have create a PR (kubernetes/kubernetes#103226)  to fix this issue. Could you review it?
Another, I want to make sure with you for somethings.
1. To fix this issue,  many files must be modified ,I found.  For review PR easier， I  want to create a few of PRs to fix this issue. Is it OK?
2. The changes are base on v1beta3 .There are more and more difference between cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go with cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go. Then as if we should add more and more functions into cmd/kubeadm/app/apis/kubeadm/v1beta2/conversion.go. I am not  sure whether it is right.  Can you give me a hand？Thanks.

**Comment by neolit123** [comment]
i think it is more appropriate to have a single PR with multiple commits.
i can have a look next week.

**Comment by wangyysde** [comment]
OK， I try to create  a single PR with multiple commits for this issue.

**Comment by neolit123** [comment]
commented on the PR:
https://github.com/kubernetes/kubernetes/pull/103226#pullrequestreview-698272625

> given code freeze is Thursday next week, i'm not sure how much time i will have to review this again until then. if we can't get it for v1beta3, it has to be scheduled for v1beta4.

**Comment by neolit123** [comment]
something else,

while i enumerated some timeouts that we might want in above.
i think we might need to better discuss what timeouts we want to have for init and join...

for example, we might want to have etcd timeouts and kubelet timeout during init too.
a design doc and some research might be needed, which we can then document in the kubeadm API KEP.

**Comment by wangyysde** [comment]
> given code freeze is Thursday next week, i'm not sure how much time i will have to review this again until then. if we can't get it for v1beta3, it has to be scheduled for v1beta4

Ok. I found there are some errors in the PR. So I think that  it has to be scheduled for v1beta4.
> for example, we might want to have etcd timeouts and kubelet timeout during init too.

In fact, I am agree with you. But I try to add etcd timeout and kubelet timeout to join only as above discussing.
> a design doc and some research might be needed, which we can then document in the kubeadm API KEP.

I want to prepare an API KEP for this. But I have never created API KEP. So maybe I  need some help.

**Comment by neolit123** [comment]
There is no need for a new KEP i'd say. Just a hack.md or a Google doc where we can agree on the design. Once we agree we can summarize the change in the kubeadm API KEP.

**Comment by wangyysde** [comment]
I have prepared a document at here: https://docs.google.com/document/d/1q0OLHSD6M0JPjN8PxgvpJX1726omQh_Qd3os4LQqrtI

**Comment by neolit123** [comment]
@wangyysde i have added some comments in the doc. again, thanks a lot for looking in to this.

a couple of things to note about the design:
- usually it's fine to not include most of the implementation details, like file names, conversion code, renames. sometimes this can change during review, so unless the reviewers ask explicitly about having the detail, it's not needed - e.g. sections "The relations of functions’ call", "How to do" can be omitted.
- we don't know when we are going to start work on v1beta4...so it might not be for 1.23.
for v1beta3 it took a number of releases to accumulate sufficient number of new features. the api-change label shows some of the pending ones for v1beta4 https://github.com/kubernetes/kubeadm/labels/kind%2Fapi-change

my personal preference would be for the kubeadm API work to move slightly faster, but we shall see.

**Comment by neolit123** [comment]
if we are moving the apiserver timeout, a question becomes do we want to move the "discovery" timeout as well.
it is used in code under /discovery:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/discovery/discovery.go#L74-L87

https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#Discovery

**Comment by neolit123** [comment]
also something else we can do is move away from metav1.Duration and use `someTimeoutSeconds` (`*int32` everywhere).
i recall issues where metav1.Duration was not CRD fiendly.

**Comment by wangyysde** [comment]
> if we are moving the apiserver timeout, a question becomes do we want to move the "discovery" timeout as well.
> it is used in code under /discovery:
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/discovery/discovery.go#L74-L87
> 
> https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#Discovery
Ok, I try to move the discovery to under JoinTimeouts




> also something else we can do is move away from metav1.Duration and use `someTimeoutSeconds` (`*int32` everywhere).
> i recall issues where metav1.Duration was not CRD friendly.
> 
> EDIT: actually it was metav1.Time as explained here:
> [kubernetes/kubernetes#86811](https://github.com/kubernetes/kubernetes/issues/86811)

Then, should we create a new type named TimeoutSeconds with *int32?

**Comment by wangyysde** [comment]
> * usually it's fine to not include most of the implementation details, like affect files, conversion code, renames. sometimes this can change during review, .........

Ok, I will delete these section. Thanks. 

> * we don't know when we are going to start work on v1beta4 .......

Ok .

**Comment by neolit123** [comment]
> Then, should we create a new type named TimeoutSeconds with *int32?

Thinking more about this. This is only a problem if the kubeadm api is used
by non-golang clients, because they would need to implement custom parsing
of the go duration format (e.g. 12s). I do not think we will have a use
case for non-go, so we can keep using *Duration.

**Comment by wangyysde** [comment]
@neolit123 @fabriziopandini   I have modified the document at here: https://docs.google.com/document/d/1q0OLHSD6M0JPjN8PxgvpJX1726omQh_Qd3os4LQqrtI.  I am going to prepare a PR following the document if you are agree on.

**Comment by neolit123** [comment]
@wangyysde i am going to have a look at the doc again. Like i've explained above we are probably not going to release v1beta4 in 1.23 which means we cannot accept the PR for this. But if you like to get review on it you can have the PR against your fork of k/k for the time being.

**Comment by fabriziopandini** [comment]
Even if we are not implementing in this cycle, what about if we start the KEP process so things will be ready for the next cycle (or when we rev the next release)?

WRT to the document, I think the API surface needs some refinements in order to provide consistency with existing timeouts in Kubernetes and a cleaner separation of timeouts for components/scope. This will require some nested structs, but IMO it will greatly improve UX and provide a more composable and extensible/future proof solution.

**Comment by neolit123** [comment]
@fabriziopandini 

> Even if we are not implementing in this cycle, what about if we start the KEP process so things will be ready for the next cycle (or when we rev the next release)?

@wangyysde what do you think about working on the KEP without PRs for 1.23?

> WRT to the document, I think the API surface needs some refinements in order to provide consistency with existing timeouts in Kubernetes and a cleaner separation of timeouts for components/scope. This will require some nested structs, but IMO it will greatly improve UX and provide a more composable and extensible/future proof solution.

@fabriziopandini can you provide examples of what you mean so that @wangyysde can better grasp your sub-struct / component ideas.

**Comment by fabriziopandini** [comment]
> @fabriziopandini can you provide examples of what you mean so that @wangyysde can better grasp your sub-struct / component ideas.

I have provided comments on the attached document; they got resolved by @wangyysde, but in the proposal it seems that there is still a flat struct when all the timeouts for different components/no consistency with the rest of Kubernetes. So from my point of view this is still to be addressed; I will loop again on it the KEP eventually.

**Comment by wangyysde** [comment]
> @neolit123  what do you think about working on the KEP without PRs for 1.23?

Should  I try to prepare a KEP for this first?

> @fabriziopandini I have provided comments on the attached document; they got resolved by @wangyysde, but in the proposal it seems that there is still a flat struct when all the timeouts for different components/no consistency with the rest of Kubernetes. So from my point of view this is still to be addressed; I will loop again on it the KEP eventually.

I have read your comments on the attached document. Thanks. Recently ,I am too busy to  modify the file in time. Can I change the structure from flat to nested in the KEP( if I should prepare a KEP) without the attached document modified?

**Comment by neolit123** [comment]
SGTM @wangyysde 

>  Recently ,I am too busy to modify the file in time. 

take your time as this is not urgent for 1.23.

**Comment by chenk008** [comment]
Can I work on it?

**Comment by neolit123** [comment]
@chenk008 sure you can try asking @wangyysde what progress he made.
see linked docs and prs. also note that we do not add new fields in old apis, do this must be added in the future beta4. we could add the boiler plate now and just expose the fields in beta4.

**Comment by chendave** [comment]
I am trying to figure out who can own this for v1beta4, note that v1beta4 has been planned for .29 release cycle. this is does something we can have for v1beta4, and there is a WIP pr for this: https://github.com/kubernetes/kubernetes/pull/103226

I haven't seen any major problem for this, but we can leave some details for review.

@chenk008 @wangyysde do you still want to work on it, if yes, pls assign it to yourself. Otherwise, we will find someone else to help (myself is a candidate as well).

**Comment by neolit123** [comment]
@chendave i see you sent a new PR:
https://github.com/kubernetes/kubernetes/pull/119015

having some sort of a PR for experiments is OK, but we are missing status update on the latest proposal in doc form.
https://github.com/kubernetes/kubeadm/issues/2463#issuecomment-905262531

there were some discussions around nested vs flat timeouts, but i have forgotten the details as this was from 2 years ago...
in any case, we should not invest in PRs until we know what we are doing.

this is arguably the biggest change for https://github.com/kubernetes/kubeadm/issues/2890 or API-next and it needs an owner.

**Comment by chendave** [comment]
> in any case, we should not invest in PRs until we know what we are doing.

I will refresh the doc (properly, in the coming week) so that we can continue the discussion there.

**Comment by chendave** [comment]
Refreshed the doc and shared with "kubernetes-sig-cluster-lifecycle@googlegroups.com", all the member of the sig should able to access the doc. 

https://docs.google.com/document/d/1VNGpGWb-vqblfZQLp9DY1lx777rwhwIFAjDFQNIwWh0



@fabriziopandini I added your idea about the nested structure of each components, is that what you meant?

@neolit123 @pacoxu @SataQiu pls review and comment, thanks!

Hope we can finalize the approach before the opening of the 1.29 release cycle.

**Comment by neolit123** [comment]
what remains here is support for upgrade timeouts.
they must be added once we have UpgradeConfiguration in v1beta4.

**Comment by neolit123** [comment]
this was done as part of v1beta4.
separate requests can be done in new issues.
https://github.com/kubernetes/kubeadm/issues/2890
