### ISSUE TITLE
kubeadm should support configurable addons

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubeadm#247]
This is a feature request collected from users.

Now the build-in addons like kubedns is using a hard coded [yaml template](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/manifests.go), makes is impossible to configure it easily (correct me if I'm wrong).

We should consider make it configurable somehow. The most frequently requested feature is modifying resource limit of kubedns pod, which is common if user want to serve a big cluster (user have to re-build kubeadm now).

We don't have to have `kubadm update-addon` at first stage, maybe just use a configure file template and `kubadm reset & init`.

**Comment by resouer** [comment]
cc @luxas any thoughts?

**Comment by luxas** [comment]
@resouer This will be kind of incorporated in #156 

ping @justinsb how's the addon management proposal proceeding?

**Comment by luxas** [comment]
@resouer This is out of scope for `kubeadm init`, but you will be able to do it with `kubeadm phase` by executing all phases but `kube-dns` and providing your own manifest instead.

In the meantime, we're not looking into a flag or something to `kubeadm init` to customize this.
Instead, it's expected that users do `kubeadm init && kubectl apply -f my-new-kubedns-manifest.yaml` if they need to.

**Comment by resouer** [comment]
`kubeadm init && kubectl apply -f my-new-kubedns-manifest.yaml` is exactly what I am doing, thanks.

**Comment by tamalsaha** [comment]
@luxas , where can I learn more about kubedam phaes?

**Comment by luxas** [comment]
@tamalsaha Yes. I don't have any user-facing docs for this yet -- sorry, but the state in v1.7 was captured here (will be updated): https://github.com/kubernetes/kubeadm/blob/master/docs/design/design.md

Some rough notes are in https://github.com/kubernetes/kubeadm/issues/267 as well.
I hope to get to docs for this in some weeks.

In the meantime, check out the kubeadm adoption WG: https://docs.google.com/document/d/1KdXsLYiJYJdiRbtgZsx6qbHF4g_K-gAScB9Zs4avgzg/edit#heading=h.aly6m9xjbivl
You can also try out `kubeadm alpha phase` built from master in the meantime

**Comment by luxas** [comment]
And yes -- coming in v1.8

**Comment by tamalsaha** [comment]
Thanks @luxas !
