### ISSUE TITLE
Cluster CA validation only works when the first caCertHashes is valid

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/kubeadm#2471]
## Versions

**kubeadm version** (use `kubeadm version`): v1.21.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.21.0
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): Ubuntu 20
- **Kernel** (e.g. `uname -a`): `5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?

kubeadm join failed with the following log: 
```
[2021-05-08 12:20:58] I0508 12:20:58.282533    2583 join.go:465] [preflight] Discovering cluster-info
[2021-05-08 12:20:58] I0508 12:20:58.282556    2583 token.go:78] [discovery] Created cluster-info discovery client, requesting info from "53.6.51.164:6443"
[2021-05-08 12:20:58] error execution phase preflight: couldn't validate the identity of the API Server: cluster CA found in cluster-info ConfigMap is invalid: none of the public keys "sha256:11bdf3cc08ea132b33e1921b2d74c4bfc516802b4800c89e595ae04b3d1cf3d7" are pinned
[2021-05-08 12:20:58] To see the stack trace of this error execute with --v=5 or higher
```

Corresponding `JoinConfiguration`:
```bash
discovery:
  bootstrapToken:
    caCertHashes:
    - sha256:8b47ff2fe5f85aed300e2ae9bffb3d2e26652eb04e8d9d660de01e5342ad7728
    - sha256:11bdf3cc08ea132b33e1921b2d74c4bfc516802b4800c89e595ae04b3d1cf3d7
```

## What you expected to happen?

Should have worked

## How to reproduce it (as minimally and precisely as possible)?

Add multiple `discovery.bootstrapToken.caCertHashes` where the first one is not the correct one.

## Anything else we need to know?

If I got it correctly, the idea is that multiple `caCertHashes` can be specified and when one of those is correct the validation should be successful. Imho there's a bug in the code.

cluster CA validation is triggered here:
https://github.com/kubernetes/kubernetes/blob/429b7e227209ee557881b3d276b29090f98137a3/cmd/kubeadm/app/discovery/token/token.go#L107-L111

hashes are then checked here:
https://github.com/kubernetes/kubernetes/blob/429b7e227209ee557881b3d276b29090f98137a3/cmd/kubeadm/app/discovery/token/token.go#L186-L189

I'm seeing the error produced in this line:
https://github.com/kubernetes/kubernetes/blob/429b7e227209ee557881b3d276b29090f98137a3/cmd/kubeadm/app/util/pubkeypin/pubkeypin.go#L81

The interesting thing is that the error message only prints one hash even though there should be two.

In my opinion the bug is that not all our hashes are added to the set. We handover all hashes to `Allow`, but it returns after the first one was added in l.62.

https://github.com/kubernetes/kubernetes/blob/429b7e227209ee557881b3d276b29090f98137a3/cmd/kubeadm/app/util/pubkeypin/pubkeypin.go#L51-L68

**Comment by neolit123** [comment]
> In my opinion the bug is that not all our hashes are added to the set. We handover all hashes to Allow, but it returns after the first one was added in l.62.

that does look like a bug, thanks for the report.

> If I got it correctly, the idea is that multiple caCertHashes can be specified and when one of those is correct the validation should be successful. Imho there's a bug in the code.

if the cluster-info CM contains a set of CAs - A, and the joining nodes provide a set of CA hashes - B.
the logic is `B ⊇ A` or B must match A, or contain more elements.

PRs welcome.

/help
/priority backlog
