### ISSUE TITLE
HAproxy binding to port 6443

### ISSUE THREAD

**Issue by squigley** [kubernetes/kubeadm#2472]
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:30:03Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Supermicro X8DTN 
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
- **Kernel** (e.g. `uname -a`): Linux smic-2 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?

Tried to initialise a cluster/master node, with software HA, based on docuementation: https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md#options-for-software-load-balancing

Always times out when trying to use static pods. curl gives "curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to cluster-endpoint:6443"

I moved from trying to use static pods to running HAproxy and keepalived on the OS, then I had issues with port 6443 being in use, by HAproxy

## What you expected to happen?

I expected the cluster to initialise.

i think the issue is that the config file example contains:

```
frontend apiserver
    bind *:${APISERVER_DEST_PORT}

```
and if 6443 is configured as the DEST PORT, then it will tie it up so that the API server can't use it/start.

Once I reconfigured it to bind to port 443 instead of 6443, it would work (though with HAproxy/keepalived running on the OS still, not as static pods).

## How to reproduce it (as minimally and precisely as possible)?

Create the files as described in the documentation, /etc/keepalived/keepalived.conf /etc/haproxy/haproxy.cfg /etc/kubernetes/manifests/keepalived.yaml /etc/kubernetes/manifests/haproxy.yaml

**Comment by neolit123** [comment]
the documentation is clear that the DEST port and SRC port should not be the same:
> Note that, if ${APISERVER_DEST_PORT} has been configured to a value different from 6443 in the configuration above, kubeadm init needs to be told to use that port for the API Server. Assuming that in a new cluster port 8443 is used for the load-balanced API Server and a virtual IP with the DNS name vip.mycluster.local, an argument --control-plane-endpoint needs to be passed to ...

> ${APISERVER_DEST_PORT} the port through which Kubernetes will talk to the API Server.
> ${APISERVER_SRC_PORT} the port used by the API Server instances

6443 is reserved for SRC.

/priority awaiting-more-evidence
/kind documentation
cc @mbert
