### ISSUE TITLE
ha-considerations.md: keepalived image missing curl

### ISSUE THREAD

**Issue by jdefaver** [kubernetes/kubeadm#2478]
## What happened?

I used the documentation in `ha-considerations.md` to deploy kubernetes with haproxy and keepalived on static pods. I determined keepalived was not working as expected by looking at `/var/log/messages` on the host (`journal: /etc/keepalived/check_apiserver.sh exited with status 1`).

By connecting to the keepalived pod, I realized curl was missing:

```bash
$ kubectl exec -it  -n kube-system keepalived-kubernetes-control-2 -- /bin/bash
$ cd /etc/keepalived/
$ ./check_apiserver.sh 
./check_apiserver.sh: line 11: curl: not found
*** Error GET https://localhost:443/
 ```

## What you expected to happen?

Keepalived check script returning `0` when the endpoint is reachable. 

## How to reproduce it (as minimally and precisely as possible)?

Deploy as stated in the documentation.

**Comment by neolit123** [comment]
is this by using `osixia/keepalived:1.3.5-1`?

i think we just need a newer image tag:
https://github.com/osixia/docker-keepalived/issues/29

try `osixia/keepalived:2.0.20`

/kind documentation
/priority backlog
/help
