### ISSUE TITLE
ERROR NumCPU

### ISSUE THREAD

**Issue by 00void00** [kubernetes/kubeadm#2479]
## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
root@Manager:~# kubeadm init --apiserver-advertise-address=172.31.34.71 --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=NumCPU
[init] Using Kubernetes version: v1.21.1
[preflight] Running pre-flight checks
        [WARNING NumCPU]: the number of available CPUs 1 is less than the required 2
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Mem]: the system RAM (978 MB) is less than the minimum 1700 MB
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
root@Manager:~#

## What you expected to happen?
Since the ignore preflight error flag was passed, it should have ignored NumCPU but did otherwise

**Comment by BenTheElder** [comment]
You ignored NumCPU which only became a warning then but:
> [ERROR Mem]: the system RAM (978 MB) is less than the minimum 1700 MB

Mem is a different error and isn't being ignored. You need to `--ignore-preflight-errors=NumCPU,Mem` to ignore both.
You can also ignore all of them with `--ignore-preflight-errors=all` see: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
