### ISSUE TITLE
kinder: remove kube-dns support

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2484]
we removed kube-dns support in kubeadm 1.21, but we forgot to cleanup kinder.
we haven't been testing kube-dns in e2e tests, so it is safe to remove it completely at this point.
all kubeadm e2e jobs use coredns.

the functions in this file and the file can be removed:
kinder/pkg/kubeadm/kubednspatch.go
possibly other places too?

**Comment by CaoDonghui123** [comment]
https://github.com/kubernetes/kubeadm/blob/8b54a2f3f88295bfe54d5533dc7e18fcbaeefa0c/kinder/pkg/cluster/manager/actions/kubeadm-config.go#L229-L236

here need removed as well
