### ISSUE TITLE
node "worker-node-105" not found

### ISSUE THREAD

**Issue by saviovettoor** [kubernetes/kubeadm#2487]
Nodes going to `Not Ready` state.

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.19.9 (both Client and Server Version)
- **Cloud provider or hardware configuration**:  32Mem/16RAM/500HDD
- **OS** (e.g. from /etc/os-release): CentOS 7.8
- **Kernel** (e.g. `uname -a`): 4.20.11-1.el7.elrepo.x86_64
- **Others**: containerd://1.3.9

## What happened?
The cluster was set up using kubespray the cluster was running fine for 2 days, then the worker node went to `NotReady` 
stage. When checked kubelet logs following was the error
```
May 24 03:51:12 worker-node-105 kubelet[30687]: E0524 03:51:12.918140   30687 kubelet.go:2214] node "worker-node-105" not found
May 24 03:51:13 worker-node-105 kubelet[30687]: E0524 03:51:13.018587   30687 kubelet.go:2214] node "worker-node-105" not found
May 24 03:51:13 worker-node-105 kubelet[30687]: E0524 03:51:13.118868   30687 kubelet.go:2214] node "worker-node-105" not found
May 24 03:51:13 worker-node-105 kubelet[30687]: E0524 03:51:13.219177   30687 kubelet.go:2214] node "worker-node-105" not found
```

**Comment by fabriziopandini** [comment]
@saviovettoor I'm not sure this is the right repo for this issue; might be moving this to the kubespray repo (if you think this is related to the node provisioning) or the Kubernetes repo (if you think this is more related to kubelet) could help in getting in contact with the right people

**Comment by neolit123** [comment]
If the failure happened 2 days after cluster creation then this is not a kubeadm problem. Kubeadm works in one shot operations such as create, join and upgrade. Perhaps there is more information in the kubelet logs 

You should try asking at the support forums or #kubeadm on k8s slack.

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
