### ISSUE TITLE
RFE: Update Dockerfile to support atomic install 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#249]
The initial instructions call out setting up a private repo whose packages can only be created by a few.  I'd like to update the Dockerfile(s) that we create to have enough meta-data to support the atomic install of the kubernetes that we create for EL/fedora variants.  

This will allow anyone to create a container that can install the containerize kubelet.service as the 1st part of the installation instructions.  I believe the ubuntu guys are doing something similar with a snap package.  

Also those packages are non-standard and conflict with upstreams. 

/cc @dgoodwin @jbeda @mikedanese @luxas

**Comment by luxas** [comment]
@timothysc Something like https://github.com/luxas/kubeadm-installer?

**Comment by timothysc** [comment]
@luxas no.  I believe @jasonbrooks has something.

**Comment by jamiehannaford** [comment]
@timothysc Just so I'm clear, what Dockerfile are you referring to? My understanding was that we have an issue for containerized installs (https://github.com/kubernetes/kubeadm/issues/17) but nothing exists yet.

**Comment by luxas** [comment]
@timothysc this doesn't seem to be a kubeadm-native issue, but more a higher-level integration issue for a third-party packaging provider. Reopen if I'm wrong.
