### ISSUE TITLE
kubeadm join phase fails to get configmaps kubeadm-config

### ISSUE THREAD

**Issue by prakashmirji** [kubernetes/kubeadm#2491]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions
v1.20.2

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

K8s version
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
OS : centos 7.9

Kernal: 3.10.0-1160.25.1.el7.x86_64

## What happened?
I was trying to download the certs and configs from the apiserver using kubeadm join phase command `kubeadm join phase control-plane-prepare all --config=/opt/kubeadm-conf.yaml --v=10`. It failed with error saying unable to get the configmaps kubeadm-config and log also says json parse error.  Will attach the logs, configmap and kubeadm config file

## What you expected to happen?
kubeadm join phase command should have downloaded certs and configs on the node from where the command is executed. I mean the certs should have been created in default directory /etc/kubernetes/pki

## How to reproduce it (as minimally and precisely as possible)?
running this command from a node ( can be new join that you want to bootstrap it )
kubeadm join phase control-plane-prepare all --config=/opt/kubeadm-conf.yaml --v=10

## Anything else we need to know?
See the attached files
[kubeadm-join-phase-cmd.log](https://github.com/kubernetes/kubeadm/files/6552555/kubeadm-join-phase-cmd.log)
[kubadm-config-cli-arg-file.txt](https://github.com/kubernetes/kubeadm/files/6552571/kubadm-config-cli-arg-file.txt)
[kubeadm-configmap.txt](https://github.com/kubernetes/kubeadm/files/6552572/kubeadm-configmap.txt)

**Comment by prakashmirji** [comment]
I change the controlPlane  to ControlPlane. That error is gone I think. Now when I run the same kubeadm join phase, i don't get any results. here is the console output. 
```
kubeadm join phase control-plane-prepare all --config=/root/kubeadm-config.yaml --v=10
```

I0527 06:29:30.109220   26784 join.go:395] [preflight] found NodeName empty; using OS hostname as NodeName
I0527 06:29:30.109295   26784 joinconfiguration.go:74] loading configuration from "/root/kubeadm-config.yaml"
I0527 06:29:30.111369   26784 controlplaneprepare.go:211] [download-certs] Skipping certs download

**Comment by prakashmirji** [comment]
It appears that the lower case issue is causing too many problems. I changed certificateKey to CertificateKey, now I am getting next validation error like below. Does any one have working kubeadm config file for join phase

I0527 06:59:37.755741   29996 join.go:395] [preflight] found NodeName empty; using OS hostname as NodeName
I0527 06:59:37.755835   29996 joinconfiguration.go:74] loading configuration from "/root/kubeadm-config.yaml"
I0527 06:59:37.757075   29996 initconfiguration.go:104] detected and using CRI socket: /var/run/dockershim.sock
discovery: Invalid value: "": bootstrapToken or file must be set

my current kubeadm config looks like this
```
apiVersion: kubeadm.k8s.io/v1beta2
CaCertPath: /etc/kubernetes/pki/ca.crt
Discovery:
  bootstrapToken:
    apiServerEndpoint: xx.0.14.116:6443
    token: aweqql.x99ikrkwd8dxn1tg
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: aweqql.x99ikrkwd8dxn1tg
kind: JoinConfiguration
NodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: xx.0.14.117
  taints: null
ControlPlane:
  localAPIEndpoint:
    bindPort: 6443
  CertificateKey: 126c03091fce7419f9fda2103f2cc83ed0c95df5a542e87132936f9a26bf2ef5
```

**Comment by neolit123** [comment]
more context, we discussed this on slack
https://kubernetes.slack.com/archives/C2P1JHS2E/p1622103823032600

```
ControlPlane:
  localAPIEndpoint:
    bindPort: 6443
  CertificateKey: 126c03091fce7419f9fda2103f2cc83ed0c95df5a542e87132936f9a26bf2ef5
```

these fields should be with camelCase always as  defined in the JSON tags:
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2


> I0527 00:54:17.559390   23281 request.go:1107] Response Body: Client sent an HTTP request to an HTTPS server.
I0527 00:54:17.559466   23281 request.go:1311] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: invalid character 'C' looking for beginning of value
I0527 00:54:17.820717   23281 round_trippers.go:425] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.20.2 (linux/amd64) kubernetes/faecb19" 'http://xx.0.14.116:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s'
I0527 00:54:17.821868   23281 round_trippers.go:445] GET http://xx.0.14.116:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s 400 Bad Request in 1 milliseconds
I0527 00:54:17.821921   23281 round_trippers.go:451] Response Headers:
I0527 00:54:17.821971   23281 request.go:1107] Response Body: Client sent an HTTP request to an HTTPS server.
I0527 00:54:17.822021   23281 request.go:1311] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: invalid character 'C' looking for beginning of value
the server rejected our request for an unknown reason (get configmaps kubeadm-config)
failed to get config map
k8s.io/kubernetes/cmd/kubeadm/app/util/config.getInitConfigurationFromCluster
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/config/cluster.go:87
k8s.io/kubernetes/cmd/kubeadm/app/util/config.FetchInitConfigurationFromCluster
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/config/cluster.go:69
k8s.io/kubernetes/cmd/kubeadm/app/cmd.fetchInitConfiguration
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/joi

the error is not from kubeadm, but rather from the k8s go client.
something else is happening here, but i don't understand what.

in any case this does not seem like a kubeadm bug, as what kubeadm is doing is just getting the config map:
https://github.com/kubernetes/kubernetes/blob/5d96d978b7306dd429cf8f780fff6d00aeeb3e09/cmd/kubeadm/app/util/apiclient/idempotency.go#L344

the error indicates malformed HTTP request. you can log a kubernetes/kubernetes issue about this if you want.
or don't use the kubeadm cert copy functionality.

we also discussed that kubeadm maintainers do not encourage breaking the kubeadm commands in all their phases.
according to @prakashmirji the use case here is to run the control-plane as systemd components, which is not supported.

/kind support
/close
