### ISSUE TITLE
Kube-Proxy certificate

### ISSUE THREAD

**Issue by ws-prive** [kubernetes/kubeadm#2493]
Hello,

Is Kube-Proxy using a client certificate in a K8s cluster setup by kubeadm?

If so, which certificate is it and where is it located?

Thanks!

**Comment by neolit123** [comment]
please use #kubeadm on k8s slack or these links for support questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

the kube-proxy in kubeadm is deployed as a DaemonSet.
in each Pod in the DS, kube-proxy is setup to have a kubeconfig file with a service account token file to communicate to the api server:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L48

/kind support
/close
