### ISSUE TITLE
kubeadm init creates mysterious kubelet authentication problem, causing "Error writing Crisocket information for the control-plane node"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubeadm#2500]
## What keywords did you search in kubeadm issues before filing this one?
Error writing Crisocket information for the control-plane node

I found other issues with the same symptom, but different cause.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
`kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:17:27Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`):
    Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: VirtualBox VM with 4 CPUs, 4 GB of memory
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.1 LTS
- **Kernel** (e.g. `uname -a`): `Linux ubu20 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?
`kubeadm init` crashed, reporting a timeout waiting for completion of an update to the Node.  Upon investigation, I found that there is no Node object.  The kubelet never succeeds in creating its Node object, because of persistent authentication failures.  The kube-apiserver complains that the client cert is not signed by the right CA.  But, as far as I can tell, it _is_.

I pasted the typescript at https://pastebin.com/9sVhfbcZ

The contents of kubeadm-init.config are:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    v: "8"
```

I hacked up the kubelet logging like this:
```
root@ubu20:~# cat /etc/default/kubelet 
KUBELET_EXTRA_ARGS=-v=8
```

Following is an example complaint from the kube-apiserver log; note that the AKID does not match any other ID seen here.
```
E0602 04:34:26.982211       1 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=158795460643256169608576578930779176110, SKID=, AKID=15:95:8B:71:D0:6A:03:7E:C8:F1:24:D1:3B:4D:EE:F8:F1:B1:70:16 failed: x509: certificate signed by unknown authority]"
I0602 04:34:26.982293       1 httplog.go:89] "HTTP" verb="POST" URI="/api/v1/nodes" latency="174.746µs" userAgent="kubelet/v1.21.1 (linux/amd64) kubernetes/5e58841" srcIP="10.0.2.15:53750" resp=401
```

Here is an excerpt from the corresponding client side log messages from the kubelet:
```
Jun 02 04:34:26 ubu20 kubelet[2145]: I0602 04:34:26.981843    2145 round_trippers.go:432] POST https://10.0.2.15:6443/api/v1/nodes
Jun 02 04:34:26 ubu20 kubelet[2145]: I0602 04:34:26.981850    2145 round_trippers.go:438] Request Headers:
Jun 02 04:34:26 ubu20 kubelet[2145]: I0602 04:34:26.981855    2145 round_trippers.go:442]     Accept: application/vnd.kubernetes.protobuf,application/json
Jun 02 04:34:26 ubu20 kubelet[2145]: I0602 04:34:26.981860    2145 round_trippers.go:442]     Content-Type: application/vnd.kubernetes.protobuf
Jun 02 04:34:26 ubu20 kubelet[2145]: I0602 04:34:26.981865    2145 round_trippers.go:442]     User-Agent: kubelet/v1.21.1 (linux/amd64) kubernetes/5e58841
Jun 02 04:34:26 ubu20 kubelet[2145]: I0602 04:34:26.982653    2145 round_trippers.go:457] Response Status: 401 Unauthorized in 0 milliseconds
```

Here are the relevant processes:
```
root@ubu20:~# ps axlw | grep kubelet
4     0    2145       1  20   0 1930700 98212 wait_w Ssl ?          0:06 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.4.1 -v=8
4     0    3026    2955  20   0 1101920 342056 futex_ Ssl ?         0:21 kube-apiserver --advertise-address=10.0.2.15 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-account-signing-key-file=/etc/kubernetes/pki/sa.key --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key --v=8
```

Both the certificate-authority-data in kubelet.conf and /etc/kubernetes/pki/ca.crt hold a cert that says
```
        Serial Number: 0 (0x0)
        Subject: CN = kubernetes
            X509v3 Subject Key Identifier: 
                D9:E6:DD:99:D3:4B:9F:5F:29:29:F3:42:75:6E:21:E9:09:FA:92:4A
```

In kubelet.conf the client cert says
```
        Serial Number: 8439385665705901668 (0x751eb88c96ec7e64)
        Subject: O = system:nodes, CN = system:node:ubu20
            X509v3 Authority Key Identifier: 
                keyid:D9:E6:DD:99:D3:4B:9F:5F:29:29:F3:42:75:6E:21:E9:09:FA:92:4A
```

and there is no bootstrap-kubelet.conf anymore.

Here is an excerpt from `lsof -nP` showing the expected TCP connection:
```
kubelet   2145 2347 kubelet               root   34u     IPv4              34275       0t0        TCP 10.0.2.15:53750->10.0.2.15:6443 (ESTABLISHED)
```

The full `lsof -nP` output is at https://drive.google.com/file/d/1Av6UDOJzFPNESy1rABbBnCrbf-rSMJPb

The output of `journalctl -a | grep kubelet` is at https://drive.google.com/file/d/1DlgPnkLQq5uzKPHY9igJtYvRypyfFvBA

The kube-apiserver log is at https://drive.google.com/file/d/1sZ3Zp4FfVV-AkUvVve6VLU8-rYne7M_F

## What you expected to happen?
I expected `kubeadm init` to complete successfully.

## How to reproduce it (as minimally and precisely as possible)?
What I outlined above is pretty minimal.

**Comment by neolit123** [comment]
> kubeadm init crashed,

i assume not crashed, but just exiting with an error saying the kubelet is not healthy?

> kubeadm init crashed, reporting a timeout waiting for completion of an update to the Node. Upon investigation, I found that there is no Node object. The kubelet never succeeds in creating its Node object, because of persistent authentication failures. The kube-apiserver complains that the client cert is not signed by the right CA. But, as far as I can tell, it is.

are you just running?
```
kubeadm init --config=kubeadm-init.config
```

- are you feeding custom certificates to kubeadm?
- is this happening after a `kubeadm reset` on the node?
- is only 1.21.1 affected?

but if that is vanilla kubeadm, in theory that is not a kubeadm issue and can happen in any TLS bootstrap scenario.

>> How to reproduce it (as minimally and precisely as possible)?
> What I outlined above is pretty minimal.

this is not reproducible in our CI or in my testing

**Comment by neolit123** [comment]
in the end of the kubelet logs there is:

> Jun 02 04:34:36 ubu20 kubelet[2145]: I0602 04:34:36.493737    2145 apiserver.go:50] "node sync has not completed yet"

this means that the kubelet informer that fetches the list of nodes from the kube-apiserver never succeeds. it uses the client constructed with data from kubelet.conf.

> Jun 02 04:34:37 ubu20 kubelet[2145]: I0602 04:34:37.466152    2145 csi_plugin.go:1024] Failed to contact API server when waiting for CSINode publishing: Unauthorized

this means the kubelet cannot access the csinode API resources

confirmed by logs from the apiserver:
> E0602 04:35:13.466402       1 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=158795460643256169608576578930779176110, SKID=, AKID=15:95:8B:71:D0:6A:03:7E:C8:F1:24:D1:3B:4D:EE:F8:F1:B1:70:16 failed: x509: certificate signed by unknown authority]"
I0602 04:35:13.466541       1 httplog.go:89] "HTTP" verb="GET" URI="/apis/storage.k8s.io/v1/csinodes/ubu20" latency="257.048µs" userAgent="kubelet/v1.21.1 (linux/amd64) kubernetes/5e58841" srcIP="10.0.2.15:53750" resp=401

did you modify this kubelet.conf in any way?

what is the full output of `kubeadm init .... -v=5`?

**Comment by MikeSpreitzer** [comment]
In the "What Happened" section I posted a link to pastebin where you can read the full typescript: command line and all the output.  No, there was no `kubeadm reset` before that.  IIRC there was one preceding `kubeadm init` that failed at the check for swapping.  Looking at the output of that, I got the idea that only checking had been done.  So I turned swapping off and then proceeded with what is shown at pastebin.

**Comment by MikeSpreitzer** [comment]
I just reproduced on a fresh clone without a false start sans `swapoff`.
Also, this is a clone of an image that had run k/k `hack/local-up-cluster.sh`.  Does that leave some relevant state?  Where?

**Comment by MikeSpreitzer** [comment]
So I started over from a more basic VM image, one that had never run `hack/local-up-cluster.sh`.  Still I get the same problem.

Perhaps I should say a little bit more about VMs and images.  I have a tree of VMs (linked VM clones), each edge being some particular specialization.  In the latest trial I made a VM named `ubu20-kubeadm 1.21.1-00`, and completed the instructions in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ , getting me to the point where the instructions say "The kubelet is now restarting every few seconds, as it waits in a crashloop for kubeadm to tell it what to do".  Then I did `sudo shutdown -h now` in that VM.  After it was shutdown, I made a clone named `ubu20-kubeadm 1.21.1-00 init1`, started it, logged in as root, did `swapoff -a` and `kubeadm init --v=5`.  That led to the same symptom, `kubeadm init` crashing with

```
...
I0604 04:51:01.775508    1170 patchnode.go:30] [patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "ubu20" as an annotation
[kubelet-check] Initial timeout of 40s passed.
timed out waiting for the condition
Error writing Crisocket information for the control-plane node
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runUploadKubeletConfig
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/uploadconfig.go:129
...
```

and the kube-apiserver logging authentication failures due to wrong CA having signed the kubelet's cert.

**Comment by MikeSpreitzer** [comment]
Looking more carefully, I found that I had used my root VM to do a docker-based build of k/k, and that left some stuff around.  Most suspiciously, `/var/lib/kubelet/pki`.  So in the root VM I `rm -rf /var/lib/kublet`.  Then I made a clone named `ubu20-pre-kubeadm2` and followed the instructions at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ , stopping just _before_ `sudo apt-get install -y kubelet kubeadm kubectl`.  Then I shutdown this VM, made a clone named `ubu20-kubeadm2-1.21.1-00-init1`, started it, logged in as root, did the install, mark, swapoff, and `kubeadm init`.  This time it completed sucessfully!  So the problem is either junk in /var/lib/kubelet or the shutdown between install and init.

**Comment by MikeSpreitzer** [comment]
So I made a new clone of `ubu20-pre-kubeadm2`, named `ubu20-kubeadm2-1.12.1-00`, and completed the install instructions up through `sudo apt-mark hold kubelet kubeadm kubectl` "The kubelet is now restarting every few seconds, as it waits in a crashloop for kubeadm to tell it what to do".  Shutdown that VM, made a clone of that named `ubu20-kubeadm2-1.21.1-00-init1`, started it, logged in as root, swapoff, `kubeadm init --v=5` --- and it completed successfully!  So the problem is that junk that was in /var/lib/kubelet.

**Comment by MikeSpreitzer** [comment]
I found the problematic junk.  Going back to `ubu20-kubeadm 1.21.1-00 init1`, I looked in the kube-apiserver's log and saw lots of entries like
```
E0604 04:51:00.425315       1 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=151054237388542069782146036084566946170, SKID=, AKID=C6:80:DD:4D:4F:6B:C5:6E:42:B4:19:7B:44:44:F9:17:BF:D4:50:9D failed: x509: certificate signed by unknown authority]"
```

Looking around in /var/lib/kubelet, I found this:
```
root@ubu20:/var/lib/kubelet/pki# openssl x509 -noout -text -in kubelet-client-2021-02-01-22-37-08.pem 
Certificate:
...
        Serial Number:
            71:a3:fc:e7:19:c8:af:4b:f2:4d:45:fd:a3:98:71:7a
...
        Subject: O = system:nodes, CN = system:node:127.0.0.1
...

            X509v3 Authority Key Identifier: 
                keyid:C6:80:DD:4D:4F:6B:C5:6E:42:B4:19:7B:44:44:F9:17:BF:D4:50:9D
...
```

And 71a3fce719c8af4bf24d45fda398717a is the hex for 151054237388542069782146036084566946170.

There is also a `kubelet.crt`, but it has a different serial number and authority key ID.

**Comment by neolit123** [comment]
Understood. Before 'init' we asume users have a clean host. If not, 'reset'
would clean this for them.
