### ISSUE TITLE
document some steps about kubelet client certs recovery

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2502]
document some steps about kubelet client certs recovery

kubeadm does not manage the kubelet.conf and symlinked rotable client certificates for the kubelet to interact with the apiserver.
by default kubeadm deploys the kubelet with auto client cert rotation, but in some cases user setups can end up with with an expired cert, rendering this node as "not ready".

we can add some steps on how users can escape this scenario here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

here we have some info on what commands can be used:
https://github.com/kubernetes/kubernetes/issues/102556
https://github.com/kubernetes/kubeadm/issues/581#issuecomment-853808359

**Comment by antoinep92** [comment]
@neolit123 not sure if I'm qualified enough, but since you tagged help wanted, maybe I can draft a doc PR next week and you or somebody can review ?

**Comment by neolit123** [comment]
sure, go ahead @antoinep92
