### ISSUE TITLE
Join from second master makes apiserver in first master, fails & exits

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubeadm#2507]
What keywords did you search in kubeadm issues before filing this one?
kubeadm join error-spew from logs

## BUG REPORT
Steps:
1) Install kubelet, kubectl & kubeadm which by default installs 1.21.1
2) Run kubeadm init with control-end-point with VIP, advertise address as this-host-ip
```
    kubeadm init \
        --control-plane-endpoint "${SLB_VIP}:6443" \
        --apiserver-advertise-address "${SELF_IP}" \
        --upload-certs \
        --skip-phases=addon/kube-proxy \
        --skip-phases=addon/coredns \
        -v=5 || ret=$?

```
3) Watch kubectl get nodes to see first master running fine.
```
NAME              STATUS   ROLES                  AGE     VERSION
co4aeap000110fb   Ready    control-plane,master   2m45s   v1.21.1

```
4) Install same in second master, copy admin.conf & /etc/kubernetes/pki/* files from first master and run join as below
`kubeadm join --discovery-file ${temp_admin_conf} --control-plane -v=5 || ret=$?
`

5) Note, the second master appear as "not ready" in nodes list, briefly
```
NAME              STATUS     ROLES                  AGE     VERSION
co4aeap000110fb   Ready      control-plane,master   3m10s   v1.21.1
co4aeap000110fc   NotReady   <none>                 0s      v1.21.1
Thu Jun 10 21:53:27 UTC 2021
NAME              STATUS     ROLES                  AGE     VERSION
co4aeap000110fb   Ready      control-plane,master   3m15s   v1.21.1
co4aeap000110fc   NotReady   <none>                 5s      v1.21.1
Thu Jun 10 21:53:32 UTC 2021
Thu Jun 10 21:53:47 UTC 2021

```

6) After few seconds, the API server become unreachable in first master and eventually exits
tail end of logs from apiserver pod is as below. BTW I have attached entire log.
```
W0610 21:55:06.267520       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: context deadline exceeded". Reconnecting...
W0610 21:55:06.267544       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: context deadline exceeded". Reconnecting...
W0610 21:55:06.267625       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: context deadline exceeded". Reconnecting...
W0610 21:55:10.750627       1 controller.go:193] RemoveEndpoints() timed out
error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```

**NOTE**: The second master is not added as member to VIP, until join succeeds. So any access to control-plane-endpoint would reach the first master, until join completes.
[api_server_log_from_first_master.log](https://github.com/kubernetes/kubeadm/files/6634740/api_server_log_from_first_master.log)
[Additional info.txt](https://github.com/kubernetes/kubeadm/files/6634743/Additional.info.txt)
[join_spew_from_second_master.log](https://github.com/kubernetes/kubeadm/files/6634746/join_spew_from_second_master.log)
[script_used.sh.txt](https://github.com/kubernetes/kubeadm/files/6634756/script_used.sh.txt)

## Versions

**kubeadm version** (use `kubeadm version`): 1.21.1

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.21.1
- **Cloud provider or hardware configuration**: VM
- **OS** (e.g. from /etc/os-release):
```
- NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- **Kernel** (e.g. `uname -a`):
- 'Linux CO4AEAP000110FB 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux'
- **Others**:

## What happened?
<described above>

## What you expected to happen?
Join not to fail

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubeadm/issues/2503#issuecomment-856198328

**Comment by renukamanavalan** [comment]
Agree, this is not kubeadm issue. Filed it here[ #102797](https://github.com/kubernetes/kubernetes/issues/102797), for anyone, who may land here.
