### ISSUE TITLE
Problem joining node to Kubernetes cluster

### ISSUE THREAD

**Issue by dkoh703** [kubernetes/kubeadm#2508]
Hi folks, 
I'm new to Kubernetes and trying to set up a new Kubernetes cluster using Kubeadm. 

I managed to setup one master control plane node and I want to setup a worker node to run as different VM and join it to the cluster but I hit into issue. 

The the worker node VM, I installed the docker container, kubectl, Kubeadm and etc as per the step in 
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ but instead of running kubeadm init, I run 

kubeadm join <control-plane-host>:<control-plane-port> --token <token> --discovery-token-ca-cert-hash sha256:<hash>

But I'm getting error: 
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
error execution phase kubelet-start: error uploading crisocket: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher

Can someone point me to the right procedure to do this? 
Thanks!

**Comment by neolit123** [comment]
Hi. The most common issue is a cgroup driver missmatch. You can look at the
kubelet logs and then google error strings.

For more information also find the 'kubeadm troubleshooting guide'.

Channels like #kubeadm on k8s slack are a good place to ask for help too.

/kind support
/close
