### ISSUE TITLE
kubeadm shouldn't strip image subpaths unless explicitly told to do so

### ISSUE THREAD

**Issue by BenFradella** [kubernetes/kubeadm#2513]
## Is this a request for help?
No

## What keywords did you search in kubeadm issues before filing this one?
is:issue coredns

## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
`kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:57:56Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
After https://github.com/kubernetes/kubernetes/pull/102502, kubeadm fails to pull coredns from our mirror. It contains the entire coredns tree, not just coredns/coredns, so the bugfix doesn't work for our usecase.

## What you expected to happen?
Expected for the image subpaths to be preserved when an image repository is specified

## How to reproduce it (as minimally and precisely as possible)?
`kubeadm init --image-repository <something other than k8s.gcr.io>`

## Anything else we need to know?
Our image repository is set up as a direct mirror of what's in the public repo. I believe the directory structure would look like this:
```
foo.bar/
└── coredns/
   ├── coredns/
   │  ├── tag1
   │  ├── tag2
   │  └── tag3
   ├── coredns-s390x/
   │  ├── tag1
...
etc, etc
```
Because of this, the correct path to pull coredns from our `foo.bar` repository would be `foo.bar/coredns/coredns:tag`

As far as I can find, there isn't a workaround to enable our use case in v1.21.2. The title of this request outlines what I think would be the ideal solution, but the reverse (explicitly telling kubeadm what path to use) would work.

**Comment by neolit123** [comment]
> After kubernetes/kubernetes#102502, kubeadm fails to pull coredns from our mirror. It contains the entire coredns tree, not just coredns/coredns, so the bugfix doesn't work for our usecase.

can you provide examples in your issue description. it is a bit difficult to see what you are doing in the repository?

after that change, you can provide `--image-repository=foo.bar` and the coredns image would be `foo.bar/coredns:tag`, unless you override the coredns image path completely with `ClusterConfiguration.dns.imageRepository`.
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#DNS

cc @fabriziopandini @vincepri

**Comment by BenFradella** [comment]
Ah, I wasn't sure if I explained that very well or not.
I updated the `anything else we need to know?` section

**Comment by neolit123** [comment]
> Because of this, the correct path to pull coredns from our foo.bar repository would be foo.bar/coredns/coredns:tag

ok, thanks for the details. like i've mentioned in my previous comments this is still possible.
instead of passing --image-registry pass --config:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
imageRepository: "foo.bar"
dns:
  imageRepository: "foo.bar/coredns"
```

and that should work.
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

/kind support

**Comment by BenFradella** [comment]
That worked. Thanks for the help!

Since there is actually a reasonable workaround, I'll go ahead and close the issue
