### ISSUE TITLE
re-order the imports in kubeadm source code files

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2515]
the kubeadm code base under kubernetes/kubernetes/cmd/kubeadm has inconsistent Go imports in source code files.

for example we have:
```
import (
	"fmt"
	"strings"
	"github.com/spf13/pflag"

	bootstrapapi "k8s.io/cluster-bootstrap/token/api"
	bootstraptokenv1 "k8s.io/kubernetes/cmd/kubeadm/app/apis/bootstraptoken/v1"
	kubeadmapiv1 "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta3"
	kubeadmconstants "k8s.io/kubernetes/cmd/kubeadm/app/constants"
)
```

this is not ideal and we should have better separation and order.

```
import (
	// standard library imports are first (NOTE: these are just comments for this example, do not include them)
	"fmt"
	"strings"

	// cmd/kubeadm imports are second (as these are local)
	bootstraptokenv1 "k8s.io/kubernetes/cmd/kubeadm/app/apis/bootstraptoken/v1" 
	kubeadmapiv1 "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta3"
	kubeadmconstants "k8s.io/kubernetes/cmd/kubeadm/app/constants"

	// other *.k8s.io imports are third
	bootstrapapi "k8s.io/cluster-bootstrap/token/api"

	// external repositories are fourth
	"github.com/spf13/pflag"
)
```

if you like to work on this:
- [use this Go version, currently 1.16.5](https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L101-L113)
- do not update generated files, usually starting with `z....`
- after you make the changes make sure that you run `/hack/update-gofmt.sh`
- create a single PR with a single commit that updates the kubeadm code base.

**Comment by fabriziopandini** [comment]
@neolit123 Is there a linter that we can enable to enforce this?

**Comment by neolit123** [comment]
i don't know whether there is something that granular.

**Comment by dims** [comment]
@neolit123 i have a skeleton for a linter here https://github.com/kubernetes/kubernetes/pull/103418 in case someone wants to whip that into shape. the current output looks like this - http://paste.openstack.org/raw/807121/

**Comment by neolit123** [comment]
that's great @dims
one difference in the output seems to be that we add empty lines as separators between sections.

perhaps @xinydev you'd want to implement it as part of kuberentes/kubernetes/hack as a verify-* check?

**Comment by xinydev** [comment]
Maybe we should add empty lines as separators between sections, otherwise `gofmt` will reformat these import lines.

before `gofmt`
```
"sort"
"strings"
"time"
v1 "k8s.io/api/core/v1"
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
bootstrapapi "k8s.io/cluster-bootstrap/token/api"
bootstraputil "k8s.io/cluster-bootstrap/token/util"
bootstrapsecretutil "k8s.io/cluster-bootstrap/util/secrets"
"github.com/pkg/errors"
```

after `gofmt`
```
"github.com/pkg/errors"
"k8s.io/api/core/v1"
"k8s.io/apimachinery/pkg/apis/meta/v1"
metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
bootstrapapi "k8s.io/cluster-bootstrap/token/api"
bootstraputil "k8s.io/cluster-bootstrap/token/util"
bootstrapsecretutil "k8s.io/cluster-bootstrap/util/secrets"
"sort"
"strings"
"time"
```

**Comment by thockin** [comment]
Re-stating from the linked PR - I do not see ANY value in doing anything other than what `goimports` does by default.   This just does not matter very much, and it's a big waste of energy.
