### ISSUE TITLE
add imagePullPolicy field to kubeadm config print

### ISSUE THREAD

**Issue by wangyysde** [kubernetes/kubeadm#2519]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.22

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
According to kubernetes/kubernetes#102901 "imagePullPolicy" has be added. So I think we should add this field to output of kubeadm config print init-defaults|join-defaults

## What you expected to happen?
Add to ield to output of kubeadm config print init-defaults|join-defaults

## How to reproduce it (as minimally and precisely as possible)?
kubeadm config print   init-defaults | join-defaults

**Comment by neolit123** [comment]
When printing a config structure kubeadm takes an empty one and uses
defaulting to populate it. If you look at the defaulting code for v1beta3
you will notice that we do not default noderegistrationoptions and most of
it is defaulted dynamically on runtime.

The same applies to the new imagepullpolicy. It is doable, but i don't
thinks it is needed as long as we have the documentation that "" means
ifnotpresent.

**Comment by wangyysde** [comment]
Ok. Thanks! Now I am reading and learning kubeadm's code. I found that function getDefaultNodeConfigBytes can return the default content of  NodeRegistration,then I try to add imagePullPolicy into it.  :-)
