### ISSUE TITLE
Create kubeadm release process / checklist

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#252]
Now that kubeadm is Beta, and users generally expect quality releases, forwards-compatibility, etc., it's probably time to formalize and document the steps that our SIG needs to take for every release.

Here are some ideas, but they are by no means complete or agreed on yet:
- Clone existing release-branch end-to-end tests to run against the new release branch
  - Manually test against any supported OSes/platforms we don't have e2e variants for
- Automate or manually test upgrade/downgrade with previous kubeadm version(s)
- Curate kubeadm-related release notes
- Verify that our Getting Started guide is updated for any UX changes, and only endorses CNI addons that have been verified to work with the new release
- Should/can we block the tagging of the final release commit on the completion our own release checklist?

This is one of the action items from the [1.6.0 postmortem](https://docs.google.com/document/d/1o-wJ39O8eqBxOCHgu0MGmgH4EdojzI3WlrsV3TVwhe0/edit?usp=sharing).

**Comment by luxas** [comment]
@pipejakob @mikedanese any of you can take ownership over this for v1.7?
I might be able to help as well

**Comment by timothysc** [comment]
@pipejakob ping.

**Comment by pipejakob** [comment]
I don't think I'll have enough bandwidth to take this on in the 1.7 timeframe, but I am happy to contribute to a subsection about the e2e requirements for each release.
