### ISSUE TITLE
Why does kubeadm check the path of conntrack? Without this, it does not seem to affect the cluster function

### ISSUE THREAD

**Issue by wuxinsuoqiu** [kubernetes/kubeadm#2534]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by neolit123** [comment]
Conntrack is used for connection tracking in k8s. The binary is a
dependency of the kubelet and your node might not operate as expected under
high load.

Here is a detailed blog post on conntrack
https://deploy.live/blog/kubernetes-networking-problems-due-to-the-conntrack/

The k8s.io website is missing documentation on what dependencies the
kubelet needs. Kubeadm just tries to check if these binaries exist on
runtime, but we don't have full context on the usage.

If you want action to be taken log an issue at kubernetes/website and tag
with '/sig node cluster-lifecycle'.

/close
/kind support documentation
