### ISSUE TITLE
RFE: Boot-strapping etcd cluster + operator

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#254]
## FEATURE REQUEST 

This is one of several changes I'm proposing regarding kubeadm support for HA and I will cross link with the draft-doc I'd like to share tomorrow, which highlights the details, right now this is a placeholder to be cross-linked.  

## Versions

All

/cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by timothysc** [comment]
xref: https://docs.google.com/document/d/1lH9OKkFZMSqXCApmSXemEDuy9qlINdm5MfWWGrK3JYc/edit#

**Comment by justinsb** [comment]
Tracking some issues here: https://github.com/coreos/tectonic-installer/issues/257

**Comment by jamiehannaford** [comment]
Unless someone else has claimed it, I'd like to work on this feature if that's okay

**Comment by timothysc** [comment]
@jamiehannaford go for it.  I'd be happy to help it along where I can.

**Comment by luxas** [comment]
@timothysc @jamiehannaford Is this tracking issue needed when we have https://github.com/kubernetes/kubeadm/issues/261?

**Comment by jamiehannaford** [comment]
I think we can close this since it's covered by https://github.com/kubernetes/kubeadm/issues/261 and https://github.com/kubernetes/kubeadm/issues/277

**Comment by luxas** [comment]
Ok, thanks @jamiehannaford
