### ISSUE TITLE
Kubeadm init error - Ubuntu

### ISSUE THREAD

**Issue by happylucki** [kubernetes/kubeadm#2541]
While Installing on Ubuntu nusing kubeadm.... Getting the following error 

[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.

**Comment by KelvinAkpobome** [comment]
Same issue here too.

**Comment by happylucki** [comment]
I think it is because Kubernetes  as deprecated docker .... May be running with containerd will help

**Comment by KelvinAkpobome** [comment]
Yes. It did help

Thanks a lot

**Comment by SataQiu** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/104230#issuecomment-894933632

**Comment by neolit123** [comment]
please always check the release notes:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#no-really-you-must-read-this-before-you-upgrade

>> Kubeadm: remove the automatic detection and matching of cgroup drivers for Docker. For new clusters if you have not configured the cgroup driver explicitly you might get a failure in the kubelet on driver mismatch (kubeadm clusters should be using the systemd driver). Also remove the IsDockerSystemdCheck preflight check (warning) that checks if the Docker cgroup driver is set to systemd. Ideally such detection / coordination should be on the side of CRI implementers and the kubelet (tracked here). Please see the page on how to configure cgroup drivers with kubeadm manually (#99647, @neolit123)

> I think it is because Kubernetes as deprecated docker .... May be running with containerd will help

the docker support in k8s is currently built-in. it's moving to external:
https://github.com/Mirantis/cri-dockerd

/kind support
