### ISSUE TITLE
kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"

### ISSUE THREAD

**Issue by PengBo-Tyler** [kubernetes/kubeadm#2542]
hello!
     I am a chines,my english is terrible！Sometimes，Maybe you can't understand what it is mean. I am so sorry for it.But I really hope you can help me to "do it -the problem".

    I am deploying the K8S in "kubeadm-1.22.0",docker's version is  20.10.8 . the OS is Red Hat 8.2 and the OS run in VMware. OS swap off , SELinux  disabled .
"kubeadm config images list " ==  "docker images"--> (I have images and version is OK)
k8s.gcr.io/etcd                                     3.5.0-0
k8s.gcr.io/kube-apiserver                    v1.22.0
k8s.gcr.io/kube-controller-manager   v1.22.0
k8s.gcr.io/kube-scheduler                   v1.22.0
k8s.gcr.io/kube-proxy                          v1.22.0
k8s.gcr.io/coredns/coredns                  v1.8.4
k8s.gcr.io/pause                                   3.5

The problem: 
    I run the command--> "kubeadm init --config=kubeadm-init-config.yaml"
    ......console print......
-----------------------------------------------------------------------
[init] Using Kubernetes version: v1.22.0
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [192.168.206.128 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.206.128]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [192.168.206.128 localhost] and IPs [192.168.206.128 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [192.168.206.128 localhost] and IPs [192.168.206.128 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
---------------------------------------------------------------

Now! it will stop this status long time! And I open othes tty to see the log (use this command:"journalctl -xeu kubelet")
journalctl -xeu kubelet-->print:
---------------------------------------------------------------
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.225443   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: I0810 05:23:26.261886   68865 scope.go:110] "RemoveContainer" containerID="1051c237a075cb9f4176cf6132de9af69d3f3fc1f9c43af0924725064bc8528>
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.262272   68865 pod_workers.go:747] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"etcd\" with CrashL>
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.326602   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.427971   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.529514   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.631099   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.732562   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.833025   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:26 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:26.933353   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:27 RHEL-SERVER-1 kubelet[68865]: I0810 05:23:27.024196   68865 scope.go:110] "RemoveContainer" containerID="1051c237a075cb9f4176cf6132de9af69d3f3fc1f9c43af0924725064bc8528>
Aug 10 17:23:27 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:27.024494   68865 pod_workers.go:747] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"etcd\" with CrashL>
Aug 10 17:23:27 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:27.033712   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
Aug 10 17:23:27 RHEL-SERVER-1 kubelet[68865]: E0810 05:23:27.135464   68865 kubelet.go:2407] "Error getting node" err="node \"192.168.206.128\" not found"
------------------------------------------------------------

Why???What's reason？
How to resolve the problem?

If you can help me to resolve the problem ，I appreciate for you!!!

**Comment by neolit123** [comment]
hi, we try to keep the kubeadm issue tracker only for bugs/features.
for support you can use #kubeadm on k8s slack or the links here:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

> I am deploying the K8S in "kubeadm-1.22.0",docker's version is  20.10.8 . the OS is Red Hat 8.2 and the OS run in VMware. OS swap off , SELinux  disabled .

this might be caused by a cgroupdriver problem (it's very common), see:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

kubeadm 1.22 changed it's behavior for docker, see the change log:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md

>> Kubeadm: remove the automatic detection and matching of cgroup drivers for Docker. For new clusters if you have not configured the cgroup driver explicitly you might get a failure in the kubelet on driver mismatch (kubeadm clusters should be using the systemd driver). Also remove the IsDockerSystemdCheck preflight check (warning) that checks if the Docker cgroup driver is set to systemd. Ideally such detection / coordination should be on the side of CRI implementers and the kubelet (tracked here). Please see the page on how to configure cgroup drivers with kubeadm manually (#99647, @neolit123)

/kind support
