### ISSUE TITLE
Remake some func args for dry run

### ISSUE THREAD

**Issue by Haleygo** [kubernetes/kubeadm#2543]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

During the process of [adding dryrun join](https://github.com/kubernetes/kubernetes/pull/103027), we found out that there are some func in kubeadm cmd can't be easily remake to accept directory as expected.
Like:
[#103027 (comment)](https://github.com/kubernetes/kubernetes/pull/103027#discussion_r655531613)
[#103027 (comment)](https://github.com/kubernetes/kubernetes/pull/103027#discussion_r655532163)
To avoid making that too big, here is a separate task to do that.

edit by neolit123:
this is to avoid modifying fields like cfg.CertificatesDir during dry run.

**Comment by neolit123** [comment]
test
(just testing a github action that we recently added)

**Comment by neolit123** [comment]
@Haleygo hey do you have time to work on this for 1.25?

**Comment by Haleygo** [comment]
> @Haleygo hey do you have time to work on this for 1.25?

So sorry, I have worked on it a few months ago but not finished. This week I will rebase and try to finish it, if not, I will ask for help.

**Comment by neolit123** [comment]
/remove-lifecycle stale

perhaps we can close this? the refractor is ultimately a nice to have / for correctness.

**Comment by chendave** [comment]
I think we can close this by https://github.com/kubernetes/kubernetes/pull/113005, but I don't have the permission to close this.

**Comment by chendave** [comment]
let me have a try

/close
