### ISSUE TITLE
error syncing endpoints with etcd: context deadline exceeded To see the stack trace of this error execute with --v=5 or higher

### ISSUE THREAD

**Issue by ymwfish** [kubernetes/kubeadm#2549]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by fabriziopandini** [comment]
Could you kindly fill in the required info to help the team in reproduce and triage the problem

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubeadm#support

/kind support
/close
