### ISSUE TITLE
update a certificate front-proxy-ca.crt

### ISSUE THREAD

**Issue by guleng** [kubernetes/kubeadm#2553]
## What happened?
kubeadm:1.15.5
The “front-proxy-ca.crt and front-proxy-ca.key” does not change after the certificate is updated with the “ kubeadm alpha certs renew all  --use-api” command

## What you expected to happen?
The above certificate causes this error "Error from server (Forbidden): nodes.metrics.k8s.io is forbidden: User "front-proxy-client" cannot list resource "nodes" in API group "metrics.k8s.io" at the cluster scope" when executing "kubectl top node"

Is there a way to update “front-proxy-ca.crt and front-proxy-ca.key” certificate?

Is this a 1.15.1 bug?

**Comment by neolit123** [comment]
hi,

> kubeadm:1.15.5

this version is very old and out of support.

> kubeadm alpha certs renew all --use-api

note, the --use-api flag no longer exists in newer versions of kubeadm.

> The above certificate causes this error "Error from server (Forbidden): nodes.metrics.k8s.io is forbidden: User "front-proxy-client" cannot list resource "nodes" in API group "metrics.k8s.io" at the cluster scope" when executing "kubectl top node"
> Is there a way to update “front-proxy-ca.crt and front-proxy-ca.key” certificate?

kubeadm signs all CAs with a 10 years duration.
the above message talks about front-proxy-client, that client cert is signed for 1 year.

if you wish to update the client cert you can use `kubeadm alpha certs renew`
to rotate the CAs in the cluster you can see this guide:
https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

> Is this a 1.15.1 bug?

i don't remember such a bug, this looks like a separate problem.

for more questions see https://git.k8s.io/kubeadm/README.md#support

/kind support
