### ISSUE TITLE
kubeadm e2e tests should upload relevant master/node logs

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#256]
When initialization of a cluster fails, our kubeadm e2e tests have an opaque error in the build log about not being able to fetch the `admin.conf` kubeconfig file from the master.

Here is one such instance:

    W0427 22:38:47.813] +(./do:60): fetch_kubeconfig(): sleep 5
    W0427 22:38:52.814] +(./do:64): fetch_kubeconfig(): echo Exhausted attempts to fetch kubeconfig.
    W0427 22:38:52.815] Exhausted attempts to fetch kubeconfig.
    W0427 22:38:52.815] +(./do:65): fetch_kubeconfig(): exit 1
    W0427 22:38:52.816] make[1]: *** [do] Error 1
    W0427 22:38:52.816] make: *** [deploy-cluster] Error 2

(from [ci-kubernetes-e2e-kubeadm-gce#1457](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/1457))

In this case, the real failure is likely to be a part of the VM startup script log on the master (or on the nodes, if those fail to join), so we should fetch those logs from the remote VMs into the local `artifacts` directory that gets archived as part of the job run so that it's possible to diagnose the failure after the cluster has been torn down.

**Comment by luxas** [comment]
@pipejakob any update on this issue?

**Comment by luxas** [comment]
ping @pipejakob 
As we enhance our testing setup, this becomes a must.

Do you have a couple of hours to put on this?
Adding to the v1.9 milestone

**Comment by jessicaochen** [comment]
From my experience, having at least the kubelet logs on the master would be helpful. Most of the opaque errors (as described in first post) that I have hit were diagnosable with those logs.

So far I have had to manually test my own cluster to get at said logs.

**Comment by luxas** [comment]
@jessicaochen Yeah, we know :/ Could you please fix it?
Getting the master components' logs should be trivial (`kubectl -n kube-system logs kube-apiserver-${MASTERNAME}`), but kubelet logs is a bit harder. Getting those from the master at least as an initial step would be good.

Sorry, I'm partially OOO for some time yet.

**Comment by jessicaochen** [comment]
I am motivated for a fix since it causes me pain. However, I am unsure I can promise the time to it. I will poke around a bit and if I can get some pull requests out, I will grab the issue.

**Comment by luxas** [comment]
Thank you!

**Comment by luxas** [comment]
@dims I remember you worked on this for some time. Did you ever finish the work or :grin:?

**Comment by dims** [comment]
/assign @dims 

Hey Lucas, i'll check what we ended up with and my older experiments

**Comment by luxas** [comment]
Thanks @dims!!

**Comment by dims** [comment]
@luxas looks like https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/ has been red since https://github.com/kubernetes/kubernetes/pull/55468 merged. There was enough info in the logs to see the problem, example for the log that shows why we are failing:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/8748/artifacts/e2e-8748-node-10fj/startupscript.log

I have submitted https://github.com/kubernetes/kubernetes-anywhere/pull/484 to help with the situation, Looks like when that merges, we will need to update https://github.com/kubernetes/test-infra/blob/master/images/kubeadm/runner#L29 and cut a fresh e2e-kubeadm container image. 

Is my analysis correct? 

Thanks,
Dims

**Comment by xiangpengzhao** [comment]
Is this full implemented? When I try to triage https://github.com/kubernetes/kubeadm/issues/585, I can't find enough info on master (for why master components aren't restarted by kubelet).

**Comment by shashidharatd** [comment]
I stumbled upon this issue while analyzing the failures in CI. https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce
one of the reason why we see the error as described in this issue is because the startup-script has failed.
Here is log from one such failure.
```
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script: Errors were encountered while processing:
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script:  /tmp/k8s-debs/kubernetes-cni.deb
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script:  kubelet
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script:  kubeadm
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script: + echo Ignoring expected dpkg failure
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script: Ignoring expected dpkg failure
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script: + apt-get install -f -y
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script: Reading package lists...
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script: Building dependency tree...
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script: Reading state information...
Feb  7 01:56:15 e2e-9556-master startup-script: INFO startup-script: Correcting dependencies... Done
Feb  7 01:56:16 e2e-9556-master startup-script: INFO startup-script: The following packages will be REMOVED:
Feb  7 01:56:16 e2e-9556-master startup-script: INFO startup-script:   kubeadm kubelet
Feb  7 01:56:16 e2e-9556-master startup-script: INFO startup-script: 0 upgraded, 0 newly installed, 2 to remove and 65 not upgraded.
Feb  7 01:56:16 e2e-9556-master startup-script: INFO startup-script: 2 not fully installed or removed.
Feb  7 01:56:16 e2e-9556-master startup-script: INFO startup-script: After this operation, 0 B of additional disk space will be used.
Feb  7 01:56:16 e2e-9556-master startup-script: INFO startup-script: (Reading database ... #015(Reading database ... 5%#015(Reading database ... 10%#015(Reading database ... 15%#015(Reading database ... 20%#015(Reading database ... 25%#015(Reading database ... 30%#015(Reading database ... 35%#015(Reading database ... 40%#015(Reading database ... 45%#015(Reading database ... 50%#015(Reading database ... 55%#015(Reading database ... 60%#015(Reading database ... 65%#015(Reading database ... 70%#015(Reading database ... 75%#015(Reading database ... 80%#015(Reading database ... 85%#015(Reading database ... 90%#015(Reading database ... 95%#015(Reading database ... 100%#015(Reading database ... 67984 files and directories currently installed.)
Feb  7 01:56:16 e2e-9556-master startup-script: INFO startup-script: Removing kubeadm (1.10.0~alpha.3.254+056e9ecc43e53b) ...
Feb  7 01:56:16 e2e-9556-master startup-script: INFO startup-script: Removing kubelet (1.10.0~alpha.3.254+056e9ecc43e53b) ...
Feb  7 01:56:17 e2e-9556-master startup-script: INFO startup-script: + systemctl enable kubelet
Feb  7 01:56:17 e2e-9556-master startup-script: INFO startup-script: Failed to execute operation: No such file or directory
Feb  7 01:56:17 e2e-9556-master startup-script: INFO startup-script: Return code 1.
Feb  7 01:56:17 e2e-9556-master startup-script: INFO Finished running startup scripts.
```
It clearly shows there is some problem in installing `kubernetes-cni.deb`. Is anyone working on fixing this issue?

**Comment by timothysc** [comment]
closing this one as we have a debug doc now and know howto debug the upstream suite.  However we need to totally refator it which I'm hoping folks can work on in the 1.11 cycle
