### ISSUE TITLE
Add mirror sub-command to kubeadm config images

### ISSUE THREAD

**Issue by nfisher** [kubernetes/kubeadm#2562]
## FEATURE REQUEST

Add a `mirror` subcommand to `kubeadm config images`.

## Versions

**kubeadm version** (use `kubeadm version`): all

**Environment**:
- **Kubernetes version** (use `kubectl version`): all
- **Cloud provider or hardware configuration**: NA
- **OS** (e.g. from /etc/os-release): NA
- **Kernel** (e.g. `uname -a`): NA
- **Others**: NA

## What happened?

Mirroring gcr images requires knowledge of what kubeadm expects. As an example coredns is in a subpath of /coredns/ which can create problems for people such as the following https://github.com/kubernetes/kubeadm/issues/2525 .

## What you expected to happen?

A `mirror` subcommand would combine a pull, retag, and push to a mirror repository with the structure that default kubeadm would expect without changes to the kubeadm cluster config.

**Comment by neolit123** [comment]
hello,

i think the command can be useful, but it would step outside of the scope of kubeadm which has been to only support the minimal viable functionality to create a cluster. listing and pulling the images is a necessary functionality, today.
tagging and pushing seems like and advanced use case that can be done with the host container runtime tools.

> Mirroring gcr images requires knowledge of what kubeadm expects. As an example coredns is in a subpath of /coredns/ which can create problems for people such as the following #2525 .

as noted on the issue, kubeadm users can use the ClusterConfiguration object to configure the coredns image location entirely.
the defaults in the later versions with a custom registry is to not have a path for the coredns image, by default.

the whole introduction of the coredns subpath created a lot of problems for users and higher level tools. some wanted the custom registry path to have coredns, but the majority didn't, thus we had to revert it.

retagging works, but i don't think we should recommend it as a workaround in subcommands or in the documentation.
