### ISSUE TITLE
How to build kubeadm from source code and build image to run K8S cluster

### ISSUE THREAD

**Issue by zhaocheng173** [kubernetes/kubeadm#2565]
Who can help me? Now I was installed through the yum/apt kubelet, kubectl, kubeadm, when deployed, the default/etc/kubernetes/manifest and/var/lib/kubelet/config. Yml has increased the default parameters, WHAT I know is that I can clone kubenetes code, make WHAT= CMD /kubeadm to compile kubeadm, modify the code configuration in it to start kubeadm with the specified parameters, However, I am confused about how to modify the location. For example, I modified or added the parameter of /var/lib/kubelet, and I don't know where to modify it. In addition, I modified it like this.

**Comment by neolit123** [comment]
to build kubeadm clone kubernetes/kubernetes and type:
`make all WHAT=/cmd/kubeadm` the output binary will be in `_output`.

what you are trying to do is not recommended.
you don't have to clone source code to modify how kubeadm works.

configuring is documented here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/

for more help try #kubeadm on k8s slack.

/support
