### ISSUE TITLE
kubeadm config images list wrong when initializing cluster

### ISSUE THREAD

**Issue by ricosega** [kubernetes/kubeadm#2569]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm config images list wrong when initializing cluster

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:44:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
Baremetal

- **OS** (e.g. from /etc/os-release):
Debian11

- **Kernel** (e.g. `uname -a`):
```
Linux planet 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
```

## What happened?
This is the list of images that I get when I use the following command:
```
kubeadm config images list --kubernetes-version v1.22.1
k8s.gcr.io/kube-apiserver:v1.22.1
k8s.gcr.io/kube-controller-manager:v1.22.1
k8s.gcr.io/kube-scheduler:v1.22.1
k8s.gcr.io/kube-proxy:v1.22.1
k8s.gcr.io/pause:3.5
k8s.gcr.io/etcd:3.5.0-0
k8s.gcr.io/coredns/coredns:v1.8.4
```
So we downloaded this images and then uploaded them in our offline repo.
But when I initialize the cluster is expecting another image:
```
module.k8s_cluster.vsphere_virtual_machine.k8s_cp[0] (remote-exec):     [ERROR ImagePull]: failed to pull image private.local/k8s/k8s.gcr.io/coredns:v1.8.4: output: Error response from daemon: unknown: artifact k8s/k8s.gcr.io/coredns:v1.8.4 not found
```

## What you expected to happen?
To expect proper image, same as in the list.

## How to reproduce it (as minimally and precisely as possible)?
Initiliaze a cluster with kubeadm in offline or using different repository image:
```
kubeadm --image-repository private.local ...
```

## Anything else we need to know?
With other Kubernetes versions works good.

**Comment by neolit123** [comment]
please see:
https://github.com/kubernetes/kubeadm/issues/2513#issuecomment-867004320

and

https://kubernetes.slack.com/archives/C13J86Z63/p1631243935015600?thread_ts=1631209647.012500&cid=C13J86Z63

> the coredns subpath change that the coredns team made certainly broke people.
what you can do is use kubeadm config images list --config for the image source -> target mapping. this will work for versions post *and* pre 1.21 (so portable, before the subpath change too...).
> - pass empty config to obtain the GCR sources
> - pass a config with a custom ClusterConfiguration.imageRepository
> - pull image foo from its source location (1) and push it to the target (2).

at the time of the change., most users requested that local repositories do not have the subpath, despite the GCR repository having it. but some users still complain about the subpath discrepancy between remote and custom registires.

^ @vincepri @fabriziopandini @ykakarap

**Comment by neolit123** [comment]
logged https://github.com/kubernetes/kubeadm/issues/2570 to track adding some documentation for this.
