### ISSUE TITLE
kubeadm init with pod-network-cidr but still remains using 10.85.0.0

### ISSUE THREAD

**Issue by nghyjohn** [kubernetes/kubeadm#2572]
I tried to init k8s by the following command:

`kubeadm init --control-plane-endpoint example.com --upload-certs --pod-network-cidr 172.31.0.0/16 --service-cidr 10.240.0.0/12 --kubernetes-version v1.22.2`

After init, the pod network still using 10.85.0.0, which is not my expectation:
$ kubectl get pods -A -owide
```
NAMESPACE     NAME                                  READY   STATUS    RESTARTS   AGE     IP           NODE          NOMINATED NODE   READINESS GATES
kube-system   coredns-78fcd69978-qhrmb              1/1     Running   1          10m     10.85.0.4    dsok8smst01   <none>           <none>
kube-system   coredns-78fcd69978-vd6sc              1/1     Running   1          10m     10.85.0.5    dsok8smst01   <none>           <none>
kube-system   etcd-dsok8smst01                      1/1     Running   1          10m     10.9.17.44   dsok8smst01   <none>           <none>
...other_pods...
```

$ cat /etc/cni/net.d/100-crio-bridge.conf
`{
    "cniVersion": "0.3.1",
    "name": "crio",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "hairpinMode": true,
    "ipam": {
        "type": "host-local",
        "routes": [
            { "dst": "0.0.0.0/0" },
            { "dst": "1100:200::1/24" }
        ],
        "ranges": [
            [{ "subnet": "10.85.0.0/16" }],
            [{ "subnet": "1100:200::/24" }]
        ]
    }
}`

$ kubeadm version
`kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:37:34Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`

Would like to know if it is a normal behaviour. If not, am I missing any configuration?
Thank you.

**Comment by neolit123** [comment]
> "subnet": "10.85.0.0/16"

IIUC, having this in your cni config cannot be overriden by the kubeadm
flag, which is just propagated as the "cluster-cidr" flag in the
kube-controller-manager manifest.

This CNI seems to *require* the 10.85.0.0 subnet and that is what you
should be passing to pod-network-cidr.

At least this is my understanding.
You can confirm with the k8s network experts in #sig-network on k8s slack.

I do not see a kubeadm bug here, as kubeadm just passes the user value to
the kcm.

/kind support

**Comment by neolit123** [comment]
Closing. For more support questions see the bot message below.

/support

**Comment by volker-raschek** [comment]
Hi @nghyjohn, 
I have the same problem in my kubernetes environment. Have you been able to solve the problem?

**Comment by pschoen-itsc** [comment]
@volker-raschek I also had this problem on a cluster. I then just installed my CNI Operator (Calico), rollout the pods with the wrong IPs and they got the IPs from the correct network.
