### ISSUE TITLE
`kubeadm init` prints /var/run/dockershim.sock, when it means /var/run/docker.sock

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubeadm#2576]
On my system I had the file /var/run/docker.sock and I had no file /var/run/dockershim.sock .
```
$ kubeadm init
Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock
To see the stack trace of this error execute with --v=5 or higher
```

kubeadm version: &version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-rc.0.12+2c0e4a232a3c10", GitCommit:"2c0e4a232a3c10a9083012ec28a3622bd4e4be90", GitTreeState:"clean", BuildDate:"2021-09-25T19:32:20Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by pacoxu** [comment]
/assign
Let me try to reproduce.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/cde45fb161c5a4bfa7cfe45dfd814f6cc95433f7/cmd/kubeadm/app/util/runtime/runtime.go#L204-L207

It seems to be intended.

**Comment by neolit123** [comment]
The logic seems valid. The message is slightly misleading, but it is a bit hard to explain in a message that CRI support in the kubelet is integrated and one socket is used for container runtime detection and one for actual comms.  The dockershim.sock file is created by the kubelet on runtime currently.

If kubeadm detects multiple container runtimes and you need to specify which one. To avoid this you can also uninstall docker and leave only crio.

/kind support

**Comment by dilyanpalauzov** [comment]
I mean, kubeadm shall not suggest

> Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock

when the system has no file `/var/run/dockershim.sock`.
