### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by lukemarsden** [kubernetes/kubeadm#258]
The kubeadm guide (https://kubernetes.io/docs/getting-started-guides/kubeadm/) links to https://github.com/kubernetes/kubeadm/blob/master/CHANGELOG.md, but that doesn’t refer to any release that installs kube 1.6.

**Comment by luxas** [comment]
I'll go ahead and fix this

**Comment by luxas** [comment]
Fixed with: https://github.com/kubernetes/kubernetes.github.io/pull/4018
