### ISSUE TITLE
`kubeadm --ignore-preflight-errors=swap` shall put `failSwapOn: false` in /var/lib/kubelet/config.yaml

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubeadm#2580]
On my system I have swap on.  I run `kubeadm init  -v 1000 --ignore-preflight-errors=swap`.  kubeadm prints
```
I1002 19:49:45.622569 1056789 checks.go:618] validating kubelet version
I1002 19:49:45.725253 1056789 checks.go:132] validating if the "kubelet" service is enabled and active
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
I1002 19:49:45.766482 1056789 checks.go:205] validating availability of port 10250
I1002 19:49:45.766572 1056789 checks.go:205] validating availability of port 2379
I1002 19:49:45.766655 1056789 checks.go:205] validating availability of port 2380
…
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
…
I1002 19:50:01.819611 1056789 waitcontrolplane.go:89] [wait-control-plane] Waiting for the API server to be healthy
I1002 19:50:01.820534 1056789 loader.go:372] Config loaded from file:  /etc/kubernetes/admin.conf
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". Thi
s can take up to 4m0s
I1002 19:50:07.169308 1056789 round_trippers.go:435] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.22.2 (
linux/amd64) kubernetes/8b5a191" 'https://144.76.142.78:6443/healthz?timeout=10s'
I1002 19:50:07.169569 1056789 round_trippers.go:454] GET https://144.76.142.78:6443/healthz?timeout=10s  in 0 milliseconds
I1002 19:50:07.169603 1056789 round_trippers.go:460] Response Headers:
I1002 19:50:07.670815 1056789 round_trippers.go:435] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.22.2 (linux/amd64) kubernetes/8b5a191" 'https://144.76.142.78:6443/healthz?timeout=10s'
```

Since kubeadm creates /var/lib/kubelet/config.yaml I assume that the kubelet is started with that file as parameter.

* On systems, where kubeadm is called with `--ignore-preflight-errors=swap` the generated `/var/lib/kubelet/config.yaml` does not contain `failSwapOn: false` and thus kubelet does not start.
-----------------------------
> I1002 19:49:45.725253 1056789 checks.go:132] validating if the "kubelet" service is enabled and active
>        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
> I1002 19:49:45.766482 1056789 checks.go:205] validating availability of port 10250

I think the above makes no sense.  If kubelet is running, then `kubeadm init -v 100` fails with
```
I1002 22:14:40.632520  433975 checks.go:618] validating kubelet version
I1002 22:14:40.727051  433975 checks.go:132] validating if the "kubelet" service is enabled and active
I1002 22:14:40.757490  433975 checks.go:205] validating availability of port 10250
I1002 22:14:40.757800  433975 checks.go:205] validating availability of port 2379
I1002 22:14:40.757863  433975 checks.go:205] validating availability of port 2380
I1002 22:14:40.757909  433975 checks.go:245] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Some fatal errors occurred:
        [ERROR Port-10250]: Port 10250 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        /git/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        /git/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        /git/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        /git/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /git/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:852
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /git/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:960
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /git/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:897
k8s.io/kubernetes/cmd/kubeadm/app.Run
```

So if kubelet is not running, kubeadm complains that it is not running, but if it running, kubeadm complains that port 10250 is in use.

* Verifying whether kubelet service is enabled and active, and whether port 10250 is available are mutually exclusive checks, since it is not possible to pass both checks at the same time.

## What keywords did you search in kubeadm issues before filing this one?
swap

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"archive", BuildDate:"2021-09-26T07:22:48Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"archive", BuildDate:"2021-09-26T07:22:48Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Linux from Scratch
- **Kernel** (e.g. `uname -a`): Linux mail 5.10.69 hash5 SMP Wed Sep 29 12:54:02 UTC 2021 x86_64 GNU/Linux

**Comment by dilyanpalauzov** [comment]
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/ - the kubeadm Configuration (v1beta3), also has no toggle to enable swap for the kubelet configuration file.

**Comment by neolit123** [comment]
> the kubeadm Configuration (v1beta3), also has no toggle to enable swap for the kubelet configuration file.

This is intentional. You can pass a KubeletConfiguration next to your InitConfiguration separated with by ---. This is covered in the above doc.

**Comment by neolit123** [comment]
> [WARNING Service-Kubelet]: kubelet service is not enabled,

Peobably related to your other reports. Your kubelet is not running.

> On systems, where kubeadm is called with --ignore-preflight-errors=swap the generated /var/lib/kubelet/config.yaml does not contain failSwapOn: false and thus kubelet does not start.

If you ignore the preflight error for swap, then you must configure failswapon in the kubeletconfiguration explicitly. See above api link again.

Swap is not really supported in the kubelet, and it might just crash on you. Kubelet 1.22 added an alpha feature gate called NodeSwap that may graduate to beta in 1.23. Until that happens using swap is not recommended.

Please try using #kubeadm on the k8s slack or the support channels before logging issues on sonething that may not be a bug. Users can help you understand some of the quirks.

https://github.com/kubernetes/kubeadm#support

**Comment by dilyanpalauzov** [comment]
I think that `--ignore-preflight-errors=swap` shall instruct kubeadm to insert `failSwapOn: false` in the kubelet configuration file.  I do not care if it crashes, I want to build kubernetes on a tiny system to understand how it works.

**Comment by neolit123** [comment]
> I think that --ignore-preflight-errors=swap shall instruct kubeadm to insert failSwapOn: false in the kubelet configuration file. I do not care if it crashes, I want to build kubernetes on a tiny system to understand how it works.

we have plans to remove the "swap" preflight check entirely because of the new kubelet NodeSwap feature gate.
in 1.23 we are moving it to a warning instead of an error:
https://github.com/kubernetes/kubernetes/pull/104854

the NodeSwap feature gate will likely graduate to GA in 1.24 and the kubeadm "swap" feature gate will be removed.
