### ISSUE TITLE
kubeadm init: when kubelet.service does not exist, propose content of the kubelet.service file

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubeadm#2584]
I have compiled kubeadm and kubelet from source.  Running `kubeadm init` prints:
```
[init] Using Kubernetes version: v1.22.2
[preflight] Running pre-flight checks
	[WARNING Service-Kubelet]: kubelet service does not exist
…
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
```
The control plane of course never starts.  The source code at https://github.com/kubernetes/kubernetes does not contain the content of an eventual kubelet.service file.

When the kubelet.service file exists, but is not turned on, `kubeadm init` prints:

```
[preflight] Running pre-flight checks
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
```
Finding the right kubelet.service, which correctly utilizes the output of `kubeadm init`, turned out to be very hard:
* https://github.com/kubernetes/website/issues/29913
* https://github.com/kubernetes/website/issues/29943

I propose when “Kubelet service does not exist” is printed, that kubeadm init prints suggestion how kubelet.service shall look like, (not as base kubelet.service, and in addition drop-in systemd file), or provide detailed description how the service file shall be obtained.

**Comment by neolit123** [comment]
Sorry but I am really not in favour of this. There should be a single source of truth about the kubelet service files. That place is currently k/release and it would create a weird binding with k/k. We might also want to remove the examples from the website.

If kubeadm move to a different versioning things would become worse.

To install the systemd files users must follow our guide "without a package manager" and not copy paste files contents from somewhere.

**Comment by dilyanpalauzov** [comment]
It would be nice, if `kubeadm init` prints information how the kubelet.service file can be obtained,  e.g. by printing some html-links containing information on this.
