### ISSUE TITLE
Reference to "old kubeadm" is broken link

### ISSUE THREAD

**Issue by lukemarsden** [kubernetes/kubeadm#259]
At https://kubernetes.io/docs/getting-started-guides/kubeadm/, the docs say:

> While this guide is correct for kubeadm 1.6, the previous version is still available but can be a bit tricky to install. [See below](https://kubernetes.io/docs/getting-started-guides/kubeadm/#old-kubeadm) for details.

The "See below" link (https://kubernetes.io/docs/getting-started-guides/kubeadm/#old-kubeadm) is broken.

**Comment by luxas** [comment]
Fixed with: https://github.com/kubernetes/kubernetes.github.io/pull/4018
