### ISSUE TITLE
CI for 1.20 is failing after move to io / os package functions

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2598]
EDIT: looks like 1.20 uses Go 1.15.15
https://github.com/kubernetes/kubernetes/blob/release-1.20/build/dependencies.yaml#L100-L102

kubernetes/kubeadm#2593 broke CI for 1.20 where go 1.16 is used:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-1-20/1455272256916688896/build-log.txt

> pkg/extract/extract.go:464:14: undefined: io.ReadAll

https://pkg.go.dev/io/ioutil claims:
> As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.

but io.ReadAll is not in 1.16 for some reason?
should os.ReadAll be used instead?

**Comment by neolit123** [comment]
/assign @ahrtr 
why do you think this is happening?

**Comment by ahrtr** [comment]
> /assign @ahrtr why do you think this is happening?

@neolit123 The io.ReadAll is correct for sure. The reason should be that the golang version used in the pipeline is older than 1.16?

**Comment by neolit123** [comment]
ok, looks like i was mistaken and 1.20 uses 1.15.15
https://github.com/kubernetes/kubernetes/blob/release-1.20/build/dependencies.yaml#L100-L102

which is a problem and means we have to revert https://github.com/kubernetes/kubeadm/pull/2593
until 1.20 goes out of support, later this year.

this can be tracked in an issue.

**Comment by neolit123** [comment]
revert PR:
https://github.com/kubernetes/kubeadm/pull/2600

tracking issue for adding back the io / os changes once 1.20 goes out of support:
https://github.com/kubernetes/kubeadm/issues/2599

**Comment by ahrtr** [comment]
Does it make more sense to cut off different branches for kubeadm, and use a corresponding branch for each kubernetes branch?

**Comment by neolit123** [comment]
once kubeadm moves here and if kubeadm continues to follow the k8s release cycle, yes.
until then this is only about kinder, which should support the skew of go versions.

there are ways to make kinder always build with specific Go version X, but that's a complication.
