### ISSUE TITLE
reintroduce the Go io / os package changes once 1.20 goes out of support

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2599]
1.20 still uses go 1.15.15 for building
which means we cannot have the changes that this PR made:
https://github.com/kubernetes/kubeadm/pull/2593

re-add the changes in the 1.24 cycle after 1.20 goes out of support.

**Comment by calvin0327** [comment]
@neolit123 To replace Ioutil in the 1.24 cycle? If so, I'll do it.

**Comment by neolit123** [comment]
This should be done only after we stop testing 1.20 k8s. https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm

**Comment by pacoxu** [comment]
> This should be done only after we stop testing 1.20 k8s. https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm

https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md#120
End of Life for 1.20 is 2022-02-28 (today).

It's time to stop testing 1.20 k8s, isn't it?

**Comment by RA489** [comment]
> > This should be done only after we stop testing 1.20 k8s. https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm
> 
> https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md#120 End of Life for 1.20 is 2022-02-28 (today).
> 
> It's time to stop testing 1.20 k8s, isn't it?

@pacoxu we are good to go after we merge https://github.com/kubernetes/test-infra/pull/25065 today.
