### ISSUE TITLE
kubeadm should have an option on master to print out join command again

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#26]
_From @peterkellyonline on October 7, 2016 12:43_

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kubeadm master join

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST 

A convenient command such as `kubeadm config` or `kubeadm show` to return the command for a node to join the cluster i.e. `kubeadm join --token <token> <master-ip>`. 

(I am happy to work on this myself and contribute)

_Copied from original issue: kubernetes/kubernetes#34324_

**Comment by mikedanese** [comment]
_From @luxas on October 12, 2016 14:57_

I'd say feel free to :)
cc @kubernetes/sig-cluster-lifecycle

**Comment by mikedanese** [comment]
_From @errordeveloper on October 12, 2016 16:1_

I think you might be able to solve this with `kubeadm init --token=...`. If you want to be more specific about the IP address as well, you can pass `--api-advertise-addresses` as well. We have advance usage docs here now: http://kubernetes.io/docs/admin/kubeadm/.

**Comment by mikedanese** [comment]
_From @luxas on October 12, 2016 16:8_

I think the use case was to let kubeadm generate a random token and be able to fetch it later, but I don't know if it's worthwhile... May be easier to just specify a random token to kubeadm init directly

**Comment by mikedanese** [comment]
_From @peterkellyonline on October 12, 2016 16:42_

Yes, the use case letting init generate the random token but then be able
to fetch that token later, outside of the print out from the successful run
of init on master node.

It is straight forward to get it through the master API, then decode the
value to JSON and get the token that way, but I expected to be able to get
this easily from kubeadm cli.

If it's not worthwhile and the advice is to generate and store your own
token first, before init, then that's okay.

**Comment by mikedanese** [comment]
_From @pires on October 12, 2016 19:57_

I believe this is something @dgoodwin is working on.

**Comment by mikedanese** [comment]
_From @dgoodwin on October 13, 2016 19:20_

Yes haven't been able to start but I'm hoping to start designing richer token management.

**Comment by mikedanese** [comment]
_From @pires on October 13, 2016 21:28_

@dgoodwin if you're good with it, I can implement this simple functionality and then when token mgmt becomes a thing I'm ok with replacing it.

**Comment by mikedanese** [comment]
_From @pires on October 14, 2016 13:58_

@luxas please assign to me.

**Comment by mikedanese** [comment]
_From @luxas on October 14, 2016 21:36_

FYI, you can fetch the token already this way:
```bash
kubectl -n kube-system get secret clusterinfo -o yaml | grep token-map | awk '{print $2}' | base64 -d | sed "s|{||g;s|}||g;s|:|.|g;s/\"//g;" | xargs echo
```

May be a bit hacky, but it works :smile:

**Comment by mikedanese** [comment]
_From @luxas on October 25, 2016 21:35_

@dgoodwin I guess we could come up with something like `kubeadm token list -n 1` for this

**Comment by mikedanese** [comment]
_From @dgoodwin on October 26, 2016 13:16_

Yeah token list is on my "list".

**Comment by mikedanese** [comment]
_From @pires on October 26, 2016 14:11_

@luxas then please re-assign to @dgoodwin.

**Comment by mikedanese** [comment]
_From @dgoodwin on November 17, 2016 19:38_

Fixed in #35805.

**Comment by luxas** [comment]
This is fixed in https://github.com/kubernetes/kubernetes/pull/41663, now it's possible to output the token again (and even modify it!)

**Comment by vglisin** [comment]
I got: 404 when I followed your link.

**Comment by vglisin** [comment]
so, the problem of getting token remains?

**Comment by 1605200517** [comment]
@vglisin  https://github.com/kubernetes/kubeadm/issues/519#issuecomment-343207374

**Comment by cfregly** [comment]
Check out https://stackoverflow.com/a/48691158/656810
