### ISSUE TITLE
"Master images" is out of date

### ISSUE THREAD

**Issue by lukemarsden** [kubernetes/kubeadm#260]
There's a table called "Master Images" at https://kubernetes.io/docs/getting-started-guides/kubeadm/ which is out of date, since it says 1.6.0 but clearly the latest version at time of writing installs 1.6.2.

**Comment by mikedanese** [comment]
Can we delete that? There's no way we will ever be able to keep that up to date.

**Comment by lukemarsden** [comment]
I think someone in China wanted to have the list so that they can sideload the images avoiding the great firewall.

**Comment by joelbirchler** [comment]
It's also useful information for anyone in a more restricted enterprise environment. I don't know that it needs to be tracked on the guide though. Is there a configuration file that lists the images and versions instead?

(Note: It's 1.6.3 now).

**Comment by luxas** [comment]
It should just be moved to the kubeadm reference page and specify things on a release branch level.
That is, leave it as `1.6.x`

Anyone wanna pick that up here?

**Comment by luxas** [comment]
@lukemarsden Can you take ownership of this?

**Comment by luxas** [comment]
Fixed with: https://github.com/kubernetes/kubernetes.github.io/pull/4018
