### ISSUE TITLE
BUG REPORT - kubelet cgroup driver: \"cgroupfs\" is different from docker cgroup driver: \"systemd\

### ISSUE THREAD

**Issue by gerardquinn43** [kubernetes/kubeadm#2605]
## Versions
**kubeadm version** (use `kubeadm version`): v1.22.3
**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.22.3
- **Cloud provider or hardware configuration**: VMWARE Fusion - Ubuntu iso
- **OS** :
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- **Kernel** (e.g. `uname -a`):Linux ubuntu 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Others**: DockerCE Version: 20.10.10

## What happened?
This had been reported before but I've tried them all but can't seem to get kubeadm init to recognise systemd cgroup. Docker is set to systemd but kublet is not. 

The error is 
**E1113 12:45:55.265410   14324 server.go:294] "Failed to run kubelet" err="failed to run Kubelet: misconfiguration: kubelet cgroup driver: \"cgroupfs\" is different from docker cgroup driver: \"systemd\""**

I've modified /etc/systemd/system/kubelet.service.d/10-kubeadm.conf and set additional arg - "KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"

I also added to /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1

When I check kubelet process it says systemd.
ps aux | grep kubelet
root        8612  5.1 14.4 1104300 287924 ?      Ssl  12:26   0:51 kube-apiserver --advertise-address=192.168.136.147 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-account-signing-key-file=/etc/kubernetes/pki/sa.key --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
root       11295  2.1  5.0 1786020 100972 ?      Ssl  12:33   0:12 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --cgroup-driver=systemd
root       13705  0.0  0.0  17672   724 pts/0    S+   12:43   0:00 grep --color=auto kubelet

## What you expected to happen?
I expect kubelet to start without this error

## How to reproduce it (as minimally and precisely as possible)?
> kubeadm reset
> kubeadm init --config kubeadm-config.yaml 
> kubelet (error occurs in the output)

kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.22.3
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd

## Anything else we need to know?
I don't think so.

**Comment by neolit123** [comment]
following the guide here works for me:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

this works as config:
```
# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.21.0
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
```

and this in the docker config:
```
sudo mkdir /etc/docker
cat <<EOF | sudo tee /etc/docker/daemon.json
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF
```

but instead of using docker it might be a better idea to start with with containerd/crio because the built in docker support is being removed in the kubelet.

i don't think there is a bug here, so please use the support channels:
/support
for more questions please

**Comment by zziawan** [comment]
i have the same issue, even the https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/ not working for me.  ubuntu 20.04. can some one give a help ? thanks!
