### ISSUE TITLE
[Feedback] Deployment with HAproxy failed with official guide

### ISSUE THREAD

**Issue by Alceatraz** [kubernetes/kubeadm#2609]
Neither BUG or FEATURE, It's FEEDBACK

https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/high-availability I follow this guide and run into issue, As the guide's request I post an feedback here. 

## Versions

**kubeadm version** (use `kubeadm version`): 
```
kubeadm version: &version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:47:19Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**: VirtualBOX 6.1
- **OS** (e.g. from /etc/os-release): debain-11.1
- **Kernel** (e.g. `uname -a`): `Linux master-1 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux`

Not sure if this is related https://github.com/kubernetes/kubeadm/issues/2227

### 0: My server

master-1 10.188.180.241
master-2 10.188.180.242
master-3 10.188.180.243

worker-1 10.188.180.244
worker-2 10.188.180.245
worker-3 10.188.180.246

### 1: Setup keepalived

```text
global_defs {
	router_id KUBERNETES_SLB
}

vrrp_instance VI_1 {
	state MASTER
	priority 101
	interface enp0s3
	virtual_router_id 200
	authentication {
		auth_type PASS
		auth_pass 00000000
	}
	virtual_ipaddress {
		10.188.180.250/24
	}
}
```
This is working properly. VIP can transfer if server shutdown.

### 2: Setup HAProxy

```text
frontend k8s-apiserver
	bind *:8443
	mode tcp
	default_backend apiserver

backend apiserver
	mode tcp
	option ssl-hello-chk
	option httpchk GET /healthz
    http-check expect status 200
	balance roundrobin
		server master-1 10.188.180.241:6443 check 
		server master-2 10.188.180.242:6443 check
		server master-3 10.188.180.243:6443 check
```

This is working properly. But haproxy give me warning  — I didn't init the k8s yet.

### 3: Containerd for runtime

I want containerd as runtime so I need save the default config  
I'm using mirror images registry so I need changed containerd config  

```shell
containerd config default > /etc/containerd/config.toml
sed -i 's#k8s.gcr.io/pause#registry.aliyuncs.com/google_containers/pause#g' /etc/containerd/config.toml
```

kubeadm config images pull --kubernetes-version=1.22.4 --image-repository=registry.aliyuncs.com/google_containers

This is working fine, Images pulled.

### 4: Init the master of masters

```shell
kubeadm init \
--kubernetes-version=1.22.4 \
--pod-network-cidr=172.16.0.0/16 \
--cri-socket=/run/containerd/containerd.sock \
--image-repository=registry.aliyuncs.com/google_containers \
--upload-certs \
--control-plane-endpoint 10.188.180.250:8443
```

This also working fine, `Your Kubernetes control-plane has initialized successfully!`.

### 5: Now I get into trouble

- Wait about 3 mins
- Install CNI plugin 
- Join another master
- Join worker

Will cause the master kubelet crash

## What happened?

- Kubectl can't access api-server, Because 6443 not listening.
- Use htop see process will found everything restarting.
- kubelet logs become very wild. Many errors.
- kubectl (api-server) can back normal about 5~8 mins, And down after 30s.
- Restart server not working.

## What you expected to happen?

As the guide, Install CNI / join node shouldn't cause any problem.

## How to reproduce it (as minimally and precisely as possible)?

100% on my server, I try init cluster and restore vm about 20 times.

## Anything else we need to know?

Not yet

[kubelet-log.txt](https://github.com/kubernetes/kubeadm/files/7578927/kubelet-log.txt)

**Comment by neolit123** [comment]
> Wait about 3 mins
> Install CNI plugin
> Join another master
> Join worker
> Will cause the master kubelet crash

this sounds like a CNI / Container runtime bug and not an issue with kubeadm or the HA docs.

please try weavnet/calico/cilium for CNI.
containerd for CR.

> kubectl (api-server) can back normal about 5~8 mins, And down after 30s.

this might be an indication that the control plane machine is running out of RAM/CPU.
the min spec is a modern 2core CPU with 1.5 GB of RAM.

for more questions please use the support channels linked bellow.
you can also reference your summary here.

/support

**Comment by Alceatraz** [comment]
> > Wait about 3 mins
> > Install CNI plugin
> > Join another master
> > Join worker
> > Will cause the master kubelet crash
> 
> this sounds like a CNI / Container runtime bug and not an issue with kubeadm or the HA docs.
> 
> please try weavnet/calico/cilium for CNI. containerd for CR.
> 
> > kubectl (api-server) can back normal about 5~8 mins, And down after 30s.
> 
> this might be an indication that the control plane machine is running out of RAM/CPU. the min spec is a modern 2core CPU with 1.5 GB of RAM.
> 
> for more questions please use the support channels linked bellow. you can also reference your summary here.
> 
> /support

I'm using containerd and calico and server run with 16c32t 64g for each vm and host not overload. I mean even if let it be there after kube init, do nothing for 3~5min will cause into crash loop, join or install cni just make the crush faster . I was worry about mirror but I try this with an vultr server still same issue .
Anyway I will post this in slack.
Thanks

**Comment by neolit123** [comment]
Its important to also look at the logs of the failed containers.

If you think there is bug in kubelet or the kube-* components you can log
an issue in the kubernetes/kubernetes repository.

I would also try a different CNI plugin.

**Comment by Alceatraz** [comment]
> Its important to also look at the logs of the failed containers. If you think there is bug in kubelet or the kube-* components you can log an issue in the kubernetes/kubernetes repository. I would also try a different CNI plugin.

I try CentOS 7.9 instead Debian 11.1, All exception gone and all problem solved.
Cluster working proper. Well. Just let you know that :)

**Comment by neolit123** [comment]
Kubeadm supports all Linux distros that are somewhat standard and have
systemd. I have seen Debian users so not sure what the problem was. CentOS
and Ubuntu are more popular choices.
