### ISSUE TITLE
kubeadm init stage kubelet-check got error with version v1.18.9

### ISSUE THREAD

**Issue by totemofwolf** [kubernetes/kubeadm#2610]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:54:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

- **Kubernetes version** (use `kubectl version`): v1.18.9
- **Cloud provider or hardware configuration**: aws ec2
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`): Linux vm-master 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

```
kubeadm init --image-repository registry.aliyuncs.com/google_containers   --kubernetes-version v1.18.9 --apiserver-advertise-address=0.0.0.0 --service-cidr=10.24.0.0/20 --pod-network-cidr=10.244.0.0/16

got output:

[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: i/o timeout.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: i/o timeout.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: i/o timeout.




	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in docker:
		- 'docker ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'docker logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

```

```
# curl -sSL http://localhost:10248/healthz -m2
curl: (28) Connection timed out after 2001 milliseconds
```

AND i must mannual do `iptables -I INPUT -p tcp --dport 10248 -s 127.0.0.1 -j ACCEPT` got works....

```
# curl -sSL http://localhost:10248/healthz -m2
ok
```

## How to reproduce it (as minimally and precisely as possible)?
kubeadm init --image-repository registry.aliyuncs.com/google_containers   --kubernetes-version v1.18.9 --apiserver-advertise-address=0.0.0.0 --service-cidr=10.24.0.0/20 --pod-network-cidr=10.244.0.0/16

## Anything else we need to know?
-

**Comment by neolit123** [comment]
Versions < 1.20 are no longer in support.
For new clusters we recomnend the latest stable.

This seems like the kubelet is not running so you have to look at the
kubelet logs. Check the links below.

/support
