### ISSUE TITLE
Add to Documentation: Reschedule / Rebalance core-dns pods on clusters with more than 1 node

### ISSUE THREAD

**Issue by zenhighzer** [kubernetes/kubeadm#2615]
Hi there, 
I just fresh-started with k8s / kubeadm

I installed a 6 node-cluster with kubeadm (3 x cp, 3 x worker) 

Two core-dns-pod are running on first master node, same like: https://github.com/kubernetes/kubeadm/issues/1657

I just wonder why you dont mention in a single phrase like "if you install a cluster with more than one node, please reschedule your core-dns pods with "kubectl -n kube-system rollout restart deployment coredns" in the documentation on https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

I think this would make fresh users´ life easier. I really scratched my head to understand what was going on after i did some fail-over-tests with the first master-node. :-)

BR
Zen

**Comment by neolit123** [comment]
hi, kubeadm adds coredns after only the first node is available and it is not that simple to tell the deployment to auto spread once more nodes are available.
e.g. see https://github.com/kubernetes/kubernetes/pull/105865

i agree that this is something good to mention in the documentation
PRs welcome.

/kind documentation
/help
/good-first-issue
/area coredns
