### ISSUE TITLE
POST timeout to api-server when init kubernet cluster witth kubeadm

### ISSUE THREAD

**Issue by vupv** [kubernetes/kubeadm#2616]
When I provision a Kubernetes cluster, I always see that all the POST request sent to API is 10s. How can I increase this value because sometimes 10s are not enough and get a timeout error?

Below are some examples, I see when init.

POST https://192.168.1.88:6443/api/v1/namespaces/kube-system/configmaps?timeout=10s 201 Created in 552 milliseconds

POST https://192.168.1.88:6443/api/v1/namespaces/kube-system/serviceaccounts?timeout=10s 201 Created in 302 milliseconds

POST https://192.168.1.88:6443/apis/rbac.authorization.k8s.io/v1/namespaces/kube-system/rolebindings?timeout=10s 201 Created in 1186 milliseconds POST https://192.168.1.88:6443/api/v1/namespaces/kube-system/configmaps?timeout=10s 201 Created in 552 milliseconds

**Comment by vupv** [comment]
I1130 21:46:56.739550  201036 round_trippers.go:460] Response Headers:
Post "https://192.168.1.88:6443/apis/apps/v1/namespaces/kube-system/daemonsets?timeout=10s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
unable to create daemonset

**Comment by vupv** [comment]
I1130 21:53:22.197854  202547 round_trippers.go:460] Response Headers:
Post "https://192.168.1.88:6443/api/v1/namespaces/kube-public/configmaps?timeout=10s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
unable to create ConfigMap

**Comment by neolit123** [comment]
> When I provision a Kubernetes cluster, I always see that all the POST request sent to API is 10s. How can I increase this value because sometimes 10s are not enough and get a timeout error?

10s is a hardcoded value. if the connection requires more than 10s then something is really wrong with this cluster initialization. kubeadm tries to connect to the apiserver on the local machine possibly through the LB (control-plane endpoint) so maybe the LB is delaying the traffic.
you should try to resolve these connection problems instead of increasing this timeout.

for future questions please use the support forums in the (see the bot links below)

/support

**Comment by jscottsf** [comment]
Having the same issue. Restarting the kubelet happens, it actually starts fine, but the commands timeout. Probably just need 1 or 2 more seconds.
