### ISSUE TITLE
kubeadm init fails with version 1.23

### ISSUE THREAD

**Issue by damoon** [kubernetes/kubeadm#2623]
## What keywords did you search in kubeadm issues before filing this one?
config init patches

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:15:11Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?`

- **Cloud provider or hardware configuration**:
`hetzner bare metal AX61-NVMe`

- **OS** (e.g. from /etc/os-release):
`flatcar 2983.2.1`

- **Kernel** (e.g. `uname -a`):
`Linux nautilus01 5.10.80-flatcar #1 SMP Fri Nov 19 19:28:59 -00 2021 x86_64 AMD Ryzen 9 3900 12-Core Processor AuthenticAMD GNU/Linux`

- **Others**:

## What happened?
updated from 1.22 to 1.23.
this required the command to change from `kubeadm init --experimental-patches %s --config %s` to `kubeadm init --patches %s --config %s`.
the patches are needed to apply resource limits to the control plane.
Running the new command with 1.23 shows the error `can not mix '--config' with arguments [patches]` and aborts

## What you expected to happen?
init a new cluster

## How to reproduce it (as minimally and precisely as possible)?
run `kubeadm init --patches %s --config %s`

**Comment by neolit123** [comment]
Hi, this is mentioned in the release notes

> Kubeadm: remove the deprecated flag --experimental-patches for the init|join|upgrade commands. The flag --patches is no longer allowed in a mixture with the flag --config. Please use the kubeadm configuration for setting patches for a node using {Init|Join}Configuration.patches.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#no-really-you-must-read-this-before-you-upgrade

https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches

Not allowing the mixture is a standard practice in kubeadm and you should use the config. The upgrade command does not have a config yet and  --patches should be used there.

/kind support

**Comment by damoon** [comment]
thanks i for the hint.
i failed to find the new location to set the config path.

i close this now.
thanks again.
