### ISSUE TITLE
handle kubelet skew with and without dockershim support

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2626]
dockershim was removed from the kubelet in early 1.24 development. related flags are also being removed.

history here:
https://github.com/kubernetes/kubeadm/issues/1412

a few tasks need to be performed to adapt kubeadm for 1.24 and later.

1.24:
- [x] kubeadm currently has flags specific to dockershim independent of the kubelet version. these flags must be made specific for kubelet <1.24.
https://github.com/kubernetes/kubernetes/pull/106973
- [x] change autodetection to not mix containerd and docker sockets for docker 18.xx+. use `unix:///var/run/cri-dockerd.sock` as the default docker socket?
https://github.com/kubernetes/kubernetes/pull/107317
- [x] k/website kubeadm docs changes to reflect the dockershim removal:
https://github.com/kubernetes/website/pull/31309

1.25:
in kubeadm 1.25 kubelet 1.23 will go out of support, because kubeadm 1.25 would only support kubelet 1.25 and 1.24:
- [x] remove handling of skew for <1.23 kublets (see PR above), fix TODOs that mention this issue.
https://github.com/kubernetes/kubernetes/pull/110022
- [x] fix [failing kubelet 1.23 skew test](https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-23-on-latest) after the removal of `--container-runtime=remote`
https://github.com/kubernetes/kubernetes/pull/110047

1.26
- [x] remove --container-runtime=remote for init/join/upgrade
https://github.com/kubernetes/kubernetes/pull/112000

1.27
- [x] cleanup workaround in https://github.com/kubernetes/kubernetes/pull/112000
TODO
- [ ] cleanup remaining flags `pod-infra-container-image` .. ?
https://github.com/kubernetes/kubernetes/issues/106893

**Comment by neolit123** [comment]
1.24 PR is here:
https://github.com/kubernetes/kubernetes/pull/106973

**Comment by pacoxu** [comment]
I may take `change autodetection to not mix containerd and docker sockets for docker 18.xx+` task.
/assign

**Comment by neolit123** [comment]
I will send PRs for all the 1.24 changes as these are a bit tricky. But
reviews will be appreciated.

**Comment by neolit123** [comment]
second PR that changes the kubeadm defaults / auto detection is here:
https://github.com/kubernetes/kubernetes/pull/107317

**Comment by neolit123** [comment]
tasks are completed for 1.24, moving to 1.25 milestone.

**Comment by neolit123** [comment]
1.25 cleanup PR is here:
https://github.com/kubernetes/kubernetes/pull/110022

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/issues/106893#issuecomment-1465875895
`pod-infra-container-image` removal will be postponed to v1.28 or later.

**Comment by neolit123** [comment]
so, one issue is that since we now support kubelet skew of N-3, we can't remove the flag --pod-infra-container-image in kubeadm deployments until N-3 kubelet goes out of support.

- we can do this - stop applying the flag for new clusters created with kubelet >= 1.29
- but we cannot do this - remove the flag from systemd drop-ins that kubeadm uses to start the kubelet. kubelet on workers is upgraded out of band and we don't know what version the user will choose.
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes/
if they choose 1.29 we could remove the flag from the systemd file, but else we don't know if it's OK to remove the flag.

up until now we waited 2 releases before removing a flag, because the skew was N-1. but N-3 changes this.
so we either need to modify `kubeadm upgrade` to wait for kubelet upgrade, check the version and then perform action foo (behavior change) or wait ask the kubelet maintainers to delay the removal of --pod-infra-container-image, until 1.29 goes out of support (if my math is correct).

@liggitt this is an example of the complexity at hand for N-3.
cc @SataQiu @pacoxu @afbjorklund

**Comment by liggitt** [comment]
> * kubelet on workers is upgraded out of band and we don't know what version the user will choose.
>   https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes/
>   if they choose 1.29 we could remove the flag from the systemd file, but if the kubelet is older we cannot.

having some way to indicate the version kubeadm should make a config for seems like it could help simplify this

**Comment by neolit123** [comment]
> > * kubelet on workers is upgraded out of band and we don't know what version the user will choose.
> >   https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes/
> >   if they choose 1.29 we could remove the flag from the systemd file, but if the kubelet is older we cannot.
> 
> having some way to indicate the version kubeadm should make a config for seems like it could help simplify this

agreed, and seems like an oversight that kubeadm upgrade is not wrapping this kubelet upgrade and checking what version if kubelet the user installs, and then perform some action.

one quick fix might be to call "kubeadm upgrade ..." another time after the user upgrades a kubelet on a node. for control plane nodes this will be a bit slow.

what i don't like is the deprecation progression of the --pod-infra-container-image flag in the kubelet and i think it is messy.

- the flag was needed to pin the pause image and prevent GC
- in 1.29 the flag is no-op-ed
- in 1.30 it is planned for removal

that doesn't seem right, and will force all tools on top of kubelet to have version branching around the k8s support skew. if they care about the GC problem, that is..

https://github.com/kubernetes/kubernetes/pull/118544/files#r1359721938

**Comment by liggitt** [comment]
> what i don't like is the deprecation progression of the --pod-infra-container-image flag in the kubelet and i think it is messy.
> 
> * the flag was needed to pin the pause image and prevent GC
> * in 1.29 the flag is no-op-ed
> * in 1.30 it is planned for removal

Making it easy for tools to keep setting the no-op flag until the release where it was needed hits EOL would be nice, especially if it is ~zero cost for sig-node. I'd ask them about that.

**Comment by carlory** [comment]
Hi @liggitt any update about it? 

kubeadm and scripts are still using this flag in 1.29. Can we remove this flag from kubelet in 1.30?
 
```
if cleanFlagSet.Changed("pod-infra-container-image") {
klog.InfoS("--pod-infra-container-image will not be pruned by the image garbage collector in kubelet and should also be set in the remote runtime")
_ = cmd.Flags().MarkDeprecated("pod-infra-container-image", "--pod-infra-container-image will be removed in 1.30. Image garbage collector will get sandbox image information from CRI.")
}
``` 

Or update the deprecated message with a different release?

**Comment by liggitt** [comment]
In what release can we count on CRI having the info required so `--pod-infra-container-image` no longer needs to be passed?

**Comment by liggitt** [comment]
> in 1.29 the flag is no-op-ed

If the flag is no-op and cheap for node to keep around, I'd ask if they can keep it until 1.29 is the oldest release.

Separately, `kubeadm` knowing what kubelet version it is generating a config for seem like a really important gap to close, and would let kubeadm stop setting this flag for >=1.29 kubelets.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/issues/106893#issuecomment-1867197876 some updates about the pinned image feature in containerd side:

> From containerd side, containerd v1.7.3 and [containerd 1.6.22](https://github.com/containerd/containerd/releases/tag/v1.6.22)  includes the support of pinned image: 
> - Pinned image support (https://github.com/containerd/containerd/pull/8720)
> 
> - [1.6.25](https://github.com/containerd/containerd/releases/tag/v1.6.25)+ and [containerd 1.7.10](https://github.com/containerd/containerd/releases/tag/v1.7.10)+ fixed a bug **cri: fix using the pinned label to pin image** (https://github.com/containerd/containerd/pull/9381). 
> 
> However, there are still two bugfix pull requests in progress:
> - [ ] https://github.com/containerd/containerd/pull/9460
> - [ ] https://github.com/containerd/containerd/pull/8866

**Comment by neolit123** [comment]
> cleanup remaining flags pod-infra-container-image .. ?
> https://github.com/kubernetes/kubernetes/issues/106893

scoped this item in a dedicated ticket:
- https://github.com/kubernetes/kubeadm/issues/3108

all other AIs are done here.
