### ISSUE TITLE
kubeadm kubeconfig user command fails with invalid configuration

### ISSUE THREAD

**Issue by sitilge** [kubernetes/kubeadm#2629]
## Versions
```
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:39:51Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: `Hetzner cloud, 2vCPU, 4GB RAM`
- **OS** (e.g. from /etc/os-release):
`
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
`
- **Kernel** (e.g. `uname -a`): ```Linux master-1 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```
- **Container runtime (CRI)** (e.g. containerd, cri-o): `containerd`
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): `cilium`

## What happened?
Was following the kubeadm docs, setting up a new control plane. Then `kubeadm kubeconfig user --client-name=abc --config=/etc/kubernetes/admin.conf --v=5` fails with the logs provided below. Basically, it says: `invalid configuration for GroupVersionKind /v1, Kind=Config: kind and apiVersion is mandatory information that must be specified`. The kubeadm config file is as follows:

```
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.23.0
clusterName: xx
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
kubernetesVersion: v1.23.0
```

## What you expected to happen?
The previous command to work.

## How to reproduce it (as minimally and precisely as possible)?
Initialize a new control-plane node, then run the command above.

## Anything else we need to know?
```
root@master-1:~# kubeadm kubeconfig user --client-name=abc --config=/etc/kubernetes/admin.conf --v=5
I1218 15:15:22.095073   14488 initconfiguration.go:248] loading configuration from "/etc/kubernetes/admin.conf"
invalid configuration for GroupVersionKind /v1, Kind=Config: kind and apiVersion is mandatory information that must be specified
k8s.io/kubernetes/cmd/kubeadm/app/util.SplitYAMLDocuments
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/marshal.go:101
k8s.io/kubernetes/cmd/kubeadm/app/util/config.BytesToInitConfiguration
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/config/initconfiguration.go:278
k8s.io/kubernetes/cmd/kubeadm/app/util/config.LoadInitConfigurationFromFile
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/config/initconfiguration.go:255
k8s.io/kubernetes/cmd/kubeadm/app/util/config.LoadOrDefaultInitConfiguration
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/config/initconfiguration.go:267
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdUserKubeConfig.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/kubeconfig.go:86
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1581
```

Seems like related to not being able to split Yaml documents?

**Comment by neolit123** [comment]
/kind support

> --config=/etc/kubernetes/admin.conf

You seem to be passing a kubeconfig file (admin.conf), and not a kubeadm
config file.

**Comment by sitilge** [comment]
@neolit123 you're right, don't know what I was thinking.

**Comment by SataQiu** [comment]
as per above response
/close
