### ISSUE TITLE
Verify apt-get and yum package managers in e2e tests

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubeadm#263]
In https://github.com/kubernetes/kubeadm/issues/250#issuecomment-296178197, one user suggested that the e2e tests should verify kubeadm works using other linux distro package managers:

> So, right now, our end-to-end tests build a fresh set of .debs as part of the CI process, and do dpkg -i *.deb to install them. It sounds like part of what you're suggesting is to at least have end-to-end tests that instead do apt-get install kubeadm to test the latest stable/unstable offerings, like users actually do while installing (and likely the equivalent yum commands for .rpms).

It doesn't seem that our e2e tests are catching regressions at the package level: 

> most ppl follow the install doc, using apt-get or rpm's. This was a huge problem with the release (and still is, 1.6.2 is released, but no packages in the repo's, although one older release is, it should be all), the old, known working packages were not there. So ppl could not go back to what they knew was working

**Comment by timothysc** [comment]
I'd like to make a -testing repo so we can make a merge blocking job.

**Comment by luxas** [comment]
@jamiehannaford @timothysc @pipejakob I'm moving this issue to the v1.9 milestone as we didn't have enough resources to do this in v1.8 (if nobody volunteers  ~now)

**Comment by luxas** [comment]
At least, this is not _blocking_ the v1.8 release IMO

**Comment by luxas** [comment]
@jamiehannaford this is working for debs now and rpms still to be done, right?

**Comment by jamiehannaford** [comment]
@luxas Yep. I'll try to create a script for rpms next week

**Comment by luxas** [comment]
ping @jamiehannaford on that script or I'll move it out of the v1.9 milestone. Either works for me if you're very busy right now

**Comment by luxas** [comment]
Most of this is done, so we're nearly good to go. This is not blocking v1.9
Last piece is https://github.com/kubernetes/test-infra/pull/5738

**Comment by timothysc** [comment]
Until bazel is the default, this is unlikely to happen, punting out of this cycle.

**Comment by luxas** [comment]
https://github.com/kubernetes/kubeadm/pull/803 together with https://github.com/kubernetes/test-infra/pull/8020 fixed this.

https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-kubernetes-e2e-packages-pushed shows the results daily. Example output: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-kubernetes-e2e-packages-pushed/1/build-log.txt
