### ISSUE TITLE
coredns CrashLoopBackOff when I added a new node on k8s cluster

### ISSUE THREAD

**Issue by xyc2019** [kubernetes/kubeadm#2631]
The coredns pod on new node is not running normally.
OS version:Ubuntu 16.04.2 Kubeadm version: v1.12.4

>coredns status:
coredns-788d98cc7b-bv75r                  0/1     CrashLoopBackOff   393        26h

> Error log of the coredns pod:
E0106 06:45:17.843924       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:318: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
E0106 06:45:17.844043       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:311: Failed to list *v1.Service: Get https://10.233.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout
E0106 06:45:17.844709       1 reflector.go:205] github.com/coredns/coredns/plugin/kubernetes/controller.go:313: Failed to list *v1.Endpoints: Get https://10.233.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: i/o timeout

> kubelet config of new node:
--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --cluster-dns=10.233.0.3 --cluster-domain=cluster.local --resolv-conf=/etc/resolv.conf --kube-reserved cpu=100m,memory=256M --node-labels=node-role.kubernetes.io/node=

> cluster config:
apiServerCertSANs:
- kubernetes
- kubernetes.default
- kubernetes.default.svc
- kubernetes.default.svc.cluster.local
- 10.233.0.1
- localhost
- 127.0.0.1
- scarlet191
- scarlet192
- scarlet193
- 192.168.248.191
- 192.168.248.192
- 192.168.248.193
apiServerExtraArgs:
  allow-privileged: "true"
  apiserver-count: "3"
  authorization-mode: Node,RBAC
  bind-address: 0.0.0.0
  endpoint-reconciler-type: lease
  insecure-port: "0"
  kubelet-preferred-address-types: InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP
  runtime-config: admissionregistration.k8s.io/v1alpha1
  service-node-port-range: 30000-32767
  storage-backend: etcd3
apiVersion: kubeadm.k8s.io/v1alpha3
auditPolicy:
  logDir: /var/log/kubernetes/audit
  logMaxAge: 2
  path: ""
certificatesDir: /etc/kubernetes/ssl
clusterName: cluster.local
controlPlaneEndpoint: 192.168.248.192:6443
controllerManagerExtraArgs:
  node-cidr-mask-size: "24"
  node-monitor-grace-period: 40s
  node-monitor-period: 5s
  pod-eviction-timeout: 5m0s
etcd:
  external:
    caFile: /etc/kubernetes/ssl/etcd/ca.pem
    certFile: /etc/kubernetes/ssl/etcd/node-scarlet192.pem
    endpoints:
    - https://192.168.248.191:2379
    - https://192.168.248.192:2379
    - https://192.168.248.193:2379
    keyFile: /etc/kubernetes/ssl/etcd/node-scarlet192-key.pem
imageRepository: gcr.io/google-containers
kind: ClusterConfiguration
kubernetesVersion: v1.12.4
networking:
  dnsDomain: cluster.local
  podSubnet: 10.233.64.0/18
  serviceSubnet: 10.233.0.0/18

**Comment by neolit123** [comment]
That doesn't seem like a kubeadm bug per se.
>  i/o timeout

Might be due to slow connection to the server.

/support
