### ISSUE TITLE
warnings printed to stdout instead of stderr

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubeadm#2632]
## What keywords did you search in kubeadm issues before filing this one?

`stderr`

>If you have found any duplicates, you should instead reply there and close this page.
>
>If you have not found any duplicates, delete this section and continue on.

There's some close-ish issues but I don't see this specifically.

https://github.com/kubernetes/kubeadm/issues/494 which is rather old mentions it I think but currently the most recent note seems to be:

> we need to be clear that the machine readable output is a much desired, but a secondary use case.

That's fair, but I think just moving warnings to stderr would go a long way, and some commands are necessarily meant for more "machine" purposes. I got here from `kubeadm config migrate` which *should* produce _only_ valid updated yaml in the output or else it's unnecessarily difficult to use the output. Currently it prints warning(s) to stdout along with the yaml.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

/kind bug

## Versions

**kubeadm version** (use `kubeadm version`): `kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2022-01-06T22:13:50Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2022-01-06T22:13:50Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: KIND
- **OS** (e.g. from /etc/os-release): Linux
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?

Warnings are printed to stdout when using `kubeadm config migrate --old=/kind/kubeadm.conf`.

## What you expected to happen?

Warnings (and other human readable diagnostics) should be printed to stderr while program output (the updated configuration) should be printed to stderr, so the updated yaml can be e.g. redirected to a file or captured by a program.

Printing them both to the same handle makes even trivial usage like `kubeadm config migrate --old=/kind/kubeadm.conf >/kind/migrated.conf` malfunction (the yaml is invalid due to the warning log).

**NOTE**: KIND does *not* need this, I was simply comparing the converted configuration to updated config generated by kind with a new template. I want to help the ecosystem though and it seems like a straightforward fix, however I discovered that `fmt.Printf("[phase] WARNING ...")` is used widely throughout kubeadm currently.

## How to reproduce it (as minimally and precisely as possible)?

https://github.com/kubernetes/kubernetes/blame/c7d57a01b7291c19d3fdd51fd1cccff5dd4787f9/cmd/kubeadm/app/util/config/initconfiguration.go#L331

## Anything else we need to know?

Happy to patch this particular one or work on a broader patch to fix these. I think we can pretty trivially just swap `fmt.Printf(` => `fmt.Fprintf(os.Stderr, ` in most locations where the output is clearly intended for a human. However I understand that there is some history here, so I've refrained from submitting any patches for now and filed this issue first instead ...

**Comment by neolit123** [comment]
+1 for warnings to go on stderr.

**Comment by SataQiu** [comment]
+1 for klog.Warning

**Comment by BenTheElder** [comment]
Thank you!!!
