### ISSUE TITLE
kubeadm join  404 Not Found Node

### ISSUE THREAD

**Issue by zhangxiaoyus** [kubernetes/kubeadm#2635]
I'm a beginner, When I input the following command, I don't know what caused this problem
Here are the question tips

preflight] Running pre-flight checks
I0110 18:52:19.751485   73630 preflight.go:92] [preflight] Running general checks
I0110 18:52:19.751530   73630 checks.go:283] validating the existence of file /etc/kubernetes/kubelet.conf
I0110 18:52:19.751566   73630 checks.go:283] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0110 18:52:19.751586   73630 checks.go:107] validating the container runtime
I0110 18:52:19.791107   73630 checks.go:133] validating if the "docker" service is enabled and active
I0110 18:52:19.807325   73630 checks.go:332] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0110 18:52:19.807434   73630 checks.go:332] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0110 18:52:19.807484   73630 checks.go:654] validating whether swap is enabled or not
I0110 18:52:19.807524   73630 checks.go:373] validating the presence of executable conntrack
I0110 18:52:19.807537   73630 checks.go:373] validating the presence of executable ip
I0110 18:52:19.807573   73630 checks.go:373] validating the presence of executable iptables
I0110 18:52:19.807597   73630 checks.go:373] validating the presence of executable mount
I0110 18:52:19.807607   73630 checks.go:373] validating the presence of executable nsenter
I0110 18:52:19.807628   73630 checks.go:373] validating the presence of executable ebtables
I0110 18:52:19.807657   73630 checks.go:373] validating the presence of executable ethtool
I0110 18:52:19.807665   73630 checks.go:373] validating the presence of executable socat
I0110 18:52:19.807673   73630 checks.go:373] validating the presence of executable tc
I0110 18:52:19.807680   73630 checks.go:373] validating the presence of executable touch
I0110 18:52:19.807710   73630 checks.go:521] running all checks
I0110 18:52:19.852601   73630 checks.go:404] checking whether the given node name is valid and reachable using net.LookupHost
I0110 18:52:19.852717   73630 checks.go:620] validating kubelet version
I0110 18:52:19.908056   73630 checks.go:133] validating if the "kubelet" service is enabled and active
I0110 18:52:19.925216   73630 checks.go:206] validating availability of port 10250
I0110 18:52:19.925402   73630 checks.go:283] validating the existence of file /etc/kubernetes/pki/ca.crt
I0110 18:52:19.925428   73630 checks.go:433] validating if the connectivity type is via proxy or direct
I0110 18:52:19.925625   73630 join.go:530] [preflight] Discovering cluster-info
I0110 18:52:19.925677   73630 token.go:80] [discovery] Created cluster-info discovery client, requesting info from "192.168.58.154:6443"
I0110 18:52:19.939272   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 13 milliseconds
I0110 18:52:19.939901   73630 token.go:118] [discovery] Requesting info from "192.168.58.154:6443" again to validate TLS against the pinned public key
I0110 18:52:19.944890   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 4 milliseconds
I0110 18:52:19.945172   73630 token.go:135] [discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "192.168.58.154:6443"
I0110 18:52:19.945239   73630 discovery.go:52] [discovery] Using provided TLSBootstrapToken as authentication credentials for the join process
I0110 18:52:19.945265   73630 join.go:544] [preflight] Fetching init configuration
I0110 18:52:19.945286   73630 join.go:590] [preflight] Retrieving KubeConfig objects
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
I0110 18:52:19.951400   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s 200 OK in 5 milliseconds
I0110 18:52:19.953310   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-system/configmaps/kube-proxy?timeout=10s 200 OK in 1 milliseconds
I0110 18:52:19.954101   73630 kubelet.go:91] attempting to download the KubeletConfiguration from the new format location (UnversionedKubeletConfigMap=true)
I0110 18:52:19.955189   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config?timeout=10s 403 Forbidden in 0 milliseconds
I0110 18:52:19.969587   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config?timeout=10s 403 Forbidden in 1 milliseconds
I0110 18:52:20.023877   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config?timeout=10s 403 Forbidden in 1 milliseconds
I0110 18:52:20.287161   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config?timeout=10s 403 Forbidden in 1 milliseconds
I0110 18:52:20.287287   73630 kubelet.go:94] attempting to download the KubeletConfiguration from the DEPRECATED location (UnversionedKubeletConfigMap=false)
I0110 18:52:20.288854   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/namespaces/kube-system/configmaps/kubelet-config-1.23?timeout=10s 200 OK in 1 milliseconds
I0110 18:52:20.289955   73630 interface.go:432] Looking for default routes with IPv4 addresses
I0110 18:52:20.289994   73630 interface.go:437] Default route transits interface "ens33"
I0110 18:52:20.290290   73630 interface.go:209] Interface ens33 is up
I0110 18:52:20.290348   73630 interface.go:257] Interface "ens33" has 2 addresses :[192.168.58.153/24 fe80::79c9:c785:a8dc:4d59/64].
I0110 18:52:20.290377   73630 interface.go:224] Checking addr  192.168.58.153/24.
I0110 18:52:20.290399   73630 interface.go:231] IP found 192.168.58.153
I0110 18:52:20.290419   73630 interface.go:263] Found valid IPv4 address 192.168.58.153 for interface "ens33".
I0110 18:52:20.290440   73630 interface.go:443] Found active IP 192.168.58.153 
W0110 18:52:20.294870   73630 utils.go:69] The recommended value for "resolvConf" in "KubeletConfiguration" is: /run/systemd/resolve/resolv.conf; the provided value is: /run/systemd/resolve/resolv.conf
I0110 18:52:20.294959   73630 preflight.go:103] [preflight] Running configuration dependant checks
I0110 18:52:20.294985   73630 controlplaneprepare.go:220] [download-certs] Skipping certs download
I0110 18:52:20.295022   73630 kubelet.go:119] [kubelet-start] writing bootstrap kubelet config file at /etc/kubernetes/bootstrap-kubelet.conf
I0110 18:52:20.295515   73630 kubelet.go:134] [kubelet-start] writing CA certificate at /etc/kubernetes/pki/ca.crt
I0110 18:52:20.295760   73630 loader.go:372] Config loaded from file:  /etc/kubernetes/bootstrap-kubelet.conf
I0110 18:52:20.296071   73630 kubelet.go:155] [kubelet-start] Checking for an existing Node in the cluster with name "k8snode1" and status "Ready"
I0110 18:52:20.297962   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/nodes/k8snode1?timeout=10s 404 Not Found in 1 milliseconds
I0110 18:52:20.298603   73630 kubelet.go:170] [kubelet-start] Stopping the kubelet
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
I0110 18:52:20.321520   73630 flags.go:109] setting kubelet hostname-override to "k8snode1"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
I0110 18:52:25.499256   73630 loader.go:372] Config loaded from file:  /etc/kubernetes/kubelet.conf
I0110 18:52:25.499849   73630 cert_rotation.go:137] Starting client certificate rotation controller
I0110 18:52:25.500096   73630 loader.go:372] Config loaded from file:  /etc/kubernetes/kubelet.conf
I0110 18:52:25.500385   73630 kubelet.go:218] [kubelet-start] preserving the crisocket information for the node
I0110 18:52:25.500394   73630 patchnode.go:31] [patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "k8snode1" as an annotation
I0110 18:52:26.010365   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/nodes/k8snode1?timeout=10s 404 Not Found in 9 milliseconds
I0110 18:52:26.504630   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/nodes/k8snode1?timeout=10s 404 Not Found in 2 milliseconds
I0110 18:52:27.005680   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/nodes/k8snode1?timeout=10s 404 Not Found in 4 milliseconds
I0110 18:52:27.504441   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/nodes/k8snode1?timeout=10s 404 Not Found in 3 milliseconds
I0110 18:52:28.003295   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/nodes/k8snode1?timeout=10s 404 Not Found in 2 milliseconds
I0110 18:52:28.506063   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/nodes/k8snode1?timeout=10s 404 Not Found in 4 milliseconds
I0110 18:52:29.003741   73630 round_trippers.go:553] GET https://192.168.58.154:6443/api/v1/nodes/k8snode1?timeout=10s 404 Not Found in 2 milliseconds

**Comment by neolit123** [comment]
Hello, try getting help in the support forums instead.

When this happens it means the kubelet on the host cannot create the Node
object. I.e. a k8s Node that can normally be seen with 'kubectl get nodes'.
Check the kubelet logs for errors.

/support
