### ISSUE TITLE
HA stacked control planes in kubernetes

### ISSUE THREAD

**Issue by RogainaAli** [kubernetes/kubeadm#2641]
I setup 3 HA stacked kubernetes control planes by kubeadm tool, how to Backup and recover etcd snapshot for each control plane?

load balancer IP : 192.168.22.132
master1 IP : 192.168.22.133
master2 IP : 192.168.22.134
master3 IP : 192.168.22.135
 before backup when running this command on each control plane ** it lists 3 etcd members** 
sudo ETCDCTL_API=3 /usr/local/bin/etcdctl member list --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key

but after restore each snapshot on each etcd control plane and running the previous command 
each control plane list its etcd member only and couldn't see other two members 

so how to backup and restore 3 etcd stacked control planes in kubernetes ?

**Comment by neolit123** [comment]
Perhaps the etcd members separated and and you may have to recreate the
cluster again. Not sure why that is happening exacly but its not a kubeadm
bug. Something disruptive happened during manual restore.

This is the page with restore docs:
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster

If you think something is missing there log a ticket in k/website.

To ask other users check the links from the bot below.

/support
