### ISSUE TITLE
kubeadmn problem how to solve

### ISSUE THREAD

**Issue by ashwan999** [kubernetes/kubeadm#2646]
The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.

**Comment by neolit123** [comment]
hi, you need to look at the kubelet logs.
here you might see some information:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

you can also ask on the links the bot will give below.

/support
