### ISSUE TITLE
RFE: Create a kubeadm man page

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#265]
We're missing a man page and TBH I think 

https://kubernetes.io/docs/admin/kubeadm/ 

should be just be a reference to it.  

/cc @kubernetes/sig-cluster-lifecycle-bugs

**Comment by luxas** [comment]
@timothysc Is the new title correct?

Are you envisioning to work on this for v1.8?
Maybe @fabriziopandini can work on these man pages in the meantime?

**Comment by jamiehannaford** [comment]
Would this just exist as a static doc? 

In the past I've written a [man page generator](https://github.com/rackspace/rack/blob/master/man.go), which would allow us to dynamically generate docs based off specific kubeadm commands as they exist in the codebase. WDYT?

**Comment by luxas** [comment]
I think it's possible to create a man page for kubeadm commands directly from cobra, cc @kubernetes/sig-cli-misc, right?
I think kubectl has that already.

Then we might want to add some more (custom) information as well, but I think that's the second, not primary task of this issue

**Comment by jamiehannaford** [comment]
Yeah, [you can](https://github.com/spf13/cobra/blob/f95d58bdf33e9ff7b9db528dee4966359d6bbe8d/doc/man_docs.md) @luxas, although I couldn't find any refs to it in the kubectl codebase. So if we go ahead with the cobra thing

1. where/when should the manpage be generated? The easiest option is adding it as a new command, so the user can generate locally. This wouldn't be hosted as docs though
2. if we did host as documentation, how would it be synced with flag changes? Also, how would we format it in markdown?

cc/ @chenopis Do we have manpages for any other k8s docs?

**Comment by chenopis** [comment]
Well, technically not manpages, but we do have autogenerated docs for [kubectl](https://kubernetes.io/docs/user-guide/kubectl-overview/) and the config references: [kubelet](https://kubernetes.io/docs/admin/kubelet/), [kube-apiserver](https://kubernetes.io/docs/admin/kube-apiserver/), [kube-control-manager](https://kubernetes.io/docs/admin/kube-controller-manager/), etc. Also, I think someone is working on one for kubefed.

**Comment by jamiehannaford** [comment]
Perhaps we should change the scope of this issue then to generating docs for kubeadm, similar to how kubectl et al. does it

**Comment by luxas** [comment]
@timothysc I assume this is not something you're gonna work on in the nearest future, right?
I'm kicking this out of v1.8

**Comment by fabriziopandini** [comment]
Call for review: improve kubeadm reference docs & generate kubeadm man pages (part of “better documentation” - priority 1 task for 1.9) 
Validate a possible approach, related trade-off and start addressing pending items
https://docs.google.com/document/d/1w22y-C1YD1mmqqETxrQrCLnJpzwttscanddgvfYceYY/edit?usp=sharing

**Comment by luxas** [comment]
@fabriziopandini Is this fixed with https://github.com/kubernetes/kubernetes/pull/54616?

**Comment by fabriziopandini** [comment]
@luxas no.
Reference doc and man pages are now generated, but not yet published on the respective targets.
There is still some work to be done here...

**Comment by luxas** [comment]
@fabriziopandini now made this a thing with the wonderful new docs: https://github.com/kubernetes/website/pull/6103
Thank you :tada:!!

We might consider bundling these with the debs/rpms as well, but that should be tracked in a new issue in that case
