### ISSUE TITLE
ETCD cluster install failed :- Error: failed to fetch endpoints from etcd cluster member list: context deadline exceeded

### ISSUE THREAD

**Issue by sanjaz10** [kubernetes/kubeadm#2651]
## What happened?

I tried to Set up a High Availability etcd Cluster with kubeadm.
I followed the official guide https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
after all the steps execute when i check cluster health its giving below error message 

[root@etcd-01 ~]# docker run --rm -it \
> --net host \
> -v /etc/kubernetes:/etc/kubernetes k8s.gcr.io/etcd:3.5.1-0 etcdctl \
> --cert /etc/kubernetes/pki/etcd/peer.crt \
> --key /etc/kubernetes/pki/etcd/peer.key \
> --cacert /etc/kubernetes/pki/etcd/ca.crt \
> --endpoints https://137.184.157.161:2379 endpoint health --cluster
{"level":"warn","ts":"2022-02-09T08:12:22.497Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00045e540/137.184.157.161:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 137.184.157.161:2379: connect: connection refused\""}
Error: failed to fetch endpoints from etcd cluster member list: context deadline exceeded

## What you expected to happen?
as per the official guide etcd cluster should be healthy state.

## How to reproduce it (as minimally and precisely as possible)?

You can follow the official guide with https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ 

## Versions

**kubeadm version** (use `v1.23.3`):

**Environment**:
- **Kubernetes version** (use `v1.23.3`):
- **Cloud provider or hardware configuration**:

Master Nodes -03 
Worker Nodes -03 
etcd -03 
HA load balancer -01 

Digital Ocean cloud 
all instance - 4 HB Ram ,2 CPU ,80 GB disk 

- **OS** (e.g. from /etc/os-release):
CentOS 8

[root@etcd-01 ~]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

- **Kernel** (e.g. `uname -a`):

[root@etcd-01 ~]# uname -a
Linux etcd-01 4.18.0-277.el8.x86_64 #1 SMP Wed Feb 3 20:35:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- **Container runtime (CRI)** (e.g. containerd, cri-o):
Docker

- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
wavenet 
- **Others**:

**Comment by neolit123** [comment]
hi, the setup steps work and are used by kubeadm HA users.
it could be that you did not follow one of the steps correctly.

> DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = "transport: Error while dialing dial tcp 137.184.157.161:2379: connect: connection refused""}

this looks like one of the etcd members is not running.

please try getting on the support channels (see links from the bot below).

/support

**Comment by sanjaz10** [comment]
Hi @neolit123 .Thanks for the reply .i tried with kubeadm with Stacked etcd .its working .
 Between i followed the https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ setup  etcd cluster. i'm also wondering why etcd not working for HA setup.  it would you be great if you can point out the issue . beacuse i refer those guide. but no luck

**Comment by neolit123** [comment]
we have etcd HA e2e tests so it must be something that you missed in the steps.
if you have suggestion fixes for https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ just PR them.

also to your question why we don't give support here...it's not that we don't want to, it's just that we don't have time.
the k8s project has dedicated support channels:
https://github.com/kubernetes/kubeadm#support

**Comment by sanjaz10** [comment]
Hi @neolit123 . already posted slack channel ..seems no one having answer .that's why i post here.
 if you follow the guidance you will noticed another document issue. In the steps 7 they mention kubeadmcfg.yaml in /tmp folder all the etcd instance. but steps 6 showing in the kubeadmcfg.yaml only  $HOST0 having tmp other etcd instance having document root.  i'll create a PR them . anyway thanks for checking my issue . 

![image](https://user-images.githubusercontent.com/35827824/153225908-6b20d5c7-2014-4c12-88f3-068e0c8d13a7.png)

**Comment by sanjaz10** [comment]
Issue sorted . https://github.com/kubernetes/website/issues/31674
