### ISSUE TITLE
kubeadm v1.6.0 daemonset empty  

### ISSUE THREAD

**Issue by Slahser** [kubernetes/kubeadm#266]
thx for your works first.

![screen shot 2017-05-08 at 17 17 59](https://cloud.githubusercontent.com/assets/3760744/25798091/63cf698e-3412-11e7-8a25-880cdc2c5109.png)

kubernetes v1.6.2
kubeadm v1.6.0

I think this is  a serious bug ....

will we have a v1.6.1 to fix this someday?

**Comment by luxas** [comment]
Hmm, how is this related to kubeadm?
None of these DaemonSets are deployed by default and shouldn't be...

How many nodes do you have in your cluster? Only one master or...?

**Comment by Slahser** [comment]
I saw a same issue before but forget the keyword...

```
 »»»» kubectl get ds -n kube-system                                                                                                           0|19:47:28
NAME          DESIRED   CURRENT   READY     NODE-SELECTOR                     AGE
calico-etcd   1         1         1         node-role.kubernetes.io/master=   3d
calico-node   4         4         4         <none>                            3d
kube-proxy    4         4         4         <none>                            3d
```


![screen shot 2017-05-08 at 19 48 41](https://cloud.githubusercontent.com/assets/3760744/25802967/6368b7e2-3427-11e7-9666-a7cc55e1accd.png)

**Comment by Slahser** [comment]
hah,i put this in a  wrong place ...sorry

close it
