### ISSUE TITLE
Windows Node fails to join IPv6 cluster

### ISSUE THREAD

**Issue by wenyingd** [kubernetes/kubeadm#2664]
## What keywords did you search in kubeadm issues before filing this one?

keywords: Windows worker Node, IPv6, kubeadm, preflight check

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

kubeadm preflight checks include file content check on path `/proc/sys/net/bridge/bridge-nf-call-ip6tables` and `/proc/sys/net/ipv6/conf/default/forwarding` on if IPv6 is enabled or not. These files actually exist only on Linux Nodes, but the check logic doesn't validate if it is running on Windows Node. As a result, Windows node would not join IPv6 cluster with kubeadm command if not ignoring the errors.

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Others**: kubeadm: v1.21.0

## What happened?
```
kubeadm join [2001::e03a:c3ff:ab0:d20f]:6443 --token zjdnmi.bgpyhxvzags63vxy --discovery-token-ca-cert-hash sha256:e09ce52d350e57dd
00f3231a1c5a612535ce221abd0c66e9acf1e65f6aa43c31                                                                                            
[preflight] Running pre-flight checks                                                                                                       
        [WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.7. Latest validated version: 20.10
error execution phase preflight: [preflight] Some fatal errors occurred:                                                                    
        [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-ip6tables]: /proc/sys/net/bridge/bridge-nf-call-ip6tables does not exist     
        [ERROR FileContent--proc-sys-net-ipv6-conf-default-forwarding]: /proc/sys/net/ipv6/conf/default/forwarding does not exist           
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`                             
To see the stack trace of this error execute with --v=5 or highe
```

## What you expected to happen?
Windows Node is expected to join the IPv6 cluster successfully

## How to reproduce it (as minimally and precisely as possible)?
1. Deploy an IPv6 cluster 
2. Print the token with kubeadm token create --print-join-command
3. Join the cluster with a Windows Node using kubeadm command

**Comment by neolit123** [comment]
These checks are Linux only according to the code:
https://github.com/kubernetes/kubernetes/blob/release-1.21/cmd/kubeadm/app/preflight/checks.go#L1031

Are you sure this is the output from a windows joining node?

**Comment by neolit123** [comment]
Ok looks like there are cases where there is no goos check for some of these https://github.com/kubernetes/kubernetes/blob/release-1.21/cmd/kubeadm/app/preflight/checks.go#L932
https://github.com/kubernetes/kubernetes/blob/release-1.21/cmd/kubeadm/app/preflight/checks.go#L1003

/kind bug

We should fix this in latest kubeadm (if still an issue?) but no need to backport the fixes becase the error is non blocking and can be ignored.
