### ISSUE TITLE
kubeadm use of private registry by specifying credentials in ClusterConfiguration

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes/kubeadm#2667]
### What would you like to be added?

The ability to provide an authentication string to kubeadm via the ClusterConfiguration that can be used to pull Kubernetes, DNS and etcd images from a private registry when kubeadm is called programmatically. 

### Why is this needed?

Some private container registry services like AWS ECR can not be configured to allow anonymous pulls. This makes cluster creation difficult, especially for internet restricted environments that don't have access to a public ECR. kubernetes-sigs/cri-tools#904 was added to allow use of an environment variable by crictl but it'd be helpful to be able to provide it via a configuration file.

**Comment by sbueringer** [comment]
Sounds to me like it would makes sense to tackle this on the ClusterAPI level instead.

One question I would be interested in is if the goal is to configure this only for the kubeadm pulls or globally for the container runtime used so it can also be used outside of kubeadm calls for other Pods running in Kubernetes later on.
