### ISSUE TITLE
how to skip  "kubeadm config images pull" ?

### ISSUE THREAD

**Issue by oldthreefeng** [kubernetes/kubeadm#2668]
## What keywords did you search in kubeadm issues before filing this one?

we want to skip images pull . 

https://github.com/kubernetes/kubernetes/blob/0ade4678a7ba527d22f6baa81034dea423267608/cmd/kubeadm/app/util/runtime/runtime.go#L118-L122

we make the new oci image shim. 
but the image exsit is in the fucntion. it cant be the command the find the image exsit if user define oci shim.
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?

during kubeadm init . we find images must be pulled if  image not exsit by `crictl` test.  even if the image implementation by user define . 

## Anything else we need to know?

https://github.com/fanux/sealos/issues/883

**Comment by SataQiu** [comment]
If you want to use a private repository, you can use `--image-repository` flag.
```sh
kubeadm init --image-repository sealos.hub:5000
```
