### ISSUE TITLE
After restarting ubuntu Unable to connect to the kubernetes cluster

### ISSUE THREAD

**Issue by subham-awasthi** [kubernetes/kubeadm#2669]
I am facing issues with connecting my kubernetes cluster in local dev setup

I have a single node(master) kubernetes cluster in Ubuntu
I have already replaced IP with hostname in ~/.kube/config but still after restart if IP changes it's giving me error

`The connection to the server user-ThinkPad-P14s-Gen-1:6443 was refused - did you specify the right host or port?`

Kubelet is also in active(running) state

I am getting error connecting node error in kubelet logs

I tried kubeadm reset and then Kubeadm init...it works but my cluster gets deleted and after restart it doesn't work

Please help

**Comment by neolit123** [comment]
Hi, if the IP changes after restart k8s cannot work. Components need
certificates that are valid for a given IP. Find a way to make the IP fixed.

For more support questions please use the support channels.

/support

**Comment by neolit123** [comment]
Also if you just need a single node cluster have a look at the minikube and
kind projects.
