### ISSUE TITLE
Start kubelet in e2e tests

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#268]
Apparently, our kubeadm e2e tests were relying on buggy behavior that was recently fixed (https://github.com/kubernetes/kubernetes/pull/45231), which was causing `kubeadm init` and `kubeadm join` to start the `kubelet` service, even though preflight checks were disabled. Now that this behavior has changed, our e2es are failing (in part) because `kubelet` never starts. Unlike our release .debs, the bazel-generated .debs don't automatically start `kubelet`.

It seems like we have three options:

1. Manually perform `systemctl enable/start kubelet` in kubernetes-anywhere ([configure-vm-kubeadm.sh](https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/gce/configure-vm-kubeadm.sh#L16)). This seems like the easiest fix, although it then deviates from the Getting Started instructions that omit that step.
2. Update our bazel-generated debs to match our release debs. Our release debs have postinstall scripts for kubelet to automatically be enabled and started (and for kubeadm to restart the kubelet service).
3. Reenable preflight checks in our e2e tests. At the time these tests were written, the preflight checks were hitting race conditions and making our e2es flaky. Those issues might be gone now, or this could be a good excuse to chase them down.

I believe (2) is the right long-term direction, since we're hoping to ultimately replace our current `release` deb process ([build.go](https://github.com/kubernetes/release/blob/master/debian/build.go)) with the bazel build, but (3) would also be a step forward, if anyone has the time.

**Comment by mikedanese** [comment]
I like 1.

**Comment by mikedanese** [comment]
I like 1. For 2, I think that it's best practice for packages to default to "don't enable" but obey systemd-preset (which we don't do). 3 sounds ok as well.

https://www.freedesktop.org/software/systemd/man/systemd.preset.html

**Comment by luxas** [comment]
@pipejakob What's the status of this issue?
Which option did you choose?

**Comment by pipejakob** [comment]
I went with option 1: https://github.com/kubernetes/kubernetes-anywhere/commit/bb7dc09e518001cc66f483f624838b143f193912
