### ISSUE TITLE
support for specifying full image refs (incl digests) in places where ImageMeta is used

### ISSUE THREAD

**Issue by cppforlife** [kubernetes/kubeadm#2680]
FEATURE REQUEST

kubeadm configuration has places where it needs to reference registry locations (via `ImageMeta` struct [0]). currently it does not seem possible to use full image ref with digest (e.g. `some-registry.com/my-repo/my-image@sha256:abc...`). i won't go into details here why it is beneficial to use digests instead of tags (topic covered in plenty of places), but i would like to propose following change to ImageMeta:

```diff
// ImageMeta allows to customize the image used for components that are not
// originated from the Kubernetes/Kubernetes release process
type ImageMeta struct {
	// ImageRepository sets the container registry to pull images from.
	// if not set, the ImageRepository defined in ClusterConfiguration will be used instead.
	ImageRepository string

	// ImageTag allows to specify a tag for the image.
	// In case this value is set, kubeadm does not change automatically the version of the above components during upgrades.
	ImageTag string

+      // Image contains full image reference in any preferred valid format
+      // (e.g. some-image, some-image:tag, some-image@sha256:...)
+      Image string
}
```

Above change in my opinion would be in alignment with how Pod API accepts an image (of any ref format) and will provide easy interface to external tools to modify such field programmatically.

[0] https://github.com/kubernetes/kubernetes/blob/4ce435cc95959c3cf24e3ecb38c14b7071f8ec58/cmd/kubeadm/app/apis/kubeadm/types.go#L182

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

**Comment by neolit123** [comment]
allowing the user to pass a entirely custom image has been discussed a few times in the past and this has been rejected.
related:
https://github.com/kubernetes/kubeadm/issues/2411

`kubeadm upgrade` requires an image to be known by kubeadm (i.e. a constant in the binary - etcd, coredns, kube-apiserver, etc...) tags and repositories can be custom.

that was the original design in the ImageMeta.

i think what we can do here is when constructing the `image: ` fields in kubeadm generated manifests, see if the `imageTag` field is not a tag, but a digest and don't add the `:`

instead of `image:tag`, construct `image@digest`.

frankly i though that we already support this.

**Comment by neolit123** [comment]
> instead of image:tag, construct image@digest.

the change can be made here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/images/images.go#L31-L33

like so:
```
// GetGenericImage generates and returns a platform agnostic image (backed by manifest list)
func GetGenericImage(prefix, image, tag string) string {
	// Assume that the "tag" is a digest and don't add the ":" separator
	if strings.HasPrefix(tag, "@") {
		fmt.Sprintf("%s/%s%s", prefix, image, tag)
	}
	return fmt.Sprintf("%s/%s:%s", prefix, image, tag)
}
```

it would also require:
- updates to the API documentation above `ImageTag` fields.
- adding unit test for `GetGenericImage`

other ideas are welcome, but changing the API in kubeadm is quite entangled at this point.

**Comment by fabriziopandini** [comment]
One note from my side
Currently, we have 1 ImageMeta for all the Kubernetes components, if we will consider supporting digest we will probably need one for each of the 3 control-plane images and most probably also one for kube-proxy, and this will require changes to the kubeadm config API that are not eligible for backporting to older versions.

We should also broadcast the change as early as possible so the ecosystem (e.g Cluster API) could get ready to take benefit of the new option as soon as available.

**Comment by neolit123** [comment]
as mentioned to @cppforlife and @voor, allowing kubeadm to provide custom digests for individual component images for the control plane will require API changes not only in the ClusterConfiguration but also during mutable upgrades (ALA `upgrade apply`) in something like an UpgradeConfiguration (NA currently) where users can feed conditionally custom digests for the target upgrade images. reusing ClusterConfiguration for upgrade was claimed as not ideal and deprecated.

that still leaves a gap for coredns / kube-proxy for which kubeadm does not support patches or k8s API object level customization. the users can either patch post deployment or skip them. moving the addons to external is still my preferences, which means that the "external solution" would have to support the digests somehow. it depends on what we end up doing with the ClusterConfiguration.dns API.

i've also pointed out that i have not seen any kubeadm users request the digests support.
but also, oddly i have hardly seen the wider k8s user base to use digests in `image` fields in k8s API objects.
with that in mind, this topic might be worth a survey before we proceed with any action here.

**Comment by voor** [comment]
We also discussed how kubeadm does offer several mechanisms to add in digest through the lifecycle, either pausing in phases or passing in json patches that could address these concerns elsewhere.

**Comment by neolit123** [comment]
> that still leaves a gap for coredns / kube-proxy for which kubeadm does not support patches or k8s API object level customization. the users can either patch post deployment or skip them. moving the addons to external is still my preferences, which means that the "external solution" would have to support the digests somehow. it depends on what we end up doing with the ClusterConfiguration.dns API and whether we are going to add a ClusterConfiguration.proxy API (NA currently).

i was thinking that what we can do on the kubeadm side is the following kubeadm init phase addons {kube-proxy|coredns} --dump-manifest which can output the manifest for these components to STDOUT, they can then be modified and applied with kubectl. (edited)

**Comment by fabriziopandini** [comment]
> with that in mind, this topic might be worth a survey before we proceed with any action here.

Agreed. 
If we have a signal that the use of digest is going to increase (due to growing attention to security/software supply chain or any other reason) then we should reconsider making it a first-class citizen in the kubeadm config API, because this will improve UX and provide more stability to everything we build on top, e.g by shielding users from changes to the generated manifest.

**Comment by voor** [comment]
A good first step towards that might be similar to what knative does; during the init process resolve the current tags to manifests to pin them, and then look at how best to expose that outward in the API.
