### ISSUE TITLE
Kubeadm upgrade failure with v1.18.20 with Ipv6 cluster

### ISSUE THREAD

**Issue by kubebeginner** [kubernetes/kubeadm#2683]
Problem Statement;

Upgrade failure from 1.17.8 to 1.18.20 in ipv6 cluster using kubeadm upgrade 

Description :

During upgrade observed , the kube-apiserver fails to start with the new manifest changes. 
docker logs from kube-apiserver has the below error,

W0421 13:46:43.968456       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://[::1]:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp [::1]:2379: connect: connection refused". Reconnecting...

ETCD logs,

2022-04-21 13:45:34.072198 I | mvcc: finished scheduled compaction at 2906738 (took 13.323027ms)
2022-04-21 13:45:58.602168 I | embed: rejected connection from "[2001:420:293:2471:172:29:54:132]:55648" (error "EOF", ServerName "")

From the diff of the manifest files , notice the etcd server address might be causing the issue .

<     - --etcd-servers=https://[::1]:2379
---
>     - --etcd-servers=https://127.0.0.1:2379

Any suggestions to fix the issue ?
Is there any option available to dynamically update the kubeapiserver.yaml during the upgrade ?

**Comment by kubebeginner** [comment]
Hello @neolit123 ,

Attached the files for your reference. 
The cluster setup has 3 master nodes (HA availability).

The upgrade is tried using the kubeadm upgrade command on the first master node with VIP and the failure is seen. 

# Upgrade sequence ( done through ansible playbooks)
 yum install -y kubeadm-1.18.20
/usr/bin/kubectl drain {{ ansible_hostname }} --delete-local-data --force --ignore-daemonsets --grace-period=5 --timeout=180s
/usr/bin/kubeadm upgrade apply v{{ upgrade_version }} -y
 /usr/bin/kubectl uncordon {{ ansible_hostname }}

Issue reproduced consistently when attempted with kubeadm upgrade.

### etcd.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://[2001:420:293:2471:172:29:54:132]:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://[2001:420:293:2471:172:29:54:132]:2380
    - --initial-cluster=cvmonq1=https://[2001:420:293:2471:172:29:54:132]:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://[2001:420:293:2471:172:29:54:132]:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://[2001:420:293:2471:172:29:54:132]:2380
    - --name=cvmonq1
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: 10.10.1.5:5000/etcd:3.4.3-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
#apiserver.yaml (17.8)

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=2001:420:293:2471:172:29:54:132
    - --allow-privileged=true
    - --apiserver-count=3
    - --authorization-mode=Node,RBAC
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --endpoint-reconciler-type=lease
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --runtime-config=settings.k8s.io/v1alpha1=true
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=fd00:1234::/110
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: 10.10.1.5:5000/kube-apiserver:v1.17.8
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 2001:420:293:2471:172:29:54:132
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
status: {}

### kube-apiserver ( 18.20)

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: '[2001:420:293:2471:172:29:54:132]:6443'
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=2001:420:293:2471:172:29:54:132
    - --allow-privileged=true
    - --apiserver-count=3
    - --authorization-mode=Node,RBAC
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --endpoint-reconciler-type=lease
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://[::1]:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=fd00:1234::/110
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: 10.10.1.5:5000/kube-apiserver:v1.18.20
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 2001:420:293:2471:172:29:54:132
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
status: {}
##Kubeadm configs

apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
        apiserver-count: "3"
        authorization-mode: Node,RBAC
        bind-address: 0.0.0.0
        endpoint-reconciler-type: lease
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta2
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: '[2001:420:293:2471:172:29:54:135]:6443'
    controllerManager:
      extraArgs:
        bind-address: '::'
        node-monitor-grace-period: 40s
        node-monitor-period: 5s
        pod-eviction-timeout: 5m0s
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: 10.10.1.5:5000
    kind: ClusterConfiguration
    kubernetesVersion: v1.17.8
    networking:
      dnsDomain: cluster.local
      podSubnet: fd20::0/112
      serviceSubnet: fd00:1234::/110
    scheduler:
      extraArgs:
        bind-address: '::'
  ClusterStatus: |
    apiEndpoints:
      cvmonq1:
        advertiseAddress: 2001:420:293:2471:172:29:54:132
        bindPort: 6443
      cvmonq2:
        advertiseAddress: 2001:420:293:2471:172:29:54:133
        bindPort: 6443
      cvmonq3:
        advertiseAddress: 2001:420:293:2471:172:29:54:134
        bindPort: 6443
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterStatus
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-21T20:00:37Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "832"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kubeadm-config
  uid: c51ffc16-8eab-4ab6-b73b-20884a8078c7
[kubeadm-upgrade-logs.pdf](https://github.com/kubernetes/kubeadm/files/8536613/kubeadm-upgrade-logs.pdf)

**Comment by neolit123** [comment]
i must admit i still don't understand what is happening here exactly.
so after you upgrade with kubeadm 1.18 this is the new address?

> - --etcd-servers=https://[::1]:2379

the value before was this?

> - --etcd-servers=https://127.0.0.1:2379

or is it the other way around?


try the following:
- run kubeadm upgrade
- open a new terminal and edit the /etc/manifests/etcd.yaml / /etc/manifests/kube-apiserver.yaml files to change to an address that works
- see if kubeadm upgrade finishes

**Comment by neolit123** [comment]
```
    apiEndpoints:
      cvmonq1:
        advertiseAddress: 2001:420:293:2471:172:29:54:132
        bindPort: 6443
      cvmonq2:
        advertiseAddress: 2001:420:293:2471:172:29:54:133
        bindPort: 6443
      cvmonq3:
        advertiseAddress: 2001:420:293:2471:172:29:54:134
        bindPort: 6443
```

this is strange. you seem to have 3 apiservers on the same host.

**Comment by neolit123** [comment]
added help wanted if someone has the time to help debug.

**Comment by neolit123** [comment]
> try the following:

alternatively try `kubeadm upgrade apply --patches ...` and add extra flags
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches


example patch etcd.yaml:

```
[{"op": "add", "path": "/spec/template/spec/containers/0/args", "value": [
  "--some-flag=some-value",
]}]
```

**Comment by kubebeginner** [comment]
> i must admit i still don't understand what is happening here exactly. so after you upgrade with kubeadm 1.18 this is the new address?
> 
> > * --etcd-servers=https://[::1]:2379
> 
> the value before was this?
> 
> > * --etcd-servers=https://127.0.0.1:2379
> 
> or is it the other way around?
> 
> try the following:
> 
> * run kubeadm upgrade
> * open a new terminal and edit the /etc/manifests/etcd.yaml / /etc/manifests/kube-apiserver.yaml files to change to an address that works
> * see if kubeadm upgrade finishes

Yes , the understanding is correct.

During the upgrade from 1.17.x to 1.18.x - the etcd server URL in the apiserver manifest is changing from 

--etcd-servers=https://127.0.0.1:2379/.  =====> --etcd-servers=https://[::1]:2379

and the upgrade fails.

As suggested, if I modify the etcd-servers URL back to https://127.0.0.1:2379/ in new terminal , while upgrade is in progress - kubeadm upgrade is proceeding to completion. 

The cluster is getting updated to 1.18.20.

Is the recommended steps to go with the upgrade ? 
Kindly confirm

**Comment by kubebeginner** [comment]
> ```
>     apiEndpoints:
>       cvmonq1:
>         advertiseAddress: 2001:420:293:2471:172:29:54:132
>         bindPort: 6443
>       cvmonq2:
>         advertiseAddress: 2001:420:293:2471:172:29:54:133
>         bindPort: 6443
>       cvmonq3:
>         advertiseAddress: 2001:420:293:2471:172:29:54:134
>         bindPort: 6443
> ```
> 
> this is strange. you seem to have 3 apiservers on the same host.

The apiservers are hosted on 3 different hosts ( cvmonq1, cvmonq2,cvmonq3)

**Comment by neolit123** [comment]
> During the upgrade from 1.17.x to 1.18.x - the etcd server URL in the apiserver manifest is changing from

I do not know why that is happening. But if the cluster is ipv6 etcd should use https://[::1]:2379. So that seems like the correct value to me. Not 127.0.0.1. Etcd's listen urls in the etcd manifest should also use https://[::1]:2379.

> The cluster is getting updated to 1.18.20.

So it worked? Even if it worked 127.0.0.1 doesn't seem correct for etcd in a ipv6 only cluster.

> Is the recommended steps to go with the upgrade ?

Normally you shouldn't have to edit manifests in separate terminals during upgrade.

**Comment by neolit123** [comment]
Can you show the output of:
```
kubectl get cm -n kube-system kubeadm-config -o yaml
```

**Comment by neolit123** [comment]
to construct the etcd static pod manifest kubeadm uses some data stored in the cluster.
https://github.com/kubernetes/kubernetes/blob/release-1.18/cmd/kubeadm/app/phases/etcd/local.go#L224

kubeadm 1.18 has two ways to determine what is the API endpoint for a CP node.
https://github.com/kubernetes/kubernetes/blob/release-1.18/cmd/kubeadm/app/util/config/cluster.go#L115

https://github.com/kubernetes/kubernetes/blob/0f3e6609388defe7d0149216cb0409531f8d33b3/cmd/kubeadm/app/util/config/cluster.go#L209-L229

it will first check what is the annotation of the apiserver pod:
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubeadm-kubernetes-io-kube-apiserver-advertise-address-endpoint

e.g. `kubectl get po -n kube-system kube-apiserver-<some-name> -o yaml`

if it cannot get it, it will use the `advertiseAddress` in the kubeadm-config ClusterStatus.

based on that address it then decides whether to use `::1` or `127.0.0.1` for the etcd / kube-apiserver static pod.
https://github.com/kubernetes/kubernetes/blob/release-1.18/cmd/kubeadm/app/phases/etcd/local.go#L226-L229
https://github.com/kubernetes/kubernetes/blob/b6c06a95d7ff262a876b95a1035eaf478a7cb961/cmd/kubeadm/app/phases/controlplane/manifests.go#L206-L209

i don't see a bug, if the cluster is IPv6, etcd should be at `[::1]`.

in your 1.17 IPv6 cluster:

you should have this for etcd.yaml

```
--listen-client-urls=https://[::1]:2379,https://<.....some adress....>:2379
```

and this for kube-apiserver.yaml:
```
--etcd-servers=https://[::1]:2379
```

make sure that IPv6 is correctly used in annotations:
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubeadm-kubernetes-io-kube-apiserver-advertise-address-endpoint
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubeadm-kubernetes-io-etcd-advertise-client-urls
and try editing them to be `[::1]` if they are `127.0.0.1`.
