### ISSUE TITLE
kubeadm-kinder-latest-on-1-24 failed for create cluster

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubeadm#2684]
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest-on-1-24

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?

v1.24.0

```
# task-02-create-cluster
kinder create cluster --name=kinder-xony --image=kindest/node:test --control-plane-nodes=3 --worker-nodes=2 --loglevel=debug

time="01:37:23" level=debug msg="Running: docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster --format {{.Label \"io.k8s.sigs.kind.cluster\"}}"
Creating cluster "kinder-xony" ...

time="01:38:58" level=error msg="node kinder-xony-worker-2 did not start in 40s: node state is not Running, error: <nil>, output lines: ['false'], "
Error: failed to create cluster: node kinder-xony-worker-2 did not start in 40s: node state is not Running, error: <nil>, output lines: ['false'], 
 exit status 1
```

**Comment by pacoxu** [comment]
The CI is green now.
Is this a flake?
/kind flake

**Comment by neolit123** [comment]
Looks like it was an issue with the 1.24 test Image. Should not happen any
more.

/close
