### ISSUE TITLE
pods created by kubeadm periodically killed and restart

### ISSUE THREAD

**Issue by kmahyyg** [kubernetes/kubeadm#2686]
## Before all

I've already sent request to slack channel without getting any useful response. And also, this issue satisfy the requirement of "Only submit a issue when the pod is not working only after you execute `kubeadm init` without any other command followed."

All the OS and VM that K8S running on is created by a self-made template of Arch Linux without any modification. The same template works well when following tutorial of [kubernetes-the-hard-way](https://github.com/kelseyhightower/kubernetes-the-hard-way) .

## What keywords did you search in kubeadm issues before filing this one?

`localhost access`  `refuse conn` `restart`

- [X] I have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

- [X] BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):  `kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"archive", BuildDate:"2022-04-21T13:54:39Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}` shipped with Arch Linux official package repo

**Environment**:
- **Kubernetes version** (use `kubectl version`):  

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"archive", BuildDate:"2022-04-21T13:54:39Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
``` 

- **Cloud provider or hardware configuration**: Arch Linux VM running on Intel i7-9750H with Win10 Host using VMWare Workstation Pro, Network is configured as static IP via NAT. All other settings were default or configured strictly following the official document. Network firewall is enabled but allowed all traffic without any other rules. Brand new VM, other services running on the VM is `opensshd` and `vmtoolsd`. 4vCPU core, 8GiB RAM, 40G SSD.

- **OS** (e.g. from /etc/os-release):

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

- **Kernel** (e.g. `uname -a`):

```
Linux k8shostcp1 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64 GNU/Linux
```

- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd

- **Container networking plugin (CNI)** (e.g. Calico, Cilium):  Calico. But since it's a bug report, no CNI was deployed currently.

- **Others**: The same configuration can run [k8s-the-hard-way](https://github.com/kelseyhightower/kubernetes-the-hard-way) smoothly. So I do not think it is a problem of underlying VM.

## What happened?

`kubeadm init --pod-network-cidr 10.99.0.0/16 --service-cidr 10.0.1.0/24 --upload-certs --control-plane-endpoint "k8shostcp:6443"` successfully finished. But the static pods created by kubeadm keep in `CrashLoopBackOff` status. When run `crictl ps` and `crictl logs` to check for containers, both `api-server` and `etcd` are working and liveness check is success, however they got killed and restart periodically, exit code is `2`, reason is `terminated`.

## What you expected to happen?

All the pods created by `kubeadm init` runs smoothly without any restart.

## How to reproduce it (as minimally and precisely as possible)?

- Create a new Arch Linux VM strictly following official Arch Wiki Installation guide. Only install required software like `vim sudo wget curl ca-certificates containerd`. No further configuration is required.
- Set static IP using systemd-networkd with minimum required configuration just containing network if name and IP, gateway, DNS.
- Following the Arch Wiki, install `kubernetes-control-plane kubernetes-node cni-plugins conntrack-tools base-devel`, set `sysctl.conf` following the K8S document for containerd. Containerd has NO configuration, which means all default.
- Set hostname to `k8shostcp1` and configured corresponding `/etc/hosts` to `127.0.0.1 k8shostcp1`.
- Set host alias to `k8shostcp` and configured corresponding `/etc/hosts` to `192.168.56.10 k8shostcp`.  (192.168.56.10 was a static IP in VM instance IP pool, no conflict or shared IP here.)
- Start and enable systemd service of `kubelet containerd`.
- Run: `kubeadm init --pod-network-cidr 10.99.0.0/16 --service-cidr 10.0.1.0/24 --upload-certs --control-plane-endpoint "k8shostcp:6443"`
- Check `crictl ps -a` you could see periodically restart of `etcd` and `kube-apiserver`. Due to instability of `kube-apiserver`, `kube-controller-manager` and `kube-scheduler` cannot run correctly.
- If you are a lucky guy, `apiserver` might be alive for a few seconds after restart (around 60-90 secs), you could use `kubectl get pods -A` and check logs correspondingly.

## Anything else we need to know?

Feel free to chat with me using the same ID in `#kubeadm` channel of slack.

**Comment by kmahyyg** [comment]
<img width="1000" alt="CleanShot 2022-04-23 at 10 59 03@2x" src="https://user-images.githubusercontent.com/16604643/164872657-bd349010-f31c-4660-bed0-04e1f18e5337.png">

Logs from `crictl logs` :

https://gist.github.com/kmahyyg/e87506038fdf85fb05731cf79948ba0c

**Comment by kmahyyg** [comment]
Same configuration were apply to a brand new Ubuntu 20.04 VM. All pods works correctly. Since Arch Linux does NOT contain any unnecessary pre-tuned configuration, I do consider this problem might be related to Linux kernel. Some experiment is currently on-going.

**Comment by kmahyyg** [comment]
I can confirm this is related to kubeadm support of Arch Linux.

**Comment by kmahyyg** [comment]
When configured to use pre-defined CNI configuration with CRI-O, problem resolved.

**Comment by kmahyyg** [comment]
> 

Hi, I finally figured out its root cause after about a month. I just checked your profile. It looks like you are in China Mainland. Please do STOP using any fake-ip based proxy tool such as Clash (tun mode only) or Proxifier or Surge (fake-ip mode) when running K8S cluster.

Also, you should check the troubleshooting page of kubeadm. It mentioned that you should make sure `hostname -i` returns a directly routable address. FUCK GFW!

And also, please try switch the default image mirror to some others instead of using `gcr.io` .

**Comment by kmahyyg** [comment]
Or you could use override node IP option when starting kubelet service, but I do NOT recommend you to do so.

**Comment by rocna** [comment]
> I can confirm this is related to kubeadm support of Arch Linux.

Hi, is it really related to the kernel?  I also had this problem with Rocky 9. 

```
Linux master001 5.14.0-70.30.1.el9_0.x86_64 #1 SMP PREEMPT Thu Nov 3 20:29:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
