### ISSUE TITLE
Empty output of docker ps after kubeadm init

### ISSUE THREAD

**Issue by CVilinsky** [kubernetes/kubeadm#2695]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** v1.24.0

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Amazon Linux 2 
- **Kernel** (e.g. `uname -a`): Linux ip-172-31-2-210.eu-central-1.compute.internal 5.10.109-104.500.amzn2.x86_64 #1 SMP Wed Apr 13 20:31:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- **Container runtime (CRI)** : containerd
- **Container networking plugin (CNI)**:  WeaveWorks

## What happened?
docker ps output is empty
![image](https://user-images.githubusercontent.com/76901551/168467956-937a334d-a7f3-4a8f-b028-d1101b16f7ab.png)
## What you expected to happen?
List the existing containers

## How to reproduce it (as minimally and precisely as possible)?
kubeadm init
and docker ps after wards

**Comment by pacoxu** [comment]
Kubernetes v1.24 will use containerd as the default container runtime. So `crictl pods` instead following https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/.
