### ISSUE TITLE
kubeadm join discovery/kubeconfig file does not recognize client-go credential plugin

### ISSUE THREAD

**Issue by tallaxes** [kubernetes/kubeadm#2708]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT (arguably)

## Versions

**kubeadm version** (use `kubeadm version`): 1.22.6 (but all current versions are affected)

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.22.6
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS
- **Kernel** (e.g. `uname -a`): 5.13.0-1023-azure
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): kubenet

## What happened?

When `kubeadm join --discovery-file ...` is passed discovery file / kubeconfig that includes any [client-go credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) (aka exec), kubeadm does not recognize the credential plugin and treats kubeconfig file as not having any auth credentials: `[discovery] Discovery file does not contains authentication credentials, using unauthenticated request for validating TLS connection`

(Same behavior can be observed with `JoinConfiguration` pointing - via `discovery.file.kubeConfigPath` - to such kubeconfig).

## What you expected to happen?

kubeadm can be expected to accept any valid kubeconfig here, as long as it contains some credentials. This seems to have been the intent of [`HasAuthenticationCredentials`](https://github.com/kubernetes/kubernetes/blob/0fe0dbf3fb8cf501c24c87f4113a3819cb86a550/cmd/kubeadm/app/util/kubeconfig/kubeconfig.go#L118-L143) (possibly as the first step in ensuring a self-contained kubeconfig can be produced), but currently it only checks for token, basic and X.509 authentication. There are valid use cases for using client-go credential plugins here (we would like to be able to use [Azure/kubelogin](https://github.com/Azure/kubelogin), for example). 

As another data point, kubelet itself does not have any problem accepting kubeconfig with exec plugin as bootstrap-kubeconfig. (Neither does kubectl, and likely any other generic client-go consumer ...)

## How to reproduce it (as minimally and precisely as possible)?

```bash
# create kubeconfig with (fake) client-go credential plugin
cat > kubeconfig-with-exec <<EOF
apiVersion: v1
kind: Config
users:
- name: my-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: example-client-go-exec-plugin
clusters:
- cluster:
    server: https://localhost:443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-cluster
current-context: my-cluster
EOF

# attempt joining using the above
kubeadm join -v=4 --discovery-file kubeconfig-with-exec
```

Observe `[discovery] Discovery file does not contains authentication credentials, using unauthenticated request for validating TLS connection` in log.

## Anything else we need to know?

Besides client-go credential plugins, kubeadm currently would not recognize two other [auth info flavors generally supported by client-go](https://github.com/kubernetes/client-go/blob/d4fc9af2dfada718e01e58a7a929a0cdaec8f77c/tools/clientcmd/api/types.go#L101-L151):
* `TokenFile` - pointer to a file that contains a bearer token.
* `AuthProvider` - custom authentication plugin. Looking at the [state](https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth) of support for authentication plugins, most (azure/gcp/openstack) are migrating to client-go credential plugins - yet another reason to support this in kubeadm. This leaves [OIDC authenticator](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-1-oidc-authenticator).

I am not sure how important it is to support either of these two; but mentioning them here for completeness.

**Comment by neolit123** [comment]
thanks for logging the issue, tagged with backlog/help-wanted.

> kubeadm can be expected to accept any valid kubeconfig here, as long as it contains some credentials. This seems to have been the intent of [HasAuthenticationCredentials](https://github.com/kubernetes/kubernetes/blob/0fe0dbf3fb8cf501c24c87f4113a3819cb86a550/cmd/kubeadm/app/util/kubeconfig/kubeconfig.go#L118-L143) (possibly as the first step in ensuring a self-contained kubeconfig can be produced), but currently it only checks for token, basic and X.509 authentication. There are valid use cases for using client-go credential plugins here (we would like to be able to use [Azure/kubelogin](https://github.com/Azure/kubelogin), for example).

it seems like a valid request, thus a PR is welcome if someone wants to prepare it.
