### ISSUE TITLE
[kubeadm reset]some container removed fail

### ISSUE THREAD

**Issue by lixd** [kubernetes/kubeadm#2711]
## What keywords did you search in kubeadm issues before filing this one?

reset

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
```console
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:48:05Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
1.23.6
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```console
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`): 
```console
Linux kc-1 5.4.156-1.el7.elrepo.x86_64 #1 SMP Tue Oct 26 11:19:09 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- **Container runtime (CRI)** (e.g. containerd, cri-o): 
containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
Calico
- **Others**:

## What happened?
use kubeadm reset to clean node, occasionally some container clean failed.
> and this will cause another error, such as,if the container is api-server, it will use 6443 port, and next kubeadm init will failed.

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/31980412/174258933-ee4adfac-a3a1-437c-a655-e2c8d8a4ae46.png">
## What you expected to happen?

all container were removed.

## How to reproduce it (as minimally and precisely as possible)?

make some container restarting， and exec kubeadm reset cmd. 
> when k8s exist, direct use containerd client to kill some container, and k8s will restart it. now we exec kubeadm reset. Maybe it will happen.
## Anything else we need to know?

kubeadm log
```console
[reset] Reading configuration from the cluster...                                                                                                                              
[reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'                                                                      
[preflight] Running pre-flight checks                                                                                                                                          
W0616 14:09:08.678238   31408 reset.go:101] [reset] Unable to fetch the kubeadm-config ConfigMap from cluster: failed to get config map: Get "https://apiserver.cluster.local:6
443/api/v1/namespaces/kube-system/configmaps/kubeadm-config?timeout=10s": dial tcp 192.168.10.210:6443: connect: connection refused                                            
W0616 14:09:08.678431   31408 removeetcdmember.go:80] [reset] No kubeadm config, using etcd pod spec to get data directory                                                     
[reset] Stopping the kubelet service                                                                                                                                           
[reset] Unmounting mounted directories in "/var/lib/kubelet"                                                                                                                   
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]                                                                               
W0616 14:09:09.696319   31408 cleanupnode.go:84] [reset] Failed to remove containers: [failed to remove running container 3be3fe891f98857c3a1bd4adc4dbc230bc294ef585269d40d8eea
2906b085166: output: removing the pod sandbox "3be3fe891f98857c3a1bd4adc4dbc230bc294ef585269d40d8eea2906b085166": rpc error: code = Unknown desc = failed to remove container "
ecd866a5c9942d181022725b867cbf428a996e0ec1a9d9e73ae83420f7c6c5ed": failed to set removing state for container "ecd866a5c9942d181022725b867cbf428a996e0ec1a9d9e73ae83420f7c6c5ed
": container is in starting state, can't be removed                                                                                                                            
, error: exit status 1, failed to remove running container 447a5b9e70d776b2eab90bafd4a5471a15b8def6a16edec77d48e11fb9e839f9: output: removing the pod sandbox "447a5b9e70d776b2
eab90bafd4a5471a15b8def6a16edec77d48e11fb9e839f9": rpc error: code = Unknown desc = failed to remove container "7ee3e97af0a3db102fed8e19985f1a832a509f47b5e33f7dfb09c5484fd17ea
f": failed to set removing state for container "7ee3e97af0a3db102fed8e19985f1a832a509f47b5e33f7dfb09c5484fd17eaf": container is in starting state, can't be removed 
```
containerd log
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/31980412/174259102-ae046c81-38f4-4b1a-b3d6-1ecc1b2407d7.png">

containerd forbid remove stating container.
```go
func setContainerRemoving(container containerstore.Container) error {
   return container.Status.Update(func(status containerstore.Status) (containerstore.Status, error) {
      // ...
      if status.Starting {
         return status, errors.New("container is in starting state, can't be removed")
      }
     // ....
      return status, nil
   })
}
```
so,if some contianer are restarting,and kubeadm reset try to remove it, will got a error,so the container not clean and the port is used.
maybe we can deal with this error, and retry delete.

**Comment by neolit123** [comment]
Thanks for logging the issue. I have not seen these errors before. Something we have to clarify is the "reset" has always been designed as a best effort command. If it fails or cannot complete for some reason users must take manual action.

So having said that, what can we do to force stop these containers is there a crictl flag for that? If retry is the only option, for how long should we retry?

/priority awaiting-more-evidence

**Comment by whichdew** [comment]
> /kind bug

I also ran into this problem, but I can't find the corresponding podSandboxId in ps-ef
> version: 1.24.1

**Comment by neolit123** [comment]
> failed to destroy network for sandbox

that seems unrelated and is a kubelet error, not kubeadm.
kubeadm uses `crictl` to remove containers.

**Comment by neolit123** [comment]
@lixd do you have an answer to this question:

> So having said that, what can we do to force stop these containers - is there a crictl flag for that? If retry is the only option, for how long should we retry?

**Comment by lixd** [comment]
> @lixd do you have an answer to this question:
> 
> > So having said that, what can we do to force stop these containers - is there a crictl flag for that? If retry is the only option, for how long should we retry?

there is no crictl flag for this, as you see  "reset" has always been designed as a best effort command,**so we can retry in 2 minute max.** 

i found kubelet's default runtime timeout is 2 minute,at [there](https://github.com/kubernetes/kubernetes/blob/487512bb563ad8cfb70f1763bce07e754073d759/pkg/kubelet/apis/config/v1beta1/defaults.go#L170-L172) :
```go
	if obj.RuntimeRequestTimeout == zeroDuration {
		obj.RuntimeRequestTimeout = metav1.Duration{Duration: 2 * time.Minute}
	}
```
if req timeout,containerd will set container's status.Starting = false,then we can stop it.
or not timeout,container start success,containerd will set container's status.Starting = false too, we also can stop it.

if the user set a custom runtime timeout, we maybe emit this error, but this is out of our control.

**Comment by neolit123** [comment]
happy to look at PRs if someone has the time to send one

/help

**Comment by neolit123** [comment]
> there is no crictl flag for this

should it be added as a feature?

**Comment by SataQiu** [comment]
>  also this might require running the container removals in separate go routines instead of linearly. ...linear vs parallel depends if e.g. only 1 container is stuck. parallel sounds better overall, but hopefully it doesn't bug the container runtime...

Emm... our testing framework does not seem to support concurrency, I wonder how to handle concurrent tests about `fakeexec.FakeCmd`. Any suggestions? @neolit123 

https://github.com/kubernetes/kubernetes/blob/d2c5779dadc9ed7a462c36bc280b2f9a200c571e/cmd/kubeadm/app/util/runtime/runtime_test.go#L167-L176

**Comment by neolit123** [comment]
We should probably keep it linear, retry for small time (10sec?) and show warnings for containers that cannot be removed instead of erroring.
