### ISSUE TITLE
Kubeadm scheduler manifest contains incorrect flag

### ISSUE THREAD

**Issue by vipinjn24** [kubernetes/kubeadm#2716]
## Error: unknown flag: --address

BUG REPORT

After upgrading from 1.23.8 to 1.24.2 I saw that my pods are not getting scheduled. so I checked the issue and found that kube-scheduler is in error due to an old flag i.e. --address, however in 1.24 it is changed to --bind-address.

## Versions

**kubeadm version** : 1.24.2

**Environment**:
- **Kubernetes version**: 1.24.2
- **Cloud provider or hardware configuration**: Bare-metal
- **OS** (e.g. from /etc/os-release): ubuntu 22.04
- **Kernel** (e.g. `uname -a`): Linux vjs-net-in 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico
- **Others**:

## What happened?
Pods not getting scheduled after upgrade to 1.24.x

## What you expected to happen?
Pods should be scheduled.

## How to reproduce it (as minimally and precisely as possible)?
Install or upgrade kubernetes to 1.24.x

## Anything else we need to know?
I was able to resolve the issue by running the below command.
sudo sed -i -e 's/--address=0.0.0.0/--bind-address=0.0.0.0/' /etc/kubernetes/manifests/kube-scheduler.yaml

Please fix the issue in upcoming versions.

**Comment by neolit123** [comment]
are you sure you did not add the flag manually?
what are the contents of your kubeadm config file and `kubectl get cm -n kube-system kubeadm-config -o yaml`?

we have e2e upgrade tests and this problem is not present there:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-23-1-24

**Comment by neolit123** [comment]
please see:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/
