### ISSUE TITLE
No service for endpoints

### ISSUE THREAD

**Issue by erikbgithub** [kubernetes/kubeadm#272]
## What keywords did you search in kubeadm issues before filing this one?
"service"

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: VMWare local on Win10
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux ubuntu 4.8.0-51-generic #54~16.04.1-Ubuntu SMP Wed Apr 26 16:00:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Others**: others what?

## What happened?

With `kubectl get pods --all-namespaces` we saw dns had `2/3` and `CrashLoopBackoff` all the time.

docker logs of a dead container ( only in `docker ps -a`) shows:
```
I0517 10:32:39.262912       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0517 10:32:39.263054       1 nanny.go:86] Starting dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
I0517 10:32:39.287696       1 nanny.go:111] 
W0517 10:32:39.287731       1 nanny.go:112] Got EOF from stdout
I0517 10:32:39.287701       1 nanny.go:108] dnsmasq[10]: started, version 2.76 cachesize 1000
I0517 10:32:39.287806       1 nanny.go:108] dnsmasq[10]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0517 10:32:39.287828       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0517 10:32:39.287868       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0517 10:32:39.287889       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0517 10:32:39.287929       1 nanny.go:108] dnsmasq[10]: reading /etc/resolv.conf
I0517 10:32:39.287945       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0517 10:32:39.287959       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0517 10:32:39.287973       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0517 10:32:39.287987       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.1.1#53
I0517 10:32:39.288051       1 nanny.go:108] dnsmasq[10]: read /etc/hosts - 7 addresses
I0517 10:35:27.996644       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0517 10:35:38.022715       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0517 10:35:48.038237       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0517 10:35:58.052300       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0517 10:36:08.084236       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0517 10:36:18.087025       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0517 10:36:28.093344       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0517 10:36:38.107142       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
```

endpoints (see the two `<none>` blocks? is that supposed to be like that?):
```
kube-system   kube-controller-manager   <none>                                                      1h
kube-system   kube-dns                  172.2.0.9:53,172.2.0.9:53                                   1h
kube-system   kube-scheduler            <none>                                                      1h
kube-system   kubernetes-dashboard      172.2.0.2:9090                                              14m
kube-system   tiller-deploy             172.2.0.3:44134            
```

`kubectl logs -n kube-system <pod-name> kubedns contains lines like these (when redeployed with "-v=9":
```
No service for endpoint "kube-controller-manager" in namespace "kube-system"
No service for endpoint "kube-scheduler" in namespace "kube-system"
```

## What you expected to happen?
DNS just works

## How to reproduce it (as minimally and precisely as possible)?
checkout my deploy.sh:
```
#!/bin/bash

# KUBECONFIG should be defined in /etc/environment and should contain the admin user "kubeconfig" as created by kubeadm
kubeadm reset
echo "resettet"
sleep 2
kubeadm init --service-cidr=172.1.0.0/16 --pod-network-cidr=172.2.0.0/16
chmod 644 ${KUBECONFIG}
kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --user=system:anonymous --group=system:serviceaccounts
kubectl apply -f weave.yaml 
kubectl taint nodes --all node-role.kubernetes.io/master-
```

## Anything else we need to know?
I hope not.

**Comment by luxas** [comment]
@timothysc Dupe of #273?

**Comment by timothysc** [comment]
Very similar closing.

**Comment by erikbgithub** [comment]
Can't reproduce the proposed solution from #273. Ubuntu 16.04 doesn't use `systemd-resolved` yet and 16.04's resolv.conf doesn't contain `127.0.0.35`.

```
$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search localdomain
```

**Comment by luxas** [comment]
@erikbgithub Can you give more information?
To me it seems like `Maximum number of concurrent DNS queries reached (max: 150)` is the issue.

What weave manifest are you using?
What do `/etc/{nsswitch.conf,hosts}` contain?
What does `nslookup $(hostname)`, `nslookup localhost.$(hostname -d)` and `nslookup localhost` output?

**Comment by straticsryan** [comment]
I think I just ran into this issue as well.

My private network is 10.X.X.X and so I changed the `service-cidr` and `pod-network-cidr` to 172.30.X.X. I'm using weave as well, so I had to modify weave's yml to add the IPALLOC_RANGE env variable to match the cidr's.

Once I got this going I finally was able to get application pods installed and everything working -- except pod dns.

Using the sock-shop demo (https://github.com/microservices-demo/microservices-demo), I noticed the pages weren't rendering properly.

I debugged and eventually found that its front-end svc pod couldn't locate its user svc via `user`. `cat /etc/resolv.conf` (on an alpine-based container) showed that its nameserver was `10.96.0.10`.

I started searching the webs to see if others had ran into this issue which lead me here.

I didn't, however, have the `Maximum number of concurrent DNS queries reached` issue logging anywhere.

**Comment by luxas** [comment]
> My private network is 10.X.X.X and so I changed the service-cidr and pod-network-cidr to 172.30.X.X

@straticsryan Did you change them to _the same CIDR_?
Then I totally understand why it didn't work, as kube-proxy, the kubelet and Weave will fight against each other... The service-cidr and pod-network-cidr must not overlap.

**Comment by jhesshybris** [comment]
Hello. I'm having this same issue and I found a work-around.  It seems like weave gets into a state where it floods the kubedns service. This causes messages like this to appear in the logs of (pod: kube-dns,  container:dnsmasq)

```
I0517 10:35:27.996644       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0517 10:35:38.022715       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
```

With dnsmasq overwhelmed, the healthcheck running in  (pod: kube-dns,  container:sidecar) fails, causing kubernetes to reboot the dns pod. This begins a negative feedback cycle where the DNS is less and less available. 

My workaround: To recover from this bad state, I deleted all the weave pods and the kube-dns pod. Kubernetes recreated the pods. The problem went away.  I still see the log `Maximum number of concurrent DNS queries reached (max: 150)` occasionally, but the service seems to be working. 

I also scaled kube-dns to 2 instances instead of the default 1 that kubeadm sets up: `kubectl -n kube-system scale deployment kube-dns --replicas=2`

**Comment by jhesshybris** [comment]
The reason there were problems in the first place on my machines was that on my debian 9 machine, systemd-resolved.service and resolveconf.service were running. These services rewrote my resolv.conf to include `nameserver 127.0.0.53`  This localhost nameserver address was copied verbatim into kube-dns.dnsmasq, causing havoc. 

Disabling these services and hardcoding resolv.conf on my hosts solved the problem.

**Comment by errordeveloper** [comment]
It sounds like this is configuration issue as some folks mention having to override CIDRs, but I am not quite sure whether that is what @erikbgithub had to do or not.
Also,  I would like to know whether each person commenting here was using VMWare on a Windows host or, that fact is unrelated.

**Comment by luxas** [comment]
Duplicate of #273
