### ISSUE TITLE
proposal: unify the way to cleanup the files for `kubeadm reset`

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubeadm#2721]
## Is this a BUG REPORT or FEATURE REQUEST?

I think this should be a small feature.

## Versions

**kubeadm version** (use `kubeadm version`): master, and I think this should applicable to the legacy version as well.

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?
Currently, kubeadm handle the file deletion in two ways, 

1) delete the files when the each phase is called, e.g. `/etc/kubernetes/manifests/etcd.yaml` is removed when the phase of `cleanup-node` is called.
2) some of the folders, such as `/var/lib/etcd` and `/var/lib/kubelet` are appended to `dirsToClean`, and defer to be removed in the main `kubeadm reset` cmd.

I found one issue if we go with this approach, as the `phase` can be called independently, e.g. I might run `kubeadm reset phase cleanup-node`, then the file `/etc/kubernetes/manifests/etcd.yaml` will be deleted.

Then I would call `kubeadm reset` to destroy the cluster entirely, but this time, kubeadm assume it is external etcd, and won't clean up the data in the `/var/lib/etcd/` folder, checkout the [code here](https://github.com/kubernetes/kubernetes/blob/89aaf7c02dd33415ac994cecfddca7c02ed75834/cmd/kubeadm/app/cmd/phases/reset/removeetcdmember.go#L70-L71) 

This will leave us a unclear environment and lead to the failure to bootstrap a cluster with `kubeadm init` in the next time.

So, I propose to remove all those files within each phase to avoid the problem I described above.

I'm not sure is there any special consideration, pls correct me if there is any.

## What you expected to happen?
A unify way to cleanup the files for `kubeadm reset`

## How to reproduce it (as minimally and precisely as possible)?
pls see the description above.

**Comment by neolit123** [comment]
Why not call the "remove etcd member" phase of reset on demand too?

**Comment by chendave** [comment]
`kubeadm reset phase remove-etcd-member` doesn't help in this case, 

- Since `/etc/kubernetes/manifests/etcd.yaml` is removed by the `kubeadm reset phase cleanup-node`, it will assume this is a external etcd, and no action will done.
> W0705 09:54:27.281551   13401 removeetcdmember.go:84] [reset] No kubeadm config, using etcd pod spec to get data directory
[reset] No etcd config found. Assuming external etcd
[reset] Please, manually reset etcd to prevent further issues

- `kubeadm reset phase remove-etcd-member` doesn't remove the content in the folder (/var/lib/etcd), it just remove the ectd member, and it won't do anything if there is only one member, the relevant [code is here](https://github.com/kubernetes/kubernetes/blob/47ad357c52713aa692aff3b6906e16f27231bab1/cmd/kubeadm/app/phases/etcd/local.go#L105-L129)

**Comment by neolit123** [comment]
We established there is no need to use the etcd client to remove a single remaining etcd member from the etcd cluster and just deleting the static pod and data dir will suffice.

> So, I propose to remove all those files within each phase to avoid the problem I described above.

Could you please summarize what actions you'd like to change and in what phases?

> I'm not sure is there any special consideration, pls correct me if there is any.

Ideally we should avoid breaking user assumptions - I.e. breaking changes that affect users in a negative way. But what you are describing seems like a bug.

**Comment by chendave** [comment]
> We established there is no need to use the etcd client to remove a single remaining etcd member from the etcd cluster and just deleting the static pod and data dir will suffice.

+1

>Could you please summarize what actions you'd like to change and in what phases?

I think the idea should be simple, 
- when the phase of "cleanup node" is called, clean the folder of "/var/lib/kubelet/" directly.
- when the phase of "reset etcd member" is called, clean the folder of "/var/lib/etcd" directly.
- remove the function call of "cleanDirs" in the root cmd of "kubeadm reset".

> Ideally we should avoid breaking user assumptions - I.e. breaking changes that affect users in a negative way. But what you are describing seems like a bug.

+1, this sound like a bug instead.

**Comment by neolit123** [comment]
OK if you have a PR in mind please send it. I will appreciate more reviewers on this one.

**Comment by chendave** [comment]
:) will do, thanks for your comments!
