### ISSUE TITLE
Using --config <file> for kubeadm init and kubeadm join and setting kube-proxy and kubelet addresses to a Wireguard VPN address fails

### ISSUE THREAD

**Issue by jkempf42** [kubernetes/kubeadm#2724]
## What keywords did you search in kubeadm issues before filing this one?

configure Kubeproxy and Kubelet from command line using config file 

## Versions

`kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:38Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`):WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: worker node: VirtualBox Version 6.1.34 r150636 (Qt5.12.8), control node: Ubuntu 20.04 VM running in Azure
- **OS** (e.g. from /etc/os-release):NAME="Ubuntu" VERSION="20.04.4 LTS (Focal Fossa)"
- **Kernel** (e.g. `uname -a`): Linux bldg2 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd 
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Flannel
- **Others**: Multus

## What happened?

The control VM in Azure and worker VirtualBox VM on my local network are connected using a Wireguard VPN. Wireguard wg0 interface address in Azure is 10.8.0.1 and locally is 10.8.0.2. Here are the routing tables:

worker node: 
`default via 192.168.0.1 dev enp0s3 proto dhcp metric 100 
default via 192.168.0.1 dev enp0s8 proto dhcp metric 101 
10.8.0.0/24 dev wg0 proto kernel scope link src 10.8.0.2 
10.244.0.0/24 via 10.244.0.0 dev flannel.1 onlink 
10.244.1.0/24 dev cni0 proto kernel scope link src 10.244.1.1 linkdown 
169.254.0.0/16 dev enp0s3 scope link metric 1000 
192.168.0.0/24 dev enp0s3 proto kernel scope link src 192.168.0.126 metric 100 
192.168.0.0/24 dev enp0s8 proto kernel scope link src 192.168.0.127 metric 101`

control node:
`default via 10.0.0.1 dev eth0 proto dhcp src 10.0.0.4 metric 100 
10.0.0.0/24 dev eth0 proto kernel scope link src 10.0.0.4 
10.8.0.0/24 dev wg0 proto kernel scope link src 10.8.0.1 
10.244.0.0/24 dev cni0 proto kernel scope link src 10.244.0.1 
168.63.129.16 via 10.0.0.1 dev eth0 proto dhcp src 10.0.0.4 metric 100 
169.254.169.254 via 10.0.0.1 dev eth0 proto dhcp src 10.0.0.4 metric 100`

I want the Kubenetes control plane to run exclusively over the Wireguard VPN, i.e. kube-apiserver bind address is 10.8.0.1, kubelet and kubeproxy on control node bind to 10.0.0.1, kubelet and kubeproxy on worker node bind to 10.0.0.2.

I configured a control node using kubeadm -config with the following config file:

`apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.8.0.1"
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "10.8.0.1"
networking:
  podSubnet: "10.244.0.0/16"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: "10.8.0.1"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: "10.8.0.1"`

Seemed to work OK. The kube-proxy pod is binding to 10.8.0.1 and 127.0.0.1.

Then I tried:

`kubectl exec -n kube-system -it pod/kube-proxy-n8ksb -- /bin/bash
Error from server: error dialing backend: dial tcp 10.0.0.4:10250: connect: connection refused`

10.0.0.4 is the address of the Azure VM on the Azure SDN network.

## What you expected to happen?

I expected to be able to exec into the kube-proxy pod. 

## How to reproduce it (as minimally and precisely as possible)?

Set up a VM in Azure and a local VM, set up a Wireguard VPN, and configure the VM with the config file above. 

## Anything else we need to know?

Furthermore, when I try to use `kubeadm join -config` to join the worker to the cluster using the following config file:
`apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"
discovery:
  bootstrapToken:
    token: "fh03ow.okzd1zndnko5mcy0"
    apiServerEndpoint: "10.8.0.1:6443"
    caCertHashes:
      - "sha256:1c80af8c0f7dafa9bbcf19abb59f2287b0bd4a0470a4a3ebfcbb019c6e50f3d5"
  
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: "10.8.0.2"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: "10.8.0.2"`

I get the following message:

`W0708 11:17:25.822676   56316 utils.go:69] The recommended value for "bindAddress" in "KubeProxyConfiguration" is: 0.0.0.0; the provided value is: 10.8.0.1`

then the kubeproxy hangs by also trying to bind to 10.8.0.1.

**Comment by neolit123** [comment]
The kubeproxyconfigudation that you pass to init is global. Thus you cannot pass a bind address to all instances that way. You could use the downward app / env vars to play with setting a value:
https://kubernetes.io/docs/concepts/workloads/pods/downward-api/

Or skip the kubeadm proxy addon with `init --skip-phases addon/kube-proxy` and deploy your own addon.

/support
