### ISSUE TITLE
Kubeadm is not bootstrapping Kubernetes cluster (Self-Managed) 

### ISSUE THREAD

**Issue by malikdraz** [kubernetes/kubeadm#2725]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):  v1.24.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.24.0
- **Cloud provider or hardware configuration**: AWS Provider with m5.large instance type
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Kernel** (e.g. `uname -a`): 5.15.0-1011-aws 
- **Container runtime (CRI)** (e.g. containerd, cri-o): Containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico (Didn't install it yet)
- **Others**: kubelet=v1.24.0

## What happened?

I have setup 3 AWS instances type of m5.large to create Kubernetes v1.23.0 or v1.24.0 cluster. I have followed Kubernetes offical  documentation to install required packages along with containerd, kubelet, kubectl and kubeadm. 

Once everything was installed on both control plane and worker nodes, I ran below command to initiate the kubeadm cluster. 

`sudo kubeadm init --pod-network-cidr 192.168.0.0/16 --kubernetes-version 1.24.0`

### Following is the output of the above command

ubuntu@k8s-control:~$ sudo kubeadm init --pod-network-cidr 192.168.0.0/16 --kubernetes-version 1.24.0
[init] Using Kubernetes version: v1.24.0
[preflight] Running pre-flight checks
        [WARNING SystemVerification]: missing optional cgroups: blkio
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [k8s-control kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 172.31.45.61]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [k8s-control localhost] and IPs [172.31.45.61 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [k8s-control localhost] and IPs [172.31.45.61 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 18.502672 seconds
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config" in namespace kube-system with the configuration for the kubelets in the cluster
[upload-certs] Skipping phase. Please see --upload-certs
[mark-control-plane] Marking the node k8s-control as control-plane by adding the labels: [node-role.kubernetes.io/control-plane node.kubernetes.io/exclude-from-external-load-balancers]
[mark-control-plane] Marking the node k8s-control as control-plane by adding the taints [node-role.kubernetes.io/master:NoSchedule node-role.kubernetes.io/control-plane:NoSchedule]
[bootstrap-token] Using token: 5dc180.tu39hveyq2mjyrm1
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

#### Once cluster was initialised successfully, I have copied /etc/kubernetes/admin.conf to ~/.kube/config. 

Prerequisities: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#forwarding-ipv4-and-letting-iptables-see-bridged-traffic
Containerd: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
Kubeadm: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

## What you expected to happen?

I expected to see my node in NotReady status by running the following command:

`kubectl get nodes`

#### =====Output=====
ubuntu@k8s-control:~$ kubectl get nodes
NAME          STATUS     ROLES           AGE   VERSION
k8s-control   NotReady   control-plane   48s   v1.24.0
#### =====Output=====

I have also expected the kube-system pods to be in pending state, not in CrashLoopBackOff. 

`kubectl get pods -A -o wide`

#### =====Output=====
ubuntu@k8s-control:~$ kubectl get pods -A -o wide
NAMESPACE     NAME                                  READY   STATUS             RESTARTS      AGE   IP             NODE          NOMINATED NODE   READINESS GATES
kube-system   coredns-6d4b75cb6d-27vw4              0/1     Pending            0             24s   <none>         <none>        <none>           <none>
kube-system   coredns-6d4b75cb6d-4kwbk              0/1     Pending            0             24s   <none>         <none>        <none>           <none>
kube-system   kube-apiserver-k8s-control            1/1     Running            1 (56s ago)   88s   172.31.45.61   k8s-control   <none>           <none>
kube-system   kube-controller-manager-k8s-control   0/1     CrashLoopBackOff   1 (4s ago)    4s    172.31.45.61   k8s-control   <none>           <none>
kube-system   kube-proxy-s2w9b                      1/1     Running            1 (23s ago)   25s   172.31.45.61   k8s-control   <none>           <none>
#### =====Output=====
After few minutes, when I ran the `kubectl get pods -A -o wide` command, I started getting the following error:
#### =====Output=====
ubuntu@k8s-control:~$ kubectl get pods -A -o wide
The connection to the server 172.31.45.61:6443 was refused - did you specify the right host or port?
## How to reproduce it (as minimally and precisely as possible)?
Use Kubernetes official document to bootstrap Kubernetes cluster using kubeadm. Its the same issue with the v1.23.0 and v1.24.0. 

## Anything else we need to know?
I was able to grab kube-apiserver logs just before lost the access to cluster. 
#### =====Output=====
Cubuntu@k8s-control:~$ kubectl logs kube-apiserver-k8s-control -n kube-system
I0712 06:42:13.251421       1 server.go:558] external host was not specified, using 172.31.45.61
I0712 06:42:13.252066       1 server.go:158] Version: v1.24.0
I0712 06:42:13.252094       1 server.go:160] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0712 06:42:13.433450       1 shared_informer.go:255] Waiting for caches to sync for node_authorizer
I0712 06:42:13.434365       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I0712 06:42:13.434380       1 plugins.go:161] Loaded 11 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I0712 06:42:13.435288       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I0712 06:42:13.435304       1 plugins.go:161] Loaded 11 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
W0712 06:42:13.483251       1 genericapiserver.go:557] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.
I0712 06:42:13.484059       1 instance.go:274] Using reconciler: lease
I0712 06:42:13.696571       1 instance.go:586] API group "internal.apiserver.k8s.io" is not enabled, skipping.
W0712 06:42:14.138128       1 genericapiserver.go:557] Skipping API authentication.k8s.io/v1beta1 because it has no resources.
W0712 06:42:14.139819       1 genericapiserver.go:557] Skipping API authorization.k8s.io/v1beta1 because it has no resources.
W0712 06:42:14.152820       1 genericapiserver.go:557] Skipping API certificates.k8s.io/v1beta1 because it has no resources.
W0712 06:42:14.154720       1 genericapiserver.go:557] Skipping API coordination.k8s.io/v1beta1 because it has no resources.
W0712 06:42:14.161349       1 genericapiserver.go:557] Skipping API networking.k8s.io/v1beta1 because it has no resources.
W0712 06:42:14.164769       1 genericapiserver.go:557] Skipping API node.k8s.io/v1alpha1 because it has no resources.
W0712 06:42:14.171968       1 genericapiserver.go:557] Skipping API rbac.authorization.k8s.io/v1beta1 because it has no resources.
W0712 06:42:14.171990       1 genericapiserver.go:557] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W0712 06:42:14.173739       1 genericapiserver.go:557] Skipping API scheduling.k8s.io/v1beta1 because it has no resources.
W0712 06:42:14.173756       1 genericapiserver.go:557] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
W0712 06:42:14.179046       1 genericapiserver.go:557] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
W0712 06:42:14.183906       1 genericapiserver.go:557] Skipping API flowcontrol.apiserver.k8s.io/v1alpha1 because it has no resources.
W0712 06:42:14.188773       1 genericapiserver.go:557] Skipping API apps/v1beta2 because it has no resources.
W0712 06:42:14.188791       1 genericapiserver.go:557] Skipping API apps/v1beta1 because it has no resources.
W0712 06:42:14.191037       1 genericapiserver.go:557] Skipping API admissionregistration.k8s.io/v1beta1 because it has no resources.
I0712 06:42:14.195738       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I0712 06:42:14.195754       1 plugins.go:161] Loaded 11 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
W0712 06:42:14.217853       1 genericapiserver.go:557] Skipping API apiregistration.k8s.io/v1beta1 because it has no resources.
I0712 06:42:15.570306       1 dynamic_cafile_content.go:157] "Starting controller" name="request-header::/etc/kubernetes/pki/front-proxy-ca.crt"
I0712 06:42:15.570665       1 secure_serving.go:210] Serving securely on [::]:6443
I0712 06:42:15.570758       1 dynamic_serving_content.go:132] "Starting controller" name="serving-cert::/etc/kubernetes/pki/apiserver.crt::/etc/kubernetes/pki/apiserver.key"
I0712 06:42:15.589049       1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0712 06:42:15.589250       1 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
I0712 06:42:15.590190       1 cluster_authentication_trust_controller.go:440] Starting cluster_authentication_trust_controller controller
I0712 06:42:15.590289       1 shared_informer.go:255] Waiting for caches to sync for cluster_authentication_trust_controller
I0712 06:42:15.590893       1 dynamic_serving_content.go:132] "Starting controller" name="aggregator-proxy-cert::/etc/kubernetes/pki/front-proxy-client.crt::/etc/kubernetes/pki/front-proxy-client.key"
I0712 06:42:15.591271       1 apiservice_controller.go:97] Starting APIServiceRegistrationController
I0712 06:42:15.591359       1 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I0712 06:42:15.591968       1 apf_controller.go:317] Starting API Priority and Fairness config controller
I0712 06:42:15.592084       1 controller.go:83] Starting OpenAPI AggregationController
I0712 06:42:15.592172       1 controller.go:80] Starting OpenAPI V3 AggregationController
I0712 06:42:15.592482       1 customresource_discovery_controller.go:209] Starting DiscoveryController
I0712 06:42:15.592622       1 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
I0712 06:42:15.593421       1 available_controller.go:491] Starting AvailableConditionController
I0712 06:42:15.593515       1 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
I0712 06:42:15.596140       1 dynamic_cafile_content.go:157] "Starting controller" name="request-header::/etc/kubernetes/pki/front-proxy-ca.crt"
I0712 06:42:15.598624       1 autoregister_controller.go:141] Starting autoregister controller
I0712 06:42:15.598725       1 cache.go:32] Waiting for caches to sync for autoregister controller
I0712 06:42:15.626781       1 crdregistration_controller.go:111] Starting crd-autoregister controller
I0712 06:42:15.626895       1 shared_informer.go:255] Waiting for caches to sync for crd-autoregister
I0712 06:42:15.631566       1 controller.go:85] Starting OpenAPI controller
I0712 06:42:15.631602       1 controller.go:85] Starting OpenAPI V3 controller
I0712 06:42:15.631628       1 naming_controller.go:291] Starting NamingConditionController
I0712 06:42:15.631663       1 establishing_controller.go:76] Starting EstablishingController
I0712 06:42:15.631681       1 nonstructuralschema_controller.go:192] Starting NonStructuralSchemaConditionController
I0712 06:42:15.631759       1 apiapproval_controller.go:186] Starting KubernetesAPIApprovalPolicyConformantConditionController
I0712 06:42:15.631857       1 crd_finalizer.go:266] Starting CRDFinalizer
I0712 06:42:15.730229       1 shared_informer.go:262] Caches are synced for crd-autoregister
I0712 06:42:15.734170       1 shared_informer.go:262] Caches are synced for node_authorizer
I0712 06:42:15.746265       1 shared_informer.go:262] Caches are synced for cluster_authentication_trust_controller
I0712 06:42:15.746432       1 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I0712 06:42:15.751286       1 apf_controller.go:322] Running API Priority and Fairness config worker
I0712 06:42:15.793663       1 cache.go:39] Caches are synced for AvailableConditionController controller
I0712 06:42:15.798894       1 cache.go:39] Caches are synced for autoregister controller
I0712 06:42:16.300281       1 controller.go:132] OpenAPI AggregationController: action for item : Nothing (removed from the queue).
I0712 06:42:16.300303       1 controller.go:132] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
E0712 06:42:16.570491       1 controller.go:113] loading OpenAPI spec for "" failed with: APIService  does not exist for update
I0712 06:42:16.570510       1 controller.go:126] OpenAPI AggregationController: action for item : Rate Limited Requeue.
I0712 06:42:16.595899       1 storage_scheduling.go:111] all system priority classes are created successfully or already exist.
I0712 06:42:18.654205       1 controller.go:611] quota admission added evaluator for: leases.coordination.k8s.io
I0712 06:42:31.526997       1 controller.go:611] quota admission added evaluator for: serviceaccounts
I0712 06:42:43.680920       1 controller.go:611] quota admission added evaluator for: controllerrevisions.apps
I0712 06:42:43.829631       1 controller.go:611] quota admission added evaluator for: endpoints
I0712 06:42:43.882990       1 controller.go:611] quota admission added evaluator for: endpointslices.discovery.k8s.io
I0712 06:42:44.081376       1 controller.go:611] quota admission added evaluator for: replicasets.apps
I0712 06:42:45.047898       1 controller.go:611] quota admission added evaluator for: events.events.k8s.io
#### I have tried creating cluster using kubeadm about 5 times with different version v1.23.0 and v1.24.0. I am still getting the same error. Please help if anyone have any ideas? Thank you!

**Comment by neolit123** [comment]
/support

Hi thus seems like a request for support.

The apiserver going down can be due to a number of reasons. Node resources, container runtime problems, etc. Try looking at kubelet logs as well.

The node not ready problem is due to missing cni plugin. This step is part of all guides.
