### ISSUE TITLE
Kubedm init get version consultation

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubeadm#2729]
## Is this a BUG REPORT or FEATURE REQUEST?
We use kubedm to deploy k8s on the intranet, 
Why does `kubedm init` always get the version from the Internet by default instead of using local client version by default?

**Comment by neolit123** [comment]
this is by design since the early days of kubeadm so that it fetches the latest patch version of a release, which may include critical fixes.

please use the support channels for questions.
/support
