### ISSUE TITLE
feat: `kubeadm init`  or `kubeadm join` should be atomic

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubeadm#2736]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?

Currently, if `kubeadm init` failed for some reason, some files like manifest or certs will be left on disk, those file won't be cleanup unless we run `kubeadm reset` manually to revert the changes made by `kubeadm`. 

Revert the change made by `kubeadm` is needed so that we can try again after fixing the relevant issues, but we can make `kubeadm` more smart and cleanup those files when there is any issue found during `kubeadm init`, in other words, we can make `kubeadm init` an atomic operation, and let `kubeadm reset` focus on reset of a running cluster.

## What you expected to happen?

`kubeadm init`  or `kubeadm join` should be atomic.  

## Anything else we need to know?

/kind feature

**Comment by chendave** [comment]
@neolit123 @SataQiu @pacoxu  Just a rough idea, need to think more about this, do you have any inputs?

/assign

**Comment by neolit123** [comment]
hi, @chendave i don't exactly agree with this.
the requirement for reset to be called is part of the kubeadm design and is also present in other unix commands - i.e. one command does something and another does a cleanup after it. atomic has not been a design goal.

**Comment by chendave** [comment]
> i.e. one command does something and another does a cleanup after it.

So that cleanup command is called along with the command when this command failed, right?  `reset` is a separate process it's never got called unless we do that manually.

I am thinking about this like DB transaction, or some cleanup in the defer when we programming.

But if this is by design from the first beginning, I am fine with it, then all we need is some info printed on stdout to remind user to `reset`  if some errors is hit.

**Comment by pacoxu** [comment]
As we have already divided `init`/`jon` into phases, can we make the phase atomic?

Then we can add a suggested command to run `kubeadm init --skip-phases=step1,step2,step3` when step4 failed.

**Comment by neolit123** [comment]
> So that cleanup command is called along with the command when this command failed, right? reset is a separate process it's never got called unless we do that manually.

yes, it is a manual process.

> But if this is by design from the first beginning, I am fine with it, then all we need is some info printed on stdout to remind user to reset if some errors is hit.

kubeadm reset is mentioned as the "cleanup" command in the docs:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

>> [kubeadm reset](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/) to revert any changes made to this host by kubeadm init or kubeadm join

**Comment by neolit123** [comment]
> As we have already divided init/jon into phases, can we make the phase atomic?

i guess, making the phases as a whole atomic will be equivalent of making the whole command atomic.

**Comment by chendave** [comment]
close this per the feedback from @neolit123
