### ISSUE TITLE
incorrect unreleased version warning

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubeadm#2737]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.25.0-alpha.3.348+d046a58de435a0
- **Cloud provider or hardware configuration**: KIND
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): kindnetd
- **Others**:

## What happened?

The previous "possibly unreleased" version is printed instead of the current one (off-by-one error)

https://github.com/kubernetes-sigs/kind/pull/2846#issuecomment-1200754808

## What you expected to happen?

This line:
> WARNING: tolerating control plane version v1.25.0-alpha.3.348+d046a58de435a0, assuming that k8s version 1.24.0 is not released yet

Should read:
> WARNING: tolerating control plane version v1.25.0-alpha.3.348+d046a58de435a0, assuming that k8s version **1.25.0** is not released yet

## How to reproduce it (as minimally and precisely as possible)?

Run a kubeadm cluster with a pre-release Kubernetes version, I'm using kubernetes@d046a58de435a0

**Comment by neolit123** [comment]
looks like a bug.

**Comment by neolit123** [comment]
> looks like a bug.

or not?
https://github.com/kubernetes/kubernetes/blob/5b92e46b2238b4d84358451013e634361084ff7d/cmd/kubeadm/app/util/config/common.go#L120-L130

the validation problem happens when e.g. 1.24.0 is not released yet but the 1.25.0-alpha tag is already there on the master branch. we might just want to remove the warning to not confuse users and just return nil.

**Comment by BenTheElder** [comment]
the commit I'm using should be past of v1.24.0 which has already been released, it is a v1.25.0 prerelease.

v1.25.0-alpha is for v1.25.0, not v1.24.0, it shouldn't be printing the minimum control plane version, we could take the current version and drop the prerelease portion for that log mesessge, or drop that part of the log entirely.

**Comment by BenTheElder** [comment]
I might have misunderstood the intent, but if not https://github.com/kubernetes/kubernetes/pull/111615 is an attempt at logging what I think the intent was (drops the pre-release part to form a release version).

I've put a `/hold` on it because I'm not confident, the >= minimum version check makes sense, I'm not sure what the point of this check is other than the warning about tolerating a pre-release version.

**Comment by neolit123** [comment]
commented on the PR.

**Comment by BenTheElder** [comment]
/assign
/close
https://github.com/kubernetes/kubernetes/pull/111615

thanks!
