### ISSUE TITLE
kubeadm: do not include --container-runtime= and --pod-infra-container-image in KUBELET_KUBEADM_ARGS

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubeadm#2742]
kubeadm creates /var/lib/kubelet/kubeadm-flags.env with:

> KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock --pod-infra-container-image=k8s.gcr.io/pause:3.7"

The parameters `--container-runtime=remote ` and `--pod-infra-container-image` are deprecated, as seen by `kubelet --help`:
>  --container-runtime string                                 The container runtime to use. Possible value: 'remote'. (default "remote") (DEPRECATED: will be removed in 1.27 as the only valid value is 'remote')
> --pod-infra-container-image string                         Specified image will not be pruned by the image garbage collector. CRI implementations have their own configuration to set this image. (default "k8s.gcr.io/pause:3.7") (DEPRECATED: will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.)

```console
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.4-rc.0.14+3dc15e1cdde539", GitCommit:"3dc15e1cdde539e62c75342d516eacb2a9042ce1", GitTreeState:"clean", BuildDate:"2022-08-05T06:17:42Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by neolit123** [comment]
yes, this is known and we will remove the flags ftom kubeadm before they are removed from the kubelet. until then we need to keep the flags like that.

**Comment by McTrk** [comment]
Still there, see https://github.com/issues/created?issue=kubernetes%7Ckubeadm%7C3281
