### ISSUE TITLE
prometheus-cvimmon-monitor-cert-exporter - fails to start on CNI error 

### ISSUE THREAD

**Issue by kubebeginner** [kubernetes/kubeadm#2748]
## Versions

**Environment**:
- **Kubernetes version** (use `kubectl version`): v.1.17.8
- **OS** (e.g. from /etc/os-release): RHEL 8.4
- **Kernel** (e.g. `uname -a`):  4.18.0-193.70.1.el8_2.x86_64
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico

## What happened?

The pod service prometheus-cvimmon-monitor-cert-exporter fails to get restarted on particular master node and gets struck in Failed state.

Manually issuing the kubectl delete is able to restart the pod service.

 **Kubectl outputs**

NAMESPACE         NAME                                                             READY   STATUS               RESTARTS   AGE   IP                NODE               NOMINATED NODE   READINESS GATES
cvimmon-monitor   prometheus-cvimmon-monitor-cert-exporter-gz9lt                   0/1     **ContainerCannotRun**   1          13d   <none>            p3-tkymn-p1mon03   <none>           <none>

 kubectl describe pods prometheus-cvimmon-monitor-cert-exporter-gz9lt -n cvimmon-monitor
Name:           prometheus-cvimmon-monitor-cert-exporter-gz9lt
Namespace:      cvimmon-monitor
Priority:       0
Node:           p3-tkymn-p1mon03/172.19.126.102
Start Time:     Fri, 08 Jul 2022 13:49:47 +0900
Labels:         app=prometheus
                chart=prometheus-11.3.0
                component=cert-exporter
                controller-revision-hash=f659c5d7f
                heritage=Helm
                pod-template-generation=1
                release=prometheus-cvimmon-monitor
Annotations:    cni.projectcalico.org/podIP: 192.168.103.200/32
                cni.projectcalico.org/podIPs: 192.168.103.200/32
Status:         Running
IP:             
IPs:            <none>
Controlled By:  DaemonSet/prometheus-cvimmon-monitor-cert-exporter
Containers:
  prometheus-cert-exporter:
    Container ID:  docker://6d15e70e46f3c57bedee0687772ef14af5c676577618fca99626a8c9f9c0be08
    Image:         172.21.190.193:5000/cert-exporter:v2.3.0
    Image ID:      docker-pullable://172.21.190.193:5000/cert-exporter@sha256:8cd6bf087c7b12365c23b8078fefb1d7626f307b028b013209866e9b15e3290e
    Port:          8080/TCP
    Host Port:     8080/TCP
    Command:
      ./app
    Args:
      --alsologtostderr
      --include-cert-glob=/etc/kubernetes/pki/**/*.crt
      --include-cert-glob=/etc/kubernetes/pki/*.crt
      --secrets-include-glob=tls.crt
      --include-kubeconfig-glob=/etc/kubernetes/admin.conf
    State:          Terminated
      Reason:       ContainerCannotRun
      Message:      cannot join network of a non running container: 40d5b3b1f046251f4243c609c22836e5cb012fe7055ab20bbf0b0ae131306438
      Exit Code:    128
      Started:      Wed, 20 Jul 2022 10:31:51 +0900
      Finished:     Wed, 20 Jul 2022 10:31:51 +0900
    Ready:          False
    Restart Count:  1
    Liveness:       http-get http://:8080/metrics delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /etc/kubernetes from etcmount (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-cvimmon-monitor-cert-exporter-token-grc9p (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  etcmount:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes
    HostPathType:  
  prometheus-cvimmon-monitor-cert-exporter-token-grc9p:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-cvimmon-monitor-cert-exporter-token-grc9p
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type    Reason          Age                    From                       Message
  ----    ------          ----                   ----                       -------
  Normal  SandboxChanged  3m24s (x2481 over 8h)  kubelet, p3-tkymn-p1mon03  Pod sandbox changed, it will be killed and re-created.

**systemctl status kubelet.service**
* kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           `-10-kubeadm.conf
   Active: active (running) since Thu 2022-07-21 06:53:13 JST; 9h ago
     Docs: https://kubernetes.io/docs/
 Main PID: 1883788 (kubelet)
    Tasks: 118 (limit: 1645678)
   Memory: 175.2M
   CGroup: /system.slice/kubelet.service
           `-1883788 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --c>

Jul 21 15:58:18 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:18.413923 1883788 remote_runtime.go:128] StopPodSandbox "40d5b3b1f046251f4243c609c22836e5cb012fe7055ab20bbf0b0ae13130643>
Jul 21 15:58:18 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:18.413949 1883788 kuberuntime_manager.go:898] Failed to stop sandbox {"docker" "40d5b3b1f046251f4243c609c22836e5cb012fe7>
Jul 21 15:58:18 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:18.413983 1883788 kuberuntime_manager.go:676] killPodWithSyncResult failed: failed to "KillPodSandbox" for "a41d5c22-887>
Jul 21 15:58:18 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:18.414000 1883788 pod_workers.go:191] Error syncing **pod a41d5c22-887e-4674-ae31-ca0041f31d0e ("prometheus-cvimmon-monito>
**Jul 21 15:58:30 p3-tkymn-p1mon03 kubelet[1883788]: W0721 15:58:30.401963 1883788 cni.go:331] CNI failed to retrieve network **namespace path: cannot find network namespace for the termi>****
Jul 21 15:58:30 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:30.413623 1883788 cni.go:385] Error deleting cvimmon-monitor_prometheus-cvimmon-monitor-cert-exporter-gz9lt/40d5b3b1f046>**
Jul 21 15:58:30 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:30.413954 1883788 remote_runtime.go:128] StopPodSandbox "40d5b3b1f046251f4243c609c22836e5cb012fe7055ab20bbf0b0ae13130643>
Jul 21 15:58:30 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:30.413987 1883788 kuberuntime_manager.go:898] Failed to stop sandbox {"docker" "40d5b3b1f046251f4243c609c22836e5cb012fe7>
Jul 21 15:58:30 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:30.414023 1883788 kuberuntime_manager.go:676] killPodWithSyncResult failed: failed to "KillPodSandbox" for "a41d5c22-887>
Jul 21 15:58:30 p3-tkymn-p1mon03 kubelet[1883788]: E0721 15:58:30.414041 1883788 pod_workers.go:191] Error syncing pod a41d5c22-887e-4674-ae31-ca0041f31d0e ("prometheus-cvimmon-monito>
lines 1-22/22 (END)lines 1-22/22 (END)lines 1-22/22 (END)lines 1-22/22 (END)lines 1-22/22 (END)lines 1-22/22 (END)
[root@p3-tkymn-p1mon03 ~]# 

**Kubectl logs** 
Aug 13 10:13:51 p3-tkymn-p1mon03 kubelet[2711899]: W0813 10:13:51.499048 2711899 cni.go:331] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "40d5b3b1f046251f4243c609c22836e5cb012fe7055ab20bbf0b0ae131306438"
**Aug 13 10:13:51 p3-tkymn-p1mon03 kubelet[2711899]: E0813 10:13:51.510950 2711899 cni.go:385] Error deleting cvimmon-monitor_prometheus-cvimmon-monitor-cert-exporter-gz9lt/40d5b3b1f046251f4243c609c22836e5cb012fe7055ab20bbf0b0ae131306438 from network calico/k8s-pod-network: could not teardown ipv4 dnat: running [/usr/sbin/iptables -t nat -N CNI-DN-f5ecedb6ae747f19c82d0 --wait]: exit status 1: iptables: Chain already exists.**
Aug 13 10:13:51 p3-tkymn-p1mon03 kubelet[2711899]: E0813 10:13:51.511505 2711899 remote_runtime.go:128] StopPodSandbox "40d5b3b1f046251f4243c609c22836e5cb012fe7055ab20bbf0b0ae131306438" from runtime service failed: rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod "prometheus-cvimmon-monitor-cert-exporter-gz9lt_cvimmon-monitor" network: could not teardown ipv4 dnat: running [/usr/sbin/iptables -t nat -N CNI-DN-f5ecedb6ae747f19c82d0 --wait]: exit status 1: iptables: Chain already exists.
Aug 13 10:13:51 p3-tkymn-p1mon03 kubelet[2711899]: E0813 10:13:51.511556 2711899 kuberuntime_gc.go:170] Failed to stop sandbox "40d5b3b1f046251f4243c609c22836e5cb012fe7055ab20bbf0b0ae131306438" before removing: rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod "prometheus-cvimmon-monitor-cert-exporter-gz9lt_cvimmon-monitor" network: could not teardown ipv4 dnat: running [/usr/sbin/iptables -t nat -N CNI-DN-f5ecedb6ae747f19c82d0 --wait]: exit status 1: iptables: Chain already exists.
Aug 13 10:13:56 p3-tkymn-p1mon03 kubelet[2711899]: W0813 10:13:56.934768 2711899 cni.go:331] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "a9f953e673accb89d2c0ad8d0942d49fece054423e7f5afe03798d7fd6b71957"
Aug 13 10:13:56 p3-tkymn-p1mon03 kubelet[2711899]: E0813 10:13:56.946444 2711899 cni.go:385] Error deleting cvimmon-monitor_prometheus-cvimmon-monitor-cert-exporter-fp4qw/a9f953e673accb89d2c0ad8d0942d49fece054423e7f5afe03798d7fd6b71957 from network calico/k8s-pod-network: could not teardown ipv4 dnat: running [/usr/sbin/iptables -t nat -N CNI-DN-987163815b20de7f061ff --wait]: exit status 1: iptables: Chain already exists.

## What you expected to happen?
Pod service to be restarted without any issues. 

The node hardware resources are well within the limits. 
Did not find any relevant materials to further debug the issue . Need help to debug/ resolve the issue.

**Comment by pacoxu** [comment]
it seems to be not related to kubeadm. It sounds like a calico issue.

**Comment by neolit123** [comment]
yes, please try contracting the owners of the failing component or ask for help on the support channels.

/support
