### ISSUE TITLE
Make it possible to use admin.conf for input to kubeadm init?

### ISSUE THREAD

**Issue by leah03** [kubernetes/kubeadm#275]
Can I just use my own admin.conf before kubeadm init and after that kubeadm will use the file for authorization? This will be really convenient for accessing this cluster outside it because I don't need to process the certs and keys each time.

**Comment by fabriziopandini** [comment]
Might be I can help here

If you can copy a ca.key and a ca.crt used to sign your admin.conf file under /etc/kubernetes/pki before running kubeadm, kubeadm won't generate a new ca, an thus your admin.conf will work also on the new cluster

**Comment by luxas** [comment]
It's very hard to do this because the CA private key is not in the admin.conf file, so it can't be extracted just like that. You will have to touch certs in any case.

@leah03 Can you provide more information about your use-case please?

**Comment by luxas** [comment]
@leah03 In v1.8, you can now generate certs/kubeconfig files in beforehand by executing `kubeadm alpha phase certs all` and `kubeadm alpha phase kubeconfig all` and then moving over the `/etc/kubernetes` directory to the master where you're then running `kubeadm init`.
By doing that, you will be able to re-use your certs/credentials.
