### ISSUE TITLE
"/etc/kubernetes/pki/sa.key isn't in RSA format" error when using ECDSA certs

### ISSUE THREAD

**Issue by inflatador** [kubernetes/kubeadm#2756]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** :

```kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"archive", BuildDate:"2022-08-18T00:00:00Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"archive", BuildDate:"2022-08-18T00:00:00Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}```
- **Cloud provider or hardware configuration**: KVM virtual machine 
- **OS** (e.g. from /etc/os-release): Fedora Linux 36 (Cloud Edition)
- **Kernel** (e.g. `uname -a`): 5.19.8-200.fc36.x86_64
- **Container runtime (CRI)** (e.g. containerd, cri-o): cri-o
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico
- **Others**: Using existing ECDSA CA cert/key as described [in the docs](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#custom-certificates): 
"copy an existing CA...and kubeadm will use this CA for signing the rest of the certificates."

## What happened?

After bootstrapping the initial control-plane node, attempting to join other control-plane nodes via `kubeadm join` fails with an error: `the private key file /etc/kubernetes/pki/sa.key isn't in RSA format`

## What did you expect to happen?

The control-plane node should join the existing cluster.

## How to reproduce it (as minimally and precisely as possible)?

- On the first control-plane node, copy existing ECDSA CA cert/key into `/etc/pki/kubernetes` 

- On the first control-plane node, bootstrap a cluster with `kubeadm init --feature-gates PublicKeysECDSA=true  ...`

- Copy all cert and key files generated by `kubeadm init` to the second control-plane node's /etc/kubernetes/pki directory

- On the second control-plane node, attempt to join the cluster using `kubeadm join ...`

## Anything else we need to know?

I can confirm that the `sa.key` and `sa.pub` files generated by `kubeadm init` are both ECDSA, and they match each other.

**Comment by neolit123** [comment]
> --feature-gates PublicKeysECDSA=true

note this is alpha  / experimental and not recommended for production clusters.
we might change how it works and make it a toggle in the kubeadm --config, instead of force graduating it to always ON by default.

> On the second control-plane node, attempt to join the cluster using kubeadm join ...

+

> the private key file /etc/kubernetes/pki/sa.key isn't in RSA format

might be a problem where the ECDSA feature gate is not checked during "join" and the cert validation fails.
can you show join logs with --v=5?

**Comment by inflatador** [comment]
Hey, thanks so much for the quick reply!
As requested, [here are the join logs](https://gist.github.com/inflatador/7f0d822e402faf45cd3d4d028b426895) .

> might be a problem where the ECDSA feature gate is not checked during "join" and the cert validation fails.

Let me know if there is an existing flag for that, I tried including `--feature-gates PublicKeysECDSA=true` in my `kubeadm join` command, but that didn't seem to work.

**Comment by neolit123** [comment]
i think the error is happening here when checking if the sa.* can be loaded:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/certs/certs.go#L485-L490

they the function to load public/private key only supports RSA:
https://github.com/kubernetes/kubernetes/blob/02ac8ac4181e179c2f030a9f8b1abef0d9a0b512/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L350-L377

unless there is a limitation here of which i am not aware of, we should just allow the function to pass if the private key is ECDSA?

i.e. removing this check:
```
	// Allow RSA format only
	k, ok := privKey.(*rsa.PrivateKey)
	if !ok {
		return nil, nil, fmt.Errorf("the private key file %s isn't in RSA format", privateKeyPath)
	}
```

if someone wishes to test this please go ahead, as i won't be able to in the next ~1 week.

/help

**Comment by neolit123** [comment]
@SataQiu this is blocking bug for a feature, so perhaps we should backport to tte supported releases. wdyt?

**Comment by SataQiu** [comment]
> @SataQiu this is blocking bug for a feature, so perhaps we should backport to the supported releases. wdyt?

Yes, I think it's reasonable, I'll cherry-pick it to 1.25, 1.24 and 1.23 branch.
