### ISSUE TITLE
kube-proxy is not proxying

### ISSUE THREAD

**Issue by JedenPies2** [kubernetes/kubeadm#276]
**kubeadm version** (use `kubeadm version`): kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: VMware virtual machine
- **OS** (e.g. from /etc/os-release): Oracle Linux Server release 7.3
- **Kernel** (e.g. `uname -a`): Linux 3.10.0-514.10.2.el7.x86_64 
- **Others**:

## What happened?
Install kubernetes cluster with kubeadm and kube-proxy is not proxying. I followed instructions in https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ but couldn´t get proxy to work.

I have this service:
kubectl get svc hostnames
NAME        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
hostnames   10.106.180.119   <none>        80/TCP    49m

but curl 10.106.180.119:80 is not working.

iptables-save |grep hostnames
-A KUBE-SEP-AJ5CYLJ5NPFKNEWC -s 10.44.0.4/32 -m comment --comment "default/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-AJ5CYLJ5NPFKNEWC -p tcp -m comment --comment "default/hostnames:" -m tcp -j DNAT --to-destination 10.44.0.4:9376
-A KUBE-SEP-EXC5A6AH5JY7IQDI -s 10.36.0.4/32 -m comment --comment "default/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-EXC5A6AH5JY7IQDI -p tcp -m comment --comment "default/hostnames:" -m tcp -j DNAT --to-destination 10.36.0.4:9376
-A KUBE-SEP-LPP5T7DQ4E6XTYNJ -s 10.36.0.5/32 -m comment --comment "default/hostnames:" -j KUBE-MARK-MASQ
-A KUBE-SEP-LPP5T7DQ4E6XTYNJ -p tcp -m comment --comment "default/hostnames:" -m tcp -j DNAT --to-destination 10.36.0.5:9376
-A KUBE-SERVICES -d 10.106.180.119/32 -p tcp -m comment --comment "default/hostnames: cluster IP" -m tcp --dport 80 -j KUBE-SVC-NWV5X2332I4OT4T3
-A KUBE-SVC-NWV5X2332I4OT4T3 -m comment --comment "default/hostnames:" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-EXC5A6AH5JY7IQDI
-A KUBE-SVC-NWV5X2332I4OT4T3 -m comment --comment "default/hostnames:" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-LPP5T7DQ4E6XTYNJ
-A KUBE-SVC-NWV5X2332I4OT4T3 -m comment --comment "default/hostnames:" -j KUBE-SEP-AJ5CYLJ5NPFKNEWC

## What you expected to happen?
Start to work with kube-poxy service

**Comment by timothysc** [comment]
Did you check your firewall settings?

**Comment by jeffie9** [comment]
I have been following the same trail of creating a cluster with kubeadm and executing the steps in debugging-services (created hostnames deployment and searching in DNS).  Here is an observation:
Running iptables-save | grep hostnames on the master node yields no results, but running the same command inside the kube-proxy pod will show all the expected entries.
My conclusion is the proxy service is listening and writing but in the wrong place.  Is it possible to get the kube-proxy to write to the node's iptables?  I am wondering if I need to add a hostPath or two to get it working.

**Comment by luxas** [comment]
Closing this; I think it should be working well in v1.8
If not, please reopen @JedenPies2.
Thanks!
