### ISSUE TITLE
kubeapi server ignores manifest changes

### ISSUE THREAD

**Issue by jseparovic** [kubernetes/kubeadm#2763]
## What keywords did you search in kubeadm issues before filing this one?
is:issue kubeapi manifest 

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT
## Versions

**kubeadm version** (use `kubeadm version`):
`kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:50:04Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

- **Cloud provider or hardware configuration**: Baremetal, kubelet
- **OS** (e.g. from /etc/os-release): AlmaLinux 8.6 (Sky Tiger)
- **Kernel** (e.g. `uname -a`): 4.18.0-372.19.1.el8_6.x86_64
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): weave
- **Others**:

## What happened?
After updating `/etc/kubernetes/manifests/kube-apiserver.yaml` and adding `--feature-gates=MixedProtocolLBService=true` to the command array, the apiserver pod restarts as expected. However, upon restart, it does not update the command when inspecting with kubectl get pod -o=yaml or ps -ef.
I do notice that if I change the name of the pod in the manifest, then this new pod does have the updated command, but the old pod is not removed, so they both run and conflict with each other.

## What you expected to happen?
I expected the apiserver to restart and the new command arg to be present in the pod output and ps -ef output.

## How to reproduce it (as minimally and precisely as possible)?
Add `--feature-gates=MixedProtocolLBService=true` to `/etc/kubernetes/manifests/kube-apiserver.yaml`
run kubectl -n kube-system get pod/kube-apiserver-$(hostname) -o=yaml
You will see that the command list does not include the new argument.

## Anything else we need to know?
No, just that changing the pod name exhibits the correct behaviour in the new pod, but the old pod is not removed, so they conflict.

**Comment by neolit123** [comment]
hi, this is technically something that the kubelet handles and not kubeadm. the kubelet by default does a diff of a manifest file every 40 seconds. if it changes the static pod is retreated.
 
i doubt the container command line change is not reflected as this is something that presumably users do all the time.

closing as support ticket. you might get better responses in the #kubernetes-users channel on k8s slack.

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support

**Comment by neolit123** [comment]
if you are _really_ sure there is a bug, please log an issue in k/k

**Comment by jseparovic** [comment]
> i doubt the container command line change is not reflected as this is something that presumably users do all the time.

Don’t know what to tell you but the pod command line doesn’t change. Why would I make that up?

**Comment by neolit123** [comment]
it would be odd. as i mentioned earlier the kublet static pod logic recreates a pod on any manifest diff (i.e. file bytes changed). it does not watch only parts of the manifest like container command line.

but

> if you are _really_ sure there is a bug, please log an issue in kubernetes/kubernetes

**Comment by jseparovic** [comment]
I would go further than odd, and say it’s infuriating, lol. I’m just reporting what I saw. I wish it just worked so I don’t have to waste any more time on it. I’ll try it again on a second cluster and create a bug in k/k if it persists. Cheers

**Comment by jseparovic** [comment]
@neolit123 Same issue on a second cluster:
```
[root@master1.kube3 ~]$ cat /etc/kubernetes/manifests/kube-apiserver.yaml | grep MixedProtocolLBService
    - --feature-gates=MixedProtocolLBService=true
[root@master1.kube3 ~]$ ksg pod/kube-apiserver-master1.kube3 -o=yaml | grep MixedProtocolLBService
[root@master1.kube3 ~]$ ksg pod/kube-apiserver-master1.kube3
NAME                                      READY   STATUS    RESTARTS   AGE
kube-apiserver-master1.kube3   1/1     Running   6          48d
[root@master1.kube3 ~]$ ksx pod kube-apiserver-master1.kube3
pod "kube-apiserver-master1.kube3" deleted
[root@master1.kube3 ~]$ ksg pod/kube-apiserver-master1.kube3
NAME                                      READY   STATUS    RESTARTS   AGE
kube-apiserver-master1.kube3   1/1     Running   6          8s
[root@master1.kube3 ~]$ ksg pod/kube-apiserver-master1.kube3 -o=yaml | grep MixedProtocolLBService
[root@master1.kube3 ~]$ cat /etc/kubernetes/manifests/kube-apiserver.yaml | grep MixedProtocolLBService
    - --feature-gates=MixedProtocolLBService=true
[root@master1.kube3 ~]$
```
