### ISSUE TITLE
Bare metal --apiserver-advertise-address is not workong.

### ISSUE THREAD

**Issue by Davidnovarro** [kubernetes/kubeadm#2764]
## Versions
**Environment**:
- **kubeadm version** v1.25.2:
- **Kubernetes version** v1.25.2:
- **Bare Metal server**:  
- **OS**  Ubuntu 20.04.5 LTS:
- **Container runtime (CRI)** containerd:
- **Container networking plugin (CNI)** Calico:

## What happened?
I've initied kubeadm with --apiserver-advertise-address but the EXTERNAL-IP is  none

Init command issued
  kubeadm init --apiserver-advertise-address=$EXTERNAL_IP --pod-network-cidr=192.168.0.0/16

**Comment by neolit123** [comment]
please try asking on the support channels

/support
