### ISSUE TITLE
sudo kubeadm join 10.0.2.15:6443 --token zqss0q.y7hsu227c5ymeb19 \ >         --discovery-token-ca-cert-hash sha256:27907eaae5d0fd5c8509f9b505e92b87da211631fd5352918c3ba5c9c3855bf9 [preflight] Running pre-flight checks error execution phase preflight: couldn't validate the identity of the API Server: Get "https://10.0.2.15:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp 10.0.2.15:6443: connect: connection refused To see the stack trace of this error execute with --v=5 or higher

### ISSUE THREAD

**Issue by nanmegnealain** [kubernetes/kubeadm#2774]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

**Comment by neolit123** [comment]
responded here
https://github.com/kubernetes/kubeadm/issues/2775
