### ISSUE TITLE
identity of the API Server

### ISSUE THREAD

**Issue by nanmegnealain** [kubernetes/kubeadm#2775]
[preflight] Running pre-flight checks
error execution phase preflight: couldn't validate the identity of the API Server: Get "https://10.0.2.15:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp 10.0.2.15:6443: connect: connection refused
To see the stack trace of this error execute with --v=5 or higher

**Comment by neolit123** [comment]
please use the support channels
/support
