### ISSUE TITLE
the kubeadm had this path since the early days of containerd. perhaps it changed at some point.

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubeadm#2779]
the kubeadm had this path since the early days of containerd. perhaps it changed at some point.

_Originally posted by @neolit123 in https://github.com/kubernetes/kubernetes/pull/112136#discussion_r1015552261_

**Comment by neolit123** [comment]
i don't think we should change it though

**Comment by pacoxu** [comment]
This is a Linux behavior.
https://unix.stackexchange.com/a/175349/373902

> Modern Linux distributions include a /run directory as a temporary filesystem (tmpfs) which stores volatile runtime data, following the FHS version 3.0. According to the FHS version 2.3, this data should be stored in /var/run but this was a problem in some cases because this directory isn't always available at early boot. As a result, these programs have had to resort to trickery, such as using /dev/.udev, /dev/.mdadm, /dev/.systemd or /dev/.mount directories, even though the device directory isn't intended for such data. Among other advantages, this makes the system easier to use normally with the root filesystem mounted read-only.

And kubeadm is not running at very early boot, this should not be an issue.
For containerd and kubelet, we's better use `/run`.

**Comment by neolit123** [comment]
> Until now, we did not get not issues that are related. (no bad effects yet).

i think that's because containerd writes both socket paths for some reason on linux. if we want to change the kubeadm default we need to figure out how to migrate users - i.e. figure out if this is a breaking change to user setups.
