### ISSUE TITLE
kubeadm add flag to enable parallel image pulling by default

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubeadm#2780]
+0 to have tools such as `kubeadm` manage the value of that flag

_Originally posted in https://github.com/kubernetes/kubernetes/issues/108405#issuecomment-1056029579_
      

This is a custom flag of kubelet and in rancher, they already switch to enable it by default.

Several ways we can promote parallel image pulling
1. we may enable it by default without a flag
2. we may use a flag to enable it, and now default to false, and change it to true once we think it is ready. (Or directly default to enable it, and leave a flag for users concerned about it to disable it.)
3. we may always use the kubelet default value here and wait for sig-node decisions.

/kind feature

---------------

edit by neolit123

API change proposal here:
https://github.com/kubernetes/kubeadm/issues/2780#issuecomment-1874234408

```
what we can do in kubeadm is to add an API field that controls the kubeadm image pulls to be parallel (crictl ...), NOT the kubelet pulls.
it can be NodeRegistration.ImagePullSerial: true for Init|joinConfiguration (we already have imagePullPolicy there) and the default to be true, no such field will be in ResetConfiguration . kubeadm config images uses InitConfiguration.
for UpgradeConfiguration doesn't have NodeRegistration, so there we can have it a top level.

if people are +1 to the above we can add this new field to v1beta4.
if you don't like the ImagePullSerial name please suggest something else.
```

v1beta4 PRs
- https://github.com/kubernetes/kubernetes/pull/122616 (init/join configuration)
- TODO upgrade configuration

**Comment by neolit123** [comment]
do you think this is the default all users want?
i think its ok to add a flag that is true by default and also add a noderegistrationoptions field for api version "next"

@SataQiu wdyt?

**Comment by SataQiu** [comment]
I'm +1 for adding a `NodeRegistrationOptions` field to control this feature.
Given that currently users can achieve it by setup `KubeletExtraArgs`, I'm not sure if we need to add a flag for `kubeadm` now.

**Comment by pacoxu** [comment]
> do you think this is the default all users want?

My key point here is to set it by default like Rancher and some other kube-installers.

**Comment by frederiko** [comment]
> I'm +1 for adding a `NodeRegistrationOptions` field to control this feature. Given that currently users can achieve it by setup `KubeletExtraArgs`, I'm not sure if we need to add a flag for `kubeadm` now.

Is anyone working on this? If no one is, I would like to take a crack at it to contribute back. Please let me know. Thanks.

**Comment by pacoxu** [comment]
@frederiko the final solution is not decided yet.

Either is OK now. I hope the 1 can happen soon. See more at https://github.com/kubernetes/kubernetes/issues/108405#issuecomment-1056029579.
1. wait for sig-node status on https://github.com/kubernetes/enhancements/issues/3673 or  Parallel Image Pulls becomes a default behavior.
2. as Lubomir and Sata pointed out, users can gain this with  NodeRegistrationOptions.KubeletExtraArgs. This is the current status and a suggested way now.
3. add a flag to disable it and enable `Parallel Image Pulls` by default: this is my proposal, but no agreement was reached.

**Comment by neolit123** [comment]
since kubeadm shells to crictl during config images pull, init, join, upgrade, etc... we could add a kubeadm option in config and flag to opt out of parallel pulls.

at least this is my understanding? kubelet pulls are a separate feature and be controlled with kubelet config and flag.

**Comment by frederiko** [comment]
> @frederiko the final solution is not decided yet.
> 
> 
> 
> Either is OK now. I hope the 1 can happen soon. See more at https://github.com/kubernetes/kubernetes/issues/108405#issuecomment-1056029579.
> 
> 1. wait for sig-node status on https://github.com/kubernetes/enhancements/issues/3673 or  Parallel Image Pulls becomes a default behavior.
> 
> 2. as Lubomir and Sata pointed out, users can gain this with  NodeRegistrationOptions.KubeletExtraArgs. This is the current status and a suggested way now.
> 
> 3. add a flag to disable it and enable `Parallel Image Pulls` by default: this is my proposal, but no agreement was reached.

I see. I may have misread it here. I thought a config would be added and a decision about leaving it on or off would be done at later point, following whichever direction sig-node goes, option 3 in such case.

**Comment by neolit123** [comment]
looking at the history in:
https://github.com/kubernetes/kubernetes/pull/114552

i think we should not make kubeadm deploy a kubelet with `KubeletCopnfiguration.serializeImagePulls = false`. if the kubelet eventually decides to default to `serializeImagePulls = false`, all kubeadm users will benefit from that new default behavior. generaly kubeadm tries to deploy all components with their default configuration. there are a few minor exceptions, of course, like enabling the NodeRestriction controller, bootstrap tokens, and some other things. 

changing defaults is not great, because you break an API contract - users with slow connections expect one pull at a time, but then they might not be happy with a parallel pull.

what we can do in kubeadm is to add an API field that controls the kubeadm image pulls to be parallel (`crictl ...`).
it can be `NodeRegistration.ImagePullSerial: true` for `Init|joinConfiguration` (we already have `imagePullPolicy` there) and the default to be `true`, not such field will be in ResetConfiguration . `kubeadm config images uses InitConfiguration.
for UpgradeConfiguration doesn't have NodeRegistration, so there we can have it a top level.

if people are +1 to the above we can add this new field to v1beta4.
if you don't like the `ImagePullSerial` name please suggest something else.

**Comment by pacoxu** [comment]
For kubelet side, we may wait for the progress and it may be a long journey. 

+0.5 for the proposal. Then we may rename this issue to be something like
```
`kubeadm config images pull` will use the new flag to decide to pull in parallel or not.
```

For parallel image pulling, the most concerned issue is that the disk will in heavy load if we pull many images at a time.
- However, for kubeadm during init and join/upgrade, the node is already in a maintenance mode, and heavy io is acceptable.

**Comment by neolit123** [comment]
looks like we forgot to add ImagePull* controls to UpgradeConfiguration

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go#L261-L271
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go#L732-L755

cc @calvin0327 

currently we pull images on upgrade during preflight for "node" and "apply" so we should allow the same config as in "init" and "join", we should finish this for 1.31.

**Comment by pacoxu** [comment]
Yes. `NodeRegistration.imagePullPolicy` is only used in init/join configuration.

/priority important-soon
/remove-priority backlog
Can we tag with important-soon as we will finish it in v1.31?

**Comment by neolit123** [comment]
> Yes. NodeRegistration.imagePullPolicy is only used in init/join configuration.

we shouldn't add noderegistration in upgrad config, but the two options for image policy and parallel pul can be either in:
- top level upgrade config
- only in apply and node configuration (i tend to prefer this option)
-
