### ISSUE TITLE
component config is overwritten after upgrading by kubeadm

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubeadm#2785]
## Is this a BUG REPORT or FEATURE REQUEST?

Let's have a discussion here first, 

Suppose I have a config file with cluster config or init config, and upgrade the cluster by the following command, 

```
kubeadm upgrade apply xxx --config=xxx
```

the config file is valid, and contains either cluster config, init config or both of them, the cluster could be upgrade successfully at the end, but one thing I noticed was that if the it's not a default component config, e.g. I have proxy mode configured as "ipvs" for `kube-proxy`, then the config for the `kube-proxy` will be overwritten at the end by a default config.

```diff
43c43
<     mode: ""
---
>     mode: "ipvs"
```

I read the comment above the related code, 
```golang
	// If there are kubeadm types (API group kubeadm.kubernetes.io) present, we need to keep the existing behavior
	// here. Basically, we have to load all of the configs from the file and none from the cluster. Configs that are
	// missing from the file will be automatically regenerated by kubeadm even if they are present in the cluster.
	// The resulting configs overwrite the existing cluster ones at the end of a successful upgrade apply operation.
	if isKubeadmConfigPresent(docmap) {
		klog.Warning("WARNING: Usage of the --config flag with kubeadm config types for reconfiguring the cluster during upgrade is not recommended!")
		cfg, err := configutil.BytesToInitConfiguration(configBytes)
		return cfg, true, err
	}
```

But I still think we shouldn't overwritten a valid component config by a default one as the user will lost his configuration and some  inconsistent behavior might caused by  this.

what do you think?  @neolit123 @SataQiu @pacoxu 

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

**Comment by chendave** [comment]
> As the warning show, I would suggest that user should edit configmap to what he like and run kubeadm upgrade

We need to remove the warning when we have a upgrade API ready, and pass a config file for upgrade.

**Comment by neolit123** [comment]
> kubeadm upgrade apply xxx --config=xxx

--config in its current state, allowing init/cluster config during apply is legacy and unsupported. see the warning it throws. it can result in undefined behavior, yet we kept it because there were some consumers.

supporting --config with an UpgradeConfiguration is what we can do in the future.

i don't see a bug, given we claim unsupported in k8s focs and cli warning.

**Comment by neolit123** [comment]
> We need to remove the warning when we have a upgrade API ready, and pass a config file for upgrade.

yes, but we don't need to track it in this issue. it will be part of the upgradeconfiguration work.

**Comment by chendave** [comment]
> I would suggest that the user should edit configmap to what he likes and run kubeadm upgrade

Do you mean also provide the config for those two component in the config file as well? or else I cannot see how to edit the configmap.

Of cause, user can backup the configmap and restore it manually after upgrade is done.

**Comment by pacoxu** [comment]
> Do you mean also provide the config for those two component in the config file as well? or else I cannot see how to edit the configmap.

I mean `kubectl edit cm xx`.


> Of cause, user can backup the configmap and restore it manually after upgrade is done.

If a user wants to use a new config to upgrade, why not save it to configmap?
- You want to use a new configuration to override the current configuration(saved in configmap). However, you want to restore it after the upgrade. Why?
- - after upgrade, if you restore the configmap, the configmap will be inconsistent with the cluster configuration.(This will make users confused.)

**Comment by chendave** [comment]
@pacoxu the point of this issue is that the configmap will be overwritten after the upgrade for the specific case I described, so whether you edit configmap or not *before* upgrade will doesn't take any difference.

the reason why we need to restore the configmap is it's not the configmap that was used before upgrade, any customized config on the configmap before the upgrade will be lost after upgrading.

I agree we already have logs to warn that, but this is a potential issue that could caused problem after cluster's upgrade.

Let's close this issue, and I already removed the warn in the PR: https://github.com/kubernetes/kubernetes/pull/114062, something I think we need to add for the new API is trying to fetch the configmap from cluster for whatever the case is instead of a default one.

/close

**Comment by pacoxu** [comment]
To summarize, I think there are two practices now. 

Suggested One:
1. edit configmap to what you like
2. upgrade without `--config`

Another way that can work smoothly(maybe no best practice):
1. get configmap from cluster to a `cluster.yaml` file
2. edit `cluster.yaml` to what you like
3. upgrade with `--config cluster.yaml` and this `cluster.yaml` will override the configmap
- - you will get a warning as this is not the preferred but valid way. (Now and before version)
- - with PR https://github.com/kubernetes/kubernetes/pull/114062 is merged, UpgradeConfiguration is added. No warning is needed for `UpgradeConfiguration`. And there will be a deprecated warning for other configurations.
