### ISSUE TITLE
[discussion] The precedence of flag and config 

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubeadm#2786]
## Is this a BUG REPORT or FEATURE REQUEST?

File this issue for tracking purpose and also hoping to generate some comments on this.

Currently, kubeadm has a different view for the case when both the flag and config has been set for a specific option,  it suggests that flag should always take precedence over the config, here is one example, 

```golang  
// k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/common.go

	// If features gates are passed to the command line, use it (otherwise use featureGates from configuration)
	if flags.featureGatesString != "" {
		cfg.FeatureGates, err = features.NewFeatureGate(&features.InitFeatureGates, flags.featureGatesString)
		if err != nil {
			return nil, nil, nil, errors.Wrap(err, "[upgrade/config] FATAL")
		}
	}
```

But this seems is not align with other major services of kubernetes, e.g. scheduler or kube-proxy, flags will be ignored if the config file is provided.

I created an issue (https://github.com/kubernetes/kubernetes/issues/107156) for that long time ago, and final action (https://github.com/kubernetes/kubernetes/pull/107157)  is just add some comments for these options and just say they will be ignored when the config file is provided.

Here is also a reference link for the related discussion (https://github.com/kubernetes/kubernetes/pull/101273#issuecomment-823357862).

So, my question is shall we continue to stick to the legacy way to handle the case when both the flag and config are provided, or shall we move to align with the other major services in kubernetes?

@neolit123 @SataQiu @pacoxu ?

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

**Comment by neolit123** [comment]
afaik, the common way of doing flags vs config even outside of k8s is for flags to override config or to not allow mixtures. kubeadm and kubelet are doing similar. Kubeproxy and scheduler had a number of issues around doing the opposite. for example - no simple way of feeding instance specific options.

unfortunately the working group called "component standard" disbanded before we standardized across components, especially around the topic of instance specific config. also unfortunately, any change in this space is quite breaking to users.

i think kubeadm should continue following its current approach.

**Comment by chendave** [comment]
Really glad to know the context around this! thanks for the feedback. @neolit123  👍 

/close
