### ISSUE TITLE
missing cri-socket flag for upload-certs phase

### ISSUE THREAD

**Issue by Teresajw** [kubernetes/kubeadm#2791]
<h1>Problem encountered<h1>
<h2>kubelet、kubeadm、kubeclt version</h2>
kubelet v1.25.5、kubeadm v1.25.5、kubeclt v1.25.5
<h2>First-command: kubeadm init phase upload-certs --upload-certs</h2>
<h3>description:</h3>When I use kubeadm init phase upload certs -- upload certs to upload a certificate, I am prompted that I have not specified criSocket. 
<h3>result:</h3>[root@k8s-master-01 ~]# kubeadm init phase upload-certs --upload-certs
Found multiple CRI endpoints on the host. Please define which one do you wish to use by setting the 'criSocket' field in the kubeadm configuration file: unix:///var/run/containerd/containerd.sock, unix:///var/run/cri-dockerd.sock
To see the stack trace of this error execute with --v=5 or higher
<h2>second-command: kubeadm init phase upload-certs --upload-certs --cri-socket unix:///var/run/cri-dockerd.sock </h2>
<h3>description:</h3>When I add -- criSocket= unix:///var/run/cri-dockerd.socket After that, I am prompted that there is no -- cri socket parameter
<h3>result:</h3>unknown flag: --cri-socket

**Comment by Teresajw** [comment]
> we can add the --cri-socket param to this phase, but you can also pass --config with InitConfiguration.noderegistrationoptions.crisocket check the v1beta3 api docs.
> 
> in fact using config is always preferred.

>Thanks for the answer. However, this parameter does not take effect. It is prompted that this option is not available. The command prompt given in the reference is like this. This parameter is not included
>Look at the figure below，it has no parameter  as --cri-socket ,not only one ,The kubeadm init phase subcommand does not include
![image](https://user-images.githubusercontent.com/39899297/207258752-6dd13a08-5388-4da4-97ef-8ec4f9ac61a5.png)

**Comment by SataQiu** [comment]
/assign
will add the --cri-socket param to this phase

**Comment by Teresajw** [comment]
> /assign will add the --cri-socket param to this phase
> no this param
![image](https://user-images.githubusercontent.com/39899297/207261063-79c20a45-ff3b-4e60-84c5-76b9c947aa06.png)

**Comment by SataQiu** [comment]
@Teresajw 
After https://github.com/kubernetes/kubernetes/pull/114443 merged, the `--cri-socket` flag will be available.
For now, you can use configuration to achieve it, like this:
```sh
cat <<EOF > kubeadm-init-config
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
EOF

kubeadm init phase upload-certs --upload-certs --config kubeadm-init-config
```

**Comment by Teresajw** [comment]
Many subcommands of kubeadm init phase does not have -- cri socket flag ,It can be repaired together
 for example
 kubeadm init phase certs apiserver

**Comment by Teresajw** [comment]
> @Teresajw[kubernetes/kubernetes#114443](https://github.com/kubernetes/kubernetes/pull/114443)合并 后，`--cri-socket`flag 将可用。 现在，您可以使用配置来实现它，如下所示：
> 
> ```shell
> cat <<EOF > kubeadm-init-config
> apiVersion: kubeadm.k8s.io/v1beta3
> kind: InitConfiguration
> nodeRegistration:
>   criSocket: unix:///var/run/containerd/containerd.sock
> EOF
> 
> kubeadm init phase upload-certs --upload-certs --config kubeadm-init-config
> ```

I'll try, thanks
