### ISSUE TITLE
fix failing dryrun e2e job

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2796]
some of our recent changes broke the dryrun e2e

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-latest

tip: to see what commits was it one can click a red box and drag to a green box. i am currently on mobile and can't do that.

we should try to fix this before xmas and not having any failing tests during the holidays...preferably since folks are not around.

@pacoxu @SataQiu @chendave

**Comment by pacoxu** [comment]
```
[upgrade] backing up kubelet config file to /etc/kubernetes/tmp/kubeadm-kubelet-config4028019749/config.yaml
rename /etc/kubernetes/tmp/kubeadm-upgrade-dryrun1808990387/config.yaml /etc/kubernetes/tmp/kubeadm-kubelet-config4028019749/config.yaml: no such file or directory
error backing up the kubelet config file
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/upgrade/node.runKubeletConfigPhase.func1
	cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go:83
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:259
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:232
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.newCmdNode.func1
	cmd/kubeadm/app/cmd/upgrade/node.go:78
github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:1040
github.com/spf13/cobra.(*Command).Execute
	vendor/github.com/spf13/cobra/command.go:968
k8s.io/kubernetes/cmd/kubeadm/app.Run
	cmd/kubeadm/app/kubeadm.go:50
main.main
	cmd/kubeadm/kubeadm.go:25
runtime.main
```

I think this is caused by https://github.com/kubernetes/kubernetes/pull/114330

**Comment by neolit123** [comment]
i think all latest jobs broke
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-patches-latest

or perhaps this is another problem.

**Comment by chendave** [comment]
For the dry-run mode, there is no config file created under the temp dir, so the rename would fail.
`/etc/kubernetes/tmp/kubeadm-upgrade-dryrun1808990387/config.yaml`

I forgot to verify the pr with dry-run mode enabled, sorry about that. This reminds me we at least miss some *UT* to check the behavior of dry-run.

**Comment by neolit123** [comment]
/reopen 

latest tests are still failing!

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-patches-latest/1603446850055049216/build-log.txt

> [upgrade] The control plane instance for this node was successfully updated!
[upgrade] backing up kubelet config file to /etc/kubernetes/tmp/kubeadm-kubelet-config2752156677/config.yaml
rename /var/lib/kubelet/config.yaml /etc/kubernetes/tmp/kubeadm-kubelet-config2752156677/config.yaml: invalid cross-device link
error backing up the kubelet config file

i will try to send a fix today.

**Comment by neolit123** [comment]
it's odd because https://github.com/kubernetes/kubernetes/pull/114532/files seems like a valid fix.
it almost seems as if dryRun is not set properly..

**Comment by pacoxu** [comment]
The failure is different.
```
[upgrade/version] You have chosen to change the cluster version to "v1.27.0-alpha.0.537+0fdb14f63a83a8"
[dryrun] Would perform action GET on resource "version" in API group "core/"
the --version argument is invalid due to these fatal errors:

	- Unable to fetch cluster version: Couldn't fetch cluster version from the API Server: can't cast get reactor event action object to GetAction interface

Please fix the misalignments highlighted above and try upgrading again
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.EnforceVersionPolicies
	cmd/kubeadm/app/cmd/upgrade/apply.go:188
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.runApply
	cmd/kubeadm/app/cmd/upgrade/apply.go:131
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.newCmdApply.func1
	cmd/kubeadm/app/cmd/upgrade/apply.go:74
github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:1040
github.com/spf13/cobra.(*Command).Execute
	vendor/github.com/spf13/cobra/command.go:968
k8s.io/kubernetes/cmd/kubeadm/app.Run
	cmd/kubeadm/app/kubeadm.go:50
main.main
	cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
[upgrade/version] FATAL
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.runApply
	cmd/kubeadm/app/cmd/upgrade/apply.go:132
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.newCmdApply.func1
	cmd/kubeadm/app/cmd/upgrade/apply.go:74
github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:1040
github.com/spf13/cobra.(*Command).Execute
	vendor/github.com/spf13/cobra/command.go:968
k8s.io/kubernetes/cmd/kubeadm/app.Run
	cmd/kubeadm/app/kubeadm.go:50
main.main
	cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
 exit status 1
```

It started to fail yesterday.

**Comment by neolit123** [comment]
i will first submit a PR to revert the backup feature, it must also target "upgrade apply"

**Comment by neolit123** [comment]
revert for the backup kubelet conf:
https://github.com/kubernetes/kubernetes/pull/114608

> The failure is different.

huh, which test run is this?
it seems unrelated to https://github.com/kubernetes/kubernetes/pull/114455

**Comment by pacoxu** [comment]
I will get a deeper look into the failure tomorrow if you do not have time.

**Comment by neolit123** [comment]
ok,


the testgrid / commits / diff are perhaps wrong.
i think this is due to a change in the client go discovery client
https://github.com/kubernetes/kubernetes/pull/114291

cc @enj @sttts @MaxHorstmann

unclear what we are doing wrong in kubeadm for this change to break us.

this is where it fails:
https://github.com/kubernetes/kubernetes/blob/00c0c9d880c1448f778bf892c43664081c80d11e/cmd/kubeadm/app/phases/upgrade/versiongetter.go#L60

the fake client is doing some fake client version hacks here
https://github.com/kubernetes/kubernetes/blob/bf49c7c0b5192326b03c0226dc7a7a28a780befb/cmd/kubeadm/app/cmd/upgrade/common.go#L251-L278

the reactor case handling is here:
https://github.com/kubernetes/kubernetes/blob/bf49c7c0b5192326b03c0226dc7a7a28a780befb/cmd/kubeadm/app/util/apiclient/dryrunclient.go#L117-L138

so i wonder if kubeadm is doing something wrong or if
https://github.com/kubernetes/kubernetes/pull/114291
regressed fakeclient.Discovery().ServerVersion() calls?

**Comment by neolit123** [comment]
> failure point:
https://github.com/kubernetes/kubernetes/blob/bf49c7c0b5192326b03c0226dc7a7a28a780befb/cmd/kubeadm/app/util/apiclient/dryrunclient.go#L120

in the reactor handling kubeadm was doing a k8s.io/client-go/testing.Action -> GetAction cast, which previously worked, so this seems more like a regression. if this cast is/was somehow wrong for fakeclient.Discovery().ServerVersion(), let us know so that we an adapt the logic.

**Comment by MaxHorstmann** [comment]
Hey @neolit123, my guess is that invoking the action in fakeclient.Discovery().ServerVersion() returned an error but it was ignored prior to https://github.com/kubernetes/kubernetes/pull/114291. Can dig a little more in a bit.

**Comment by neolit123** [comment]
thanks @MaxHorstmann 

one fix i have in mind is the following:
```
diff --git a/cmd/kubeadm/app/phases/upgrade/versiongetter.go b/cmd/kubeadm/app/phases/upgrade/versiongetter.go
index 234351f3b91..8ddd8ea4611 100644
--- a/cmd/kubeadm/app/phases/upgrade/versiongetter.go
+++ b/cmd/kubeadm/app/phases/upgrade/versiongetter.go
@@ -24,6 +24,8 @@ import (
 	v1 "k8s.io/api/core/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	versionutil "k8s.io/apimachinery/pkg/util/version"
+	pkgversion "k8s.io/apimachinery/pkg/version"
+	fakediscovery "k8s.io/client-go/discovery/fake"
 	clientset "k8s.io/client-go/kubernetes"
 	"k8s.io/component-base/version"
 
@@ -57,9 +59,18 @@ func NewKubeVersionGetter(client clientset.Interface) VersionGetter {
 
 // ClusterVersion gets API server version
 func (g *KubeVersionGetter) ClusterVersion() (string, *versionutil.Version, error) {
-	clusterVersionInfo, err := g.client.Discovery().ServerVersion()
-	if err != nil {
-		return "", nil, errors.Wrap(err, "Couldn't fetch cluster version from the API Server")
+	var err error
+	var clusterVersionInfo *pkgversion.Info
+
+	// If dry-running, use the FakedServerVersion pinned in cmd/upgrade/common.go#getClient()
+	fakeclientDiscovery, ok := g.client.Discovery().(*fakediscovery.FakeDiscovery)
+	if ok {
+		clusterVersionInfo = fakeclientDiscovery.FakedServerVersion
+	} else {
+		clusterVersionInfo, err = g.client.Discovery().ServerVersion()
+		if err != nil {
+			return "", nil, errors.Wrap(err, "Couldn't fetch cluster version from the API Server")
+		}
 	}
```

but trying to understand if we actually regressed  ServerVersion(), as there might be other consumers like kubeadm.

**Comment by MaxHorstmann** [comment]
@neolit123 hi, trying to understand this a little better-

> in the reactor handling kubeadm is doing a k8s.io/client-go/testing.Action -> GetAction cast, which previously worked

are you sure the [type assertion](https://github.com/kubernetes/kubernetes/blob/bf49c7c0b5192326b03c0226dc7a7a28a780befb/cmd/kubeadm/app/util/apiclient/dryrunclient.go#L120) previously worked? It would appear to me that it might have been failing for a while already, returning an error...

```
getAction, ok := action.(core.GetAction)
if !ok {
	// something's wrong, we can't handle this event
	return true, nil, errors.New("can't cast get reactor event action object to GetAction interface")
}
```

... but since that error was ignored by fake_discovery prior to https://github.com/kubernetes/kubernetes/pull/114291, this was not detected?

**Comment by neolit123** [comment]
yes, the type assertion definitely worked. this kubeadm reactor code is old, and there are a number of other  action casts there as well.

notably it seems to fail only for ServerVersion from the fake client.

the failures started happening around the pr merged and we caught it with our e2e tests. i don't see any other recent prs that touch the discovery / fake client.

**Comment by chendave** [comment]
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-patches-latest seems green after the revert (https://github.com/kubernetes/kubernetes/pull/114608), but https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-latest is still failing, this looks like two different issues.

is there any way for us to reproduce the issue locally?

**Comment by MaxHorstmann** [comment]
[Here](https://github.com/kubernetes/kubernetes/commit/e4353d3ec21e13f05a1986b1eaf3c18fa8f224cd) is my attempt at a local repo of the issue.

```
=== RUN   TestDiscoveryServerVersion
[dryrun] Would perform action GET on resource "version" in API group "core/"
    dryrunclient_test.go:39: Get ServerVersion failed.: can't cast get reactor event action object of type testing.ActionImpl to GetAction interface
--- FAIL: TestDiscoveryServerVersion (6.96s)
```

So the cast fails because `action` is of type `testing.ActionImpl` (created by fake discovery [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/discovery/fake/discovery.go#L141)) which can't be cast to `core.GetAction`.

It's still not clear to me how this cast could have worked in the past. As I suggested above, maybe the cast failed in the past but prior to https://github.com/kubernetes/kubernetes/pull/114291 the resulting error was ignored?

**Comment by neolit123** [comment]
thanks for digging into this @MaxHorstmann 
i guess we just need to handle bare ActionImpl with "get" verbs.
i have a PR in the works, that will also include your handy unit test.

**Comment by pacoxu** [comment]
I tried to fix it based on @MaxHorstmann 's commit in https://github.com/kubernetes/kubernetes/compare/master...pacoxu:kubernetes:fix-dry-run-failure?expand=1

Not sure if it is the correct way.

**Comment by neolit123** [comment]
@pacoxu 

> Not sure if it is the correct way.

i think adding Name to ActionImpl might make sense, but we can fix this in kubeadm instead of waiting for the client-go approval for the change. it's technically a public API change - adding a new field and a getter. unlikely to merge before xmas / new year.

@MaxHorstmann the bigger question i have here is why discovery methods are not constructing GetActionImpl, given the actions are with a "get" verb. i think users of the fake client / discovery might find this a bit confusing.
 
my PR is here, please review / lgtm.

https://github.com/kubernetes/kubernetes/pull/114632

**Comment by neolit123** [comment]
looks like this problem here is more entangled, i have a PR in the works but it seems like a workaround..

@MaxHorstmann or anyone else in this thread, do you happen to know what is the Discovery().ServerVersion() analog for dynamic clients? kubeadm has some sketchy real client / fake client mixture in reactors where an object is fetched and then printed as unstructured when dry-running. in the reactor handler for GetAction the dynamic client call and the GetAction for `/version` looks like this:

```
dynamicClient.Resource(action.GetResource()).Namespace(action.GetNamespace()).Get(context.TODO(), action.GetName(), metav1.GetOptions{})
```
```
testing.GetActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"get", Resource:schema.GroupVersionResource{Group:"", Version:"", Resource:"version"}, Subresource:""}, Name:"version"}
```

but the dynamic client returns
```
the server could not find the requested resource
```

so either server version cannot be obtained from a dynamic client or somehow our resource request is malformed.

**Comment by neolit123** [comment]
> looks like this problem here is more entangled, i have a PR in the works but it seems like a workaround..

PR is here
https://github.com/kubernetes/kubernetes/pull/114658

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-latest

Green now. 👍
