### ISSUE TITLE
Etcd Encryption enabled by default during bootstrap

### ISSUE THREAD

**Issue by Daxcor69** [kubernetes/kubeadm#2798]
Request:
- I would like to be able to pass an encryption key and encryption type to kubeadmin --init so that etcd encryption can be installed during the boot strap process. 
- using kubeadm with a flag like "--rotate" to automate the rotation of the encryption key.

Why:
There is no real reason not to have etcd encrypted by default.  I think this would up the security profile of k8s in general. The encryption/decryption is seamless thus not adding any additional complexities to the developers.  This would make the secret a true secret and allow people to use the normal kubectl to add and remove secrets.

Pros:
- eliminate misconfiguration by users post install, and destroying cluster
- set appropriate file permission on key file to match the user of the api server.
- no need to go back and read then encrypt existing data.
- eliminating the need for developers to have to deal with managing secrets in an external authority like  hashicorp vault.

Cons:
- complicating the environment for new kubernetes users.
- confusing the issue with external vs internal etcd clusters.

**Comment by pacoxu** [comment]
Some references:
- Encrypting Secret Data at Rest: https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
- - Encrypting your data with the KMS provider: https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#encrypting-your-data-with-the-kms-provider
- Openshift supports it. https://docs.openshift.com/container-platform/4.9/security/encrypting-etcd.html

BTW, can this be enabled by using apiServer.extraArgs? `--encryption-provider-config=/etc/kubernetes/enc/enc.yaml`
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#apiserver-flags
- It seems not as it needs a configuration file mount.

**Comment by neolit123** [comment]
>  There is no real reason not to have etcd encrypted by default. I think this would up the security profile of k8s in general. 

i am generally -1 to do etcd encryption by default in kubeadm. kubeadm tries to follow k8s defaults and k8s does not do it by default. i know some enterprise customers do want this for hardening, but it is still not a good justification to switch this to opt-out for the rest of the users.

as @pacoxu explains above, kubeadm already allows you to configure individual components so that you can for example use a KMS.

if you think there is missing documentation on this topic please log a ticket in kubernetes/website (k8s.io).

**Comment by neolit123** [comment]
btw, for a broader discussion you can message #sig-api-machinery in the k8e slack. they own the apiserver / etcd integration.

**Comment by Daxcor69** [comment]
I didn't make it clear,  I wasn't thinking it should be ON by default.  Rather it should be an option at boot strap time to implement right from the start of the clusters life. Making an easy path to greater security.  This way the configuration is correct and no danger of damaging the cluster after the fact, like I almost did.  Still haven't got it working yet.

At boot strap time:
```kubeadmin --init --encrypt --key akldjfa;skdjfadskjf4534 --kind aescbc    <rest of options>```

After bootstrap:
``` kubeadm  --encrypt --key akldjfa;skdjfadskjf4534 --kind aescbc

To rotate keys
``` kubeadm --rotate --key 345334534535543 ```

Thank you for the consideration.

**Comment by neolit123** [comment]
understood, well,  like we pointed out kubeadm allows users to do this by configuring individual components at bootstap or after.

kubeadm has one philosophy which i personally agree with and that is to keep the scope of the project minimal with features that are only needed by the majority of users. i think we have a couple of small exceptions ('kubeconfig user' comes to mind), but any form of etcd encryption is significant efford for us to maintain and we have not seen the demand. with these thoughts i'd say this is out of scope, but let's see if others have comments.

**Comment by Daxcor69** [comment]
Ok I didn't see that link in the reply so when the flag is set in the custom yaml

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.16.0
apiServer:
  extraArgs:
    --encryption-provider-config=/etc/kubernetes/enc/enc.yaml
```
Does it also create the volume mounts etc nessessary?  So all a person has to do is put the key file on the control plane node or use a kms?

**Comment by neolit123** [comment]
there is also extraVolumes if something has to be mounted in the apiserver or other static pods.

**Comment by neolit123** [comment]
closing this as possible via kubeadm exposed config.
discussion can continue on slack. thanks

**Comment by apiwat-chantawibul** [comment]
For future viwers, the [format of `extraArgs` given by @Daxcor69](https://github.com/kubernetes/kubeadm/issues/2798#issuecomment-1359981591) is incorrect.
(Refer to long example config in [here](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/).)

> ```yaml
> apiVersion: kubeadm.k8s.io/v1beta3
> kind: ClusterConfiguration
> kubernetesVersion: v1.16.0
> apiServer:
>   extraArgs:
>     --encryption-provider-config=/etc/kubernetes/enc/enc.yaml
> ```

Also, to give a more complete example with `extraVolumes` too, I give the
following example:

```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    encryption-provider-config: /etc/kubernetes/enc/enc.yaml
  extraVolumes:
    - name: etcd-encryption
      hostPath: /etc/kubernetes/enc/enc.yaml
      mountPath: /etc/kubernetes/enc/enc.yaml
      readOnly: true
      pathType: File
```
