### ISSUE TITLE
Make it easy to run an other certificates controller

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#280]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

FEATURE REQUEST

It would be nice if we made it easy to deploy your own certificates controller instead of relying on the one that's built-in into the core controller-manager.

If the user opts in to running a separate certificates signing controller, the availability of `ca.key` on disk will be optional _if and only if_ the user specifies the rest of the required files, namely:
 - ca.crt
 - apiserver.{crt,key}
 - apiserver-kubelet-client.{crt,key}
 - admin.conf
 - kubelet.conf
 - controller-manager.conf
 - scheduler.conf

This assumes the CSR approval controller will still be run, so it's only the CSR signing controller that's deactivated. This can be done by just omitting the `cluster-signing-cert-file` and `cluster-signing-key-file` flags to the controller-manager.

Combined with kubelet certification rotation, all kubelets (including the master) will have a client/server cert/key pair signed by the external CA without ever having the CA key on disk.

kubeadm changes: The certificates controller can be added just by a `kubectl apply -f` post-installation, the only thing that needs to be done is to inactivate the default CSR signing controller.
We should document how to do this in detail.

Is there anything I missed that has to be done for this to work?

Thoughts?
@kubernetes/sig-auth-feature-requests @mikedanese @jcbsmpsn

**Comment by mikedanese** [comment]
Can we implement this in phases and not as part of the bundled install? Also which certificates controller are you talking about? There are two now.

**Comment by luxas** [comment]
What we can do/should do practically here is to not pass `--cluster-signing-cert-file` or `--cluster-signing-key-file` to the controller-manager if the CA key doesn't exist on disk.
That will automatically disable the in-cluster certificates controller.
ref:
```go
        if ctx.Options.ClusterSigningCertFile == "" || ctx.Options.ClusterSigningKeyFile == "" {
		return false, nil
	}
```
We should emit a warning from kubeadm that we do this though...
cc @krousey

**Comment by luxas** [comment]
@nckturner volunteered to fix that :tada:
Reach out if you need any help contributing that

**Comment by krousey** [comment]
I was going to argue that this should be an explicit option instead of implicitly triggered through a missing file, but the only way for that file to be missing at this point in the flow is if we didn't rely on kubeadm to generate the certs to begin with and took special precautions to make sure the master couldn't sign keys. So SGTM.

**Comment by nckturner** [comment]
Thanks @luxas, will take a look and reach out with questions.

**Comment by mikedanese** [comment]
> If the user opts in to running a separate certificates signing controller, the availability of ca.key on disk will be optional if and only if the user specifies the rest of the required files, namely:
> 
> ca.crt
> apiserver.{crt,key}
> apiserver-kubelet-client.{crt,key}
> admin.conf
> kubelet.conf
> controller-manager.conf
> scheduler.conf

Should we be checking if all of these exist and that the ca.key does not? I'm worried about masking both user and programmer error.

**Comment by mikedanese** [comment]
Also the user experience here is not spectacular. It would be great to point kubeadm to and external CA and not require the user to place this list of files manually.

**Comment by mikedanese** [comment]
Musing: A great end user experience would be allowing kubeadm to point to an ACME directory for issuance and call it a day.

**Comment by luxas** [comment]
@mikedanese Can you write up a short proposal for pointing to the ACME directory thing?
I think that'd be useful as well; but before we can use that fully the csrsigner should support ACME as well I guess?
