### ISSUE TITLE
kubeadm init no flag for IPv6-only

### ISSUE THREAD

**Issue by agowa338** [kubernetes/kubeadm#2806]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm init ipv6

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): `kubeadm version: &version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"archive", BuildDate:"2023-01-12T15:26:48Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): ```WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"archive", BuildDate:"2023-01-12T15:26:48Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?```
- **Cloud provider or hardware configuration**: Alpine Linux, Bare Metal, 2 NICs (1 WAN, 1 peer-to-peer MLX)
- **OS** (e.g. from /etc/os-release): ```NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.17.1
PRETTY_NAME="Alpine Linux v3.17"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"```
- **Kernel** (e.g. `uname -a`): `Linux storage001 5.15.86-0-lts #1-Alpine SMP Mon, 02 Jan 2023 09:28:30 +0000 x86_64 Linux`
- **Container runtime (CRI)** (e.g. containerd, cri-o): cri-o
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Flannel
- **Others**: NAT64 and DNS64 are provided by another node on the network.

## What happened?
```
# kubeadm init --node-name=storage001 --feature-gates PublicKeysECDSA=true --cri-socket /run/crio/crio.sock --upload-certs --pod-network-cidr=fda9:d324:354d:0::/56 --service-cidr=fda9:d324:354d:1::/112
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
        [ERROR FileContent--proc-sys-net-ipv4-ip_forward]: /proc/sys/net/ipv4/ip_forward contents are not set to 1
        [ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/5.15.86-0-lts\n", err: exit status 1
```

## What you expected to happen?
IPv4 configuration and checks should be skipped esp. because the system does not have any IPv4 connectivity.

## How to reproduce it (as minimally and precisely as possible)?
1. Have NAT64 + DNS64 available on the network (just in case connectivity to e.g. Github or something is required, otherwise not related to this at all).
2. Install alpine edge
3. Enable testing repository within /etc/apk/repositories
4. Install kubeadm, kubelet, kubectl, flannel, cri-o
5. run `kubeadm init --node-name=storage001 --feature-gates PublicKeysECDSA=true --cri-socket /run/crio/crio.sock --upload-certs --pod-network-cidr=fda9:d324:354d:0::/56 --service-cidr=fda9:d324:354d:1::/112`

## Anything else we need to know?
Partly unrelated for now, but I also don't see any way to use dynamic prefixes, an upstream DHCPv6-PD server, or just auto configuration via SLAAC.

**Comment by chendave** [comment]
ref: https://github.com/kubernetes/kubeadm/issues/2063

> IPv4 configuration and checks should be skipped esp. because the system does not have any IPv4 connectivity.

Looks like to me a valid request.
/assign

I will take a look.

**Comment by chendave** [comment]
@agowa338 pls see if this PR partially addresses your problem: https://github.com/kubernetes/kubernetes/pull/115420
