### ISSUE TITLE
kops integration tracking issue

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#281]
Hi @justinsb @kris-nova @chrislovecnm!

What do you want to see from the kops side for the kubeadm integration?
I'm gonna update the phases doc (#156) soon with more details and new ideas.

It would also be interesting to hear your story how you bring up k8s after provisioning the masters and nodes.

**Comment by chrislovecnm** [comment]
@justinsb what do you think about cert management? You understand kubeadm better than I do.

**Comment by jamiehannaford** [comment]
Since we now have the kubeadm adoption WG, is it better to delegate integration work there instead? I see this hasn't been updated in a while, just wondering whether we need to track that work here.

**Comment by luxas** [comment]
Yeah @jamiehannaford SGTM to have more specialized channels of communication
