### ISSUE TITLE
Support environment variable configuration for the control plane & nodes.

### ISSUE THREAD

**Issue by mattcary** [kubernetes/kubeadm#2813]
## What keywords did you search in kubeadm issues before filing this one?

mutation env var environment variable KUBE_CACHE_MUTATION_DETECTOR

## FEATURE REQUEST

Support plumbing env vars (environment variables) to control plane components as well as nodes. In particular, I'd like to be able to set KUBE_CACHE_MUTATION_DETECTOR for running e2e tests on kind. See https://github.com/kubernetes/kubernetes/issues/114955 for more context.

**Comment by neolit123** [comment]
isn't it just possible to patch env vars in static pod manifests?

see kubeadm's --patches and related docs pages?

**Comment by mattcary** [comment]
Ah, thanks. I'm actually trying to get this to work on kind, so digging through multiple layers of APIs. I'll see if that's accessible through kind.

**Comment by BenTheElder** [comment]
I think it's possible but going to get a bit confusing, you'll have to patch kubeadm config in kind's config to configure patches and configure kind to mount through the patches you want kubeadm to apply. This is hard to describe 🙃

**Comment by mattcary** [comment]
Yes, exactly. Any hints you can give me would be appreciated. There doesn't seem to be a lot of examples out there on using kubeadm config patches (although I got pre-empted today so still have to follow up).

**Comment by mattcary** [comment]
@neolit123 So I think that will work for the control plane -- I'm still experimenting -- but it's not clear how to add an environment variable for the kubelet? From the docs, the patch `"target" can be one of "kube-apiserver", "kube-controller-manager", "kube-scheduler", "etcd" '.

I believe we want the mutation detector enabled on the kubelet as well for most of the e2e tests.

**Comment by mattcary** [comment]
@BenTheElder I think you're right. I get this error:

```
[patches] Reading patches from path "/chromium/k/kind/"
lstat /chromium/k/kind/: no such file or directory
could not list patch files for path "/chromium/k/kind/"
```

When doing `kind create cluster --config kind..yaml` with a config of

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "StatefulSetAutoDeletePVC": true

kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    patches:
      directory: /chromium/k/kind/
```

Note that the kubeadm patches are given by listing files in a directory. It looks like kind is running everything from a container (kubernetes in docker from docker and by docker....), so can't see the host filesystem? I've tried with both absolute and relative paths---a relative path silently doesn't work, presumably because a non-existent directory doesn't have any patches to apply, but trying to walk the absolute directory at least fails as above.

Any ideas?

**Comment by BenTheElder** [comment]
https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts will let you pass through from the host

sorry, I wanted to work up an example here but i've been wrapped up in PRR https://github.com/kubernetes/registry.k8s.io/issues/143 and a couple other things 😓

**Comment by BenTheElder** [comment]
absolute path on the kubeadm side, to a path that you mounted through from the host in extraMounts kind config. the containerPath should match the patches.directory

**Comment by mattcary** [comment]
\o/ thanks, that seems to be the right idea. Still struggling with the patch but at least I'm getting it to apply to the controller manager.

I think this is probably it but I'll wait to close this issue until I actually get it working.

**Comment by neolit123** [comment]
seems doable as discussed.
please continue the discussion on #kubeadm on k8s slack if needed.
