### ISSUE TITLE
What is the correct way to renew kubernetes certificates via kubeadm?

### ISSUE THREAD

**Issue by Talgatttt** [kubernetes/kubeadm#2814]
What is the correct way to renew kubernetes certificates via kubeadm (v1.25)? The cluster consists of 3 master nodes with default etcd installed via kubeadm and 4 worker nodes. Did kubeadm certs renew all, but CERTIFICATE AUTHORITY (ca; etcd-ca; front-proxy-ca;) was not updated.
1) How to update them? and are they needed and how will they affect the work of klaster?
2) do kubeadm certs renew all on all 3 masters? Or do on one and copy to others?
3) What else needs to be done besides kubeadm certs renew all? do i need to update *conf ?
4) Do I need to do anything on the worker nodes?

**Comment by kundan2707** [comment]
@Talgatttt you can find answer of your all questions here 
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

**Comment by SataQiu** [comment]
Kubeadm does not support rotation or replacement of CA certificates out of the box.

For more information about manual rotation or replacement of CA, see [manual rotation of CA certificates](https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/).

**Comment by neolit123** [comment]
worker nodes don't need cert rotation by default.
cp nodes can use "certs renew" or just "upgrade"

/support
