### ISSUE TITLE
Kubeadm and Kubelet not found after node OS upgrade

### ISSUE THREAD

**Issue by ShinyDhas** [kubernetes/kubeadm#2818]
BUG REPORT 
after upgrading from Centos7 to Almalinux8.7 using the leapp utility, I cannot find the kubeadm and kubelet services.

below is the leapp-upgrade log file for reference
Risk Factor: high
Title: Packages not signed by Red Hat found on the system
Summary: The following packages have not been signed by Red Hat and may be removed during the upgrade process in case Red Hat-signed packages to be removed during the upgrade depend on them:
- check-mk-agent
- conmon
- containernetworking-plugins
- containers-common
- cri-o
- cri-tools
- elevate-release
- fuse-overlayfs
- gpg-pubkey
- htop
- kubeadm
- kubectl
- kubelet

I want to do a in-place upgrade, I just want the OS to be upgraded and not the kubernetes version itself.

any way to do node OS upgrade without upgrading the kubelet, kubectl and kubeadm versions?

## Versions

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:08:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.1
Kustomize Version: v4.5.4
- NAME="AlmaLinux"
VERSION="8.7 (Stone Smilodon)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.7 (Stone Smilodon)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
- 4.18.0-425.10.1.el8_7.x86_64
- rpm -qa | grep ^cri-
cri-o-1.20.2-1.6.el7.x86_64
cri-tools-1.24.0-0.x86_64

- **Container networking plugin Calico
- kubelet --version
Kubernetes v1.20.5

**Comment by SataQiu** [comment]
@ShinyDhas  Thanks for your report.
But this doesn't seem to be in the scope of `kubeadm`, you should file an issue with https://github.com/kubernetes/release/issues

**Comment by kundan2707** [comment]
@ShinyDhas  there could be multiple ways. one way could be as follow.
```
To rolling update the nodes is easy. Just adding more nodes with
updated os to the cluster and delete old nodes after you do a drain on
them.

If you want to do rolling update on the master, you have to solve the
following problems:

- How to migrate etcd data to the new master
- How to keep the apiserver address static for node servers

There are many solutions to the problems. For example, you could setup
a dedicated etcd cluster and put a proxy in front of the master
server.

I would recommend to use the [bootkube] tool to setup a Kubernetes
cluster with self-hosted-etcd. And create a loadbalancer for the
apiserver.

We had put up an [example] in our cluster management tool for an aws
setup. Hope it's useful.

[bootkube]: https://github.com/kubernetes-incubator/bootkube
[example]: https://github.com/kubeup/archon/tree/master/example/k8s-bootkube
```
