### ISSUE TITLE
kubeadm cluster dns

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubeadm#282]
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.1534+cf7301f16c0363-dirty", GitCommit:"cf7301f16c036363c4fdcb5d4d0c867720214598", GitTreeState:"dirty", BuildDate:"2016-09-27T18:10:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

What happened:

I ran:
sudo kubeadm init --service-cidr 172.16.128.0/24

The kube-dns service picks 172.16.128.10 and functions properly there, but pods created use the 100.64.0.10 address space to try and talk to kube-dns and fails. The wrong address is placed in /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

What you expected to happen:
Pods launch with a correct resolv.conf pointing to a kube-dns in the specified range.

How to reproduce it (as minimally and precisely as possible):
kubeadm init --service-cidr

launch a non net=host pod, and try to resolve a service.

**Comment by kfox1111** [comment]
This is moved from https://github.com/kubernetes/kubernetes/issues/33881

**Comment by luxas** [comment]
@kfox1111 Thanks for moving! Can you reproduce on kubeadm v1.6 (what we support at the moment)?

**Comment by shekharupland** [comment]
I am able to see this issue with the fresh install : 
kubectl exec -ti busybox -- nslookup kubernetes.default
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'kubernetes.default'

kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Any pointers??

**Comment by kfox1111** [comment]
@shekharupland usually thats an issue with kube-dns, your sdn, or settings if you changed the pod/service network. generally I've found it to be the sdn though. Would try there first.

**Comment by luxas** [comment]
@shekharupland Which CNI network plugin are you using? Weave, flannel, calico, canal?

**Comment by straticsryan** [comment]
I ran and reproduced this issue using 1.6 as well.

I'm using weave as a cni-plugin (I had to edit the IPALLOC_RANGE in weave's plugin yml to also correspond to the netmask used in by `service-cidr` and `pod-network-cidr`).

**Comment by straticsryan** [comment]
Is there a known way to update the cluster dns setting after `kubeadm init` has been run? maybe a systemd setting?

**Comment by straticsryan** [comment]
not sure if this helps, but I found out that `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` had dns settings that weren't getting cleared by `kubeadm reset` (aka the file still exists after a reset).

I imagine that file gets created the first time `kubeadm init` gets ran and then never gets overwritten? If so, then that explains why I ran into this issue because my first `kubeadm init` didn't change the `service-cidr`

**Comment by kfox1111** [comment]
its owned by the rpm and I don't think its touched by kubeadm. which seems very wrong.

**Comment by straticsryan** [comment]
gotcha. I'm trying to figure out how I can adjust my setup now to get dns working now and found that as it has the same cluster-dns ip as the /etc/resolv.conf file on one of my app containers.

**Comment by luxas** [comment]
@kfox1111 Touching that file would be wrong by kubeadm; unfortunately we haven't got #28 yet, but that will get into v1.8...

**Comment by kfox1111** [comment]
then why is it called 10-kubeadm.conf ?

**Comment by luxas** [comment]
@kfox1111 What would it be called instead?
Clarification:
kubeadm **the binary** should never touch anything systemd-related
kubeadm **the deb/rpm package** may bring options that we know work well with kubeadm the binary

**Comment by kfox1111** [comment]
ah. ok. I thought it was owned by the kubelet package not the kubeadm package.

That makes a bit more sense, but still is a usability issue. the user changes the service network and then things break unless they know every place to update the config file. Maybe if nothing else, a warning to the user on the kubeadm binary when the user switches the service network telling the user what to fix, until dynamic config lands?

**Comment by luxas** [comment]
@kfox1111 Feel free to add that warning if you want. The documentation PR just landed: https://github.com/kubernetes/kubernetes.github.io/pull/4164#event-1138949384

**Comment by jamiehannaford** [comment]
@kfox1111 Now that we have that warning documented, are we okay to close this out? Is there anything else we can do?

**Comment by kfox1111** [comment]
Yup. The doc looks good. Thanks. :)
