### ISSUE TITLE
CI failure: kubeadm-kinder-learner-mode-latest failed for joining as a learner

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubeadm#2821]
## What keywords did you search in kubeadm issues before filing this one?
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-learner-mode-latest

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT
/kind bug

## What happened?

The CI failed for https://github.com/kubernetes/kubeadm/issues/1793 feature

## What you expected to happen?
CI green

## Anything else we need to know?
See more in https://github.com/kubernetes/kubernetes/pull/115038#issuecomment-1414618428

**Comment by tobiasgiese** [comment]
First passed periodic test: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-learner-mode-latest/1622596044279779328

**Comment by tobiasgiese** [comment]
2 in a row, seems that https://github.com/kubernetes/kubernetes/pull/115038 has fixed the issue

![image](https://user-images.githubusercontent.com/23076619/217031940-428fba26-064a-4b4f-9ed0-0bc2a15f0c7e.png)

**Comment by SataQiu** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/115038

/close
