### ISSUE TITLE
Additional "." in `kubeadm join` commad when copied

### ISSUE THREAD

**Issue by Santosh1176** [kubernetes/kubeadm#2827]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST
BUG REPORT 

When the`kubeadm join` command is provided after the `kubeadm init` operation when that output is copied and pasted on the node that we want to join the cluster. An addition "." dot, is placed at the beginning of `--discovery-token-ca-cert-hash` flag which fails the join operation.

## Versions

**kubeadm version** (use `kubeadm version`):
v1.26.0
**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.26.0
- **Cloud provider or hardware configuration**: on-prem (Vagrant)
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.5 LTS
- **Kernel** (e.g. `uname -a`): 5.4.0-139-generic
- **Container runtime (CRI)** (e.g. containerd, cri-o): ContainerD
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Cilium
- **Others**:

## What happened?
An additional dot is placed while copying the `kubeadm join` command from controlplane after the `kubeadm init` and trying to paste it on the worker node. The dot appears in front of `.--discovery-token-ca-cert-hash`.

![join](https://user-images.githubusercontent.com/91916466/219940401-aa766e64-23e9-48d1-b117-e8de4c779f9e.png)

## How to reproduce it (as minimally and precisely as possible)?
Run a `kubeadm init` after the process completes, copy the `kubeadm join` command and paste it on the terminal.

**Comment by SataQiu** [comment]
Hi @Santosh1176 Thanks for your feedback.
Can you paste the output about `kubeadm init` command?

**Comment by Santosh1176** [comment]
Thank you for looking into this.
The following is the out put of the `kubeadm init` command:

```bash
vagrant@kubemaster:~$ sudo kubeadm init --pod-network-cidr=10.1.1.0/24 --apiserver-advertise-address 192.168.56.11
[init] Using Kubernetes version: v1.26.1
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
.
.
Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 192.168.56.11:6443 --token esun91.trh2iyeohyp2o3z5 \
	--discovery-token-ca-cert-hash sha256:2b366ff1884e53205e3e9e7e887447f0fe18b2a4a94489ef8552f990a4d91ed9 
vagrant@kubemaster:~$
```
and the join command copied and pasted on the worker node.

```bash
Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 192.168.56.11:6443 --token esun91.trh2iyeohyp2o3z5 \
	--discovery-token-ca-cert-hash sha256:2b366ff1884e53205e3e9e7e887447f0fe18b2a4a94489ef8552f990a4d91ed9

vagrant@kubenode01:~$ kubeadm join 192.168.56.11:6443 --token esun91.trh2iyeohyp2o3z5 \
> .--discovery-token-ca-cert-hash sha256:2b366ff1884e53205e3e9e7e887447f0fe18b2a4a94489ef8552f990a4d91ed9
```
![kubeadm-join](https://user-images.githubusercontent.com/91916466/220316004-bffc7a18-908a-4ae2-a673-94b50bad6839.png)

**Comment by neolit123** [comment]
seems like some sort of a copy / paste artifact of the terminal?
the dot cannot be found in the source code as far as i can tell.

#kubernetes-users on k8s slack might have some ideas on why this is happening.

/kind support
