### ISSUE TITLE
Kubernetes reset taking longer on version 1.26.1

### ISSUE THREAD

**Issue by nitinjagjivan** [kubernetes/kubeadm#2828]
### What happened?

On our test environment we deploy 50+ pods application everyday and reset it everyday with command 'sudo  kubeadm reset -f'. Till kubernetes v1.25.6 it worked well and would reset kubernetes in max 2 min. 
We upgeaded our environment to kubernetes v1.26.1 yesterday and now 'sudo  kubeadm reset -f' is taking more than 40 min. We tested this on one more test environment and the result is same.

### What did you expect to happen?

Considering our historical data 'sudo  kubeadm reset -f' should take max 2 min on kubernetes v1.26.1

### How can we reproduce it (as minimally and precisely as possible)?

Reset kubernetes after you deploy a heavy app with atleast 20 podson kubernetes v1.26.1

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
# paste output here
```

</details>

### Cloud provider
AWS

### OS version

CentOS 7

### Install tools
kubeadm

### Container runtime (CRI) and version (if applicable)

containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> what is the output of --v=5 for both?

what part of reset is actually slower?

**Comment by nitinjagjivan** [comment]
We are using same containerd version on both the env which is -
Client:
  Version:  1.6.9
  Revision: 1c90a442489720eec95342e1789ee8a5e1b9536f
  Go version: go1.18.7
  ```

[nitin@integrationcp ~]$ sudo kubeadm reset -f --v=5
I0221 07:45:16.801851    8132 reset.go:103] [reset] Loaded client set from kubeconfig file: /etc/kubernetes/admin.conf
[reset] Reading configuration from the cluster...
[reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
I0221 07:45:16.815950    8132 kubelet.go:74] attempting to download the KubeletConfiguration from ConfigMap "kubelet-config"
I0221 07:45:16.830934    8132 reset.go:128] [reset] Detected and using CRI socket: unix:///var/run/containerd/containerd.sock
[preflight] Running pre-flight checks
I0221 07:45:16.830979    8132 removeetcdmember.go:60] [reset] Checking for etcd config
I0221 07:45:16.830998    8132 local.go:93] [etcd] creating etcd client that connects to etcd pods
I0221 07:45:16.831014    8132 etcd.go:168] retrieving etcd endpoints from "kubeadm.kubernetes.io/etcd.advertise-client-urls" annotation in etcd Pods
I0221 07:45:16.834382    8132 etcd.go:104] etcd endpoints read from pods: https://**.**.***:***
I0221 07:45:16.845292    8132 etcd.go:224] etcd endpoints read from etcd: https://**.**.***:***
I0221 07:45:16.845310    8132 etcd.go:122] update etcd endpoints: https://**.**.***:***
I0221 07:45:16.853305    8132 local.go:109] [etcd] This is the only remaining etcd member in the etcd cluster, skip removing it
[reset] Deleted contents of the etcd data directory: /var/lib/etcd
I0221 07:45:16.865341    8132 cleanupnode.go:66] [reset] Getting init system
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
I0221 07:45:17.895754    8132 cleanupnode.go:97] [reset] Removing Kubernetes-managed containers
I0221 07:45:17.916743    8132 runtime.go:106] Attempting to remove container 8639876953dcc0ac5a195615bfe159e84da8d8ec11a779af539733d46846149a
I0221 07:45:18.400584    8132 runtime.go:106] Attempting to remove container b55ab3ec2c3a0bfdc7568b79756d3ce4521d5387d2e897405dc1329560083245
I0221 07:45:18.874624    8132 runtime.go:106] Attempting to remove container 47e63056bcc631e8934b0789eaff636163f93f81e9493f18a59dc5c479715540
I0221 07:45:19.349662    8132 runtime.go:106] Attempting to remove container 56b7e71e5f0f53a3ac1f716b551624d504a25d9b4eb8bfc82c95b390220bd2ee
I0221 07:45:19.834979    8132 runtime.go:106] Attempting to remove container 7c5ae4f6b4d5040d585b8d143f08cd535acc27274288801ab4614cc3730b0b64
I0221 07:45:20.325570    8132 runtime.go:106] Attempting to remove container 5f1d8a225b019f1216b3e0c9bdb25bf5104089dbac594bd458379c160b1b42da
I0221 07:45:20.809262    8132 runtime.go:106] Attempting to remove container e387ba5a39d1c9e9386bc6261809a810554a4e3e0218cc3148bba226a8a5d2ad
I0221 07:45:21.298220    8132 runtime.go:106] Attempting to remove container 16c74d6a43f4c814e4e25dc2f5bf1a1101bed4be92329b704a8965e8d4f8c002
I0221 07:45:21.781692    8132 runtime.go:106] Attempting to remove container bac8f195773d90330405af2ae1eddd092dc82b67dfbf3c637c7ce693388d21a8
I0221 07:45:22.287497    8132 runtime.go:106] Attempting to remove container 067e8ddc5fac4eac4eb2953640430a8f19824b313bcb655163801168e632d722
I0221 07:45:22.760498    8132 runtime.go:106] Attempting to remove container 8ca3e61acb5f7cd9698002cf750509a6eac402a78fa97cefdc380f69744a3cde
I0221 07:45:23.232159    8132 runtime.go:106] Attempting to remove container 22f7c9099c3108d010b1c189852eeb07ba32682a9fa0338190067dbeafb41766
I0221 07:45:23.638774    8132 runtime.go:106] Attempting to remove container 83647da7d6283e5a6e0434c8494f3f98046dc034d85aca67ea36e62969482f71
I0221 07:45:24.125799    8132 runtime.go:106] Attempting to remove container 20ec791d7c18b31b078fa038d5b01da1aa7f709185b719a28796894918712692
I0221 07:45:24.621817    8132 runtime.go:106] Attempting to remove container f2a8d2f731e5110a20e0fa80f6e174b5221b581e3ec81ce897c1ccf749deed84
I0221 07:45:25.102023    8132 runtime.go:106] Attempting to remove container 8f08661874bf905868dfe826a292c4a3b1102d0d66aff21d1f04f8981cc91128
I0221 07:45:25.605839    8132 runtime.go:106] Attempting to remove container 6884a60d3951ce2648ac047236fb7cbdd79a2e7acac2112770ce92eeac8c5860
I0221 07:45:26.087104    8132 runtime.go:106] Attempting to remove container ac95181855456faa5125ed5b123b4dfbe7e490b36ed90c40dfbf0412390f395b
I0221 07:45:26.596267    8132 runtime.go:106] Attempting to remove container ba5e97fe0989960723dcc79918b931e8e043cd2bccca55a4f07251b5fe35e060
I0221 07:45:27.102093    8132 runtime.go:106] Attempting to remove container 9ffe972da68ce90589dcaf38b82bc6bad538ae70a3ea2bf267ba00cb8fc9e399
I0221 07:45:27.575623    8132 runtime.go:106] Attempting to remove container 1a3540d171dc04f0091be48288f2970ae7095b4a3f2f22f33a631687a502c4e2
I0221 07:45:28.054173    8132 runtime.go:106] Attempting to remove container 89044af0a352209a75d43d0e11a4e10792779b28c08473b73fc1fd79063677b2
I0221 07:45:28.542763    8132 runtime.go:106] Attempting to remove container 9febcab14cbf26c14f4b7cc74038988cec9821307952aa63fe49f3371d5d01d3
I0221 07:45:29.034202    8132 runtime.go:106] Attempting to remove container 70aa32a526cfc5f818b775c184b4195307311123e070755b6e0b2b1115dadf45
I0221 07:45:29.524097    8132 runtime.go:106] Attempting to remove container 38bfe0ba30dd981c3c95044c48246f1aa573656fa0fdd2bf2d9d6f39f515bac0
I0221 07:45:30.001018    8132 runtime.go:106] Attempting to remove container f3420c2cddc1dcf6d164f5c53baf4cbc4d103a729dbefa1447f848bbd756efde
I0221 07:45:30.484981    8132 runtime.go:106] Attempting to remove container 1b852d7e611c4c993a0c55ef2b6e7bb05e238c7a764ab62ac40b693f82a47f99
I0221 07:45:30.969914    8132 runtime.go:106] Attempting to remove container b94ff2e10ac748e77d3c07795793f996a71f1cb3ad28a381072b2d7c5d3ee0ec
I0221 07:45:31.472585    8132 runtime.go:106] Attempting to remove container 40c27b45aabd550393abe36b4b65eeba10216250dcd5fc1c6fdae46d61ad3aa1
I0221 07:45:31.999196    8132 runtime.go:106] Attempting to remove container a1c84f610354b5ff6992b6f8653b1461f0013082c8aef79bd14f3c6643f8f772
I0221 07:45:32.499095    8132 runtime.go:106] Attempting to remove container 2c3b9f649735710c32d5897c51de6a9f916347de65b23626c47e30fb2abddd70
I0221 07:45:33.000289    8132 runtime.go:106] Attempting to remove container 6a2c563c4d74a23c1056435b61277d57d1ee5efe5a9f7384deaccb3e4e27104c
I0221 07:45:33.541633    8132 runtime.go:106] Attempting to remove container ad3b82b1c7d92a3ae63d707b90c23e80fc8541d40f8014062f2c835504505a67
I0221 07:45:34.045549    8132 runtime.go:106] Attempting to remove container 4f8eef68428f196855c1fe984087f6bcb7cd88d3401a3d827d237676434e4bad
I0221 07:45:34.517587    8132 runtime.go:106] Attempting to remove container 8ebb61f4c0e6bbef93f0fc8c72554db3b4cfa28070636a05ee69fab683fd0b7b
I0221 07:45:34.995166    8132 runtime.go:106] Attempting to remove container f17bcbe904cd81a10c284c514b67c58202f4e2c3ca4d60106fc864ef76ddcd23
I0221 07:45:35.447837    8132 runtime.go:106] Attempting to remove container 6311e1988d5d88bcd727ff252dbc6ba9f20fb65857887ecc942449e0f53a4a38
I0221 07:45:36.124992    8132 runtime.go:106] Attempting to remove container b97e023456a03c2f87d053e0e77f337d381a90317dc28f6a4dd6204be7bbe41c
I0221 07:45:36.588894    8132 runtime.go:106] Attempting to remove container 47a25afb73b3a2a7c82ac7fcb5b4688a607dc8f69b9dcc9b461d3eba08642b6f
I0221 07:45:37.068368    8132 runtime.go:106] Attempting to remove container 007f2a7c755dbdd26f444dec8822ce6dbbe1c83358f00625b92bd0b9027bac02
I0221 07:45:37.524527    8132 runtime.go:106] Attempting to remove container 1dc53865b6bce2a2dd75f7ebec7cd383e64a88b0d254ce7ec4b3632cb1ecc105
I0221 07:45:37.980527    8132 runtime.go:106] Attempting to remove container 684567670d5b63e2a1d5c831609588340055d1eb3017c082bf3b5c7b6e866bb3
I0221 07:45:38.208825    8132 runtime.go:106] Attempting to remove container ca16d3c4b03e495bc8c827327e4557f135105331195d8da6fcc7d726ac2ea5dd
I0221 07:45:38.806210    8132 runtime.go:106] Attempting to remove container 1b3511d3ecb7d49525138d8054242244808ecbe78578da231a4b521b0b5325d6
I0221 07:45:39.333657    8132 runtime.go:106] Attempting to remove container a9d3ef0a218ab4b6d10434a1305140e1fc6e26a022c9c617b675c040b5b0eabe
I0221 07:45:39.961827    8132 runtime.go:106] Attempting to remove container e30b3b20ed041bfc0982280d2f29e44fb7b52b32a57123954ec213ac3a26a79b
I0221 07:45:40.410290    8132 runtime.go:106] Attempting to remove container 18d1189d016a9f5984a7d2bc341bbffe441e6019c6cf5ddda63ab53ca465bd6c
I0221 07:45:40.872203    8132 runtime.go:106] Attempting to remove container 05b532a7f4f33d6397bae1737714d2460c583f7f797d20d1f4290ca4a1e9788f
I0221 07:45:41.081341    8132 runtime.go:106] Attempting to remove container 02b637820ead92ae2aafa9b7cdd3cff941fb74ff250ff8da96e8f54fcab52bda
I0221 07:45:41.523571    8132 runtime.go:106] Attempting to remove container 413de7987af7fb2d19b02fceb29e2f362ecb97f0caf50e16b62b0e54154586d2
I0221 07:46:41.826999    8132 runtime.go:106] Attempting to remove container 413de7987af7fb2d19b02fceb29e2f362ecb97f0caf50e16b62b0e54154586d2
I0221 07:47:41.887824    8132 runtime.go:106] Attempting to remove container 413de7987af7fb2d19b02fceb29e2f362ecb97f0caf50e16b62b0e54154586d2
I0221 07:48:41.949817    8132 runtime.go:106] Attempting to remove container 413de7987af7fb2d19b02fceb29e2f362ecb97f0caf50e16b62b0e54154586d2
..
..
..

.

..

...

```


and so on

**Comment by nitinjagjivan** [comment]
Workaround is to remove all running containers manually followed by reset command as below- 

```
sudo ctr -n k8s.io i rm $(sudo ctr -n k8s.io i ls -q)
sudo crictl rm -f  $(sudo crictl ps | awk '{print $1}')
sudo rm -rf /etc/cni
sudo  kubeadm reset -f
systemctl restart containerd
systemctl restart kubelet
```

**Comment by neolit123** [comment]
technically kubeadm just shells to crictl for container removal, but kubeadm decides what are the "k8s managed containers". are there more such containers in 1.26.1 compared to 1 25.x?

**Comment by nitinjagjivan** [comment]
No, we have same set of containers. We just upgraded kubernetes to v1.26.1 and this problem started.
Kubernetes reset was quick when we downgraded kubernetes to v1.25.6

**Comment by neolit123** [comment]
if the number of containers during reset are the same, this might indicate something happening around kubelet / container runtime / crictl. but it seems odd... 
in any case it does not sound like a kubeadm problem.

**Comment by SataQiu** [comment]
It appears that some retries occurred when removing the following containers:
```sh
I0221 07:45:41.523571    8132 runtime.go:106] Attempting to remove container 413de7987af7fb2d19b02fceb29e2f362ecb97f0caf50e16b62b0e54154586d2
I0221 07:46:41.826999    8132 runtime.go:106] Attempting to remove container 413de7987af7fb2d19b02fceb29e2f362ecb97f0caf50e16b62b0e54154586d2
I0221 07:47:41.887824    8132 runtime.go:106] Attempting to remove container 413de7987af7fb2d19b02fceb29e2f362ecb97f0caf50e16b62b0e54154586d2
I0221 07:48:41.949817    8132 runtime.go:106] Attempting to remove container 413de7987af7fb2d19b02fceb29e2f362ecb97f0caf50e16b62b0e54154586d2
```
Maybe next time try manually executing the following command to find more:
```sh
crictl stopp POD-ID
crictl rmp POD-ID
```

**Comment by nitinjagjivan** [comment]
[nitin@********* ~]$ **sudo crictl stopp $(sudo crictl pods | awk '{print $1}' | grep -vE POD)**

WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint
 instead.
ERRO[0002] connect endpoint 'unix:///var/run/dockershim.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded
WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint
 instead.
ERRO[0002] connect endpoint 'unix:///var/run/dockershim.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded
FATA[0062] stopping the pod sandbox "fa0d3ee7f91ed": rpc error: code = Unknown desc = failed to destroy network for sandbox "fa0d3ee7f91ed5c0ea6bd170e9e0c0f4c0e0ff11fe5faa077bcfaca934c0dc81":
plugin type="calico" failed (delete): error getting ClusterInformation: the server was unable to return a response in the time allotted, but may still be processing the request (get ClusterInformations.crd.projectcalico.org default)

**Comment by nitinjagjivan** [comment]
Is it because of service account of policy changed from kubernetes v1.26.0?
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#manual-secret-management-for-serviceaccounts

**Comment by SataQiu** [comment]
> failed to destroy network for sandbox "fa0d3ee7f91ed5c0ea6bd170e9e0c0f4c0e0ff11fe5faa077bcfaca934c0dc81":
plugin type="calico" failed (delete): error getting ClusterInformation: the server was unable to return a response in the time allotted, but may still be processing the request (get ClusterInformations.crd.projectcalico.org default)

Looks like we found the reason for the longer reset time. 
Maybe try upgrading the Calico CNI plugin to solve this problem？

**Comment by nitinjagjivan** [comment]
We are using CNI calico v3.25.0 which is latest one.

**Comment by Munivarna** [comment]
root@ip-172-31-36-250:~# kubeadm init
[init] Using Kubernetes version: v1.26.2
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2023-03-04T13:47:45Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by Munivarna** [comment]
root@ip-:~# kubeadm init
[init] Using Kubernetes version: v1.26.2
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2023-03-04T13:47:45Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by SataQiu** [comment]
> root@ip-:~# kubeadm init [init] Using Kubernetes version: v1.26.2 [preflight] Running pre-flight checks error execution phase preflight: [preflight] Some fatal errors occurred: [ERROR CRI]: container runtime is not running: output: time="2023-03-04T13:47:45Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint "unix:///var/run/containerd/containerd.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService" , error: exit status 1 [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...` To see the stack trace of this error execute with --v=5 or higher

Hi @Munivarna 
Since kubeadm is just a shell to crictl, please check whether the containerd service is running properly. 
```sh
systemctl status containerd
crictl pods
```

**Comment by neolit123** [comment]
closing as stale issues. please add more comments if needed.
as noted kubeadm just shells to crictl and this is not a kubeamd issue per se.

**Comment by KaustubhDhokte** [comment]
I am facing this issue for k8s version 1.25.3.
