### ISSUE TITLE
Feature:  Add kubeadm upgrade deprecated list

### ISSUE THREAD

**Issue by burkempers** [kubernetes/kubeadm#2831]
FEATURE REQUEST

I would like a sub command to kubeadm update that will check all objects in the current cluster for object that have versions that will be deprecated in the current upgrade or future upgrades.

## Versions

**kubeadm version** (use `kubeadm version`): all

**Environment**:
- **Kubernetes version** (use `kubectl version`): andy
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): N/A
- **Kernel** (e.g. `uname -a`): N/A
- **Container runtime (CRI)** (e.g. containerd, cri-o): N/A
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): N/A
- **Others**: N/A

## What happened?
I work on an air gaped system and there have been times that kubernetes objects were not checked before hand for deprecated versions.  Would like the deprecated versions to be executable via command line to support automated functions

## What you expected to happen?
A list of objects that will be deprecated.

## Anything else we need to know?
Here is my own self managed bash script to do this for me, but it would be nice for this to be built into kubeadm for everyone to take advatage

```bash
#!/bin/bash

# getList {ojbectType} {apiVerion} {kubeVersion}
getList(){
  echo "Geting list deprecated objects for $1 in k8s version $3"
  kubectl get $1 -A -o jsonpath='{range .items[*]}{.kind}{"/"}{.metadata.name}{"\t\t"}{.apiVersion}{"\n"}{end}' | grep $2
  echo "\n ----"
}


# 1.29
getList flowcontrolresources "flowcontrol.apiserver.k8s.io/v1beta2" "1.29"

# 1.28
#getList flowcontrol "flowcontrol.apiserver.k8s.io/v1beta2" "1.28"

# 1.27
getList  csistoragecapacity "storage.k8s.io/v1beta1" "1.27"


# 1.26
getList flowcontrolresources "flowcontrol.apiserver.k8s.io/v1beta1" "1.26"
getList horizontalpodautoscaler "autoscaling/v2beta2" "1.26"


# 1.25
getList cronjob "batch/v1beta1" "1.25"
getList endpointslice "discovery.k8s.io/v1beta1" "1.25"
getList event "events.k8s.io/v1beta1" "1.25"
getList horizontalpodautoscaler "autoscaling/v2beta1" "1.25"
getList poddisruptionbudget "policy/v1beta1" "1.25"
getList podsecuritypolicy "policy/v1beta1" "1.25"
getList runtimeclass "node.k8s.io/v1beta1" "1.25"
```

**Comment by neolit123** [comment]
this seems like something that can be added to kubectl as a simplified subcommand.
it would be nice if kubectl can list / warn if objects in the clusters exist that will no longer work as expected once that apiserver is upgraded to N+1.

**Comment by SataQiu** [comment]
@burkempers  You can try this tool: https://github.com/doitintl/kube-no-trouble

> Kube No Trouble (kubent) is a simple tool to check whether you're using any of these API versions in your cluster and therefore should upgrade your workloads first, before upgrading your Kubernetes cluster.

**Comment by neolit123** [comment]
> You can try this tool: https://github.com/doitintl/kube-no-trouble

+1, kubeadm might seem like the right place given it does the upgrade, but we actually try to keep it as minimally scoped as possible.

closing as possible with other tools.

**Comment by pacoxu** [comment]
The official doc can be found in https://kubernetes.io/docs/reference/using-api/deprecation-guide/.
