### ISSUE TITLE
etcd containers are in exited state on secondary nodes during kubeadm upgrade

### ISSUE THREAD

**Issue by shubham-yewalekar** [kubernetes/kubeadm#2832]
### What happened?

I was upgrading k8s from 1.25 to 1.26 using kubeadm and I observed that etcd container on secondary node goes in exited state abruptly during kubeadm upgrade is running on the primary master
and when kubeadm attempts to upgrade that secondary node, it fails as etcd contianer is in exited state

etcd logs from the exited container on secondary node
`{"level":"warn","ts":"2023-02-27T10:46:11.751Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"81cc56872b5a76de","remote-peer-id-stream-handler":"81cc56872b5a76de","remote-peer-id-from":"6ca0e7112989ebdc","cluster-id":"f9826bd4b710680a"}
{"level":"warn","ts":"2023-02-27T10:46:11.752Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"81cc56872b5a76de","remote-peer-id-stream-handler":"81cc56872b5a76de","remote-peer-id-from":"6ca0e7112989ebdc","cluster-id":"f9826bd4b710680a"}
{"level":"warn","ts":"2023-02-27T10:46:11.756Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"81cc56872b5a76de","remote-peer-id-stream-handler":"81cc56872b5a76de","remote-peer-id-from":"c2e5566aa7127225","cluster-id":"f9826bd4b710680a"}
{"level":"warn","ts":"2023-02-27T10:46:11.756Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"81cc56872b5a76de","remote-peer-id-stream-handler":"81cc56872b5a76de","remote-peer-id-from":"c2e5566aa7127225","cluster-id":"f9826bd4b710680a"}

### What did you expect to happen?

etcd container on secondary node should not go down when kubeadm upgrade is running on the primary master 

### How can we reproduce it (as minimally and precisely as possible)?

Upgrading k8s cluster from 1.25 to 1.26 using kubeadm 

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
on-prem
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
i don't think this is supposed to happen and i don't think it can be seen in our e2e tests.

cc @ahrtr do you have any comments for us on this one?

**Comment by ahrtr** [comment]
The error message just means that the exited etcd member (on secondary node) received requests from an unknown peer.  It looks like a misconfiguration of multiple K8s clusters, e.g. IP address conflict? Please provide the complete log of the exited etcd member if you reproduce this issue again. How many etcd members are in the cluster? What's the etcd versions in K8s 1.25 and 1.26?

**Comment by neolit123** [comment]
closing as a stale issue.

you might find better answers on the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
