### ISSUE TITLE
Easier installation steps for kubeadm

### ISSUE THREAD

**Issue by dipankardas011** [kubernetes/kubeadm#2837]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

like k3s, where most of the operating configs are abstracted away, can `kubeadm` also do similar thing because currently we need to install some of prerequisites (like `containerd`) and make operating system capable to handle kubeadm

## Versions

**kubeadm version** (use `kubeadm version`): 1.25

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What you expected to happen?
convient way to install kubeadm in any linux distro most common is ubuntu

**Comment by neolit123** [comment]
> like k3s, where most of the operating configs are abstracted away, can kubeadm also do similar thing because currently we need to install some of prerequisites (like containerd) and make operating system capable to handle kubeadm

you could build a distribution image where containerd and kubeadm are built in and then you can install this distro image on all your machines.
image-builder does that for cluster-api machines.
https://github.com/kubernetes-sigs/image-builder

kubeadm is a low level tool that allows you to choose your own container runtime, CNI plugin and is flexible in terms of k8s config. k3s is a bundle that does not allow certain customizations, so there is a trade off.

in the future there could be a more bundled version of a kubeadm distribution, but this is out of scope for the time being and the maintainers likely do not have time to work on such a project.

**Comment by dipankardas011** [comment]
> > like k3s, where most of the operating configs are abstracted away, can kubeadm also do similar thing because currently we need to install some of prerequisites (like containerd) and make operating system capable to handle kubeadm
> 
> you could build a distribution image where containerd and kubeadm are built in and then you can install this distro image on all your machines.
> image-builder does that for cluster-api machines.
> https://github.com/kubernetes-sigs/image-builder
> 
> kubeadm is a low level tool that allows you to choose your own container runtime, CNI plugin and is flexible in terms of k8s config. k3s is a bundle that does not allow certain customizations, so there is a trade off.
> 
> in the future there could be a more bundled version of a kubeadm distribution, but this is out of scope for the time being and the maintainers likely do not have time to work on such a project.
> 
> 

Got it✌️
