### ISSUE TITLE
kubeadm init fail，k8sv1.25.3 cri-docker

### ISSUE THREAD

**Issue by yuhonglei666** [kubernetes/kubeadm#2838]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): v1.25.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.25.3
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): ubuntu18.04.2 22.04.1
- **Kernel** (e.g. `uname -a`): 4.15.0-45-generic  5.15.0-60-generic
- **Container runtime (CRI)** (e.g. containerd, cri-o): cri-docker
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): flannel
- **Others**:
![飞书20230311-105945](https://user-images.githubusercontent.com/94445273/224461459-966a9ff7-7748-4d85-ad43-e83cb5545090.jpeg)
![飞书20230311-110547](https://user-images.githubusercontent.com/94445273/224462128-0b849275-e719-44de-ac6b-28d6d7c80200.jpeg)

## What happened?
Cluster initialization error, but cri-docker runs normally, upgrade kernel and version is not possible。
Sometimes initializations work, most don't

**Comment by neolit123** [comment]
please use the support channels for help.
you can also debug this problem with `crictl ...<socket of cri-dockerd>`

/support

**Comment by heisnamsanjay** [comment]
I'm facing the same problem - is there any fix for this issue?

**Comment by neolit123** [comment]
it's probably a cri dockerd problem. try debugging the socket with 'crictl ... info'
