### ISSUE TITLE
Error: unknown flag: --deployment-controller-sync-period kube-controller-manager:v1.26.x

### ISSUE THREAD

**Issue by dantasgut** [kubernetes/kubeadm#2839]
**unknown flag: --deployment-controller-sync-period**

**BUG REPORT**

After run kubectl init in order to install cluster, the pod of **kube-controller-manager** CrashLoopBackOff.

**Environment**:
    Kubernetes version: 1.26.x
    OS: ubuntu 22.04
    
**What happened?**
When run kubectl logs -p kube-controller-manager-xxx-xxx-xxx -n kube-system in the end of log, there is the error: 
**Error: unknown flag: --deployment-controller-sync-period**
This parameter is present in the file /etc/kubernetes/manifests/kube-controller-manager.yaml

**Snipshet of the file**
kube-controller-manager:
    Container ID:  containerd://43ab71f4c546dcfab88fa4c8e70baa83277fac9d6ae2a34545d08e1086883ec0
    Image:         registry.k8s.io/kube-controller-manager:v1.26.0
    Image ID:      registry.k8s.io/kube-controller-manager@sha256:26e260b50ec46bd1da7352565cb8b34b6dd2cb006cebbd2f35170d50935fb9ec
    Port:          <none>
    Host Port:     <none>
    Command:
      kube-controller-manager
      --allocate-node-cidrs=true
      --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
      --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
      --bind-address=127.0.0.1
      --client-ca-file=/etc/kubernetes/pki/ca.crt
      --cluster-cidr=10.244.0.0/16
      --cluster-name=klass
      --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
      --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
      --controllers=*,bootstrapsigner,tokencleaner
      **--deployment-controller-sync-period=50s**
      --kubeconfig=/etc/kubernetes/controller-manager.conf
      --leader-elect=true
      --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
      --root-ca-file=/etc/kubernetes/pki/ca.crt
      --service-account-private-key-file=/etc/kubernetes/pki/sa.key
      --service-cluster-ip-range=10.96.0.0/12
      --use-service-account-credentials=true

In order to apply a temporally solution, I edited this file and remove this attribute and it works, but there is a bug that needs fix.

**Comment by pacoxu** [comment]
The flag was removed in https://github.com/kubernetes/kubernetes/pull/107178 since v1.24 which is deprecated in v1.23.

BTW, how to reproduce it by kubeadm?

**Comment by dantasgut** [comment]
Running command sudo kubeadm --v=5 init --config kubeadm-config.yaml using kubeadm-config.yaml to version kubernetes version v1.26.2  like this:

apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- token: "xxxxxxxxxxxxxxx"
  description: "default kubeadm bootstrap token"
  ttl: "0"
localAPIEndpoint:
  advertiseAddress: 192.168.x.x
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.26.2
clusterName: klass
controlPlaneEndpoint: 192.168.x.x:6443
networking:
  podSubnet: "10.244.0.0/16"
  dnsDomain: "cluster.local"
apiServer:
  certSANs:
  - 192.168.x.x
  - 192.168.x.x

  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
  extraArgs:
    max-requests-inflight: "1000"
    max-mutating-requests-inflight: "500"        
    default-watch-cache-size: "500"
    watch-cache-sizes: "persistentvolumeclaims#1000,persistentvolumes#1000"

controllerManager:
  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
  extraArgs:
    deployment-controller-sync-period: "50s"
# scheduler:
#   # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
#   extraArgs:
#     address: 0.0.0.0
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd

But it was my mistake I add 
**extraArgs:
    deployment-controller-sync-period: "50s"** on configuration yaml to start kubeadm
Sorry and thank you.

**Comment by SataQiu** [comment]
per above comment
/close
