### ISSUE TITLE
API server is throwing error - Unable to remove old endpoints from kubernetes service: no master IPs were listed in storage

### ISSUE THREAD

**Issue by chittu11** [kubernetes/kubeadm#2844]
We are seeing API server is not responding intermittently and throwing the below error. after few mins. its working properly but its breaking our Workflow.

**Error:**

`The connection to the server 1xx.xx.xx.xx:6443 was refused - did you specify the right host or port?`

**API Server Error:**

`Unable to remove old endpoints from kubernetes service: no master IPs were listed in storage`

Made sure swapp and firewal is disabled. 

Kubernetes Version:

`v1.18.5`

Thank you
CS

**Comment by pacoxu** [comment]
/kind support

The version is quite old which is [end of life](https://endoflife.date/kubernetes).

The error message provided cannot figure out the reason.

**Comment by chittu11** [comment]
Thank you @pacoxu.
Our clusters working fine for the last 2 and half years with no issues. Yes, we are planning to move to latest K8 version but now we are kind of struck with this issue. and its happening intermittently. and hard to figure out whether its underlting infra causing issue or some K8 bug. its simply throwing the below error and our jobs getting failed.

**The connection to the server 1xx.xx.xx.xx:6443 was refused - did you specify the right host or port?**

and when I checked API server logs found this:

E0321 21:08:22.145673       1 controller.go:152] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/10.100.192.198, ResourceVersion: 0, AdditionalErrorMsg: 
I0321 21:08:22.147139       1 crd_finalizer.go:266] Starting CRDFinalizer
I0321 21:08:22.160324       1 controller.go:86] Starting OpenAPI controller
I0321 21:08:22.160373       1 customresource_discovery_controller.go:209] Starting DiscoveryController
I0321 21:08:22.160402       1 naming_controller.go:291] Starting NamingConditionController
I0321 21:08:22.160421       1 establishing_controller.go:76] Starting EstablishingController
I0321 21:08:22.160442       1 nonstructuralschema_controller.go:186] Starting NonStructuralSchemaConditionController
I0321 21:08:22.160463       1 apiapproval_controller.go:186] Starting KubernetesAPIApprovalPolicyConformantConditionController
I0321 21:08:22.245244       1 shared_informer.go:230] Caches are synced for cluster_authentication_trust_controller 
I0321 21:08:22.245291       1 cache.go:39] Caches are synced for autoregister controller
I0321 21:08:22.245908       1 shared_informer.go:230] Caches are synced for crd-autoregister 
I0321 21:08:22.246003       1 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I0321 21:08:22.275735       1 cache.go:39] Caches are synced for AvailableConditionController controller
I0321 21:08:22.329621       1 controller.go:609] quota admission added evaluator for: leases.coordination.k8s.io
I0321 21:08:22.342002       1 controller.go:609] quota admission added evaluator for: endpoints
I0321 21:08:22.354826       1 client.go:361] parsed scheme: "endpoint"
I0321 21:08:22.354879       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379  <nil> 0 <nil>}]
I0321 21:08:23.152265       1 controller.go:130] OpenAPI AggregationController: action for item : Nothing (removed from the queue).
I0321 21:08:23.152290       1 controller.go:130] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
I0321 21:08:23.181686       1 trace.go:116] Trace[801977728]: "List" url:/api/v1/pods,user-agent:kube-apiserver/v1.18.19 (linux/amd64) kubernetes/ac0cc73,client:::1 (started: 2023-03-21 21:08:22.184195626 +0000 UTC m=+4.689677485) (total time: 997.414614ms):
Trace[801977728]: [997.412182ms] [984.29361ms] Writing http response done count:8274
I0321 21:08:23.182039       1 storage_scheduling.go:143] all system priority classes are created successfully or already exist.
I0321 21:08:24.784286       1 trace.go:116] Trace[438249732]: "List etcd3" key:/argoproj.io/workflows,resourceVersion:,limit:10000,continue: (started: 2023-03-21 21:08:22.370387565 +0000 UTC m=+4.875869446) (total time: 2.413853037s):
Trace[438249732]: [2.413853037s] [2.413853037s] END

**Comment by neolit123** [comment]
/support

let's move the discussion to slack or the support forums.
check the bot links below please.

**Comment by pacoxu** [comment]
There is a long thread on a similar issue at https://github.com/kubernetes/kubernetes/issues/76146#issuecomment-582093454.
