### ISSUE TITLE
1.26 dryrun job failing

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2848]
has been failing since 23th of march
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-1-26

culprit seems to be upgrade where it tries 1.28, skipping 1.27

> --with-init-artifacts=v1.26.3-rc.0.57+e6323abe65c431 --with-upgrade-artifacts=v1.28.0-alpha.0.13+c3e7eca7fd3845

> Specified version to upgrade to "v1.28.0-alpha.0.13+c3e7eca7fd3845" is too high; kubeadm can upgrade only 1 minor version at a time

upgrade should be for 1.27. this hints the job fetches latest .28 artifacts.

**Comment by pacoxu** [comment]
This is after the v1.28.0-alpha.0 released.

ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-26-latest is using https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-26-latest/1640598899607474176/build-log.txt
```
 kubeadm upgrade apply -f v1.28.0-alpha.0.13+c3e7eca7fd3845 --v=6
```

But ci-kubernetes-e2e-kubeadm-kinder-dryrun-1-26 is using without `-f`
```
/bin/bash -c docker exec kinder-dryrun-control-plane-1 /kinder/upgrade/v1.28.0-alpha.0.13+c3e7eca7fd3845/kubeadm upgrade apply v1.28.0-alpha.0.13+c3e7eca7fd3845 --ignore-preflight-errors=Swap,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables --allow-release-candidate-upgrades=true --allow-experimental-upgrades=true --dry-run=true --v=6 || exit 1

```
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-dryrun-1-26/1640579773262467072/build-log.txt

**Comment by SataQiu** [comment]
@neolit123 If we do them like the upgrade job, we will lose the init/join/reset dry-run tests for the latest version.
Thanks for your quick fix @pacoxu
