### ISSUE TITLE
registry.k8s.io/pause:3.6 does not use the address specified by --image-repository when executing kubeadm init

### ISSUE THREAD

**Issue by Max-Qiu** [kubernetes/kubeadm#2851]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT
### What happened?

1. use `kubeadm init  ......  --image-repository registry.aliyuncs.com/google_containers` , it show : <br> [wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory /etc/kubernetes/manifests". This can take up to 4m0s<br>[kubelet-check] Initial timeout of 40s passed.
3. then use `systemctl status -l kubelet.service` , it show :<br>remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to get sandbox image \"registry.k8s.io/pause:3.6\": failed to pull image \"registry.k8s.io/pause:3.6\": failed to pull and unpack image \"registry.k8s.io/pause:3.6\": failed to resolve reference \"registry.k8s.io/pause:3.6\": failed to do request: Head \"https://registry.k8s.io/v2/pause/manifests/3.6\": net/http: TLS handshake timeout"

### What did you expect to happen?

I hope that `registry.k8s.io/pause:3.6` will be downloaded through the address specified by `--image-repository`

### How can we reproduce it (as minimally and precisely as possible)?

1. Block `registry.k8s.io`
2. Execute `kubeadm init --control-plane-endpoint=192.168.220.101 --kubernetes-version v1.26.3 --pod-network-cidr=10.244.0.0/16 --image-repository registry.aliyuncs.com/google_containers`

### Anything else we need to know?

I need to execute the following code on each node to solve the problem

```bash
ctr -n k8s.io i pull registry.aliyuncs.com/google_containers/pause:3.6
ctr -n k8s.io i tag registry.aliyuncs.com/google_containers/pause:3.6 registry.k8s.io/pause:3.6
```

### Kubernetes version

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

### OS version

```console
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux node1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pacoxu** [comment]
Check your containers configuration.

**Comment by neolit123** [comment]
see

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#override-pause-image-containerd

/kind support

**Comment by luyajin** [comment]
> 

我修改了这个配置怎么一直都不生效呢

**Comment by luyajin** [comment]
sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6"

**Comment by linonetwo** [comment]
Is this a bug? i'm using docker, not containerd , how to fix it on user side?

**Comment by chendave** [comment]
> Is this a bug? i'm using docker, not containerd , how to fix it on user side?

this is not a bug, it's just a matter of configuration, shouldn't docker use containerd as the runtime by default?

**Comment by neolit123** [comment]
> Is this a bug? i'm using docker, not containerd , how to fix it on user side?

k8s maintainers recommend to move to containerd or cri-o.
docker (via cri-dockerd) is no longer well supported.

**Comment by zhkmxx9302013** [comment]
> 我也遇到了和你类似的问题，我的解决方案如下：
> 
> ```
> mkdir /etc/containerd
> containerd config default > /etc/containerd/config.toml
> ```
> 
> 接着编辑/etc/containerd/config.toml文件，把`[plugins."io.containerd.grpc.v1.cri"]`块下的`sandbox_image`值改为国内镜像即可，如下方代码所示（pause版本因人而异）：
> 
> ```
> sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6"
> ```
> 
> 接着重启服务，重新init即可：
> 
> ```
> systemctl restart containerd.service
> ```
困扰了半个月...换了一堆源，原来在这里。。

**Comment by jiangxiaoqiang** [comment]
> 我也遇到了和你类似的问题，我的解决方案如下：
> 
> ```
> mkdir /etc/containerd
> containerd config default > /etc/containerd/config.toml
> ```
> 
> 接着编辑/etc/containerd/config.toml文件，把`[plugins."io.containerd.grpc.v1.cri"]`块下的`sandbox_image`值改为国内镜像即可，如下方代码所示（pause版本因人而异）：
> 
> ```
> sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6"
> ```
> 
> 接着重启服务，重新init即可：
> 
> ```
> systemctl restart containerd.service
> ```

我也是这个问题，不过是在集群运行过程中无法拉取。修改了配置不生效不知道是什么原因。

**Comment by Kensleycc** [comment]
> 我也是这个问题，不过是在集群运行过程中无法拉取。修改了配置不生效不知道是什么原因。

记录一下，我的情况是：

使用cri为cri-dockerd，已经修改`/usr/lib/systemd/system/cri-docker.service`
```
cat /usr/lib/systemd/system/cri-docker.service
...
ExecStart=/usr/bin/cri-dockerd --container-runtime-endpoint fd:// --network-plugin=cni --pod-infra-container-image=<Repository Path>/pause:3.8
```

主节点`kubeadm init`没问题，**worker join 之后一直处于对应的 kube-proxy pod 一直处于`FailedCreatePodSandBox`** .

最后定位原因是worker未重启cri-dockerd进程使配置生效:
```
# systemctl status cri-docker.service 

● cri-docker.service - CRI Interface for Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/cri-docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-08-27 11:44:00 UTC; 21h ago
TriggeredBy: ● cri-docker.socket
       Docs: https://docs.mirantis.com
   Main PID: 103962 (cri-dockerd)
      Tasks: 11
     Memory: 18.6M
     CGroup: /system.slice/cri-docker.service
             └─103962 /usr/bin/cri-dockerd --container-runtime-endpoint fd://
```

重启后worker重新join即可:
```
systemctl restart cri-docker.service
```

**Comment by neolit123** [comment]
you probably need to tell cri-dockerd to use exactly that image.
maybe there is a cri-dockerd config for that. try asking the cri-docker maintainers.

**Comment by WQL782795** [comment]
> 我也遇到了和你类似的问题，我的解决方案如下：
> 
> ```
> mkdir /etc/containerd
> containerd config default > /etc/containerd/config.toml
> ```
> 
> 接着编辑/etc/containerd/config.toml文件，把`[plugins."io.containerd.grpc.v1.cri"]`块下的`sandbox_image`值改为国内镜像即可，如下方代码所示（pause版本因人而异）：
> 
> ```
> sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6"
> ```
> 
> 接着重启服务，重新init即可：
> 
> ```
> systemctl restart containerd.service
> ```



> 我也遇到了和你类似的问题，我的解决方案如下：
> 
> ```
> mkdir /etc/containerd
> containerd config default > /etc/containerd/config.toml
> ```
> 
> 接着编辑/etc/containerd/config.toml文件，把`[plugins."io.containerd.grpc.v1.cri"]`块下的`sandbox_image`值改为国内镜像即可，如下方代码所示（pause版本因人而异）：
> 
> ```
> sandbox_image = "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6"
> ```
> 
> 接着重启服务，重新init即可：
> 
> ```
> systemctl restart containerd.service
> ```

义父+1！！！
