### ISSUE TITLE
PodSecurity labels for required namespaces

### ISSUE THREAD

**Issue by jcpunk** [kubernetes/kubeadm#2854]
## What keywords did you search in kubeadm issues before filing this one?

PodSecurity

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

It would be helpful if, when bootstrapping a cluster, the `pod-security.kubernetes.io/{enforce,audit,warn}` elements were set automatically on things like the `kube-system` namespace and other system namespaces.

This would make it much easier to review which namespaces have this applied, and provide a hint to folks that they should consider this for non-system namespaces.

## Versions

**kubeadm version** (use `kubeadm version`): pod-security.kubernetes.io

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-09T18:09:54Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?
I had to manually exclude `kube-system` from the default security policy enforcement file

## What you expected to happen?
When a cluster is bootstrapped it is aware of the pod security policies feature and applies the correct labels automatically to the system namespaces

## How to reproduce it (as minimally and precisely as possible)?
boot strap a cluster with kubeadm
Follow https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/ but make a typo (`s/kube-system/kubesystem/`)
restart cluster and watch it fail

**Comment by neolit123** [comment]
> I had to manually exclude kube-system from the default security policy enforcement file

i think we should keep this manual, so that users can make the choice themselves.

if we make the change in kubeadm it can either flood logs or break user expectations.

**Comment by neolit123** [comment]
@SataQiu @pacoxu wdyt?

**Comment by pacoxu** [comment]
I prefer to leave it to users. As users can easily manage the labels by themselves. https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/

For instance, they can add a policy to all ns like the below:
```
kubectl label --dry-run=server --overwrite ns --all \
    pod-security.kubernetes.io/enforce=baseline
```

The default configurations should be defined via the --admission-control-config-file of kube-apiserver.
https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/

**Comment by SataQiu** [comment]
I also prefer to let users make their own choices. The policy changes can affect the behavior of existing clusters and cause unexpected problems. And the tools on top of `kubeadm` can  achieve it easily.

**Comment by pacoxu** [comment]
BTW, for fulfilling CIS benchmark or something like`how to install a secure cluster with kubeadm?`, this should be included.

I am not sure if there is already a similar doc or blog. (Or even a popular github repo.)  I may help to update it.

**Comment by jcpunk** [comment]
I'm primarily interested in having:
```
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
```

automatically applied to `kube-system` so that the security settings on that namespace are explicit.

**Comment by neolit123** [comment]
looks like we have consensus to not apply such labels automatically. 

> automatically applied to kube-system so that the security settings on that namespace are explicit.

instead, for more clarity this can be PRed in the kubeadm documentation at kubernetes/website where k8s.io is hosted.

you can help us by loggin issue there + pr if you'd like.

**Comment by neolit123** [comment]
> I am not sure if there is already a similar doc or blog. (Or even a popular github repo.) I may help to update it.

i don't know if there is. CIS bench was never approved by core k8s maintainers, AFAIK.
