### ISSUE TITLE
in kubeadm kubectl didnot work correctly

### ISSUE THREAD

**Issue by hediehMadah** [kubernetes/kubeadm#2856]
Hello I have a problem with this command
sudo kubeadm init --pod-network-cidr 10.10.0.0/16 --kubernetes-version 1.26.3 --node-name master

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 192.168.102.212:6443 --token 0y6dye.97z0kvrhjjno16zx \
        --discovery-token-ca-cert-hash sha256:4b70ecb359beb7bd0de0e2faa97d5c3abdd4965af337c67170f9a77165e0137e 
user@master:~$ ^C
user@master:~$  mkdir -p $HOME/.kube                                                                                                                                        
user@master:~$ ^C
user@master:~$   sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo: unable to resolve host master: Name or service not known
cp: overwrite '/home/user/.kube/config'? y
user@master:~$  sudo chown $(id -u):$(id -g) $HOME/.kube/config
sudo: unable to resolve host master: Name or service not known
user@master:~$ kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml
/usr/local/bin/kubectl: line 1: syntax error near unexpected token `<'
/usr/local/bin/kubectl: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>'
user@master:~$  kubectl get nodes
/usr/local/bin/kubectl: line 1: syntax error near unexpected token `<'
/usr/local/bin/kubectl: line 1: `<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>We're sorry, but this service is not available in your location</Details></Error>'
user@master:~$ sudo kubectl get nodes
sudo: unable to resolve host master: Name or service not known
[sudo] password for user: 
/usr/local/bin/kubectl: 1: Syntax error: redirection unexpected
user@master:~$ 
I was using the Vpn for solve  this problem but it did not work

**Comment by neolit123** [comment]
please try asking on the support channels. links in the below

/support
