### ISSUE TITLE
could not find officially supported version of etcd for Kubernetes v1.27.0

### ISSUE THREAD

**Issue by vndroid** [kubernetes/kubeadm#2859]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.27.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.27.0
- **Cloud provider or hardware configuration**: Intel Xeon
- **OS** (e.g. from /etc/os-release): Debian 11
- **Kernel** (e.g. `uname -a`): 5.10.0-21-amd64
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico
- **Others**:

## What happened?

When init cluster display: 

```
W0414 21:05:35.799208   12669 images.go:80] could not find officially supported version of etcd for Kubernetes v1.27.0, falling back to the nearest etcd version (3.5.7-0)
```

## What you expected to happen?

None Warning Info

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/117169 this may help fix it.

**Comment by neolit123** [comment]
> W0414 21:05:35.799208   12669 images.go:80] could not find officially supported version of etcd for Kubernetes v1.27.0, falling back to the nearest etcd version (3.5.7-0)

this is expected when a k8s release did not bump etcd in kubeadm.

watch this or other prs
https://github.com/kubernetes/kubernetes/pull/117169

**Comment by vndroid** [comment]
I don't understand why this is normal info.
