### ISSUE TITLE
Support for more than one DNS Deployment/Service for faster failover

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubeadm#2862]
## What keywords did you search in kubeadm issues before filing this one?

"dns", also skimmed the kubeadm docs looking for a solution

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

**Problem description**:

When a coredns pod goes down (for example, due to node running out of disk space, or some other unpredictable event), it takes some time for kubelet to declare the pod "not ready", and then for it to be removed from the Endpoints and finally from the dataplane.  During that time, DNS clients can see their DNS requests **and their retries** all go to the failed pod (and thus get no response).

This is due to an interaction between flow-based load balancing for UDP (as used by kube-proxy)  and the behaviour of (at least glibc's) DNS resolver:  

* When the glibc resolver only has one nameserver and it retries a DNS query, it re-uses the same source port.  
* This results in all the retry packets being classified as part of one flow by conntrack.  
* Once a backend coredns pod has been chosen for the flow, the retry packets all go tot he same pod.  
* If the backend pod has failed, the DNS resolution fails until the pod is marked as non-ready (plus extra time for kube-proxy to clean up the dataplane state).

The impact is that, with default configuration, DNS resolution times out instead of the retry going to a good pod.  This can be fatal for many long-lived applications.

We saw the same behaviour in iptables mode, IPVS mode and it's likely that thirdparty eBPF dataplanes suffer the same problem.

**Suggested enhancement**

Since changing DNS resolver behaviour is infeasible (and none of glibc's standard configuration seems to be of much use here), I think the best solution is to:

* Deploy two kube-dns deployments
* Deploy two kube-dns services, say with well-known IPs `10.96.0.10` and `10.96.0.11`
* Configure both of those as nameservers for the pods.

Then, if any one coredns pod goes down, it will affect only one service and the resolver will naturally retry via the other service.

**Comment by neolit123** [comment]
> When a coredns pod goes down (for example, due to node running out of disk space, or some other unpredictable event), it takes some time for kubelet to declare the pod "not ready", and then for it to be removed from the Endpoints and finally from the dataplane. During that time, DNS clients can see their DNS requests and their retries all go to the failed pod (and thus get no response).

> Then, if any one coredns pod goes down, it will affect only one service and the resolver will naturally retry via the other service.

it feels there should be a better opt-in solution to this - i.e. users that need it can deploy their own coredns or patch corends post kubeadn init/upgrade.

i wonder if one can enable some coredns deployment / spec settings that can allow them to cleanup unwanted coredns pods more swiftly.

have you tried terminationGracePeriodSeconds with a low value?

doc refs
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/nodelocaldns helps during dns upgrades or downtime as there is a local cache.

- low termination period helps for upgrade; for node network issue, it will wait until the node is not ready(details in https://github.com/kubernetes-sigs/kubespray/blob/master/docs/kubernetes-reliability.md#fast-update-and-fast-reaction)

/sig network
/area dns

**Comment by aojea** [comment]
But why it takes long to become not ready?

That seems the problem

**Comment by szuecs** [comment]
DNS should bypass conntrack to local node and from there do whatever you want.

**Comment by fasaxc** [comment]
> But why it takes long to become not ready?

Kubernetes readiness probes are relatively slow to time things out (say a probe every 10s and 3 probes needed to fail the pod), and updating the service load balancing across the cluster takes seconds (possibly 30s in a very large cluster).

Anything over 1s is too slow for DNS retries; I think we should work with what DNS provides, which is to have a primary/secondary DNS server.  We can't really change all the libcs to work better with k8s load balancing behaviour.

**Comment by neolit123** [comment]
before adding such a change in kubeadm i would like to see sig network approval. it is the group responsible for networking topics like this one.

https://github.com/kubernetes/community/tree/master/sig-network

they have slack, zoom and a mailing list. if you can get their feedback - great.

**Comment by neolit123** [comment]
thanks @chrisohaver both 2xdeployments and 2xservices seem like non-optimal solutions.

for problesknow there was WIP support for subsecond probes, but that would be quite expensive.

> This scenario is how things would play out if there is a problem with a CoreDNS Pod that causes it to "hang" or become otherwise unresponsive/unreachable, but still be running. If an issue causes the CoreDNS Pod to exit, I would expect kubeproxy to adjust much more quickly.

my understanding is that when the pod fails, "the system" simply does not react fast enough.

nodelocal seems like our best suggestion for users? it is an existing solution that just workarounds the problem.
@fasaxc WDYT?

**Comment by fasaxc** [comment]
@neolit123 nodelocal DNS still has a SPOF for all the pods on one node: the local codedns instance.  IIUC, if that hangs/goes down then all pods on a node fail to resolve.

Aggressive liveness probes don't solve the problem.  Even if we could set them to 1 probe/s (which has its own issues), you'd want >1 failure before declaring a pod dead so, at least 3s before marking a pod non-ready, then ~10s for that to flow through to kube-proxy in a  large cluster.  In a very large cluster, updating iptables can take even longer.

Solving this in the dataplane is actually very difficult.  In iptables/IPVS modes conntrack is required in order to reverse-NAT the response packets and linux conntrack is symmetric so the retry packet's conntrack entry would clash with the first packet's conntrack entry.  In BPF dataplanes you could cook something up but it's still tricky and would require a bunch of special cases.  I think the best option is to work with DNS's existing capabilities by giving the pods two unique DNS server IPs and then adjusting the kubernetes DNS infra to work with that.

To be clear, I don't think we need more coredns pods overall, they just need to be split into >1 group.  And that could be 100% optional for those who need HA DNS.

**Comment by sftim** [comment]
We may be able to work around this with an enhancement to kube-proxy

If we could mark (annotate?) the EndpointSlices to request a per-packet round-robin approach, I think that could work. Acting on that marker, kube-proxy could set up packet forwarding rules to send alternative client requests to different replicas of the same Deployment, even when the source and destination tuples are the same.
Return packets can still be steered to the right place (the client Pod).

We can leave the default for UDP Services to provide flow-based tracking. This is a safer default; it just happens that the DNS protocol is request/response and doesn't require it.

**Comment by fasaxc** [comment]
@sftim I thought about that option but I'm not sure there's a good way to implement it.  In iptables, I don't think conntrack likes to have overlapping tuples (and you'd need multiple tuples to make sure you could return a late reply from the first request).  In IPVS, I don't think there's a non-flow option.  In BPF dataplanes, you could do it but it's a whole extra type of load balancing to add, which is only really useful for DNS.  As someone who maintains a BPF dataplane, I'd rather not muddy it up with a special DNS mode (and I'd rather not leave iptables/IPVS users out).

**Comment by neolit123** [comment]
> In any case, sounds like I should raise with sig-network.

did you do that @fasaxc ?
i think i saw a slack discussion with a non-lead, but better join their zoom call update us if they have comments / proposals.

**Comment by neolit123** [comment]
> > In any case, sounds like I should raise with sig-network.
> 
> did you do that @fasaxc ? i think i saw a slack discussion with a non-lead, but better join their zoom call update us if they have comments / proposals.

closing - one month without reply.
re-revisit / re-open in the future if needed. currently there are no other requests for this.
