### ISSUE TITLE
Clarify external CA support without TLS bootstrapping

### ISSUE THREAD

**Issue by adammw** [kubernetes/kubeadm#2865]
## What keywords did you search in kubeadm issues before filing this one?

bootstrap, tls, external ca

## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST / documentation improvement

## Versions

**kubeadm version**: v1.24.13

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.24.8
- **Cloud provider or hardware configuration**: AWS
- **OS**: Ubuntu 20.04.6 LTS
- **Kernel** (e.g. `uname -a`): 5.15.0-1031-aws #35~20.04.1-Ubuntu
- **Container runtime (CRI)**: containerd
- **Container networking plugin (CNI)**: https://github.com/aws/amazon-vpc-cni-k8s
- **Others**:

## What happened?
Using `kubeadm join` to manually join an existing (non-kubeadm) cluster, with certificates supplied for kubelet in the `--discovery-file` flag.

`kubeadm-config` and `kubelet-config` configmaps were manually created with `kubeadm init phase upload-config`.

## What you expected to happen?
That `kubeadm join` would trigger the external CA behaviour and decide not to attempt to perform TLS bootstrapping, and instead supply the credentials to kubelet verbatim.

Instead, kubeadm supplied these credentials to kubelet as `bootstrap-kubeconfig`, which then meant kubelet attempted to create a CSR for TLS certificates that it would actually attempt to use. Our cluster does not have a CSR ability, instead that is handled externally from Kubernetes, however there is no flag or switch to tell kubeadm that the certificates provided are already valid.

## Anything else we need to know?
Context for this request is that we are looking to standardize our existing internal bootstrapping logic on kubeadm if possible from our current setup.

Looking to either clarify the documentation on external CA behaviour, or to request this flag as a feature to enable certificates to be used verbatim.

**Comment by neolit123** [comment]
how does kubeadm join behave if you pass the discovery file to the join command but also manually write this file `/etc/kubernetes/kubelet.conf` with valid kubelet client credentials? if the file exists the kubelet should skip client bootstrap and just use the credentials in the file once kubeadm starts the kubelet.


if this just works, one option would be for us to just document it. (1)
i think this is the option i prefer for the time being.

in general i agree that passing full credentials (client cert, key and ca cert) should skip client bootstrap, but we have to acknowledge that the discovery file is a "cluster discovery file" - a way to establish node / cluster trust and it's not a way to pass kubelet client credentials. 

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#file-or-https-based-discovery

if the user passes a kubelet certificate in the file it must be validated as such.

> In order to be authorized by the Node authorizer, kubelets must use a credential that identifies them as being in the system:nodes group, with a username of system:node:<nodeName>. This group and user name format match the identity created for each kubelet as part of [kubelet TLS bootstrapping](https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/).

https://kubernetes.io/docs/reference/access-authn-authz/node/

**Comment by adammw** [comment]
Testing with `/etc/kubernetes/kubelet.conf` being supplied, I get first errors with preflight:
```
[preflight] Some fatal errors occurred:
[ERROR FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists
```

However, ignoring that preflight error, the node does actually seem to join correctly:
```
I0426 23:42:19.016270    4562 kubelet.go:119] [kubelet-start] writing bootstrap kubelet config file at /etc/kubernetes/bootstrap-kubelet.conf
I0426 23:42:19.017165    4562 kubelet.go:134] [kubelet-start] writing CA certificate at /etc/kubernetes/pki/ca.crt
I0426 23:42:19.017926    4562 kubelet.go:155] [kubelet-start] Checking for an existing Node in the cluster with name "ip-172-30-225-133.us-west-2.compute.internal" and status "Ready"
I0426 23:42:19.022270    4562 kubelet.go:170] [kubelet-start] Stopping the kubelet
W0426 23:42:19.027628    4562 kubelet.go:63] [kubelet-start] WARNING: unable to stop the kubelet service momentarily: [exit status 5]
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
I0426 23:42:19.235873    4562 cert_rotation.go:137] Starting client certificate rotation controller
I0426 23:42:19.236808    4562 kubelet.go:218] [kubelet-start] preserving the crisocket information for the node
I0426 23:42:19.236822    4562 patchnode.go:31] [patchnode] Uploading the CRI Socket information "unix:///var/run/containerd/containerd.sock" to the Node API object "ip-172-30-225-133.us-west-2.compute.internal" as an annotation

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
```

The bootstrap-kubeconfig flag is still passed to kubelet, however it seems to point to a file that doesn't exist (not sure why - the kubeadm logs said it was written), so although kubelet logs `server.go:813] "Client rotation is on, will bootstrap in background"` it doesn't seem to create a CSR in the cluster.

**Comment by neolit123** [comment]
>  it doesn't seem to create a CSR in the cluster.

yes, because preparing a kubelet.conf and skipping TLS bootstrap is a supported use case by the kubelet.

> However, ignoring that preflight error, the node does actually seem to join correctly

ok, i think we can just document this. i will write down some example text here in the ticket and mark it as help wanted.

the preflight check is there to ensure that there isn't s stale kubelet.conf. kubeadm is designed around TLS bootstrap as a prereq, but this should work fine.

**Comment by neolit123** [comment]
logged this docs ticket:
https://github.com/kubernetes/website/issues/40874

please follow it / help with us with a PR.

thanks
