### ISSUE TITLE
Upgrade / downgrade function loses encryption-provider-config setting

### ISSUE THREAD

**Issue by instantlinux** [kubernetes/kubeadm#2867]
## What keywords did you search in kubeadm issues before filing this one?

`encryption-provider`

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:35:06Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu 22.04.2 LTS
- **Kernel** (e.g. `uname -a`): 5.15.0-71
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd.io 1.6.20-1
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): flannel
- **Others**:

## What happened?

Attempted to `kubeadm upgrade apply 1.26.4`. Struggled for a couple hours with an unrelated issue (the containerd v1 vs v2 incompatibility), ran out of time and attempted downgrade with `kubeadm upgrade apply 1.25.4`. The cluster didn't recover upon this downgrade, with error messages that look like this from apiserver:
```
illegal base64 data at input byte 3
```

Because I use an encryption-provider-config setting in the file /etc/kubernetes/manifests/kube-apiserver.yaml, the cluster won't operate until a manual fix.

## What you expected to happen?

The cluster should recover upon the downgrade command, if `kubeadm` has the information it needs to accomplish that. And it should be able to, by parsing manifest files for any local settings.

## How to reproduce it (as minimally and precisely as possible)?

Set up a cluster with the `--encryption-provider-config`, perform an upgrade or downgrade.

## Anything else we need to know?

Someone reported this in #1562 long ago, but the response refers to a still-beta feature (setting up a [config settings file for kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file)). This feature request is for kubeadm to preserve such local settings without a kubeadm-specific config (or for the kubeadm config file to be fully supported.) Thanks!

**Comment by neolit123** [comment]
> This feature request is for kubeadm to preserve such local settings without a kubeadm-specific config (or f

usage of the kubeadm configuration file is encouraged and well supported, despite being beta. once it becomes v1 our tooling `config migrate` can be used to migrate the user config on disk.

usage of CLI flags is actually less encouraged because they are unversioned.

https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

> And it should be able to, by parsing manifest files for any local settings.

manifests are regenerated based on data stored in the cluster or via patches stored on disk (see --patches or the config variant). existing manifests on disk are not parsed, since it actually opens for more issues during upgrade.
