### ISSUE TITLE
kubeadm init CI failed since commit d8bdddcab42932

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubeadm#2868]
## What happened?
kubeadm init CI failed since commit d8bdddcab42932 https://github.com/kubernetes/kubernetes/commit/d8bdddcab4293284ce9f11b12f37fb827fc56f7c

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest

**Comment by pacoxu** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/117690 to fix the nil pointer panic in kube-proxy.

**Comment by neolit123** [comment]
thanks for the quick reaction!
