### ISSUE TITLE
kubeadm upgrade fails to backup the kubelet config file on a windows node

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes/kubeadm#2869]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**: v1.27.1 (GitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b)

**Environment**:
- **Kubernetes version**: Not installed on Windows worker node
- **Cloud provider or hardware configuration**: Bare Metal
- **OS**: Microsoft Windows Server 2022 Standard
- **Kernel**: 10.0.20348
- **Container runtime (CRI)**: containerd1.7.0
- **Container networking plugin (CNI)**: flannel 0.17.0
- **Others**:

## What happened?
I wanted to upgrade my two node hybrid cluster from 1.26.0 to 1.27.1 (in one run).
I followed this guides:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
and
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/

The upgrade for the linux control plane worked without any problems. But with `kubeadm upgrade node` on the windows node I got the following error:
```
PS C:\Windows\system32> kubeadm upgrade node
[upgrade] Reading configuration from the cluster...
[upgrade] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
W0502 08:58:06.883475    6716 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "npipe" to the "criSocket" with value "unix:///var/run/unknown.sock". Please update your configuration!
W0502 08:58:06.911578    6716 utils.go:69] The recommended value for "authentication.x509.clientCAFile" in "KubeletConfiguration" is: \etc\kubernetes\pki\ca.crt; the provided value is: /etc/kubernetes/pki/ca.crt
[preflight] Running pre-flight checks
[preflight] Skipping prepull. Not a control plane node.
[upgrade] Skipping phase. Not a control plane node.
[upgrade] Backing up kubelet config file to \etc\kubernetes\tmp\kubeadm-kubelet-config200940241\config.yaml
error execution phase kubelet-config: error backing up the kubelet config file, output: "Ist das Ziel \\etc\\kubernetes\\tmp\\kubeadm-kubelet-config200940241\\config.yaml ein Dateiname\r\noder ein Verzeichnisname\r\n(D = Datei, V = Verzeichnis)? \x00\r\nIst das Ziel \\etc\\kubernetes\\tmp\\kubeadm-kubelet-config200940241\\config.yaml ein Dateiname\r\noder ein Verzeichnisname\r\n(D = Datei, V = Verzeichnis)? ": exit status 2
To see the stack trace of this error execute with --v=5 or higher
```

The error
```
"Ist das Ziel \\etc\\kubernetes\\tmp\\kubeadm-kubelet-config200940241\\config.yaml ein Dateiname\r\noder ein Verzeichnisname\r\n(D = Datei, V = Verzeichnis)? \x00\r\nIst das Ziel \\etc\\kubernetes\\tmp\\kubeadm-kubelet-config200940241\\config.yaml ein Dateiname\r\noder ein Verzeichnisname\r\n(D = Datei, V = Verzeichnis)? "
```
means something like
```
"Is the target \\etc\\kubernetes\\tmp\\kubeadm-kubelet-config200940241\\config.yaml a file name\r\nor a directory name\r\n(F = File, D = Directory)? \x00\r\nIs the target \\etc\\kubernetes\\tmp\\kubeadm-kubelet-config200940241\\config.yaml a file name\r\nor a directory name\r\n(F = File, D = Directory)? "
```

The directory `/etc/kubernetes/tmp/kubeadm-kubelet-config200940241` was existing but empty.

## What you expected to happen?
The upgrade should've worked without any errors.

## How to reproduce it (as minimally and precisely as possible)?
I was able to reproduce it on two setups. The one listed above and one where I tried to upgrade from 1.27.0 to 1.27.1. The second one was a VM from azure.

To create the clusters I followed the guides:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md

## Anything else we need to know?
No.

**Comment by neolit123** [comment]
> "Is the target \\etc\\kubernetes\\tmp\\kubeadm-kubelet-config200940241\\config.yaml a file name\r\nor a directory name\r\n(F = File, D = Directory)? \x00\r\nIs the target \\etc\\kubernetes\\tmp\\kubeadm-kubelet-config200940241\\config.yaml a file name\r\nor a directory name\r\n(F = File, D = Directory)? "

this is odd because if the dir exists we are obviously trying to write a file config.yaml to it.
are there any more error messages? i don't think i've seen Windows ask such a "question" as the error message.

cc @chendave 
i believe you added the kubelet backup feature. is there something that could go wrong on Windows with it's `\\` vs `/` paths?

**Comment by Mik4sa** [comment]
Seems that you try to copy a single file but with a method which is supposed to copy a whole directory.
See:
https://github.com/kubernetes/kubernetes/blob/f51dad586ddc1a02b4fcc4e3974092ad78b630a7/cmd/kubeadm/app/phases/upgrade/postupgrade.go#L264-L279

and:
https://github.com/kubernetes/kubernetes/blob/f51dad586ddc1a02b4fcc4e3974092ad78b630a7/cmd/kubeadm/app/util/copy_windows.go#L30

Trying this local on a test basis results in the same "error" question:
`xcopy /E /H "C:\test\src\test.txt" "C:\test\dest\test.txt"`
```
PS C:\test> xcopy /E /H "C:\test\src\test.txt" "C:\test\dest\test.txt"
Ist das Ziel C:\test\dest\test.txt ein Dateiname
oder ein Verzeichnisname
(D = Datei, V = Verzeichnis)?
```

**Comment by neolit123** [comment]
> Seems that you try to copy a single file but with a method which is supposed to copy a whole directory.
See:
https://github.com/kubernetes/kubernetes/blob/f51dad586ddc1a02b4fcc4e3974092ad78b630a7/cmd/kubeadm/app/phases/upgrade/postupgrade.go#L264-L279

yep, this is not correct. for both linux and windows we must either copy a single file or a directory.
also this comment is not a portable OS one and we should remove it:

**Comment by chendave** [comment]
thanks @SataQiu for the promote fixing, I am completely missed this after backing from holiday.
