### ISSUE TITLE
flannel does not seem to work on a self-hosted cluster

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubeadm#287]
Same issue as https://github.com/kubernetes/kubernetes/issues/39701

I end up hardcoding the IP of the host and flannel breaks a bit further down the road
```
kc logs kube-flannel-ds-p8sdr -f -n kube-system -c kube-flannel
I0604 18:23:48.746091       1 kube.go:111] Waiting 10m0s for node controller to sync
I0604 18:23:48.746513       1 kube.go:315] starting kube subnet manager
I0604 18:23:49.750800       1 kube.go:118] Node controller sync successful
I0604 18:23:49.750982       1 main.go:132] Installing signal handlers
I0604 18:23:49.759527       1 manager.go:149] Using interface with name docker0 and address 172.17.42.1
I0604 18:23:49.759630       1 manager.go:166] Defaulting external address to interface address (172.17.42.1)
E0604 18:23:49.776924       1 network.go:102] failed to register network: operation not supported
E0604 18:23:50.780064       1 network.go:102] failed to register network: operation not supported
E0604 18:23:51.784538       1 network.go:102] failed to register network: operation not supported
E0604 18:23:52.788697       1 network.go:102] failed to register network: operation not supported
E0604 18:23:53.791882       1 network.go:102] failed to register network: operation not supported
```
Since flannel is the only plugin that works on ARM, that means self-hosting is broken on ARM.

I am using 1.6.4

@kubernetes/sig-cluster-lifecycle-bugs

**Comment by kargakis** [comment]
Hrm, the pod is Running but DNS is not coming up for some reason and the node is flipping between Ready and NotReady every 4m (https://github.com/kubernetes/kubeadm/issues/230)

**Comment by luxas** [comment]
> Since flannel is the only plugin that works on ARM, that means self-hosting is broken on ARM.

@kargakis Weave do too, since v1.9: https://www.weave.works/blog/weave-net-1-9-released-encrypted-fast-datapath-arm/ (I helped implement that)

cc @aaronlevy on the flannel issue, what do we think the problem might be?

**Comment by ericchiang** [comment]
Is this an issue for all architectures or just ARM?

**Comment by kargakis** [comment]
@ericchiang the report in https://github.com/kubernetes/kubernetes/issues/39701 is not using ARM.

**Comment by ericchiang** [comment]
Ah, would a better issue title be "flannel does not use iface parameter to contact the API server"?

**Comment by mikedanese** [comment]
@tomdee

**Comment by tomdee** [comment]
@kargakis  Could you try running with an actual flannel release? It looks like you're running a random git commit `image: quay.io/coreos/flannel-git:v0.6.1-28-g5dde68d-amd64`

**Comment by kargakis** [comment]
@tomdee pretty sure I was using the manifest from https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml and was switching amd64 to arm. Not sure where did you get that image from? I will try once more this weekend.

**Comment by tomdee** [comment]
I think I got that version from one of the linked issues. It looks to me from the logging that you're using an order version. Either way, it would be helpful for me to know the exact version to help me diagnose it.

**Comment by luxas** [comment]
Closing as I don't think this is an issue with kubeadm at least...

**Comment by veyselsahin** [comment]
> quay.io/coreos/flannel-git:v0.6.1-28-g5dde68d-amd64

Thank you!
