### ISSUE TITLE
kubeadm upgrade PullImage failed: rpc error

### ISSUE THREAD

**Issue by ytlai** [kubernetes/kubeadm#2870]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT
## Versions

**kubeadm version** (use `kubeadm version`): 1.25.9

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.24.0
- **Cloud provider or hardware configuration**: ubuntu
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
- **Kernel** (e.g. `uname -a`): Linux master-node 4.15.0-144-generic
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): flannel
- **Others**:

## What happened?
I use containerd for CRI, but when I try to upgrade control-plane node from 1.24.0 to 1.25.9 I met below issue, it Iooks like kubeadm try to use cri-o.
`[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.25.9: output: E0502 09:40:16.519194    1409 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory\"" image="registry.k8s.io/kube-apiserver:v1.25.9"
time="2023-05-02T09:40:16Z" level=fatal msg="pulling image: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory\""
, error: exit status 1`

## What you expected to happen?

kubeadm uses containerd as CRI and upgrade the cluster to version 1.25.9 successfully

## How to reproduce it (as minimally and precisely as possible)?
kubeadm upgrade apply v1.25.9

## Anything else we need to know?

I try to do the "kubeadm config images pull" and specify the cri-socket to containerd, but kubeadm still uses cri-o.

$ kubeadm config images pull --cri-socket="unix:///var/run/containerd/containerd.sock"
I0502 10:20:48.682858    5263 version.go:256] remote version is much newer: v1.27.1; falling back to: stable-1.25
failed to pull image "registry.k8s.io/kube-apiserver:v1.25.9": output: E0502 10:20:49.139350    5284 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory\"" image="registry.k8s.io/kube-apiserver:v1.25.9"
time="2023-05-02T10:20:49Z" level=fatal msg="pulling image: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory\""
, error: exit status 1

containerd and kubelet are both working good and  cri-o is not running.

$ systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Tue 2023-05-02 09:32:01 UTC; 50min ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 32354 (kubelet)
    Tasks: 18 (limit: 4915)
   CGroup: /system.slice/kubelet.service
           └─32354 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf  --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock

$ systemctl status containerd
● containerd.service - containerd container runtime
   Loaded: loaded (/lib/systemd/system/containerd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2023-05-02 09:31:55 UTC; 52min ago
     Docs: https://containerd.io
  Process: 32184 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 32185 (containerd)
    Tasks: 139
   CGroup: /system.slice/containerd.service

$ systemctl status cri-o
● crio.service - Container Runtime Interface for OCI (CRI-O)
   Loaded: loaded (/usr/lib/systemd/system/crio.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2023-05-02 09:39:53 UTC; 56min ago
     Docs: https://github.com/cri-o/cri-o
  Process: 11738 ExecStart=/usr/bin/crio $CRIO_CONFIG_OPTIONS $CRIO_RUNTIME_OPTIONS $CRIO_STORAGE_OPTIONS $CRIO_NETWOR
 Main PID: 11738 (code=exited, status=0/SUCCESS)

May 02 09:39:52 master-node systemd[1]: Stopping Container Runtime Interface for OCI (CRI-O)...
May 02 09:39:53 master-node systemd[1]: Stopped Container Runtime Interface for OCI (CRI-O).
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

Besides, when doing kubeadm upgrading, I met below issues first but can be skipped using --force option.
Not sure if these issues are related.

$ kubeadm upgrade apply v1.25.9
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade/version] You have chosen to change the cluster version to "v1.25.9"
[upgrade/versions] Cluster version: v1.24.0
[upgrade/versions] kubeadm version: v1.25.9
[upgrade/version] FATAL: the --version argument is invalid due to these errors:

        - couldn't parse kubelet version

Can be bypassed if you pass the --force flag
To see the stack trace of this error execute with --v=5 or higher
$ kubelet --version
Kubernetes v1.24.0

**Comment by neolit123** [comment]
if you do this:
> kubeadm config images pull --cri-socket="unix:///var/run/containerd/containerd.sock"

but then kubeadm still searches for the crio socket maybe we have a bug in kubeadm.
cc @pacoxu @SataQiu WDYT?

if you want to upgrade a node but also change the socket in the process you must `kubectl edit node <node-name>` find the annotation with the old socket and change it to the new socket that you want.

see full steps here (contains example for cri-dockerd but you need similar steps):
https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd/

what you are trying to do is generally not supported by kubeadm during upgrade and requires manual interaction. ideally you should have only one container runtime on a host.

**Comment by ytlai** [comment]
Hi neolit123,
Thanks for replying soon.
I don't want to change the CRI during the upgrading.
I just want to upgrade the kubernetes version to 1.27 eventually.
Both containerd and cri-o are installed on my control-plane node, but I use containerd and stop the cri-o

$ kubectl get nodes -o wide
NAME                   STATUS     ROLES           AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
master-node            Ready      control-plane   690d   v1.24.0   10.0.100.8    <none>        Ubuntu 18.04.4 LTS   4.15.0-144-generic   containerd://1.6.20
slave-node2            Ready      <none>          690d   v1.24.0   10.0.100.9    <none>        Ubuntu 18.04.4 LTS   4.15.0-209-generic   containerd://1.2.13

I check with the option --cri-sock, it seems fine to have multiple CRI installed on one node.
--cri-socket string
Path to the CRI socket to connect. If empty kubeadm will try to auto-detect this value; use this option only if you have more than one CRI installed or if you have non-standard CRI socket.

Not sure where went wrong. Any else configuration file I should provide?

**Comment by ytlai** [comment]
I found runtime-endpoint and image-endpoint in crictl.yaml pointed to crio.sock.
```
$cat /etc/crictl.yaml
runtime-endpoint: "unix:///var/run/crio/crio.sock"
image-endpoint: "unix:///var/run/crio/crio.sock"
timeout: 0
debug: false
pull-image-on-create: true
disable-pull-on-run: false
```
After pointing both of them to containerd.sock, `kubeadm upgrade` and` kubeadm config images pull` all work good.

```
$cat /etc/crictl.yaml
runtime-endpoint: "unix:///var/run/containerd/containerd.sock"
image-endpoint: "unix:///var/run/containerd/containerd.sock"
timeout: 0
debug: false
pull-image-on-create: true
disable-pull-on-run: false
```

But it's strange the option --cri-sock doesn't overwrite the crictl config.

**Comment by neolit123** [comment]
> But it's strange the option --cri-sock doesn't overwrite the crictl config.

it is a crictl ptoblem. kubeadm passes the socket to crictl as a -- flag, but crictl still uses the config value. the standard way is for flags to override config files.

i was going to suggest for you to log an issue in kubernetes/website about documenting this but a better place seems crictl docs maybe. there is no crictl specific page in k8s docs.

**Comment by pacoxu** [comment]
I submitted https://github.com/kubernetes-sigs/cri-tools/issues/1157 and confirmed it is a crictl problem IMO.

**Comment by pacoxu** [comment]
/reopen 

> the `crictl images` or  `crictl pull` should use --image-endpoint or -i or IMAGE_SERVICE_ENDPOINT.

> Not --runtime-endpoint -r or CONTAINER_RUNTIME_ENDPOINT. That is the problem.
