### ISSUE TITLE
Add ability to validate configuration yaml

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubeadm#2871]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
v1.27.1

**Environment**:
N/A

## What happened?

I want to be able to run something like `kubeadm config validate --config my-config.yaml` and have syntax validation of my configuration.

## What you expected to happen?

Command does not exist.

Dry run is close, but it does *too much*:
```
$ kubeadm join --dry-run --config config.yaml
couldn't create a temporary directory on dryrun: failed to create directory "/etc/kubernetes/tmp": mkdir /etc/kubernetes: permission denied
```

I tried just fixing that permission error and quickly went down a rabbit hole of other errors.  I do not want to join, so I have non of the pre-reqs setup. I just want to validate a JoinConfiguration

**Comment by chendave** [comment]
I am not aware of any similar command from other components in kubernetes, but  most of the components have a `validation` packages for the syntax validation as well as other internal constraints. 

We'd better understand why kubeadm need to provide such command, some usecase would be helpful, and then outline the scope of the command, so we can judge whether the `validation` package does is good fit or not.

**Comment by pacoxu** [comment]
/kind feature

> I am not aware of any similar command from other components in kubernetes, but most of the components have a `validation` packages for the syntax validation as well as other internal constraints.

kubectl server-side dry-run will trigger validation of yaml.

**Comment by neolit123** [comment]
> I want to be able to run something like kubeadm config validate --config my-config.yaml and have syntax validation of my configuration.

this is a fair request and kubeadm already has the mechanisms to do it. so +1 from me...i can try adding this command when i have time.

here is some context. component config in k8s uses the same private / public api coupling that core k8s api use. one downside is that validation can only be performed on a private api. and private apis are only known by the owned component. this means that if users want api validation, the component must expose it on the cli or at a service endpoint.

this is an api machinery limitation. and same for api conversion. i did a prototype some time ago that solves these problems, but it didn't get adoption.

**Comment by jordanbreen28** [comment]
+1 for this.

Could really use this right now.

**Comment by SataQiu** [comment]
That seems like a reasonable request.
Also +1 for this feature

**Comment by neolit123** [comment]
PR is here
https://github.com/kubernetes/kubernetes/pull/118013

**Comment by neolit123** [comment]
k8s.io docs PR
https://github.com/kubernetes/website/pull/41150

**Comment by neolit123** [comment]
please add LGTM to the docs PR
https://github.com/kubernetes/website/pull/41150
