### ISSUE TITLE
fix broken manifest list e2e due to arm arch

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2873]
looks like the e2e test job has been broken for a while
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kubernetes-e2e-manifest-lists/1656908203142680576

reading the logs shows missing arm arch for images

> I0512 06:25:22.591] * ERROR: kube-apiserver:v1.27.1; error: did not find a match for these architectures: arm
I0512 06:25:22.591] 

is arm no longer supported? if yes, we need to update the test code.

if no, we need to log k/k issue ad ping #sig-release

NOTE also it would be nice to make this e2e job send email alerts. it currently does not!
https://github.com/kubernetes/kubeadm/pull/2872#discussion_r1192555102

**Comment by dims** [comment]
> is arm no longer supported?

yes, let's update the test code!

**Comment by BenTheElder** [comment]
Yes, https://github.com/kubernetes/kubernetes/pull/115742

We have a build time warning throughout the 1.27 branch, I dropped it for 1.28 development branch (master) after release.

If you build 1.27.x:
```
+++ [0512 19:03:40] Running build command...
+++ [0512 19:03:40] WARNING: linux/arm will no longer be built/shipped by default, please build it explicitly if needed.
+++ [0512 19:03:40]          support for linux/arm will be removed in a subsequent release.
+++ [0512 19:03:40] Building go targets for linux/amd64
```

**Comment by rjsadow** [comment]
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-manifest-lists test is passing again.

**Comment by chendave** [comment]
Can we close this issue now?

**Comment by pacoxu** [comment]
/close
as the ci is green
