### ISSUE TITLE
apt-get update error on  https://packages.cloud.google.com/apt kubernetes-xenial

### ISSUE THREAD

**Issue by collin-perschon** [kubernetes/kubeadm#2880]
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):  N/A

**Environment**:
- **Kubernetes version** (use `kubectl version`):  N/A
- **Cloud provider or hardware configuration**:  8CPU, 32GB virtual machine on ESXI
- **OS** (e.g. from /etc/os-release): Ubuntu 22.04.2 LTS (Jammy Jellyfish)
- **Kernel** (e.g. `uname -a`): Linux k8s-c 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico
- **Others**:

## What happened?
I have a freshly deployed Ubuntu 22.0.4 VM and I am following the documentation to install kubeadm.  I have having an issue running apt-get update on the repository that contains kubeadm:

```
Err:2 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
Reading package lists... Done
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I am following the install documentation to install kubeadm.   
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

I am specifically getting stuck on step 4 running apt-get update, I have verified that steps 1-3 all work as expected.  I see the PGP key in /etc/apt/keyrings/kubernetes-archive-keyring.gpg and I see the entry in /etc/apt/sources.list.d/kubernetes.list.  

## What you expected to happen?
I would expect that following the installation instructions, I should be able to run apt-get update and install kubeadm.  I believe that there is either a bug in the documentation or a but in the repo?  Specifically this:
**The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.**

## How to reproduce it (as minimally and precisely as possible)?
1. Download the latest Ubuntu Server 22.0.4 ISO
2. Deploy a VM with that ISO (I chose the installer option to run updates).
3. Follow the instructions to install Kubeadm 

## Anything else we need to know?
If I errored here and there is not bug or not the right place for it I apologize.

**Comment by neolit123** [comment]
it's a documentation problem AFAIK.
https://github.com/kubernetes/website/issues/41246
https://github.com/kubernetes/website/issues/41235

**Comment by collin-perschon** [comment]
Thank you @neolit123 , it is the exact same issue.  From the tickets you listed, the work-around is to replace step 2 with:

sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://dl.k8s.io/apt/doc/apt-key.gpg

Sorry for any troubles,
