### ISSUE TITLE
rework etcd version warning message

### ISSUE THREAD

**Issue by vndroid** [kubernetes/kubeadm#2882]
### What happened?

when I init the kubernetes cluster, kubeadm display the warning:

```bash
$ kubeadm config images list
W0528 19:01:00.816868    6480 images.go:80] could not find officially supported version of etcd for Kubernetes v1.27.2, falling back to the nearest etcd version (3.5.7-0)
registry.k8s.io/kube-apiserver:v1.27.2
registry.k8s.io/kube-controller-manager:v1.27.2
registry.k8s.io/kube-scheduler:v1.27.2
registry.k8s.io/kube-proxy:v1.27.2
registry.k8s.io/pause:3.9
registry.k8s.io/etcd:3.5.7-0
registry.k8s.io/coredns/coredns:v1.10.1
```

https://github.com/kubernetes/kubernetes/blob/b374404825125f5ea8c46313ccaf3717e6ba46fb/cmd/kubeadm/app/constants/constants.go#L469-L482

### What did you expect to happen?

No warning message is displayed.

### How can we reproduce it (as minimally and precisely as possible)?

As the usual.

### Anything else we need to know?

As we known, the etcd image is already exist. Even version 3.5.9 already exists

```bash
$ sudo crictl pull registry.k8s.io/etcd:3.5.8-0
Image is up to date for sha256:291c432e82cb31038db567f89db79530419118472a134b55f540291ceb4cd882
$ sudo crictl pull registry.k8s.io/etcd:3.5.9-0
Image is up to date for sha256:73deb9a3f702532592a4167455f8bf2e5f5d900bcc959ba2fd2d35c321de1af9
$ sudo crictl images
IMAGE                  TAG                 IMAGE ID            SIZE
registry.k8s.io/etcd   3.5.8-0             291c432e82cb3       103MB
registry.k8s.io/etcd   3.5.9-0             73deb9a3f7025       103MB

```

### Kubernetes version

```console
$ kubectl version --output=yaml
clientVersion:
  buildDate: "2023-05-17T14:20:07Z"
  compiler: gc
  gitCommit: 7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647
  gitTreeState: clean
  gitVersion: v1.27.2
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
```

### Cloud provider

KVM based Virtual Machine.

### OS version

```console
OS:
Debian GNU/Linux 11 (bullseye)
Kernel:
Linux k8s1 5.10.0-23-cloud-amd64 kubernetes/kubernetes#1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
```

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

<details>
None
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
None
</details>

**Comment by neolit123** [comment]
> @pacoxu @SataQiu maybe we should make this a V(1) instead of warning?

we have the etcd version map update in our housekeeping tasks, but it seems we can forget about it sometimes. wondering if tests / automation can be added to ensure the map is updated.

**Comment by SataQiu** [comment]
Maybe we can add some e2e tests to ensure this warning will never occur in every release?
+1 for V(1)
/assign

**Comment by neolit123** [comment]
we should backport the missing version map values to .27 too, IMO.

> Maybe we can add some e2e tests to ensure this warning will never occur in every release?

not sure how it would work. we must be able to catch an error when the map is missing key/values for the latest stable k8s. we could add a unit test that is normally skipped if an env var is not set. and during the e2e we could clone kubeadm source, get the stable-1 version, set the special env var, call 'go test' for this test to run.

the e2e could be just a script in k/kubeadm. similar setup to the manifest list test.

**Comment by pacoxu** [comment]
Cherry-pick https://github.com/kubernetes/kubernetes/pull/117169 to v1.27?

**Comment by neolit123** [comment]
> Cherry-pick [kubernetes/kubernetes#117169](https://github.com/kubernetes/kubernetes/pull/117169) to v1.27?

yes, that would fix it.

**Comment by neolit123** [comment]
this is done, thanks
