### ISSUE TITLE
k8s control plane redundancy issue 

### ISSUE THREAD

**Issue by rajaee1211** [kubernetes/kubeadm#2888]
## Versions

**kubeadm version** (use `kubeadm version`): 1.26
**Environment**: k8s
- **Kubernetes version** (use `kubectl version`): 1.26
- **Cloud provider or hardware configuration**: hardware configuration
- **OS** (e.g. from /etc/os-release): ubuntu 22.04
- **Kernel** (e.g. `uname -a`): latest
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico
- **Others**: 3 masters 3 workers cluster

## What happened?
I have setup my cluster on the primary control plane normally and have joined the other masters/worker normally without an issue , cluster is working great , but the moment i try redundancy by turning off the primary master i get the following error and cluster is not working anymore 
Unable to connect to the server: dial tcp 192.168.10.10:6443: connect: no route to host

## What you expected to happen?
the 2nd or 3rd master to be elected as leader 

## How to reproduce it (as minimally and precisely as possible)?
when i power off the primary control plane

## Anything else we need to know?
i run the cluster on private network with CIDR 192.168.10.0/24 and pods CIDR 10.10.0.0/16

**Comment by pacoxu** [comment]
The leader can be elected inside the etcd cluster. There is no leader apiserver concept.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#create-load-balancer-for-kube-apiserver

IMO, you should create an LB for all apiservers, and then the LB can still work no matter which apiserver is down among 3 control-plane(master) apiservers.

**Comment by rajaee1211** [comment]
thank you for the prompt reply @pacoxu 

the article mentions the following point which i find confusing :
- Make sure the address of the load balancer always matches the address of kubeadm's ControlPlaneEndpoint.

so in that case how the load balancer will have a different ip address and work with my api-server 

also if there is a proper guide to create load balancer compatible with the k8s cluster environment i mentioned in the post

**Comment by neolit123** [comment]
the lb should be an entity with an unique domain name or ip sitting in front of the control plane machines (api servers). the controlplaneendpoint address the lb address.

for lb guide check
https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md

this is a support question. you can continue the discussion here, but in the future please use #kubeadm on k8s slack.

/kind support

**Comment by rajaee1211** [comment]
i have tried haproxy and keepalived combination (on the local host) was installed exactly as the guide but still there is no redundancy , it will keep searching for the VIP of the load balancer whenever the primary control-plane is down

**Comment by neolit123** [comment]
try asking for help on discuss.k8s.io or #kubeadm on k8s slack (better) we have some  lb experts there.
