### ISSUE TITLE
Deploying v1.6 clusters with kubeadm at HEAD is broken

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#289]
https://github.com/kubernetes/kubernetes/pull/45619 completely removed the flag we used for auto-approval in v1.6 (`--insecure-experimental-approve-all-kubelet-csrs-for-group=system:bootstrappers`)

This "broke" deploying v1.6 clusters with kubeadm in the sense that `kubeadm join` will wait until you manually approve the CSR as there is no autoapprover configured.

The fix is pretty simple, we just need to check the version and use the right arguments for the right versions respectively.

PR: https://github.com/kubernetes/kubernetes/pull/46864

**Comment by timothysc** [comment]
This merged, so I'm assuming it's all good?

**Comment by luxas** [comment]
Yup, now the second required PR merged as well so now it's working
