### ISSUE TITLE
fix failing /support command workflow

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2892]
we have a /support command in this repo, defined as a github workflow.

it started failing today on every comment!, log:

<details>
support_comment
failed 5 minutes ago in 29s
2s
26s
Build container for action use: '/home/runner/work/_actions/ben-z/actions-comment-on-issue/1.0.2/Dockerfile'.
  /usr/bin/docker build -t ed866e:763cd85dd607431c9b7fe28f128ef456 -f "/home/runner/work/_actions/ben-z/actions-comment-on-issue/1.0.2/Dockerfile" "/home/runner/work/_actions/ben-z/actions-comment-on-issue/1.0.2"
  Sending build context to Docker daemon  36.35kB
  
  Step 1/4 : FROM node:slim
  slim: Pulling from library/node
  5b5fe70539cd: Pulling fs layer
  b6b4ba8b66ef: Pulling fs layer
  dc3acd1165f9: Pulling fs layer
  5672c64b5e46: Pulling fs layer
  ea5d3a7fd2f9: Pulling fs layer
  5672c64b5e46: Waiting
  ea5d3a7fd2f9: Waiting
  b6b4ba8b66ef: Verifying Checksum
  b6b4ba8b66ef: Download complete
  5672c64b5e46: Verifying Checksum
  5672c64b5e46: Download complete
  5b5fe70539cd: Verifying Checksum
  5b5fe70539cd: Download complete
  ea5d3a7fd2f9: Verifying Checksum
  ea5d3a7fd2f9: Download complete
  dc3acd1165f9: Verifying Checksum
  dc3acd1165f9: Download complete
  5b5fe70539cd: Pull complete
  b6b4ba8b66ef: Pull complete
  dc3acd1165f9: Pull complete
  5672c64b5e46: Pull complete
  ea5d3a7fd2f9: Pull complete
  Digest: sha256:c0a80bc11d7cd2427092476664c2255462a4a5e331d7877104b7c7e240efc577
  Status: Downloaded newer image for node:slim
   ---> a654fa76705d
  Step 2/4 : COPY . .
   ---> a3eaf909f945
  Step 3/4 : RUN npm install --production
   ---> Running in 852eb62e899a
  exec /bin/sh: no such file or directory
  The command '/bin/sh -c npm install --production' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 7.618 seconds before retry.
  /usr/bin/docker build -t ed866e:763cd85dd607431c9b7fe28f128ef456 -f "/home/runner/work/_actions/ben-z/actions-comment-on-issue/1.0.2/Dockerfile" "/home/runner/work/_actions/ben-z/actions-comment-on-issue/1.0.2"
  Sending build context to Docker daemon  36.35kB
  
  Step 1/4 : FROM node:slim
   ---> a654fa76705d
  Step 2/4 : COPY . .
   ---> Using cache
   ---> a3eaf909f945
  Step 3/4 : RUN npm install --production
   ---> Running in 7cbc4494fa5f
  exec /bin/sh: no such file or directory
  The command '/bin/sh -c npm install --production' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 8.678 seconds before retry.
  /usr/bin/docker build -t ed866e:763cd85dd607431c9b7fe28f128ef456 -f "/home/runner/work/_actions/ben-z/actions-comment-on-issue/1.0.2/Dockerfile" "/home/runner/work/_actions/ben-z/actions-comment-on-issue/1.0.2"
  Sending build context to Docker daemon  36.35kB
  
  Step 1/4 : FROM node:slim
   ---> a654fa76705d
  Step 2/4 : COPY . .
   ---> Using cache
   ---> a3eaf909f945
  Step 3/4 : RUN npm install --production
   ---> Running in ee3e8388507a
  exec /bin/sh: no such file or directory
  The command '/bin/sh -c npm install --production' returned a non-zero code: 1
  
Error: Docker build failed with exit code 1
0s
0s
0s
0s

</details>

sh is now missing for some reason.
haven't checked what's going on; just logging the issue.

**Comment by pacoxu** [comment]
It seems to be related to newer release of `node:slim`.
https://hub.docker.com/layers/library/node/slim/images/sha256-9d3d6a6ad1fb459efb295e77967ab9643e8fc3a3e3edc6ed4feec8793fa774c2?context=explore

**Comment by pacoxu** [comment]
The old `node:buster-slim` or old `20.2.0-slim` can work.
