### ISSUE TITLE
kubeadm 1.4: kube-dns fails on CentOS 7.1

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#29]
_From @jimmyjones2 on October 9, 2016 20:42_

CentOS 7.1.1503 minimal VM, using kubeadm guide with weave networking. kube-dns has issues starting up:

```
I1009 20:09:37.093825       1 dns.go:173] Ignoring error while waiting for service default/kubernetes: Get https://100.64.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 100.64.0.1:443: getsockopt: no route to host. Sleeping 1s before retrying.
E1009 20:09:39.098145       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Endpoints: Get https://100.64.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 100.64.0.1:443: getsockopt: no route to host
I1009 20:09:39.522095       1 logs.go:41] skydns: failure to forward request "read udp 10.32.0.2:48292->192.168.1.1:53: i/o timeout"
```

Disabling firewalld resolves the issue.

_Copied from original issue: kubernetes/kubernetes#34420_

**Comment by mikedanese** [comment]
_From @errordeveloper on October 11, 2016 10:27_

> Disabling firewalld resolves the issue.

I believe we need to work out what would be better here. May be @dgoodwin has some ideas?

**Comment by mikedanese** [comment]
_From @errordeveloper on October 11, 2016 10:27_

@luxas this is tagged incorrectly, we should fix the bot...

**Comment by mikedanese** [comment]
_From @errordeveloper on October 11, 2016 19:39_

Are you using VirtualBox?

**Comment by mikedanese** [comment]
_From @jimmyjones2 on October 11, 2016 19:53_

@errordeveloper Yes

**Comment by mikedanese** [comment]
_From @errordeveloper on October 26, 2016 17:31_

I've managed to resolv this and other issue in my Vagrant+Ansible repo (https://github.com/errordeveloper/kubernetes-ansible-vagrant), please take a look and let me know if you have any question (Slack may be the best place). There are a few things around firewalld and SELinux, that repo has all the right pieces without disabling both of those security features of CentOS.

**Comment by mikedanese** [comment]
_From @jimmyjones2 on October 28, 2016 19:1_

@errordeveloper Do you know if your firewall fixes will be folded into kubeadm?

**Comment by mikedanese** [comment]
_From @dgoodwin on November 14, 2016 19:13_

Doing a little experimenting today with kubelet compiled from master (1.5 effectively) and the new selinux work done there, it looks as though kube-dns and weave can come up without issue and with no denials when selinux is enforcing.

**Comment by mikedanese** [comment]
_From @luxas on November 14, 2016 19:15_

So you mean v1.5 will work fine on CentOS without `setenforce 0`?

**Comment by mikedanese** [comment]
_From @dgoodwin on November 14, 2016 19:20_

Yes I believe so, in my testing we do still need etcd running unconfined because it uses /var/lib/etcd/, but we don't need kube-discovery running unconfined anymore (but it's going away soon anyhow), and the weave/kube-dns problems appear to be gone as well.

**Comment by luxas** [comment]
Closing in favor for #21
