### ISSUE TITLE
Reduce user participation steps to zero after kubeadm finishes

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubeadm#290]
When kubeadm finishes installing the user is recommended to do the following:

```
sudo cp /etc/kubernetes/admin.conf $HOME/
sudo chown $(id -u):$(id -g) $HOME/admin.conf
export KUBECONFIG=$HOME/admin.conf
```

which is fine, but having to copy/paste three lines is suboptimal if we can do it in fewer.

Could we instead have kubeadm automatically copy `/etc/kubernetes/admin.conf` to `$HOME/.kubeconfig`? I assume that would cover 90% of use cases and the user would need to do nothing after kubeadm finishes.

**Comment by gtirloni** [comment]
Relevant discussion https://groups.google.com/d/topic/kubernetes-sig-cluster-lifecycle/xluhdEaawsM/discussion

**Comment by jamiehannaford** [comment]
Closing in favour of https://github.com/kubernetes/kubeadm/issues/235.
