### ISSUE TITLE
Wrong repository replacement when used --image-repository

### ISSUE THREAD

**Issue by zavyalovpe** [kubernetes/kubeadm#2921]
## Versions

**kubeadm version** (use `kubeadm version`):v1.28.1, v1.27.5

**Environment**:
- **Cloud provider or hardware configuration**: Metal
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 12 (bookworm)
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd

## What happened?
When I use a mirror repository, the path to CoreDNS is incorrectly replaced. The subdirectory is truncated. Which results in an error.
```
kubeadm init --image-repository "myrepo"
```
```
error execution phase preflight: [preflight] Some fatal errors occurred:
[ERROR ImagePull]: failed to pull image myrepo/coredns:v1.10.1
myrepo/coredns:v1.10.1: not found
```
kubeadm config images list
```
registry.k8s.io/kube-apiserver:v1.28.0
registry.k8s.io/kube-controller-manager:v1.28.0
registry.k8s.io/kube-scheduler:v1.28.0
registry.k8s.io/kube-proxy:v1.28.0
registry.k8s.io/pause:3.9
registry.k8s.io/etcd:3.5.9-0
registry.k8s.io/coredns/coredns:v1.10.1
```
kubeadm config images list --image-repository "myrepo"
```
myrepo/kube-apiserver:v1.28.0
myrepo/kube-controller-manager:v1.28.0
myrepo/kube-scheduler:v1.28.0
myrepo/kube-proxy:v1.28.0
myrepo/pause:3.9
myrepo/etcd:3.5.9-0
myrepo/coredns:v1.10.1
```
works great
```
crictl pull myrepo/coredns/coredns:v1.10.1 
```
## How to reproduce it (as minimally and precisely as possible)?
```
kubeadm config images list --image-repository "myrepo"
```

**Comment by neolit123** [comment]
not s bug, it's by design. please read:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

if using a custom repo use coredns image without coredns subpath.
