### ISSUE TITLE
latest.txt version marker points at 1.28.x-x

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2925]
the marker should point at 1.29.x-x.
this means we are not testing merged PRs at master with e2e periodics. only 1.28.1 max.

sig release bug report:
https://github.com/kubernetes/sig-release/issues/2333

discussion at slack:
https://kubernetes.slack.com/archives/CJH2GBF7Y/p1694024539464429?thread_ts=1694024539.464429&cid=CJH2GBF7Y

we can switch to latest-fast.txt for the master branch:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/kubernetes-versions.md

**Comment by neolit123** [comment]
looks like we cannot use latest-fast, as it points to missing artifacts:
https://github.com/kubernetes/sig-release/issues/2333#issuecomment-1709643321

this is a problem for us, so i think we should stop merging k/k PRs for a while until latest.txt is fixed.
we change latest.txt to be latest-1.29.txt (i.e. current release) but it means we are going to stop testing e.g. 1.30 once it works starts at k/k master after the branch split / release of 1.29.

hmm, but we usually update our CI jobs manually anyway.
perhaps this is the right thing to do?
- when ./kinder/hack/update-workflows.sh is called take the --kubernetes-version value and put it into `ci/latest-foo` (replace foo). instead of using `ci/latest`

**Comment by pacoxu** [comment]
I tried to check our CI in https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-learner-mode-latest. It is using v1.29. 

Is there an example of kubeadm CI using v1.28 as the latest?

**Comment by neolit123** [comment]
> I tried to check our CI in https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-learner-mode-latest. It is using v1.29.
> 
> Is there an example of kubeadm CI using v1.28 as the latest?

our "regular" job's last run was at 1.29:
https://[storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1699668038380425216/build-log.txt](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1699668038380425216/build-log.txt)

**Comment by neolit123** [comment]
> kinder build node-image-variant --base-image=kindest/base:v20221102-76f15095 --image=kindest/node:test --with-init-artifacts=v1.28.1-49+b77dd745f65196 --loglevel=debug

https://github.com/kubernetes/kubeadm/blob/main/kinder/ci/workflows/regular-latest.yaml

**Comment by neolit123** [comment]
> when ./kinder/hack/update-workflows.sh is called take the --kubernetes-version value and put it into ci/latest-foo (replace foo). instead of using ci/latest

i got this working in the update-workflows tool but it's a bit messy.
much rather wait for a fix.

here is what to check:
https://dl.k8s.io/ci/latest.txt

**Comment by pacoxu** [comment]
https://github.com/kubernetes/release/pull/3254 was merged to fix it. 

> I think we should stop merging k/k PRs for a while until latest.txt is fixed.

We may check the CIs tomorrow. If no failure, we can start merging new PRs in K/K then, right?

**Comment by neolit123** [comment]
sig release have a pending fix
https://github.com/kubernetes/sig-release/issues/2333

**Comment by neolit123** [comment]
https://dl.k8s.io/ci/latest.txt

it's fixed.
