### ISSUE TITLE
`kube-apiserver-etcd-client` shouldn't have `O=system:masters`

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/kubeadm#2926]
## Versions

```bash
kubeadm version --output short
v1.27.3

kubectl version --short
Client Version: v1.27.3

# cloud provider: n/a

cat /etc/os-release
PRETTY_NAME="Ubuntu 23.04"

uname -a
Linux master-1 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

containerd --version
containerd github.com/containerd/containerd v1.7.2 0cae528dd6cb557f7201036e9f43420650207b58

# CNI: calico
```

## What happened?

The `kube-apiserver-etcd-client` certificate is created as specified in the [documentation](https://kubernetes.io/docs/setup/best-practices/certificates/#all-certificates), but [this issue](https://github.com/kubernetes/website/issues/42724) proved that this is not as it should be.

## What you expected to happen?

The `kube-apiserver-etcd-client` certificate should be created without `O=system:masters`, because etcd doesn't take this into account.

## How to reproduce it (as minimally and precisely as possible)?

```bash
kubeadm init
```

**Comment by SataQiu** [comment]
/assign
Will have a look.

**Comment by neolit123** [comment]
@SataQiu would like to also send the k/website change?

**Comment by SataQiu** [comment]
> @SataQiu would like to also send the k/website change?

Yes, I will do it after this PR is merged.

**Comment by neolit123** [comment]
same issue for the apiserver-kubelet-client.crt
https://github.com/kubernetes/kubernetes/pull/121837
https://github.com/kubernetes/website/pull/43870
