### ISSUE TITLE
add more documentation about the format of  certificateKey

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2928]
SataQiu added validation for certificateKey:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L619-L635

but we should also add information about the format of the certificateKey in the API godocs and on the HA page at the website.

- [x] PR for kubernetes/kubernetes: add comment about the size and format over the certificateKey fields in v1beta3 and v1beta4 and flags: https://github.com/kubernetes/kubernetes/pull/120546

add new sentence:
```
The certificate key is a hex encoded string that is an AES key of size 32 bytes.
```

near the comment of `CertificateKey` instances in these files:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/types.go

should be 2 per file, 6 total.

also add the same sentence in the --certificate-key flag description here:
https://github.com/kubernetes/kubernetes/blob/f8ca582a06a8379968ddb7960adefeea3c467e36/cmd/kubeadm/app/cmd/init.go#L191
https://github.com/kubernetes/kubernetes/blob/f8ca582a06a8379968ddb7960adefeea3c467e36/cmd/kubeadm/app/cmd/join.go#L254

- [x] PR for kuberntes/website: here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#stacked-control-plane-and-etcd-nodes https://github.com/kubernetes/website/pull/42981

under the note:
````
Note: The kubeadm-certs Secret and decryption key expire after two hours.
````

write a new note:
```
The certificate key is a hex encoded string that is an AES key of size 32 bytes.
````

**Comment by SaumyaBhushan** [comment]
Can I work on this issue ?

**Comment by Hii-Arpit** [comment]
Hello, @SaumyaBhushan, will you be working on the issue?

**Comment by SaumyaBhushan** [comment]
Hi Arpit! It's almost done both the PR have been approved. It will get merged soon that means it's done
