### ISSUE TITLE
403 while running kubeadm init command. 

### ISSUE THREAD

**Issue by faizan-bootnext** [kubernetes/kubeadm#2934]
I am running below command on AWS EC2 VMs in ap-south-1 zone. The Kubeadm command is giving 403 error 

sudo kubeadm init --pod-network-cidr 192.168.100.0/24  --apiserver-advertise-address <master_ip>
or 
 sudo kubeadm config images pull

**ERROR Output:** 

 [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.28.1: output: E0913 12:18:31.635477    5021 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.28.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/kube-apiserver/blobs/sha256:5c801295c21d0de2947ad600b9388f090f0f7ff22add9d9d95be82fa12288f77: 403 Forbidden" image="registry.k8s.io/kube-apiserver:v1.28.1" time="2023-09-13T12:18:31Z" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.28.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/kube-apiserver/blobs/sha256:5c801295c21d0de2947ad600b9388f090f0f7ff22add9d9d95be82fa12288f77: 403 Forbidden" , error: exit status 1     

    [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-controller-manager:v1.28.1: output: E0913 12:18:39.397907    5057 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.28.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/kube-controller-manager/blobs/sha256:821b3dfea27be94a3834878bec6f36d332c83250be3e3c2a2e2233575ebc9bac: 403 Forbidden" image="registry.k8s.io/kube-controller-manager:v1.28.1" time="2023-09-13T12:18:39Z" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.28.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/kube-controller-manager/blobs/sha256:821b3dfea27be94a3834878bec6f36d332c83250be3e3c2a2e2233575ebc9bac: 403 Forbidden" , error: exit status 1       

  [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-scheduler:v1.28.1: output: E0913 12:18:47.178326    5093 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.28.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/kube-scheduler/blobs/sha256:b462ce0c8b1ff16d466c6e8c9fcae54ec740fdeb73af6e637b77eea36246054a: 403 Forbidden" image="registry.k8s.io/kube-scheduler:v1.28.1" time="2023-09-13T12:18:47Z" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.28.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/kube-scheduler/blobs/sha256:b462ce0c8b1ff16d466c6e8c9fcae54ec740fdeb73af6e637b77eea36246054a: 403 Forbidden" , error: exit status 1       

  [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-proxy:v1.28.1: output: E0913 12:18:54.672729    5129 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-proxy:v1.28.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/kube-proxy/blobs/sha256:6cdbabde3874e1eca92441870b0ddeaef0edb514c3b3e2a3d5ade845b500bba5: 403 Forbidden" image="registry.k8s.io/kube-proxy:v1.28.1" time="2023-09-13T12:18:54Z" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/kube-proxy:v1.28.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/kube-proxy/blobs/sha256:6cdbabde3874e1eca92441870b0ddeaef0edb514c3b3e2a3d5ade845b500bba5: 403 Forbidden" , error: exit status 1   

      [ERROR ImagePull]: failed to pull image registry.k8s.io/pause:3.9: output: E0913 12:19:02.466161    5173 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/pause:3.9\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/pause/blobs/sha256:e6f1816883972d4be47bd48879a08919b96afcd344132622e4d444987919323c: 403 Forbidden" image="registry.k8s.io/pause:3.9" time="2023-09-13T12:19:02Z" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/pause:3.9\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/pause/blobs/sha256:e6f1816883972d4be47bd48879a08919b96afcd344132622e4d444987919323c: 403 Forbidden" , error: exit status 1     

    [ERROR ImagePull]: failed to pull image registry.k8s.io/etcd:3.5.9-0: output: E0913 12:19:10.245509    5210 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/etcd:3.5.9-0\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/etcd/blobs/sha256:73deb9a3f702532592a4167455f8bf2e5f5d900bcc959ba2fd2d35c321de1af9: 403 Forbidden" image="registry.k8s.io/etcd:3.5.9-0" time="2023-09-13T12:19:10Z" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/etcd:3.5.9-0\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/etcd/blobs/sha256:73deb9a3f702532592a4167455f8bf2e5f5d900bcc959ba2fd2d35c321de1af9: 403 Forbidden" , error: exit status 1     

    [ERROR ImagePull]: failed to pull image registry.k8s.io/coredns/coredns:v1.10.1: output: E0913 12:19:18.009815    5246 remote_image.go:180] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.10.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/coredns/coredns/blobs/sha256:ead0a4a53df89fd173874b46093b6e62d8c72967bbf606d672c9e8c9b601a4fc: 403 Forbidden" image="registry.k8s.io/coredns/coredns:v1.10.1" time="2023-09-13T12:19:18Z" level=fatal msg="pulling image: failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.10.1\": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry.k8s.io/v2/coredns/coredns/blobs/sha256:ead0a4a53df89fd173874b46093b6e62d8c72967bbf606d672c9e8c9b601a4fc: 403 Forbidden" , error: exit status 1

**Comment by neolit123** [comment]
hi, this seems like an issue with your aws vm.
try plain docker pull or crictl.

support is not provided on github.
