### ISSUE TITLE
Document how to setup HostPort #47310

### ISSUE THREAD

**Issue by ekozan** [kubernetes/kubeadm#294]
Now cni have the "portmap" plugin who fix the bug on hostport of kubernetes ... maybe we can have a small documentation how to set it up in kubeadm cluster

**Comment by luxas** [comment]
Yeah, that would make sense.
Anyway, I'm not sure of which providers support that yet...

cc @kubernetes/sig-network-feature-requests @bboreham 
Do you know any CNI network providers that support this?

**Comment by cmluciano** [comment]
/assign

I'm working on some doc updates how to use the bridge plugin. I can work on this too.

**Comment by caseydavenport** [comment]
@luxas Calico is tested and works with the upstream `portmap` plugin.

I'm not sure the onus falls on kubeadm for this though - I think it's a per-network-provider thing (providers should update their manifests to include the correct config).

**Comment by nicolai86** [comment]
@luxas does calico have some docs on this somewhere? or is https://github.com/kubernetes/kubernetes/issues/31307#issuecomment-307608333 still the best we got?

**Comment by caseydavenport** [comment]
@nicolai86 docs are on the way - will need to sort out how we document that this is a v1.7+ feature (we now need slightly different manifests for <v1.6, v1.6, v1.7+)

Here's an example for Calico: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/calico-policy-controller/calico-node-daemonset.yaml#L77

**Comment by ekozan** [comment]
sadly weave seen to not work :/ https://github.com/weaveworks/weave/issues/3016

**Comment by luxas** [comment]
I don't either think this is kubeadm-specific, but it makes sense to document in general.
Do we think this should be moved to kubernetes/kubernetes or?

**Comment by luxas** [comment]
ping @cmluciano any movement on this issue lately?

**Comment by cmluciano** [comment]
@caseydavenport @ekozan @luxas Based on the conversation here, should we just cross link the docs per CNI plugin that supports this?

**Comment by luxas** [comment]
@cmluciano Yes, we should link to the each provider's own docs.
We already have the tabs in place, etc. so it should be pretty straightforward :+1: 

@cmluciano Can I assign this to you?

**Comment by cmluciano** [comment]
Yes I will update the docs. It looks like only calico has this so far. The weave PR seems to be pending.

**Comment by cmluciano** [comment]
Trying to determine the proper place to put these docs. Should it be 
- https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network
- https://kubernetes.io/docs/admin/kubeadm/
- main k8s docs (CNI-setup directory under the Concepts->Configuration path)
- main k8s docs (Cluster Administration->Cluster Networking)

**Comment by jamiehannaford** [comment]
@cmluciano For now, I think a new paragraph/sentence at the end of https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network is enough. There is a plan to break up this page into smaller pages, but that's not a blocker. Do you think you'll be able to add this soon?

**Comment by luxas** [comment]
I think that we can close this now that https://github.com/kubernetes/website/pull/5940 is merged

**Comment by smorrisfv** [comment]
So I'm trying to get HostPorts working, but they just don't seem to work.  I set them up in my deployment config on the container and they don't get mapped.  I've scowered the net far and wide but there doesn't seem to be a concrete way to set things up.  I've look at the merge request that is mentioned above ( kubernetes/website#5940) and it mentions the [_portmap_ documentation](https://github.com/containernetworking/plugins/blob/master/plugins/meta/portmap/README.md), that doesn't mention how to set it up either.

In terms of configuration the closest I can find is [this fellow's comment](https://github.com/kubernetes/kubernetes/issues/31307#issuecomment-343318474) and my configuration seems to match his but even now it's not clear now to make the configuration take effect.

Does anyone know of any documentation that lays out the moving parts of setting up a host port and how to set one up, and any example configuration files/commands would be useful?

**Comment by jamiehannaford** [comment]
@smorrisfv Which CNI provider are you using? I recommend opening an issue on their repo with full details of your node, what's installed, configuration files, etc.

**Comment by smorrisfv** [comment]
@jamiehannaford I'm using Flannel.  I'll go checkout their repo to open an issue with them.

**Comment by jamiehannaford** [comment]
@smorrisfv Cool, I think that's where you'll find the most useful feedback. If you run into any kubeadm-specific errors or issues, please open a new issue and we'll be happy to help.
