### ISSUE TITLE
Usage of the --config flag not recommended

### ISSUE THREAD

**Issue by nabiladoui** [kubernetes/kubeadm#2940]
## Versions

kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.9
Kustomize Version: v4.5.7
Server Version: v1.26.9

## What happened?
Running kubeadm upgrade the --config flag is triggering the below warning :

kubeadm upgrade apply --force --config=/etc/kubernetes/kubeadmin-config.yaml --certificate-renewal=false
[upgrade/config] Making sure the configuration is correct:
W1005 15:38:39.283288 2452119 common.go:106] WARNING: Usage of the --config flag with kubeadm config types for reconfiguring the cluster during upgrade is not recommended!

What's the cause of this warning, and what's the recommended way ?

Thanks

**Comment by neolit123** [comment]
the warning is correct and up to date for API versions <= v1beta3. don't use upgrade with --config.
to reconfigure a cluster it should be done manually:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/

the --config for upgrade will be added for a future API, but reconfiguration of an existing node or the whole cluster will remain manual, until we have a plan how to manage that.

/kind support
