### ISSUE TITLE
Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix: missing address

### ISSUE THREAD

**Issue by devbiu** [kubernetes/kubeadm#2945]
## What keywords did you search in kubeadm issues before filing this one?
issues: https://github.com/kubernetes/kubeadm/issues/1893

## Versions

**kubeadm version** (use `kubeadm version`): 1.24.7

**Environment**:
- **Kubernetes version** (use `kubectl version`):  1.24.7
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): centos8
- **Kernel** (e.g. `uname -a`): Linuxxxxxx 4.18.0-240.el8.x86_64 #1 SMP Wed Sep 23 05:13:10 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Container runtime (CRI)** (e.g. containerd, cri-o): cri-docker
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): cni
- **Others**:

## What happened?
```shell
kubeadm init --kubernetes-version=1.24.7 --cri-socket unix:///run/cri-dockerd.sock --v=5 
```

<img width="1425" alt="image" src="https://github.com/kubernetes/kubeadm/assets/99388822/a1b778ff-6c2c-43a6-a26a-a1b8817423ad">

```shell
systemctl status kubelet
```
<img width="1413" alt="image" src="https://github.com/kubernetes/kubeadm/assets/99388822/2a45742c-eb2c-4976-a5f1-62b49c1e0517">

```shell
Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix: missing address
```

```shell
crictl --runtime-endpoint unix:///run/cri-dockerd.sock logs CONTAINERID
```
<img width="1446" alt="image" src="https://github.com/kubernetes/kubeadm/assets/99388822/06b1d988-ab2f-4ec9-a260-980e16d722e3">

Because the error reasons are the same, I tried all the methods in the issues, but still can't solve my problem. 
issues: https://github.com/kubernetes/kubeadm/issues/1893

## What you expected to happen?
kubernetes successful installation

## How to reproduce it (as minimally and precisely as possible)?
```shell
kubeadm init --kubernetes-version=1.24.7 --cri-socket unix:///run/cri-dockerd.sock --v=5 
```

## Anything else we need to know?
before executing issues, runtime error
issues: https://github.com/kubernetes/registry.k8s.io/issues/266#issuecomment-1767788059

**Comment by neolit123** [comment]
> unix:///run/cri-dockerd.sock

k8s maintainers recommend switching to containerd or crio. they are more up to date with k8s...

this is not a kubeadm bug, per se.
