### ISSUE TITLE
dial tcp 10.217.95.95:6443: connect: network is unreachable

### ISSUE THREAD

**Issue by wangZhuangSunHao** [kubernetes/kubeadm#2946]
I only have one server and I deploy single-node k8s，Server intranet IP address：10.217.95.95
docker --version  ： Docker version 18.09.9, build 039a7df9ba
1. yum install -y kubelet-1.18.0 kubeadm-1.18.0 kubectl-1.18.0 --disableexcludes=kubernetes  this is ok
2. kubeadm init --apiserver-advertise-address=10.217.95.95 --image-repository registry.aliyuncs.com/google_containers  --kubernetes-version v1.18.0  --service-cidr=10.96.0.0/12  --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all

3. systemctl status kubelet ，this is ok
4. journalctl -f -u kubelet，Reported several errors：
Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: networ...g uninitialized；
Failed to initialize CSINodeInfo: error updating CSINode annotation: timed out waiting for the condition; caused by: Get https://10.217.95.95:6443/apis/storage.k8s.io/v1/csinodes/policy-svr: dial tcp 10.217.95.95:6443: connect: network is unreachable
failed to ensure node lease exists, will retry in 800ms, error: Get https://10.217.95.95:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/policy-svr?timeout=10s: dial tcp 10.217.95.95:6443: connect: network is unreachable
5. kubectl get nodes，Prompt error：Unable to connect to the server: dial tcp 10.217.95.95:6443: connect: network is unreachable

**Comment by neolit123** [comment]
doesn't look like a kubeadm bug. network failures are likely local to your setup. please use the support channels instead of github to get help.

/support
