### ISSUE TITLE
e2e: handle the migration from ginkgo tags to labels

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2947]
see
https://groups.google.com/g/kubernetes-sig-testing/c/r_aaZVYR_Ts/m/h865YEspAgAJ

the migration means we can no longer pass --skip / --focus to ginkgo and instead we must use --label-filter.

new flag spec:
https://onsi.github.io/ginkgo/#filtering-specs

tracking issues / PRs:
- https://github.com/kubernetes/kubernetes/pull/121394

----------

for kinder we have to change a few places:

https://github.com/kubernetes/kubeadm/blob/main/kinder/ci/tools/update-workflows/templates/workflows/skew-kubelet-x-on-y.yaml

https://github.com/kubernetes/kubeadm/blob/74420c3b2ce12164bf203861a9e3de45f6a02bd8/kinder/ci/tools/update-workflows/templates/workflows/skew-x-on-y-tasks.yaml

https://github.com/kubernetes/kubeadm/blob/74420c3b2ce12164bf203861a9e3de45f6a02bd8/kinder/cmd/kinder/test/e2ekubeadm/e2ekubeadm.go

https://github.com/kubernetes/kubeadm/blob/74420c3b2ce12164bf203861a9e3de45f6a02bd8/kinder/cmd/kinder/test/e2e/e2e.go

possible other places too.

**Comment by pohly** [comment]
> the migration means we can no longer pass --skip / --focus to ginkgo and instead we must use --label-filter.

I forgot to mention it in the email: there is no plan yet when or if at all the inline tags get removed. The goal right now is only to *enable* jobs to use labels, but not to *force* them to do it.

**Comment by neolit123** [comment]
> I forgot to mention it in the email: there is no plan yet when or if at all the inline tags get removed. The goal right now is only to _enable_ jobs to use labels, but not to _force_ them to do it.

right, i saw later the mention that labels will generate `[ tag ]` inside the names to be backwards compatible.
if it's forced the change can be quite breaking to k8s and consumers of e.g. conformance tests.

**Comment by neolit123** [comment]
> EDIT: i will lower the priority for this ticket, as "something we can update".

let's close for the time being.
if k/k plans to migrate this, we can reopen.
