### ISSUE TITLE
Generate certs with a custom validity by signing CSRs

### ISSUE THREAD

**Issue by Lighty55** [kubernetes/kubeadm#2959]
## What keywords did you search in kubeadm issues before filing this one?
_kubeadm alpha certs check-expiration_
<img width="383" alt="image" src="https://github.com/kubernetes/kubeadm/assets/82205076/86d89eb0-289c-4a71-95bc-0633b8cee1d7">

## Is this a BUG REPORT or FEATURE REQUEST?
Feature Request

## Versions

**kubeadm version** (use `kubeadm version`): 1.15.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.15.2
- **Cloud provider or hardware configuration**: Local VM
- **OS** (e.g. from /etc/os-release): CentOS 7.9
- **Kernel** (e.g. `uname -a`): 3.10.0-1062.el7.x86_64
- **Container runtime (CRI)** (e.g. containerd, cri-o): docker
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): Calico

## What happened?
I have a use case where Kubernetes Cluster is deployed to a set of labs (i.e. offline, no internet access, air-gapped, etc.), and is expected to have the certification validity of 10 years.

## What you expected to happen?
Looking for guide to manually extend the Kubernetes certifications validity

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): 1.15.2

the oldest supported k8s version is 1.25
https://kubernetes.io/releases/
the subcommands i talk about below do not exist in 1.15.

> I have a use case where Kubernetes Cluster is deployed to a set of labs (i.e. offline, no internet access, air-gapped, etc.), and is expected to have the certification validity of 10 years.

this is not a supported or recommended use case.
the CA cert by default is signed for 10 years, but other certs are for 1 year, which is a secure default.

you need to implement a crone job that goes on your control-plane nodes every e.g. 300 days and does this:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal

kubeadm also supports `kubeadm certs generate-csr`. this will generate some CSR files in the `/etc/kubernetes{/pki}` directories. then you can use a CA and `openssl` to sign these CSR for any time you want. but we don't have a guide about singing the CSRs at the k8s.io website yet.
