### ISSUE TITLE
improve user experience about CNI errors

### ISSUE THREAD

**Issue by GheRivero** [kubernetes/kubeadm#296]
FEATURE REQUEST
One of the most common questions in the kubeadm channel is about "errors" with the CNI plugin. Before deploying any network addon, people take a look at the cluster status and see errors in the DNS "Pending" pod the main node in a NotReady status (runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized). 

To avoid this recurrent UX problem, there should be a way in `kubeadm init` to include which network add-on to deploy to avoid this kind of problems. There should be no default option and be totally compatible with current kubeadm behaviour. Possible options:

- Add a flag to `kubeadm init` to specify the addon to deploy (-network-addon=) This could be a full URL to the manifest to use. (could be extended to use only the addon name, but this would require maintaining a map in kubeadm about all the solutions and their manifest file location). There could be problems with current addons that use more than one manifest, like flannel (one for RBAC groups and the second one for the services. This is easily fixable by compacting them into just one manifest)

- Extend the config file to include the addon. This option is already implemented and can be easily extended to include a new option.

- Any other suggestions? This should be open to debate to get full consensus.

**Comment by timothysc** [comment]
I no longer see this being reported.  Closing. 
If you feel otherwise and have reproduction information please re-open.
