### ISSUE TITLE
Kubernetes :[ERROR Port-10250]: Port 10250 is in use

### ISSUE THREAD

**Issue by estem** [kubernetes/kubeadm#2974]
Hi,
when I'm trying to execute : 
`sudo kubeadm init --control-plane-endpoint=192.168.1.2 --node-name k8s-ctrlr --pod-network-cidr=10.244.0.0/16`

I got this error : 
`[init] Using Kubernetes version: v1.28.4
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Port-10250]: Port 10250 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher`

when I run : 
`netstat -ltnp | grep -w ":10250"`

`tcp6       0      0 :::10250                :::*                    LISTEN      -
`
what should I do please ?

thanks

**Comment by neolit123** [comment]
seems like a problem on the host and not kubeadm. please try asking on the support forums.
/support
