### ISSUE TITLE
kubeadm cluster configuration multi image repository with their tag

### ISSUE THREAD

**Issue by rastinrastini** [kubernetes/kubeadm#2977]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm cluster configuration multi image repository with their tag

FEATURE REQUEST

  - Describe *in detail* the feature/behavior/change you'd like to see.
 i used below kubeadm clusterinfo config but dont work. it seems that is good capability of setting all images used in kubeadm init in configuration optionally with their tag and repository

## Versions

**kubeadm version** (use `kubeadm version`):
1.28.2
**Environment**:
- **Kubernetes version** (use `kubectl version`):1.28.2
- **Cloud provider or hardware configuration**:16 GB ram
- **OS** (e.g. from /etc/os-release):ubuntu bionic
- **Kernel** (e.g. `uname -a`):4.15.0
- **Container runtime (CRI)** (e.g. containerd, cri-o):containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):calico
- **Others**:

## What happened?
only change last image

## What you expected to happen?
change several images mentioned in config file and used during init to complete and find their equivalence based on text between last ":" and last "/" if exists

## How to reproduce it (as minimally and precisely as possible)?
`Kubernetes version:1.28.4
Cloud being used: (put bare-metal if not on a public cloud)
Installation method:vagrant
Host OS: ubuntu
i use config with kubeadm init. i want to replace for example below images with custom my repository address and tags. but dont work. how can do that?

apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
imageRepository: 172.16.20.160:18082
dns:
        imageRepository: "172.16.20.160:18082/coredns"
        imageTag: "v1.10.0"
        imageRepository: "172.16.20.160:18082/pause"
        imageTag: "3.1"
networking:
  podSubnet: "192.168.0.0/16" # --pod-network-cidr
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.42.42.100
  bindPort: 6443`

kubeadm init --config init_conf.yaml --v=9

**Comment by neolit123** [comment]
please read the api docs  there is no need to pass pause. dns has only one imagerepository

https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

/support
