### ISSUE TITLE
Change kube-proxy xtables container to use a file type mount

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/kubeadm#298]
## Versions

**kubeadm version** (use `kubeadm version`):
master

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.7

At the moment we rely on kubernetes/kubernetes#47212 to create the xtables file upon kubelet startup. This means that we don't need anymore prep when mounting the xtables path into the kube-proxy. Since kubernetes/kubernetes#47212 has a TODO about fixing init-containers, we cannot rely on it to be there in future releases. 

When kubernetes/kubernetes#46597 merges, we should change the xtables lock to a file based mount. This should create the xtables lock as a file if it does not already exist

**Comment by luxas** [comment]
Fixed the original issue but introduced a new one: https://github.com/kubernetes/kubeadm/issues/306

**Comment by cmluciano** [comment]
/reopen

this is for tracking a file based mount once https://github.com/kubernetes/kubernetes/pull/46597 is merged

**Comment by luxas** [comment]
Ah, yeah, ok

**Comment by luxas** [comment]
This will be fixed once https://github.com/kubernetes/kubernetes/pull/50063 is merged
cc @dixudx

**Comment by dixudx** [comment]
@luxas Yeah. Right. Will rebase and retest once #46597 gets merged.

**Comment by luxas** [comment]
This is now fixed with https://github.com/kubernetes/kubernetes/pull/50063 :tada:
