### ISSUE TITLE
kubeadm: consider use --lazy option for unconnected nfs server when cleanup node mountpoints

### ISSUE THREAD

**Issue by zhangzhiqiangcs** [kubernetes/kubeadm#2980]
### What would you like to be added?

kubeadm cleanup load try `--lazy` option when encounting umount nfs error.
umount reference: https://linux.die.net/man/8/umount

### Why is this needed?

The kubeadm command may hangs if the node can not connect to nfs server

**Comment by neolit123** [comment]
please add more details to the description.

where is this --lazy flag supposed to be added?
is it for "kubeadm reset"?

if yes, then maybe this is a related issue:
https://github.com/kubernetes/kubeadm/issues/2923

and PR:
https://github.com/kubernetes/kubernetes/pull/120377

**Comment by zhangzhiqiangcs** [comment]
> please add more details to the description.
> 
> where is this --lazy flag supposed to be added? is it for "kubeadm reset"?
> 
> if yes, then maybe this is a related issue: #2923
> 
> and PR: [kubernetes/kubernetes#120377](https://github.com/kubernetes/kubernetes/pull/120377)

That issue and PR seems is just what I looked for. Thanks @neolit123

**Comment by neolit123** [comment]
ok, we can close this one.
that PR is blocked because we did not agree on how to do the change exactly so that it does not break users.
