### ISSUE TITLE
upgrading kubernetes cluster v.1.20 to v1.28

### ISSUE THREAD

**Issue by talsh5528** [kubernetes/kubeadm#2981]
i have Kubernetes clustet that i created using kubeadm command.
OS:  centos7
kubeadm,kubelet,kubectl: v1.20

i created the cluster by this command:
`kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version=v1.20.8` the engine was docker.

now I am trying to upgrade my cluster to v1.28 using cri-dockerd as my engine.
i installed kubeadm v1.28, and run:
`sudo kubeadm upgrade plan --v=5`
get this error:
I1212 09:44:10.674136   21512 plan.go:251] [upgrade/plan] verifying health of cluster
I1212 09:44:10.674220   21512 plan.go:252] [upgrade/plan] retrieving configuration from cluster
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
W1212 09:44:10.688332   21512 cluster.go:94] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"ClusterConfiguration"}: no kind "ClusterConfiguration" is registered for version "kubeadm.k8s.io/v1beta2" in scheme "cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:32"
no kind "ClusterConfiguration" is registered for version "kubeadm.k8s.io/v1beta2" in scheme "cmd/kubeadm/app/apis/kubeadm/scheme/scheme.go:32"

**Comment by neolit123** [comment]
you must upgrade one minor version at a time:
1.20 - > 21 -> 22 -> 23 ....  -> 28

> skipping MINOR versions when upgrading is unsupported. 

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

also note that cri-dockerd is really not well supported.
it's recommended to try migrating your nodes to containerd before you start upgrading.
https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/

for more questions please use the support forums.

/support

**Comment by talsh5528** [comment]
> you must upgrade one minor version at a time: 1.20 - > 21 -> 22 -> 23 .... -> 28
> 
> > skipping MINOR versions when upgrading is unsupported.
> 
> https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
> 
> also note that cri-dockerd is really not well supported. it's recommended to try migrating your nodes to containerd before you start upgrading. https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/
> 
> for more questions please use the support forums.
> 
> /support
do you have explanation why cri-dockerd is really not well supported ? where i can find doc that explain that

**Comment by talsh5528** [comment]
> you must upgrade one minor version at a time: 1.20 - > 21 -> 22 -> 23 .... -> 28
> 
> > skipping MINOR versions when upgrading is unsupported.
> 
> https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
> 
> also note that cri-dockerd is really not well supported. it's recommended to try migrating your nodes to containerd before you start upgrading. https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/
> 
> for more questions please use the support forums.
> 
> /support

@neolit123 
do you have explanation why cri-dockerd is really not well supported ? where i can find doc that explain that

**Comment by neolit123** [comment]
> do you have explanation why cri-dockerd is really not well supported ? where i can find doc that explain that

there is no doc and my information could be out of date. cri-dockerd was struggling at some point to keep up with CRI changes, thus users were unable to upgrade to newer kubelets.

the general recommandation is to migrate to containerd or cri-o.
for more Qs on this topic you can ask in #sig-node on the k8s slack, or you could also just ask cri-dockerd folks about the status and if they can't keep up.

**Comment by MoShaaban13** [comment]
Did you make the upgrade successfully?

**Comment by oldthreefeng** [comment]
Did you make the upgrade successfully?   this helps me alot
