### ISSUE TITLE
fix flaky test TestRunRenewCommands

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#2985]
sometimes when running all the kubeadm unit tests with this command from kubernetes/kubernetes:
```
go test ./cmd/kubeadm/app/... -count=1
```

there is one test that fails from time to time:
```
Error: unknown command "args --cert-dir=/tmp/1668299040" for "apiserver"
Usage:
  apiserver [flags]

Flags:
      --cert-dir string     The path where to save the certificates (default "/etc/kubernetes/pki")
      --config string       Path to a kubeadm configuration file.
  -h, --help                help for apiserver
      --kubeconfig string   The kubeconfig file to use when talking to the cluster. If the flag is not set, a set of standard locations can be searched for an existing kubeconfig file. (default "/etc/kubernetes/admin.conf")

--- FAIL: TestRunRenewCommands (0.84s)
    --- FAIL: TestRunRenewCommands/apiserver (0.04s)
        certs_test.go:285: certificate apiserver was not renewed as expected
```

**Comment by neolit123** [comment]
i haven't investigated the problem, and it's quite odd that it fails only sometimes.

on a quick look this `args` seems wrong:
```
 unknown command "args ...
```

cc @my-git9
perhaps something you would like to take a look at.

we can try adding the `help-wanted` label alternatively.

**Comment by my-git9** [comment]
/assgin I'll take a look at it later

**Comment by my-git9** [comment]
/assign
I'll take a look at it later

**Comment by my-git9** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/certs_test.go#L242-L243

This seems to be a deliberately designed scenario. In this scenario, the test result returns Error. In this test case, this "unknown command" error is expected. Do we need to optimize here?

**Comment by neolit123** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/certs_test.go#L242-L243
> 
> This seems to be a deliberately designed scenario. In this scenario, the test result returns Error. In this test case, this "unknown command" error is expected. Do we need to optimize here?

thanks for checking!

i see what is happening here...
i get the output of this test that expects the error only when another test somewhere FAILs. that happens because when a test fails "go test" enables verbosity (i think).

the problem is that we don't usually want to see this type of output.
i think if we change this line:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/certs_test.go#L267
to use io.Discard i will work.
https://pkg.go.dev/io#Discard

**Comment by my-git9** [comment]
> > https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/certs_test.go#L242-L243
> > This seems to be a deliberately designed scenario. In this scenario, the test result returns Error. In this test case, this "unknown command" error is expected. Do we need to optimize here?
> 
> thanks for checking!
> 
> i see what is happening here... i get the output of this test that expects the error only when another test somewhere FAILs. that happens because when a test fails "go test" enables verbosity (i think).
> 
> the problem is that we don't usually want to see this type of output. i think if we change this line: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/certs_test.go#L267 to use io.Discard i will work. https://pkg.go.dev/io#Discard

I tried using the following method, which seems to be invalid:

```
renewCmds := getRenewSubCommands(io.Discard, tmpDir)
```

The I tried the following method to modify it, and it worked after testing, but I don’t know if it is appropriate:

https://github.com/kubernetes/kubernetes/compare/master...my-git9:certs-fake?expand=1

**Comment by neolit123** [comment]
>  I tried the following method to modify it, and it worked after testing, but I don’t know if it is appropriate:

is it possible to write to a buffer instead of file?
https://stackoverflow.com/a/23454941

**Comment by neolit123** [comment]
> tried using the following method, which seems to be invalid:

not sure why it does not work, we use io.Discard in other places for cobra commands.

**Comment by my-git9** [comment]
> not sure why it does not work, we use io.Discard in other places for cobra commands.

Yes, It can be:

```go
			var stderrBuf bytes.Buffer
			oldStderr := os.Stderr
			r, w, _ := os.Pipe()
			os.Stderr = w
			go func() {
				_, _ = io.Copy(&stderrBuf, r)
			}()
			err := cmdtestutil.RunSubCommand(t, renewCmds, test.command, args)
			os.Stderr = oldStderr
			_ = w.Close()
```

**Comment by neolit123** [comment]
@my-git9 
please use this simple diff:
```diff
diff --git a/cmd/kubeadm/app/cmd/certs_test.go b/cmd/kubeadm/app/cmd/certs_test.go
index 8dff90ad8e2..3b50a6babe4 100644
--- a/cmd/kubeadm/app/cmd/certs_test.go
+++ b/cmd/kubeadm/app/cmd/certs_test.go
@@ -23,6 +23,7 @@ import (
        "crypto"
        "crypto/x509"
        "fmt"
+       "io"
        "os"
        "path/filepath"
        "strings"
@@ -269,7 +270,7 @@ func TestRunRenewCommands(t *testing.T) {
                        if len(test.Args) > 0 {
                                args = test.Args + " " + args
                        }
-                       err := cmdtestutil.RunSubCommand(t, renewCmds, test.command, args)
+                       err := cmdtestutil.RunSubCommand(t, renewCmds, test.command, io.Discard, args)
                        // certs renew doesn't support positional Args
                        if (err != nil) != test.expectedError {
                                t.Errorf("failed to run renew commands, expected error: %t, actual error: %v", test.expectedError, err)
diff --git a/cmd/kubeadm/test/cmd/util.go b/cmd/kubeadm/test/cmd/util.go
index d48e82d1646..0c0186d3a97 100644
--- a/cmd/kubeadm/test/cmd/util.go
+++ b/cmd/kubeadm/test/cmd/util.go
@@ -18,6 +18,7 @@ package kubeadm
 
 import (
        "bytes"
+       "io"
        "os"
        "os/exec"
        "testing"
@@ -50,8 +51,9 @@ func RunCmd(command string, args ...string) (string, string, int, error) {
 }
 
 // RunSubCommand is a utility function for kubeadm testing that executes a Cobra sub command
-func RunSubCommand(t *testing.T, subCmds []*cobra.Command, command string, args ...string) error {
+func RunSubCommand(t *testing.T, subCmds []*cobra.Command, command string, output io.Writer, args ...string) error {
        subCmd := getSubCommand(t, subCmds, command)
+       subCmd.SetOutput(output)
        subCmd.SetArgs(args)
        if err := subCmd.Execute(); err != nil {
                return err
```

RunSubCommand is only used in TestRunRenewCommand.
sometimes it's OK to change more code to make the test simpler!

**Comment by my-git9** [comment]
> only

OK, Thanks
