### ISSUE TITLE
separate cidr for control plane / master nodes and data plane / worker nodes

### ISSUE THREAD

**Issue by rgherta** [kubernetes/kubeadm#2993]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

latest

## What happened?

Hey guys... I know the managed kubernetes services like aws ecr and probably gke have separate subnets/cidrs for control plane and data plane... So I wonder if kubernetes allows this at all since kubeadm is just a wrapper around kubelet and other services....

## What you expected to happen?

In an enterprise environment control plane and data plane should be on different subnets and kubeadm should have a configuration property to allow this customization.

## Anything else we need to know?

Thank you for your effort

**Comment by neolit123** [comment]
> Hey guys... I know the managed kubernetes services like aws ecr and probably gke have separate subnets/cidrs for control plane and data plane... So I wonder if kubernetes allows this at all since kubeadm is just a wrapper around kubelet and other services....

hello, i could be wrong but i think what you are describing is that control plane and workload hosts deployed by these managed kubernetes services reside in separate subnets?
if so, that is entirely plausible, but kubeadm expects hosts to be prepared as a prerequisite, not configured by it.

if you are asking whether there is a way to have separate Node subnet groups, with a stock kube-controller-manager that is not possible. a custom cloud provider node controller maybe could do it, but that is out of scope for kubeadm.

**Comment by rgherta** [comment]
Hi @neolit123 ... This would explain a lot... so controller-manager should be able to handle 2 cidrs for 2 subnets... Anyways, let's keep this issue open oor stale for a while just in case someone else is searching for this.... Do you think I need to open an issue on the kubenretes project?

**Comment by neolit123** [comment]
> Hi @neolit123 ... This would explain a lot... so controller-manager should be able to handle 2 cidrs for 2 subnets... 

that's not how the k8s networking model works currently, but let's see if your other ticket gets any comments.
note that in this kubeadm repo we close tickets relatively fast, if we think something is not actionable.

> Anyways, let's keep this issue open or stale for a while just in case someone else is searching for this.... Do you think I need to open an issue on the kubernetes project?

i moved your other ticket to kubernetes/kubernetes.

**Comment by rgherta** [comment]
I am closing this since kubernetes makes no assumption about nodes provisioning and kube controller manager splits only the pod cidr. Sorry about the confusion.
