### ISSUE TITLE
kubeadm supports custom node check

### ISSUE THREAD

**Issue by yxxhero** [kubernetes/kubeadm#2994]
## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?
supports custom node check

exit code 0 will be ok

## What you expected to happen?
supports custom node check

**Comment by neolit123** [comment]
@yxxhero before sending a PR, can you explain in more details what this feature requestion is?

**Comment by yxxhero** [comment]
@neolit123 thanks for your reply. details: 
``` 
kubeadm has already done basic node checking, but in many scenarios, this is often not enough.
We can provide a parameter or configuration to let the user specify a script or command. When
 the script exit code is 0, the check passes, otherwise it does not pass. 
```

**Comment by neolit123** [comment]
> kubeadm has already done basic node checking, but in many scenarios, this is often not enough.
We can provide a parameter or configuration to let the user specify a script or command. When
 the script exit code is 0, the check passes, otherwise it does not pass. 

but users can do this additional node checking before calling kubeadm?

**Comment by yxxhero** [comment]
@neolit123 make senses. maybe kebeadm only supports key node check is enough.
