### ISSUE TITLE
[Failing Test]  kubeadm-kinder-super-admin-latest keeps failing for timeout

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubeadm#2995]
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-super-admin-latest 

```
+ docker exec kinder-super-admin-control-plane-1 kubeadm certs renew super-admin.conf
[renew] Reading configuration from the cluster...
[renew] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
 timeout. The task did not complete in less than 5m0s as expected
```
yesterday, after merging https://github.com/kubernetes/kubernetes/pull/122735 and https://github.com/kubernetes/kubernetes/pull/122529.

**Comment by pacoxu** [comment]
A local test shows that this is caused by https://github.com/kubernetes/kubernetes/pull/122529 @neolit123 @SataQiu

**Comment by pacoxu** [comment]
Commented here: https://github.com/kubernetes/kubernetes/pull/122529/files#r1452908313

**Comment by neolit123** [comment]
> https://github.com/kubernetes/kubernetes/pull/122529/files#r1452908313

we should stop using exp backoff in kubeadm.

> https://github.com/kubernetes/kubernetes/pull/122529/files#r1452908313

500ms / 1min is 120 retries
is it still failing?

**Comment by pacoxu** [comment]
I tried to fix in https://github.com/kubernetes/kubernetes/pull/122802. I tested locally and it works. 

> 500ms / 1min is 120 retries
Yes.

> is it still failing, does it need more time?
still

**Comment by neolit123** [comment]
> I tried to fix in [kubernetes/kubernetes#122802](https://github.com/kubernetes/kubernetes/pull/122802). I tested locally and it works.
> 
> > 500ms / 1min is 120 retries
> > Yes.
> 
> > is it still failing, does it need more time?
> > still

i will try locally as well.
instead of exp backoff we can try `KubernetesAPICall.Duration = 2m`

but it's surprising that locally it fails with a 1m timout.

**Comment by SataQiu** [comment]
I have test the backoff mode, it takes about ~320ms.
```go
func TestBackoff(t *testing.T) {
	backoff := wait.Backoff{
		Steps:    4,
		Duration: 10 * time.Millisecond,
		Factor:   5.0,
		Jitter:   0.1,
	}
	start := time.Now()
	err := wait.ExponentialBackoff(backoff, func() (bool, error) {
		return false, nil
	})
	t.Logf("elapsed time: %v", time.Since(start))	
	if err != nil {
		t.Error(err)
	}
}
```

**Comment by pacoxu** [comment]
> is the error actually due to timeout?
> 500ms interval in 1 minute is more attempts

`The task did not complete in less than 5m0s as expected`

https://github.com/kubernetes/kubeadm/blob/4598c42b932f19306e6fa5f54a14450f7c26a9a4/kinder/ci/workflows/super-admin-tasks.yaml#L97

We have a 5 minutes timeout for each step.

**Comment by neolit123** [comment]
yes, but these certs renew calls should complete right away. they do not block the execution for 1 minute each.
a "poll function' returns as soon as it gets the job done - e.g. 500ms, 1000ms, 1500ms...

**Comment by pacoxu** [comment]
my local test is one minute each

**Comment by neolit123** [comment]
i understand what the problem is now:

> [renew] Reading configuration from the cluster...
> [renew] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
> [renew] Error reading configuration from the Cluster. Falling back to default configuration

the way some parts of kubeadm are designed is:
- kubeadm checks if it can pull config from cluster
- if not it uses default config

in such conditions we should pass a shorter timeout to kubeadm, but not use a expbackoff.

**Comment by pacoxu** [comment]
Adding another short timeout would be a better solution.


I roughly revert that part😄 which may be not a final solution.

**Comment by neolit123** [comment]
yeah, like i mentioned a few times we should no longer use exp backoff in kubeadm.
just PollUntilContextTimeout

**Comment by neolit123** [comment]
@pacoxu please LGTM
https://github.com/kubernetes/kubernetes/pull/122811

your PR is correct, but i used Poll* for consistency instead.
