### ISSUE TITLE
Kubeadm init/join support setting kubelet KubeConfig serverURL to local APIEndpoint

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubeadm#2996]
### What would you like to be added?

Kubeadm  will create kubelet KubeConfig file when init/join control-plane. The serverURL is control-plane-endpoint load balancer address by default.

Adding a flag to change kubelet KubeConfig serverURL to local APIEndpoint, instead of controlPlane load balancer address 

### Why is this needed?

With some load balancer, the node can not connect to itself across the load balancer, so kubeadm init will fail. Setting kubelet KubeConfig serverURL to local APIEndpoint, the kubeadm init will succeed.

**Comment by neolit123** [comment]
> With some load balancer, the node can not connect to itself across the load balancer, so kubeadm init will fail. Setting kubelet KubeConfig serverURL to local APIEndpoint, the kubeadm init will succeed.

do you mean serverURL in kubelet.conf?
i don't think we want to do that. currently it points to the control plane endpoint which is expected for HA setups.
 
there is a plan to make the kubelet.conf point to localhost actually:
https://github.com/kubernetes/kubeadm/issues/2271

cc @chrischdi

**Comment by neolit123** [comment]
> Yes, it is. The node can not connect to itself across the load balancer (e.g. Alibaba cloud Classic Load Balancer).

is this hairpin mode? the azure LB had a similar problem, more details in #2271, IIRC.

> I think it is acceptable the kubelet will failed to register or be not ready if the local apiserver is not ready.

yes, but this is a complicated problem. if you enable the option you request the node that this kubelet manages will currently fail to register.

i suggest we close this ticket and continue the discussion in here:
>> there is a plan to make the kubelet.conf point to localhost actually:
>> https://github.com/kubernetes/kubeadm/issues/2271

**Comment by neolit123** [comment]
@pacoxu please LGTM
https://github.com/kubernetes/kubernetes/pull/122811

your PR is correct, but i used Poll* for consistency instead.

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubeadm/issues/2996#issuecomment-1893947965
/close
