### ISSUE TITLE
Kubeadm 1.17.0 upgrade fails

### ISSUE THREAD

**Issue by zhegemingzimeibanquan** [kubernetes/kubeadm#3001]
## What keywords did you search in kubeadm issues before filing this one?

version upgrade

## Is this a BUG REPORT or FEATURE REQUEST?

 BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:56:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`):
Linux ab60196 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
I upgrade kubeadm by yum upgrade and run kubeadm upgrade plan 
![image](https://github.com/kubernetes/kubeadm/assets/56252858/881ba14c-90f6-4374-b43c-83664359c3ab)
it reports this problrm above,but "kubernetes-admin" is not my node the node name is ab60192-ab60196,the master is ab60196

## What you expected to happen?
show the upgrade plane

## How to reproduce it (as minimally and precisely as possible)?

I dont now ,when i run the command ,it will report the error

```[tasklist]
### Tasks
```

**Comment by pacoxu** [comment]
Both v1.18.20 and 1.17 are out of support for a long time. https://endoflife.date/kubernetes

Please try 1.26 + in https://kubernetes.io/releases/.

**Comment by zhegemingzimeibanquan** [comment]
> Both v1.18.20 and 1.17 are out of support for a long time. https://endoflife.date/kubernetes
> 
> Please try 1.26 + in https://kubernetes.io/releases/.

i plan to upgrade to new version and i know that i need to upgrade version by version

**Comment by neolit123** [comment]
if a node is missing then something went really wrong.

try upgrading to 1.17.LATEST first and then to 1.18.LATEST. 

we don't have bandwidth to support old releases.
your best bet is to ask for help on support channels.

/support
