### ISSUE TITLE
Kubernetes cluster not form

### ISSUE THREAD

**Issue by Jaykhanderay** [kubernetes/kubeadm#3002]
when i was giving the command minikube start  in the terminal .it giving me the following error 

docker desktop acquired 2 CPU and kubernetes at least required 2 CPU when I go to the docker desktop setting there is 
.wslconfig file which I need to edit . i change the .wslconfig file but it giving me the same error please help me what should I do? 

i also created .wslconfig file but it doesn't work

**Comment by neolit123** [comment]
best to talk to the minikube maintainers.
/support
