### ISSUE TITLE
Provide options to use at least 3072-bits RSA to meet German federal BSI Technical Guideline TR-02102-2

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/kubeadm#3003]
EDIT: neolit123

latest proposal was outlined as a feature for v1beta4 here:
https://github.com/kubernetes/kubeadm/issues/3003#issuecomment-1917467330

PR to merge:
- https://github.com/kubernetes/kubernetes/pull/123054

v1beta4 tracking issue:
https://github.com/kubernetes/kubeadm/issues/2890

----

## What keywords did you search in kubeadm issues before filing this one?

rsa

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`): main

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?

This would have been a feature request, but as of 2024/1/1 this is now a bug. Germany's BSI (Federal Office for Information Security) requires government systems to use at least 3000 bit RSA keys since 2024/1/1. This means that kubeadm cannot meet federal security standards as the 2048-bit RSA key length is hardcoded.

>3000 bit keys are considered good until 2030.

Recommend changing the default to 3072-bits. This should have no impact on existing clusters.

## What you expected to happen?

To have keys defaulted to >3000-bits, or have the option to do so.

## How to reproduce it (as minimally and precisely as possible)?

N/A

## Anything else we need to know?

Guidelines are at https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-2.pdf?__blob=publicationFile&v=10 

No other deltas found against standards.

**Comment by neolit123** [comment]
thanks for informing us @randomvariable 
i will assign myself and send the PR to update this at master.

> This would have been a feature request, but as of 2024/1/1 this is now a bug. Germany's BSI (Federal Office for Information Security) requires government systems to use at least 3000 bit RSA keys since 2024/1/1. This means that kubeadm cannot meet federal security standards as the 2048-bit RSA key length is hardcoded.

i guess this makes it backportable to older releases of kubeadm. once the PR at master merges we can backport.

**Comment by enj** [comment]
> Germany's BSI (Federal Office for Information Security) requires government systems ...

This does not seem like a good reason to change anything in k/k.  You will inevitably run into conflicts between different entities wanting different things.

> To have keys defaulted to >3000-bits, or have the option to do so.

Giving users the choice seems fine, especially since you really should be using EC crypto over RSA.  But, before making any change to any defaults, make sure the approach that is configured has an assembly based crypto implementation for all platforms that we care to target.  Kube redoes crypto verification for every request (and not every connection), so we need to be careful here.

**Comment by neolit123** [comment]
something that @randomvariable commented on slack, we can enable this in kubeadm v1beta4 - i.e. string types that carry size or curve type:

```
	// EncryptionAlgorithmRSA2048 defines the RSA encryption algorithm type.
	EncryptionAlgorithmRSA2048 EncryptionAlgorithmType = "RSA-2048"
	// EncryptionAlgorithmRSA3072 defines the RSA encryption algorithm type.
	EncryptionAlgorithmRSA3072 EncryptionAlgorithmType = "RSA-3072"
	// EncryptionAlgorithmRSA4096 defines the RSA encryption algorithm type.
	EncryptionAlgorithmRSA4096 EncryptionAlgorithmType = "RSA-4096"
	// EncryptionAlgorithmECDSACurveP256 defines the ECDSA encryption algorithm type.
	EncryptionAlgorithmECDSACurveP256 EncryptionAlgorithmType = "ECDSA-CurveP256"
```

right now we have the basic:
```
	// EncryptionAlgorithmECDSA defines the ECDSA encryption algorithm type.
	EncryptionAlgorithmECDSA EncryptionAlgorithmType = "ECDSA"
	// EncryptionAlgorithmRSA defines the RSA encryption algorithm type.
	EncryptionAlgorithmRSA EncryptionAlgorithmType = "RSA"
```

but the v1beta4 API is not released yet so we can amend.

**Comment by pacoxu** [comment]
> but the v1beta4 API is not released yet so we can amend.

Link to https://github.com/kubernetes/kubeadm/issues/2890 v1beta4 tracking issue.
