### ISSUE TITLE
`--rootfs` flag breaks control plane detection for `upgrade node`

### ISSUE THREAD

**Issue by bjencks** [kubernetes/kubeadm#3007]
edit: neolit123

PRs

- 1.30 https://github.com/kubernetes/kubernetes/pull/123077
- 1.29 https://github.com/kubernetes/kubernetes/pull/123096
- 1.28 https://github.com/kubernetes/kubernetes/pull/123097

-------

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.28

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.27 -> 1.28
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): Fedora CoreOS 39.20240112.3.0
- **Kernel** (e.g. `uname -a`): 6.6.9-200.fc39.aarch64
- **Container runtime (CRI)** (e.g. containerd, cri-o): cri-o
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): cilium
- **Others**:

## What happened?

Using `kubeadm` from inside a toolbox container, `kubeadm --rootfs /run/host/ upgrade apply v1.28.6` on the first control plane node is successful, but `kubeadm --rootfs /run/host/ upgrade node` on the other control plane nodes reports "Skipping prepull. Not a control plane node."

## What you expected to happen?

Detects control plane node and performs control plane upgrade.

## How to reproduce it (as minimally and precisely as possible)?

Have a redundant control plane configuration and use `kubeadm` from inside a toolbox to act on the host.

## Anything else we need to know?

This was introduced by https://github.com/kubernetes/kubernetes/commit/e3d84aa93cda4d764f3eee8274f3dcff73ee89ee, which moved the `isControlPlaneNode` check from `newNodeData`, which runs during command execution after the chroot, to `newCmdNode` which runs before the chroot.

I'm aware that the `rootfs` flag is not well supported, but it's worked well enough for me up to now.

There is a workaround: create a symlink inside the toolbox of `/etc/kubernetes -> /run/host/etc/kubernetes/`

**Comment by neolit123** [comment]
@SataQiu can you please PTAL, that commit is yours.

**Comment by neolit123** [comment]
> This was introduced by https://github.com/kubernetes/kubernetes/commit/e3d84aa93cda4d764f3eee8274f3dcff73ee89ee, which moved the isControlPlaneNode check from newNodeData, which runs during command execution after the chroot, to newCmdNode which runs before the chroot.

@bjencks
on paper, the chroot is one of the first things that runs in kubadm
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/cmd.go#L71-L78

TMU, cobra calls PersistentPreRunE before everything else - e.g.:
- calls the prerun of chroot
- calls a subcommand like "kubeadm upgrade node"
- at that point the rootfs should be changed.

is my logic flawed?

**Comment by neolit123** [comment]
looks like you are right. after applying this patch:
```
diff --git a/cmd/kubeadm/app/cmd/cmd.go b/cmd/kubeadm/app/cmd/cmd.go
index 0a0729d7696..e8b002c87a5 100644
--- a/cmd/kubeadm/app/cmd/cmd.go
+++ b/cmd/kubeadm/app/cmd/cmd.go
@@ -17,6 +17,7 @@ limitations under the License.
 package cmd
 
 import (
+       "fmt"
        "io"
 
        "github.com/lithammer/dedent"
@@ -70,6 +71,7 @@ func NewKubeadmCommand(in io.Reader, out, err io.Writer) *cobra.Command {
                SilenceUsage:  true,
                PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
                        if rootfsPath != "" {
+                               fmt.Printf("--------- calling chroot with path: %s\n", rootfsPath)
                                if err := kubeadmutil.Chroot(rootfsPath); err != nil {
                                        return err
                                }
diff --git a/cmd/kubeadm/app/cmd/upgrade/node.go b/cmd/kubeadm/app/cmd/upgrade/node.go
index 0523172d339..eefd004b521 100644
--- a/cmd/kubeadm/app/cmd/upgrade/node.go
+++ b/cmd/kubeadm/app/cmd/upgrade/node.go
@@ -17,6 +17,7 @@ limitations under the License.
 package upgrade
 
 import (
+       "fmt"
        "io"
        "os"
 
@@ -116,6 +117,8 @@ func newNodeOptions() *nodeOptions {
                isControlPlaneNode = false
        }
 
+       fmt.Printf("--------- newNodeOptions() isControlPlaneNode: %v\n", isControlPlaneNode)
+
        if isControlPlaneNode {
                kubeConfigPath = constants.GetAdminKubeConfigPath()
        }
```

i see:
```
sudo kubeadm --rootfs /foo upgrade node
--------- newNodeOptions() isControlPlaneNode: false
--------- calling chroot with path: /foo
unable to chroot to /foo: no such file or directory
To see the stack trace of this error execute with --v=5 or higher
```

so looks like for some reason our subcommands get callled before the rootfs. that's not right.

**Comment by neolit123** [comment]
PR for this
https://github.com/kubernetes/kubernetes/pull/123077

we could backport to 1.28 and 1.29.

**Comment by neolit123** [comment]
updared OP with a list of PRs for .30, .29 .28

**Comment by SataQiu** [comment]
/close

the backports were merged
