### ISSUE TITLE
kubeadm: uploaded kubelet configuration with patch affects joining of other nodes without patches

### ISSUE THREAD

**Issue by ilia1243** [kubernetes/kubeadm#3008]
edit neolit123:

PRs:
- https://github.com/kubernetes/kubernetes/pull/123093
- https://github.com/kubernetes/kubernetes/pull/123108
- https://github.com/kubernetes/kubernetes/pull/123107
- https://github.com/kubernetes/kubernetes/pull/123106

-------
### What happened?

`kubeadm init phase upload-config kubelet` phase takes into account `kubeletconfiguration` patches. Thus, it overrides the values in `KubeletConfiguration` passed in `kubeadm --config`.

This affects joining of other nodes that do not have patches. The result of installation depends on the order of nodes added via `kubeadm init/join`.

This behavior appeared after https://github.com/kubernetes/kubernetes/pull/115575 in Kubernetes >= 1.27

### What did you expect to happen?

`upload-config kubelet` phase is expected to do not take into account `kubeletconfiguration` patches, as much as, for example, `upload-config kubeadm` does not take into account patches for control plane components.

### How can we reproduce it (as minimally and precisely as possible)?

Case 1:

Install cluster with two nodes configuring `serializeImagePulls` property of KubeletConfiguration as an example.

1. Create patch file `kubeletconfiguration.yaml` on Node 1 that sets `serializeImagePulls:` **true**
2. Add Node 1 using `kubeadm init --config` passing KubeletConfiguration with `serializeImagePulls:` **false**
3. Add Node 2 using `kubeadm join`.

Expected result:
1. Node 1 has `serializeImagePulls:` **true**
2. Node 2 has `serializeImagePulls:` **false**

Actual result:

Both nodes have `serializeImagePulls:` **true**.

Case 2:

The same as Case 1 but nodes are added in the reverse order.

1. Create patch file `kubeletconfiguration.yaml` on Node 1 that sets `serializeImagePulls:` **true**
2. Add Node 2 using `kubeadm init --config` passing KubeletConfiguration with `serializeImagePulls:` **false**
3. Add Node 1 using `kubeadm join`.

Expected result = Actual result:
1. Node 1 has `serializeImagePulls:` **true**
2. Node 2 has `serializeImagePulls:` **false**

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8", GitCommit:"66fee42707cd7f5a89f1987f7cb81b02dd19161c", GitTreeState:"clean", BuildDate:"2023-11-15T16:59:43Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8", GitCommit:"66fee42707cd7f5a89f1987f7cb81b02dd19161c", GitTreeState:"clean", BuildDate:"2023-11-15T16:50:09Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On premise installation
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux k8s-control-plane-1 5.15.0-92-generic kubernetes/kubernetes#102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd=1.6.12-0ubuntu1~22.04.3
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> https://github.com/kubernetes/kubernetes/pull/115575

hm, was not on this PR as a reviewer.
@SataQiu @pacoxu 
that seems like something we don't want to do.

on "init" when the kubelet CM is created for the first time we just want to upload what the user put in the --config as KubeletConfiguration, we don't want to patch it with the patch passed on "init".

@ilia1243 your workaround is to pass a patch on join.

**Comment by SataQiu** [comment]
So maybe we don't need to upload the patch? If yes, I can send a revert PR, maybe I misunderstood that at first

**Comment by neolit123** [comment]
reopen until we merge the backports.

**Comment by pacoxu** [comment]
> hm, i was not on this PR as a reviewer.
> @SataQiu @pacoxu
> that seems like something we don't want to do.

Patches are node specific and should not be uploaded.


>       --patches string                       Path to a directory that contains files named "target[suffix][+patchtype].extension". For example, "kube-apiserver0+merge.yaml" or just "etcd.json". "target" can be one of "kube-apiserver", "kube-controller-manager", "kube-scheduler", "etcd", "kubeletconfiguration". "patchtype" can be one of "strategic", "merge" or "json" and they match the patch formats supported by kubectl. The default "patchtype" is "strategic". "extension" must be either "json" or "yaml". "suffix" is an optional string that can be used to determine which patches are applied first alpha-numerically.

I cannot recall what I am considering when I review https://github.com/kubernetes/kubernetes/pull/115575.  I might thought the patch is from `kubeadm init` and should be uploaded at that time. However, that is a behavior change then.

**Comment by SataQiu** [comment]
/close

the backports were merged
