### ISSUE TITLE
kubeadm e2e's should exist for both supported minor versions

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#301]
Since we support v1.6 and v1.7 API servers for kubeadm CLI v1.7, we should run e2e tests for both control plane versions, so we can be sure both v1.6 and v1.7 (as the example) works at any given time.

This was discussed today in the SIG meeting where we agreed that this is a thing we should implement ASAP

**Comment by pipejakob** [comment]
PR opened: https://github.com/kubernetes/test-infra/pull/3104

**Comment by pipejakob** [comment]
To close the loop on this, the new test is part of the sig-cluster-lifecycle testgrid tab, and its first run was a success:

https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce-1.6-on-1.7
