### ISSUE TITLE
kubeadm init or join fails when swap is active

### ISSUE THREAD

**Issue by devZer0** [kubernetes/kubeadm#3017]
i'm getting this message on init/join

	[WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
	
when swap enabled, kubadm init/join fails with obscure errors and for no apparent reason. 

if swap BLOCKS kubeadm init/join it should not be a WARNING but an ERROR and it should be a mandatory/prerequisite requirement that swap is being disabled before any further action with kubernetes

i'm 25yrs+ into linux/unix and i have NEVER seen something fail because swap being active, so this cost me a while to find out that this has blocked kubernetes installation/configuration

did cost me some hours today and project now is using cloud provider now because i was not fast/reliable enough for providing a dev environment.

i did not disable swap at installation time as i did comment out in /etc/fstab and thought, the next reboot is ok for that. i had NEVER thought that this could create installation issues

that sucks

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:

- **Kubernetes version** (use `kubectl version`):
# kubectl version
Client Version: v1.28.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.6

- **Cloud provider or hardware configuration**:
3x virtual machine on pve 7.4 hypervisor, 8gb ram, 4vcpu

- **OS** (e.g. from /etc/os-release):
Debian 12 Bookworm 

- **Kernel** (e.g. `uname -a`):
Kernel 6.1.0-17-amd64

- **Container runtime (CRI)** (e.g. containerd, cri-o):
# dpkg --list|egrep "containerd|cri-"
ii  containerd                     1.6.20~ds1-1+b1                amd64        open and reliable container runtime
ii  cri-tools                      1.28.0-1.1                     amd64        Command-line utility for interacting with a container runtime

- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

https://github.com/kubernetes/kubeadm/issues/1893#issuecomment-706754173

"@cheeseyeah and anyone else stumbling upon this thread: in my case the containers where not created, or at least they weren't there after the kubeadm command finished. I managed to make it work only after disabling swap. This is crazy, from my point of view, because swap is a normal OS function and shouldn't create this bizarre behavior. But, hey, it works."

yes @rendler-denis, i think that can be called "crazy" to some degree :)

**Comment by neolit123** [comment]
closing, let's continue the discussion here:
https://github.com/kubernetes/kubeadm/issues/2563
