### ISSUE TITLE
make the temporary directory used for backing up static pod manifests during upgrade configurable

### ISSUE THREAD

**Issue by shubham-yewalekar** [kubernetes/kubeadm#3023]
## What keywords did you search in kubeadm issues before filing this one?

TempDirForKubeadm and KubernetesDir

I see values for these variables are hardcoded, so we cannot use a different directory than /etc/kubernetes/tmp for taking the backup of manifest files for static pods during upgrade

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

We should allow a custom backup directory for backing up the manifests for static pods during upgrade, we hit issues with upgrade if the /etc/kubernetes/tmp directory doesn't have enough space and blocks the upgrade, instead we should accept custom directory for taking the manifest backups

## Versions

Kubeadm version: 1.22 onwards (but I think so this problem will be for all the kubeadm releases, I observed it on 1.22 kubeadm version)

NOTE: I would like to work on the code changes required for adding this functionality if this feature proposal is accepted as a valid request. Thanks!!

**Comment by neolit123** [comment]
> I see values for these variables are hardcoded, so we cannot use a different directory than /etc/kubernetes/tmp for taking the backup of manifest files for static pods during upgrade

i'm generally not in favor of such a change. you could use symlink, correct?

**Comment by sgouda26** [comment]
> > I see values for these variables are hardcoded, so we cannot use a different directory than /etc/kubernetes/tmp for taking the backup of manifest files for static pods during upgrade
> 
> i'm generally not in favor of such a change. you could use symlink, correct?

No symlink doesn't work.  It fails with an error 

`[upgrade/etcd] Failed to upgrade etcd: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: [rename /etc/kubernetes/manifests/etcd.yaml /etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-13-23-27-53/etcd.yaml: invalid cross-device link, rename /etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-13-23-27-53/etcd.yaml /etc/kubernetes/manifests/etcd.yaml: invalid cross-device link]
[upgrade/etcd] Waiting for previous etcd to become available
I0213 23:27:56.716523   52085 etcd.go:463] [etcd] attempting to see if all cluster endpoints ([https://10.9.60.231:2379 https://10.9.60.230:2379 https://10.9.60.232:2379]) are available 1/10
[upgrade/etcd] Etcd was rolled back and is now available
[rename /etc/kubernetes/manifests/etcd.yaml /etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-13-23-27-53/etcd.yaml: invalid cross-device link, rename /etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-13-23-27-53/etcd.yaml /etc/kubernetes/manifests/etcd.yaml: invalid cross-device link]
couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced`

This implies that the filesystem for `/etc/kubernetes` and the filesystem redirected by the symlink for `/etc/kubernetes/tmp` are not located in the same filesystem. Therefore, creating a separate filesystem for `/etc/kubernetes/tmp` would not alleviate the issue and would likely result in the same error.

**Comment by shubham-yewalekar** [comment]
I also faced similar issue while using symlink for the backup dir /etc/kubernetes/tmp `invalid cross-device link`

Its an issue with the os.Rename function which is used to move the manifest files during the upgrade from the backup directory

**Comment by sadeek-robin** [comment]
I also had similar issue, symlink doesn't work unless has it big filesystem and we cannot have big / partition.

**Comment by neolit123** [comment]
> [upgrade/etcd] Failed to upgrade etcd: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: [rename /etc/kubernetes/manifests/etcd.yaml /etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-13-23-27-53/etcd.yaml: invalid cross-device link, rename /etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-13-23-27-53/etcd.yaml /etc/kubernetes/manifests/etcd.yaml: invalid cross-device link] [upgrade/etcd] Waiting for previous etcd to become available I0213 23:27:56.716523

that seems like something we can fix with a better rename function?
https://gist.github.com/var23rav/23ae5d0d4d830aff886c3c970b8f6c6b?permalink_comment_id=4431960#gistcomment-4431960

another thing you can try is to use is --rootfs (the kubeadm flag), to have your whole kubernetes tree on a different volume?
unclear if chroot (which --rootfs uses) would even work for this.,

**Comment by neolit123** [comment]
> We should allow a custom backup directory for backing up the manifests for static pods during upgrade, we hit issues with upgrade if the /etc/kubernetes/tmp directory doesn't have enough space and blocks the upgrade, instead we should accept custom directory for taking the manifest backups

what disk sizes are we talking about here? how much is the disk and how much is the tmp dir taking out of it?
manifests files don't contribute to size, is the etcd backup that is the culprit here?
if you have old etcd backups you should delete them or manually move them somewhere.

```sh
$ sudo du -sh /etc/kubernetes/tmp/kubeadm-backup-etcd-2024-02-15-21-59-40
124M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-02-15-21-59-40

$ sudo du -sh /etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-15-21-59-40
16K	/etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-15-21-59-40
```

we are in the process of developing a new upgradeconfiguration v1beta4.
https://github.com/kubernetes/kubernetes/pull/123068

so now would be the time to add such new options, for example:
- `tempPath String`
but maybe we want the symlink working instead.
currently none of these paths for /etc/kubernetes and /var/lib/kubelet and /var/lib/etcd are configurable.  

cc @pacoxu @calvin0327

**Comment by calvin0327** [comment]
@neolit123  Sorry, I'm not very clear, do we want a custom tmpPath instead of /etc/kubernetes/tmp? and which file do we link to?

**Comment by shubham-yewalekar** [comment]
> > We should allow a custom backup directory for backing up the manifests for static pods during upgrade, we hit issues with upgrade if the /etc/kubernetes/tmp directory doesn't have enough space and blocks the upgrade, instead we should accept custom directory for taking the manifest backups
> 
> what disk sizes are we talking about here? how much is the disk and how much is the tmp dir taking out of it? manifests files don't contribute to size, is the etcd backup that is the culprit here? if you have old etcd backups you should delete them or manually move them somewhere.
> 
> ```shell
> $ sudo du -sh /etc/kubernetes/tmp/kubeadm-backup-etcd-2024-02-15-21-59-40
> 124M	/etc/kubernetes/tmp/kubeadm-backup-etcd-2024-02-15-21-59-40
> 
> $ sudo du -sh /etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-15-21-59-40
> 16K	/etc/kubernetes/tmp/kubeadm-backup-manifests-2024-02-15-21-59-40
> ```
> 
> we are in the process of developing a new upgradeconfiguration v1beta4. [kubernetes/kubernetes#123068](https://github.com/kubernetes/kubernetes/pull/123068)
> 
> so now would be the time to add such new options, for example:
> 
> * `tmpPath String`
>   but maybe we want the symlink working instead.
>   currently none of these paths for /etc/kubernetes and /var/lib/kubelet and /var/lib/etcd are configurable.
> 
> cc @pacoxu @calvin0327

We were having a 2GB root partition which the /etc file-system was using, the root partition size was restricted by the customer

the symlink solution doesn't work because the error pointed in the last comments

yes, I believe the etcd backup was the culprit here and not the manifest files, but I think so it would be better to have all these directories configurable 

/etc/kubernetes
/var/lib/kubelet
/var/lib/etcd

to support all kinds of different environments

**Comment by neolit123** [comment]
> We were having a 2GB root partition which the /etc file-system was using, the root partition size was restricted by the customer

were there multiple etcd backups in there before upgrade.
if yes, you could delete / move them before upgrade, so that there is always only one.

> yes, I believe the etcd backup was the culprit here and not the manifest files, but I think so it would be better to have all these directories configurable
>
> /etc/kubernetes
> /var/lib/kubelet
> /var/lib/etcd

as a summary for the all the above dirs, that is not doable in the near future. the problem is complex and they are also hardcoded in systemd dropin files.

**Comment by neolit123** [comment]
> the symlink solution doesn't work because the error pointed in the last comments

yes, but i mentioned we can use a symlink approach that works:
https://github.com/kubernetes/kubeadm/issues/3023#issuecomment-1947205348

are you able to build kubeadm from source?
if yes, you can help us debug this custom solution.

also can you provide exact minimal steps for reproducing the problem, e.g. with tmpfs
- mount volume
- ... call upgrade

**Comment by neolit123** [comment]
> > the symlink solution doesn't work because the error pointed in the last comments
> 
> yes, but i mentioned we can use a symlink approach that works: [#3023 (comment)](https://github.com/kubernetes/kubeadm/issues/3023#issuecomment-1947205348)
> 
> are you able to build kubeadm from source? if yes, you can help us debug this custom solution.
> 
> also can you provide exact minimal steps for reproducing the problem, e.g. with tmpfs
> 
> * mount volume
> * ... call upgrade

code freeze for 1.30 is march 6th
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.30

**Comment by shubham-yewalekar** [comment]
> > the symlink solution doesn't work because the error pointed in the last comments
> 
> yes, but i mentioned we can use a symlink approach that works: [#3023 (comment)](https://github.com/kubernetes/kubeadm/issues/3023#issuecomment-1947205348)
> 
> are you able to build kubeadm from source? if yes, you can help us debug this custom solution.
> 
> also can you provide exact minimal steps for reproducing the problem, e.g. with tmpfs
> 
> * mount volume
> * ... call upgrade

Yes, I can build kubeadm from source, I will try to implement this custom solution with a better rename function to handle the symlink. Thanks!

**Comment by neolit123** [comment]
> @neolit123 does it make sense to make these directories configurable in future releases, to allow more flexibility to users while configuring the k8s clusters ?

with the current way kubeadm works, there is no plan.
our users use symlinks for all the discussed system dirs already.

also, there is nowhere to persist these changes. some node specific settings are lost once the user applies kubeadm init / join commands. such a change would need a KEP and we need to decide where the directories would be stored.
https://github.com/kubernetes/enhancements/blob/master/keps/README.md
ClusterConfiguration as cluster wide, doesn't seem ideal. we have a certsDir in there that we want to make node specific.

**Comment by shubham-yewalekar** [comment]
can we have a NodeConfiguration configmap for each node, something similar to KubeletConfiguration which is node specific, this will allow us to add other node specific configurations if needed in future

Using symlinks to solve this issue is not a good approach IMO, it may land us in unknown issues like it did in this case.

**Comment by shubham-yewalekar** [comment]
I can raise a KEP for this, for further discussions

**Comment by neolit123** [comment]
> can we have a NodeConfiguration configmap for each node, something similar to KubeletConfiguration which is node specific, this will allow us to add other node specific configurations if needed in future
> 

this has been discussed in the past, but it's not so simple.
if you are prepared for months of discussion go ahead.

> Using symlinks to solve this issue is not a good approach IMO, it may land us in unknown issues like it did in this case.

how so?

**Comment by shubham-yewalekar** [comment]
what I have observed is whenever there are disk partitions created on the system for different mount paths, its with an intention of isolating the partitions from each other, symlink defeats that purpose and hence many customers are hesitant to create symlinks across different partitions (it may have security implications as well)

**Comment by neolit123** [comment]
users must understand that cross-device symlinks are not inherently insecure.
kubeadm runs as root, and as long as we have the right permissions set, a symlink would be as secure.

i do not disagree with the feature request to eventually support these paths as customizable, in fact that's one of the first things i questioned when i joined the project. but at this point it's complicated and we are a small team that does not have the bandwidth to even provide sufficient review attention on a KEP that wants to swiftly address the change...that's a problem.

and the demand for customizing the paths is minimal ATM, AFAIK.
if customers need the proper topology they can use external etcd, that way the etcd backup is completely adjacent and managed. collocated etcd on CP nodes and big clusters do not mix well.
