### ISSUE TITLE
why does kube-apiserver use 127.0.0.1 as the etch-servers?

### ISSUE THREAD

**Issue by yxxhero** [kubernetes/kubeadm#3028]
```  
containers:
  - command:
    - kube-apiserver
    - --advertise-address=10.1.2.122
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379

```

see above
thanks so much.

**Comment by neolit123** [comment]
@yxxhero please use k8s slack channel #kubeadm for questions like this, not github.

the answer is that in stacked etcd topology etcd is running on the same host
if can use external etcd to run etcd  on different hosts

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/

or if you don't want 127.0.0.1
you can use patches to modify it:

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches

per node with the `etcd` patch target.

**Comment by yxxhero** [comment]
@neolit123  thanks so much.
