### ISSUE TITLE
feature-gate=SCTPSupport=true added in apiserver.yaml in running k8s cluster 1.28, but after adding this line under commands cluster is not accessible

### ISSUE THREAD

**Issue by HappyHuru** [kubernetes/kubeadm#3036]
I have referred the Kuberntes feature-gate official document and that shows SCTP is removed at 1.22 
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

Any idea on adding SCTPSupport in 1.28 K8S 

What I am facing issue while adding this line directly in k8s api-server.yaml manifest 
The connection to the server instance-20240315-20240315-140536:6443 was refused - did you specify the right host or port?

Experimented with kubeadm upgrade command 

root@instance-20240315-20240315-140536:/etc/kubernetes/manifests# sudo kubeadm upgrade apply 1.28.0 --feature-gates SCTPSupport=true --v=5
I0319 12:37:14.423173 3203612 apply.go:106] [upgrade/apply] verifying health of cluster
I0319 12:37:14.423438 3203612 apply.go:107] [upgrade/apply] retrieving configuration from cluster
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
I0319 12:37:14.446594 3203612 kubelet.go:74] attempting to download the KubeletConfiguration from ConfigMap "kubelet-config"
I0319 12:37:14.477759 3203612 common.go:186] running preflight checks
[preflight] Running pre-flight checks.
I0319 12:37:14.477945 3203612 preflight.go:77] validating if there are any unsupported CoreDNS plugins in the Corefile
I0319 12:37:14.487261 3203612 preflight.go:109] validating if migration can be done for the current CoreDNS release.
[upgrade] Running cluster health checks
I0319 12:37:14.499918 3203612 health.go:157] Creating Job "upgrade-health-check" in the namespace "kube-system"
I0319 12:37:14.515408 3203612 health.go:187] Job "upgrade-health-check" in the namespace "kube-system" is not yet complete, retrying
I0319 12:37:15.520453 3203612 health.go:187] Job "upgrade-health-check" in the namespace "kube-system" is not yet complete, retrying
I0319 12:37:16.520442 3203612 health.go:187] Job "upgrade-health-check" in the namespace "kube-system" is not yet complete, retrying
I0319 12:37:17.520571 3203612 health.go:187] Job "upgrade-health-check" in the namespace "kube-system" is not yet complete, retrying
I0319 12:37:18.520984 3203612 health.go:194] Job "upgrade-health-check" in the namespace "kube-system" completed
I0319 12:37:18.521018 3203612 health.go:200] Deleting Job "upgrade-health-check" in the namespace "kube-system"
unrecognized feature-gate key: SCTPSupport

Kindly help.

**Comment by SataQiu** [comment]
`SCTPSupport` is GAed, so the feature is stable and always enabled, you do not need to set it up manually.
@HappyHuru
