### ISSUE TITLE
Change etcd liveness probes to the new livez and readyz endpoints

### ISSUE THREAD

**Issue by siyuanfoundation** [kubernetes/kubeadm#3039]
This is related to https://github.com/etcd-io/etcd/issues/16007

Since v3.5.11, etcd has added [new livez/readyz HTTP endpoints](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#v3511-2023-12-07)
The design for the new probes is documented in [etcd livez and readyz probes](https://docs.google.com/document/d/1PaUAp76j1X92h3jZF47m32oVlR8Y-p-arB5XOB7Nb6U/edit?usp=sharing)

The new probes are Kubernetes API compliant, have more fine-grained metrics, and are better suited for liveness and readiness checks than  `/health?exclude=NOSPACE&serializable=true`, and `/health?serializable=false`

| Probe | endpoint used by kubeadm | endpoint proposed to use | difference |
| ------ | --------------------------- | -------------------------- | ---------- |
| LivenessProbe | `/health?exclude=NOSPACE&serializable=true` | `/livez` | `/livez` does not check for leaders because restarting local server does not mitigate the problem of cluster missing leader, while a crashing loop would worsen the problem. |
| StartupProbe | `/health?serializable=false` | `/readyz` | `/readyz` ignores the `NOSPACE` alarm, because if the local server is out of quota, the server is still able to take read/delete requests, and still able forward write requests to the leader to write successfully in the cluster. | 
| ReadinessProbe | None | `/readyz` | |

We should switch the current etcd `LivenessProbe` and `StartupProbe` to the new endpoints which are Kubernetes API compliant.

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

**Comment by siyuanfoundation** [comment]
cc @serathius

**Comment by neolit123** [comment]
> /readyz

do we expect any behavior changes if we add a readiness probe for etcd in kubeadm?
currently we indeed don't have a readiness probe.

**Comment by pacoxu** [comment]
Since we backport etcd minor version to previous releases as well, it's quite safe to change the probe in v1.31.

https://github.com/kubernetes/kubernetes/blob/release-1.27/cmd/kubeadm/app/constants/constants.go#L481-L486

**Comment by pacoxu** [comment]
BTW, do we plan to add the ReadinessProbe?
- https://github.com/kubernetes/kubernetes/pull/110767 & https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/manifests/etcd.manifest GCE even not add the startupProbe yet.

**Comment by SataQiu** [comment]
+1 for applying the new livez/readyz probe in v1.31

> do we expect any behavior changes if we add a readiness probe for etcd in kubeadm?
currently it indeed don't have a readiness probe.

That seems safe because we have already checked the etcd cluster health by client and have adopted a retry mechanism.

**Comment by neolit123** [comment]
> It's totally up to kubeadm / cluster-life-cycle's maintainers / leads to decide when to use the new /livez and /readyz endpoints. But please do not expect we can get etcd 3.6.0 released soon.

ok, seems like this can be added in kubeadm 1.31 once code freeze for 1.30 is over.
thanks for the info

**Comment by neolit123** [comment]
@siyuanfoundation @ahrtr any notable regressions in >= 3.5.11 that may keep users on < 3.5.11?
also i assume we really do recommend users to move to the latest PATCH of 3.5 due to CVE fixes, correct?

i have a WIP PR for this here, but it does not versions checking and it will cause an error for kubeadm users that are deploying a custom etcd version < 3.5.11 on kubeadm 1.31.

to be on the safe side the PR can also include some version checking, but it will not work for custom image strings as some users pass SHA for the etcd image. it would only work for users that are using a semver in the etcd image.

i think my preference would be to just have this mentioned in the release note, and also make kubeadm users stuck on older custom etcd version to finally upgrade!

https://github.com/kubernetes/kubernetes/pull/124465

**Comment by ahrtr** [comment]
> @siyuanfoundation @ahrtr any notable regressions in >= 3.5.11 that may keep users on < 3.5.11?
> also i assume we really do recommend users to move to the latest PATCH of 3.5 due to CVE fixes, correct?

No regression in >= 3.5.11.

Yes, it's recommended to bump etcd to the latest patch.
