### ISSUE TITLE
v1beta4: support custom certificate expiration time

### ISSUE THREAD

**Issue by jmjoy** [kubernetes/kubeadm#3040]
## What keywords did you search in kubeadm issues before filing this one?

expire, custom

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): 1.23.4

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.23.4
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?

Client certificates generated by [kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/) expire after `1 year`.

## What you expected to happen?

When running `kubeadm init` or `kubeadm certs renew`, we can pass extras command line arguments, or configuration item in yaml, to optionally specifiy the expiration time of certificate, not jsut the fixed `1 year`.

**Comment by SataQiu** [comment]
This is most likely a reference to client-go best practices https://github.com/kubernetes/client-go/blob/master/util/cert/cert.go#L40, and periodically rotating certificates is necessary for security reasons.

But we might consider supporting this configuration in v1beta4 Kubeadm API, and throw a warning when the configured expiration time is too long.

**Comment by neolit123** [comment]
> But we might consider supporting this configuration in v1beta4 Kubeadm API, and throw a warning when the configured expiration time is too long.

there have been too many requests for this, indeed.
it has to be a clusterconfiguration option, in terms of location, which is maybe fine.

one problem is that cert expiration time is a function of key sizes.
v1beta4 can support 4096 RSA
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go#L151-L154

but for example, if the user has passed an expiration time of N years, we'd have to know when to show a warning for a given key size. ... or maybe just show a warning always if the value is != 1 year.

**Comment by neolit123** [comment]
it to add a note about it. kubeadm today does support certs with custom expiration:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#signing-csr

**Comment by neolit123** [comment]
...so given the lack of customizable key size other than that hardcoded v1beta4 custom "types"
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go#L151-L154

and given users will be able to turn the cluster insecure easily with this option.

i'm -1.

@SataQiu @pacoxu 
what are your votes?

**Comment by SataQiu** [comment]
@neolit123 Although this may reduce the security level of the cluster, there to be many similar requests about this feature, and kubeadm does not support automatic certificate rotation at this time (maybe some operator can do it?). I think we can try to support this option in v1beta4 ClusterConfiguration, but throw a security warning if the specified value is bigger than the default value during the verification of the configuration. We already support change the `validity-period` for `kubeconfig`.

https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/cmd/kubeadm/app/cmd/kubeconfig.go#L92-L95

What do you think？@pacoxu

**Comment by neolit123** [comment]
ping @pacoxu ^

**Comment by neolit123** [comment]
i can try sending a PR for 1.31.
