### ISSUE TITLE
[QUESTION] How to add extra args from the command line?

### ISSUE THREAD

**Issue by tibeer** [kubernetes/kubeadm#3041]
## What keywords did you search in kubeadm issues before filing this one?

oidc, extraargs

## Is this a BUG REPORT or FEATURE REQUEST?

Neither not - just a question

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.8", GitCommit:"fc11ff34c34bc1e6ae6981dc1c7b3faa20b1ac2d", GitTreeState:"clean", BuildDate:"2024-03-15T00:05:37Z", GoVersion:"go1.21.8", Compiler:"gc", Platform:"linux/arm64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):

    Client Version: v1.29.3
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.28.8

- **Cloud provider or hardware configuration**:

    ARM64 Server, 4C 24GB RAM

- **OS** (e.g. from /etc/os-release):

    PRETTY_NAME="Ubuntu 22.04.4 LTS"
    NAME="Ubuntu"
    VERSION_ID="22.04"
    VERSION="22.04.4 LTS (Jammy Jellyfish)"
    VERSION_CODENAME=jammy
    ID=ubuntu
    ID_LIKE=debian
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    UBUNTU_CODENAME=jammy

- **Kernel** (e.g. `uname -a`):

    Linux beta 6.5.0-1019-oracle #19~22.04.1-Ubuntu SMP Tue Mar 12 23:02:13 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

- **Container runtime (CRI)** (e.g. containerd, cri-o):

    containerd github.com/containerd/containerd 1.7.2

- **Container networking plugin (CNI)** (e.g. Calico, Cilium):

    calico

- **Others**:

## What happened?

My current setup is trimmed to execute kubeadm without any configuration file, but instead with every parameter set from the command line itself from a remote host:

```sh
kubeadm init --upload-certs --apiserver-cert-extra-sans=<fqdn> --apiserver-advertise-address=0.0.0.0 --control-plane-endpoint=<fqdn>:6443 --pod-network-cidr=<pod_cidr_ipv4>,<pod_cidr_ipv6> --service-cidr=<service_cidr_ipv4>,<service_cidr_ipv6>
```

## What you expected to happen?

I would like to also configure oidc as extra arguments for the apiServer, but I cannot find any command line option that allows me to set extraArgs.

## How to reproduce it (as minimally and precisely as possible)?

N/A

## Anything else we need to know?

Since it seems kubeadm command line arguments are a second class citizen, should I move to the config file instead?

**Comment by neolit123** [comment]
hi, we don't provide support on github. there e.g. #kubeadm on k8s slack.

for this Q

you need to switch to config:
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/

but note if a flag with the same name is added more than one time it's not supported in v1beta3 
https://github.com/kubernetes/kubeadm/issues/1601

you can use patches to workaround
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches

/support
