### ISSUE TITLE
graduate the flag for structural output --experimental-output to just --output

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#3045]
noticed the flag is still experimental here:
https://github.com/kubernetes/website/pull/45911

the feature of structural output in kubeadm has been active for a 5+ releases.
this implies the backend works. the API is still alpha, but it's not attached to the backend usage.
we can just graduate the output API in another iteration.

https://github.com/carlory/kubernetes/blob/227c2e7c2b2c05a9c8b2885460e28e4da25cf558/cmd/kubeadm/app/util/output/output.go#L102-L108

in 1.31:
- mark --experimental-output as deprecated. add a new flag --output that also does the same thing
- https://github.com/kubernetes/kubernetes/pull/124393

in 1.32:
- remove --experimental-output 
TODO

**Comment by carlory** [comment]
@neolit123 I can do it 😊

**Comment by carlory** [comment]
but according to the KEP, some commands still need to be implemented. https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2504-kubeadm-machine-output#goals

**Comment by neolit123** [comment]
> but according to the KEP, some commands still need to be implemented. https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2504-kubeadm-machine-output#goals

the KEP is output date, but new commands can be added and still use --output.
we can prefix the description of --output for a particular command as EXPERIMENTAL

generally using --experimental-.... is a breaking change and not desired.

**Comment by neolit123** [comment]
>> add a new flag --output that also does the same thing

> Could we do that part in a v1.30 patch release? Any reason why we couldn't?

not a bugfix, thus can't be advocated for.
