### ISSUE TITLE
Bug: Update pull.go: Fix Typo, And a suggestion

### ISSUE THREAD

**Issue by 1000oaks** [kubernetes/kubeadm#3059]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

kinder (not kubeadm)

**Environment**:
- environment agnostic

## What happened?
I was wondering why each time I use kinder create cluster ..., connections to `auth.docker.io` and `registry-1.docker.io` would be made. Then I found this typo.

Because I found that I have no permission to pull requests to the repository, thus I have to paste the fixes here:

File: `kubeadm/kinder/pkg/cri/host/pull.go`

Fix: `exec.NewHostCmd("docker", "inspect", "--type=image", image);` to `exec.NewHostCmd("docker", "inspect", "--type=image", image).Run();`

```
func PullImage(image string, retries int) (bool, error) {
	// once we have configurable log levels
	// if this did not return an error, then the image exists locally

	if err := exec.NewHostCmd("docker", "inspect", "--type=image", image).Run(); err == nil {
		return false, nil
	}

	...
}
```

## What you expected to happen?

When I execute `kinder create cluster --image:kindest/node:vX` with `kindest/node:vX`, no network connections to `auth.docker.io` and `registry-1.docker.io` should be made.

## How to reproduce it (as minimally and precisely as possible)?

Execute `kinder create cluster --image:kindest/node:vX`, and capturing network traffic.

## Anything else we need to know?

Besides, to keep in accordance with KinD, I think that imagePullPolicy: "Never" can be provided (or becoming configurable) in kinder/pkg/kubeadm/config.go (variable configTemplateBetaV2 and configTemplateBetaV3) to make clustion creation process fully offline-friendly.

If I were wrong, please point out. Thanks!

**Comment by neolit123** [comment]
> Fix: exec.NewHostCmd("docker", "inspect", "--type=image", image); to exec.NewHostCmd("docker", "inspect", "--type=image", image).Run();

seems ok as a fix.

> Besides, to keep in accordance with KinD

we don't have to. kinder is strictly for kubeadm testing.
