### ISSUE TITLE
stop shelling out to crictl from kubeadm

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#3064]
instead of shelling out to crictl for CRI actions kubeadm can use the new https://git.k8s.io/cri-client library.

actions

1.31
- switch kubeadm to use the cri-client and only show a warning if crictl is missing
https://github.com/kubernetes/kubernetes/pull/124685
https://github.com/kubernetes/kubernetes/pull/125212
- update kubeadm install docs to optionally install crictl in >= 1.31
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl\
- https://github.com/kubernetes/website/pull/46576

1.32
- don't show a warning/error if the crictl binary is missing on kubeadm preflight
https://github.com/kubernetes/kubernetes/pull/126596
- decouple the kubeadm package from the cri-tools package in k/release
https://github.com/kubernetes/release/blob/38d66edef/cmd/krel/templates/latest/metadata.yaml#L15-L16
https://github.com/kubernetes/release/pull/3626

**Comment by saschagrunert** [comment]
> don't show a warning/error if the crictl binary is missing on kubeadm preflight

This should be addressed with https://github.com/kubernetes/kubernetes/pull/126596

**Comment by saschagrunert** [comment]
@neolit123 can we close this one?

**Comment by neolit123** [comment]
yes, closing. thanks!
