### ISSUE TITLE
Does it support master without container runtime?

### ISSUE THREAD

**Issue by ttc0419** [kubernetes/kubeadm#3068]
Does kubeadm support initializing a master node without using container (i.e. using systemd services)?

**Comment by dims** [comment]
@ttc0419 no.

**Comment by ttc0419** [comment]
> @ttc0419 no.

Thanks for the reply, is it recommended to use a container to host master components in production and why?

**Comment by neolit123** [comment]
/support
please direct such questions on the support channels
