### ISSUE TITLE
Remove deprecated flags of kubeadm upgrade

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubeadm#3083]
The `--api-server-manifest`, `--controller-manager-manifest` and `--scheduler-manifest` flags of `kubeadm upgrade diff` are marked as deprecated in v1.31, they can be removed in v1.33.

ref: https://github.com/kubernetes/kubernetes/pull/125779

https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli

----

edit by neolit123 

same for the `--feature-gates` flag:
https://github.com/kubernetes/kubernetes/pull/125797

**Comment by neolit123** [comment]
edited the OP to also track the feature-gates flag removel.
