### ISSUE TITLE
kubeadm e2e targeted at HEAD should use control plane images from master

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#309]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

TESTING REQUEST

Using something as simple as https://gist.github.com/luxas/7515d1e1fb94cff1327b83ae4affd7a4, it's possible to download and `docker load` images from the latest CI builds.

We should use this instead of relying on `dl.k8s.io/release/latest.txt`, which has been a major obstacle for us in the v1.7 cycle.

It's fairly straightforward to implement this functionality in kubernetes-anywhere now that https://github.com/kubernetes/test-infra/pull/2761 is merged. We should just make the `master` or `HEAD` keyword of kubernetes-version special and when kubernetes-anywhere picks that up it will use the latest images from the CI builds.

@pipejakob Can you fix this?

**Comment by roberthbailey** [comment]
Docker load is a pretty ugly hack. While we might want to support it in the short term, we should really be making each of the CI builds push images into gcr (in a different bucket from the release images). 

@ixdy

**Comment by luxas** [comment]
I agree that it's kind of ugly, but I can't convince Google to pay for uploading the CI images from the crossbuild to `gcr.io/kubernetes-release-dev` or the like...
Spawned https://github.com/kubernetes/test-infra/issues/1400 some time ago for this...

**Comment by roberthbailey** [comment]
I don't think it's a cost issue.... we are already pushing the tarballs to GCS and storing the docker images in gcr.io (which is backed by GCS). And @ixdy commented on the linked issue that "we'd like to start doing this." I think it's more a matter of getting it set up.

**Comment by luxas** [comment]
@roberthbailey Ok, great, thanks for clarifying.
Would we all agree on having the cross-build CI job do this?
Could we agree on `gcr.io/kubernetes-release-dev/` or `gcr.io/kubernetes-ci-cross/` or the like?

I'm not actually sure how hard it would be to implement, I'm not familiar with how to get the credentials to gcr.io etc for such a job

**Comment by ixdy** [comment]
I agree with @roberthbailey. I want to get rid of sideloading entirely. All that we really need to fix kubernetes/test-infra#1400 is to figure out which project to upload to. We could use `kubernetes-jenkins`, or we could create a new one.

**Comment by roberthbailey** [comment]
I like the idea of creating a new project for the sole use of storing these CI images. @luxas proposed two names [above](https://github.com/kubernetes/kubeadm/issues/309#issuecomment-309790840). I think we should go with `kubernetes-ci-cross` or even `kubernetes-ci-images` to be explicit about exactly what we are storing in the gcr repository.

**Comment by ixdy** [comment]
+1 `kubernetes-ci-images`.

**Comment by pipejakob** [comment]
I unassigned myself as I don't have bandwidth for this right now (and didn't want to dissuade anyone else from picking it up). I am interested in following the progress of https://github.com/kubernetes/test-infra/issues/1400, and will take another look at this once the CI images are automatically pushed.

**Comment by pipejakob** [comment]
I think this duplicates https://github.com/kubernetes/kubeadm/issues/238, but I'll let @luxas confirm and close in case I missed a subtle difference.

**Comment by luxas** [comment]
Actually kind of a dupe, yes
Closing...
