### ISSUE TITLE
kubeadm init "Status from runtime service failed" err="rpc error: code = Unknown desc = stat /proc/1087/ns/pid: permission denied: unknown"

### ISSUE THREAD

**Issue by liuxun931** [kubernetes/kubeadm#3092]
suse-master1:~# cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.6"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.6"
PRETTY_NAME="openSUSE Leap 15.6"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.6"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"

suse-master1:~# kubeadm init \
--apiserver-advertise-address=192.168.59.121 \
--image-repository=registry.aliyuncs.com/google_containers \
--kubernetes-version v1.30.2 \
--service-cidr=10.96.0.0/12 \
--pod-network-cidr=10.244.0.0/16 \
--cri-socket=unix:///run/containerd/containerd.sock
[init] Using Kubernetes version: v1.30.2
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        **[ERROR CRI]: container runtime is not running: output: E0723 22:15:01.047666   14666 remote_runtime.go:633] "Status from runtime service failed" err="rpc error: code = Unknown desc = stat /proc/1087/ns/pid: permission denied: unknown"**
time="2024-07-23T22:15:01+08:00" level=fatal msg="getting status of runtime: rpc error: code = Unknown desc = stat /proc/1087/ns/pid: permission denied: unknown"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

suse-master1:~ # stat /proc/1087/ns/pid
  File: /proc/1087/ns/pid -> pid:[4026531836]
  Size: 0               Blocks: 0          IO Block: 1024   symbolic link
Device: 13h/19d Inode: 21152       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-07-23 22:02:01.608865876 +0800
Modify: 2024-07-23 22:01:24.698084419 +0800
Change: 2024-07-23 22:01:24.698084419 +0800
 Birth: -

#journalctl -xeu containerd
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013772732+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.sandbox-controllers\"..." type=io.containerd.gr>
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013783980+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.sandboxes\"..." type=io.containerd.grpc.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013794234+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.snapshots\"..." type=io.containerd.grpc.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013804169+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.streaming\"..." type=io.containerd.grpc.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013813769+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.tasks\"..." type=io.containerd.grpc.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013824934+08:00" level=info msg="loading plugin \"io.containerd.transfer.v1.local\"..." type=io.containerd.transfer.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013849997+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.transfer\"..." type=io.containerd.grpc.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013860247+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.version\"..." type=io.containerd.grpc.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013868323+08:00" level=info msg="loading plugin \"io.containerd.internal.v1.restart\"..." type=io.containerd.internal.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013920788+08:00" level=info msg="loading plugin \"io.containerd.tracing.processor.v1.otlp\"..." type=io.containerd.trac>
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013940406+08:00" level=info msg="skip loading plugin \"io.containerd.tracing.processor.v1.otlp\"..." error="skip plugin>
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013949612+08:00" level=info msg="loading plugin \"io.containerd.internal.v1.tracing\"..." type=io.containerd.internal.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013961335+08:00" level=info msg="skip loading plugin \"io.containerd.internal.v1.tracing\"..." error="skip plugin: trac>
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013977702+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.healthcheck\"..." type=io.containerd.grpc.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.013987704+08:00" level=info msg="loading plugin \"io.containerd.nri.v1.nri\"..." type=io.containerd.nri.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.014018012+08:00" level=info msg="NRI interface is disabled by configuration."
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.014027650+08:00" level=info msg="loading plugin \"io.containerd.grpc.v1.cri\"..." type=io.containerd.grpc.v1
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.014260919+08:00" level=warning msg="`mirrors` is deprecated, please use `config_path` instead"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.014319236+08:00" level=info msg="Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs De>
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.014363901+08:00" level=info msg="Connect containerd service"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.014389093+08:00" level=info msg="using legacy CRI server"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.014395611+08:00" level=info msg="using experimental NRI integration - disable nri plugin to prevent this"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.014470663+08:00" level=info msg="Get image filesystem path \"/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs>
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.015877008+08:00" level=error msg="failed to load cni during init, please check CRI plugin status before setting up netw>
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.015970761+08:00" level=info msg="Start subscribing containerd event"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.016002134+08:00" level=info msg="Start recovering state"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.022414214+08:00" level=info msg=serving... address=/run/containerd/containerd.sock.ttrpc
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.022522726+08:00" level=info msg=serving... address=/run/containerd/containerd.sock
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.102326442+08:00" level=info msg="Start event monitor"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.102451735+08:00" level=info msg="Start snapshots syncer"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.102506473+08:00" level=info msg="Start cni network conf syncer for default"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.102693472+08:00" level=info msg="Start streaming server"
Jul 23 22:00:01 suse-master1 containerd[1087]: time="2024-07-23T22:00:01.102838963+08:00" level=info msg="containerd successfully booted in 0.191674s"
Jul 23 22:00:01 suse-master1 systemd[1]: Started containerd container runtime.
░░ Subject: A start job for unit containerd.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit containerd.service has finished successfully.
░░
░░ The job identifier is 254.
Jul 23 22:01:24 suse-master1 containerd[1087]: time="2024-07-23T22:01:24.702311977+08:00" level=error msg="Status failed" error="stat /proc/1087/ns/pid: permission denied: unknown"
Jul 23 22:02:01 suse-master1 containerd[1087]: time="2024-07-23T22:02:01.613405663+08:00" level=error msg="Status failed" error="stat /proc/1087/ns/pid: permission denied: unknown"
Jul 23 22:06:53 suse-master1 containerd[1087]: time="2024-07-23T22:06:53.743345801+08:00" level=error msg="Status failed" error="stat /proc/1087/ns/pid: permission denied: unknown"
Jul 23 22:07:37 suse-master1 containerd[1087]: time="2024-07-23T22:07:37.529143875+08:00" level=error msg="Status failed" error="stat /proc/1087/ns/pid: permission denied: unknown"
Jul 23 22:08:09 suse-master1 containerd[1087]: time="2024-07-23T22:08:09.343230471+08:00" level=error msg="Status failed" error="stat /proc/1087/ns/pid: permission denied: unknown"
Jul 23 22:15:01 suse-master1 containerd[1087]: time="2024-07-23T22:15:01.047356585+08:00" level=error msg="Status failed" error="stat /proc/1087/ns/pid: permission denied: unknown"

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

The issue can be reproduced by setting kubeadm, kubelet, kubectl in complain mode in apparmor.

**Comment by neolit123** [comment]
> [ERROR CRI]: container runtime is not running: output: E0723 22:15:01.047666 14666 remote_runtime.go:633] "Status from runtime service failed" err="rpc error: code = Unknown desc = stat /proc/1087/ns/pid: permission denied: unknown"

you seem to have some sort of a permission problem on the host.
but we don't provide supprot on github. try seeking help on the support channels.
see links below from the bot.

/support
