### ISSUE TITLE
Error from server: etcdserver: request timed out

### ISSUE THREAD

**Issue by BHANU123MYREPO** [kubernetes/kubeadm#3095]
Hi support 

i have setuped perfectly HA kubeadm cluster  with aws NLB with port : 6443 
every thing is working fine and i have 3 masters and when i turnoff master1 machine and  no network connectivity issues are there with cluster and  kubectl  client machines 
i am getting below error 

Error:     Error from server: etcdserver: request timed out

**Comment by neolit123** [comment]
please use the support forums
/support
