### ISSUE TITLE
Verify that the Node Authorizer is enabled and working on kubeadm 1.7.x+ clusters

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#310]
How to implement: https://github.com/kubernetes/kubernetes/issues/47174#issue-234494786

Basically the only thing we have to do is to run an extra bash script on kubeadm v1.7.x+ clusters, until the linked issue is fixed and we can `ginkgo.focus` it.

@pipejakob Should you or I take this on?

**Comment by pipejakob** [comment]
I'm already very oversubscribed for this release cycle, so if you're capable, go for it, @luxas! I'll try to offer help/pointers as much as possible, but I don't think I can take this on.

**Comment by luxas** [comment]
Yay, this test is now enabled :tada:
