### ISSUE TITLE
After running kubeadm init the kube-proxy pod crashing 

### ISSUE THREAD

**Issue by FearLessSaad** [kubernetes/kubeadm#3103]
After running kubeadm init the kube-proxy pod keep crashing and right after it gose **_CrashLoopBackOff_** state.
The Version of kubernetes is 1.30.
![image](https://github.com/user-attachments/assets/9469ad4e-cd8b-478e-b0f5-d6bceefa9fa3)

**Comment by neolit123** [comment]
what is in the kube proxy logs?

**Comment by FearLessSaad** [comment]
[image: image.png]

**Comment by neolit123** [comment]
try asking for help on the support forums please.
/support
