### ISSUE TITLE
In Kubernetes V1.30.2, is there any wat to migrate from stacked etcd to external etcd?

### ISSUE THREAD

**Issue by raj1596** [kubernetes/kubeadm#3106]
Currently we are running our services on kubeadm cluster( Kubernetes V1.30.2) with stacked etcd. 
We want to move from stacked etcd to external etcd cluster. is this achievable without any data loss?

please suggest me if there any solution for this.

**Comment by neolit123** [comment]
note: we don't use github for support.

/support

in theory you could:
- create a etcd snapshot and deploy it on an external etcd cluster
- stop the kubelet on control plane nodes
- edit the kubeadm ClusterConfiguration in the kube-system/kubeadm-config configmap to use the external etcd struct field
- edit kube-apiserver.yaml to point to the external etcd instances
- remove local etcd.yaml instances
- restart kubelets on CP nodes

i don't think we claim this as supported migration but it seems doable. i suggest you create a test cluster with local etcd and try to migrate it to external. then if it works do it on your prod cluster.
