### ISSUE TITLE
The  calico-node pods are restarted automatically

### ISSUE THREAD

**Issue by srinidks** [kubernetes/kubeadm#3121]
Hi Team,

We have observed that the calico-node pods in the production infrastructure are restarting automatically. Attached below are the error logs for your review. We would appreciate your assistance in diagnosing and resolving this issue.
[0.log](https://github.com/user-attachments/files/17643089/0.log)

Thanks in advance.

**Comment by neolit123** [comment]
kubeadm is CNI agnostic. please contact the calico team.

/support
