### ISSUE TITLE
kubectl connection refused

### ISSUE THREAD

**Issue by iamantil** [kubernetes/kubeadm#3122]
Not sure if this a bug

## What keywords did you search in kubeadm issues before filing this one?
"Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused"

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

clientVersion:
  buildDate: "2024-09-11T21:26:49Z"
  compiler: gc
  gitCommit: 948afe5ca072329a73c8e79ed5938717a5cb3d21
  gitTreeState: clean
  gitVersion: v1.31.1
  goVersion: go1.22.6
  major: "1"
  minor: "31"
  platform: linux/amd64

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Container runtime (CRI)** (e.g. containerd, cri-o):
- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
- **Others**:

## What happened?

Unable to use the kubectl CLU

## What you expected to happen?

At least the pods should be displayed after the initialization of the cluster.

## How to reproduce it (as minimally and precisely as possible)?
I guess initializing the kubedm cluster in External CA mode can do it.

**Comment by pharazon** [comment]
You need to run kubectl get nodes on master, or remotely to master node. If you run the command on or to workers, you get this error.

On kube worker:

```
# kubectl get nodes
E1224 09:52:40.990045  718653 memcache.go:265] "Unhandled Error" err="couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

On kube master:

```
# kubectl get nodes
NAME          STATUS   ROLES           AGE   VERSION
kubernetes1   Ready    control-plane   35d   v1.31.2
kubernetes2   Ready    control-plane   35d   v1.31.2
kubernetes3   Ready    control-plane   35d   v1.31.2
kubeworker1   Ready    <none>          35d   v1.31.2
kubeworker2   Ready    <none>          35d   v1.31.2
kubeworker3   Ready    <none>          25d   v1.31.3
```
