### ISSUE TITLE
[BUG] Kubelet Ignores Updated etcd.yaml and Monitors Only etcd.yaml.backup During kubeadm Upgrade

### ISSUE THREAD

**Issue by rad1k4l** [kubernetes/kubeadm#3136]
### What happened?

During the `kubeadm upgrade` process, `kubeadm` creates a backup of the existing etcd manifest (`etcd.yaml.backup`) and updates the `etcd.yaml` manifest to a newer version (e.g., from etcd 3.4.13-0 to 3.5.16-0). However, post-upgrade, the `kubelet` appears to ignore the updated `etcd.yaml` and continues to monitor and apply changes only to `etcd.yaml.backup`. This behavior prevents the etcd cluster from upgrading, causing the `kubeadm upgrade` process to fail.

### What did you expect to happen?

After initiating the kubeadm upgrade:

- kubeadm should update the etcd.yaml manifest to the new etcd version (3.5.16-0).
- kubelet should detect changes in etcd.yaml, apply the updated configuration, and successfully upgrade the etcd cluster to version 3.5.16-0.
- The etcd.yaml.backup should remain as a backup and kubelet should continue to monitor only the primary etcd.yaml manifest.

### How can we reproduce it (as minimally and precisely as possible)?

There are two methods to reproduce the issue: Automated Upgrade via kubeadm and Manual Updating of etcd.

**Automated Upgrade via kubeadm:**
   - Attempt to upgrade the cluster using kubeadm to upgrade etcd to version 3.5.16-0:

>    `kubeadm upgrade apply v1.32.0`

   - kubeadm creates `etcd.yaml.backup` and updates `etcd.yaml` to version 3.5.16-0.
   - `kubelet` ignores `etcd.yaml`(verison 3.5.16-0 ) and only monitors `etcd.yaml.backup` ( version 3.4.13-0), preventing the etcd upgrade.

**Manual :**
 
- Create a backup of the existing `etcd.yaml` file: 
`cp /etc/kubernetes/manifests/etcd.yaml /etc/kubernetes/manifests/etcd.yaml.backup`

- Open etcd.yaml in a text editor and update the etcd image version from `3.4.13-0` to `3.5.16-0`.
- Restart the kubelet service: 
`systemctl restart kubelet`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.31.4
```

</details>

### Cloud provider

<details>
On-premises bare-metal servers
</details>

### OS version

<details>

```console
# Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux srv 5.15.0-130-generic kubernetes/kubernetes#140-Ubuntu SMP Wed Dec 18 17:59:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
there is undocumented behavior of the kubelet here.
if you have any file YAML in the /etc/kubernetes/manfiests dir the kubelet will try to load it even if it's named .yaml.backup.
bottom line is don't put backups in the directory.

this is a kubelet problem you should log an issue in kubernetes/kubernetes if you want to discuss with the kubelet maintainers.
there was already an issue for this in the past but i cannot find it.

**Comment by neolit123** [comment]
if your cluster is broken after these actions. try getting help on the support channels
/support

**Comment by rad1k4l** [comment]
@neolit123 I wrote this on kubernetes/kubernetes but @HirazawaUi transferred this issue here

**Comment by HirazawaUi** [comment]
Sorry for moving it here.

> * Attempt to upgrade the cluster using kubeadm to upgrade etcd to version 3.5.16-0:
> 
> > `kubeadm upgrade apply v1.32.0`
> 
> * kubeadm creates `etcd.yaml.backup` and updates `etcd.yaml` to version 3.5.16-0.
> * `kubelet` ignores `etcd.yaml`(verison 3.5.16-0 ) and only monitors `etcd.yaml.backup` ( version 3.4.13-0), preventing the etcd upgrade.

According to your description, `/etc/kubernetes/manifests/etcd.yaml.backup` is generated during the execution of `kubeadm upgrade apply`.

If this is caused by kubeadm upgrade, the issue should also be attributed to kubeadm. However, I don't believe `kubeadm upgrade performs` such actions.

`kubeadm upgrade` backs up etcd.yaml to the `kubeadm-backup-manifests` directory.
ref: https://github.com/kubernetes/kubernetes/blob/3ec9c7f4d20be445af83d0bd5c4e77a9f22ab6cc/cmd/kubeadm/app/phases/upgrade/staticpods.go#L101-L116

**Comment by HirazawaUi** [comment]
I noticed that you created a new issue in k/k. If `/etc/kubernetes/manifests/etcd.yaml.backup` was created by you, you should avoid mentioning kubeadm in the issue description. This will help the sig-node maintainers make an accurate assessment.
