### ISSUE TITLE
Feature Request - pre-flight command

### ISSUE THREAD

**Issue by gtirloni** [kubernetes/kubeadm#314]
In light of the work on supporting phases in kubeadm (#267) it would also be interesting to have the pre-flight checks be available as a phase and accessible through a specific command.

This would be useful to configuration management tools that want to first make sure everything is fine before continuing with the next phases.

**Comment by luxas** [comment]
Thanks for the issue @gtirloni! Sounds very good to me, do you want to contribute that change :smile:?
I can guide you if you want...

**Comment by gtirloni** [comment]
@luxas definitely want to work on this if you're willing to tolerate newcommer mistakes :)

Would it be okay if I add this under `kubeadm alpha phase preflight` ?

**Comment by luxas** [comment]
> @luxas definitely want to work on this if you're willing to tolerate newcommer mistakes :)

I'd love to see a PR from you that fixes this! If there's something you struggle with, we know what to improve on our SIG's contribex side, and that's truly helpful information. We want the contributor experience to be really smooth, so tell me if you see something that looks strange, there surely are things that we can improve ;)

> Would it be okay if I add this under kubeadm alpha phase preflight ?

Sounds very good to me!

**Comment by timothysc** [comment]
It might also be worth while to rationalize a portion of the "node conformance" tests into the preflight checks.

**Comment by luxas** [comment]
> It might also be worth while to rationalize a portion of the "node conformance" tests into the preflight checks.

@timothysc Can you create a new issue for that?
