### ISSUE TITLE
KUBELET_DNS_ARGS isn't reflecting the kubeadm init command line flags

### ISSUE THREAD

**Issue by farcaller** [kubernetes/kubeadm#315]
## Versions

**kubeadm version** (use `kubeadm version`): `kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:03:38Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:15:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: KVM
- **OS** (e.g. from /etc/os-release): Ubuntu 16.10 Yakkety Yak
- **Kernel** (e.g. `uname -a`): `Linux kube-master-1 4.8.0-56-generic #61-Ubuntu SMP Wed Jun 14 08:15:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## Kubeadm invocation

```
$ kubeadm init --service-cidr 10.200.0.0/13 --service-dns-domain example.error
```

## What happened?
systemd launch file is incorrect:

```
# /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_EXTRA_ARGS
```

## What you expected to happen?

`KUBELET_DNS_ARGS` should reflect `service-cidr` and `service-dns-domain` flags in `cluster-dns` and `cluster-domain` respectively.

## How to reproduce it (as minimally and precisely as possible)?

See Kubeadm invocation above.

**Comment by luxas** [comment]
We are very well aware of this issue and are keeping #28 open for this issue.

@farcaller or @jamiehannaford could you take on documenting this behavior though?

**Comment by jamiehannaford** [comment]
@luxas Sure I'll send a PR tomorrow or Friday

**Comment by luxas** [comment]
Thanks @jamiehannaford!

**Comment by luxas** [comment]
PR is merged :+1:
