### ISSUE TITLE
Docker is not detected if running with different service name

### ISSUE THREAD

**Issue by gtirloni** [kubernetes/kubeadm#317]
With the introduction of [docker-latest](https://access.redhat.com/articles/2317361) by Red Hat, the test partially fails because the systemd unit is called "docker-latest" and kubeadm is looking for "docker".

Would actually trying to use Docker be a better test (e.g. `docker info|ps|version`)?

```
# kubeadm reset
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] docker doesn't seem to be running, skipping the removal of running kubernetes containers
[reset] No etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml", assuming external etcd.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]

# docker run hello-world >/dev/null && echo ok
ok

# docker ps -a --filter name=k8s_ -q | wc -l
3
```

## Versions

**kubeadm version**: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:03:38Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version**: 1.6.5
- **Cloud provider or hardware configuration**: bare-metal
- **OS** (e.g. from /etc/os-release): CentOS 7.3
- **Kernel**: 3.10.0-514.21.1.el7.x86_64

## What happened?
`kubeadm reset` emits warning about missing Docker daemon and doesn't delete Kubernetes containers.

## What you expected to happen?
kubeadm would understand that Docker is running

## How to reproduce it (as minimally and precisely as possible)?
1. Enable virt7-docker-common-candidate repository

```
[virt7-docker-common-candidate]
name=virt7-docker-common-candidate
baseurl=https://cbs.centos.org/repos/virt7-docker-common-candidate/x86_64/os/
enabled=1
gpgcheck=0
```

2. Install docker-latest (`yum install docker-latest`)
3. Start docker (`systemctl start docker-latest`)
4. Run `kubeadm reset`

## Anything else we need to know?

```
# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

# docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Package version: docker-common-1.13.1-17.git27e468e.el7.x86_64
 Go version:   go1.7.4
 Git commit:   6cd0bbe/1.13
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-dev
 API version:         1.25
 Minimum API version: 1.12
 Package version:     docker-common-1.13.1-17.git27e468e.el7.x86_64
 Go version:          go1.7.4
 Git commit:          6cd0bbe/1.13
 Built:               
 OS/Arch:             linux/amd64
 Experimental:        false
```

## Workaround

For people facing this issue, one workaround is to edit /usr/lib/systemd/system/docker-latest.service and add an "Alias=docker.service" in the "[Install]" section (then re-enable docker-latest.service so the symlinks are created).

**Comment by gtirloni** [comment]
Related https://github.com/kubernetes/kubernetes/issues/26259

**Comment by luxas** [comment]
Sure! Propose a PR if you come up with some clever way to solve this :)

**Comment by gtirloni** [comment]
We ended up getting too many issues running docker-latest (not related to kubeadm) so I won't be using that for the time being (eyeballing cri-o now). If folks still think this would be useful (specially considering other runtimes), I'd say leave it open otherwise I would be okay with closing this.

**Comment by luxas** [comment]
You choose. Is there any actionable item here, keep open. If not, close.

**Comment by gtirloni** [comment]
Ok, closing. If the need resurfaces we can re-open this and work on it. Thanks.
