### ISSUE TITLE
support for adding extra kubelet configuration

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#32]
_From @spacexnice on October 25, 2016 8:17_

# Support for adding extra Kubelet config

kubeadm should support for adding extra kubelet configuration while doing kubeadm init.   i want to add an extra [ --pod-infra-container-image] parameter to kubelet cmdline ,but cant find a parameter doing so.  

_Copied from original issue: kubernetes/kubernetes#35502_

**Comment by mikedanese** [comment]
_From @codablock on November 4, 2016 8:7_

I had to provide cloud-config flags to the kubelet and opened an issue with a proposal that may also solve your requirements: https://github.com/kubernetes/kubernetes/issues/36213

**Comment by mikedanese** [comment]
_From @spacexnice on November 4, 2016 8:11_

@codablock yes, that` correct !

**Comment by luxas** [comment]
Closing in favor for #28, which would fix this issue as well.
