### ISSUE TITLE
Review how kubeadm parses yaml and converts resources to internal API objects

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#322]
Caught in https://github.com/kubernetes/kubernetes/pull/47346

@caesarxuchao noted that the way kubeadm decodes resources is kind of strange.
Let me show here in this issue what code we are using (what actually works, but might use some hidden knobs we didn't know about)

Parsing the MasterConfiguration object in the kubeadm API group:
```go
"k8s.io/kubernetes/pkg/api"
"k8s.io/apimachinery/pkg/runtime"
// Internal version
kubeadmapi "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm"
// Versioned API
kubeadmapiext "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha1"
---
// Without information populated by flags
cfg := &kubeadmapiext.MasterConfiguration{}
api.Scheme.Default(cfg)

// After information from flags has been set; default again and then convert
api.Scheme.Default(cfg)
internalcfg := &kubeadmapi.MasterConfiguration{}
api.Scheme.Convert(cfg, internalcfg, nil)
// From now; the internal version is used everywhere

// Decode from the yaml config file
if cfgPath != "" {
	b, err := ioutil.ReadFile(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("unable to read config from %q [%v]", cfgPath, err)
	}
	if err := runtime.DecodeInto(api.Codecs.UniversalDecoder(), b, internalcfg); err != nil {
		return nil, fmt.Errorf("unable to decode config from %q [%v]", cfgPath, err)
	}
}
```

Now that I started thinking about this; I'm unsure of how it actually can work as well :joy:, however, it indeed does

Parsing/decoding addons:
```go
"k8s.io/api/core/v1"
"k8s.io/kubernetes/pkg/api"
kuberuntime "k8s.io/apimachinery/pkg/runtime"
clientset "k8s.io/client-go/kubernetes"
---

func CreateKubeProxyAddon(configMapBytes []byte, client *clientset.Clientset) error {
	kubeproxyConfigMap := &v1.ConfigMap{}
	if err := kuberuntime.DecodeInto(api.Codecs.UniversalDecoder(), configMapBytes, kubeproxyConfigMap); err != nil {
		return fmt.Errorf("unable to decode kube-proxy configmap %v", err)
	}

	if _, err := client.CoreV1().ConfigMaps(metav1.NamespaceSystem).Create(kubeproxyConfigMap); err != nil {
		...
	}
}
```

@kubernetes/sig-api-machinery-pr-reviews as this was originally commented on a PR, but just moved here

**Comment by deads2k** [comment]
A universal decoder will perform a conversion to get you to internal if it needs to.

**Comment by luxas** [comment]
So the question here is -- is it okay to do this (using the universal decoder, which works) or should we somehow change the way we parse/decode/convert?

**Comment by deads2k** [comment]
> So the question here is -- is it okay to do this (using the universal decoder, which works) or should we somehow change the way we parse/decode/convert?

The universal decoder seems reasonable.  I'd like to see you create your own scheme though to avoid re-using a "private" kube one that everyone shares.

**Comment by luxas** [comment]
Ok, thanks for confirming.

> I'd like to see you create your own scheme though to avoid re-using a "private" kube one that everyone shares.

@deads2k Can you elaborate on that?

Code in `register.go` for the versioned group currently:
```go
// GroupName is the group name use in this package
const GroupName = "kubeadm.k8s.io"

// SchemeGroupVersion is group version used to register these objects
var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: "v1alpha1"}

var (
	// TODO: move SchemeBuilder with zz_generated.deepcopy.go to k8s.io/api.
	// localSchemeBuilder and AddToScheme will stay in k8s.io/kubernetes.
	SchemeBuilder      runtime.SchemeBuilder
	localSchemeBuilder = &SchemeBuilder
	AddToScheme        = localSchemeBuilder.AddToScheme
)

func init() {
	// We only register manually written functions here. The registration of the
	// generated functions takes place in the generated files. The separation
	// makes the code compile even when the generated files are missing.
	localSchemeBuilder.Register(addKnownTypes, addDefaultingFuncs)
}

// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(SchemeGroupVersion,
		&MasterConfiguration{},
		&NodeConfiguration{},
	)
	metav1.AddToGroupVersion(scheme, SchemeGroupVersion)
	return nil
}
```

What would you like to change (other than the TODO)?

**Comment by deads2k** [comment]
The code you pasted into the description references `api.Codecs` and `api.Scheme` from `"k8s.io/kubernetes/pkg/api"`.  Can you make your own CodecFactory like `api.Codecs` based on your scheme?

**Comment by luxas** [comment]
@deads2k Ah, you mean that way. Sure, but that would work only when deserializing the kubeadm-specifc types (case one), not when deserializing ConfigMaps, Deployments, etc, right?
We'd still have to use `pkg/api` there or would the UniversalDecoder work in any case?

```
// Scheme is the default instance of runtime.Scheme to which types in the Kubernetes API are already registered.
// NOTE: If you are copying this file to start a new api group, STOP! Copy the
// extensions group instead. This Scheme is special and should appear ONLY in
// the api group, unless you really know what you're doing.
// TODO(lavalamp): make the above error impossible.
var Scheme = runtime.NewScheme()

// Codecs provides access to encoding and decoding for the scheme
var Codecs = serializer.NewCodecFactory(Scheme)
```

Also I'm wondering what that comment on Scheme implicates in this scenario...

**Comment by deads2k** [comment]
> We'd still have to use pkg/api there or would the UniversalDecoder work in any case?

Given a goal of decoupling types from their usage, its more proper to either allow the client to do it for you (which it already does in its own scheme) or install the particular APIs you need into your scheme.  `install.Install(your registry, metasomething, scheme)`



> Also I'm wondering what that comment on Scheme implicates in this scenario...

It means that your API types themselves don't have a scheme, but your process should have a scheme.  Your types need to be installable into many schemes (must not hardcode to one).

**Comment by mikedanese** [comment]
I'm confused as to why this wouldn't work... We import `"k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/install"` which install the apigroup in the default Scheme.

**Comment by mikedanese** [comment]
We should try to match what the kube-proxy does https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go

**Comment by luxas** [comment]
So it works fine, but I got asked whether we could move out of the default Scheme I think and make a kubeadm-specific one. Not sure how important doing that is though...

**Comment by mikedanese** [comment]
It's tech debt. That is what kube-proxy does:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L172

**Comment by YDD9** [comment]
I'm trying to run `kubeadm init --config=config.yaml` but have error during parsing.

unable to decode config from "config.yaml" [v1alpha1.MasterConfiguration: APIServerExtraArgs: ReadMapCB: expect { or n, parsing 102 ...traArgs":"... at {"api":{"advertiseAddress":"192.168.0.43"},"apiServerCertSANs":["192.168.0.53"],"apiServerExtraArgs":"endpoint-reconciler-type=lease","apiVersion":"kubeadm.k8s.io/v1alpha1","etcd":{"caFile":"/etc/kubernetes/pki/etcd/ca.pem","certFile":"/etc/kubernetes/pki/etcd/client.pem","endpoints":["http://192.168.0.50:2379","http://192.168.0.51:2379","http://192.168.0.52:2379"],"keyFile":"/etc/kubernetes/pki/etcd/client-key.pem"},"kind":"MasterConfiguration","networking":{"podSubnet":"10.244.0.0/16"}}]

My yaml is a copy from the doc.
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 192.168.0.43
etcd:
  endpoints:
  - http://192.168.0.50:2379
  - http://192.168.0.51:2379
  - http://192.168.0.52:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: 10.244.0.0/16
apiServerCertSANs:
  - 192.168.0.53
apiServerExtraArgs:
  endpoint-reconciler-type=lease
```

**Comment by bart0sh** [comment]
@YDD9 can you point me out to that doc?

It looks like a format error to me. "endpoint-reconciler-type=lease" doesn't look like valid yaml to me.

**Comment by mattkelly** [comment]
@bart0sh I'm guessing that @YDD9 was referring to this doc: https://kubernetes.io/docs/setup/independent/high-availability/#kubeadm-init-master0. There was some misleading text in there that has [since been fixed](https://github.com/kubernetes/website/pull/7370/files#diff-882a2f00a1e48794c57974b92121984aR445).

@YDD9 have you changed that last line to `endpoint-reconciler-type: lease` and retried?

**Comment by YDD9** [comment]
@bart0sh @mattkelly  yes, it's a format error in yaml from the document, should be `endpoint-reconciler-type: lease`, it looks now the documents has updated and changed.  https://github.com/kubernetes/website/issues/7355

**Comment by luxas** [comment]
I'm grabbing this one as part of https://github.com/kubernetes/community/pull/2131 for v1.11

PRs:
 - https://github.com/kubernetes/kubernetes/pull/63782
 - https://github.com/kubernetes/kubernetes/pull/63787
 - https://github.com/kubernetes/kubernetes/pull/63799

**Comment by luxas** [comment]
This is now done. Finally I added unit tests in https://github.com/kubernetes/kubernetes/pull/63917
