### ISSUE TITLE
Add --feature-flags to kubeadm

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#323]
We should use the same mechanism as the rest of k8s to enable/disable new features.

**Comment by luxas** [comment]
Assignee: @jamiehannaford :+1:

**Comment by svitlanacs** [comment]
+1 for this feature
I've been [trying to figure out](https://stackoverflow.com/questions/45113034/kubernetes-gpu-support-how-to-enable) how to enable "feature-gates=Accelerators=true" (GPU support) for days now. Had to manually rule out which service exactly requires this option. And have not been entirely successful yet...

**Comment by luxas** [comment]
@svitlanacs I think you should enable that on the kubelets in your cluster.
Unfortunately, this `--feature-flags` option only controls kubeadm features, not the rest of the k8s ones, which you can set in other ways already.

This is now fixed with https://github.com/kubernetes/kubernetes/issues/48943
