### ISSUE TITLE
 kubeadm init --token is only respected if its the sole flag

### ISSUE THREAD

**Issue by zilman** [kubernetes/kubeadm#325]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 

## Versions

kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): Centos7
- **Kernel** (e.g. `uname -a`): Linux ip-172-20-0-211 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## What happened?

```
You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token 80dde6.5ea0388857dfb1c3 172.20.0.211:6443
```

## What you expected to happen?

```
You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token thecustomtoken 172.20.0.211:6443
```

## How to reproduce it (as minimally and precisely as possible)?

`kubeadm init --token=${TOKEN} --config=/etc/kubernetes/kubeadm.conf`

## Anything else we need to know?

`kubeadm init --token=${TOKEN}` works as expected.

## Anything else we need to know?

I'm not sure if this is by design or not. I believe I was able to use two flags with kubeadm init just a few days ago, so perhaps this is a regression with kubeadm 1.6.6.

**Comment by gtirloni** [comment]
Can you share you /etc/kubernetes/kubeadm.conf file?

**Comment by luxas** [comment]
This is working as expected and documented. `--config` has precedence over any flag.
I think we made v1.7 error out or warn if you combine them...

**Comment by gtirloni** [comment]
@luxas I was able to reproduce this behavior with the following kubeadm.conf file:

```yaml
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
selfHosted: false
```
The token passed to `kubeadm init --token` was ignored and a new one generated, even though the config file is not specifying a token.

**Comment by zilman** [comment]
@gtirloni sure, it is the basic one.

```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
cloudProvider: aws
```

@luxas you're not wrong in that appending `token: $TOKEN` to the config file works as expected.
However, when there is no token in the config file the --token flag _should_ be respected. I do believe there is a (non critical) bug here.

**Comment by luxas** [comment]
> However, when there is no token in the config file the --token flag should be respected. I do believe there is a (non critical) bug here.

That's a design decision.
What happens?
1. There is an empty, defaulted, versioned struct object (`cfg`).
2. Flags are applied upon that object `cfg`, and defaulted once again.
3. `cfg` is converted to the internal version of the struct => `internalcfg`
4. If config is specified, there is a decoder that marshals the yaml/json file into `internalcfg`
5. Use `internalcfg` for all operations

**Comment by zilman** [comment]
@luxas I think if I'm getting it correctly is that the config file takes precedence. I agree with that as a design decision. 

What I'm saying is that up until this latest version if you specified something like the token via a flag that _did not exist in the config file_, it would get picked up. That is both intuitive and documented. An example like that is given in the docs and was working last week.

If the change is now that if a config file is specified _at all_ no other flag is respected, that's also fine, but then at least the documentation needs to reflect this.

**Comment by luxas** [comment]
> What I'm saying is that up until this latest version if you specified something like the token via a flag that did not exist in the config file, it would get picked up. That is both intuitive and documented. An example like that is given in the docs and was working last week.

@zilman Interesting. Which `kubeadm version`?
