### ISSUE TITLE
Move all environment variables into the API

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#326]
We should have this mix of "you can set this env param to modify behavior" (which is unversioned from the API machinery PoV) and the real API group with corresponding types using the correct API machinery.

Everything in [this file](https://github.com/kubernetes/kubernetes/blob/v1.7.0/cmd/kubeadm/app/apis/kubeadm/env.go) should be moved into the API types file.

**Comment by fabriziopandini** [comment]
+1
