### ISSUE TITLE
[ARM]etcd POD abnormally terminated after a few minutes executing 'kubeadm init'

### ISSUE THREAD

**Issue by Mazza-Chen** [kubernetes/kubeadm#332]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
        1.7.0
**Environment**:
- **Kubernetes version** (use `kubectl version`):
I've tried these two version:
          v1.6.3
          v1.7.0
- **Cloud provider or hardware configuration**:
Hardware: Raspberry Pi 3 Model B (Element14), 1GB RAM
- **OS** (e.g. from /etc/os-release):
pi-topOS: Polaris
- **Kernel** (e.g. `uname -a`):
Linux pi-top 4.4.32-v7+ #924 SMP Tue Nov 15 18:11:28 GMT 2016 armv7l GNU/Linux
- **Others**:
DOCKER_VERSION: 17.05.0-ce-rc3

## What happened?
etcd POD abnormally terminated after a few minutes executing 'kubeadm init'

etcd container name outputted by docker ps command
k8s_POD_etcd-pi-top_kube-system_13090a4a3e916f30d104eafb78de580e_0 

I found that the etcd service is down through the following command: 
`kubectl taint nodes -v99 --all node-role.kubernetes.io/master-`

>I0702 09:49:33.413003   16757 round_trippers.go:405] GET https://192.168.3.55:6443/api/v1/nodes 504 Gateway Timeout in 60002 milliseconds 

I copy the log making use of the time gap before etcd POD silently crashed. 
But frankly I can't see the root cause leading to etcd temination from the logs.
One thing deserve to be mentioned, the log file **etcd*.log** will be deleted in dir `/var/log/containers` when etcd POD terminated.
On the basis of this system behavior, I am not sure the log contains the latest records for etcd. 

Anyone can give me some suggestion to find out more valuable logs about etcd ?
(I have tried `docker logs` and `journalctl` )
`sudo cat /var/log/containers/etcd* `

> {"log":"2017-07-02 22:48:25.619435 W | etcdmain: running etcd on unsupported architecture \"arm\" since ETCD_UNSUPPORTED_ARCH is set\n","stream":"stderr","time":"2017-07-02T22:48:25.619943351Z"}
{"log":"2017-07-02 22:48:25.621174 W | flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=arm\n","stream":"stderr","time":"2017-07-02T22:48:25.621636364Z"}
{"log":"2017-07-02 22:48:25.621332 I | etcdmain: etcd Version: 3.0.17\n","stream":"stderr","time":"2017-07-02T22:48:25.621754436Z"}
{"log":"2017-07-02 22:48:25.621371 I | etcdmain: Git SHA: cc198e2\n","stream":"stderr","time":"2017-07-02T22:48:25.621786467Z"}
{"log":"2017-07-02 22:48:25.621405 I | etcdmain: Go Version: go1.7.5\n","stream":"stderr","time":"2017-07-02T22:48:25.621816779Z"}
{"log":"2017-07-02 22:48:25.621439 I | etcdmain: Go OS/Arch: linux/arm\n","stream":"stderr","time":"2017-07-02T22:48:25.621846623Z"}
{"log":"2017-07-02 22:48:25.621478 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4\n","stream":"stderr","time":"2017-07-02T22:48:25.62187704Z"}
{"log":"2017-07-02 22:48:25.623442 N | etcdmain: the server is already initialized as member before, starting as etcd member...\n","stream":"stderr","time":"2017-07-02T22:48:25.623810885Z"}
{"log":"2017-07-02 22:48:25.629687 I | etcdmain: listening for peers on http://localhost:2380\n","stream":"stderr","time":"2017-07-02T22:48:25.630212366Z"}
{"log":"2017-07-02 22:48:25.629893 I | etcdmain: listening for client requests on 127.0.0.1:2379\n","stream":"stderr","time":"2017-07-02T22:48:25.630324553Z"}
{"log":"2017-07-02 22:48:25.721024 I | etcdserver: name = default\n","stream":"stderr","time":"2017-07-02T22:48:25.721474861Z"}
{"log":"2017-07-02 22:48:25.721117 I | etcdserver: data dir = /var/lib/etcd\n","stream":"stderr","time":"2017-07-02T22:48:25.721598297Z"}
{"log":"2017-07-02 22:48:25.721157 I | etcdserver: member dir = /var/lib/etcd/member\n","stream":"stderr","time":"2017-07-02T22:48:25.721632516Z"}
{"log":"2017-07-02 22:48:25.721201 I | etcdserver: heartbeat = 100ms\n","stream":"stderr","time":"2017-07-02T22:48:25.721986733Z"}
{"log":"2017-07-02 22:48:25.721253 I | etcdserver: election = 1000ms\n","stream":"stderr","time":"2017-07-02T22:48:25.722051733Z"}
{"log":"2017-07-02 22:48:25.721288 I | etcdserver: snapshot count = 10000\n","stream":"stderr","time":"2017-07-02T22:48:25.722084024Z"}
{"log":"2017-07-02 22:48:25.721370 I | etcdserver: advertise client URLs = http://127.0.0.1:2379\n","stream":"stderr","time":"2017-07-02T22:48:25.722114701Z"}
{"log":"2017-07-02 22:48:25.885428 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 4360\n","stream":"stderr","time":"2017-07-02T22:48:25.885876913Z"}
{"log":"2017-07-02 22:48:25.886651 I | raft: 8e9e05c52164694d became follower at term 3\n","stream":"stderr","time":"2017-07-02T22:48:25.888520182Z"}
{"log":"2017-07-02 22:48:25.888198 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 3, commit: 4360, applied: 0, lastindex: 4360, lastterm: 3]\n","stream":"stderr","time":"2017-07-02T22:48:25.888584974Z"}
{"log":"2017-07-02 22:48:25.977125 I | etcdserver: starting server... [version: 3.0.17, cluster version: to_be_decided]\n","stream":"stderr","time":"2017-07-02T22:48:25.977568677Z"}
{"log":"2017-07-02 22:48:25.980167 I | membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32\n","stream":"stderr","time":"2017-07-02T22:48:25.980506059Z"}
{"log":"2017-07-02 22:48:25.981146 N | membership: set the initial cluster version to 3.0\n","stream":"stderr","time":"2017-07-02T22:48:25.981432722Z"}
{"log":"2017-07-02 22:48:25.981588 I | api: enabled capabilities for version 3.0\n","stream":"stderr","time":"2017-07-02T22:48:25.981789283Z"}
{"log":"2017-07-02 22:48:26.695111 I | raft: 8e9e05c52164694d is starting a new election at term 3\n","stream":"stderr","time":"2017-07-02T22:48:26.695502547Z"}
{"log":"2017-07-02 22:48:26.695258 I | raft: 8e9e05c52164694d became candidate at term 4\n","stream":"stderr","time":"2017-07-02T22:48:26.695629057Z"}
{"log":"2017-07-02 22:48:26.695306 I | raft: 8e9e05c52164694d received vote from 8e9e05c52164694d at term 4\n","stream":"stderr","time":"2017-07-02T22:48:26.695670827Z"}
{"log":"2017-07-02 22:48:26.695426 I | raft: 8e9e05c52164694d became leader at term 4\n","stream":"stderr","time":"2017-07-02T22:48:26.695750254Z"}
{"log":"2017-07-02 22:48:26.695489 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 4\n","stream":"stderr","time":"2017-07-02T22:48:26.695787337Z"}
{"log":"2017-07-02 22:48:26.702829 I | etcdmain: ready to serve client requests\n","stream":"stderr","time":"2017-07-02T22:48:26.703491156Z"}
{"log":"2017-07-02 22:48:26.703339 I | etcdserver: published {Name:default ClientURLs:[http://127.0.0.1:2379]} to cluster cdf818194e3a8c32\n","stream":"stderr","time":"2017-07-02T22:48:26.703615686Z"}
{"log":"2017-07-02 22:48:26.704714 N | etcdmain: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!\n","stream":"stderr","time":"2017-07-02T22:48:26.708065197Z"}
{"log":"2017-07-02 22:48:32.635844 W | wal: sync duration of 4.740227417s, expected less than 1s\n","stream":"stderr","time":"2017-07-02T22:48:32.636795142Z"}
{"log":"2017-07-02 22:49:00.118836 W | etcdserver: apply entries took too long [341.54613ms for 9 entries]\n","stream":"stderr","time":"2017-07-02T22:49:00.119202822Z"}
{"log":"2017-07-02 22:49:00.118919 W | etcdserver: avoid queries with large range/delete range!\n","stream":"stderr","time":"2017-07-02T22:49:00.119336259Z"}
{"log":"2017-07-02 22:49:00.955601 W | etcdserver: apply entries took too long [303.343286ms for 3 entries]\n","stream":"stderr","time":"2017-07-02T22:49:00.966590833Z"}
{"log":"2017-07-02 22:49:00.955703 W | etcdserver: avoid queries with large range/delete range!\n","stream":"stderr","time":"2017-07-02T22:49:01.248847498Z"}
{"log":"2017-07-02 22:49:01.328136 W | etcdserver: apply entries took too long [16.27055ms for 1 entries]\n","stream":"stderr","time":"2017-07-02T22:49:01.331199773Z"}
{"log":"2017-07-02 22:49:01.332326 W | etcdserver: avoid queries with large range/delete range!\n","stream":"stderr","time":"2017-07-02T22:49:01.332809974Z"}

## What you expected to happen?
If Kubernetes cluster successfully initialized, there should be 11 containers running in master node OS
(including network provider containers)
`sudo docker ps`

CONTAINER ID        IMAGE                                                  COMMAND                  CREATED              STATUS              PORTS               NAMES
- 99fa71fbdd62        gcr.io/google_containers/pause-arm:3.0                 "/pause"                 34 seconds ago       Up 32 seconds                           k8s_POD_kube-flannel-ds-wwzh3_kube-system_da3a98b9-5f28-11e7-824a-b827ebfe0863_0
- 9db379afe477        gcr.io/google_containers/kube-proxy-arm                "/usr/local/bin/ku..."   About a minute ago   Up About a minute                       k8s_kube-proxy_kube-proxy-3fjjz_kube-system_ab4bd3ed-5f28-11e7-824a-b827ebfe0863_0
- 743542c938cf        gcr.io/google_containers/pause-arm:3.0                 "/pause"                 About a minute ago   Up About a minute                       k8s_POD_kube-proxy-3fjjz_kube-system_ab4bd3ed-5f28-11e7-824a-b827ebfe0863_0
- 02eafaef36dd        gcr.io/google_containers/etcd-arm                      "etcd --advertise-..."   2 minutes ago        Up 2 minutes                            k8s_etcd_etcd-pi-top_kube-system_4e1ffaca3c7c5d6537ae511c34388951_0
- 3fe8697e6598        gcr.io/google_containers/kube-controller-manager-arm   "kube-controller-m..."   2 minutes ago        Up 2 minutes                            k8s_kube-controller-manager_kube-controller-manager-pi-top_kube-system_d031d914fc42952b48a082363a0dc879_0
- 0a15c649e59f        gcr.io/google_containers/kube-apiserver-arm            "kube-apiserver --..."   2 minutes ago        Up 2 minutes                            k8s_kube-apiserver_kube-apiserver-pi-top_kube-system_e9caab8da78a0abe186ac2c3d10125a5_0
- 79396fca6e17        gcr.io/google_containers/kube-scheduler-arm            "kube-scheduler --..."   2 minutes ago        Up 2 minutes                            k8s_kube-scheduler_kube-scheduler-pi-top_kube-system_a70735dad8efb6666df83eddff227ed3_0
- 13d1601d8814        gcr.io/google_containers/pause-arm:3.0                 "/pause"                 2 minutes ago        Up 2 minutes                            k8s_POD_etcd-pi-top_kube-system_4e1ffaca3c7c5d6537ae511c34388951_0
- e4fd181894fa        gcr.io/google_containers/pause-arm:3.0                 "/pause"                 2 minutes ago        Up 2 minutes                            k8s_POD_kube-apiserver-pi-top_kube-system_e9caab8da78a0abe186ac2c3d10125a5_0
- 0b7ab79ec6a7        gcr.io/google_containers/pause-arm:3.0                 "/pause"                 2 minutes ago        Up 2 minutes                            k8s_POD_kube-scheduler-pi-top_kube-system_a70735dad8efb6666df83eddff227ed3_0
- 2c0b577695dd        gcr.io/google_containers/pause-arm:3.0                 "/pause"                 2 minutes ago        Up 2 minutes                            k8s_POD_kube-controller-manager-pi-top_kube-system_d031d914fc42952b48a082363a0dc879_0

`kubectl get no`
NAME      STATUS    AGE       VERSION
pi-top    Ready     4m        v1.7.0

## How to reproduce it (as minimally and precisely as possible)?
You need a pi-topOS, it is a commerical product bundled with Pi hardware.
But I think pi-topOS has the same base as Raspbian OS.
Then install docker version 17.05.0-ce-rc3

## Anything else we need to know?
When I run the command `sudo kubeadm init --kubernetes-version v1.6.3 --apiserver-advertise-address 192.168.3.55 --pod-network-cidr=10.244.0.0/16`
kubeadm output the following warning:
> [preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.05.0-ce-rc3. Max validated version: 1.12

Maybe I should try version 1.12~

ARM & ARM64 are under unstable and experimental
[etcd Supported platforms](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/supported-platform.md)

**Comment by luxas** [comment]
I'd guess the SD card is too slow for etcd or something like that

**Comment by luxas** [comment]
yes, that is the right way to approach the problem (and probably upgrading the SD card)
