### ISSUE TITLE
Kubeadm upgrade quietly disregards the previous customizations

### ISSUE THREAD

**Issue by farcaller** [kubernetes/kubeadm#333]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): `kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: bare metal / kvm
- **OS** (e.g. from /etc/os-release): ubuntu 16.10
- **Kernel** (e.g. `uname -a`): 4.10.0-22-generic
- **Others**:

## What happened?

`kubeadm init --skip-preflight-checks --kubernetes-version v1.7.0` upgraded the cluster from 1.6.6 to 1.7, but quietly ignored custom cluster setup, specifically, `--service-cidr xxx` that was used to rollout the 1.6.6 cluster. As I later noted by examining apiserver logs:

```
kube-apiserver-kube-master-1 kube-apiserver E0703 13:49:59.897588       6 repair.go:160] the cluster IP 10.200.120.28 for service kube-prometheus-exporter-node/kube-prometheus is not within the service CIDR 10.96.0.0/12; please recreate
```

## What you expected to happen?

Kubeadm re-uses the customizations from the previous init run or fails the rollout altogether.

## How to reproduce it (as minimally and precisely as possible)?

Install 1.6 cluster with kubeadm 1.6 and a custom `--service-cidr`. Upgrade to 1.7.

**Comment by luxas** [comment]
You must pass the same arguments to init the second time as you did the first time. I'll make that clearer in the documentation.

**Comment by luxas** [comment]
This is now documented
