### ISSUE TITLE
Improper Master Endpoint Formation When Using IPv6

### ISSUE THREAD

**Issue by danehans** [kubernetes/kubeadm#334]
kubeadm uses ip:port to create a master endpoint url. This works fine when using an ipv4 address but not for ipv6. According to [rfc 3386](https://www.ietf.org/rfc/rfc3986.txt), an ipv6 address should be encased in brackets when being joined by a port using a colon.

/area kubeadm
/area ipv6

**Comment by luxas** [comment]
This was fixed with https://github.com/kubernetes/kubernetes/pull/48228 I think
@danehans reopen if not :)
