### ISSUE TITLE
Make the kubeadm API group self-explainatory by adding comments to all fields

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#336]
And structs, and in the files in general.

Sub-task of https://github.com/kubernetes/kubeadm/issues/117

**Comment by luxas** [comment]
Moving this to v1.9, where a holistic pass on refreshing the API and making v1alpha2 and/or v1beta1 API groups is planned

**Comment by kargakis** [comment]
I will take a look

/assign
