### ISSUE TITLE
Make kubeadm able to consume CI images

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#337]
Now that https://github.com/kubernetes/test-infra/issues/1400 is implemented, we can go on and make it possible to do

```
$ kubeadm init --kubernetes-version master
```
or
```
$ kubeadm init --kubernetes-version HEAD
```
or
```
$ kubeadm init --kubernetes-version ci/latest
```
or
```
$ kubeadm init --kubernetes-version latest-ci
```

What do people prefer?
What would basically happen is that the repository prefix would automatically get adjusted to `gcr.io/kubernetes-ci-images` and the latest available tag would be fetched like this (pseudo-code):
```
$ curl -sSL dl.k8s.io/ci-cross/latest.txt
v1.8.0-alpha.1.608+992002689e3c54
```
Then kubeadm will go on and use those images super easily :tada:

This will unblock https://github.com/kubernetes/kubeadm/issues/238

**Comment by zilman** [comment]
That's awesome. I think it should be possible to override the repository prefix.

**Comment by luxas** [comment]
@zilman It has been possible to override repository prefix since v1.5-ish, but it hasn't been well documented other than on the kubeadm reference docs on the site. It has been possible using the environment variable `KUBE_REPO_PREFIX`. However, that's being moved to the API in v1.8, ref: #326 

However, being able to consume the latest CI builds automatically is exciting as well!

**Comment by ixdy** [comment]
`cluster/get-kube.sh` and `kubetest` use the `ci/latest` (or `ci/latest-1.7`, etc) form, so that seems most consistent with existing tooling.

**Comment by luxas** [comment]
@andrewrynhard volunteered to contribute this :tada:
Ask if you need anything

**Comment by kad** [comment]
consistency is a key. if we have "latest", "latest-1.7" and so on for releases, same should be for "ci/".

**Comment by kad** [comment]
@luxas @andrewrynhard if you don't mind, I'll take that issue, I have some early days drafts for it.

**Comment by andrewrynhard** [comment]
@kad Don't mind at all.

**Comment by luxas** [comment]
Great to have this issue closed, thanks @kad!
