### ISSUE TITLE
External etcd options are not validated

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#342]
Well, the title says it all. You can put whatever you like there but kubeadm won't catch wrong args but happily proceed until something hangs in between.

**Comment by CaptTofu** [comment]
I'll gladly take on this.

**Comment by luxas** [comment]
Thanks @CaptTofu, just reach out to me if you need any help :)

**Comment by luxas** [comment]
Moving this out of the v1.8 milestone

**Comment by medinatiger** [comment]
Hi @CaptTofu, did u get a chance to look at those issue? If you plan to work on this issue, please assign it to yourself. Otherwise, I will take it:-)

**Comment by luxas** [comment]
Good first PR in https://github.com/kubernetes/kubernetes/pull/53352, but we still need to validate these values in the API validation here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/validation/validation.go
