### ISSUE TITLE
`kubeadm init` should default to a finite token TTL

### ISSUE THREAD

**Issue by mattmoyer** [kubernetes/kubeadm#343]
## Versions

**kubeadm version** (use `kubeadm version`): <= 1.7

## What happened?
`kubeadm init` created a default token with infinite TTL.

## What you expected to happen?
`kubeadm` creates a token with limited (2 hour?) TTL by default

## How to reproduce it (as minimally and precisely as possible)?
Run `kubeadm init` without specifying the `--token-ttl` parameter.

## Anything else we need to know?
This was discussed in SIG-cluster-lifecycle earlier today. It should be a trivial fix if we agree on the new default.

cc @jbeda @luxas

**Comment by luxas** [comment]
I think we should do this, set it to something reasonable (maybe 24 h), and cherrypick a warning into v1.7 kubeadm init that "Unlimited is the default token duration now, it will be xxx in v1.8"

**Comment by luxas** [comment]
Fixed with https://github.com/kubernetes/kubernetes/issues/48783 :tada:
