### ISSUE TITLE
kubernetes-version

### ISSUE THREAD

**Issue by adiri** [kubernetes/kubeadm#357]
OS: Ubuntu 16.04.2

kubeadm will always install 1.7.1 even if it wills state 1.7.2 during the install process. 

selecting stable-1.6 which should install 1.6.7 will also install 1.7.1

**Comment by luxas** [comment]
@adiri Can you explain what you mean?
Versions when doing `kubeadm init --kubernetes-version` are wrong or when doing `apt-get install`?

**Comment by adiri** [comment]
Sure! doring kubeadm init it will state the current version intended to install:

```
root@ip-nnn-nnn-nnn-nnn:~$ kubeadm init
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.7.2
[init] Using Authorization modes: [Node RBAC]
....
```

While after the install process is complete, it will show 1.7.1 was installed:

```
$ kubectl get nodes

NAME              STATUS     AGE       VERSION
ip-nnn-nnn-nnn-nnn   Ready      8h        v1.7.1
```

Same for the slaves. if I'll use --kubernetes-version stable-1.6 with kubeadm, it will me that its installing 1.6.7 but again it will install 1.7.1.

**Comment by luxas** [comment]
@adiri `--kubernetes-version` controls the _control plane_ version. If you run `kubectl version`, `Server version` will show the expected value. Upgrading the node agents (with `apt-get install kubelet=version`) is up to you.
