### ISSUE TITLE
Kubernetes route

### ISSUE THREAD

**Issue by nat9999** [kubernetes/kubeadm#358]
I want to configure the interface of master node and slave node. After running the master node and joining slave node, master shows:

```
vagrant@kube4local:~$ sudo kubectl get nodes
NAME         STATUS    AGE       VERSION
kube4local   Ready     6m        v1.7.1
```
Why is my slave node is not added in cluster ? I tried to change the interface, but still it does not help.

ip route master:

```
vagrant@kube4local:~$ ip r
default via 192.168.56.104 dev enp0s8
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
10.32.0.0/12 dev weave  proto kernel  scope link  src 10.32.0.1
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
192.168.56.0/24 dev enp0s8  proto kernel  scope link  src 192.168.56.104
```
ip route slave:

```
vagrant@kube5local:~$ ip r
default via 192.168.56.105 dev enp0s8
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
192.168.56.0/24 dev enp0s8  proto kernel  scope link  src 192.168.56.105
```

**Comment by luxas** [comment]
Can you give the output of `journalctl -xeu kubelet` please?

**Comment by nat9999** [comment]
@luxas After the reboot vm`s slave node was added in cluster, but in status
```
vagrant@kube4local:~$ sudo kubectl get nodes
NAME         STATUS     AGE       VERSION
kube4local   Ready      1h        v1.7.1
kube5local   NotReady   8m        v1.7.1
```
And route interface master:
```
vagrant@kube4local:~$ ip r
default via 10.0.2.2 dev enp0s3
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
10.32.0.0/12 dev weave  proto kernel  scope link  src 10.32.0.1
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
192.168.56.0/24 dev enp0s8  proto kernel  scope link  src 192.168.56.104
```
slave:
```
vagrant@kube5local:~$ ip r
default via 10.0.2.2 dev enp0s3
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
192.168.56.0/24 dev enp0s8  proto kernel  scope link  src 192.168.56.105
```
Output of journalctl -xeu kubelet 
[1.zip](https://github.com/kubernetes/kubeadm/files/1173763/1.zip)

attached

**Comment by luxas** [comment]
The zip file you attached seems like the kubelet logs from the master, but I need to see the worker's logs.
Sorry for not being clear about that

**Comment by nat9999** [comment]
@luxas I do not see the logs. On the master they are in /var/log/containers/. I think the problem is in routing, but I can`t properly configure.

**Comment by jamiehannaford** [comment]
@nat9999 If the worker node successfully registered with the master (it shows up when you run `kubectl get nodes`), that indicates networking must be working on some level. What happens when you run `kubectl describe` on the node that's not ready?

**Comment by luxas** [comment]
I don't think this is an issue with kubeadm itself,  at least not anymore.
@nat9999 Please reopen this issue if you can provide more information about the failure with the latest kubeadm v1.8.
Thank you!
