### ISSUE TITLE
DNS lookup problem

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubeadm#359]
## Versions

**kubeadm version**:
```
kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version**
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
Linux m4c45 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

## What happened?

Sometimes if you receive big size response from dns,  you can get this errors:

If you have search domain in /etc/resolv.conf, and if it can be resolved (eg. wildcard *.mydomain.tld in dns):
```bash
# kubeadm init
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
unable to get URL "https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt: x509: certificate has expired or is not yet valid
```

If you have no resolvable search domain in /etc/resolv.conf:
```bash
# kubeadm init
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
unable to get URL "https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.7.txt: dial tcp: lookup storage.googleapis.com on 10.36.1.10:53: read udp 10.36.128.180:40844->10.36.1.10:53: i/o timeout
```

## What you expected to happen?

That Installation will be continued.

## How to reproduce it (as minimally and precisely as possible)?

Please read https://github.com/golang/go/issues/21160

## Anything else we need to know?

Conneted: https://github.com/golang/go/issues/21160

**Comment by jamiehannaford** [comment]
@kvaps Because this relates to a potential bug in go's internal DNS resolver, I'm not sure what kubeadm can do here. I don't think it's sensible for us to continually retry runtime errors from the language. IMO it's a fatal error that needs to be resolved externally (i.e. by flushing your DNS server). What do you think?

**Comment by kvaps** [comment]
I think this issue more for information than for doing something here.
If someone has same problem than me, he can find this issue.
So I'll close it, thank you.
