### ISSUE TITLE
The discovery interface in the API needs to be refactored

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#36]
_From @mikedanese on October 18, 2016 22:47_

The token discovery interface is not properly factored to extend to the other two discovery methods. Discovery should return a kubeconfig. TLS bootstrap should accept a kubeconfig. The internals of the token discovery should be hidden.

cc @dgoodwin @kubernetes/sig-cluster-lifecycle 

_Copied from original issue: kubernetes/kubernetes#35073_

**Comment by mikedanese** [comment]
_From @luxas on October 24, 2016 15:53_

@dgoodwin can I assign this issue to you?

**Comment by mikedanese** [comment]
_From @dgoodwin on October 24, 2016 19:22_

Sure I have some notes from @mikedanese on how to approach (ComponentConfig is new to me), Mike yell fast and loud if you started on this, otherwise I will try to find some time to dig in.

**Comment by mikedanese** [comment]
_From @luxas on October 24, 2016 19:26_

It's not different from any other structs; just code normally :)

**Comment by mikedanese** [comment]
I'm going to start looking at this.

**Comment by mikedanese** [comment]
_From @dgoodwin on November 9, 2016 13:36_

Thanks Mike, apologies I haven't been able to get anywhere close to starting it.

**Comment by mikedanese** [comment]
No worries :+1:

**Comment by luxas** [comment]
The PR is here: https://github.com/kubernetes/kubernetes/pull/36462
