### ISSUE TITLE
Build kubeadm for Windows Server

### ISSUE THREAD

**Issue by Techwolfy** [kubernetes/kubeadm#364]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): `kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2",
GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean",
BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: Hyper-V and bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS, Windows Server 2016
- **Kernel** (e.g. `uname -a`): `4.4.0-87-generic`
- **Others**: N/A

## What happened?

The documentation indicates that `kubeadm` is the recommended tool to use for creating a new Kubernetes cluster, and it seems to be working fine on Linux despite the beta warnings. However, there isn't currently a Windows build for the tool, so I can't connect Windows nodes to the cluster. It seems like this should be possible if I write a script to run the join steps of https://kubernetes.io/docs/admin/kubeadm/, but it would be a lot easier (and far more user-friendly) if I could use `kubeadm join` on Windows as well.

Ideally `kubeadm` will become entirely cross-platform in the future, but as Windows control planes aren't supported yet that will likely take a lot more work.

**Comment by luxas** [comment]
cc @kubernetes/sig-release-feature-requests 
Technically there is nothing stopping us from building kubeadm on Windows I think, and I'm 99.99% sure the join flow works on Windows. Only hard part is running kubelet with the right args and deploying a CNI network plugin that works both on Windows and Linux.

**Comment by luxas** [comment]
cc @kubernetes/sig-windows-feature-requests

**Comment by luxas** [comment]
Talked to @michmike about this, and we're not gonna do this for v1.8
Instead we're gonna look into deeper integration possibilities for v1.9
