### ISSUE TITLE
Hostname not being detected

### ISSUE THREAD

**Issue by hickey** [kubernetes/kubeadm#366]
## Is this a request for help?

A bit. Need to determine how the hostname is being derived. 

## What keywords did you search in kubeadm issues before filing this one?

hostname

Figured that it is related to #135, but I could not fully track down the code. I was able to narrow down to kubernetes/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go, but not sure what is calling that code to generate the error message. 

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version**: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: AWS on a t2.large
- **OS**: Debian GNU/Linux 8 (jessie)
- **Kernel**: Linux kube-4248 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux 
- **Others**:

## What happened?

```
admin@kube-4248:~$ sudo kubeadm join --token 7c21af.ae6a7b5c6623f93d 10.24.6.11:6443
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] WARNING: docker version is greater than the most recently validated version. Docker version: 17.03.1-ce. Max validated version: 1.12
[preflight] WARNING: hostname "" could not be reached
[preflight] WARNING: hostname "" lookup : no such host
[preflight] Some fatal errors occurred:
        hostname "" a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
[preflight] If you know what you are doing, you can skip pre-flight checks with `--skip-preflight-checks`
admin@kube-4248:~$ hostname
kube-4248
admin@kube-4248:~$ hostname --fqdn
kube-4248.colossus.smartsheet.com
```

As you can see it appears that during the execution of kubeadm the hostname could not be determined. Yet hostname is known by the OS. I believe that Python uses libc to get the system hostname and that seems to be working. 

```
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostname()
'kube-4248'
```

## What you expected to happen?

Completion of kubeadm. At this point the host is not registered in DNS and looking at the validation.go I have to infer that hostname is being collected by a DNS query on the IP. 

## How to reproduce it (as minimally and precisely as possible)?

In building a cluster I write the hostname (not the AWS generated hostname) to /etc/hostname in the user data script. This hostname is the name that will eventually be created in DNS, but is not in DNS at the time of provisioning. 

## Anything else we need to know?

Again making the assumption that this is due to not having the host registered in DNS. Would like to confirm if this is the possible reason. 

Maybe there should be another switch added (i.e. --skip-hostname-checks) so that the hostname does not trigger a failure of the preflight checks. It is still very desirable to have the preflight checks abort the execution if it finds something anomalous. Kubeadm will eventually be put into provision automation so I would rather not skip  the majority of the preflight checks.

**Comment by hickey** [comment]
I should have added that the execution of kubeadm on the master was just fine. Same OS and configured the same as the worker nodes, but it is registered in DNS.

**Comment by hickey** [comment]
After getting DNS records pushed out, the same results occur when running kubeadm. Even tried rebooting the hosts to insure that there was not any local caches causing issues.

**Comment by ejilay** [comment]
See #347

**Comment by hickey** [comment]
Yes, agree that it is the same issue. Going to close this issue and track #347.
