### ISSUE TITLE
Host knowledge sharing session about kubeadm e2e test infrastructure

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#370]
In order to help disseminate knowledge about how kubeadm e2e tests are configured, run, and have their results reported, I would like to host a knowledge sharing session over Zoom. This will be a walkthrough and demo of the different layers of test-infra and kubernetes-anywhere and hopefully largely driven by interactive questions.

This issue is to help coordinate schedules for those who would like to attend, and to link to any notes/recordings after it happens. There is a lot to cover, so it's possible that there will be follow-up sessions to cover more content.

**Comment by pipejakob** [comment]
If you're interested in attending, please mark your availability [here](https://docs.google.com/a/google.com/spreadsheets/d/13WGf0oS2jMbaLOX0GXXJ7HZL7nfW62IAMjAQrr5JySs/edit?usp=sharing). If none of the slots work for you, let me know and I'll try to add more.

**Comment by pipejakob** [comment]
It looks like Monday, August 14 @ 09:00 PST is the overwhelming winner. I'll send out an email/invite to the SIG mailing list. Thanks everyone for RSVPing!

**Comment by tamalsaha** [comment]
@pipejakob , which sig is this one?

**Comment by pipejakob** [comment]
@tamalsaha Anyone is invited to join, but since kubeadm is primarily discussed in SIG Cluster Lifecycle, that is the target audience where I just sent the invite. I'll also be covering some of the layers in `test-infra`, though, so anyone new to SIG Testing might find it useful.

All of the details for the meeting can be found in this [Google doc](https://docs.google.com/a/google.com/document/d/17KYWMfslBLvJtgi34hux5hgd38LIttaqkiAu5Y9-kEE/edit?usp=sharing). Joining the [kubernetes-sig-cluster-lifecycle](https://groups.google.com/forum/#!forum/kubernetes-sig-cluster-lifecycle) Google group should get the invite on your calendar.

**Comment by tamalsaha** [comment]
Thanks @pipejakob . I have received the invitation.

**Comment by pipejakob** [comment]
Session 2 is scheduled for Monday, August 21 @ 09:00 PST. All of the links for the Zoom meeting and notes are the same.

**Comment by shashidharatd** [comment]
@pipejakob, is there a recording of the first session?. I missed it :(. now i am putting a meeting reminder.

**Comment by shashidharatd** [comment]
Got the recording link from the doc. Thanks !

**Comment by luxas** [comment]
@shashidharatd I'm glad you found the link to the video. See you next time :)

**Comment by pipejakob** [comment]
Apologies for the late notice, but I just realized that I foolishly scheduled the next session on the day of the first coast-to-coast total solar eclipse in North America in 99 years. What's more, I even scheduled the meeting in the middle of the eclipse itself (local time). Many people in the US are going to be enjoying something far more [interesting](https://www.ted.com/talks/david_baron_you_owe_it_to_yourself_to_experience_a_total_solar_eclipse) than our test infrastructure.

I'm pushing back the next session a week to August 28 @ 09:00 PST.

**Comment by pipejakob** [comment]
For the last session, I'm tentatively targeting September 18th @ 09:00 PST. The topics will include how to simulate kubeadm e2e test runs locally in order to develop new jobs and debug failures, how jobs are configured (prow's `config.yaml` and `jobs/config.json`), and [testgrid](https://k8s-testgrid.appspot.com/).

The session will be recorded, but if you would like to attend live and can't make that timeslot, please respond on this issue. If there are enough people, I'll start another scheduling spreadsheet to find a better slot.

**Comment by luxas** [comment]
I'm not gonna make that :(

Away that whole week because exams ;)

**Comment by pipejakob** [comment]
It sounds like the week of October 2nd would work best all around. I'll send out another availability spreadsheet to coordinate for the best time.

**Comment by luxas** [comment]
Did you send out the invite for that @pipejakob? I don't see it in my calendar...

**Comment by pipejakob** [comment]
Not yet (I was out for a large portion of last week with the flu). I'll still send out a scheduling spreadsheet, using this issue to track.

**Comment by jamiehannaford** [comment]
@pipejakob Did you end up doing this? If so, is there a recording? would like to learn about all this :)

**Comment by jamiehannaford** [comment]
Since this no longer being worked on or planned, I think we can close. WDYT @luxas @pipejakob?

**Comment by errordeveloper** [comment]
/close

@pipejakob please do feel free to re-open, if you would like to do this soon.
