### ISSUE TITLE
Make deploying the control plane self-hosted the default 

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#371]
Title says kind of everything :)

**Comment by luxas** [comment]
In https://github.com/kubernetes/kubernetes/pull/50968 there is context why we chose to not enable this by default in v1.8. It will still be available and supported at a beta level. Deferring defaulting to self-hosting in  v1.9 instead.

**Comment by calaniz** [comment]
So if I make the the api-server not start with a configuration change, how do we get back into k8s to change the configuration.  I ran into this today.  We might want to document a workaround.  We used to go into the manifests directory and fix that.

**Comment by luxas** [comment]
Bumping to v1.10

**Comment by luxas** [comment]
Bumping to v1.10. Self-hosting will be beta in v1.10 but not enabled by default

**Comment by timothysc** [comment]
I have new thoughts here which are different than before.

**Comment by timothysc** [comment]
xref #651 - closing this to rally on some later issues and I'll put-up the kep this week.
