### ISSUE TITLE
e2e-test the self-hosted mode of kubeadm

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#372]
Very important as soon as we turn on #371

**Comment by xiangpengzhao** [comment]
As per https://github.com/kubernetes/kubeadm/issues/371#issuecomment-345847109, we can bump this issue to 1.10 as well ? @luxas

**Comment by luxas** [comment]
No, we should add this test now before v1.9 is cut

**Comment by xiangpengzhao** [comment]
@luxas I didn't find where/what such a test case can be added.  This should be a new CI job, right?

**Comment by luxas** [comment]
@xiangpengzhao yes, it should be a new CI job enabling the self-hosted feature gate. Can you help out with that please?

**Comment by xiangpengzhao** [comment]
@luxas yeah sure, I will investigate the CI config and send a PR to k/test-infra.

**Comment by xiangpengzhao** [comment]
@luxas PR https://github.com/kubernetes/test-infra/pull/5904 sent.

One concern is from @krzyzacy https://github.com/kubernetes/test-infra/pull/5904#issuecomment-350962379

> >do you want to enable the feature gate for an existing kubeadm job instead?

>@krzyzacy Surely we can enable it in an existing job such as ci-kubernetes-e2e-kubeadm-gce. But I personally prefer it running as a separate job since we may want to test both the scenarios with/without the feature. @luxas WDYT?

**Comment by BenTheElder** [comment]
see also: https://github.com/kubernetes/test-infra/issues/5905, https://github.com/kubernetes/test-infra/pull/5904#discussion_r156280975

**Comment by luxas** [comment]
Thanks @xiangpengzhao for this!
