### ISSUE TITLE
Apply ValidateMixedArguments to all kubeadm commands

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#376]
[PR #43558](https://github.com/kubernetes/kubernetes/pull/49498) introduced a validation check avoiding usage of `---config` (to provide a configuration) mixed with other CLI flags for `kubeadm init` and `kubeadm join` commands.
The same implementation should be done also for any other kubeadm commands/sub-commands with `---config` flag.
NB. I'm already doing this for some `kubeadm alpha phase`s I'm working on; this issue is a reminder to check ValidateMixedArguments in the remaining parts

**Comment by luxas** [comment]
@fabriziopandini Is this now fixed for all phases?

**Comment by fabriziopandini** [comment]
Yes!
As of today MixedArguments can happen in following cases; between parenthesis you can find the PR that implemented the MixedArguments check/and or explanation of exception:
- `init` (#43558)
- `join` (#43558)
- `alpha phase certs` (#50691)
- `alpha phase controlplane` (#50302)
- `alpha phase etcd` (#50302)
- `alpha phase kubeconfig` (#50692)
- `alpha phase upload-config`(mixed arguments should be allowed by design).

Nb. There is in flight a PR that will introduce MixedArguments condition in `alpha phase self-hosting`, but the PR will implement MixedArguments check as well.

**Comment by luxas** [comment]
This was fixed by @fabriziopandini for most phases, fully fixed now that @andrewrynhard's PR https://github.com/kubernetes/kubernetes/pull/51171 merged :tada:
