### ISSUE TITLE
Kubeadm init --api-advertise-addresses stringSlice not allow nodes to join master

### ISSUE THREAD

**Issue by jianlianggao** [kubernetes/kubeadm#378]
Hi there,
My master node (CentOS7 in VBox) has host-only and NAT network interfaces. kubeadm init always chooses NAT ip address (for Internet),, which can not be connected by other nodes. If I use option --api-advertise-addresses pointing master to the host-only ip. The kubeadm join runs ok on nodes, but the "joined" nodes are not listed. The master node still shows only itself. I doubt that the other nodes  join successfully. Any help please. Many thanks.

**Comment by jamiehannaford** [comment]
@jiangyaoguo Do the kubelets on the worker nodes have the correct apiserver IP address? Can you verify their kubeconfigs?

**Comment by luxas** [comment]
@jianlianggao I think the issue might be that the kubelet isn't running successfully.
You can try to run `journalctl -xeu kubelet` to troubleshoot why your kubelets aren't joining correctly.
I'm closing this now, but please reopen if this issue can be reproduced with kubeadm v1.8

**Comment by jianlianggao** [comment]
Thank you very much Luxas
