### ISSUE TITLE
Create unit tests for uploadconfigphase

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#379]
Due to time constraints, the [uploadconfigphase](https://github.com/kubernetes/kubernetes/pull/50320) code was merged without any automated testing. It should have basic unit tests as well as idempotency tests to ensure that `kubeadm init` can still be used for [upgrades](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-7/), since that process requires that all of the phases in the init flow are idempotent.

**Comment by luxas** [comment]
As agreed, I'll take this follow up

**Comment by pipejakob** [comment]
It's possible that @medinatiger was going to pick this up as a starter task. Can you two sync up to make sure we don't duplicate the work?

**Comment by luxas** [comment]
Please do. I'm currently really over-booked with work...

Please get in touch with me if you need any advice @medinatiger :)

**Comment by medinatiger** [comment]
@luxas I will start to work on this very soon
