### ISSUE TITLE
[RFC] add prefight command for kubeadm check the sandbox image requirement

### ISSUE THREAD

**Issue by netroby** [kubernetes/kubeadm#388]
The kubeadm need some sandbox image to setup the kubernetes 

```
gcr.io/google_containers/kube-apiserver-amd64            v1.7.3              a1cc3a3d8d0d        10 days ago         186MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.7.3              d014f402b272        10 days ago         138MB
gcr.io/google_containers/kube-scheduler-amd64            v1.7.3              51967bf607d3        10 days ago         77.2MB
gcr.io/google_containers/kube-proxy-amd64                v1.7.3              54d2a8698e3c        10 days ago         115MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.4              38bac66034a6        6 weeks ago         41.8MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.4              a8e00546bcf3        6 weeks ago         49.4MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.4              f7f45b9cb733        6 weeks ago         41.4MB
gcr.io/google_containers/etcd-amd64                      3.0.17              243830dae7dd        5 months ago        169MB
gcr.io/google_containers/pause-amd64                     3.0                 99e59f495ffa        15 months ago       747kB
```

Can we add a command ```kubeadm prefight```

It will list the pre images

```
docker pull gcr.io/google_containers/kube-apiserver-amd64:v1.7.3    
docker pull gcr.io/google_containers/kube-controller-manager-amd64:v1.7.3
docker pull gcr.io/google_containers/kube-scheduler-amd64:v1.7.3
docker pull gcr.io/google_containers/kube-proxy-amd64:v1.7.3
docker pull gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.4 
docker pull gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4
docker pull gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.4
docker pull gcr.io/google_containers/etcd-amd64:3.0.17
docker pull gcr.io/google_containers/pause-amd64:3.0
```

So the user can pre download these images , prepare for kubeadm . 

If not download these images. kubeadm will not quick to set up kubernete. 

And often hang up due to network problem.

=====================================

ps: this issue imported from https://github.com/kubernetes/kubernetes/issues/50567

**Comment by jamiehannaford** [comment]
@luxas WDYT?

**Comment by luxas** [comment]
@fabriziopandini @jbeda @mattmoyer @timothysc What do you think about this?
We've dismissed the proposal some times so far, but we might be able to implement something under `kubeadm phases`?

**Comment by jamiehannaford** [comment]
We've had some users express interest in running kubeadm in envs with no connection to the public internet. Being able to list Docker images might help them prepare for that.

**Comment by bart0sh** [comment]
I'd like to work on this issue. Any objections? Any suggestions on the best way to implement this?

**Comment by timothysc** [comment]
@bart0sh - Please coordinate with @kad on your side.

**Comment by timothysc** [comment]
So I'm not really a fan of having kubeadm pull the images, but I do like the option of list images which could be piped into a docker pull command.  This seems trivial and would help with other image automation tools. 

/cc @detiber

**Comment by bart0sh** [comment]
Is it better to implement as a preflight check for kubeadm init or you can suggest better place?

**Comment by timothysc** [comment]
Having local images pulled should be the exception case and people build tooling around it, adding a configuration parameter that can be leveraged during preflight check seems ok, but I don't think it should rise to a publicly visible flag.  I do think a 1st class `kubeadm images` subcommand is generally useful but I think I'd want to discuss that with the sig.

**Comment by chuckha** [comment]
I'm going to start with `kubeadm images` for now and will bring it up in next week's sig.
