### ISSUE TITLE
Use the apps/v1beta2 group in v1.9 for DaemonSets/Deployments

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#390]
We all want to get rid of the `extensions` API group. Part of the work being done there is moving workload objects to the `apps` API group. Deployments/DaemonSets are moved to `apps/v1beta2` in v1.8

Due to our version skew policy (CLI can handle k8s that is one minor version below itself), we can always assume the `apps/v1beta2` API group exists and use it in v1.9

**Comment by sbezverk** [comment]
@luxas could you explain a little bit more the problem? As from above for a person very little familiar with kubeadm code is not clear where even start. Maybe a link to the code highlighting the problem would be really useful. Same comment goes for issue #398 ...

**Comment by luxas** [comment]
Yeah, sure.
Whereever you see `extensions/v1beta1` in the kubeadm codebase, it should probably be moved to `apps/v1beta2`... Same goes for RBAC

This is all about changing imports:

https://github.com/kubernetes/kubernetes/blob/87a1b5f6d77f1bf6a0d29e6a2aac469fcd414f2e/cmd/kubeadm/app/util/apiclient/idempotency.go#L24

There the `rbac "k8s.io/api/rbac/v1beta1"` should now be `rbac "k8s.io/api/rbac/v1"`. 
`extensions "k8s.io/api/extensions/v1beta1"` should be `apps "k8s.io/api/apps/v1beta2"`, and `client.AppsV1beta2()` should be used instead, etc.

This change should also be done in inline YAML manifests etc.

Makes sense?
