### ISSUE TITLE
kubeadm e2e jobs failing

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#392]
Our [kubeadm-gce](https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce) e2e jobs are still failing, even after @krzyzacy completed the migration to Boskos.

This could be the introduction of a legitimate bug in kubeadm/Kubernetes with unfortunate timing, or could still be another subtle problem with the Boskos migration.

This issue is to coordinate and track the progress on debugging and fixing these jobs.

**Comment by pipejakob** [comment]
Looking at the master on a recent run, it looks like kubelet is trying to run, but keeps crash-looping.

The start-up logs still show `kubeadm init` waiting for the control plane:

    Aug 15 18:14:33 ubuntu startupscript: [apiclient] Created API client, waiting for the control plane to become ready

and kubelet occasionally gets restarted with these flags:

    /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt --cadvisor-port=0

but `journalctl -u kubelet` shows this in its logs:

    Aug 15 18:16:42 e2e-5006-master systemd[1]: Started kubelet: The Kubernetes Node Agent.
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: 2017/08/15 18:16:42 proto: duplicate proto type registered: google.protobuf.Any
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: 2017/08/15 18:16:42 proto: duplicate proto type registered: google.protobuf.Duration
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: 2017/08/15 18:16:42 proto: duplicate proto type registered: google.protobuf.Timestamp
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: I0815 18:16:42.920781    6259 feature_gate.go:150] feature gates: map[]
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: I0815 18:16:42.927565    6259 client.go:74] Connecting to docker on unix:///var/run/docker.sock
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: I0815 18:16:42.927818    6259 client.go:94] Start docker client with request timeout=2m0s
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: W0815 18:16:42.934249    6259 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: I0815 18:16:42.956699    6259 feature_gate.go:150] feature gates: map[]
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: I0815 18:16:42.962594    6259 manager.go:143] cAdvisor running in container: "/system.slice/kubelet.service"
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: W0815 18:16:42.971703    6259 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockop
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: I0815 18:16:42.978198    6259 fs.go:117] Filesystem partitions: map[/dev/sda1:{mountpoint:/var/lib/docker/devicemapper major:8 minor:1 fsType:ext4 blockSize:
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: I0815 18:16:42.983866    6259 manager.go:198] Machine: {NumCores:1 CpuFrequency:2500000 MemoryCapacity:3879792640 MachineID:0eea22c8d4aa7d880d0a7df33fe26171 
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: I0815 18:16:42.986052    6259 manager.go:204] Version: {KernelVersion:4.4.0-21-generic ContainerOsVersion:Ubuntu 16.04 LTS DockerVersion:1.12.0 DockerAPIVers
    Aug 15 18:16:42 e2e-5006-master kubelet[6259]: error: failed to run Kubelet: rootDirectory "/var/lib/kubelet" does not exist
    Aug 15 18:16:42 e2e-5006-master systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
    Aug 15 18:16:42 e2e-5006-master systemd[1]: kubelet.service: Unit entered failed state.
    Aug 15 18:16:42 e2e-5006-master systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by pipejakob** [comment]
@krzyzacy It definitely seems like a legitimate bug on the master branch. I was going to do more triaging before looping in EngProd :-).

**Comment by pipejakob** [comment]
Also, my last kubelet logs were width-truncated. Here's a better copy:

    Started kubelet: The Kubernetes Node Agent.
    2017/08/15 18:31:05 proto: duplicate proto type registered: google.protobuf.Any
    2017/08/15 18:31:05 proto: duplicate proto type registered: google.protobuf.Duration
    2017/08/15 18:31:05 proto: duplicate proto type registered: google.protobuf.Timestamp
    I0815 18:31:05.934867    8446 feature_gate.go:150] feature gates: map[]
    I0815 18:31:05.942344    8446 client.go:74] Connecting to docker on unix:///var/run/docker.sock
    I0815 18:31:05.942663    8446 client.go:94] Start docker client with request timeout=2m0s
    W0815 18:31:05.950564    8446 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
    I0815 18:31:05.971235    8446 feature_gate.go:150] feature gates: map[]
    I0815 18:31:05.978363    8446 manager.go:143] cAdvisor running in container: "/system.slice/kubelet.service"
    W0815 18:31:05.988781    8446 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
    I0815 18:31:05.997885    8446 fs.go:117] Filesystem partitions: map[/dev/sda1:{mountpoint:/var/lib/docker/devicemapper major:8 minor:1 fsType:ext4 blockSize:0}]
    I0815 18:31:06.003287    8446 manager.go:198] Machine: {NumCores:1 CpuFrequency:2500000 MemoryCapacity:3879792640 MachineID:0eea22c8d4aa7d880d0a7df33fe26171 SystemUUID:0EEA22C8-D4AA-7D88-0D0A-7DF33FE26171 BootID:29662a26-e2c4-4c15-97c4-cffb6f075b44 Filesystems:[{Device:/dev/sda1 DeviceMajor:8 DeviceMinor:1 Capacity:10340831232 Type:vfs Inodes:1280000 HasInodes:true}] DiskMap:map[252:0:{Name:dm-0 Major:252 Minor:0 Size:107374182400 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:10737418240 Scheduler:noop}] NetworkDevices:[{Name:ens4 MacAddress:42:01:0a:80:00:02 Speed:0 Mtu:1460}] Topology:[{Id:0 Memory:3879792640 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-standard-1 InstanceID:175275427185461149}
    I0815 18:31:06.006022    8446 manager.go:204] Version: {KernelVersion:4.4.0-21-generic ContainerOsVersion:Ubuntu 16.04 LTS DockerVersion:1.12.0 DockerAPIVersion:1.24 CadvisorVersion: CadvisorRevision:}
    error: failed to run Kubelet: rootDirectory "/var/lib/kubelet" does not exist
    kubelet.service: Main process exited, code=exited, status=1/FAILURE
    kubelet.service: Unit entered failed state.
    kubelet.service: Failed with result 'exit-code'.

**Comment by pipejakob** [comment]
It seems like a recent change that might make kubelet require its root directory to exist before it gets run (`/var/lib/kubelet`), rather than auto-creating it. It doesn't look like our Debian packages were ever creating it manually. https://github.com/kubernetes/kubernetes/pull/48487 looks like the culprit, but I want to confirm that kubelet was auto-creating this directory before to ensure this is actually a regression.

**Comment by pipejakob** [comment]
The kubelet rootDir regression is fixed, so now our e2es are getting further. They're still red, though, and all e2es seem to pass, but the log-dump step is failing:

    W0822 21:37:47.629] 2017/08/22 21:37:47 util.go:133: Step 'make -C /workspace/kubernetes-anywhere FORCE_DESTROY=y destroy' finished in 2m38.317499299s
    W0822 21:37:48.507] 2017/08/22 21:37:48 main.go:204: Saved XML output to /workspace/k8s.io/kubernetes/_artifacts/junit_runner.xml.
    W0822 21:37:48.573] 2017/08/22 21:37:48 main.go:245: Something went wrong: encountered 1 errors: [error during ./cluster/log-dump/log-dump.sh /workspace/k8s.io/kubernetes/_artifacts: exit status 127]
    W0822 21:37:48.574] Traceback (most recent call last):
    W0822 21:37:48.574]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 682, in <module>
    W0822 21:37:48.607]     main(parse_args())
    W0822 21:37:48.608]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 545, in main
    W0822 21:37:48.608]     mode.start(runner_args)
    W0822 21:37:48.608]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 223, in start
    W0822 21:37:48.609]     check_env(env, self.command, *args)
    W0822 21:37:48.609]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 62, in check_env
    W0822 21:37:48.609]     subprocess.check_call(cmd, env=env)
    W0822 21:37:48.610]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    W0822 21:37:48.628]     raise CalledProcessError(retcode, cmd)
    W0822 21:37:48.628] subprocess.CalledProcessError: Command '('kubetest', '-v', '--dump=/workspace/k8s.io/kubernetes/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--cluster=e2e-5157', '--gcp-network=e2e-5157', '--deployment=kubernetes-anywhere', '--extract=ci/latest', '--gcp-zone=us-central1-f', '--kubernetes-anywhere-kubernetes-version=latest', '--provider=kubernetes-anywhere', '--test_args=--ginkgo.focus=\\[Conformance\\]|\\[Feature:BootstrapTokens\\]|\\[Feature:NodeAuthorizer\\] --minStartupPods=8', '--timeout=300m', '--kubernetes-anywhere-path=/workspace/kubernetes-anywhere', '--kubernetes-anywhere-phase2-provider=kubeadm', '--kubernetes-anywhere-cluster=e2e-5157', '--kubernetes-anywhere-kubeadm-version=gs://kubernetes-release-dev/bazel/v1.8.0-alpha.2.2264+336e38bd4d8692/bin/linux/amd64/')' returned non-zero exit status 1
    E0822 21:37:48.633] Command failed
    I0822 21:37:48.633] process 288 exited with code 1 after 72.2m
    E0822 21:37:48.633] FAIL: ci-kubernetes-e2e-kubeadm-gce

I know there were recent changes in this area, so I'll track down the author and follow up.

**Comment by krzyzacy** [comment]
@shyamjvs I thought you added more logs around the dump script? Or this is busted before the first log?

**Comment by pipejakob** [comment]
You can also see recent job runs of kubeadm-gce here for the full logs:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce

**Comment by shyamjvs** [comment]
@krzyzacy Yes, I added more logs (but in release-1.7 branch only) and none of them got printed. Seems like it didn't even enter the script. Explained here - https://github.com/kubernetes/kubernetes/issues/50760#issuecomment-324172585

**Comment by luxas** [comment]
@pipejakob Let's close this and track the remaining DumpClusterLogs in https://github.com/kubernetes/kubernetes/issues/50760 to avoid information sprawl.

Reopen if you don't agree.
