### ISSUE TITLE
RFE: Add support uninterruptible priority on control plane pods once prio+preemption is enabled. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#395]
This is a placeholder for 1.9+ to mark control plane pods as uninterruptible, to force the hosting kubelet to always kill other components 1st.  

There exists edge cases today with the critical components annotation.

**Comment by jamiehannaford** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/47604

**Comment by luxas** [comment]
ref: https://github.com/kubernetes/features/issues/268 & https://github.com/kubernetes/kubernetes/issues/47604, not gonna make it to beta in v1.9, bumping

**Comment by bsalamat** [comment]
Our plan is to use `system-node-critical` or `system-cluster-critical` priority for control plane pods. These priorities are highest in the system and no user defined priority can be higher. These priorities ensure that control plane pods are never evicted by kubelet IF they do not exceed their requested resources.
The priorities guarantee that these pods are never preempted.

cc: @dashpole

**Comment by timothysc** [comment]
cc: @chuckha

**Comment by timothysc** [comment]
Notes: We will need to apply the kubelet flags to all nodes, due to support for the proxy.

**Comment by bsalamat** [comment]
cc: @ravisantoshgudimetla

**Comment by timothysc** [comment]
@bsalamat what is the plan for beta?

**Comment by bsalamat** [comment]
@timothysc The plan is to go to Beta in 1.11.

**Comment by timothysc** [comment]
@bsalamat Please poke when it's official and we'll enable.

**Comment by bsalamat** [comment]
We have added PriorityClassName in kubernetes/kubernetes#59237 to a few of our system critical pods. We added those in 1.10. I am not sure if kubeadm uses those yaml files though.
