### ISSUE TITLE
Revisit dry-run implementation options

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#399]
Action item from https://github.com/kubernetes/kubernetes/pull/50631
We should investigate what other approaches might work for dry-running in kubeadm.

Requirements:
 - Whatever object is returned/used; it should implement `clientset.Interface`
 - No modifications should be applied, but instead logged and exit cleanly
 - GETs/LISTs might in some cases be faked (for instance for `kubeadm init`, where no real API server is available) or proxied to a real API server (for `kubeadm token`, `kubeadm upgrade` etc. => acts on real data, which makes it useful)

cc @kubernetes/sig-api-machinery-feature-requests @ncdc @caesarxuchao Is something like this already available, or do we have to go with what I wrote in that PR?

@sttts also noted that the stability of the faked clientset _might_ be suboptimal in the future if something changes drastically...

cc @timothysc

**Comment by ncdc** [comment]
I'm not aware of anything pre-baked for this

**Comment by luxas** [comment]
@ncdc Thanks for confirming. Does this sound like a sane approach longer-term to you to do this (implemented in https://github.com/kubernetes/kubernetes/pull/50631):
 - Use the fake clientset in `client-go/kubernetes/fake` for prereq 1
 - Add a global reactor (resource: `*`, verb: `*`) that logs everything (and outputs attached objects from the caller if present, like the object on `update/create` and the patch on `patch`, etc) for prereq 2
 - Add reactors for all modification verbs and just `return true, nil, nil`(or the attached object if present) for prereq 2
 - Forward all GETs/LISTs to an interface object, which has currently two implementations:
    - An impl for getting `kubeadm init` off the ground for prereq 3
    - An impl that forwards the requests to the "real" backing API server using the dynamic client in `client-go/dynamic` for prereq 3

Anything we can do better here in a way that doesn't consume way too much code (like generating a whole new clientset)? Thanks

**Comment by ncdc** [comment]
It sounds reasonable to me. I'm curious to know what @sttts had in mind re possible suboptimal issues.

For the forwarding bullet, maybe instead of having two separate implementations, it would be nice if we could come up with some functions similar to the `PrependReactor`/`AppendReactor` approach where we could control what was handled, what the fallbacks are (e.g. fall back to the dynamic client for get/list). I'm not sure exactly how to construct it based on your requirements, but I think I would find that cleaner.

**Comment by luxas** [comment]
> I'm curious to know what @sttts had in mind re possible suboptimal issues.

It was about future development of the fake clientset. Just to watch it isn't developed in a way that is incompatible with this flow. That is, now works; with a future refactor, who knows?

**Comment by sttts** [comment]
> It sounds reasonable to me. I'm curious to know what @sttts had in mind re possible suboptimal issues.

My concern is/was that those fake clients are expected to run in tests and therefore might be changed in ways which are incompatible with non-test usage. E.g. we could add clever logging to them which is unacceptable in kubeadm.

One thing I remember is that we do not know whether types are namespaced inside fake client or something in this direction (some PR from @DirectXMan12 or me a handful of months ago?). So we have code in them which is mostly correct, but not 100%, but good enough for tests.

**Comment by DirectXMan12** [comment]
> One thing I remember is that we do not know whether types are namespaced inside fake client or something in this direction

I vaguely recall that, I think we fixed it when I submitted all those PRs for getting metrics clients working.

> So we have code in them which is mostly correct, but not 100%, but good enough for tests.

Yeah, in my experience there's some amount of code in the fake clients that works pretty well for tests, but occasionally behaves in a confusing or non-standard way.  It's not unworkable, but it worth making sure they actually behave how you'd expect (e.g. they do label filtering for you in a few places, so if you don't set the properly labels, they'll filter out everything you return).

**Comment by neolit123** [comment]
dry run for `init` seems to be in a good shape and i don't think we have seen complains about this (from devs or users): https://github.com/kubernetes/kubernetes/pull/50631#pullrequestreview-57296249.

on another note, we found that `join` has no dry run and added it recent version. it behaves similarly:
https://github.com/kubernetes/kubeadm/issues/2505

from my POV the current implementation works fine.
if we see issues with it in the future we can cross reference to this and prior discussions.
