### ISSUE TITLE
Use the Downward API's PodIP field for selfhosted API Server's advertise address

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#400]
In order to support multiple masters, the `--advertise-address` value must be unique per-apiserver.
We should use the Downward API to achieve that automatically (using the `.podIP` field).

The only downside here is that we kind of lose the configurability of that value that we've had so far.
It's not critical for v1.8 per-se, but if we want to have this in v1.9, it's best to do this for v1.8 so we don't have to perform a lot of hacks later in the v1.8->v1.9 upgrade process...

cc @timothysc @moyer @mikedanese WDYT? Should we do this right now? I can send a PR easily in that case...

**Comment by luxas** [comment]
Moving this to v1.9 to minimize the risk of merging something like this in this point in the cycle.
This is only useful for HA in any case anyway...

**Comment by andrewsykim** [comment]
@luxas this seems like a good starting issuing to get some of the HA work rolling. I can look into this one soon :).

**Comment by luxas** [comment]
@andrewsykim Any update on this?

**Comment by andrewsykim** [comment]
Will try to schedule this in for this weekend. Haven't started any work here though so if anyone else is interested feel free to assign them :)

**Comment by xiangpengzhao** [comment]
ping :)

**Comment by andrewsykim** [comment]
@luxas @xiangpengzhao here it is https://github.com/kubernetes/kubernetes/pull/56084, sorry it took so long, haven't had too much time lately to work on Kubernetes, should have more time during holidays :)

**Comment by timothysc** [comment]
Closing this issue, it should be complete.
