### ISSUE TITLE
Review and improve the kubeadm UX further

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#407]
As @timothysc noted in https://github.com/kubernetes/kubernetes/pull/50967; we should soon-ish start to have more conversations generally on the kubeadm UX and how we can improve it further

Currently, all the UX discussion happens in PR reviews or in a design doc like the upgrade one.
We should maybe just play with kubeadm a little and review all text that is outputted and see what we think.

**Comment by timothysc** [comment]
I'm going to close this one b/c there a bunch of other similar issues that exist touching on logging level and terminology.
