### ISSUE TITLE
Running out-of-tree cloud controller with kubeadm

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubeadm#408]
Hi, I am trying to use my custom out-of-tree cloud provider with Kubernetes. I am able to run it thanks to help from @luxas . But I noticed that kubelet calls apis like `NodeAddressByProviderID()` with empty `providerID` for `external` cloud provider. Digging in the code for 1.7 branch, I see that `Kubelet.Cloud` is null for `external` cloud-providers. As a result `GetInstanceProviderID(..)` returns empty string.

My questions are:
- What features are lacking from out-of-tree cloud providers as a result of this?
- Is this intentional or a tempary thing that will be fixed in future?

**Comment by errordeveloper** [comment]
xref https://github.com/kubernetes/features/issues/88

**Comment by tamalsaha** [comment]
Found a duplicate https://github.com/kubernetes/kubernetes/issues/49836

**Comment by luxas** [comment]
@tamalsaha Bug/limitation in the CCM. Will be fixed for sure.
