### ISSUE TITLE
Controller-manager needs to mount hostpath the flexvolume plugin dir

### ISSUE THREAD

**Issue by kokhang** [kubernetes/kubeadm#410]
I am using Kubeadm to setup my K8S cluster. I am also trying a flexvolume. https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md

The controller-manager by default loads flex volume plugins from `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`, which can be overwritten by passing the `--flex-volume-plugin-dir` arg.

The problem I’m seeing is that since the kubeadm deploys the controller-manager in a container, I have to modify the controller-manager manifest on `/etc/kubernetes/manifests` to add a volume mount to this directory from hostpath.

is this what is normally done to enable flexvolume on a k8s cluster brought up by kubeadm?  If so, there should be a better way for enabling flexvolume plugins, that is not as invasive.

**Comment by luxas** [comment]
@kokhang will send a PR for this :+1:

**Comment by luxas** [comment]
Woot, fixed with https://github.com/kubernetes/kubernetes/pull/51296 :tada:!
