### ISSUE TITLE
join w/ master dns name writes ip to kubelet config

### ISSUE THREAD

**Issue by kapilt** [kubernetes/kubeadm#411]
i'm using kubeadm in a corporate cloud environment with enforced node recycling, one of the challenges of using kubeadm is that join will always use the ip address of the master instead of a passed in dns name (master cert also with subject alt to include dns name). the join ends up writing out the master ip to the kubelet.conf which complicates rotation/restoration of the master. given the symmetric secret, and the ca hash work being done in
https://docs.google.com/document/d/1SP4P7LJWSA8vUXj27UvKdVEdhpo5Fp0QHNo4TXvLQbw/edit?ts=5971498a#heading=h.5bejulk96xxi

is there any reason why kubeadm couldn't support using the actual value passed (ip or dns per user choice) instead of forcing ip usage?

kubeadm version - 1.7.4

**Comment by kapilt** [comment]
related #338

**Comment by luxas** [comment]
@timothysc @mattmoyer ^

**Comment by mattmoyer** [comment]
+1, this seems reasonable to allow a hostname and validate the certificate against that hostname rather than pre-resolving to an IP address.

**Comment by mattmoyer** [comment]
I was confused because I thought this already worked, and I just tested to confirm and it seems to:
```
# on my master node
$ kubeadm init --apiserver-cert-extra-sans k8s-api.myservice.foo.local
[...]
You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token 7bb4c3.25fe05a25378e218 10.0.2.15:6443 --discovery-token-ca-cert-hash sha256:19402aab9dd795f0bfb74e1a7f2dcf215392222b2020510bdab5e87dda19526a
```

```
# on my worker node
$ kubeadm join --token 7bb4c3.25fe05a25378e218 k8s-api.myservice.foo.local:6443 --discovery-token-ca-cert-hash sha256:19402aab9dd795f0bfb74e1a7f2dcf215392222b2020510bdab5e87dda19526a
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Running pre-flight checks
[preflight] Starting the kubelet service
[discovery] Trying to connect to API Server "k8s-api.myservice.foo.local:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://k8s-api.myservice.foo.local:6443"
[discovery] Requesting info from "https://k8s-api.myservice.foo.local:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "k8s-api.myservice.foo.local:6443"
[discovery] Successfully established connection with API Server "k8s-api.myservice.foo.local:6443"

Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.

Run 'kubectl get nodes' on the master to see this machine join.
```

In this case I have a (local) DNS entry for `k8s-api.myservice.foo.local` that resolves to my API server IP. The only missing thing right now is that there's no way to get `kubeadm init` to print out the right `kubeadm join` command with a hostname. However, if you substitute in the hostname yourself it should all work.

The API server TLS certificate common name/SANs will be validated against whatever name you pass to `kubeadm join`, so you need to make sure to add it with `--apiserver-cert-extra-sans` when you run `kubeadm init`.

**Comment by kapilt** [comment]
The issue is when i examine the contents of /etc/kubernetes/kubelet.conf its the  ip address of the master not the dns name thats configured. If we join with dns name, i would expect to see the dns name here.

join
```
$ kubeadm join --token 5bb4c3.25fe05a25378e218 bdata-dev.example.com:6443
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Skipping pre-flight checks
[discovery] Trying to connect to API Server "bdata-dev.example.com:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://bdata-dev.example.com:6433"
[discovery] Cluster info signature and contents are valid, will use API Server "https://bdata-dev.example.com:443"
[discovery] Successfully established connection with API Server "bdata-dev.example.com:443"
[bootstrap] Detected server version: v1.7.4
[bootstrap] The server supports the Certificates API (certificates.k8s.io/v1beta1)
[csr] Created API client to obtain unique certificate for this node, generating keys and certificate signing request
[csr] Received signed certificate from the API server, generating KubeConfig...
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"

Node join complete:
* Certificate signing request sent to master and response
  received.
* Kubelet informed of new secure connection details.

Run 'kubectl get nodes' on the master to see this machine join.
```

config file
```
$ cat /etc/kubernetes/kubelet.conf | grep http
server: https://192.168.10.8:11433
```

**Comment by mattmoyer** [comment]
Ah, I see what you mean. The initial kubeadm discovery process works but then the bootstrap kubelet config (`/etc/kubernetes/bootstrap-kubelet.conf`) ends up configured incorrectly with the IP. I'll take a look at where this happens.

**Comment by kapilt** [comment]
this appears to be the issue https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/config/masterconfig.go#L45

**Comment by kapilt** [comment]
fixing it there has a minor ripple to generating the api server pod's cli params to use the netutil.ChooseBindAddress. i.e. the root reason afaics for the early rewrite of the configured value was its use in both the client config as well as there server bind addresses, separating the two uses allows the use of a dns entry for the client.

**Comment by kapilt** [comment]
fwiw, I have fixes against 1.7 release branch here https://github.com/kapilt/kubernetes/tree/kubeadm-use-advertised

I assume I should replant to 1.8 trunk, is this something that is appropriate for a pr to the extant release branch?

**Comment by mattmoyer** [comment]
@kapilt great! We'll definitely want it rebased onto `master`/trunk for 1.8. Once we get a PR set up for 1.8 we can talk to @wojtek-t and others to decide if it's something we should cherry pick into the 1.7.x series.

**Comment by luxas** [comment]
@mattmoyer can we close this?

**Comment by wimvanleuven** [comment]
Running into this issue myself. 3 questions here:

1. Will this be enhanced in a future release? 
1. What is the current workaround?
1. Can I help with fixing, documenting or testing?

**Comment by rharmse** [comment]
To confirm, I just bootstrapped a master node on a HypriotOS raspberry pi for my pi-cluster and can confirm that this is still happening on 1.8.

If you need any info from me feel free to let me know below is version info of the kubeadm used : 

$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/arm"}

Thanks for the great work!

**Comment by kapilt** [comment]
also happening on 1.9.1

**Comment by kapilt** [comment]
fwiw, the mechanics underlying this issue also cause the master to write out its ip to on kubeadm init to config files on disk and to the configmap it initializes.

**Comment by stevesloka** [comment]
I'd like to take this on, will post back updates as I progress through.

**Comment by timothysc** [comment]
@stevesloka - just poke me on review and I can help guide it through.

**Comment by stevesloka** [comment]
@timothysc Is the best place to get the dns name from `--apiserver-cert-extra-sans`? What should happen if multiple sans are specified? Use the first?

**Comment by jaxxstorm** [comment]
@stevesloka As someone who uses this heavily, I think it should be a configurable parameter. This means you can use things like ELB addresses.

Currently the advertise address is used I believe, maybe a flag like `--apiserver-dns-name` which automatically gets added to the extra-sans?

**Comment by stevesloka** [comment]
@jaxxstorm that sounds good to me, I like the idea of a new flag.

**Comment by stevesloka** [comment]
@jaxxstorm would it make sense to just use `--apiserver-advertise-address`? This way we don't need a new flag.

**Comment by jaxxstorm** [comment]
@stevesloka doesn't that get used as the listen address for the apiserver manifest? Would a hostname be acceptable there?

**Comment by stevesloka** [comment]
yup you are correct @jaxxstorm I got ahead of myself and forgot API server requires an IP address.

**Comment by Matt272727** [comment]
@mattmoyer Hi. As you said that using the hostname in kubeadm join command should work but it seems not to be working. I used kubeadm init with the hostname of the master node and then used the kubeadm join command with master hostname but it throws error "Failed to request cluster info, will try again..." 
Both the machines can ping each other using hostname
