### ISSUE TITLE
kubeadm master e2e job failing (BeforeSuite, KubeletNotReady)

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#412]
The kubeadm master branch CI job has a new failure, during `BeforeSuite`.

https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce

Here is an example of a failed job:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5219

The cluster comes up, and has weave-net deployed, but this message is spamming the client side logs:

    I0824 14:32:32.721] Aug 24 14:32:32.721: INFO: Condition Ready of node e2e-5219-node-3k71 is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
    I0824 14:32:32.721] Aug 24 14:32:32.721: INFO: Condition Ready of node e2e-5219-node-zf8h is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
    I0824 14:32:32.721] Aug 24 14:32:32.721: INFO: Condition Ready of node e2e-5219-node-8mfj is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
    I0824 14:32:32.722] Aug 24 14:32:32.721: INFO: Condition Ready of node e2e-5219-master is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
    I0824 14:32:32.722] Aug 24 14:32:32.721: INFO: Condition Ready of node e2e-5219-node-ds17 is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

We'll probably need to dig into the server-side logs to figure out what's going wrong. Since kubernetes-anywhere took a snapshot of the weave-net manifest, it's possible that enough skew has occurred that we need to update our manifests.

@kubernetes/sig-cluster-lifecycle-bugs

**Comment by pipejakob** [comment]
If anyone has the bandwidth, a really quick test anyone can do is to follow our normal kubeadm cluster setup instructions using the newest CI artifacts to see if you can reproduce the problem.

You can either build the artifacts yourself from master, or grab the CI debs from here:

gs://kubernetes-release-dev/bazel/v1.8.0-alpha.3.99+1957e4a2ced19d/bin/linux/amd64

For instance, you can do this on an Ubuntu system:

    mkdir /tmp/k8s
    gsutil rsync gs://kubernetes-release-dev/bazel/v1.8.0-alpha.3.99+1957e4a2ced19d/bin/linux/amd64 /tmp/k8s
    sudo dpkg -i /tmp/k8s/*.deb
    sudo apt-get install -f -y

Then perform the `kubeadm init` / `kubeadm join` steps as normal.

**Comment by pipejakob** [comment]
Using the builds from our last good, green run, if I just do `kubeadm init` for the master, and then `kubectl get pods --all-namespaces`, I get this output:

    $ kubectl get pods --all-namespaces
    NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
    kube-system   etcd-master                      1/1       Running   0          24s
    kube-system   kube-apiserver-master            1/1       Running   0          22s
    kube-system   kube-controller-manager-master   0/1       Pending   0          4s
    kube-system   kube-dns-1848271846-smc4w        0/3       Pending   0          41s
    kube-system   kube-proxy-2j682                 1/1       Running   0          41s
    kube-system   kube-scheduler-master            1/1       Running   0          21s

Everything is marked running, except `kube-dns` and `kube-controller-manger` are in Pending, although `docker ps` shows the controller manager running fine.

If I then apply the weave-net manifest, then eventually all pods become Running and the master node becomes Ready:

    $ kubectl apply -f https://cloud.weave.works/k8s/v1.7/net.yaml
    serviceaccount "weave-net" created
    clusterrole "weave-net" created
    clusterrolebinding "weave-net" created
    daemonset "weave-net" created

    $ kubectl get pods --all-namespaces
    NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
    kube-system   etcd-master                      1/1       Running   0          4m
    kube-system   kube-apiserver-master            1/1       Running   0          4m
    kube-system   kube-controller-manager-master   1/1       Running   0          3m
    kube-system   kube-dns-1848271846-smc4w        3/3       Running   0          4m
    kube-system   kube-proxy-2j682                 1/1       Running   0          4m
    kube-system   kube-scheduler-master            1/1       Running   0          4m
    kube-system   weave-net-pt8bj                  2/2       Running   0          35s

    $ kubectl get nodes
    NAME      STATUS         AGE       VERSION
    master    Ready,Master   5m        v1.8.0-alpha.3.53+3f78723427ec8c

Contrast that with what happens with the **newest** build, where our e2es are red. After `kubeadm init`, I see:

    $ kubectl get pods --all-namespaces
    NAMESPACE     NAME                            READY     STATUS    RESTARTS   AGE
    kube-system   etcd-master0                      0/1       Pending   0          1m
    kube-system   kube-apiserver-master0            0/1       Pending   0          1m
    kube-system   kube-controller-manager-master0   0/1       Pending   0          1m
    kube-system   kube-dns-1848271846-lhcxv         0/3       Pending   0          2m
    kube-system   kube-proxy-lbwnm                  0/1       Pending   0          2m
    kube-system   kube-scheduler-master0            0/1       Pending   0          1m

Everything is stuck in pending. Adding a CNI provider doesn't help:

    $ kubectl apply -f https://cloud.weave.works/k8s/v1.7/net.yaml
    serviceaccount "weave-net" created
    clusterrole "weave-net" created
    clusterrolebinding "weave-net" created
    daemonset "weave-net" created

    $ kubectl get pods --all-namespaces
    NAMESPACE     NAME                            READY     STATUS    RESTARTS   AGE
    kube-system   etcd-master0                      0/1       Pending   0          3m
    kube-system   kube-apiserver-master0            0/1       Pending   0          3m
    kube-system   kube-controller-manager-master0   0/1       Pending   0          3m
    kube-system   kube-dns-1848271846-lhcxv         0/3       Pending   0          3m
    kube-system   kube-proxy-lbwnm                  0/1       Pending   0          3m
    kube-system   kube-scheduler-master0            0/1       Pending   0          3m
    kube-system   weave-net-dn53m                   0/2       Pending   0          25s

None of the pods ever get out of Pending, and kubelet's logs are still full of:

    Aug 24 17:37:53 master0 kubelet[14246]: W0824 17:37:53.532783   14246 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
    Aug 24 17:37:53 master0 kubelet[14246]: E0824 17:37:53.533449   14246 kubelet.go:2037] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
    Aug 24 17:37:58 master0 kubelet[14246]: W0824 17:37:58.534613   14246 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
    Aug 24 17:37:58 master0 kubelet[14246]: E0824 17:37:58.535265   14246 kubelet.go:2037] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
    Aug 24 17:38:03 master0 kubelet[14246]: W0824 17:38:03.536546   14246 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d

**Comment by pipejakob** [comment]
For reference:

Last known good commit: 3f7872342
First known bad commit: b2f324403

There are many commits between them that don't have e2e runs, so it would also be useful to bisect and see exactly what commit broke this behavior if it isn't obvious from the diffs.

**Comment by pipejakob** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/46597 was the cause, but we're hoping that https://github.com/kubernetes/kubernetes/pull/50063 fixes things.

**Comment by dixudx** [comment]
Latest [pull-kubernetes-e2e-kubeadm-gce](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kubeadm-gce/?) seems to have nothing with #46597.

> W0728 04:40:38.736] Run: ('kubetest', '-v', '--dump=/workspace/k8s.io/kubernetes/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--cluster=e2e-5308', '--gcp-network=e2e-5308', '--deployment=kubernetes-anywhere', '--extract=local', '--gcp-project=k8s-jkns-pr-kubeadm', '--gcp-zone=us-central1-f', '--kubernetes-anywhere-kubernetes-version=latest', '--provider=kubernetes-anywhere', '--test_args=--ginkgo.focus=\\[Conformance\\] --ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\] --minStartupPods=8', '--timeout=55m', '--kubernetes-anywhere-path=/workspace/kubernetes-anywhere', '--kubernetes-anywhere-phase2-provider=kubeadm', '--kubernetes-anywhere-cluster=e2e-5308', '--kubernetes-anywhere-kubeadm-version=gs://kubernetes-release-dev/bazel/49495/master:e4551d50e57c089aab6f67333412d3ca64bc09ae,49495:b7286f3188e997c98c89e1a8755b58ae69fbd4b0/bin/linux/amd64/')

> W0728 04:40:39.009] flag provided but not defined: -cluster

Wrong settings on the flags.

For https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/5219, @pipejakob I did not find any obvious logs on the hostpath type.

**Comment by thockin** [comment]
Other than bisection, how do we know that PR causes the failure?  What is actually failing?  The new field is optional.

**Comment by luxas** [comment]
Oddly enough, the job went back to being 100% green again...
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce

Not sure what happened there tbh

**Comment by liggitt** [comment]
yeah, the field is optional and defaults to a no-op... I don't see any behavior changes on that that would have hit kubeadm

**Comment by dixudx** [comment]
@luxas @liggitt Thanks for this clarification. I am relieved. :-)

**Comment by pipejakob** [comment]
Yup, the job is back to green which means I have no idea what was actually going wrong. Closing.
