### ISSUE TITLE
Documentation request for https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by eddytruyen** [kubernetes/kubeadm#419]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report
- [x] Documentation request
**Problem:**
Many CNI-based plugins do not set hairpin mode which allows pods to access themselves via their Service IP, if they don't know about their podIP. 
https://github.com/containernetworking/cni/issues/476
This is not documented in kubeadm. However kubeam only supports CNI-based plugins and not kubenet-based plugins

(I came across this problem when deploying a MongoDB replicaset. My rs-initiate-command for bootstrapping a MongoDB replicaset configures the MongoDB endpoints as ServiceIPs such that different mongodb instances connect to each other via the stable service IP.  However, each mongo instance also uses its own ServiceIp for internal processing.  The trivial solution to this particular problem is using a StatefulSet with a Headless Service such that DNSNames for each Mongodb Pod  are used for setting up the MongoDB endpoints).

**Proposed Solution:**
Is it possible to extend the documentation of the section "Install Pod network" with additional information which network add-ons support hairpin mode?

I can confirm that flannel-cni plugin does not support setting up MongoDB with ServiceIPs,  while weave.net does support it. 

When looking at the kubelet logs for weave.net I get the following output
```
W0902 22:08:28.136786     941 kubelet_network.go:70] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I0902 22:08:28.136845     941 kubelet.go:508] Hairpin mode set to "hairpin-veth"
```

**Page to Update:**
k8s.io/docs/setup/independent/create-cluster-kubeadm/

**Kubernetes Version:**
v1.7.2

**Comment by luxas** [comment]
Sounds good to me to do such a doc change?
@eddytruyen as you have the context, can you please send a PR and I'll review?

**Comment by eddytruyen** [comment]
@luxas Ok, it's my pleasure. 

Should I add it to the [Troubleshooting](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/setup/independent/create-cluster-kubeadm.md#troubleshooting-troubleshooting) section or the [network add-ons](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/setup/independent/create-cluster-kubeadm.md#34-installing-a-pod-network-pod-network) section? 

I prefer the troubleshooting section because I expect that issue containernetworking/cni#476 will quickly propagate to various Pod Network providers. People will need to consult the information provided by Pod Network providers to get timely information.

**Comment by eddytruyen** [comment]
Note that the problem that pods cannot reach themselves via their service ip is discussed as an item of the [debug services](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#a-pod-cannot-reach-itself-via-service-ip) page of the general Kubernetes documentation. The first paragraph of this item's description suggests that the hairpin-mode can be set by setting a flag of the kubelet. 
This advice does not work anymore for CRI-based K8s deployments; a concise account of the problem and resolution for the Weave plugin is contained [here](https://github.com/weaveworks/weave/pull/2971) .

**Comment by luxas** [comment]
You can add it to troubleshooting, explain the problem and link to refs
Then in each provider's tab state whether they support that thing or not

**Comment by eddytruyen** [comment]
I am newbie wrt to pull requests. 
I don't have permission to create a topic branch on kubernetes.github.io. Shall I make a pull request from a fork. Please advise

**Comment by luxas** [comment]
This seems to be fixed now. Thanks @eddytruyen for the PR :tada:!
