### ISSUE TITLE
Investigate rollback options for upgrade

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubeadm#420]
In Lucas's upgrades PR a discussion span off about how we can ensure clusters are never left in a corrupted state after failed/borked upgrades. I think @pipejakob encapsulated it best: 

> It would be great if our upgrade plan had ... properties, so that kubeadm or any random component could crash at any time during the upgrade, and we would never leave the cluster in an unusable state where human intervention would be required to fix it

More context here: https://github.com/kubernetes/kubernetes/pull/48899#issuecomment-325017058. We should look at if there's any easy way to do this.

/cc @luxas @timothysc

**Comment by luxas** [comment]
Not sure there are enough action items here to do something for v1.9, but we'll hopefully start supporting downgrades in v1.9, see https://github.com/kubernetes/kubeadm/issues/452
