### ISSUE TITLE
DNS is not updated with new services

### ISSUE THREAD

**Issue by TristanPeers** [kubernetes/kubeadm#422]
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Cluster built using kubeadm in AWS (without enabling the cloud-provider)
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core) 
- **Kernel** (e.g. `uname -a`): 3.10.0-514.26.2.el7.x86_64
- **Others**:

## What happened?
We installed a brand new cluster using the guide ( https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/ ). We chose Calico as the overlay. Unfortunately our Centos machines already run within the 10.96.x.x subnet so we have to specify new CIDR ranges. We start the cluster using this command `kubeadm init --service-cidr=10.66.0.0/16 --pod-network-cidr=10.67.0.0/16 --kubernetes-version v1.7.4`.

We override the kubelet service kubeadm DNS definition using the workaround in this issue -> https://github.com/kubernetes/kubernetes/issues/33881#issuecomment-251065019

We then deploy a test nginx service. This is not picked up by DNS until we kill the DNS pod/container and a new one is spawned.
 
```
[root@ip-10-96-3-245 ~]# kubectl run --namespace=default nginx --replicas=2 --image=nginx
deployment "nginx" created

[root@ip-10-96-3-245 ~]# kubectl expose --namespace=default deployment nginx --port=80
service "nginx" exposed

[root@ip-10-96-3-245 ~]# kubectl run --namespace=default access --rm -ti --image busybox /bin/sh

If you don't see a command prompt, try pressing enter.
/ # nslookup nginx
Server:    10.66.0.10
Address 1: 10.66.0.10

nslookup: can't resolve 'nginx'
/ # exit
Session ended, resume using 'kubectl attach access-2475823348-7c8p1 -c access -i -t' command when the pod is running

[root@ip-10-96-3-245 ~]# kubectl get pods --all-namespaces -o wide | grep 'kube-dns' | grep -v 'NAME' | awk '{print $2}' | while read pod; do kubectl delete pod --namespace=kube-system $pod --grace-period=0 --force; done
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "kube-dns-2425271678-688ss" deleted

[root@ip-10-96-3-245 ~]# kubectl run --namespace=default access --rm -ti --image busybox /bin/sh

If you don't see a command prompt, try pressing enter.
/ # nslookup nginx
Server:    10.66.0.10
Address 1: 10.66.0.10 kube-dns.kube-system.svc.cluster.local

Name:      nginx
Address 1: 10.66.190.223 nginx.default.svc.cluster.local
```

## What you expected to happen?
We expected new services to appear in DNS automatically without having to respawn the DNS container(s)

## How to reproduce it (as minimally and precisely as possible)?
1. Use Centos 7 - start 2 machines, master and worker.
2. Change kubelet service to use correct DNS -> `printf '[Service]\nEnvironment="KUBELET_DNS_ARGS=--cluster-domain=cluster.local --cluster-dns=%s"\n' 10.66.0.10 > /etc/systemd/system/kubelet.service.d/20-dns-override.conf; systemctl daemon-reload`
3. Create cluster using kubeadm using non-default CIDR's and join worker to master -> `kubeadm init --service-cidr=10.66.0.0/16 --pod-network-cidr=10.67.0.0/16 --kubernetes-version v1.7.4`
4. Create test nginx service
5. Check it appears in DNS

**Comment by luxas** [comment]
This is a known issue @TristanPeers. We need #28 in order for this to work automatically,  probably coming in v1.9
Until then,  you need to modify `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` manually on each node.
