### ISSUE TITLE
Separate Etcd instances from events and rest

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubeadm#428]
Kubeadm creates a single etcd for storing all data. But the kube-up scripts used to create 2 separate etcd : one for events and one for rest.  Looking at the MasterConfiguration, it seems that there is option to pass only one Etcd. How do we create separate etcd for events and rest?

**Comment by luxas** [comment]
I think that's doable by pointing to the events etcd instance by using flags in `apiServerExtraArgs`

**Comment by tamalsaha** [comment]
Can Kubeadm create that etcd too?

**Comment by luxas** [comment]
No, I don't think so.
We're binding the ports to localhost for the main etcd, so it isn't feasible to start doing hacky things to get a separate etcd for events. Also there is no value in "splitting up" etcd if you still run everything on the same machine. That machine is everything kubeadm owns, so if you want a custom etcd for events, you should set it up yourself (as the ways to implement that are endless)

**Comment by luxas** [comment]
Closing this as out of scope. kubeadm will set up one etcd instance, if you want many you can just add the right parameters to the config file to point to your other etcd instance for Events
