### ISSUE TITLE
kubeadm should indicate progress

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#43]
_From @errordeveloper on September 29, 2016 11:22_

It may take quite long for API server to come up, as this involves pulling Docker images in the background.

We have already discussed adding a progress bar, and it'd would be great. Also, we should consider pulling directly from kubeadm, so we can provide user with a real progress bar. Also, we could consider adding `kubeadm util pull-images` and allow alternative registries, as it would help users in air-gapped environments.

_Copied from original issue: kubernetes/kubernetes#33744_

**Comment by luxas** [comment]
We discussed this, and decided not to implement a docker-only feature.
Instead we should focus on making the overall output of kubeadm better.
