### ISSUE TITLE
Issue kubeadm on Orcale linux - Hangs on 'Created API client, waiting for the control plane to become ready'

### ISSUE THREAD

**Issue by wheestermans** [kubernetes/kubeadm#432]
Running on Oracle Linux 7.3 - Docker 1.12

# kubeadm version

kubeadm version: &version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Executing kubeadm init is hanging on the following step

**[apiclient] Created API client, waiting for the control plane to become ready**

# docker images

REPOSITORY TAG IMAGE ID CREATED SIZE
gcr.io/google_containers/kube-apiserver-amd64 v1.7.5 33cecf00bef1 11 days ago 186.1 MB
gcr.io/google_containers/kube-controller-manager-amd64 v1.7.5 4d581c01252d 11 days ago 138 MB
gcr.io/google_containers/kube-scheduler-amd64 v1.7.5 2aad6febbb16 11 days ago 77.2 MB
gcr.io/google_containers/etcd-amd64 3.0.17 243830dae7dd 6 months ago 168.9 MB
gcr.io/google_containers/pause-amd64 3.0 99e59f495ffa 16 months ago 746.9 kB

# docker ps

CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
c3d83dc80279 gcr.io/google_containers/etcd-amd64@sha256:d83d3545e06fb035db8512e33bd44afb55dea007a3abd7b17742d3ac6d235940 "etcd --advertise-cli" 8 minutes ago Up 8 minutes k8s_etcd_etcd-lxdocapt13_kube-system_10388e5ca072958c4f33ec2488d20b33_0
193fdcf4af4f gcr.io/google_containers/kube-controller-manager-amd64@sha256:cc8e9333a98ab48e83c94e4c2c6d27f5d98654ffb398d8c659b5bb553f134edd "kube-controller-mana" 8 minutes ago Up 8 minutes k8s_kube-controller-manager_kube-controller-manager-lxdocapt13_kube-system_d55d43fdee2a846d0acf9cd0e019131e_0
b3e77804d757 gcr.io/google_containers/kube-scheduler-amd64@sha256:fc1b1e8d94fe30c8b3fcacc2146fca16d7eba3b8a75e6710277e398653cfe79b "kube-scheduler --kub" 8 minutes ago Up 8 minutes k8s_kube-scheduler_kube-scheduler-lxdocapt13_kube-system_256efe0717a609d25d5670d809d968f9_0
b3aeef692b84 gcr.io/google_containers/kube-apiserver-amd64@sha256:aa5674d9cfb2e7c445d10b25cda16f0db03455a1adf4550bdc9121dc7fd5b504 "kube-apiserver --ins" 9 minutes ago Up 9 minutes k8s_kube-apiserver_kube-apiserver-lxdocapt13_kube-system_908ca90e810585712aa970cc64038de5_0
a51a1b46d0fc gcr.io/google_containers/pause-amd64:3.0 "/pause" 9 minutes ago Up 9 minutes k8s_POD_etcd-lxdocapt13_kube-system_10388e5ca072958c4f33ec2488d20b33_0
a9bc07bf78a5 gcr.io/google_containers/pause-amd64:3.0 "/pause" 9 minutes ago Up 9 minutes k8s_POD_kube-controller-manager-lxdocapt13_kube-system_d55d43fdee2a846d0acf9cd0e019131e_0
3ea752e0e439 gcr.io/google_containers/pause-amd64:3.0 "/pause" 9 minutes ago Up 9 minutes k8s_POD_kube-scheduler-lxdocapt13_kube-system_256efe0717a609d25d5670d809d968f9_0
2a6b5574a5ba gcr.io/google_containers/pause-amd64:3.0 "/pause" 9 minutes ago Up 9 minutes k8s_POD_kube-apiserver-lxdocapt13_kube-system_908ca90e810585712aa970cc64038de5_0

# But the kubeadm init hangs

[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.7.5
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks
[preflight] WARNING: Connection to "https://150.45.89.108:6443" uses proxy "http://150.45.87.133:8080". If that is not intended, adjust your proxy settings
[kubeadm] WARNING: starting in 1.8, tokens expire after 24 hours by default (if you require a non-expiring token use --token-ttl 0)
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API Server serving cert is signed for DNS names [lxdocapt13 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 150.45.89.108]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[apiclient] Created API client, waiting for the control plane to become ready

# kubelet logs

W0911 16:02:15.109499 7495 server.go:496] No API client: no api servers specified
I0911 16:02:15.109535 7495 client.go:72] Connecting to docker on unix:///var/run/docker.sock
I0911 16:02:15.109547 7495 client.go:92] Start docker client with request timeout=2m0s
W0911 16:02:15.110973 7495 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
I0911 16:02:15.134851 7495 manager.go:143] cAdvisor running in container: "/"
W0911 16:02:15.143181 7495 manager.go:151] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp 127.0.0.1:15441: getsockopt: connection refused
I0911 16:02:15.155252 7495 fs.go:117] Filesystem partitions: map[/dev/mapper/vg01-lv_root:{mountpoint:/ major:251 minor:0 fsType:ext4 blockSize:0} /dev/sda1:{mountpoint:/boot major:8 minor:1 fsType:ext4 blockSize:0} /dev/mapper/vg01-lv_tmp:{mountpoint:/tmp major:251 minor:1 fsType:ext4 blockSize:0} docker-thinpool:{mountpoint: major:251 minor:3 fsType:devicemapper blockSize:1024}]
I0911 16:02:15.167643 7495 manager.go:198] Machine: {NumCores:6 CpuFrequency:2500029 MemoryCapacity:3872628736 MachineID:38f09137bfe8414883d92fd03b825cbb SystemUUID:42007FD7-6278-8BEE-E7FA-0C395BA55823 BootID:6d076f14-0e49-42c6-b8b9-ad20041d7bd9 Filesystems:[{Device:/dev/sda1 DeviceMajor:8 DeviceMinor:1 Capacity:499337216 Type:vfs Inodes:128016 HasInodes:true} {Device:/dev/mapper/vg01-lv_tmp DeviceMajor:251 DeviceMinor:1 Capacity:4093313024 Type:vfs Inodes:262144 HasInodes:true} {Device:docker-thinpool DeviceMajor:251 DeviceMinor:3 Capacity:153004015616 Type:devicemapper Inodes:0 HasInodes:false} {Device:/dev/mapper/vg01-lv_root DeviceMajor:251 DeviceMinor:0 Capacity:15719145472 Type:vfs Inodes:983040 HasInodes:true}] DiskMap:map[251:12:{Name:dm-12 Major:251 Minor:12 Size:10737418240 Scheduler:none} 251:7:{Name:dm-7 Major:251 Minor:7 Size:10737418240 Scheduler:none} 251:9:{Name:dm-9 Major:251 Minor:9 Size:10737418240 Scheduler:none} 2:0:{Name:fd0 Major:2 Minor:0 Size:4096 Scheduler:deadline} 251:10:{Name:dm-10 Major:251 Minor:10 Size:10737418240 Scheduler:none} 251:11:{Name:dm-11 Major:251 Minor:11 Size:10737418240 Scheduler:none} 251:4:{Name:dm-4 Major:251 Minor:4 Size:153004015616 Scheduler:none} 251:5:{Name:dm-5 Major:251 Minor:5 Size:10737418240 Scheduler:none} 251:6:{Name:dm-6 Major:251 Minor:6 Size:10737418240 Scheduler:none} 251:8:{Name:dm-8 Major:251 Minor:8 Size:10737418240 Scheduler:none} 8:32:{Name:sdc Major:8 Minor:32 Size:161061273600 Scheduler:deadline} 251:0:{Name:dm-0 Major:251 Minor:0 Size:16106127360 Scheduler:none} 251:1:{Name:dm-1 Major:251 Minor:1 Size:4294967296 Scheduler:none} 8:16:{Name:sdb Major:8 Minor:16 Size:6442450944 Scheduler:deadline} 251:2:{Name:dm-2 Major:251 Minor:2 Size:1606418432 Scheduler:none} 251:3:{Name:dm-3 Major:251 Minor:3 Size:153004015616 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:21474836480 Scheduler:deadline}] NetworkDevices:[{Name:ens160 MacAddress:00:50:56:80:0b:9d Speed:10000 Mtu:1500} {Name:ens192 MacAddress:00:50:56:80:01:b3 Speed:10000 Mtu:1500} {Name:ens224 MacAddress:00:50:56:80:41:f3 Speed:10000 Mtu:1500}] Topology:[{Id:0 Memory:3872628736 Cores:[{Id:0 Threads:[0] Caches:[{Size:16384 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:2097152 Type:Unified Level:2}]}] Caches:[{Size:12582912 Type:Unified Level:3}]} {Id:2 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[{Size:16384 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:2097152 Type:Unified Level:2}]}] Caches:[{Size:12582912 Type:Unified Level:3}]} {Id:4 Memory:0 Cores:[{Id:0 Threads:[2] Caches:[{Size:16384 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:2097152 Type:Unified Level:2}]}] Caches:[{Size:12582912 Type:Unified Level:3}]} {Id:6 Memory:0 Cores:[{Id:0 Threads:[3] Caches:[{Size:16384 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:2097152 Type:Unified Level:2}]}] Caches:[{Size:12582912 Type:Unified Level:3}]} {Id:8 Memory:0 Cores:[{Id:0 Threads:[4] Caches:[{Size:16384 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:2097152 Type:Unified Level:2}]}] Caches:[{Size:12582912 Type:Unified Level:3}]} {Id:10 Memory:0 Cores:[{Id:0 Threads:[5] Caches:[{Size:16384 Type:Data Level:1} {Size:65536 Type:Instruction Level:1} {Size:2097152 Type:Unified Level:2}]}] Caches:[{Size:12582912 Type:Unified Level:3}]}] CloudProvider:Unknown InstanceType:Unknown InstanceID:None}
I0911 16:02:15.169042 7495 manager.go:204] Version: {KernelVersion:4.1.12-61.1.23.el7uek.x86_64 ContainerOsVersion:Oracle Linux Server 7.3 DockerVersion:1.12.2 DockerAPIVersion:1.24 CadvisorVersion: CadvisorRevision:}
W0911 16:02:15.169858 7495 server.go:356] No api server defined - no events will be sent to API server.
I0911 16:02:15.169873 7495 server.go:536] --cgroups-per-qos enabled, but --cgroup-root was not specified. defaulting to /
W0911 16:02:15.173104 7495 container_manager_linux.go:218] Running with swap on is not supported, please disable swap! This will be a fatal error by default starting in K8s v1.6! In the meantime, you can opt-in to making this a fatal error by enabling --experimental-fail-swap-on.
I0911 16:02:15.173194 7495 container_manager_linux.go:246] container manager verified user specified cgroup-root exists: /
I0911 16:02:15.173213 7495 container_manager_linux.go:251] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:} {Signal:nodefs.available Operator:LessThan Value:{Quantity: Percentage:0.1} GracePeriod:0s MinReclaim:} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity: Percentage:0.05} GracePeriod:0s MinReclaim:}]} ExperimentalQOSReserved:map[]}
W0911 16:02:15.180778 7495 kubelet_network.go:70] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
I0911 16:02:15.180834 7495 kubelet.go:508] Hairpin mode set to "hairpin-veth"
W0911 16:02:15.186568 7495 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
I0911 16:02:15.212251 7495 docker_service.go:208] Docker cri networking managed by kubernetes.io/no-op
I0911 16:02:15.216990 7495 docker_service.go:225] Setting cgroupDriver to cgroupfs
I0911 16:02:15.226956 7495 remote_runtime.go:42] Connecting to runtime service unix:///var/run/dockershim.sock
I0911 16:02:15.228926 7495 kuberuntime_manager.go:166] Container runtime docker initialized, version: 1.12.2, apiVersion: 1.24.0
I0911 16:02:15.230557 7495 server.go:943] Started kubelet v1.7.5
W0911 16:02:15.230639 7495 kubelet.go:1313] No api server defined - no node status update will be sent.
E0911 16:02:15.230649 7495 server.go:612] Starting health server failed: listen tcp 127.0.0.1:10248: bind: address already in use
I0911 16:02:15.230692 7495 server.go:132] Starting to listen on 0.0.0.0:10250
E0911 16:02:15.230860 7495 kubelet.go:1229] Image garbage collection failed once. Stats initialization may not have completed yet: unable to find data for container /
I0911 16:02:15.230916 7495 kubelet_node_status.go:247] Setting node annotation to enable volume controller attach/detach
I0911 16:02:15.233261 7495 server.go:310] Adding debug handlers to kubelet server.
F0911 16:02:15.233460 7495 server.go:160] listen tcp 0.0.0.0:10255: bind: address already in use

**Comment by ddurgadas** [comment]
I would like to take a look at this issue. Can someone please assign it to me?

**Comment by pipejakob** [comment]
@ddurgadas It seems that GitHub doesn't allow it. It's not a problem of the permission of being able to assign the issue, but of who it can be assigned to. I have permission\ to assign it, but am still not allowed to assign it to you, since you're not a part of the Kubernetes org.

That said, feel free to dive in and investigate, and keep posting any progress you make here! Anyone else will read through the issue history and clearly see that you're working on it. However, I don't think that should stop anyone else from looking into the issue if they're still interested, knowing that you're also debugging.

**Comment by wheestermans** [comment]
Is someboby looking to this issue. Or is there another way to get kubernetes up-and-running on my Oracle Linux environment?

REgards
walter

**Comment by wheestermans** [comment]
I have attached zip file with the logs of the running docker containers

[docker-containers.zip](https://github.com/kubernetes/kubeadm/files/1306547/docker-containers.zip)

**Comment by arunatechtalk** [comment]
Having the same issue on Linux 7.2 version.
it is hanging in  same place with same error

**Comment by luxas** [comment]
Please reopen this or create a new issue with more information if you can reproduce this with kubeadm v1.8.
Thank you!
