### ISSUE TITLE
Version flag needs documentation

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubeadm#435]
Currently I cannot find any documentation on what's the allowed value format for `kubernetesVersion:` field in MasterConfiguration type, or what's the format for `kubeadm --kubernetes-version` (KUBERNETES_VERSION env) options.

I'm told that it accepts

-  latest/stable/latest-1.X/stable-1.X. In v1.8 also ci/latest
- also exact tag names from https://github.com/kubernetes/kubernetes/releases

Please consider documenting this on https://kubernetes.io/docs/admin/kubeadm/

**Comment by luxas** [comment]
@mattmoyer could you address this at the same time when you update the kubeadm reference doc?

**Comment by timothysc** [comment]
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-version/ appears up to date.  Closing.
