### ISSUE TITLE
Kubeadm phase addon does not work

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#437]
## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.3561+523ec9c78a4ad3-dirty", GitCommit:"523ec9c78a4ad34afe72dfc2a41782d998511fe0", GitTreeState:"dirty", BuildDate:"2017-09-12T21:16:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}

## What happened?
when you run `kubeadm alpha phase addon *` you get

```
failed to load admin kubeconfig [open : no such file or directory]
```

Non matter if you pass `--kubeconfig` or not (it should pick `/etc/kubernetes/admin.conf` in this case)

**Comment by luxas** [comment]
Now fixed, thanks!
