### ISSUE TITLE
kubeadm offline installer support

### ISSUE THREAD

**Issue by helphi** [kubernetes/kubeadm#439]
We hope `kubeadm` can support offline installer such as `kubectl` and `minikube`, because we can't access google cloud in China.

For example, i can download `minikube` from <https://github.com/kubernetes/minikube/releases>, and then put it in `/usr/local/bin`, but i can't download `kubeadm` from somewhere because it is in google cloud apt/yum repository.

/kind feature
/area kubeadm

**Comment by fabriziopandini** [comment]
@helphi kubeadm binaries are available `https://dl.k8s.io/release/{release}/bin/linux/amd64/kubeadm`
release are semantic version strings with `v` prefix e.g. ´v1.8.0` or labels like `latest`, ´stable`

**Comment by luxas** [comment]
@helphi This is documented on the website: https://kubernetes.io/docs/admin/kubeadm/#running-kubeadm-without-an-internet-connection

**Comment by jimangel** [comment]
If anyone comes across this post, looks like the link changed: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#running-kubeadm-without-an-internet-connection
