### ISSUE TITLE
kubeadm init occasionally fails on creating configmap

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubeadm#440]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): v1.8.0-beta1

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.7.3
- **Cloud provider or hardware configuration**: none
- **OS** (e.g. from /etc/os-release): Ubuntu Xenial
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
Repeating kubeadm init --config $MYCONFIG occasionally fails when uploading configmap. 

## What you expected to happen?
Either the delay should be slightly longer before trying to upload the config or kubeadm should retry the attempt.

## How to reproduce it (as minimally and precisely as possible)?
See config and output after trying a few times to kubeadm init
https://gist.github.com/dfb88607f69d2b65735adfce13929bd4
https://gist.github.com/19f5f6cde43d560c72dd2fe2e55e65bd

## Anything else we need to know?
Repeated attempts eventually work.

**Comment by medinatiger** [comment]
@mattymo,

Have you already start on this issue? If not, I can take a bite for this issue.

**Comment by mattymo** [comment]
@medinatiger I can't reproduce this in v1.8.0-beta1. Closing.
