### ISSUE TITLE
kubeadm cannot mount basic auth file for apiserver static pod

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubeadm#441]
Choose one: BUG REPORT
## Versions

**kubeadm version** (use `kubeadm version`): v1.8.0-beta1

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.7.3
- **Cloud provider or hardware configuration**: none
- **OS** (e.g. from /etc/os-release): ubuntu xenial
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
In kubeadm v1.7.3, /etc/kubernetes is mounted directly on kube-apiserver static pod. This allows me to specify `basic-auth-file: /etc/kubernetes/users/known_users.csv` in the apiServerExtraArgs section. In v1.8.0-beta1, this mount was removed. Now only very specific mounts are made. If I move my users file into my pki dir, then it could be seen, but I don't prefer to store my user file there.

## What you expected to happen?
Keep /etc/kubernetes mount or make an option to specify extra mount volumes.

## How to reproduce it (as minimally and precisely as possible)?
Add to kubeadm config YAML:
Create a basic auth csv file.
```
apiServerExtraArgs:
  basic-auth-file: /etc/kubernetes/users/known_users.csv
```

## Anything else we need to know?
There should be an option to make extra mounts for static pods for features like basic auth file

**Comment by luxas** [comment]
cc @andrewrynhard as your PR will fix this as well

**Comment by mattymo** [comment]
@luxas @andrewrynhard Do you have a link to the PR?

**Comment by luxas** [comment]
First PR is here: https://github.com/kubernetes/kubernetes/pull/49840
