### ISSUE TITLE
Update deb/rpm manifests

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#442]
Basically flipping the versions to v1.8.0 when released and updating the kubelet manifests to match https://github.com/kubernetes/kubernetes/blob/master/build/debs/kubeadm-10.conf

We might also have to run `systemctl daemon-reload` in `kubeadm` or `kubelet` postinst as discussed with @jessicaochen 

@pipejakob can you please take ownership over getting this done and pushing the debs on release day?

**Comment by pipejakob** [comment]
I accept this grave responsibility. :-)

**Comment by pipejakob** [comment]
I'm going to work on adding this to the deb/rpm release tooling so that we don't accidentally bundle the wrong version of `kubeadm-10.conf` with different releases (since we use the same scripts to still release 1.6.x and 1.7.x patches).

CC @mikedanese

**Comment by luxas** [comment]
@pipejakob addressed this some days ago in https://github.com/kubernetes/release/pull/413
Closing...
