### ISSUE TITLE
unexpect http_proxy settings in static pod

### ISSUE THREAD

**Issue by lastboy1228** [kubernetes/kubeadm#443]
If you set http_proxy as environment variable when execute "kubeadm init", the env variable will be recorded in the yaml files in /etc/kubernetes/manifests/. 
When I delete the http_proxy setting in yaml file, the static pod is not able to be restarted by kubelete. And I can't find the error log.

**Comment by luxas** [comment]
@kad PTAL

**Comment by kad** [comment]
That is interesting. What does output of 
`kubectl -n kube-system describe pod kube-apiserver-$master_name` and `kubectl -n kube-system logs kube-apiserver-$master_name` says ?

Anything about static manifest in kubelet log ? (e.g. if manual editing resulted with syntax errors in manifests ?

Generally, if *_proxy was set during init time, in 99% of cases you will need same settings for your control plane. Only trick here is to have correct NO_PROXY set, so your CIDR ranges for Pods and Services will be specified there.

**Comment by kad** [comment]
@lastboy1228 would you be able to update this issue with details above ?
