### ISSUE TITLE
Stop using the PersistentVolumeLabel admission controller in v1.9

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#444]
Since kubeadm doesn't really use in-tree cloud providers, we can do this.
This admission controller is now deprecated in v1.8, since this functionality is now in the form of a normal controller.
If the user wants to run the in-tree cloud provider in v1.9, he/she can do so using the config file anyway.

Also, in v1.9, we're targeting out-of-tree cloud providers to be ready to use more generally as part of moving to beta.

For reference, see: https://github.com/kubernetes/kubernetes/pull/44680

**Comment by jamiehannaford** [comment]
@ss22ever do you want to take this one? It's part of a wider effort of extracting cloud providers (such as OpenStack) from the main Kubernetes codebase.

**Comment by ss22ever** [comment]
@jamiehannaford @luxas Yes, I would like to take that.

**Comment by luxas** [comment]
Cool, you can just start working on it then ;)
If the instructions here are unclear, just reach out to me and I'll clarify what to do and why

Thanks!

**Comment by luxas** [comment]
@ss22ever Do you need help with this task? Reach out to me on Slack in that case :)
I'm @luxas on Slack as well
