### ISSUE TITLE
Remove old alpha Bootstrap Token legacy code in v1.9

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#445]
As we don't support v1.7 in kubeadm v1.9, we can remove the alpha (legacy) parts of the Bootstrap Token handing in kubeadm at that version.
Examples of now legacy code:

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L125-L129

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L204-L210

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/postupgrade_v17_v18.go#L110-L152

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/controlplane/manifests.go#L170-L172

**Comment by kad** [comment]
I'm planning also to look at this.

**Comment by luxas** [comment]
Thanks!

**Comment by luxas** [comment]
@andrewsykim fixed this in https://github.com/kubernetes/kubernetes/pull/53181 :tada:
