### ISSUE TITLE
Remove the old Kubelet TLS Bootstrapping mode in v1.9

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#447]
Part of #173. We had to re-enable this functionality temporarily in v1.8 to still support v1.7 clusters, but we can safely remove that functionality in v1.9 https://github.com/kubernetes/kubernetes/pull/52188

**Comment by kad** [comment]
I'm planning to work on this item.

**Comment by luxas** [comment]
This is still an issue. Reopening.
@kad Please fix this if you have time.

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/join.go#L224

**Comment by kad** [comment]
@luxas have a look at PR #53917. Hopefully I've made it correctly.
