### ISSUE TITLE
Run Density & Scale testing (kubemark) on top of kubeadm

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#449]
cc @kubernetes/sig-scalability-feature-requests 
This is some of the things we probably want to do in v1.9 in order to gradually move from `kube-up.sh`

Can you please put some pointers here how to run a 1000-node or 5000-node cluster for example with kubemark and extract the right info from those tests?

**Comment by timothysc** [comment]
I don't think they will flip the bill until kubeadm is the default.  I would bump the milestone on this.

**Comment by luxas** [comment]
cc @roberthbailey You had some contact that gradually is moving e2e tests over to using kubeadm, right?
Does this seam feasible?

**Comment by roberthbailey** [comment]
We are doing it slowly. This is in scope, but isn't likely to happen in the 1.9 timeframe unless we get a volunteer to work on it.

**Comment by luxas** [comment]
Ok, let's keep it in v1.9 for now and push it out when we get closer to the dates if nobody picked it up.
Who is/are the person(s)?

**Comment by timothysc** [comment]
@roberthbailey can we bump this out of this milestone?

**Comment by roberthbailey** [comment]
Yes

**Comment by timothysc** [comment]
I'm of the opinion that this should only be enabled at scale if there are folks who are watching this regularly and actively fixing.  This effectively means it's gating on google defaulting to kubeadm.

**Comment by timothysc** [comment]
I'm closing and will aim to try and eliminate the roadblocks to getting 1st classed for google to adopt.
