### ISSUE TITLE
Upgrade etcd version to 3.1.10 in v1.9

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#450]
Requires validation of etcd 3.1.10 from @kubernetes/sig-api-machinery-feature-requests and @kubernetes/sig-scalability-feature-requests.

Also filed #449 to set up similar suites for kubeadm to help this effort.

cc @timothysc @xiang90 @hongchaodeng

**Comment by ncdc** [comment]
What about 3.2.x?

**Comment by liggitt** [comment]
specifically, 3.2.6+ to pick up a fix for https://github.com/coreos/etcd/issues/8411 which can leave an API server with a persistently stale watch cache

**Comment by luxas** [comment]
For new clusters, that'd be ok
Basically I just want to use a version that is validated for the rest of k8s and scale-tested.
If that is 3.2.x, I'm ok with that.

However, an upgrade from 3.0.x to 3.2.y _should work_, but 3.0.x to 3.1.y is definitely safer...

**Comment by luxas** [comment]
Fixed with https://github.com/kubernetes/kubernetes/pull/49393
