### ISSUE TITLE
Allow the user to upgrade to a CI version label like "ci/latest" or "stable"

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#451]
Currently we don't support this in the initial version of `kubeadm upgrade` by design, but it might be worth it to reconsider this... This would be a neat UX and the upgrade to `ci/latest` functionality would be really convenient for the `stable-master` upgrade jobs.
cc @jessicaochen

**Comment by kad** [comment]
@luxas  what do you mean here by `or "stable` ?
I understand upgrade path from X to "ci/latest", but what it mean for "stable" ?

**Comment by luxas** [comment]
@kad well you can be on v1.8.1 and the current stable k8s version is v1.8.6
Then a `kubeadm upgrade apply stable` might make sense...

**Comment by luxas** [comment]
@kad did you want to work on this?

**Comment by kad** [comment]
Yes, sounds interesting to me as well.
