### ISSUE TITLE
Make it possible to set a custom config file in e2e CI tests

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#455]
For example, we want to set some custom args like reduce the kubelet cert expiration time in order to have those certs rotated during e2e time. This would automatically add coverage for that feature. cc @jcbsmpsn 

For this to work, we have to be able to specify a custom kubeadm.yaml file for configuration in the e2e tests.

**Comment by luxas** [comment]
cc @pipejakob @jessicaochen @jamiehannaford Any ideas?

**Comment by pipejakob** [comment]
We're missing an extensions mechanism in kubernetes-anywhere that I think we could really use. I believe the original intent was that anyone who wanted to alter the default behavior would have to fork the repository and manually edit the templates, fighting any merge conflicts in the future when they try to sync from upstream to pick up updates. It would be great to offer extension points that allow you to create new files alongside the existing templates that could add to or modify the behavior of the baseline templates. In this case, we could allow the user to supply `kubeadm.yaml` on disk and have all of its contents override the baseline configuration at initialization time.

**Comment by timothysc** [comment]
This requires an understanding of how the test-infra setup is run and how to dynamically change configs on the fly which may require restarting components.

**Comment by timothysc** [comment]
Closing this due to the grand refactorings we are planning.
