### ISSUE TITLE
Create `[Feature:kubeadm]` e2e tests

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#456]
...under `test/e2e_kubeadm/` in the core kubernetes repo.
e2e tests here should for instance make sure that:
 - At least one node is tainted/labelled with `node-role.kubernetes.io/master=""`
 - `cluster-info` is exposed in a correct manner, and the right `Role` and `RoleBinding` exist
 - The right Node Bootstrap Token RBAC rules exist, the SAR approver is enabled, etc.
 - The `kubeadm-config` ConfigMap exists.
 - API Aggregation features are enabled
 - What else?

@timothysc @pipejakob Ideas?

**Comment by timothysc** [comment]
So this requires segregating into it's own location for future forking.

**Comment by timothysc** [comment]
/assign @fabriziopandini @liztio 

This will be a requirement for some of the HA work in order to validate it.

**Comment by liztio** [comment]
Can we clarify this a little more? What RBAC roles should be expected? What's the "correct manner" for cluster-info to be exposed? What node bootstrap token rules should exist?

**Comment by fabriziopandini** [comment]
@liztio I think that this document can be a good starting point
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#wait-for-the-control-plane-to-come-up.
If I got this right we have to check that kubeadm-- executes properly the steps starting from mark master.

Is there a WIP for this work?

**Comment by liztio** [comment]
@fabriziopandini my WIP is https://github.com/kubernetes/kubernetes/pull/62665. 

I'm feeling a bit weird about this though... most of these things aren't really E2E tests, they're more like integration tests.

**Comment by timothysc** [comment]
@liz I'm totally ok with getting what you have hooked up, and we can create a new tracking issue with a list.  You could easily back-hole on this, and we could federate the work items across the SIG for this type of work.

**Comment by luxas** [comment]
Reopening until we've got these running automatically

**Comment by timothysc** [comment]
Per discussion, I think we should separate out the automation from the enablement so move to close.

**Comment by liztio** [comment]
Closed in favor of #813
