### ISSUE TITLE
Create a kubeadm upgrade stable-master e2e CI suite

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#457]
In the same manner as https://github.com/kubernetes/kubeadm/issues/401 is set up, we should engineer upgrade tests (like https://github.com/kubernetes/kubeadm/issues/402). This in order to quickly catch upgrading regressions from v1.8 to HEAD.

**Comment by jessicaochen** [comment]
Test is created and running. Looks like kubeadm upgrade from stable -> head fails:

> FATAL: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: [timed out waiting for the condition]

Do not have the time right now to dig further.

**Comment by luxas** [comment]
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-upgrade-stable-master is green and passing now
