### ISSUE TITLE
kubeadm should have custom flags for net.IP slice

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#46]
_From @errordeveloper on October 3, 2016 11:38_

Right now we do it an ad-host fashion, but should do it properly instead, may be we just need to make a PR to cobra.

_Copied from original issue: kubernetes/kubernetes#33921_

**Comment by luxas** [comment]
Closing this as the values on the API struct has to be `string`s, we just have to parse them at `Run()`-time
