### ISSUE TITLE
kubeadm upgrade apply should read version from config file

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubeadm#460]
version flag should be optional if --config is specified and kubernetesVersion key is specified in the file.

**Comment by medinatiger** [comment]
@mattymo , I'm happy to take this one on if you haven't got to this.

**Comment by medinatiger** [comment]
@mattymo, when I tried, it seems that the Kebernetes-Version flag is optional. If it's not specified, it will pick up latest. Can you elaborate a bit more on this issue?

**Comment by medinatiger** [comment]
please ignore my question. I got it now.
