### ISSUE TITLE
kubeadm token create cannot read from config file

### ISSUE THREAD

**Issue by mattymo** [kubernetes/kubeadm#461]
Choose one: FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):v1.8.0-beta1

## What happened?
kubeadm token create can only work with a specified token string. Using a config file keeps the token off of bash history.

**Comment by luxas** [comment]
@fabriziopandini can I assign you this?

**Comment by fabriziopandini** [comment]
Yes!

**Comment by timothysc** [comment]
@fabianofranz will try to complete in this cycle.
