### ISSUE TITLE
Add / update kubeadm upgrade instructions for 1.7 -> 1.8

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#469]
During the upgrade testing for the kubeadm 1.8 release cycle, it was discovered that the existing [1.6 -> 1.7 upgrade instructions](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-7/) don't quite work for upgrading from 1.7 -> 1.8.

This is because the existing instructions ask the user to upgrade all of the OS packages at once, which upgrades kubeadm and kubelet at the same time. The problem here is that the proper way to do an upgrade is to first upgrade the control plane, then upgrade the kubelets on master/nodes. However, our steps upgrade kubelet first (along with kubeadm), before kubeadm is used to upgrade the control plane, and this causes problems.

However, if the cluster admin specifically upgrades kubeadm first (in order to use it to upgrade the control plane) and leaves kubelet alone, the kubelet flags config file that is bundled with kubeadm can cause the kubelet to crashloop if it is restarted before its package is upgraded.

Whether we add these details into the existing upgrade guide, or create a new upgrade guide, we should make sure that users have a clear, working path to upgrade their 1.7.x clusters to 1.8.x.

@kubernetes/sig-cluster-lifecycle-bugs

**Comment by pipejakob** [comment]
CC @jessicaochen, who I believe has the most context on this. If anyone else wants to pick this up, please coordinate with her to review for accuracy.

**Comment by luxas** [comment]
> 1.6 -> 1.7 upgrade instructions don't quite work for upgrading from 1.7 -> 1.8.

That is expected. You MUST NOT use those instructions to upgrade from v1.7 to v1.8 or your cluster will break. Using `kubeadm upgrade` is the _only_ supported way.

**Comment by pipejakob** [comment]
> That is expected. You MUST NOT use those instructions to upgrade from v1.7 to v1.8 or your cluster will break. Using kubeadm upgrade is the only supported way.

I should clarify: even if you use `kubeadm upgrade`, our overall flow of when to upgrade which OS package is still broken (if you try to upgrade both kubeadm and kubelet at the same time, before running `kubeadm upgrade`, then we incorrectly have a newer version of kubelet than the control plane, and I thought that this was causing nil panics).

Regardless, it sounds like we still need to write out the user documentation for how to upgrade clusters from 1.7.x to 1.8.x.

**Comment by luxas** [comment]
> Regardless, it sounds like we still need to write out the user documentation for how to upgrade clusters from 1.7.x to 1.8.x.

That's done: https://github.com/kubernetes/kubernetes.github.io/blob/release-1.8/docs/tasks/administer-cluster/kubeadm-upgrade-1-8.md

**Comment by pipejakob** [comment]
Oh, fantastic! We weren't sure if it had been documented yet, hence the issue. I'll close this, then.
