### ISSUE TITLE
kubeadm/images: make registry configurable

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#47]
_From @errordeveloper on September 30, 2016 10:30_

We should allow users to use their own private registry instead of GCR. We should also make it clear what images need to be mirrored, ideally we should implement a helper for doing pull/retag/push (i.e. `kubeadm util mirror-images`), as we have a handful of images and users will have to write scripts to do it. People will have to mirror images continuously, when we provide upgrades, so helper would be very handy.

_Copied from original issue: kubernetes/kubernetes#33828_

**Comment by luxas** [comment]
We have a first PR for that already here: https://github.com/kubernetes/kubernetes/pull/35948

**Comment by luxas** [comment]
This is fixed now on master.
