### ISSUE TITLE
"kubeadm config upload from-flags" shouldn't upload kubeadm version

### ISSUE THREAD

**Issue by medinatiger** [kubernetes/kubeadm#470]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT
## Versions

**kubeadm version** (use `kubeadm version`):
root@k8s-m:~# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-rc.1", GitCommit:"c8a2429cb355d357d90174d3744a930dbd0bbff6", GitTreeState:"clean", BuildDate:"2017-09-23T01:24:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
root@k8s-m:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
root@k8s-m:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty

- **Kernel** (e.g. `uname -a`):
Linux k8s-m 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
"kubeadm config upload from-flags" tries to pull the version for kubeadm instead of the kube cluster. If the kubeadm is a CI version w/o a stable label, things get weird.

root@k8s-m:~# kubeadm config upload from-flags
unable to fetch file. URL: "https://dl.k8s.io/release/stable-1.8.txt" Status: 404 Not Found
root@k8s-m:~# kubeadm config upload from-flags

## What you expected to happen?
kubeadm shouldn't try to care its own version when upgrading cluster config.

## How to reproduce it (as minimally and precisely as possible)?

kubeadm config upload from-flags

On a v1.7.6 cluster, When we use v1.8.0-rc.1 kubeadm

**Comment by pipejakob** [comment]
This was also reported in https://github.com/kubernetes/kubeadm/issues/466.

**Comment by medinatiger** [comment]
The following command works.

kubeadm config upload from-flags --kubernetes-version=v1.7.6 

Anyway, when kubernetes-version is not specified, kubeadm should try to get cluster version rather than kubeadm version.
