### ISSUE TITLE
Kubeadm 1.7 -> 1.8 Upgrade Tests Fail To Generate New Config

### ISSUE THREAD

**Issue by jessicaochen** [kubernetes/kubeadm#472]
Looks like this line is not doing what the author intended. Instead of funneling the output to the `originalConfigPath`, it put the output on stdout and tried to read `originalConfigPath`

	// modify config with specified k8s version
	if _, _, err := RunCmd("sed",
		fmt.Sprintf(`s/kubernetes_version=.*$/kubernetes_version=%s/`, v),
		backupConfigPath, ">", originalConfigPath); err != nil {
		return err
	}

https://github.com/kubernetes/kubernetes/blob/3b755e43700402492d7a26240716fdefc21141b7/test/e2e/framework/nodes_util.go#L129

Error [1.7 -> 1.8 upgrade tests](https://k8s-testgrid.appspot.com/sig-cluster-lifecycle#kubeadm-gce-upgrade-1.7-1.8) are running into :

> error running sed [s/kubernetes_version=.*$/kubernetes_version=1.8.0-rc.1.14+3b755e43700402/ /workspace/kubernetes-anywhere/.config.bak > /workspace/kubernetes-anywhere/.config]; got error exit status 2, stdout "\n.phase1.num_nodes=4\n.phase1.cluster_name=\"e2e-77\"\n.phase1.ssh_user=\"\"\n.phase1.cloud_provider=\"gce\"\n\n.phase1.gce.os_image=\"ubuntu-1604-xenial-v20160420c\"\n.phase1.gce.instance_type=\"n1-standard-1\"\n.phase1.gce.project=\"kube-gce-upg-1-4-1-5-upg-clu-n\"\n.phase1.gce.region=\"us-central1\"\n.phase1.gce.zone=\"us-central1-f\"\n.phase1.gce.network=\"default\"\n\n.phase2.installer_container=\"docker.io/colemickens/k8s-ignition:latest\"\n.phase2.docker_registry=\"gcr.io/google-containers\"\n.phase2.kubernetes_version=1.8.0-rc.1.14+3b755e43700402\n.phase2.provider=\"kubeadm\"\n.phase2.kubelet_version=\"gs://kubernetes-release-dev/bazel/v1.7.7-beta.0.33+7484ce45c266a7/bin/linux/amd64/\"\n.phase2.kubeadm.version=\"gs://kubernetes-release-dev/bazel/v1.8.0-rc.1.14+3b755e43700402/bin/linux/amd64/\"\n.phase2.kube_context_name=\"\"\n.phase2.kubeadm.master_upgrade.method=\"upgrade\"\n\n.phase3.run_addons=y\n.phase3.weave_net=y\n.phase3.kube_proxy=n\n.phase3.dashboard=n\n.phase3.heapster=n\n.phase3.kube_dns=n\n", stderr "sed: can't read >: No such file or directory\nsed: can't read /workspace/kubernetes-anywhere/.config: No such file or directory\n"
> not to have occurred

**Comment by jessicaochen** [comment]
Another interesting thing to node is the version outputted was 1.8.0-rc.1.14+3b755e43700402. The lack of a v may be an issue. Would be worth checking.

> phase2.kubernetes_version=1.8.0-rc.1.14+3b755e43700402

**Comment by jessicaochen** [comment]
@krousey Any idea if there is some process to get the fix into a released version of 1.8 (as opposed to only in ci)?

**Comment by luxas** [comment]
I think this is coming in v1.8.1
