### ISSUE TITLE
Kubeadm 1.7 -> 1.8 Upgrade Tests generate invalid config

### ISSUE THREAD

**Issue by krousey** [kubernetes/kubeadm#477]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/periodic-kubernetes-e2e-kubeadm-gce-upgrade-1-7-1-8/118#master-upgrade-sig-cluster-lifecycle-master-upgrade

`error: Invalid numeric literal (while parsing '1.8.1')`

**Comment by jamiehannaford** [comment]
@krousey Was this fixed by https://github.com/kubernetes/kubernetes/pull/53346? If so, can we close this out?
