### ISSUE TITLE
kubeadm 1.7-blocking tests consistently failing

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#481]
These tests are consistently failing, and are blocking a patch release of 1.7 now:

https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-kubeadm-1.6-on-1.7
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-kubeadm-upgrade-1.6-1.7

**Comment by pipejakob** [comment]
Pull request for fixing: https://github.com/kubernetes/test-infra/pull/4847

**Comment by pipejakob** [comment]
I just merged the fix (fingers crossed). These jobs only trigger on new commits, so I'll see if I still have permissions to manually rerun prow jobs to kick off new runs.

**Comment by pipejakob** [comment]
I found another error for the upgrade test, with a fix here: https://github.com/kubernetes/test-infra/pull/4858

**Comment by pipejakob** [comment]
The "1.6 on 1.7" job is back to green:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-1-6-on-1-7/622

I still need a new run of the upgrade test to confirm its fixes.

**Comment by pipejakob** [comment]
The upgrade test is running again now, with only two failing tests:

* CustomResourceDefinition resources Simple CustomResourceDefinition creating/deleting custom resource definition objects works [Conformance]
* [k8s.io] Downward API should provide pod and host IP as an env var [Conformance]

The first failure makes sense, because this test is erroneously running newer e2e tests than the control plane (a known issue), but I'm not sure about the second. It's likely a newer test that isn't expected to pass against the 1.6 control plane.

**Comment by pipejakob** [comment]
The second test is potentially a legitimate failure. This test does seem to exist in the `release-1.7` branch, so it should be expected to pass after upgrading a cluster from 1.6 to 1.7, but since we're erroneously running the 1.8 version of the e2e tests, it's possible that the test function itself has changed in ways that aren't expected to pass against a 1.7 control plane.

**Comment by pipejakob** [comment]
I don't know if this should be closed yet. There are still failures in the upgrade test that might need further triaging before the next 1.7.x release, and regardless, we would still like to fix the job to use the correct e2e tests so this job would become completely green.

**Comment by jamiehannaford** [comment]
@pipejakob Are we able to apply the correct e2e tests or is it unfixable at the moment?

**Comment by pipejakob** [comment]
It is fixable by anyone who has the time. This is something that @jessicaochen was working on before her vacation, and I believe she'll be back next week. But, if anyone else has the bandwidth, I'm sure she would appreciate the help!

My understanding of the problem is that Jessica added new code in the e2e testing framework in Kubernetes to support testing kubeadm upgrades, and this code is now on `master` and `release-1.8`, but in order to exercise the upgrade from 1.6 -> 1.7 and then run the 1.7 e2e tests, we'll need to backport that new code to the `release-1.7` branch so it actually exists alongside the 1.7 version of the e2e tests. As a shortcut, since the code exists in the 1.8 e2e tests, we're using those, but that means we're also running a few tests that aren't expected to succeed against older cluster versions, hence the few failures.

So if anyone wants to, they can trace through Jessica's recent PRs and figure out what patches need to be cherrypicked to `release-1.7`. I believe @krousey also has a lot of context on what needs to be done, and might be able to offer guidance.

**Comment by luxas** [comment]
/assign @krousey @jessicaochen 

Whoever of you all that get to it first can do it :)

**Comment by krousey** [comment]
I have done some work on the upgrade framework side and fixed bugs there, but I am not familiar enough with the kubeadm upgrade flow (through kubernetes anywhere) to be able to fix the most recent bug as seen in https://k8s-testgrid.appspot.com/release-1.8-all#periodic-kubernetes-e2e-kubeadm-gce-upgrade-1-7-1-8&sort-by-failures=

It would be pointless to backport @jessicaochen's work and my fixes until we can get this working.

**Comment by luxas** [comment]
This seems to be fixed now. Thanks!
