### ISSUE TITLE
Tokens should be stripped from `kubeadm-config` config map

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubeadm#485]
This isn't part of the persistent config for a cluster but rather a point in time thing for init.  For clarity and security this should be stripped out of the configmap.

/cc @luxas @mattmoyer

**Comment by luxas** [comment]
Yes, I agree. Let's fix this in v1.8.1 if possible, but not v1.8.1 blocking.

**Comment by fabriziopandini** [comment]
I will take a look at this tomorrow or during the week end.
What about `tokenTTL`?

**Comment by jbeda** [comment]
tokenTTL is incidental and can probably be stripped too.  But the key thing is to remove secret stuff from something that isn't a secret.

**Comment by mattmoyer** [comment]
Should we add a small note under [known issues](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#known-issues) that mentions the exposure in 1.8.0 clusters?

Proposed note:
> Clusters created or upgraded with `kubeadm` 1.8.0 have a stored copy of the join token in the `kubeadm-config` ConfigMap in the `kube-system` namespace. This could be a security concern if `--tokenTTL=0` was specified. Upgrading to 1.8.1 will sanitize the ConfigMap.

**Comment by mattmoyer** [comment]
Cherry pick for release-1.8 is in https://github.com/kubernetes/kubernetes/pull/53660.

**Comment by luxas** [comment]
@mattmoyer LGTM. It might be v1.8.2 though :)

**Comment by mattmoyer** [comment]
Updated known issues blurb with correct versions:

> Clusters created or upgraded with `kubeadm` 1.8.0 and 1.8.1 have a stored copy of the join token in the `kubeadm-config` ConfigMap in the `kube-system` namespace. This could be a security concern if `--tokenTTL=0` was specified. Upgrading to 1.8.2 will sanitize the ConfigMap.

**Comment by luxas** [comment]
Closing as fixed
