### ISSUE TITLE
dpkg: error processing package kubeadm (--configure):  subprocess installed post-installation script returned error exit status 127

### ISSUE THREAD

**Issue by sea475190** [kubernetes/kubeadm#488]
Hi I am new to Kubernates and GitHub.
I am trying to install Kubeadm on Ububtu. I have followed Kubernates docks for installing kubeadm.
I am working in an organisation network.
While running following command: apt-get install -y kubelet kubeadm kubectl
I am getting following result:

root@sj-VirtualBox:~# apt-get install -y kubelet kubeadm kubectl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
kubeadm is already the newest version.
kubectl is already the newest version.
kubelet is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up kubeadm (1.8.0-01) ...
/var/lib/dpkg/info/kubeadm.postinst: 25: /var/lib/dpkg/info/kubeadm.postinst: systemctl: not found
dpkg: error processing package kubeadm (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 kubeadm
E: Sub-process /usr/bin/dpkg returned an error code (1)

I checked docker pull/run , it is also giving error:

root@sj-VirtualBox:~# docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository hello-world
FATA[0132] Get https://index.docker.io/v1/repositories/library/hello-world/images: dial tcp 52.200.132.201:443: connection timed out 

Please help.

**Comment by luxas** [comment]
Which Ubuntu version do you have?
Only Ubuntu 16.04+ is supported.

**Comment by luxas** [comment]
I think you need to upgrade to Ubuntu 16.04 that has systemd installed
