### ISSUE TITLE
should kubeadm have an assets abstraction?

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#49]
_From @errordeveloper on October 3, 2016 12:0_

It'd help to implement dry-run mode, tarball export or other things.

_Copied from original issue: kubernetes/kubernetes#33926_

**Comment by mikedanese** [comment]
_From @errordeveloper on October 3, 2016 12:21_

We currently write files from every other function, and it's not exactly consistent how it happens and what helper funcs are used for doing it. However, in some cases this provides us with an ability to have more user-friendly error message, which is something we will need to ensure assets abstraction would be capable of. We shouldn't have to document files we write, if we have dry-run mode, or good logging etc. We could permit some files, e.g. PKI assets or static pods to exists on disk before `kubeadm init`, which would be convenient way of not having to implement too many extra flags...

**Comment by mikedanese** [comment]
_From @errordeveloper on October 3, 2016 12:23_

We could add validation of existing files could also come into this, and even warn about deprecated files.

**Comment by mikedanese** [comment]
_From @luxas on October 25, 2016 20:35_

@errordeveloper Can I close this?
It doesn't seem like we're going that way...

**Comment by luxas** [comment]
Closing, @errordeveloper comment if you strongly disagree...
