### ISSUE TITLE
Support etcd upgrade in `kubeadm upgrade`

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubeadm#490]
Now that we are defaulting to a newer etcd (https://github.com/kubernetes/kubeadm/issues/450) in kubeadm we need to support upgrade in `kubeadm upgrade`.

@luxas -- is this on your radar?  I couldn't find an existing issue or PR.

**Comment by xiang90** [comment]
if you do not care about rollback, it should just work. or you'd backup before doing upgrades. we are in the process of designing rollback though.

**Comment by luxas** [comment]
@xiang90 Let's say we do want to backup; how do we do that in the simplest possible way?
And then upgrade; and something fails. How do we rollback to the earlier state?

**Comment by timothysc** [comment]
Backup can be done many different ways, we should spell it out in the instructions and possibly a warning message.  Roll-back can be an issue.

**Comment by luxas** [comment]
Is kubeadm doing that for you automatically in scope? I guess so, as we do promise a seamless experience...

**Comment by jamiehannaford** [comment]
etcd is a part of the control panel, so it should be within kubeadm's scope IMO. It'd probably be something like this:

1. snapshot etcd data dir
2. snapshot etcd manifest
3. update PodSpec of static pods to new version
4. health check
5. rollback to previous PodSpec if unhealthy or if user manually triggers

If we had the operator, however, we could do this in 1 API call and have the operator handle everything for us (including rollback too when that gets added).

We could also document this instead if we don't want to take on the risk.

**Comment by luxas** [comment]
Talked about this in the SIG meeting today. High-level 3.0.17 -> 3.1.10 upgrade prereqs:
Basically, the `kubeadm upgrade apply` will need to do this when upgrading from `v1.8.x` to `v1.9.y`:
1) Add some kind of flag, defaulting to true, that specifies whether to upgrade etcd or not
2) Move /etc/kubernetes/manifests/etcd.yaml to the backup directory
3) Write a new etcd manifest to /etc/kubernetes/manifests/etcd.yaml (upgraded, with 3.1.10) (edited)
4) Test whether things work and conditionally proceed
   - if not ok, rollback the backup manifest

Relevant file: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/staticpods.go

@sbezverk will help out with this, awesome and thanks!

**Comment by luxas** [comment]
meeting notes: https://docs.google.com/document/d/16CEsBSSGm3sMpvB_cFnKnqqi1OxhIcyX3lVwBpIyMHc/edit#

video will be up shortly

**Comment by sbezverk** [comment]
@luxas @jamiehannaford : I started looking into this and have a couple of questions.  
- should new etcd image be pre pulled? if yes, should it be done unconditionally or only in the case of etcd upgrade being true?
- new version for etcd image, should it correspond to the target version of k8s or it can be independent and can be specified as one of the parameters?

**Comment by jamiehannaford** [comment]
@sbezverk 

> should new etcd image be pre pulled? if yes, should it be done unconditionally or only in the case of etcd upgrade being true?

Yes, I think so, since that's what we do for DaemonSets. I'd expect you'd run a temporary pod that would allow the kubelet to pull the image. This would only be done if the user has indicated they want to upgrade etcd. 

> new version for etcd image, should it correspond to the target version of k8s or it can be independent and can be specified as one of the parameters?

Good question. I'd expect us to pin the etcd version depending on what the k8s release expects - we shouldn't allow arbitrary versions IMO. I'm not sure whether there's an easy way to infer the supported etcd version for a specific k8s release. I think @timothysc has been working on this, WDYT?

**Comment by luxas** [comment]
> new version for etcd image, should it correspond to the target version of k8s or it can be independent and can be specified as one of the parameters?

It should be the validated etcd version for the right k8s version. I don't think it needs to be configurable. You can use the config file in any case if you really must override it, but then you're on your own.
