### ISSUE TITLE
Restarting kubelet leads to Node NotReady

### ISSUE THREAD

**Issue by camflan** [kubernetes/kubeadm#492]
## What keywords did you search in kubeadm issues before filing this one?
Kubelet, NotReady

## Is this a BUG REPORT or FEATURE REQUEST?
Bug Report

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: linode
- **OS** (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`): `Linux node-1 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?
After bootstrapping a cluster, I ran `systemctl restart kubelet`. This node was then marked as `NotReady` when running `kubectl get nodes`.

## What you expected to happen?
I expected all nodes to be `Ready`

## How to reproduce it (as minimally and precisely as possible)?
Bootstrap cluster with kubeadm, manually restarting kubelet

## Anything else we need to know?
Removing --rotate-certificates from `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`, reloading configuration and restarting kubelet brought the node back online

**Comment by f0** [comment]
@camflan its a known bug  https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#known-issues

**Comment by DanielZhangQD** [comment]
@camflan @f0 
Hi camflan, f0
Could you please help update which pull request fixed this issue exactly?
I did not find it in the changelog-since-v180 nor in the git logs of v1.8.1.

Thanks,
Daniel
