### ISSUE TITLE
Document replacement for KUBE_PREFIX_REPO in 1.8

### ISSUE THREAD

**Issue by blankmail** [kubernetes/kubeadm#493]
## What keywords did you search in kubeadm issues before filing this one?
KUBE_PREFIX_REPO

## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST
## Versions
**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"

- **Cloud provider or hardware configuration**:
VMWare ESXi 5

- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- **Kernel** (e.g. `uname -a`):
Linux HOSTNAME 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
I installed kubeadm 1.8 in an offline environment and was following the instructions here. 
https://kubernetes.io/docs/admin/kubeadm/#environment-variables 

I used KUBE_PREFIX_REPO but found out that the environment variables are deprecated in 1.8 as the documentation noted.

## What you expected to happen?
I expect the documentation to show what the replacement to KUBE_PREFIX_REPO is. The documentation just says the environment variables will stop functioning.

## How to reproduce it (as minimally and precisely as possible)?
I docker save'd all the images mentioned in the following link for 1.8 and loaded it into a private registry.
https://kubernetes.io/docs/admin/kubeadm/#running-kubeadm-without-an-internet-connection

I set KUBE_PREFIX_REPO to be my private registry and ran "kubeadm init --kubernetes-version v1.8.0". /var/log/syslog shows that kubelet constantly tries to reach out to gcr.io to PullImage but it fails.

**Comment by luxas** [comment]
You can set `.imageRepository` in the config file, as outlined in https://kubernetes.io/docs/admin/kubeadm.

Could you please send a docs PR to make that more clear? Thanks!

**Comment by luxas** [comment]
cc @jamiehannaford this is also related to docs

**Comment by fabriziopandini** [comment]
done in https://github.com/kubernetes/website/pull/6103
