### ISSUE TITLE
Machine readable output from kubeadm commands

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubeadm#494]
(original FR by tamalsaha)

[Feature Request]

We would like to compose the output from `kubeadm upgrade plan` command to our GO binary. It will be very helpful if `kubeadm upgrade` could return the output in machine readable form (json/yaml). 

--------
(edits by: neolit123)

KEP: 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/20190506-kubeadm-machine-output.md

status / supported commands:

- [x] `kubeadm config images list`
- [x] `kubeadm token list`
- [x] `kubeadm upgade plan`: https://github.com/kubernetes/kubernetes/pull/108447
- [x] `kubeadm certs check-expiration`: https://github.com/kubernetes/kubernetes/pull/123372
- [ ] can we make `kubeadm init` with machine readable output print the join command + token only?
do other commands need machine readable output?

**Comment by luxas** [comment]
Thanks! I'm open to reviewing a short design proposal for this if you can help making that possible. i.e. What exactly would you like to see, what's the use case, etc.

**Comment by luxas** [comment]
Moving out of the v1.9 milestone, as it won't fit into the release anymore at this point
@tamalsaha can you provide a short status update on where we are with this feature?

**Comment by errordeveloper** [comment]
I'd help if you could suggest an example of a kind JSON/YAML object you'd like to see instead of plain log lines kubeadm currently offers!

**Comment by stealthybox** [comment]
Is this something that can be achieved by vendoring kubeadm into your go binary directly?
An example of the desired output could also be helpful.

**Comment by spiffxp** [comment]
/remove-help
I don't think this meets [the criteria for `help wanted`](http://git.k8s.io/community/contributors/devel/help-wanted.md). Please add back via `/help` if I'm incorrect

**Comment by timothysc** [comment]
/assign @detiber  

This will likely dovetail with cluster-api work 
Ideally we will start to refactor the code to be more consumable from an import perspective.  This is very similar to other work we had done on sonobuoy. 

/cc @chuckha @vincepri

**Comment by fabriziopandini** [comment]
IMO machine readable output (ideally for all the kubeadm commands) and provide better support for kubeadm vendoring are two separated problems.
The latter relates to https://github.com/kubernetes/kubeadm/issues/1205, so IMO this issue should focus only on the first

**Comment by bart0sh** [comment]
@neolit123 @fabriziopandini  I can work on this after https://github.com/kubernetes/kubernetes/pull/75633 is merged.

@tamalsaha Is it still needed for you?

**Comment by tamalsaha** [comment]
Thanks for asking @bart0sh ! This will be still helpful.

**Comment by neolit123** [comment]
i think we need to draw the boundary of what is machine readable though.
so let's have some discussion before jumping into PRs...

the whole output of init, might be out of scope for now, because even if we put it in fields in a structure, the will just end up as lines of text. so this type of wrapping in a machine readable object is not needed.

however at the end of `kubeadm init` there is the join command which is useful to have machine readable.

i see this in the lines of
```
$ kubeadm init:
....
{
  kubeadmLog: <big log here>
  errors: <optionally if there is an error>
  joinCommand: .....
}
```

```
$ kubeadm ... --print-join-command --output=json
{
  joinCommand: ....
}
```

```
$ kubeadm upgrade plan
{
  plan: {
    ...
  }
}
```


but we should probably go one command at a time, starting with the smaller ones.
also using some sort of a mechanic to marshal any type of object.

@bart0sh 
next to token list, do you have any other commands in mind?
i think we should leave `plan`, `init` `join` for last....
@kubernetes/sig-cluster-lifecycle

**Comment by bart0sh** [comment]
@neolit123 no, I didn't have anything in particular, but I like the overall idea to have parseable output from kubeadm commands. Why not to do 'upgrade plan' if there is a clear  interest for it?

@tamalsaha Can you show us what you'd like to see in 'upgrade plan' JSON or YAML output?

**Comment by neolit123** [comment]
`plan` is broken ATM, so i need to look at what the problem is.
but if we are doing machine readable we should support both YAML and JSON always because `kubeadm version` already does that `-o, --output string   Output format; available options are 'yaml', 'json'`

**Comment by neolit123** [comment]
@bart0sh could you please start with `kubeadm config images list` ?
so that we can define how are we going to do the utility that can marshal any object for any command..

**Comment by bart0sh** [comment]
yes, the general idea is to support -o, --output yaml, json. This is what I did for 'token list'.

I'll do 'kubeadm config images list' then.

**Comment by bart0sh** [comment]
@neolit123 done, please review [PR 75878](https://github.com/kubernetes/kubernetes/pull/75878)

**Comment by neolit123** [comment]
posted some ideas in this comment on how we may handle this as a common utility:
https://github.com/kubernetes/kubernetes/pull/75878#discussion_r270383820

**Comment by bart0sh** [comment]
I'll answer to your comment here.

> we need to define a unified way that handles all possible output format cases in a utility function.
> we don't want to handle if format == "text" in a lot of places.

Agree with this.


> we want to define all outputFormats as constants.
> OutputFormatText = "text"
> OutputFormatJSON = "json"
> OutputFormatYAML = "yaml"

not sure we need this. It's better to keep this logic only in one module.


> possibly the location of this should be cmd/kubeadm/app/util/machinereadable.go

If we want to handle *all* output formats then the name should be different in my opinion.
I'd propose cmd/kubeadm/app/util/output.go

> we can do marshaling and printing in the same function:
> PrintMachineReadable(target, input *bytes.Buffer, data interface{}, outputFormat string) error {
>  if outputFormat == "text" {
>      if input == nil {
>         return errors.Errorf("PrintMachineReadable input is nil for outputFormat: %s", outputFormat)
>      }
>       fmt.Fprintf(target, input.String())
>       return nil
>   }
>   // marshall cases here in a utility function that can be unit tested.
> }
>
>// usage:
>var buf bytes.Buffer
>// write images to buf for format "text"
>PrintMachineReadable(os.Stdout, &buf, someStruct, format)

I'd propose to implement conversion from data structures to output text. The main API, let's call it ConvertToOutputFormat(data interface{}, outputFormat string) would return string representation of the output. Then caller can do whatever needed with this - parse, print, write to file, parse, etc.

>it is still unclear to me how to handle commands like init, join, reset and upgrade

I'd propose to do it the same way - collect the output to the data structure and use the same API.

**Comment by neolit123** [comment]
>> we want to define all outputFormats as constants.
>> OutputFormatText = "text"
>>  OutputFormatJSON = "json"
>> OutputFormatYAML = "yaml"

> not sure we need this. It's better to keep this logic only in one module.

if we define the constants in the same file that has the utility function(s) it would be ideal.
these constants will be used in multiple files so we need them.

> If we want to handle all output formats then the name should be different in my opinion.
> I'd propose cmd/kubeadm/app/util/output.go

it's OK, outputformat.go seems a bit better.

> I'd propose to implement conversion from data structures to output text. The main API, let's call it ConvertToOutputFormat(data interface{}, outputFormat string) would return string representation of the output. Then caller can do whatever needed with this - parse, print, write to file, parse, etc.

ConvertToOutputFormat is OK  for yaml and json.
if "text" is the desired output format, how are we going to print to stdout or stderr?

>> it is still unclear to me how to handle commands like init, join, reset and upgrade

> I'd propose to do it the same way - collect the output to the data structure and use the same API.

i still think we need some sort of wrapper utility:
if "text" - > print to the standard output streams
if "yaml/json" -> append to a buffer or a field in a struct.

i suggest that you open this in a google doc so that:
- we can discuss on the API implementation
- see examples of handling e.g. `config images`, `token list`, `init`... etc.
- have a cleaner overview of the proposal

what do you think?

**Comment by rosti** [comment]
@bart0sh I see where you are going with `PrintMachineReadable`. It's a good idea to have such a function.
However, I propose to start simple and if we need something along those lines, we can certainly retrofit it where it's needed.

Also, +1 for @neolit123 's proposition to start drafting ideas in a gdoc.

**Comment by bart0sh** [comment]
> if we define the constants in the same file that has the utility function(s) it would be ideal.
> these constants will be used in multiple files so we need them.

If they're going to be used in multiple files then we need them. However, I'm having hard time understanding why would we need them outside of outputformat.go

> if "text" is the desired output format, how are we going to print to stdout or stderr?

We're going to call ConvertToOutputFormat(&data, "text"), get the output and print it to stdout or stderr.

> i suggest that you open this in a google doc so that:
>
> we can discuss on the API implementation
> see examples of handling e.g. config images, token list, init... etc.
> have a cleaner overview of the proposal
> what do you think?

I'm finishing a prototype code that uses this API for 'kubeadm version', 'kubeadm token list' and 'kubeadm config images list'. I'm going to create a doc after that as it's going to take longer than writing a code for me.

**Comment by bart0sh** [comment]
> @bart0sh I see where you are going with `PrintMachineReadable`. It's a good idea to have such a function.
> However, I propose to start simple and if we need something along those lines, we can certainly retrofit it where it's needed.

I already started simple (see https://github.com/kubernetes/kubernetes/pull/75633), but it didn't work out it seems.

> Also, +1 for @neolit123 's proposition to start drafting ideas in a gdoc.

Yes, will do.

**Comment by neolit123** [comment]
> If they're going to be used in multiple files then we need them. However, I'm having hard time understanding why would we need them outside of outputformat.go

possibly so that the CLI flags can know about the same formats and so that we can perform validation if case a format is unknown.

> We're going to call ConvertToOutputFormat(&data, "text"), get the output and print it to stdout or stderr.

but, for "text" we need to print immediately to the standard streams after each line and not buffer the output in the "data" object.

> I'm finishing a prototype code that uses this API for 'kubeadm version', 'kubeadm token list' and 'kubeadm config images list'. I'm going to create a doc after that as it's going to take longer than writing a code for me.

sounds good. thanks.

**Comment by bart0sh** [comment]
> possibly so that the CLI flags can know about the same formats and so that we can perform validation if case a format is unknown.

We can also perform validation in the ConvertToOutputFormat and make the CLI code simply defining the flag as it does now.

> but, for "text" we need to print immediately to the standard streams after each line and not buffer the output in the "data" object.

that's a valid point. So far I didn't think of this API as a way to handle output of long-running processes. For 'kubeadm version', 'kubeadm token list' and 'kubeadm config images list' the difference is not even noticeable.

**Comment by bart0sh** [comment]
@neolit123 'kubeadm version' has 'short' output option. Should we consider having it handled by this API as well?

**Comment by neolit123** [comment]
> @neolit123 'kubeadm version' has 'short' output option. Should we consider having it handled by this API as well?

possibly. we want the same code to be used in `version`.

**Comment by bart0sh** [comment]
@neolit123 > we want the same code to be used in version.

then we need to handle 'text', 'short', 'json' and 'yaml'
This would require implementation for 'short' output in other places('token list', 'images list' etc) as far as I understand.

**Comment by bart0sh** [comment]
@neolit123 > but, for "text" we need to print immediately to the standard streams after each line and not buffer the output in the "data" object.

If we really need this, current approach (collect data to some structure and then call output API) would not work. I'd not go that far right now.

P.S. It looks like it's time to create google doc

**Comment by neolit123** [comment]
>> then we need to handle 'text', 'short', 'json' and 'yaml'

> This would require implementation for 'short' output in other places('token list', 'images list' etc) as far as I understand.

we don't want to break "version", by not supporting "short" anymore.
we can possibly treat "short"=="text" in cases where it's not supported or throw an error.

**Comment by neolit123** [comment]
> but, for "text" we need to print immediately to the standard streams after each line and not buffer the output in the "data" object.

we need "text" to work like that, but for other types (json,yaml) we might have to buffer and on finishing the work or on error dump the structure.

**Comment by bart0sh** [comment]
> I'm finishing a prototype code that uses this API for 'kubeadm version', 'kubeadm token list' and 'kubeadm config images list'. I'm going to create a doc after that as it's going to take longer than writing a code for me.

Above PR is what I came up with so far. Please, review.

Now when we have a working prototype I'm going to to write a proposal.

**Comment by neolit123** [comment]
> Above PR is what I came up with so far. Please, review.
> Now when we have a working prototype I'm going to to write a proposal.

the idea in the PR will work, but we also we need to consider:
> but, for "text" we need to print immediately to the standard streams after each line and not buffer the output in the "data" object.

ideally the machine readable support for different commands should be separate PRs, possibly starting from "version".

**Comment by bart0sh** [comment]
@neolit123 
> for "text" we need to print immediately to the standard streams after each line

That would make it impossible to use the same API for text and JSON/YAML output. I need to think about it, but so far I don't know how to implement this.

**Comment by rosti** [comment]
Ok, folks, I think, that we are deviating a bit from the subject at hand. Let's start from the user story and the desired UX:

1. What commands do we want to see in machine readable form and why?
1.1. If users finds that `kubeadm token list` has machine readable form, would they expect that `kubeadm token generate` has it too?
1.2. If users finds that `kubeadm token list` has machine readable form, would they expect that `kubeadm config images list` has it too?
2. What commands should get "short text" and "long text" forms? What is the difference between those two forms? Why each command needs to get each form?

Don't get me wrong here, I am all in for this feature. However, we need to get the user story and UX right via a set of "Do"s and "Don't"s. If we don't do it that way, we can end up with a mash up of incoherent and inconsistent features and having those as a technical debt for quite some time, before we do things right.

Therefore, I am more inclined to think in the terms of Google Docs and KEPs at this point in time, rather than if we should have certain constants or not.

**Comment by bart0sh** [comment]
@rosti Thank you for your comments. I'm preparing google doc where we can discuss this further. Will share it here soon.

**Comment by bart0sh** [comment]
shared with kubernetes-sig-cluster-lifecycle@googlegroups.com

**Comment by bart0sh** [comment]
@rosti, @fabriziopandini @neolit123 I need your help to proceed further with this. 

Current status is: [the PR](https://github.com/kubernetes/kubernetes/pull/75894l) is stuck in the review. Discussion in the design document is not moving anywhere.

Main issue with the PR is that it doesn't implement text output immediately. However, do we really need that? I don't see any need in this in the 'kubeadm token list', 'kubeadm config images list' and  'kubeadm version' areas that my PR touched.

Thoughts?

**Comment by neolit123** [comment]
> Current status is: the PR is stuck in the review. Discussion in the design document is not moving anywhere.

the design proposals should happen in the document. also you have to understand that this ticket has `priority/backlog` for 1.15 and we are allocated to different tasks.

> Main issue with the PR is that it doesn't implement immediate output of the text. However, I'm not sure if we really need that.

we need to be clear that the machine readable output is a much desired, but a secondary use case.
the primary use case is incremental output, one line at a time that kubeadm performs during the runtime of it's commands. with the PR and current gdoc proposal the immediate output is blocked until a command exits.

> At least I don't see any need in this in the 'kubeadm token list', 'kubeadm config images list' and 'kubeadm version' areas that my PR touched.

yes, this is quite true. some commands don't need the immediate line-by-line output.
in my opinion the proposal needs to cover both use cases and we need to write a KEP for that.

Enhancements Freeze is Tuesday, April 30th, EOD PST.

**Comment by astrieanna** [comment]
Could someone link to the google doc referenced in this issue? I'm having trouble finding it.

**Comment by akutz** [comment]
Hi @astrieanna,

I believe you can find it from https://github.com/kubernetes/enhancements/issues/1053.

**Comment by astrieanna** [comment]
Maybe the help wanted label should be removed until the KEP is implementable?
(as is, this doesn't seem to fit [the definition](https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md))

**Comment by neolit123** [comment]
@astrieanna +1

**Comment by neolit123** [comment]
moving to 1.17

**Comment by neolit123** [comment]
moving to 1.18. in 1.17 kubeadm adds machine readable output for `kubeadm config images list`.
thanks to @bart0sh

**Comment by pacoxu** [comment]
I submitted the PR https://github.com/kubernetes/kubernetes/pull/108447 to fix this.

**Comment by pacoxu** [comment]
> * can we make `kubeadm init` with machine readable output print the join command + token only?
>   do other commands need machine readable output?

@neolit123 is this the next step? 
If this is expected, I may give it a try.

**Comment by neolit123** [comment]
it's open for discussion, i guess. it was something we spoke about in the past.

**Comment by neolit123** [comment]
added `certs check-expiration` as a recent FR:
https://github.com/kubernetes/kubeadm/issues/494
PRs welcome.

**Comment by neolit123** [comment]
> kubeadm certs check-expiration

a user reminded us recently that we lack the above ^

**Comment by carlory** [comment]
> kubeadm certs check-expiration

I would like to pick this up
/assign

**Comment by neolit123** [comment]
> > kubeadm certs check-expiration
> 
> I would like to pick this up /assign

thanks, seems doable before march 6th - core freeze
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.30

**Comment by neolit123** [comment]
after https://github.com/kubernetes/kubernetes/pull/123372 merged we can track individual options as separate tracking issues.
