### ISSUE TITLE
Remotely callable `kubeadm upgrade plan`

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubeadm#495]
[Feature Request]

We would like to show the tables that tells user about potential upgrade options from `kubeadm upgrade plan` command in a webpage. Currently this command needs (i guess) to be run from the master machine for the local dir checks. This means the api server backing the webpage needs to do ssh into the master. 

Can a lighter version of `upgrade plan` command be supported that skips the local dir checks and only do the parts that checks against kube api server and remote dl-stable urls? This will allow calling this without needing to ssh into master instance.

**Comment by luxas** [comment]
Did you check whether this works already or not?
In case it doesn't, where is it failing. We might be able to fix this (maybe even in v1.8.x)

Please give a bit more details. Thanks!

**Comment by luxas** [comment]
Moving out of v1.9 milestone, please provide more information here @tamalsaha

**Comment by stealthybox** [comment]
This sounds like an external application that would vendor kubeadm.
You would probably host the app on the cluster with hostPath mounts and access the webpage using a service.

@luxas I'm not aware of any webpages that kubeadm can serve.
Is this something that has prior art?

**Comment by errordeveloper** [comment]
We don't really have any APIs that are exposed via the apiserver, so this is a pretty big feature to ask for.

Additionally, if we had an API, how would expect to find the plan? Kubernetes API doesn't send a body on a response to e.g. a POST (at least as far as I am aware)

However, one thing you can do via the API is run it in a pod and looking find the output in the logs. Which is probably close to what @stealthybox is suggesting.
