### ISSUE TITLE
discuss CA checksum flag for kubeadm join

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#50]
_From @errordeveloper on October 3, 2016 11:31_

It could prevent MITM, where attacker has guessed the JWS token, yet hasn't provided the same CA certificate.

_Copied from original issue: kubernetes/kubernetes#33918_

**Comment by luxas** [comment]
@jbeda Is this something your new proposal will address? I guess so...

**Comment by jbeda** [comment]
Yeah -- feel free to close this and point it at the feature comment.  If/when this results in a proposal we'll open new issues around that.
