### ISSUE TITLE
unable to load kernel module "configs"

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubeadm#501]
Running on ARM
```
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.8.1
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks
[preflight] The system verification failed. Printing the output from the verification:
OS: Linux
KERNEL_VERSION: 4.9.24-v7+
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
DOCKER_VERSION: 1.13.1
DOCKER_GRAPH_DRIVER: overlay
[preflight] WARNING: Running with swap on is not supported. Please disable swap or set kubelet's --fail-swap-on flag to false.
	failed to parse kernel config: unable to load kernel module "configs": output - "modprobe: ERROR: ../libkmod/libkmod.c:557 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.24-v7+/modules.dep.bin'\n", err - exit status 1
```
cc @luxas

**Comment by luxas** [comment]
You need to fix this:
```
[preflight] WARNING: Running with swap on is not supported. Please disable swap or set kubelet's --fail-swap-on flag to false.
```

I don't know why the other error happens, but this error originates from the System Verification Check: https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system/kernel_validator.go

Maybe you find the problem there, either on your machine or in the system verification check. If you do find an issue, ping sig-node and open an issue in k/k

**Comment by kargakis** [comment]
How can I set kubelet flags with kubeadm? The kernel verification error I was getting was due to missing modules.

**Comment by kargakis** [comment]
`swapoff -a && rm /var/swap` did the trick.

**Comment by dhrp** [comment]
Just as it may help some others; I needed to `kubeadm remove` before I could re-init without getting this "unable to load kernel module "configs"" error.
