### ISSUE TITLE
Make etcd ports configurable

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubeadm#506]
Sometimes users run `kubeadm init` on hosts with pre-existing (but different) etcd clusters which are already bound to 2379/2380. Right now this will fail the preflight checks, but we should probably allow users to specify their own if necessary.

**Comment by luxas** [comment]
I'm not sure whether we should add that deep configurability... why not just set up etcd externally then or reuse the already-running etcd instance?

**Comment by jamiehannaford** [comment]
@luxas To take one example, AFAIK OpenStack uses etcd for its control plane too. I don't think it's safe to have that and K8s using the same datastore due to the risk of key collisions, it also poses additional security concerns. 

In terms of external etcd - sure, they could, but it's raising the barriers for entry IMO. It'd be a lot simpler if they could just use kubeadm and tweak 2 config vars. This goes back to the recurring debate about focus vs usability though 😄

**Comment by lynx-coding** [comment]
Would be interested to have a way to configure etcd ports as well.

**Comment by jamiehannaford** [comment]
Closing this as I'm not sure this is relevant or useful anymore.
