### ISSUE TITLE
kubeadm reset shouldn't assume docker, use crictl

### ISSUE THREAD

**Issue by runcom** [kubernetes/kubeadm#508]
ref https://github.com/kubernetes-incubator/cri-o/issues/1057

kubeadm reset assumes docker when resetting the an host:
```
108         fmt.Println("[reset] Removing kubernetes-managed containers")
109         if err := exec.Command("sh", "-c", "docker ps -a --filter name=k8s_ -q | xargs -r docker rm --force --volumes").Run(); err != nil {
110             fmt.Println("[reset] Failed to stop the running containers")
111         }
```
Since kubernetes is now using the CRI to perform containers operation, I suggest to change docker to [`crictl`](https://github.com/kubernetes-incubator/cri-tools) so that everything is cleaned up correctly even if docker isn't running (cri-o for instance)

@luxas @rhatdan PTAL

**Comment by runcom** [comment]
This should be the command to be used:
```sh
$ sudo /home/amurdaca/go/bin/crictl -r /run/crio.sock sandboxes --quiet | xargs -r sudo /home/amurdaca/go/bin/crictl -r /run/crio.sock rms
```
The socket parameter can be easily customized at command line

Let me know how we want to handle this and I'll work on it :)

**Comment by vbatts** [comment]
There loads of places that it is assumed. Moving to a CRI socket and crictl would be preferred

**Comment by runcom** [comment]
> There loads of places that it is assumed. Moving to a CRI socket and crictl would be preferred

probably kubeadm needs another flag/param/arg to support CRI sockets as well

**Comment by luxas** [comment]
I'm open to a PR here that would use `crictl` if it exists locally on a node and `docker` isn't present on the node. The CRI socket can be a parameter. WDYT?

**Comment by runcom** [comment]
> I'm open to a PR here that would use crictl if it exists locally on a node and docker isn't present on the node. The CRI socket can be a parameter. WDYT?

I'm working on this then :)
