### ISSUE TITLE
fix the realization of kube-proxy mode information ASAP

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubeadm#511]
To use kubeadm build ipvs CI test, we need pass kube-proxy mode information to kubeadm, and this should be done before v1.9, since we haven't realized use `ComponentConfig ` right now, so I chose use feature gate `SupportIPVSProxyMode`. see this pr : #53962
This is definitely a short-term solution, so we need to fix this ASAP, properly before v1.9, maybe. 

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

**Comment by luxas** [comment]
Thanks @Lion-Wei! I'll assign you this and poke here when the parent PR is merged.

**Comment by jamiehannaford** [comment]
Closing this as we already have https://github.com/kubernetes/kubeadm/issues/512
