### ISSUE TITLE
modify the realization of kube-proxy mode

### ISSUE THREAD

**Issue by Lion-Wei** [kubernetes/kubeadm#512]
We need pass kube-proxy mode information to kubeadm so that we can build ipvs CI test before v1.9, since we didn't realized use `ComponentConfig` right now, I chose use feature gate to identify ipvs proxy mode. see this pr: kubernetes/kubernetes#53962

This is definitely a short-term solution, so we need fix this ASAP, maybe before v1.9. 

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

**Comment by xiangpengzhao** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/56311#issue-276510486
