### ISSUE TITLE
DNS Manifests Use IPv4 Loopback in IPv6 Deployments

### ISSUE THREAD

**Issue by danehans** [kubernetes/kubeadm#513]
## What happened?
kubeadm statically assigns an IPv4 loopback within the deployment manifest. For users that require IPv6 only deployments, use of an IPv4 address is not allowed.

## How to reproduce it (as minimally and precisely as possible)?
Deploy k8s using kubeadm and set the api-server address to an IPv6 address. After the deployment is complete, inspect the details of the dns addon deployment and observe the use of an IPv4 loopback.

## Anything else we need to know?
https://github.com/kubernetes/dns/pull/148 added support for DNSv6.

**Comment by luxas** [comment]
Thanks for the issue and PR @danehans; as we saw https://github.com/kubernetes/kubernetes/pull/54437 fixes this issue so I'll close it.

However, I would very much like an "umbrella" issue for tracking IPv6 support in kubeadm generally, where you link to all those related PRs so I and others can easily track the progress.
Can you do that please?
