### ISSUE TITLE
Kubelet does not assign Host IP for pods with HostNetwork

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubeadm#514]
I am trying to test CCM in DigitalOcean using Ubuntu 16.04 64-bit image using Kubeadm 1.8.0. I have found that Kubelet will not assign IP for pods with `HostNetwork: true`, if I start kubelet with `--cloud-provider=true`.  This breaks CNi plugins like Calico #510 .

Reproducible steps:
```
#!/bin/bash

set -x
set -eou pipefail

apt-get update -y
apt-get install -y apt-transport-https curl ca-certificates

curl -fSsL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list

apt-get update -y
apt-get install -y cron docker.io ebtables git kubectl kubelet socat kubeadm ntp || true

cat > /etc/systemd/system/kubelet.service.d/20-pharmer.conf <<EOF
[Service]
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=external"
EOF
systemctl daemon-reload

kubeadm reset
kubeadm init --pod-network-cidr=192.168.0.0/16 --skip-token-print

mkdir -p ~/.kube
sudo cp -i /etc/kubernetes/admin.conf ~/.kube/config
sudo chown $(id -u):$(id -g) ~/.kube/config
```

```
root@c8:~# kubectl get pods -n kube-system -o wide
NAME                         READY     STATUS    RESTARTS   AGE       IP        NODE
etcd-c8                      1/1       Running   0          9m        <none>    c8
kube-apiserver-c8            1/1       Running   0          8m        <none>    c8
kube-controller-manager-c8   1/1       Running   0          8m        <none>    c8
kube-dns-545bc4bfd4-zcr9b    0/3       Pending   0          9m        <none>    <none>
kube-proxy-7ktph             1/1       Running   0          9m        <none>    c8
kube-scheduler-c8            1/1       Running   0          8m        <none>    c8
```
We are supposed to see the external IP of the Host for these pods 9except kube-dns pod).

**Comment by tamalsaha** [comment]
cc: @andrewsykim

**Comment by jamiehannaford** [comment]
@tamalsaha Is this a bug with kubeadm or the kubelet itself?

**Comment by luxas** [comment]
This _might be_ a kubelet bug with the `--cloud-provider=external` flag.
What you need to do with `--cloud-provider=external` is to deploy the external ccm; if you haven't done that, this might even be expected... If you deployed the ccm though and things didn't work as expected, there might be a kubelet bug.

However, pls reopen this in kubernetes/kubernetes, as this is not a kubeadm bug.

**Comment by tamalsaha** [comment]
Reopened in main repo: https://github.com/kubernetes/kubernetes/issues/54965
