### ISSUE TITLE
Better usability for the join token

### ISSUE THREAD

**Issue by 1605200517** [kubernetes/kubeadm#519]
/kind feature
@kubernetes/sig-cli
**What happened**:
I have discovered that if it is not so easy to add new machines if you do not have original joun string output from kubeadm. "Is there a way to generate the whole join command? **I feel like I have to reset the entire cluster to be able to "reach" the magic string**" (c) @alexellis 

**What you expected to happen**:
Likewise in Docker Swarm, you can always tell the master to print a copy-pastable join string to add.. or assimilate? more machines.

Example input:

`kubeadm token string`

Example output:

`kubeadm join --token TOK MASTER_IP:6443 --discovery-token-ca-cert-hash sha256:HASH`

**Anything else we need to know?**:
You are awesome!

(Follow-up from: https://github.com/kubernetes/kubernetes/pull/41663)
@luxas  @mattmoyer  @jamiehannaford

**Comment by mattmoyer** [comment]
+1 on something like this.

Some riffs on this idea:
 - A new `kubeadm ca-cert-hash` command (name TBD) that just prints out the current CA hash. This would basically be the same thing as the `openssl` command we give in the [`kubeadm join` docs](https://kubernetes.io/docs/admin/kubeadm/#kubeadm-join).

 - Add a `--print-join-command` flag for `kubeadm token create` that prints out the whole join command just like `kubeadm init` does. This would hopefully make it easy to automate around by running something like `kubeadm token create --print-join-command >> worker_init.sh` during provisioning.

 - A new command `kubeadm token get <token id>` that gets the full token given the ID, with a `--print-join-command` flag to optionally print the full join command instead of just the token.

**Comment by alexellis** [comment]
Thanks for tagging me in this. Take a note from the UX of Docker Swarm - at any point you can type in `docker swarm join-token worker` and have a command to paste into a worker or to send over SSH. With Kubeadm it's so hard I literally tear down the cluster to add add a new node - I'm pretty confident with CLIs so I'm sure I'm not the only one.

**Comment by cpuguy83** [comment]
Also the init output is so heavy you can't really get just the join command and stash it somewhere... currently I'm resorting to `kubeadm init ... | grep 'kubeadm join --token' > /some_file`.
Would be cool to have a quiet mode where the only thing on stdout is the join command.

**Comment by zcalusic** [comment]
Anyway, what is the way to get that ca-cert-hash right now? Of course, the `kubeadm init` output is long gone at this point... and I didn't save it expecting it would be easy to extract that info later, on demand.

I managed to get join token with `kubeadm token list` and joined another node with `kubeadm join --token`, but it is saying:
```
[validation] WARNING: using token-based discovery without DiscoveryTokenCACertHashes can be unsafe (see https://kubernetes.io/docs/admin/kubeadm/#kubeadm-join).
[validation] WARNING: Pass --discovery-token-unsafe-skip-ca-verification to disable this warning. This warning will become an error in Kubernetes 1.9.
```
So, before it becomes error, how do I pass that parameter? Thanks for any help!

**Comment by mattmoyer** [comment]
@zcalusic the current way is to calculate the hash with OpenSSL like this (run on the master or wherever you have a copy of `/etc/kubernetes/pki/ca.crt`):
```
openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
```

**Comment by wackxu** [comment]
Agree with `--print-join-command`

**Comment by luxas** [comment]
We concluded in the SIG meeting that we're gonna proceed with both https://github.com/kubernetes/kubernetes/pull/55468 _and_ this feature addition.
We'll see in what form exactly in a bit

**Comment by vielmetti** [comment]
This was discussed on the November 21, 2017 zoom call; minutes for that call are at https://docs.google.com/document/d/1deJYPIF4LmhGjDVaqrswErIrV7mtwJgovtLnPCDxP7U/edit#

**Comment by xiangpengzhao** [comment]
I just had a quick look on this but haven't worked on it yet.

>Add a --print-join-command flag for kubeadm token create that prints out the whole join command just like kubeadm init does. This would hopefully make it easy to automate around by running something like kubeadm token create --print-join-command >> worker_init.sh during provisioning.

If we prefer this one, I think there is already the same logic in [bootstrap token create](https://github.com/kubernetes/kubernetes/pull/56025/files#diff-5e955aa2c2f0ab5a527686118d0e0d5cR355). We can use that here.

>A new command kubeadm token get <token id> that gets the full token given the ID, with a --print-join-command flag to optionally print the full join command instead of just the token.

I prefer this one personally. But seems like both the two ideas need more context when implementing, e.g., we need MasterConfiguration to get apiserver advertise address. Currently the `token create` don't have the config.

**Comment by mattmoyer** [comment]
I implemented just the first idea in https://github.com/kubernetes/kubernetes/pull/56185. I'm not opposed to implementing the `kubeadm get` idea also, but we're short on time.

**Comment by fabriziopandini** [comment]
Instead of `kubeadm get`, IMO we should print the hash/the kubeadm join statement at the end of the already existing `kubeadm token list`.

**Comment by luxas** [comment]
I think `kubeadm token list --print-join-command` would be great!

**Comment by alexellis** [comment]
I like that ideas @luxas. I think we could make it less verbose, I find I'm typing very long flags `kubeadm` compared to the `docker` CLI.

`kubeadm token list --verbose`

`kubeadm token list --tokens`

`kubeadm token list --join-token`

**Comment by luxas** [comment]
`kubeadm token list --verbose|-v` works for me as well

**Comment by tzurE** [comment]
Hey, is this done?
How can I get the token to join new nodes in my cluster?

**Comment by mattmoyer** [comment]
@tzurE it's merged but not released yet, it will be part of Kubernetes 1.9 which is [scheduled to be released later this week](https://github.com/kubernetes/features/blob/master/release-1.9/release-1.9.md#timeline).

The new functionality allows you to run this command to join nodes:
```
# on a master node (or any node with admin access to your cluster)
$ kubeadm token create --print-join-command
kubeadm join --token 447067.20b55955bd6abe6c 192.168.99.100:8443 --discovery-token-ca-cert-hash sha256:17023a5c90b996e50c514e63e161e46f78be216fd48c0c3df3be67e008b28889
```

```
# on the new node (copy-pasted from the output above)
$ kubeadm join --token 447067.20b55955bd6abe6c 192.168.99.100:8443 --discovery-token-ca-cert-hash sha256:17023a5c90b996e50c514e63e161e46f78be216fd48c0c3df3be67e008b28889
```

**Comment by tzurE** [comment]
nice, thank you.
is there a solution in the meantime? A way to extract it not using the regular commands?

**Comment by mattmoyer** [comment]
@tzurE see this comment: https://github.com/kubernetes/kubeadm/issues/519#issuecomment-343192126

**Comment by siddharthjoshi745** [comment]
Hi @mattmoyer 

The command "kubeadm token create --print-join-command" works great in 1.9. But i am getting NotReady status on my node. I am Using ubuntu 16.04 with k8s 1.9.0. Any suggestions?

**Comment by luxas** [comment]
@siddharthjoshi745 Deploy a Pod Network like Weave Net (as can be seen in our docs).
Please don't comment on old issues though, instead open a new one if you've found something wrong, or ask for help on Slack
Have a great day!

**Comment by stephaneeybert** [comment]
How can we output just one value ? Xay the token or the discovery token sha, etc..
