### ISSUE TITLE
kubeadm should use k8s.io/client-go where possible

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#52]
_From @errordeveloper on October 3, 2016 11:8_

_Copied from original issue: kubernetes/kubernetes#33914_

**Comment by luxas** [comment]
First part of this is done: https://github.com/kubernetes/kubernetes/pull/36673

I'm not sure if we should switch over to client-go fully, but I think so.

cc @mikedanese @taimir 

@taimir Can you take this on after we've moved the source to this repository?

**Comment by taimir** [comment]
Hey, nice to see transition to `client-go` in core is done. I'll have a look at what needs to be done for `kubeadm` when you move the code, sure.

**Comment by luxas** [comment]
Ok, thanks.

Right now on master, kubeadm mostly uses the versioned api, but we still probably have to switch fully over to `client-go`, but not before all the code is moved over here.

**Comment by mikedanese** [comment]
I'm pretty sure it should be fine to switch to client-go before moving. That package exists in vendor/.

**Comment by luxas** [comment]
@mikedanese @caesarxuchao @deads2k After kubeadm was moved to the versioned API, these kinds of errors show up:
```
Failed to delete test deployment [no kind "DeleteOptions" is registered for version "kubeadm.k8s.io/v1alpha1"] (will ignore)
```

From this code:
```go
       dummyDeployment := NewDeployment("dummy", 1, v1.PodSpec{
		HostNetwork:     true,
		SecurityContext: &v1.PodSecurityContext{},
		Containers: []v1.Container{{
			Name:  "dummy",
			Image: images.GetAddonImage("pause"),
		}},
	})

	wait.PollInfinite(apiCallRetryInterval, func() (bool, error) {
		// TODO: we should check the error, as some cases may be fatal
		if _, err := client.Extensions().Deployments(api.NamespaceSystem).Create(dummyDeployment); err != nil {
			fmt.Printf("<master/apiclient> failed to create test deployment [%v] (will retry)", err)
			return false, nil
		}
		return true, nil
	})

	wait.PollInfinite(apiCallRetryInterval, func() (bool, error) {
		d, err := client.Extensions().Deployments(api.NamespaceSystem).Get("dummy")
		if err != nil {
			fmt.Printf("<master/apiclient> failed to get test deployment [%v] (will retry)", err)
			return false, nil
		}
		if d.Status.AvailableReplicas < 1 {
			return false, nil
		}
		return true, nil
	})

	fmt.Println("<master/apiclient> test deployment succeeded")

	if err := client.Extensions().Deployments(api.NamespaceSystem).Delete("dummy", &v1.DeleteOptions{}); err != nil {
		fmt.Printf("<master/apiclient> failed to delete test deployment [%v] (will ignore)", err)
	}
```

The last line that should remove the deployment fails

**Comment by deads2k** [comment]
Where an how did you construct the client?  It looks like its encoder may be set incorrectly.

**Comment by luxas** [comment]
@deads2k 
```go
func CreateClientAndWaitForAPI(adminConfig *clientcmdapi.Config) (*clientset.Clientset, error) {
	adminClientConfig, err := clientcmd.NewDefaultClientConfig(
		*adminConfig,
		&clientcmd.ConfigOverrides{},
	).ClientConfig()
	if err != nil {
		return nil, fmt.Errorf("<master/apiclient> failed to create API client configuration [%v]", err)
	}

	fmt.Println("<master/apiclient> created API client configuration")

	client, err := clientset.NewForConfig(adminClientConfig)
	if err != nil {
		return nil, fmt.Errorf("<master/apiclient> failed to create API client [%v]", err)
	}
```

Thanks for helping, I hope we can get this sorted out

**Comment by deads2k** [comment]
Huh, nothing looks off there.  It should just take defaults.  You may have to chase down why the encoder is trying to use `"kubeadm.k8s.io/v1alpha1"` as a target when speaking to an `extensions/v1beta1` API.  It's probably worth chasing down instead of trying to cross register the delete and listoptions.

**Comment by caesarxuchao** [comment]
I agree with @deads2k. The group/version and codec of the clientset is set statically, "kubeadm.k8s.io/v1alpha1" shouldn't sneak in. The constructor is [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/clientset_generated/release_1_5/typed/extensions/v1beta1/extensions_client.go#L80
), could you test if they are called?

**Comment by mikedanese** [comment]
This is very broken right now. Is anyone working on this?

**Comment by caesarxuchao** [comment]
@mikedanese you can assign it to me if no one is working on it.

**Comment by luxas** [comment]
Thanks @caesarxuchao!
FYI, we're planning to release a stable version of kubeadm soon (about the time v1.5 is released), so it would be great if it could be prioritized :)

Just reach out to me if you need anything.

**Comment by caesarxuchao** [comment]
Looks like the error message is printed by the api-server. I'll try to print out the api-server log to further debug.

**Comment by caesarxuchao** [comment]
Here's what went wrong:
* when kubeadm sends a delete request, it uses the direct codec to serialize the v1.DeleteOptions{} object, and sets its APIVersion and Kind ([code](https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/serializer/versioning/versioning.go#L235-L249)):
```
gvks, _, err := e.ObjectTyper.ObjectKinds(obj)
...
kind.SetGroupVersionKind(gvks[0])
```

* because DeleteOptions is registered as a kubeadm.k8s.io/v1alpha resource, so `gvks[0]=kubeadm.k8s.io/v1alpha`, that's the APIVersion ends up being sent to the apiserver

* API server doesn't install the kubeadm.k8s.io group, so it doesn't know how to decode the DeleteOptions, and thus the error.

Possible fixes:
1. don't register DeleteOptions in kubeadm.k8s.io group. Then `gvks[0]` would be whatever group that's last initialized. As long as that group is registered in API server, it will work.
2. Or, install the kubeadm group in the master, in this [file](https://github.com/kubernetes/kubernetes/blob/master/pkg/master/import_known_versions.go).

I favor the second approach, it looks safer.

This is a @kubernetes/sig-api-machinery issue. cc @smarterclayton, @lavalamp

**Comment by liggitt** [comment]
Master shouldn't need to know about kubeadm API types. I wouldn't want to start registering groups the master doesn't serve under master

**Comment by mikedanese** [comment]
There's a test that checks that common types like DeleteOptions are registered in all api groups. This is why they were added in the first place. Maybe that's just a bad test.

**Comment by lavalamp** [comment]
kubeadm group should definitely *not* be installed in the master :)

**Comment by lavalamp** [comment]
That test is only applicable for types that are linked into the master...

**Comment by caesarxuchao** [comment]
> That test is only applicable for types that are linked into the master...

Right. Currently testapi can tell if a group is meant for master or client, so perhaps just blacklist `kubeadm` in that test, until testapi is refactored.

**Comment by lavalamp** [comment]
SGTM

"refactored" is certainly a polite way of describing what needs to happen
to testapi... ;)

**Comment by caesarxuchao** [comment]
It still doesn't work after we remove DeleteOptions from the kubeadm group. The next `gvks[0]` is federaion/v1beta1, which is not installed in apiserver either. The fed api gets registered via this path: 
```
  k8s.io/kubernetes/cmd/kubeadm
  k8s.io/kubernetes/cmd/kubeadm/app
  k8s.io/kubernetes/pkg/kubectl/cmd/util
  k8s.io/kubernetes/federation/client/clientset_generated/federation_internalclientset
  k8s.io/kubernetes/federation/apis/federation/install
```

**Comment by luxas** [comment]
Can we just remove it from federation as well?

**Comment by caesarxuchao** [comment]
No, federation api-server [registers](https://github.com/kubernetes/kubernetes/blob/56bbfd259a6f45dfbcfb6f3c9f61643a787ed067/federation/cmd/federation-apiserver/app/federation.go#L28) it so I think the fed apiserver expects the fed client to encode the the deleteOptions with federation/v1beta1.

**Comment by luxas** [comment]
For now, I just uncommented the line where we're using `v1.DeleteOptions` to fix the failure.
It's only a temporary solution, in the future we want to delete the `dummy` deployment we have, but it works for now.

Hmm, I'm not sure what we should do here, but I guess we have to refactor/update the code that just sets `kind.SetGroupVersionKind(gvks[0])` regardless of whether the caller wants it or not...

**Comment by caesarxuchao** [comment]
>  I guess we have to refactor/update the code that just sets kind.SetGroupVersionKind(gvks[0]) regardless of whether the caller wants it or not...

Yes, I'm fixing the DirectCodec. I'll send out a PR for comments.

**Comment by caesarxuchao** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/38330 to fix.

**Comment by caesarxuchao** [comment]
#38330 is merged. The issue should be fixed.

**Comment by mikedanese** [comment]
@caesarxuchao well the bug is fixed but the original issue which was hijacked is still not resolved. Thanks for looking into this.

**Comment by luxas** [comment]
This is now fixed with https://github.com/kubernetes/kubernetes/issues/41104 :+1:
