### ISSUE TITLE
Add `.KubeProxy.Image` & `.KubeProxy.ExtraVolumes` in MasterConfiguration

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubeadm#520]
FEATURE REQUEST

Currently there is no way to configure `kube-proxy` DaemonSet using MasterConfiguration. We could probably use kubectl to patch the daemonset but supporting configuration will be handy. I think this will also require supporting extra mounts.

related: https://github.com/kubernetes/kubeadm/issues/512

**Comment by jamiehannaford** [comment]
@tamalsaha What type of additional configuration would you like? Specifying extra args to the binary?

**Comment by tamalsaha** [comment]
Here is the list of flags that are set by GKE. https://gist.github.com/tamalsaha/9e0b637ffa536e4e91c83c71e92a81fd#file-gke-flags-L29

We want to do the same for our GCE cluster using kubeadm (not GKE). So, `--feature-gates` will be one. Also, some flags point to files (--azure-container-registry-config, --google-json-key). Need mount for those.

**Comment by luxas** [comment]
We're gonna do this with kube-proxy ComponentConfig and embed the whole struct in `.KubeProxy.Config` in `MasterConfiguration`. We're avoiding the `map[string]string` as long as possible, i.e. until ComponentConfig is available.

**Comment by luxas** [comment]
@tamalsaha Repruposed this a little, and opened #527 specifically for ComponentConfig.
