### ISSUE TITLE
Where is the path to the certificate file and private key file referenced by the "kubernetes-admin" user?

### ISSUE THREAD

**Issue by JinsYin** [kubernetes/kubeadm#521]
```bash
# kubernetes master
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://172.17.0.44:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

Where can I find the `kubernetes-admin.crt` file and `kubernetes-admin.key` file?

**Comment by kad** [comment]
@JinsYin content of the fields `client-certificate-data` and `client-key-data` is the base64 encoded content of files you're looking for.

**Comment by jamiehannaford** [comment]
@JinsYin You can save them to the file by doing `echo REDACTED | base64 -d > file.crt`.

**Comment by JinsYin** [comment]
@kad @jamiehannaford Does not kubeadm create these two files automatically?
If I accidentally modified the `~/.kube/config`  file, how should I view the `rolebinding` or `clusterrolebinding` for the `kubernetes-admin` user?

```bash
$ kubectl get clusterrolebinding -o yaml | grep kubernetes-admin

$ kubectl get rolebinding -o yaml | grep kubernetes-admin
```

**Comment by kad** [comment]
No, kubeadm does not create those files separately. They are only part of admin.conf. If you somehow lost content in your home directory, try to check on your master node `/etc/kubernetes/admin.conf`. 

If you're looking for how clusterrolebinding is done, it is 
```yaml
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: cluster-admin
    namespace: ""
    resourceVersion: "96"
    selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/cluster-admin
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:masters
```

**Comment by JinsYin** [comment]
@kad Thanks. So the `kubernetes-admin` user belongs to the `system:masters` group?

**Comment by kad** [comment]
Yes, it does.

**Comment by JinsYin** [comment]
Thanks. My problem has been solved. I will close the issue.
