### ISSUE TITLE
Provide consistent UX for installation docs

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubeadm#525]
- Do an initial run-through of our installation instructions and refactor any cruft to provide a more consistent and clear UX. Users should be able to get up and running with minimal confusion.
- Assemble a list of related tools that might help users do a thing (e.g. run kubeadm in containers with DIND, set up CNI binaries, deploy CNI plugin)
- Begin to own the "how to install Kubernetes" story in k8s docs
- Regularly sync with sig-docs to ensure we integrate with any ongoing initiatives

/cc @luxas @jbeda

**Comment by luxas** [comment]
@jamiehannaford is this targeted for v1.9 or v1.10?

**Comment by timothysc** [comment]
cc: @craigtracey

**Comment by aberoham** [comment]
I haven't touched kubeadm in a while but want to try to help with this in my spare time.

**Comment by errordeveloper** [comment]
@aberoham I'm intending to start go through all the docs soon, feel free to get started when you have the time and do come and feel free to ping me Slack =)

**Comment by luxas** [comment]
@timothysc do we have a "docs lead" person for our kubeadm team that can take responsibility for this?

**Comment by timothysc** [comment]
This is being done now with all the 1.11 docs changes... closing this issue.
