### ISSUE TITLE
Use ComponentConfig for kube-scheduler

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#528]
Similar to https://github.com/kubernetes/kubeadm/issues/527 but for the scheduler

Relevant PRs: https://github.com/kubernetes/kubernetes/pull/54211 & 
https://github.com/kubernetes/kubernetes/pull/52562

The type would look like this in its simplest, earliest form:

```go
type KubeScheduler struct {
     Config kubeschedulerconfig.KubeSchedulerConfiguration
}
```

Then `cmd/kubeadm/app/utils.MarshalToYaml` will be used for serializing the object to bytes. These bytes will be written down to a path locally (`/etc/kubernetes/config/kube-scheduler.yaml`?,  TBD) for consumption,  but also uploaded to the `kube-scheduler` ConfigMap in the `kube-system` namespace, in the `config.yaml` key.

This means that the Static Pod written for v1.8 will still use normal flags, but the v1.9 manifest will have an extra hostPath mount to the ComponentConfig file and only have one flag: `--config`

cc @timothysc @kad @fabriziopandini @jamiehannaford

**Comment by luxas** [comment]
This will most likely not make v1.9, bumping to v1.10

**Comment by Lion-Wei** [comment]
@luxas If you don't mind, I can help to do this. :-)

**Comment by resouer** [comment]
https://github.com/kubernetes/kubernetes/pull/62515 This patch would help to generate default config file for kube-scheduler.

**Comment by timothysc** [comment]
This heavily depends on this proposal - https://docs.google.com/document/d/1-u2y03ufX7FzBDWv9dVI_HyiIQZL8iz3o3vabeOpP5Y/edit#heading=h.b7twqx6j3pvo

**Comment by luxas** [comment]
xref: https://github.com/kubernetes/community/pull/2354

**Comment by stewart-yu** [comment]
good issues, much helpful to `kubeadm` out of tree
/cc
