### ISSUE TITLE
Use the `--alpha-apiserver-endpoint-reconciler-type=storage` flag for HA in v1.9

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#529]
Referencing the accepted proposal: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/apiserver-count-fix.md

If the HA feature gate is enabled, this flag should be enabled as well

**Comment by fabriziopandini** [comment]
@luxas I guess we can close this issue now

**Comment by luxas** [comment]
Yeah, thanks!
