### ISSUE TITLE
kubeadm UpdateMasterRoleLabelsAndTaints should not use recursion

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#53]
_From @errordeveloper on October 3, 2016 11:6_

_Copied from original issue: kubernetes/kubernetes#33913_

**Comment by bruceauyeung** [comment]
this is already fixed by https://github.com/kubernetes/kubernetes/pull/36625

**Comment by mikedanese** [comment]
Fix was reverted https://github.com/kubernetes/kubernetes/issues/37813

**Comment by luxas** [comment]
Yes, but we should rewrite the whole thing instead...
Patch the node configuration instead of trying to update it like now
