### ISSUE TITLE
Set etcd version based on Kubernetes version

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#530]
Currently, we define `DefaultEtcdVersion` https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L147 as a constant, although the decision should be made based on the kubernetes version:

 - k8s v1.8 = etcd 3.0.17
 - k8s v1.9 = etcd 3.1.10

We should consume a function instead of a constant.

@fabriziopandini @timothysc @mattmoyer @kad @jamiehannaford

**Comment by kad** [comment]
Resolved in kubernetes/kubernetes#55010
