### ISSUE TITLE
Why does kubelet not run as a container?

### ISSUE THREAD

**Issue by JinsYin** [kubernetes/kubeadm#532]
Why does `kubelet` not run as a container, but run `kube-proxy` as a container?

**Comment by luxas** [comment]
Running kubelet in a container is not supported by SIG Node.
There are gotchas, drawbacks and bugs.

If you do things cleverly, you might get it to work in a Docker container. You have an increased chance to get it working in an rkt container. But that requires more work than a systemd unit.

**Comment by plombardi89** [comment]
is there anywhere these gotchas, drawbacks and bugs are documented? There's some use case for wanting to do this with Kubernetes in Kubernetes

**Comment by baikai** [comment]
So, the conclusion is kubelet still running outside the docker container?  And kubeadm will not be  enhance to start kubelet in docker?

**Comment by yagonobre** [comment]
Yes kubelet still running outside docker, IMO it's a decision for sig-node not kubeadm.
