### ISSUE TITLE
DockerValidator should use the CRI, not the Docker API

### ISSUE THREAD

**Issue by runcom** [kubernetes/kubeadm#533]
The `DockerValidator` in https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system/docker_validator.go which is used by kubeadm preflights checks is using the Docker API directly. With https://github.com/kubernetes/kubernetes/pull/55055 we're moving dockerisms to use `crictl` and the CRI. The `DockerValidator` should use `crictl` to gather Docker version via the CRI Version endpoint. However, the CRI isn't exposing the docker graphdriver (hence the need for an issue to track). We need to understand if and how those additional info are to be exported by the CRI.

/cc @luxas @Random-Liu @feiskyer

**Comment by luxas** [comment]
@runcom I actually think this issue would fit better in the kubernetes/kubernetes repo as this is a general improvement suggestion to the system verification check owned by sig-node and they track their issue in the main repo. WDYT? Can you reopen there possibly and tag (@)kubernetes/sig-node-bugs?

**Comment by runcom** [comment]
Yup! Will do

**Comment by luxas** [comment]
@runcom did you ever file an issue for this? I don't see it linked here?

**Comment by luxas** [comment]
nvm found it
