### ISSUE TITLE
Start erroring out when CA pinning isn't used and not explicitely opted out of

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#534]
@mattmoyer added the CA pinning feature of the Bootstrap Token in the discovery phase of `kubeadm join` in v1.8
In v1.9, the plan is to start erroring out when `kubeadm join --token <token>` is used without the CA hash, unless `cfg.DiscoveryTokenUnsafeSkipCAVerification` is set.
cc @jbeda

**Comment by mcapuccini** [comment]
Hi @luxas. Does it mean that in `1.9` we have to set `--discovery-token-unsafe-skip-ca-verification` when joining the cluster? Is there any security concern by doing so in your opinion?

**Comment by mcapuccini** [comment]
Never mind. I just realized that we need to hash the token.
