### ISSUE TITLE
cni config uninitialized worker node added some time after Weave

### ISSUE THREAD

**Issue by definitelyuncertain** [kubernetes/kubeadm#536]
Update: I seem to have resolved the issue as I've posted [here](https://github.com/weaveworks/weave/issues/3167)

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version**:
1.8.2

**Environment**:
- Kubernetes version (use `kubectl version`): `1.8.2` on all nodes, with `kubernetes-cni 0.5.1` 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 on all nodes
- Kernel (e.g. `uname -a`): 4.4.0-97-generic
- Install tools: `kubeadm`
- Others: I am using the weave works add-on, installed by running `kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"`

Note: I posted this issue [here](https://github.com/kubernetes/kubernetes/issues/55073), and I've moved the issue on their recommendation. Since I'm not sure where the issue lies , I'm posting here as well as in the Weave repo. I've since tried some other things and have updated the post here.

## What happened?
I followed this [guide](https://github.com/Langhalsdino/Kubernetes-GPU-Guide) for setting up a Kubernetes cluster with `kubeadm` for both master and worker nodes.

Just like in https://github.com/kubernetes/kubernetes/issues/48798 , the CNI network plugin remains uninitialized, but on a worker node rather than the master. I get the following from `systemctl status kubelet` : 

```
4282 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
4282 cni.go:196] Unable to update cni config: No networks found in /etc/cni/net.d
```
I get the exact same messages from `journalctl -u kubelet` as well. `kubectl get nodes` shows the node status is "Not Ready".

Thing is, I've already connected several other nodes to the cluster and they are all able to run pods quite fine, and I added them using the exact same steps.

Additionally, it seems this happens only to nodes that I add a couple of hours after adding the Weave add-on. The very same nodes are ready if I first join all of them to the master and then add Weave, so the problem isn't with the number of nodes or any particular node.

When I do `kubeadm reset` and try again, the same thing happens. I've also tried restarting the master node.

## What you expected to happen?
The node should have been added and ready for scheduling.

**How to reproduce it (as minimally and precisely as possible)**:
The usual procedure for adding a worker node. I followed this [guide](https://github.com/Langhalsdino/Kubernetes-GPU-Guide) except that I used `kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"` instead of `kubectl apply -f https://git.io/weave-kube-1.6` for Weave.

## Anything else we need to know?

I checked one of the working nodes and found a file `/etc/cni/net.d/10-weave.conf` and copied it over to the problematic node in the same place. Now, the node becomes ready, but when I schedule a pod on it, the pod remains pending indefinitely (the pod runs fine on other nodes).

The docker daemon seems to be running without errors, and swap has been turned off.

I have tried rebooting and adding the node again with no avail.

**Comment by timothysc** [comment]
Closing, self resolved.

**Comment by chenchix** [comment]
@timothysc hi, how did you resolve the issue? I am facing the same problem.
