### ISSUE TITLE
how to use it without internet 

### ISSUE THREAD

**Issue by fanhongli** [kubernetes/kubeadm#537]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by neolit123** [comment]
the user does not provide details about the exact problem.

this page already provides info on how to download Docker images if no i-net connection is available:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
`Running kubeadm without an internet connection`

Google also returns the above page as a first result for:
`kubeadm without internet`.

suggesting `/close`.

**Comment by stealthybox** [comment]
Here's the header to the docs for this:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init#running-kubeadm-without-an-internet-connection

It's rather minimal in describing what "pre-pulling images" means, but that's out of scope as it's runtime specific.

Closing as suggested.

**Comment by timothysc** [comment]
The list images PR also helps, and we should update that doc.

**Comment by stealthybox** [comment]
@timothysc are you referring to @chuckha's PR?
https://github.com/kubernetes/kubernetes/pull/63833
