### ISSUE TITLE
kubeadm development 

### ISSUE THREAD

**Issue by psyhomb** [kubernetes/kubeadm#538]
I would like to know why development of `kubeadm` is so slow and when exactly we can expect for this tool to get multi-master support and all the other required features for provisioning production ready kubernetes cluster on bare-metal, similar to what `kops` can do on AWS?

Thanks

**Comment by jbeda** [comment]
PRs accepted.  Feel free to chip in. 

https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle
