### ISSUE TITLE
improve kubeadm progress log and success summary messages

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#54]
_From @errordeveloper on October 3, 2016 12:5_

We should use templates instead of format strings, we also shouldn't print multi-line summary message in non-interactive mode. Colours would a great addition too. We should probably also provide a quite mode, default no-too-verbose mode, and a verbose mode.

_Copied from original issue: kubernetes/kubernetes#33929_

**Comment by mikedanese** [comment]
_From @errordeveloper on October 3, 2016 12:6_

xref https://github.com/kubernetes/kubernetes/pull/33831#issuecomment-250985320

**Comment by luxas** [comment]
a) Templates instead of format strings: done
b) Better certification logging: done
c) Colors: https://github.com/kubernetes/kubeadm/issues/41
d) Log level: https://github.com/kubernetes/kubeadm/issues/41

Closing in favor for: https://github.com/kubernetes/kubeadm/issues/41
