### ISSUE TITLE
imageRepository option not taken into account for the pause image

### ISSUE THREAD

**Issue by sebastien-prudhomme** [kubernetes/kubeadm#540]
## Versions

**kubeadm version** (use `kubeadm version`): 1.8.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.8.3
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): CentOS 7.4
- **Kernel** (e.g. `uname -a`): 3.10.0-693.5.2.el7.x86_64
- **Others**:

## What happened?

When using a config file with imageRepository set to other value than gcr.io/google_containers, the image pulled for the "pause" container is still gcr.io/google_containers/pause-amd64:3.0

All other image are correctly pulled from the right registry.

```
docker images
REPOSITORY                                                               TAG                 IMAGE ID            CREATED             SIZE
my.example.com/google_containers/kube-apiserver-amd64            v1.8.3              cb809b44649a        4 days ago          194MB
my.example.com/google_containers/kube-controller-manager-amd64   v1.8.3              daf30b917b69        4 days ago          129MB
my.example.com/google_containers/kube-scheduler-amd64            v1.8.3              8c83f779e0f1        4 days ago          54.9MB
my.example.com/google_containers/kube-proxy-amd64                v1.8.3              b1c0d274f2fb        4 days ago          93.1MB
my.example.come/google_containers/etcd-amd64                      3.0.17              243830dae7dd        8 months ago        169MB
gcr.io/google_containers/pause-amd64                                     3.0                 99e59f495ffa        18 months ago       747kB
```

## What you expected to happen?

The image for the "pause" container should be pulled from the custom registry.

**Comment by roadmapper** [comment]
This is not really a kubeadm bug; the kubelet is installed independently from kubeadm and thus has its own configuration for the pause container. See https://github.com/kubernetes/kubeadm/issues/257#issuecomment-298007840 for a way to specify the pause image location.

**Comment by sebastien-prudhomme** [comment]
Thanks
