### ISSUE TITLE
Kubeadm does not retain changes to kube-apiserver manifest on upgrade

### ISSUE THREAD

**Issue by teeram** [kubernetes/kubeadm#541]
# Bug Report

## Versions

**kubeadm version** (use `kubeadm version`): 

kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): **POST UPGRADE**

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Dell server
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

Recently, I ran into what I think might be a bug in Kubeadm when trying to upgrade my cluster from 1.8.2 to 1.8.3.  I had made a few slight changes to my kube-apiserver.yaml file within my /etc/kubernetes/manifest directory.  These changes instantiated kube-apiserver with a few extra arguments to communicate with etcd using TLS.  The problem I ran into was that when I attempted to use Kubeadm to upgrade from 1.8.2 -> 1.8.3, the newly generated kube-apiserver.yaml did not retain any of the custom settings I had provided.

In my case, this prevented the 1.8.3 api-server from starting up and being able to communicate with etcd.  Therefore, Kubeadm viewed this as an upgrade failure and reverted my manifest files back to their 1.8.2 edition.  I realized this was occurring by using the dry-run option to see the changes made to individual files.

To get around this issue, I doctored up a sample 1.8.3 kube-apiserver manifest using the output of dry-run and the custom parameters I provided in my 1.8.2 manifest file.  I then waited for the stage in in the upgrade process where Kubeadm awaits Kubelet restarting the kube-apiserver & friends pods.  During this phase, I manually copied my new kube-apiserver manifest file over the auto-generated one in /etc/kubernetes/manifest/kube-apiserver.yaml.  After a quick restart of Kubelet, the 1.8.3 api-server with my custom params started up.  Kubeadm was then able to complete the upgrade once it detected the api-server was back online.

## What you expected to happen?

Kubeadm would absorb the custom parameters I placed in the 1.8.2 kube-apiserver.yaml manifest and reproduce them in the 1.8.3 manifest.  Unless they were deprecated, then perhaps just warn me it may break.

## How to reproduce it (as minimally and precisely as possible)?

Make a few changes to a 1.8.2 kube-apiserver.yaml manifest and note how they don't survive after the upgrade to 1.8.3

## Anything else we need to know?

**Comment by timothysc** [comment]
This problem should no longer exist, if it does please feel free to reopen

**Comment by echel0n** [comment]
This issue is still present in v1.17

**Comment by neolit123** [comment]
> This issue is still present in v1.17

as per the original description of this ticket:

> I had made a few slight changes to my kube-apiserver.yaml file within my /etc/kubernetes/manifest

this is not supported. kubeadm regenerates new manifest files on upgrade.
you have the option to use the kubeadm config or --experimental-kustomize (ALPHA!).

**Comment by echel0n** [comment]
Just so others know, I edited the config using `kubectl -n kube-system edit cm/kubeadm-config`
