### ISSUE TITLE
kubdeadm init operation: created API client, waiting for the control plane to become ready

### ISSUE THREAD

**Issue by sumesh83** [kubernetes/kubeadm#542]
On my RHEL 7.3 server, I have successfully installed Kubernetes using the below command

Installed:
  kubeadm.x86_64 0:1.5.0-0.alpha.1.409.714f816a349e79             kubectl.x86_64 0:1.4.1-0             kubelet.x86_64 0:1.4.1-0            

Dependency Installed:
  kubernetes-cni.x86_64 0:0.3.0.1-0.07a8a2                                    socat.x86_64 0:1.7.3.2-2.el7                                   

Complete!

Now, I am trying to Initialize the master using the command 'kubeadm init' and the command output struck  forvere at the point 'created API client, waiting for the control plane to become ready'

Below is the output trace:
****************************

[root@s00]# kubeadm init --skip-preflight-checks
Skipping pre-flight checks
<master/tokens> generated token: "01f5d6.4557fbd30f5012b9"
<master/pki> generated Certificate Authority key and certificate:
Issuer: CN=kubernetes | Subject: CN=kubernetes | CA: true
Not before: 2017-11-15 08:53:43 +0000 UTC Not After: 2027-11-13 08:53:43 +0000 UTC
Public: /etc/kubernetes/pki/ca-pub.pem
Private: /etc/kubernetes/pki/ca-key.pem
Cert: /etc/kubernetes/pki/ca.pem
<master/pki> generated API Server key and certificate:
Issuer: CN=kubernetes | Subject: CN=kube-apiserver | CA: false
Not before: 2017-11-15 08:53:43 +0000 UTC Not After: 2018-11-15 08:53:44 +0000 UTC
Alternate Names: [10.196.18.64 10.0.0.1 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local]
Public: /etc/kubernetes/pki/apiserver-pub.pem
Private: /etc/kubernetes/pki/apiserver-key.pem
Cert: /etc/kubernetes/pki/apiserver.pem
<master/pki> generated Service Account Signing keys:
Public: /etc/kubernetes/pki/sa-pub.pem
Private: /etc/kubernetes/pki/sa-key.pem
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready

Can you please help me how to resolve this issue in order to move forward with the rest of the steps.

## Versions

**kubeadm version** (use `kubeadm version`): 
kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.1.409+714f816a349e79", GitCommit:"714f816a349e7978bc93b35c67ce7b9851e53a6f", GitTreeState:"clean", BuildDate:"2016-10-17T13:01:29Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:13:36Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
 

- **Cloud provider or hardware configuration**: NA
- **OS** (e.g. from /etc/os-release):  Red Hat Enterprise Linux Server release 7.3 (Maipo)
- **Kernel** (e.g. `uname -a`): Linux s00000.com 4.1.12-61.1.27.el7uek.x86_64 #2 SMP Fri Feb 3 12:31:56 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

Please help in resolve the hang issue.

**Comment by stewart-yu** [comment]
you should checkout the cgroupfs parameter between docker  and kubelet, may refer to [this PR](https://github.com/kubernetes/website/pull/6309)

**Comment by timothysc** [comment]
Closing stale, if issue still exists please reopen
