### ISSUE TITLE
What good is kubeadm when you're locked out from doing anything?

### ISSUE THREAD

**Issue by dalu** [kubernetes/kubeadm#543]
I'm sorry but I have wasted like 2 weeks on kubernetes already and I'm not getting anywhere.

I have again used kubeadm to setup a 3 node test cluster.
The first time I couldn't log into dashboard and after 4 days of psychodrain I ragequit.
And I'm not paying 3000€ / month for a lousy 8 vpcu 30GB RAM VM on GCE with a reasonable amount of traffic (30TB)

So far this kubernetes thing was nothing but a huge waste of time and psychic drain.
Promises of the holy land of milk and honey are met with a booby-trapped documentation where barely anything works and I believe this is intentional to force users to rent those overpriced "cloud" instances.

Do you know how far I could've advanced already in those 14 days if I were to focus on writing code?
Almost done with my project, that's how far. Instead I followed empty promises of kubernetes by Mr. Awesome superstar himself, Kelsey Hightower. His book doesn't help either. Total waste of time and energy.

kubeadm cli is beta?
well it certainly doesn't feel like it.

So after evaluating docker swarm which sadly also does thing only half-way,
I gave kubeadm another try.
After following booby-trap docs again because every damned command there is wrong and an intentional mistake to make people believe that this is rocket science, which it really isn't.
It's configuration in etcd, which is also not explained AT ALL but obfuscated.
Instead of having separate components you have this kubeadm bs which yeah it sets up a 1 node master where nodes can join. Big deal.
But your're locked out of your cluster.
You receive that /etc/kubernetes/admin.conf
and btw there is NO mention that you have to copy that to ~/.kube/config
So after you do that you can query the api on master:6443
But as soon as you're trying to do anything, I followed the namespace documentation - another booby-trapped chapter - to create those dev and prod namespaces, your cluster shifts to localhost:8080 and only by manually editing the config I was able to at least get pods from all namespaces...
So I thought let's deploy something, since I'm locked out of the dashboard because it doesn't accept my config as being valid, the config kube-effing-adm created isn't valid.
So alright I read up on helm the eierlegende wollmilchsau.
Sure enough I install helm and init.
But what's that? I can't deploy to namespace default.
After resolving the aforementioned booby-trap issues I switch to namespace dev and try that again.
But NOOOO why would I the freaking kubeadm create admin have access to the dev namespace, the default namespace can't access the dev namespace because you suck that's why.

idk... I'm giving your company about half my ad earning and that's if I can believe that which has summed up to be around 120k€ over the years by now. And this is the result?
booby-trapped docs?
a cluster setup tool that locks you out of your own cluster?
I know that's barely enough to pay even one year of you guys salaries.

Whatever

What good is kubeadm when you're locked out from doing anything with the cluster?
Imagine I didn't get to test those 3 nodes for free because Hetzner has a "cloud test phase" running.
I would've paid hard cash only to play with your toy that doesn't work for the most part.

why the booby-trapped docs?
why are you locked out of your own cluster with kubeadm?
why doesn't the dashboard recognise the admin.conf's credentials?
where is the k8s community? G+ one is DEAD. Are you even using your own platform?
Or is this just a playtoy for rich silicon valley kids so they can pretend they're actually doing something useful?
Yeah I'm pissed if you didn't get it by now.

**Comment by jbeda** [comment]
Hi @dalu.  I think you are confused with the nature of Kubernetes.  You refer to "your company" but Kubernetes isn't a company so I'm not sure who you are paying.

Regardless, we are a set of community members that are coming together to try and make something work.  I'm sorry that you didn't have a good experience. At this point your choices are (a) help fix it, (b) pay someone explicitly to help you out or (c) move on.  If you want to help fix it, we'd be happy to help get you started so you can become a functioning member of our community.

Regardless, the bug tracker isn't an appropriate place for abusive rants or to look for user support.
