### ISSUE TITLE
kubeadm init and join should allow usage without JWS

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#55]
_From @errordeveloper on October 3, 2016 11:0_

We should allow users to manage discover out of band, by copying CA cert or providing a local config file.

_Copied from original issue: kubernetes/kubernetes#33909_

**Comment by mikedanese** [comment]
_From @pires on October 5, 2016 10:33_

While I'm in favor of configuration files instead of flags (the latter are harder to manage as the number grows), our approach so far has been to provide flags.

**Comment by luxas** [comment]
@mikedanese's PR will fix this: https://github.com/kubernetes/kubernetes/pull/36462

**Comment by luxas** [comment]
Duplicate of #36
