### ISSUE TITLE
Make some feature gates require and opt-in to others

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#554]
There will be a dependency chain between our feature gates. In order to provide a consistent and good UX, kubeadm needs to automatically opt into dependent feature gates of a chosen one.

Example dependencies:
`HighAvailability` depends on `StoreCertsInSecrets` and `SelfHosting`
`StoreCertsInSecrets` depends on `SelfHosting`

Use case: I, as an user, want to enable the HA feature gate and run:
```
kubeadm init --feature-gates HighAvailability=true
```

which is a valid command. Under the hood, the `StoreCertsInSecrets` and `SelfHosting` will then also be enabled.

cc @stewart-yu can you please help contribute this?
cc @jamiehannaford @timothysc FYI

**Comment by stewart-yu** [comment]
Yes, i'm glad to it. @luxas

**Comment by luxas** [comment]
Thank you @stewart-yu! Feel free to ask here in case you need something, otherwise just go ahead and cc me on the PR :+1:

**Comment by stewart-yu** [comment]
Have others dependencies expect for two in example? If have, i think should better construct a struct to store dependencies chain; if not, hardcode just well. @luxas

**Comment by luxas** [comment]
@stewart-yu I think it is only those two features with dependencies right now

**Comment by luxas** [comment]
PR https://github.com/kubernetes/kubernetes/pull/56042 from @stewart-yu has fixed this issue. Thank you!
