### ISSUE TITLE
kubeadm install failed due to no valid OpenPGP data found. 

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubeadm#556]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?

```
root@k8s001:~# cat /etc/*releae
cat: '/etc/*releae': No such file or directory
root@k8s001:~# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
root@k8s001:~# curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
gpg: no valid OpenPGP data found.
```

**Comment by gyliu513** [comment]
My bad, it is a proxy issue, the behind proxy is not working, after update the proxy, works fine.

**Comment by wakeupcolumn** [comment]
> 
> 
> My bad, it is a proxy issue, the behind proxy is not working, after update the proxy, works fine.

What is the fix that you did on the proxy ?

**Comment by ronaldpetty** [comment]
Similar issue, across different networks, still looking.
