### ISSUE TITLE
kubeadm doesn't start

### ISSUE THREAD

**Issue by sachinar** [kubernetes/kubeadm#557]
I am  facing  issue with kubelet on centos7

[root@master1 ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/kubelet.service.d
└─10-kubeadm.conf
Active: activating (auto-restart) (Result: exit-code) since Thu 2017-11-16 08:29:00 UTC; 3s ago
Docs: http://kubernetes.io/docs/
Process: 1761 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
Main PID: 1761 (code=exited, status=1/FAILURE)

Nov 16 08:29:00 master1.com systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Nov 16 08:29:00 master1.com systemd[1]: Unit kubelet.service entered failed state.
Nov 16 08:29:00 master1.com systemd[1]: kubelet.service failed.

**Comment by luxas** [comment]
is swap enabled on your node?
What does `journalctl -xeu kubelet` say?

**Comment by sachinar** [comment]
swap is off

**Comment by sachinar** [comment]
try this out ..!!!
Your error will be sloved.

kubectl apply -f https://git.io/weave-kube-1.6
