### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#56]
@roberthbailey @mikedanese 
Can I take the liberty to create some labels for this repo in line with what we have in the main repo plus some extra kubeadm-specific?

I suppose so, but asking anyway if there's some formal rules for this...

**Comment by mikedanese** [comment]
sure

**Comment by roberthbailey** [comment]
Yes, create whatever labels you feel are useful.

**Comment by roberthbailey** [comment]
As you are creating labels, keep in mind the recent announcement of the name changes: https://groups.google.com/d/msg/kubernetes-dev/LEtIxeG0i84/kQDS-7AnCAAJ

**Comment by luxas** [comment]
This is now kind of done.
Of course it's a never-ending process, but I've now created some initial labels that might be useful

Also I went through all issues in this repo and tagged them properly, and closed all duplicates.

Feel free to improve the label names, add/remove some, etc. but at least we have the foundation now
