### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by vielmetti** [kubernetes/kubeadm#560]
## What happened?

Looked at CHANGELOG https://github.com/kubernetes/kubeadm/blob/master/CHANGELOG.md to see what was added in the latest release. It has not been updated in about a year.

## What you expected to happen?

CHANGELOG up to date, or moved to a less prominent place in the distribution.

## Anything else we need to know?

#258 #81 #88 are all previous CHANGELOG issues.

**Comment by luxas** [comment]
we should just remove this file at this moment I think. Our changelog was aligned with k8s' in v1.6, and support for v1.5 has already been dropped k8s-wide in the ecosystem
@fabriziopandini can you delete it?
