### ISSUE TITLE
kubeadm single node - kubelet, apiserver bind to localhost but mixed ipv4 and ipv6

### ISSUE THREAD

**Issue by ieugen** [kubernetes/kubeadm#564]
Hi,

This is a BUG REPORT

## Versions

**kubeadm version** 
````
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
````

**Environment**:
- **Kubernetes version** (use `kubectl version`):
````
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
````

- **Cloud provider or hardware configuration**:
Baremetal, hetzner server EX-60 line

- **OS** (e.g. from /etc/os-release): PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
- **Kernel** (e.g. `uname -a`): 
````
Linux aaaaa.example.com 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
````
- **Others**:

## What happened?

I've installed a single node kubernetes cluster on a hetzner machine using kubeadm 1.8.4 and Debian Stretch 9.1 all updates - linux 4.9, docker-ce 17.03 . 

The install produced an incomplete, sometimes functional sometimes infunctional setup. 
I believe I have tracked the issue to how kubernetes components bind to a mixed ipv4/ipv6 setup.

My install command is:

````
 kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=<private_ip_address> .
````

And this produced a setup like the following (some services omitted):
````
root@aaa:~# netstat -plnt 
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name       
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      6828/kubelet        
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      7480/kube-scheduler 
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      7253/etcd           
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      7416/kube-controlle 
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      7253/etcd           
tcp6       0      0 :::10255                :::*                    LISTEN      6828/kubelet         
tcp6       0      0 :::10250                :::*                    LISTEN      6828/kubelet        
tcp6       0      0 :::6443                 :::*                    LISTEN      7331/kube-apiserver 
````

As you can see, the kubernetes control plane services and other components are spread among ipv4 and ipv6 addresses. 

I've done the install multiple times and it seems the binds are a bit random. 

I have taken steps to disable ipv6 as per instructions [1]
It seems that only the grub kernel command line parameter completely disable ipv6 . sysctl did not work. 

Now, after a reboot I get:

````
ging:~# netstat -plnt 
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:10255           0.0.0.0:*               LISTEN      2371/kubelet        
tcp        0      0 0.0.0.0:10256           0.0.0.0:*               LISTEN      3318/kube-proxy     
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      2371/kubelet        
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      3318/kube-proxy     
tcp        0      0 0.0.0.0:10250           0.0.0.0:*               LISTEN      2371/kubelet        
tcp        0      0 0.0.0.0:6443            0.0.0.0:*               LISTEN      3127/kube-apiserver 
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      3052/kube-scheduler 
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      2970/etcd          
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      2970/etcd           
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      2870/kube-controlle 
````

[1] https://wiki.debian.org/DebianIPv6

Hope it helps and I hope I can get a solution on how to bind to ipv4 or specific network without rebooting my system - this is very important to me a.t.m .

Regards,

**Comment by ieugen** [comment]
Restarting docker service changes the ip addresses that the components are bound so I went and disabled ipv6 for docker as per instructions [1] .

Added `  "ipv6": false,` to `/etc/docker/daemon.json` . 
Now I'm looking to bind kubelet service to ipv4 only as well. 

[1] https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by anguslees** [comment]
I don't think this is the source of your problem (whatever the problem is).

What you're seeing here is some processes listening on ports on (ipv4) localhost explicitly, and some listening on ports on any address (all-zeros, aka `0.0.0.0` or `::` in IPv6-speak.  Note this is _not_ IPv6 localhost `::1`).

In particular, those entries like `:::6443` are _also_ listening on IPv4 on the same port - thanks to the way IPv6 has always been implemented(*).

If you would like to verify this you can make an IPv4 TCP connection to one of these ports using something like `telnet 127.0.0.1 6443`, and watch the connect succeed (compare the result against a port you know isn't open like 6444 - you will get an immediate connection refused).

(*) It _is_ possible to turn this off using an obscure sysctl.  Nobody does this because it breaks normal usage like the above, and you don't mention having done so, so I am assuming you are using the default behaviour.

This is not the bug you are looking for (unfortunately).
