### ISSUE TITLE
Add CoreDNS to kubeadm phase addons

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#565]
FEATURE REQUEST

`kubeadm alpha phase addon all` should install CoreDNS instead of kube-proxy when invoked with `--feature-gates=CoreDNS`.

and

`kubeadm alpha phase addon coredns` subcommand should be created

**Comment by luxas** [comment]
Isn't this working already at HEAD?

**Comment by fabriziopandini** [comment]
CoreDNS is implemented only in `kubeadm init` at HEAD, not in phases ...

**Comment by luxas** [comment]
> kubeadm alpha phase addon all should install CoreDNS instead of kube-proxy when invoked with --feature-gates=CoreDNS.

I think _this_ works at HEAD. I also think `kubeadm alpha phase addon kube-dns --feature-gates CoreDNS=true` works. We could add a shim `coredns` sub-command easily there as well that automatically enables the feature gate internally in time for v1.9 though

**Comment by fabriziopandini** [comment]
@luxas, you are right, this is already there at HEAD (didn't noticed at the first sight).
Closing this one
