### ISSUE TITLE
Add token usages and groups in MasterConfiguration

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#566]
FEATURE REQUEST

Enhance MasterConfiguration file allowing to setup token `usages` and `groups` (and eventually also the token `description`).

Modify `kubeadm init`, `kubeadm token *`, `kubeadm phase bootstrap-token *`, for using the above configuration options.

**Comment by wackxu** [comment]
I can help fix this

**Comment by luxas** [comment]
@wackxu please don't code this up before we've commented here with further, more detailed instructions on how this should be implemented

Thanks for offering help!

**Comment by wackxu** [comment]
@luxas yeah, you are right, I have just finish it and I would not commit a PR until we make sure the detail for how this should be implemented

**Comment by fabriziopandini** [comment]
This is going to be fixed with https://github.com/kubernetes/kubernetes/pull/60059

**Comment by fabriziopandini** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/60059
