### ISSUE TITLE
setting --oidc-groups-claim=groups makes apiserver not restart

### ISSUE THREAD

**Issue by dhrp** [kubernetes/kubeadm#579]
## What keywords did you search in kubeadm issues before filing this one?

--oidc-groups-claim

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
Major:"1", Minor:"8", GitVersion:"v1.8.3",

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.8.3
- **Cloud provider or hardware configuration**: Packet / baremetal
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2 (Xenial Xerus)
- **Kernel** (e.g. `uname -a`): Kernel 4.13.0-16-generic
- **Others**:

## What happened?
After editing the /etc/kubernetes/manifests/kube-apiserver.yaml to add the flag to add group support with a claim name of `groups`, the apiserver will no longer start, and no errors are reported.

```
# fails
    - --oidc-groups-claim=groups
``` 

**Turns out that does work if the claim specified is not `groups`** 
```
# works
    - --oidc-groups-claim=teams
``` 

## What you expected to happen?
The apiserver container to start normally and accept that oidc claim. 

I expect it to have something to do with it already being the default or something. But setting a value to the default should not cause a system to fail.

## How to reproduce it (as minimally and precisely as possible)?

Add the following to your kube-apiserver.yaml:
```
    - --oidc-groups-claim=groups
```
No other oidc settings are needed to make it fail.

**Comment by dhrp** [comment]
I've also confirmed that without a `--oidc-groups-claim` groups is not like a default. In other words; omitting this flag doesn't make putting a 'groups' claim work.

**Comment by mikedanese** [comment]
What was the error in the apiserver logs?
