### ISSUE TITLE
kubeadm and kube-discovery should use kubeconfig instead of a custom type

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#58]
_From @errordeveloper on October 3, 2016 11:1_

_Copied from original issue: kubernetes/kubernetes#33910_

**Comment by mikedanese** [comment]
_From @luxas on October 15, 2016 7:48_

@dgoodwin can I assign this to you?

cc @jbeda as well

**Comment by mikedanese** [comment]
_From @dgoodwin on October 16, 2016 15:39_

Technically in Joe's domain per our most recent separation of duties, though things may change in the coming week.

**Comment by mikedanese** [comment]
_From @jbeda on October 17, 2016 17:10_

This will be resolved as we implement the stuff out of #30707

**Comment by jbeda** [comment]
Tagging kubernetes/kubernetes#30707

**Comment by luxas** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/36101 and https://github.com/kubernetes/kubernetes/pull/35805

After those we need to hook up the `kubeadm token` commands to the BootstrapSigner backend... 
This is a high-priority issue.

**Comment by pires** [comment]
Isn't this fixed?

**Comment by luxas** [comment]
Nope, this is unfortunately not fixed. We're using a custom `ClusterInfo` type that we should get rid of.

**Comment by pires** [comment]
@luxas what's blocking us from doing this?

**Comment by luxas** [comment]
Not much really, but I don't see the point to produce a new `kube-discovery` image that returns kubeconfigs and edit some code in kubeadm, it feels backwards

I'd rather carry @jbeda's PR in that case or something.

**Comment by dgoodwin** [comment]
IMO we're just waiting for Joe's PR to merge, it already uses kubeconfig, so probably doesn't make sense to invest any time in killing off cluster info in the discovery pod we're going to remove entirely soon.

**Comment by luxas** [comment]
Yes, exactly. And I think @jbeda's PR only needs a rebase, ~10 line code changes to implement the `--controllers` flag and then we can merge it.

**Comment by jbeda** [comment]
This is done.  Yay!
