### ISSUE TITLE
Should kubeadm check that ip_forward is turned on?

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubeadm#580]
## FEATURE REQUEST

I came across someone whose kubeadm-created cluster was somewhat broken because IP forwarding was turned off.  I believe it's mandatory for Kubernetes; for example [this guide](https://kubernetes.io/docs/getting-started-guides/scratch/#network-connectivity) says it has to be on.

> Enable ipv4 forwarding sysctl, `net.ipv4.ip_forward = 1`

So, should this be added to the preflight checks?

**Comment by sathieu** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/40182? (fixed by https://github.com/kubernetes/kubernetes/pull/52569 in 1.9)

**Comment by bboreham** [comment]
The systctl is distinct from the iptables setting which is what that PR targets; both have to be on for Kubernetes to work.

**Comment by sathieu** [comment]
But docker sets ip_forward. You're talking about other CRI?

**Comment by kad** [comment]
beside ipv4 there is also ipv6 forwarding and also question, should it be enabled for all interfaces or not ?
