### ISSUE TITLE
Extending current HA k8s cluster (deployed by kubeadm and ansible) by adding new masters

### ISSUE THREAD

**Issue by kcao3** [kubernetes/kubeadm#586]
Hello, 
I am trying to add a new master node to my HA k8s cluster previously deployed by using kubeadm with ansible. You can see #546 for the detailed procedure. 

The issue I am facing now is the certs that were generated  based on the FIXED number of k8s master hosts that was specified at the time the cluster was initially bootstrapped. This now prevents any new master to join the cluster. The kubelet's log of the new master shows something like this:  "... x509: certificate is valid for 192.168.1.w, 192.168.1.x,192.168.1.y not 192.168.1.z" ( where 192.168.1.w,x,y are the IP address of the current masters, and 192.168.1.z is the address of the new master)
 
Does anyone know the best way to resolve this issue? Currently, all of my existing master nodes use the same certs. 
On my new master node, I was able to generate new certs on for the new master node using this command: kubeadm alpha phase certs all --config=kubeadmConfig.yaml

Is there a way to sync these certs across all the existing master/worker nodes? If yes, are there any additional steps required to ensure all the masters are properly configured and in sync?

Thank you in advance for your time and support.

**Comment by zatricky** [comment]
Sorry to answer your query indirectly. I figure I could at least try be helpful even if I don't directly have the proper answer right here.

My instinct is to use Kelsey Hightower's [kubernetes-the-hard-way guide](https://github.com/kelseyhightower/kubernetes-the-hard-way/) for insight about how certs are done without kubeadm's automation.

I would also refer to cookeem's [kubeadm-ha guide](https://github.com/cookeem/kubeadm-ha) for hints on doing HA.

When HA becomes a kubeadm built-in, it will still be a good idea to know how to do these things manually.

**Comment by bitgandtter** [comment]
Any progress on this, im facing the same issue? I have a functional ha cluster but certs prevent me to add new masters

**Comment by bitgandtter** [comment]
I just found and test [stackoverflow](https://stackoverflow.com/questions/46360361/invalid-x509-certificate-for-kubernetes-master) which works, we can generate a new certs and then copy them to all masters

**Comment by timothysc** [comment]
This is the canonical reference - https://kubernetes.io/docs/setup/independent/high-availability/
