### ISSUE TITLE
kube-proxy configmap not using apiserver-advertise-address

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubeadm#590]
BUG REPORT
## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.0.724+160270800f0995", GitCommit:"160270800f099538d9ba888201737b4dbab7587a", GitTreeState:"clean", BuildDate:"2017-11-30T03:05:52Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version**: 1.8.4
*I know this isn't really supported but shouldn't matter for this issue. Had to use the version since I depend on other changes*

## What happened?
I've created a cluster with kubeadm and a config specifying api / advertiseAddress. When looking at the kube-proxy config map I see the generated kubeconfig does not contain the advertiseAddress but one of the apiservers IPs.

## What you expected to happen?
As far as I understand https://github.com/kubernetes/kubernetes/blob/64ccd7665f6bc4792bf7263b7de88ce4a155e46c/cmd/kubeadm/app/phases/addons/proxy/proxy.go#L56, the generated config is supposed to use the advertiseAddress which is exactly what I need since my apiservers are behind a load balancer and have dynamic IPs.

## How to reproduce it (as minimally and precisely as possible)?
I haven't tried it but I assume all that is needed is running `kubeadm init --apiserver-advertise-address example.com`. The generated kube-proxy kubeconfig should use example.com but it doesn't.

## Anything else we need to know?
I just now realize the help for kubeadm init says this is suppose to be "The IP address the API Server will advertise it's listening on. 0.0.0.0 means the default network interface's address.". Which sounds like it's more a bind address than something that's advertised. This is a bit confusing. Can someone clarify?

**Comment by Lion-Wei** [comment]
Seems like `apiserver-advertise-address` can only be ipv4 or ipv6 format. If not, it will silently change to hostIP. 
https://github.com/kubernetes/kubernetes/blob/64ccd7665f6bc4792bf7263b7de88ce4a155e46c/cmd/kubeadm/app/util/config/masterconfig.go#42

**Comment by discordianfish** [comment]
Ah! That makes sense. Any reasons for this?
If that can't be changed, there should be another way to set the address kube-proxy connects to in kubeadm. This is required for many multi-master setup scenarios.

**Comment by miry** [comment]
I have same issue. and now we need to update `featureGates` to work with version 10

**Comment by fabriziopandini** [comment]
@discordianfish what about using the API.ControlPlaneEndpoint config option to solve your issue?
This new config option, added in the v1.10 cycle, allows to define a stable address that will be used also in the kube-proxy config map (currently only a DNS name are supported; see https://github.com/kubernetes/kubernetes/pull/59288 for details about the originating PR).

**Comment by discordianfish** [comment]
@fabianofranz Yes, sounds like this should work for me too.

**Comment by fabriziopandini** [comment]
@discordianfish this is Great!
If this works for you, could you kindly close the issue?

**Comment by discordianfish** [comment]
Ok, but since we're on it and it's related, would be great to get some attention on #699
