### ISSUE TITLE
Use apps/v1 API in kubeadm

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubeadm#596]
The core workloads API has been promoted to GA stability in the apps/v1 group version from 1.9. The apps/v1beta2 group version is deprecated. Let's update the kubeadm code.

**Comment by luxas** [comment]
Let's keep this open until we've gotten an answer on the changed OrphanDependents/DeleteDependents question here: https://github.com/kubernetes/kubernetes/pull/57235#pullrequestreview-84062603

> > The default garbage collection policy for Deployment, DaemonSet, StatefulSet, and ReplicaSet has changed from OrphanDependents to DeleteDependents when the deletion is requested through an apps/v1 endpoint. (#55148, @dixudx)
Clients using older endpoints will be unaffected. This change is only at the REST API level and is independent of the default behavior of particular clients (e.g. this does not affect the default for the kubectl --cascade flag).
If you upgrade your client-go libs and use the AppsV1() interface, please note that the default garbage collection behavior is changed.

> Which I don't think should affect us very much....
> But maybe we can stop setting DeleteOptions.PropagationPolicy = DeletePropagationForeground manually now and only go with the normal delete path? Is that right @janetkuo?

cc @kow3ns @janetkuo @dixudx

**Comment by jpweber** [comment]
I took at look at this and it appears it has been fixed by PR  #57235. I think this can probably be closed.
