### ISSUE TITLE
kubeadm refactor token handling

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#60]
_From @errordeveloper on October 3, 2016 11:2_

As discussed in #33262:
- https://github.com/kubernetes/kubernetes/pull/33262/files#r80333662
- https://github.com/kubernetes/kubernetes/pull/33262/files#r80336374
- https://github.com/kubernetes/kubernetes/pull/33262/files#r80333982

_Copied from original issue: kubernetes/kubernetes#33911_

**Comment by mikedanese** [comment]
_From @luxas on October 25, 2016 20:41_

Assigning @dgoodwin and @pipejakob since they are working on the `kubeadm token` command

**Comment by mikedanese** [comment]
_From @dims on November 16, 2016 14:39_

This needs to be triaged as a release-blocker or not for 1.5 @errordeveloper @dgoodwin @pipejakob

**Comment by mikedanese** [comment]
_From @luxas on November 16, 2016 16:32_

Nope not a release blocker

**Comment by luxas** [comment]
A lot related to #58 

One PR already up for this: kubernetes/kubernetes#35805

**Comment by pires** [comment]
Isn't this fixed?
