### ISSUE TITLE
kubeadm 1.8.4 dependencies wrong

### ISSUE THREAD

**Issue by rrati** [kubernetes/kubeadm#603]
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):  1.8.4-0

**Environment**: 
- **Kubernetes version** (use `kubectl version`): 1.9.0
- **Cloud provider or hardware configuration**:  AWS
- **OS** (e.g. from /etc/os-release): Red Hat Enterprise Linux Server release 7.4 (Maipo)
- **Kernel** (e.g. `uname -a`):  3.10.0-693.el7.x86_64
- **Others**:

## What happened?
Trying to install kubeadm-1.8.4 from the kubernetes repo pulls in kubernetes 1.9.0 packages instead of kubernetes 1.8.4.  Worse, the 1.9.0 kubernetes packages create conflicts with the 1.8.4 kubernetes packages.

kubernetes repo:
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

yum install kubeadm-1.8.4
Installing:
 kubeadm                           x86_64                    1.8.4-0                             kubernetes                                           15 M
Installing for dependencies:
 ebtables                          x86_64                    2.0.10-15.el7                       rhui-REGION-rhel-server-releases                    123 k
 kubectl                           x86_64                    1.9.0-0                             kubernetes                                          8.9 M
 kubelet                           x86_64                    1.9.0-0                             kubernetes                                           17 M
 kubernetes-cni                    x86_64                    0.6.0-0                             kubernetes                                          8.6 M
 socat                             x86_64                    1.7.3.2-2.el7                       rhui-REGION-rhel-server-releases                    290 k

yum install kubelet-1.8.4 kubeadm-1.8.4
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.x86_64 0:1.8.4-0 will be installed
--> Processing Dependency: kubectl >= 1.6.0 for package: kubeadm-1.8.4-0.x86_64
--> Processing Dependency: kubernetes-cni for package: kubeadm-1.8.4-0.x86_64
---> Package kubelet.x86_64 0:1.8.4-1 will be installed
--> Processing Dependency: kubernetes-cni = 0.5.1 for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: socat for package: kubelet-1.8.4-1.x86_64
--> Processing Dependency: ebtables for package: kubelet-1.8.4-1.x86_64
--> Running transaction check
---> Package ebtables.x86_64 0:2.0.10-15.el7 will be installed
---> Package kubectl.x86_64 0:1.9.0-0 will be installed
---> Package kubelet.x86_64 0:1.8.4-1 will be installed
--> Processing Dependency: kubernetes-cni = 0.5.1 for package: kubelet-1.8.4-1.x86_64
---> Package kubernetes-cni.x86_64 0:0.6.0-0 will be installed
---> Package socat.x86_64 0:1.7.3.2-2.el7 will be installed
--> Finished Dependency Resolution
Error: Package: kubelet-1.8.4-1.x86_64 (kubernetes)
           Requires: kubernetes-cni = 0.5.1
           Available: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64 (kubernetes)
               kubernetes-cni = 0.3.0.1-0.07a8a2
           Available: kubernetes-cni-0.5.1-0.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-0
           Available: kubernetes-cni-0.5.1-1.x86_64 (kubernetes)
               kubernetes-cni = 0.5.1-1
           Installing: kubernetes-cni-0.6.0-0.x86_64 (kubernetes)
               kubernetes-cni = 0.6.0-0
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

## What you expected to happen?
kubernetes 1.8.4 packages should be installed if anything

## How to reproduce it (as minimally and precisely as possible)?
Setup the repo
Run yum install kubelet-1.8.4 kubeadm-1.8.4
or
yum install kubeadm-1.8.4

**Comment by rrati** [comment]
@pipejakob

**Comment by luxas** [comment]
Let's track this in https://github.com/kubernetes/kubernetes/issues/57334 instead

**Comment by bladedoyle** [comment]
> Let's track this in [kubernetes/kubernetes#57334](https://github.com/kubernetes/kubernetes/issues/57334) instead

That issue has been closed, yet the problem continues to exist.
