### ISSUE TITLE
kubeadm init fails on CentOS 7.4 with Docker CE 17.09

### ISSUE THREAD

**Issue by gtirloni** [kubernetes/kubeadm#604]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

`kubeadm init` fails on CentOS with Docker CE 17.09 because `kubelet` defaults to the `systemd` driver (in `10-kubeadm.conf`) while Docker CE uses `cgroupfs`. If the user wishes to use `cgroupfs`, it's not possible to continue with initialization.

**What you expected to happen**:

kubeadm would create a kubelet.service configuration that matches what is used by Docker CE or an option to specify it during `kubeadm init`.

**How to reproduce it (as minimally and precisely as possible)**:

 * On CentOS 7.4 with Docker CE 17.09, attempt `kubeadm init`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.9.0
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): CentOS 7,.4
- Kernel (e.g. `uname -a`): 4.14.7

Workaround:

 * Stop `kubeadm init`
 * Edit /etc/systemd/system/kubelet.service.d/10-kubeadm.conf (switch to cgroupfs driver)
 * Run `systemctl daemon-reload`
 * Run `systemctl restart kubelet`
 * Run `kubeadm reset`
 * Run `kubeadm init` again

**Comment by luxas** [comment]
As documented here https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md#external-dependencies, we only support Docker up to 17.03.

**Comment by gtirloni** [comment]
@luxas, the issue is the same in 17.03. Sorry for not testing it before.

**Comment by gtirloni** [comment]
@luxas, thanks, it does work with 17.03.

I wonder how the community should help test newer configurations though. Is testing newer Docker versions the responsibility of a specific group? How can one follow/help the work that's being done?

**Comment by luxas** [comment]
@gtirloni SIG Node is responsible for doing that: https://github.com/kubernetes/kubernetes/issues/51205

**Comment by gtirloni** [comment]
Thank you! Happy holidays!
