### ISSUE TITLE
Instructions for switching from KubeDNS to CoreDNS

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubeadm#605]
There is alpha support for CoreDNS in 1.9 and I was wondering whether there are any instructions about switching to use it in existing clusters.

**Comment by luxas** [comment]
Just set `--feature-gates CoreDNS` when init-ing or upgrading and you'll get CoreDNS instead of kube-dns :)

**Comment by luxas** [comment]
We should improve the docs if we don't have anything specifically about it yet
cc @rajansandeep

**Comment by rajansandeep** [comment]
@luxas Is there a specific place where we can include this instruction?

**Comment by luxas** [comment]
In these places probably:
 - https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
 - https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/#cmd-phase-addon
 - https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-9/

Something's already there, but may be worth it to clarify and make more visible

**Comment by rajansandeep** [comment]
@kargakis in case you're still looking for docs.
https://coredns.io/2018/01/29/deploying-kubernetes-with-coredns-using-kubeadm/

**Comment by kargakis** [comment]
Thanks!
