### ISSUE TITLE
Feature Request: Run kubeadm init without addons

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubeadm#607]
I would like to run kubeadm init without any addons, something like `kubeadm init --no-addons`. I know that I can run the individual phases (but that could be a moving target over kube releases). Can something like this be supported?

**Comment by luxas** [comment]
Not in scope IMO at least. Either `kubeadm init && kubectl delete` or `kubeadm phase ...` all the way.
Does that make sense to you?

**Comment by tamalsaha** [comment]
I understand. Thanks @luxas !
