### ISSUE TITLE
Create new flag to specify apiserver address for kube-proxy

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubeadm#609]
Right now kubeadm uses the host IP it's running on for the apiserver address in the kube-proxy configmap.
For a multi-master setup where the apiserver are behind a load balancer, we need a way to configure kube-proxy to talk to the load balancer instead.
Therefor I propose adding a flag to kubeadm to set the apiserver address in the kube-proxy config map.

This is probably required for https://github.com/kubernetes/kubeadm/issues/261
Related:
- https://github.com/kubernetes/kubernetes/pull/56956
- https://github.com/kubernetes/kubeadm/issues/546

**Comment by fabriziopandini** [comment]
@discordianfish considering the availability of the new API.ControlPlaneEndpoint config option (that could be used also for defining the address of the LB in an HA scenario), is the new flag still needed or not?

**Comment by discordianfish** [comment]
Oh right, this can be closed now too.
