### ISSUE TITLE
review kubeadm return codes

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#61]
_From @errordeveloper on October 3, 2016 12:4_

Right now it returns either 0 or 1, there is no way to tell other errors... For example not being able to init due to permission errors should probably return something else, and not being able to join due to bad args vs potential network issue vs already joined... etc.

_Copied from original issue: kubernetes/kubernetes#33928_

**Comment by mikedanese** [comment]
_From @pires on October 5, 2016 11:1_

A lot of users will want to automate `kubeadm` usage. Returning error codes instead of parsing error logs makes a lot of sense!

**Comment by mikedanese** [comment]
_From @dmmcquay on October 5, 2016 16:0_

I'll work on this one.

**Comment by mikedanese** [comment]
_From @pires on October 14, 2016 13:41_

@luxas Fixed by #34341.

**Comment by mikedanese** [comment]
_From @dmmcquay on October 14, 2016 15:21_

@pires @luxas I was actually thinking of going a little deeper into this issue now that #34341 got merged in and look at more errors that could be handled correctly (permission errors, bad args, potential networks issues).

**Comment by mikedanese** [comment]
_From @pires on October 15, 2016 13:48_

I can support that but make sure to update docs to reflect that functionality.

**Comment by luxas** [comment]
What's the status of this @dmmcquay?

**Comment by dmmcquay** [comment]
@luxas this is still a WIP.

**Comment by luxas** [comment]
@dmmcquay do you consider this work done?

**Comment by pipejakob** [comment]
Friendly ping, @dmmcquay. Is there more left to do in this issue? Are you still owning its completion?

**Comment by dmmcquay** [comment]
I believe there is still more to do on this. I would be happy to still own its completion.

**Comment by luxas** [comment]
@dmmcquay Absolutely, feel free to go for it ;)

**Comment by jamiehannaford** [comment]
@dmmcquay Friendly ping :) What do you think is left to do before closing this out? If we list what's left, folks can jump in to help finish the work if you're backed up.

**Comment by luxas** [comment]
@dmmcquay If you do work on this, please reopen, ping here, open a new issue, or just file the PR.
Thank you
