### ISSUE TITLE
Document all phases' high-level functions in `app/phases/*/doc.go`

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#614]
Right now this text is missing in most places, or out of date.
The counterproposal here would to NOT document the high-level function of the phase in the code at all, instead in other docs.
cc @fabriziopandini @xiangpengzhao WDYT?

**Comment by xiangpengzhao** [comment]
From my perspective, it'd be good to document them in other docs which are user-faced. But if the docs in the code can be automatically generated to a user-faced doc, it'd be better to keep the docs in the code for it's easier to keep docs in code up-to-date.

**Comment by luxas** [comment]
> if the docs in the code can be automatically generated to a user-faced doc

I'm not sure how easy/hard this is... @fabriziopandini ?

**Comment by fabriziopandini** [comment]
IMO high level description of phases should be done in user-facing documents like e.g. [init workflow](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#init-workflow).

I don't think that we should create a direct connection between doc.go files and the above user facing docs. Instead  we should use doc.go for documenting implementation details **only for packages that need large amounts of introductory documentation** as suggested by godoc guidelines.

One last consideration; if we can transform this issue in a checklist with detailed actions items it will be easier to get help from other contributors here

**Comment by luxas** [comment]
> I don't think that we should create a direct connection between doc.go files and the above user facing docs. Instead we should use doc.go for documenting implementation details only for packages that need large amounts of introductory documentation as suggested by godoc guidelines.

:+1: 

> if we can transform this issue in a checklist with detailed actions items it will be easier to get help from other contributors here

Sounds good to me, @fabriziopandini can you post such a list with what you see as necessary advice here please?

**Comment by timothysc** [comment]
Closing this issue in favor of the 1/2 dozen others around promoting phases and current ongoing efforts.
