### ISSUE TITLE
Remove `well_known_labels.go`

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#615]
Basically resubmit https://github.com/kubernetes/kubernetes/pull/48056 and remove the old file that now has no consumers.

cc @wackxu @stewart-yu Do you want to help with this?

**Comment by vbmade2000** [comment]
Is this to be worked on after shifting kubeadm code to this new repo ?

**Comment by luxas** [comment]
No, this can be done now. @vbmade2000 do you want to help out with this task?

**Comment by luxas** [comment]
Oh, first now noticed that @xiangpengzhao had sent https://github.com/kubernetes/kubernetes/pull/57231 :smile:.
@vbmade2000 Let's look at an other issue for you :wink:

**Comment by vbmade2000** [comment]
@luxas No issues :)

**Comment by xiangpengzhao** [comment]
@luxas oh sorry, I should create an issue for each of my PRs. (I thought some of them are trivial so I didn't :sweat_smile: )

**Comment by luxas** [comment]
Even though they are trivial, it often helps when looking back retroactively at the closed issues in the milestone list when trying to summarize everything that happened during the cycle... I found that by experience when not doing it first myself as well ;)
