### ISSUE TITLE
Add the “Certified Kubernetes” mark on the kubeadm docs page

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#616]
We should make it clear to readers that we're conformant

cc @errordeveloper @stealthybox @fabriziopandini @timothysc

**Comment by stealthybox** [comment]
Related #617

**Comment by stealthybox** [comment]
<img src="https://raw.githubusercontent.com/cncf/artwork/master/kubernetes/certified-kubernetes/versionless/color/certified_kubernetes_color.png" align="right" width="150px">
This is a good reference:

[Certified Kubernetes Branding Guide](https://github.com/cncf/artwork/blob/master/kubernetes/certified-kubernetes/certified-kubernetes-brand-guide.pdf)

Here's an example with logo on the right.

Which docs should we add the mark to?
#### website
  - setup
    - **[setup/independent/install-kubeadm](https://kubernetes.io/docs/setup/independent/install-kubeadm/)  no version**
    - [setup/independent/create-cluster-kubeadm](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/)
  - reference
  - tasks
    - **[reference/setup-tools/kubeadm/kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/)  no version?**
    - [tasks/administer-cluster/kubeadm-upgrade-1-8](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-8/)  all applicable versions
    - [tasks/administer-cluster/kubeadm-upgrade-1-9](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm-upgrade-1-9/)  all applicable versions

#### this repo
  - **[design_v1.8](https://github.com/kubernetes/kubeadm/tree/master/docs/design/design_v1.8.md)  /w version**
  - [release-cycle](https://github.com/kubernetes/kubeadm/tree/master/docs/release-cycle.md)
  - [test-failures](https://github.com/kubernetes/kubeadm/tree/master/docs/test-failures.md)

I'll start PR's for the ones in bold.
Should we add any others?

**Comment by luxas** [comment]
I'd be fine with adding the mark to /setup/independent/install-kubeadm as well :+1:

**Comment by timothysc** [comment]
We need to submit the community distribution details.

**Comment by stealthybox** [comment]
@timothysc here's the v1.8 conformance PR:
https://github.com/cncf/k8s-conformance/pull/62

**Comment by luxas** [comment]
> We need to submit the community distribution details.

??
Do you mean that the badge should have some explicit "Community"-mark on it or what?

**Comment by stealthybox** [comment]
@luxas, @timothysc said he'd sync up with you on what he means by this.
It has something to do with how the conformance process has been vendor-centric up to this point.
