### ISSUE TITLE
Improve etcd version/endpoint validation

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#619]
In our etcd-specific preflight checks we should:
 - Match the _exact etcd version_ that is supported, not only check for the minimum version. We should not let the etcd version go too low (e.g. for v1.9, we support 3.1.10, not 3.0.17 which is the minimum version concerning v1.8)
 - Actually validate that all endpoints given in the external etcd case belong to the same cluster. I've heard stories when endpoints belonging to different clusters have been specified, and that has been kinda hard to debug. We should automatically fail in such a scenario.

cc @xiang90 @hongchaodeng @jamiehannaford @timothysc @xiangpengzhao @stewart-yu @wackxu

**Comment by luxas** [comment]
@ronncc will help out with this task. I can't assign you (sorry!), but please do work on it anyway :)

**Comment by luxas** [comment]
Can you see if your current PR already fixes both of these cases? I think the first one is the most important to get right, and we should have all the tools needed in kubeadm to implement this.

**Comment by detiber** [comment]
@luxas My PR only addresses the second part of this Issue. I do not do any additional validation or enforcement of etcd versions, but the cluster is validated for all of the specified endpoints.

**Comment by luxas** [comment]
Okay, great. Can you do the 1st part in a future PR or? (i.e. are you okay with having this in your backlog?)

**Comment by detiber** [comment]
@luxas no issues with keeping it on my backlog as long as it isn't a hard requirement to get the fix in for v1.11. I have some other work that will be taking up a considerable amount of time for the next few weeks.

**Comment by luxas** [comment]
@detiber It isn't a priority for now, okay to defer

**Comment by timothysc** [comment]
I'm a meh on doing hard validation checks, I'm closing this.  

If we decide otherwise for a specific reason we can do reopen this or another issue.
