### ISSUE TITLE
Discuss which addons kubeadm should deploy by default

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#62]
_From @mikedanese on October 3, 2016 19:36_

It's important for kubeadm to deploy critical addons because we want users to have a functioning cluster after the process completes. The current implementation is an new addon management solution which does not align with the larger goals for the addon manager.

cc @kubernetes/sig-cluster-lifecycle 

_Copied from original issue: kubernetes/kubernetes#33961_

**Comment by mikedanese** [comment]
_From @luxas on October 3, 2016 19:40_

Which addons except dns belongs to this group?
dashboard and heapster?

Should the process be to opt in (`kubeadm init --addons=dashboard,heapster`) or opt-out (`kubeadm init --exclude-addon heapster`) in your mind?

**Comment by mikedanese** [comment]
_From @bprashanth on October 3, 2016 19:43_

I think the problem is broader than just deployment. I want priority on pods (nice) that kicks in even when they get vertically autoscaled. If there're finite resources on nodes, I want them allocated to the most important pods, even if this means evicting lower priority pods. Does the deployment problem solve itself with such a system?

**Comment by mikedanese** [comment]
> Which addons except dns belongs to this group?

kube-proxy, heapster, maybe dashboard

We should fix addon deployment in general and use that solution rather than inventing yet another.

**Comment by mikedanese** [comment]
_From @colemickens on October 3, 2016 20:14_

Sorry to rehash this since I've had this conversation a couple times in ephemeral Slack contexts... but what are the arguments against `kube-cert-manager`? It was suggested as an option for our use, but I hesitated because I knew there were reservations... but I don't recall them well enough to argue for/against it's use.

**Comment by mikedanese** [comment]
_From @luxas on October 3, 2016 20:16_

xref my proposal earlier: kubernetes/kubernetes#23233 (comment)

**Comment by mikedanese** [comment]
_From @justinsb on October 4, 2016 5:34_

Check out channels, which is how I've avoided the problems of kube-addons: https://github.com/kubernetes/kops/tree/master/channels

It depends on your work on getting prune to work in `kubectl apply` @mikedanese (or will do!), but it also adds a few things for a better UX:

1) a meta-manifest for an addon, listing the various available versions (https://github.com/kubernetes/kops/blob/master/addons/kubernetes-dashboard/addon.yaml)
2) a when you install an addon, we record the version you have installed and the source (currently as an annotation on the namespace)
3) this means if you edit the addon, we won't immediately undo your changes (I'm looking at you, kube-addons), even if run in a cron-job
4) we also can prompt you to upgrade your addons when a new version comes out

I think we should aim to replace the kube-addons container in 1.5 with something like this.  I was planning on working on it anyway - want to team up @mikedanese ?   I think kubeadm should call into it, but there is much wider appetite for this (and for starting to build a repository of addons).  Of course if it's all go code it can be a standalone tool _and_ part of kubeadm.

**Comment by mikedanese** [comment]
_From @errordeveloper on October 11, 2016 10:25_

Current implementation is there only because there was not concrete proposal at the time. There are several ideas floating around, let's make sure we settle on something soon.

**Comment by luxas** [comment]
@mikedanese Which addons do we consider critical other than dns?

**Comment by kad** [comment]
I think, dashboard and heapster (standalone version) are essentials. And opt-in solution for them is the best.

**Comment by mikedanese** [comment]
Heapster, kube-dns, kube-proxy, pod network overlay depending on the environment and probably the dashboard

**Comment by kad** [comment]
@mikedanese I hope that under "pod network" you mean different options for most common solutions (flannel, calico, weave, romana?, canal?) ?
Manifests for those addons will be part of kubeadm repo or it will be fetching from somewhere else ?

**Comment by mikedanese** [comment]
I hadn't thought about the implementation, just what needs to run to have a minimally functional cluster.

**Comment by luxas** [comment]
The long term goal for this will be solved with the [Addon Manager v2](https://docs.google.com/document/d/1Laov9RCOPIexxTMACG6Ffkko9sFMrrZ2ClWEecjYYVg/edit#heading=h.rwtjflxdmlmi) proposal, [feature#18](https://github.com/kubernetes/features/issues/18)

I think the general consensus here is that kubeadm won't include support for other addons than kube-proxy and kube-dns which are required for the conformance e2e tests. Everything else is out of scope for now.

An in-core addon manager will make it easy for users to manager other addons like Heapster++ (metrics-server), the Dashboard, network plugins, etc. but out of scope for the time being.
