### ISSUE TITLE
Bump minimum version to v1.9 and cleanup v1.8-specific code at HEAD

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#622]
TODO:
 - Bump minimum version: https://github.com/kubernetes/kubernetes/pull/57233, done!
 - kube-proxy cleanup: https://github.com/kubernetes/kubernetes/pull/57305, done!
 - kube-dns cleanup: https://github.com/kubernetes/kubernetes/pull/57271, done!
 - Cleanup old upgrading code that is v1.8->v1.9-specific

ref: https://github.com/kubernetes/kubeadm/blob/master/docs/release-cycle.md

**Comment by xiangpengzhao** [comment]
@vbmade2000 you can take a look at the last bullet if you are interested in :) This was once on my TODO list but not yet be done.

**Comment by vbmade2000** [comment]
@xiangpengzhao Sure. I'll ping you for that separately on kubernetes slack if you are available.

**Comment by xiangpengzhao** [comment]
@vbmade2000 cool! My slack ID is the same as my GH.

**Comment by vbmade2000** [comment]
Ok. Thanks :)

**Comment by luxas** [comment]
Awesome coordination there @xiangpengzhao @vbmade2000 :clap:!

**Comment by xiangpengzhao** [comment]
@vbmade2000 FYI:  `cmd/kubeadm/app/phases/upgrade/postupgrade_v18_19.go` is one of the files should be checked. There might be other v1.8->v1.9-specific codes as well. If you find somewhere but not sure, feel free to ping @luxas (or me, hopefully I can confirm it :smile: )

**Comment by vbmade2000** [comment]
@xiangpengzhao I'll check mentioned file and other info. Thanks buddy :)

**Comment by timothysc** [comment]
@xiangpengzhao - Where are we at with this issue and is there anything I can help with?

**Comment by vbmade2000** [comment]
@timothysc I was supposed to work on this issue but due to time constraint I was not able to work. Let me check it again. I'll ping you on slack if I would be in need of help.

**Comment by xiangpengzhao** [comment]
As per chat with @vbmade2000 on slack, I will finish the TODO `Cleanup old upgrading code that is v1.8->v1.9-specific`. PR https://github.com/kubernetes/kubernetes/pull/60359 sent.
