### ISSUE TITLE
Enable advanced auditing in v1.10?

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#623]
Open question -- should we enable advanced auditing in some form by default in kubeadm?
If so -- in what form?

cc @xiangpengzhao @roberthbailey @timothysc @errordeveloper @fabriziopandini WDYT?

**Comment by fabriziopandini** [comment]
> should we enable advanced auditing in some form by default in kubeadm?

Yes in the long term. 
I have no strong opinion if auditiong should blocker for kubeadm GA, if it should be in v1.10, if it should be default as soon as it is ready or it should be under feautures-gate for a while

> If so -- in what form?

The docs says "The audit profile used by GCE should be used as reference by admins constructing their own audit profiles".  I'm fine in using this as a base for the kubeadm as well. 

As a backend, I think that a simple viable solution is to store data on a host mount with 2/3 days of retention.

**Comment by luxas** [comment]
> As a backend, I think that a simple viable solution is to store data on a host mount with 2/3 days of retention.

Sounds good to me

> I have no strong opinion if auditiong should blocker for kubeadm GA, if it should be in v1.10, if it should be default as soon as it is ready or it should be under feautures-gate for a while

If it goes to GA in v1.10, we can enable it for sure. Probably even though it's in beta.
I think a first very good step would be to code what's needed on the kubeadm side, and then hold until we feel we're ready. This would be not-critical for v1.10, but a very good starter project for someone new to kubeadm.

**Comment by timothysc** [comment]
@chuckha xref: https://github.com/heptio/sonobuoy/issues/163

**Comment by timothysc** [comment]
Chuck is digging in here, but I assigned to me until he gets contributor acls.
