### ISSUE TITLE
Make the self-hosted upgrades rollback-able

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#624]
Right now, if you look at the [self-hosting upgrading code](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/upgrade/selfhosted.go), you'll notice that if something goes wrong, there is no easy way to rollback currently.

What we need to do here is to "go down" temporarily to static Pods if, let's say, the API server wouldn't come up cleanly when upgrading it.
More information on how the self-hosting is achieved can be found in this presentation: https://docs.google.com/presentation/d/1Gp-2blk5WExI_QR59EUZdwfO2BWLJqa626mK2ej-huo/edit

@xiangpengzhao would you be interested in looking into how we could be able to rollback from a bad upgrade when upgrading a single master? This is probably a requirement for graduating self-hosting to beta in v1.10

cc @errordeveloper @timothysc @fabriziopandini

**Comment by xiangpengzhao** [comment]
@luxas yeah I will investigate it.

**Comment by luxas** [comment]
Thanks! Just ping me if you need more clarification on how it may be done...

**Comment by fabriziopandini** [comment]
@luxas, @xiangpengzhao 
I'm a little bit concerned about possible corner cases that should be taken into consideration. At least:
- does the proposed solution works if certificates are stored in secrets?
- does the proposed solution works in a multi master scenario?
Not sure if there are more....

**Comment by luxas** [comment]
We're not gonna prioritize making self-hosted k8s work at the moment in the near future, so I'm gonna close this.
