### ISSUE TITLE
Sync k8s.io/kubeadm/OWNERS with k8s.io/kubernetes/cmd/kubeadm/OWNERS

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#632]
What's in [`k8s.io/kubernetes/cmd/kubeadm/OWNERS` ](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/OWNERS) should also be in this repo's OWNERS file [`k8s.io/kubeadm/OWNERS`](https://github.com/kubernetes/kubeadm/blob/master/OWNERS)

Please update the OWNERS file in this repo based on what's merged in the core repo now...

**Comment by luxas** [comment]
cc @stealthybox @mattkelly could one of you make the change please and I'll approve?

cc @timothysc @roberthbailey

**Comment by mattkelly** [comment]
Sure, I'll throw the change up real quick.
