### ISSUE TITLE
Address MAC and reschedule Pods

### ISSUE THREAD

**Issue by HamzaK8s** [kubernetes/kubeadm#633]
Hello
I was wondering how to assign a static address Mac to a Pod ? also there is any possibility to reschedule a running pod to another worker-node in cluster ?

Thanks

**Comment by kad** [comment]
kubeadm issue tracker is not the correct place to ask this kind of questions.
Please use appropriate places, e.g. https://groups.google.com/forum/#!forum/kubernetes-users 
/close
