### ISSUE TITLE
Document how to set custom args for kube-proxy

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kubeadm#636]
I wanted to set the `--cluster-cidr` argument on kube-proxy, via kubeadm.

On Slack I was advised:

> in v1.9 you can use `kubeadm init` with `--config` and set the `.kubeProxy.config.clusterCIDR` value in the MasterConfiguration file

It seems to me this should be mentioned at https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/ - it mentions apiserver, controller-manager and scheduler but not proxy.

**Comment by neolit123** [comment]
@liztio i can the flag at the web page.

**Comment by neolit123** [comment]
^ pushed a PR with an update for that.
the info on kube-proxy links directly to godocs. not ideal but we don't have a page for kube-proxy yet, i think.
