### ISSUE TITLE
Example configs for using external Certificates 

### ISSUE THREAD

**Issue by rambo45** [kubernetes/kubeadm#638]
When using Kubeadm generated CA certs, all kubectl commands fail due to unknown signing CA. Documentation for using External CA is not clear, please provide examples

**Comment by liztio** [comment]
There's a bunch of different parts to fixing this.

1. Better documentation around what certs are required for kubeadm to work without a CA. [Jason's got a good gist on this][j]
2. Document pitfalls of doing this (cert rotation etc)
3. Better error messages when not all those certs are present. Currently we just fall back on "no ca key found" when we miss anything
4. Specify how to create a kubeconfig from your own CA and the server's credentials (possibly using kubectl)

[j]: https://gist.github.com/detiber/81b515df272f5911959e81e39137a8bb

**Comment by liztio** [comment]
Spoke to @Bradamant3, we both agree a list of certs required and the hierarchy needed would be useful to more than just kubeadm. I'm going to make that list, which will also function as documentation for kubeadm, commit it upstream, and then link from our kubeadm docs.

**Comment by liztio** [comment]
initial PR for certificate documentation added to [k8s/website](https://github.com/kubernetes/website/pull/8232)

**Comment by liztio** [comment]
Working on part 3. Copied from [#sig-cluster-lifecycle](https://kubernetes.slack.com/archives/C13J86Z63/p1525285287000274):
>  I'm working on the external CA logic. Right now the logic is:
> 1. Check if _all required external certs are presents_. If they are not, continue:
> 2. For every CA pair, see if the pair already exists. If only the key or only the cert exist, error. if both exist, continue: if neither exist, create them and continue:
> 3. Generate certificates using those CAs
> this means, for example, if you send an external CA, but not all the required client/server certificates, a relatively obtuse error message occurs
`failure loading ca certificate: couldn't load the private key file /etc/kubernetes/pki/ca.key: open /etc/kubernetes/pki/ca.key: no such file or directory`
I'm trying to figure out what is least surprising to do here, because the current thing is pretty surprising / unhelpful

**Comment by luxas** [comment]
@timothysc I think we should classify this as a bug (well it is), and target v1.11
