### ISSUE TITLE
Possible error while using `kubeadm upgrade`

### ISSUE THREAD

**Issue by rajansandeep** [kubernetes/kubeadm#641]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.9

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
In the scenario when I have CoreDNS installed via `kubeadm init` and I want to continue using CoreDNS after `kubeadm upgrade`, the upgrade is unsuccessful and it gives an error:

```
....
bootstraptoken] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy
[upgrade/postupgrade] FATAL post-upgrade error: timed out waiting for the condition
```
I suspect this occurs as it times out waiting for the kube-dns deployment, which is non-existent in this scenario.

## What you expected to happen?
Successfully upgrade kubernetes using `kubeadm upgrade` with no errors.

## How to reproduce it (as minimally and precisely as possible)?
- Use `kubeadm init --feature-gates CoreDNS=true` to install CoreDNS.
- Then upgrade using `kubeadm upgrade apply v1.10.0-alpha.1 --feature-gates CoreDNS=true --allow-experimental-upgrades`

## Anything else we need to know?
Moving the issue kubernetes/kubernetes#57783 here.

**Comment by kargakis** [comment]
I think this happens because in case the feature gate is on, kubeadm will try to delete kubeDNS. The second time you will do an upgrade with coreDNS installed, kubeDNS is missing but [this wait loop blocks trying to delete it](https://github.com/kubernetes/kubernetes/blob/7a58a5caee002d7d9f996ab5de8396ebbd3560fd/cmd/kubeadm/app/phases/upgrade/postupgrade.go#L127).
