### ISSUE TITLE
ARM APIServer timeout is too short for upgrade.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubeadm#644]
An APIServer on ARM takes ~1.5 minutes to come up. However, the health-check kicks in earlier than that, and the kubelet kills the APIServer.

This prevents successful kubeadm based upgrades on ARM.

We should make this timeout be configurable.

It's even worse on self-hosted clusters, because you can not manually edit the timeout when the apiserver is down. I had to use `systemctl stop kubelet` to prevent the kubelet from killing the apiserver repeatedly.

**Comment by luxas** [comment]
In what way would you like this to be configurable? Via flags or the Config file?

**Comment by kargakis** [comment]
Dupe of https://github.com/kubernetes/kubeadm/issues/413?

**Comment by brendandburns** [comment]
Yeah, this is a dupe of #413.

I think a flag is sufficient.
