### ISSUE TITLE
kubeadm 1.9.1 can't upgrade v1.7.x to another 1.8.x

### ISSUE THREAD

**Issue by ilyakitaev** [kubernetes/kubeadm#647]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT
## Versions

**kubeadm version** (v1.9.1):

**Environment**:
- **Kubernetes version** (v1.7.5):
- **Cloud provider or hardware configuration**:
Baremetal
- **OS** (e.g. from /etc/os-release):
Centos7
- **Kernel** (e.g. `uname -a`):
3.10.0-514.26.2.el7.x86_64
- **Others**:

## What happened?
Trying to upgrade cluster from version 1.7.5 to 1.8.6

kubeadm upgrade apply v1.8.6

See error below:
`
[bootstraptoken] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[addons] Applied essential addon: kube-dns
[addons] Applied essential addon: kube-proxy
[upgrade/postupgrade] FATAL post-upgrade error: [unable to update RBAC clusterrolebinding: ClusterRoleBinding.rbac.authorization.k8s.io "kubeadm:node-autoapprove-bootstrap" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"system:certificates.k8s.io:certificatesigningrequests:nodeclient"}: cannot change roleRef, unable to update RBAC rolebinding: RoleBinding.rbac.authorization.k8s.io "kubeadm:bootstrap-signer-clusterinfo" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"Role", Name:"kubeadm:bootstrap-signer-clusterinfo"}: cannot change roleRef]

`

## What you expected to happen?

upgrade should succeed without errors

**Comment by kad** [comment]
have you tried to use kubeadm v1.8.x to upgrade  1.7.x->1.8.x ?

**Comment by ilyakitaev** [comment]
@kad that's ok with kubeadm 1.8.6

**Comment by kad** [comment]
To best of my memory, kubeadm 1.9 should support only 1.8 clusters and up. So, to upgrade 1.7 to 1.8 is better to use kubeadm 1.8.x
