### ISSUE TITLE
"kubeadm init" not works

### ISSUE THREAD

**Issue by wangwanchao** [kubernetes/kubeadm#661]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`):
Linux wangsir 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
when execute 'kubeadm init'(i try it with kubeadm1.7.5 and kubeadm 1.8.4)，i get this errors:
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
unable to get URL "https://dl.k8s.io/release/stable-1.8.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.8.txt: net/http: TLS handshake timeout
**OR** [kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
unable to get URL "https://dl.k8s.io/release/stable-1.8.txt": Get https://dl.k8s.io/release/stable-1.8.txt: dial tcp 23.236.58.218:443: getsockopt: connection refused

## What you expected to happen?
it works normally,such as:
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[apiclient] Created API client, waiting for the control plane to become ready
[apiclient] All control plane components are healthy after 31.001311 seconds
[token] Using token: 472def.6bbb304791b76492
[apiconfig] Created RBAC rules
[addons] Applied essential addon: kube-proxy
[addons] Applied essential addon: kube-dns

Your Kubernetes master has initialized successfully!

## How to reproduce it (as minimally and precisely as possible)?
yum install -y socat 
rpm -ivh kubeadm-1.8.4-0.x86_64.rpm kubectl-1.8.4-0.x86_64.rpm kubelet-1.8.4-0.x86_64.rpm kubernetes-cni-0.5.1-1.x86_64.rpm

kubeadm init

## Anything else we need to know?
when execute, the /var/log/messages shows:
Jan 14 10:29:09 wangsir systemd: kubelet.service holdoff time over, scheduling restart.
Jan 14 10:29:09 wangsir systemd: Started kubelet: The Kubernetes Node Agent.
Jan 14 10:29:09 wangsir systemd: Starting kubelet: The Kubernetes Node Agent...
Jan 14 10:29:09 wangsir kubelet: I0114 10:29:09.370760  101467 feature_gate.go:156] feature gates: map[]
Jan 14 10:29:09 wangsir kubelet: I0114 10:29:09.370815  101467 controller.go:114] kubelet config controller: starting controller
Jan 14 10:29:09 wangsir kubelet: I0114 10:29:09.370818  101467 controller.go:118] kubelet config controller: validating combination of defaults and flags
Jan 14 10:29:09 wangsir kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Jan 14 10:29:09 wangsir systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Jan 14 10:29:09 wangsir systemd: Unit kubelet.service entered failed state.
Jan 14 10:29:09 wangsir systemd: kubelet.service failed.
Jan 14 10:29:19 wangsir systemd: kubelet.service holdoff time over, scheduling restart.
Jan 14 10:29:19 wangsir systemd: Started kubelet: The Kubernetes Node Agent.
Jan 14 10:29:19 wangsir systemd: Starting kubelet: The Kubernetes Node Agent...
Jan 14 10:29:19 wangsir kubelet: I0114 10:29:19.621334  101477 feature_gate.go:156] feature gates: map[]
Jan 14 10:29:19 wangsir kubelet: I0114 10:29:19.621408  101477 controller.go:114] kubelet config controller: starting controller
Jan 14 10:29:19 wangsir kubelet: I0114 10:29:19.621411  101477 controller.go:118] kubelet config controller: validating combination of defaults and flags
Jan 14 10:29:19 wangsir kubelet: error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Jan 14 10:29:19 wangsir systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Jan 14 10:29:19 wangsir systemd: Unit kubelet.service entered failed state.
Jan 14 10:29:19 wangsir systemd: kubelet.service failed.

**Comment by kad** [comment]
Your setup seems doesn't have direct access to the internet. Please make sure that before running kubeadm you have specified correctly in environment variables (HTTP_PROXY, HTTPS_PROXY) your proxy host and in NO_PROXY variable you should have at least "localhost,127.0.0.1" and network ranges for your Pod and Services CIDRs. e.g. "10.0.0.0/8".

**Comment by wangwanchao** [comment]
Could you give me some examples?

**Comment by kad** [comment]
Here is example from one of my development hosts, CentOS 7.x. Your distribution might have different way to specify that.

```
[root@k8s-c1 kad]# cat /etc/environment 
export http_proxy=http://proxy.example.com:3128
export https_proxy=http://proxy.example.com:3128
export no_proxy="localhost,127.0.0.1,.example.com,10.0.0.0/8"
[root@k8s-c1 kad]# 
```

**Comment by wangwanchao** [comment]
oh,thank you.due to the GFW, i have encountered all kinds of problems.via VPN, i have deal with this problem.

**Comment by vivuu1989** [comment]
getting same error, when installing kubeadm init

error pulling image configuration: Get https://storage.googleapis.com/asia.artifacts.google-containers.appspot.com/containers/images/sha256:f59dcacceff45b5474d1385cd5f500d0c019ed9ca50ed5b814ac0c5fcec8699e: x509: certificate signed by unknown authority

my hosting server is running behind a proxy (http:// url:8080). How can resolve the issue please. any suggestions, highly appreciated.
