### ISSUE TITLE
Container linux installation - nodes not routable

### ISSUE THREAD

**Issue by Mosho1** [kubernetes/kubeadm#665]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** 1.9.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.9.2
- **Cloud provider or hardware configuration**: Digital Ocean
- **OS** (e.g. from /etc/os-release): coreos 1576.5.0
- **Kernel** (e.g. `uname -a`): 4.14.11-coreos

## What happened?

Tried to install kubeadm using https://kubernetes.io/docs/setup/independent/install-kubeadm/, the container linux sections. While the cluster worked and I could apply configurations which seemed to work, a node was not routable from another node using the flannel assigned IP. The cloud provider-provided private networking IP was routable. Using the ubuntu installation I didn't have the same problem.

## What you expected to happen?

For the installation to work similar to the ubuntu installation.

## How to reproduce it (as minimally and precisely as possible)?

Follow the instructions verbatim (on coreos droplets in DO in my case).

**Comment by errordeveloper** [comment]
Have you tried using Weave Net instead?

**Comment by timothysc** [comment]
closing, no response.
