### ISSUE TITLE
Move release notes to this repo

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#67]
Right now they are in https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/kubeadm.md#releases-and-release-notes, which is a bad place.

Now when we have this repo, they should be moved over here.

**Comment by mikedanese** [comment]
I disagree with this. Docs should remain in the docs repo so they are published to the site.

**Comment by luxas** [comment]
They should never have gone into the website docs, we just had no other place to put them at the time.
Why wouldn't we move them over here in a CHANGELOG like the main repo?
It's not an user-facing document, but more a developer facing doc.

**Comment by mikedanese** [comment]
Release notes are definitely user facing. Release notes are meant to be read by users before upgrading. It would be very nice to publish them on the site.

**Comment by luxas** [comment]
I just think we should be consistent with all other projects.
The main kubernetes repo and minikube both have the CHANGELOG in the repo, not in the docs

We would of course link to the changelog/release notes from the site, but they should not be there IMO.

If we want all changelogs in the docs repo, we should be consistent and do it for all projects in that case.

**Comment by luxas** [comment]
Fixed with #81
