### ISSUE TITLE
kubeadm v1.9.2 join --token [value] [IP:PORT] --discovery-token-ca-cert-hash sha256:[value] results to [discovery] Failed to request cluster info in Vagrant Box

### ISSUE THREAD

**Issue by dominicespiritu** [kubernetes/kubeadm#670]
I'm using vagrant box xenial64 and configured 3 vms named:
node1 = as my master
node2 = as worker node
node3 = as worker node
with docker.io kubeadm kubectl kubelet kubernetes-cni installed on all machines

docker.io version (1.13.1-0ubuntu1~16.04.2).
kubeadm version (1.9.2-00).
kubectl version (1.9.2-00).
kubelet version (1.9.2-00).
kubernetes-cni version (0.6.0-00).

Vagrant file:
  config.vm.define "node1" do |node1|
      node1.vm.box = "ubuntu/xenial64"
      node1.vm.hostname = "master"
      node1.vm.network "private_network", ip: "192.168.32.10"
      node1.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"
  end

  config.vm.define "node2" do |node2|
      node2.vm.box = "ubuntu/xenial64"
      node2.vm.hostname = "node2"
      node2.vm.network "private_network", ip: "192.168.32.20"
  end

  config.vm.define "node3" do |node3|
      node3.vm.box = "ubuntu/xenial64"
      node3.vm.hostname = "node3"
      node3.vm.network "private_network", ip: "192.168.32.30"
  end

## What happened?
when I try to join from my node2 or node3 using 
kubeadm join --token [token value] [ip:port] --discovery-token-ca-cert-hash sha256:[token value]
the result is:
[discovery] Trying to connect to API Server "10.0.2.15:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://10.0.2.15:6443"
[discovery] Failed to request cluster info, will try again: [Get https://10.0.2.15:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.0.2.15:6443: getsockopt: connection refused]

## How to reproduce it (as minimally and precisely as possible)?
connect from worker node to your master using the value generated after kubeadm init

Thanks

**Comment by dixudx** [comment]
@dominicespiritu Please help check the apiserver on node1, whether the port is opened and listened on `192.168.32.10`. Also please make sure node2/node3 can access node1.

If it is listened on localhost/127.0.0.1, please run `kubeadm rest` to purge the cluster and rerun `kubeadm init --apiserver-advertise-address=192.168.32.10` to boot up a new cluster.

**Comment by dominicespiritu** [comment]
@dixudx thank you for your response, I manage to resolve the problem by adding --apiserver-advertise-address, the problem that popped out then is when I join a node, my minion is trying to connect with  master ip 10.96.0.1, which on my case the ip of my master is 192.168.32.10, so after some searching I found a solution at this [thread](https://stackoverflow.com/questions/41984399/denied-requested-access-to-the-resource-is-denied-docker), now my local environment works fine with 1 master and 2 cluster inside my vagrant box.

**Comment by dixudx** [comment]
@dominicespiritu So we can close this issue now ?

**Comment by dominicespiritu** [comment]
@dixudx yes this is now resolved. Thank you
