### ISSUE TITLE
CoreOS: Mount /usr/share/ca-certificates inside kube-controller-manager

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes/kubeadm#671]
## What keywords did you search in kubeadm issues before filing this one?

CoreOS, /usr/share/ca-certificates, /etc/ssl/certs

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** 1.9.2
**Environment**:
- **Kubernetes version** 1.9.2
- **Cloud provider or hardware configuration**: DigitalOcean
- **OS** (e.g. from /etc/os-release): CoreOS

## What happened?

`kube-controller-manager` currently mounts `/etc/ssl/certs`, but on CoreOS `/etc/ssl/certs` just contain a bunch of symlinks to `/usr/share/ca-certificates`.

A CA root is needed for ex [flexvolume plugin](https://github.com/kubernetes-incubator/external-storage/issues/571#issuecomment-360155462).

## What you expected to happen?

`kube-controller-manager` (and other pods which mounts `/etc/ssl/certs`), should also mount `/usr/share/ca-certificates` so the root is also available if the Linux distribution use symlinks to `/usr/share/ca-certificates`.

## How to reproduce it (as minimally and precisely as possible)?

Use a flexvolume plugin which require a CA root on ex: CoreOS, it won't work as the symlink isn't available inside the `kube-controller-manager` pod.

## Anything else we need to know?

See also: https://github.com/kubernetes-incubator/external-storage/issues/571#issuecomment-360155462, https://github.com/kubernetes-incubator/external-storage/issues/571#issuecomment-360176495 and https://github.com/kubernetes-incubator/external-storage/issues/571#issuecomment-360179063.

cc @lloeki

**Comment by lloeki** [comment]
There are some other paths that may be symlinked to:

- `/usr/local/share/ca-certificates`: https://manpages.debian.org/stretch/ca-certificates/update-ca-certificates.8.en.html
- `/etc/ca-certificates/trust-source/anchors` https://www.archlinux.org/news/ca-certificates-update/

**Comment by lblackstone** [comment]
It looks like this condition is already partially handled in the volume mount code.

https://github.com/kubernetes/kubernetes/blob/v1.9.2/cmd/kubeadm/app/phases/controlplane/volumes.go#L41-L43

https://github.com/kubernetes/kubernetes/blob/v1.9.2/cmd/kubeadm/app/phases/controlplane/volumes.go#L92-L93

https://github.com/kubernetes/kubernetes/blob/v1.9.2/cmd/kubeadm/app/phases/controlplane/volumes.go#L218-L220

**Comment by klausenbusk** [comment]
> It looks like this condition is already partially handled in the volume mount code.

PR opened: https://github.com/kubernetes/kubernetes/pull/59122

**Comment by klausenbusk** [comment]
> There are some other paths that may be symlinked to:

I only think `/etc/ca-certificates` is relevant, `update-ca-certificates` on Debian "bundle" all the certificates into `/etc/ssl/certs/ca-certificates.crt`, so I suppose that is enough (?).
