### ISSUE TITLE
kubeadm upgrade is not aware of installed kubelet version

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubeadm#672]
```
[upgrade/successful] SUCCESS! Your cluster was upgraded to "v1.9.2". Enjoy!

[upgrade/kubelet] Now that your control plane is upgraded, please proceed with upgrading your kubelets in turn.
root@raspberrypi:/home/pi# kubectl get no raspberrypi
NAME          STATUS    ROLES     AGE       VERSION
raspberrypi   Ready     master    94d       v1.9.2
```
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by timothysc** [comment]
@kargakis this is known - What do you propose?

**Comment by timothysc** [comment]
cc: @chuckha

**Comment by kargakis** [comment]
One solution is to list all nodes, check their status (since `kubeletVersion` is a field), and report accordingly. We should assess whether that's a viable option for big clusters (node objects can get pretty large). Another option is to slightly reword the message to something like "please proceed with upgrading your kubelets if you haven't already done it".
