### ISSUE TITLE
Require user confirmation when resetting a master node

### ISSUE THREAD

**Issue by binarybana** [kubernetes/kubeadm#673]
### FEATURE REQUEST

Using `kubeadm` 1.9, I accidentally issued a `kubeadm reset` on my master node instead of a worker node (due to a dropped SSH connection). This deleted the cluster credentials and despite the `etcd` manifest using a `hostDir` for data, it seems that the re-created cluster did not successfully get repopulated with the previous etcd data.

I think it would be really nice if there was a strong confirmation requirement when `kubeadm reset` is issued on a master node. Something like:
```
$ kubeadm reset
[Warning] Are you sure you want to delete this master node? Type the word 'confirm' below to continue:
```

Luckily it is/was just a test cluster, but still caused a bit of (avoidable) pain...

**Comment by timothysc** [comment]
Strong +1 here.  

cc @chuckha

**Comment by alexbrand** [comment]
I can work on this if it's still up for grabs.

**Comment by timothysc** [comment]
go for it.. I will remove the label
