### ISSUE TITLE
Move passthrough commands to either phases or feature gated flags.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#676]
TODO: Link to other issue.  

Temporary flags had been promoted to 1st class flags when they should not be.

**Comment by kris-nova** [comment]
@timothysc I might be able to help with this one - any more information?

**Comment by timothysc** [comment]
@kris-nova yes, https://github.com/kubernetes/kubernetes/pull/58080 moved some flags to top level when they should really be either phase-alpha or feature gates options.

**Comment by fabriziopandini** [comment]
@kris-nova I'm working to an idea for getting rid of all the scaffholding code for handling command line flags that exists both in `kubeadm\app\cmd` and in `kubeadm\app\cmd\phases`. 

ping me on slack if you think that this can be of interest for this issue 😉

**Comment by kris-nova** [comment]
So this is pending a discussion next week in sig cluster lifecycle regarding flags in general. I will add to the agenda.
