### ISSUE TITLE
manifest files shouldn't be executable

### ISSUE THREAD

**Issue by jaxxstorm** [kubernetes/kubeadm#678]
## Is this a request for help?

no

## What keywords did you search in kubeadm issues before filing this one?

manifest, permissions

## Is this a BUG REPORT or FEATURE REQUEST?

Feature Request

Currently, when kubeadm generates manifest files, the permissions on those files are 700 with owner root:root.

It makes very little sense to have the excute perms on there. The CIS for Kubernetes rules specify that they should be 0644 or lower, so perhaps they should be set to 0600

## Versions

**kubeadm version** (use `kubeadm version`):
 1.8.4

**Environment**:
- **Kubernetes version** (use `kubectl version`):  1.8.4
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): 3.10.0-514.16.1.el7.x86_64
- **Others**:

**Comment by timothysc** [comment]
cc: @chuckha @detiber

**Comment by jaxxstorm** [comment]
@timothysc @chuckbutler @detiber I've submitted a PR for this
