### ISSUE TITLE
Allow configuration of criSocket when using the MasterConfiguration manifest

### ISSUE THREAD

**Issue by JordanFaust** [kubernetes/kubeadm#679]
Currently, it is not possible to use the MasterConfiguration manifest file to configure a cluster and use a container runtime other than docker. The use of the --config flag disables the ability to use the --cri-socket flag to set the desired container runtime to something other than docker. The MasterConfiguration manifest should be updated to include a similar field to configure the cri socket.

## Versions
(use `kubeadm version`): 1.9.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.9.2
- **Cloud provider or hardware configuration**: RHEL 7
- **OS** (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.3 (Maipo)
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
When choosing to use cri-o as the container runtime in place of docker, kubeadm fails in preflight checks since the --cri-socket option can not be used with the --config flag. The default for --cri-socket is set the /var/run/dockershim.sock which will not exist on nodes that don't have docker installed.

## What you expected to happen?
The --cri-socket flag to be a configuration value within the MasterConfiguration manifest.

## How to reproduce it (as minimally and precisely as possible)?
* Install cri-o in-place of docker: https://github.com/kubernetes-incubator/cri-o

* Create a minimal master configuration file:

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 10.190.168.14
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.244.0.0/16
kubernetesVersion: v1.9.2
nodeName: kubernetes01
token: REDACTED
apiServerCertSANs:
- kubernetes01
apiServerExtraArgs:
  endpoint-reconciler-type: lease
```

* Attempt to init the master
```
kubeadm init --config=config.yaml
```

Output:

```
11:06:58 # kubeadm init --config=config.yaml --dry-run
[init] Using Kubernetes version: v1.9.2
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
criSocket %v /var/run/dockershim.sock
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 3.10.0-514.26.2.el7.x86_64
CONFIG_NAMESPACES: enabled
CONFIG_NET_NS: enabled
CONFIG_PID_NS: enabled
CONFIG_IPC_NS: enabled
CONFIG_UTS_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_CPUSETS: enabled
CONFIG_MEMCG: enabled
CONFIG_INET: enabled
CONFIG_EXT4_FS: enabled (as module)
CONFIG_PROC_FS: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_AUFS_FS: not set - Required for aufs.
CONFIG_BLK_DEV_DM: enabled (as module)
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
[preflight] Some fatal errors occurred:
	[ERROR SystemVerification]: failed to get docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	[ERROR CRI]: unable to check if the container runtime at "/var/run/dockershim.sock" is running: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

**Comment by xiangpengzhao** [comment]
/close
as this is already fixed by the referenced PRs.
