### ISSUE TITLE
no service with name default/default-http-backend found

### ISSUE THREAD

**Issue by balasath** [kubernetes/kubeadm#680]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`): 1.8.7

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
I tried to create nginx ingress controller.  I am getting the following error in the container log.

launch.go:113] no service with name default/default-http-backend found: Get https://10.96.0.1:443/api/v1/namespaces/default/services/default-http-backend: dial tcp 10.96.0.1:443: getsockopt: no route to host

default-http-backend container is created and running.  But when I execute the above url (https://10.96.0.1:443/api/v1/namespaces/default/services/default-http-backend) using curl.  I got the following message:

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "services \"default-http-backend\" is forbidden: User \"system:anonymous\" cannot get services in the namespace \"default\"",
  "reason": "Forbidden",
  "details": {
    "name": "default-http-backend",
    "kind": "services"
  },
  "code": 403

What is missing here?

**Comment by timothysc** [comment]
cc @chuckha @detiber

**Comment by balasath** [comment]
OS: Redhat
Not running on cloud
Kubectl version: 1.8.7

**Comment by kargakis** [comment]
How did you create the ingress controller? Can you share its config?

**Comment by roberthbailey** [comment]
Where are you running curl from? The error message is that you aren't passing client credentials, so the Kubernetes apiserver is rejecting your request because it can't authenticate you; not because the service doesn't exist.

Based on the first set of logs, it appears that even if you launched the default-http-backend pod you haven't created the service to point to it. What's interesting is that it is looking for the service in the default namespace. If you run `kubectl get svc -n kube-system` does it show that there is a service called `default-http-backend`?

Here's what I see on a newly created GKE cluster:

```
$ kubectl get svc -n kube-system default-http-backend
NAME                   TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
default-http-backend   NodePort   10.23.252.31   <none>        80:30817/TCP   29m
```

/cc @nicksardo

**Comment by nicksardo** [comment]
User commented that they're not running on a cloud, so they won't see a default backend - that addon is shipped for GCE/GKE clusters.  

The ingress-nginx docs show how to deploy it: https://github.com/kubernetes/ingress-nginx/tree/master/deploy

**Comment by roberthbailey** [comment]
In the first comment it says

> default-http-backend container is created and running.

which I took to mean that it had been manually added.

**Comment by timothysc** [comment]
So I'm closing this issue, b/c there are a number of well-documented paths for setting up ingress on different providers and on-prem, and due to lack of activity from the original filer.  

We setup ingress on-prem and across different clouds w/kubeadm installations.
