### ISSUE TITLE
Error while initializing connection to kubernetes apiserver

### ISSUE THREAD

**Issue by balasath** [kubernetes/kubeadm#681]
I tried to create haproxy ingress controller.  I got the following error when I tried to create controller pod:

 launch.go:318] Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration). Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: getsockopt: no route to host.

I tried to execute the url https://10.96.0.1:443/version using curl.  I got the following message

{
  "major": "1",
  "minor": "8",
  "gitVersion": "v1.8.7",
  "gitCommit": "b30876a5539f09684ff9fde266fda10b37738c9c",
  "gitTreeState": "clean",
  "buildDate": "2018-01-16T21:52:38Z",
  "goVersion": "go1.8.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
What I am missing here?  Can you please help?

**Comment by timothysc** [comment]
Could you provide more details, please?  

What is your host OS?
Are you running on a Cloud Provider?
What CNI did you Choose? 
Did you run the conformance tests post standup (https://scanner.heptio.com/) 

... 

Right now there is not enough detail for me to dig.   

cc: @chuckha

**Comment by balasath** [comment]
OS: Redhat
Are you running on a Cloud provider? No
CNI: Weave

**Comment by chuckha** [comment]
@balasath did you use kubeadm to install your cluster?
would you be able to provide steps to reproduce & is it reproducible on newer versions of kubernetes?

**Comment by timothysc** [comment]
Closing due to timeout, please reopen with more data if you are still having an issue.

**Comment by adityajalkhare** [comment]
Dirty and Fast Solution: Restart all the pods in kube-system namespace.
Actual Solution: Run kubectl get nodes, then kubectl describe nodes.

Check the output of describe, whether the heartbeat signals are latest or not. 

See the logs of networking pods as to know what caused this and Why. In the end, restart pods related to networking and other networking related components.

**Comment by adityajalkhare** [comment]
> I tried to create haproxy ingress controller. I got the following error when I tried to create controller pod:
> 
> launch.go:318] Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration). Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: getsockopt: no route to host.
> 
> I tried to execute the url https://10.96.0.1:443/version using curl. I got the following message
> 
> {
> "major": "1",
> "minor": "8",
> "gitVersion": "v1.8.7",
> "gitCommit": "b30876a5539f09684ff9fde266fda10b37738c9c",
> "gitTreeState": "clean",
> "buildDate": "2018-01-16T21:52:38Z",
> "goVersion": "go1.8.3",
> "compiler": "gc",
> "platform": "linux/amd64"
> }
> What I am missing here? Can you please help?

Dirty and Fast Solution: Restart all the pods in kube-system namespace.
Actual Solution: Run kubectl get nodes, then kubectl describe nodes.

Check the output of describe, whether the heartbeat signals are latest or not.

See the logs of networking pods as to know what caused this and Why. In the end, restart pods related to networking and other networking related components.
