### ISSUE TITLE
kubectl 1.9.2 pod status always pending on single cluster setup

### ISSUE THREAD

**Issue by dominicespiritu** [kubernetes/kubeadm#685]
## What happened?
My test pod is always on pending status
below is the pod description

Name:         boot1-pod
Namespace:    default
Node:         <none>
Labels:       version=v1
              zone=prod
Annotations:  <none>
Status:       Pending
IP:
Containers:
  boot1-ctr:
    Image:        dominicespiritu/boot1
    Port:         8080/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2222s (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  default-token-2222s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2222s
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  0s (x20 over 5m)  default-scheduler  0/1 nodes are available: 1 PodToleratesNodeTaints.

my kubernetes cluster is inside vagrant box ubuntu xenial64
## What you expected to happen?
pod created should be running

## How to reproduce it (as minimally and precisely as possible)?
I manually install docker.io kubeadm kubectl kubelet kubernetes-cni on my vagrant box ubuntu xenial64 and created 1 test pod

## Anything else we need to know?
the versions installed are:
docker.io1.13.1-0ubuntu1~16.04.2
kubeadm 1.9.2-00
kubectl 1.9.2-00
kubelet 1.9.2-00
kubernetes-cni 0.6.0-00

**Comment by kad** [comment]
what reports `kubectl get nodes` ? e.g. do you have your node in NotReady state due to missing network provider ?
Another reason might be: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#master-isolation

**Comment by dominicespiritu** [comment]
Hi Kad,

Thank you for your reply, I just created a new and different setup approach on my local using centos7 and now its working.

Cheers,
Dominic
