### ISSUE TITLE
Add details how to contribute to kubeadm in the docs

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/kubeadm#686]
I attempted to run the tests under `k8s.io/kubernetes/cmd/kubeadm/test` by running:

```
# pwd
/Users/abrand/go/src/k8s.io/kubernetes
# make test WHAT=./cmd/kubeadm/test/cmd
```

However, this failed because I hadn't set an environment variable that is expected in one of the tests. After setting the env var, the tests passed. It also seems like one can run `./hack/make-rules/test-kubeadm-cmd.sh` to achieve the same thing. 

I couldn't find this documented, so it would be nice for newcomers to have this documented somewhere, although I am not sure where. Maybe a small developer guide in this repo?

**Comment by timothysc** [comment]
I believe there is a development doc on this repo that can be updated.

**Comment by neolit123** [comment]
^ submitted change to `website` that adds a new kubeadm page about unit tests at this location:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/
