### ISSUE TITLE
prefilight checks fail when external etcd uses /var/lib/etcd as data directory

### ISSUE THREAD

**Issue by codablock** [kubernetes/kubeadm#69]
When I try to create a custom/external etcd cluster which runs on the same host, I currently can not use /var/lib/etcd as data directory. The reason is, that etcd is already running when kubeadm init is called and the preflight checks fail due to /var/lib/etcd not being empty.

I would assume that the preflight checks to not check /var/lib/etcd when --external-etcd-endpoints is specified. Also, I would expect kubeadm reset to NOT clear /var/lib/etcd when there is no static etcd manifest in /etc/kubernetes/manifests/.

As I've seen, --external-etcd-endpoints is deprecated and will be replaced with "componentconfig". Is there already a timeline for this? I would like to create a PR which adds some conditionals to the preflight checks and the reset command. Would such a PR still be accepted?

**Comment by luxas** [comment]
Feel free to send a PR and we'll see which parts we want, overall sounds good to me.

Re componentconfig: It's possible to already set `--config my-kubeadm-init-yaml-file.yaml` and let init or join take its options from there. We will and should document that,

**Comment by codablock** [comment]
Created a PR: https://github.com/kubernetes/kubernetes/pull/37524
