### ISSUE TITLE
Unable to get Kubernetes-HA-Cluster up and running when following the docu on Kubernets.io

### ISSUE THREAD

**Issue by SGrengel** [kubernetes/kubeadm#691]
## Is this a request for help?

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

**YES ... allready been going through those files a lot.**

## What keywords did you search in kubeadm issues before filing this one?

Bearer-Tocken, Master NotReady, core.Service: Unauthorized, core.Endpoints: Unauthorized, CNI missing, Weave, Calico, proxy, kube-dns not starting, ...

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**OS version:**
_Linux eisvm051 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux_

**Docker version:**
_Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Jul 20 00:06:39 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Jul 20 00:06:39 2017
 OS/Arch:         linux/amd64_

**ETCD version:**
_etcd Version: 3.1.10
Git SHA: 0520cb9
Go Version: go1.8.3
Go OS/Arch: linux/amd64_

**KeepaliveD version:**
_keepalived.x86_64                   1.3.5-1.el7_

**Kubectl version:**
_Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}_

**Kubeadm version:**
_kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}_

## What happened?

All Servers are VM’s on ESX-Farm

3 Servers for Kubernetes-Master running ETCD and keepalived (Loadbalancer) in parallel.
2 to 4 Workers in Test-Env. Up to 13 Workers will be joined at the End.

All Servers are connecting to the Internet using a coporate Proxy. Proxy-Settings on each Server look as shown below:

_http_proxy=<Our-Porxy>:8080
https_proxy=<Our-Porxy>:8080
no_proxy=localhost,127.0.0.1,localaddress,10.96.0.0/12,16.31.17.51,16.31.17.52,16.31.17.53,192.168.0.0/16_

Docker-Proxy is configured seperatly in two files located in /etc/systemd/system/docker.service.d/ as shown below:

**http-proxy.conf**

_[Service]
Environment="HTTP_PROXY=https:// <Our-Porxy>:8080/"_

**https-proxy.conf**

_[Service]
Environment="HTTPS_PROXY=https:// <Our-Porxy>:8080/"_

I am following the Installation-Guid on **https://kubernetes.io/docs/setup/independent/high-availability/** to install the HA-Cluster as described. Following option 2 which means that the ETCD-Cluster is running on the same Servers as the Kubernetes-Master-Nodes. ETCD-Config looks as follows:

_[Unit]
Description=etcd
Documentation=https://github.com/coreos/etcd
Conflicts=etcd.service
Conflicts=etcd2.service

[Service]
EnvironmentFile=/etc/etcd.env
Type=notify
Restart=always
RestartSec=5s
LimitNOFILE=40000
TimeoutStartSec=0

ExecStart=/usr/local/bin/etcd --name eisvm051 \
    --data-dir /var/lib/etcd \
    --listen-client-urls https://16.31.17.51:2379 \
    --advertise-client-urls https://16.31.17.51:2379 \
    --listen-peer-urls https://16.31.17.51:2380 \
    --initial-advertise-peer-urls https://16.31.17.51:2380 \
    --cert-file=/etc/kubernetes/pki/etcd/server.pem \
    --key-file=/etc/kubernetes/pki/etcd/server-key.pem \
    --client-cert-auth \
    --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem \
    --peer-cert-file=/etc/kubernetes/pki/etcd/peer.pem \
    --peer-key-file=/etc/kubernetes/pki/etcd/peer-key.pem \
    --peer-client-cert-auth \
    --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem \
    --initial-cluster eisvm051=https://16.31.17.51:2380,eisvm052=https://16.31.17.52:2380,eisvm053=https://16.31.17.53:2380 \
    --initial-cluster-token my-etcd-token \
    --initial-cluster-state new

[Install]
WantedBy=multi-user.target_

Using keepalived as the loadbalancer with the following config on Master:

_! Configuration File for keepalived
 
vrrp_instance VI_1 {
  state MASTER
  interface ens192
  virtual_router_id 51
  priority 101
  advert_int 1
  authentication {
      auth_type PASS
      auth_pass 1111
  }
  virtual_ipaddress {
      16.31.17.92
  }
}
 
virtual_server 16.31.17.92 6443 {
  delay_loop 5
  lb_algo lc
  lb_kind DR
  persistence_timeout 7200
  protocol TCP

  real_server 16.31.17.51 6443 {
      weight 1
      TCP_CHECK {
        connect_timeout 5
        connect_port    6443
      }
  }
  real_server 16.31.17.52 6443 {
      weight 1
      TCP_CHECK {
        connect_timeout 5
        connect_port    6443
      }
  }
  real_server 16.31.17.53 6443 {
      weight 1
      TCP_CHECK {
        connect_timeout 5
        connect_port    6443
      }
  }
}_

The only **difference on the Slaves** are the **state and priority which is BACKUP and 100 on both**.
The config.yaml which will be used by kubeadm looks as follows:

_apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 16.31.17.51
etcd:
  endpoints:
  - https://16.31.17.51:2379
  - https://16.31.17.52:2379
  - https://16.31.17.53:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: 192.168.0.0/16
apiServerCertSANs:
- 16.31.17.92
apiServerExtraArgs:
--endpoint-reconciler-type: lease_

AdvertiseAddress is changed on all three Servers to match the IP of the related Server. Everything else stays the same.

We are then running kubeadm init –config=config.yaml to initialize the first Master on 51. Everything runs smooth except a warning on crictl which can´t be found, but that shouldn´t be a problem according to other posts here.

 

At that point the Master is in Status NotReady and kubelet is complaining about the missing CNI-Network. All pods are up except DNS-Pod.

Next thing we are copying the ca.crt and ca.key from /etc/kubernetes/pki to the same folder on the other two Servers. Then we are running the kubeadm with the same config.yaml except the changed advertiseAddress on the second master. Everything looks the same as on the first master only difference is that we are now getting the following entries in /var/log/messages:

_Feb  2 15:49:31 eisvm052 journal: E0202 14:49:31.716127       1 authentication.go:64] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]
Feb  2 15:49:31 eisvm052 journal: E0202 14:49:31.715354       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.Service: Unauthorized
Feb  2 15:49:31 eisvm052 journal: E0202 14:49:31.716482       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.Endpoints: Unauthorized_

We ignore that and keep going with the third master with the same result as we got on the second one.

All nodes are now showing the Status NotReady at this point.
All Pods are up and running except kube-dns.

Now we proceed with installing Weave on the first Master as follows:

_export kubever=$(kubectl version | base64 | tr -d '\n')
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"_

No Errors and the Node changes Status to Ready, Master2 and 3 are still NotReady.
Kube-dns is still down in Status ContainerCreating, weave-net-pod on Master1 is up

We proceed with installing Weave on Master 2 and 3 which doesn’t change anything on the Status of the Nodes, only difference is that we have two additional weave-net-pods which keep failing with Status CrashLoopBackOff.

Does anybody a an Idea what we could do to get the Cluster up and running, we are running out of options.

## What you expected to happen?

I expected the Kubernetes Master to come up without errors so I am able to join the workers

## How to reproduce it (as minimally and precisely as possible)?

Follow the Docu on https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by alexpekurovsky** [comment]
Try to copy also sa.* files, not only ca.*
It solve do for me exact same problem

**Comment by krasaee** [comment]
Confirmed, problem was the /etc/kubernetes/pki/sa.* files need to be moved from master0 node as well. Suggest updating the document to reflect this. I was able to fix this simply by copying the files over and restarting the cluster.  in my case kube-dns refused to go online after calico-node installation using external etcd.

**Comment by alexpekurovsky** [comment]
It's already in PR for documentation https://github.com/kubernetes/website/pull/7425

**Comment by SGrengel** [comment]
Thank You for the hint we'll Test it ...

**Comment by SGrengel** [comment]
Cluster works fine now after sa.* files in /etc/kubernetes/pki have been copied to the additional Masters, too before running kubeadm init.

Thank´s to everybody for the help.

**Comment by SGrengel** [comment]
Problem solved ...
