### ISSUE TITLE
kubeadm init - returns 403 forbidden

### ISSUE THREAD

**Issue by eltonplima** [kubernetes/kubeadm#692]
**kubeadm version**:
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
4 x Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz

- **OS** (e.g. from /etc/os-release):
ubuntu 16.04.3 LTS (Xenial Xerus)

- **Kernel** (e.g. `uname -a`):
Linux INDQRPDM02 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
When I try to run:
```
sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.1.82 --kubernetes-version stable-1.9
```

I only get this error:
unable to fetch file. URL: "https://dl.k8s.io/release/stable-1.9.txt" Status: 403 Forbidden

## What you expected to happen?

The kubernetes cluster is initialized.

**Comment by joshuacox** [comment]
I imagine someone at google moved something around without realizing this would happen

**Comment by eltonplima** [comment]
Works again!
