### ISSUE TITLE
kubeadm init --service-cidr= validations are broken for IPv6 subnets

### ISSUE THREAD

**Issue by SpComb** [kubernetes/kubeadm#695]
## Versions
`kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

## What happened?

The `kubeadm init` validations incorrectly reject a `--service-cidr=.../64` subnet as being too *small*:

```
$ sudo kubeadm init --service-cidr=fd00::/64
[init] Using Kubernetes version: v1.9.2
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING FileExisting-crictl]: crictl not found in system path
service-subnet: Invalid value: "fd00::/64": subnet is too small
```

This presumably happens because the [`ipallocator.RangeSize(svcSubnet)` => `2^64`](https://github.com/kubernetes/kubernetes/blob/v1.9.2/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L258-L261) overflows an `int64`.

OTOH the `kubeadm init` validations accept a `--service-cidr=.../96`:
```
$ sudo kubeadm init --apiserver-advertise-address=... --service-cidr=fd00::/96
[init] Using Kubernetes version: v1.9.2
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING FileExisting-crictl]: crictl not found in system path
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [terom-kube-master kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [fd00::1 2604:1...:13]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[controlplane] Wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] Wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] Wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
```

But the apiserver startup fails with `--service-cluster-ip-range=fd00::/96`, causing the `kubeadm init` to hang:

```
$ docker logs k8s_kube-apiserver_...
I0208 18:19:41.153675       1 server.go:121] Version: v1.9.2
specified --service-cluster-ip-range is too large
```

The service cluster IP range is [validated by the kube-apiserver](https://github.com/kubernetes/kubernetes/blob/v1.9.2/cmd/kube-apiserver/app/options/validation.go#L29-L32) to have at most 20 host bits, because it gets used a a bit mask: https://github.com/kubernetes/kubernetes/issues/12820

## What you expected to happen?

The `kubeadm init` command should reject an IPv6 `--service-subnet=...` as being "too large" if it is larger than a `/108`. I was able to successfuly initialize a cluster using a `--service-cidr=fd00:XXXX:XXX::/112` subnet (16 host bits).

## How to reproduce it (as minimally and precisely as possible)?

See examples under "What happened"

## Anything else we need to know?

Likewise for IPv4, a `kubeadm init --service-subnet=10.0.0.0/8` should probably also fail validation before causing the `kube-apiserver` to fail? I did not test this...

**Comment by fabriziopandini** [comment]
Might be this PR already fixes this issue:
https://github.com/kubernetes/kubernetes/pull/58769

**Comment by timothysc** [comment]
Closing, it looks like kubernetes/kubernetes#58769 fixes.

**Comment by sanmai-NL** [comment]
@timothysc However, this limitation hasn't been documented.

**Comment by neolit123** [comment]
> @timothysc However, this limitation hasn't been documented.

where would you expect this to be documented?

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/dual-stack-support/#create-a-dual-stack-cluster
https://kubernetes.io/docs/concepts/services-networking/dual-stack/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

or another location? 

kubeadm does have validation for the pod / service subnet sizes, but there are no subnet sizes explained in the kubeadm API or CLI flags.

**Comment by sanmai-NL** [comment]
In both the config parameter docs as well as the networking guides, since it's both a validation/restriction and a fundamental design choice that warrants some background.

**Comment by sanmai-NL** [comment]
And I wouldn't put it in `kubeadm`, but rather in the components/subsystems, since it applies to other certified Kubernetes packages too.

**Comment by neolit123** [comment]
got it. you can help us by logging a ticket in https://github.com/kubernetes/website and explain the problem there.
tag the ticket with this command in a comment `/sig network`. you can also ping #sig-network on k8s slack with a link to this ticket. sig-network are the owners of all things networking in k8s.
