### ISSUE TITLE
KubeDNS should run as a daemonset

### ISSUE THREAD

**Issue by HcgRandon** [kubernetes/kubeadm#697]
## What keywords did you search in kubeadm issues before filing this one?
dns, kubedns, daemonset

## Is this a BUG REPORT or FEATURE REQUEST?
Choose one: FEATURE REQUEST

Due to kube-dns running on only the master node in a `kubeadm init` cluster this creates a single point of failure for applications that heavily rely on dns, a simple reboot of the master node is enough to break such an application until master returns.

For these reasons I feel that kube-dns should run across all nodes in the cluster as a daemonset, or at least more then one node.

Thanks.

## Versions

**kubeadm version** (use `kubeadm version`):
```
root@master-1:~# salt '*' cmd.run 'kubeadm version'
us-east-1:
    kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
master-1:
    kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
eu-1:
    kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
bare metal
- **OS** (e.g. from /etc/os-release):
```
root@master-1:~# salt '*' cmd.run 'cat /etc/os-release'
master-1:
    PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
    NAME="Debian GNU/Linux"
    VERSION_ID="8"
    VERSION="8 (jessie)"
    ID=debian
    HOME_URL="http://www.debian.org/"
    SUPPORT_URL="http://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
us-east-1:
    PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
    NAME="Debian GNU/Linux"
    VERSION_ID="9"
    VERSION="9 (stretch)"
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
eu-1:
    PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
    NAME="Debian GNU/Linux"
    VERSION_ID="9"
    VERSION="9 (stretch)"
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
```
- **Kernel** (e.g. `uname -a`):
```
root@master-1:~# salt '*' cmd.run 'uname -a'
master1:
    Linux master-1 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
us-east-1:
    Linux us-east-1 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
eu-1:
    Linux eu-1 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
```
- **Others**:

## What happened?
Outbound traffic fails to continue, due to dns being unavailable for resolving ip

## What you expected to happen?
dns to continue to resolve without the presence of master, or at least dns lookups to fallback to current nodes /etc/resolve.conf

## How to reproduce it (as minimally and precisely as possible)?
1. init a kubeadm cluster
2. create and deploy a simple application that does a lot of dns lookups to an external service (ie: example.com)
3. reboot / turn off master node while application is running

## Anything else we need to know?
The application where I am experiencing this behaviour is nodejs based.

**Comment by webwurst** [comment]
Maybe see https://github.com/kubernetes/kubernetes/pull/57683 and https://github.com/kubernetes/kubernetes/pull/59357 for some earlier discussion around this problem.

**Comment by timothysc** [comment]
Closing, we've been following the other patterns that exist for all deployments.  

/assign @detiber
