### ISSUE TITLE
Allow passing a version to kubeadm upgrade plan

### ISSUE THREAD

**Issue by mbert** [kubernetes/kubeadm#698]
## What keywords did you search in kubeadm issues before filing this one?

upgrade

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

When running `kubeadm upgrade plan`, kubeadm will try to obtain the latest stable release via http. On systems without connection to the internet this will fail. While kubeadm deals with this nicely by selecting its own version, it takes some unnessary waiting until the http GET has failed. It would be nice to pass a version argument to `upgrade plan` the same way as to `upgrade apply`.

**Comment by luxas** [comment]
Sounds good to me. PRs welcome :wink:

**Comment by mattkelly** [comment]
I'm happy to pick this up unless you were planning on it @mbert. I know there was some recent discussion around avoiding adding command line flags for now. I guess an optional arg such as this doesn't count so we're ok with doing this?

**Comment by mbert** [comment]
That would be nice. I wasn't planning on it since I usually don't develop in go, hence would have to do some catching up in setting up toolchain, understanding code etc. I guess you'll be faster :)
