### ISSUE TITLE
[kubeadm] fail fast if two nodes have the same name

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubeadm#7]
_From @luxas on November 4, 2016 19:22_

ref: http://stackoverflow.com/questions/40294423/kubeadm-why-does-my-node-not-show-up-though-kubelet-says-it-joined/40416796#40416796

@kubernetes/sig-cluster-lifecycle 

_Copied from original issue: kubernetes/kubernetes#36255_

**Comment by pires** [comment]
This may be caused by #64.

**Comment by luxas** [comment]
PR is here: https://github.com/kubernetes/kubernetes/pull/37084

**Comment by chrissound** [comment]
This still seems to be an issue: https://stackoverflow.com/questions/49017719/kubernetes-pods-in-master-node-restarting-after-kubeadm-join-on-worker-node
