### ISSUE TITLE
Release third stable revision of kubeadm

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#70]
We will release the third revision of kubeadm from the kubernetes/kubernetes before we move the kubeadm code over here.

That new version will feature the following PRs and will have the following CHANGELOG:
 - Incorporated the system verification check into the preflight checks [#36334](https://github.com/kubernetes/kubernetes/pull/36334)
 - The control plane version automatically defaults to the latest stable version of kubernetes [#37222](https://github.com/kubernetes/kubernetes/pull/37222)
 - Use of etcd 3.0.14 as the default etcd version [#35921](https://github.com/kubernetes/kubernetes/pull/35921)
 - Added a new command: `kubeadm token generate` [#35144](https://github.com/kubernetes/kubernetes/pull/35144)
 - Changed unconfined_t to spc_t [#37327](https://github.com/kubernetes/kubernetes/pull/37327)
 - Removes `/etc/cni` when doing `kubeadm reset` [#35709](https://github.com/kubernetes/kubernetes/pull/35709)
 - The image repository prefix can be changed via the environment [#35948](https://github.com/kubernetes/kubernetes/pull/35948)
 - Small other improvements: [#36040](https://github.com/kubernetes/kubernetes/pull/36040), [#36625](https://github.com/kubernetes/kubernetes/pull/36625), [#36474](https://github.com/kubernetes/kubernetes/pull/36474)

I might extend this list to a few more if necessary...

I will merge these PRs as soon as master opens for v1.6 PRs and release that version as stable for v1.5.

PTAL @kubernetes/sig-cluster-lifecycle

**Comment by dgoodwin** [comment]
Could we pick up https://github.com/kubernetes/kubernetes/pull/35805 before the migration or does this need to wait?

**Comment by luxas** [comment]
I will pick up all PRs before I move the code over to this repo, but before that I will release a stable version of kubeadm from kubernetes master.

Your PR is kind of "unstable", so I don't think it should be in the release, but it'll get merged the day after :)

**Comment by dgoodwin** [comment]
Works for me, thanks!

**Comment by luxas** [comment]
Posting progress from https://docs.google.com/document/d/1deJYPIF4LmhGjDVaqrswErIrV7mtwJgovtLnPCDxP7U:
```
[lucas] Progress on the stable release
    Trying to get everything ready for Thursday so we can demo the new version
        Now down to ~5 PRs, of which 3 are lgtm’d
    Mike, Devan, others please take a look
    What the output of kubeadm now is going to look like:         
        https://github.com/kubernetes/kubernetes/pull/37568#issuecomment-265199717
        https://github.com/kubernetes/kubernetes/pull/37835
    We still have to fix the versioned client, which broke our setup
        Otherwise we have to revert it temporarily
    We need somewhere to place the release notes, I already have a PR for that
        https://github.com/kubernetes/kubeadm/pull/81
    I’m soon gonna aggregate more relnotes for the third release and add them there
        The release notes for v1.5 are in the works
            https://github.com/kubernetes/features/pull/140
            I had some nits I wanted to be fixed there, make sure you read through it and approve
    We have to update the docs as well to reflect the changes in the new version
        Assignee?
    When everything’s merged, please test it!
    The kubelet and kubectl packages should be updated to v1.5.0
    After that, we can release from master, I’ll update kubernetes/release and ping Mike to push it
```

I'm hoping to be able to build a stable kubeadm release this week, but it can be deferred if the main v1.5.0 release slips.

**Comment by luxas** [comment]
This is what I said on the sig-meeting this Tuesday: https://docs.google.com/document/d/1deJYPIF4LmhGjDVaqrswErIrV7mtwJgovtLnPCDxP7U
```
[lucas] Update on the v1.5 kubeadm release
    My UX improvement PR was merged: https://github.com/kubernetes/kubernetes/pull/37568
    I patched the cross-build to get it working again during the weekend: https://github.com/kubernetes/kubernetes/pull/38584, https://github.com/kubernetes/kubernetes/pull/38565, so now we have healthy builds to release kubeadm from
    Release notes for kubeadm: https://github.com/kubernetes/kubeadm/pull/88
    Here’s the PR to actually release kubeadm: (https://github.com/kubernetes/release/pull/229,) https://github.com/kubernetes/release/pull/230
```

This is now done, yet only my docs PR is still yet to be merged: https://github.com/kubernetes/kubernetes.github.io/pull/1968

**Comment by luxas** [comment]
This is now done, given that the docs PR is merged. Hooray :tada:
