### ISSUE TITLE
--ignore-preflight-errors doesn't seem to work

### ISSUE THREAD

**Issue by matthewfischer** [kubernetes/kubeadm#700]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.9.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.9.3
- **Cloud provider or hardware configuration**: hosted on AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.4
- **Kernel** (e.g. `uname -a`): 4.4.0-1049-aws #58-Ubuntu SMP
- **Others**:

## What happened?

I have an issue with CRI (which is outside the scope of this bug) and attempting to ignore it when trying to add a node to the cluster is failing. I've tried using the forms of:

` --ignore-preflight-errors stringSlice` - from kubeadm -h
and the form of 
`--ignore-preflight-errors=...` which comes when there is an error. Neither seems to work.

I've specified to ignore cri issues directly and i've also tried "all" per the help.

```
ubuntu@ip-172-31-38-142:~$ sudo kubeadm join -h
...
      --ignore-preflight-errors stringSlice           A list of checks whose errors will be shown as warnings. Example: 'IsPrivilegedUser,Swap'. Value 'all' ignores errors from all checks.
```

Trying with **--ignore-preflight-errors all**
```
ubuntu@ip-172-31-38-142:~$ sudo kubeadm join --token ca3f65.9e6258b8d6109e8f --discovery-token-ca-cert-hash --ignore-preflight-errors all 172.31.19.230:6443
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
	[ERROR CRI]: unable to check if the container runtime at "/var/run/dockershim.sock" is running: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

Trying with **--ignore-preflight-errors=all**

ubuntu@ip-172-31-38-142:~$ sudo kubeadm join --token ca3f65.9e6258b8d6109e8f --discovery-token-ca-cert-hash --ignore-preflight-errors=all 172.31.19.230:6443
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
	[ERROR CRI]: unable to check if the container runtime at "/var/run/dockershim.sock" is running: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

Same results with:

- --ignore-preflight-errors=CRI
- --ignore-preflight-errors=cri
- --ignore-preflight-errors cri
- --ignore-preflight-errors CRI

## What you expected to happen?

I expected my CRI errors to be ignored when I specified ignore all or ignore cri. Additionally the error message and the help message seem to disagree on whether or not I should be using the = sign, that should be rectified.

## Anything else we need to know?

At a minimum here I think you should rectify the help and the error message. Is the = sign needed or not?

**Comment by matthewfischer** [comment]
It looks like my ca-cert-hash got messed up after being pasted - adding it correctly and the ignore seems to work.

**Comment by satyasure** [comment]
try like this it is working ..
kubeadm init --config=kubeadm-config.yaml --ignore-preflight-errors=all --upload-certs

**Comment by satyasure** [comment]
in your case: sudo kubeadm join --token=ca3f65.9e6258b8d6109e8f --discovery-token-ca-cert-hash --ignore-preflight-errors=all 172.31.19.230:6443

**Comment by mewawalaabdeali** [comment]
how to use --ignore-preflight-errors=... for two errors

**Comment by hoangpbc** [comment]
--ignore-preflight-errors=all

**Comment by pacoxu** [comment]
> how to use --ignore-preflight-errors=... for two errors

'Example: 'IsPrivilegedUser,Swap'. Value 'all' ignores errors from all checks.'
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
