### ISSUE TITLE
kubeadm 1.9.3 applying https_proxy to internal traffic

### ISSUE THREAD

**Issue by andreas-p** [kubernetes/kubeadm#701]
There are quite some complaints about having a hard time to define no_proxy exceptions for https_proxy settings so that kubeadm can work successfully. Actually, I fail to see why kubeadm does apply  https_proxy settings for internal traffic in the first place. A web proxy is installed to control access to websites and download areas, not for filtering internal traffic. That's why I believe that it's the wrong approach to obey no_proxy definitions in a better way than now, as suggested in other issues.

kubeadm knows that any proxy will harm its function, but instead of ignoring it right away it just warns about the configuration that is doomed to fail.

I consider this as a bug, kubeadm should evaluate https_proxy for plugin downloads from k8n.io only, not for site internal control and pod traffic.

**Comment by kad** [comment]
/assign @kad 

Passing proxy variables to control plane by kubeadm was a resolution to earlier issues. Some users have that unusual setup.

We nowadays have checks that validate that internal traffic for cluster CIDR ranges is included in `no_proxy` settings. However, we recently found few other corner cases which cluster administrator can forget to specify. I'm planning to look how to add checks for those as well, and then it should be able to cover all known internal traffic.

**Comment by timothysc** [comment]
@kad do you plan to address in 1.13?

**Comment by kad** [comment]
Yes, I'll add more checks in 1.13 for corner cases we identified.

**Comment by neolit123** [comment]
doing triage of old issues...

@andreas-p

> A web proxy is installed to control access to websites and download areas, not for filtering internal traffic. That's why I believe that it's the wrong approach to obey no_proxy definitions in a better way than now, as suggested in other issues.

but it's unclear how would kubeadm know what the proxy is used for.
e.g. corporate proxies can apply not only to website traffic.

> I consider this as a bug, kubeadm should evaluate https_proxy for plugin downloads from k8n.io only, not for site internal control and pod traffic.

there are two sides to that, some users reported a problem that we are not applying the env.variables to containers, but some other users don't want it.

the current default is applying them and quite frankly i have not seen recent reports about proxy problems.

also kubeadm and a shell already allow you to choose _when_ to use the proxy settings:
for example if a https proxy is enabled:
- pre-pull images with `kubeadm config images pull` (using proxy)
- `no_proxy= https_proxy= kubeadm init` (to disable proxy settings propagating to the containers)

> kubeadm knows that any proxy will harm its function, but instead of ignoring it right away it just warns about the configuration that is doomed to fail.

if we don't have these checks the users will not get the correct feedback in case they are behind a proxy and they don't want that.

@kad

>  I'm planning to look how to add checks for those as well, and then it should be able to cover all known internal traffic.

i personally think that we should not add extra proxy checks. it seems there are a lot of corner cases to cover here.

i'd be closing this issue and if there are more recent reports we can think of possible actions.
if something is unclear let's log a separate ticket about e.g. documentation.
