### ISSUE TITLE
Couldn't connect to the node

### ISSUE THREAD

**Issue by arunkumar9050** [kubernetes/kubeadm#702]
root@ip- -- -- :~# kubeadm join --token 7907ea.c9fde6c416155afb 172.31.xx.xx:6443 --discovery-token-ca-cert-hash sha256:c9bc0680fbbc4951c917548ebd061c0f788bb5513ec6716b2dbaef2ac97

[preflight] Running pre-flight checks.
        [WARNING FileExisting-crictl]: crictl not found in system path
[discovery] Trying to connect to API Server "172.31.xx.xx:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://172.31.xxxx:6443"
[discovery] Failed to request cluster info, will try again: [Get https://172.31.xx.xx:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 172.31.xx.xx:6443: i/o timeout]

**Comment by bartosh** [comment]
Is this host behind a proxy?

**Comment by arunkumar9050** [comment]
yes

**Comment by bartosh** [comment]
Can you show the output of the following command:
```
set | grep -i proxy
```

**Comment by bartosh** [comment]
Btw, which kubeadm version do you use?

**Comment by arunkumar9050** [comment]
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/22399060/36283285-aaf8ea98-1269-11e8-8615-2d691123c627.png">

**Comment by kad** [comment]
Please verify that you don't have firewall running on master and worker nodes. (you can verify with expecting output of `iptables-save`). Also, please verify that you have network connectivity between your networks 172.31.26.xx (master) and 172.31.25.xx (slave)

**Comment by bartosh** [comment]
Is the host in the same network? what's the host ip address? Is there active firewall either on the host or on 172.31.26.90 filtering out port 6443 traffic.

**Comment by arunkumar9050** [comment]
this is my output after i run the command iptables-save
<img width="960" alt="1" src="https://user-images.githubusercontent.com/22399060/36284035-e5e61e58-126b-11e8-8831-a03edfeb7601.png">

**Comment by arunkumar9050** [comment]
yes both are in same network

**Comment by bartosh** [comment]
Can you check if you're able to access your master before and after 'kubeadm reset' on the node?
You should see something like this if all goes well:

```
# nc -zv  172.31.26.90 6443
Connection to  172.31.26.90 6443 port [tcp/sun-sr-https] succeeded!
```

**Comment by arunkumar9050** [comment]
I have disabled the firewall in both master and node. and i got the output 


kubeadm join --token 7907ea.c9fde6c416155afb 172.31.26.90:6443 --discovery-token-ca-cert-hash sha256:c9bc0680fbbc4951c9172ddec548ebd061c0f788bb5513ec6716b2dbaef2ac97
[preflight] Running pre-flight checks.
        [WARNING FileExisting-crictl]: crictl not found in system path
[discovery] Trying to connect to API Server "172.31.26.90:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://172.31.26.90:6443"
[discovery] Requesting info from "https://172.31.26.90:6443" again to validate TLS against the pinned public key
[discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "172.31.26.90:6443"
[discovery] Successfully established connection with API Server "172.31.26.90:6443"

This node has joined the cluster:
* Certificate signing request was sent to master and a response
  was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the master to see this node join the cluster.

but if i run kubectl get nodes,  i cannot see this node in master..and i got the output like, 
root@ip-172-31-26-90:~# kubectl get nodes
NAME              STATUS    ROLES     AGE       VERSION
ip-172-31-26-90   Ready     master    1h        v1.9.3
root@ip-172-31-26-90:~#

**Comment by bartosh** [comment]
interesting. Do you see any errors in kubelet log?

```
journalctl -u kubelet 
```

**Comment by arunkumar9050** [comment]
![image](https://user-images.githubusercontent.com/22399060/36285562-adf87b34-1271-11e8-9f5b-edca7da9456a.png)

**Comment by bartosh** [comment]
How did you initialized your master? Did you install a [pod network](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network)?

**Comment by arunkumar9050** [comment]
https://www.techrepublic.com/article/how-to-quickly-install-kubernetes-on-ubuntu/

**Comment by arunkumar9050** [comment]
My problem is that kubectl get nodes only shows the master, not the worker node as well.
