### ISSUE TITLE
kubectl get nodes only shows the master, not the worker node

### ISSUE THREAD

**Issue by arunkumar9050** [kubernetes/kubeadm#703]
I have tried installing kubernetes using 
[https://www.techrepublic.com/article/how-to-quickly-install-kubernetes-on-ubuntu/]

i connected one node successfully. 
if i type kubectl get nodes in master, i can see only master and not the connected node

**Comment by hsachdevah** [comment]
Were you able to solve the issue? What was the problem?

**Comment by amritihealthlabs** [comment]
facing same issue "if i type kubectl get nodes in master, i can see only master and not the connected node" whats the resolution ??
