### ISSUE TITLE
Not able to resize GlusterFS persistent volume

### ISSUE THREAD

**Issue by alvarosIGZ** [kubernetes/kubeadm#707]
# Versions

**kubeadm version**
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version**
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- CentOS
Linux 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
So I have a Kubernetes cluster (v1.9.2) installed with kubeadm with GlusterFS for persistent storage. I've seen in documentation (https://kubernetes.io/docs/admin/admission-controllers/#persistentvolumeclaimresize)  that since 1.8. is possible to do persistent volume resize enabling the admission controller and the feature gate.

So I've done all described, the admission controller seems enabled (when I enter in kube-apiserver pod and do ps aux | grep kube the output is kube-apiserver --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --client-ca-file=/etc/kubernetes/pki/ca.crt --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --secure-port=6443 --insecure-port=0 --allow-privileged=true --requestheader-extra-headers-prefix=X-Remote-Extra- --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --enable-bootstrap-token-auth=true --requestheader-username-headers=X-Remote-User --requestheader-group-headers=X-Remote-Group --service-cluster-ip-range=10.96.0.0/12 --tls-private-key-file=/etc/kubernetes/pki/apiserver.key **--admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota,PersistentVolumeClaimResize** **--feature-gates=ExpandPersistentVolumes=true -**-requestheader-allowed-names=front-proxy-client --advertise-address=10.68.18.45 --service-account-key-file=/etc/kubernetes/pki/sa.pub --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --authorization-mode=Node,RBAC --etcd-servers=http://127.0.0.1:2379)

Also, I've created a storage class with allowVolumeExpansion: true.
When I create and delete PVC everything is ok, kube master logs are ok, heketi also noticed and the volume is created/ deleted.

But when I resize, no logs and no action. 

## What you expected to happen?

See something in heketi and kube master logs of resize volume and also resize the volume.

**Comment by chuckha** [comment]
@alvarosIGZ would you be able to provide your PVC, StorageClass and exactly how you tried to resize it?

It would also help to know how you configured your API server since it looks like Kubeadm successfully bootstrapped the cluster.

**Comment by timothysc** [comment]
Closing due to timeout, please reopen with more data if you are still having an issue.
