### ISSUE TITLE
Make kubeadm give an option to generate certificates for x amount of days.

### ISSUE THREAD

**Issue by ricklagerweij** [kubernetes/kubeadm#708]
If this is a FEATURE REQUEST, please:
Currently kubeadm generates certificates for 1 year, when upgrading a cluster these certificates obviously don't refresh. 

Would it be possible to give an x amount of days for certificate valid duration?

## Versions

**kubeadm version** (use `kubeadm version`): 1.9.3

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.9.3
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): 4.14.9
- **Others**:

## Anything else we need to know?
I've made a bash script myself performing all the steps needed to extend these to 10 years. You could make a variable of the days ofcourse since the ca.crt is valid for 10 years.
https://github.com/ricklagerweij/Kubeadm-Certificate-Extension

**Comment by mattkelly** [comment]
There's a lot of discussion already around supporting certificate rotation: https://github.com/kubernetes/kubeadm/issues/206. Additionally, as of 1.9, a `kubeadm upgrade` will [automatically renew certificates that are going to expire within 180 days](https://github.com/kubernetes/website/pull/6901/files#diff-63b2ac648f939ca8bfa354ef91f3f31cR178.).

Just adding some historical context. I'm not sure whether or not adding a flag for this is something that would be desired for `kubeadm` as it's pretty opinionated about just setting up a" best-practice, reasonably secure" cluster.

**Comment by timothysc** [comment]
Yup, closing this one as the upgrade will rotate, and the lifecycle of support for a given release is typically a year.

**Comment by candlerb** [comment]
I don't know if you want a separate FR for this, but I think it would be useful for `kubeadm alpha kubeconfig user` to be able to issue longer-lived certs, since these are outside the scope of k8s automatic certificate rotation.

For example, we have a Jenkins CD setup which uses a cert to authenticate to production k8s cluster.  I would be happier with a long-lived cert than a ticking time bomb.

**Comment by neolit123** [comment]
the future of `kubeadm alpha kubeconfig user` is tracked in this ticket;
https://github.com/kubernetes/kubeadm/issues/1381

> ticking time bomb

adding certificate expiration options to kubeadm commands or it's API was discussed multiple times, and the maintainers are not in favor of doing that. it just opens the possibility of bad security practices, as everyone will start adding 10^6 years for cert expiration.

if the users want to customize their certificates, they need to jump some hoops, but currently kubeadm already supports accepting custom certificates:

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#custom-certificates
https://kubernetes.io/docs/setup/best-practices/certificates/
