### ISSUE TITLE
Bootstrapping HA master nodes fails

### ISSUE THREAD

**Issue by seafoodbuffet** [kubernetes/kubeadm#709]
## Is this a BUG REPORT or FEATURE REQUEST?
Choose one: BUG REPORT
## Versions

**kubeadm version** (use `kubeadm version`):

```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: Vagrant / Virtualbox
- **OS** (e.g. from /etc/os-release): CentOS 7.4
- **Kernel** (e.g. `uname -a`): Linux master01 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
I'm following the HA kubeadm instructions from here: https://kubernetes.io/docs/setup/independent/high-availability/

I've followed every step up to when I'm ready to kubeadm init on the first master node

When I run `kubeadm init` on the first master node, I get the following output:
```
# kubeadm init --config /root/config.yaml
[init] Using Kubernetes version: v1.9.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Some fatal errors occurred:
	[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
	[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
	[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

## What you expected to happen?
I had expected it to setup the first master node using a Static Pod configuration for etcd

## How to reproduce it (as minimally and precisely as possible)?
Here's my `/etc/kubernetes/manifests/etcd.yaml`
```
apiVersion: v1
kind: Pod
metadata:
labels:
    component: etcd
    tier: control-plane
name: master01
namespace: kube-system
spec:
containers:
- command:
    - etcd --name ${PEER_NAME} \
    - --data-dir /var/lib/etcd \
    - --listen-client-urls https://${PRIVATE_IP}:2379 \
    - --advertise-client-urls https://${PRIVATE_IP}:2379 \
    - --listen-peer-urls https://${PRIVATE_IP}:2380 \
    - --initial-advertise-peer-urls https://${PRIVATE_IP}:2380 \
    - --cert-file=/certs/server.pem \
    - --key-file=/certs/server-key.pem \
    - --client-cert-auth \
    - --trusted-ca-file=/certs/ca.pem \
    - --peer-cert-file=/certs/peer.pem \
    - --peer-key-file=/certs/peer-key.pem \
    - --peer-client-cert-auth \
    - --peer-trusted-ca-file=/certs/ca.pem \
    - --initial-cluster etcd0=https://192.168.22.10:2380,etcd1=https://192.168.22.11:2380,etcd1=https://192.168.22.12:2380 \
    - --initial-cluster-token my-etcd-token \
    - --initial-cluster-state new
    image: gcr.io/google_containers/etcd-amd64:3.1.0
    livenessProbe:
    httpGet:
        path: /health
        port: 2379
        scheme: HTTP
    initialDelaySeconds: 15
    timeoutSeconds: 15
    name: etcd
    env:
    - name: PUBLIC_IP
    valueFrom:
        fieldRef:
        fieldPath: status.hostIP
    - name: PRIVATE_IP
    valueFrom:
        fieldRef:
        fieldPath: status.podIP
    - name: PEER_NAME
    valueFrom:
        fieldRef:
        fieldPath: metadata.name
    volumeMounts:
    - mountPath: /var/lib/etcd
    name: etcd
    - mountPath: /certs
    name: certs
hostNetwork: true
volumes:
- hostPath:
    path: /var/lib/etcd
    type: DirectoryOrCreate
    name: etcd
- hostPath:
    path: /etc/kubernetes/pki/etcd
    name: certs
```

here's my kubeadm config yaml
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 192.168.22.10
etcd:
  endpoints:
  - https://192.168.22.10:2379
  - https://192.168.22.11:2379
  - https://192.168.22.12:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
apiServerCertSANs:
- "192.168.22.10"
- "192.168.22.11"
- "192.168.22.12"
- "127.0.0.1"
apiServerExtraArgs:
  endpoint-reconciler-type: lease
```

## Anything else we need to know?
If I remove /etc/kubernetes/manifests/etcd.yaml I avoid the FileAvailable error, but it still doesn't work (I'm guessing because it's looking for an already extant etcd cluster?)
```
# kubeadm init --config /root/config.yaml
[init] Using Kubernetes version: v1.9.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING FileExisting-crictl]: crictl not found in system path
[preflight] Some fatal errors occurred:
	[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
	[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
	[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

**Comment by seafoodbuffet** [comment]
Okay, figured out what was wrong... I'm leaving my findings in case anyone else finds this. The core problem is that this is a chicken and the egg issue. When you put etcd endpoints into the config yaml for kubeadm, it's expecting that etcd ALREADY EXISTS. I was under the impression that it would deploy etcd pods for me, which wasn't the case.

I ended up choosing the "run etcd using systemd" option which proved to be the fastest path to getting something working.

**Comment by Wylan** [comment]
Just going to comment on this incase it helps someone else with this issue. 

I had the same error message, however in our case etcd was already running. Strangely providing the FQDN to the etcd endpoints instead of the IP addresses in the  config.yaml file worked for us. I'm not sure why this would make a difference as the FQDN resolves to the same IP address, the etcd certificates contain both the IP address and the FQDN of the node. 🤷‍♂️

**Comment by srinathkotu** [comment]
not sure if this would help anybody, i was able to get around the issue by ignoring the pre-flight checks using the following command:
`kubeadm init --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml,ExternalEtcdVersion --config=config.yaml`

**Comment by Klmanjaro** [comment]
Could you share your etcd.yaml file? I am running into same issue. I have etcd server running 3.1.10 (since that was prev supported with kubernetes 1.9).  I have tried upgrading master node to use kubeadm 1.10.2 but that doesn't help.
thanks

**Comment by Klmanjaro** [comment]
Hi. I have figured out the issue and it has turned out to be non-issue. Sorry!

**Comment by ocofaigh** [comment]
@seafoodbuffet When following the "run etcd using systemd" steps, did you get etcd to start OK? I am getting an error saying: `unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory`
Everything I have ready seems to indicate this cert file is generated only **after** I run kubeadm init, but that steps doesn't come until later in the doc, and if I try to run it anyway I get: 

```
[root@XXXX ~]# kubeadm init --config=config.yaml
[init] Using Kubernetes version: v1.10.3
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
        [WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
[preflight] Some fatal errors occurred:
        [ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
        [ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
        [ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```
Chicken and the egg springs to mind.... Any ideas?

**Comment by ocofaigh** [comment]
Quick update on my comments in https://github.com/kubernetes/kubeadm/issues/709#issuecomment-391665776 
Managed to get the etcd cluster running using the "run etcd using systemd" steps. My problem was the config.yaml endpoints were set to https and I had set etcd up on http

**Comment by supnobita** [comment]
I ran into same issue. I cannot make etcd work with kubelet like what they write in the official document. I try ignore file etcd.yaml option but it didnt work.I must use systemd to start etcd cluster first. I think it is kubeadm bug

**Comment by ocofaigh** [comment]
@supnobita Take a look at the new steps for version 1.1: https://kubernetes.io/docs/setup/independent/high-availability/. 
They say they no longer support HA with v1.10. New steps are much better - kubeadm actually sets up the etcd cluster for you

**Comment by Klmanjaro** [comment]
@supnobita : Make sure your etcd certs are good. 
I used this command to make sure *pem files are good on all the etcd nodes:
openssl x509 -noout -text -in *.pem
Once you start etcd cluster make sure you see messages about raft nodes and publishing etcd server in your log files.
