### ISSUE TITLE
Please document that self-hosted feature does not survive a reboot (v 1.9.3)

### ISSUE THREAD

**Issue by TonyApuzzo** [kubernetes/kubeadm#711]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
```
core@localhost ~ $ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
core@localhost ~ $ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
Dell R720 Bare Metal Server

- **OS** (e.g. from /etc/os-release):
```
core@localhost ~ $ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.3.0
VERSION_ID=1632.3.0
BUILD_ID=2018-02-14-0338
PRETTY_NAME="Container Linux by CoreOS 1632.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- **Kernel** (e.g. `uname -a`):
```
core@localhost ~ $ uname -a
Linux localhost 4.14.19-coreos #1 SMP Wed Feb 14 03:18:05 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz GenuineIntel GNU/Linux
```

- **Others**:

## What happened?
Please document that the self-hosted feature does not work when you reboot the server without additional configuration. Kubernetes cluster does not restart after reboot

## What you expected to happen?
Expected it to restart.

## How to reproduce it (as minimally and precisely as possible)?
```
sudo kubeadm init --feature-gates=SelfHosting=true --pod-network-cidr=10.244.0.0/16
sudo systemctl enable kubelet.service
sudo shutdown -r now
```

## Anything else we need to know?

A workaround is described here: https://github.com/xetys/k8s-self-hosted-recovery

It took me a long time to find it because I didn't understand what was going wrong so it was hard to search.  Once I understood that the API service wasn't starting and it was a catch-22 problem due to the self-hosted feature, then it was pretty each to search and find the workaround.

**Comment by xiangpengzhao** [comment]
This is documented here:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#self-hosting

>Self-hosting in 1.8 has some important limitations. In particular, a self-hosted cluster cannot recover from a reboot of the master node without manual intervention. This and other limitations are expected to be resolved before self-hosting graduates from alpha.

But yeah, it's kinda simple and doesn't give a workaround (the `manual intervention`).

**Comment by timothysc** [comment]
I think I have a plan where we can mitigate the startup concerns, I'm going to put this on the 1.11 milestone.

**Comment by timothysc** [comment]
So I think what is written is really clear, and "in general" if you are using alpha-grade features we don't technically support known issues.  

This cycle I am planning to have an updated KEP wrt to self-hosting to try and solve this problem, so I'm going to close this issue and clear out the backlog.
