### ISSUE TITLE
Kubernetes dashboard / dns is not working after installation on the kubeadm - inited master.

### ISSUE THREAD

**Issue by Deimos620** [kubernetes/kubeadm#717]
##### Environment
```
Dashboard version: 1.8.3
Kubernetes version: 1.9.3
Operating system: Ubuntu 16.0.4
Node.js version: N/A
Go version: N/A
Docker version: 1.13
```

##### Steps to reproduce
1. install kubeadm: sudo apt-get install kubeadm kubectl kubelet kubernetes-cni
2. kubeadm init
3. config kubernetes

> mkdir -p $HOME/.kube
> sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
> sudo chown $(id -u):$(id -g) $HOME/.kube/config

4. And, I installed pod network with this:

> sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

> sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
5. Install dashboard:

> kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

##### Observed result
Here is result: 

> kubectl get pods --all-namespaces
>
> NAMESPACE     NAME                                               READY     STATUS              RESTARTS   AGE
> kube-system   kube-dns-6f4fd4bdf-pkpbf                           0/3       **_ContainerCreating_**   0          5h
> kube-system   kubernetes-dashboard-7f645d76f6-gpbhq              0/1       **_ContainerCreating_**   0          1h

> 
> kubectl logs kubernetes-dashboard-7f645d76f6-gpbhq --namespace=kube-system
>
> Error from server (BadRequest): container "kubernetes-dashboard" in pod "kubernetes-dashboard-7f645d76f6-gpbhq" is waiting to start: ContainerCreating

It says in "ContainerCreating" status, and , totally, can't access to dashboard via proxy due to "Service is not available" error.

##### Expected result
Generate correctly working dashboard service and pods

##### Comments
I am not sure why this happens.

**Comment by fabriziopandini** [comment]
I'm not 100% abut this, but IMO this is a networking issue.
Here you can find some recommendation/links for using flannel with kubeadm (e.g. pass the --pod-network-cidr)
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network (flannel tab)

**Comment by timothysc** [comment]
agreed & closing.  

There are a number of blog posts and youtube videos that outline the details, and we "Heptio" test this for every single release.
