### ISSUE TITLE
etcd fails kubelet's health checks

### ISSUE THREAD

**Issue by Q-Lee** [kubernetes/kubeadm#720]
## What keywords did you search in kubeadm issues before filing this one?

etcd ssl health

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): HEAD

**Environment**: custom/docker-in-docker, docker-in-docker-in-docker
- **Kubernetes version** (use `kubectl version`): HEAD
- **Cloud provider or hardware configuration**: local
- **OS** (e.g. from /etc/os-release): Debian
- **Kernel** (e.g. `uname -a`): 4.9.0-5

## What happened?

tl;dr - kubelet doesn't know the key/crt for etcd, so that etcd returns "non-sense" for its health check.

1. kubeadm creates etcd file
1. kubelet creates etcd container
1. cluster comes up, etcd is taking writes, and everything's great
1. etcd fails kubelet's health checks
1. nothing's great

$ curl -k https://127.0.0.1:2379/health --key apiserver-etcd-client.key --cert apiserver-etcd-client.crt 
{"health": "true"}
$ curl -k https://127.0.0.1:2379/health
curl: (35) error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
$ journalctl | grep "Liveness probe" | grep -v succeeded | tail -n1
Mar 03 09:49:08 7e928d1f665e kubelet[151]: I0303 09:49:08.142334     151 server.go:422] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"etcd-7e928d1f665e", UID:"17c2da92666b4a9242f31873234f3101", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{etcd}"}): type: 'Warning' reason: 'Unhealthy' Liveness probe failed: Get http://127.0.0.1:2379/health: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

## What you expected to happen?

I expect etcd to pass health checks.

## How to reproduce it (as minimally and precisely as possible)?

I suspect any kubeadm cluster built from HEAD will have this quirk.

**Comment by Q-Lee** [comment]
Looking at the kubeadm code, it appears we statically set the probe scheme to http, but etcd is https. Even if we didn't set client auth to true, I don't know how this could ever have worked. Did etcd's behavior change under us?

https://github.com/kubernetes/kubernetes/blame/master/cmd/kubeadm/app/phases/etcd/local.go#L68

**Comment by stealthybox** [comment]
Hi @Q-Lee -- these were the changes that introduced etcd TLS:
- https://github.com/kubernetes/kubernetes/pull/57415
- https://github.com/kubernetes/kubernetes/pull/60385

Here's is the bugfix:
https://github.com/kubernetes/kubernetes/pull/60728
