### ISSUE TITLE
bearer token option for remote api/config access

### ISSUE THREAD

**Issue by pswenson** [kubernetes/kubeadm#721]
## FEATURE REQUEST

I think kubeadm should offer an option to pass in a bearer token on `kubeadm init`
`kubeadm init --bearer-token=${mybearertoken}`

this would allow for much easier kubectl configuration remotely.  The current approach of copying and the `admin.conf` file and hacking the local kubeconfig is very manual, awkward, and error prone.

**Comment by timothysc** [comment]
@pswenson could you provide a detailed description of the workflow you want to optimize.

**Comment by pswenson** [comment]
Looks like this is already supported in kubeadm anyway:  https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-token/
