### ISSUE TITLE
kubernetes pods stuck at containercreating

### ISSUE THREAD

**Issue by bilalAchahbar** [kubernetes/kubeadm#722]
I have a raspberry pi cluster (one master , 3 nodes) 

My basic image is : raspbian stretch lite

I already set up a basic kubernetes setup where a master can see all his nodes (kubectl get nodes) and they're all running.
I used a weave network plugin for the network communication

When everything is all setup i tried to run a nginx pod (first with some replica's but now just 1 pod) on my cluster as followed
kubectl run my-nginx --image=nginx

But somehow the pod get stuck in the status "Container creating" , when i run docker images i can't see the nginx image being pulled. And normally an nginx image is not that large so it had to be pulled already by now (15 minutes). 
The kubectl describe pods give the error that the pod sandbox failed to create and kubernetes will rec-create it.

I searched everything about this issue and tried the solutions on stackoverflow (reboot to restart cluster, searched describe pods  , new network plugin tried it with flannel) but i can't see what the actual problem is.
I did the exact same thing in Virtual box (just ubuntu not ARM ) and everything worked.

First i thougt it was a permission issue because i run everything as a normal user , but in vm i did the same thing and nothing changed.
Then i checked kubectl get pods --all-namespaces to verify that the pods for the weaver network and kube-dns are running and also nothing wrong over there . 

Is this a firewall issue in Raspberry pi ? 
Is the weave network plugin not compatible (even the kubernetes website says it is) with arm devices ? 
I 'am guessing there is an api network problem and thats why i can't get my pod runnning on a node

[EDIT]
Log files

   kubectl describe podName 

    >     
    >     Name:           my-nginx-9d5677d94-g44l6 Namespace:      default Node: kubenode1/10.1.88.22 Start Time:     Tue, 06 Mar 2018 08:24:13
    > +0000 Labels:         pod-template-hash=581233850
    >                     run=my-nginx Annotations:    <none> Status:         Pending IP: Controlled By:  ReplicaSet/my-nginx-9d5677d94 Containers: 
    > my-nginx:
    >         Container ID:
    >         Image:          nginx
    >         Image ID:
    >         Port:           80/TCP
    >         State:          Waiting
    >           Reason:       ContainerCreating
    >         Ready:          False
    >         Restart Count:  0
    >         Environment:    <none>
    >         Mounts:
    >           /var/run/secrets/kubernetes.io/serviceaccount from default-token-phdv5 (ro) Conditions:   Type           Status  
    > Initialized    True   Ready          False   PodScheduled   True
    > Volumes:   default-token-phdv5:
    >         Type:        Secret (a volume populated by a Secret)
    >         SecretName:  default-token-phdv5
    >         Optional:    false QoS Class:       BestEffort Node-Selectors:  <none> Tolerations:     node.kubernetes.io/not-ready:NoExecute for
    > 300s
    >                      node.kubernetes.io/unreachable:NoExecute for 300s Events:   Type     Reason                  Age   From               
    > Message   ----     ------                  ----  ----               
    >     -------   Normal   Scheduled               5m    default-scheduler   Successfully assigned my-nginx-9d5677d94-g44l6 to kubenode1   Normal  
    > SuccessfulMountVolume   5m    kubelet, kubenode1  MountVolume.SetUp
    > succeeded for volume "default-token-phdv5"   Warning 
    > FailedCreatePodSandBox  1m    kubelet, kubenode1  Failed create pod
    > sandbox.   Normal   SandboxChanged          1m    kubelet, kubenode1 
    > Pod sandbox changed, it will be killed and re-created.

kubectl logs podName

    Error from server (BadRequest): container "my-nginx" in pod "my-nginx-9d5677d94-g44l6" is waiting to start: ContainerCreating

**Comment by ageekymonk** [comment]
I have the same issue as well.

**Comment by bilalAchahbar** [comment]
The thing is , and thats the weird part. 
It all works fine when i use a fresh rasbian lite image with the same installs and the same settings . But the moment i read the image with win32image on  my laptop and burn it on new nodes it doesn't work anymore. 
no problem now but i need a copy of my image for back up reasons. So somewhere down the line the image get broken.

**Comment by timothysc** [comment]
I really don't think this is a kubeadm issue it sounds like an image compat problem.  

If you have specific data pointing to kubeadm being the problem please feel free to reopen.

**Comment by pouyaesm** [comment]
In my case, docker could not access the internet ([my solution](https://serverfault.com/a/920207/477274))

**Comment by PREngineer** [comment]
> 

Thank you sir!  This was precisely my issue.

**Comment by vishlvirus** [comment]
![image](https://github.com/kubernetes/kubeadm/assets/103377103/097decee-9a0a-4bdf-be98-24edecb54ebb)

**Comment by chendave** [comment]
@vishlvirus you can inspect the log of the flannel, and see what's happened there, this does sound like a issue from kubeadm itself. 

Make sure the cni is running first.

**Comment by chendave** [comment]
FYI,

```
kubectl logs kube-flannel-ds-kv2cm -n kube-flannel
```
