### ISSUE TITLE
kubeadm upgrade doesn't support an external etcd cluster

### ISSUE THREAD

**Issue by sgmiller** [kubernetes/kubeadm#727]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions
1.9.3

**Environment**:
- Kubernetes 1.8.8
- AWS
- Ubuntu 16.10
- 4.8.0-59-generic

## What happened?
Attempting to plan an upgrade from 1.8.8 to 1.9.3 fails trying to query the etcd version, hitting localhost rather than any of the external etcd cluster endpoints.

## What you expected to happen?
Expected kubeadm to either use an external endpoint from the cluster configmap, or provide a flag to skip the etcd upgrade (our etcd was already up to date).

## How to reproduce it (as minimally and precisely as possible)?
Init a cluster with external etcd, then run kubeadm upgrade plan.

**Comment by sgmiller** [comment]
Looking at the code, it appears RunPlan in cmd/upgrade/plan.go hardcodes a  LocalEtcdCluster with no regard to the cluster configuration:

`// RunPlan takes care of outputting available versions to upgrade to for the user
func RunPlan(parentFlags *cmdUpgradeFlags) error {
        // Start with the basics, verify that the cluster is healthy, build a client and a versionGetter. Never dry-run when planning.
        upgradeVars, err := enforceRequirements(parentFlags, false, "")
        if err != nil {
                return err
        }

        // Define Local Etcd cluster to be able to retrieve information
        etcdCluster := kubeadmutil.LocalEtcdCluster{}

        // Compute which upgrade possibilities there are
        availUpgrades, err := upgrade.GetAvailableUpgrades(upgradeVars.versionGetter, parentFlags.allowExperimentalUpgrades, parentFlags.allowRCUpgrades, etcdCluster, upgradeVars.c

`

**Comment by detiber** [comment]
@jmara most likely not, you might be able to work around by executing the phases independently, but I haven't tested it.

**Comment by timothysc** [comment]
@schmitch We intend to document a etcd deployment using phases this cycle.

**Comment by zoidbergwill** [comment]
Would it be possible to get [the fix](https://github.com/kubernetes/kubernetes/pull/63495) in  kubeadm 1.9?

I tried cherry-pick'ing it into the branch [on my fork](https://github.com/kubernetes/kubernetes/compare/release-1.9...zoidbergwill:release-1.9) so we could use it, but it'd probably be worth someone else re'doing it.

**Comment by Zsuz** [comment]
Has anyone looked into getting the fix into kubeadm 1.9?

**Comment by luxas** [comment]
@detiber @stealthybox @timothysc on cherrypicking the fix into kubeadm v1.9?

**Comment by zoidbergwill** [comment]
Thanks @luxas :pray:

**Comment by ShaunMaxwell** [comment]
Has anyone had a chance to investigate this? We'd really like to use kubeadm to upgrade from 1.8 to 1.9 but out etcd is external so this blocks us.
