### ISSUE TITLE
kubernetes pods stuck at container creating when shrinking image raspbian lite

### ISSUE THREAD

**Issue by bilalAchahbar** [kubernetes/kubeadm#728]
I have a raspbian cluster with kubernetes cluster on it.

When i have my set up all running everyhing in kubernetes works (creating pods , scaling them on the different nodes). 
I backed up my image to a file and burned it to another sd card still everything works fine.

But when i shrink my image to delete all the free space so the back up file is smaller and faster to burn , my kubernetes gets all twisted.
I tried to shrink it with these 2 tutorials , both of them have the same outcome (pods on the nodes stuck at container creating)
- www.aoakley.com/articles/2015-10-09-resizing-sd-images.php
- https://github.com/Drewsif/PiShrink

After the first boot i expand my filesystem , the operation system (rasbian stretch lite) works fine and does not create any problems with the shrinked image file. 
But kubernetes does  :( 
Here is my stackoverflow question with the logs that kubernetes and journalctl give me:
https://stackoverflow.com/questions/49113253/kubernetes-pods-stuck-at-containercreating

**Comment by timothysc** [comment]
If it's stuck in container creating, it's likely due to the fact the image was not created for that arch.  All images need to match the target architecture.  

This is not a kubeadm issue, closing.
