### ISSUE TITLE
Recommendations for customizing cluster created via kubeadm

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/kubeadm#73]
We are exploring the idea of using kubeadm over saltstack as the mechanism for provisioning Kubernetes cluster. But the question if we want to customize various parts of a cluster creation process, what is kubeadm's vision/suggestion is that regard? With the original saltstack mechanism, we could modify the state files and control how various  manifest, etc files were generated. Some of the areas for customization: 

 - We prefer Debian as the host OS. It is not there.
 - What is the recommended way to install various addons? (edited)
 - Some of these addons need config data from the setup (passed via pillars and grains in saltstack)

Thanks.

**Comment by luxas** [comment]
@TamalSaha We're gonna implement `kubeadm phases` in more detail in time for v1.8.
That's the expected mechanism to use for extending kubeadm...

See: #156
