### ISSUE TITLE
upgrade ignores HighAvailability feature gate

### ISSUE THREAD

**Issue by mxey** [kubernetes/kubeadm#731]
Choose one: BUG REPORT

I have the `HighAvailability` feature gate enabled in my kubeadm configuration file. On `kubeadm init`, that added `--endpoint-reconciler-type=lease` to the kube-apiserver static pod. After running `kubeadm upgrade` with the same configuration file, that option is gone.

## Versions

**kubeadm version** (use `kubeadm version`): 1.9.4

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.9.3
- **Cloud provider or hardware configuration**: Vagrant with VirtualBox
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
- **Kernel** (e.g. `uname -a`):  Linux vagrant-kubernetes-master1 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?

Before upgrade:
```
[root@vagrant-kubernetes-master1 etc]# grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --endpoint-reconciler-type=lease
```

After upgrade:

```
[root@vagrant-kubernetes-master1 etc]# grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml 
```

## What you expected to happen?

After upgrade:
```
[root@vagrant-kubernetes-master1 etc]# grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --endpoint-reconciler-type=lease
```

## How to reproduce it (as minimally and precisely as possible)?

* Create kubeadm.yaml:
```
kind: MasterConfiguration

networking:
  podSubnet: 10.244.0.0/16

featureGates:
  HighAvailability: true
```

* `kubeadm init --config /etc/kubernetes/kubeadm.yaml`
* `grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml`: shows option
* Install CNI to make node ready: `kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml`
* Wait for node to become ready: `kubectl get nodes -w`
* `kubeadm upgrade --yes --config /etc/kubernetes/kubeadm.yaml apply v1.9.4`
* `grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml`: no output

## Anything else we need to know?

**Comment by fabriziopandini** [comment]
@mxey a possible workaround is to pass `--features-gates` to upgrade as a flag; the fix is on the flight
