### ISSUE TITLE
Disable the kubelet readonly port

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#732]
@liggitt said, very reasonably:

> kubeadm should also disable the readonly port to follow best practices.

ref: https://github.com/kubernetes/kubernetes/pull/59666#issuecomment-373829976

While we already protect the most essential parts (e.g. disable cAdvisor, protect the API using the authorizer, etc.), we could lock this down by default more as well before going to GA.

cc @timothysc @kad @stealthybox

**Comment by kad** [comment]
`http://localhost:10255/healthz` is used to check that kubelet started. Should we drop those and just keep `WaitForAPI()` ?

**Comment by stealthybox** [comment]
^ worth noting we will need to be using the secure port more for other planned uses of the kubelet API.

**Comment by luxas** [comment]
@woopstar do you want to work on this issue (given #804?).
Please do in that case, I don't think @detiber has started working on this yet.

**Comment by luxas** [comment]
> Do we simply just want to update the WaitForHealthyKubelet function to use https instead of http? And apply the client certificates to the request?

That's the first step :+1: 

> Do we simply just expect it to be https://localhost:10250 ?

For now at least, yes

**Comment by luxas** [comment]
Sent first required PR https://github.com/kubernetes/kubernetes/pull/63812

**Comment by woopstar** [comment]
Oi. Using the the dedicated health endpoint is actually way better than using the https endpoint I guess :)

**Comment by detiber** [comment]
That does complicate things a bit...  Although, I really don't see an issue with relying on the api server and validating the mirror pods after the api server is already up and responding...

**Comment by stealthybox** [comment]
> The kubelet exec's out a SubjectAccessReview call to the API server when it gets a request to its own API in order to verify whether the caller is authorized to talk to the kubelet. So when there's no API server we can't talk to the kubelet secure API either. However, this was fixed with using the dedicated healthz port

This is probably not true though the apiserver-kubelet cert is used, right?

**Comment by luxas** [comment]
> This is probably not true though the apiserver-kubelet cert is used, right?

This happens always, even though the apiserver-kubelet-client is used AFAIK, check it up in the code, but I haven't seen any exceptions :wink:

**Comment by drewgonzales360** [comment]
I know this is old, but can someone explain what
> While we already protect the most essential parts (e.g. disable cAdvisor, protect the API using the authorizer, etc.), we could lock this down by default more as well before going to GA.

Means?
