### ISSUE TITLE
How to get `kubeadm init` to not fail?

### ISSUE THREAD

**Issue by bis-sb** [kubernetes/kubeadm#733]
I am going through the [setup procedure](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/) but when I run `kubeadm init` I am met by errors:
```
[init] Using Kubernetes version: v1.9.5
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
        [ERROR IsPrivilegedUser]: user is not running as root
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

I check what groups my user belongs to and it lists `root` as one of the groups:
```
sbrown@Dev-kube-01:~$ groups
sbrown root adm cdrom sudo dip plugdev lxd lpadmin sambashare docker
```

I am a novice with Ubuntu so I'm having trouble making sense of this error: why does kubernetes not think my user is privileged? Does the error mean that I'll have to run `sudo kubeadm init...` or does it intend for me to run everything as `root`? Is it possible for me to modify my current user so that I can run `kubeadm init` without `IsPrivilegedUser` throwing an error?

**Comment by bis-sb** [comment]
I just went ahead and used the root account; now I encounter other errors:
```
[ERROR Swap]: running with swap on is not supported. Please disable swap
[ERROR CRI]: unable to check if the container runtime at "/var/run/dockershim.sock" is running: exit status 1
```

OK I'll disable swap, but the CRI issue was confusing and based on some quick searching it seemed as though the [crictl](https://github.com/kubernetes-incubator/cri-tools/blob/master/docs/crictl.md) tool required some configuring but the [installation instructions](https://kubernetes.io/docs/setup/independent/install-kubeadm/) has no remarks about crictl, i.e. how Kubernetes is using crictl, what problem crictl solves, etc.

OK so disabling the swap and cri pre-flight checks makes things get a little further, except now I notice that despite pre-pulling the docker images (as mentioned [here](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#running-kubeadm-without-an-internet-connection)), Kubernetes still tries to pull the images anyway and fails. What needs to be set is the `imagePullPolicy` but again, the [kubeadm init reference page](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init) makes no remark about this setting or where to set it (the instructions seem to imply that pre-pulling the images is sufficient, but it isn't).

Not trying to complain, just trying to understand how to set this tool up and have a place to document issues so that at a future time when I need to set it up I can refer here. Help in understanding these issues is appreciated.

**Comment by srinivas491-oneconvergence** [comment]
Container runtime is required for the kubelet to launch the pods on a node. Runtime exposes interfaces for the kubelet to schedule containers and manage the state of the pods. One of the container runtime is  docker. [Kubernetes installation](https://kubernetes.io/docs/setup/independent/install-kubeadm/) instruction has the information to setup the docker (under the heading Installing Docker).  

More information about [CRI](http://blog.kubernetes.io/2016/12/container-runtime-interface-cri-in-kubernetes.html)

**Comment by bis-sb** [comment]
I already went through the instructions for installing kubeadm and that didn't give me any issues, although I was wondering if Docker CE 17.03 is an absolute, or if I could get away with using 17.12.1 CE (which is the one that was already installed on the server).

That blog post on the CRI really helped me understand its role, thank you.

I still am having trouble getting `kubeadm init` to use the images that are already on the machine instead of trying to get them from the internet (which is inaccessible).

**Comment by bis-sb** [comment]
I found some unofficial documentation which lists some [environment variables](http://unofficial-kubernetes.readthedocs.io/en/latest/admin/kubeadm/#environment-variables) that looked promising but the environment variables have no effect: I look at the manifest files that kubeadm generates and the images that the reference are all still `gcr.io/google_container` instead of `<my private repo>/gcr.io/google_container`

**Comment by bis-sb** [comment]
OK I wrongly assumed from that error message that the error was in pulling the images: it actually looks like it's because kubelet wasn't running:
```
I0320 15:13:43.853388    8656 server.go:182] Version: v1.9.5
I0320 15:13:43.853429    8656 feature_gate.go:226] feature gates: &{{} map[]}
I0320 15:13:43.853513    8656 plugins.go:101] No cloud provider specified.
W0320 15:13:43.853551    8656 server.go:328] standalone mode, no API client
W0320 15:13:43.878162    8656 server.go:236] No api server defined - no events will be sent to API server.
I0320 15:13:43.878191    8656 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
error: failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. 
```
So in a new terminal I ran `kubelet --fail-swap-on=false` and now kubelet is running. Now I see `dockershim.sock` under `/var/run/`

**Comment by srinivas491-oneconvergence** [comment]
Kubeadm init will start pods for etcd, dns and cni on the master node. For this it requires dockershim.sock.

**Comment by bis-sb** [comment]
Docker is running fine, what's confusing me is there appears to be a circular dependency when running `kubeadm init`:
- if kubelet is not already running, then the error is `[ERROR CRI]: unable to check if the container runtime at "/var/run/dockershim.sock" is running: exit status 1`
- if kubelet is running, then the error is `[ERROR Port-10250]: Port 10250 is in use`

**Comment by bart0sh** [comment]
That circular dependency is also mentioned here: https://github.com/kubernetes-incubator/cri-tools/issues/153#issuecomment-365286449

It looks like a bug in kubeadm. It shouldn't run cry pre-flight check before running kubelet as dockershim.sock seems to be created by kubelet.

**Comment by bis-sb** [comment]
ok so that is a bug, thanks for clarifying that

**Comment by jacobtomlinson** [comment]
I am also having the same issue where the preflight check is looking for `/var/run/dockershim.sock` before it should exist.

The following runs successfully:

```
kubeadm init --ignore-preflight-errors=all
```

**Comment by bart0sh** [comment]
Preflight check issue should be fixed by [PR 58802](https://github.com/kubernetes/kubernetes/pull/58802)

Temporary workaround for this issue is to switch off CRI check:
```
kubeadm init --ignore-preflight-errors=cri
```

**Comment by bis-sb** [comment]
Thanks for the pointers, I'll try them out if I revisit Kubernetes (or maybe by then it'll be easier to set up)

**Comment by faizurrahmann** [comment]
Hi friends,
I am getting below mentioned kubeadm init error due to the number of available CPUs 1 is less than the required 2. Anybody know how to ignore this error y using "--ignore-preflight-errors=" ?

**Error:**
Use "kubeadm init [command] --help" for more information about a command.
root@ip-172-31-15-167:~# kubeadm init --ignore-preflight-errors=cpu --apiserver-advertise-address 172.31.15.167 --pod-network-cidr=172.16.0.0/16
[init] Using Kubernetes version: v1.15.3
[preflight] Running pre-flight checks
        [WARNING Firewalld]: firewalld is active, please ensure ports [6443 10250] are open or your cluster may not function correctly
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.1. Latest validated version: 18.09
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR NumCPU]: the number of available CPUs 1 is less than the required 2
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
root@ip-172-31-15-167:~# docker --version
Docker version 19.03.1, build 74b1e89

**Comment by neolit123** [comment]
@faizurrahmann 

> [preflight] If you know what you are doing, you can make a check non-fatal with --ignore-preflight-errors=...

^ it tells you here.

try `kubeadm init ... --ignore-preflight-errors=NumCPU`

**Comment by faizurrahmann** [comment]
Yes --ignore-preflight-errors=**NumCPU** worked for me. 
I got it. The possible string value is what associated with error
Note below:
[ERROR _**NumCPU**_]: the number of available CPUs 1 is less than the required 2

**Comment by Mounika666** [comment]
kubeadm init   --ignore-preflight-errors=all

**Comment by Anushamobis** [comment]
sudo kubeadm init --ignore-preflight-errors=all
 worked for me

**Comment by lutuantai95** [comment]
On offical docs of kubeadm, there is no mention of `--ignore-preflight-errors=all`. I just see them using `kube init`.
It's absurd that kubectl can run without root but kubeadm gives errors.
Is there any way to fix it without using `--ignore-preflight-errors=all` and `sudo` ?
