### ISSUE TITLE
split `phase selfhosting convert-from-staticpods`

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/kubeadm#735]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: FEATURE REQUEST

## Rationale

We want to use most of kubeadm, but supply our own self-hosted control plane at the end.

(In particular, we want to be masterless, with Deployments for the apiserver, controller-manager and scheduler, following from our current setup with bootkube)

The phases work great for most of this, however we only need one half of `kubeadm alpha phase selfhosting convert-from-staticpods`. We need the secret uploading part, but not the conversion from static pods.

## Current workaround (for context)
```
kubeadm --config /etc/kubernetes/kubeadm.yaml alpha phase controlplane all
for component in apiserver controller-manager scheduler; do
  mv /etc/kubernetes/manifests/kube-${component}{,-custom}.yaml
done

...

kubeadm --config /etc/kubernetes/kubeadm.yaml alpha phase selfhosting convert-from-staticpods

...

apply our manifests

echo Waiting for self-hosted control plane to come online...
  for component in apiserver controller-manager scheduler; do
    while ! kubectl --namespace kube-system get pod -l k8s-app=kube-${component} -o wide | grep $(hostname); do
      sleep 5
    done
  rm /etc/kubernetes/manifests/kube-${component}-custom.yaml
done
```

## Proposal

```
kubeadm alpha phase selfhosting upload-secrets
kubeadm alpha phase selfhosting convert-from-staticpods
```

**Comment by stealthybox** [comment]
I can see why you want this, and I think it's a reasonable proposal :+1:

**Comment by fabriziopandini** [comment]
@mikebryant  fyi there is a proposal for graduating phases in this cycle, and I think that the implementation of your proposal could take benefit from this effort as well. See
https://github.com/kubernetes/community/pull/1939
https://github.com/kubernetes/kubernetes/pull/61631

**Comment by timothysc** [comment]
So I'm actually going to close this issue, b/c right now we are going to overhaul both phases and self-hosting in an effort to move to beta.
