### ISSUE TITLE
Auto import Kubernetes resources from directory

### ISSUE THREAD

**Issue by steven-sheehy** [kubernetes/kubeadm#736]
FEATURE REQUEST

It would be useful for kubeadm init to support the ability to apply all Kubernetes resource yamls from a specified directory after the cluster is initialized. A CLI option or configuration property can be added like --auto-import-dir to enable this feature. 

As it stands now, a Kubernetes cluster is not usable without applying at least the yaml containing the network configuration and possibly others. Since it is not a goal of kubeadm to install the network, this would be a nice middle ground to help administrators automate the cluster boostrapping in a more declarative fashion. With this the administrator can drop some kubernetes resource files in a directory and kick off kubeadm init and the kubernetes node would be fully ready to use without additional scripting. The goal of this auto-import is not to replace a real kubernetes package manager like Helm, but more for essential resources like the network, tiller serviceaccount, etc.

## Versions

- **kubeadm version**: v1.9.3
- **Kubernetes version**: v1.9.3
- **Cloud provider or hardware configuration**: VMware
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): 4.4.0-116
- **Others**:

**Comment by timothysc** [comment]
I'm going to close this b/c I consider it orthogonal to the main purpose of kubeadm.  Other tooling can apply the config as a separate step.
