### ISSUE TITLE
KUBE-API --insecure-bind-address

### ISSUE THREAD

**Issue by bishnuroy** [kubernetes/kubeadm#737]
## Versions

**Environment**:
- **Kubernetes version** 1.9.3:
- **Cloud provider or hardware configuration**: Mirantis Openstack
- **OS** (e.g. from /etc/os-release): 
```
# cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.3.0
VERSION_ID=1632.3.0
BUILD_ID=2018-02-14-0338
PRETTY_NAME="Container Linux by CoreOS 1632.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- **Kernel** (e.g. `uname -a`):
```
Linux bflk8smas201 4.14.19-coreos #1 SMP Wed Feb 14 03:18:05 UTC 2018 x86_64 Intel Xeon E312xx (Sandy Bridge) GenuineIntel GNU/Linux
```

**## Quires:**

Is it possible to assign multiple host ips in " --insecure-bind-address=" flag?

**Comment by rosti** [comment]
This project tracks the issues connected to kubeadm.

However, I do think that `--insecure-bind-address` works only with a single IP.

**Comment by timothysc** [comment]
This is an api-server flag not kubeadm specific, closing...
