### ISSUE TITLE
kubeadm not creating /etc/cni/net.d .. pods will fail to load.

### ISSUE THREAD

**Issue by adiri** [kubernetes/kubeadm#74]
I tested kubeadm on CentOS 7, did exactly what the document stated and everything work as expected.

when I created a pod I had the following error:

```
  1m		1m		4	{kubelet server.name}			Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "appname-a94fb6130669dde66c7ebe8cd697c498463fa721-5rg6i_default" with SetupNetworkError: "Failed to setup network for pod \"appname-a94fb6130669dde66c7ebe8cd697c498463fa721-5rg6i_default(45543fa1-b1fe-11e6-af4d-5254002465aa)\" using network plugins \"cni\": cni config unintialized; Skipping pod"
```

creating  at the master and slaves /etc/cni/net.d fixed the problem.

**Comment by fieg** [comment]
I'm experiencing the same on ubuntu xenial.

@adiri what do you mean with "creating /etc/cni/net.d"? Just create an empty directory?

**Comment by mikedanese** [comment]
kubeadm doesn't create this, a network daemonset should. Are your running weave or flannel in a daemonset?

**Comment by adiri** [comment]
@mikedanese Yes, I applied the weave daemonset (kubectl apply -f https://git.io/weave-kube)

**Comment by mikedanese** [comment]
Then this might be a problem with weave-kube cc @errordeveloper @lukemarsden

**Comment by mattseh** [comment]
I'm also experiencing this with a fresh Digital Ocean 4GB 16.04 VM (single node cluster). I followed http://kubernetes.io/docs/getting-started-guides/kubeadm/ and didn't install a network daemonset, as it wasn't mentioned as required.

kube-dns and kube-dashboard are the pods that fail to come up.

I hope that helps.

**Comment by damaspi** [comment]
On an Ubuntu 16.04.1 LTS, with a master and 3 nodes in an internal static network (192.168.2.99 to 102) but having also an IP address going directly on the Internet, I have installed k8 (1.5.1) with 
```kubeadm init --api-advertise-addresses=192.168.2.99```

I then installed my weave-kube by typing
```kubectl apply -f https://git.io/weave-kube```

```kubectl get pods --namespace=kube-system``` shows that everything seems to be ok, but when I add successfully the nodes, I see regular crashes of the weave-net-xxxx pods.

When I deploy some demo application, I have the same message as above. (Error syncing pod, skipping: failed to "SetupNetwork" ).

When I check the logs of the proxy pod, ``` kubectl logs kube-proxy-g7qh1 --namespace=kube-system
``` I get the following info: ```proxier.go:254] clusterCIDR not specified, unable to distinguish between internal and external traffic```

The test for an empty clusterCIDR in pkg/proxy/iptables/proxier.go seems rather recent, so is kubeadm adapted to ensure that this flag is properly set? In the templates (.json), I don't find it and I don't know where to add this flag to ensure that it is properly taken by the proxy...

**Comment by pires** [comment]
@damaspi it seems to me that's a different issue. Please open a new issue.

**Comment by damaspi** [comment]
I worked-around temporarily by configuring proxy-mode to userspace but any advice welcome...

(inspired by [this issue](https://github.com/kubernetes/kubernetes/issues/34101)

`kubectl -n kube-system get ds -l "component=kube-proxy" -o json | jq ".items[0].spec.template.spec.containers[0].command |= .+ [\"--proxy-mode=userspace\"]" | kubectl apply -f - && kubectl -n kube-system delete pods -l "component=kube-proxy"
`

**Comment by luxas** [comment]
kubeadm should not create the /etc/cni/net.d directory; that's a task for the CNI DaemonSet plugins.

And the other issue that's faced here is handled in #102

**Comment by funnydevnull** [comment]
I am having similar problems but _only_ when I use an internal IP address for kubeadm init --api-advertise (I have two interfaces, one internal one external).  Is this related to #102?

**Comment by luxas** [comment]
@funnydevnull I can't say, please open a new issue with more details and we'll see
