### ISSUE TITLE
surface apiserver container errors in kubeadm init

### ISSUE THREAD

**Issue by liztio** [kubernetes/kubeadm#741]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

currently, if the API server pod fails to initialise, the `kubeadm init` will stall on:

```
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests".
[init] This might take a minute or longer if the control plane images have to be pulled.
```

And then hang forever. The info message is misleading, because there are any number of things that could go wrong at this point.

In my particular case, I eventually found the error that was causing my problems by looking at `docker logs`: 

```
ubuntu@ip-172-31-80-217:~$ docker logs ca4405266f74
I0329 19:10:50.856076       1 server.go:121] Version: v1.9.6
I0329 19:10:50.856317       1 cloudprovider.go:59] --external-hostname was not specified. Trying to get it from the cloud provider.
I0329 19:10:50.856446       1 aws.go:1000] Building AWS cloudprovider
I0329 19:10:50.856506       1 aws.go:963] Zone not specified in configuration file; querying AWS metadata service
error setting the external host value: "aws" cloud provider could not be initialized: could not init cloud provider "aws": error finding instance i-0066b41e9dab8d832: "error listing AWS instances: \"NoCredentialProviders: no valid providers in chain. Deprecated.\\n\\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\""
```

It would be great if we could expose these docker errors, or the errors from `docker.service` or `kubelet.service` to `kubeadm init`

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by timothysc** [comment]
Closing due to staleness.
