### ISSUE TITLE
controllerManagerExtraArgs enable-hostpath-provisioner

### ISSUE THREAD

**Issue by chriskinsman** [kubernetes/kubeadm#743]
## What keywords did you search in kubeadm issues before filing this one?

controllerManagerExtraArgs enable-hostpath-provisioner

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:05:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/arm"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/arm"}
- **Cloud provider or hardware configuration**:
Selfhosted on hypriotos / rpi
- **OS** (e.g. from /etc/os-release):
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
HYPRIOT_OS="HypriotOS/armhf"
HYPRIOT_OS_VERSION="v1.2.3"
HYPRIOT_DEVICE="Raspberry Pi"
HYPRIOT_IMAGE_VERSION="v1.7.1-k8s-ALPHA"
- **Kernel** (e.g. `uname -a`):
Linux node1 4.4.50-hypriotos-v7+ #1 SMP PREEMPT Sun Mar 19 14:11:54 UTC 2017 armv7l GNU/Linux
- **Others**:

## What happened?

Trying to add a controller manager extra arg, enable-hostpath-provisioner.  Using this config with kubeadm init --config kubeadm-init.yaml:

`
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
controllerManagerExtraArgs:
 enable-hostpath-provisioner:
tokenTTL: 0s
networking:
  podSubnet: 10.244.0.0/16
`

Get in preflight output:

[preflight] WARNING: kube-controller-manager: failed to parse extra argument --enable-hostpath-provisioner=

Have tried enable-hostpath-provisioner: true also but this causes it to fail to parse the config.

## What you expected to happen?

Flag to be added to pod startup command.  

## How to reproduce it (as minimally and precisely as possible)?

Use above kubeadm config

**Comment by timothysc** [comment]
@chriskinsman - could you please pastebin your .yaml file.  It seems like it could be a formatting issue.  

You can always verify with - http://www.yamllint.com/

**Comment by chriskinsman** [comment]
Verified fine with yamllint

Pastebin is here:  [https://pastebin.com/EweJs3JY](https://pastebin.com/EweJs3JY)

When I look at the manifest for kube-controller-manager it puts it in with an = on the end but no value.  Docs for kube-controller-manager args make it appear to be a flag with no value.  Not sure if true would be valid in this context.

**Comment by bart0sh** [comment]
@chriskinsman Can you check if it works for you with this ```enable-hostpath-provisioner: "true"```?

**Comment by chriskinsman** [comment]
In the middle of testing something else so won't be able to try for a bit.  I had tried it without the double quotes with no luck.  Will try it with later this week.

**Comment by cfregly** [comment]
@bart0sh @chriskinsman 

same issue with "true"

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
controllerManagerExtraArgs:
  enable-hostpath-provider: "true"
```

```
	[WARNING ExtraArgs]: kube-controller-manager: failed to parse extra argument --enable-hostpath-provider=true
```

kube 1.10.0, ubuntu 16.04

**Comment by cfregly** [comment]
oops, typo on my end.  `enable-hostpath-provider` => `enable-hostpath-provisioner`.

it seems to be working with `enable-hostpath-provider: "true"`  <= must have the quotes around "true", btw.

**Comment by bart0sh** [comment]
@cfregly I'm glad it worked for you. @timothysc should we close this issue?

**Comment by timothysc** [comment]
@bart0sh - yup, closing.
