### ISSUE TITLE
[WARNING FileExisting-ebtables]: ebtables not found in system path. Linux

### ISSUE THREAD

**Issue by arunmothe** [kubernetes/kubeadm#745]
I am getting error ebtables not found in system path during initializing Kubeadm. This issue is resolved in latest package but i am still facing the same. https://github.com/kubernetes/kubeadm/issues/6
I am using YAML to perform this, below is my code:

     -name: Initialize Kubeadm
      become: true
      become_method: pbrun
      become_user: root
      command: kubeadm init
      register: out
    - debug: var=out.stdout_lines`

Below is the error i am getting:
FAILED! => {"changed": true, "cmd": ["kubeadm", "init"], "delta": "0:00:02.550572", "end": "2018-04-08 00:23:32.576190", "failed": true, "rc": 2, "start": "2018-04-08 00:23:30.025618", "stderr": "\t[WARNING FileExisting-ebtables]: ebtables not found in system path\n\t[WARNING FileExisting-ethtool]: ethtool not found in system path\n\t

**Comment by detiber** [comment]
@arunmothe can you provide me the output of both `kubeadm version` and `cat /etc/os-release` on the host you are running the playbook against?

**Comment by detiber** [comment]
@arunmothe A few more followup questions:
- How did you install the kubelet binary?
- If from a package, which repository and which version of the package?

**Comment by kad** [comment]
Both debian and rpm packages have nowadays dependencies to both ethtool and ebtables from the warnings output above. Closing. 
/close
