### ISSUE TITLE
kubeconfig should allow groups (organizations) to be specified in client cert

### ISSUE THREAD

**Issue by TomRK1089** [kubernetes/kubeadm#753]
## What keywords did you search in kubeadm issues before filing this one?

kubeconfig, client certificate, group

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST
I'd like to be able to specify one or more organizations in the client certificate generated by `kubeadm alpha phase kubeconfig user`. Currently I can specify the CN (corresponding to a user) but not any of the O (corresponding to a group) fields. (or if I can, the command-line help doesn't show how.)

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
Virtualized OS on Hyper-V (private cloud)
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
Linux kubernetes-master 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?
I generated a client certificate using the command documented in the Kubernetes kubeadm guide:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

> For normal users, it’s recommended to generate an unique credential to which you whitelist privileges. You can do this with the kubeadm alpha phase kubeconfig user --client-name <CN> command. That command will print out a KubeConfig file to STDOUT which you should save to a file and distribute to your user. After that, whitelist privileges by using kubectl create (cluster)rolebinding.

## What you expected to happen?
There would be an additional flag to specify one or more groups.

**Comment by xiangpengzhao** [comment]
@TomRK1089 I send PR https://github.com/kubernetes/kubernetes/pull/62627 to support this. PTAL.
