### ISSUE TITLE
"kubeadm alpha phase kubeconfig user" fails on restricted networks

### ISSUE THREAD

**Issue by chrisob** [kubernetes/kubeadm#756]
## What keywords did you search in kubeadm issues before filing this one?
kubeadm alpha phase kubeconfig user restricted network offline

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions
**kubeadm version** (use `kubeadm version`):
`kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
`
- **Cloud provider or hardware configuration**:
AWS
- **OS** (e.g. from /etc/os-release):
CentOS Linux release 7.4.1708
- **Kernel** (e.g. `uname -a`):
`Linux <REDACTED>.compute.internal 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- **Others**:

## What happened?
It appears that the command `kubeadm alpha phase kubeconfig user` attempts to "phone home" to get the latest stable version of k8s, which causes a failure in restricted/offline/corporate networks:
```
kubeadm alpha phase kubeconfig user --client-name admin --apiserver-advertise-address <REDACTED>
unable to get URL "https://dl.k8s.io/release/stable-1.9.txt": Get https://dl.k8s.io/release/stable-1.9.txt: EOF
```
I have verified that this command works as expected when whitelisting the domains `dl.k8s.io` and `storage.googleapis.com` in our proxy (and letting kubeadm call out over the internet), but this is not a production-ready solution!

## What you expected to happen?
I would expect that we can override this behavior of "phoning home" with a command line flag to specify the k8s version, similar to how other `kubeadm` sub-commands accept an explicit `--kubernetes-version`.

## How to reproduce it (as minimally and precisely as possible)?
Run `kubeadm alpha phase kubeconfig user` in a k8s cluster that is on a restricted/offline network, or on an already-running cluster with the `dl.k8s.io` domain blacklisted with something like `echo 127.0.0.1 dl.k8s.io >>/etc/hosts`.

**Comment by xiangpengzhao** [comment]
kubernetes version is not actually used here, so we don't need to specify it by an extra flag. We need to address this case in the code of this command.

/kind enhancement
/assign

**Comment by chrisob** [comment]
Even better, thanks for looking into this :)
