### ISSUE TITLE
Enable Advanced Auditing Webhook Backend Configuration

### ISSUE THREAD

**Issue by hh** [kubernetes/kubeadm#759]
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#webhook-backend

```--audit-webhook-config-file``` should be supported at a minimum

**Comment by timothysc** [comment]
@hh - This exists as an option that can be passed through to enable, but hasn't yet been abled by default.  

I don't know what stage it lives at in it's lifecycle, but we may want to setup sane defaults now.  

/cc @chuckha @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by hh** [comment]
I could only find the following parameters:

```
--audit-policy-file
--audit-log-path
--audit-log-maxage
```
For webhooks we are going to need ```--audit-webhook-*``` and [friends](https://github.com/kubernetes/website/blob/master/docs/tasks/debug-application-cluster/audit.md#webhook-backend):

```go
$ grep -r \\-\\-audit ./cmd/kubeadm/
./cmd/kubeadm/app/phases/controlplane/manifests_test.go:                                "--audit-policy-file=/etc/kubernetes/audit/audit.yaml",
./cmd/kubeadm/app/phases/controlplane/manifests_test.go:                                "--audit-log-path=/var/log/kubernetes/audit/audit.log",
./cmd/kubeadm/app/phases/controlplane/manifests_test.go:                                "--audit-log-maxage=0",
./cmd/kubeadm/app/phases/controlplane/manifests.go:             command = append(command, "--audit-policy-file="+kubeadmconstants.GetStaticPodAuditPolicyFile())
./cmd/kubeadm/app/phases/controlplane/manifests.go:             command = append(command, "--audit-log-path="+filepath.Join(kubeadmconstants.StaticPodAuditPolicyLogDir, kubeadmconstants.AuditPolicyLogFile))
./cmd/kubeadm/app/phases/controlplane/manifests.go:                     command = append(command, fmt.Sprintf("--audit-log-maxage=%d", kubeadmapiext.DefaultAuditPolicyLogMaxAge))
./cmd/kubeadm/app/phases/controlplane/manifests.go:                     command = append(command, fmt.Sprintf("--audit-log-maxage=%d", *cfg.AuditPolicyConfiguration.LogMaxAge))
```

**Comment by hh** [comment]
Work happening in https://github.com/kubernetes/kubernetes/pull/62826.
Any feedback / guidance is appreciated.

**Comment by luxas** [comment]
We concluded that this can be done via `.APIServerExtraArgs` and `.APIServerExtraVolumes` instead. We'll provide documentation for this instead.

**Comment by chrissound** [comment]
Any idea where is this documented? @luxas I'm not sure what config parameters to set.
