### ISSUE TITLE
kubeadm does not copy the cloud configuration file to nodes

### ISSUE THREAD

**Issue by nnashok** [kubernetes/kubeadm#77]
When initializing a cluster using `kubeadm` with a cloud provider, the cloud configuration is not copied to the nodes. This causes the `kubelet` on the node fail, the logs show:
```text
Nov 29 18:06:29 ip-x-x-x-x systemd[1]: Starting Kubernetes Kubelet Server...
Nov 29 18:06:29 ip-x-x-x-x kubelet[15981]: F1129 18:06:29.760971   15981 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/cloud-config.conf: &os.PathError{Op:"open", Path:"/etc/kubernetes/cloud-config.conf", Err:0x2}
Nov 29 18:06:29 ip-x-x-x-x systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Nov 29 18:06:29 ip-x-x-x-x systemd[1]: Unit kubelet.service entered failed state.
Nov 29 18:06:29 ip-x-x-x-x systemd[1]: kubelet.service failed.
```

Workaround: Create the cloud config file on the nodes and restart `kubelet` on the nodes. However, this then requires that `kubeadm` be started with `--skip-preflight-checks` argument as it otherwise complains with:
```text
Running pre-flight checks
preflight check errors:
        /etc/kubernetes is not empty
```

**Comment by luxas** [comment]
That's expected. Read the warning that kubeadm init outputs. You have to copy the cloud config file yourself.
