### ISSUE TITLE
Kube-Scheduelr Static Pod picking up wrong yaml

### ISSUE THREAD

**Issue by anishasthana** [kubernetes/kubeadm#771]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 

## Versions

**kubeadm version**: `&version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version**: `version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}` 
- **Cloud provider or hardware configuration**: CentOS Instances running on an OpenStack environment
- **OS**:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel**: `Linux version 3.10.0-514.26.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) )`

## What happened?

There seems to be something wrong with the parsing for manifests/kube-scheduler.yaml . I had to make some modifications to the yaml so I created a copy of the original called kube-scheduler_orig.yaml . The scheduler pod picked up config options from kube-scheduler_orig.yaml. I was able to fix the problem by moving kube-scheduler_orig.yaml to a directory somewhere else. 

## What you expected to happen?

I expected it to pick up settings from kube-scheduler.yaml.

## How to reproduce it (as minimally and precisely as possible)?

Create a file called kube-scheduler_orig.yaml in the manifests directory. The kube-scheduler pod picks up config settings from kube-scheduler_orig.yaml instead of kube-scheduler.yaml.

**Comment by chuckha** [comment]
This is part of how the kubelet runs static pods. By default, if you installed the kubelet with a package manager, the static manifests file will be `/etc/kubernetes/manifests`. So the kubelet will load any file in that directory regardless of the file name.

Here is some further reading to see how the kubelet handles static pods: https://kubernetes.io/docs/tasks/administer-cluster/static-pod/

**Comment by luxas** [comment]
> So the kubelet will load any file in that directory regardless of the file name.

Exactly right. Just move the _orig.yaml file in any other directory and things will work :)
