### ISSUE TITLE
Create a Test Plan Document 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#772]
1.10 bit us hard, and there were even a bunch of scenarios that are not covered by testing.  

We should outline a manual test-plan that we should exercise before the next release. 

Developer documentation can reside in this repository.  

/cc @liztio @stealthybox

**Comment by luxas** [comment]
This is happening while we release v1.11, but the doc itself is not critical (blocking) to releasing v1.11

**Comment by rdodev** [comment]
Agreed. Let's focus on cutting a release and then think about the plan more deliberately.

**Comment by stealthybox** [comment]
@kad mentions increasing importance of test matrix for kubeadm deployments with different CRI's because:
- we've run into cluster configuration issues for device driver development /w other CRI's
- kubeadm has bugs related to CRI deployment support

need automated tests running in Prow

**Comment by stealthybox** [comment]
@rdodev I can help you push this forward

We mentioned this in today's [kubeadm office hours](https://docs.google.com/document/d/130_kiXjG7graFNSnIAgtMS1G8zPDwpkshgfRYS0nggo/edit#heading=h.1n16sghgip83) and plan to talk about the test plan again on July 11

@timothysc mentioned you have a test plan you've already been enacting -- we'd like to turn that into documented steps that we can action to others as well.

**Comment by rdodev** [comment]
@stealthybox The plan I've been working on was very specific to beta.2 and rc.1 _manual_ testing. Basically identified areas that needed 👀 to make the 1.11 cut and lacked automated testing.

@fabriziopandini has a doc which good skeleton of all major areas of kubeadm which can be expanded upon and rally around of, however.

**Comment by rdodev** [comment]
@stealthybox et all. One issue I want to raise is that before we talk about support matrices and intricate testing plans, is that we should have the testing infrastructure in place to support that. Perhaps I'm wrong because I'm new to all of this, but I don't see the testing infrastructure today that would be able to truly test permutations and variations in configuration for correctness. However, there's work presently being done by testing-commons that could possibly help alleviate that.

//cc @timothysc

**Comment by timothysc** [comment]
Let's figure out how - where to automate this in 1.12.
/assign @stealthybox

**Comment by timothysc** [comment]
I'm going to close this issue due to staleness.  Basically walking our documentation now has become the manual test plan.  Ideally, as we formalize tests we get them added to the kubeadm.test utilities.
