### ISSUE TITLE
Fix the upgrade tests. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#775]
The kubeadm upgrade tests are totally broken, I have decided to serve as tribute to go and help fix them 

/cc @jberkus

**Comment by jberkus** [comment]
Thank you!

**Comment by stealthybox** [comment]
these tests are super important :+1: tyvm

**Comment by timothysc** [comment]
PR's in flight 
https://github.com/kubernetes/kubernetes/pull/63504
https://github.com/kubernetes/kubernetes/pull/63595
https://github.com/kubernetes/kubernetes/pull/63596

We'll have to check the status in the next ~24-hours 

/cc @dims @BenTheElder @luxas @kad

**Comment by kad** [comment]
After those patches will be merged to kubeadm, I think we will need to update line: 
https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L10268 to have `--upgrade-target=ci-cross/latest`. That should be correct value for master.

**Comment by colemickens** [comment]
@timothysc There's this one too, haven't seen you explictly ACK it yet so I'm mentioning it so that it's tracked. https://github.com/kubernetes/kubernetes/issues/63508

**Comment by dims** [comment]
@kad ack!

**Comment by dims** [comment]
@luxas @timothysc what other tests were broken?

**Comment by timothysc** [comment]
I scoured testgrid this morning, and all major upgrade tests look to be good.  

@dims thx for the help!  
https://youtu.be/XeGRwe4g0ew

**Comment by dims** [comment]
Aye Aye Captain! :)

**Comment by timothysc** [comment]
fwiw - I don't see a need to back-patch to 1.8 tests
