### ISSUE TITLE
Make kube-proxy optional (default to install)

### ISSUE THREAD

**Issue by iMartyn** [kubernetes/kubeadm#776]
## What keywords did you search in kubeadm issues before filing this one?

kube-proxy

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

If this is a FEATURE REQUEST, please:

Kubeadm should give users a way not to install `kube-proxy` as it is not an essential part of kubernetes in some scenarios.

For instance, if using `kube-router` in "All features" mode, you have to delete kube-proxy and do cleanup.

## Versions

**kubeadm version** (use `kubeadm version`): &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Packet.net
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): 4.16.5-1.el7.elrepo.x86_64 #1 SMP Thu Apr 26 09:54:55 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

There was no way to disable the installation of kube-proxy with kubeadm

## What you expected to happen?

To be able to pass a flag to disable the installation of kube-proxy

## How to reproduce it (as minimally and precisely as possible)?

kubeadm init?

## Anything else we need to know?

It's not a big or high priority issue but it would make for a cleaner workflow if people do not require kube-proxy.

**Comment by detiber** [comment]
@xlgao-zju It will require a new item in the config: https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/app/apis/kubeadm, and adding a condition to anywhere the proxy phase is called, such as: https://github.com/kubernetes/kubernetes/blob/218b334d2681077db6a384a6671f89faa4122873/cmd/kubeadm/app/cmd/init.go#L505-L508

**Comment by timothysc** [comment]
I'm going to close this issue for 1.13 b/c we are addressing this via our promotion of phases to init.  

This will allow folks to skip specific phases. 
/cc @fabriziopandini

**Comment by ensonic** [comment]
The milestone (https://github.com/kubernetes/kubeadm/milestone/9) is close, where can I read about "promotion of phases to init"? https://github.com/kubernetes/kubeadm/tree/master/docs/design did not got an update for a while.

**Comment by neolit123** [comment]
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#init-phases

although there is a bug when skipping the kube-proxy addon from a CP node and then joining a worker node.
