### ISSUE TITLE
Enable CoreDNS by default in v1.11

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#782]
Both IPVS, and CoreDNS are being moved to beta and we should determine if we are ready to enable and default. 

I'd be in favor of enabling CoreDNS as a default, but I'm slightly concerned about the ordering IPVS and who should do what. 

/cc @kubernetes/sig-cluster-lifecycle-misc @kubernetes/sig-network-misc 

/assign @detiber

**Comment by luxas** [comment]
I think enabling CoreDNS by default in v1.11 makes sense. kubeadm is beta, which requires our dependencies to be beta. I don't expect our clusters to break when making this the default, but we might even catch one or two bugs in CoreDNS by exposing more users to it before it goes GA.

What we win on doing this is better reliability and higher performance by default.

**Comment by bowei** [comment]
CoreDNS is going GA but we are not enabling CoreDNS by default in 1.11.

**Comment by luxas** [comment]
Split this into two tickets, this one for CoreDNS in v1.11 and https://github.com/kubernetes/kubeadm/issues/817 for ipvs in the future

**Comment by luxas** [comment]
https://github.com/kubernetes/kubernetes/pull/63509 fixed this. Please open a new issue for documenting this @neolit123
