### ISSUE TITLE
Flag to add extra SAN for etcd server in kubeadm 

### ISSUE THREAD

**Issue by gauravyadav01** [kubernetes/kubeadm#786]
If this is a FEATURE REQUEST, please:
   Flag to add extra SANs for etcd server in kubeadm 

  - Describe *in detail* the feature/behavior/change you'd like to see.
     Flag to add extra SANs for etcd server very similar to Api server --apiserver-cert-extra-sans in 
     Kubeadm.

     Right now it is default to localhost and 127.0.0.1. 

## Versions
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:

Vagrant 
- **OS** (e.g. from /etc/os-release):
Centos 7.4

- **Kernel** (e.g. `uname -a`):
Linux master1.example.com 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stealthybox** [comment]
Thanks for submitting this issue @gauravyadav01 
We won't be adding a flag for this, as we're not adding flags anymore.

It is supported by the config file:
```yaml
etcd:
  serverCertSANs:
    - hostname1
    - hostname2
  peerCertSANs:
    - hostname2
    - hostname3
```
The code that implements this option is here:
https://github.com/kubernetes/kubernetes/blob/8abc54d2576037b92c0fcae7aa4c43128332801c/cmd/kubeadm/app/apis/kubeadm/types.go#L198-L203

It looks like we need to update the docs to demonstrate this:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file
