### ISSUE TITLE
kubeadm join command gets timed out every time in Ubuntu 16.04

### ISSUE THREAD

**Issue by aryak007** [kubernetes/kubeadm#789]
I am using Ubuntu 16.04 (Xenial) but here's a problem which I face with `kubeadm` while joinig `nodes` to my `master`: 

**While joining a `node` to my `master`, I continuouly get a timeout issue** - 

    [discovery] Failed to request cluster info, will try again: [Get 
    https://{{MASTER_IP}}/api/v1/namespaces/kube- 
    public/configmaps/cluster-info: dial tcp {{MASTER_IP}}: i/o timeout]
    [discovery] Failed to request cluster info, will try again: [Get 
    https://{{MASTER_IP}}/api/v1/namespaces/kube- 
    public/configmaps/cluster-info: dial tcp {{MASTER_IP}}: i/o timeout]

*I can `ping` the `master` from my `node`. I can even `ssh` into the `master` from my `node` but I can't join it to the cluster. I must also mention that I am not operating behind a proxy as I can ping and ssh into the `master` from the `node`* 

I have tried with flags like `no_proxy={{MASTER_IP}}` . I have also tried initiating the cluster on the master with the command 

    sudo kubeadm init --apiserver-advertise-address={{MASTER_IP}}

P.S. - I have gone through the git issues which are related to this. I've tried their solutions but in vain. Here's a link to one of them - 
[https://github.com/kubernetes/kubernetes/issues/58921][1]

  [1]: https://github.com/kubernetes/kubernetes/issues/58921

**Comment by Kailashcj** [comment]
can you provide the output of 'kubectl get svc kubernetes -o yaml'?
are you able to telnet cluster ip from your client node on port 443?

**Comment by aryak93** [comment]
After running `kubectl get svc kubernetes -o yaml` on the master
<img width="503" alt="screen shot 2018-05-06 at 1 30 10 pm" src="https://user-images.githubusercontent.com/6023820/39671234-aba1a85c-5131-11e8-87ea-95210b5cd8fb.png">

I notice that the cluster IP is different from my master's IP. Is that desired behaviour? 

Also, if I try telnet `telnet <<Cluster_IP>> 443`, it doesn't work. It stays stuck on `Trying <<Cluster_IP>> ...`

**Comment by Kailashcj** [comment]
yes, cluster-ip is different than node ip. 
IMO, when you add a client node through kubeadm join command, your port 6443 on master should be listening and your token should hold good. I suggest verify these,

1. sudo netstat -tuplen on master. verify that port 6443 is listening & from your client node do a telnet to port 6443 on master node ip. if this is working, the other thing which plays a role is your token. you can create a new token using below command on master node, if that works for you.
2. sudo kubadm token create --print-join-command

use the command generated in step2 to join your node with a new token

**Comment by aryak93** [comment]
When I run `sudo netstat -tuplen | grep 6443` on master, I get 
`tcp6       0      0 :::6443                 :::*                    LISTEN      0          177985      -`
, i.e., the port is running but I am unable to telnet it from the `node`. 

I am getting a timeout on `telnet <<Cluster_IP>> 6443` . Is it that any inbound connection to 6443 is getting rejected? How do I debug it? 

P.S. - Thanks for your help, though.

**Comment by Kailashcj** [comment]
ok. are you able to telnet 6443 as localhost on master node? what's the status of your firewall on both the systems?
check sudo ufw status on both nodes. 
also review the output of journalctl -xe on your worker node after join command fails.

**Comment by timothysc** [comment]
Please check the firewall settings, we vet 16.04 with every release and have built an image creation tool to  ensure our images are correct. https://github.com/heptiolabs/wardroom

**Comment by nlamirault** [comment]
I've got same issue (can't join cluster) using Kubernetes v1.9.6, with Master on Artful 17.04 and Node on HypriotOS 64b.
I see this logs : 

```
$ kubectl -n kube-system logs weave-net-dg5mv weave
FATA: 2018/05/14 10:44:32.580198 [kube-peers] Could not get peers: Get https://10.96.0.1:443/api/v1/nodes: dial tcp 10.96.0.1:443: i/o timeout
Failed to get peers
```

On master : 

```
$ sudo netstat -tuplen | grep 6443
tcp6       0      0 :::6443                 :::*                    LISTEN      0          41322       4571/kube-apiserver
```

On node : 

```
$ $ nc -vz 192.168.1.33 6443
Connection to 192.168.1.33 6443 port [tcp/*] succeeded!
```

**Comment by aryak93** [comment]
@timothysc  @Kailashcj Yes. It was a firewall issue. It works if I turn off the firewall. @nlamirault You can also check the firewall once.

**Comment by nlamirault** [comment]
On node : 

```$ sudo ufw status
Status: inactive

$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  anywhere             anywhere            

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  anywhere             anywhere            

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain WEAVE-NPC (0 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             base-address.mcast.net/4 
WEAVE-NPC-DEFAULT  all  --  anywhere             anywhere             state NEW
WEAVE-NPC-INGRESS  all  --  anywhere             anywhere             state NEW
ACCEPT     all  --  anywhere             anywhere             ! match-set weave-local-pods dst

Chain WEAVE-NPC-DEFAULT (1 references)
target     prot opt source               destination         

Chain WEAVE-NPC-INGRESS (1 references)
target     prot opt source               destination         
```

On master : 

```
$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere            

Chain FORWARD (policy DROP)
target     prot opt source               destination         
WEAVE-NPC  all  --  anywhere             anywhere             /* NOTE: this must go before '-j KUBE-FORWARD' */
NFLOG      all  --  anywhere             anywhere             state NEW nflog-group 86
DROP       all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forward rules */
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere            

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  10.244.0.0/16        anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             10.244.0.0/16        /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination         

Chain WEAVE-NPC (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             base-address.mcast.net/4 
WEAVE-NPC-DEFAULT  all  --  anywhere             anywhere             state NEW
WEAVE-NPC-INGRESS  all  --  anywhere             anywhere             state NEW
ACCEPT     all  --  anywhere             anywhere             ! match-set weave-local-pods dst

Chain WEAVE-NPC-DEFAULT (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             match-set weave-E.1.0W^NGSp]0_t5WwH/]gX@L dst /* DefaultAllow isolation for namespace: default */
ACCEPT     all  --  anywhere             anywhere             match-set weave-0EHD/vdN#O4]V?o4Tx7kS;APH dst /* DefaultAllow isolation for namespace: kube-public */
ACCEPT     all  --  anywhere             anywhere             match-set weave-?b%zl9GIe0AET1(QI^7NWe*fO dst /* DefaultAllow isolation for namespace: kube-system */

Chain WEAVE-NPC-INGRESS (1 references)
target     prot opt source               destination       
```

**Comment by nlamirault** [comment]
@luxas :+1:

**Comment by rowshan** [comment]
I tried to connect slave to master node via:
`sudo kubeadm join {master_ip}:6443 --token qsyq32.jsvm1emj05bk85p5 --discovery-token-ca-cert-hash sha256:e4faf6143b282f0d6fc55ce5e563f748e06a258176497da36564aeeacsudo kubeadm join 10.147.69.63:6443 --token qsyq32.jsvm1emj05bk85p5 --discovery-token-ca-cert-hash sha256:e4faf6143b282f0d6fc55ce5e563f748e06a258176497da36564aeeac657dc0657dc0`
I checked the port and found:
`sro@sro-T460:~/Desktop$ sudo netstat -nlpt|grep :10250
tcp6       0      0 :::10250                :::*                    LISTEN      24284/localkube 
`

then I stopped minikube : 
`minikube stop`

but then once again if I  try to join the slave node to master I get following error:
`sudo kubeadm join 10.147.69.63:6443 --token qsyq32.jsvm1emj05bk85p5 --discovery-token-ca-cert-hash sha256:e4faf6143b282f0d6fc55ce5e563f748e06a258176497da36564aeeac657dc0c `


`[preflight] Running pre-flight checks
[discovery] Trying to connect to API Server "10.147.69.63:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://10.147.69.63:6443"
[discovery] Failed to request cluster info, will try again: [Get https://10.147.69.63:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.147.69.63:6443: connect: no route to host]
[discovery] Failed to request cluster info, will try again: [Get https://10.147.69.63:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.147.69.63:6443: connect: no route to host]
[discovery] Failed to request cluster info, will try again: [Get https://10.147.69.63:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.147.69.63:6443: connect: no route to host]
[discovery] Failed to request cluster info, will try again: [Get https://10.147.69.63:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.147.69.63:6443: connect: no route to host]
[discovery] Failed to request cluster info, will try again: [Get https://10.147.69.63:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.147.69.63:6443: connect: no route to host]
`
Any suggestion?

**Comment by rowshan** [comment]
Here I would like to mentioned I have two different subnet for master and slave node.

**Comment by alexfromapex** [comment]
I was having this issue adding `--v=5` to the `kubeadm join` command helped to diagnose with more verbose output
