### ISSUE TITLE
Incorrect sample commands/example in official documents for HA using kubeadm

### ISSUE THREAD

**Issue by ajaynemade** [kubernetes/kubeadm#797]
## Versions

**kubeadm version** (use `kubeadm version`): 1.10.2

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.10.2
- **Cloud provider or hardware configuration**: AWS instances
- **OS** (e.g. from /etc/os-release): Centos 7.4
- **Kernel** (e.g. `uname -a`): 3.10.0-693.21.1.el7.x86_64
- **Others**:

## What happened?
I was referring https://kubernetes.io/docs/setup/independent/high-availability/ document for HA and saw some commands are incomplete i.e. values for few required fields are missing. 
For example,
After generating etcd and peer certificates, there is a choice to setup the etcd using systemd or static pods. In systemd, 

> Next, generate the environment file that systemd will use:
>    touch /etc/etcd.env
>    echo "PEER_NAME=" >> /etc/etcd.env
>    echo "PRIVATE_IP=" >> /etc/etcd.env 

I think it should be something like following
 
> Next, generate the environment file that systemd will use:
>    touch /etc/etcd.env
>    echo "PEER_NAME=${PEER_NAME}" >> /etc/etcd.env
>    echo "PRIVATE_IP=${PRIVATE_IP}" >> /etc/etcd.env

I used the PEER_NAME and PRIVATE_IP variables as those being exported in earlier steps
Similarly for etcd systemd init file content,

```
cat >/etc/systemd/system/etcd.service <<EOF
   [Unit]
   Description=etcd
   Documentation=https://github.com/coreos/etcd
   Conflicts=etcd.service
   Conflicts=etcd2.service

   [Service]
   EnvironmentFile=/etc/etcd.env
   Type=notify
   Restart=always
   RestartSec=5s
   LimitNOFILE=40000
   TimeoutStartSec=0

   ExecStart=/usr/local/bin/etcd --name  --data-dir /var/lib/etcd --listen-client-urls https://:2379 --advertise-client-urls https://:2379 --listen-peer-urls https://:2380 --initial-advertise-peer-urls https://:2380 --cert-file=/etc/kubernetes/pki/etcd/server.pem --key-file=/etc/kubernetes/pki/etcd/server-key.pem --client-cert-auth --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem --peer-cert-file=/etc/kubernetes/pki/etcd/peer.pem --peer-key-file=/etc/kubernetes/pki/etcd/peer-key.pem --peer-client-cert-auth --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem --initial-cluster <etcd0>=https://<etcd0-ip-address>:2380,<etcd1>=https://<etcd1-ip-address>:2380,<etcd2>=https://<etcd2-ip-address>:2380 --initial-cluster-token my-etcd-token --initial-cluster-state new

   [Install]
   WantedBy=multi-user.target
   EOF
```
In the above sinppet(taken from office document), if you check the ExecStart line the you will find few values are missing like,
--name <Hostname I believe>
--listen-client-urls https://<IP is missing private/public>:2379
--advertise-client-urls https://<IP is missing private/public>:2379
--listen-peer-urls https://<IP is missing private/public>:2380
--initial-advertise-peer-urls https://<IP is missing private/public>:2380

I observed same issue in the setting etcd using static pods section as well.

## What you expected to happen?
It would be greate if given commands are with proper required values otherwise it will create confusion like if to use private ip or public ip.

## How to reproduce it (as minimally and precisely as possible)?
Visit following link,
https://kubernetes.io/docs/setup/independent/high-availability/#etcd-mode-1
https://kubernetes.io/docs/setup/independent/high-availability/#etcd-mode-2

**Comment by neolit123** [comment]
@ajaynemade 

1)

> I think it should be something like following
```
> Next, generate the environment file that systemd will use:
touch /etc/etcd.env
echo "PEER_NAME=${PEER_NAME}" >> /etc/etcd.env
echo "PRIVATE_IP=${PRIVATE_IP}" >> /etc/etcd.env
```

looks like the correct way to do it.

2)

> In the above sinppet(taken from office document), if you check the ExecStart line the you will find few values are missing like,

some of the values are missing due to being wrapped in `<>`.

i will try to submit a fix for these (1, 2).

**Comment by neolit123** [comment]
^ that should do it, @ajaynemade
