### ISSUE TITLE
--data-dir of etcd should be '/var/lib/etcd  instead of '/var/etcd/data'

### ISSUE THREAD

**Issue by tonyclam** [kubernetes/kubeadm#80]
Is this a request for help? (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
 No
 What keywords did you search in Kubernetes issues before filing this one? (If you have found any duplicates, you should instead reply there.):
 '--data-dir'+'etcd'

Is this a BUG REPORT or FEATURE REQUEST? (choose one):
 BUG REPORT

Kubernetes version (use kubectl version):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Environment:

Cloud provider or hardware configuration:
 OS (e.g. from /etc/os-release): Centos 7.2
 Kernel (e.g. uname -a): 4.1.12-37.5.1.el7uek.x86_64 #2 SMP Thu Jun 9 16:01:20 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
 Install tools:
 Others:
 What happened:
I used the following kubectl command:
kubectl describe pods etcd-ovm25 --namespace=kube-system:
(partial output)
Containers:
  etcd:
    Container ID:       docker://28970a7bee926148ee8972789cfad908b7869abb51a52a70f4377da0b6a6a801
    Image:              gcr.io/google_containers/etcd-amd64:2.2.5
    Image ID:           docker://sha256:72bd8a257d7ab32461debdef1eed6729979e448c34f8f883edb616e1de9c5d25
    Port:
    Command:
      etcd
      --listen-client-urls=http://127.0.0.1:2379
      --advertise-client-urls=http://127.0.0.1:2379
      --data-dir=/var/etcd/data

What you expected to happen:
 --data-dir=/var/lib/etcd

How to reproduce it (as minimally and precisely as possible):
-install the kubernetes master
-kubeadm init 
-kubectl describe pods etcd-ovm25 --namespace=kube-system

 Anything else do we need to know:
 kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.421+a6bea3d79b8bba", GitCommit:"a6bea3d79b8bbaa5e8b57482c9fff9265d402708", GitTreeState:"clean", BuildDate:"2016-11-03T06:54:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

The recommended fix:
/root/kubernetes/cmd/kubeadm/app/master/manifests.go:

        // Add etcd static pod spec only if external etcd is not configured
        if len(s.InitFlags.API.Etcd.ExternalEndpoints) == 0 {
                staticPodSpecs[etcd] = componentPod(api.Container{
                        Name: etcd,
                        Command: []string{
                                "etcd",
                                "--listen-client-urls=http://127.0.0.1:2379",
                                "--advertise-client-urls=http://127.0.0.1:2379",
92c92
<                               "--data-dir=/var/etcd/data",
---
>                               "--data-dir=/var/lib/etcd",
                        },
                        VolumeMounts:  []api.VolumeMount{certsVolumeMount(), etcdVolumeMount(), k8sVolumeMount()},
                        Image:         images.GetCoreImage(images.KubeEtcdImage, s, s.EnvParams["etcd_image"]),

**Comment by luxas** [comment]
On your host, the data is stored on `/var/lib/etcd` as it should. It's just _inside the container_ the data is on `/var/etcd/data`

**Comment by tonyclam** [comment]
Thanks for reply.
May I ask on /root/kubernetes/cmd/kubeadm/app/master/manifests.go:
func etcdVolumeMount() api.VolumeMount {
        return api.VolumeMount{
                Name:      "etcd",
                MountPath: "/var/etcd",
        }
}
The MountPath should be '/var/lib'

**Comment by kad** [comment]
even inside container it's better to use FHS paths. any reason why historically those paths /var/etcd appeared ?

**Comment by luxas** [comment]
Historically, I think `/var/etcd/data` has been the default path, but I don't know for sure.
Sure, we can change that to `/var/lib/etcd` inside the container as well, but I don't think it's super-priority since it's not affecting anyone.

**Comment by tonyclam** [comment]
/root/kubernetes/cmd/kubeadm/app/master/manifests.go:
func etcdVolumeMount() api.VolumeMount {
return api.VolumeMount{
Name: "etcd",
MountPath: "/var/etcd",
}
}
The MountPath may be '/var/lib'

**Comment by pires** [comment]
Since there is no upgrade path for `kubeadm` yet, changing this is trivial.
