### ISSUE TITLE
Drop dependency on `pkg/client/clientset_generated/internalclientset` from kubeadm

### ISSUE THREAD

**Issue by dims** [kubernetes/kubeadm#806]
As part of the research into recursive dependencies of kubeadm in https://github.com/kubernetes/kubernetes/pull/63740/ we found that we depend on a lot of packages under `"k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset`

Since we are using client-go, we need to find out why we depend on these packages and try to get rid of them

**Comment by rosti** [comment]
Managed to trace this to the usage of the following:
- [GetFlagString](https://github.com/kubernetes/kubernetes/blob/a481f4bbe828d7fdec95782c02df3743c1020820/cmd/kubeadm/app/cmd/version.go#L63) from `k8s.io/kubernetes/pkg/kubectl/cmd/util`

- [LeaseEndpointReconcilerType](https://github.com/kubernetes/kubernetes/blob/a481f4bbe828d7fdec95782c02df3743c1020820/cmd/kubeadm/app/phases/controlplane/manifests.go#L205) from `k8s.io/kubernetes/pkg/master/reconcilers`

Excluding this from the build shaved off almost 5MB from the amd64 executable.

Will prepare PRs and send them for review.

**Comment by luxas** [comment]
xref: https://github.com/kubernetes/kubeadm/issues/497
