### ISSUE TITLE
Support preflight checks in config.yaml

### ISSUE THREAD

**Issue by davejrt** [kubernetes/kubeadm#808]
## What keywords did you search in kubeadm issues before filing this one?

config.yaml

preflight checks

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

When using a config.yaml file it would be great to be able to specify any preflight checks in the yaml file, rather than having to use the flag. My use case for this is having to skip a check based on the runtime being used but that's being determined upstream so I'd like to populate this file with the correct checks based on flags being setup further upstream. 

## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

Both Ubuntu 16.04 and Centos 7

- **Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
Vagrant 2.1.1
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04
Centos 7.4

**Comment by neolit123** [comment]
/assign @neolit123
we should probably decide if the command line flag for this should be deprecated completely in favor of the config.

**Comment by timothysc** [comment]
@neolit123 assigned ;-)

**Comment by timothysc** [comment]
We've decided against this.  
closing.
