### ISSUE TITLE
kubeadm upgrade needs some UX attention

### ISSUE THREAD

**Issue by detiber** [kubernetes/kubeadm#810]
## Is this a BUG REPORT or FEATURE REQUEST?

/kind feature

#### upgrade apply

the general error output from `apply` can be improved:
`[upgrade/apply] FATAL: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: [timed out waiting for the condition]`

if we can get some extra hints in there it could be easier for users to debug issues.
ref: https://github.com/kubernetes/kubeadm/issues/1005

#### upgrade plan

The current output from `kubeadm upgrade plan` leaves a bit to be desired, some examples are:
- before version for core components only uses the version introspected from the api server and uses that version for all core components, so if a user has modified the running versions or replaced a component with a custom image it is not reflected.
- the output when changing addons (such as migrating from Kube DNS to CoreDNS is not very intuitive
  - current master will show the different versions but list them under the same component name.
  - https://github.com/kubernetes/kubernetes/pull/63509 changes this to show both components, with empty columns to show added/removed, but having the output lumped in with standard component upgrades makes it a bit difficult to see what is happening at a quick glance.
- output for adding a component that didn't exist previously or one that is being removed is not overly intuitive if lumping in with component upgrades

I believe it would make sense to attempt to better summarize what is happening with the upgrade and have a way to break out information for newly added components, removed components, or component replacement into their own sections with some additional context to help users understand what is going to happen during their upgrade.

## Versions

**kubeadm version** (use `kubeadm version`): v1.10.2, v1.11.0-alpha.2

**Comment by neolit123** [comment]
> I believe it would make sense to attempt to better summarize what is happening with the upgrade and have a way to break out information for newly added components, removed components, or component replacement into their own sections with some additional context to help users understand what is going to happen during their upgrade.

i like the idea! here is how i see the pseudo-output:

```
UPGRADE:

* upgraded:
<name>	<old version>	<new version>
...

* added:
<name>	<version>
	<possibly-outline-reason-if-automatic>
<name>	<version>
	<possibly-outline-reason-if-automatic>
...

* removed:
<name>	<version>
	<possibly-outline-reason-if-automatic>
<name>	<version>
	<possibly-outline-reason-if-automatic>
...

* replaced: 
<old comp. name>	<old version>	<new comp. name>	<new version>
	<possibly-outline-reason-if-automatic>
<old comp. name>	<old version>	<new comp. name>	<new version>
	<possibly-outline-reason-if-automatic>
...
```

if we don't have any `replaced` and `added` it could look like:
```
UPGRADE:
* upgraded:
<name>	<old version>	<new version>
...

* removed:
<name>	<version>
	<possibly-outline-reason-if-automatic>
<name>	<version>
	<possibly-outline-reason-if-automatic>
...
```

i guess we can break these sections into separate tabwriters and then iterate only those that are filled and concat into a final buffer. something in those lines...

it's probably better to stick to the tabwriter, because we might not want to introduce another dependency.

**Comment by neolit123** [comment]
someone recently requested upgrade phases as well.

**Comment by timothysc** [comment]
Closing in favor of #494 b/c changes there will overlap in this area.
