### ISSUE TITLE
Automatic Kubeadm E2E Tests

### ISSUE THREAD

**Issue by liztio** [kubernetes/kubeadm#813]
Since we created E2E tests for kubeadm (#190) we want to automatically run those tests.

Some things we may want to test:

- [ ] `kubeadm init`
- [ ] `kubeadm upgrade`
- [ ] multiple providers (AWS, GKE, Azure...)
- [ ] Version matrix?

**Comment by timothysc** [comment]
@liztio lets coordinate testing efforts with @stealthybox this cycle.

**Comment by neolit123** [comment]
> kubeadm init
>  kubeadm upgrade
...
> Version matrix?

we have plans to test these with kind.

> multiple providers (AWS, GKE, Azure...)

seems to me this enters the land of cluster-api.

> Create `[Feature:kubeadm]`

this we need to look at with the kind deployer and possibly run it next to the e2e conformance tests.

/assign

**Comment by timothysc** [comment]
Closing in favor of #1543 where the changes are being made.
