### ISSUE TITLE
Track when we can enable the ipvs mode for the kube-proxy by default

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#817]
xref: https://github.com/kubernetes/kubeadm/issues/816 and https://github.com/kubernetes/kubeadm/issues/782

cc @kubernetes/sig-network-feature-requests when is ipvs going GA?

**Comment by cmluciano** [comment]
There are no current releases targeted for a GA release at this time. We are still assembling the GA criteria and gathering feedback from the community.

**Comment by luxas** [comment]
Okay, thanks

**Comment by timothysc** [comment]
Only updating to track for this cycle.

**Comment by timothysc** [comment]
@caseydavenport any insight?

**Comment by bowei** [comment]
cc: @Lion-Wei

**Comment by caseydavenport** [comment]
IPVS kube-proxy went GA in v1.11 - https://github.com/kubernetes/features/issues/265

However, there seem to be a few issues open affecting IPVS mode re: the version of iptables/ipset shipped in the kube-proxy container image that might inhibit its adoption in kubeadm, that we'll need to sort out first.

- https://github.com/kubernetes/kubernetes/issues/68974
- https://github.com/kubernetes/kubernetes/issues/68703

CC @m1093782566

**Comment by Lion-Wei** [comment]
Thanks, @bowei 
@caseydavenport , I think both those issue are solved in master, maybe need cherry-pick to 1.11/1.10 to make all version work.
xref: 
https://github.com/kubernetes/kubernetes/issues/68974#issuecomment-424315216
https://github.com/kubernetes/kubernetes/issues/68703#issuecomment-426102874
I'll trace those issues to make sure they all completely solved.

**Comment by m1093782566** [comment]
@caseydavenport 

These issues you mentioned has already been fixed and we only need to cherry-pick the fixes.

**Comment by timothysc** [comment]
@caseydavenport @Lion-Wei @m1093782566 - Is there any reason for it to not be the default for all deployments?

**Comment by neolit123** [comment]
as a side note, our e2e by default does iptables currently.

**Comment by Lion-Wei** [comment]
Hi, @timothysc , I think there still an issue https://github.com/kubernetes/kubernetes/issues/70747 we should pay attention.

**Comment by timothysc** [comment]
k, I'm thinking we should make this a default for 1.14 out of the gate move the feature gate.

**Comment by timothysc** [comment]
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ipvs+label%3Asig%2Fnetwork+  

clearly is not ready for defaulting

**Comment by neolit123** [comment]
adding some feedback to this old issue.

with Windows nodes in the picture and with the planned changes for multi-OS in the kube-proxy config things are moving in this space.

given the complications i've seen in past reports with IPVS kernel modules missing or disabled on user nodes, i'm inclined to recommend that we do not enable IPVS as the default mode yet.

iptables works and people are familiar with it, IPVS is advanced, faster and feels to me it should be the decisions on the side of cluster operators.

**Comment by cmluciano** [comment]
@andrewsykim @lbernail Do you think we should close this issue ? I agree with @neolit123 's comments and I'm not sure if this issue makes sense to keep open.

**Comment by andrewsykim** [comment]
Yeah I agree, not sure that it was ever intended for IPVS to be the default.

**Comment by lbernail** [comment]
Yeah I think at one point we really wanted to try but we are still lacking tests. I'd say for mid-size clusters iptables is very good because it's very well tested. ipvs makes more sense in large clusters but still does not completely align with what support in iptables mode

**Comment by neolit123** [comment]
thanks for the comments. let's continue keeping iptables as the default with opt-in for IPVS, maybe one day making IPVS the default if kube-proxy has it as the default.
