### ISSUE TITLE
Graduate audit logging in kubeadm to beta and on-by-default in v1.12

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#818]
Investigate what we still need to do to graduate all this

**Comment by timothysc** [comment]
I don't think we should turn on something like this by default, b/c it gets into policy.  I'd prefer to have a guide for folks to hook into instead, especially given the dynamic webhook proposal.  

https://github.com/kubernetes/community/pull/2188

**Comment by timothysc** [comment]
closing in favor of dynamic policy.
