### ISSUE TITLE
Set up testing infra for v1.11

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#819]
(and remove testing infra for v1.8)

Similar to https://github.com/kubernetes/kubeadm/issues/426

**Comment by luxas** [comment]
@hh volunteered to help work on this :tada:

**Comment by hh** [comment]
- [ ] https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-upgrade-stable-master
Doesn't seem to be healthy, heaps of e2e tests executed
- [ ] deprecating all *1.8*
- [ ] upgrade* 1.10-11 (create a 1.10 cluster using 1.10, then upgrade to 1.11 using 1.11)
- [ ] kubeadm-gce-1.11 (creating 1.11 cluster using latest 1.11 branch)
- [ ] kubeadm-gce-1.10-on-1.11 (creating a 1.10 cluster using cli 1.11)

* https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#kubeadm-gce-upgrade-1.9-1.10 (works)
expe8ted to fail: statefulset/hpa/service-upgrades

**Comment by neolit123** [comment]
i suggest we extend this `README.md`:
https://github.com/kubernetes/kubeadm/tree/master/tests/e2e

* title the whole document `E2E tests for kubeadm`
* move `Tools for verifying Kubernetes packages are published` into a sub-section
* include another section that can outline some of the steps in the video you guys did:
https://www.youtube.com/watch?v=aTGbdPU0fE8
