### ISSUE TITLE
CoreDNS manifest does not allow custom image repository

### ISSUE THREAD

**Issue by praseodym** [kubernetes/kubeadm#821]
In kubeadm 1.10, CoreDNS is available as a beta replacement for kube-dns. Unfortunately, the manifest that is deployed is not suitable for offline or limited connectivity environments, because it is [not possible to set the image repository](https://github.com/kubernetes/kubernetes/blob/e9f996bfe26ca1257089937cc5ada4025661e2a6/cmd/kubeadm/app/phases/addons/dns/manifests.go#L248) (`imageRepository`) in the same way as possible for other manifests.

I think this can be worked around on by issuing a `kubectl set image` after kubeadm has deployed the CoreDNS manifest.

**Comment by luxas** [comment]
@praseodym Yes. Can you please send a docs PR to fix this?

**Comment by praseodym** [comment]
Sure thing: https://github.com/kubernetes/website/pull/8574
