### ISSUE TITLE
Prepull images already in preflight checks

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#825]
Following up on https://github.com/kubernetes/kubeadm/issues/812, we should investigate what it takes to try to prepull all required images already in preflight checks, and fail fast if the CRI daemon can't (lets say you're behind some proxy that is misconfigured or similar).

/assign @chuckha

**Comment by chuckha** [comment]
I started this last week and got pulled off. There's a fun import cycle when implementing this. Util package imports something it shouldn't imo.

**Comment by luxas** [comment]
Ok LMK on Slack if you need help resolving that.
What I forgot to mention is that it should check for presence of the image(s) first so it works well in airgapped envs.
