### ISSUE TITLE
kubeadm can not recognize the proxy format with username and password

### ISSUE THREAD

**Issue by ylhyh** [kubernetes/kubeadm#828]
## Versions
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **Kernel** (e.g. `uname -a`):
Linux upro-centos-01 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:
**docker version**:

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-58.git87f2fab.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      87f2fab/1.13.1
 Built:           Fri May 11 14:30:13 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-58.git87f2fab.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      87f2fab/1.13.1
 Built:           Fri May 11 14:30:13 2018
 OS/Arch:         linux/amd64
 Experimental:    false

## What happened?
Throw below error when execute kubeadm init:
kubelet[2160]: E0517 09:46:29.596445    2160 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed pulling image "k8s.gcr.io/pause-amd64:3.1": Get https://k8s.gcr.io/v1/_ping: invalid proxy URL port "[password]"

## What you expected to happen?
initialize k8s environment success 

## How to reproduce it (as minimally and precisely as possible)?
The host behind in a corporate proxy, and the proxy require username and password, so i configured http_proxy env variable in docker drop-in file:
http_proxy=http://[username]:[password]@[proxyhost.com]:8080/

## Anything else we need to know?
kubeadm couldn't recognize the proxy format with username and password like this:
http://[username]:[password]@[proxyhost.com]:8080/
it consider the content after ':' as "port".

**Comment by ylhyh** [comment]
hi, there is a special character '#' in my password, after i changed it to %23, it works now. I don't know if it is a bug, but the character '#' works in system environment variables.

**Comment by stewart-yu** [comment]
IMO, it's not  problem of `kubeadm`. If you setting the same proxy in local, can you run `docker pull <imagename>:<tagversion>` in your Env? @ylhyh

**Comment by ylhyh** [comment]
Yes, it should not the problem of kubeadm, docker pull has the same issue. 
I think the special character should be encoded in the proxy config in docker. issue closed.

@stewart-yu, @timothysc
