### ISSUE TITLE
Add e2e regression tests for the kubelet being secure

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#838]
As part of https://github.com/kubernetes/kubeadm/issues/732, https://github.com/kubernetes/kubeadm/issues/650 and https://github.com/kubernetes/kubernetes/pull/63881 we should make sure the following things in our end-to-end testing:
1. The kubelet cAdvisor port (4194) can't be reached, neither via the API server proxy nor directly on the public IP address
2. The kubelet read-only port (10255) can't be reached, neither via the API server proxy nor directly on the public IP address
3. The kubelet can delegate ServiceAccount tokens to the API server
4. The kubelet's main port (10250) has both authentication (should fail with no credentials) and authorization (should fail with insufficient permissions) set-up

These e2e tests, which I preliminarily propose to host under `[sig-cluster-lifecycle] [Feature:KubeletSecurity]`, would be run by any kubeadm e2e suite running against v1.11+ clusters.
These test are super important to make sure no kubeadm version regresses security-wise by accident.

@dixudx is working on creating these tests, thank you a lot!

FYI @kubernetes/sig-node-proposals @kubernetes/sig-auth-proposals

**Comment by tallclair** [comment]
I think the latter 2 tests should be under sig-auth. I'd also like to make the 4th one a conformance test eventually.

**Comment by luxas** [comment]
@tallclair Thanks, I'm very happy to move 3. and 4. directly under the `[sig-auth]` umbrella
I just proposed the sig-cluster-lifecycle thing in the meantime in case nobody wanted to own it :wink:

**Comment by luxas** [comment]
https://github.com/kubernetes/kubernetes/pull/64140 is up there and kind of ready, but it's not gonna make v1.11.0. Maybe (hopefully) a point release. In any case, retargeting this issue to v1.12
