### ISSUE TITLE
Drop dependency on `k8s.io/kubernetes/pkg/apis`

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#839]
Very similar to https://github.com/kubernetes/kubeadm/issues/806.
We only want kubeadm to depend on the external APIs `k8s.io/api/*` and client-go `k8s.io/client-go`, not the internal, duplicated representations which are `k8s.io/kubernetes/pkg/apis` and `k8s.io/kubernetes/pkg/client`.

@rosti any chance you could help us one more time here :smile:?
This is part of the effort to make kubeadm leaner in terms of binary size and dependencies needed to be vendored. The less the better. This will also make it easier to break kubeadm out of the monorepo eventually.
cc @dims @timothysc

**Comment by luxas** [comment]
Okay even though the bot doesn't let you be assigned (yet!) please do work on this :)

**Comment by rosti** [comment]
`k8s.io/kubernetes/pkg/apis` is pulled into kubeadm via 10 different routes. Most of these are transitive pulls, yet some are direct ones:

1. `k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm` depends on `k8s.io/kubernetes/pkg/kubelet/apis/kubeletconfig/v1beta1`, due to inheritance in [KubeletConfiguration](https://github.com/kubernetes/kubernetes/blob/a0036fcae173f299ffcb6038f9878ffe7ee1a51f/cmd/kubeadm/app/apis/kubeadm/types.go#L246) struct

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm
k8s.io/kubernetes/pkg/kubelet/apis/kubeletconfig/v1beta1
k8s.io/kubernetes/pkg/kubelet/qos
k8s.io/kubernetes/pkg/apis/core/v1/helper/qos

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm
k8s.io/kubernetes/pkg/kubelet/apis/kubeletconfig/v1beta1
k8s.io/kubernetes/pkg/kubelet/types
k8s.io/kubernetes/pkg/apis/core

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm
k8s.io/kubernetes/pkg/kubelet/apis/kubeletconfig/v1beta1
k8s.io/kubernetes/pkg/kubelet/types
k8s.io/kubernetes/pkg/apis/scheduling
```

2. [ipallocator.GetIndexedIP](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/constants/constants.go#L359) call in `GetDNSIP`

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/scheme
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha1
k8s.io/kubernetes/cmd/kubeadm/app/constants
k8s.io/kubernetes/pkg/registry/core/service/ipallocator
k8s.io/kubernetes/pkg/apis/core
```

3. [ValidateNodeName](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/preflight/checks.go#L411) call in `(hc HostnameCheck) Check()`

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation
k8s.io/kubernetes/cmd/kubeadm/app/util
k8s.io/kubernetes/cmd/kubeadm/app/preflight
k8s.io/kubernetes/pkg/apis/core/validation
```

4. [ValidateDNS1123Subdomain](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L294) called by `ValidateNetworking`

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation
k8s.io/kubernetes/pkg/apis/core/validation
```

5. [GetHostName](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L314) called in `ValidateNodeName`

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation
k8s.io/kubernetes/pkg/util/node
k8s.io/kubernetes/pkg/apis/core
```

6. [RBAC](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo/clusterinfo.go#L86)

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo
k8s.io/kubernetes/pkg/apis/rbac/v1
```

7. [RBAC](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/phases/kubelet/kubelet.go#L157)

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubelet
k8s.io/kubernetes/pkg/apis/rbac/v1
```

8. [DetachedTokenIsValid](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/discovery/token/token.go#L95) in `RetrieveValidatedClusterInfo`

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/discovery
k8s.io/kubernetes/cmd/kubeadm/app/discovery/token
k8s.io/kubernetes/pkg/controller/bootstrap
k8s.io/kubernetes/pkg/apis/core
```

9. [SecretTypeField](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/cmd/token.go#L267) in `RunListTokens`

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/pkg/apis/core
``` 

10. [LoadPodFromFile](https://github.com/kubernetes/kubernetes/blob/080739a12a25bc1f13f5d96b592c69cdc50dee33/cmd/kubeadm/app/phases/selfhosting/selfhosting.go#L89) in `CreateSelfHostedControlPlane`

```
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/apis/core/v1/helper

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/apis/core

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/apis/core/install

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/apis/core/validation

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/scheduler/algorithm
k8s.io/kubernetes/pkg/apis/core

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/scheduler/algorithm
k8s.io/kubernetes/pkg/scheduler/schedulercache
k8s.io/kubernetes/pkg/apis/core/v1/helper

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/scheduler/algorithm
k8s.io/kubernetes/pkg/scheduler/schedulercache
k8s.io/kubernetes/pkg/scheduler/util
k8s.io/kubernetes/pkg/apis/scheduling

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/serviceaccount
k8s.io/kubernetes/pkg/apis/core

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/util/taints
k8s.io/kubernetes/pkg/apis/core

--------------------------------------------------------------------------------
k8s.io/kubernetes/cmd/kubeadm
k8s.io/kubernetes/cmd/kubeadm/app
k8s.io/kubernetes/cmd/kubeadm/app/cmd
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases
k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting
k8s.io/kubernetes/pkg/volume/util
k8s.io/kubernetes/pkg/volume
k8s.io/kubernetes/pkg/cloudprovider
k8s.io/kubernetes/pkg/controller
k8s.io/kubernetes/pkg/util/taints
k8s.io/kubernetes/pkg/apis/core/helper
```

**Comment by luxas** [comment]
Great, thank you very much for that detailed information @rosti!
I moved this to v1.12, as that is a fair bit of work. If you find smaller pieces to work on in order to make incremental progress, please send PRs towards this goal :+1: 
If you're unsure of how to remove some of the dependencies in particular, please ask for guidance here.

**Comment by rosti** [comment]
I agree with the milestone movement. Some of these will need to be done in the code bases of other SIGs and I am skeptical that all the PRs are going to be merged in time for June 5th.

**Comment by rosti** [comment]
Regarding cases 6 & 7 of my comment above (the RBAC cases), the `k8s.io/kubernetes/pkg/apis/rbac/v1` package is not very large and it has only dependencies that we actively use (yet no `k8s.io/kubernetes/pkg/apis` stuff).
Thus I don't think, that this package is worth the havoc of removing it (or reworking it). I suggest keeping it as is.
@luxas WDYT?

**Comment by timothysc** [comment]
@rosti - keep this open, or close?

**Comment by rosti** [comment]
I'll try to redo the tracking of dependencies some time later in this cycle and see how realistic this is. If it's not we can close it.

**Comment by timothysc** [comment]
booting to 1.14

**Comment by timothysc** [comment]
@rosti we should work with @detiber and folks working on clusterAPI to reduce the dep-graph as much as possible for 1.14.

**Comment by rosti** [comment]
@detiber are there any dependencies in particular, that CAPI folks want us to remove ASAP?

**Comment by chuckha** [comment]
The dep graph isn't really that bad when we pull in kubeadm types:

```
+[[projects]]
+  digest = "1:694796918b3fe258b1eebffafd7b155ab6850508051544c37e3920aedc4f30f7"
+  name = "k8s.io/kubernetes"
+  packages = [
+    "cmd/kubeadm/app/apis/kubeadm",
+    "cmd/kubeadm/app/apis/kubeadm/v1beta1",
+    "cmd/kubeadm/app/constants",
+    "pkg/apis/core",
+    "pkg/kubelet/apis/config",
+    "pkg/proxy/apis/config",
+    "pkg/registry/core/service/allocator",
+    "pkg/registry/core/service/ipallocator",
+  ]
+  pruneopts = "UT"
+  revision = "721bfa751924da8d1680787490c54b9179b1fed0"
+  version = "v1.13.3"
+
```

These are the only deps from k8s that we would be pulling in. We also pull in a few more apimachinery packages but we're already vendoring a lot of apimachinery.

@rosti I'll look through these and see if any can be easily removed or if the packages we're pulling in are huge, but at first glance this looks pretty good.

**Comment by dims** [comment]
@chuckha kubeadm itself does not look too good ( peeking at cmd/kubeadm/.import-restrictions ) right?

**Comment by chuckha** [comment]
@dims I'm not familiar with `.import-restrictions`. I just found import-boss and need to do some reading. Can you expand on your comment a bit further?

**Comment by chuckha** [comment]
Ah, you mean kubeadm the project, not just the types dep graph. Yes, we could probably prune some more dependencies from kubeadm. From my perspective though kubeadm is doing a good job since vendoring types does not result in a massive dependency graph. It would be cool to get rid of any more dependencies that we can, but the *types* from kubeadm api aren't so bad.

**Comment by neolit123** [comment]
@rosti do we want to do something here or move to next cycle?

**Comment by rosti** [comment]
I think, that one can safely be moved to the next cycle. If there is something urgent, that needs to be done for this cycle, it will be far smaller and probably related to CAPI needs.

**Comment by neolit123** [comment]
this is now tracked in the "import-boss" issue. we have ongoing PRs for a lot of "pkg/" items (see the linked google doc)
https://github.com/kubernetes/kubeadm/issues/1600
/close
