### ISSUE TITLE
kube-dns container not starting on CentOS 7

### ISSUE THREAD

**Issue by bjornl** [kubernetes/kubeadm#84]
Then setting up cluster on CentOS 7 using kubeadm the kube-dns container can not start due to it is not able to connect to the kubernetes-api IP address on the cluster network.

I1206 13:34:14.874445       1 dns.go:173] Ignoring error while waiting for service default/kubernetes: Get https://10.96.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.96.0.1:443: getsockopt: no route to host. Sleeping 1s before retrying.

**Comment by pires** [comment]
Which version are you using?

Also, can you provide `kube-proxy` logs on any node other than the master?

**Comment by bjornl** [comment]
@pires Closing this issue. This problem is solved with commit [https://github.com/kubernetes/kubernetes/commit/495ab24fb54e6807e0ab363d8a500f2b1c871752](https://github.com/kubernetes/kubernetes/commit/495ab24fb54e6807e0ab363d8a500f2b1c871752)
