### ISSUE TITLE
Set the kubelet `--cgroup-driver` flag conditionally at kubeadm init time for Docker

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#844]
When https://github.com/kubernetes/kubernetes/pull/63887 merges, we should set the kubelet's `--cgroup-driver` flag to either `systemd` or `cgroupfs` conditionally at kubeadm init time, in `cmd/kubeadm/app/phases/kubelet/flags.go`.

This instead of doing it statically in the deb/rpm packages.
xref related issue: https://github.com/kubernetes/kubeadm/issues/822

PR:
https://github.com/kubernetes/kubernetes/pull/64347

**Comment by filbranden** [comment]
@neolit123 I meant to work on something like that... But talking to @Random-Liu we noticed it was hard to support that since the Runtime (CRI) doesn't need to be up when kubelet starts and we would like to avoid blocking on the Runtime for kubelet startup...

We discussed a few alternative proposals, but we have nothing to show yet.

One possible alternative is to make the CRI the slave and kubelet the master for that attribute. (If kubelet sends the Runtime a systemd cgroup path, then Runtime also uses the systemd cgroup driver and vice-versa.) We might need some changes in libcontainer to do that... It should be feasible.

**Comment by neolit123** [comment]
@filbranden

> One possible alternative is to make the CRI the slave and kubelet the master for that attribute. (If kubelet sends the Runtime a systemd cgroup path, then Runtime also uses the systemd cgroup driver and vice-versa.) We might need some changes in libcontainer to do that... It should be feasible.

it's a complicated change and a long-term one, but i guess it would work!

> I meant to work on something like that... But talking to @Random-Liu we noticed it was hard to support that since the Runtime (CRI) doesn't need to be up when kubelet starts and we would like to avoid blocking on the Runtime for kubelet startup...

> We discussed a few alternative proposals, but we have nothing to show yet.

you have probably considered this already, but wouldn't the following be the easiest short-term solution that doesn't modify the current kubelet / CRI (master-on-slave) setup:
- add the `auto` parameter to kubelet's `cgroup-driver` argument
- if the CRI is running take it's cgroup driver
- if the CRI isn't running use `cgroupfs`

**Comment by filbranden** [comment]
The current way the code is laid out makes it tricky...

Even with docker-shim, it turns out there is code that depends on the cgroup driver setting that runs before the first connection to docker-shim is made... So it's actually quite a big refactor. That's when I started talking to @Random-Liu about this and we looked at the other shortcomings of the approach.

Agreed, having CRI runtimes do both cgroup drivers (and have the request from kubelet decide) is a long term project, it's gonna take a while...

**Comment by neolit123** [comment]
@filbranden 
understood, i was almost sure that there is a catch here, otherwise `auto` would have easily made it as the default option. thank you for the detailed explaination!

**Comment by neolit123** [comment]
@luxas what do you have in mind for the detection of the CRI driver at kubeadm runtime?

something like this would fetch it:
```
docker info | grep -i cgroupfs
```
but it's a command line and only for docker...

**Comment by luxas** [comment]
We expect the CRI to be running at the time kubeadm is running. Can you query the CRI runtime for that information for the general case or just query `docker info` or similar for the special case?

**Comment by neolit123** [comment]
> Can you query the CRI runtime for that information for the general case

should that be done `crictl`?

> or just query docker info or similar for the special case?

could you elaborate on `general case` vs `special case`.
i'm sorry for the silly questions.

**Comment by filbranden** [comment]
You might find this interesting too!

https://github.com/filbranden/community/blob/009f067c6bc106d062a416d0a1537de5ffa8c023/contributors/design-proposals/node/cgroup-driver-kubelet-and-runtime.md

Cheers,
Filipe

**Comment by neolit123** [comment]
@filbranden 

thanks for the details! i will have a look at this tomorrow:

https://github.com/filbranden/community/blob/009f067c6bc106d062a416d0a1537de5ffa8c023/contributors/design-proposals/node/cgroup-driver-kubelet-and-runtime.md

> That's also part of the problem... CRI doesn't really have an official way to expose that either...
> When I checked cri-o, it doesn't have anything like that...

> So if you want to query it, you might need to add some more support in CRI to export that... (Perhaps the Status request is the appropriate place... just might need an explicit proto field to export that, and update existing implementations.)

oh, well. i'm not exactly sure how we can proceed with this for 1.11.
@luxas what do you think about the outlined complication?

**Comment by luxas** [comment]
hmm, let's do this _only for docker_ then. So if the CRISocket is dockershim, check `docker ps` output or whatever to determine what to use. We _really_ need this for docker in the general case, otherwise all our rpm-based installations fail.
@neolit123 seems legit to do this?

**Comment by stealthybox** [comment]
available since 1.13
```bash
$ docker system info -f '{{.CgroupDriver}}'
cgroupfs
```

**Comment by neolit123** [comment]
**NOTE:** keeping this issue for the rest of the CRI.

**Comment by luxas** [comment]
@neolit123 Would you be okay with keeping this in the v1.11 milestone to track what's needed for v1.11 and then open a new to track the rest of the CRI work in order to not change purpose midterm?

**Comment by neolit123** [comment]
@luxas ok!
