### ISSUE TITLE
[Feature Request] upgrade from k8s version A to B using kubeadm

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubeadm#85]
saying i have used kubeadm to setup a cluster with kubernetes version 1.4.6 . after a few months later, kubernetes 1.5.x stable version is out, i'd like use kubeadm to upgrade my cluster to kubernetes 1.5.x.
i suggest a subcommand : `kubeadm upgrade 1.5.0` , 1.5.0 is the target kubernets version.

**Comment by kad** [comment]
Duplicate to #14
