### ISSUE TITLE
Create a KEP for the kubeadm-kubelet integration

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#851]
Create a KEP for https://github.com/kubernetes/kubeadm/issues/822
We also need to finally decide whether to embed the kubelet ComponentConfiguration in our config or if we should just do `kubeadm init --config kubeadm.yaml --kubelet-config kubelet.yaml --kube-proxy-config kubeproxy.yaml ...` for all components as the end goal.

cc @mtaufen @timothysc

**Comment by mtaufen** [comment]
Or even just:

kubeadm --config path

If path=dir, Kubeadm should be able to figure out which object is for which
component based on group/kind. Same for path=yaml file with multiple
objects in it.

**Comment by luxas** [comment]
Or we could just say our config file can look like this:
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
...
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
...
---
apiVersion: kubeproxy.config.k8s.io/v1beta1
kind: KubeProxyConfiguration
...
```

@timothysc @fabriziopandini @mtaufen WDYT?

**Comment by luxas** [comment]
Also xref related: https://github.com/kubernetes/kubeadm/issues/847

**Comment by fabriziopandini** [comment]
+1 to 
> If path=dir, Kubeadm should be able to figure out which object is for which
> component based on group/kind. Same for path=yaml file with multiple
> objects in it (allowing multiple object in a file without forcing it)

**Comment by timothysc** [comment]
This is already in, so closing imo.
