### ISSUE TITLE
kubeadm fails after v1.12.0-alpha.0 tag was added to the repository

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubeadm#853]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

Move kubernetes/kubernetes#64241 for better tracking.

**Comment by dixudx** [comment]
```
kubelet version: &version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.307+481b2dc7cf50d8-dirty", GitCommit:"481b2dc7cf50d8698166c0a78c6bf81410cbf226", GitTreeState:"dirty", BuildDate:"2018-05-24T09:36:33Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

This is because the version of the binaries will become `v1.12.0-alpha.0.307+481b2dc7cf50d8-dirty`, which are not supported by current kubeadm. 

```
I0523 10:03:06.408780     579 init.go:254] [init] using Kubernetes version: v1.10.0
I0523 10:03:06.408805     579 init.go:256] [preflight] running pre-flight checks
    [WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
    [WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
I0523 10:03:06.446429     579 kernel_validator.go:81] Validating kernel version
I0523 10:03:06.446566     579 kernel_validator.go:96] Validating kernel config
    [WARNING KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.12.0-alpha.0.253+23d9a48e6a59bc" Control plane version: "1.10.0"
[kubelet] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
```

Although the control plane version is still v1.10.0, but kubelet version is `"1.12.0-alpha.0.253+23d9a48e6a59bc"`, which is larger than `MinimumKubeletConfigVersion = version.MustParseSemantic("v1.11.0-alpha.1")`.

@ivan4th So when running `kubeadm join`, it will try to download the configmap. But related clusterrolebinding has never been created. That's why configmaps `"kubelet-config-1.12"` is forbidden.

**Comment by ivan4th** [comment]
I confirm that setting `kubernetesVersion` to 1.12.0 in kubeadm config fixes the issue now. I thought that setting only affects the version of the control plane image to pull and in case if `unifiedControlPlaneImage` is updated it's only used for some checks, but turns out I was wrong.

Please close this issue. Thanks!
