### ISSUE TITLE
Improve logging on kubeadm reset for external etcd

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#859]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
v1.10.3

## What happened?
I ran kubeadm reset with an external etc and got this message:
[reset] No etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml". Assuming external etcd.                     

## What you expected to happen?
I would expect it to tell me that i need to manually go and reset etcd. The implication should be made explicit.

**Comment by stealthybox** [comment]
Interesting -- does kubernetes pick up where it left off if you re-init against etcd?
If so, we should ensure that the message expresses that this is optional.

**Comment by seh** [comment]
Note that [the _kubeadm reset_ documentation does mention this need](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/#external-etcd-clean-up), but that takes nothing away from the validity of your request for improvement here.

**Comment by timothysc** [comment]
I'm punting out of 1.11 will be fixed in 1.12.

**Comment by stealthybox** [comment]
I'll mention again that it's important to express this is an optional step.
It's only necessary if you want to return to a completely clean state.

The existing docs @seh linked imply that kubernetes may be functional re-initializing against an existing etcd. This may be exactly what the user wants to do.

**Comment by carl-danley-heptio** [comment]
@stealthybox Any recommended word-smithing this then?

**Comment by carldanley** [comment]
@stealthybox Any recommended word-smithing this then?
