### ISSUE TITLE
--service-cidr should set route to gateway

### ISSUE THREAD

**Issue by bronger** [kubernetes/kubeadm#86]
If you set the kubeadm option `--service-cidr`, you probably have to set manually the route for this IP range to an interface on the system (and, in a way that survives reboots).  In my opinion this should be done by kubeadm.  For example, on an `nmcli`-based system (RedHat), it is

    nmcli connection modify {connection_name} +ipv4.routes {service_cidr}
    systemctl restart network.service

**Comment by kad** [comment]
service-cidr should not be really routable. kube-proxy handles intercepts for used ClusterIPs in the service-cidr range so it redirects on each node of the cluster to right pod IP.

**Comment by bronger** [comment]
Setting the route was recommended to me by Adam Harrison (Weaveworks) [on the Weave mailinglist](https://groups.google.com/a/weave.works/d/msg/weave-users/-JWHW_jAXNM/doESmljBBQAJ).  However this was in the context that I have two interfaces on each node, one for the Internet and one for the internal network, so maybe he recommended it only to make sure that the services traffic uses the internal network.

I find this necessity odd, too.  I would have thought that the service IP reaches the local kubelet via iptables, and the kubelet forwards the traffic to the pod IP directly.  In other words, the service IP is not used *between* nodes, only *within* nodes.  But still, I must say `ip route add {service_cidr} dev {interface}` so that services also work across nodes.

**Comment by kad** [comment]
Interesting. I'll try to replicate that use case in my lab.
Out of curiosity, without route, what do you have in your iptables on the node which can't reach service IPs ? and what is the status if weavenet on each node ?

**Comment by bronger** [comment]
I'm sorry but even after hours of tests – despite HDD snapshots and detailed Git history – I cannot reproduce it anymore.  Thus, I close it and re-open it if I'm haunted by this “service partition” again.
