### ISSUE TITLE
Deprecating testing infra for v1.8

### ISSUE THREAD

**Issue by hh** [kubernetes/kubeadm#863]
Separating out from kubernetes/kubeadm#819 kubernetes/test-infra#8142

**Comment by luxas** [comment]
We can do this when v1.11 is released.

**Comment by luxas** [comment]
You can always already send the PR though ;)

**Comment by neolit123** [comment]
today we had a discussion about what old kubeadm jobs to remove.
i will file a PR for this later today or tomorrow.

**Comment by timothysc** [comment]
closing
