### ISSUE TITLE
Use hpa to cause the controller-manager to run down

### ISSUE THREAD

**Issue by hppx5456** [kubernetes/kubeadm#864]
i want use hpa in my cluster 
when i add --horizontal-pod-autoscaler-use-rest-clients=true into kube-controller-manager.yaml
i see  my kube-controller-manager-master is stop
when i delete -horizontal-pod-autoscaler-use-rest-clients=true
Business as usual

**Comment by neolit123** [comment]
@hppx5456 please, answers some of the questions here, which will help us more:
https://github.com/kubernetes/kubeadm/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by timothysc** [comment]
closing due to lack of feedback.
