### ISSUE TITLE
Remove usage of `PersistentVolumeLabel` in phases/controlplane/manifests*.go

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#866]
This PR added usage of `--disable-admission-plugins=PersistentVolumeLabel` as an APIServer argument:
https://github.com/kubernetes/kubernetes/pull/64165
https://github.com/kubernetes/kubernetes/pull/64165/files#diff-366b1adfb12059a0ddf31d524e8827cbR145
it was done because we need to support 1.10 and because `--admission-control` is deprecated.

TODO (do this on a later stage in 1.11, not now)
remove `PersistentVolumeLabel` as it's will be automatically disabled in v1.11:

references:
kubernetes/kubernetes#64326
kubernetes/kubernetes#52618
kubernetes/kubernetes#52617

**Comment by xlgao-zju** [comment]
/assign 
@neolit123 I'd like to help this.

**Comment by neolit123** [comment]
sounds good!
thank you @xlgao-zju
