### ISSUE TITLE
document the process of bumping test-infra on each release

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#868]
we need to document the process of adding new e2e jobs/ tests for a new release and removing older tests:

issue for 1.11:
https://github.com/kubernetes/kubeadm/issues/819

proposal:

> i suggest we extend this README.md:
https://github.com/kubernetes/kubeadm/tree/master/tests/e2e

> title the whole document E2E tests for kubeadm
move Tools for verifying Kubernetes packages are published into a sub-section
include another section that can outline some of the steps in the video you guys did:
https://www.youtube.com/watch?v=aTGbdPU0fE8

/assign @neolit123
/assign @hh

cc @luxas

**Comment by timothysc** [comment]
Umm I want to burn some of this in 1.12, so when we plan for that cycle lets talk.

**Comment by neolit123** [comment]
/lifecycle active

i have a doc in the works for this.
will update once we have this PR merged:
https://github.com/kubernetes/test-infra/pull/9219
