### ISSUE TITLE
kubeadm cannot specify ControlPlaneEndpoint when do init

### ISSUE THREAD

**Issue by adohe** [kubernetes/kubeadm#872]
fyi. When use `kubeadm init`, I would hope that I can specify a stable IP address of DNS name for control plane.

**Comment by neolit123** [comment]
hi, could you please fill this issue report as described in our issue template:
https://github.com/kubernetes/kubeadm/blob/master/.github/ISSUE_TEMPLATE.md

more details are needed. thanks.

**Comment by adohe** [comment]
@neolit123 what I mean is that I cannot specify `ControlPlaneEndpoint` when run `kubeadm init`.

**Comment by neolit123** [comment]
@adohe 

your report is missing **detail**. please, answer the following questions or we are going to have to close the issue. thanks for understanding. :)

* which k8s version is that?
* is this an HA cluster?

we have `ControlPlaneEndpoint` in the latest kubeadm config:
https://github.com/stevesloka/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/types.go#L147

* ^ isn't that working for you?

**Comment by adohe** [comment]
@neolit123 I am using Kubernetes 1.10, sure it's an HA cluster, and that's why I wan to use `ControlPlaneEndpoint`, I did notice we have this in our kubeadm config, but I don't find how to specify this through command arguments.

**Comment by neolit123** [comment]
@adohe 
you should use the config for this as there are no command line arguments for it, as far as i know.

but also please, have a look at this:
https://github.com/kubernetes/kubeadm/issues/726

**Comment by adohe** [comment]
@neolit123 see ur point~ I will take a look at the HA proposal, thanks very much!

**Comment by zhujintao** [comment]
Please refer to this https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2
