### ISSUE TITLE
remove the docker cgroup driver detection

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#874]
#### old issue was tracking cgroup driver detection for docker and other CRs

this is targeting 1.22.

remove the docker cgroupdriver detection in kubeadm:
- [x] k/k PR:
https://github.com/kubernetes/kubernetes/pull/99647

- [x] k/website PR:
sent website PR to update these pages after the change:
https://github.com/kubernetes/website/blob/281df0c16b0ce403bfa1442388794c13fbcc9d27/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
https://github.com/kubernetes/website/blob/253d6ab66db2972a0af21c27af77458fe3a841f9/content/en/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
https://github.com/kubernetes/website/blob/cfe5edfd3112bc4e94160dc09fedd4900ea14608/content/en/docs/setup/production-environment/container-runtimes.md
https://github.com/kubernetes/website/blob/401c4fc0fae978d73894418a710b14c5a0474098/content/en/docs/tasks/administer-cluster/reserve-compute-resources.md

- [x] pin the cgroup driver for docker / containerd to "systemd" in kinder. should be done [here](
https://github.com/kubernetes/kubeadm/blob/daf8cabc4ed98f90a1adc5a7251a629e9874eb03/kinder/pkg/build/alter/alter.go#L280); information about setting the driver for CRs is [here](https://kubernetes.io/docs/setup/production-environment/container-runtimes/)
https://github.com/kubernetes/kubeadm/pull/2495

--------------------
old description:

this was already done for docker:
https://github.com/kubernetes/kubeadm/issues/844

> When kubernetes/kubernetes#63887 merges, we should set the kubelet's --cgroup-driver flag to either systemd or cgroupfs conditionally at kubeadm init time, in cmd/kubeadm/app/phases/kubelet/flags.go.
This instead of doing it statically in the deb/rpm packages.
xref related issue: #822

we need to detect the driver for other CRI as well.

Docker PR:
kubernetes/kubernetes#64347

Document outlining some of the previous proposals and issues for handling this in the kubelet:
https://github.com/filbranden/community/blob/009f067c6bc106d062a416d0a1537de5ffa8c023/contributors/design-proposals/node/cgroup-driver-kubelet-and-runtime.md

**Comment by neolit123** [comment]
/lifecycle frozen
until there is a way to ingrate detection for other CRI.

**Comment by timothysc** [comment]
@neolit123 @kad  - any update on this one ? 
If @rosti is updating the CRI detection we should address this as well for 1.13. 
Thoughts?

**Comment by neolit123** [comment]
AFAIK, it's not possible to detect a cgroup driver using crictl, yet.

for docker we probe the output of the CLI. other CRIs don't allow that TMK and we need to parse configs.

ideally this should be in the kubelet:
https://github.com/filbranden/kubernetes-community/blob/009f067c6bc106d062a416d0a1537de5ffa8c023/contributors/design-proposals/node/cgroup-driver-kubelet-and-runtime.md

cc @Random-Liu @filbranden @bart0sh

**Comment by kad** [comment]
I agree with @neolit123 here. There is no at the moment good way to reliably detect correct driver.
I would probably go the way of parsing `cgroupfs` and trying to guess based on slice names... but that will be just good enough guess and not a 100% solution.

**Comment by timothysc** [comment]
@neolit123 want to re-eval for 1.14 cycle?

**Comment by neolit123** [comment]
@timothysc i don't see us finding a good solution for this in the next few cycles.
i think the ecosystem should default to the `cgroupfs` driver instead of us trying to fix it.

some stats:
according to our survey 30% of the user base are using non-docker.

- 1/3 of those are using CRI-O and are safe because it defaults to `cgroupfs` - the same as the kubelet.
so if they change the driver for some reason, they are on they own. but we can still try to detect it and parse the `crio.conf`.
- 1/3 are using containerd. no idea how to detect what is uses.
- 1/3 are using other runtimes. we can't handle all of them.

**Comment by rosti** [comment]
We may want to try to tackle this in 1.15.

As part of the manual testing that I did for #1495, I found out that the instructions for CRI-O on Ubuntu [here](https://kubernetes.io/docs/setup/cri/#cri-o) aren't up to date.
First, I had some problem installing the 1.11 package and I installed CRI-O 1.13 instead. In it, the cgroups driver was set to `systemd`. As kubelet is defaulted to `cgroupfs`, it didn't work out of the box, requiring me to manually override it via `kubeletExtraArgs`.

We should verify that, but it seems to me, that most packages targeting systemd based Linux distros are moving to defaulting the cgroup driver to `systemd`. If that's true we may want to try the same.

The other option is to continue adding detection code for the most popular CRIs out there and document a way of overriding it in the kubelet (via the config).

**Comment by neolit123** [comment]
> As part of the manual testing that I did for #1495, I found out that the instructions for CRI-O on Ubuntu here aren't up to date.

the docs there say:
> To use the systemd cgroup driver, set plugins.cri.systemd_cgroup = true in /etc/containerd/config.toml. 

is this not actual?

> When using kubeadm, manually configure the cgroup driver for kubelet as well.

this does not explain how to do it very well, but the link is here:
https://kubernetes.io/docs/setup/independent/#configure-cgroup-driver-used-by-kubelet-on-master-node

(not using the config).

> it didn't work out of the box, requiring me to manually override it via kubeletExtraArgs.

the question is how to automatically detect it. should we parse `/etc/containerd/config.toml`?
is it safe long term?

> We should verify that, but it seems to me, that most packages targeting systemd based Linux distros are moving to defaulting the cgroup driver to systemd. If that's true we may want to try the same.

it's rather sparse. docker defaults to cgroupfs and the kubelet has no plans to do the detection anytime soon or to move from it's default of cgroupfs.

> The other option is to continue adding detection code for the most popular CRIs out there and document a way of overriding it in the kubelet (via the config).

the manual setup is documented here:
https://kubernetes.io/docs/setup/independent/#configure-cgroup-driver-used-by-kubelet-on-master-node

the auto-detection for containerd and cri-o is under question - e.g. "what is the best way".

**Comment by timothysc** [comment]
IMO this should really be an output variable of cri-tools.

**Comment by chenzhiwei** [comment]
For CRI-O, I asked this question in crio, and I think in the meantime we can get it from `/etc/crio/crio.conf`, the section is `cgroup_manager = "systemd"`.

**Comment by chenzhiwei** [comment]
According to https://github.com/cri-o/cri-o/pull/2416#issuecomment-496841562

```
> sudo curl -s --unix-socket /var/run/crio/crio.sock http://localhost/info | jq
{
  "storage_driver": "btrfs",
  "storage_root": "/var/lib/containers/storage",
  "cgroup_driver": "cgroupfs",
  "default_id_mappings": {
    "uids": [
      {
        "container_id": 0,
        "host_id": 0,
        "size": 4294967295
      }
    ],
    "gids": [
      {
        "container_id": 0,
        "host_id": 0,
        "size": 4294967295
      }
    ]
  }
}
```

**Comment by neolit123** [comment]
@chenzhiwei
nice, this is something we can look at for 1.16.
but we shouldn't use `curl/jq` and possibly try `net.Dial("unix", " /var/run/crio/crio.sock")` + `encoding/json` 
instead.

also, is there something similar for containerd?

**Comment by chenzhiwei** [comment]
@neolit123 I will work on this after my PR https://github.com/kubernetes/kubernetes/pull/77059 is merged.

Will try to check with containerd team about this, I can't find it on google or containerd website.

**Comment by villasenor** [comment]
Now that we are [encouraging the use of fully CRI-compliant runtimes](https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/), it might be time to implement this. Even if the Dockershim is maintained and provides a CRI-compliant interface, making it easy to use CRI-O or containerd during `kubeadm init` should be a priority. The current documentation on setting the cgroupDriver during `init` is sparse, so I can try to work on that, but would be good to have a helping hand during `init` programmatically as well.

**Comment by neolit123** [comment]
this is still problematic - doable but not maintainable as a layer in kubeadm. different container runtimes place their configuration in different locations, behind different tools and endpoints. so unless we have something consistent like `curl -s --unix-socket <some socket> http://localhost/info` i'm leaning towards not managing this in kubeadm.

`crictl info` exists nowadays https://github.com/cri-o/cri-o/issues/2414#issuecomment-496833983
but i see it only prints conditions and the `CgroupManager` type is not always present.

instead we could always default the kubelet configuration field (cgroupDriver) to `systemd` and tell users to setup their container runtime to the same value, because that is the one they should be using regardless:

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers

**Comment by villasenor** [comment]
@neolit123 I agree, pushing for the default to be `systemd` for the cgroupDriver in the kubelet and kubeadm, adding an optional flag/struct option for override to `cgroupfs` in kubeadm, and adding a pre-flight check during `kubeadm init` (if override isn't set) might be the best solution here. What are the next steps to get this going?

**Comment by neolit123** [comment]
> adding an optional flag/struct option for override to cgroupfs

this is already possible via the KubeletConfiguration field during "kubeadm init".

> and adding a pre-flight check during kubeadm init

a preflight check to tell the user that "cgroupfs" is not recommended if they used the override?

> What are the next steps to get this going?

1.20 is in code freeze, but we can try making these changes in 1.21.

**Comment by villasenor** [comment]
Sorry, new to this and probably could have been more clear!

> this is already possible via the KubeletConfiguration field during "kubeadm init".

Right, yes!

> a preflight check to tell the user that "cgroupfs" is not recommended if they used the override?

No, I meant a pre-flight check that ensures users are using `systemd`. If the user is not using `systemd`, we can say something like "It looks like you're not using the systemd cgroupDriver (default). Please switch to using systemd as your cgroupDriver, or override with a KubeletConfiguration field to use cgroupfs"

> 1.20 is in code freeze, but we can try making these changes in 1.21.

Sounds good! Hopefully this helps some people going forward :)

**Comment by neolit123** [comment]
changing OP and description

/retitle remove the docker cgroup driver detection

**Comment by neolit123** [comment]
the OP now includes details on how you can help us with removing this detection.

**Comment by neolit123** [comment]
this work is done.
