### ISSUE TITLE
Allow overriding the version enforcement with --force

### ISSUE THREAD

**Issue by liztio** [kubernetes/kubeadm#877]
Right now, because of bugs we've encountered in the past, we only allow upgrading to kubernetes 1.x.? with a kubeadm also versioned 1.x. This avoids some issues associated with kubeadm serialising structs in ways that are possibly incompatible, but it makes certain kinds of testing more difficult.

Pros:
* Easier testing of upgrades and downgrades
* Lets power users manually change configuration

Cons:
* Bad configuration could put kuberentes/kubeadm in an unknown state
* Error messages are unlikely to be helpful or useful
* More testing surface

**Comment by timothysc** [comment]
In general, I'm a plus +1 on letting power users blast their own foot off.
