### ISSUE TITLE
Inconsistent logging during kubeadm init

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#883]
## Is this a BUG REPORT or FEATURE REQUEST?
FEATURE REQUEST

During `kubeadm init` we call out to two places in the code that use bare glog logging. Since we do not log with this style, we end up with some glog output in the middle of our nice output without the prefix.

There is no way to remove the prefix in glog logging.

The two calls are

[test/e2e](https://github.com/kubernetes/kubernetes/blob/1635393bd1cb21e82fbc899ce7fd6a997194abe2/cmd/kubeadm/app/preflight/checks.go#L540) and the [kubelet](https://github.com/kubernetes/kubernetes/blob/1635393bd1cb21e82fbc899ce7fd6a997194abe2/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L460)

**Comment by Klaven** [comment]
can I take this one?

**Comment by neolit123** [comment]
@Klaven is working on this. :tada: 

please ask questions that you may have to me or @chuckha about this.
thanks.

**Comment by Klaven** [comment]
@neolit123 or @chuckha 
There are other cases of glog being used in kubeadm like the one here:
https://github.com/kubernetes/kubernetes/blob/be11540775e36b1f1acdd6cb43500c1717af0ad4/cmd/kubeadm/app/util/system/kernel_validator.go#L255

Do you want me to try and fix as many as I can find? or just the ones that log improperly on init during a "standard"/"successful" init?

Is `[kernelvalidator]` or `[preflight/kernel]` the right "tag" for there? Using `preflight` felt wrong as the kernel validator could be used in other things then preflight checks but does not currently look like it is. That being said `[preflight/kernel]` matches `[preflight/images]`.

**Comment by neolit123** [comment]
@Klaven 
sorry for the delay. too many things.

i'm currently investigating what is best to do here.

**Comment by neolit123** [comment]
@Klaven 
so digging a little i find only a couple of potential issues:

```
$cd cmd/kubeadm/app
$ grep "glog.Info" * -rnI
cmd/join.go:329:		glog.Infoln("[join] running pre-flight checks before initializing the new control plane instance")
util/system/validators.go:44:		glog.Infof("Validating %s...", v.Name())
```

the original links in the OP seem out of date.
the idea would be to only remove `glog.Info` or `glog.Infof` calls because these mix with our standard output.

1) please start as a PR changing the above two calls to `fmt.Println` / `fmt.Printf`.
2) start `kubeadm init` and see if you get output such as:
```
I0905 18:59:00.337035    4195 kernel_validator.go:81] Validating kernel version
I0905 18:59:00.337255    4195 kernel_validator.go:96] Validating kernel config
```
for non-errors.

`I0905 18:59:00.337255` is the kind of output from glog that we don't want unless there is an error or a warning or if verbosity is enabled `glog.V(x > 0)....`

LMK if you have any further questions. :+1:

**Comment by Klaven** [comment]
@neolit123 I think I have done everything needed for the above. Please let me know if there is more I need to do! Please let me know if I missed any step.
https://github.com/kubernetes/kubernetes/pull/68455
I tried to assign it too you :) but I don't think it lets me.
Thanks for your help getting me into the project!

**Comment by Klaven** [comment]
I am not sure if I screwed this up linking it, but this ticket still says it is open, and the PR was merged.
Here is the link to the PR:
https://github.com/kubernetes/kubernetes/pull/68455
Thanks!

**Comment by neolit123** [comment]
thanks
/close
