### ISSUE TITLE
Provide the users with a filtered list of know bugs / workarounds

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#886]
@detiber made a good proposal at Slack:
> We should probably have a link to a query in the docs to list bugs that affect the current release that will be fixed in the upcoming release, and make sure that we clearly document the workaround in the github issues.

We can have some links under a `Known bugs` section here:
https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/

there could be links that filter the `k/kubeadm` issue list by a set of (new) labels, that indicate to the users that we know about certain bugs and that there are workarounds for them, until we fix them.

Link titles:
- Known bugs in the current version
- Known bugs in the current version with workarounds
- Known bugs in previous versions
- Known bugs in previous versions with workarounds

suggestions for query labels and status:
- the issue should be open
- label: `kind/bug`
- label: `kind/bug-latest-release` (new)
- label: `has-workaround` (new)

please, share your thoughts:
@kubernetes/sig-cluster-lifecycle-misc

**Comment by timothysc** [comment]
@detiber @liztio  Rolling this into a single larger group copy edit issue #896 closing this issue and rally there.
