### ISSUE TITLE
Additions to trouble shooting guide. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#887]
This issue is a parent catch all for items that need to be updated in the kubeadm troubleshooting documentation listed here - https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/ 

1. With modifications from 1.10 Config there are a number of args that no longer will apply on 1.11 and we should outline a path for folks to migrate to using extra-args.  I highly recommend enumerating the 1.10 vs. 1.11 list.  IMO providing a link to a gocdoc based config is easier to maintain and cleaner to parse. 

2. Outlining common knobs that folks will need to based on 1.11 issues that feed into "Extra - args" 

3. Audit the existing troubleshooting guide. 

4. Solicit the slack channel on common known trouble-shooting scenarios.

**Comment by timothysc** [comment]
Cloud provider integration ..? 
/cc @detiber @Bradamant3

**Comment by neolit123** [comment]
this has to go under the Troubleshooting guide:
https://github.com/kubernetes/kubeadm/issues/886

folks ideally should comment on the proposed labels and links.
(the links are static and will not change over time as long as we don't change the labels).

**Comment by timothysc** [comment]
Rolling this into a single larger group copy edit issue https://github.com/kubernetes/kubeadm/issues/896  closing this issue and rally there.
