### ISSUE TITLE
preflight check suggestions

### ISSUE THREAD

**Issue by bruceauyeung** [kubernetes/kubeadm#89]
1. `PreFlightError` and `PreFlightCheck` better be renamed to `Error` and `Checker` seperately, otherwise these will be used as `preflight.PreflightError` and `preflight.PreFlightCheck`, that stutters.
2. i noticed `RunRootCheckOnly` is added to make sure preflight checks fail fast when user is not running as root. but i think it's better to add a method named `failOnError` into `PreFlightCheck` interface, then we can fail fast any check in `RunChecks` while it returning an error.
3. currently an extra redundant `IsRootCheck` is run in `RunInitMasterChecks`, if we add  `failOnError`, this can be fixed gracefully.

**Comment by dmmcquay** [comment]
I took care of option 1 here: https://github.com/kubernetes/kubernetes/pull/39495

**Comment by luxas** [comment]
ok, this is fixed then
