### ISSUE TITLE
1.11 Copy edits to Setup: "Using kubeadm to Create a Cluster"

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#894]
Instead of dozens of issues we will collect updates and do bulk PRs to content areas. 

https://docs.google.com/document/d/11irKjRDqHCP38WtMt3j2ZjDB0VtgNHGdf5RIlVOLhuc/edit#heading=h.z7o9rstbcxog

**Comment by timothysc** [comment]
This page should really be: "Creating a single master cluster with kubeadm"

**Comment by Bradamant3** [comment]
We can change the title, that's fine :-)

I've done fairly substantial copyediting/reorganizing up to the example output. I've added some questions there that affect what I do with the rest of the Initializing content.

**Comment by timothysc** [comment]
PRs for this one are posted.

**Comment by timothysc** [comment]
Merged, and other pieces will be merged after release.

**Comment by timothysc** [comment]
This one has been merged.
