### ISSUE TITLE
1.11 Copy edits to Setup: "Creating HA clusters with kubeadm" 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#895]
Make edits on someone on this team submit the PR. 

https://docs.google.com/document/d/1GFkc9rPQG2YMsMlEgGrXzJxkP2BMFcghMinet_QyyKM/edit#heading=h.opcqam64ycrv

/assign @timothysc @neolit123 @chuckha @detiber @rdodev

**Comment by timothysc** [comment]
Please roll in details of https://kubernetes.io/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm/  into a single cohesive HA doc for kubeadm.

**Comment by neolit123** [comment]
we also need to fix the links for the YAML files on this page (if we are keeping them).

issue report:
https://github.com/kubernetes/website/issues/8485

new location for the YAMLs is:
https://github.com/kubernetes/website/tree/master/content/en/docs/admin/high-availability

**Comment by neolit123** [comment]
@fabriziopandini @timothysc looks like the Hugo transition for `k/website` removed some of the content Jamie originally added to this page. :\

https://github.com/kubernetes/website/issues/9034#issuecomment-396438379

**Comment by neolit123** [comment]
updated our google docs content discussion with the missing text.

**Comment by chuckha** [comment]
https://github.com/kubernetes/website/pull/9088

**Comment by luxas** [comment]
I believe this issue is fixed. @timothysc reopen if not.
