### ISSUE TITLE
1.11 Copy edits to Setup: "Troubleshooting kubeadm"

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#896]
https://docs.google.com/document/d/1a96Q4Ax8G4Qzz0xWLRfU4uRVeOZmiyoCIO3uN_X05yA/edit?usp=sharing

/assign @liztio @fabriziopandini  @detiber @timothysc @neolit123 

@liztio please take lead on this one.

**Comment by timothysc** [comment]
@stealthybox - you've came across a number of items in case you want to help out here.

**Comment by timothysc** [comment]
@detiber - shuffle to you for on point here b/c @liztio will be out. 

please work together on the deets.

**Comment by detiber** [comment]
master pr: https://github.com/kubernetes/website/pull/9028
release-1.11 backport pr: https://github.com/kubernetes/website/pull/9029

**Comment by timothysc** [comment]
I'm going to close this one now as @luxas has a separate doc on args override.  

https://docs.google.com/document/d/1KuDHonX_5-tZqTO17muBtDOFQKLmMN0K1eXh-q24Ny8/edit#heading=h.b1yrhblhpivc

But I do think we should cross-list with trouble-shooting.
