### ISSUE TITLE
1.11 Copy edits to Setup: "Using CoreDNS for Service Discovery"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#897]
Instead of dozens of issues we will collect updates and do bulk PRs to content areas.

tracking sheet:
https://docs.google.com/spreadsheets/d/1SQ-_FYq9vDCvizIQUZIhfk5IydPf9loCBYlk5m7HwWw/edit#gid=0

We want to discuss if this page needs any kubeadm related improvements:
https://github.com/kubernetes/website/blob/release-1.11/content/en/docs/tasks/administer-cluster/coredns.md
(mind that i'm linking against the `release-1.11` branch as it has the newest versions)

Content discussion:
https://docs.google.com/document/d/1YgWynhJ3-8BfJVu550NRNT-9BfYnyVFOzUszTy9d7EU/edit

**Comment by fturib** [comment]
@neolit123 : @chrisohaver, @rajansandeep and myself reviewed and modified the google doc, adding simple introduction to CoreDNS and links to some pages of the project for doc.

**Comment by neolit123** [comment]
@fturib thank you for the edits!
it's on my TODO to push commits for this at `k/website`.
