### ISSUE TITLE
1.11 Copy edits to Setup: "Implementation details"

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#900]
Instead of dozens of issues we will collect updates and do bulk PRs to content areas.

tracking sheet:
https://docs.google.com/spreadsheets/d/1SQ-_FYq9vDCvizIQUZIhfk5IydPf9loCBYlk5m7HwWw/edit#gid=0

We want to discuss if this page needs any kubeadm related improvements:
https://github.com/kubernetes/website/blob/master/content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
(mind that i'm linking against the `release-1.11` branch as it has the newest versions)

Content discussion:
https://docs.google.com/document/d/1PRDUGnyxTKSkwQ96-SHc6Sajlq6JhHjR1X7CQhtwKjM/edit#heading=h.73lph8rwasco

**Comment by fabriziopandini** [comment]
@timothysc 
Since we cleaning up and simplifying things for better readability and maintainability, IMO  before updating this page we should re-consider the level of detail in this page and/or if to maintain this page. WDYT?
