### ISSUE TITLE
Scheduling pods on master

### ISSUE THREAD

**Issue by craigwillis85** [kubernetes/kubeadm#91]
Hi

I have a single master, which I want to schedule pods on. I don't want to allow any other pods to schedule on it, only ones that I have specifially want.

I know I can `taint` the master, but will this make it available to other pods to schedule on?

I have a Deployment manifest like the following:

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      replicas: 2
      template:
        metadata:
          labels:
            app: nginx
          annotations:
            scheduler.alpha.kubernetes.io/tolerations: |
              [
                {
                  "key": "dedicated",
                  "operator": "Equal",
                  "value": "master",
                  "effect": "NoSchedule"
                }
              ]
        spec:
          nodeSelector:
            kubeadm.alpha.kubernetes.io/role: master
          hostNetwork: true
          containers:
            - name: nginx
               image: nginx:1.7.9
               ports:
               - containerPort: 80

This always gives me the following error:

    failed to fit in any node fit failure on node (master): PodToleratesNodeTaints

Any ideas on how to do this? Is it even possible?

Thanks

**Comment by sheerun** [comment]
Why is this closed, any resultion? I'd like to setup single-node "cluster" with kubeadm
