### ISSUE TITLE
Create a v1beta1 version for kubeadm config API types

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#911]
Follow up from https://github.com/kubernetes/kubeadm/issues/750#issuecomment-396679842.

> For beta, we need to
> - update the KEP to reflect the current state
> - improve the structure of our API types further (gdocs proposal)
> - decide whether to embed other components' ComponentConfig in our types or not

There is way more needed here wrt details, but I don't have time to write up that all now, it will go into the KEP and be discussed during kubeadm Office Hours in the v1.12 cycle.

**Edit:** The KEP gdoc proposal for this is [here](https://docs.google.com/document/d/1Sk2VW7IKaLjrjf_4a1NEU0l7X0ysZoXq9lVBvH-ruYY/edit#heading=h.vd99op8cffst)

**Comment by fabriziopandini** [comment]
@luxas 
This [document](https://docs.google.com/document/d/1Sk2VW7IKaLjrjf_4a1NEU0l7X0ysZoXq9lVBvH-ruYY/edit#heading=h.vd99op8cffst) is still the starting point for this discussion?

**Comment by timothysc** [comment]
Pushing to 1.13

**Comment by fabriziopandini** [comment]
After v1.12 the remaining activities are:
[ ] - create v1beta1 (and delete v1Alpha2)
[ ] - Improve controlplane configuration by using substructs
[ ] - Refactor the Discovery joining API types by using substructs
[ ] - Addons configuration (tracked in #1091)
[ ] - Make flags override config values (tracked in #1040)
[ ] - Stacked etcd (tracked in #1123)
[ ] - Move out BootstrapToken (https://github.com/kubernetes/kubernetes/pull/67356)

**Comment by neolit123** [comment]
@rosti and @fabriziopandini 
please babysit this issue when we are done to close it!

**Comment by timothysc** [comment]
Closing.
