### ISSUE TITLE
Add output to give user awareness of how long timeouts are expected to be

### ISSUE THREAD

**Issue by detiber** [kubernetes/kubeadm#914]
In https://github.com/kubernetes/kubernetes/pull/64988 we increased the manifest upgrade timeout from 1 minute to 5 minutes to improve the reliability of upgrades, however we do not currently give the user any output to know how long to wait before deciding if kubeadm is hung.

We should provide the user some output to help them know if kubeadm is waiting to complete an action or if it is hung on some task. It may even be nice to present the user with some type of progress bar or other indication of how much time has elapsed for a given task.

**Comment by stealthybox** [comment]
@detiber would you like to reopen this?
https://github.com/kubernetes/kubernetes/pull/65164#pullrequestreview-129709081

**Comment by stealthybox** [comment]
^ re: @detiber

**Comment by xlgao-zju** [comment]
As I said in [kubernetes/kubernetes/#65164](https://github.com/kubernetes/kubernetes/pull/65164) , we can add a `TODO` list in this issue. In that `TODO` list,  We can add all the places where we should print the similar log. And we can use this PR as an example.

wdyt?
