### ISSUE TITLE
1.10 -> 1.11 upgrades 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#916]
Create guide on 1.11 upgrade process.

**Comment by timothysc** [comment]
Install kubeadm on 1.10 
Fetch from head and upgrade to latest 1.11 using upgrade apply 
Fetch latest debs/rpms and install them and verify it’s working 
Check kubelet config / unit file changes

**Comment by liztio** [comment]
1. Follow the normal instructions to set up a 1.10 cluster.
2. Checkout HEAD on the branch you want to test.
3. Build a kubeadm binary: `bazel build //cmd/kubeadm:kubeadm   --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64`
4. scp the binary up to your master node
5. Upgrade the kubernetes master. `sudo /tmp/kubeadm upgrade apply ci/<k8s version> --allow-experimental-upgrades`
   Make sure that `<k8s version>` is a HEAD revision or the build artifacts won't exist. 
   You can double-check that it does with e.g. `gsutil ls gs://kubernetes-release-dev/ci/v1.11.0-beta.2.78+e0b33dbc2bde88`.
6. scp the kubeconfig locally. Set the host address to `kubernetes` in `/etc/hosts`
7. In your local hosts file, point `kubernetes` to the master's IP.
8. Alternatively, if you haven't opened port 6443 to the internet, you can forward port 6443 with `ssh <master> -L 6443:localhost:6443`, and set `kubernetes` to `127.0.0.1` in `/etc/hosts`
9. Run the kubeadm e2e tests: `go run test/e2e_kubeadm/runner/local/run_local.go -build -test-flags="--kubeconfig=<path to configi>"` from the kubernetes/kubernetes directory
10. Get a kubelet binary from `https://storage.googleapis.com/kubernetes-release-dev/bazel/<k8s version>/bin/linux/amd64/kubelet.deb`
11. Install the binary with `sudo dpkg -i` on the master and all nodes
12. Restart the kubelet with `systemctl restart kubelet`
13. Check the node version with `kubectl get nodes`. Make sure it says `Ready`.
14. Repeat on all worker nodes.
15. Re-run the kubeadm e2e tests.

**Comment by luxas** [comment]
The PR for this has been merged :+1:
