### ISSUE TITLE
Kubelet unable to load client CA file

### ISSUE THREAD

**Issue by maheshmadpathi** [kubernetes/kubeadm#920]
## Is this a request for help?
yes

If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.

If no, delete this section and continue on.

## What keywords did you search in kubeadm issues before filing this one?
kubadm, kubelet, CA certificate, healthz

If you have found any duplicates, you should instead reply there and close this page.

If you have not found any duplicates, delete this section and continue on.

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT 

## Versions
**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.3 (Maipo)
- **Kernel** (e.g. `uname -a`):  Linux 3.10.0-514.el7.x86_64
- **Others**: Virtualization: vmware

## What happened?
when we try to initialize kubeadm the kubelet status becomes "failed" as a result of this we get below errors

kubeadm init --pod-network-cidr *.*.*.*/24 --kubernetes-version=v1.10.4 --skip-preflight-checks --apiserver-advertise-address=*.*.*.*

[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp [::1]:10255: getsockopt: connection refused.```

I see below errors in `journalctl -xeu kubelet`

```bash
Jun 13 19:27:56 lg-l-p-obo00798 kubelet[21266]: I0613 19:27:56.820222   21266 feature_gate.go:226] feature gates: &{{} map[]}
Jun 13 19:27:56 lg-l-p-obo00798 kubelet[21266]: F0613 19:27:56.820374   21266 server.go:218] unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kube
Jun 13 19:27:56 lg-l-p-obo00798 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jun 13 19:27:56 lg-l-p-obo00798 systemd[1]: Unit kubelet.service entered failed state.
Jun 13 19:27:56 lg-l-p-obo00798 systemd[1]: kubelet.service failed.
Jun 13 19:28:06 lg-l-p-obo00798 systemd[1]: kubelet.service holdoff time over, scheduling restart.
Jun 13 19:28:06 lg-l-p-obo00798 systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up```

but I did generate a cert myself manually and tried too, but no luck.



## What you expected to happen?
kubeadm should initialize and a token is given.

## How to reproduce it (as minimally and precisely as possible)?
kubeadm should initialize and a token is given.

$# ```bash
cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS```

## Anything else we need to know?

I also tried installing k8s with kubespray which didn't work either, I get the same error.
               SELinux disabled
                swap is off
                firewall rules are added
                communication with management IP is blocked
                 ```bash
                  env | grep -i proxy
                 http_proxy=http://*.*.*.*:3128
                 https_proxy=http://*.*.*.*:3128
                  no_proxy=http://127.0.0.1```

**Comment by chuckha** [comment]
@maheshmadpathi do you have the kubeadm logs?

I would also suggest encoding your command line flags into a configuration file and running with `kubeadm init --config kubeadm_config.yaml`

**Comment by luxas** [comment]
Can this be reproduced with latest kubeadm?

**Comment by timothysc** [comment]
@maheshmadpathi  - closing due to lack of response.  Please feel free to reopen if you believe there is an issue with the documentation outlined here - https://kubernetes.io/docs/setup/certificates/
