### ISSUE TITLE
kubeadm alpha phase preflight master fails

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#924]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

## Versions
v1.11 (.debs, kubeadm binary e docker images build from master)

## What happened?
`sudo kubeadm alpha phase preflight master` failed with:

```bash
I0615 12:04:11.687738    7245 kernel_validator.go:81] Validating kernel version
I0615 12:04:11.687816    7245 kernel_validator.go:96] Validating kernel config
	[WARNING Hostname]: hostname "" could not be reached
	[WARNING Hostname]: hostname "" lookup : no such host
[preflight] Some fatal errors occurred:
	[ERROR KubernetesVersion]: couldn't parse kubernetes version "": could not parse "" as version
	[ERROR CRI]: unable to find command crictl: exec: "crictl": executable file not found in $PATH
	[ERROR Hostname]: hostname "" a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

## What you expected to happen?
`sudo kubeadm alpha phase preflight master` to works; probably, we should change the command to require `--config` parameter instead of using an empty config map

**Comment by seh** [comment]
Potentially related, as a subset of this complaint: #835.

**Comment by luxas** [comment]
Yeah solving https://github.com/kubernetes/kubeadm/issues/835 fixed this a bit, but there is still the bug that this phase should require config to be functional (create the `--config` flag and make it mandatory)

/assign @fabriziopandini

**Comment by miry** [comment]
@luxas btw in v1.11-beta.2 we had only warning message if there are no cri tools.
`[WARNING FileExisting-crictl]: crictl not found in system path`
 In version v1.11-rc.1 it is error, that related to this exception. Do you know why it becomes important?

**Comment by timothysc** [comment]
@fabriziopandini could you post an update on this please.

**Comment by fabriziopandini** [comment]
@timothysc the error is confirmed i v1.12.0-beta.1 as well (even if slightly changed)

```
$ sudo kubeadm alpha phase preflight master
	[WARNING Hostname]: hostname "" could not be reached
	[WARNING Hostname]: hostname "" lookup : no such host
[preflight] Some fatal errors occurred:
	[ERROR KubernetesVersion]: couldn't parse kubernetes version "": could not parse "" as version
	[ERROR CRI]: container runtime is not running: output: NAME:
   crictl info - Display information of the container runtime

USAGE:
   crictl info [command options] [arguments...]

OPTIONS:
   --output value, -o value  Output format, One of: json|yaml (default: "json")

time="2018-09-07T15:10:23Z" level=fatal msg="failed to connect: --runtime-endpoint is not set"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```
