### ISSUE TITLE
AnnotateCRISocket cannot be invoked as a phase

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/kubeadm#925]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

`kubeadm alpha phases` are meant to provide atomic action for reproducing the full `kubeadm init` sequence.

In v1.11 timeframe  `AnnotateCRISocket` step was added to `kubeadm init`, but currently there is no phase for reproducing this step atomically.

It should be defined where to add this new phase (e.g upload-config, kubelet or somewhere else); as alternative, we should conflate this issue into #454 

## Versions
v1.11

**Comment by fabriziopandini** [comment]
In v1.12, after the changing how kubeadm-config upload/fetch, `AnnotateCRISocket` becomes a necessary for getting a cluster that can be upgraded using phases. I see two options
- add the `AnnotateCRISocket` step to the existing `alpha phase kubelet config upload` subcommand 
- add a new subcommand `alpha phase kubelet config annotateCRI` or something else 
Opinions?

**Comment by neolit123** [comment]
hi @fabriziopandini 
i think `alpha phase kubelet config annotateCRI` might be better.

**Comment by timothysc** [comment]
@fabriziopandini - I'd vote for `alpha phase kubelet config annotateCRI` as well.

**Comment by dims** [comment]
a mixed case command line looks a bit odd ..

**Comment by timothysc** [comment]
I think `config cri` would possibly suffice .

**Comment by neolit123** [comment]
`annotate-cri` alternatively.
sub-command are lowercase with `-`.
e.g.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/#cmd-phase-addon

**Comment by fabriziopandini** [comment]
/close 
because #68449 merged
