### ISSUE TITLE
Issues with image names when using non-docker run time

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#927]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
v1.11.0-beta.2
**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
I installed cri-o and ran `kubeadm config images pull --config config.yaml`

## What you expected to happen?
All images should be pulled by the container runtime, but it failed on coredns/coredns:1.1.3 because that lives on dockerhub.

## How to reproduce it (as minimally and precisely as possible)?
Use cri-o, install crictl, configure a kubelet to use the crio socket, run `kubeadm config images pull --config config.yaml`

```
[config/images] Pulled k8s.gcr.io/kube-apiserver-amd64:v1.11.0-beta.2
[config/images] Pulled k8s.gcr.io/kube-controller-manager-amd64:v1.11.0-beta.2
[config/images] Pulled k8s.gcr.io/kube-scheduler-amd64:v1.11.0-beta.2
[config/images] Pulled k8s.gcr.io/kube-proxy-amd64:v1.11.0-beta.2
[config/images] Pulled k8s.gcr.io/pause-amd64:3.1
failed to pull image "coredns/coredns:1.1.3": exit status 1
```

## Anything else we need to know?
We need to give the full path to coredns image.

**Comment by chuckha** [comment]
Work around:

1. `crictl pull registry.hub.docker.com/coredns/coredns:1.1.3`
2. `./kubeadm init --config config.yaml  --ignore-preflight-errors=ImagePull`

**Comment by luxas** [comment]
This needs fixing ASAP. CoreDNS now lives in `k8s.gcr.io/coredns` as of recently (v1.11)

**Comment by chuckha** [comment]
Confirmed that `k8s.gcr.io/coredns:1.13` exists
