### ISSUE TITLE
kubeadm should support file-based discovery

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#93]
Building on the recent discovery interface refactoring (https://github.com/kubernetes/kubernetes/pull/36462), kubeadm should implement file-based discovery, e.g.:

    $ kubeadm join --discovery file:///etc/kubernetes/cluster.json

See also: [Discovery API Proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/bootstrap-discovery.md) and [#94: kubeadm should support HTTPS-based discovery](https://github.com/kubernetes/kubeadm/issues/94)

@kubernetes/sig-cluster-lifecycle-misc

**Comment by pires** [comment]
This seems to have been implemented and merged.

**Comment by pipejakob** [comment]
Which commit are you referring to? @mikedanese refactored discovery behind an interface (https://github.com/kubernetes/kubernetes/commit/690c7e578b341a34dbb9b72f6355655a373dc423), but the implementations for file and https discovery are still missing, just stubbed out.

**Comment by pires** [comment]
Nevermind then, I overlooked the code.

**Comment by pires** [comment]
@luxas @pipejakob I can pick this up if no one else who's best prepared to do it is available.

**Comment by luxas** [comment]
Cool, can you do this and the HTTPS thing today?
That would be awesome, and let's us move faster!

I'm hacking on the refactoring/API stuff today; any help with more coding would be super-appreciated!
I can assign this to you if you want

**Comment by pires** [comment]
Do it @luxas.

**Comment by mikedanese** [comment]
@pipejakob called /dibs two days ago and was assigned. That implies he is working on this. Why would you reassign? What is the urgency?

This is not a good practice for getting new folk to start learning the codebase and contributing. By ramping people up we may take a hit on velocity in the short term but in the longer term we will have more active contributors thereby improving velocity. Please be mindful of this.

**Comment by luxas** [comment]
I'm very sorry @pipejakob, that was not my intention. I guess I have learned a new word today then, I didn't interpret it correctly it seems, apologies.

I just happened to chat with pires while reading the source and saw this was not done yet and assigned pires from the issues view of this.

That was not my intention. @pipejakob if you want to sync up on Slack or have any questions any time; just ask and I'll try to help. Coding/refactoring/fixing bugs is going to be a more critical task than ever now with the planned beta release soon, and I'm very grateful you're working on kubeadm things :+1:. 

Next time I'll be much more careful and know what `/dibs` mean.

**Comment by pires** [comment]
Indeed, it was not my intention either. It just seems trivial and since I was already at it, it seemed OK. I am open to work with @pipejakob to get either a new PR of his with some of my commits or his/hers commits into my PR.

**Comment by pipejakob** [comment]
No worries, it looks like you're quite far along already. I'm sure there's enough work for everyone while we prepare for beta, so I'll look for something else to pick up.

**Comment by pires** [comment]
@pipejakob thanks! Would you be so kind and help with the review?
