### ISSUE TITLE
ZFS isn't supported

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubeadm#930]
## FEATURE REQUEST

ZFS driver isn't allowed for now. This request for enable zfs support in kubeadm.

## Versions

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version**: `&version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: `hardware`
- **OS**: `Ubuntu 16.04.4 LTS (Xenial Xerus)`
- **Kernel**: `4.15.17-3-pve`
- **Others**:

## What happened?

When you run `kubeadm join`, it is falling down with the next preflight check:

```
[preflight] Some fatal errors occurred:
        [ERROR SystemVerification]: unsupported graph driver: zfs
```

## What you expected to happen?

Succesful join to the cluster

## How to reproduce it (as minimally and precisely as possible)?

Use zfs and docker with `--storage-driver zfs`

## Anything else we need to know?

Temprorary solution for run `kubeadm` with `--ignore-preflight-errors=SystemVerification` flag.

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-bugs
@kubernetes/sig-node-proposals 

google says that people are actually running zfs +docker + k8s, so i'm going to assume that it just works.

but we don't treat `zfs` as valid here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system/docker_validator.go#L92

should i just add `zfs` to the `GraphDriver` slice?
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/system/types_unix.go

**Comment by kvaps** [comment]
For me zfs is working fine in test instances. We going to use it in production.

**Comment by dims** [comment]
looks like this was fixed in https://github.com/kubernetes/kubernetes/pull/65635

/close
