### ISSUE TITLE
kubeadm upgrade plan output should also print required flags

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#935]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions
Upgrading k8s from 1.10.4 to 1.11.0-beta.2

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2.57+8bb1309efed13d-dirty", GitCommit:"8bb1309efed13d572c12bf29397e533e07579b56", GitTreeState:"dirty", BuildDate:"2018-06-12T19:00:36Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

## What happened?
I ran `kubeadm upgrade plan --allow-experimental-upgrades`

and received the line

```
You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply v1.11.0-beta.2

Note: Before you can perform this upgrade, you have to update kubeadm to v1.11.0-beta.2.
```

I then ran `kubeadm upgrade apply v1.11.0-beta.2` and received an error:

```
[upgrade/version] FATAL: The --version argument is invalid due to these errors:

        - Specified version to upgrade to "v1.11.0-beta.2" is an unstable version and such upgrades weren't allowed via setting the --allow-*-upgrades flags
```

## What you expected to happen?
I expected to run the provided command without errors.

## How to reproduce it (as minimally and precisely as possible)?
upgrade to a non-stable release version

**Comment by neolit123** [comment]
/assign
i can take this. if someone else wants it - do tell. :)

**Comment by xlgao-zju** [comment]
/assign
@neolit123 Thank you for your suggestion of taking this. I'd love to help this. 😆
