### ISSUE TITLE
1.11 Release Notes. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubeadm#938]
This issue exists for us to track + update our 1.11 release notes. 

https://github.com/kubernetes/sig-release/blob/master/releases/release-1.11/release_notes_draft.md

/cc @jberkus @nickchase

**Comment by timothysc** [comment]
@neolit123 please post a google doc for group edit

**Comment by neolit123** [comment]
waiting on confirmation from #sig-release about the missing username / PR links here:
https://github.com/kubernetes/sig-release/blob/master/releases/release-1.11/release_notes_draft.md

and i'm going to copy paste it into gdocs.

**Comment by neolit123** [comment]
```
nickchase [8:11 PM]
yes, they will be added in the next day or so.
```

**Comment by neolit123** [comment]
looks like the release note editing has started at gdocs while the links are still missing:
https://docs.google.com/document/d/1MoHdmqSpWT4dJ3AcONwPwquNa2NIBa1dhpb0g8xyyoI/edit

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-misc 

https://docs.google.com/document/d/1MoHdmqSpWT4dJ3AcONwPwquNa2NIBa1dhpb0g8xyyoI/edit

please edit the notes of your or related/known PRs.
we also need to add the SIG themes in there.

**Comment by luxas** [comment]
This work has been completed, the release is out :tada:
