### ISSUE TITLE
kubeadm should support HTTPS-based discovery

### ISSUE THREAD

**Issue by pipejakob** [kubernetes/kubeadm#94]
Building on the recent discovery interface refactoring (kubernetes/kubernetes#36462), kubeadm should implement HTTPS-based discovery, e.g.:

    $ kubeadm join --discovery https://storage.google.apis.com/kube-discovery/98ea6e4/kubeconfig.json

See also: [Discovery API Proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/bootstrap-discovery.md) and [#93: kubeadm should support file-based discovery](https://github.com/kubernetes/kubeadm/issues/93)

@kubernetes/sig-cluster-lifecycle-misc

**Comment by pires** [comment]
This seems to have been implemented and merged.

**Comment by pipejakob** [comment]
Copying response from #93:

Which commit are you referring to? @mikedanese refactored discovery behind an interface (kubernetes/kubernetes@690c7e5), but the implementations for file and https discovery are still missing, just stubbed out.

**Comment by pires** [comment]
Nevermind then, I overlooked the code.

**Comment by luxas** [comment]
Yup this is yet to be fixed in the code; @pipejakob do you take this on?

**Comment by pires** [comment]
I can pick this up if no one else who's best prepared to do it is available.
