### ISSUE TITLE
bazel packaging needs a re-think

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#940]
I believe we are using the `http_file` function in bazel in an unexpected way. Generally it looks like you want to grab files without version numbers or hashes or timestamps (or other changing identifiers). This would be something like a `.deb` file.

The consequence of this is that we have to hard code the version or do unexpected bash in rpm files because of the order of substitutions that happen. First, bazel substitutes `{filename}` with the full path of where that file actually lives. Then when the spec file is executed, things like %version are substituted. So if your filename has a `%{version}` embedded in it, bazel will not substitute with the full path, but the spec file will properly fill in the version.

What we might consider doing is use `genrule` or something to rename the file.

Alternatively we could consider building critools and kubernetes-cni as part of the build step. Then we could take advantage of the `strip_prefix` argument the *_archive functions get.

**Comment by timothysc** [comment]
Closing in preference for https://github.com/kubernetes/kubernetes/issues/71677
