### ISSUE TITLE
Not able to add the worker node to Master : getting "[discovery] Failed to request cluster info, will try again: [Get https://10.148.0.2:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.148.0.2:6443: i/o timeout]"

### ISSUE THREAD

**Issue by anuprath87** [kubernetes/kubeadm#941]
Worker Node:
[root@worker1 ~]# kubeadm join 10.148.0.2:6443 --token t8op84.9zc5zx4w8ox906og --discovery-token-ca-cert-hash sha256:23eb63377a46b03748ded7220a448be206923c0d494ca7a7e6146a6f98f89f95
[preflight] Running pre-flight checks.
        [WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
[discovery] Trying to connect to API Server "10.148.0.2:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://10.148.0.2:6443"
[discovery] Failed to request cluster info, will try again: [Get https://10.148.0.2:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.148.0.2:6443: i/o timeout]
[discovery] Failed to request cluster info, will try again: [Get https://10.148.0.2:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.148.0.2:6443: i/o timeout]
[discovery] Failed to request cluster info, will try again: [Get https://10.148.0.2:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.148.0.2:6443: i/o timeout]

[root@worker1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Master End:
[root@master ~]# kubectl get svc kubernetes -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-06-20T03:13:17Z
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "6"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: e0d223a8-7437-11e8-ac41-42010a940002
spec:
  clusterIP: 10.96.0.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
[root@master ~]#

[root@master ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2018-06-20 03:13:07 UTC; 2h 49min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 14028 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─14028 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/...

Jun 20 06:01:30 master kubelet[14028]: E0620 06:01:30.694120   14028 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed...
Jun 20 06:01:30 master kubelet[14028]: E0620 06:01:30.694153   14028 summary.go:102] Failed to get system container stats for "/system.slice/docker.service...r.service"
Jun 20 06:01:40 master kubelet[14028]: E0620 06:01:40.704482   14028 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed...
Jun 20 06:01:40 master kubelet[14028]: E0620 06:01:40.704513   14028 summary.go:102] Failed to get system container stats for "/system.slice/docker.service...r.service"
Jun 20 06:01:50 master kubelet[14028]: E0620 06:01:50.715007   14028 summary.go:102] Failed to get system container stats for "/system.slice/docker.service...r.service"
Jun 20 06:01:50 master kubelet[14028]: E0620 06:01:50.715524   14028 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed...
Jun 20 06:02:00 master kubelet[14028]: E0620 06:02:00.725504   14028 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed...
Jun 20 06:02:00 master kubelet[14028]: E0620 06:02:00.725566   14028 summary.go:102] Failed to get system container stats for "/system.slice/docker.service...r.service"
Jun 20 06:02:10 master kubelet[14028]: E0620 06:02:10.736515   14028 summary.go:102] Failed to get system container stats for "/system.slice/kubelet.service": failed...
Jun 20 06:02:10 master kubelet[14028]: E0620 06:02:10.736546   14028 summary.go:102] Failed to get system container stats for "/system.slice/docker.service...r.service"
Hint: Some lines were ellipsized, use -l to show in full.

[root@master ~]# netstat -tuplen | grep 6443
tcp6       0      0 :::6443                 :::*                    LISTEN      0          88533      14317/kube-apiserve

[root@master ~]# kubectl get nodes
NAME      STATUS    ROLES     AGE       VERSION
master    Ready     master    2h        v1.10.4

[root@master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by neolit123** [comment]
@anuprath87 
what pod network plugin did you install?
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

have you tried with a different one from the current one?

**Comment by rosti** [comment]
Are your nodes running on CentOS or similar Linux distro?

**Comment by timothysc** [comment]
Closing due to timeout on a response.
