### ISSUE TITLE
crictl preflight check is marked as mandatory

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#942]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

It might be a feature though.

## Versions

**kubeadm version** (use `kubeadm version`):
affects 1.11

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
I ran `kubeadm init` and it failed because crictl could not be found

## What you expected to happen?
I expected a warning letting me know crictl could not be found, but not an error.

## How to reproduce it (as minimally and precisely as possible)?
get the latest binaries and run `kubeadm init` without crictl on the system.

## Anything else we need to know?

Current workaround is to run `kubeadm init --config config.yaml  --ignore-preflight-errors=FileExisting-crictl`

**Comment by chuckha** [comment]
This is intentional. 

Error was cri-tools was not added as a dep to `kubeadm` deb/rpm.

**Comment by bart0sh** [comment]
> Error was cri-tools was not added as a dep to kubeadm deb/rpm.

Can you remind me what was the point of adding it as a dependency? I'd say it shouldn't be required unless user wants to use CRI. 

Are we going to add docker as a mandatory dependency too? Other tools that kubeadm may or may not use?

**Comment by luxas** [comment]
> Can you remind me what was the point of adding it as a dependency? I'd say it shouldn't be required unless user wants to use CRI.

Long-term the only way to run k8s is to do CRI. I don't see `dockershim` living inside of the kubelet being there forever, so hence we're preparing ourselves for that future.

`crictl` is going to be an essential tool to kubeadm going forward. I know it's been optional and badly-managed in earlier releases, but we're treating it as a first-class citizen from v1.11 and everything here should be transparent to the user really.

Does that make sense to you?

> Are we going to add docker as a mandatory dependency too?

We've _never_ had such plans.

**Comment by bart0sh** [comment]
yes, it makes sense. Thank you for the explanations. 

I didn't think about cri-tools as something special as both docker and CRI are used in the current kubeadm code.

**Comment by luxas** [comment]
execing to docker is a stop-gap until we're all CRI, in order to make the current "default happy path" good UX-wise. Using CRI (only) is the future direction.
