### ISSUE TITLE
release debs restart kubelet after an update; bazel artifacts do not

### ISSUE THREAD

**Issue by chuckha** [kubernetes/kubeadm#944]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions
All known versions

## What happened?
Installing a `.deb` built from bazel in k/k will not restart the kubelet.
Installing a `.deb` built from the k/release repo *will* restart the kubelet

## What you expected to happen?
I expected both to restart the kubelet

## How to reproduce it (as minimally and precisely as possible)?
upgrade with a .deb built by bazel and see that the kubelet does not receive the upgrade until you manually restart

**Comment by rdodev** [comment]
@chuckha to clarify:

When running `apt-get install -y ./kubelet.deb` generated by bazel build, will not cause a service restart. However, doing the same with one built by the official release mechanism _does_? Or are talking about one installed from the official k8s pap repo?

**Comment by chuckha** [comment]
I don't know what pap is -- but yes, that's the restart behavior is the disconnect between debs built with bazel in k8s/k8s and debs built without bazel in k8s/release

**Comment by rdodev** [comment]
I'll ping you on Monday. I _think_ I found the place where the dpkg-ing takes place where we can drop the service restart line, but want to run it by you in case I'm way off -- my bazel skills are still at the padawan level.

**Comment by rdodev** [comment]
WIP. The build machinery is vastly different from release machinery. For the moment going to focus on having bazel include a `postinst` in the deb when it's generating them. Long term solution would be to have both release and build be the same (which, incidentally and part of larger conversation, I suppose, has implications for the fidelity of QA).

**Comment by rdodev** [comment]
Status: testing solution

**Comment by timothysc** [comment]
Closing PR merged a while back.
