### ISSUE TITLE
Support `kubeadm join` with a pre-existing client certificate

### ISSUE THREAD

**Issue by ivan-section-io** [kubernetes/kubeadm#945]
## Is this a request for help?

No.

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Detail

I'd like to use `kubeadm join` with a pre-existing client certificate (no token/TLSBootstrap).

We've got a environment where interacting with the master to setup a bootstrap token and feeding that to the new node is impractical/sub-optimal (security boundaries, provisioning latency, machine orchestration tooling, privileged credential practices, etc)

We currently generate our cluster CA & worker node client certificates externally and lay those down during system provisioning. (So far, it's been a pretty smooth approach)

On the master we run `kubeadm init`, which will detect and use our existing CA files.  On worker nodes, we lay down a suitable `/etc/kubernetes/kubelet.conf` with the externally generated node certificate. (This approach also allows us to add workers at a later date without having to interact with the master - our deployment tooling has the original CA keys and creates a suitable client-certificate externally)

I've noticed `kubeadm join` appears to be doing an increasing amount of "extrajoin" configuration (e.g. CRISocket, DynamicKubeletConfig) and imagine that this is will only increase in the future.

I feel that our manual `kubelet.conf` approach will become faulty or high maintenance if we must mimic a set of increasing requirements performed by `kubeadm join`.

Would it make sense to support:
a) Exposing `kubeadm join` phases via `kubeadm alpha phase` style commands
b) Use of existing on-disk `kubelet.conf` during `kubeadm join` (akin to CA files during `kubeadm init`).
c) Explicitly providomg node CA/client certificate "credentials" to `kubeadm join`

Or is our external certificate generation approach doomed for other reasons? (And we should start making other plans)

I hope I've explained that clearly.

**Comment by neolit123** [comment]
> Would it make sense to support:
> a) Exposing kubeadm join phases via kubeadm alpha phase style commands

there are plans to move the phases to `kubeadm init` for the next release in terms of CLI.
yet both `init` and `join` are users of the kubelet phase ATM, so not sure how this would end up as a structure.

> b) Use of existing on-disk kubelet.conf during kubeadm join (akin to CA files during kubeadm init).

but then how would you keep the existing `kubelet.conf` compatible with the latest release.
isn't this still high maintenance - manual work?

> c) Explicitly providomg node CA/client certificate "credentials" to kubeadm join

this might be the right option, except i'm not sure about all the implications here.

**Comment by luxas** [comment]
Thank you very much for the issue report @ivan-section-io :+1:. This is actually a user story, and issue I was about to write up to target v1.12. But it was only a feature I assumed people needed (as I new kubeadm is lacking this functionality), now we have data it's worth prioritizing.

I think just letting the user do `kubeadm join --discovery-file foo.conf` with foo.conf containing the CA cert, API server endpoint and a token **or** client certificates for authentication makes a lot of sense. kubeadm will then just drop this to `/etc/kubernetes/bootstrap-kubelet.conf` without modifying it much in particular as all information already is there.
What do you think about that?

**Comment by ivan-section-io** [comment]
@luxas That sounds pretty well aligned to my way of thinking. It seems explicit, lives where expected, and would solve my particular use case.

**Comment by luxas** [comment]
Great, we'll implement this then :)
/assign @dixudx

**Comment by jstangroome** [comment]
I just tried to use `kubeadm join --discovery-file X` where the file contains a pre-generated client certificate already signed by the master CA cert as per the work completed in the PR mentioned above:
https://github.com/kubernetes/kubernetes/pull/66482

However, `kubeadm join` failing and insisting on a bootstrap token which would appear to defeat the purpose of this feature:
```tlsBootstrapToken: Invalid value: "": the bootstrap token is invalid```

This is with kubeadm v1.12-beta.1 which should include these changes if I have understood correctly:
https://github.com/kubernetes/kubernetes/commit/f7641e87100cbb04a1696fc9554b01a5e9394235

Am I doing it wrong or is this feature perhaps incomplete? Do I need to open a new issue?

**Comment by neolit123** [comment]
@jstangroome 
yes, please file a new issue so that we can track this.

**Comment by dixudx** [comment]
> tlsBootstrapToken: Invalid value: "": the bootstrap token is invalid

@jstangroome I think you should remove field `tlsBootstrapToken` from your discovery file. I don't think this is a bug brought by kubernetes/kubernetes#66482.

**Comment by orangefruity** [comment]
[root@ip-172-31-20-92 centos]# kubeadm join --token sha256:2bc3384ae194d966b2f63535c86026a788c21e34eb5571c172790ef4c08ff592 54.202.149.95
[discovery.bootstrapToken: Invalid value: "": using token-based discovery without caCertHashes can be unsafe. Set unsafeSkipCAVerification as true in your kubeadm config file or pass --discovery-token-unsafe-skip-ca-verification flag to continue, discovery.bootstrapToken.token: Invalid value: "sha256:2bc3384ae194d966b2f63535c86026a788c21e34eb5571c172790ef4c08ff592": the bootstrap token is invalid, discovery.bootstrapToken.apiServerEndpoint: Invalid value: "54.202.149.95": address 54.202.149.95: missing port in address, discovery.tlsBootstrapToken: Invalid value: "sha256:2bc3384ae194d966b2f63535c86026a788c21e34eb5571c172790ef4c08ff592": the bootstrap token is invalid]
[root@ip-172-31-20-92 centos]#
