### ISSUE TITLE
Upgrade path for Stacked HA Controller Nodes

### ISSUE THREAD

**Issue by rdodev** [kubernetes/kubeadm#948]
## Is this a request for help?

NO

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## Versions

1.11.0-beta.2 ===> 1.11.-rc.1

## Description

There's presently not an upgrade path for stacked controller nodes (etcd and control plane on same host). This basically means users going through the trouble of setting up such cluster might find themselves unable to upgrade to new version as they come along.

//cc @timothysc @detiber

**Comment by schmitch** [comment]
I could not find any info in the https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md
which feature forbids running a standalone etcd and k8s control plane on the same node (when using kubeadm)?

**Comment by fabriziopandini** [comment]
@timothysc @rdodev 
If I got this right an upgrade path for stacked etcd is required only if etch version changes. I'm right?  
Is this use case expected with v1.12?

**Comment by timothysc** [comment]
https://github.com/kubernetes/website/pull/10264 Fixes and deduping with https://github.com/kubernetes/kubeadm/issues/1044
