### ISSUE TITLE
kubeadm upgrade from 1.10.1 to 1.10.3 does not retain apiserver manifest changes

### ISSUE THREAD

**Issue by sarmak1179** [kubernetes/kubeadm#950]
## What keywords did you search in kubeadm issues before filing this one?

kubeadm upgrade does not retain apiserver manifest changes

## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):

kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
Azure Standalone VM Image
- **OS** (e.g. from /etc/os-release):
NAME="Oracle Linux Server"
VERSION="7.4"
ID="ol"
VERSION_ID="7.4"
PRETTY_NAME="Oracle Linux Server 7.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.4

- **Kernel** (e.g. `uname -a`):
Linux xxxx 4.1.12-124.14.1.el7uek.x86_64 #2 SMP Thu Apr 12 13:56:36 XXX 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?
I had kubeadm cluster 1.10.1 and I have made some changes to kube-apiserver.yaml after I installed and configured the cluster

I have added the following line to the apiserver
--service-node-port-range=8081-9020

Issue 1:

Now I did a yum install/upgrade kubelet-1.10.3 kubeadm-1.10.3 kubectl-1.10.3

I also had changes to kubelet config (cgroup-driver=cgroupfs). 

Once I restarted kubelet the existing changes to kubelet were gone. So the service kubelet didn't come back until made the change again

Issue 2:

Now I did a kubeadm upgrade apply 1.10.3
The log indicated that it took a backup of the api-server.yml (But I could find one in the folder mentioned) after the upgrade is complete.
The upgrade completed successfully, but when I looked at the api-server.yml, the changes were gone (--service-node-port-range=8081-9020)

## What you expected to happen?
The changes for kubelet configuration as well as kube-apiserver or any other kubeadm component should be retained after successful upgrade

## How to reproduce it (as minimally and precisely as possible)?
Make changes to kubeadm manifest files and upgrade kubeadm to minor releases and observe the changes that were done to manifest files

## Anything else we need to know?
I was not able to find any option that could actually retain the configuration after an upgrade. I am not sure if I am missing something here. Please do let me know if that is the case.

**Comment by rosti** [comment]
Did you modify the generated static pod YAML directly or you used the `apiServerExtraArgs` config file option?

**Comment by sarmak1179** [comment]
I modified the YAML

**Comment by timothysc** [comment]
This is expected until component config exists for the api-server.
