### ISSUE TITLE
CoreDNS: wrong port for Prometheus in 1.11

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#955]
@swade1987 has raised the concern that he has to manually edit a Prometeus port in 1.11:

> looks like the kube-dns service on Kubeadm for @corednsio needs to explicitly set the port to be http://prometheus.io/port : "9153" as its defaulting to port 53 and failing. 

https://twitter.com/swade1987/status/1012344170030264320

do you think we should fix this on the kubeadm / phases side?
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go

CoreDNS ref line:
https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L140

/cc @rajansandeep 
/cc @johnbelamaric 
/cc @kubernetes/sig-cluster-lifecycle-bugs

**Comment by chrisohaver** [comment]
Prometheus defaults to scrape from port 53?  That doesn't sound right.

**Comment by swade1987** [comment]
It's using the service port, it's an issue in the coredns/deployment repo
too

**Comment by chrisohaver** [comment]
Ah, Prometheus tries all open TCP ports...

**Comment by chrisohaver** [comment]
So it's probably also scraping health port too... and also the prometheus port.
So the issue is that Prometheus tries to scrape additional ports to the prometheus port.

**Comment by swade1987** [comment]
From my understanding, Prometheus scrapes the ports listed in the service by default. 

In our case this is port 53, we just need to explicitly set it to 9153.

**Comment by chrisohaver** [comment]
> From my understanding, Prometheus scrapes the ports listed in the service by default.

Yes, and in the coredns/deployment, metrics is one of those ports, so Prometheus scrapes 53 and 9153.  IOW, it successfully scrapes metrics on 9153, but it also scrapes ports 53 which is a waste of time (although not catastrophically harmful).

AHA... I see - 9153 is missing from the exposed services in the kubeadm manifest.
