### ISSUE TITLE
Kube-dns failed to resolve the services inside the pods after stopping one master node in a multi-master/HA setup

### ISSUE THREAD

**Issue by ajaynemade** [kubernetes/kubeadm#956]
## Versions

**kubeadm version** (use `kubeadm version`): 1.10.5

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.10.5
- **Kubelet version** 1.10.5
- **Cloud provider or hardware configuration**: EC2 instances on aws
- **OS** (e.g. from /etc/os-release): Centos 7.5
- **Kernel** (e.g. `uname -a`): 3.10.0-862.3.2.el7.x86_64
- **Others**: It's 3 node(ec2 instances) setup on aws. Deployed kubernetes HA using kubeadm. All 3 nodes are in master role and scheduling is allowed on all nodes i.e. on all master nodes.
- **kubernetes components docker images** 
```
k8s.gcr.io/kube-scheduler-amd64                  v1.10.5             1f3f4b7d8ff7        7 days ago          51.2MB
k8s.gcr.io/kube-controller-manager-amd64         v1.10.5             c38845efbf65        7 days ago          151MB
k8s.gcr.io/kube-apiserver-amd64                  v1.10.5             06990282ebc5        7 days ago          228MB
k8s.gcr.io/kube-proxy-amd64                      v1.10.5             32609f1b11ae        7 days ago          97.9MB
weaveworks/weave-npc                             2.3.0               21545eb3d6f9        2 months ago        47.2MB
weaveworks/weave-kube                            2.3.0               f15514acce73        2 months ago        96.8MB
weaveworks/weaveexec                             2.3.0               c2030610fb92        2 months ago        79.1MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64           1.14.8              c2ce1ffb51ed        5 months ago        41MB
k8s.gcr.io/k8s-dns-sidecar-amd64                 1.14.8              6f7f2dc7fab5        5 months ago        42.2MB
k8s.gcr.io/k8s-dns-kube-dns-amd64                1.14.8              80cc5ea4b547        5 months ago        50.5MB
k8s.gcr.io/pause-amd64                           3.1                 da86e6ba6ca1        6 months ago        742kB
```

## What happened?
I brought down one node intentionally to test the k8s ha behaviour. Kubectl get nodes is showing correct output by mentioning 2 nodes in Ready state and 1 node in NotReady state. All the pods in kube-system namespace are up and running.
Kube-dns pod was running on the node which I brought down. Before bringing down the node, everything was working fine. After bringing down the node, kube-dns pod got rescheduled to the one of the node which was in running state.
```
kube-dns-86f4d74b45-7jf8d                            3/3       Running    0          1h        10.117.113.109   master-0
kube-dns-86f4d74b45-7whkm                            3/3       Unknown    0          3h        10.117.113.129   master-1
```
Kube-dns pod i.e. `kube-dns-86f4d74b45-7whkm` which was running on master-1 went into Unknown state and I believe, this is as per the design. New pod `kube-dns-86f4d74b45-7jf8d`  came up on master-0 and all containers of the pod are in running state. 

**Please check the ip of the pods**
Kubedns pod which is in **Running** state is having **10.117.113.109**
and the kubedns pod which is in **Unknown** state was having **10.117.113.129**

Following is my get node output

```
[root@ip-10-0-1-104 centos]# kubectl get nodes -o wide
NAME       STATUS     ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION              CONTAINER-RUNTIME
master-0   Ready      master    3h        v1.10.5   <none>        CentOS Linux 7 (Core)   3.10.0-862.3.2.el7.x86_64   docker://17.12.0-ce
master-2   Ready      master    3h        v1.10.5   <none>        CentOS Linux 7 (Core)   3.10.0-862.3.2.el7.x86_64   docker://17.12.0-ce
master-1   NotReady   master    3h        v1.10.5   <none>        CentOS Linux 7 (Core)   3.10.0-862.3.2.el7.x86_64   docker://17.12.0-ce

```
master-0 and master-2 are in running state.

Now the main issue is here,
Pods running on master-0 are resolving the service name properly

> $ kubectl exec -it my-pod-1 -- host kubernetes.default
and output is: 
 kubernetes.default.svc.cluster.local has address 10.96.0.1

Pods running on master-2 are giving issue in the resolution.

> $ kubectl exec -it my-pod-2 -- host kubernetes.default
and output is: 
;; connection timed out; trying next origin
;; connection timed out; trying next origin

Following is my observation and I think the root cause

I went through the iptables rules on both nodes which are in Ready state.

On master-0, on which the resolution is working inside the pods running on it, following are the rules

```
[root@ip-10-0-1-104 centos]# iptables-save |grep dns
-A KUBE-SEP-5Y5UGQTIEY6E6GMK -s 10.117.113.109/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-5Y5UGQTIEY6E6GMK -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.117.113.109:53
-A KUBE-SEP-A3LANKKXX5Q6MODX -s 10.117.113.109/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-A3LANKKXX5Q6MODX -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.117.113.109:53
-A KUBE-SERVICES ! -s 10.117.113.0/24 -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 10.117.113.0/24 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-A3LANKKXX5Q6MODX
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-5Y5UGQTIEY6E6G
```
Check IP in first 4 rules.

On master-2, following are the iptable rules relevant to kube-dns

```
[root@ip-10-0-1-152 centos]# iptables-save |grep dns
-A KUBE-SEP-R6YMCWDUASN32VLL -s 10.117.113.129/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-R6YMCWDUASN32VLL -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 10.117.113.129:53
-A KUBE-SEP-ZZF2UW7NTBAIKDZD -s 10.117.113.129/32 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-MARK-MASQ
-A KUBE-SEP-ZZF2UW7NTBAIKDZD -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp" -m tcp -j DNAT --to-destination 10.117.113.129:53
-A KUBE-SERVICES ! -s 10.117.113.0/24 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4
-A KUBE-SERVICES ! -s 10.117.113.0/24 -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m comment --comment "kube-system/kube-dns:dns-tcp" -j KUBE-SEP-ZZF2UW7NTBAIKDZD
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-R6YMCWDUASN32VLL

```
Check IP in first 4 rules.

Kubedns pod which is in **Running** state is having ip **10.117.113.109**
and the kubedns pod which is in **Unknown** state was having ip **10.117.113.129**

I can see that iptable-rules on the master-2 node are still showing the kube-dns pod ip which is in Unknown state. Iptables rules on master-0 node are seems to be correct one hence no issue there on that node.

## What you expected to happen?
All pods on all the Ready node should resolve the services. As far as I know, iptables rules should have gotten updated and should have pointed to the correct kube-dns pod ip on node master-2

## How to reproduce it (as minimally and precisely as possible)?
In the multi-master setup, bring down the node on which kube-dns pod is running.

## Anything else we need to know?
I followed the https://kubernetes.io/docs/setup/independent/high-availability/ document to setup the k8s HA and in my case etcd cluster is running on same nodes but not inside the containers.

**Comment by neolit123** [comment]
@kubernetes/sig-network-bugs 
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by stealthybox** [comment]
@ajaynemade, could you show us the output of this?
```
kubectl -n kube-system get svc,ep kube-dns
```

The kube-dns service is always set to be the 10th address of the Service CIDR.
It's kube-proxy's job to update the vip backing the kube-dns service.

I'm curious what the state of that Service is and whether the Endpoints match the Pods.
If so, kube-proxy is not managing the rules correctly in your case.

**Comment by ajaynemade** [comment]
I had verified `kubectl -n kube-system get svc,ep kube-dns` the  and I guess the output is as expected

```
[root@ip-10-0-1-104 centos]# kubectl -n kube-system get svc,ep kube-dns
NAME               TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
service/kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP   13h

NAME                 ENDPOINTS                             AGE
endpoints/kube-dns   10.117.113.109:53,10.117.113.109:53   13h

```

**Comment by ajaynemade** [comment]
Can anyone please suggest me the workaround? Should I try any other version?

**Comment by ajaynemade** [comment]
I figured out the cause. I was not using the failover mechanism which is recommended in the official doc. 
As predicted by @stealthybox, issue was related to kube-proxy. Kube proxy does the iptable restore if any change in endpoints is seen. 
In my case, kube-proxy was trying to get the endpoints from the apiserver using the ip of the master which is in switched off mode and hence kube-proxy did not get any event to update the iptables rules on the host.
I tried using keepalived and I did not face this issue. Iptable rules on the running nodes got upgraded correctly.
Now, around keepalived, it works differently on aws, gcp setups. I need to use the cloud specific api to handle the ip association in case of failover. In my case, if I did not use the cloud apis and keepalived is landing in split brain situation. This discussion might be going out of track but the purpose is same.
I just wanted to check if I configure same ip address on default interface of all the nodes in the k8s cluster then would I face the kube-proxy issue? Because, lets say I am using 192.168.117.17 as virtual ip and providing the same to --api-advertised-address then all the pods on all the nodes will try to contact apiserver using 192.168.117.17:6443 and the request will get settled locally as 192.168.117.17 is present and configured on each node of the cluster.

**Comment by stealthybox** [comment]
@ajaynemade you would want to avoid a request for the apiserver originating from one of your nodes ever getting directed to a node that is unable to serve the response. I would think you'd use keepalived only for the nodes you'd ever intend running the apiserver on.

I would expect that an LB would have an independent IP. I probably wouldn't set the default interface of every node to the same IP address. That's a foreign setup to me, but maybe you have a good reason.

**Comment by ajaynemade** [comment]
I think the root cause was not having LB or failover mechanism. With keepalived, I never seen this. Closing the issue.
