### ISSUE TITLE
Start utilizing kubectl `genericclioptions`

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubeadm#959]
ref: https://github.com/kubernetes/features/issues/581

As part of ongoing work that focuses on containing all significant kubectl command utilities in a single package (pkg/kubectl/genericclioptions), this package should be split out into its own repo in order to allow use by third-party clients as well as plugins. The self-contained genericclioptions package currently provides all of the major components (kubeconfig parsing, obtaining a config and a REST client, printing, etc.) needed to build a generic kubectl command. Making this package into a separate repository would allow external plugins to behave and be structured as a typical kubectl command, particularly in terms of communicating with the api server.

**Comment by neolit123** [comment]
there are a lot of PR in k/k the past few weeks moving things out to staging.

but we might need better detail to outline what can actually be used.

>  The self-contained genericclioptions package currently provides all of the major components (kubeconfig parsing, obtaining a config and a REST client, printing, etc.) needed to build a generic kubectl command

for most things we already use client-go, printing of e.g. runtime objects is nice and it we might use it for the machine readable output work.

**Comment by neolit123** [comment]
most of the kubectl backend is now in staging.
as part of the future work around the "kubeadm library" we could evaluate what can be reused:
https://github.com/kubernetes/kubeadm/issues/2316
