### ISSUE TITLE
kube-dns started on slave node while cluster restarted and something went wrong with DNS

### ISSUE THREAD

**Issue by zh168654** [kubernetes/kubeadm#96]
I used kubeadm to create my cluster and it worked well.By default,kube-dns is deployed in the master node.But after the cluster restarted several times,kube-dns would start on the slave node such as slave1.

Then I encountered a problem that DNS service is invalid on slave1,while other nodes worked fine.I went into a container in slave1 and exec cmd such as `ping kubernetes-dashboard`,the result showed `ping: unknown host  kubernetes-dashboard`,while the same cmd executed in another container on other node could show kubernetes-dashboard cluster-ip.

I noticed that the deployment of kube-dns didn't have a setting like `nodeName:master`. So should kube-dns be deployed on the master node?If it is not necessary,why it didn't work with kube-dns pods on slave node?

**Comment by pires** [comment]
Most probably related to https://github.com/kubernetes/kubeadm/issues/102.
