### ISSUE TITLE
kubeadm alpha phase certs etcd-ca fails without Internet access

### ISSUE THREAD

**Issue by mbert** [kubernetes/kubeadm#960]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

This issue has been moved here from [Kubernetes issue #64920](https://github.com/kubernetes/kubernetes/issues/64920)

**What happened**:

On a system that has no Internet access, run `kubeadm alpha phase certs etcd-ca`
After a while the following error message is displayed:
```
unable to get URL "https://dl.k8s.io/release/stable-1.10.txt": Get https://dl.k8s.io/release/stable-1.10.txt: dial tcp 23.236.58.218:443: getsockopt: connection timed out
```

**What you expected to happen**:

The certificates get created

**How to reproduce it (as minimally and precisely as possible)**:

Run the command on a machine without Internet access. 

**Anything else we need to know?**:

It would probably be a good idea to introduce a global flag for setting a Kubernetes version from the command line, so that the above query can be skipped. Some kubeadm commands already provide this. 

**Environment**:
- kubeadm version 1.10.4-0

/assign @luxas

/sig cluster-lifecycle
/area kubeadm

**Comment by LJosef** [comment]
+1

**Comment by chuckha** [comment]
The workaround for now, as alluded to by @LJosef is to create a configuration file like this

config.yaml
```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
kubernetesVersion: v1.10.4
```
then
```
kubeadm alpha certs etcdca --config config.yaml
```

We are working to implement flag precedence over configuration files. This issue has a very high priority in our v1.12 planning document.

**Comment by mbert** [comment]
Thank you, @chuckha - this works just well and I'm just fine with this workaround. 

May I ask another question here: when pulling up the `etcd` cluster on a fresh system with just `kubeadm`, `kubelet`, `kubectl` installed I cannot run `kubelet`, because the configuration it needs is missing (since 1.11.0 came out: `/var/lib/kubelet/config.yaml`). 

If I want to use my new `etcd` cluster for bootstrapping Kubernetes using `kubeadm` I need some simple and standardised way to have `kubelet` up before running `kubeadm init` (or whatever the next step would be). 

Is there such a way (and I just haven't found it)? Or else, is it in the pipeline?

**Comment by chuckha** [comment]
Followed up in slack;

[the instructions](https://kubernetes.io/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster) have recently been updated to account for this

**Comment by neolit123** [comment]
tracking issue for air-gapped support:
https://github.com/kubernetes/kubeadm/issues/1041

/close
