### ISSUE TITLE
Graduate Bootstrap Tokens to GA

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#964]
bellow are remaining tasks after the [recent discussions](https://github.com/kubernetes/kubernetes/pull/77669#issuecomment-545590770)

we do not know of any remaining feature work for the feature to not be GA at this point.
code cleanup and moving bits around is a separate effort.

---

update kubernetes/kubernetes/cmd/kubeadm to not mention bootstrap tokens as Beta
**EDIT: i cannot find any mentions of that**

----
update kubernetes/website to not mention the tokens as Beta
assigned: @neolit123 
- [x] PR: https://github.com/kubernetes/website/pull/18428

**Comment by neolit123** [comment]
moved to 1.13 according to the release team:
https://github.com/kubernetes/kubernetes/pull/67356#issuecomment-421860750

**Comment by timothysc** [comment]
/assign @fabriziopandini  

for cross coverage on token shuffling config work.

**Comment by neolit123** [comment]
apart from the creation of this repo:
https://github.com/kubernetes/cluster-bootstrap

what are the remaining items for this tickets?

**Comment by fabriziopandini** [comment]
@neolit123 
There are still some bootstrap-token utilities hosted in kubeadm codebase (e.g. under each config version there is `bootstraptokenstring.go`, probably there is also something else around the code).
My understanding is that we want to move those utilities - or at least of some of those utilities - by moving everything not kubeadm specific into https://github.com/kubernetes/cluster-bootstrap

**Comment by neolit123** [comment]
given we cannot move BoostrapTokenString in 1.16 (v1beta3 will come in 1.17), moving to the 1.17 milestone.

**Comment by neolit123** [comment]
/lifecycle frozen
this move is seeing objection here:
https://github.com/kubernetes/kubernetes/pull/77669#pullrequestreview-306041423

**Comment by neolit123** [comment]
updated OP with documentation update items.
also added help-wanted as these cleanups are trivial.

**Comment by neolit123** [comment]
no, we are sending a docs update:
https://github.com/kubernetes/website/pull/18428

**Comment by neolit123** [comment]
https://github.com/kubernetes/website/pull/18428
merged.

closing.
