### ISSUE TITLE
 Developer/Power user documentation on features

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#965]
1.12 Planning doc:
https://docs.google.com/document/d/1YP8sCtgo58yqQ9sR4nsn9iuVFmglCCBMivCTwjd1ERE/edit#

Create Developer/Power user documentation on features.

Lubomir: i don't know the details on this yet, but i'm assuming this should go in the `k/kubeadm` repo and possibly be linked from `k/website`.

**Comment by Bradamant3** [comment]
Point of clarification: I can help with deciding where/how to link from k/website, and getting /website PRs merged. But I have <0 bandwidth to help out with content for this repo.

**Comment by timothysc** [comment]
closing stale.
