### ISSUE TITLE
Improvements to `kubeadm etcd upgrade`

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#966]
1.12 Planning doc
https://docs.google.com/document/d/1YP8sCtgo58yqQ9sR4nsn9iuVFmglCCBMivCTwjd1ERE/edit#

- [ ] Use crictl in `kubeadm upgrade` for a better flow
Assigned: @chuckha 
PR: ?

- [ ] Expose a `kubeadm upgrade etcd` command
Assigned: ?
PR: ?
Website PR: ?

- [ ] Create a `kubeadm upgrade apply --rotate-certificates`
Assigned: @liztio 
PR: ?
Website PR: ?

**Comment by neolit123** [comment]
this has to move for 1.13.
we are too late in the 1.12 cycle.

**Comment by timothysc** [comment]
Focus on etcd upgrade docs

**Comment by timothysc** [comment]
Closing this one due to overlapping other issues, and some of this has been addressed.
