### ISSUE TITLE
Make the kube-proxy ComponentConfig `v1beta1`

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#967]
1.12 planning doc:
https://docs.google.com/document/d/1YP8sCtgo58yqQ9sR4nsn9iuVFmglCCBMivCTwjd1ERE/edit#

- [ ] @timothysc  to sync with mtaufen

- [x]  Propagate hostname-override to kube-proxy
Assigned: ?
PR: ?

**Comment by timothysc** [comment]
@luxas are you going to be able to tackle this in 1.14?

**Comment by luxas** [comment]
@timothysc I hope so, but it depends on SIG Network approvers. After f2f discussions at KubeCon I'm optimistic about this happening in the next cycle though :)

**Comment by timothysc** [comment]
Closing this should no longer apply.
