### ISSUE TITLE
Bazel debs/rpms and package deployment

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#969]
1.12 planning doc:
https://docs.google.com/document/d/1YP8sCtgo58yqQ9sR4nsn9iuVFmglCCBMivCTwjd1ERE/edit#

options to consider:
- Maybe also hosted (in parallel) in a CNCF apt/rpm repos
- Maybe publishing a meta container with local hosted repo?
- Rid ourselves of the packaging problem via a single container that hosts all the bits
- automatic generation of .debs/.rpm for alpha/beta/RC releases

**Comment by timothysc** [comment]
This will likely be blocked until the @kubernetes/k8s-infra-team has a hosting plan.

**Comment by timothysc** [comment]
Closing in preference of https://github.com/kubernetes/kubernetes/issues/71677
