### ISSUE TITLE
Improve `kubeadm reset` for 1.13

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#971]
1.12 planning doc:
https://docs.google.com/document/d/1YP8sCtgo58yqQ9sR4nsn9iuVFmglCCBMivCTwjd1ERE/edit#

we need better context for the set of tasks for this one.

**Comment by rosti** [comment]
There are some `kubeadm reset` related issues:

- [ ] #689 
- [ ] #932

**Comment by timothysc** [comment]
@rosti The general theme is kubeadm reset is not consistent on the cleanup.  

1 - issue WRT iptables rules imo is outside the scope of kubeadm and falls on the proxy.  But that doesn't mean that the proxy shouldn't support a cleanup option that kubeadm can call. 

the other CRI cleanup issues definitely is in our wheelhouse.

**Comment by fabriziopandini** [comment]
Orthogonal to container cleanup we can improve kubeadm reset us by reading the crisocket from the node (instead of forcing the user to the user to re-pass the --criSocket flag)

**Comment by rosti** [comment]
As this is moved to 1.13 we can improve a lot. There is some Linux specific stuff, some hard coded paths, etc. which could not be addressed for 1.12 since they were not bugs (leftovers from reset).

**Comment by timothysc** [comment]
closing due to other issues for tracking and other PRs are already in for 1.13
