### ISSUE TITLE
Support machine readable output

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#972]
1.12 planning doc:
https://docs.google.com/document/d/1YP8sCtgo58yqQ9sR4nsn9iuVFmglCCBMivCTwjd1ERE/edit#

adding this for tracking; it's outside of the GA scope.

token related: #659 (closed using a workaround)
upgrade related: #494

context:
> kubeadm targets high-level automation tools as a first class use case, but it provides only a human readable output

**Comment by jberkus** [comment]
Just to be clear, while #659 was closed, the workarounds are hardly desireable.  Users shouldn't need clever ansible tricks and/or regexes to automate "kubeadm join".  I'm not quite following the proposed solution; does that give a way to call join on remote hosts that's easily scriptable via Ansible, Puppet, etc.?

Happy to test stuff.

**Comment by neolit123** [comment]
i'd agree that those workarounds are not ideal.

in terms of this issue as a whole we had a talk today with the team (meeting had a rather limited staff) and decided to move this outside of 1.12, because we simply don't have the bandwidth to work on it.

if you know someone who is willing to work on this, that would be great!

**Comment by stephaneeybert** [comment]
I'm now using Terraform and trying to build the join command from another server, and it's not easy.

**Comment by timothysc** [comment]
I'm going to close this one and leave the #494 one.
