### ISSUE TITLE
elb created seccessfully not no instances registered to this load balancer (cloud-provider=aws)

### ISSUE THREAD

**Issue by BKS1989** [kubernetes/kubeadm#973]
i have configured cloud provider  as aws using below setting and configure instanceTag
Instance Tag
     kubernetes.io/cluster/kubernetes = shared
    KubernetesCluster=kubernetes
i am getting  this error while creating load balancer
 **node "ip-172-31-3-42.ap-southeast-1.compute.internal" did not have ProviderID set**
elb created seccessfully not no instances registered to this load balancer

**Comment by chuckha** [comment]
I think this is a question for sig-aws: https://github.com/kubernetes/community/tree/master/sig-aws

**Comment by BKS1989** [comment]
I have

**Comment by jiashenC** [comment]
I have the exactly the same issue. No instances are registered to the load balancer. Do you find any workaround?

**Comment by BKS1989** [comment]
i am still waiting for reply from sig/aws

**Comment by timothysc** [comment]
This is not germane to kubeadm, and re-closing.  Please work within that sig on the issues you are having.

**Comment by jiashenC** [comment]
Could you point me to the issue you create for sig/aws? @BKS1989

**Comment by jiashenC** [comment]
@timothysc Would you like to take a look at this issue [stackoverflow](https://stackoverflow.com/questions/51254530/aws-load-balancer-is-not-registered-with-instances). I post under sig but is redirected to stackoverflow. I have this issue for 2 weeks, but still not sure what's wrong on my side.

**Comment by danielsand** [comment]
just as reference - open a bug in SIG-AWS GH
https://github.com/kubernetes/cloud-provider-aws/issues/14

hit the same problem since kubernetes 1.11 =>
