### ISSUE TITLE
cmd/kubeadm/app/preflight/checks.go should not depend on code in test harness

### ISSUE THREAD

**Issue by dims** [kubernetes/kubeadm#976]
checks.go has an import `"k8s.io/kubernetes/test/e2e_node/system"`. please see https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L53

We should not mix the runtime code with test harness, right?

**Comment by neolit123** [comment]
@dims @Random-Liu 
@kad @luxas @kubernetes/sig-cluster-lifecycle-bugs 

> We should not mix the runtime code with test harness, right?

i've noticed the same myself when i looked at the kubeadm preflight checks code for the first time.

we use the package `k8s.io/kubernetes/test/e2e_node/system` for validators like:
```
DockerValidator
OSValidator
CgroupsValidator
...
```
but kubeadm is not the only consumer of these validators, the node e2e tests are too.

so it becomes a question of should these utilities be exposed outside of `kubernetes/test`?

options:
1) move the validators outside of `kubernetes/test`.
2) remove usage of `k8s.io/kubernetes/test/e2e_node/system` in kubeadm and write local validators.

**Comment by chenyb4** [comment]
@neolit123
This issues was finish, but it doesn't auto close?

**Comment by neolit123** [comment]
@chenyb4 you need to type
`Fixes #some-number`

but also it's probably a good idea only to do that once in the PR text and not in the commit, because it causes all the above references on rebase. see how many they are ^.

thanks.
/close
