### ISSUE TITLE
kubeadm config images pull - no way to specify vers

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/kubeadm#978]
## What keywords did you search in kubeadm issues before filing this one?
config images pull
## Is this a FEATURE REQUEST

kubeadm config images pull - no way to specify vers of images to pull
Ideally, there should be a way to provide the kubeadm-master.conf config file, so it will download the images with the k8s defined (note: kubeadm-master.conf is later on used for init/join).

(e.g.  kubernetesVersion: v1.10.5 from kubeadm-master.conf , not the 1.11.0 as it downloads now )

## Versions
1.11.0
**kubeadm version** (use `kubeadm version`):
1.11.0
## What you expected to happen?
fetch the required images versions, not the default version

**Comment by luxas** [comment]
Can't you do this with `kubeadm config images pull --kubernetes-version v1.10.5`?

**Comment by neolit123** [comment]
the above should work for you @ReSearchITEng.
closing this issue. please feel free to re-open if there are related problem.
