### ISSUE TITLE
Enabling DisableSecurityGroupIngress for aws installations

### ISSUE THREAD

**Issue by munai-das** [kubernetes/kubeadm#979]
## Is this a request for help?

Yes.

Hi, how to enable the DisableSecurityGroupIngress feature for kubeadm **aws** installation?

**Code**: https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/cloudprovider/providers/aws/aws.go#L419
**Kops** way of doing it: https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#cloudconfig

**Comment by neolit123** [comment]
this is a AWS specific question and i don't have good answer for you.

the idea is that kubeadm allows you to pass the `--cloud-config` and `--cloud-provider` flags to the apiserver and controller manager and in the cloud config you can specify things like `DisableSecurityGroupIngress`.

more details:
https://kubernetes.io/docs/setup/independent/control-plane-flags/
https://github.com/kubernetes/kubeadm/issues/526
https://github.com/kubernetes/kubeadm/issues/526#issuecomment-342613707
