### ISSUE TITLE
kubeadm commands fail without public ip

### ISSUE THREAD

**Issue by EqbalS** [kubernetes/kubeadm#982]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT 

## Versions

**kubeadm version** (use `kubeadm version`):
`&version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: vitrual machine on a dedicated server ran by Qemu
- **OS** (e.g. from /etc/os-release): `NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`
- **Kernel** (e.g. `uname -a`): `Linux kube1 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

## What happened?
After installing kubernetes components (kubeadm, kubelet, and kubectl) on the machine, before we do anythinng else we ran:
```
$ kubeadm config images pull
unable to select an IP from default routes.
```

It also happened when we ran other `kubeadm config` commands:
```
$ kubeadm config print-default
unable to select an IP from default routes.
```

It happend when we ran `kubeadm init` too:
```
$ kubeadm init
unable to select an IP from default routes.
```

It was fixed when we added  `--apiserver-advertise-address` flag:
```
$ kubeadm init --apiserver-advertise-address 10.0.0.2
I0710 08:05:09.612114    8752 feature_gate.go:230] feature gates: &{map[]}
[init] using Kubernetes version: v1.11.0
...
```

The following is the network configuration:
```
docker0   Link encap:Ethernet  HWaddr 02:42:26:96:77:65  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr 52:54:00:44:f9:7c  
          inet addr:10.0.0.2  Bcast:10.0.255.255  Mask:255.255.0.0
          inet6 addr: fe80::5054:ff:fe44:f97c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:496 (496.0 B)  TX bytes:578 (578.0 B)

eth1      Link encap:Ethernet  HWaddr 52:54:00:b6:2f:49  
          inet addr:169.254.1.2  Bcast:169.254.1.255  Mask:255.255.255.0
          inet6 addr: fe80::5054:ff:feb6:2f49/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:145638 errors:0 dropped:0 overruns:0 frame:0
          TX packets:115836 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:311059772 (311.0 MB)  TX bytes:8299673 (8.2 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:162 errors:0 dropped:0 overruns:0 frame:0
          TX packets:162 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:11940 (11.9 KB)  TX bytes:11940 (11.9 KB)
```

`eth0` is an interface to a private network between a set of virtual machines. and `eth1` is an interface to a private network between this vm and the host running the vm and it provides internet connectivity 
by ip forwarding from the host (host ip is 169.254.1.1 and it works as a gateway).

## What you expected to happen?
It was expected for `kubeadm config` commands to work normally.
but `kubeadm init` needed the `--apiserver-advertise-address` flag and it was expected to fail without the flag.

## How to reproduce it (as minimally and precisely as possible)?
It would probably happen on any machine without a public ip configured.

**Comment by rosti** [comment]
Hi @EqbalS and thanks for filing this issue!

It looks to me, that you don't have a properly configured default route on the machine.
Can you, please, provide the output of the `route` command?

Thanks!

**Comment by EqbalS** [comment]
This is the output of `route`:
```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         169.254.1.1     0.0.0.0         UG    0      0        0 eth1
10.0.0.0        *               255.255.0.0     U     0      0        0 eth0
169.254.1.0     *               255.255.255.0   U     0      0        0 eth1
172.17.0.0      *               255.255.0.0     U     0      0        0 docker0
```

**Comment by timothysc** [comment]
@EqbalS - You don't have external internet access - closing.

**Comment by EqbalS** [comment]
I'm sorry, but I have. As I explained in the issue the gateway 169.254.1.1 is the host that the virtual machine is running on and it provides internet connectivity by ip forwarding to its public interface, so basically this machine has internet access through NAT that I think it's a common case.
And as I also mentioned in the issue when I provide `--apiserver-advertise-address` flag in the `kubeadm init` everything works smoothly and it pulls all necessary docker images.

**Comment by rosti** [comment]
@EqbalS looking through the routing table, the default gateway seems to be a link local IP. Normally this should not be the case if you have a configured interface. Therefore, I think that your default route is misconfigured and the issue should be resolved if you use eth0 for default gateway.

**Comment by lcavajani** [comment]
I'm a bit late for the party but just in case somebody stumble upon this, there can be cases where `169.254.*` is used as the default route. This the case for example with the `routed` nic type in `LXD`:

> It sets up a veth pair between host and instance and then configures the following link-local gateway IPs on the host end which are then set as the default gateways in the instance:
>
> 169.254.0.1 fe80::1

https://linuxcontainers.org/lxd/docs/master/instances#nictype-routed
