### ISSUE TITLE
ECDSA private key

### ISSUE THREAD

**Issue by Unb9rn** [kubernetes/kubeadm#984]
FEATURE REQUEST

I was trying to deploy a new cluster with autogenerated EC CAs when I discovered that kubeadm waits for CA key to be in RSA format.
I thought maybe there is no capabilities to generate EC certificates in kubeadm, so I've generated whole chain: ca, frontproxy-ca, apiserver, apiserver-kubelet-client, front-proxy-client and sa private and public keys.
Now kubeadm stopped on private key to apiserver certificate (while accepting ECDSA certificate itself)

So the feature request: please add support for EC keys if underlying infrastructure is able to support it.

**Comment by neolit123** [comment]
i need to do some investigation for the stakes here, but for now my answer is that EC will not be supported any time soon (don't quote me on that).

**Comment by joejulian** [comment]
To repro:

ca-config.json
```json
{"signing":{"default":{"expiry":"43800h"},"profiles":{"server":{"expiry":"43800h","usages":["signing","key encipherment","server auth","client auth"]},"client":{"expiry":"43800h","usages":["signing","key encipherment","client auth"]},"peer":{"expiry":"43800h","usages":["signing","key encipherment","server auth","client auth"]}}}}
```

ca-csr.json
```json
{"CN":"etcd","key":{"algo":"ecdsa","size":256}}
```

Then use cfssl:

```bash
cfssl gencert -initca -config ca-config.json ca-csr.json | cfssljson -bare ca -
mv ca.pem ca.crt
mv ca-key.pem ca.key
```

Now try to use this CA cert:

```bash
kubeadm alpha phase certs all --cert-dir $PWD
```

```
failure loading ca certificate: the private key file /home/foo/test/ca.key isn't in RSA format
```

**Comment by joejulian** [comment]
@neolit123 What led you to your expectation that this would not be coming soon? Do you see some specific blocker?

**Comment by neolit123** [comment]
@joejulian

> @neolit123 What led you to your expectation that this would not be coming soon? Do you see some specific blocker?

i think the biggest blocker is that this is a relatively low priority task and the kubeadm team is busy.

i did some investigation and it feels like the rest of kubernetes is ECDSA is "ready".
PRs for kubeadm are welcome!

**Comment by geoffgarside** [comment]
Looks like the `certutil.NewSignedCert` functions have been updated to use `crypto.Signer` as of https://github.com/kubernetes/client-go/commit/30575d7a9fdb0e1f9014cf1b6c453f34d2cfe87f

**Comment by rojkov** [comment]
I'd like to tackle this if nobody is working on it.

**Comment by fabriziopandini** [comment]
@rojkov great
/assign @rojkov 
/lifecycle active

**Comment by rojkov** [comment]
The corresponding PR is https://github.com/kubernetes/kubernetes/pull/76390.
