### ISSUE TITLE
kubeadm config upload deprecation

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#987]
`kubeadm config upload` was introduced back in v1.8 to manually upload kubeadm init configuration.
As this is done automatically on init and upgrade ever since v1.8 and given the fact, that the command itself has a bit of an awkward interface, it is probably time to consider its deprecation and eventual removal.

**Comment by neolit123** [comment]
discussed with @fabriziopandini on slack.
/cc @luxas for feedback.

**Comment by neolit123** [comment]
closing in favor of #988.
no need to have both.
