### ISSUE TITLE
kubeadm config upload replacement

### ISSUE THREAD

**Issue by rosti** [kubernetes/kubeadm#988]
info from #987:
> kubeadm config upload was introduced back in v1.8 to manually upload kubeadm init configuration.
As this is done automatically on init and upgrade ever since v1.8 and given the fact, that the command itself has a bit of an awkward interface, it is probably time to consider its deprecation and eventual removal.

As mentioned in #987 , `kubeadm config upload` has awkward interface, which cannot be changed easily since it's in beta.
The problem there is, that there are two sub-commands:
- `from-file` - uploads configuration from kubeadm init config file (InitConfiguration/MasterConfiguration)
- `from-flags` - uses default configuration which is partially overridden by command line flags (the same ones used in `kubeadm init`)

As per #906 we need to provide a command line interface that allows loading the config from a file and then partially overriding it via command line flags. Therefore a new command should be introduced or an old one upgraded to support this.
We can easily upgrade `kubeadm alpha phase upload-config` by adding support for flags and flag override in it.

/area UX
/kind design
/kind documentation
/cc @luxas @timothysc @fabriziopandini

**Comment by luxas** [comment]
What about just deprecating the `from-*` commands and instead supporting the "normal" `kubeadm init` flags as usual (if applicable obviously) in `kubeadm config upload` without any other subcommand?

**Comment by rosti** [comment]
@luxas Keeping the `kubeadm config upload` name is probably the most logical thing to do (unless we think we should rename the `upload` to, say, `push` or something like that.

**Comment by timothysc** [comment]
@rosti  - Are you going to be able to work on this item in 1.14?

**Comment by rosti** [comment]
@timothysc Sorry for the delay, I missed that one, because I was sick back then.

Given the fact, that we have a graduated phase (`kubeadm init phase upload-config`) then I think we can safely deprecate `kubeadm config upload from-*` stuff and hook `kubeadm config upload` as an alias to `kubeadm init phase upload-config`.

WDYT?

**Comment by neolit123** [comment]
+1 on my side given we have the phase now.

**Comment by timothysc** [comment]
We should mark as deprecated and shift towards `kubeadm init phase upload-config`

**Comment by neolit123** [comment]
see
https://github.com/kubernetes/kubeadm/issues/1827#issuecomment-541429602

i think we should remove the `kubeadm config upload/view` commands as they overlap with kubectl.

> We should mark as deprecated and shift towards kubeadm init phase upload-config

the phase does more than uploading the config.

> As per #906 we need to provide a command line interface that allows loading the config from a file and then partially overriding it via command line flags. Therefore a new command should be introduced or an old one upgraded to support this.

ideally we should not support these commands solely for flag overrides.

**Comment by xlgao-zju** [comment]
so, we gonna remove `kubeadm config upload/view`, right?

**Comment by rosti** [comment]
> so, we gonna remove `kubeadm config upload/view`, right?

`kubeadm config upload` is functional, but deprecated. I don't think we have made any concrete plans for the deprecation of `kubeadm config view`.

For ClusterConfiguration, it might be OK to allow users to use the config map directly. The only thing stopping us from doing it ATM is the cluster status that is still present in that config map.

**Comment by neolit123** [comment]
with the fact that admins can call `kubectl get cm -n kube-system kubeadm-config -o yaml`, i'd say the benefits of us maintaining the `view` command are minimal.

**Comment by rosti** [comment]
@neolit123 indeed in its current form it's not very useful. It just does what the kubectl command you have does.
In that essence, we can deprecate and delete it.

It might be useful to have a separate `kubeadm config` command (probably under `print`) that would display the active config in its entirety - that is `ClusterConfiguration` plus component configs. That can be useful to replicate clusters (the output of it can be fed as is to `kubeadm init`). In addition a sanitize command line flag would allow printing of the configuration of a cluster for use in issues. WDYT?

**Comment by neolit123** [comment]
if the command is moved to a new location under print and extend to print component config too, i guess this means we need to concat parts of these ConfigMaps kubeadm-config, kube-proxy and kubelet-config-VER?

**Comment by abdennour** [comment]
i got lost. 
Actually, i cannot see "upload" in subcommands of "kubeadm config -h". It seems like it was removed.
My question now is what's the new working command of this old one : 

```sh
 kubeadm config upload from-file --config ./kubeadm-latest.yaml 
```

**Comment by abdennour** [comment]
i even tried the new way 
```sh
kubeadm init phase upload-config --config=myconfig.yaml
```

but i got :

```console
unknown flag: --config
To see the stack trace of this error execute with --v=5 or higher
```

My reference was: https://v1-20.docs.kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/#cmd-phase-upload-config

accordingly, we have been blocked

**Comment by neolit123** [comment]
try `kubeadm init phase upload-config kubeadm --config ...`

**Comment by abdennour** [comment]
Yep @neolit123  ! it's `--config ...` not `--config=...`

**Comment by danielloczi** [comment]
> with the fact that admins can call `kubectl get cm -n kube-system kubeadm-config -o yaml`, i'd say the benefits of us maintaining the `view` command are minimal.

It took me a while to get exactly the same result as we got previously by executed `kubeadm config view`. So here is to solution, which could be maybe useful for others:
`kubectl describe cm -n kube-system kubeadm-config | awk '/ClusterConfiguration:/{flag=1; next} /---/{next} /^$/{flag=0} flag'`
