### ISSUE TITLE
CoreDNS image not embedded in GetAllImages (list of container images kubeadm expects to use on a control plane node)

### ISSUE THREAD

**Issue by fturib** [kubernetes/kubeadm#989]
## What keywords did you search in kubeadm issues before filing this one?
CoreDNS 
GetAllImages

## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

While browsing the code of kubeadm I found that the function `GetAllImages`
from file `cmd/kubeadm/app/images/images.go`
```
// GetAllImages returns a list of container images kubeadm expects to use on a control plane node
func GetAllImages(cfg *kubeadmapi.InitConfiguration) []string {

```

embed etcd and kube-dns, but not CoreDNS, which is now the default DNS server (when deployed with kubeadm).

I do not know the impact of that miss.
As it seems be ok for usual deployement, I guess that list of container images is used only in specific use cases
- Should it be fixed ?

## Versions

**kubeadm version** (use `kubeadm version`): v1.11 and current master

**Comment by fturib** [comment]
FYI - @rajansandeep and @luxas

**Comment by luxas** [comment]
cc @chuckha and @rosti

**Comment by rajansandeep** [comment]
@fturib 
Seems like CoreDNS is included

```
dnsImage := fmt.Sprintf("%v/k8s-dns-kube-dns-%v:%v", cfg.ImageRepository, runtime.GOARCH, constants.KubeDNSVersion)
	if features.Enabled(cfg.FeatureGates, features.CoreDNS) {
		dnsImage = fmt.Sprintf("%v/coredns:%v", cfg.ImageRepository, constants.CoreDNSVersion)
	}
	imgs = append(imgs, dnsImage)
```

**Comment by fturib** [comment]
Oops !
I just misread the code.
Sorry for wrong alert !

Thanks @rajansandeep for qhick reply.
