### ISSUE TITLE
submit a SIG charter

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubeadm#999]
SIG Cluster Lifecycle has to write and submit a "SIG charter" document to the `k/community` repository.

guide:
https://github.com/kubernetes/community/blob/master/committee-steering/governance/README.md

template in markdown:
https://github.com/wking/community/blob/master/committee-steering/governance/sig-governance-template-short.md

existing charter PRs by other SIGs for reference:
https://github.com/kubernetes/community/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+charter

@kubernetes/sig-cluster-lifecycle-feature-requests 

stages:
- [ ] write charter in gdocs using raw markdown.
link: https://docs.google.com/document/d/1_Cfp61RPxenjVs4o9-mECfn6C1qSLzdihrhoGqZdXuY/edit
- [ ] submit PR for `k/community`.
link: TODO

**Comment by neolit123** [comment]
FYI, my initial edit is done. please, apply your edits.

**Comment by timothysc** [comment]
Closing this issue, submitted to community here - https://github.com/kubernetes/community/pull/2456
